// Language strings: Croatian
// Author: Optimal Programs
// License: MIT License
//---------------------------------------------------------------------------
#include <string.h>
//---------------------------------------------------------------------------
#include "language_string_id.h"
//---------------------------------------------------------------------------
void set_hr(void)
{
	//Croatian
	//automatic translation
	//2025.3.29.0
	strcpy(s_Advanced, "Napredno");
	strcpy(s_Relative_coordinates, "Relativne koordinate");
	strcpy(s_Absolute_coordinates, "Apsolutne koordinate");
	strcpy(s_Append_more_rows, "Dodajte više redaka");

	strcpy(s_Add_to_parts, "Dodaj dijelovima.");
	strcpy(s_Additional, "Dodatni");
	strcpy(s_All_results, "Svi rezultati.");
	strcpy(s_Allow_movement_of_pieces, "Dopustite kretanje komada");
	strcpy(s_Allow_part_in_part, "Dopustite komad po komad");
	strcpy(s_Invalid_piece_Angles_are_too_small_or_too_big_or_height_is_too_small, "Nevažeći komad! Kutovi su premali ili preveliki ili je visina premala.");
	strcpy(s_Append, "Dodati");
	strcpy(s_As_it_is, "Kako je");
	strcpy(s_As_text, "Kao tekst");
	strcpy(s_Ascending, "Uzlazni");
	strcpy(s_Automatic, "Automatski");
	strcpy(s_Cannot_connect_to_the_Internet_Please_visit_our_website_from_a_browser, "Povezivanje s Internetom nije moguće! Posjetite našu web stranicu putem preglednika.");
	strcpy(s_Cannot_copy_or_move_the_files, "Ne možete kopirati ili premjestiti datoteke!");
	strcpy(s_Cannot_delete_the_file, "Nije moguće izbrisati datoteku!");
	strcpy(s_Cannot_modify_old_results, "Nije moguće mijenjati stare rezultate!");
	strcpy(s_To_change_click_inside_a_cell_or_press_0_1_or_2, "Za promjenu kliknite unutar ćelije ili pritisnite 0, 1 ili 2.");
	strcpy(s_Cell, "Ćelija");
	strcpy(s_Click_on_the_table_header_to_change_the_columns, "Kliknite na zaglavlje tablice da promijenite stupce.");
	strcpy(s_Close, "Zatvori to");
	strcpy(s_Contact_us, "Kontaktirajte nas");
	strcpy(s_Column, "Stupac");
	strcpy(s_Comma, "Zarez");

	strcpy(s_Copy, "Kopirati");
	strcpy(s_Copy_for_move, "Kopija za premještanje");
	strcpy(s_Cut_higher_level_strips_first, "Prvo izrežite trake više razine");
	strcpy(s_Cut_index, "Prikaži indeks rezanje");

	strcpy(s_The_data_have_been_changed_Do_you_want_to_save_them_to_a_file, "Podaci su promijenjeni. Želite li ih spremiti u datoteku?");
	strcpy(s_Decimal_separator, "Decimalni razdjelnik");
	strcpy(s_Restore_default_settings, "Vratite zadane postavke");
	strcpy(s_Delete_fiber, "Izbrišite vlakna");
	strcpy(s_Descending, "Silazni");
	strcpy(s_Discard_changes, "Odbaciti promjene");

	strcpy(s_Delete_all_data, "Izbrisati sve podatke?");
	strcpy(s_Dot, "Točka");
	strcpy(s_Do_you_want_to_delete_the_picture, "Želite li izbrisati sliku?");
	strcpy(s_Do_you_want_to_delete_the_product, "Želite li izbrisati proizvod?");
	strcpy(s_Duplicate_and_append, "Duplikat i dodavanje.");
	strcpy(s_Duplicate_values_are_ignored, "Dvostruke vrijednosti su zanemarene!");
	strcpy(s_Error, "Pogreška");
	strcpy(s_Error_loading_file, "Pogreška prilikom učitavanja datoteke.");
	strcpy(s_export_everything, "Izvezi sve");
	strcpy(s_Fit_to_screen, "Prilagodi zaslonu.");
	strcpy(s_Force_fixed_height, "Nacrtajte dijelove s fiksnom visinom.");
	strcpy(s_Flipped, "Okrenuto");
	strcpy(s_Import, "Uvoz");
	strcpy(s_If_angles_are_different_from_90_degrees_height_must_be_greater_than_0, "Ako se kutovi razlikuju od 90 stupnjeva, visina mora biti veća od 0.");
	strcpy(s_Ignore, "Zanemariti");
	strcpy(s_Incorrect_value, "Netočna vrijednost");
	strcpy(s_Info, "Info");
	strcpy(s_Interior, "iznutra");
	strcpy(s_Give_a_name, "Dajte ime.");
	strcpy(s_Group, "Grupirajte ga");
	strcpy(s_Header, "Zaglavlje");
	strcpy(s_Keep_it_as_it_is, "Neka bude kako jest");
	strcpy(s_Level, "Level");
	strcpy(s_Licensee, "Vlasnik licence");
	strcpy(s_List_separator, "Razdjelnik popisa");
	strcpy(s_Made_with_love_in_Cugir_Romania, "Proizvedeno, s ljubavlju, u Cugir, Rumunjska");
	strcpy(s_Made_in, "Proizvedeno u");
	strcpy(s_Manufacturer, "Proizvođač");

	strcpy(s_Manual_arrange, "Ručno složiti");

	strcpy(s_Mixed, "Mješovit");
	strcpy(s_Multiple_shapes_detected_Next_rows_will_be_overwritten_Continue, "Otkriveno je više od jednog oblika. Stoga će naredni redovi biti prebrisani. Nastaviti?");
	strcpy(s_More, "Više");
	strcpy(s_Multiple_values, "Više vrijednosti");
	strcpy(s_No_texture, "Bez teksture");
	strcpy(s_Number, "Broj");
	strcpy(s_Number_of_images, "Broj slika");
	strcpy(s_Number_of_vertices, "Broj vrhova");
	strcpy(s_Offset, "Pomak");
	strcpy(s_Only_the_currently_selected_items, "Samo trenutno odabrane stavke.");
	strcpy(s_Optimizing_please_wait, "Optimiziranje ... pričekajte.");

	strcpy(s_Paste, "Paste");

	strcpy(s_Piece_label, "Prikaži komad naljepnicu");
	strcpy(s_Piece_size, "Pokazuju veličinu komada");
	strcpy(s_Please_contact_us_by_email_if_you_receive_this_error, "Ako primite ovu pogrešku, kontaktirajte nas e-poštom.");
	strcpy(s_Please_save_it_first, "Molimo, prvo ga spremite.");
	strcpy(s_Position, "Položaj");
	strcpy(s_Preview, "Pregled");
	strcpy(s_Rectangle, "Pravokutnik");

	strcpy(s_Redo_the_last_operation, "Vrati posljednju operaciju");
	strcpy(s_Regular_polygon, "Regularni poligon");

	strcpy(s_Reused, "Ponovno korišteno");
	strcpy(s_Rotated, "Rotirano");
	strcpy(s_Save_all, "Spremi sve");
	strcpy(s_Scrap_label, "Prikaži otpada oznaku");
	strcpy(s_Scrap_size, "Pokazuju veličinu otpada");
	strcpy(s_Semicolon, "Točka i zarez");
	strcpy(s_Show_cut_index, "Prikaži indeks rezanje");
	strcpy(s_Show_information, "Pokaži informacije");
	strcpy(s_Show_piece_label, "Prikaži komad naljepnicu");
	strcpy(s_Show_scrap_label, "Prikaži otpada oznaku");
	strcpy(s_Show_scrap_s_size_on_the_small_pieces, "Na malim komadima prikažite veličinu otpada");
	strcpy(s_Show_size_of_pieces, "Pokazuju veličinu komada");
	strcpy(s_Show_size_of_scrap, "Pokazuju veličinu otpada");
	strcpy(s_Show_sizes, "Prikaži veličine");
	strcpy(s_Show_label, "Prikaži oznaku");
	strcpy(s_Show_length, "Prikaži duljinu");

	strcpy(s_Some_numerical_values_are_incorrect_Should_I_fix_all_the_incorrect_values, "Neke su numeričke vrijednosti netočne! Trebam li popraviti sve netočne vrijednosti?");
	strcpy(s_Some_invalid_values_have_been_removed, "Neke nevažeće vrijednosti su uklonjene.");
	strcpy(s_Sort_by, "Poredaj po");
	strcpy(s_Sort_ascending_by, "Poredaj uzlazno prema");
	strcpy(s_Sort_descending_by, "Poredaj silazno prema");
	strcpy(s_Start, "Start");
	strcpy(s_Starting_angle, "Početni kut");


	strcpy(s_Stock, "Inventar");
	strcpy(s_Stop, "Stop");

	strcpy(s_Tabular, "Tablični");
	strcpy(s_Total, "Ukupno");
	strcpy(s_Total_size, "Ukupna veličina");
	strcpy(s_Terms_of_the_license, "Uvjeti licence");
	strcpy(s_The_current_product_has_been_changed_Do_you_want_to_save_it_to_file, "Trenutni proizvod je promijenjen. Želite li ga spremiti u datoteku?");
	strcpy(s_The_value_is_out_of_the_allowed_range, "Vrijednost je izvan dopuštenog raspona.");
	strcpy(s_The_value_must_be_a_real_or_fractional_number_Try_to_replace_the_comma_with_the_dot_if_you_want_to_enter_a_real_number, "Vrijednost mora biti stvarni ili frakcijski broj. Pokušajte zamijeniti zarez sa točkicom ako želite unijeti stvarni broj.");
	strcpy(s_This_feature_is_not_implemented_yet, "Ova značajka još nije implementirana.");
	strcpy(s_This_operation_cannot_be_reversed, "Ovu operaciju nije moguće poništiti.");
	strcpy(s_Undo_the_last_operation, "Otkaži posljednju operaciju.");
	strcpy(s_Utilization, "Iskorištenje");
	strcpy(s_Utilized_Stock, "Korištene zalihe");
	strcpy(s_Version, "Verzija");
	strcpy(s_Visible_columns, "Vidljivi stupci");
	strcpy(s_You_already_have_the_latest_version_installed, "Već imate instaliranu najnoviju verziju!");
	strcpy(s_What_is_exported, "Što se izvozi?");
	strcpy(s0meansanynumberofpieces, "Nula označava bilo koji broj komada");
	strcpy(sAbout, "Oko");
	strcpy(sAccept, "Prihvatiti");
	strcpy(sAcceptall, "Prihvati sve");
	strcpy(sAcceptthecurrentsolution, "Prihvati trenutno rješenje");
	strcpy(sAdd, "Dodati");
	strcpy(sAddapiece, "Dodaj komad");
	strcpy(sAddasimpleproducttoDemand, "Dodaj proizvod na postojećoj potražnji.");
	strcpy(sAddgrindingthicknesstopartsize, "Dodaj brušenje debljinu komada veličine");
	strcpy(sAddproductnametolabel, "Dodavanje naziva proizvoda na naljepnici");
	strcpy(sAddress, "Adresa");
	strcpy(sAddselectedsizetoInventory, "Dodaj odabranu veličinu za popis");
	strcpy(sAdhesivelabels, "Naljepnice");
	strcpy(sAdhesivelabelwithinformationaboutpiecesinDemandCustomernameLabelSizeCurrentData, "Naljepnica s podacima o komadima u potražnji: Kupac naziv, oznaka, veličina, trenutnim podacima.");
	strcpy(sAdhesivelabelwithinformationaboutsheetsinInventory, "Naljepnica s podacima o listova u Registar.");
	strcpy(sAll, "svi");
	strcpy(sAlloffcutswhichhavethesizegreaterthanthisvaluewillbeaddedtoInventory, "Svi Odsječeni ostatci koji imaju veličinu veću od ove vrijednosti će biti dodan u Registar");
	strcpy(sAllowMirroring, "Dopusti zrcaljenje");
	strcpy(sAllowRotation, "Dopustite rotaciju");
	strcpy(sAllPieces, "Svi komada");
	strcpy(sAllpredefinedproducts, "Svi predefinirane proizvodi");
	strcpy(sAnewwindowwillbedisplayedwheretheusercansettheedgebandsforeachedge, "Novi prozor će se prikazati gdje korisnik može postaviti rubne trake za svaki rub");
	strcpy(sAnewwindowwillbedisplayedwheretheusercansetthegrindingvalueforeachedgeofthsheet, "novi prozor će se prikazati u kojem korisnik može postaviti brušenje vrijednost za svaku rubu komadu.");
	strcpy(sAnewwindowwillbedisplayedwheretheusercansetthetrimvalueforeachedgeofthsheet, "Novi prozor će se prikazati gdje korisnik može postaviti nedostatke za svaku rubu komadu.");
	strcpy(sAngle, "Kut");
	strcpy(sAngles, "kutovi");
	strcpy(sAnoptimizationparameterisarealnumber, "Optimiranje parametara je pravi broj.");
	strcpy(sAnoptimizationparameterisfractionalnumber, "Optimiranje parametara je djelomični broj.");
	strcpy(sAnyShape, "Bilo kojeg oblika");
	strcpy(sApolygonmusthaveatleast2vertices, "Poligon mora imati najmanje 2 vrha!");
	strcpy(sApolygonmusthaveatleast3vertices, "Poligon mora imati najmanje 3 vrha!");
	strcpy(sApplication_fails_to_initialize, "Softver se nije pokrenuo.");
	strcpy(sArc, "Arc");
	strcpy(sArcLength, "Duljina luka krivulje");
	strcpy(sAreaofusedsheets, "Površina korištenih listova");
	strcpy(sAshortdescriptionofthesheet, "Kratki opis stanja");
	strcpy(sAtleastonepart, "Barem jedan komad mora biti uveden.");
	strcpy(sAtTheMarginOfTheSheet, "Na rubu lista");
	strcpy(sBandtypes, "Vrste ruba benda.");
	strcpy(sBar, "Barovi / cijevi");
	strcpy(sBars, "Barovi / cijevi");
	strcpy(sBothsizesoftheoffcutsmustbegreaterthanthisvalue, "Obje Veličine Odsječeni ostatci mora biti veća od ove vrijednosti.");
	strcpy(sBottom, "Dno");
	strcpy(sBottomcoordinateofthedefect, "Dno koordinatni o kvaru");
	strcpy(sBreakCut, "Break rez");
	strcpy(sBrowse, "brstiti");
	strcpy(sBuy, "Kupiti");
	strcpy(sBuynow, "Kupi sada ...");
	strcpy(sCancel, "Ga Odustani");
	strcpy(sCannotBeEmpty, "ne može biti prazno!");
	strcpy(sCannotmovepartsbetweensheetswhenidenticalsheetsaregroupedPleaseungroupthesheetsfrommenu, "Ne mogu premjestiti dijelove iz jednog lista u drugi, ako su jednojajčani listovi grupirani Molim otkazati grupiranje listova iz izbornika..");
	strcpy(sCannotSaveFile, "Ne mogu spremiti datoteku");
	strcpy(sCenter, "Centar");

	strcpy(sChangeDirection, "Promijenite smjer");
	strcpy(sChoose, "Izabrati");
	strcpy(sChooseProduct, "Odaberite Proizvod");
	strcpy(sCircle, "Krug");
	strcpy(sCity, "Grad");
	strcpy(sClear, "Vedro");
	strcpy(sClockWise, "Smjeru kazaljke na satu");
	strcpy(sClosewindow, "Zatvori prozor");
	strcpy(sColor, "Boja");
	strcpy(sColorofedgeband, "Boja ruba benda");
	strcpy(sColorPattern, "Boja / Uzorak");
	strcpy(sColorpiecesandwastes, "Komadi i otpad šarene.");
	strcpy(sColumns, "Kolumne");
	strcpy(sComment, "Komentirati");
	strcpy(sCompanyname, "Ime tvrtke");
	strcpy(sComplexMaterialExists, "Naziv materijala već definirano u popisu složenih materijala. Molim Vas, dajte mu novi naziv.");
	strcpy(sComputerCode, "Računalo kod");
	strcpy(sComputerCodefromyourcomputer, "Računalo Šifra (od računala)");
	strcpy(sComputethetotalpriceofDemand, "Izračunajte ukupnu cijenu Demand");
	strcpy(sContents, "Sadržaj");
	strcpy(sContinutComanda, "Sadržaj potražnje u dan");
	strcpy(sContinutDepozit, "Sadržaj inventure u dan");
	strcpy(sConversionIsDoneOnlyWhenSomePiecesHaveFractionalValues, "Obraćenje je učinjeno tek kad neki dijelovi imaju nepotpune vrijednosti.");
	strcpy(sConvertsTheSizeOfWasteToAFractionalUnit, "Prikazuje veličinu otpada kao djelomični vrijednosti.");
	strcpy(sCouldNotSaveFile1, "Ne mogu pisati datoteku u direktorij");
	strcpy(sCouldNotSaveFile2, "Vi ne svibanj imati dovoljno prava. Molimo Vas da provjerite ili promijenite radni imenik iz izbornika Postavke | Radi direktorija u mapu gdje imate prava za pisanje (na primjer C:\\temp).");
	strcpy(sCreationdateYMDHMS, "Datum kreiranja (Y / M / D- H: M: S)");
	strcpy(sCurrentDate, "Trenutni datum");
	strcpy(sCurrentDiagram, "Trenutni dijagram");
	strcpy(sCurrentMaterial, "Trenutni Materija");
	strcpy(sCurrentversion, "Trenutna verzija");
	strcpy(sCurve_not_closed_Try_increasing_DXF_linking_distance_parameter, "Poligon nije zatvoren! Pokušajte povećati parametar DXF poveznica.");
	strcpy(sCustomer, "Kupac");
	strcpy(sCustomerName, "Naziv klijenta");
	strcpy(sCustomMessage, "Prilagođena poruka");
	strcpy(sCutlength, "Duljina reza");
	strcpy(sCut, "Rez");
	strcpy(sCuts, "Rezovi");
	strcpy(sCutterThickness, "Debljina rezanja");
	strcpy(sData, "Podaci");
	strcpy(sDataCannotBeEmpty, "Podaci ne mogu biti prazni!");
	strcpy(sDateymdhms, "Datum (y / d / m / h / m / s)");
	strcpy(sDays_left_for_trial, "Dostupni za testiranje Dani ");
	strcpy(sDaysLeft, "Preostalo dana");
	strcpy(sStandard, "Zadani");
	strcpy(sDefaultInterface, "Zadani sučelje");
	strcpy(sDefects, "Greške");
	strcpy(sDefectsManager, "Upravljanje nedostatke");
	strcpy(sDefectsofthematerialNopiecescanbeplacedinthefaultyzone, "Oštećenja materijala. Nema komadi mogu biti smješteni u kvaru zoni.");
	strcpy(sDelete, "Izbrisati");
	strcpy(sDeletePiece, "Brisanje komad");
	strcpy(sDeleteRow, "Izbriši redak");
	strcpy(sDemandutilization, "Iskorištenost potražnje");
	strcpy(sDepozitulmodificat, "Korištena komada su uklonjene. Ostaci su dodani lageru.");
	strcpy(sDepozitvid, "Dionica je prazna");
	strcpy(sDesk, "pisaći sto");
	strcpy(sDiagram, "Dijagram");
	strcpy(sDiagrams, "Dijagrami");
	strcpy(sDiagramasatable, "Dijagram kao sto");
	strcpy(sDigits, "brojke");
	strcpy(sDimensiuniplaca, "Veličina list");
	strcpy(sDirection, "Vjetra");
	strcpy(sDistanceBetweenRows, "Udaljenost između redaka");
	strcpy(sDonotuseit, "Nemojte ga koristiti");
	strcpy(sDownload, "preuzimanje datoteka");
	strcpy(sDoYouWantToClearTheData, "Želite li izbrisati podatke?");
	strcpy(sDoYouWantToSaveDemand, "Dijelovi su se promijenili! Želite li spremiti promjene?");
	strcpy(sDoYouWantToSaveParts, "Želite li spremiti dijelove?");
	strcpy(sDoYouWantToSaveRepository, "Dioničko je promijenjen! Želite li spremiti promjene?");
	strcpy(sDrawing, "Crteži");
	strcpy(sDrawthesolutioncolorful, "Nacrtajte rješenje šarene");
	strcpy(sDuplicateTypes, "Neke vrste su dvostruki! Molimo uklanjanje duplikata");
	strcpy(sDuplicateTypesWithComplex, "Neka od imena materijala već postoje u popisu složenih tipova! Molim vas da uklonite duplikate");
	strcpy(sDuplicateValues, "Umnožavati vrijednosti");
	strcpy(sEdgeband, "Bendovi za rubove");
	strcpy(sEdgebandingwhichisplacedontheedgesofyourpiecePleasedefineedgebandingtypesfromMaterialsEdgeBandingmenu, "Kantovanje koja se nalazi na rubu svog komada. Molimo definirati Kantovanje vrsta materijala iz izbornika.");
	strcpy(sEdgebandsthatwillbeappliedtoeachpart, "Edge bendova koji će se primjenjivati ​​na svaki dio.");
	strcpy(sEdgeBandTolerance, "Tolerancija za Kantovanje");
	strcpy(sEdgesthatmustbecutduefaults, "Rubovi koji se moraju rezati zbog kvarova.");
	strcpy(sEdgetoedge, "Od ruba do ruba");
	strcpy(sEdit, "Uredi");
	strcpy(sEmail, "E-mail");
	strcpy(sEmptyData, "Podaci su prazna!");
	strcpy(sEnabled, "Omogućeno");
	strcpy(sEnabledisabledefectsoftheinventorysheets, "Omogućite / onemogućite nedostatke u skladištu");
	strcpy(sEnterLabel, "Ulaz oznaka");
	strcpy(sEnterTheMaterialName, "Ulaz naziv materijala");
	strcpy(sEnterTheProductName, "Unesite naziv proizvoda");
	strcpy(sEvaluationError, "Pogreška izrazu ocjenu!");
	strcpy(sExit, "Izlaz");
	strcpy(sExpired, "Softver je istekla! Molimo da se registrirate softver!");
	strcpy(sExport, "Izvoz");
	strcpy(sExportAllDiagrams, "Izvezite sve dijagrame");
	strcpy(sExportAllToASingleFile, "Izvezite sve u jednu datoteku");
	strcpy(sExportOptions, "Mogućnosti izvoza.");
	strcpy(sExporttoDXFformat, "Izvoz u DXF formatu");
	strcpy(sExporttoExcel, "Izvoz u Excel");
	strcpy(sExpresieIncorecta, "Nepravilan matematički izraz!");
	strcpy(sExtensions, "Proširenja");
	strcpy(sExtra, "Extra");
	strcpy(sExtraComponents, "Dodatni Komponente");
	strcpy(sExtracomponentsattachedtoDemand, "Dodatni dijelovi priključeni na dijelove");
	strcpy(sFile, "Datoteka");
	strcpy(sFileName, "Naziv datoteke");
	strcpy(sFillWastes, "Ždrijeb otpad s kosim linijama");
	strcpy(sFindoptimalbarsheetsize, "Nađi optimalne veličine za cijevi i limova.");
	strcpy(sFindoptimalsizeofInventorypieces, "Nađi optimalnu veličinu zaliha komada");
	strcpy(sFirstcutMultiplestages, "Prvo rezanje smjer - Multiple faze");
	strcpy(sFirstdirectionforcutishorizontal, "Prvi smjer za rez je horizontalna.");
	strcpy(sFirstdirectionforcutisvertical, "Prvi smjer za rez je okomit.");
	strcpy(sFollowthecontourofpieces, "Slijedite konture komada");
	strcpy(sFont, "Krstionica");
	strcpy(sFontsize, "Veličina fonta");
	strcpy(sFullInfo, "Cijela informacija");
	strcpy(sDisposedWaste, "Odloženi otpad");
	strcpy(sGeneral, "Genera");
	strcpy(sGenerateCNC, "Generiranje CNC");
	strcpy(sGrain, "Tekstura");
	strcpy(sGraindirection, "Smjer vlakana");
	strcpy(sGraphic, "Grafički");
	strcpy(sGreaterorequalto, "Veće ili jednako");
	strcpy(sGrid, "Stolovi ");
	strcpy(sGrinding, "brušenje debljina");
	strcpy(sGrosimeTaieturaScalata, "Rez debljine od ove slike može se razlikovati od one stvarne, jer su komadi nisu zastupljeni na svoje istinske skali. Ta činjenica ne utječe na rezultate.");
	strcpy(sGroupidenticallayouts, "Grupiranje istih listova");
	strcpy(sGroupIdenticalParts, "Identični dijelovi grupirani.");
	strcpy(sGroupingOfIdenticalPiecesIntoOneRow, "Grupiranje identičnih komada u jednom redu.");
	strcpy(sGroupPartsAfterLoadingFromFile, "Grupiranje dijelova nakon utovara iz datoteke");
	strcpy(sHeight, "Visina");
	strcpy(sHeighttolerance, "Tolerancija za visinu");
	strcpy(sHelp, "Pomoći");
	strcpy(sHistory, "Povijest");
	strcpy(sHorizontal, "Horizontalan");
	strcpy(sHowtodisplayprintedgebands, "Kako to prikazuje rubne trake?");
	strcpy(sIfyousetthebandforoneedgeallwillreceivethesamevalue, "Ako ste postavili bend za jednom rubu, svi će dobiti istu vrijednost.");
	strcpy(sIfyousetthegrindingforoneedgeallwillreceivethesamevalue, "Ako ste postavili vrijednosti za brušenje jednom rubu, svi rubovi će dobiti istu vrijednost.");
	strcpy(sIfyousetthetrimforoneedgeallwillreceivethesamevalue, "Ako ste postavili podrezivanje za jedan rub, svi rubovi će dobiti istu vrijednost.");
	strcpy(sImageBounds, "Granice za slike");
	strcpy(sImageSize, "Veličina slike.");
	strcpy(sImportData, "Uvoz podataka.");
	strcpy(sIncorrectPassword, "Netočna lozinka");
	strcpy(sIndex, "indeks");
	strcpy(sInformationaboutcustomer, "Informacije o kupcu");
	strcpy(sInputALanguageName, "Dajte ime na jeziku");
	strcpy(sInsert, "Umetnite");
	strcpy(sInsertPiece, "Stavite komad");
	strcpy(sInterface, "Sučelje");
	strcpy(sInterfaceSettings, "Sučelje postavke");
	strcpy(sInvalidHardware, "Nisam mogao otkriti hardver. Molimo da nas kontaktirate na contact@optimalprograms.com~~pobj");
	strcpy(sInvalidNumber, "Pogrešan broj");
	strcpy(sInvalidOrderOfComputation, "Nalog za računanje duljine ne može utvrditi. Postoji kružni odnos u definiciju proizvoda!");
	strcpy(sInvalidRegistration, "Registracija je nevažeća!");
	strcpy(sInvalidTime, "Vrijeme vašeg sustava je nevažeći.");
	strcpy(sInventory, "Inventar");
	strcpy(sisafractionalvalue, "je djelomični vrijednost.");
	strcpy(sIsArc, "Je arc");
	strcpy(sisarealvalue, "je stvarna vrijednost.");
	strcpy(sLabel, "Oznaka");
	strcpy(sLabels, "Oznake");
	strcpy(sLanguage, "Jezik");
	strcpy(sLatimeanumar0, "Širina mora biti veći od 0!");
	strcpy(sLatimeanumarreal, "Širina mora biti pravi broj!");
	strcpy(sLayerName, "Naziv sloja");
	strcpy(sLeft, "Lijevo");
	strcpy(sLeftcoordinateofthedefect, "Lijevi koordinatni o kvaru");
	strcpy(sLength, "Dužina");
	strcpy(sLengthofthepiecestocut, "Piece veličina za rezanje");
	strcpy(sLengthofthepiecestocutfrom, "Veličina ploče za rezanje");
	strcpy(sLengthofusedbars, "Veličina korištenih rešetaka");
	strcpy(sLicenseAgreement, "Dozvola sporazum");
	strcpy(sLinear, "Linearni");
	strcpy(sLinethickness, "Debljina olovke");
	strcpy(sLoadafileandappenddatatothecurrentDemand, "Učitaj datoteku i dodati podatke o trenutnoj potražnji.");
	strcpy(sLoadanexistingDemandfromafile, "Učitaj postojeću potražnju iz datoteke.");
	strcpy(sLoadAppend, "Load i dodavanje");
	strcpy(sLoadEverything, "Učitaj sve");
	strcpy(sLoadInventory, "Stavite dionica");
	strcpy(sLoadInventoryandDemand, "Stavite zaliha i potražnje");
	strcpy(sLoadResults, "Učitaj rezultate");
	strcpy(sLocked, "zaključan");
	strcpy(sLogo, "logo");
	strcpy(sLong, "Long");
	strcpy(sLongerexecutiontime, "Dulje vrijeme izvršenja");
	strcpy(sLungime, "Širina");
	strcpy(sLungimeanumar0, "Duljina mora biti veći od 0!");
	strcpy(sLungimeanumarreal, "Duljina mora biti pravi broj!");
	strcpy(sLungimeaTotalaFolosita, "Ukupna dužina koristi");
	strcpy(sMagnification, "Povećanje");
	strcpy(sMagnify, "Veličati");
	strcpy(sMargins, "Margine");
	strcpy(sMarginsForPaper, "Margine za papir");
	strcpy(sMarginsOfTheLabel, "Razlike u oznaci");
	strcpy(sMaterial, "Materija");
	strcpy(sMaterialName, "Naziv materijala");
	strcpy(sMaterials, "materijali");
	strcpy(sMaterialstypes, "Materijali vrste");
	strcpy(sMax, "Maks");
	strcpy(sMaximalArea, "Maksimalna površina");
	strcpy(sMaximalCutLength, "Maksimalna duljina reza");
	strcpy(sMaxlength, "Maksimalna duljina");
	strcpy(sMaxPiecesperBar, "Max komada Baru");
	strcpy(sMaxwidth, "Maksimalna širina.");
	strcpy(sMeasurementUnit, "Mjerenje jedinica");
	strcpy(sMin, "Min");
	strcpy(sMinimalBreakSize, "Minimalna veličina rupture");
	strcpy(sMinimalUsefulSize, "Minimalna korisna površina");
	strcpy(sMinimalwastesizetoInventory, "Minimalna veličina za otpad Registar");
	strcpy(s_What_to_minimize, "Što minimizirati?");
	strcpy(sMinlength, "Minimalna duljina");
	strcpy(sMinwidth, "Minimalna širina");
	strcpy(sMirror, "Ogledalo");
	strcpy(sMirroring, "Zrcaljenje");
	strcpy(sMiscellaneous, "Razni");
	strcpy(sModify, "Izmijeniti");
	strcpy(sModifytheselectedpiece, "Izmjena odabranog komad");
	strcpy(sMovePiece, "Premjestiti komad.");
	strcpy(sMultiplestages, "Višestruki faze");
	strcpy(sName, "Ime");
	strcpy(sNameofedgeband, "Ime rubnih bendova");
	strcpy(sNewDEMANDUnsaveddatawillbelost, "Novi dijelovi? Nespremljeni podaci će biti izgubljeni!");
	strcpy(sNewLanguage, "Novi jezik");
	strcpy(sNewMaterial, "Novi materija");
	strcpy(sNewPasswordincorectlyintroduced, "Nova lozinka pogrešno uveden!");
	strcpy(sNewProduct, "Novi proizvod");
	strcpy(sNewversion, "Nova verzija");
	strcpy(sNo, "Ne");
	strcpy(sNumarBucati, "Broj komada");
	strcpy(sNumberOfCopies, "Broj primjeraka");
	strcpy(sNumberofstages, "Broj stupnjeva");
	strcpy(sNusuficienteplacidepozit, "Nisu svi dijelovi su optimizirane. Mogući uzroci: Nema dovoljno komada u skladištu; Piece nisu iskorišteni u optimizaciji; Materijali od potražnje i inventara ne podudaraju; Ostali parametri su pogrešno postavljen.");
	strcpy(sOfficeNotInstaled, "Microsoft Office nije instaliran na vaše računalo ili netočnih verzija je instalirana!");
	strcpy(sOldpassworddoesnotmatch, "Stara zaporka ne podudaraju!");
	strcpy(sOnlinehelp, "Online pomoć");
	strcpy(sOnlypiecesofthesameheightinthelaststage, "Komadi istoj visini u posljednjoj fazi.");
	strcpy(sOpen, "Otvoreno");
	strcpy(sOptimization, "Optimizacija");
	strcpy(sOptimizationDone, "Optimizacija izvodi! Možete ispisati ili spremiti dobivenih dijagrama. Pritisnite gumb Prihvati li ste zadovoljni s trenutnom rješenje. Inače pritisnite Start opet.");
	strcpy(sOptimizationType, "Vrsta optimizacije");
	strcpy(sOptions, "Opcije");
	strcpy(sOptionsrelatedtotheinterface, "Opcije vezane na sučelje");
	strcpy(sor, "ili");
	strcpy(sOthercomponents, "Ostale komponente");
	strcpy(sOthers, "Drugi");
	strcpy(sOtherstatistics, "Ostale statistike");
	strcpy(sOverrideExcelCSVfiles, "Override Excel / CSV datoteke");
	strcpy(sParameter, "Parametar");
	strcpy(sParts, "DIJELOVI");
	strcpy(sPattern, "Uzorak");
	strcpy(sPatternforwaste, "Uzorak za otpad");
	strcpy(sPerimeter, "Perimetar");
	strcpy(sPermitedRotationAngle, "Kut okretanja da je dopušteno.");
	strcpy(sPhone, "Telefon");
	strcpy(sPicture, "Slika");
	strcpy(sPiece, "Komad");
	strcpy(sPieceindex, "Komad indeks");
	strcpy(sPieces, "Komadi");
	strcpy(sPiecesize, "Komad je veličina");
	strcpy(sPiecesizelabeledgebandwillbeprinted, "Komad veličina, oznaka, rub bendovi će se tiskati.");
	strcpy(sPierdere, "Gubljenje");
	strcpy(sPixels, "piksela");
	strcpy(sPlacilefolositeDepozit, "Korištena komada iz inventure.");
	strcpy(sPlease_contact_us_at_contact_nestingtechnologies_com, "Molimo kontaktirajte nas na contact@nesting-technologies.com");
	strcpy(sPlease_contact_us_at_contact_optimalprograms_com, "Molimo kontaktirajte nas na contact@optimalprograms.com");
	strcpy(sPleaseenteralldataeitherasfractionalorrealDonotmixthem, "Molimo unesite sve podatke, bilo kao udjelnih ili pravi Nemojte ih miješati!");
	strcpy(sPleaseEnterSomeTypesOfMaterials, "Nema vrsta materijala definiran. Možete ih definirati iz materijala izbornika.");
	strcpy(sPleasesendtheNameandtheCodetotheaddresscontactoptimalprogramscominordertoobtaintheRegistrationKey, "Da bi se dobio registracijski ključ molimo poslati ime i kod za: contact@optimalprograms.com~~HEAD=dobj.");
	strcpy(sPolygon, "Poligona");
	strcpy(sPolygonsCircles, "Poligoni, krugovi");
	strcpy(sPrecision, "Preciznost");
	strcpy(sPretulnumar0, "Cijena mora biti veći od 0!");
	strcpy(sPretulnumarreal, "Cijena mora biti pravi broj!");
	strcpy(sPreview, "Pregled");
	strcpy(sPrice, "Cijena");
	strcpy(sPriceMustBeGreaterThanZero, "Cijena mora biti veća od nule");
	strcpy(sPriceofbars, "Cijena rešetaka");
	strcpy(sPriceperbar, "Cijena po traci");
	strcpy(sPricepersheet, "Cijena po listu");
	strcpy(sPricepersquareunitofmaterial, "Cijena po jedinici površine materijala.");
	strcpy(sPriceperunit, "Cijena po jedinici");
	strcpy(sPrint, "Tiskati");
	strcpy(sPrintdiagramsastables, "Ispis dijagrama u obliku tablice.");
	strcpy(sPrinter, "Printer");
	strcpy(sPrinterBounds, "Margine za pisač");
	strcpy(sPrinting, "tiskanje");
	strcpy(sPrintonlyutilizedarea, "Ispis samo iskoristiti prostor");
	strcpy(sPrintthecontentsoftheDemand, "Ispis sadržaja zahtjev.");
	strcpy(sPrintthecontentsoftheInventory, "Ispis sadržaja dionica.");
	strcpy(sPrintthecurrentsolution, "Ispis trenutne rješenje.");
	strcpy(sPriority, "Prioritet");
	strcpy(sPrioritytocutapieceZero0isthehighestpriority, "Prioritet izrezati komad. Nula (0) je najviši prioritet.");
	strcpy(sProcentul0100, "U postotaka mora biti veći od 0 i manji ili jednak 100!");
	strcpy(sProcentulnumarreal, "U postotaka mora biti pravi broj!");
	strcpy(sProductdefinition, "Definicija proizvoda");
	strcpy(sProductExists, "Proizvod već postoji. Odaberite drugo ime.");
	strcpy(sProductName, "Naziv proizvoda");
	strcpy(sProducts, "Proizvod");
	strcpy(sProducts, "Proizvodi");
	strcpy(sProject, "Projekt");
	strcpy(sProperties, "Nekretnine");
	strcpy(sProperty, "svojstvo");
	strcpy(sQuantity, "Količina");
	strcpy(sQuantitynumberofsheetsofthistype, "Broj listova ove vrste");
	strcpy(sRadius, "Radijus");
	strcpy(sRectangular, "Pravokutni");
	strcpy(sRedefinetypesofedgeband, "Redefinirati vrsta ruba benda");
	strcpy(sRedefinetypesofmaterial, "Redefiniranje vrsta materijala");
	strcpy(sRegistration, "Registracija");
	strcpy(sRegistrationKeyfromOptimalPrograms, "Registracija Ključ");
	strcpy(sRegistrationSuccessful, "Registracija uspješna!");
	strcpy(sRemoveallpiecesinInventory, "Uklonite sve dijelove u Registar.");
	strcpy(sRemoveCut, "Brisanje cut");
	strcpy(sRemovetheselectedpiece, "Uklonite odabrani komad");
	strcpy(sReports, "Izvješća");
	strcpy(sRequestedMaterial, "Traženi materija");
	strcpy(sRestore, "Vratiti");
	strcpy(sResults, "Rezultati");
	strcpy(sReusedwaste, "Ponovno upotrijebiti otpad");
	strcpy(sRight, "Desno");
	strcpy(sRightcoordinateofthedefect, "Koordinate grešaka iz desni");
	strcpy(sRotation, "Rotacija");
	strcpy(sRotationAngle, "Rotacija kut");
	strcpy(sRotationStep, "Rotacija korak");
	strcpy(sRoundAllFractionsTo, "U djelomični vrijednosti moraju biti zaokružena na");
	strcpy(sRow, "red");
	strcpy(sRows, "Redovi");
	strcpy(sRun, "Najnoviji rješenja");
	strcpy(sRunningtime, "trčanje vrijeme");
	strcpy(sSameforall, "Sve za sve");
	strcpy(sSave, "Spasiti");
	strcpy(sSaveAllImages, "Spremi sve slike");
	strcpy(sSaveAs, "Spremi kao");
	strcpy(sSaveChanges, "Potražnja je promijenjen. Želite li spasiti?");
	strcpy(sSaveCurrentImage, "Spremi trenutnu sliku");
	strcpy(sSavedataparameters, "Spremi podatke i parametre");
	strcpy(sSaveEverything, "Spremi sve");
	strcpy(sSaveInventory, "Spremi inventar");
	strcpy(sSaveInventoryandDemand, "Spremi inventar i potražnja");
	strcpy(sSaveResults, "Spremi rezultate");
	strcpy(sSaveStatisticsinafile, "Spremi statistiku u datoteci");
	strcpy(sSavethecurrentimage, "Spremi trenutnu sliku");
	strcpy(sSavethecurrentimageorstatistic, "Spremi trenutnu sliku ili statistika");
	strcpy(sSavetheDEMANDinafile, "Spremi u datoteku");
	strcpy(sSavetheDemandinafilewithadifferentname, "Spremite potražnje u datoteci s drugim imenom.");
	strcpy(sSavetheREPOSITORYinafile, "Spremi repozitorij u datoteku");
	strcpy(sSerialNumber, "Registracija ključ");
	strcpy(sService, "usluga");
	strcpy(sSetDefaultValues, "To će vratiti sve parametre na njihove zadane vrijednosti. Sve postavke će biti izgubljen. Jeste li sigurni da to želite učiniti?");
	strcpy(sSetedgeband, "Postavite rub bend");
	strcpy(sSetedgetrim, "Postavite rezanje za nedostatke rubovima");
	strcpy(sSetthesameedgebandforalledges, "Postavite isti rub bend za sve rubove");
	strcpy(sSetthesamegrindingforalledges, "Postavite isti brušenje svih rubova.");
	strcpy(sSetthesametrimforalledges, "Postavite istu rezanje za nedostataka za sve rubove");
	strcpy(sSettings, "Postavke");
	strcpy(sShape, "Oblik");
	strcpy(sSheet, "List");
	strcpy(sSheetsBarstypes, "Listovi_cijevi vrste");
	strcpy(sSheetSize, "Veličina list");
	strcpy(sSheetsperPage, "Listovi po stranici");
	strcpy(sShort, "Kratki");
	strcpy(sShorterexecutiontime, "Kratko vrijeme rada");
	strcpy(sShowallsimpleproducts, "Prikaži sve jednostavne proizvode");
	strcpy(sShowcustomername, "Prikaži kupca ime");
	strcpy(sShowCustomTextOnEachPiece, "Prikaži prilagođeni tekst na svakom komadu");
	strcpy(sShowdiagramasatable, "Prikaži dijagram kao tablicu.");
	strcpy(sShowedgeband, "Pokaži rub bendova");
	strcpy(sShowedgebandssettinginanewwindow, "Prikaži postavke rubnih bendova u novom prozoru.");
	strcpy(sShowgrindingsettingsinanewwindow, "Prikazuje brušenje postavke u novom prozoru.");
	strcpy(sShowHorizontalLabelsAlways, "Pokaži uvijek horizontalne etikete");
	strcpy(sShowRemovethesizeofthepiecesinthecurrentsolution, "Prikaži / ukloni veličinu komada u tekućem rješenje.");
	strcpy(sShowRemovethesizeofthewastesinthecurrentsolution, "Prikaži / Uklonite veličinu otpada u tekućem rješenje.");
	strcpy(sShowtotalcutlength, "Prikaži ukupne dužine rezanja");
	strcpy(sShowtrimedgesettingsinanewwindow, "Prikaži postavke nedostataka u novom prozoru.");
	strcpy(sSimpleMaterialExists, "Naziv materijala već definirano u popisu materijala. Molim Vas, dajte mu novi naziv.");
	strcpy(sSinglePieceStrips, "Stripes iz jednog komada.");
	strcpy(sSizes, "Veličine");
	strcpy(sSmallerorequalto, "Manji ili jednak");
	strcpy(sSort, "Vrsta");
	strcpy(sSortAscendingByArea, "Sortiraj uzlazno po području");
	strcpy(sSortDescendingByArea, "Sortiraj silazno po području");
	strcpy(sSpecifyhowdifferentthepiecesinthelaststagecanbeValue0meansnodifference, "Odredite kako drugačije može biti komada u posljednjem stadiju. Vrijednost 0 znači da nema razlike.,");
	strcpy(sSpecifyifpiecesinthelaststagecanbedifferentornotdepeultimaetapapotfidiferitesaunucadimensiune, "Navedite ako komada u posljednjem stadiju može biti drugačiji ili ne");
	strcpy(sSpecifyifthepiececanberotatedornotIfnotitwillbecutinthesamewayasitwasintroducedinDemandLengthofthepieceparalleltothelengthofthesheet, "Navedite ako komad se može okretati ili ne. Ako ne, to će se smanjiti na isti način kao što je uveden u Demand (duljina komada paralelno s dužinom list),");
	strcpy(sSpecifyinhowmanystageswemakethecutsDuringastageallcutshavethesamedirection, "Navedite u koliko faze smo napraviti rez.");
	strcpy(sStartthesearchprocess, "Pokrenite postupak za pretraživanje");
	strcpy(sStatistics, "Statistika");
	strcpy(sStatisticsE, "Izvješća Dodatni");
	strcpy(sStatisticsforeachtypeofmaterial, "Statistika za svaku vrstu materijala");
	strcpy(sStep, "Korak");
	strcpy(sStergeDepozit, "Želite li izbrisati inventar?");
	strcpy(sStergeMaterial, "Brisanje materijala?");
	strcpy(sStergePiesele, "Želite li izbrisati komad?");
	strcpy(sStergePiesa, "Želite li izbrisati komad?");
	strcpy(sStopthesearchprocess, "Zaustavi proces pretraživanje");
	strcpy(sStrongoptimization, "Jaka optimizacija");
	strcpy(sSubtractthebandthicknessfrompiecesize, "Smanjenje komad veličine s bendova debljine");
	strcpy(sSummary, "rezime");
	strcpy(sSuprafataTotalaFolosita, "Ukupna površina koristi");
	strcpy(sSuprafatautilizata, "Upotreba");
	strcpy(sSwitchbetweenfiberandrotationoption, "Prebacivanje između vlakana i opciju rotacije.");
	strcpy(sTechnical, "Tehnički");
	strcpy(sTechnicalsettings, "Tehnički postavke");
	strcpy(sTemporaryPanelHint, "Privremeni ploča za pokretne dijelove između listova.");
	strcpy(sText, "Tekst");
	strcpy(sThe_application_has_expired, "Program je istekao.");
	strcpy(sThe_application_is_not_registered, "Softver nije registriran.");
	strcpy(sThe_application_was_first_started_on, "Softver je prvi put započeo je.");
	strcpy(sThecutsareperformedfromasidetotheothersideofthematerial, "Terećenja izvode iz strane na drugu stranu materijala.");
	strcpy(sThecuttingmachinecanfollowtheshapeofthematerial, "Stroj za rezanje može slijediti oblik komadu.");
	strcpy(sTheedgesofsheetsthatmustbetrimedduefaults, "Rubovi listova koji mora biti obrubljen zbog kvarova");
	strcpy(sTheLargestSize, "Najveća veličina.");
	strcpy(sThenameofthecustomerforwhichyoucutthepiece, "Ime kupca za koje ste izrezali komad.");
	strcpy(sThenameofyourcustomer, "Ime svog klijenta");
	strcpy(sThepiececanberotated, "Komad može se rotirati");
	strcpy(sTheprogramtriestoavoidwasteswhichhavebothsizeslessthanthisvalue, "Program pokušava izbjeći otpad koji imaju obje veličine manje od ove vrijednosti");
	strcpy(sThereAreNoProducts, "Nema definiranih proizvodi još");
	strcpy(sThestockofmaterialhasbeenpreviouslyloadedfromanExcelorCSVformatPleaseloaditagain, "Zaliha materijala je prethodno učitati iz Excel ili CSV formatu. Molimo ponovno ga stavite, ako želite raditi na njemu.");
	strcpy(sThetotallengthofcutting, "Ukupna dužina rezanja");
	strcpy(sThewidthofthecuttingsawForglasscuttingoptimizationitcanbe0Forwooditshouldbegreaterthan0, "Debljina pile. Za rezanje stakla može biti 0. Za drva to bi trebao biti veći od 0..");
	strcpy(sThewidthofthecuttingsawforlinearpieces, "Debljina pile za linearne komada.");
	strcpy(sThickness, "Debljina");
	strcpy(sThischaracterisusedforfillingthewasterectanglesIfyoudonotwantfilledwastejustremovethischaracter, "Ovaj simbol se koristi za punjenje otpada pravokutnike. Ako ne želite da se napuni otpada samo ga ukloniti.");
	strcpy(sThisindexhasvaluebetween1andthenumberofpieces, "Ovaj indeks ima vrijednost između 1 i broj komada.");
	strcpy(sThisOptionWillOverrideTheInventoryFileIfLoadedFromExcelOrCsvFiles, "Ova opcija će nadjačati datoteku zaliha ako učitati iz Excel ili CSV datoteke.");
	strcpy(sThisProgramisLicensedTo, "Ovaj program je licenciran");
	strcpy(sThisvaluewillbeaddedtotheedgebandingmaterialoneachside, "Ova vrijednost će biti dodan u Kantovanje materijala na svakoj strani");
	strcpy(sTipNevid, "Vrsta materijala ne može biti prazan.");
	strcpy(sTitle, "Naslov");
	strcpy(sTools, "alat");
	strcpy(sTop, "Vrh");
	strcpy(sTopcoordinateofthedefect, "Vrh koordinatni o kvaru.");
	strcpy(sTotalGarbageWaste, "Sve odbacuju otpad");
	strcpy(sTotalInventoryWaste, "Ukupno dionica otpad");
	strcpy(sTotalRecycledWaste, "Sve reciklirani otpad");
	strcpy(sTotalusedarea, "Ukupna površina koristi");
	strcpy(sTotalusedlength, "Ukupna dužina koristi");
	strcpy(sTrigonometric, "Trigonometrijski");
	strcpy(sTrim, "Podrezati");
	strcpy(sTrimalledgesatthebeginning, "Izrezivanje sve rubove na početku");
	strcpy(sTrimEdge, "Trim rub");
	strcpy(sTwoPanels, "2 ploče");
	strcpy(sType, "vrsta");
	strcpy(sTypeofmaterialfromwhichtocut, "Vrsta materijala od kojih se smanjiti");
	strcpy(sTypesAreNotMatched, "Optimizacija nije izvedena! Komadi će se smanjiti od listova iz inventure imaju istu vrstu materijala. Trenutno, u skladištu, ne postoji takav materijal! Promjena neke materijale iz odgovarajućeg stupca!");
	strcpy(sUndo, "Otkopčati");
	strcpy(sUndoAccept, "Poništi Prihvati");
	strcpy(sUnits, "jedinice");
	strcpy(sUnregisteredVersion, "Neregistrovan");
	strcpy(sUpdates, "Nadopune");
	strcpy(sUsefulforwoodfurniture, "Korisno za drva namještaj");
	strcpy(sUseit, "Koristite ga");
	strcpy(sUsePieceinOptimization, "Koristite komad u optimizaciji");
	strcpy(sUserName, "Korisničko ime");
	strcpy(sUtilizationandWastes, "Iskorištenost i Otpad");
	strcpy(sUtilizedArea, "Površina korištenih dijelova");
	strcpy(sUtilizedBars, "Iskorišteni barovi");
	strcpy(sUtilizeddemandcount, "Broj iskorištenih komada.");
	strcpy(sUtilizedParts, "Iskorišteni dijelovi");
	strcpy(sUtilizedPieces, "Iskorišteni komada");
	strcpy(sUtilizedSheets, "Iskorišteni listova");
	strcpy(sValue, "Vrijednost");
	strcpy(sValueGreaterEqualToZero, "Vrijednost mora biti veća ili jednaka nuli");
	strcpy(sValueGreaterThanZero, "Vrijednost mora biti veća od nule");
	strcpy(sValueIntegerNumber, "Vrijednost mora biti cijeli broj!");
	strcpy(sValueRealNumber, "Vrijednost mora biti pravi broj. Možda ste koristili, umjesto. ili obrnuto. Ispravite ga!");
	strcpy(s_The_number_is_too_big_or_it_has_too_many_digits_after_decimal_separator, "Broj je prevelik ili ima previše decimalnih znakova nakon razdvajanja!");
	strcpy(s_The_number_is_too_big, "Broj je prevelik!");
	strcpy(sVertical, "Vertikala");
	strcpy(sWaste, "Gubljenje");
	strcpy(sWastes, "Gubljenje");
	strcpy(sWasteAddedToWarehouse, "Otpad dodaje skladištu");
	strcpy(sWastelimits, "Rokovi za otpad");
	strcpy(sWasteType, "Vrsta otpada");
	strcpy(sWeakoptimization, "Najslabija optimizacija");
	strcpy(sWhattoprint, "Što bih trebao ispisati");
	strcpy(s_What_to_print_or_save_to_file, "Što ispisati ili spremiti u datoteku");
	strcpy(sWhattoprintoneachpiece, "Što ispisati na svaki komad");
	strcpy(sWhattoshowoneachpiece, "Što pokazati na svaki komad?");
	strcpy(sWidth, "Širina");
	strcpy(sWood, "drvo");
	strcpy(sWorkingDirectory, "Rad imenik");
	strcpy(sWrongKey, "Pogrešno Registracija Ključ!");
	strcpy(sYes, "Da");
	strcpy(sYoucannotchooseblackblueorredcolors, "You cannot choose black, blue or red colors.");
	strcpy(sYouCannotMixFractionalDataWithDecimalOnes, "Vi ne možete miješati decimalnih vrijednosti sa stvarnim vrijednostima!");
	strcpy(sYourcompany, "Vaša tvrtka");
	strcpy(sZip, "Poštanski broj");
	strcpy(s_Set_the_origin_and_the_direction_of_the_axes, "Postavite ishodište i smjer koordinatnih osi.");

}
