// Language strings: Swedish
// Author: Optimal Programs
// License: MIT License
//---------------------------------------------------------------------------
#include <string.h>
//---------------------------------------------------------------------------
#include "language_string_id.h"
//---------------------------------------------------------------------------
void set_sv(void)
{
	// Swedish
	// did not check manually
	// last update on: 2025.11.01.0
	
	strcpy(s_Area, "Area");
	strcpy(s_Mass, "Massa");
	strcpy(s_Advanced, "Avancerad");
	strcpy(s_Relative_coordinates, "Relativa koordinater");
	strcpy(s_Absolute_coordinates, "Absoluta koordinater");
	strcpy(s_Append_more_rows, "Lägg till fler rader");

	strcpy(s_Add_to_parts, "Lägg till delar.");
	strcpy(s_Additional, "Ytterligare");
	strcpy(s_All_results, "Alla resultat.");
	strcpy(s_Allow_movement_of_pieces, "Tillåt rörelse av bitar");
	strcpy(s_Allow_part_in_part, "Permitir pieza en pieza");
	strcpy(s_Invalid_piece_Angles_are_too_small_or_too_big_or_height_is_too_small, "Ogiltig pjäs! Vinklarna är för små eller för stora, eller höjden är för liten.");
	strcpy(s_Append, "Bifoga");
	strcpy(s_As_it_is, "Som det är");
	strcpy(s_As_text, "Som text");
	strcpy(s_Ascending, "Stigande");
	strcpy(s_Automatic, "Automatisk");
	strcpy(s_Cannot_connect_to_the_Internet_Please_visit_our_website_from_a_browser, "Det går inte att ansluta till Internet! Besök vår webbplats från en webbläsare.");
	strcpy(s_Cannot_copy_or_move_the_files, "Det går inte att kopiera eller flytta filerna!");
	strcpy(s_Cannot_delete_the_file, "Det går inte att radera filen!");
	strcpy(s_Cannot_modify_old_results, "Det går inte att ändra gamla resultat!");
	strcpy(s_To_change_click_inside_a_cell_or_press_0_1_or_2, "För att ändra, klicka inuti en cell eller tryck på 0, 1 eller 2.");
	strcpy(s_Cell, "Cell");
	strcpy(s_Click_on_the_table_header_to_change_the_columns, "Klicka på tabellrubriken för att ändra kolumnerna.");
	strcpy(s_Close, "Stäng det");
	strcpy(s_Contact_us, "Kontakta oss");
	strcpy(s_Column, "Kolumn");
	strcpy(s_Comma, "Kommatecken");
	strcpy(s_The_comma_symbol_cannot_simultaneously_be_the_list_separator_and_the_decimal_separator, "Kommatecknet kan inte samtidigt vara listavgränsare och decimalavgränsare!");
	strcpy(s_Copy, "Kopiera");
	strcpy(s_Copy_for_move, "Kopiera för flytt");
	strcpy(s_Cut_higher_level_strips_first, "Klipp först remsor på högre nivå");
	strcpy(s_Cut_index, "Index skära");

	strcpy(s_The_data_have_been_changed_Do_you_want_to_save_them_to_a_file, "Uppgifterna har ändrats. Vill du spara dem i en fil?");
	strcpy(s_Decimal_separator, "Decimalavgränsare");
	strcpy(s_Restore_default_settings, "Återställ standardinställningar");
	strcpy(s_Delete_fiber, "Ta bort fiber");
	strcpy(s_Descending, "Nedåtgående");
	strcpy(s_Discard_changes, "Ignorera ändringar");

	strcpy(s_Delete_all_data, "Radera all data?");
	strcpy(s_Dot, "Punkt");
	strcpy(s_Do_you_want_to_delete_the_picture, "Vill du ta bort bilden?");
	strcpy(s_Do_you_want_to_delete_the_product, "Vill du ta bort produkten?");
	strcpy(s_Duplicate_and_append, "Duplicera och lägg till.");
	strcpy(s_Duplicate_values_are_ignored, "Dubbla värden ignorerades!");
	strcpy(s_Error, "Fel");
	strcpy(s_Error_loading_file, "Fel vid inläsning av fil.");
	strcpy(s_export_everything, "Exportera allt");
	strcpy(s_Fit_to_screen, "Anpassa till skärm.");
	strcpy(s_Force_fixed_height, "Rita bitarna med en fast höjd.");
	strcpy(s_Flipped, "Vänd");
	strcpy(s_Import, "Importera");
	strcpy(s_If_angles_are_different_from_90_degrees_height_must_be_greater_than_0, "Om vinklarna skiljer sig från 90 grader måste höjden vara större än 0.");
	strcpy(s_Ignore, "Strunta i");
	strcpy(s_Incorrect_value, "Felaktigt värde");
	strcpy(s_Info, "Info");
	strcpy(s_Interior, "inuti");
	strcpy(s_Give_a_name, "Ge ett namn.");
	strcpy(s_Group, "Gruppera det");
	strcpy(s_Header, "Rubrik");
	strcpy(s_Keep_it_as_it_is, "Håll det som det är");
	strcpy(s_Level, "Level");
	strcpy(s_Licensee, "Licensinnehavare");
	strcpy(s_List_separator, "Listavgränsare");
	strcpy(s_Made_with_love_in_Cugir_Romania, "Tillverkad, med kärlek, i: Cugir, Rumänien");
	strcpy(s_Made_in, "Tillverkad i");
	strcpy(s_Manufacturer, "Tillverkare");

	strcpy(s_Manual_arrange, "Manuellt arrangera");

	strcpy(s_Mixed, "Blandad");
	strcpy(s_Multiple_shapes_detected_Next_rows_will_be_overwritten_Continue, "Mer än en form upptäcktes. Därför kommer de efterföljande raderna att skrivas över. Fortsätta?");
	strcpy(s_More, "Mer");
	strcpy(s_Multiple_values, "Flera värden");
	strcpy(s_No_texture, "Ingen textur");
	strcpy(s_Number, "siffra");
	strcpy(s_Number_of_images, "Antal bilder");
	strcpy(s_Number_of_vertices, "Antal vertikaler");
	strcpy(s_Offset, "Offset");
	strcpy(s_Only_the_currently_selected_items, "Endast de för närvarande valda objekten.");
	strcpy(s_Optimizing_please_wait, "Optimerar ... vänta.");

	strcpy(s_Paste, "Paste");

	strcpy(s_Piece_label, "Visar bit etikett");
	strcpy(s_Piece_size, "Visar storleken av styckena");
	strcpy(s_Please_contact_us_by_email_if_you_receive_this_error, "Kontakta oss via e-post om du får detta fel.");
	strcpy(s_Please_save_it_first, "Snälla, spara det först.");
	strcpy(s_Position, "Placera");
	strcpy(s_Preview, "Förhandsvisning");
	strcpy(s_Rectangle, "Rektangel");

	strcpy(s_Redo_the_last_operation, "Återställ den sista handlingen");
	strcpy(s_Regular_polygon, "Regelbunden polygon");

	strcpy(s_Reused, "Återanvänds");
	strcpy(s_Rotated, "Roterad");
	strcpy(s_Save_all, "Rädda alla");
	strcpy(s_Scrap_label, "Visar avfall etikett");
	strcpy(s_Scrap_size, "Visa storleken av avfal");
	strcpy(s_Semicolon, "Semikolon");
	strcpy(s_Show_cut_index, "Visa index skära");
	strcpy(s_Show_information, "Visa information");
	strcpy(s_Show_piece_label, "Visar bit etikett");
	strcpy(s_Show_scrap_label, "Visar avfall etikett");
	strcpy(s_Show_scrap_s_size_on_the_small_pieces, "Visa skrotets storlek på de små bitarna");
	strcpy(s_Show_size_of_pieces, "Visar storleken av styckena");
	strcpy(s_Show_size_of_scrap, "Visa storleken av avfal");
	strcpy(s_Show_sizes, "Visa storlekar");
	strcpy(s_Show_label, "Visa etikett");
	strcpy(s_Show_length, "Visa längd");

	strcpy(s_Some_numerical_values_are_incorrect_Should_I_fix_all_the_incorrect_values, "Vissa numeriska värden är felaktiga! Ska jag fixa alla felaktiga värden?");
	strcpy(s_Some_invalid_values_have_been_removed, "Vissa ogiltiga värden har tagits bort.");
	strcpy(s_Sort_by, "Sortera efter");
	strcpy(s_Sort_ascending_by, "Sortera stigande efter");
	strcpy(s_Sort_descending_by, "Sortera fallande efter");
	strcpy(s_Start, "Start");
	strcpy(s_Starting_angle, "Startvinkel");
	strcpy(s_Sticker, "Klistermärke");

	strcpy(s_Stock, "Varumagasin");
	strcpy(s_Stop, "Stop");
	strcpy(s_System_setting, "Systeminställning");
	strcpy(s_Tabular, "Tabellform");
	strcpy(s_Total, "Total");
	strcpy(s_Total_size, "Total storlek");
	strcpy(s_Terms_of_the_license, "Licensvillkor");
	strcpy(s_The_current_product_has_been_changed_Do_you_want_to_save_it_to_file, "Den aktuella produkten har ändrats. Vill du spara den till fil?");
	strcpy(s_The_value_is_out_of_the_allowed_range, "Värdet ligger utanför det tillåtna intervallet.");
	strcpy(s_The_value_must_be_a_real_or_fractional_number_Try_to_replace_the_comma_with_the_dot_if_you_want_to_enter_a_real_number, "Värdet måste vara ett verkligt eller bråknummer. Försök ersätta komma med punkten om du vill ange ett riktigt nummer.");
	strcpy(s_This_feature_is_not_implemented_yet, "Denna funktion är inte implementerad ännu.");
	strcpy(s_This_operation_cannot_be_reversed, "Denna åtgärd kan inte omvändas.");
	strcpy(s_Undo_the_last_operation, "Ångra den sista åtgärden.");
	strcpy(s_Utilization, "Utnyttjande");
	strcpy(s_Utilized_Stock, "Utnyttjat lager");
	strcpy(s_Version, "Version");
	strcpy(s_Visible_columns, "Synliga kolumner");
	strcpy(s_You_already_have_the_latest_version_installed, "Du har redan installerat den senaste versionen!");
	strcpy(s_What_is_exported, "Vad exporteras?");
	strcpy(s0meansanynumberofpieces, "Zero varje antal bitar");
	strcpy(sAbout, "Ca");
	strcpy(sAccept, "Acceptera");
	strcpy(sAcceptall, "Acceptera alla");
	strcpy(sAcceptthecurrentsolution, "Acceptera den nuvarande lösningen");
	strcpy(sAdd, "Bifoga");
	strcpy(sAddapiece, "Lägg en bit");
	strcpy(sAddasimpleproducttoDemand, "Lägga en produkt i den befintliga efterfrågan.");
	strcpy(sAddgrindingthicknesstopartsize, "Lägg slipning tjocklek pjäs storlek");
	strcpy(sAddproductnametolabel, "Bifoga produktnamn till etikett");
	strcpy(sAddress, "Adress");
	strcpy(sAddselectedsizetoInventory, "Lägg till vald storlek till registret");
	strcpy(sAdhesivelabels, "Självhäftande etiketter");
	strcpy(sAdhesivelabelwithinformationaboutpiecesinDemandCustomernameLabelSizeCurrentData, "Etikett med information om delar av efterfrågan: Kund, Label, storlek, aktuella data.");
	strcpy(sAdhesivelabelwithinformationaboutsheetsinInventory, "Etikett med information om ark i lager.");
	strcpy(sAll, "Allt");
	strcpy(sAlloffcutswhichhavethesizegreaterthanthisvaluewillbeaddedtoInventory, "Alla spill som har större än detta värde kommer att läggas till inventering");
	strcpy(sAllowMirroring, "Tillåt spegling.");
	strcpy(sAllowRotation, "Medge rotation");
	strcpy(sAllPieces, "Alla bitar");
	strcpy(sAllpredefinedproducts, "Alla angivna produkter");
	strcpy(sAnewwindowwillbedisplayedwheretheusercansettheedgebandsforeachedge, "Ett nytt fönster visas där användaren kan ställa in banden för varje kant.");
	strcpy(sAnewwindowwillbedisplayedwheretheusercansetthegrindingvalueforeachedgeofthsheet, "Ett nytt fönster visas där användaren kan ställa in slipning värdet för varje kant av verket.");
	strcpy(sAnewwindowwillbedisplayedwheretheusercansetthetrimvalueforeachedgeofthsheet, "Ett nytt fönster visas där användaren kan ställa in fel för varje kant av verket.");
	strcpy(sAngle, "Vinke");
	strcpy(sAngles, "vinklar");
	strcpy(sAnoptimizationparameterisarealnumber, "En optimering parameter är ett reellt tal.");
	strcpy(sAnoptimizationparameterisfractionalnumber, "En optimering parameter är bråk.");
	strcpy(sAnyShape, "Herhangi bir şekil");
	strcpy(sApolygonmusthaveatleast2vertices, "En polygon måste ha minst 2 hörn!");
	strcpy(sApolygonmusthaveatleast3vertices, "En polygon måste ha minst 3 hörn!");
	strcpy(sApplication_fails_to_initialize, "Programvaran misslyckades initieringen.");
	strcpy(sArc, "Arc");
	strcpy(sArcLength, "Arc längd");
	strcpy(sAreaofusedsheets, "Område av begagnade skivor");
	strcpy(sAshortdescriptionofthesheet, "En kort beskrivning av arket");
	strcpy(sAtleastonepart, "Åtminstone ett stycke måste införas.");
	strcpy(sAtTheMarginOfTheSheet, "Vid kanten av arket");
	strcpy(sBandtypes, "Typer av kantlist.");
	strcpy(sBar, "Barer / rör");
	strcpy(sBars, "Barer / rör");
	strcpy(sBothsizesoftheoffcutsmustbegreaterthanthisvalue, "Båda storlekarna av spill måste vara större än detta värde.");
	strcpy(sBottom, "Botten");
	strcpy(sBottomcoordinateofthedefect, "Botten koordinaten för defekten");
	strcpy(sBreakCut, "Bryt cut");
	strcpy(sBrowse, "Bläddra");
	strcpy(sBuy, "Köp");
	strcpy(sBuynow, "Köp nu ...");
	strcpy(sCancel, "Avbryta");
	strcpy(sCannotBeEmpty, "kan inte vara tom!");
	strcpy(sCannotmovepartsbetweensheetswhenidenticalsheetsaregroupedPleaseungroupthesheetsfrommenu, "Kan inte flytta delarna från ett ark till en annan om de identiska arken grupperade Vänligen avbryta grupperingen av arken från menyn..");
	strcpy(sCannotSaveFile, "Kan inte spara filen");
	strcpy(sCenter, "Center");

	strcpy(sChangeDirection, "Ändra riktningen");
	strcpy(sChoose, "Välja");
	strcpy(sChooseProduct, "Välj produkt");
	strcpy(sCircle, "Circle");
	strcpy(sCity, "Stad");
	strcpy(sClear, "Rensa");
	strcpy(sClockWise, "Medurs");
	strcpy(sClosewindow, "Stäng fönster");
	strcpy(sColor, "Färg");
	strcpy(sColorofedgeband, "Färgen på kanten band");
	strcpy(sColorPattern, "Färg / Mönster");
	strcpy(sColorpiecesandwastes, "Bitar och avfall färgglada.");
	strcpy(sColumns, "Kolonner");
	strcpy(sComment, "Kommentar");
	strcpy(sCompanyname, "Företagsnamn");
	strcpy(sComplexMaterialExists, "Namnet på materialet som redan definierats i listan av komplexa material. Vänligen ge den ett nytt namn.");
	strcpy(sComputerCode, "Datakod");
	strcpy(sComputerCodefromyourcomputer, "Datakod (från datorn)");
	strcpy(sComputethetotalpriceofDemand, "Beräkna den totala kostnaden för efterfrågan");
	strcpy(sContents, "Innehål");
	strcpy(sContinutComanda, "Innehållet i efterfrågan i dag");
	strcpy(sContinutDepozit, "Innehållet i registret i dag");
	strcpy(sConversionIsDoneOnlyWhenSomePiecesHaveFractionalValues, "Konvertering görs endast när vissa bitar har bråktal.");
	strcpy(sConvertsTheSizeOfWasteToAFractionalUnit, "Visar storleken av avfall som ett bråktal.");
	strcpy(sCouldNotSaveFile1, "Kunde inte skriva filen i katalogen");
	strcpy(sCouldNotSaveFile2, "Du kanske inte har tillräckligt med rättigheter. Kontrollera eller ändra arbetskatalog från menyn Inställningar | Arbeta katalog till en mapp där du har rätt att skriva (t.ex. c:\\temp).");
	strcpy(sCreationdateYMDHMS, "Datum för skapande (Y / M / D, H: M: S)");
	strcpy(sCurrentDate, "aktuellt datum");
	strcpy(sCurrentDiagram, "Aktuellt diagram");
	strcpy(sCurrentMaterial, "Aktuell Materia");
	strcpy(sCurrentversion, "Current version");
	strcpy(sCurve_not_closed_Try_increasing_DXF_linking_distance_parameter, "Polygonen är inte stängd! Försök att öka parametern DXF-länkavstånd.");
	strcpy(sCustomer, "Kund");
	strcpy(sCustomerName, "Kundens namn");
	strcpy(sCustomMessage, "Eget meddelande");
	strcpy(sCutlength, "Längden av skuren");
	strcpy(sCut, "Skära");
	strcpy(sCuts, "Cuts");
	strcpy(sCutterThickness, "Skärning tjocklek");
	strcpy(sData, "Data");
	strcpy(sDataCannotBeEmpty, "Uppgifterna kan inte vara tomma!");
	strcpy(sDateymdhms, "Datum (y / m / d / h / m / s)");
	strcpy(sDays_left_for_trial, "Dagar tillgängliga för testning ");
	strcpy(sDaysLeft, "dagar kvar");
	strcpy(sStandard, "Standard");
	strcpy(sDefaultInterface, "standardgränssnitt");
	strcpy(sDefects, "Defekter");
	strcpy(sDefectsManager, "Hantera defekter");
	strcpy(sDefectsofthematerialNopiecescanbeplacedinthefaultyzone, "Defekter i materialet. Inga delar kan placeras i den trasiga zonen.");
	strcpy(sDelete, "Bort");
	strcpy(sDeletePiece, "Bort bit");
	strcpy(sDeleteRow, "Ta bort rad");
	strcpy(sDemandutilization, "Utnyttjande av efterfrågan");
	strcpy(sDepozitulmodificat, "De använda delar har tagits bort. Resterna har lagts till lager.");
	strcpy(sDepozitvid, "Beståndet är tom");
	strcpy(sDesk, "skrivbord");
	strcpy(sDiagram, "Diagrammet");
	strcpy(sDiagrams, "Diagram");
	strcpy(sDiagramasatable, "Diagrammet som en tabel");
	strcpy(sDigits, "siffror");
	strcpy(sDimensiuniplaca, "Storleken av arket");
	strcpy(sDirection, "Riktning");
	strcpy(sDistanceBetweenRows, "Avståndet mellan raderna");
	strcpy(sDonotuseit, "Använd den inte");
	strcpy(sDownload, "Ladda ner");
	strcpy(sDoYouWantToClearTheData, "Du vill ta bort data?");
	strcpy(sDoYouWantToSaveDemand, "Delarna har ändrats! Du vill spara ändringarna?");
	strcpy(sDoYouWantToSaveParts, "Vill du spara delar?");
	strcpy(sDoYouWantToSaveRepository, "Beståndet har ändrats! Du vill spara ändringarna?");
	strcpy(sDrawing, "Ritningar");
	strcpy(sDrawthesolutioncolorful, "Rita lösningen färgstarka");
	strcpy(sDuplicateTypes, "Vissa typer är dubblerade! Ta bort dubbletter");
	strcpy(sDuplicateTypesWithComplex, "Några namn av material finns redan i listan med komplexa typer! Ta bort dubbletter");
	strcpy(sDuplicateValues, "Duplicerade värden");
	strcpy(sEdgeband, "Band för kanter");
	strcpy(sEdgebandingwhichisplacedontheedgesofyourpiecePleasedefineedgebandingtypesfromMaterialsEdgeBandingmenu, "Edge banding som placeras på kanterna av din pjäs. Vänligen ange kantlistmaskiner typer från Materials menyn.");
	strcpy(sEdgebandsthatwillbeappliedtoeachpart, "Edge band som kommer att tillämpas på varje del.");
	strcpy(sEdgeBandTolerance, "Tolerans för kanten banding");
	strcpy(sEdgesthatmustbecutduefaults, "Kanter som måste skäras grund fel.");
	strcpy(sEdgetoedge, "Från kant till kant");
	strcpy(sEdit, "Redigera");
	strcpy(sEmail, "E-post");
	strcpy(sEmptyData, "Uppgifterna är tom!");
	strcpy(sEnabled, "Aktiverad");
	strcpy(sEnabledisabledefectsoftheinventorysheets, "Aktivera / inaktivera fel i beståndet");
	strcpy(sEnterLabel, "Input etikett");
	strcpy(sEnterTheMaterialName, "Mata in namnet på materialet");
	strcpy(sEnterTheProductName, "Ange namnet på produkten");
	strcpy(sEvaluationError, "Fel att uttrycket utvärderingen!");
	strcpy(sExit, "Utgång");
	strcpy(sExpired, "Programvaran har gått ut! Vänligen registrera programvaran!");
	strcpy(sExport, "Exportera");
	strcpy(sExportAllDiagrams, "Exportera alla diagram");
	strcpy(sExportAllToASingleFile, "Exportera allt till en enda fil");
	strcpy(sExportOptions, "Export alternativ.");
	strcpy(sExporttoDXFformat, "Exportera till DXF-format");
	strcpy(sExporttoExcel, "Exportera till Excel");
	strcpy(sExpresieIncorecta, "Felaktig matematiska uttryck!");
	strcpy(sExtensions, "förlängning");
	strcpy(sExtra, "Extra");
	strcpy(sExtraComponents, "Extra komponenter");
	strcpy(sExtracomponentsattachedtoDemand, "Extra komponenter som fästs delar");
	strcpy(sFile, "Fi");
	strcpy(sFileName, "Filnamn");
	strcpy(sFillWastes, "Rita avfall sneda linjer");
	strcpy(sFindoptimalbarsheetsize, "Hitta optimal storlek för rör och plåt.");
	strcpy(sFindoptimalsizeofInventorypieces, "Hitta optimal storlek på lager stycken");
	strcpy(sFirstcutMultiplestages, "Första skärriktningen - Flera steg");
	strcpy(sFirstdirectionforcutishorizontal, "Första riktning för cut är horisontell.");
	strcpy(sFirstdirectionforcutisvertical, "Första riktning för cut är vertikal.");
	strcpy(sFollowthecontourofpieces, "Följa konturen av styckena");
	strcpy(sFont, "Font");
	strcpy(sFontsize, "Teckenstorlek");
	strcpy(sFullInfo, "Fullständig information");
	strcpy(sDisposedWaste, "Kasserat avfall");
	strcpy(sGeneral, "Allmänt");
	strcpy(sGenerateCNC, "Generera CNC");
	strcpy(sGrain, "Textur");
	strcpy(sGraindirection, "Fiber");
	strcpy(sGraphic, "Grafisk");
	strcpy(sGreaterorequalto, "Större eller lika med");
	strcpy(sGrid, "Tabeller ");
	strcpy(sGrinding, "slipning tjocklek");
	strcpy(sGrosimeTaieturaScalata, "Snittet tjocklek från den här bilden kan vara annorlunda än den verkliga eftersom bitarna inte är representerade på deras verkliga omfattning. Detta faktum påverkar inte resultaten.");
	strcpy(sGroupidenticallayouts, "Gruppering av identiska ark");
	strcpy(sGroupIdenticalParts, "Identiska delar grupperas.");
	strcpy(sGroupingOfIdenticalPiecesIntoOneRow, "Gruppering av identiska bitar i en rad.");
	strcpy(sGroupPartsAfterLoadingFromFile, "Gruppera delarna efter lastning från fi");
	strcpy(sHeight, "Höjd");
	strcpy(sHeighttolerance, "Tolerans för höjd");
	strcpy(sHelp, "Hjälp");
	strcpy(sHistory, "Historia");
	strcpy(sHorizontal, "Horisontel");
	strcpy(sHowtodisplayprintedgebands, "Hur det visar kanten band?");
	strcpy(sIfyousetthebandforoneedgeallwillreceivethesamevalue, "Om du ställer in bandet för en kant, kommer alla att få samma värde.");
	strcpy(sIfyousetthegrindingforoneedgeallwillreceivethesamevalue, "Om du ställer in slipning värdet för en kant, kommer alla kanter får samma värde.");
	strcpy(sIfyousetthetrimforoneedgeallwillreceivethesamevalue, "Om du ställer in rengöring värdet för en kant, kommer alla kanter får samma värde.");
	strcpy(sImageBounds, "Gränser för bild");
	strcpy(sImageSize, "Bildstorlek.");
	strcpy(sImportData, "Importera data");
	strcpy(sIncorrectPassword, "Felaktigt lösenord");
	strcpy(sIndex, "Index");
	strcpy(sInformationaboutcustomer, "Information om kunden");
	strcpy(sInputALanguageName, "Ge ett namn till det språk");
	strcpy(sInsert, "Infoga");
	strcpy(sInsertPiece, "Insatsdelen");
	strcpy(sInterface, "Gränssnitt");
	strcpy(sInterfaceSettings, "Gränssnittsinställningar");
	strcpy(sInvalidHardware, "Jag kunde inte upptäcka hårdvaran. Kontakta oss på contact@optimalprograms.com");
	strcpy(sInvalidNumber, "Ogiltigt nummer");
	strcpy(sInvalidOrderOfComputation, "En order för att beräkna längderna inte kan fastställas. Det finns cirkulära relationer i definitionen av produkten!");
	strcpy(sInvalidRegistration, "Registreringen är ogiltigt!");
	strcpy(sInvalidTime, "Tiden för ditt system är ogiltig.");
	strcpy(sInventory, "VARUMAGASIN");
	strcpy(sisafractionalvalue, "är en fraktionerad värde.");
	strcpy(sIsArc, "Är bågen");
	strcpy(sisarealvalue, "är ett verkligt värde.");
	strcpy(sLabel, "Etiketter");
	strcpy(sLabels, "Etiketter");
	strcpy(sLanguage, "Språk");
	strcpy(sLatimeanumar0, "Bredden måste vara större än 0!");
	strcpy(sLatimeanumarreal, "Bredden måste vara ett reellt tal!");
	strcpy(sLayerName, "Lagernamn");
	strcpy(sLeft, "Vänster");
	strcpy(sLeftcoordinateofthedefect, "Vänster-koordinaten för defekten");
	strcpy(sLength, "Längd");
	strcpy(sLengthofthepiecestocut, "Styckestorlek för skärning");
	strcpy(sLengthofthepiecestocutfrom, "Arkstorlek för kapning");
	strcpy(sLengthofusedbars, "Storlek som används barer");
	strcpy(sLicenseAgreement, "Licensavta");
	strcpy(sLinear, "linjär");
	strcpy(sLinethickness, "Tjocklek på pennan");
	strcpy(sLoadafileandappenddatatothecurrentDemand, "Ladda en fil och lägga till data till rådande efterfrågan.");
	strcpy(sLoadanexistingDemandfromafile, "Ladda en befintlig efterfrågan från en fil.");
	strcpy(sLoadAppend, "Ladda och Bifoga");
	strcpy(sLoadEverything, "load allt");
	strcpy(sLoadInventory, "Ladda beståndet");
	strcpy(sLoadInventoryandDemand, "Fyll på lager och efterfrågan");
	strcpy(sLoadResults, "Ladda resultaten");
	strcpy(sLocked, "Låst");
	strcpy(sLogo, "logotyp");
	strcpy(sLong, "Long");
	strcpy(sLongerexecutiontime, "Längre genomförandetid");
	strcpy(sLungime, "Bredd");
	strcpy(sLungimeanumar0, "Längden måste vara större än 0!");
	strcpy(sLungimeanumarreal, "Längden ska vara ett reellt tal!");
	strcpy(sLungimeaTotalaFolosita, "Total utnyttjad längd");
	strcpy(sMagnification, "Förstoring");
	strcpy(sMagnify, "Förstora");
	strcpy(sMargins, "Marginaler");
	strcpy(sMarginsForPaper, "Marginalerna för papper");
	strcpy(sMarginsOfTheLabel, "Marginaler etiketten");
	strcpy(sMaterial, "Materia");
	strcpy(sMaterialName, "Namn på materialet");
	strcpy(sMaterials, "material");
	strcpy(sMaterialstypes, "Material typer");
	strcpy(sMax, "Max");
	strcpy(sMaximalArea, "Maximal område");
	strcpy(sMaximalCutLength, "Maximal skärlängd");
	strcpy(sMaxlength, "Maximallängds");
	strcpy(sMaxPiecesperBar, "Max Antal per Bar");
	strcpy(sMaxwidth, "Maximal bredd.");
	strcpy(sMeasurementUnit, "Mätenhet");
	strcpy(sMin, "min");
	strcpy(sMinimalBreakSize, "Minimal bristning storlek");
	strcpy(sMinimalUsefulSize, "Minimal användbar storlek");
	strcpy(sMinimalwastesizetoInventory, "Minimalt spill storlek för att inventering");
	strcpy(s_What_to_minimize, "Vad ska man minimera?");
	strcpy(sMinlength, "Minimal längd");
	strcpy(sMinwidth, "Minimal bredd");
	strcpy(sMirror, "Spege");
	strcpy(sMirroring, "Spegling.");
	strcpy(sMiscellaneous, "Övrigt");
	strcpy(sModify, "Ändra");
	strcpy(sModifytheselectedpiece, "Ändra den markerade delen");
	strcpy(sMovePiece, "Flytta pjäs.");
	strcpy(sMultiplestages, "Flera steg");
	strcpy(sName, "Namn");
	strcpy(sNameofedgeband, "Namn kantband");
	strcpy(sNewDEMANDUnsaveddatawillbelost, "Nya delar? Osparade data kommer att förloras!");
	strcpy(sNewLanguage, "Nya språket");
	strcpy(sNewMaterial, "New Materia");
	strcpy(sNewPasswordincorectlyintroduced, "Nytt lösenord introducerade fel!");
	strcpy(sNewProduct, "Ny produkt");
	strcpy(sNewversion, "Ny version");
	strcpy(sNo, "Ingen");
	strcpy(sNumarBucati, "Antalet bitar");
	strcpy(sNumberOfCopies, "Antalet kopior");
	strcpy(sNumberofstages, "Antal steg");
	strcpy(sNusuficienteplacidepozit, "Inte alla delar har optimerats. Möjliga orsaker: Det finns inte tillräckligt med bitar i INVENTERING), Piece inte utnyttjas i optimering), typer av bitarna från Efterfrågan och inventering inte matchas), andra parametrar har felaktigt inställd. Om du inte kan hitta orsaken kan du skicka oss en rapport genom att gå till menyn Hjälp | Service | Spara allt. Vänligen skicka oss via e-post den genererade filen.");
	strcpy(sOfficeNotInstaled, "Microsoft Office är inte installerat på datorn eller en incorect version installerad!");
	strcpy(sOldpassworddoesnotmatch, "Gammalt lösenord stämmer inte!");
	strcpy(sOnlinehelp, "Online hjälp");
	strcpy(sOnlypiecesofthesameheightinthelaststage, "Bitar av samma höjd i det sista steget");
	strcpy(sOpen, "Öppet");
	strcpy(sOptimization, "Optimering");
	strcpy(sOptimizationDone, "Optimering genomförs! Du kan skriva ut eller spara de erhållna diagram. Tryck på knappen Acceptera om du är nöjd med den nuvarande lösningen. Annars trycka på Starta igen.");
	strcpy(sOptimizationType, "Typ av optimering");
	strcpy(sOptions, "alternativ");
	strcpy(sOptionsrelatedtotheinterface, "Alternativ för gränssnittet");
	strcpy(sor, "eller");
	strcpy(sOthercomponents, "Övriga komponenter");
	strcpy(sOthers, "Andra");
	strcpy(sOtherstatistics, "Övrig statistik");
	strcpy(sOverrideExcelCSVfiles, "Åsidosätt Excel / CSV-filer");
	strcpy(sParameter, "Parameter");
	strcpy(sParts, "DELAR");
	strcpy(sPattern, "Mönster");
	strcpy(sPatternforwaste, "Mönster för avfal");
	strcpy(sPerimeter, "Perimeter");
	strcpy(sPermitedRotationAngle, "Den tillåtna rotationsvinkel.");
	strcpy(sPhone, "Telefonen");
	strcpy(sPicture, "Bild");
	strcpy(sPiece, "Piece");
	strcpy(sPieceindex, "Piece index");
	strcpy(sPieces, "Pieces");
	strcpy(sPiecesize, "Piece storlek");
	strcpy(sPiecesizelabeledgebandwillbeprinted, "Piece storlek, etikett kommer edge banden ut.");
	strcpy(sPierdere, "Avfal");
	strcpy(sPixels, "pixlar");
	strcpy(sPlacilefolositeDepozit, "Utnyttjat bitar från registret.");
	strcpy(sPlease_contact_us_at_contact_nestingtechnologies_com, "Kontakta oss på contact@nesting-technologies.com");
	strcpy(sPlease_contact_us_at_contact_optimalprograms_com, "Kontakta oss på contact@optimalprograms.com");
	strcpy(sPleaseenteralldataeitherasfractionalorrealDonotmixthem, "Ange alla data antingen som fraktionerad eller verkliga Blanda inte dem!");
	strcpy(sPleaseEnterSomeTypesOfMaterials, "Det finns ingen typ av definierat material. Du kan definiera dem från Materials menyn.");
	strcpy(sPleasesendtheNameandtheCodetotheaddresscontactoptimalprogramscominordertoobtaintheRegistrationKey, "För att få registrering Key skicka namn och kod till contact@optimalprograms.com.");
	strcpy(sPolygon, "Polygon");
	strcpy(sPolygonsCircles, "Polygoner, cirklar");
	strcpy(sPrecision, "Precision");
	strcpy(sPretulnumar0, "Priset måste vara större än 0!");
	strcpy(sPretulnumarreal, "Priset måste vara ett reellt tal!");
	strcpy(sPreview, "Förhandsgranska");
	strcpy(sPrice, "Pris");
	strcpy(sPriceMustBeGreaterThanZero, "Pris måste vara större än nol");
	strcpy(sPriceofbars, "Pris barer");
	strcpy(sPriceperbar, "Pris per bar");
	strcpy(sPricepersheet, "Pris per ark");
	strcpy(sPricepersquareunitofmaterial, "Per ytenhet av materialet.");
	strcpy(sPriceperunit, "Pris per enhet");
	strcpy(sPrint, "Skriva ut");
	strcpy(sPrintdiagramsastables, "Skriv diagram i form av tabeller.");
	strcpy(sPrinter, "Skrivare");
	strcpy(sPrinterBounds, "Marginalerna för skrivare");
	strcpy(sPrinting, "Utskrift");
	strcpy(sPrintonlyutilizedarea, "Skriv bara utnyttjad area");
	strcpy(sPrintthecontentsoftheDemand, "Skriva ut innehållet i efterfrågan.");
	strcpy(sPrintthecontentsoftheInventory, "Skriva ut innehållet i beståndet.");
	strcpy(sPrintthecurrentsolution, "Skriva ut den aktuella lösningen.");
	strcpy(sPriority, "Prioritet");
	strcpy(sPrioritytocutapieceZero0isthehighestpriority, "Prioritet för att skära en bit. Noll (0) är den högsta prioriteten.");
	strcpy(sProcentul0100, "De procenttal måste vara större än 0 och mindre eller lika med 100!");
	strcpy(sProcentulnumarreal, "De procenttal måste vara ett reellt tal!");
	strcpy(sProductdefinition, "Produkten definitionen");
	strcpy(sProductExists, "Produkten finns redan. Välj ett annat namn.");
	strcpy(sProductName, "Produktnamn");
	strcpy(sProducts, "Produkt");
	strcpy(sProducts, "Produkter");
	strcpy(sProject, "Projekt");
	strcpy(sProperties, "Egenskaper");
	strcpy(sProperty, "Fastighetsförmedling");
	strcpy(sQuantity, "Kvantitet");
	strcpy(sQuantitynumberofsheetsofthistype, "Antal ark av denna typ");
	strcpy(sRadius, "Radie");
	strcpy(sRectangular, "Rektangulär");
	strcpy(sRedefinetypesofedgeband, "Omdefiniera typer av kantband");
	strcpy(sRedefinetypesofmaterial, "Omdefiniera typer av materia");
	strcpy(sRegistration, "Registrering");
	strcpy(sRegistrationKeyfromOptimalPrograms, "Registreringsnycke");
	strcpy(sRegistrationSuccessful, "Registrering lyckad!");
	strcpy(sRemoveallpiecesinInventory, "Ta bort alla delar i lager.");
	strcpy(sRemoveCut, "Bort skära");
	strcpy(sRemovetheselectedpiece, "Ta bort den markerade delen");
	strcpy(sReports, "Rapporter");
	strcpy(sRequestedMaterial, "Begärda materialet");
	strcpy(sRestore, "Återstäl");
	strcpy(sResults, "Resultaten");
	strcpy(sReusedwaste, "Återanvändas avfal");
	strcpy(sRight, "Höger");
	strcpy(sRightcoordinateofthedefect, "Koordinater för defekten från höger");
	strcpy(sRotation, "Rotation.");
	strcpy(sRotationAngle, "Rotation vinkel.");
	strcpy(sRotationStep, "Rotationssteget");
	strcpy(sRoundAllFractionsTo, "De fraktionella värden måste avrundas till");
	strcpy(sRow, "rad");
	strcpy(sRows, "Rader");
	strcpy(sRun, "Senaste lösningarna");
	strcpy(sRunningtime, "gångtid");
	strcpy(sSameforall, "Samma för alla");
	strcpy(sSave, "Spara");
	strcpy(sSaveAllImages, "Spara alla bilder");
	strcpy(sSaveAs, "Spara som");
	strcpy(sSaveChanges, "Efterfrågan har ändrats. Vill du spara?");
	strcpy(sSaveCurrentImage, "Spara aktuell bild");
	strcpy(sSavedataparameters, "Spara data och parametrar");
	strcpy(sSaveEverything, "Spara allt");
	strcpy(sSaveInventory, "Spara Inventory");
	strcpy(sSaveInventoryandDemand, "Spara Inventering och efterfrågan");
	strcpy(sSaveResults, "Spara resultat");
	strcpy(sSaveStatisticsinafile, "Spara statistik i en fi");
	strcpy(sSavethecurrentimage, "Spara den aktuella bilden");
	strcpy(sSavethecurrentimageorstatistic, "Spara den aktuella bilden eller statistik");
	strcpy(sSavetheDEMANDinafile, "Spara till fi");
	strcpy(sSavetheDemandinafilewithadifferentname, "Spara Efterfrågan i en fil med ett annat namn.");
	strcpy(sSavetheREPOSITORYinafile, "Spara förvaret i en fi");
	strcpy(sSerialNumber, "Registreringsnycke");
	strcpy(sService, "tjänsten");
	strcpy(sSetDefaultValues, "Detta kommer att återställa alla parametrar till sina standardvärden. Alla dina inställningar kommer att försvinna. Är du säker på att du vill göra detta?");
	strcpy(sSetedgeband, "Ställ kantlist");
	strcpy(sSetedgetrim, "Ställ den skärande för fel på kanter");
	strcpy(sSetthesameedgebandforalledges, "Ställ in samma kant bandet för alla kanter");
	strcpy(sSetthesamegrindingforalledges, "Ställ in samma slipning för alla kanter");
	strcpy(sSetthesametrimforalledges, "Ställ in samma skärning för fel på alla kanter");
	strcpy(sSettings, "Inställningarna");
	strcpy(sShape, "Shape");
	strcpy(sSheet, "Arket");
	strcpy(sSheetsBarstypes, "Ark_rör typer");
	strcpy(sSheetSize, "Storleken av arket");
	strcpy(sSheetsperPage, "Ark per sida");
	strcpy(sShort, "Kort");
	strcpy(sShorterexecutiontime, "Kort gångtid");
	strcpy(sShowallsimpleproducts, "Visa alla enkla produkter");
	strcpy(sShowcustomername, "Visa kundens namn");
	strcpy(sShowCustomTextOnEachPiece, "Visa egen text på varje bit");
	strcpy(sShowdiagramasatable, "Visar diagram som en tabell.");
	strcpy(sShowedgeband, "Visa senaste band");
	strcpy(sShowedgebandssettinginanewwindow, "Visa inställningarna för kanten banden i ett nytt fönster");
	strcpy(sShowgrindingsettingsinanewwindow, "Visar slipning inställningar i ett nytt fönster");
	strcpy(sShowHorizontalLabelsAlways, "Visa alltid horisontella etiketter");
	strcpy(sShowRemovethesizeofthepiecesinthecurrentsolution, "Visa / Ta bort storleken av bitarna i den aktuella lösningen.");
	strcpy(sShowRemovethesizeofthewastesinthecurrentsolution, "Visa / Ta bort storleken av avfallet i den aktuella lösningen.");
	strcpy(sShowtotalcutlength, "Visa totala skärlängden");
	strcpy(sShowtrimedgesettingsinanewwindow, "Visa inställningarna för defekter i ett nytt fönster");
	strcpy(sSimpleMaterialExists, "Namnet på materialet som redan definierats i förteckningen över material. Vänligen ge den ett nytt namn.");
	strcpy(sSinglePieceStrips, "Ränder av ett stycke");
	strcpy(sSizes, "Storlekar");
	strcpy(sSmallerorequalto, "Mindre eller lika med");
	strcpy(sSort, "Sortera");
	strcpy(sSortAscendingByArea, "Sortera stigande efter område");
	strcpy(sSortDescendingByArea, "Sortera i sjunkande ordning efter område");
	strcpy(sSpecifyhowdifferentthepiecesinthelaststagecanbeValue0meansnodifference, "Ange hur olika kan vara bitar i sista steget. Värdet 0 betyder ingen skillnad.,");
	strcpy(sSpecifyifpiecesinthelaststagecanbedifferentornotdepeultimaetapapotfidiferitesaunucadimensiune, "Ange om delar i den sista kan vara olika eller inte");
	strcpy(sSpecifyifthepiececanberotatedornotIfnotitwillbecutinthesamewayasitwasintroducedinDemandLengthofthepieceparalleltothelengthofthesheet, "Ange om pjäsen kan roteras eller inte. Om inte, kommer den skäras på samma sätt som det infördes Demand (längden av delen parallellt med längden av arket),");
	strcpy(sSpecifyinhowmanystageswemakethecutsDuringastageallcutshavethesamedirection, "Ange i hur många etapper vi gör nedskärningar.");
	strcpy(sStartthesearchprocess, "Starta sökningen");
	strcpy(sStatistics, "Statistik");
	strcpy(sStatisticsE, "Rapporter Extra");
	strcpy(sStatisticsforeachtypeofmaterial, "Statistik för varje typ av materia");
	strcpy(sStep, "Steg");
	strcpy(sStergeDepozit, "Du vill ta bort Inventory?");
	strcpy(sStergeMaterial, "Ta bort material?");
	strcpy(sStergePiesele, "Du vill ta bort pjäsen?");
	strcpy(sStergePiesa, "Du vill ta bort pjäsen?");
	strcpy(sStopthesearchprocess, "Stoppa sökningen");
	strcpy(sStrongoptimization, "Stark optimering");
	strcpy(sSubtractthebandthicknessfrompiecesize, "Minska pjäsen storlek med bandets tjocklek");
	strcpy(sSummary, "Sammanfattning");
	strcpy(sSuprafataTotalaFolosita, "Totalt används ytan");
	strcpy(sSuprafatautilizata, "Utnyttjande");
	strcpy(sSwitchbetweenfiberandrotationoption, "Växla mellan fiber och rotation alternativ.");
	strcpy(sTechnical, "Teknisk");
	strcpy(sTechnicalsettings, "Tekniska inställningar");
	strcpy(sTemporaryPanelHint, "Tillfällig panel för rörliga delar mellan ark.");
	strcpy(sText, "Text");
	strcpy(sThe_application_has_expired, "Programmet har gått ut.");
	strcpy(sThe_application_is_not_registered, "Programvaran är inte registrerad.");
	strcpy(sThe_application_was_first_started_on, "Programvaran var först började på.");
	strcpy(sThecutsareperformedfromasidetotheothersideofthematerial, "Debiteringen utförs från en sida till den andra sidan av materialet.");
	strcpy(sThecuttingmachinecanfollowtheshapeofthematerial, "Skärmaskinen kan följa formen hos föremålet.");
	strcpy(sTheedgesofsheetsthatmustbetrimedduefaults, "Kanterna av arken som måste trimmas på grund av felen");
	strcpy(sTheLargestSize, "Den största storleken.");
	strcpy(sThenameofthecustomerforwhichyoucutthepiece, "Namnet på kunden som du skär pjäsen.");
	strcpy(sThenameofyourcustomer, "Namnet på din kund");
	strcpy(sThepiececanberotated, "Verket kan roteras");
	strcpy(sTheprogramtriestoavoidwasteswhichhavebothsizeslessthanthisvalue, "Programmet försöker undvika avfall som har både storlek mindre än detta värde");
	strcpy(sThereAreNoProducts, "Det finns inga definierade produkter ännu");
	strcpy(sThestockofmaterialhasbeenpreviouslyloadedfromanExcelorCSVformatPleaseloaditagain, "Det lager av material har tidigare laddats från ett Excel eller CSV-format. Vänligen ladda det igen om du vill arbeta på det.");
	strcpy(sThetotallengthofcutting, "Den totala längden av skärning");
	strcpy(sThewidthofthecuttingsawForglasscuttingoptimizationitcanbe0Forwooditshouldbegreaterthan0, "Tjockleken hos sågen. För glas skärning kan det vara 0. För trä den bör vara större än 0.");
	strcpy(sThewidthofthecuttingsawforlinearpieces, "Tjockleken av sågen för linjära bitar.");
	strcpy(sThickness, "Tjocklek");
	strcpy(sThischaracterisusedforfillingthewasterectanglesIfyoudonotwantfilledwastejustremovethischaracter, "Denna symbol används för att fylla avfall rektanglar. Om du inte vill fylld avfall bara ta bort den.");
	strcpy(sThisindexhasvaluebetween1andthenumberofpieces, "Detta index har värdet mellan 1 och antalet bitar.");
	strcpy(sThisOptionWillOverrideTheInventoryFileIfLoadedFromExcelOrCsvFiles, "Detta alternativ kommer att åsidosätta den fil som innehåller lager om beståndet laddas från Excel eller CSV-filer.");
	strcpy(sThisProgramisLicensedTo, "Det här programmet licensieras til");
	strcpy(sThisvaluewillbeaddedtotheedgebandingmaterialoneachside, "Detta värde kommer att adderas till kanten bandningsmaterialet på vardera sidan");
	strcpy(sTipNevid, "Den typ av material kan inte vara tom.");
	strcpy(sTitle, "Title");
	strcpy(sTools, "Verktyg");
	strcpy(sTop, "Topp");
	strcpy(sTopcoordinateofthedefect, "Toppen koordinaten för defekten.");
	strcpy(sTotalGarbageWaste, "Helt kasserad avfall");
	strcpy(sTotalInventoryWaste, "Totala stocken avfall");
	strcpy(sTotalRecycledWaste, "Allt återvunnet avfall");
	strcpy(sTotalusedarea, "Totalt används området");
	strcpy(sTotalusedlength, "Total angivna längden");
	strcpy(sTrigonometric, "Trigonometriska");
	strcpy(sTrim, "Trim");
	strcpy(sTrimalledgesatthebeginning, "Trimma alla kanter i början");
	strcpy(sTrimEdge, "Trimma kanten");
	strcpy(sTwoPanels, "2 paneler");
	strcpy(sType, "Typ");
	strcpy(sTypeofmaterialfromwhichtocut, "Typ av material från att skära");
	strcpy(sTypesAreNotMatched, "Optimeringen utfördes inte! Material från tabellerna Artikel och Lager överensstämmer inte! Man kan bara skära en artikel från materialet med samma namn i lager. Ändra materialets namn från motsvarande kolumner!");
	strcpy(sUndo, "Ångra");
	strcpy(sUndoAccept, "Ångra Acceptera");
	strcpy(sUnits, "enheter");
	strcpy(sUnregisteredVersion, "Oregistrerade");
	strcpy(sUpdates, "Uppdatering");
	strcpy(sUsefulforwoodfurniture, "Användbart för trämöbler");
	strcpy(sUseit, "Använd den");
	strcpy(sUsePieceinOptimization, "Använd biten i optimeringen");
	strcpy(sUserName, "Användarnamn");
	strcpy(sUtilizationandWastes, "Användning och avfal");
	strcpy(sUtilizedArea, "Ett område med utnyttjade delar");
	strcpy(sUtilizedBars, "Utnyttjas stängerna");
	strcpy(sUtilizeddemandcount, "Antalet utnyttjade bitar.");
	strcpy(sUtilizedParts, "Utnyttjas delar");
	strcpy(sUtilizedPieces, "Utnyttjade bitar");
	strcpy(sUtilizedSheets, "Utnyttjas ark");
	strcpy(sValue, "Värde");
	strcpy(sValueGreaterEqualToZero, "Värdet måste vara större eller lika med nol");
	strcpy(sValueGreaterThanZero, "Värdet måste vara större än nol");
	strcpy(sValueIntegerNumber, "Värdet måste vara ett heltal!");
	strcpy(sValueRealNumber, "Värdet måste vara ett reellt tal. Kanske du har använt, i stället för. eller vice versa. Vänligen fixa det!");
	strcpy(s_The_number_is_too_big_or_it_has_too_many_digits_after_decimal_separator, "Numret är för stort eller för många siffror efter decimalavskiljare!");
	strcpy(s_The_number_is_too_big, "Antalet är för stort!");
	strcpy(sVertical, "Vertika");
	strcpy(sWaste, "Avfal");
	strcpy(sWastes, "Avfal");
	strcpy(sWasteAddedToWarehouse, "Skrot till lagret");
	strcpy(sWastelimits, "gränsvärden för avfal");
	strcpy(sWasteType, "Typ av avfal");
	strcpy(sWeakoptimization, "Den svagaste optimering");
	strcpy(sWhattoprint, "Vad ska jag skriva ut");
	strcpy(s_What_to_print_or_save_to_file, "Vad du ska skriva ut eller spara till fil");
	strcpy(sWhattoprintoneachpiece, "Vad ska skriva ut på varje bit");
	strcpy(sWhattoshowoneachpiece, "Vad som ska visas på varje bit?");
	strcpy(sWidth, "Bredd");
	strcpy(sWood, "trä");
	strcpy(sWorkingDirectory, "Arbetskatalog");
	strcpy(sWrongKey, "Fel Registrering nyckeln!");
	strcpy(sYes, "Ja");
	strcpy(sYoucannotchooseblackblueorredcolors, "You cannot choose black, blue or red colors.");
	strcpy(sYouCannotMixFractionalDataWithDecimalOnes, "Du kan inte blanda bråktal med riktiga värden!");
	strcpy(sYourcompany, "Ditt företag");
	strcpy(sZip, "Postnummer");
	strcpy(s_Set_the_origin_and_the_direction_of_the_axes, "Ställ in origo och riktning för koordinataxlarna.");










	strcpy(s_Number_of_digits_after_the_decimal_separator, "Antal siffror efter decimalavgränsaren");
	strcpy(s_Percentages, "Procentandelar");
}

