// Language strings: Ukrainean
// Author: Optimal Programs
// License: MIT License
//---------------------------------------------------------------------------
#include <string.h>
//---------------------------------------------------------------------------
#include "language_string_id.h"
//---------------------------------------------------------------------------
void set_uk(void)
{
	//Ukrainean
	// translated by a distributor
	// last update on: 2025.9.25.0
	strcpy(s_Area, "Площа");
	strcpy(s_Mass, "Маса");
	strcpy(s_Advanced, "Просунутий");
	strcpy(s_Relative_coordinates, "Відносні координати");
	strcpy(s_Absolute_coordinates, "Абсолютні координати");
	strcpy(s_Append_more_rows, "Додайте більше рядків");

	strcpy(s_Add_to_parts, "Додати до деталей.");
	strcpy(s_Additional, "Додатковий");
	strcpy(s_All_results, "Всі результати.");
	strcpy(s_Allow_movement_of_pieces, "Дозволяють рух частин");
	strcpy(s_Allow_part_in_part, "Дозвольте по частинах");
	strcpy(s_Invalid_piece_Angles_are_too_small_or_too_big_or_height_is_too_small, "Недійсний шматок! Кути замалі або завеликі, або висота замала.");
	strcpy(s_Append, "Додавати");
	strcpy(s_As_it_is, "Так як є");
	strcpy(s_As_text, "Як текст");
	strcpy(s_Ascending, "Зростання");
	strcpy(s_Automatic, "Автоматичний");
	strcpy(s_Cannot_connect_to_the_Internet_Please_visit_our_website_from_a_browser, "Не вдається підключитися до Інтернету! Відвідайте наш веб-сайт із браузера.");
	strcpy(s_Cannot_copy_or_move_the_files, "Не вдається скопіювати або перемістити файли!");
	strcpy(s_Cannot_delete_the_file, "Не вдається видалити файл!");
	strcpy(s_Cannot_modify_old_results, "Неможливо змінити старі результати!");
	strcpy(s_To_change_click_inside_a_cell_or_press_0_1_or_2, "Щоб змінити, клацніть всередині комірки або натисніть 0, 1 або 2.");
	strcpy(s_Cell, "Стільниковий");
	strcpy(s_Click_on_the_table_header_to_change_the_columns, "Натисніть на заголовок таблиці, щоб змінити стовпці.");
	strcpy(s_Close, "Закрий це");
	strcpy(s_Contact_us, "Зв'яжіться з нами");
	strcpy(s_Column, "Колонка");
	strcpy(s_Comma, "Кома");
	strcpy(s_The_comma_symbol_cannot_simultaneously_be_the_list_separator_and_the_decimal_separator, "Символ коми не може одночасно бути роздільником списку та десятковим роздільником!");
	strcpy(s_Copy, "Копіювати");
	strcpy(s_Copy_for_move, "Taşınmak için kopyala");
	strcpy(s_Cut_higher_level_strips_first, "Спочатку виріжте смужки вищого рівня");
	strcpy(s_Cut_index, "Індекс з/п різу");

	strcpy(s_The_data_have_been_changed_Do_you_want_to_save_them_to_a_file, "Дані змінено. Ви хочете зберегти їх у файл?");
	strcpy(s_Decimal_separator, "Десятковий роздільник");
	strcpy(s_Restore_default_settings, "Відновити налаштування за замовчуванням");
	strcpy(s_Delete_fiber, "Видаліть клітковину");
	strcpy(s_Descending, "Спад");
	strcpy(s_Discard_changes, "Скасувати зміни");

	strcpy(s_Delete_all_data, "Видалити всі дані?");
	strcpy(s_Dot, "Крапка");
	strcpy(s_Do_you_want_to_delete_the_picture, "Видалити зображення?");
	strcpy(s_Do_you_want_to_delete_the_product, "Ви хочете видалити продукт?");
	strcpy(s_Duplicate_and_append, "Дублювати та додавати.");
	strcpy(s_Duplicate_values_are_ignored, "Повторювані значення проігноровано!");
	strcpy(s_Error, "Помилка");
	strcpy(s_Error_loading_file, "Помилка завантаження файлу.");
	strcpy(s_export_everything, "Експортуйте все");
	strcpy(s_Fit_to_screen, "Підходить до екрану.");
	strcpy(s_Force_fixed_height, "Намалюйте частини з фіксованою висотою.");
	strcpy(s_Flipped, "Перевернуто");
	strcpy(s_Import, "Імпорт");
	strcpy(s_If_angles_are_different_from_90_degrees_height_must_be_greater_than_0, "Якщо кути відрізняються від 90 градусів, висота має бути більше 0.");
	strcpy(s_Ignore, "Ігнорувати");
	strcpy(s_Incorrect_value, "Неправильне значення");
	strcpy(s_Info, "Інформація");
	strcpy(s_Interior, "всередині");
	strcpy(s_Give_a_name, "Дайте ім’я.");
	strcpy(s_Group, "Згрупуйте його");
	strcpy(s_Header, "Заголовок");
	strcpy(s_Keep_it_as_it_is, "Зберігайте так, як є");
	strcpy(s_Level, "Level");
	strcpy(s_Licensee, "Ліцензіат");
	strcpy(s_List_separator, "Роздільник списку");
	strcpy(s_Made_with_love_in_Cugir_Romania, "Зроблено з любов'ю в: Кугір, Румунія");
	strcpy(s_Made_in, "Виготовлено в");
	strcpy(s_Manufacturer, "Виробник");

	strcpy(s_Manual_arrange, "Ручне оформлення");

	strcpy(s_Mixed, "Змішаний");
	strcpy(s_Multiple_shapes_detected_Next_rows_will_be_overwritten_Continue, "Виявлено більше однієї форми. Таким чином, наступні рядки будуть перезаписані. Продовжити?");
	strcpy(s_More, "більше");
	strcpy(s_Multiple_values, "Кілька значень");
	strcpy(s_No_texture, "Без текстури");
	strcpy(s_Number, "Кількість");
	strcpy(s_Number_of_images, "Кількість зображень");
	strcpy(s_Number_of_vertices, "Кількість вершин");
	strcpy(s_Offset, "Зсув");
	strcpy(s_Only_the_currently_selected_items, "Лише вибрані елементи.");
	strcpy(s_Optimizing_please_wait, "Оптимізація... зачекайте.");

	strcpy(s_Paste, "Paste");

	strcpy(s_Piece_label, "Мітки деталей");
	strcpy(s_Piece_size, "Розміри деталей");
	strcpy(s_Please_contact_us_by_email_if_you_receive_this_error, "Будь ласка, зв'яжіться з нами електронною поштою, якщо ви отримаєте цю помилку.");
	strcpy(s_Please_save_it_first, "Збережіть його спочатку.");
	strcpy(s_Position, "Позиція");
	strcpy(s_Preview, "Попередній перегляд");
	strcpy(s_Rectangle, "Прямокутник");

	strcpy(s_Redo_the_last_operation, "Відновити останню операцію");
	strcpy(s_Regular_polygon, "Регулярний багатокутник");

	strcpy(s_Reused, "Повторне використання");
	strcpy(s_Rotated, "Поворот");
	strcpy(s_Save_all, "Зберегти все");
	strcpy(s_Scrap_label, "Мітки залишків");
	strcpy(s_Scrap_size, "Розміри залишків");
	strcpy(s_Semicolon, "Крапка з комою");
	strcpy(s_Show_cut_index, "Індекс з/п різу");
	strcpy(s_Show_information, "Показати інформацію");
	strcpy(s_Show_piece_label, "Мітки деталей");
	strcpy(s_Show_scrap_label, "Мітки залишків");
	strcpy(s_Show_scrap_s_size_on_the_small_pieces, "Показати розмір брухту на невеликих шматочках");
	strcpy(s_Show_size_of_pieces, "Розміри деталей");
	strcpy(s_Show_size_of_scrap, "Розміри залишків");
	strcpy(s_Show_sizes, "Показати розміри");
	strcpy(s_Show_label, "Показати мітку");
	strcpy(s_Show_length, "Показати довжину");

	strcpy(s_Some_numerical_values_are_incorrect_Should_I_fix_all_the_incorrect_values, "Деякі числові значення неправильні! Чи потрібно виправити всі невірні значення?");
	strcpy(s_Some_invalid_values_have_been_removed, "Деякі недійсні значення видалено.");
	strcpy(s_Sort_by, "Сортувати за");
	strcpy(s_Sort_ascending_by, "Сортувати за зростанням за");
	strcpy(s_Sort_descending_by, "Сортувати за спаданням за");
	strcpy(s_Start, "Start");
	strcpy(s_Starting_angle, "Початковий кут");


	strcpy(s_Stock, "СКЛАД");
	strcpy(s_Stop, "Stop");
	strcpy(s_System_setting, "Налаштування системи");
	strcpy(s_Tabular, "Табличні");
	strcpy(s_Total, "Всього");
	strcpy(s_Total_size, "Загальний розмір");
	strcpy(s_Terms_of_the_license, "Умови ліцензії");
	strcpy(s_The_current_product_has_been_changed_Do_you_want_to_save_it_to_file, "Поточний продукт змінено. Ви хочете зберегти його у файлі?");
	strcpy(s_The_value_is_out_of_the_allowed_range, "Значення виходить за межі допустимого діапазону.");
	strcpy(s_The_value_must_be_a_real_or_fractional_number_Try_to_replace_the_comma_with_the_dot_if_you_want_to_enter_a_real_number, "Значення повинно бути реальним чи дробовим числом. Спробуйте замінити кому крапкою, якщо ви хочете ввести дійсне число.");
	strcpy(s_This_feature_is_not_implemented_yet, "Ця функція ще не реалізована.");
	strcpy(s_This_operation_cannot_be_reversed, "Цю операцію неможливо скасувати.");
	strcpy(s_Undo_the_last_operation, "Скасуйте останню операцію.");
	strcpy(s_Utilization, "Утилізація");
	strcpy(s_Utilized_Stock, "Використаний запас");
	strcpy(s_Version, "Версія");
	strcpy(s_Visible_columns, "Видимі стовпці");
	strcpy(s_You_already_have_the_latest_version_installed, "У вас вже встановлена остання версія!");
	strcpy(s_What_is_exported, "Що експортується?");
	strcpy(s0meansanynumberofpieces, "Нуль означає будь-яку кількість деталей");
	strcpy(sAbout, "Про програму..");
	strcpy(sAccept, "Прийняти");
	strcpy(sAcceptall, "Прийняти все");
	strcpy(sAcceptthecurrentsolution, "Прийняти поточне рішення");
	strcpy(sAdd, "Додати");
	strcpy(sAddapiece, "Додати деталь в Заказ");
	strcpy(sAddasimpleproducttoDemand, "Додати в Заказ простий виріб");
	strcpy(sAddgrindingthicknesstopartsize, "Додати товщину шліфування до розміру деталі");
	strcpy(sAddproductnametolabel, "Внести назву вироба до мітки");
	strcpy(sAddress, "Адреса");
	strcpy(sAddselectedsizetoInventory, "Додати обраний розмір на Склад");
	strcpy(sAdhesivelabels, "Самоклеючі етикетки");
	strcpy(sAdhesivelabelwithinformationaboutpiecesinDemandCustomernameLabelSizeCurrentData, "Клейкі етикетки з інформацією про деталі Замовлення: Ім'я замовника, Мітка, Розмір, Поточні дані");
	strcpy(sAdhesivelabelwithinformationaboutsheetsinInventory, "Клейкі етикетки з інформацією о листах зі Складу");
	strcpy(sAll, "Усі");
	strcpy(sAlloffcutswhichhavethesizegreaterthanthisvaluewillbeaddedtoInventory, "Всі залишки, які мають кожен розмір більше ніж це значення, будуть відправлені на Склад");
	strcpy(sAllowMirroring, "Дозволити зеркалирования.");
	strcpy(sAllowRotation, "Дозволити обертання");
	strcpy(sAllPieces, "Всі фігури");
	strcpy(sAllpredefinedproducts, "Всі визначені вироби");
	strcpy(sAnewwindowwillbedisplayedwheretheusercansettheedgebandsforeachedge, "З'явиться нове вікно, де користувач може встановити кромку для кожного краю листа");
	strcpy(sAnewwindowwillbedisplayedwheretheusercansetthegrindingvalueforeachedgeofthsheet, "З'явиться нове вікно, де користувач може встановити значення шліфування для кожного краю деталі");
	strcpy(sAnewwindowwillbedisplayedwheretheusercansetthetrimvalueforeachedgeofthsheet, "З'явиться нове вікно, де користувач може встановити значення обрізки для кожного краю листа");
	strcpy(sAngle, "Кут");
	strcpy(sAngles, "Кути");
	strcpy(sAnoptimizationparameterisarealnumber, "Параметр оптимізації є дійсним числом");
	strcpy(sAnoptimizationparameterisfractionalnumber, "Параметр оптимізації є дробовим числом");
	strcpy(sAnyShape, "Будь-яка форма");
	strcpy(sApolygonmusthaveatleast2vertices, "Полігон повинен мати не менше 2 вершин!");
	strcpy(sApolygonmusthaveatleast3vertices, "Полігон повинен мати не менше 3 вершин!");
	strcpy(sApplication_fails_to_initialize, "Програмне забезпечення Збій при ініціалізації.");
	strcpy(sArc, "Д'Арк");
	strcpy(sArcLength, "Довжина дуги");
	strcpy(sAreaofusedsheets, "Площа використаних листів");
	strcpy(sAshortdescriptionofthesheet, "Короткий опис листа");
	strcpy(sAtleastonepart, "Принаймні, необхідно представити одну деталь");
	strcpy(sAtTheMarginOfTheSheet, "На краю листа");
	strcpy(sBandtypes, "Види кромки");
	strcpy(sBar, "Прутки / труби");
	strcpy(sBars, "Прутки / труби");
	strcpy(sBothsizesoftheoffcutsmustbegreaterthanthisvalue, "Обидва розміра залишків повинні бути більше цього значення");
	strcpy(sBottom, "Внизу");
	strcpy(sBottomcoordinateofthedefect, "Нижня координата дефекта");
	strcpy(sBreakCut, "Перервати розтин");
	strcpy(sBrowse, "Перегляд..");
	strcpy(sBuy, "Придбати");
	strcpy(sBuynow, "Придбати зараз ...");
	strcpy(sCancel, "Скасувати");
	strcpy(sCannotBeEmpty, "не може бути порожнім!");
	strcpy(sCannotmovepartsbetweensheetswhenidenticalsheetsaregroupedPleaseungroupthesheetsfrommenu, "Не можна переміщати деталі з одного листа на інший, якщо ідентичні листи згруповані. Будь ласка, скасуйте групування листів");
	strcpy(sCannotSaveFile, "Неможливо зберегти файл");
	strcpy(sCenter, "Центр");

	strcpy(sChangeDirection, "Змініть напрямок");
	strcpy(sChoose, "Оберіть");
	strcpy(sChooseProduct, "Оберіть Виріб");
	strcpy(sCircle, "Кругом");
	strcpy(sCity, "Місто");
	strcpy(sClear, "Очистити");
	strcpy(sClockWise, "За годинниковою стрілкою");
	strcpy(sClosewindow, "Закрити вікно");
	strcpy(sColor, "Колір");
	strcpy(sColorofedgeband, "Колір кромки");
	strcpy(sColorPattern, "Колір/Текстура");
	strcpy(sColorpiecesandwastes, "Колір деталей та залишків");
	strcpy(sColumns, "Стовпчики");
	strcpy(sComment, "Коментар");
	strcpy(sCompanyname, "Назва Вашої компанії");
	strcpy(sComplexMaterialExists, "Назва матеріалу вже є в списку складних матеріалів. Будь ласка, дайте йому нове ім'я");
	strcpy(sComputerCode, "Код комп'ютера");
	strcpy(sComputerCodefromyourcomputer, "Код");
	strcpy(sComputethetotalpriceofDemand, "Обчислити загальну вартість Заказа");
	strcpy(sContents, "Зміст");
	strcpy(sContinutComanda, "Зміст Замовлення станом на");
	strcpy(sContinutDepozit, "Зміст Складу станом на");
	strcpy(sConversionIsDoneOnlyWhenSomePiecesHaveFractionalValues, "Перетворення виконується тільки тоді, коли деякі частини мають дробові значення.");
	strcpy(sConvertsTheSizeOfWasteToAFractionalUnit, "Показує розмір відходів як дробового значення.");
	strcpy(sCouldNotSaveFile1, "Не можливо записати файл в папці: ");
	strcpy(sCouldNotSaveFile2, "Ви не маєте достатньо прав. Будь ласка, перевірте або змініть робочий каталог в меню Налаштування | Робоча папка на папку, де у вас є права на запис (наприклад, C:\\Temp)");
	strcpy(sCreationdateYMDHMS, "Дата створення (Р/М/Д, г:хв:с)");
	strcpy(sCurrentDate, "Поточна дата");
	strcpy(sCurrentDiagram, "Поточна діаграма");
	strcpy(sCurrentMaterial, "Поточний матеріал");
	strcpy(sCurrentversion, "Current version");
	strcpy(sCurve_not_closed_Try_increasing_DXF_linking_distance_parameter, "Полігон не закритий! Спробуйте збільшити параметр DXF відстань зв'язку.");
	strcpy(sCustomer, "Замовник");
	strcpy(sCustomerName, "Замовник");
	strcpy(sCustomMessage, "Користувальницькі повідомлення");
	strcpy(sCutlength, "Довжина розрізу");
	strcpy(sCut, "Вирізати");
	strcpy(sCuts, "Список різів");
	strcpy(sCutterThickness, "Ширина розрізу");
	strcpy(sData, "Дані");
	strcpy(sDataCannotBeEmpty, "Дані не можуть бути порожніми!");
	strcpy(sDateymdhms, "Дата (Р/М/Д /г/хв/с)");
	strcpy(sDays_left_for_trial, "Дні, доступні для тестування ");
	strcpy(sDaysLeft, "днів залишилося");
	strcpy(sStandard, "За умовч.");
	strcpy(sDefaultInterface, "Скидання Налаштувань");
	strcpy(sDefects, "Дефекти");
	strcpy(sDefectsManager, "Управління дефектами");
	strcpy(sDefectsofthematerialNopiecescanbeplacedinthefaultyzone, "Дефекти матеріалу. Деталі не будуть розташовані в зіпсованій зоні");
	strcpy(sDelete, "Видалити");
	strcpy(sDeletePiece, "Видалити деталь");
	strcpy(sDeleteRow, "видалити рядок");
	strcpy(sDemandutilization, "Замовлення виконано на %");
	strcpy(sDepozitulmodificat, "Використані деталі та листи були прибрані з Замовлення і Склада. Ділові залишки були додані на Склад");
	strcpy(sDepozitvid, "Склад порожній");
	strcpy(sDesk, "стіл");
	strcpy(sDiagram, "Схема");
	strcpy(sDiagrams, "Діаграми");
	strcpy(sDiagramasatable, "Схема у вигляді таблиці");
	strcpy(sDigits, "цифри");
	strcpy(sDimensiuniplaca, "Розмір листа");
	strcpy(sDirection, "Напрямок");
	strcpy(sDistanceBetweenRows, "Відстань між рядками");
	strcpy(sDonotuseit, "Не використовувати");
	strcpy(sDownload, "Завантажити");
	strcpy(sDoYouWantToClearTheData, "Ви бажаєте видалити дані?");
	strcpy(sDoYouWantToSaveDemand, "Замовлення було змінено! Бажаєте зберегти зміни?");
	strcpy(sDoYouWantToSaveParts, "Бажаєте зберегти деталі?");
	strcpy(sDoYouWantToSaveRepository, "Склад був змінений! Бажаєте зберегти зміни?");
	strcpy(sDrawing, "малюнки");
	strcpy(sDrawthesolutioncolorful, "Накреслити рішення в кольорі");
	strcpy(sDuplicateTypes, "Деякі типи дублюються! Будь ласка, видаліть дублікати");
	strcpy(sDuplicateTypesWithComplex, "Деякі назви матеріалів вже існують в списку складних типів! Будь ласка, видаліть дублікати");
	strcpy(sDuplicateValues, "Дубльовані значення");
	strcpy(sEdgeband, "Кромка");
	strcpy(sEdgebandingwhichisplacedontheedgesofyourpiecePleasedefineedgebandingtypesfromMaterialsEdgeBandingmenu, "Кромка, яка кріпиться до країв вашої деталі. Визначайте типи кромки в меню Матеріали | Кромка");
	strcpy(sEdgebandsthatwillbeappliedtoeachpart, "Кромка, що буде застосована до кожної деталі");
	strcpy(sEdgeBandTolerance, "Додати довжину кромки");
	strcpy(sEdgesthatmustbecutduefaults, "Края які повинні бути обрізані через дефекти");
	strcpy(sEdgetoedge, "Наскрізний");
	strcpy(sEdit, "Редагувати");
	strcpy(sEmail, "E-mail");
	strcpy(sEmptyData, "Даних немає!");
	strcpy(sEnabled, "Увімкнено");
	strcpy(sEnabledisabledefectsoftheinventorysheets, "Вкл/викл дефектів листів складу");
	strcpy(sEnterLabel, "Введіть мітку");
	strcpy(sEnterTheMaterialName, "Введіть назву матеріалу");
	strcpy(sEnterTheProductName, "Введіть назву виробу");
	strcpy(sEvaluationError, "Помилка в підрахунку виразу!");
	strcpy(sExit, "Вихід");
	strcpy(sExpired, "Пробний період закінчився! Будь ласка зареєструйтесь");
	strcpy(sExport, "Експорт");
	strcpy(sExportAllDiagrams, "Експортуйте всі діаграми");
	strcpy(sExportAllToASingleFile, "Експортуйте все в один файл");
	strcpy(sExportOptions, "Параметри експорту.");
	strcpy(sExporttoDXFformat, "Експорт у формат DXF");
	strcpy(sExporttoExcel, "Експорт в Excel");
	strcpy(sExpresieIncorecta, "Неправильний математичний вираз!");
	strcpy(sExtensions, "Розширення");
	strcpy(sExtra, "Додатково");
	strcpy(sExtraComponents, "Додаткові компоненти");
	strcpy(sExtracomponentsattachedtoDemand, "Додаткові компоненти Замовлення (фурнітура)");
	strcpy(sFile, "Файл");
	strcpy(sFileName, "Ім'я файлу");
	strcpy(sFillWastes, "Малювати залишки з косими лініями");
	strcpy(sFindoptimalbarsheetsize, "Знайти оптимальний розмір для смуг і листів.");
	strcpy(sFindoptimalsizeofInventorypieces, "Знайти оптимальні розміри листів Склада");
	strcpy(sFirstcutMultiplestages, "Перший напрямок різання (багатокроковий режим)");
	strcpy(sFirstdirectionforcutishorizontal, "Перший напрямок розрізу горизонтальний");
	strcpy(sFirstdirectionforcutisvertical, "Перший напрямок розрізу вертикальний");
	strcpy(sFollowthecontourofpieces, "Не наскрізний (за контуром)");
	strcpy(sFont, "Шрифт");
	strcpy(sFontsize, "Розмір шрифту");
	strcpy(sFullInfo, "Повна інформація");
	strcpy(sDisposedWaste, "Утилізовані відходи");
	strcpy(sGeneral, "Загальний");
	strcpy(sGenerateCNC, "Створювати команди ЧПК (багатокроковий режим)");
	strcpy(sGrain, "Волокно");
	strcpy(sGraindirection, "Волокно");
	strcpy(sGraphic, "Карта");
	strcpy(sGreaterorequalto, "Більше або дорівнює");
	strcpy(sGrid, "столи ");
	strcpy(sGrinding, "Шліфування");
	strcpy(sGrosimeTaieturaScalata, "Ширина пропилу на схемі може відрізнятися від реальної тому, що карта розкрою не представляє реальний масштаб елементів. У будь-якому випадку це не впливає на результат роботи");
	strcpy(sGroupidenticallayouts, "Групувати однакові листи");
	strcpy(sGroupIdenticalParts, "Групувати однакові деталі");
	strcpy(sGroupingOfIdenticalPiecesIntoOneRow, "Угруповання однакових частин в один рядок.");
	strcpy(sGroupPartsAfterLoadingFromFile, "Групувати деталі після завантаження файлу");
	strcpy(sHeight, "Висота");
	strcpy(sHeighttolerance, "Допуски висоти");
	strcpy(sHelp, "Допомога");
	strcpy(sHistory, "Історія");
	strcpy(sHorizontal, "Горизонтально");
	strcpy(sHowtodisplayprintedgebands, "Як відображати кромку?");
	strcpy(sIfyousetthebandforoneedgeallwillreceivethesamevalue, "При установці кромки для одного краю, решта отримують ту ж");
	strcpy(sIfyousetthegrindingforoneedgeallwillreceivethesamevalue, "Якщо ви встановите значення шліфовки для одного краю, всі інші отримають те ж значення");
	strcpy(sIfyousetthetrimforoneedgeallwillreceivethesamevalue, "Якщо ви встановите значення обрізки для одного краю, всі інші отримають те ж значення");
	strcpy(sImageBounds, "Межі для зображення");
	strcpy(sImageSize, "Розмір зображення.");
	strcpy(sImportData, "Імпорт даних");
	strcpy(sIncorrectPassword, "Невірний пароль");
	strcpy(sIndex, "Індекс");
	strcpy(sInformationaboutcustomer, "Інформація про замовника");
	strcpy(sInputALanguageName, "Дайте назву мові");
	strcpy(sInsert, "Вставити");
	strcpy(sInsertPiece, "Вставити деталь");
	strcpy(sInterface, "Зовнішній вигляд");
	strcpy(sInterfaceSettings, "Налаштування інтерфейсу та результатів");
	strcpy(sInvalidHardware, "Не можливо визначити апаратне забезпечення. Зв'яжіться з нами: contact@cutting.com.ua");
	strcpy(sInvalidNumber, "Невірне число");
	strcpy(sInvalidOrderOfComputation, "Не можливо здійснити підрахунок. Існують циклічні залежності у визначенні виробу!");
	strcpy(sInvalidRegistration, "Помилка реєстрації!");
	strcpy(sInvalidTime, "Час у вашій системі виставлено невірно");
	strcpy(sInventory, "СКЛАД");
	strcpy(sisafractionalvalue, "є дробовим значенням");
	strcpy(sIsArc, "Є дуги");
	strcpy(sisarealvalue, "є реальним значенням");
	strcpy(sLabel, "Мітка");
	strcpy(sLabels, "Етикетки");
	strcpy(sLanguage, "Мова");
	strcpy(sLatimeanumar0, "Ширина повинна бути більше 0!");
	strcpy(sLatimeanumarreal, "Ширина повинна бути дійсним числом!");
	strcpy(sLayerName, "Назва шару");
	strcpy(sLeft, "Зліва");
	strcpy(sLeftcoordinateofthedefect, "Ліва координата дефекту");
	strcpy(sLength, "Довжина");
	strcpy(sLengthofthepiecestocut, "Розміри деталей для розкрою");
	strcpy(sLengthofthepiecestocutfrom, "Розміри початкових листів та залишків");
	strcpy(sLengthofusedbars, "Розміри використаних смуг");
	strcpy(sLicenseAgreement, "Ліцензійна угода");
	strcpy(sLinear, "Лінійний");
	strcpy(sLinethickness, "Товщина ліній");
	strcpy(sLoadafileandappenddatatothecurrentDemand, "Відкрити файл і додати дані до поточного Замовлення.");
	strcpy(sLoadanexistingDemandfromafile, "Відкрити існуюче Замовлення з файлу");
	strcpy(sLoadAppend, "Додати до поточного Замовлення");
	strcpy(sLoadEverything, "Відкрити все..");
	strcpy(sLoadInventory, "Відкрити Склад");
	strcpy(sLoadInventoryandDemand, "Відкрити Склад та Замовлення");
	strcpy(sLoadResults, "Відкрити Результати");
	strcpy(sLocked, "замкнений");
	strcpy(sLogo, "Логотип");
	strcpy(sLong, "Лонг");
	strcpy(sLongerexecutiontime, "БІЛЬШЕ ЧАСУ");
	strcpy(sLungime, "Ширина");
	strcpy(sLungimeanumar0, "Довжина повинна бути більше 0!");
	strcpy(sLungimeanumarreal, "Довжина повинна бути дійсним числом!");
	strcpy(sLungimeaTotalaFolosita, "Вся використана довжина: ");
	strcpy(sMagnification, "Збільшення");
	strcpy(sMagnify, "Збільшити");
	strcpy(sMargins, "Поля");
	strcpy(sMarginsForPaper, "Поля для паперу");
	strcpy(sMarginsOfTheLabel, "Поля етикетки");
	strcpy(sMaterial, "Матеріали");
	strcpy(sMaterialName, "Назва матеріалу");
	strcpy(sMaterials, "Матеріали");
	strcpy(sMaterialstypes, "Види Матеріалу");
	strcpy(sMax, "Макс");
	strcpy(sMaximalArea, "Максимальна площа");
	strcpy(sMaximalCutLength, "MAX довжина різу");
	strcpy(sMaxlength, "MAX довжина");
	strcpy(sMaxPiecesperBar, " MAX деталей на смугу");
	strcpy(sMaxwidth, "MAX ширина");
	strcpy(sMeasurementUnit, "Одиниця виміру");
	strcpy(sMin, "Мін");
	strcpy(sMinimalBreakSize, "Min розмір розриву");
	strcpy(sMinimalUsefulSize, "Min корисний розмір");
	strcpy(sMinimalwastesizetoInventory, "Min залишок на Склад");
	strcpy(s_What_to_minimize, "Що звести до мінімуму?");
	strcpy(sMinlength, "Min довжина");
	strcpy(sMinwidth, "Min ширина");
	strcpy(sMirror, "Дзеркально");
	strcpy(sMirroring, "Що відображає");
	strcpy(sMiscellaneous, "Різне");
	strcpy(sModify, "Змінити");
	strcpy(sModifytheselectedpiece, "Змінити обрану деталь");
	strcpy(sMovePiece, "Переміщення частини.");
	strcpy(sMultiplestages, "Багатокроковий");
	strcpy(sName, "Назва");
	strcpy(sNameofedgeband, "Назва кромки");
	strcpy(sNewDEMANDUnsaveddatawillbelost, "Нові деталі? Незбережені дані будуть втрачені!");
	strcpy(sNewLanguage, "Нова мова");
	strcpy(sNewMaterial, "Новий матеріал");
	strcpy(sNewPasswordincorectlyintroduced, "Новий пароль введено невірно!");
	strcpy(sNewProduct, "Новий виріб");
	strcpy(sNewversion, "Нова версія");
	strcpy(sNo, "Ні");
	strcpy(sNumarBucati, "Кількість деталей");
	strcpy(sNumberOfCopies, "Кількість копій");
	strcpy(sNumberofstages, "Кількість кроків");
	strcpy(sNusuficienteplacidepozit, "Не всі деталі були розкроєні. Можливі причини: Не вистачає листів на Складі; Деталі не використовуються в оптимізації; Тип деталей Замовлення та листів Склада не збігаються; Деякі інші параметри встановлені невірно.");
	strcpy(sOfficeNotInstaled, "Microsoft Office не встановлений на комп'ютер або встановлена хибна версія!");
	strcpy(sOldpassworddoesnotmatch, "Старий пароль не співпадає!");
	strcpy(sOnlinehelp, "Допомога онлайн");
	strcpy(sOnlypiecesofthesameheightinthelaststage, "Тільки деталі однакової висоти на останньому кроці");
	strcpy(sOpen, "Відкрити");
	strcpy(sOptimization, "Оптимізація");
	strcpy(sOptimizationDone, "Розрахунок закінчений. Ви можете роздрукувати / зберегти отримані схеми. Натисніть <Прийняти> якщо ви задоволені цим рішенням. Інакше натисніть << Пуск >> знову");
	strcpy(sOptimizationType, "Тип оптимізації");
	strcpy(sOptions, "Параметри");
	strcpy(sOptionsrelatedtotheinterface, "Параметри пов'язані з інтерфейсом");
	strcpy(sor, "або");
	strcpy(sOthercomponents, "Інші компоненти");
	strcpy(sOthers, "Інші");
	strcpy(sOtherstatistics, "Інші статистичні дані");
	strcpy(sOverrideExcelCSVfiles, "скасовувати Excel / CSV файлів");
	strcpy(sParameter, "Параметр");
	strcpy(sParts, "ЗАМОВЛЕННЯ");
	strcpy(sPattern, "Текстура");
	strcpy(sPatternforwaste, "Текстура для друку");
	strcpy(sPerimeter, "Периметр");
	strcpy(sPermitedRotationAngle, "Допустимий кут повороту.");
	strcpy(sPhone, "Телефон");
	strcpy(sPicture, "Зображення");
	strcpy(sPiece, "Деталь");
	strcpy(sPieceindex, "№ п/п деталі");
	strcpy(sPieces, "деталі");
	strcpy(sPiecesize, "Розмір деталі");
	strcpy(sPiecesizelabeledgebandwillbeprinted, "Розмір деталі, мітка і кромка будуть надруковані");
	strcpy(sPierdere, "Залишок");
	strcpy(sPixels, "пікселів");
	strcpy(sPlacilefolositeDepozit, "Використані листи Склада");
	strcpy(sPlease_contact_us_at_contact_nestingtechnologies_com, "Будь ласка, зв'яжіться з нами по contact@nesting-technologies.com");
	strcpy(sPlease_contact_us_at_contact_optimalprograms_com, "Будь ласка, зв'яжіться з нами по contact@optimalprograms.com");
	strcpy(sPleaseenteralldataeitherasfractionalorrealDonotmixthem, "Будь ласка, введіть всі дані або у вигляді дробів або реальних чисел. Не змішуйте їх!");
	strcpy(sPleaseEnterSomeTypesOfMaterials, "Не визначений тип матеріалу. Ви можете визначити необхідні матеріали в меню Матеріали | Листи та Смуги");
	strcpy(sPleasesendtheNameandtheCodetotheaddresscontactoptimalprogramscominordertoobtaintheRegistrationKey, "Будь ласка вишліть на contact@cutting.com.ua Ім'я та Код щоб отримати Реєстраційний Ключ");
	strcpy(sPolygon, "Полігон");
	strcpy(sPolygonsCircles, "Багатокутники, кола");
	strcpy(sPrecision, "точність");
	strcpy(sPretulnumar0, "Ціна повинна бути більше 0!");
	strcpy(sPretulnumarreal, "Ціна повинна бути дійсним числом!");
	strcpy(sPreview, "Перегляд");
	strcpy(sPrice, "Ціна");
	strcpy(sPriceMustBeGreaterThanZero, "Ціна повинна бути більше нуля");
	strcpy(sPriceofbars, "Ціна барів");
	strcpy(sPriceperbar, "Ціна за один бар");
	strcpy(sPricepersheet, "Ціна за лист");
	strcpy(sPricepersquareunitofmaterial, "Ціна за одиницю площі матеріалу");
	strcpy(sPriceperunit, "Ціна за одиницю");
	strcpy(sPrint, "Друк");
	strcpy(sPrintdiagramsastables, "Друк схеми у вигляді таблиці");
	strcpy(sPrinter, "Принтер");
	strcpy(sPrinterBounds, "Поля для принтера");
	strcpy(sPrinting, "Друк");
	strcpy(sPrintonlyutilizedarea, "Друк тільки використаних листів");
	strcpy(sPrintthecontentsoftheDemand, "Роздрукувати вміст Замовлення");
	strcpy(sPrintthecontentsoftheInventory, "Роздрукувати вміст Склада");
	strcpy(sPrintthecurrentsolution, "Друк поточного рішення");
	strcpy(sPriority, "Пріоритет");
	strcpy(sPrioritytocutapieceZero0isthehighestpriority, "Пріоритет нарізки деталі. Нуль (0) має найвищий пріоритет.");
	strcpy(sProcentul0100, "Відсоток повинен бути більше 0 і менше або дорівнювати 100!");
	strcpy(sProcentulnumarreal, "Відсоток має бути дійсним числом!");
	strcpy(sProductdefinition, "Опис виробу");
	strcpy(sProductExists, "Виріб з такою назвою вже існує. Оберіть іншу");
	strcpy(sProductName, "Назва виробу");
	strcpy(sProducts, "Вироби");
	strcpy(sProducts, "Вироби");
	strcpy(sProject, "проект");
	strcpy(sProperties, "властивості");
	strcpy(sProperty, "властивість");
	strcpy(sQuantity, "Кількість");
	strcpy(sQuantitynumberofsheetsofthistype, "Кількість листів даного типу");
	strcpy(sRadius, "Радіус");
	strcpy(sRectangular, "Прямокутний");
	strcpy(sRedefinetypesofedgeband, "Перевизначення типів кромки");
	strcpy(sRedefinetypesofmaterial, "Перевизначення типів матеріалів");
	strcpy(sRegistration, "Реєстрація");
	strcpy(sRegistrationKeyfromOptimalPrograms, "Реєстраційний ключ");
	strcpy(sRegistrationSuccessful, "Реєстрація пройшла успішно!");
	strcpy(sRemoveallpiecesinInventory, "Прибрати всі елементи зі Складу");
	strcpy(sRemoveCut, "Прибрати різ");
	strcpy(sRemovetheselectedpiece, "Прибрати обрану деталь");
	strcpy(sReports, "Звіти");
	strcpy(sRequestedMaterial, "Потрібний тип");
	strcpy(sRestore, "Відновлення");
	strcpy(sResults, "Результати");
	strcpy(sReusedwaste, "Діловий залишок");
	strcpy(sRight, "Зправа");
	strcpy(sRightcoordinateofthedefect, "Права координата дефекту");
	strcpy(sRotation, "Обертання.");
	strcpy(sRotationAngle, "Кут повороту.");
	strcpy(sRotationStep, "Обертання крок");
	strcpy(sRoundAllFractionsTo, "Дробові значення повинні бути округлені до");
	strcpy(sRow, "рядок");
	strcpy(sRows, "Рядки");
	strcpy(sRun, "Останні рішення");
	strcpy(sRunningtime, "Час роботи");
	strcpy(sSameforall, "Те ж саме для всіх");
	strcpy(sSave, "Зберегти");
	strcpy(sSaveAllImages, "Зберегти всі зображення");
	strcpy(sSaveAs, "Зберегти як");
	strcpy(sSaveChanges, "Замовлення було змінено. Бажаєте зберегти?");
	strcpy(sSaveCurrentImage, "Зберегти поточне зображення");
	strcpy(sSavedataparameters, "Зберегти дані та параметри");
	strcpy(sSaveEverything, "Зберегти Все..");
	strcpy(sSaveInventory, "Зберегти Склад");
	strcpy(sSaveInventoryandDemand, "Зберегти Склад і Замовлення");
	strcpy(sSaveResults, "Зберегти Результати");
	strcpy(sSaveStatisticsinafile, "Зберегти статистику в файл");
	strcpy(sSavethecurrentimage, "Зберегти поточне зображення");
	strcpy(sSavethecurrentimageorstatistic, "Зберегти поточне зображення або статистику");
	strcpy(sSavetheDEMANDinafile, "Зберегти в файл");
	strcpy(sSavetheDemandinafilewithadifferentname, "Зберегти Замовлення у файлі під іншим ім'ям");
	strcpy(sSavetheREPOSITORYinafile, "Зберегти Склад у файлі");
	strcpy(sSerialNumber, "Реєстраційний ключ");
	strcpy(sService, "Сервіс");
	strcpy(sSetDefaultValues, "Це відновить всі параметри в їх значення за замовчуванням. Всі налаштування будуть втрачені. Ви впевнені, що хочете це зробити?");
	strcpy(sSetedgeband, "Установка кромки");
	strcpy(sSetedgetrim, "Установка обрізки країв");
	strcpy(sSetthesameedgebandforalledges, "Встановити ту ж кромку для кожного краю");
	strcpy(sSetthesamegrindingforalledges, "Встановити те ж шліфування для всіх сторін");
	strcpy(sSetthesametrimforalledges, "Встановити ту ж обрізку для всіх сторін");
	strcpy(sSettings, "Налаштування");
	strcpy(sShape, "Shape");
	strcpy(sSheet, "Лист");
	strcpy(sSheetsBarstypes, "Листи і Смуги");
	strcpy(sSheetSize, "Розмір листа");
	strcpy(sSheetsperPage, "Листів на Сторінку");
	strcpy(sShort, "Short");
	strcpy(sShorterexecutiontime, "менше часу");
	strcpy(sShowallsimpleproducts, "Показати всі прості вироби");
	strcpy(sShowcustomername, "Ім'я замовника");
	strcpy(sShowCustomTextOnEachPiece, "Довільний текст на кожній деталі Замовлення");
	strcpy(sShowdiagramasatable, "Показати схему таблицею");
	strcpy(sShowedgeband, "Кромку");
	strcpy(sShowedgebandssettinginanewwindow, "Налаштування смуг в новому вікні");
	strcpy(sShowgrindingsettingsinanewwindow, "Шліфувальні параметри в новому вікні");
	strcpy(sShowHorizontalLabelsAlways, "Мітки завжди горизонтально");
	strcpy(sShowRemovethesizeofthepiecesinthecurrentsolution, "Показати/Прибрати розміри деталей цього рішення");
	strcpy(sShowRemovethesizeofthewastesinthecurrentsolution, "Показати/Прибрати розміри залишків цього рішення");
	strcpy(sShowtotalcutlength, "Загальну довжину порізки");
	strcpy(sShowtrimedgesettingsinanewwindow, "Налаштування обрізки краю в новому вікні");
	strcpy(sSimpleMaterialExists, "Назва матеріалу вже є в списку матеріалів. Дайте іншу назву");
	strcpy(sSinglePieceStrips, "Одно-детальні смуги");
	strcpy(sSizes, "Розміри");
	strcpy(sSmallerorequalto, "Менше або дорівнює");
	strcpy(sSort, "Сортувати");
	strcpy(sSortAscendingByArea, "По зростанню площі");
	strcpy(sSortDescendingByArea, "По убуванню площі");
	strcpy(sSpecifyhowdifferentthepiecesinthelaststagecanbeValue0meansnodifference, "Вказує наскільки різними по висоті можуть бути деталі останнього кроку. Значення 0 означає, що немає різниці");
	strcpy(sSpecifyifpiecesinthelaststagecanbedifferentornotdepeultimaetapapotfidiferitesaunucadimensiune, "Вказує чи можуть деталі на останньому кроці бути різними чи ні");
	strcpy(sSpecifyifthepiececanberotatedornotIfnotitwillbecutinthesamewayasitwasintroducedinDemandLengthofthepieceparalleltothelengthofthesheet, "Вказує - може обертатися деталь чи ні. Якщо ні, вона буде розкроєна так само, як представлена ​​в замовленні (довжина деталі паралельна довжині листа)");
	strcpy(sSpecifyinhowmanystageswemakethecutsDuringastageallcutshavethesamedirection, "Вкажіть скільки кроків порізки можливо. На кожному кроці всі розтини матимуть один напрямок");
	strcpy(sStartthesearchprocess, "Почати процес пошуку");
	strcpy(sStatistics, "Статистика");
	strcpy(sStatisticsE, "Звіти: Додаткове");
	strcpy(sStatisticsforeachtypeofmaterial, "За типом матеріалу");
	strcpy(sStep, "Крок");
	strcpy(sStergeDepozit, "Ви хочете очистити Склад?");
	strcpy(sStergeMaterial, "Видалити матеріал?");
	strcpy(sStergePiesele, "Ви хочете, щоб видалити шматок?");
	strcpy(sStergePiesa, "Ви хочете, щоб видалити шматок?");
	strcpy(sStopthesearchprocess, "Зупинити процес пошуку");
	strcpy(sStrongoptimization, "СИЛЬНА");
	strcpy(sSubtractthebandthicknessfrompiecesize, "Відняти товщину кромки з розмірів деталей");
	strcpy(sSummary, "резюме");
	strcpy(sSuprafataTotalaFolosita, "Вся використана площа");
	strcpy(sSuprafatautilizata, "Використано");
	strcpy(sSwitchbetweenfiberandrotationoption, "Перемикання між режимами напрямки текстури і обертанням");
	strcpy(sTechnical, "Технічні");
	strcpy(sTechnicalsettings, "Технічні параметри");
	strcpy(sTemporaryPanelHint, "Тимчасова панель для перенесення деталей між листами");
	strcpy(sText, "Текст");
	strcpy(sThe_application_has_expired, "Програма закінчився.");
	strcpy(sThe_application_is_not_registered, "Програмне забезпечення не зареєстровані.");
	strcpy(sThe_application_was_first_started_on, "Програмне забезпечення було вперше почав на.");
	strcpy(sThecutsareperformedfromasidetotheothersideofthematerial, "Різ проводиться від однієї сторони матеріалу до іншої");
	strcpy(sThecuttingmachinecanfollowtheshapeofthematerial, "Машина порізки може слідувати формі деталей");
	strcpy(sTheedgesofsheetsthatmustbetrimedduefaults, "Край листа, що повинен бути обрізаний через пошкодження");
	strcpy(sTheLargestSize, "Найбільший розмір.");
	strcpy(sThenameofthecustomerforwhichyoucutthepiece, "Ім'я замовника, для якого ви робите порізку");
	strcpy(sThenameofyourcustomer, "Ім'я Вашого замовника");
	strcpy(sThepiececanberotated, "Деталь може обертатися");
	strcpy(sTheprogramtriestoavoidwasteswhichhavebothsizeslessthanthisvalue, "Всі залишки, у яких обидва розміру менше ніж це значення, будуть проігноровані");
	strcpy(sThereAreNoProducts, "Поки що не визначено жодного виробу");
	strcpy(sThestockofmaterialhasbeenpreviouslyloadedfromanExcelorCSVformatPleaseloaditagain, "Запаси матеріальних раніше була завантажена з формату Excel або CSV. Будь ласка, завантажте його знову, якщо ви хочете працювати на ньому.");
	strcpy(sThetotallengthofcutting, "Загальна довжина порізки");
	strcpy(sThewidthofthecuttingsawForglasscuttingoptimizationitcanbe0Forwooditshouldbegreaterthan0, "Ширина розрізу. Для різання скла воно може бути 0. Для деревини завжди більше 0");
	strcpy(sThewidthofthecuttingsawforlinearpieces, "Ширина розрізу для лінійного матеріалу");
	strcpy(sThickness, "Товщина");
	strcpy(sThischaracterisusedforfillingthewasterectanglesIfyoudonotwantfilledwastejustremovethischaracter, "Цей символ використовується для заповнення площі залишків. Якщо Ви не хочете цього - просто приберіть його");
	strcpy(sThisindexhasvaluebetween1andthenumberofpieces, "Цей номер має значення від 1 і до числа деталей");
	strcpy(sThisOptionWillOverrideTheInventoryFileIfLoadedFromExcelOrCsvFiles, "Цей параметр замінює файл, що містить запас, якщо фондовий завантажується з Excel або CSV файлах.");
	strcpy(sThisProgramisLicensedTo, "Програму зареєстровано на");
	strcpy(sThisvaluewillbeaddedtotheedgebandingmaterialoneachside, "Ця довжина буде додаватися до кожного відрізу кромки для зручності поклейки на матеріал");
	strcpy(sTipNevid, "Тип матеріалу не може бути порожнім");
	strcpy(sTitle, "Title");
	strcpy(sTools, "Інструменти");
	strcpy(sTop, "Зверху");
	strcpy(sTopcoordinateofthedefect, "Верхня координата дефекту");
	strcpy(sTotalGarbageWaste, "Всього відхідних залишків");
	strcpy(sTotalInventoryWaste, "Всього залишків Склада");
	strcpy(sTotalRecycledWaste, "Всього перероблених залишків");
	strcpy(sTotalusedarea, "Вся використана Площа");
	strcpy(sTotalusedlength, "Вся використана Довжина");
	strcpy(sTrigonometric, "Тригонометричні");
	strcpy(sTrim, "Обрізка");
	strcpy(sTrimalledgesatthebeginning, "Обрізка кожного краю на початку");
	strcpy(sTrimEdge, "Обрізка країв");
	strcpy(sTwoPanels, "2 панелі");
	strcpy(sType, "Тип");
	strcpy(sTypeofmaterialfromwhichtocut, "Тип початкового матеріалу для розкрою");
	strcpy(sTypesAreNotMatched, "Оптимізацію не виконано! Матеріали з таблиць Деталі та Запас не збігаються! Деталь можна вирізати лише з матеріалу з такою ж назвою в наявності. Змініть назви матеріалів з відповідних стовпців!");
	strcpy(sUndo, "Скасувати");
	strcpy(sUndoAccept, "Скасувати Прийняття");
	strcpy(sUnits, "одиниць");
	strcpy(sUnregisteredVersion, "Незареєстровано");
	strcpy(sUpdates, "оновлення");
	strcpy(sUsefulforwoodfurniture, "Корисно для корпусних меблів");
	strcpy(sUseit, "Використати");
	strcpy(sUsePieceinOptimization, "Використати деталь в розкрої");
	strcpy(sUserName, "Ім'я користувача");
	strcpy(sUtilizationandWastes, "Використано і Залишки");
	strcpy(sUtilizedArea, "Площа розкроєних деталей");
	strcpy(sUtilizedBars, "Використані смуги");
	strcpy(sUtilizeddemandcount, "Число розкроєних деталей Замовлення");
	strcpy(sUtilizedParts, "Розкроєні деталі");
	strcpy(sUtilizedPieces, "Використовувані частини");
	strcpy(sUtilizedSheets, "Використані листи");
	strcpy(sValue, "Значення");
	strcpy(sValueGreaterEqualToZero, "Значення має бути більше або дорівнює нулю");
	strcpy(sValueGreaterThanZero, "Значення має бути більше нуля");
	strcpy(sValueIntegerNumber, "Значення має бути цілим числом!");
	strcpy(sValueRealNumber, "Значення має бути дійсним числом. Може бути, ви використовували, замість. або навпаки. Будь ласка, виправте це!");
	strcpy(s_The_number_is_too_big_or_it_has_too_many_digits_after_decimal_separator, "Число занадто велике або воно має занадто багато цифр після десяткового роздільника!");
	strcpy(s_The_number_is_too_big, "Цифра завелика!");
	strcpy(sVertical, "Вертикально");
	strcpy(sWaste, "Залишок");
	strcpy(sWastes, "Залишок");
	strcpy(sWasteAddedToWarehouse, "Залишки додані на Склад");
	strcpy(sWastelimits, "Обмеження для залишків");
	strcpy(sWasteType, "Тип залишку");
	strcpy(sWeakoptimization, "слабка");
	strcpy(sWhattoprint, "Що друкувати");
	strcpy(s_What_to_print_or_save_to_file, "Що роздрукувати чи зберегти у файл");
	strcpy(sWhattoprintoneachpiece, "Що друкувати на кожній деталі");
	strcpy(sWhattoshowoneachpiece, "Що показувати на кожній деталі?");
	strcpy(sWidth, "Ширина");
	strcpy(sWood, "дерево");
	strcpy(sWorkingDirectory, "Робочий каталог");
	strcpy(sWrongKey, "Невірний ключ реєстрації!");
	strcpy(sYes, "Так");
	strcpy(sYoucannotchooseblackblueorredcolors, "You cannot choose black, blue or red colors.");
	strcpy(sYouCannotMixFractionalDataWithDecimalOnes, "Ви не можете змішувати дробові значення з реальними значеннями!");
	strcpy(sYourcompany, "Ваша компанія");
	strcpy(sZip, "Поштовий код");
	strcpy(s_Set_the_origin_and_the_direction_of_the_axes, "Задайте початок і напрямок осей координат.");










	strcpy(s_Number_of_digits_after_the_decimal_separator, "Кількість цифр після десяткового роздільника");
	strcpy(s_Percentages, "Відсотки");
}

