// Language strings: Norvegian
// Author: Optimal Programs
// License: MIT License
//---------------------------------------------------------------------------
#include <string.h>
//---------------------------------------------------------------------------
#include "language_string_id.h"
//---------------------------------------------------------------------------
void set_no(void)
{
	//Norvegian
	//automatic translation
	//2025.3.29.0
	strcpy(s_Advanced, "Avansert");
	strcpy(s_Relative_coordinates, "Relative koordinater");
	strcpy(s_Absolute_coordinates, "Absolutte koordinater");
	strcpy(s_Append_more_rows, "Legg til flere rader");

	strcpy(s_Add_to_parts, "Legg til deler.");
	strcpy(s_Additional, "Ytterligere");
	strcpy(s_All_results, "Alle resultater.");
	strcpy(s_Allow_movement_of_pieces, "Tillat bevegelse av brikkene");
	strcpy(s_Allow_part_in_part, "Tillat stykke i stykke");
	strcpy(s_Invalid_piece_Angles_are_too_small_or_too_big_or_height_is_too_small, "Ugyldig brikke! Vinklene er for små eller for store, eller høyden er for liten.");
	strcpy(s_Append, "Tilføy");
	strcpy(s_As_it_is, "Som det er");
	strcpy(s_As_text, "Som tekst");
	strcpy(s_Ascending, "stigende");
	strcpy(s_Automatic, "Automatisk");
	strcpy(s_Cannot_connect_to_the_Internet_Please_visit_our_website_from_a_browser, "Kan ikke koble til Internett! Besøk vår hjemmeside fra en nettleser.");
	strcpy(s_Cannot_copy_or_move_the_files, "Kan ikke kopiere eller flytte filene!");
	strcpy(s_Cannot_delete_the_file, "Kan ikke slette filen!");
	strcpy(s_Cannot_modify_old_results, "Kan ikke endre gamle resultater!");
	strcpy(s_To_change_click_inside_a_cell_or_press_0_1_or_2, "For å endre, klikk inne i en celle eller trykk på 0, 1 eller 2.");
	strcpy(s_Cell, "Celle");
	strcpy(s_Click_on_the_table_header_to_change_the_columns, "Klikk på tabelloverskriften for å endre kolonnene.");
	strcpy(s_Close, "Lukk den");
	strcpy(s_Contact_us, "Kontakt oss");
	strcpy(s_Column, "Kolonne");
	strcpy(s_Comma, "Komma");

	strcpy(s_Copy, "Kopiere");
	strcpy(s_Copy_for_move, "Kopier for flytting");
	strcpy(s_Cut_higher_level_strips_first, "Klipp strimler på høyere nivå først");
	strcpy(s_Cut_index, "Vis oversikt over kutte");

	strcpy(s_The_data_have_been_changed_Do_you_want_to_save_them_to_a_file, "Dataene er endret. Vil du lagre dem i en fil?");
	strcpy(s_Decimal_separator, "Desimalskilletegn");
	strcpy(s_Restore_default_settings, "Gjenopprett standardinnstillinger");
	strcpy(s_Delete_fiber, "Slett fiber");
	strcpy(s_Descending, "synkende");
	strcpy(s_Discard_changes, "Forkaste endringer");

	strcpy(s_Delete_all_data, "Vil du slette all data?");
	strcpy(s_Dot, "Punktum");
	strcpy(s_Do_you_want_to_delete_the_picture, "Vil du slette bildet?");
	strcpy(s_Do_you_want_to_delete_the_product, "Vil du slette produktet?");
	strcpy(s_Duplicate_and_append, "Dupliser og legg til.");
	strcpy(s_Duplicate_values_are_ignored, "Dupliserte verdier ble ignorert!");
	strcpy(s_Error, "Feil");
	strcpy(s_Error_loading_file, "Feil ved lasting av filen.");
	strcpy(s_export_everything, "Eksporter alt");
	strcpy(s_Fit_to_screen, "Tilpass til skjermen.");
	strcpy(s_Force_fixed_height, "Tegn brikkene med fast høyde.");
	strcpy(s_Flipped, "Snudd");
	strcpy(s_Import, "Importere");
	strcpy(s_If_angles_are_different_from_90_degrees_height_must_be_greater_than_0, "Hvis vinklene er forskjellige fra 90 grader, må høyden være større enn 0.");
	strcpy(s_Ignore, "Overse");
	strcpy(s_Incorrect_value, "Feil verdi");
	strcpy(s_Info, "Info");
	strcpy(s_Interior, "inne");
	strcpy(s_Give_a_name, "Gi et navn.");
	strcpy(s_Group, "Grupper det");
	strcpy(s_Header, "Overskrift");
	strcpy(s_Keep_it_as_it_is, "Hold det som det er");
	strcpy(s_Level, "Level");
	strcpy(s_Licensee, "Rettighetshaver");
	strcpy(s_List_separator, "Listeskilletegn");
	strcpy(s_Made_with_love_in_Cugir_Romania, "Laget, med kjærlighet, i: Cugir, Romania");
	strcpy(s_Made_in, "Produsert i");
	strcpy(s_Manufacturer, "Produsent");

	strcpy(s_Manual_arrange, "Ordne manuelt");

	strcpy(s_Mixed, "blandet");
	strcpy(s_Multiple_shapes_detected_Next_rows_will_be_overwritten_Continue, "Mer enn én form ble oppdaget. Derfor vil de påfølgende radene bli overskrevet. Fortsette?");
	strcpy(s_More, "Mer");
	strcpy(s_Multiple_values, "Flere verdier");
	strcpy(s_No_texture, "Ingen tekstur");
	strcpy(s_Number, "Antall");
	strcpy(s_Number_of_images, "Antall bilder");
	strcpy(s_Number_of_vertices, "Antall hjørner");
	strcpy(s_Offset, "Offset");
	strcpy(s_Only_the_currently_selected_items, "Bare de valgte elementene.");
	strcpy(s_Optimizing_please_wait, "Optimaliserer ... vennligst vent.");

	strcpy(s_Paste, "Paste");

	strcpy(s_Piece_label, "Vis stykke etikett");
	strcpy(s_Piece_size, "Vis størrelsen på bitene");
	strcpy(s_Please_contact_us_by_email_if_you_receive_this_error, "Ta kontakt med oss via e-post hvis du får denne feilen.");
	strcpy(s_Please_save_it_first, "Vær så snill, lagre den først.");
	strcpy(s_Position, "Stilling");
	strcpy(s_Preview, "Forhåndsvisning");
	strcpy(s_Rectangle, "Rektangel");

	strcpy(s_Redo_the_last_operation, "Gjenopprett den siste operasjonen");
	strcpy(s_Regular_polygon, "Vanlig polygon");

	strcpy(s_Reused, "Gjenbrukt");
	strcpy(s_Rotated, "Rotert");
	strcpy(s_Save_all, "Lagre alt");
	strcpy(s_Scrap_label, "Vis avfall etikett");
	strcpy(s_Scrap_size, "Vis størrelsen på avfal");
	strcpy(s_Semicolon, "Semikolon");
	strcpy(s_Show_cut_index, "Vis oversikt over kutte");
	strcpy(s_Show_information, "Vis informasjon");
	strcpy(s_Show_piece_label, "Vis stykke etikett");
	strcpy(s_Show_scrap_label, "Vis avfall etikett");
	strcpy(s_Show_scrap_s_size_on_the_small_pieces, "Vis skrapens størrelse på de små bitene");
	strcpy(s_Show_size_of_pieces, "Vis størrelsen på bitene");
	strcpy(s_Show_size_of_scrap, "Vis størrelsen på avfal");
	strcpy(s_Show_sizes, "Vis størrelser");
	strcpy(s_Show_label, "Vis etikett");
	strcpy(s_Show_length, "Vis lengde");

	strcpy(s_Some_numerical_values_are_incorrect_Should_I_fix_all_the_incorrect_values, "Noen numeriske verdier er feil! Bør jeg fikse alle uriktige verdier?");
	strcpy(s_Some_invalid_values_have_been_removed, "Noen ugyldige verdier er fjernet.");
	strcpy(s_Sort_by, "Sorter etter");
	strcpy(s_Sort_ascending_by, "Sorter stigende etter");
	strcpy(s_Sort_descending_by, "Sorter synkende etter");
	strcpy(s_Start, "Start");
	strcpy(s_Starting_angle, "Startvinkel");


	strcpy(s_Stock, "Lager");
	strcpy(s_Stop, "Stop");

	strcpy(s_Tabular, "Tabell");
	strcpy(s_Total, "Total");
	strcpy(s_Total_size, "Total størrelse");
	strcpy(s_Terms_of_the_license, "Vilkår for lisensen");
	strcpy(s_The_current_product_has_been_changed_Do_you_want_to_save_it_to_file, "Gjeldende produkt er endret. Vil du lagre den som fil?");
	strcpy(s_The_value_is_out_of_the_allowed_range, "Verdien er utenfor det tillatte området.");
	strcpy(s_The_value_must_be_a_real_or_fractional_number_Try_to_replace_the_comma_with_the_dot_if_you_want_to_enter_a_real_number, "Verdien må være et reelt eller brøknummer. Prøv å erstatte komma med prikken hvis du vil oppgi et reelt tall.");
	strcpy(s_This_feature_is_not_implemented_yet, "Denne funksjonen er ikke implementert ennå.");
	strcpy(s_This_operation_cannot_be_reversed, "Denne operasjonen kan ikke reverseres.");
	strcpy(s_Undo_the_last_operation, "Angre den siste operasjonen.");
	strcpy(s_Utilization, "Utnyttelse");
	strcpy(s_Utilized_Stock, "Utnyttet lager");
	strcpy(s_Version, "Versjon");
	strcpy(s_Visible_columns, "Synlige kolonner");
	strcpy(s_You_already_have_the_latest_version_installed, "Du har allerede installert den nyeste versjonen!");
	strcpy(s_What_is_exported, "Hva eksporteres?");
	strcpy(s0meansanynumberofpieces, "Null betyr enhver antall brikker");
	strcpy(sAbout, "Om");
	strcpy(sAccept, "Godta");
	strcpy(sAcceptall, "Godta alle");
	strcpy(sAcceptthecurrentsolution, "Godta dagens løsning");
	strcpy(sAdd, "Legg till");
	strcpy(sAddapiece, "Legg et stykke");
	strcpy(sAddasimpleproducttoDemand, "Legge et produkt i den eksisterende etterspørselen.");
	strcpy(sAddgrindingthicknesstopartsize, "Legg sliping tykkelse til stykke size");
	strcpy(sAddproductnametolabel, "Tilføy produkt navn til etiketten");
	strcpy(sAddress, "Adresse");
	strcpy(sAddselectedsizetoInventory, "Legg til valgt størrelse til inventar");
	strcpy(sAdhesivelabels, "Selvklebende etiketter");
	strcpy(sAdhesivelabelwithinformationaboutpiecesinDemandCustomernameLabelSizeCurrentData, "Selvklebende etikett med informasjon om brikker i Etterspørselen: Kunde, etiketter, størrelse, aktuelle data.");
	strcpy(sAdhesivelabelwithinformationaboutsheetsinInventory, "Selvklebende etikett med informasjon om ark i Inventory.");
	strcpy(sAll, "Alle");
	strcpy(sAlloffcutswhichhavethesizegreaterthanthisvaluewillbeaddedtoInventory, "Alle kapp som har størrelse større enn denne verdien vil bli lagt til varelager");
	strcpy(sAllowMirroring, "Tillat speiling");
	strcpy(sAllowRotation, "Tillat rotasjon");
	strcpy(sAllPieces, "Alle brikker");
	strcpy(sAllpredefinedproducts, "Alle forhåndsdefinerte produkter");
	strcpy(sAnewwindowwillbedisplayedwheretheusercansettheedgebandsforeachedge, "Et nytt vindu vil vises der brukeren kan sette kanten bandene for hver kant");
	strcpy(sAnewwindowwillbedisplayedwheretheusercansetthegrindingvalueforeachedgeofthsheet, "Et nytt vindu vil vises der brukeren kan sette sliping verdi for hver kant av stykket.");
	strcpy(sAnewwindowwillbedisplayedwheretheusercansetthetrimvalueforeachedgeofthsheet, "Et nytt vindu vil vises der brukeren kan sette de feil for hver kant av stykket.");
	strcpy(sAngle, "Vinke");
	strcpy(sAngles, "Hoeken");
	strcpy(sAnoptimizationparameterisarealnumber, "En optimalisering parameter er et reelt tall.");
	strcpy(sAnoptimizationparameterisfractionalnumber, "En optimalisering parameter er desimaltall.");
	strcpy(sAnyShape, "Enhver form");
	strcpy(sApolygonmusthaveatleast2vertices, "En polygon må ha minst 2 hjørner!");
	strcpy(sApolygonmusthaveatleast2vertices, "En polygon må ha minst 3 hjørner!");
	strcpy(sApplication_fails_to_initialize, "Programvaren mislyktes.");
	strcpy(sArc, "Arc");
	strcpy(sArcLength, "Buelengden");
	strcpy(sAreaofusedsheets, "Areal av brukte ark");
	strcpy(sAshortdescriptionofthesheet, "En kort beskrivelse av arket");
	strcpy(sAtleastonepart, "Minst én brikke må innføres.");
	strcpy(sAtTheMarginOfTheSheet, "På kanten av arket");
	strcpy(sBandtypes, "Typer edge bandet.");
	strcpy(sBar, "Barer / rør");
	strcpy(sBars, "Barer / rør");
	strcpy(sBothsizesoftheoffcutsmustbegreaterthanthisvalue, "Både størrelsen på kapp må være større enn denne verdien.");
	strcpy(sBottom, "Bottom");
	strcpy(sBottomcoordinateofthedefect, "Bunnen koordinat av defekten");
	strcpy(sBreakCut, "Bryt kutt");
	strcpy(sBrowse, "bla");
	strcpy(sBuy, "Kjøp");
	strcpy(sBuynow, "Kjøp nå ...");
	strcpy(sCancel, "Avbryt den");
	strcpy(sCannotBeEmpty, "kan ikke være tomt!");
	strcpy(sCannotmovepartsbetweensheetswhenidenticalsheetsaregroupedPleaseungroupthesheetsfrommenu, "Kan ikke flytte deler fra ett ark til et annet dersom de identiske ark er gruppert Vennligst avbryte gruppering av arkene fra menyen..");
	strcpy(sCannotSaveFile, "Kan ikke lagre filen");
	strcpy(sCenter, "Center");

	strcpy(sChangeDirection, "Endre retning");
	strcpy(sChoose, "Velg");
	strcpy(sChooseProduct, "Velg Produkt");
	strcpy(sCircle, "Sirke");
	strcpy(sCity, "By");
	strcpy(sClear, "Fjern");
	strcpy(sClockWise, "Klokken");
	strcpy(sClosewindow, "Lukk vindu");
	strcpy(sColor, "Color");
	strcpy(sColorofedgeband, "Fargen kanten bandet");
	strcpy(sColorPattern, "Farge / mønster");
	strcpy(sColorpiecesandwastes, "Deler og avfall fargerike.");
	strcpy(sColumns, "Kolonner");
	strcpy(sComment, "Kommentar");
	strcpy(sCompanyname, "Selskapets navn");
	strcpy(sComplexMaterialExists, "Navn på materiale er allerede definert i listen over komplekse materialer. Vennligst gi den et nytt navn.");
	strcpy(sComputerCode, "Datakode");
	strcpy(sComputerCodefromyourcomputer, "Computer kode (fra datamaskinen)");
	strcpy(sComputethetotalpriceofDemand, "Beregn den totale prisen for Etterspørselen");
	strcpy(sContents, "Innhold");
	strcpy(sContinutComanda, "Innhold av etterspørselen i dag");
	strcpy(sContinutDepozit, "Innhold av inventaret i dag");
	strcpy(sConversionIsDoneOnlyWhenSomePiecesHaveFractionalValues, "Konverteringen gjøres bare når noen stykker har brøkverdier.");
	strcpy(sConvertsTheSizeOfWasteToAFractionalUnit, "Viser størrelsen på avfallet som en brøk verdi.");
	strcpy(sCouldNotSaveFile1, "Kunne ikke skrive fil i katalogen");
	strcpy(sCouldNotSaveFile2, "Du har kanskje ikke nok rettigheter. Vennligst sjekk eller forandre arbeidskopien fra menyen Innstillinger | arbeidsmappen til en mappe der du har rettigheter til å skrive (for eksempel c:\\temp).");
	strcpy(sCreationdateYMDHMS, "Creation date (Y / M / D- H: M: S)");
	strcpy(sCurrentDate, "gjeldende dato");
	strcpy(sCurrentDiagram, "Gjeldende diagram");
	strcpy(sCurrentMaterial, "Gjeldende Materia");
	strcpy(sCurrentversion, "Gjeldende versjon");
	strcpy(sCurve_not_closed_Try_increasing_DXF_linking_distance_parameter, "Polygonen er ikke lukket! Prøv å øke parameteren DXF linking distance.");
	strcpy(sCustomer, "Kunden");
	strcpy(sCustomerName, "Kundenavn");
	strcpy(sCustomMessage, "Tilpasset melding");
	strcpy(sCutlength, "Lengden på kuttet");
	strcpy(sCut, "Kutte opp");
	strcpy(sCuts, "Cuts");
	strcpy(sCutterThickness, "Cutting tykkelse");
	strcpy(sData, "Dataene");
	strcpy(sDataCannotBeEmpty, "Dataene kan ikke være tomme!");
	strcpy(sDateymdhms, "Dato (y / m / d / t / m / s)");
	strcpy(sDays_left_for_trial, "Dager tilgjengelig for testing ");
	strcpy(sDaysLeft, "dager igjen");
	strcpy(sStandard, "Standard");
	strcpy(sDefaultInterface, "standard grensesnitt");
	strcpy(sDefects, "Defekter");
	strcpy(sDefectsManager, "Administrer defekter");
	strcpy(sDefectsofthematerialNopiecescanbeplacedinthefaultyzone, "Defekter av materialet. Ingen brikker kan plasseres i feil sone.");
	strcpy(sDelete, "Slett");
	strcpy(sDeletePiece, "Slett stykke");
	strcpy(sDeleteRow, "Slett rad");
	strcpy(sDemandutilization, "Utnyttelse av etterspørse");
	strcpy(sDepozitulmodificat, "De benyttede brikker har blitt fjernet. Restene har blitt lagt til lager.");
	strcpy(sDepozitvid, "Bestanden er tom");
	strcpy(sDesk, "skrivebord");
	strcpy(sDiagram, "Diagram");
	strcpy(sDiagrams, "Diagrammer");
	strcpy(sDiagramasatable, "Diagram som en tabel");
	strcpy(sDigits, "sifre");
	strcpy(sDimensiuniplaca, "Størrelse på ark");
	strcpy(sDirection, "Retning");
	strcpy(sDistanceBetweenRows, "Avstanden mellom radene");
	strcpy(sDonotuseit, "Ikke bruk det");
	strcpy(sDownload, "nedlasting");
	strcpy(sDoYouWantToClearTheData, "Du ønsker å slette dataene?");
	strcpy(sDoYouWantToSaveDemand, "Delene er endret! Du ønsker å lagre endringene?");
	strcpy(sDoYouWantToSaveParts, "Vil du gjøre for å redde deler?");
	strcpy(sDoYouWantToSaveRepository, "Aksjen har blitt endret! Du ønsker å lagre endringene?");
	strcpy(sDrawing, "tegninger");
	strcpy(sDrawthesolutioncolorful, "Tegn løsningen fargerike");
	strcpy(sDuplicateTypes, "Noen typer er duplisert! Vennligst fjern duplikater");
	strcpy(sDuplicateTypesWithComplex, "Noen navn på materialer som allerede eksisterer i listen av komplekse typer! Vennligst fjern duplikater");
	strcpy(sDuplicateValues, "Dupliserte verdier");
	strcpy(sEdgeband, "Bands for kanter");
	strcpy(sEdgebandingwhichisplacedontheedgesofyourpiecePleasedefineedgebandingtypesfromMaterialsEdgeBandingmenu, "Kantbåndmaskiner som er plassert på kanten av stykket ditt. Vennligst definere Kantbåndmaskiner typer fra Materials menyen.");
	strcpy(sEdgebandsthatwillbeappliedtoeachpart, "Edge band som vil bli anvendt til hver del.");
	strcpy(sEdgeBandTolerance, "Toleranse for Kantbåndmaskiner");
	strcpy(sEdgesthatmustbecutduefaults, "Kanter som må kuttes på grunn av feil.");
	strcpy(sEdgetoedge, "Fra kant til kant");
	strcpy(sEdit, "Rediger");
	strcpy(sEmail, "E-post");
	strcpy(sEmptyData, "Dataene er tom!");
	strcpy(sEnabled, "Aktivert");
	strcpy(sEnabledisabledefectsoftheinventorysheets, "Aktiver / deaktiver defekter på lager");
	strcpy(sEnterLabel, "Inngang etikett");
	strcpy(sEnterTheMaterialName, "Skriv inn navnet på materialet");
	strcpy(sEnterTheProductName, "Skriv inn navnet på produktet");
	strcpy(sEvaluationError, "Feil på uttrykket evalueringen!");
	strcpy(sExit, "Utgang");
	strcpy(sExpired, "Programvaren har utløpt! Vennligst registrer programmet!");
	strcpy(sExport, "Eksport");
	strcpy(sExportAllDiagrams, "Eksporter alle diagrammer");
	strcpy(sExportAllToASingleFile, "Eksporter alt til en enkelt fil");
	strcpy(sExportOptions, "Eksport alternativer.");
	strcpy(sExporttoDXFformat, "Eksporter til DXF format");
	strcpy(sExporttoExcel, "Eksporter til Excel");
	strcpy(sExpresieIncorecta, "Feil matematiske uttrykk!");
	strcpy(sExtensions, "utvidelser");
	strcpy(sExtra, "Extra");
	strcpy(sExtraComponents, "Ekstra Komponenter");
	strcpy(sExtracomponentsattachedtoDemand, "Ekstra komponenter festet til deler");
	strcpy(sFile, "File");
	strcpy(sFileName, "Filnavn");
	strcpy(sFillWastes, "Tegn avfall med skrå linjer");
	strcpy(sFindoptimalbarsheetsize, "Finn optimal størrelse for rør og plater.");
	strcpy(sFindoptimalsizeofInventorypieces, "Finn optimal størrelse på lager brikker");
	strcpy(sFirstcutMultiplestages, "Først cutting retning - flere stadier");
	strcpy(sFirstdirectionforcutishorizontal, "Først retning for kutt er horisontal.");
	strcpy(sFirstdirectionforcutisvertical, "Først retning for kutt er vertikal.");
	strcpy(sFollowthecontourofpieces, "Følg konturen av stykkene");
	strcpy(sFont, "Font");
	strcpy(sFontsize, "Skriftstørrelse");
	strcpy(sFullInfo, "Fullstendig informasjon");
	strcpy(sDisposedWaste, "Kassert avfall");
	strcpy(sGeneral, "Generelt");
	strcpy(sGenerateCNC, "Generer CNC");
	strcpy(sGrain, "Tekstur");
	strcpy(sGraindirection, "Teksturretning");
	strcpy(sGraphic, "Grafisk");
	strcpy(sGreaterorequalto, "Større eller lik");
	strcpy(sGrid, "tabeller ");
	strcpy(sGrinding, "sliping tykkelse");
	strcpy(sGrosimeTaieturaScalata, "Kuttet tykkelse fra dette bildet kan være forskjellig fra den virkelige fordi bitene ikke er representert ved sin sanne skala. Dette faktum påvirker ikke resultatene.");
	strcpy(sGroupidenticallayouts, "Gruppering av identiske ark");
	strcpy(sGroupIdenticalParts, "Identiske deler gruppert.");
	strcpy(sGroupingOfIdenticalPiecesIntoOneRow, "Gruppering av identiske brikker i en rad.");
	strcpy(sGroupPartsAfterLoadingFromFile, "Gruppere deler etter lasting fra fi");
	strcpy(sHeight, "Høyde");
	strcpy(sHeighttolerance, "Toleranse for høyde");
	strcpy(sHelp, "Hjelp");
	strcpy(sHistory, "Historie");
	strcpy(sHorizontal, "Horisonta");
	strcpy(sHowtodisplayprintedgebands, "Hvordan det viser edge band?");
	strcpy(sIfyousetthebandforoneedgeallwillreceivethesamevalue, "Hvis du setter bandet for en kant, vil alle få samme verdi.");
	strcpy(sIfyousetthegrindingforoneedgeallwillreceivethesamevalue, "Hvis du setter sliping verdi for én kant, vil alle kanter får samme verdi.");
	strcpy(sIfyousetthetrimforoneedgeallwillreceivethesamevalue, "Hvis du setter trimming for en kant, vil alle kanter får samme verdi.");
	strcpy(sImageBounds, "Bounds for bilde");
	strcpy(sImageSize, "Bildestørrelse");
	strcpy(sImportData, "Importer data");
	strcpy(sIncorrectPassword, "Feil passord");
	strcpy(sIndex, "Index");
	strcpy(sInformationaboutcustomer, "Informasjon om kunde");
	strcpy(sInputALanguageName, "Gi et navn til språket");
	strcpy(sInsert, "Sette inn");
	strcpy(sInsertPiece, "Sett stykke");
	strcpy(sInterface, "Interface");
	strcpy(sInterfaceSettings, "Interface innstillinger");
	strcpy(sInvalidHardware, "Jeg kunne ikke oppdage maskinvaren. Vennligst kontakt oss på contact@optimalprograms.com");
	strcpy(sInvalidNumber, "Ugyldig nummer");
	strcpy(sInvalidOrderOfComputation, "En ordre for å beregne lengder ikke kan etableres. Det er sirkulære relasjoner i produktet definisjonen!");
	strcpy(sInvalidRegistration, "Registrering er ugyldig!");
	strcpy(sInvalidTime, "Tiden i systemet ditt er ugyldig.");
	strcpy(sInventory, "LAGER");
	strcpy(sisafractionalvalue, "er en brøk verdi.");
	strcpy(sIsArc, "Er bue");
	strcpy(sisarealvalue, "er en reell verdi.");
	strcpy(sLabel, "Etikett");
	strcpy(sLabels, "Etiketter");
	strcpy(sLanguage, "Språk");
	strcpy(sLatimeanumar0, "Bredden må være større enn 0!");
	strcpy(sLatimeanumarreal, "Bredden må være et reelt tall!");
	strcpy(sLayerName, "Lagnavn");
	strcpy(sLeft, "Venstre");
	strcpy(sLeftcoordinateofthedefect, "Den venstre koordinat av defekten");
	strcpy(sLength, "Lengde");
	strcpy(sLengthofthepiecestocut, "Piece størrelse for å kutte");
	strcpy(sLengthofthepiecestocutfrom, "Platestørrelse for å kutte");
	strcpy(sLengthofusedbars, "Størrelsen av brukte barer");
	strcpy(sLicenseAgreement, "lisensavtale");
	strcpy(sLinear, "Linear");
	strcpy(sLinethickness, "Tykkelse på penn");
	strcpy(sLoadafileandappenddatatothecurrentDemand, "Laste en fil og legge dataene til dagens etterspørsel.");
	strcpy(sLoadanexistingDemandfromafile, "Legge en eksisterende etterspørsel fra en fil.");
	strcpy(sLoadAppend, "Laste og Tilføy");
	strcpy(sLoadEverything, "belastning alt");
	strcpy(sLoadInventory, "Legg lager");
	strcpy(sLoadInventoryandDemand, "Legg lager og etterspørselen");
	strcpy(sLoadResults, "Legge resultatene");
	strcpy(sLocked, "låst");
	strcpy(sLogo, "logo");
	strcpy(sLong, "Lang");
	strcpy(sLongerexecutiontime, "Lengre kjøretid");
	strcpy(sLungime, "Bredde");
	strcpy(sLungimeanumar0, "Lengden skal være større enn 0!");
	strcpy(sLungimeanumarreal, "Lengden skal være et reelt tall!");
	strcpy(sLungimeaTotalaFolosita, "Totalt benyttet lengde");
	strcpy(sMagnification, "Forstørrelse");
	strcpy(sMagnify, "Magnify");
	strcpy(sMargins, "Marginer");
	strcpy(sMarginsForPaper, "Marginer for papir");
	strcpy(sMarginsOfTheLabel, "Margene etiketten");
	strcpy(sMaterial, "Materia");
	strcpy(sMaterialName, "Navn på materiale");
	strcpy(sMaterials, "materialer");
	strcpy(sMaterialstypes, "Materialer typer");
	strcpy(sMax, "Max");
	strcpy(sMaximalArea, "Maximal område");
	strcpy(sMaximalCutLength, "Maksimal kutt lengde");
	strcpy(sMaxlength, "Maksimal lengde");
	strcpy(sMaxPiecesperBar, "Maks Deler pr Bar");
	strcpy(sMaxwidth, "Maksimal bredde.");
	strcpy(sMeasurementUnit, "Måleenhet");
	strcpy(sMin, "min");
	strcpy(sMinimalBreakSize, "Minimal ruptur størrelse");
	strcpy(sMinimalUsefulSize, "Minimal nyttig størrelse");
	strcpy(sMinimalwastesizetoInventory, "Minimal avfall størrelse til varelager");
	strcpy(s_What_to_minimize, "Hva skal man minimere?");
	strcpy(sMinlength, "Minimal lengde");
	strcpy(sMinwidth, "Minimal bredde");
	strcpy(sMirror, "Mirror");
	strcpy(sMirroring, "Speiling");
	strcpy(sMiscellaneous, "Diverse");
	strcpy(sModify, "Endre");
	strcpy(sModifytheselectedpiece, "Endre valgte stykket");
	strcpy(sMovePiece, "Flytt stykke.");
	strcpy(sMultiplestages, "Flere stadier");
	strcpy(sName, "Navn");
	strcpy(sNameofedgeband, "Navn på edge band");
	strcpy(sNewDEMANDUnsaveddatawillbelost, "Nye deler? Ulagrede data vil gå tapt!");
	strcpy(sNewLanguage, "Nytt språk");
	strcpy(sNewMaterial, "New Materia");
	strcpy(sNewPasswordincorectlyintroduced, "Nytt passord feil introdusert!");
	strcpy(sNewProduct, "Nytt produkt");
	strcpy(sNewversion, "Ny verson");
	strcpy(sNo, "Ingen");
	strcpy(sNumarBucati, "Antall brikker");
	strcpy(sNumberOfCopies, "Antall eksemplarer");
	strcpy(sNumberofstages, "Antall etapper");
	strcpy(sNusuficienteplacidepozit, "Ikke alle brikker har blitt optimalisert. Mulige årsaker: Det er ikke nok brikker i beholdningen), Piece er ikke benyttet i optimalisering), Typer bitene fra Etterspørsel og skogkartlegging er ingen samsvar), Andre parametere er feil innstilt. Hvis du ikke finner årsaken til at du kan sende oss en rapport ved å gå til menyen Hjelp | Service | Lagre alt. Vennligst send oss ??via e-post, den genererte filen.");
	strcpy(sOfficeNotInstaled, "Microsoft Office er ikke installert på datamaskinen eller en incorect versjonen installeres!");
	strcpy(sOldpassworddoesnotmatch, "Gammelt passord samsvarer ikke!");
	strcpy(sOnlinehelp, "Online hjelp");
	strcpy(sOnlypiecesofthesameheightinthelaststage, "Brikker av samme høyde i den siste fasen.");
	strcpy(sOpen, "Åpent");
	strcpy(sOptimization, "Optimalisering");
	strcpy(sOptimizationDone, "Optimalisering utført! Du kan skrive ut eller lagre de innhentede diagrammene. Trykk på knappen Godta hvis du er fornøyd med dagens løsning. Ellers trykk Start igjen.");
	strcpy(sOptimizationType, "Typen optimalisering");
	strcpy(sOptions, "alternativer");
	strcpy(sOptionsrelatedtotheinterface, "Alternativer relatert til grensesnittet");
	strcpy(sor, "eller");
	strcpy(sOthercomponents, "Andre komponenter");
	strcpy(sOthers, "Andre");
	strcpy(sOtherstatistics, "Annen statistikk");
	strcpy(sOverrideExcelCSVfiles, "Overstyre Excel / CSV-filer");
	strcpy(sParameter, "Parameter");
	strcpy(sParts, "DELER");
	strcpy(sPattern, "Mønster");
	strcpy(sPatternforwaste, "Mønster for avfal");
	strcpy(sPerimeter, "Perimeter");
	strcpy(sPermitedRotationAngle, "Den tillatte dreievinkel.");
	strcpy(sPhone, "Telefon");
	strcpy(sPicture, "Bilde");
	strcpy(sPiece, "Piece");
	strcpy(sPieceindex, "Piece-indeksen");
	strcpy(sPieces, "Deler");
	strcpy(sPiecesize, "Piece størrelse");
	strcpy(sPiecesizelabeledgebandwillbeprinted, "Piece størrelse, etikett, vil edge band skal skrives ut.");
	strcpy(sPierdere, "Avfal");
	strcpy(sPixels, "piksler");
	strcpy(sPlacilefolositeDepozit, "Utnyttet brikkene fra Inventory.");
	strcpy(sPlease_contact_us_at_contact_nestingtechnologies_com, "Ta kontakt med oss på contact@nesting-technologies.com");
	strcpy(sPlease_contact_us_at_contact_optimalprograms_com, "Ta kontakt med oss på contact@optimalprograms.com");
	strcpy(sPleaseenteralldataeitherasfractionalorrealDonotmixthem, "Vennligst skriv inn alle data enten som brøk eller ekte Ikke bland dem!");
	strcpy(sPleaseEnterSomeTypesOfMaterials, "Det er ingen type materiale definert. Du kan definere dem fra Materials menyen.");
	strcpy(sPleasesendtheNameandtheCodetotheaddresscontactoptimalprogramscominordertoobtaintheRegistrationKey, "For å få registreringsnøkkelen du sende navn og koden til: contact@optimalprograms.com.");
	strcpy(sPolygon, "Polygon");
	strcpy(sPolygonsCircles, "Polygoner, sirkler");
	strcpy(sPrecision, "Presisjon");
	strcpy(sPretulnumar0, "Prisen må være større enn 0!");
	strcpy(sPretulnumarreal, "Prisen må være et reelt tall!");
	strcpy(sPreview, "Forhåndsvisning");
	strcpy(sPrice, "Pris");
	strcpy(sPriceMustBeGreaterThanZero, "Prisen må være større enn nul");
	strcpy(sPriceofbars, "Prisen på barer");
	strcpy(sPriceperbar, "Pris pr bar");
	strcpy(sPricepersheet, "Pris per ark");
	strcpy(sPricepersquareunitofmaterial, "Pris per kvadratmeter enhet av materiale.");
	strcpy(sPriceperunit, "Pris per enhet");
	strcpy(sPriceperunit, "Prisen per enhet");
	strcpy(sPrint, "Skriv ut");
	strcpy(sPrintdiagramsastables, "Skriv diagrammene i form av tabeller.");
	strcpy(sPrinter, "Skriver");
	strcpy(sPrinterBounds, "Marginene for skriveren");
	strcpy(sPrintonlyutilizedarea, "Skriv kun benyttes området");
	strcpy(sPrintthecontentsoftheDemand, "Skriv ut innholdet av etterspørselen.");
	strcpy(sPrintthecontentsoftheInventory, "Skriv ut innholdet i lager.");
	strcpy(sPrintthecurrentsolution, "Skrive ut gjeldende løsning.");
	strcpy(sPriority, "Prioritet");
	strcpy(sPrioritytocutapieceZero0isthehighestpriority, "Prioritet å klippe et stykke. Null (0) er den høyeste prioritet.");
	strcpy(sProcentul0100, "De prosentene må være større enn 0 og mindre eller lik 100!");
	strcpy(sProcentulnumarreal, "De prosentene må være et reelt tall!");
	strcpy(sProductdefinition, "Produkt definisjon");
	strcpy(sProductExists, "Produktet finnes allerede. Velg et annet navn.");
	strcpy(sProductName, "Produktnavn");
	strcpy(sProducts, "Produkt");
	strcpy(sProducts, "Produkter");
	strcpy(sProject, "Prosjekt");
	strcpy(sProperties, "egenskaper");
	strcpy(sProperty, "eiendom");
	strcpy(sQuantity, "Antal");
	strcpy(sQuantitynumberofsheetsofthistype, "Antall ark av denne typen");
	strcpy(sRadius, "Radius");
	strcpy(sRectangular, "Rektange");
	strcpy(sRedefinetypesofedgeband, "Omdefiner typer kanten bandet");
	strcpy(sRedefinetypesofmaterial, "Omdefiner typer materiale");
	strcpy(sRegistration, "Registrering");
	strcpy(sRegistrationKeyfromOptimalPrograms, "Registrering Nøkke");
	strcpy(sRegistrationSuccessful, "Registrering vellykket!");
	strcpy(sRemoveallpiecesinInventory, "Fjern alle brikkene i Inventory.");
	strcpy(sRemoveCut, "Slett kutte");
	strcpy(sRemovetheselectedpiece, "Fjern den valgte stykket");
	strcpy(sReports, "Rapporter");
	strcpy(sRequestedMaterial, "Ønsket Materia");
	strcpy(sRestore, "Gjenopprett");
	strcpy(sResults, "Resultater");
	strcpy(sReusedwaste, "Gjenbrukt avfal");
	strcpy(sRight, "Høyre");
	strcpy(sRightcoordinateofthedefect, "Koordinater til feilen fra høyre");
	strcpy(sRotation, "Rotasjon");
	strcpy(sRotationAngle, "Rotasjon vinke");
	strcpy(sRotationStep, "Rotasjon trinn");
	strcpy(sRoundAllFractionsTo, "De brøkverdier må avrundes til");
	strcpy(sRow, "rad");
	strcpy(sRows, "Rader");
	strcpy(sRun, "Nyeste løsningene");
	strcpy(sRunningtime, "driftstid");
	strcpy(sSameforall, "Samme for alle");
	strcpy(sSave, "Lagre");
	strcpy(sSaveAllImages, "Lagre alle bildene");
	strcpy(sSaveAs, "Lagre som");
	strcpy(sSaveChanges, "Etterspørselen har blitt endret. Vil du spare?");
	strcpy(sSaveCurrentImage, "Lagre gjeldende bilde");
	strcpy(sSavedataparameters, "Lagre data og parametere");
	strcpy(sSaveEverything, "Lagre alt");
	strcpy(sSaveInventory, "Lagre Varelager");
	strcpy(sSaveInventoryandDemand, "Lagre Inventar og etterspørse");
	strcpy(sSaveResults, "Lagre Resultater");
	strcpy(sSaveStatisticsinafile, "Lagre statistikk i en fi");
	strcpy(sSavethecurrentimage, "Lagre gjeldende bilde");
	strcpy(sSavethecurrentimageorstatistic, "Lagre gjeldende bilde eller statistikk");
	strcpy(sSavetheDEMANDinafile, "Lagre til fi");
	strcpy(sSavetheDemandinafilewithadifferentname, "Lagre Etterspørselen i en fil med et annet navn.");
	strcpy(sSavetheREPOSITORYinafile, "Lagre depotet i en fi");
	strcpy(sSerialNumber, "Registreringsnøkkelen");
	strcpy(sService, "tjeneste");
	strcpy(sSetDefaultValues, "Dette vil gjenopprette alle parametere til standardverdiene. Alle dine innstillinger vil gå tapt. Er du sikker på at du vil gjøre dette?");
	strcpy(sSetedgeband, "Sett kanten bandet");
	strcpy(sSetedgetrim, "Still cutting for defekter kanter");
	strcpy(sSetthesameedgebandforalledges, "Sett samme kanten bandet for alle kanter");
	strcpy(sSetthesamegrindingforalledges, "Still inn samme sliping for alle kanter.");
	strcpy(sSetthesametrimforalledges, "Still samme skjæring for feil for alle kanter");
	strcpy(sSettings, "Innstillinger");
	strcpy(sShape, "Form");
	strcpy(sSheet, "Ark");
	strcpy(sSheetsBarstypes, "Ark_rør typer");
	strcpy(sSheetSize, "Størrelse på ark");
	strcpy(sSheetsperPage, "Ark per side");
	strcpy(sShort, "Short");
	strcpy(sShorterexecutiontime, "Kort kjøretid");
	strcpy(sShowallsimpleproducts, "Vis alle enkle produkter");
	strcpy(sShowcustomername, "Vis kundenavn");
	strcpy(sShowCustomTextOnEachPiece, "Vis egendefinert tekst på hver brikke");
	strcpy(sShowdiagramasatable, "Vis diagram som en tabell.");
	strcpy(sShowedgeband, "Vis edge band");
	strcpy(sShowedgebandssettinginanewwindow, "Vis innstillingene for edge bandene i et nytt vindu.");
	strcpy(sShowgrindingsettingsinanewwindow, "Viser sliping innstillinger i et nytt vindu.");
	strcpy(sShowHorizontalLabelsAlways, "Vis alltid horisontale etiketter");
	strcpy(sShowRemovethesizeofthepiecesinthecurrentsolution, "Vis / fjern størrelsen på bitene i dagens løsning.");
	strcpy(sShowRemovethesizeofthewastesinthecurrentsolution, "Vis / fjern størrelsen på avfall i dagens løsning.");
	strcpy(sShowtotalcutlength, "Vis total skjærelengde");
	strcpy(sShowtrimedgesettingsinanewwindow, "Vis innstillingene for defekter i et nytt vindu.");
	strcpy(sSimpleMaterialExists, "Navn på materiale er allerede definert i listen over materialer. Vennligst gi den et nytt navn.");
	strcpy(sSinglePieceStrips, "Striper av ett stykke.");
	strcpy(sSizes, "Størrelser");
	strcpy(sSmallerorequalto, "Mindre eller lik");
	strcpy(sSort, "Sortere");
	strcpy(sSortAscendingByArea, "Sorter stigende etter område");
	strcpy(sSortDescendingByArea, "Sorter synkende etter område");
	strcpy(sSpecifyhowdifferentthepiecesinthelaststagecanbeValue0meansnodifference, "Angi hvordan ulike kan være brikker i siste stadium. Verdi 0 betyr ingen forskjell.,");
	strcpy(sSpecifyifpiecesinthelaststagecanbedifferentornotdepeultimaetapapotfidiferitesaunucadimensiune, "Spesifiser om brikker i den siste fasen kan være forskjellig eller ikke");
	strcpy(sSpecifyifthepiececanberotatedornotIfnotitwillbecutinthesamewayasitwasintroducedinDemandLengthofthepieceparalleltothelengthofthesheet, "Angi om stykket kan roteres eller ikke. Hvis ikke, vil det bli kuttet på samme måte som det ble innført i etterspørselen (lengden av stykket parallelt med lengden på arket),");
	strcpy(sSpecifyinhowmanystageswemakethecutsDuringastageallcutshavethesamedirection, "Angi i hvor mange etapper vi gjør kuttene.");
	strcpy(sStartthesearchprocess, "Start søkeprosessen");
	strcpy(sStatistics, "Statistikk");
	strcpy(sStatisticsE, "Rapporter Ekstra");
	strcpy(sStatisticsforeachtypeofmaterial, "Statistikk for hver type materiale");
	strcpy(sStep, "Trinn");
	strcpy(sStergeDepozit, "Du ønsker å slette Inventory?");
	strcpy(sStergeMaterial, "Slette materiale?");
	strcpy(sStergePiesele, "Du ønsker å slette stykket?");
	strcpy(sStergePiesa, "Du ønsker å slette stykket?");
	strcpy(sStopthesearchprocess, "Stopp søkeprosessen");
	strcpy(sStrongoptimization, "Sterk optimalisering");
	strcpy(sSubtractthebandthicknessfrompiecesize, "Reduser stykke størrelse med band tykkelse.");
	strcpy(sSummary, "Oppsummering");
	strcpy(sSuprafataTotalaFolosita, "Totalt brukte overflate");
	strcpy(sSuprafatautilizata, "Utnyttelse");
	strcpy(sSwitchbetweenfiberandrotationoption, "Bytt mellom fiber og rotasjon alternativet.");
	strcpy(sTechnical, "Teknisk");
	strcpy(sTechnicalsettings, "Tekniske innstillinger");
	strcpy(sTemporaryPanelHint, "Midlertidig panel for bevegelige deler mellom ark.");
	strcpy(sText, "Tekst");
	strcpy(sThe_application_has_expired, "Programmet er utløpt.");
	strcpy(sThe_application_is_not_registered, "Programvaren er ikke registrert.");
	strcpy(sThe_application_was_first_started_on, "Programvaren ble først startet på.");
	strcpy(sThecutsareperformedfromasidetotheothersideofthematerial, "Den belastning utføres fra en side til den andre siden av materialet.");
	strcpy(sThecuttingmachinecanfollowtheshapeofthematerial, "Den cutting maskin kan følge formen på stykket.");
	strcpy(sTheedgesofsheetsthatmustbetrimedduefaults, "Kantene på ark som må trimmes på grunn av fei");
	strcpy(sTheLargestSize, "Den største størrelsen");
	strcpy(sThenameofthecustomerforwhichyoucutthepiece, "Navnet på kunden som skjære deg stykket.");
	strcpy(sThenameofyourcustomer, "Navnet på dine kunder");
	strcpy(sThepiececanberotated, "Stykket kan roteres");
	strcpy(sTheprogramtriestoavoidwasteswhichhavebothsizeslessthanthisvalue, "Programmet forsøker å unngå avfall som har begge størrelser mindre enn denne verdien");
	strcpy(sThereAreNoProducts, "Det er ingen definerte produkter ennå");
	strcpy(sThestockofmaterialhasbeenpreviouslyloadedfromanExcelorCSVformatPleaseloaditagain, "Bestanden av materialet tidligere er lastet inn fra et Excel-eller CSV-format. Vennligst legg det inn igjen hvis du ønsker å arbeide med den.");
	strcpy(sThetotallengthofcutting, "Den totale lengden for å kutte");
	strcpy(sThewidthofthecuttingsawForglasscuttingoptimizationitcanbe0Forwooditshouldbegreaterthan0, "Tykkelsen på sagen. For glass skjæring kan det være 0. For tre bør det være større enn 0.");
	strcpy(sThewidthofthecuttingsawforlinearpieces, "Tykkelsen på sagen for lineære stykker.");
	strcpy(sThickness, "Tykkelse");
	strcpy(sThischaracterisusedforfillingthewasterectanglesIfyoudonotwantfilledwastejustremovethischaracter, "Dette symbolet brukes til å fylle avfall rektangler. Hvis du ikke vil fylles avfall bare fjerne den.");
	strcpy(sThisindexhasvaluebetween1andthenumberofpieces, "Denne indeksen har verdi mellom 1 og antall brikker.");
	strcpy(sThisOptionWillOverrideTheInventoryFileIfLoadedFromExcelOrCsvFiles, "Dette alternativet vil overstyre inventar filen hvis lastet fra Excel eller CSV-filer.");
	strcpy(sThisProgramisLicensedTo, "Dette programmet er lisensiert ti");
	strcpy(sThisvaluewillbeaddedtotheedgebandingmaterialoneachside, "Denne verdien vil bli lagt til Kantbåndmaskiner materiale på hver side");
	strcpy(sTipNevid, "Den type materiale kan ikke være tom.");
	strcpy(sTitle, "Titte");
	strcpy(sTools, "Verktøy");
	strcpy(sTop, "Topp");
	strcpy(sTopcoordinateofthedefect, "Toppen koordinat av mangelen.");
	strcpy(sTotalGarbageWaste, "Alt kassert avfall");
	strcpy(sTotalInventoryWaste, "Totalt lager avfall");
	strcpy(sTotalRecycledWaste, "All resirkulert avfall");
	strcpy(sTotalusedarea, "Totalt brukte område");
	strcpy(sTotalusedlength, "Totalt brukte lengde");
	strcpy(sTrigonometric, "Trigonometriske");
	strcpy(sTrim, "Trim");
	strcpy(sTrimalledgesatthebeginning, "Trim alle kantene på begynnelsen");
	strcpy(sTrimEdge, "Trim kanten");
	strcpy(sTwoPanels, "2 paneler");
	strcpy(sType, "Type");
	strcpy(sTypeofmaterialfromwhichtocut, "Type materiale som å kutte");
	strcpy(sTypesAreNotMatched, "Optimalisering ble ikke utført! Deler vil bli kuttet fra ark fra Lagerbeholdning har samme type materiale. Foreløpig, i lager, er det ingen slike materiale! Endre noen materialer fra tilsvarende kolonnen!");
	strcpy(sUndo, "Angre");
	strcpy(sUndoAccept, "Angre Godta");
	strcpy(sUnits, "enheter");
	strcpy(sUnregisteredVersion, "Uregistrerte");
	strcpy(sUpdates, "Oppdateringer");
	strcpy(sUsefulforwoodfurniture, "Nyttig for tre møbler");
	strcpy(sUseit, "Bruk den");
	strcpy(sUsePieceinOptimization, "Bruk brikke i optimalisering");
	strcpy(sUserName, "Brukernavn");
	strcpy(sUtilizationandWastes, "Utnyttelse og avfal");
	strcpy(sUtilizedArea, "Areal av benyttede deler");
	strcpy(sUtilizedBars, "Benyttede barer");
	strcpy(sUtilizeddemandcount, "Antall utnyttet stykker.");
	strcpy(sUtilizedParts, "Benyttede deler");
	strcpy(sUtilizedPieces, "Utnyttet stykker");
	strcpy(sUtilizedSheets, "Benyttede ark");
	strcpy(sValue, "Verdi");
	strcpy(sValueGreaterEqualToZero, "Verdien må være større eller lik nul");
	strcpy(sValueGreaterThanZero, "Verdien må være større enn nul");
	strcpy(sValueIntegerNumber, "Verdien må være et heltall!");
	strcpy(sValueRealNumber, "Verdien må være et reelt tall. Kanskje du har brukt, i stedet for. eller viceversa. Fiks det!");
	strcpy(s_The_number_is_too_big_or_it_has_too_many_digits_after_decimal_separator, "Tallet er for stort, eller det har for mange sifre etter desimal separator!");
	strcpy(s_The_number_is_too_big, "Antallet er for stort!");
	strcpy(sVertical, "Vertika");
	strcpy(sWaste, "Avfal");
	strcpy(sWastes, "Avfal");
	strcpy(sWasteAddedToWarehouse, "Skrap lagt til lageret");
	strcpy(sWastelimits, "grenser for avfal");
	strcpy(sWasteType, "Type avfal");
	strcpy(sWeakoptimization, "Den svakeste optimalisering");
	strcpy(sWhattoprint, "Hva skal jeg skrive");
	strcpy(s_What_to_print_or_save_to_file, "Hva du skal skrive ut eller lagre i fil");
	strcpy(sWhattoprintoneachpiece, "Hva å skrive ut på hver brikke");
	strcpy(sWhattoshowoneachpiece, "Hva som skal vises på hver brikke?");
	strcpy(sWidth, "Bredde");
	strcpy(sWood, "tre");
	strcpy(sWorkingDirectory, "Arbeide katalogen");
	strcpy(sWrongKey, "Feil Registrering Nøkkel!");
	strcpy(sYes, "Ja");
	strcpy(sYoucannotchooseblackblueorredcolors, "You cannot choose black, blue or red colors.");
	strcpy(sYouCannotMixFractionalDataWithDecimalOnes, "Du kan ikke blande brøkverdier med reelle verdier!");
	strcpy(sYourcompany, "Din bedrift");
	strcpy(sZip, "Postnummer");
	strcpy(s_Set_the_origin_and_the_direction_of_the_axes, "Angi opprinnelsen og retningen til koordinatene.");

}
