// Language strings: Chinese traditional
// Author: Optimal Programs
// License: MIT License
//---------------------------------------------------------------------------
#include <string.h>
//---------------------------------------------------------------------------
#include "language_string_id.h"
//---------------------------------------------------------------------------
void set_cn_t(void)
{
	// Chinese traditional
	// checked manually by a customer on 2023.1.17
	// last update on: 2025.11.01.0
	
	strcpy(s_Area, "面積");
	strcpy(s_Mass, "質量");
	strcpy(s_Advanced, "先進的");
	strcpy(s_Relative_coordinates, "相對座標");
	strcpy(s_Absolute_coordinates, "絕對座標");
	strcpy(s_Append_more_rows, "追加更多行");

	strcpy(s_Add_to_parts, "添加零件");
	strcpy(s_Additional, "額外的");
	strcpy(s_All_results, "所有結果。");
	strcpy(s_Allow_movement_of_pieces, "允許移動零件");
	strcpy(s_Allow_part_in_part, "允許零件置於另一塊內");
	strcpy(s_Invalid_piece_Angles_are_too_small_or_too_big_or_height_is_too_small, "無效片！角度太小或太大，或高度太小。");
	strcpy(s_Append, "附加");
	strcpy(s_As_it_is, "依照原樣");
	strcpy(s_As_text, "作為文本");
	strcpy(s_Ascending, "遞進");
	strcpy(s_Automatic, "自動");
	strcpy(s_Cannot_connect_to_the_Internet_Please_visit_our_website_from_a_browser, "無法連接到互聯網！ 請通過瀏覽器訪問我們的網站。");
	strcpy(s_Cannot_copy_or_move_the_files, "無法複製或移動檔案！");
	strcpy(s_Cannot_delete_the_file, "無法刪除檔案！");
	strcpy(s_Cannot_modify_old_results, "無法修改舊結果！");
	strcpy(s_To_change_click_inside_a_cell_or_press_0_1_or_2, "要進行更改，點擊方格內部或按0、1或2。");
	strcpy(s_Cell, "細胞");
	strcpy(s_Click_on_the_table_header_to_change_the_columns, "單擊表標題可更改列。");
	strcpy(s_Close, "關閉");
	strcpy(s_Contact_us, "聯繫我們");
	strcpy(s_Column, "列");
	strcpy(s_Comma, "逗號");
	strcpy(s_The_comma_symbol_cannot_simultaneously_be_the_list_separator_and_the_decimal_separator, "逗號符號不能同時作為列表分隔符號和小數點分隔符號！");
	strcpy(s_Copy, "複製");
	strcpy(s_Copy_for_move, "複製並移動");
	strcpy(s_Cut_higher_level_strips_first, "先切割較高等級的條帶");
	strcpy(s_Cut_index, "切割係數");
	strcpy(s_Cuts_may_overlap, "切割可能重疊");
	strcpy(s_The_data_have_been_changed_Do_you_want_to_save_them_to_a_file, "數據已更改。 您要將它們儲存到檔案中嗎？");
	strcpy(s_Decimal_separator, "小數分隔符");
	strcpy(s_Restore_default_settings, "恢復預設設定");
	strcpy(s_Delete_fiber, "刪除條子");
	strcpy(s_Descending, "遞減");
	strcpy(s_Discard_changes, "放棄更改");

	strcpy(s_Delete_all_data, "刪除所有資料？");
	strcpy(s_Dot, "點");
	strcpy(s_Do_you_want_to_delete_the_picture, "您要刪除圖片嗎？");
	strcpy(s_Do_you_want_to_delete_the_product, "您要刪除產品嗎？");
	strcpy(s_Duplicate_and_append, "複製並附加");
	strcpy(s_Duplicate_values_are_ignored, "重複的數值將被忽略！");
	strcpy(s_Error, "錯誤");
	strcpy(s_Error_loading_file, "載入檔案時發生錯誤");
	strcpy(s_export_everything, "匯出所有內容");
	strcpy(s_Fit_to_screen, "調整為螢幕大小");
	strcpy(s_Force_fixed_height, "繪製具有固定高度的碎片。");
	strcpy(s_Flipped, "翻轉");
	strcpy(s_Import, "輸入");
	strcpy(s_If_angles_are_different_from_90_degrees_height_must_be_greater_than_0, "如果角度不是 90 度，則高度必須大於 0。");
	strcpy(s_Ignore, "忽略");
	strcpy(s_Incorrect_value, "數值不正確");
	strcpy(s_Info, "資訊");
	strcpy(s_Interior, "內部");
	strcpy(s_Give_a_name, "命名");
	strcpy(s_Group, "組合");
	strcpy(s_Header, "標頭");
	strcpy(s_Keep_it_as_it_is, "保持原樣");
	strcpy(s_Level, "層級");
	strcpy(s_Licensee, "許可證持有人");
	strcpy(s_List_separator, "列表分隔符");
	strcpy(s_Made_with_love_in_Cugir_Romania, "用愛製造，產地：羅馬尼亞庫吉爾");
	strcpy(s_Made_in, "製造於");
	strcpy(s_Manufacturer, "製造商");
	strcpy(s_Maximum_distance_between_2_linked_segments, "2 個連接線段之間的最大距離");
	strcpy(s_Manual_arrange, "手動安排");
	strcpy(s_Mix_layers, "考慮來自所有圖層的物件");
	strcpy(s_Mixed, "混合的");
	strcpy(s_Multiple_shapes_detected_Next_rows_will_be_overwritten_Continue, "檢測到不止一個形狀. 後續行將被覆蓋，繼續？");
	strcpy(s_More, "更多的");
	strcpy(s_Multiple_values, "多個值");
	strcpy(s_No_texture, "無紋理");
	strcpy(s_Number, "數");
	strcpy(s_Number_of_images, "圖片數量");
	strcpy(s_Number_of_vertices, "頂點數量");
	strcpy(s_Offset, "抵消");
	strcpy(s_Only_the_currently_selected_items, "僅當前選擇的項目。");
	strcpy(s_Optimizing_please_wait, "優化中... 請稍候。");

	strcpy(s_Paste, "貼上");
	strcpy(s_Paste_from_Clipboard, "從剪貼簿貼上");
	strcpy(s_Piece_label, "零件標籤");
	strcpy(s_Piece_size, "零件大小");
	strcpy(s_Please_contact_us_by_email_if_you_receive_this_error, "如果收到此錯誤，請通過電子郵件與我們聯繫。");
	strcpy(s_Please_save_it_first, "請先保存");
	strcpy(s_Position, "位置");
	strcpy(s_Preview, "預覽");
	strcpy(s_Rectangle, "長方形");
	strcpy(s_Resolution, "解析度");
	strcpy(s_Redo_the_last_operation, "恢復上一個操作");
	strcpy(s_Regular_polygon, "正多邊形");
	strcpy(s_Relative, "相對的");
	strcpy(s_Reused, "重複使用");
	strcpy(s_Rotated, "旋轉");
	strcpy(s_Save_all, "保存全部");
	strcpy(s_Scrap_label, "廢料標籤");
	strcpy(s_Scrap_size, "廢料大小");
	strcpy(s_Semicolon, "分號");
	strcpy(s_Show_cut_index, "顯示切割指數");
	strcpy(s_Show_information, "顯示資訊");
	strcpy(s_Show_piece_label, "顯示零件的標籤");
	strcpy(s_Show_scrap_label, "顯示廢料的標籤");
	strcpy(s_Show_scrap_s_size_on_the_small_pieces, "在小零件上顯示廢料大小");
	strcpy(s_Show_size_of_pieces, "顯示零件的尺寸");
	strcpy(s_Show_size_of_scrap, "顯示廢料的尺寸");
	strcpy(s_Show_sizes, "顯示尺碼");
	strcpy(s_Show_label, "顯示標籤");
	strcpy(s_Show_length, "顯示長度");

	strcpy(s_Some_numerical_values_are_incorrect_Should_I_fix_all_the_incorrect_values, "一些數值不正確！ 是否修正所有不正確的數值？");
	strcpy(s_Some_invalid_values_have_been_removed, "一些無效值已被刪除。");
	strcpy(s_Sort_by, "排序方式");
	strcpy(s_Sort_ascending_by, "遞進排列");
	strcpy(s_Sort_descending_by, "遞減排列");
	strcpy(s_Start, "開始排板");
	strcpy(s_Starting_angle, "起始角度");
	strcpy(s_Starting_corner, "起始點");
	strcpy(s_Starting_direction, "起始方向");
	strcpy(s_Sticker, "貼紙");
	
	strcpy(s_Stock, "庫存");
	strcpy(s_Stop, "停止");
	strcpy(s_System_setting, "系統設定");
	strcpy(s_Tabular, "表格式的");
	strcpy(s_Total, "總數");
	strcpy(s_Total_size, "總尺寸");
	strcpy(s_Terms_of_the_license, "許可條款");
	strcpy(s_The_current_product_has_been_changed_Do_you_want_to_save_it_to_file, "當前產品已更改。 您要儲存到檔案嗎？");
	strcpy(s_The_value_is_out_of_the_allowed_range, "該值超出了允許的範圍。");
	strcpy(s_The_value_must_be_a_real_or_fractional_number_Try_to_replace_the_comma_with_the_dot_if_you_want_to_enter_a_real_number, "該值必須是實數或小數。 如果要輸入實數，請嘗試用點替換逗號。");
	strcpy(s_This_feature_is_not_implemented_yet, "此功能尚未實現。");
	strcpy(s_This_operation_cannot_be_reversed, "此操作不能取消。");
	strcpy(s_Undo_the_last_operation, "恢復上一個操作。");
	strcpy(s_Utilization, "利用率");
	strcpy(s_Utilized_Stock, "已用庫存");
	strcpy(s_Version, "版本");
	strcpy(s_Visible_columns, "可見列");
	strcpy(s_You_already_have_the_latest_version_installed, "您已經安裝了最新版本！");
	strcpy(s_What_is_exported, "出口什麼？");
	strcpy(s0meansanynumberofpieces, "零件表示任意數量");
	strcpy(sAbout, "關於");
	strcpy(sAccept, "確認");
	strcpy(sAcceptall, "全部確認");
	strcpy(sAcceptthecurrentsolution, "確認當前的解決方案");
	strcpy(sAdd, "附加");
	strcpy(sAddapiece, "加入零件");
	strcpy(sAddasimpleproducttoDemand, "添加產品到現有零件");
	strcpy(sAddgrindingthicknesstopartsize, "將磨削厚度增加到零件尺寸");
	strcpy(sAddproductnametolabel, "將產品名稱附加到標籤上");
	strcpy(sAddress, "位址");
	strcpy(sAddselectedsizetoInventory, "將選定的尺寸添加到庫存中");
	strcpy(sAdhesivelabels, "黏貼標籤");
	strcpy(sAdhesivelabelwithinformationaboutpiecesinDemandCustomernameLabelSizeCurrentData, "帶有零件資訊的黏貼標籤：客戶名稱，標籤，尺寸，當前數據等。");
	strcpy(sAdhesivelabelwithinformationaboutsheetsinInventory, "帶有庫存板材信息的標籤");
	strcpy(sAll, "所有");
	strcpy(sAlloffcutswhichhavethesizegreaterthanthisvaluewillbeaddedtoInventory, "所有大於此值的廢料將添加到庫存中");
	strcpy(sAllowMirroring, "允許翻轉");
	strcpy(sAllowRotation, "允許旋轉");
	strcpy(sAllPieces, "所有零件");
	strcpy(sAllpredefinedproducts, "所有預先定義的產品");
	strcpy(sAnewwindowwillbedisplayedwheretheusercansettheedgebandsforeachedge, "將顯示一個新視窗，用戶可以在其中設置零件每側的封邊帶。");
	strcpy(sAnewwindowwillbedisplayedwheretheusercansetthegrindingvalueforeachedgeofthsheet, "將顯示一個新視窗，用戶可以在其中設置零件每側的磨削尺寸。");
	strcpy(sAnewwindowwillbedisplayedwheretheusercansetthetrimvalueforeachedgeofthsheet, "將顯示一個新視窗，用戶可以在其中設置的每一面的修剪值。");
	strcpy(sAngle, "角度");
	strcpy(sAngles, "角度");
	strcpy(sAnoptimizationparameterisarealnumber, "優化參數是實數。");
	strcpy(sAnoptimizationparameterisfractionalnumber, "優化參數是小數。");
	strcpy(sAnyShape, "真實形狀");
	strcpy(sApolygonmusthaveatleast2vertices, "多邊形必須至少有2個頂點！");
	strcpy(sApolygonmusthaveatleast3vertices, "多邊形必須至少具有3個頂點！");
	strcpy(sApplication_fails_to_initialize, "應用程式初始化失敗！");
	strcpy(sArc, "弧");
	strcpy(sArcLength, "弧長");
	strcpy(sAreaofusedsheets, "使用板材的面積");
	strcpy(sAshortdescriptionofthesheet, "板材簡介");
	strcpy(sAtleastonepart, "您必須至少輸入一個零件");
	strcpy(sAtTheMarginOfTheSheet, "在板材的邊緣");
	strcpy(sBandtypes, "封邊帶類型");
	strcpy(sBar, "條形材");
	strcpy(sBars, "條形材");
	strcpy(sBothsizesoftheoffcutsmustbegreaterthanthisvalue, "兩種廢料尺寸都必須大於此值。");
	strcpy(sBottom, "下");
	strcpy(sBottomcoordinateofthedefect, "缺陷的底座標");
	strcpy(sBreakCut, "中斷切割");
	strcpy(sBrowse, "流覽");
	strcpy(sBuy, "購買");
	strcpy(sBuynow, "立即購買 ...");
	strcpy(sCancel, "取消");
	strcpy(sCannotBeEmpty, "不能為空！");
	strcpy(sCannotmovepartsbetweensheetswhenidenticalsheetsaregroupedPleaseungroupthesheetsfrommenu, "如果將相同的板材組合，則無法將零件從一張板材移動到另一張板材。 請從功能表中取消板材的組合。");
	strcpy(sCannotSaveFile, "無法儲存檔案");
	strcpy(sCenter, "中心");
	strcpy(s_Centering, "置中");
	strcpy(sChangeDirection, "更改切割方向");
	strcpy(sChoose, "選擇");
	strcpy(sChooseProduct, "選擇產品");
	strcpy(sCircle, "圓圈");
	strcpy(sCity, "城市");
	strcpy(sClear, "清除資料");
	strcpy(sClockWise, "順時針");
	strcpy(sClosewindow, "關閉視窗");
	strcpy(sColor, "顏色");
	strcpy(sColorofedgeband, "封邊帶顏色");
	strcpy(sColorPattern, "顏色/圖案");
	strcpy(sColorpiecesandwastes, "有色零件和廢料");
	strcpy(sColumns, "列");
	strcpy(sComment, "評論");
	strcpy(sCompanyname, "公司名稱");
	strcpy(sComplexMaterialExists, "材料名稱已在複合材料清單中定義。 請給它一個新名字。");
	strcpy(sComputerCode, "電腦代碼");
	strcpy(sComputerCodefromyourcomputer, "電腦代碼（來自您的電腦）");
	strcpy(sComputethetotalpriceofDemand, "計算零件總價");
	strcpy(sContents, "內容");
	strcpy(sContinutComanda, "日期內的零件資訊");
	strcpy(sContinutDepozit, "日期內庫存內容");
	strcpy(sConversionIsDoneOnlyWhenSomePiecesHaveFractionalValues, "僅當某些零件具有分數時，才進行轉換。");
	strcpy(sConvertsTheSizeOfWasteToAFractionalUnit, "將廢料的大小顯示為小數值");
	strcpy(sCouldNotSaveFile1, "無法將檔案寫入目錄：");
	strcpy(sCouldNotSaveFile2, "您可能沒有足夠的許可權。 請從選單設定 檢查或更改工作目錄。 工作目錄指定到您有許可權寫入的資料夾（例如c： temp）。");
	strcpy(sCreationdateYMDHMS, "建立日期（年/ 月 / 日- 時：分：秒）");
	strcpy(sCurrentDate, "當前日期");
	strcpy(sCurrentDiagram, "當前圖");
	strcpy(sCurrentMaterial, "當前材料");
	strcpy(sCurrentversion, "當前版本");
	strcpy(sCurve_not_closed_Try_increasing_DXF_linking_distance_parameter, "多邊形未閉合！ 請嘗試增加DXF連結距離參數。");
	strcpy(sCustomer, "客戶");
	strcpy(sCustomerName, "客戶姓名");
	strcpy(sCustomMessage, "自訂資訊");
	strcpy(sCutlength, "切割長度");
	strcpy(sCut, "切割");
	strcpy(sCuts, "切割");
	strcpy(sCutterThickness, "裁切厚度");
	strcpy(sData, "數據");
	strcpy(sDataCannotBeEmpty, "數據不能為空！");
	strcpy(sDateymdhms, "日期（年/月/日/時/分/秒）");
	strcpy(sDays_left_for_trial, "尚待試用天數");
	strcpy(sDaysLeft, "剩餘天數");
	strcpy(sStandard, "標準");
	strcpy(sDefaultInterface, "默認介面");
	strcpy(sDefects, "瑕疵");
	strcpy(sDefectsManager, "管理瑕疵");
	strcpy(sDefectsofthematerialNopiecescanbeplacedinthefaultyzone, "材料有缺陷。 不能將任何物品放置在故障區域中。");
	strcpy(sDelete, "刪除");
	strcpy(sDeletePiece, "刪除零件");
	strcpy(sDeleteRow, "刪除行");
	strcpy(sDemandutilization, "零件利用度");
	strcpy(sDepozitulmodificat, "使用過的部份已被去除。 廢料已添加到庫存中。");
	strcpy(sDepozitvid, "庫存為空");
	strcpy(sDesk, "台");
	strcpy(sDiagram, "圖");
	strcpy(sDiagrams, "圖");
	strcpy(sDiagramasatable, "圖表");
	strcpy(sDigits, "數位");
	strcpy(sDimensiuniplaca, "板材尺寸");
	strcpy(sDirection, "方向");
	strcpy(sDistanceBetweenRows, "行間距離");
	strcpy(sDonotuseit, "不要使用");
	strcpy(sDownload, "下載");
	strcpy(sDoYouWantToClearTheData, "您要刪除資料嗎？");
	strcpy(sDoYouWantToSaveDemand, "零件已更改！ 您要儲存變更嗎？");
	strcpy(sDoYouWantToSaveParts, "您要保存零件嗎？");
	strcpy(sDoYouWantToSaveRepository, "庫存已更改！ 您要儲存變更嗎？");
	strcpy(sDrawing, "圖紙");
	strcpy(sDrawthesolutioncolorful, "彩圖顯示解決方案");
	strcpy(sDuplicateTypes, "某些類型重複！ 請刪除重複項");
	strcpy(sDuplicateTypesWithComplex, "部份材料名稱已經存在於複合類型清單中！ 請刪除重複項");
	strcpy(sDuplicateValues, "重複值");
	strcpy(sEdgeband, "封邊");
	strcpy(sEdgebandingwhichisplacedontheedgesofyourpiecePleasedefineedgebandingtypesfromMaterialsEdgeBandingmenu, "封邊帶已放置在零件的邊緣。 請在材料功能表中定義封邊帶。");
	strcpy(sEdgebandsthatwillbeappliedtoeachpart, "封邊帶（應用於每個零件中）");
	strcpy(sEdgeBandTolerance, "封邊帶公差");
	strcpy(sEdgesthatmustbecutduefaults, "由於缺陷而必須切割的邊緣。");
	strcpy(sEdgetoedge, "從邊到邊");
	strcpy(sEdit, "編輯");
	strcpy(sEmail, "電子郵件");
	strcpy(sEmptyData, "數據為空！");
	strcpy(sEnabled, "已啟用");
	strcpy(sEnabledisabledefectsoftheinventorysheets, "啟用/禁用 庫存缺陷");
	strcpy(sEnterLabel, "輸入標籤");
	strcpy(sEnterTheMaterialName, "輸入材料名稱");
	strcpy(sEnterTheProductName, "輸入產品名稱");
	strcpy(sEvaluationError, "表達式評估錯誤！");
	strcpy(sExit, "離開");
	strcpy(sExpired, "該軟體已過期！ 請註冊軟體！");
	strcpy(sExport, "匯出");
	strcpy(sExportAllDiagrams, "匯出所有圖");
	strcpy(sExportAllToASingleFile, "全部匯出到單個檔");
	strcpy(sExportOptions, "匯出選項");
	strcpy(sExporttoDXFformat, "匯出為DXF格式");
	strcpy(sExporttoExcel, "匯出到Excel");
	strcpy(sExpresieIncorecta, "數學表達式不正確！");
	strcpy(sExtensions, "擴展名");
	strcpy(sExtra, "額外");
	strcpy(sExtraComponents, "額外元件");
	strcpy(sExtracomponentsattachedtoDemand, "額外元件（附加在零件上）");
	strcpy(sFile, "檔");
	strcpy(sFileName, "文件名稱");
	strcpy(sFillWastes, "用斜線表達廢料");
	strcpy(sFindoptimalbarsheetsize, "找出條形材和板材的最佳尺寸。");
	strcpy(sFindoptimalsizeofInventorypieces, "找出庫存件的最佳尺寸");
	strcpy(sFirstcutMultiplestages, "第一切割方向（進行多階段優化時）。");
	strcpy(sFirstdirectionforcutishorizontal, "第一切割方向是水準的。");
	strcpy(sFirstdirectionforcutisvertical, "第一切割方向是垂直的。");
	strcpy(sFollowthecontourofpieces, "跟隨零件的輪廓");
	strcpy(sFont, "字形");
	strcpy(sFontsize, "字體大小");
	strcpy(sFullInfo, "完整的資訊");
	strcpy(sDisposedWaste, "處置廢物");
	strcpy(sGeneral, "一般");
	strcpy(sGenerateCNC, "生成CNC");
	strcpy(sGrain, "紋理");
	strcpy(sGraindirection, "紋理方向");
	strcpy(sGraphic, "圖形化");
	strcpy(sGreaterorequalto, "廢料大於或等於");
	strcpy(sGrid, "表格");
	strcpy(sGrinding, "打磨");
	strcpy(sGrosimeTaieturaScalata, "該圖片的切割厚度可能與真實情況有偏差，因為這些圖片未按其真實比例顯示。 但這不影響結果。");
	strcpy(sGroupidenticallayouts, "組合相同的板材");
	strcpy(sGroupIdenticalParts, "組合相同的零件");
	strcpy(sGroupingOfIdenticalPiecesIntoOneRow, "將相同的零件組合為一行。");
	strcpy(sGroupPartsAfterLoadingFromFile, "從檔載入時對零件進行組合");
	strcpy(sHeight, "高度");
	strcpy(sHeighttolerance, "高度公差");
	strcpy(sHelp, "説明");
	strcpy(sHistory, "記錄");
	strcpy(sHorizontal, "橫");
	strcpy(sHowtodisplayprintedgebands, "封邊帶如何顯示？");
	strcpy(sIfyousetthebandforoneedgeallwillreceivethesamevalue, "如果設置了一個邊線的封邊帶，則所有邊線將改成相同的值。");
	strcpy(sIfyousetthegrindingforoneedgeallwillreceivethesamevalue, "如果設置了一個邊線的磨削值，則所有邊線將改成相同的值。");
	strcpy(sIfyousetthetrimforoneedgeallwillreceivethesamevalue, "如果設置了一個邊線的修剪值，則所有邊線將改成相同的值。");
	strcpy(sImageBounds, "圖像邊界");
	strcpy(sImageSize, "圖片大小");
	strcpy(sImportData, "匯入數據");
	strcpy(sIncorrectPassword, "密碼錯誤");
	strcpy(sIndex, "指數");
	strcpy(sInformationaboutcustomer, "客戶資訊");
	strcpy(sInputALanguageName, "輸入語言名稱");
	strcpy(sInsert, "插入");
	strcpy(sInsertPiece, "插入零件");
	strcpy(sInterface, "介面");
	strcpy(sInterfaceSettings, "介面設定");
	strcpy(sInvalidHardware, "無法檢測到硬體。 請通過 contact@optimalprograms.com 與我們聯繫。");
	strcpy(sInvalidNumber, "無效號碼");
	strcpy(sInvalidOrderOfComputation, "無法處理計算長度的指令。 產品定義中存在迴圈外部參照！");
	strcpy(sInvalidRegistration, "註冊無效！");
	strcpy(sInvalidTime, "您的系統時間無效。");
	strcpy(sInventory, "庫存");
	strcpy(sisafractionalvalue, "是小數值。");
	strcpy(sIsArc, "是弧線");
	strcpy(sisarealvalue, "是實數");
	strcpy(sLabel, "標籤");
	strcpy(sLabels, "標籤");
	strcpy(sLanguage, "語言");
	strcpy(sLatimeanumar0, "寬度必須大於0！");
	strcpy(sLatimeanumarreal, "寬度必須是實數！");
	strcpy(sLayerName, "層次名稱");
	strcpy(sLeft, "左");
	strcpy(sLeftcoordinateofthedefect, "缺陷的左邊座標");
	strcpy(sLength, "長度");
	strcpy(sLengthofthepiecestocut, "裁切零件的尺寸");
	strcpy(sLengthofthepiecestocutfrom, "裁切板材規格");
	strcpy(sLengthofusedbars, "條形材的尺寸");
	strcpy(sLicenseAgreement, "許可協定");
	strcpy(sLinear, "線性的");
	strcpy(sLinethickness, "筆粗");
	strcpy(sLoadafileandappenddatatothecurrentDemand, "載入檔並將數據附加到當前零件。");
	strcpy(sLoadanexistingDemandfromafile, "從檔案載入現有零件。");
	strcpy(sLoadAppend, "載入並附加");
	strcpy(sLoadEverything, "載入所有");
	strcpy(sLoadInventory, "載入庫存");
	strcpy(sLoadInventoryandDemand, "載入庫存和零件");
	strcpy(sLoadResults, "載入結果");
	strcpy(sLocked, "已鎖定");
	strcpy(sLogo, "商標");
	strcpy(sLong, "長");
	strcpy(sLongerexecutiontime, "更長運行時間");
	strcpy(sLungime, "長度");
	strcpy(sLungimeanumar0, "長度必須大於0！");
	strcpy(sLungimeanumarreal, "長度必須是實數！");
	strcpy(sLungimeaTotalaFolosita, "總利用長度");
	strcpy(sMagnification, "放大");
	strcpy(sMagnify, "放大");
	strcpy(sMargins, "邊界");
	strcpy(sMarginsForPaper, "紙邊界");
	strcpy(sMarginsOfTheLabel, "標籤邊界");
	strcpy(sMaterial, "材料");
	strcpy(sMaterialName, "材料名稱");
	strcpy(sMaterials, "材料");
	strcpy(sMaterialstypes, "材料種類");
	strcpy(sMax, "最大");
	strcpy(sMaximalArea, "最大面積");
	strcpy(sMaximalCutLength, "最大切割長度");
	strcpy(sMaxlength, "最大長度");
	strcpy(sMaxPiecesperBar, "每條條形材最大件數");
	strcpy(sMaxwidth, "最大寬度");
	strcpy(sMeasurementUnit, "計量單位");
	strcpy(sMin, "最小");
	strcpy(sMinimalBreakSize, "最小斷裂尺寸");
	strcpy(sMinimalUsefulSize, "最小可用尺寸");
	strcpy(sMinimalwastesizetoInventory, "最小廢料尺寸（添加到庫存）。");
	strcpy(s_What_to_minimize, "盡量減少什麼？");
	strcpy(sMinlength, "最小長度");
	strcpy(sMinwidth, "最小寬度");
	strcpy(sMirror, "鏡像");
	strcpy(sMirroring, "鏡射");
	strcpy(sMiscellaneous, "其他統計");
	strcpy(sModify, "修改");
	strcpy(sModifytheselectedpiece, "修改選取零件");
	strcpy(sMovePiece, "移動件");
	strcpy(sMultiplestages, "多階段");
	strcpy(sName, "名稱");
	strcpy(sNameofedgeband, "封邊帶名稱");
	strcpy(sNewDEMANDUnsaveddatawillbelost, "新零件？ 將丟失未保存的數據！");
	strcpy(sNewLanguage, "新語言");
	strcpy(sNewMaterial, "新材料");
	strcpy(sNewPasswordincorectlyintroduced, "新密碼引入錯誤！");
	strcpy(sNewProduct, "新產品");
	strcpy(sNewversion, "新版本");
	strcpy(sNo, "否");
	strcpy(sNumarBucati, "件數");
	strcpy(sNumberOfCopies, "複印數量");
	strcpy(sNumberofstages, "階段數");
	strcpy(sNusuficienteplacidepozit, "並非所有部件都已優化。 可能的原因：庫存件數不足; 件未啟用; 物料和庫存的材料不同; 其他參數設置不正確。");
	strcpy(sOfficeNotInstaled, "您的計算機上未安裝Microsoft Office或安裝了錯誤的版本！");
	strcpy(sOldpassworddoesnotmatch, "舊密碼不匹配！");
	strcpy(sOnlinehelp, "在線説明");
	strcpy(sOnlypiecesofthesameheightinthelaststage, "最後階段中高度相同的部件");
	strcpy(sOpen, "打開");
	strcpy(sOptimization, "優化");
	strcpy(sOptimizationDone, "優化已執行！ 您可以列印或保存獲得的圖表。 如果您對當前的解決方案感到滿意，請按“接受”按鈕。 否則，請再次按啟動。");
	strcpy(sOptimizationType, "優化類型");
	strcpy(sOptions, "選件");
	strcpy(sOptionsrelatedtotheinterface, "與介面相關的選項");
	strcpy(sor, "或");
	strcpy(sOthercomponents, "其他元件");
	strcpy(sOthers, "其他");
	strcpy(sOtherstatistics, "其他統計");
	strcpy(sOverrideExcelCSVfiles, "覆蓋Excel / CSV檔");
	strcpy(sParameter, "參數");
	strcpy(sParts, "零件");
	strcpy(sPattern, "模式");
	strcpy(sPatternforwaste, "廢料圖案");
	strcpy(sPerimeter, "周長");
	strcpy(sPermitedRotationAngle, "允許旋轉角度");
	strcpy(sPhone, "電話");
	strcpy(sPicture, "圖片");
	strcpy(sPiece, "部件");
	strcpy(sPieceindex, "件索引");
	strcpy(sPieces, "件");
	strcpy(sPiecesize, "件數");
	strcpy(sPiecesizelabeledgebandwillbeprinted, "將列印之件數、標籤、邊帶。");
	strcpy(sPierdere, "銷毀");
	strcpy(sPixels, "圖元");
	strcpy(sPlacilefolositeDepozit, "庫存中的利用件。");
	strcpy(sPlease_contact_us_at_contact_nestingtechnologies_com, "請通過 contact@nesting-technologies.com 與我們聯繫。");
	strcpy(sPlease_contact_us_at_contact_optimalprograms_com, "請通過 contact@optimalprograms.com 與我們聯繫。");
	strcpy(sPleaseenteralldataeitherasfractionalorrealDonotmixthem, "請輸入所有數位，包括小數值或實數值！ 不要混合它們！");
	strcpy(sPleaseEnterSomeTypesOfMaterials, "沒有定義材料的類型。 您可以從「材料」功能表中定義它們。");
	strcpy(sPleasesendtheNameandtheCodetotheaddresscontactoptimalprogramscominordertoobtaintheRegistrationKey, "為了獲得註冊金鑰，請將名稱和代碼發送至：contact@optimalprograms.com。");
	strcpy(sPolygon, "多邊形");
	strcpy(sPolygonsCircles, "多邊形，圓形");
	strcpy(sPrecision, "精確度");
	strcpy(sPretulnumar0, "價格必須大於0！");
	strcpy(sPretulnumarreal, "價格必須為實數！");
	strcpy(sPreview, "預習");
	strcpy(sPrice, "價錢");
	strcpy(sPriceMustBeGreaterThanZero, "價格必須大於零");
	strcpy(sPriceofbars, "條形材價格");
	strcpy(sPriceperbar, "每條價格");
	strcpy(sPricepersheet, "每板材價格");
	strcpy(sPricepersquareunitofmaterial, "每平方米材料的價格");
	strcpy(sPriceperunit, "每單位價格");
	strcpy(sPrint, "列印");
	strcpy(sPrintdiagramsastables, "將圖表列印為表格。");
	strcpy(sPrinter, "印表機");
	strcpy(sPrinterBounds, "印表機的邊距");
	strcpy(sPrinting, "列印中");
	strcpy(sPrintonlyutilizedarea, "僅列印使用區域");
	strcpy(sPrintthecontentsoftheDemand, "列印零件內容。");
	strcpy(sPrintthecontentsoftheInventory, "列印庫存內容。");
	strcpy(sPrintthecurrentsolution, "列印當前解決方案。");
	strcpy(sPriority, "優次");
	strcpy(sPrioritytocutapieceZero0isthehighestpriority, "切割優先次序。 零（0）是最高優先順序。");
	strcpy(sProcentul0100, "百分比必須大於0且小於或等於100！");
	strcpy(sProcentulnumarreal, "百分比必須是實數！");
	strcpy(sProductdefinition, "產品定義");
	strcpy(sProductExists, "產品已經存在。 另選名稱。");
	strcpy(sProductName, "產品名稱");
	strcpy(sProduct, "產品");
	strcpy(sProducts, "產品");
	strcpy(sProject, "專案");
	strcpy(sProperties, "屬性");
	strcpy(sProperty, "屬性");
	strcpy(sQuantity, "數量");
	strcpy(sQuantitynumberofsheetsofthistype, "這種類型的板材數");
	strcpy(sRadius, "半徑");
	strcpy(sRectangular, "長方形");
	strcpy(sRedefinetypesofedgeband, "重新定義邊帶類型");
	strcpy(sRedefinetypesofmaterial, "重新定義材料類型");
	strcpy(sRegistration, "註冊");
	strcpy(sRegistrationKeyfromOptimalPrograms, "註冊碼");
	strcpy(sRegistrationSuccessful, "註冊成功！");
	strcpy(sRemoveallpiecesinInventory, "刪除庫存中的所有零件。");
	strcpy(sRemoveCut, "刪除剪切");
	strcpy(sRemovetheselectedpiece, "刪除選定的作品");
	strcpy(sReports, "報告書");
	strcpy(sRequestedMaterial, "要求的材料");
	strcpy(sRestore, "恢復");
	strcpy(sResults, "結果");
	strcpy(sReusedwaste, "再利用廢物");
	strcpy(sRight, "右");
	strcpy(sRightcoordinateofthedefect, "右側缺陷的座標");
	strcpy(sRotation, "旋轉");
	strcpy(sRotationAngle, "旋轉角度");
	strcpy(sRotationStep, "旋轉步驟");
	strcpy(sRoundAllFractionsTo, "分數值必須四捨五入為：");
	strcpy(sRow, "行");
	strcpy(sRows, "行數");
	strcpy(sRun, "最新解決方案");
	strcpy(sRunningtime, "運行時間");
	strcpy(sSameforall, "所有都一樣");
	strcpy(sSave, "保存");
	strcpy(sSaveAllImages, "保存所有圖像");
	strcpy(sSaveAs, "另存為");
	strcpy(sSaveChanges, "零件已更改。 您要儲存嗎？");
	strcpy(sSaveCurrentImage, "保存目前的圖像");
	strcpy(sSavedataparameters, "保存數據和參數");
	strcpy(sSaveEverything, "全部保存");
	strcpy(sSaveInventory, "保存庫存");
	strcpy(sSaveInventoryandDemand, "保存庫存和零件");
	strcpy(sSaveResults, "保存結果");
	strcpy(sSaveStatisticsinafile, "將統計數據保存在文件內");
	strcpy(sSavethecurrentimage, "保存目前的圖像");
	strcpy(sSavethecurrentimageorstatistic, "保存目前的圖像或統計數據");
	strcpy(sSavetheDEMANDinafile, "保存到檔案");
	strcpy(sSavetheDemandinafilewithadifferentname, "用不同名稱將零件保存在文件內。");
	strcpy(sSavetheREPOSITORYinafile, "將庫存保存到文件內");
	strcpy(sSerialNumber, "註冊碼");
	strcpy(sService, "服務");
	strcpy(sSetDefaultValues, "這會將所有參數恢復為預設值。 您將丟失所有設定。 您確定要這樣執行嗎？");
	strcpy(sSetedgeband, "設置邊帶");
	strcpy(sSetedgetrim, "設置邊距缺陷的切割尺寸");
	strcpy(sSetthesameedgebandforalledges, "為所有面設置相同的邊帶");
	strcpy(sSetthesamegrindingforalledges, "對所有邊緣設置相同的磨削");
	strcpy(sSetthesametrimforalledges, "為所有邊緣的缺陷設置相同的切割");
	strcpy(sSettings, "設定");
	strcpy(sShape, "形狀");
	strcpy(sSheet, "板材");
	strcpy(sSheetsBarstypes, "板材類型/條形材類型");
	strcpy(sSheetSize, "板材尺寸");
	strcpy(sSheetsperPage, "每板材張數");
	strcpy(sShort, "短");
	strcpy(sShorterexecutiontime, "運行時間短");
	strcpy(sShowallsimpleproducts, "顯示所有簡單產品");
	strcpy(sShowcustomername, "顯示客戶名稱");
	strcpy(sShowCustomTextOnEachPiece, "在每件零件上顯示自定義文字");
	strcpy(sShowdiagramasatable, "將圖表顯示為表格。");
	strcpy(sShowedgeband, "顯示邊帶");
	strcpy(sShowedgebandssettinginanewwindow, "在新視窗中顯示邊帶的設置");
	strcpy(sShowgrindingsettingsinanewwindow, "在新視窗中顯示研磨設置");
	strcpy(sShowHorizontalLabelsAlways, "始終顯示水平標籤");
	strcpy(sShowRemovethesizeofthepiecesinthecurrentsolution, "顯示/隱藏零件的大小。");
	strcpy(sShowRemovethesizeofthewastesinthecurrentsolution, "顯示/隱藏廢料的大小。");
	strcpy(sShowtotalcutlength, "顯示總切割長度");
	strcpy(sShowtrimedgesettingsinanewwindow, "在新視窗中顯示缺陷的設置");
	strcpy(sSimpleMaterialExists, "材料清單中已定義相同材料名稱。 請給它一個新名字。");
	strcpy(sSinglePieceStrips, "一件的條紋");
	strcpy(sSizes, "尺寸");
	strcpy(sSmallerorequalto, "廢料必須小於或等於");
	strcpy(sSort, "分類");
	strcpy(sSortAscendingByArea, "按面積升序排列");
	strcpy(sSortDescendingByArea, "按面積降序排列");
	strcpy(sSpecifyhowdifferentthepiecesinthelaststagecanbeValue0meansnodifference, "指定最後階段的零件有多大不同。 數值0表示沒有差異。");
	strcpy(sSpecifyifpiecesinthelaststagecanbedifferentornotdepeultimaetapapotfidiferitesaunucadimensiune, "指定最後階段的零件可否不同");
	strcpy(sSpecifyifthepiececanberotatedornotIfnotitwillbecutinthesamewayasitwasintroducedinDemandLengthofthepieceparalleltothelengthofthesheet, "指定零件可否旋轉。 若否，則以引入時的方式放置（零件的長度與板材的長度平行），");
	strcpy(sSpecifyinhowmanystageswemakethecutsDuringastageallcutshavethesamedirection, "指定需要削減多少個階段。");
	strcpy(sStartthesearchprocess, "開始搜索過程");
	strcpy(sStatistics, "統計數據");
	strcpy(sStatisticsE, "報告額外");
	strcpy(sStatisticsforeachtypeofmaterial, "每種材料的統計數據");
	strcpy(sStep, "步驟");
	strcpy(sStergeDepozit, "您要刪除庫存嗎？");
	strcpy(sStergeMaterial, "您要刪除資料嗎？");
	strcpy(sStergePiesele, "您要刪除零件嗎？");
	strcpy(sStergePiesa, "您要刪除零件嗎？");
	strcpy(sStopthesearchprocess, "停止搜尋程式");
	strcpy(sStrongoptimization, "高度優化");
	strcpy(sSubtractthebandthicknessfrompiecesize, "減小邊帶厚度的零件尺寸");
	strcpy(sSummary, "摘要");
	strcpy(sSuprafataTotalaFolosita, "總使用面積");
	strcpy(sSuprafatautilizata, "使用率");
	strcpy(sSwitchbetweenfiberandrotationoption, "在條子和旋轉選項之間切換。");
	strcpy(sTechnical, "技術");
	strcpy(sTechnicalsettings, "技術設定");
	strcpy(sTemporaryPanelHint, "在板材之間移動零件的臨時面板。");
	strcpy(sText, "文字");
	strcpy(sThe_application_has_expired, "該應用程式已過期。");
	strcpy(sThe_application_is_not_registered, "該應用程式未被註冊。");
	strcpy(sThe_application_was_first_started_on, "該應用程式首次啟動於");
	strcpy(sThecutsareperformedfromasidetotheothersideofthematerial, "從材料的一側到另一側進行切割。");
	strcpy(sThecuttingmachinecanfollowtheshapeofthematerial, "切割機可以跟隨零件的形狀。");
	strcpy(sTheedgesofsheetsthatmustbetrimedduefaults, "因應瑕疵，必須修剪的板材邊緣");
	strcpy(sTheLargestSize, "最大尺寸");
	strcpy(sThenameofthecustomerforwhichyoucutthepiece, "目前切割零件的客戶名稱。");
	strcpy(sThenameofyourcustomer, "客戶名稱");
	strcpy(sThepiececanberotated, "可旋轉零件");
	strcpy(sTheprogramtriestoavoidwasteswhichhavebothsizeslessthanthisvalue, "程序嘗試避免小於此值的廢料");
	strcpy(sThereAreNoProducts, "尚無定義的產品");
	strcpy(sThestockofmaterialhasbeenpreviouslyloadedfromanExcelorCSVformatPleaseloaditagain, "已從Excel或CSV格式載入物料庫存。 如要對其進行處理，請再次載入。");
	strcpy(sThetotallengthofcutting, "裁切總長度");
	strcpy(sThewidthofthecuttingsawForglasscuttingoptimizationitcanbe0Forwooditshouldbegreaterthan0, "鋸的厚度。 切割玻璃時可以為0。 切割木材時應大於0。");
	strcpy(sThewidthofthecuttingsawforlinearpieces, "鋸的厚度（用於切割線性零件）");
	strcpy(sThickness, "厚度");
	strcpy(sThischaracterisusedforfillingthewasterectanglesIfyoudonotwantfilledwastejustremovethischaracter, "該符號用於填充矩形廢料。 若您不想填充廢料，只需將其清除即可。");
	strcpy(sThisindexhasvaluebetween1andthenumberofpieces, "該索引的值在1到件數之間。");
	strcpy(sThisOptionWillOverrideTheInventoryFileIfLoadedFromExcelOrCsvFiles, "如果從excel或csv載入文件，此選項將覆蓋清單檔案。");
	strcpy(sThisProgramisLicensedTo, "該程式被許可用於");
	strcpy(sThisvaluewillbeaddedtotheedgebandingmaterialoneachside, "該值將被添加到每一側的邊緣帶");
	strcpy(sTipNevid, "物料類型不能為空白。");
	strcpy(sTitle, "標題");
	strcpy(sTools, "工具");
	strcpy(sTop, "上");
	strcpy(sTopcoordinateofthedefect, "缺陷的頂部座標。");
	strcpy(sTotalGarbageWaste, "所有廢棄的廢料");
	strcpy(sTotalInventoryWaste, "庫存廢料總量");
	strcpy(sTotalRecycledWaste, "所有重複使用的廢料");
	strcpy(sTotalusedarea, "總使用面積");
	strcpy(sTotalusedlength, "總使用長度");
	strcpy(sTrigonometric, "三角函數");
	strcpy(sTrim, "修剪");
	strcpy(sTrimalledgesatthebeginning, "在開始時修剪所有邊緣");
	strcpy(sTrimEdge, "修剪邊緣");
	strcpy(sTwoPanels, "2個面板");
	strcpy(sType, "類型");
	strcpy(sTypeofmaterialfromwhichtocut, "切割材料的類型");
	strcpy(sTypesAreNotMatched, "優化未執行！零件表和庫存表中的材質不符！只能從庫存中同名的材質切割零件。請從對應的列中更改材質名稱！");
	strcpy(sUndo, "恢復");
	strcpy(sUndoAccept, "恢復確認");
	strcpy(sUnits, "單位");
	strcpy(sUnregisteredVersion, "未註冊");
	strcpy(sUpdates, "更新");
	strcpy(sUsefulforwoodfurniture, "適用於木製傢俱");
	strcpy(sUseit, "使用");
	strcpy(sUsePieceinOptimization, "優化使用零件");
	strcpy(sUserName, "用戶名稱");
	strcpy(sUtilizationandWastes, "利用率和報廢");
	strcpy(sUtilizedArea, "零件使用面積");
	strcpy(sUtilizedBars, "使用條形材");
	strcpy(sUtilizeddemandcount, "使用零件數");
	strcpy(sUtilizedParts, "使用零件");
	strcpy(sUtilizedPieces, "使用零件");
	strcpy(sUtilizedSheets, "使用板材");
	strcpy(sValue, "數值");
	strcpy(sValueGreaterEqualToZero, "數值必須大於或等於零");
	strcpy(sValueGreaterThanZero, "數值必須大於零");
	strcpy(sValueIntegerNumber, "數值必須為整數！");
	strcpy(sValueRealNumber, "數值必須為實數。 也許您使用了逗號而非句號，反之亦然。 請修復！");
	strcpy(s_The_number_is_too_big_or_it_has_too_many_digits_after_decimal_separator, "數位太大或在小數點分隔符后位數太多！");
	strcpy(s_The_number_is_too_big, "數位太大！");
	strcpy(sVertical, "垂直");
	strcpy(sWaste, "廢料");
	strcpy(sWastes, "廢料");
	strcpy(sWasteAddedToWarehouse, "增加到庫存的廢料");
	strcpy(sWastelimits, "廢料範圍");
	strcpy(sWasteType, "廢料類型");
	strcpy(sWeakoptimization, "最弱的優化");
	strcpy(sWhattoprint, "該列印什麼");
	strcpy(s_What_to_print_or_save_to_file, "打印或保存到文件的內容");
	strcpy(sWhattoprintoneachpiece, "在每個零件上列印什麼");
	strcpy(sWhattoshowoneachpiece, "每個零件上要展示什麼？");
	strcpy(sWidth, "寬度");
	strcpy(sWood, "木");
	strcpy(sWorkingDirectory, "工作資料夾");
	strcpy(sWrongKey, "註冊金鑰錯誤！");
	strcpy(sYes, "是");
	strcpy(sYoucannotchooseblackblueorredcolors, "您不能選擇黑色，藍色或紅色。");
	strcpy(sYouCannotMixFractionalDataWithDecimalOnes, "您不能將分數與實數混合！");
	strcpy(sYourcompany, "您的公司");
	strcpy(sZip, "郵遞區號");
	strcpy(s_Set_the_origin_and_the_direction_of_the_axes, "設置坐標軸的原點和方向。");










	strcpy(s_Number_of_digits_after_the_decimal_separator, "小數點後的數字位數");
	strcpy(s_Percentages, "百分比");
}


