// Language strings: Arabic
// Author: Optimal Programs
// License: MIT License
//---------------------------------------------------------------------------
#include <string.h>
//---------------------------------------------------------------------------
#include "language_string_id.h"
//---------------------------------------------------------------------------
void set_ar(void)
{
	//Arabic
	// translated by a customer
	// last update on: 2025.9.25.0
	strcpy(s_Area, "مساحة");
	strcpy(s_Mass, "كتلة");
	strcpy(s_Advanced, "متقدم");
	strcpy(s_Relative_coordinates, "الإحداثيات النسبية");
	strcpy(s_Absolute_coordinates, "الإحداثيات المطلقة");
	strcpy(s_Append_more_rows, "إلحاق المزيد من الصفوف");

	strcpy(s_Add_to_parts, "أضف إلى الأجزاء.");
	strcpy(s_Additional, "إضافي");
	strcpy(s_All_results, "جميع النتائج.");
	strcpy(s_Allow_movement_of_pieces, "السماح بحركة القطع");
	strcpy(s_Allow_part_in_part, "السماح قطعة قطعة");
	strcpy(s_Invalid_piece_Angles_are_too_small_or_too_big_or_height_is_too_small, "قطعة غير صالحة! الزوايا صغيرة جدًا أو كبيرة جدًا، أو الارتفاع صغير جدًا.");
	strcpy(s_Append, "إلحاق");
	strcpy(s_As_it_is, "كما هو");
	strcpy(s_As_text, "كنص");
	strcpy(s_Ascending, "تصاعدي");
	strcpy(s_Automatic, "تلقائي");
	strcpy(s_Cannot_connect_to_the_Internet_Please_visit_our_website_from_a_browser, "لا يمكن الاتصال بالإنترنت! يرجى زيارة موقعنا على الإنترنت من متصفح.");
	strcpy(s_Cannot_copy_or_move_the_files, "لا يمكن نسخ أو نقل الملفات!");
	strcpy(s_Cannot_delete_the_file, "Skedari nuk mund të fshihet!");
	strcpy(s_Cannot_modify_old_results, "لا يمكن تعديل النتائج القديمة!");
	strcpy(s_To_change_click_inside_a_cell_or_press_0_1_or_2, "للتغيير ، انقر داخل خلية أو اضغط على 0 أو 1 أو 2.");
	strcpy(s_Cell, "خلية");
	strcpy(s_Click_on_the_table_header_to_change_the_columns, "انقر على رأس الجدول لتغيير الأعمدة.");
	strcpy(s_Close, "أغلقه");
	strcpy(s_Contact_us, "اتصل بنا");
	strcpy(s_Column, "عمودي");
	strcpy(s_Comma, "فاصلة");
	strcpy(s_The_comma_symbol_cannot_simultaneously_be_the_list_separator_and_the_decimal_separator, "لا يمكن لرمز الفاصلة أن يكون فاصل القائمة والفاصل العشري في نفس الوقت!");
	strcpy(s_Copy, "نسخ");
	strcpy(s_Copy_for_move, "نسخ للتحرك");
	strcpy(s_Cut_higher_level_strips_first, "قم بقطع شرائح ذات مستوى أعلى أولاً");
	strcpy(s_Cut_index, "عرض مؤشر القص");

	strcpy(s_The_data_have_been_changed_Do_you_want_to_save_them_to_a_file, "تم تغيير البيانات. هل تريد حفظها في ملف؟");
	strcpy(s_Decimal_separator, "الفاصل العشري");
	strcpy(s_Restore_default_settings, "استعادة الإعدادات الافتراضية");
	strcpy(s_Delete_fiber, "احذف الألياف");
	strcpy(s_Descending, "تنازلي");
	strcpy(s_Discard_changes, "تجاهل التغييرات");

	strcpy(s_Delete_all_data, "حذف كافة البيانات؟");
	strcpy(s_Dot, "نقطة");
	strcpy(s_Do_you_want_to_delete_the_picture, "هل تريد حذف الصورة؟");
	strcpy(s_Do_you_want_to_delete_the_product, "هل تريد حذف المنتج؟");
	strcpy(s_Duplicate_and_append, "مكرر وإلحاق.");
	strcpy(s_Duplicate_values_are_ignored, "يتم تجاهل القيم المكررة!");
	strcpy(s_Error, "خطأ");
	strcpy(s_Error_loading_file, "خطأ في تحميل الملف.");
	strcpy(s_export_everything, "تصدير كل شيء");
	strcpy(s_Fit_to_screen, "تناسب الشاشة.");
	strcpy(s_Force_fixed_height, "ارسم القطع بارتفاع ثابت.");
	strcpy(s_Flipped, "انقلبت");
	strcpy(s_Import, "استيراد");
	strcpy(s_If_angles_are_different_from_90_degrees_height_must_be_greater_than_0, "إذا كانت الزوايا مختلفة عن 90 درجة، فيجب أن يكون الارتفاع أكبر من 0.");
	strcpy(s_Ignore, "يتجاهل");
	strcpy(s_Incorrect_value, "قيمة غير صحيحة");
	strcpy(s_Info, "معلومات");
	strcpy(s_Interior, "داخلي");
	strcpy(s_Give_a_name, "اعطني اسم.");
	strcpy(s_Group, "قم بتجميعها");
	strcpy(s_Header, "رأس");
	strcpy(s_Keep_it_as_it_is, "احتفظ بها كما هي");
	strcpy(s_Level, "Level");
	strcpy(s_Licensee, "المرخص له");
	strcpy(s_List_separator, "فاصل القائمة");
	strcpy(s_Made_with_love_in_Cugir_Romania, "صُنع بحب في: كوجير، رومانيا");
	strcpy(s_Made_in, "صُنع في");
	strcpy(s_Manufacturer, "الصانع");

	strcpy(s_Manual_arrange, "الترتيب اليدوي");

	strcpy(s_Mixed, "مختلط");
	strcpy(s_Multiple_shapes_detected_Next_rows_will_be_overwritten_Continue, "تم اكتشاف أكثر من شكل. لذلك ، سيتم الكتابة فوق الصفوف اللاحقة. يكمل؟");
	strcpy(s_More, "أكثر");
	strcpy(s_Multiple_values, "قيم متعددة");
	strcpy(s_No_texture, "لا نسيج");
	strcpy(s_Number, "رقم");
	strcpy(s_Number_of_images, "عدد الصور");
	strcpy(s_Number_of_vertices, "عدد القمم");
	strcpy(s_Offset, "عوض");
	strcpy(s_Only_the_currently_selected_items, "فقط العناصر المحددة حاليا.");
	strcpy(s_Optimizing_please_wait, "التحسين ... يرجى الانتظار.");

	strcpy(s_Paste, "Paste");

	strcpy(s_Piece_label, "تسمية قطعة");
	strcpy(s_Piece_size, "قياس القطعة");
	strcpy(s_Please_contact_us_by_email_if_you_receive_this_error, "يرجى الاتصال بنا عبر البريد الإلكتروني إذا تلقيت هذا الخطأ.");
	strcpy(s_Please_save_it_first, "من فضلك احفظها أولا.");
	strcpy(s_Position, "موقع");
	strcpy(s_Preview, "معاينة");
	strcpy(s_Rectangle, "مستطيل");

	strcpy(s_Redo_the_last_operation, "استعادة العملية الأخيرة");
	strcpy(s_Regular_polygon, "مضلع منتظم");

	strcpy(s_Reused, "معاد استخدامها");
	strcpy(s_Rotated, "مستدير");
	strcpy(s_Save_all, "احفظ الكل");
	strcpy(s_Scrap_label, "تسمية المخلفات");
	strcpy(s_Scrap_size, "قياس المخلفات");
	strcpy(s_Semicolon, "فاصلة منقوطة");
	strcpy(s_Show_cut_index, "عرض مؤشر القص");
	strcpy(s_Show_information, "مزيد من المعلومات");
	strcpy(s_Show_piece_label, "تسمية قطعة");
	strcpy(s_Show_scrap_label, "تسمية المخلفات");
	strcpy(s_Show_scrap_s_size_on_the_small_pieces, "اعرض حجم الخردة على القطع الصغيرة");
	strcpy(s_Show_size_of_pieces, "قياس القطعة");
	strcpy(s_Show_size_of_scrap, "قياس المخلفات");
	strcpy(s_Show_sizes, "عرض الأحجام");
	strcpy(s_Show_label, "إظهار التسمية");
	strcpy(s_Show_length, "عرض الطول");

	strcpy(s_Some_numerical_values_are_incorrect_Should_I_fix_all_the_incorrect_values, "بعض القيم العددية غير صحيحة! هل يجب علي إصلاح جميع القيم غير الصحيحة؟");
	strcpy(s_Some_invalid_values_have_been_removed, "تمت إزالة بعض القيم غير الصالحة.");
	strcpy(s_Sort_by, "صنف حسب");
	strcpy(s_Sort_ascending_by, "فرز تصاعدي حسب");
	strcpy(s_Sort_descending_by, "فرز تنازلي حسب");
	strcpy(s_Start, "Start");
	strcpy(s_Starting_angle, "زاوية البداية");


	strcpy(s_Stock, "مخزون");
	strcpy(s_Stop, "Stop");
	strcpy(s_System_setting, "إعدادات النظام");
	strcpy(s_Tabular, "مجدول");
	strcpy(s_Total, "المجموع");
	strcpy(s_Total_size, "الحجم الإجمالي");
	strcpy(s_Terms_of_the_license, "شروط الترخيص");
	strcpy(s_The_current_product_has_been_changed_Do_you_want_to_save_it_to_file, "تم تغيير المنتج الحالي. هل تريد حفظه في ملف؟");
	strcpy(s_The_value_is_out_of_the_allowed_range, "القيمة خارج النطاق المسموح به.");
	strcpy(s_The_value_must_be_a_real_or_fractional_number_Try_to_replace_the_comma_with_the_dot_if_you_want_to_enter_a_real_number, "يجب أن تكون القيمة رقمًا حقيقيًا أو كسريًا. حاول استبدال الفاصلة بالنقطة إذا كنت تريد إدخال رقم حقيقي.");
	strcpy(s_This_feature_is_not_implemented_yet, "لم يتم تنفيذ هذه الميزة بعد.");
	strcpy(s_This_operation_cannot_be_reversed, "لا يمكن عكس هذه العملية.");
	strcpy(s_Undo_the_last_operation, "التراجع عن العملية الأخيرة.");
	strcpy(s_Utilization, "استغلال");
	strcpy(s_Utilized_Stock, "الأسهم المستخدمة");
	strcpy(s_Version, "إصدار");
	strcpy(s_Visible_columns, "أعمدة مرئية");
	strcpy(s_You_already_have_the_latest_version_installed, "لديك بالفعل أحدث إصدار مثبت!");
	strcpy(s_What_is_exported, "ما الذي يتم تصديره؟");
	strcpy(s0meansanynumberofpieces, "الصفر يعني أي عدد من القطع");
	strcpy(sAbout, "حول");
	strcpy(sAccept, "قبول");
	strcpy(sAcceptall, "قبول الكل");
	strcpy(sAcceptthecurrentsolution, "قبول الحل الحالي");
	strcpy(sAdd, "إضافة");
	strcpy(sAddapiece, "أضف قطعة");
	strcpy(sAddasimpleproducttoDemand, "إضافة المنتج إلى القطع الموجودة.");
	strcpy(sAddgrindingthicknesstopartsize, "أضف سماكة الطحن إلى قياس القطعة");
	strcpy(sAddproductnametolabel, "إضافة اسم المنتج في التسمية.");
	strcpy(sAddress, "العنوان");
	strcpy(sAddselectedsizetoInventory, "إلحاق القياس المحدد بالمخزون");
	strcpy(sAdhesivelabels, "ملصقات");
	strcpy(sAdhesivelabelwithinformationaboutpiecesinDemandCustomernameLabelSizeCurrentData, "لصاقة تحتوي على معلومات حول القطع: اسم العميل ، التسمية ، القياس ، البيانات الحالية إلخ.");
	strcpy(sAdhesivelabelwithinformationaboutsheetsinInventory, "ملصقات تحتوي على معلومات حول الألواح الموجودة في المخزون.");
	strcpy(sAll, "الكل");
	strcpy(sAlloffcutswhichhavethesizegreaterthanthisvaluewillbeaddedtoInventory, "ستتم إضافة جميع المخلفات التي أكبر من هذه القيمة إلى المخزون");
	strcpy(sAllowMirroring, "السماح بالتقليب");
	strcpy(sAllowRotation, "السماح بالدوران");
	strcpy(sAllPieces, "جميع القطع");
	strcpy(sAllpredefinedproducts, "جميع المنتجات المحددة مسبقًا");
	strcpy(sAnewwindowwillbedisplayedwheretheusercansettheedgebandsforeachedge, "سيتم عرض نافذة جديدة حيث يمكن للمستخدم ضبط نطاق الحافة لكل جانب.");
	strcpy(sAnewwindowwillbedisplayedwheretheusercansetthegrindingvalueforeachedgeofthsheet, "سيتم عرض نافذة جديدة حيث يمكن للمستخدم تعيين قياس الطحن لكل جانب من جوانب القطعة.");
	strcpy(sAnewwindowwillbedisplayedwheretheusercansetthetrimvalueforeachedgeofthsheet, "سيتم عرض نافذة جديدة حيث يمكن للمستخدم تعيين قيمة التشذيب لكل جانب من جوانب القطعة.");
	strcpy(sAngle, "زاوية");
	strcpy(sAngles, "الزوايا");
	strcpy(sAnoptimizationparameterisarealnumber, "عامل الحساب عدد صحيح.");
	strcpy(sAnoptimizationparameterisfractionalnumber, "عامل الحساب عدد عشري.");
	strcpy(sAnyShape, "الشكل الحقيقي");
	strcpy(sApolygonmusthaveatleast2vertices, "يجب أن يحتوي المضلع على ذروتين على الأقل!");
	strcpy(sApolygonmusthaveatleast3vertices, "يجب أن يحتوي المضلع على 3 رؤوس على الأقل!");
	strcpy(sApplication_fails_to_initialize, "فشلت تهيئة التطبيق!");
	strcpy(sArc, "قوس");
	strcpy(sArcLength, "طول القوس");
	strcpy(sAreaofusedsheets, "مساحة الألواح المستخدمة");
	strcpy(sAshortdescriptionofthesheet, "وصف موجز للوح");
	strcpy(sAtleastonepart, "يجب إدخال قطعة واحدة على الأقل.");
	strcpy(sAtTheMarginOfTheSheet, "على هامش اللوح");
	strcpy(sBandtypes, "أنواع نطاقات الحواف");
	strcpy(sBar, "القضبان");
	strcpy(sBars, "القضبان");
	strcpy(sBothsizesoftheoffcutsmustbegreaterthanthisvalue, "يجب أن يكون كلا الطول والعرض للمخلفات أكبر من هذه القيمة.");
	strcpy(sBottom, "الأسفل");
	strcpy(sBottomcoordinateofthedefect, "الإحداثي السفلي للعيب");
	strcpy(sBreakCut, "جزء القص");
	strcpy(sBrowse, "تصفح");
	strcpy(sBuy, "اشتري");
	strcpy(sBuynow, "اشتري الآن ...");
	strcpy(sCancel, "الغاء");
	strcpy(sCannotBeEmpty, "لايمكن ان يكون فارغا!");
	strcpy(sCannotmovepartsbetweensheetswhenidenticalsheetsaregroupedPleaseungroupthesheetsfrommenu, "لا يمكن نقل القطع من لوح إلى آخر إذا تم تجميع الألواح المتطابقة. يرجى إلغاء تجميع الألواح من القائمة.");
	strcpy(sCannotSaveFile, "لا يمكن حفظ الملف");
	strcpy(sCenter, "مركز");

	strcpy(sChangeDirection, "تغيير اتجاه القص");
	strcpy(sChoose, "اختر");
	strcpy(sChooseProduct, "اختر منتج");
	strcpy(sCircle, "دائرة");
	strcpy(sCity, "مدينة");
	strcpy(sClear, "مسح");
	strcpy(sClockWise, "في اتجاه عقارب الساعة");
	strcpy(sClosewindow, "إغلاق النافذة");
	strcpy(sColor, "اللون");
	strcpy(sColorofedgeband, "لون نطاقات الحافة");
	strcpy(sColorPattern, "نمط/لون");
	strcpy(sColorpiecesandwastes, "تلوين القطع والضياع");
	strcpy(sColumns, "الأعمدة");
	strcpy(sComment, "تعليق");
	strcpy(sCompanyname, "اسم الشركة");
	strcpy(sComplexMaterialExists, "اسم المادة معرف مسبقاً في قائمة المواد المعقدة. يرجى إعطاء اسماً جديداً.");
	strcpy(sComputerCode, "رمز الحاسوب");
	strcpy(sComputerCodefromyourcomputer, "رمز الحاسوب (من جهاز الحاسوب الخاص بك)");
	strcpy(sComputethetotalpriceofDemand, "حساب السعر الإجمالي للقطع");
	strcpy(sContents, "محتويات");
	strcpy(sContinutComanda, "محتوى القطع حسب التاريخ");
	strcpy(sContinutDepozit, "محتوى المخزون حسب التاريخ");
	strcpy(sConversionIsDoneOnlyWhenSomePiecesHaveFractionalValues, "يتم التحويل فقط عندما يكون لبعض القطع قيم عشرية.");
	strcpy(sConvertsTheSizeOfWasteToAFractionalUnit, "إظهار قياس المخلفات كقيمة عشرية.");
	strcpy(sCouldNotSaveFile1, "تعذرت كتابة الملف في المجلد");
	strcpy(sCouldNotSaveFile2, "قد لا يكون لديك صلاحيات كافية. يرجى التحقق أو تغيير دليل العمل من قائمة الإعدادات إلى مجلد حيث لديك صلاحيات الكتابة فيه(على سبيل المثال c: \\ temp).");
	strcpy(sCreationdateYMDHMS, "تاريخ الإنشاء");
	strcpy(sCurrentDate, "التاريخ الحالي");
	strcpy(sCurrentDiagram, "الرسم البياني الحالي");
	strcpy(sCurrentMaterial, "المواد الحالية");
	strcpy(sCurrentversion, "النسخة الحالية");
	strcpy(sCurve_not_closed_Try_increasing_DXF_linking_distance_parameter, "الشكل غير مغلق حاول زيادة عامل مسافة ربط الـ DXF.");
	strcpy(sCustomer, "الزبون");
	strcpy(sCustomerName, "اسم الزبون");
	strcpy(sCustomMessage, "رسالة مخصصة");
	strcpy(sCutlength, "طول القص.");
	strcpy(sCut, "يقطع");
	strcpy(sCuts, "المقصوصات");
	strcpy(sCutterThickness, "سماكة القص");
	strcpy(sData, "البيانات");
	strcpy(sDataCannotBeEmpty, "لا يمكن أن تكون البيانات فارغة!");
	strcpy(sDateymdhms, "التاريخ (y/m/d/h/m/s)");
	strcpy(sDays_left_for_trial, "الأيام المتبقية للتجريب");
	strcpy(sDaysLeft, "الأيام المتبقية");
	strcpy(sStandard, "الإفتراضي");
	strcpy(sDefaultInterface, "الواجهة الافتراضية");
	strcpy(sDefects, "العيوب");
	strcpy(sDefectsManager, "إدارة العيوب");
	strcpy(sDefectsofthematerialNopiecescanbeplacedinthefaultyzone, "عيوب المادة. لا يمكن وضع قطع في المنطقة المعيبة.");
	strcpy(sDelete, "حذف");
	strcpy(sDeletePiece, "حذف القطعة");
	strcpy(sDeleteRow, "حذف صف");
	strcpy(sDemandutilization, "استخدام القطع");
	strcpy(sDepozitulmodificat, "تم إزالة القطع المستخدمة. تم إضافة المخلفات إلى المخزون.");
	strcpy(sDepozitvid, "المخزون فارغ");
	strcpy(sDesk, "قرص القص");
	strcpy(sDiagram, "رسم بياني");
	strcpy(sDiagram, "رسم بياني");
	strcpy(sDiagramasatable, "رسم بياني كجدول");
	strcpy(sDigits, "أرقام");
	strcpy(sDimensiuniplaca, "قياس اللوح");
	strcpy(sDirection, "الإتجاه");
	strcpy(sDistanceBetweenRows, "المسافة بين الصفوف");
	strcpy(sDonotuseit, "عدم الإستخدام");
	strcpy(sDownload, "تحميل");
	strcpy(sDoYouWantToClearTheData, "هل تريد حذف البيانات؟");
	strcpy(sDoYouWantToSaveDemand, "تم تغيير القطع! هل تريد حفظ التغييرات؟");
	strcpy(sDoYouWantToSaveParts, "هل تريد حفظ القطع؟");
	strcpy(sDoYouWantToSaveRepository, "تم تغيير المخزون! هل تريد حفظ التغييرات؟");
	strcpy(sDrawing, "رسم");
	strcpy(sDrawthesolutioncolorful, "رسم الحل بالألوان");
	strcpy(sDuplicateTypes, "بعض الأنواع مكررة! يرجى إزالة التكرار");
	strcpy(sDuplicateTypesWithComplex, "بعض أسماء المواد موجودة مسبقاً في قائمة الأنواع المعقدة! يرجى إزالة التكرار");
	strcpy(sDuplicateValues, "قيم مكررة");
	strcpy(sEdgeband, "نطاقات الحافة");
	strcpy(sEdgebandingwhichisplacedontheedgesofyourpiecePleasedefineedgebandingtypesfromMaterialsEdgeBandingmenu, "يتم وضع نطاقات الحافة على هوامش القطعة الخاصة بك. يرجى تحديد نطاقات الحافة في قائمة المواد.");
	strcpy(sEdgebandsthatwillbeappliedtoeachpart, "نطاقات الحافة التي يتم وضعها على كل قطعة.");
	strcpy(sEdgeBandTolerance, "التسامح لنطاقات الحافة");
	strcpy(sEdgesthatmustbecutduefaults, "الحواف التي يجب قطعها بسبب العيوب.");
	strcpy(sEdgetoedge, "من الحافة إلى الحافة");
	strcpy(sEdit, "تعديل");
	strcpy(sEmail, "البريد الإلكتروني");
	strcpy(sEmptyData, "البيانات فارغة!");
	strcpy(sEnabled, "ممكّن");
	strcpy(sEnabledisabledefectsoftheinventorysheets, "تمكين / تعطيل عيوب المخزون");
	strcpy(sEnterLabel, "أدخل التسمية");
	strcpy(sEnterTheMaterialName, "أدخل اسم المادة");
	strcpy(sEnterTheProductName, "أدخل اسم المنتج");
	strcpy(sEvaluationError, "خطأ في تقييم التعبير!");
	strcpy(sExit, "خروج");
	strcpy(sExpired, "انتهت صلاحية البرنامج! يرجى تسجيل البرنامج!");
	strcpy(sExport, "تصدير");
	strcpy(sExportAllDiagrams, "تصدير جميع المخططات");
	strcpy(sExportAllToASingleFile, "تصدير الكل إلى ملف واحد");
	strcpy(sExportOptions, "خيارات التصدير");
	strcpy(sExporttoDXFformat, "تصدير إلى تنسيق DXF");
	strcpy(sExporttoExcel, "تصدير إلى Excel");
	strcpy(sExpresieIncorecta, "تعبير رياضي غير صحيح!");
	strcpy(sExtensions, "Extensions");
	strcpy(sExtra, "إضافي");
	strcpy(sExtraComponents, "مكونات اضافية");
	strcpy(sExtracomponentsattachedtoDemand, "مكونات إضافية ملحقة بالقطع");
	strcpy(sFile, "ملف");
	strcpy(sFileName, "اسم الملف");
	strcpy(sFillWastes, "رسم الضياع بخطوط مائلة");
	strcpy(sFindoptimalbarsheetsize, "ابحث عن القياس الأمثل للألواح والقضبان.");
	strcpy(sFindoptimalsizeofInventorypieces, "ابحث عن القياس الأمثل لقطع المخزون");
	strcpy(sFirstcutMultiplestages, "اتجاه القص المبدئي لمراحل الحساب المتعددة.");
	strcpy(sFirstdirectionforcutishorizontal, "الاتجاه المبدئي للقص أفقي.");
	strcpy(sFirstdirectionforcutisvertical, "الاتجاه المبدئي للقص عمودي.");
	strcpy(sFollowthecontourofpieces, "اتباع محيط القطع");
	strcpy(sFont, "الخط");
	strcpy(sFontsize, "حجم الخط");
	strcpy(sFullInfo, "معلومات كاملة");
	strcpy(sDisposedWaste, "التخلص من النفايات");
	strcpy(sGeneral, "عام");
	strcpy(sGenerateCNC, "توليد CNC");
	strcpy(sGrain, "النقش");
	strcpy(sGraindirection, "فايبر");
	strcpy(sGraphic, "الرسم");
	strcpy(sGreaterorequalto, "أكبر أو يساوي");
	strcpy(sGrid, "الجداول");
	strcpy(sGrinding, "طحن");
	strcpy(sGrosimeTaieturaScalata, "قد تختلف سماكة القص من هذه الصورة عن الصورة الحقيقية لأن القطع غير ممثلة بمقياسها الحقيقي. هذا الأمر لا يؤثر على النتائج.");
	strcpy(sGroupidenticallayouts, "تجميع الألواح المتطابقة");
	strcpy(sGroupIdenticalParts, "تجميع القطع المتطابقة");
	strcpy(sGroupingOfIdenticalPiecesIntoOneRow, "تجميع القطع المتطابقة في صف واحد.");
	strcpy(sGroupPartsAfterLoadingFromFile, "تجميع القطع عند التحميل من الملف");
	strcpy(sHeight, "ارتفاع");
	strcpy(sHeighttolerance, "التسامح في الارتفاع");
	strcpy(sHelp, "مساعدة");
	strcpy(sHistory, "التاريخ");
	strcpy(sHorizontal, "عرضي");
	strcpy(sHowtodisplayprintedgebands, "كيف يتم عرض نطاقات الحافة؟");
	strcpy(sIfyousetthebandforoneedgeallwillreceivethesamevalue, "إذا قمت بتعيين النطاق لحافة واحدة ، فسيكون ذلك لجميع الحواف.");
	strcpy(sIfyousetthegrindingforoneedgeallwillreceivethesamevalue, "إذا قمت بتعيين قيمة الطحن لحافة واحدة ، فسيكون ذلك لجميع الحواف.");
	strcpy(sIfyousetthetrimforoneedgeallwillreceivethesamevalue, "إذا قمت بتعيين التشذيب لحافة واحدة ، فسيكون ذلك لجميع الحواف.");
	strcpy(sImageBounds, "حدود الصورة");
	strcpy(sImageSize, "حجم الصورة");
	strcpy(sImportData, "استيراد البيانات");
	strcpy(sIncorrectPassword, "كلمة سر خاطئة");
	strcpy(sIndex, "فهرس");
	strcpy(sInformationaboutcustomer, "معلومات عن العميل");
	strcpy(sInputALanguageName, "أدخل اسم اللغة");
	strcpy(sInsert, "إدراج");
	strcpy(sInsertPiece, "أدخل قطعة");
	strcpy(sInterface, "واجهه المستخدم");
	strcpy(sInterfaceSettings, "إعدادات الواجهة");
	strcpy(sInvalidHardware, "لم يتم الكشف عن الجهاز. يرجى الاتصال بنا على contact@optimalprograms.com");
	strcpy(sInvalidNumber, "رقم غير صالح");
	strcpy(sInvalidOrderOfComputation, "لا يمكن إنشاء أمر لحساب الأطوال. هناك علاقات دائرية في تعريف المنتج!");
	strcpy(sInvalidRegistration, "التسجيل غير صالح!");
	strcpy(sInvalidTime, "وقت النظام الخاص بك غير صالح.");
	strcpy(sInventory, "مخزون");
	strcpy(sisafractionalvalue, "قيمة عشرية.");
	strcpy(sIsArc, "قوس");
	strcpy(sisarealvalue, "قيمة صحيحة.");
	strcpy(sLabel, "التسمية");
	strcpy(sLabels, "ملصقات");
	strcpy(sLanguage, "لغة");
	strcpy(sLatimeanumar0, "يجب أن يكون العرض أكبر من 0!");
	strcpy(sLatimeanumarreal, "يجب أن يكون العرض رقمًا صحيحاً!");
	strcpy(sLayerName, "اسم الطبقة");
	strcpy(sLeft, "اليسار");
	strcpy(sLeftcoordinateofthedefect, "الإحداثي الأيسر للعيب");
	strcpy(sLength, "الطول");
	strcpy(sLengthofthepiecestocut, "قياس القطعة للقص");
	strcpy(sLengthofthepiecestocutfrom, "قياس اللوح للقص");
	strcpy(sLengthofusedbars, "قياس القضبان المستخدمة");
	strcpy(sLicenseAgreement, "اتفاقية الترخيص");
	strcpy(sLinear, "خطي");
	strcpy(sLinethickness, "سماكة القلم");
	strcpy(sLoadafileandappenddatatothecurrentDemand, "تحميل ملف وإلحاق البيانات بالقطع الحالية.");
	strcpy(sLoadanexistingDemandfromafile, "تحميل القطع من ملف.");
	strcpy(sLoadAppend, "تحميل وإلحاق");
	strcpy(sLoadEverything, "تحميل كل شيء");
	strcpy(sLoadInventory, "تحميل المخزون");
	strcpy(sLoadInventoryandDemand, "تحميل المخزون والقطع");
	strcpy(sLoadResults, "تحميل النتائج");
	strcpy(sLocked, "مقفل");
	strcpy(sLogo, "شعار");
	strcpy(sLong, "طويل");
	strcpy(sLongerexecutiontime, "وقت تشغيل أطول");
	strcpy(sLungime, "الطول");
	strcpy(sLungimeanumar0, "يجب أن يكون الطول أكبر من 0!");
	strcpy(sLungimeanumarreal, "يجب أن يكون الطول رقمًا صحيحاً!");
	strcpy(sLungimeaTotalaFolosita, "إجمالي الطول المستخدم");
	strcpy(sMagnification, "تكبير");
	strcpy(sMagnify, "تكبير");
	strcpy(sMargins, "هوامش");
	strcpy(sMarginsForPaper, "هوامش الورقة");
	strcpy(sMarginsOfTheLabel, "هوامش اللصاقة");
	strcpy(sMaterial, "مواد");
	strcpy(sMaterialName, "اسم المادة");
	strcpy(sMaterials, "المواد");
	strcpy(sMaterialstypes, "أنواع المواد");
	strcpy(sMax, "الحد الأقصى");
	strcpy(sMaximalArea, "المساحة القصوى");
	strcpy(sMaximalCutLength, "أقصى طول للقص");
	strcpy(sMaxlength, "الحد الأقصى للطول");
	strcpy(sMaxPiecesperBar, "الحد الأقصى لعدد القطع لكل قضيب");
	strcpy(sMaxwidth, "الحد الأقصى للعرض");
	strcpy(sMeasurementUnit, "وحدة قياس");
	strcpy(sMin, "الحد الأدنى");
	strcpy(sMinimalBreakSize, "الحد الأدنى لقياس الكسر");
	strcpy(sMinimalUsefulSize, "الحد الأدنى من القياس المفيد");
	strcpy(sMinimalwastesizetoInventory, "الحد الأدنى لقياس المخلفات للإضافةإلى المخزون.");
	strcpy(s_What_to_minimize, "ما الذي يجب تقليله؟");
	strcpy(sMinlength, "الحد الأدنى للطول");
	strcpy(sMinwidth, "الحد الأدنى للعرض");
	strcpy(sMirror, "مرآة");
	strcpy(sMirroring, "التعاكس");
	strcpy(sMiscellaneous, "إحصائيات أخرى");
	strcpy(sModify, "تعديل");
	strcpy(sModifytheselectedpiece, "تعديل القطعة المحددة");
	strcpy(sMovePiece, "تحريك قطعة");
	strcpy(sMultiplestages, "مراحل متعددة");
	strcpy(sName, "الاسم");
	strcpy(sNameofedgeband, "اسم نطاق الحافة");
	strcpy(sNewDEMANDUnsaveddatawillbelost, "قطع جديدة؟ سيتم فقد البيانات غير المحفوظة!");
	strcpy(sNewLanguage, "لغة جديدة");
	strcpy(sNewMaterial, "مادة جديدة");
	strcpy(sNewPasswordincorectlyintroduced, "كلمة المرور الجديدة غير صحيحة!");
	strcpy(sNewProduct, "منتج جديد");
	strcpy(sNewversion, "نسخة جديدة");
	strcpy(sNo, "لا");
	strcpy(sNumarBucati, "عدد القطع");
	strcpy(sNumberOfCopies, "عدد النسخ");
	strcpy(sNumberofstages, "عدد المراحل");
	strcpy(sNusuficienteplacidepozit, "لم يتم احتساب جميع القطع.الأسباب المحتملة : لا يوجد قطع كافية في المخزون, القطع غير ممكّنة, طبيعة مواد القطع والمخزون مختلفة, تم تعيين العوامل الأخرى بشكل غير صحيح.لم يتم احتساب جميع القطع.الأسباب المحتملة : لا يوجد قطع كافية في المخزون, القطع غير ممكّنة, طبيعة مواد القطع والمخزون مختلفة, تم تعيين العوامل الأخرى بشكل غير صحيح.");
	strcpy(sOfficeNotInstaled, "لم يتم تثبيت مايكروسوفت أوفيس على جهاز الكمبيوتر الخاص بك أو أنالإصدار المثبت غير صحيح!");
	strcpy(sOldpassworddoesnotmatch, "كلمة المرور القديمة غير متطابقة!");
	strcpy(sOnlinehelp, "مساعدة على الانترنت");
	strcpy(sOnlypiecesofthesameheightinthelaststage, "القطع ذات الإرتفاع المتساوي في المرحلة الأخيرة");
	strcpy(sOpen, "فتح");
	strcpy(sOptimization, "الحساب الأمثل");
	strcpy(sOptimizationDone, "تم تنفيذ الحساب الأمثل! يمكنك طباعة أو حفظ الرسوم البيانية التي تم الحصول عليها. اضغط على زر قبول إذا كنت راضيًا عن الحل الحالي. أو اضغط على ابدأ مرة أخرى.");
	strcpy(sOptimizationType, "نوع الحساب الأمثل");
	strcpy(sOptions, "خيارات");
	strcpy(sOptionsrelatedtotheinterface, "الخيارات المتعلقة بالواجهة");
	strcpy(sor, "أو");
	strcpy(sOthercomponents, "المكونات الأخرى");
	strcpy(sOthers, "آخر");
	strcpy(sOtherstatistics, "إحصائيات أخرى");
	strcpy(sOverrideExcelCSVfiles, "تجاوز ملفات Excel / CSV");
	strcpy(sParameter, "عوامل");
	strcpy(sParts, "قطع");
	strcpy(sPattern, "نمط");
	strcpy(sPatternforwaste, "نمط المخلفات");
	strcpy(sPerimeter, "محيط");
	strcpy(sPermitedRotationAngle, "زاوية الدوران المسموح بها");
	strcpy(sPhone, "هاتف");
	strcpy(sPicture, "صورة");
	strcpy(sPiece, "قطعة");
	strcpy(sPieceindex, "أرقام القطع");
	strcpy(sPieces, "القطع");
	strcpy(sPiecesize, "قياس القطعة");
	strcpy(sPiecesizelabeledgebandwillbeprinted, "سيتم طباعة قياس القطعة، التسمية، نطاقات الحافة.");
	strcpy(sPierdere, "المخلفات");
	strcpy(sPixels, "بكسل");
	strcpy(sPlacilefolositeDepozit, "قطع مستخدمة من المخزون.");
	strcpy(sPlease_contact_us_at_contact_nestingtechnologies_com, "يرجى الاتصال بنا على contact@nesting-technologies.com");
	strcpy(sPlease_contact_us_at_contact_optimalprograms_com, "يرجى الاتصال بنا على contact@optimalprograms.com");
	strcpy(sPleaseenteralldataeitherasfractionalorrealDonotmixthem, "الرجاء إدخال جميع البيانات إما كقيم عشرية أو قيم صحيحة! بلا خلط!");
	strcpy(sPleaseEnterSomeTypesOfMaterials, "لم يتم تحديد أي نوع من المواد. يمكنك تحديدها من قائمة المواد.");
	strcpy(sPleasesendtheNameandtheCodetotheaddresscontactoptimalprogramscominordertoobtaintheRegistrationKey, "للحصول على مفتاح التسجيل ، يرجى إرسال الاسم والرمز إلى: contact@optimalprograms.com.");
	strcpy(sPolygon, "مضلع");
	strcpy(sPolygonsCircles, "مضلعات ، دوائر");
	strcpy(sPrecision, "الدقة");
	strcpy(sPretulnumar0, "يجب أن يكون السعر أكبر من الصفر!");
	strcpy(sPretulnumarreal, "يجب أن يكون السعر رقم صحيح!");
	strcpy(sPreview, "معاينة");
	strcpy(sPrice, "السعر");
	strcpy(sPriceMustBeGreaterThanZero, "يجب أن يكون السعر أكبر من الصفر");
	strcpy(sPriceofbars, "سعر القضبان");
	strcpy(sPriceperbar, "سعر القضيب");
	strcpy(sPricepersheet, "سعر اللوح");
	strcpy(sPricepersquareunitofmaterial, "سعر الوحدة المربعة من المادة");
	strcpy(sPriceperunit, "سعر الوحدة");
	strcpy(sPrint, "طباعة");
	strcpy(sPrintdiagramsastables, "طباعة المخططات كجداول.");
	strcpy(sPrinter, "طابعة");
	strcpy(sPrinterBounds, "هوامش الطابعة");
	strcpy(sPrinting, "الطباعة");
	strcpy(sPrintonlyutilizedarea, "اطبع المنطقة المستخدمة فقط");
	strcpy(sPrintthecontentsoftheDemand, "طبع محتويات القطع.");
	strcpy(sPrintthecontentsoftheInventory, "طبع محتويات المخزون.");
	strcpy(sPrintthecurrentsolution, "طبع الحل الحالي.");
	strcpy(sPriority, "أولوية");
	strcpy(sPrioritytocutapieceZero0isthehighestpriority, "الأولوية لقص قطعة. الصفر (0) هو الأولوية القصوى.");
	strcpy(sProcentul0100, "يجب أن تكون النسب المئوية أكبر من 0 وأقل أو تساوي 100!");
	strcpy(sProcentulnumarreal, "يجب أن تكون النسب المئوية أرقام صحيحة!");
	strcpy(sProductdefinition, "التعريف بالمنتج");
	strcpy(sProductExists, "المنتج موجود بالفعل. اختر اسمًا آخر.");
	strcpy(sProductName, "اسم المنتج");
	strcpy(sProducts, "منتجات");
	strcpy(sProducts, "منتجات");
	strcpy(sProject, "مشروع");
	strcpy(sProperties, "الخصائص");
	strcpy(sProperty, "خاصية");
	strcpy(sQuantity, "الكمية");
	strcpy(sQuantitynumberofsheetsofthistype, "عدد الألواح من هذا النوع");
	strcpy(sRadius, "نصف القطر");
	strcpy(sRectangular, "مستطيلي");
	strcpy(sRedefinetypesofedgeband, "إعادة تعريف أنواع نطاق الحافة");
	strcpy(sRedefinetypesofmaterial, "إعادة تعريف أنواع المواد");
	strcpy(sRegistration, "التسجيل");
	strcpy(sRegistrationKeyfromOptimalPrograms, "مفتاح التسجيل");
	strcpy(sRegistrationSuccessful, "تم التسجيل بنجاح!");
	strcpy(sRemoveallpiecesinInventory, "إزالة جميع القطع في المخزون.");
	strcpy(sRemoveCut, "حذف القص");
	strcpy(sRemovetheselectedpiece, "حذف القطعة المحددة");
	strcpy(sReports, "التقارير");
	strcpy(sRequestedMaterial, "المواد المطلوبة");
	strcpy(sRestore, "استعادة");
	strcpy(sResults, "النتائج");
	strcpy(sReusedwaste, "ضياعات معاد استخدامها");
	strcpy(sRight, "حق");
	strcpy(sRightcoordinateofthedefect, "إحداثيات العيب من الجانب الأيمن");
	strcpy(sRotation, "دوران");
	strcpy(sRotationAngle, "زاوية الدوران");
	strcpy(sRotationStep, "خطوة الدوران");
	strcpy(sRoundAllFractionsTo, "يجب تقريب القيم العشرية إلى");
	strcpy(sRow, "سطر");
	strcpy(sRows, "السطور");
	strcpy(sRun, "أحدث الحلول");
	strcpy(sRunningtime, "زمن التشغيل");
	strcpy(sSameforall, "نفس الشيء للجميع");
	strcpy(sSave, "حفظ");
	strcpy(sSaveAllImages, "حفظ جميع الصور");
	strcpy(sSaveAs, "حفظ باسم");
	strcpy(sSaveChanges, "تم تغيير القطع. هل تريد حفظها؟");
	strcpy(sSaveCurrentImage, "حفظ الصورة الحالية");
	strcpy(sSavedataparameters, "حفظ البيانات والعوامل");
	strcpy(sSaveEverything, "حفظ كل شيء");
	strcpy(sSaveInventory, "حفظ المخزون");
	strcpy(sSaveInventoryandDemand, "حفظ المخزون القطع");
	strcpy(sSaveResults, "حفظ النتائج");
	strcpy(sSaveStatisticsinafile, "حفظ الإحصائيات في ملف");
	strcpy(sSavethecurrentimage, "حفظ الصورة الحالية");
	strcpy(sSavethecurrentimageorstatistic, "حفظ الصورة الحالية أو الإحصائيات");
	strcpy(sSavetheDEMANDinafile, "حفظ الملف");
	strcpy(sSavetheDemandinafilewithadifferentname, "افظ القطع في ملف باسم مختلف.");
	strcpy(sSavetheREPOSITORYinafile, "حفظ المخزون في ملف");
	strcpy(sSerialNumber, "مفتاح التسجيل");
	strcpy(sService, "خدمة");
	strcpy(sSetDefaultValues, "سيؤدي هذا إلى استعادة جميع الخصائص إلى قيمها الافتراضية. ستفقد جميع الإعدادات الخاصة بك. هل انت متأكد من أنك تريد أن تفعل هذا؟");
	strcpy(sSetedgeband, "ضبط نطاق الحافة");
	strcpy(sSetedgetrim, "ضبط قياس القص لهوامش العيوب");
	strcpy(sSetthesameedgebandforalledges, "ضبط نفس نطاق الحافة لجميع الجوانب.");
	strcpy(sSetthesamegrindingforalledges, "ضبط نفس الطحن لجميع الحواف.");
	strcpy(sSetthesametrimforalledges, "ضبط نفس القص للعيوب لجميع الحواف");
	strcpy(sSettings, "الإعدادات");
	strcpy(sShape, "شكل");
	strcpy(sSheet, "لوح");
	strcpy(sSheetsBarstypes, "أنواع الألواح_القضبان");
	strcpy(sSheetSize, "قياس اللوح");
	strcpy(sSheetsperPage, "الألواح لكل صفحة");
	strcpy(sShort, "قصيرة");
	strcpy(sShorterexecutiontime, "زمن تشغيل قصير");
	strcpy(sShowallsimpleproducts, "عرض جميع المنتجات البسيطة");
	strcpy(sShowcustomername, "إظهار اسم الزبون");
	strcpy(sShowCustomTextOnEachPiece, "إظهار نص مخصص على كل قطعة");
	strcpy(sShowdiagramasatable, "عرض الرسم البياني كجدول.");
	strcpy(sShowedgeband, "إظهار نطاقات الحافة");
	strcpy(sShowedgebandssettinginanewwindow, "عرض إعدادات نطاقات الحافة في نافذة جديدة.");
	strcpy(sShowgrindingsettingsinanewwindow, "عرض إعدادات الطحن في نافذة جديدة.");
	strcpy(sShowHorizontalLabelsAlways, "إظهار التسميات الأفقية دائمًا");
	strcpy(sShowRemovethesizeofthepiecesinthecurrentsolution, "إظهار / إخفاء قياس القطع.");
	strcpy(sShowRemovethesizeofthewastesinthecurrentsolution, "إظهار / إخفاء قياس المخلفات.");
	strcpy(sShowtotalcutlength, "عرض طول القص الكلي");
	strcpy(sShowtrimedgesettingsinanewwindow, "عرض إعدادات العيوب في نافذة جديدة");
	strcpy(sSimpleMaterialExists, "تم تحديد اسم المادة مسبقاً في قائمة المواد. يرجى إعطاء اسم جديد.");
	strcpy(sSinglePieceStrips, "خطوط قطعة واحدة.");
	strcpy(sSizes, "الأحجام");
	strcpy(sSmallerorequalto, "أصغر أو يساوي");
	strcpy(sSort, "فرز");
	strcpy(sSortAscendingByArea, "فرز حسب المساحة بترتيب تصاعدي");
	strcpy(sSortDescendingByArea, "فرز حسب المساحة بترتيب تنازلي");
	strcpy(sSpecifyhowdifferentthepiecesinthelaststagecanbeValue0meansnodifference, "حدد مدى اختلاف القطع في المرحلة الأخيرة. القيمة 0 تعني عدم وجود فرق.");
	strcpy(sSpecifyifpiecesinthelaststagecanbedifferentornotdepeultimaetapapotfidiferitesaunucadimensiune, "حدد ما إذا كانت القطع في المرحلة الأخيرة يمكن أن تكون مختلفة أم لا");
	strcpy(sSpecifyifthepiececanberotatedornotIfnotitwillbecutinthesamewayasitwasintroducedinDemandLengthofthepieceparalleltothelengthofthesheet, "حدد ما إذا كان يمكن تدوير القطعة أم لا. إذا لم يكن كذلك ، يتم وضعها بنفس الطريقة التي تم تقديمها بها (طول القطعة موازية لطول اللوح) ،");
	strcpy(sSpecifyinhowmanystageswemakethecutsDuringastageallcutshavethesamedirection, "حدد عدد المراحل للقص.");
	strcpy(sStartthesearchprocess, "ابدأ عملية البحث");
	strcpy(sStatistics, "إحصائيات");
	strcpy(sStatisticsE, "تقارير اضافية");
	strcpy(sStatisticsforeachtypeofmaterial, "إحصائيات لكل نوع من أنواع المواد");
	strcpy(sStep, "خطوة");
	strcpy(sStergeDepozit, "هل تريد حذف المخزون؟");
	strcpy(sStergeMaterial, "هل تريد حذف المادة؟");
	strcpy(sStergePiesele, "هل تريد حذف القطعة؟");
	strcpy(sStergePiesa, "هل تريد حذف القطعة؟");
	strcpy(sStopthesearchprocess, "أوقف عملية البحث");
	strcpy(sStrongoptimization, "حساب قوي");
	strcpy(sSubtractthebandthicknessfrompiecesize, "تقليل قياس القطع بسماكة شريط الحافة");
	strcpy(sSummary, "ملخص");
	strcpy(sSuprafataTotalaFolosita, "إجمالي المساحة المستخدمة");
	strcpy(sSuprafatautilizata, "الإستخدام");
	strcpy(sSwitchbetweenfiberandrotationoption, "خيار التبديل بين الألياف والدوران.");
	strcpy(sTechnical, "تقني");
	strcpy(sTechnicalsettings, "الإعدادات الفنية");
	strcpy(sTemporaryPanelHint, "لوح مؤقت لنقل القطع بين الألواح.");
	strcpy(sText, "نص");
	strcpy(sThe_application_has_expired, "انتهت صلاحيةالتطبيق .");
	strcpy(sThe_application_is_not_registered, "التطبيق غير مسجل.");
	strcpy(sThe_application_was_first_started_on, "تم بدء التطبيق لأول مرة في");
	strcpy(sThecutsareperformedfromasidetotheothersideofthematerial, "يتم إجراء القص من جانب إلى الجانب الآخر من المادة.");
	strcpy(sThecuttingmachinecanfollowtheshapeofthematerial, "يمكن لآلة القص أن تتبع شكل القطعة.");
	strcpy(sTheedgesofsheetsthatmustbetrimedduefaults, "حواف الألواح التي يجب تشذيبها بسبب العيوب");
	strcpy(sTheLargestSize, "أكبر قياس");
	strcpy(sThenameofthecustomerforwhichyoucutthepiece, "اسم الزبون الذي قصت القطعة من أجله.");
	strcpy(sThenameofyourcustomer, "اسم زبونك");
	strcpy(sThepiececanberotated, "يمكن تدوير القطعة");
	strcpy(sTheprogramtriestoavoidwasteswhichhavebothsizeslessthanthisvalue, "يحاول البرنامج تجنب المخلفات التي تكون أصغر من هذه القيمة");
	strcpy(sThereAreNoProducts, "لا توجد منتجات محددة حتى الان");
	strcpy(sThestockofmaterialhasbeenpreviouslyloadedfromanExcelorCSVformatPleaseloaditagain, "تم تحميل مخزون المواد مسبقًا من تنسيق Excel أو CSV. يرجى تحميله مرة أخرى إذا كنت ترغب في العمل عليه.");
	strcpy(sThetotallengthofcutting, "الطول الكلي للقص");
	strcpy(sThewidthofthecuttingsawForglasscuttingoptimizationitcanbe0Forwooditshouldbegreaterthan0, "سماكة المنشار. لقص الزجاج يمكن أن يكون 0. لقص الخشب يجب أن يكون أكبر من 0.");
	strcpy(sThewidthofthecuttingsawforlinearpieces, "سماكة المنشار للقطع الخطية.");
	strcpy(sThickness, "السماكة");
	strcpy(sThischaracterisusedforfillingthewasterectanglesIfyoudonotwantfilledwastejustremovethischaracter, "يستخدم هذا الرمز لملء مستطيلات الضياع. إذا كنت لا تريد ضياعات مملوءة فقط قم بإزالته.");
	strcpy(sThisindexhasvaluebetween1andthenumberofpieces, "هذا المؤشر له قيمة بين 1 وعدد القطع.");
	strcpy(sThisOptionWillOverrideTheInventoryFileIfLoadedFromExcelOrCsvFiles, "سيؤدي هذا الخيار إلى تجاوز ملف المخزون إذا تم تحميله من ملفات excel أو csv.");
	strcpy(sThisProgramisLicensedTo, "هذا البرنامج مرخص لـ");
	strcpy(sThisvaluewillbeaddedtotheedgebandingmaterialoneachside, "ستتم إضافة هذه القيمة إلى نطاقات الحواف على كل جانب");
	strcpy(sTipNevid, "لا يمكن أن يكون نوع المادة فارغًا.");
	strcpy(sTitle, "لقب");
	strcpy(sTools, "أدوات");
	strcpy(sTop, "أعلى");
	strcpy(sTopcoordinateofthedefect, "الإحداثي العلوي للخلل.");
	strcpy(sTotalGarbageWaste, "جميع المخلفات المهملة");
	strcpy(sTotalInventoryWaste, "إجمالي مخلفات المخزون");
	strcpy(sTotalRecycledWaste, "جميع المخلفات المعاد استخدامها");
	strcpy(sTotalusedarea, "إجمالي المساحة المستخدمة");
	strcpy(sTotalusedlength, "إجمالي الطول المستخدم");
	strcpy(sTrigonometric, "حساب المثلثات");
	strcpy(sTrim, "التشذيب");
	strcpy(sTrimalledgesatthebeginning, "تشذيب كل الحواف في البداية");
	strcpy(sTrimEdge, "تشذيب الحافة");
	strcpy(sTwoPanels, "واجهة واحدة");
	strcpy(sType, "نوع");
	strcpy(sTypeofmaterialfromwhichtocut, "نوع المواد المراد قصها");
	strcpy(sTypesAreNotMatched, "لم يتم إجراء التحسين! المواد من جدولي القطع والمخزون غير متطابقة! يمكن قص قطعة فقط من المادة التي تحمل الاسم نفسه في المخزون. غيّر اسم المواد من الأعمدة المقابلة!");
	strcpy(sUndo, "تراجع");
	strcpy(sUndoAccept, "تراجع عن القبول");
	strcpy(sUnits, "الوحدات");
	strcpy(sUnregisteredVersion, "غير مسجلة");
	strcpy(sUpdates, "التحديثات");
	strcpy(sUsefulforwoodfurniture, "مفيد للأثاث الخشبي");
	strcpy(sUseit, "استخدمه");
	strcpy(sUsePieceinOptimization, "استخدم القطعة في الحساب");
	strcpy(sUserName, "اسم المستخدم");
	strcpy(sUtilizationandWastes, "الاستخدام والمخلفات");
	strcpy(sUtilizedArea, "مساحة القطع المستخدمة");
	strcpy(sUtilizedBars, "قضبان مستخدمة");
	strcpy(sUtilizeddemandcount, "عدد القطع المستخدمة");
	strcpy(sUtilizedParts, "القطع المستخدمة");
	strcpy(sUtilizedPieces, "قطع مستخدمة");
	strcpy(sUtilizedSheets, "ألواح مستخدمة");
	strcpy(sValue, "القيمة");
	strcpy(sValueGreaterEqualToZero, "يجب أن تكون القيمة أكبر من أو تساوي الصفر");
	strcpy(sValueGreaterThanZero, "يجب أن تكون القيمة أكبر من الصفر");
	strcpy(sValueIntegerNumber, "يجب أن تكون القيمة عددًا صحيحًا!");
	strcpy(sValueRealNumber, "يجب أن تكون القيمة رقمًا صحيحاً. ربما كنت قد استخدمت الفاصلة بدلا من النقطة أو العكس. يرجى التعديل!");
	strcpy(s_The_number_is_too_big_or_it_has_too_many_digits_after_decimal_separator, "الرقم كبير جدًا أو يحتوي على عدد كبير جدًا من الأرقام بعد الفاصل العشري!");
	strcpy(s_The_number_is_too_big, "الرقم كبير جدا!");
	strcpy(sVertical, "عمودي");
	strcpy(sWaste, "المخلفات");
	strcpy(sWastes, "المخلفات");
	strcpy(sWasteAddedToWarehouse, "أضيفت المخلفات إلى المخزون");
	strcpy(sWastelimits, "نطاق المخلفات");
	strcpy(sWasteType, "نوع المخلفات");
	strcpy(sWeakoptimization, "أضعف حساب");
	strcpy(sWhattoprint, "ماذا يجب أن أطبع");
	strcpy(s_What_to_print_or_save_to_file, "ما يجب طباعته أو حفظه في ملف");
	strcpy(sWhattoprintoneachpiece, "ماذا يطبع على كل قطعة");
	strcpy(sWhattoshowoneachpiece, "ماذا يظهر على كل قطعة؟");
	strcpy(sWidth, "عرض");
	strcpy(sWood, "خشب");
	strcpy(sWorkingDirectory, "مجلد العمل");
	strcpy(sWrongKey, "مفتاح تسجيل خاطئ!");
	strcpy(sYes, "نعم");
	strcpy(sYoucannotchooseblackblueorredcolors, "لا يمكنك اختيار ألوان سوداء أو زرقاء أو حمراء.");
	strcpy(sYouCannotMixFractionalDataWithDecimalOnes, "لا يمكنك مزج القيم العشرية مع القيم الصحيحة!");
	strcpy(sYourcompany, "شركتك");
	strcpy(sZip, "الكود البريدى");
	strcpy(s_Set_the_origin_and_the_direction_of_the_axes, "عيّن أصل واتجاه محاور الإحداثيات.");










	strcpy(s_Number_of_digits_after_the_decimal_separator, "عدد الأرقام بعد الفاصل العشري");
	strcpy(s_Percentages, "النسب المئوية");
}

