// Language strings: Francais
// Author: Optimal Programs
// License: MIT License
//---------------------------------------------------------------------------
#include <string.h>
//---------------------------------------------------------------------------
#include "language_string_id.h"
//---------------------------------------------------------------------------
void set_fr(void)
{
	//Francais
	// needs human check
	// last update on: 2025.9.25.0
	strcpy(s_Area, "Aire");
	strcpy(s_Mass, "Masse");
	strcpy(s_Advanced, "Avancée");
	strcpy(s_Relative_coordinates, "Coordonnées relatives");
	strcpy(s_Absolute_coordinates, "Coordonnées absolues");
	strcpy(s_Append_more_rows, "Ajouter plus de lignes");

	strcpy(s_Add_to_parts, "Ajouter aux pièces.");
	strcpy(s_Additional, "Supplémentaire");
	strcpy(s_All_results, "Tous les résultats.");
	strcpy(s_Allow_movement_of_pieces, "Permettre le mouvement des pièces");
	strcpy(s_Allow_part_in_part, "Autoriser pièce par pièce");
	strcpy(s_Invalid_piece_Angles_are_too_small_or_too_big_or_height_is_too_small, "Pièce non valide ! Les angles sont trop petits ou trop grands, ou la hauteur est trop petite.");
	strcpy(s_Append, "Ajouter");
	strcpy(s_As_it_is, "Tel quel");
	strcpy(s_As_text, "Comme texte");
	strcpy(s_Ascending, "Ascendante");
	strcpy(s_Automatic, "Automatique");
	strcpy(s_Cannot_connect_to_the_Internet_Please_visit_our_website_from_a_browser, "Impossible de se connecter à Internet! Veuillez visiter notre site Web à partir d'un navigateur.");
	strcpy(s_Cannot_copy_or_move_the_files, "Impossible de copier ou de déplacer les fichiers!");
	strcpy(s_Cannot_delete_the_file, "Impossible de supprimer le fichier!");
	strcpy(s_Cannot_modify_old_results, "Impossible de modifier les anciens résultats !");
	strcpy(s_To_change_click_inside_a_cell_or_press_0_1_or_2, "Pour changer, cliquez dans une cellule ou appuyez sur 0, 1 ou 2.");
	strcpy(s_Cell, "Cellule");
	strcpy(s_Click_on_the_table_header_to_change_the_columns, "Cliquez sur l'en-tête du tableau pour changer les colonnes.");
	strcpy(s_Close, "Ferme le");
	strcpy(s_Contact_us, "Contactez-nous");
	strcpy(s_Column, "Colonne");
	strcpy(s_Comma, "Virgule");
	strcpy(s_The_comma_symbol_cannot_simultaneously_be_the_list_separator_and_the_decimal_separator, "Le symbole virgule ne peut pas être simultanément le séparateur de liste et le séparateur décimal !");
	strcpy(s_Copy, "Copie");
	strcpy(s_Copy_for_move, "Copier pour déplacer");
	strcpy(s_Cut_higher_level_strips_first, "Coupez d'abord les bandes de niveau supérieur");
	strcpy(s_Cut_index, "indice de coupe");

	strcpy(s_The_data_have_been_changed_Do_you_want_to_save_them_to_a_file, "Les données ont été modifiées. Voulez-vous les enregistrer dans un fichier?");
	strcpy(s_Decimal_separator, "Séparateur décimal");
	strcpy(s_Restore_default_settings, "Restaurer les paramètres par défaut");
	strcpy(s_Delete_fiber, "Supprimer la fibre");
	strcpy(s_Descending, "Descendante");
	strcpy(s_Discard_changes, "Annuler les modifications");

	strcpy(s_Delete_all_data, "Supprimer toutes les données ?");
	strcpy(s_Dot, "Point");
	strcpy(s_Do_you_want_to_delete_the_picture, "Voulez-vous supprimer l'image?");
	strcpy(s_Do_you_want_to_delete_the_product, "Voulez-vous supprimer le produit?");
	strcpy(s_Duplicate_and_append, "Dupliquer et ajouter.");
	strcpy(s_Duplicate_values_are_ignored, "Les valeurs en double ont été ignorées!");
	strcpy(s_Error, "Erreur");
	strcpy(s_Error_loading_file, "Erreur lors du chargement du fichier.");
	strcpy(s_export_everything, "Exporter tout");
	strcpy(s_Fit_to_screen, "Ajuster à l'écran.");
	strcpy(s_Force_fixed_height, "Dessinez les pièces avec une hauteur fixe.");
	strcpy(s_Flipped, "Renversée");
	strcpy(s_Import, "Importation");
	strcpy(s_If_angles_are_different_from_90_degrees_height_must_be_greater_than_0, "Si les angles sont différents de 90 degrés, la hauteur doit être supérieure à 0.");
	strcpy(s_Ignore, "Ignorer");
	strcpy(s_Incorrect_value, "Valeur incorrecte");
	strcpy(s_Info, "Info");
	strcpy(s_Interior, "Intérieur");
	strcpy(s_Give_a_name, "Donnez un nom.");
	strcpy(s_Group, "Regroupez-le");
	strcpy(s_Header, "Entête");
	strcpy(s_Keep_it_as_it_is, "Gardez-le tel quel");
	strcpy(s_Level, "Level");
	strcpy(s_Licensee, "Licenciée");
	strcpy(s_List_separator, "Séparateur de liste");
	strcpy(s_Made_with_love_in_Cugir_Romania, "Fabriqué avec amour à : Cugir, Roumanie");
	strcpy(s_Made_in, "Fabriqué en");
	strcpy(s_Manufacturer, "Fabricant");

	strcpy(s_Manual_arrange, "Organiser manuellement");

	strcpy(s_Mixed, "Mixte");
	strcpy(s_Multiple_shapes_detected_Next_rows_will_be_overwritten_Continue, "Plus d'une forme a été détectée. Par conséquent, les lignes suivantes seront écrasées. Continuez?");
	strcpy(s_More, "Suite");
	strcpy(s_Multiple_values, "Valeurs multiples");
	strcpy(s_No_texture, "Aucune texture");
	strcpy(s_Number, "Nombre");
	strcpy(s_Number_of_images, "Nombre d'images");
	strcpy(s_Number_of_vertices, "Nombre de sommets");
	strcpy(s_Offset, "Compenser");
	strcpy(s_Only_the_currently_selected_items, "Uniquement les éléments actuellement sélectionnés.");
	strcpy(s_Optimizing_please_wait, "Optimisation... veuillez patienter.");

	strcpy(s_Paste, "Paste");

	strcpy(s_Piece_label, "L'étiquette de la pièce");
	strcpy(s_Piece_size, "Taille des pièces");
	strcpy(s_Please_contact_us_by_email_if_you_receive_this_error, "Veuillez nous contacter par e-mail si vous recevez cette erreur.");
	strcpy(s_Please_save_it_first, "S'il vous plaît, enregistrez-le d'abord.");
	strcpy(s_Position, "Positionner");
	strcpy(s_Preview, "Aperçu");
	strcpy(s_Rectangle, "Rectangle");

	strcpy(s_Redo_the_last_operation, "Restaurer la dernière opération");
	strcpy(s_Regular_polygon, "Polygone régulier");

	strcpy(s_Reused, "Réutilisé");
	strcpy(s_Rotated, "Rotation");
	strcpy(s_Save_all, "Sauver tous");
	strcpy(s_Scrap_label, "Étiquette de ferraille");
	strcpy(s_Scrap_size, "Taille de la ferraille");
	strcpy(s_Semicolon, "Point-virgule");
	strcpy(s_Show_cut_index, "indice de coupe");
	strcpy(s_Show_information, "Montrer l'information");
	strcpy(s_Show_piece_label, "L'étiquette de la pièce");
	strcpy(s_Show_scrap_label, "Étiquette de ferraille");
	strcpy(s_Show_scrap_s_size_on_the_small_pieces, "Afficher la taille des rebuts sur les petits morceaux");
	strcpy(s_Show_size_of_pieces, "Taille des pièces");
	strcpy(s_Show_size_of_scrap, "Taille de la ferraille");
	strcpy(s_Show_sizes, "Afficher les tailles");
	strcpy(s_Show_label, "Afficher l'étiquette");
	strcpy(s_Show_length, "Afficher la longueur");

	strcpy(s_Some_numerical_values_are_incorrect_Should_I_fix_all_the_incorrect_values, "Certaines valeurs numériques sont incorrectes! Dois-je corriger toutes les valeurs incorrectes?");
	strcpy(s_Some_invalid_values_have_been_removed, "Certaines valeurs invalides ont été supprimées.");
	strcpy(s_Sort_by, "Trier par");
	strcpy(s_Sort_ascending_by, "Trier par ordre croissant");
	strcpy(s_Sort_descending_by, "Trier par ordre décroissant");
	strcpy(s_Start, "Start");
	strcpy(s_Starting_angle, "Angle de départ");


	strcpy(s_Stock, "Stocker");
	strcpy(s_Stop, "Stop");
	strcpy(s_System_setting, "Paramétrage du système");
	strcpy(s_Tabular, "Tabulaire");
	strcpy(s_Total, "Totale");
	strcpy(s_Total_size, "Taille totale");
	strcpy(s_Terms_of_the_license, "Termes de la licence");
	strcpy(s_The_current_product_has_been_changed_Do_you_want_to_save_it_to_file, "Le produit actuel a été modifié. Voulez-vous l'enregistrer dans un fichier?");
	strcpy(s_The_value_is_out_of_the_allowed_range, "La valeur est hors de la plage autorisée.");
	strcpy(s_The_value_must_be_a_real_or_fractional_number_Try_to_replace_the_comma_with_the_dot_if_you_want_to_enter_a_real_number, "La valeur doit être un nombre réel ou fractionnaire. Essayez de remplacer la virgule par le point si vous souhaitez entrer un nombre réel.");
	strcpy(s_This_feature_is_not_implemented_yet, "Cette fonctionnalité n'est pas encore implémentée.");
	strcpy(s_This_operation_cannot_be_reversed, "Cette opération ne peut pas être annulée.");
	strcpy(s_Undo_the_last_operation, "Annulez la dernière opération.");
	strcpy(s_Utilization, "Utilisation");
	strcpy(s_Utilized_Stock, "Stock utilisé");
	strcpy(s_Version, "Version");
	strcpy(s_Visible_columns, "Colonnes visibles");
	strcpy(s_You_already_have_the_latest_version_installed, "Vous avez déjà installé la dernière version!");
	strcpy(s_What_is_exported, "Qu'est-ce qui est exporté ?");
	strcpy(s0meansanynumberofpieces, "Zéro pour un nombre arbitraire de pièces");
	strcpy(sAbout, "A propos de...");
	strcpy(sAccept, "Accepter");
	strcpy(sAcceptall, "Accepter tout");
	strcpy(sAcceptthecurrentsolution, "Accepter la solution courante");
	strcpy(sAdd, "Ajouter");
	strcpy(sAddapiece, "Ajouter un morceau");
	strcpy(sAddasimpleproducttoDemand, "Ajouter un produit à la demande existante");
	strcpy(sAddgrindingthicknesstopartsize, "Ajouter l'épaisseur de broyage");
	strcpy(sAddproductnametolabel, "Ajouter le nom du produit à l'étiquette");
	strcpy(sAddress, "Adresse");
	strcpy(sAddselectedsizetoInventory, "Ajoutez la taille sélectionnée au stock");
	strcpy(sAdhesivelabels, "Etiquettes adhésives");
	strcpy(sAdhesivelabelwithinformationaboutpiecesinDemandCustomernameLabelSizeCurrentData, "Étiquette adhésive avec des informations sur les pièces: nom du client, étiquette, taille, données actuelles, etc.");
	strcpy(sAdhesivelabelwithinformationaboutsheetsinInventory, "Etiquette adhésive avec informations sur les  feuilles dans l'inventaire");
	strcpy(sAll, "Toute");
	strcpy(sAlloffcutswhichhavethesizegreaterthanthisvaluewillbeaddedtoInventory, "Tous les rebuts supérieurs à cette valeur seront ajoutés au stock");
	strcpy(sAllowMirroring, "Autoriser le retournement");
	strcpy(sAllowRotation, "Autoriser la rotation");
	strcpy(sAllPieces, "Tous les morceaux");
	strcpy(sAllpredefinedproducts, "Tous les produits prédéfinis");
	strcpy(sAnewwindowwillbedisplayedwheretheusercansettheedgebandsforeachedge, "Affiche une nouvelle fenêtre dans laquelle l'utilisateur peut définir les bandes de bord pour chacun des bords");
	strcpy(sAnewwindowwillbedisplayedwheretheusercansetthegrindingvalueforeachedgeofthsheet, "Affiche une nouvelle fenêtre dans laquelle l'utilisateur peut régler la valeur de ponçage pour chaque bord de la pièce");
	strcpy(sAnewwindowwillbedisplayedwheretheusercansetthetrimvalueforeachedgeofthsheet, "Affiche une nouvelle fenêtre dans laquelle l'utilisateur peut définir les défauts de chaque bord de la pièce");
	strcpy(sAngle, "Angle");
	strcpy(sAngles, "Angles");
	strcpy(sAnoptimizationparameterisarealnumber, "L'un des paramètres d'optimisation est un nombre rée");
	strcpy(sAnoptimizationparameterisfractionalnumber, "L'un des paramètres d'optimisation est un nombre fractionnaire");
	strcpy(sAnyShape, "Forme quelconque !");
	strcpy(sApolygonmusthaveatleast3vertices, "Un polygone doit comporter au moins 2 arêtes !");
	strcpy(sApolygonmusthaveatleast3vertices, "Un polygone doit comporter au moins 3 arêtes !");
	strcpy(sApplication_fails_to_initialize, "Le logiciel a échoué initialisation.");
	strcpy(sArc, "Arc");
	strcpy(sArcLength, "Longueur de l'arc");
	strcpy(sAreaofusedsheets, "Superficie des feuilles utilisées");
	strcpy(sAshortdescriptionofthesheet, "Brève description de la feuille");
	strcpy(sAtleastonepart, "Au moins une pièce doit être introduite");
	strcpy(sAtTheMarginOfTheSheet, "Au bord de la feuille");
	strcpy(sBandtypes, "Types de bande de chant");
	strcpy(sBar, "Barres / tuyaux");
	strcpy(sBars, "Barres / tuyaux");
	strcpy(sBothsizesoftheoffcutsmustbegreaterthanthisvalue, "Les deux tailles des chutes doivent être supérieures à cette valeur");
	strcpy(sBottom, "Fond");
	strcpy(sBottomcoordinateofthedefect, "La coordonnée du fond du défaut");
	strcpy(sBreakCut, "Casser la coupe");
	strcpy(sBrowse, "Feuilleter");
	strcpy(sBuy, "Acheter");
	strcpy(sBuynow, "Acheter maintenant...");
	strcpy(sCancel, "Annuler");
	strcpy(sCannotBeEmpty, "ne peut pas être vide !");
	strcpy(sCannotmovepartsbetweensheetswhenidenticalsheetsaregroupedPleaseungroupthesheetsfrommenu, "Impossible de déplacer les éléments d'une feuille à l'autre si les feuilles identiques sont regroupées. Veuillez annuler le regroupement des feuilles à partir du menu");
	strcpy(sCannotSaveFile, "Impossible d'enregistrer le fichier ");
	strcpy(sCenter, "Centre");

	strcpy(sChangeDirection, "Changez la direction");
	strcpy(sChoose, "Choisir");
	strcpy(sChooseProduct, "Choisir un produit");
	strcpy(sCircle, "Cercle");
	strcpy(sCity, "Ville");
	strcpy(sClear, "Effacer");
	strcpy(sClockWise, "Dans le sens horaire");
	strcpy(sClosewindow, "Fermer la fenêtre");
	strcpy(sColor, "Couleur");
	strcpy(sColorofedgeband, "La couleur de la bande de chant");
	strcpy(sColorPattern, "Couleur / Motif");
	strcpy(sColorpiecesandwastes, "Pièces et déchets colorés");
	strcpy(sColumns, "Colonnes");
	strcpy(sComment, "Commentaire");
	strcpy(sCompanyname, "Raison sociale");
	strcpy(sComplexMaterialExists, "Ce nom est déjà utilisé dans la liste des matériaux complexes. Donner un autre nom");
	strcpy(sComputerCode, "Code informatique");
	strcpy(sComputerCodefromyourcomputer, "Code informatique (à partir de votre ordinateur)");
	strcpy(sComputethetotalpriceofDemand, "Calculer le prix total de la demande");
	strcpy(sContents, "Contenu");
	strcpy(sContinutComanda, "Contenu de la demande en date");
	strcpy(sContinutDepozit, "Contenu de l'inventaire en date");
	strcpy(sConversionIsDoneOnlyWhenSomePiecesHaveFractionalValues, "La conversion est effectuée seulement lorsque certaines pièces ont des valeurs fractionnaires.");
	strcpy(sConvertsTheSizeOfWasteToAFractionalUnit, "Affiche la taille des déchets sous forme de fraction.");
	strcpy(sCouldNotSaveFile1, "Impossible d'écrire le fichier dans le répertoire ");
	strcpy(sCouldNotSaveFile2, "Vous ne possédez pas des droits suffisants. Vérifiez le répertoire de travail ou modifiez-le vers un emplacement où vous possédez les droits d'écriture (par exemple c:\\temp) à partir du menu Paramètres | répertoire de travai");
	strcpy(sCreationdateYMDHMS, "Date de création (Année / Mois / Date, Heure:Minutes:Secondes)");
	strcpy(sCurrentDate, "Date courante");
	strcpy(sCurrentDiagram, "Diagramme actuel");
	strcpy(sCurrentMaterial, "Matériel courant");
	strcpy(sCurrentversion, "Version actuelle");
	strcpy(sCurve_not_closed_Try_increasing_DXF_linking_distance_parameter, "Le polygone n'est pas fermé! Essayez d'augmenter le paramètre Distance de liaison DXF.");
	strcpy(sCustomer, "Client");
	strcpy(sCustomerName, "Nom du client");
	strcpy(sCustomMessage, "Message personnalisé");
	strcpy(sCutlength, "Longueur de la coupe");
	strcpy(sCut, "Couper");
	strcpy(sCuts, "Coupes");
	strcpy(sCutterThickness, "Epaisseurs de coupe");
	strcpy(sData, "Données");
	strcpy(sDataCannotBeEmpty, "Les données ne doivent pas être vides !");
	strcpy(sDateymdhms, "Date (Année / Mois / jour / heure / minutes / secondes)");
	strcpy(sDays_left_for_trial, "Jours disponibles pour les tests ");
	strcpy(sDaysLeft, "Nombre de jours restant");
	strcpy(sStandard, "Par défaut");
	strcpy(sDefaultInterface, "Interface par défaut");
	strcpy(sDefects, "Défauts");
	strcpy(sDefectsManager, "Gérer les défauts");
	strcpy(sDefectsofthematerialNopiecescanbeplacedinthefaultyzone, "Défauts du matériau. Aucune pièce ne peut être placée dans la zone défectueuse.");
	strcpy(sDelete, "Supprimer");
	strcpy(sDeletePiece, "Supprimer pièce");
	strcpy(sDeleteRow, "supprimer ligne");
	strcpy(sDemandutilization, "Utilisation de la demande");
	strcpy(sDepozitulmodificat, "Les pièces utilisées ont été enlevées. Les restes ont été ajoutés au stock.");
	strcpy(sDepozitvid, "Le stock est vide");
	strcpy(sDesk, "Bureau");
	strcpy(sDiagram, "Diagramme");
	strcpy(sDiagrams, "Diagrammes");
	strcpy(sDiagramasatable, "Schéma sous forme de tableau");
	strcpy(sDigits, "Chiffres");
	strcpy(sDimensiuniplaca, "Taille de la feuille");
	strcpy(sDirection, "Direction");
	strcpy(sDistanceBetweenRows, "Distance entre les rangées");
	strcpy(sDonotuseit, "Ne l'utilisez pas");
	strcpy(sDownload, "Télécharger");
	strcpy(sDoYouWantToClearTheData, "Souhaitez-vous supprimer les données ?");
	strcpy(sDoYouWantToSaveDemand, "Les pièces ont été modifiées ! Souhaitez-vous enregistrer les modifications ?");
	strcpy(sDoYouWantToSaveParts, "Voulez-vous enregistrer les pièces ?");
	strcpy(sDoYouWantToSaveRepository, "Le stock a été modifié ! Souhaitez-vous enregistrer les modifications ?");
	strcpy(sDrawing, "dessins");
	strcpy(sDrawthesolutioncolorful, "Dessiner la solution colorée");
	strcpy(sDuplicateTypes, "Certains types sont dupliqués ! Supprimez les doublons, SVP");
	strcpy(sDuplicateTypesWithComplex, "Certains noms de matériaux existent déjà dans la liste des types complexes ! Supprimez les doublons, SVP");
	strcpy(sDuplicateValues, "Valeurs dupliquées");
	strcpy(sEdgeband, "Types de bords de chant");
	strcpy(sEdgebandingwhichisplacedontheedgesofyourpiecePleasedefineedgebandingtypesfromMaterialsEdgeBandingmenu, "Bord de chant placé sur les bords de votre pièce : définissez les types de chants à partir du menu des matériaux.");
	strcpy(sEdgebandsthatwillbeappliedtoeachpart, "Bandes de bord qui seront appliquées à chaque pièce.");
	strcpy(sEdgeBandTolerance, "Tolérance pour les bandes de chant");
	strcpy(sEdgesthatmustbecutduefaults, "Arêtes devant être coupées en raison d'erreurs");
	strcpy(sEdgetoedge, "De bord à bord");
	strcpy(sEdit, "Éditer");
	strcpy(sEmail, "Emai");
	strcpy(sEmptyData, "Les données sont vides !");
	strcpy(sEnabled, "Activé");
	strcpy(sEnabledisabledefectsoftheinventorysheets, "Activer / désactiver les défauts du stock");
	strcpy(sEnterLabel, "Entrez l'étiquette");
	strcpy(sEnterTheMaterialName, "Entrez le nom de la matière");
	strcpy(sEnterTheProductName, "Entrez le nom du produit");
	strcpy(sEvaluationError, "Erreur lors de l'évaluation de l'expression !");
	strcpy(sExit, "Quitter");
	strcpy(sExpired, "Licence expirée : enregistrez le logiciel !");
	strcpy(sExport, "Exporter");
	strcpy(sExportAllDiagrams, "Exporter tous les diagrammes");
	strcpy(sExportAllToASingleFile, "Tout exporter dans un seul fichier");
	strcpy(sExportOptions, "Options d'exportation");
	strcpy(sExporttoDXFformat, "Exporter au format DXF");
	strcpy(sExporttoExcel, "Exporter vers Exce");
	strcpy(sExpresieIncorecta, "Expression mathématique incorrecte !");
	strcpy(sExtensions, "Extensions");
	strcpy(sExtra, "Extras");
	strcpy(sExtraComponents, "Composants supplémentaires");
	strcpy(sExtracomponentsattachedtoDemand, "Composants supplémentaires attachés à des parties");
	strcpy(sFile, "Fichiers");
	strcpy(sFileName, "Nom du fichier");
	strcpy(sFillWastes, "Dessiner les déchets avec des lignes obliques");
	strcpy(sFindoptimalbarsheetsize, "Trouvez la taille optimale pour les barres et les feuilles.");
	strcpy(sFindoptimalsizeofInventorypieces, "Trouver la taille optimale des pièces en stock");
	strcpy(sFirstcutMultiplestages, "Suivre le sens de coupe - en plusieurs étapes");
	strcpy(sFirstdirectionforcutishorizontal, "Première coupe : horizontale.");
	strcpy(sFirstdirectionforcutisvertical, "Première coupe : verticale.");
	strcpy(sFollowthecontourofpieces, "Suivre le contour des pièces");
	strcpy(sFont, "Police de caractères");
	strcpy(sFontsize, "Taille de la police");
	strcpy(sFullInfo, "Information complète");
	strcpy(sDisposedWaste, "Déchets éliminés");
	strcpy(sGeneral, "Général");
	strcpy(sGenerateCNC, "Générer CNC");
	strcpy(sGrain, "Texture");
	strcpy(sGraindirection, "Direction des fibres");
	strcpy(sGraphic, "Graphique");
	strcpy(sGreaterorequalto, "Supérieur ou égal à");
	strcpy(sGrid, "tableaux ");
	strcpy(sGrinding, "Epaisseur de broyage");
	strcpy(sGrosimeTaieturaScalata, "L'épaisseur de coupe donnée sur cette image peut être différente de sa valeur réelle car les pièces ne sont pas représentés à leur véritable échelle (ceci n'a aucune incidence sur les résultats)");
	strcpy(sGroupidenticallayouts, "Regroupement des feuilles identiques");
	strcpy(sGroupIdenticalParts, "Regrouper les parties identiques");
	strcpy(sGroupingOfIdenticalPiecesIntoOneRow, "Regrouper les pièces identiques dans une rangée");
	strcpy(sGroupPartsAfterLoadingFromFile, "Regrouper les pièces après chargement du fichier");
	strcpy(sHeight, "Hauteur");
	strcpy(sHeighttolerance, "Tolérance pour la hauteur");
	strcpy(sHelp, "Aide");
	strcpy(sHistory, "Historique");
	strcpy(sHorizontal, "Horizontal");
	strcpy(sHowtodisplayprintedgebands, "Comment les bandes de bord sont-elles affichées?");
	strcpy(sIfyousetthebandforoneedgeallwillreceivethesamevalue, "Si vous définissez la valeur de bande pour un bord, cette même valeur sera utilisée pour tous les bords");
	strcpy(sIfyousetthegrindingforoneedgeallwillreceivethesamevalue, "Si vous définissez la valeur de ponçage pour un bord, cette même valeur sera appliquée à tous les bords");
	strcpy(sIfyousetthetrimforoneedgeallwillreceivethesamevalue, "Si vous définissez la valeur de la garniture pour un bord, cette même valeur sera appliquée à tous les bords");
	strcpy(sImageBounds, "Limites pour l'image");
	strcpy(sImageSize, "Taille de l'image");
	strcpy(sImportData, "Importer les données");
	strcpy(sIncorrectPassword, "Mot de passe incorrect");
	strcpy(sIndex, "Indice");
	strcpy(sInformationaboutcustomer, "Informations sur le client");
	strcpy(sInputALanguageName, "Donnez un nom à la langue");
	strcpy(sInsert, "Insérer");
	strcpy(sInsertPiece, "Insérer une pièce");
	strcpy(sInterface, "Interface");
	strcpy(sInterfaceSettings, "Réglages de l'interface");
	strcpy(sInvalidHardware, "Le type de matériel (hardware) n'a pu être détecté. Merci de nous contacter à : contact@optimalprograms.com");
	strcpy(sInvalidNumber, "Nombre invalide");
	strcpy(sInvalidOrderOfComputation, "Une des contraintes pour le calcul des longueurs ne peut être établie : il existe des relations circulaires dans la définition du produit !");
	strcpy(sInvalidRegistration, "L'inscription est invalide!");
	strcpy(sInvalidTime, "Le temps indiqué par votre système n'est pas valide.");
	strcpy(sInventory, "Stocker");
	strcpy(sisafractionalvalue, "est une valeur fractionnaire");
	strcpy(sIsArc, "Est un arc");
	strcpy(sisarealvalue, "Est un nombre rée");
	strcpy(sLabel, "Étiquette");
	strcpy(sLabels, "Étiquettes");
	strcpy(sLanguage, "Langue");
	strcpy(sLatimeanumar0, "La largeur doit être supérieure à 0 !");
	strcpy(sLatimeanumarreal, "La largeur doit être un nombre réel !");
	strcpy(sLayerName, "Nom du calque");
	strcpy(sLeft, "Gauche");
	strcpy(sLeftcoordinateofthedefect, "Coordonnée gauche de la défectuosité");
	strcpy(sLength, "Longueur");
	strcpy(sLengthofthepiecestocut, "Taille du morceau à utiliser pour la coupe");
	strcpy(sLengthofthepiecestocutfrom, "Taille de la feuille à utiliser pour la coupe");
	strcpy(sLengthofusedbars, "Taille de barres utilisées");
	strcpy(sLicenseAgreement, "Contrat de licence");
	strcpy(sLinear, "Linéaire");
	strcpy(sLinethickness, "Épaisseur de la plume");
	strcpy(sLoadafileandappenddatatothecurrentDemand, "Chargez un fichier et ajoutez les données aux pièces actuelles.");
	strcpy(sLoadanexistingDemandfromafile, "Chargez les pièces existantes à partir du fichier.");
	strcpy(sLoadAppend, "Charger et ajouter");
	strcpy(sLoadEverything, "Tout charger");
	strcpy(sLoadInventory, "Charger le stock");
	strcpy(sLoadInventoryandDemand, "Charger le stock et la demande");
	strcpy(sLoadResults, "Charger les résultats");
	strcpy(sLocked, "fermé");
	strcpy(sLogo, "Logo");
	strcpy(sLong, "Longtemps");
	strcpy(sLongerexecutiontime, "Temps d'exécution");
	strcpy(sLungime, "Largeur");
	strcpy(sLungimeanumar0, "La longueur doit être supérieure à 0 !");
	strcpy(sLungimeanumarreal, "La longueur doit être un nombre réel !");
	strcpy(sLungimeaTotalaFolosita, "Longueur totale utilisée");
	strcpy(sMagnification, "Grossissement");
	strcpy(sMagnify, "Grossir");
	strcpy(sMargins, "Marges");
	strcpy(sMarginsForPaper, "Marges pour le papier");
	strcpy(sMarginsOfTheLabel, "Marges de l'étiquette");
	strcpy(sMaterial, "Matière");
	strcpy(sMaterialName, "Nom de la matière");
	strcpy(sMaterials, "Matériaux");
	strcpy(sMaterialstypes, "Types de matériaux");
	strcpy(sMax, "Max");
	strcpy(sMaximalArea, "Aire maximale");
	strcpy(sMaximalCutLength, "Longueur de coupe maximale");
	strcpy(sMaxlength, "Longueur maximale");
	strcpy(sMaxPiecesperBar, "Pièces Max par Barre");
	strcpy(sMaxwidth, "Largeur maximale.");
	strcpy(sMeasurementUnit, "Unité de mesure");
	strcpy(sMin, "Min");
	strcpy(sMinimalBreakSize, "Taille minimale de rupture");
	strcpy(sMinimalUsefulSize, "Taille minimale utile");
	strcpy(sMinimalwastesizetoInventory, "Taille minimale des déchets à l'inventaire");
	strcpy(s_What_to_minimize, "Que minimiser ?");
	strcpy(sMinlength, "Longueur minimale");
	strcpy(sMinwidth, "Largeur minimale");
	strcpy(sMirror, "Inverser");
	strcpy(sMirroring, "Inversion");
	strcpy(sMiscellaneous, "Autres statistiques");
	strcpy(sModify, "Modifier");
	strcpy(sModifytheselectedpiece, "Modifier la pièce sélectionnée");
	strcpy(sMovePiece, "Déplacez pièce.");
	strcpy(sMultiplestages, "En plusieurs étapes");
	strcpy(sName, "Nom");
	strcpy(sNameofedgeband, "Nom des bandes de bord");
	strcpy(sNewDEMANDUnsaveddatawillbelost, "Nouvelles pièces ? Les données non sauvegardées seront perdues !");
	strcpy(sNewLanguage, "Nouvelle langue");
	strcpy(sNewMaterial, "Nouvelle matière");
	strcpy(sNewPasswordincorectlyintroduced, "Nouveau mot de passe de manière introduit de manière incorrecye !");
	strcpy(sNewProduct, "Nouveau produit");
	strcpy(sNewversion, "Nouvelle version");
	strcpy(sNo, "Non");
	strcpy(sNumarBucati, "Nombre de pièces");
	strcpy(sNumberOfCopies, "Nombre de copies");
	strcpy(sNumberofstages, "Nombre d'étapes");
	strcpy(sNusuficienteplacidepozit, "Toutes les pièces n'ont pas été optimisées. Causes possibles: il n'y a pas assez de pièces dans le stock; Les pièces ne sont pas activées; Le matériau des pièces et le stock sont différents; D'autres paramètres ont été mal réglés.");
	strcpy(sOfficeNotInstaled, "Microsoft Office n'est pas installé sur votre ordinateur ou une version incorecte est installée !");
	strcpy(sOldpassworddoesnotmatch, "L'ancien mot de passe ne correspond pas !");
	strcpy(sOnlinehelp, "Aide en ligne");
	strcpy(sOnlypiecesofthesameheightinthelaststage, "Pièces de la même hauteur dans la dernière étape");
	strcpy(sOpen, "Ouvrir");
	strcpy(sOptimization, "Optimisation");
	strcpy(sOptimizationDone, "Optimisation effectuée ! Vous pouvez imprimer ou enregistrer les schémas obtenus : appuyez sur le bouton Accepter si vous êtes satisfait de la solution actuelle. Sinon, appuyez sur Démarrer de nouveau");
	strcpy(sOptimizationType, "Type d'optimisation");
	strcpy(sOptions, "Les options");
	strcpy(sOptionsrelatedtotheinterface, "Options de l'interface");
	strcpy(sor, "ou");
	strcpy(sOthercomponents, "Autres composants");
	strcpy(sOthers, "Autres");
	strcpy(sOtherstatistics, "Autres statistiques");
	strcpy(sOverrideExcelCSVfiles, "Remplacer les fichiers Excel / CSV");
	strcpy(sParameter, "Paramètre");
	strcpy(sParts, "PIÈCES");
	strcpy(sPattern, "Motif");
	strcpy(sPatternforwaste, "Motif pour les déchets");
	strcpy(sPerimeter, "Périmètre");
	strcpy(sPermitedRotationAngle, "Angle de rotation autorisé");
	strcpy(sPhone, "Téléphone");
	strcpy(sPicture, "Image");
	strcpy(sPiece, "Pièce");
	strcpy(sPieceindex, "Indice de la pièce");
	strcpy(sPieces, "Pièces");
	strcpy(sPiecesize, "Taille de la pièce");
	strcpy(sPiecesizelabeledgebandwillbeprinted, "Impression de la taille de la pièce, de l'étiquette, et des bandes de bord");
	strcpy(sPierdere, "Déchets");
	strcpy(sPixels, "Pixels");
	strcpy(sPlacilefolositeDepozit, "Pièces de l'inventaire utilisées");
	strcpy(sPlease_contact_us_at_contact_nestingtechnologies_com, "Se il vous plaît contactez - nous au contact@nesting-technologies.com");
	strcpy(sPlease_contact_us_at_contact_optimalprograms_com, "Se il vous plaît contactez - nous au contact@optimalprograms.com");
	strcpy(sPleaseenteralldataeitherasfractionalorrealDonotmixthem, "Merci de bien vouloir saisir toutes les données sous un seul et même format (fraction, ou bien nombre réel) !");
	strcpy(sPleaseEnterSomeTypesOfMaterials, "Il n'y a aucun type de matière défini. Vous pouvez les définir à partir du menu des matériaux");
	strcpy(sPleasesendtheNameandtheCodetotheaddresscontactoptimalprogramscominordertoobtaintheRegistrationKey, "Afin d'obtenir la clé d'enregistrement, merci d'envoyer le Nom et le Code à : contact@optimalprograms.com");
	strcpy(sPolygon, "Polygone");
	strcpy(sPolygonsCircles, "Polygones, cercles");
	strcpy(sPrecision, "Précision");
	strcpy(sPretulnumar0, "Le prix doit être supérieur à 0 !");
	strcpy(sPretulnumarreal, "Le prix doit être un nombre réel !");
	strcpy(sPreview, "Aperçu");
	strcpy(sPrice, "Prix");
	strcpy(sPriceMustBeGreaterThanZero, "Le prix doit être supérieur à zéro");
	strcpy(sPriceofbars, "Prix ​​des barres");
	strcpy(sPriceperbar, "Prix ​​par barre");
	strcpy(sPricepersheet, "Prix par feuille");
	strcpy(sPricepersquareunitofmaterial, "Prix par unité de surface de la matière");
	strcpy(sPriceperunit, "Prix ​​à l'unité");
	strcpy(sPrint, "Imprimer");
	strcpy(sPrintdiagramsastables, "Imprimer les schémas sous forme de tableaux");
	strcpy(sPrinter, "Imprimante");
	strcpy(sPrinterBounds, "Marges pour l'impression");
	strcpy(sPrinting, "Impression");
	strcpy(sPrintonlyutilizedarea, "Imprimer seulement la zone utile");
	strcpy(sPrintthecontentsoftheDemand, "Imprimer le contenu de la demande");
	strcpy(sPrintthecontentsoftheInventory, "Imprimer le contenu du stock");
	strcpy(sPrintthecurrentsolution, "Imprimer la solution actuelle");
	strcpy(sPriority, "Priorité");
	strcpy(sPrioritytocutapieceZero0isthehighestpriority, "Priorité de coupe. Zéro (0) est la plus haute priorité");
	strcpy(sProcentul0100, "Les pourcentages doivent être supérieurs à 0 et inférieurs ou égaux à 100 !");
	strcpy(sProcentulnumarreal, "Les pourcentages doivent être un nombre réel !");
	strcpy(sProductdefinition, "Définition du produit");
	strcpy(sProductExists, "Ce produit existe déjà. Choisissez un autre nom");
	strcpy(sProductName, "Nom du produit");
	strcpy(sProducts, "Produit");
	strcpy(sProducts, "Produits");
	strcpy(sProject, "Projet");
	strcpy(sProperties, "propriétés");
	strcpy(sProperty, "propriété");
	strcpy(sQuantity, "Quantité");
	strcpy(sQuantitynumberofsheetsofthistype, "Nombre de feuilles de ce type");
	strcpy(sRadius, "Rayon");
	strcpy(sRectangular, "Rectangulaire");
	strcpy(sRedefinetypesofedgeband, "Redéfinir les types de bande de chant");
	strcpy(sRedefinetypesofmaterial, "Redéfinir les types de matière");
	strcpy(sRegistration, "Enregistrement");
	strcpy(sRegistrationKeyfromOptimalPrograms, "Clé d'enregistrement");
	strcpy(sRegistrationSuccessful, "Enregistrement réussi !");
	strcpy(sRemoveallpiecesinInventory, "Retirer toutes les pièces de l'inventaire");
	strcpy(sRemoveCut, "Supprimer la coupe");
	strcpy(sRemovetheselectedpiece, "Retirer le morceau sélectionné");
	strcpy(sReports, "Rapports");
	strcpy(sRequestedMaterial, "Matériel requis");
	strcpy(sRestore, "Restaurer");
	strcpy(sResults, "Résultats");
	strcpy(sReusedwaste, "Déchets réutilisés");
	strcpy(sRight, "Droite");
	strcpy(sRightcoordinateofthedefect, "Coordonnées de la défectuosité à partir de la droite");
	strcpy(sRotation, "Rotation");
	strcpy(sRotationAngle, "Angle de rotation");
	strcpy(sRotationStep, "L'étape de rotation");
	strcpy(sRoundAllFractionsTo, "Arrondi pour les valeurs fractionnaires");
	strcpy(sRow, "Ligne");
	strcpy(sRows, "Rangées");
	strcpy(sRun, "Dernières solutions");
	strcpy(sRunningtime, "Durée écoulée");
	strcpy(sSameforall, "Identique pour tous");
	strcpy(sSave, "Enregistrer");
	strcpy(sSaveAllImages, "Enregistrer toutes les images");
	strcpy(sSaveAs, "Enregistrer sous");
	strcpy(sSaveChanges, "Les pièces ont été changées. Voulez-vous enregistrer?");
	strcpy(sSaveCurrentImage, "Enregistrer l'image actuelle");
	strcpy(sSavedataparameters, "Enregistrer les données et les paramètres");
	strcpy(sSaveEverything, "Tout Enregistrer");
	strcpy(sSaveInventory, "Enregistrer l'inventaire");
	strcpy(sSaveInventoryandDemand, "Enregistrer le stock et les pièces");
	strcpy(sSaveResults, "Enregistrer les résultats");
	strcpy(sSaveStatisticsinafile, "Enregistrer les statistiques dans un fichier");
	strcpy(sSavethecurrentimage, "Enregistrer l'image");
	strcpy(sSavethecurrentimageorstatistic, "Enregistrer l'image ou la statistique");
	strcpy(sSavetheDEMANDinafile, "Enregistrer dans un fichier");
	strcpy(sSavetheDemandinafilewithadifferentname, "Enregistrer la demande dans un fichier avec un nom différent");
	strcpy(sSavetheREPOSITORYinafile, "Enregistrer le référentiel dans un fichier");
	strcpy(sSerialNumber, "Clé d'enregistrement");
	strcpy(sService, "Service");
	strcpy(sSetDefaultValues, "Restauration de tous les paramètres à leur valeur par défaut : tous vos réglages actuels seront perdus. Etes-vous sûr de vouloir faire cela?");
	strcpy(sSetedgeband, "Régler la bande de bord");
	strcpy(sSetedgetrim, "Régler la coupe pour les défauts de bords");
	strcpy(sSetthesameedgebandforalledges, "Régler la même bande de chant pour tous les bords");
	strcpy(sSetthesamegrindingforalledges, "Réglez le même broyage pour tous les bords");
	strcpy(sSetthesametrimforalledges, "Réglez la même coupe de défaut pour tous les bords");
	strcpy(sSettings, "Paramètres");
	strcpy(sShape, "Forme");
	strcpy(sSheet, "Feuille");
	strcpy(sSheetsBarstypes, "Types de matériaux");
	strcpy(sSheetSize, "Taille de la feuille");
	strcpy(sSheetsperPage, "Nombre de feuilles par page");
	strcpy(sShort, "Court");
	strcpy(sShorterexecutiontime, "Court temps d'exécution");
	strcpy(sShowallsimpleproducts, "Afficher tous les produits simples");
	strcpy(sShowcustomername, "Afficher le nom du client");
	strcpy(sShowCustomTextOnEachPiece, "Afficher le texte personnalisé sur chaque pièce");
	strcpy(sShowdiagramasatable, "Afficher le diagramme sous forme de tableau");
	strcpy(sShowedgeband, "Afficher les bandes de chant");
	strcpy(sShowedgebandssettinginanewwindow, "Afficher les paramètres des bandes de bord dans une nouvelle fenêtre");
	strcpy(sShowgrindingsettingsinanewwindow, "Affiche les paramètres de broyage dans une nouvelle fenêtre");
	strcpy(sShowHorizontalLabelsAlways, "Afficher les étiquettes dans le sens horizontale");
	strcpy(sShowRemovethesizeofthepiecesinthecurrentsolution, "Afficher / Masquer la taille des pièces dans la solution actuelle");
	strcpy(sShowRemovethesizeofthewastesinthecurrentsolution, "Afficher / Masquer la taille des déchets dans la solution actuelle");
	strcpy(sShowtotalcutlength, "Afficher la longueur totale de coupe");
	strcpy(sShowtrimedgesettingsinanewwindow, "Afficher les paramètres des défauts dans une nouvelle fenêtre");
	strcpy(sSimpleMaterialExists, "Ce nom figure déjà dans la liste des matériaux. Merci d'utiliser un autre nom");
	strcpy(sSinglePieceStrips, "Rayures d'une seule pièce");
	strcpy(sSizes, "Tailles");
	strcpy(sSmallerorequalto, "Plus petit ou égal à");
	strcpy(sSort, "Trier");
	strcpy(sSortAscendingByArea, "Trier par zone en ordre croissant");
	strcpy(sSortDescendingByArea, "Trier par zone en ordre décroissant");
	strcpy(sSpecifyhowdifferentthepiecesinthelaststagecanbeValue0meansnodifference, "Précisez la façon dont les morceaux peuvent différer dans la dernière étape. La valeur 0 signifie : pas de différence.,");
	strcpy(sSpecifyifpiecesinthelaststagecanbedifferentornotdepeultimaetapapotfidiferitesaunucadimensiune, "Précisez si les pièces dans la dernière étape peuvent être différentes ou non");
	strcpy(sSpecifyifthepiececanberotatedornotIfnotitwillbecutinthesamewayasitwasintroducedinDemandLengthofthepieceparalleltothelengthofthesheet, "Précisez s'il est possible d'effectuer une rotation de cette pièce. Si ce n'est pas le cas, cette pièce sera coupée en positionnant sa longueur parallèlement à la longueur de la feuille");
	strcpy(sSpecifyinhowmanystageswemakethecutsDuringastageallcutshavethesamedirection, "Précisez en combien d'étapes la coupe doit être effectuée");
	strcpy(sStartthesearchprocess, "Démarrer le processus de recherche");
	strcpy(sStatistics, "Statistiques");
	strcpy(sStatisticsE, "Rapports supplémentaires");
	strcpy(sStatisticsforeachtypeofmaterial, "Statistiques pour chaque type de matériel");
	strcpy(sStep, "Étape");
	strcpy(sStergeDepozit, "Voulez-vous supprimer l'inventaire ?");
	strcpy(sStergeMaterial, "Voulez-vous supprimer la matière?");
	strcpy(sStergePiesele, "Voulez-vous supprimer la pièce ?");
	strcpy(sStergePiesa, "Voulez-vous supprimer la pièce ?");
	strcpy(sStopthesearchprocess, "Arrêter le processus de recherche");
	strcpy(sStrongoptimization, "Optimisation forte");
	strcpy(sSubtractthebandthicknessfrompiecesize, "Diminuer la taille du morceau en fonction de l'épaisseur de bande");
	strcpy(sSummary, "Résumé");
	strcpy(sSuprafataTotalaFolosita, "Surface totale utilisée");
	strcpy(sSuprafatautilizata, "Utilisation");
	strcpy(sSwitchbetweenfiberandrotationoption, "Basculer entre les fibres et l'option de rotation");
	strcpy(sTechnical, "Technique");
	strcpy(sTechnicalsettings, "Paramètres techniques");
	strcpy(sTemporaryPanelHint, "Panneau temporaire pour déplacer les pièces d'une feuille à l'autre");
	strcpy(sText, "Texte");
	strcpy(sThe_application_has_expired, "Le programme a expiré.");
	strcpy(sThe_application_is_not_registered, "Le logiciel ne est pas enregistré.");
	strcpy(sThe_application_was_first_started_on, "Le logiciel a été commencé le.");
	strcpy(sThecutsareperformedfromasidetotheothersideofthematerial, "Le débit est effetué à partir d'un côté à l'autre de la matière");
	strcpy(sThecuttingmachinecanfollowtheshapeofthematerial, "La machine de coupe peut suivre la forme de la pièce");
	strcpy(sTheedgesofsheetsthatmustbetrimedduefaults, "Bords des feuilles devant être découpés en raison des défauts");
	strcpy(sTheLargestSize, "La plus grande taille");
	strcpy(sThenameofthecustomerforwhichyoucutthepiece, "Le nom du client pour lequel vous effectuez la coupe");
	strcpy(sThenameofyourcustomer, "Le nom de votre client");
	strcpy(sThepiececanberotated, "Il est possible d'effectuer une rotation de la pièce");
	strcpy(sTheprogramtriestoavoidwasteswhichhavebothsizeslessthanthisvalue, "Le programme tente d'éviter les déchets dont les deux dimensions seraient inférieures à cette valeur");
	strcpy(sThereAreNoProducts, "Il n'y a pas encore de produits définis");
	strcpy(sThestockofmaterialhasbeenpreviouslyloadedfromanExcelorCSVformatPleaseloaditagain, "Le stock de matériel a été chargé à partir d'un format Excel ou CSV. Rechargez-le à nouveau si vous souhaitez travailler dessus");
	strcpy(sThetotallengthofcutting, "Longueur totale de la coupe");
	strcpy(sThewidthofthecuttingsawForglasscuttingoptimizationitcanbe0Forwooditshouldbegreaterthan0, "Epaisseur de la scie. Pour la coupe du verre, elle peut être fixée à 0. Pour le bois, ell devrait être supérieure à 0");
	strcpy(sThewidthofthecuttingsawforlinearpieces, "Epaisseur de la scie pour les pièces linéaires");
	strcpy(sThickness, "Épaisseur");
	strcpy(sThischaracterisusedforfillingthewasterectanglesIfyoudonotwantfilledwastejustremovethischaracter, "Ce symbole est utilisé pour le remplissage des rectangles de déchets. Si vous ne voulez pas que les déchets soient affichés ainsin, il suffit de le supprimer");
	strcpy(sThisindexhasvaluebetween1andthenumberofpieces, "Cet indice a une valeur comprise entre 1 et le nombre de pièces");
	strcpy(sThisOptionWillOverrideTheInventoryFileIfLoadedFromExcelOrCsvFiles, "Cette option écrasera le fichier d'inventaire s'il est chargé à partir de fichiers Excel ou CSV");
	strcpy(sThisProgramisLicensedTo, "La licence de ce programme est accordée à ");
	strcpy(sThisvaluewillbeaddedtotheedgebandingmaterialoneachside, "Cette valeur sera ajoutée à la matière utilisée pour le bord de chant sur chaque côté");
	strcpy(sTipNevid, "Le type de matière ne peut être vide");
	strcpy(sTitle, "Titre");
	strcpy(sTools, "Outils");
	strcpy(sTop, "Haut");
	strcpy(sTopcoordinateofthedefect, "La coordonnée supérieure de la défectuosité");
	strcpy(sTotalGarbageWaste, "Tous les rebuts jetés");
	strcpy(sTotalInventoryWaste, "Stock total de déchêts");
	strcpy(sTotalRecycledWaste, "Tous les déchets recyclés");
	strcpy(sTotalusedarea, "Superficie totale utilisée");
	strcpy(sTotalusedlength, "Longueur totale utilisée");
	strcpy(sTrigonometric, "Trigonométrique");
	strcpy(sTrim, "Tailler");
	strcpy(sTrimalledgesatthebeginning, "Tailler tous les bords au début");
	strcpy(sTrimEdge, "Tailler le bord");
	strcpy(sTwoPanels, "2 panneaux");
	strcpy(sType, "type");
	strcpy(sTypeofmaterialfromwhichtocut, "Type de matériau à partir duquel couper");
	strcpy(sTypesAreNotMatched, "L'optimisation n'a pas été effectuée ! Les matériaux des tables Pièces et Stock ne correspondent pas ! Une pièce ne peut être découpée qu'à partir du matériau du même nom en stock. Modifiez le nom du matériau dans les colonnes correspondantes !");
	strcpy(sUndo, "Annuler");
	strcpy(sUndoAccept, "Annuler Accepter");
	strcpy(sUnits, "Unités");
	strcpy(sUnregisteredVersion, "Non enregistré");
	strcpy(sUpdates, "Mises à jour");
	strcpy(sUsefulforwoodfurniture, "Utile pour des meubles en bois");
	strcpy(sUseit, "Utiliser");
	strcpy(sUsePieceinOptimization, "Utilisez ce morceau dans l'optimisation");
	strcpy(sUserName, "Nom d'utilisateur");
	strcpy(sUtilizationandWastes, "Utilisation et déchets");
	strcpy(sUtilizedArea, "Superficie des pièces utilisées");
	strcpy(sUtilizedBars, "Barres utilisées");
	strcpy(sUtilizeddemandcount, "Nombre de pièces utilisées");
	strcpy(sUtilizedParts, "Pièces utilisées");
	strcpy(sUtilizedPieces, "Pièces utilisées");
	strcpy(sUtilizedSheets, "Feuilles utilisées");
	strcpy(sValue, "Valeur");
	strcpy(sValueGreaterEqualToZero, "La valeur doit être supérieure ou égale à zéro");
	strcpy(sValueGreaterThanZero, "La valeur doit être supérieure à zéro");
	strcpy(sValueIntegerNumber, "La valeur doit être un nombre entier !");
	strcpy(sValueRealNumber, "La valeur doit être un nombre réel. Vous avez peut-être utilisé une virgule au lieu de point ou vice-versa. Regle-le, s'il te plait!");
	strcpy(s_The_number_is_too_big_or_it_has_too_many_digits_after_decimal_separator, "Le nombre est trop grand ou il a trop de chiffres après le séparateur décimal!");
	strcpy(s_The_number_is_too_big, "Le nombre est trop grand!");
	strcpy(sVertical, "Verticale");
	strcpy(sWaste, "Déchet");
	strcpy(sWastes, "Déchet");
	strcpy(sWasteAddedToWarehouse, "Scrap ajouté à l'entrepôt");
	strcpy(sWastelimits, "Contraintes pour les déchets");
	strcpy(sWasteType, "Type de déchets");
	strcpy(sWeakoptimization, "Le plus faible niveau d'optimisation");
	strcpy(sWhattoprint, "Que dois-je imprimer");
	strcpy(s_What_to_print_or_save_to_file, "Quoi imprimer ou enregistrer dans un fichier");
	strcpy(sWhattoprintoneachpiece, "Que faut-il imprimer sur chaque pièce");
	strcpy(sWhattoshowoneachpiece, "Que faut-il afficher sur chaque pièce ?");
	strcpy(sWidth, "Largeur");
	strcpy(sWood, "Bois");
	strcpy(sWorkingDirectory, "Répertoire de travai");
	strcpy(sWrongKey, "Clé d'enregistrement invalide !");
	strcpy(sYes, "Oui");
	strcpy(sYoucannotchooseblackblueorredcolors, "Vous ne pouvez sélectionner une couleur noire, bleue ou rouge");
	strcpy(sYouCannotMixFractionalDataWithDecimalOnes, "Vous ne pouvez pas mélanger des valeurs fractionnaires et des nombres réels !");
	strcpy(sYourcompany, "Votre entreprise");
	strcpy(sZip, "Code posta");
	strcpy(s_Set_the_origin_and_the_direction_of_the_axes, "Définissez l'origine et la direction des axes de coordonnées.");










	strcpy(s_Number_of_digits_after_the_decimal_separator, "Nombre de chiffres après le séparateur décimal");
	strcpy(s_Percentages, "Pourcentages");
}

