// Language strings: Greek
// Author: Optimal Programs
// License: MIT License
//---------------------------------------------------------------------------
#include <string.h>
//---------------------------------------------------------------------------
#include "language_string_id.h"
//---------------------------------------------------------------------------
void set_gr(void)
{
	//Greek
	//translated by a customer
	//2025.3.29.0
	strcpy(s_Advanced, "Προχωρημένος");
	strcpy(s_Relative_coordinates, "Σχετικές συντεταγμένες");
	strcpy(s_Absolute_coordinates, "Απόλυτες συντεταγμένες");
	strcpy(s_Append_more_rows, "Προσθήκη περισσότερων σειρών");

	strcpy(s_Add_to_parts, "Προσθήκη στα μέρη.");
	strcpy(s_Additional, "Πρόσθετος");
	strcpy(s_All_results, "Όλα τα αποτελέσματα.");
	strcpy(s_Allow_movement_of_pieces, "Επιτρέψτε την κίνηση των κομματιών");
	strcpy(s_Allow_part_in_part, "Αφήστε κομμάτι σε κομμάτι");
	strcpy(s_Invalid_piece_Angles_are_too_small_or_too_big_or_height_is_too_small, "Άκυρο κομμάτι! Οι γωνίες είναι πολύ μικρές ή πολύ μεγάλες ή το ύψος είναι πολύ μικρό.");
	strcpy(s_Append, "Προσαρτώ");
	strcpy(s_As_it_is, "Ως έχει");
	strcpy(s_As_text, "Ως κείμενο");
	strcpy(s_Ascending, "Ανερχόμενος");
	strcpy(s_Automatic, "Αυτόματο");
	strcpy(s_Cannot_connect_to_the_Internet_Please_visit_our_website_from_a_browser, "Δεν είναι δυνατή η σύνδεση στο Διαδίκτυο! Επισκεφθείτε τον ιστότοπό μας από πρόγραμμα περιήγησης.");
	strcpy(s_Cannot_copy_or_move_the_files, "Δεν είναι δυνατή η αντιγραφή ή η μετακίνηση των αρχείων!");
	strcpy(s_Cannot_delete_the_file, "Δεν είναι δυνατή η διαγραφή του αρχείου!");
	strcpy(s_Cannot_modify_old_results, "Δεν είναι δυνατή η τροποποίηση των παλαιών αποτελεσμάτων!");
	strcpy(s_To_change_click_inside_a_cell_or_press_0_1_or_2, "Για αλλαγή, κάντε κλικ μέσα σε ένα κελί ή πατήστε 0, 1 ή 2.");
	strcpy(s_Cell, "Κύτταρο");
	strcpy(s_Click_on_the_table_header_to_change_the_columns, "Κάντε κλικ στην κεφαλίδα του πίνακα για να αλλάξετε τις στήλες.");
	strcpy(s_Close, "Κλείστε το");
	strcpy(s_Contact_us, "Επικοινωνήστε μαζί μας");
	strcpy(s_Column, "Στήλη");
	strcpy(s_Comma, "Κόμμα");

	strcpy(s_Copy, "αντίγραφο");
	strcpy(s_Copy_for_move, "Αντιγραφή για μετακίνηση");
	strcpy(s_Cut_higher_level_strips_first, "Κόψτε πρώτα λωρίδες υψηλότερου επιπέδου");
	strcpy(s_Cut_index, "Εμφάνιση λίστας κοπής");

	strcpy(s_The_data_have_been_changed_Do_you_want_to_save_them_to_a_file, "Τα δεδομένα έχουν αλλάξει. Θέλετε να τα αποθηκεύσετε σε ένα αρχείο;");
	strcpy(s_Decimal_separator, "Δεκαδικό διαχωριστικό");
	strcpy(s_Restore_default_settings, "Επαναφορά προεπιλεγμένων ρυθμίσεων");
	strcpy(s_Delete_fiber, "Διαγραφή ινών");
	strcpy(s_Descending, "Φθίνων");
	strcpy(s_Discard_changes, "Απορρίψετε τις αλλαγές");

	strcpy(s_Delete_all_data, "Διαγραφή όλων των δεδομένων;");
	strcpy(s_Dot, "Τελεία");
	strcpy(s_Do_you_want_to_delete_the_picture, "Θέλετε να διαγράψετε την εικόνα;");
	strcpy(s_Do_you_want_to_delete_the_product, "Θέλετε να διαγράψετε το προϊόν;");
	strcpy(s_Duplicate_and_append, "Αντιγραφή και προσάρτηση.");
	strcpy(s_Duplicate_values_are_ignored, "Οι διπλές τιμές αγνοήθηκαν!");
	strcpy(s_Error, "Λάθος");
	strcpy(s_Error_loading_file, "Σφάλμα κατά τη φόρτωση του αρχείου.");
	strcpy(s_export_everything, "Εξάγετε τα πάντα");
	strcpy(s_Fit_to_screen, "Προσαρμογή στην οθόνη.");
	strcpy(s_Force_fixed_height, "Σχεδιάστε τα κομμάτια με σταθερό ύψος.");
	strcpy(s_Flipped, "Αναποδογυρισμένο");
	strcpy(s_Import, "Εισαγωγή");
	strcpy(s_If_angles_are_different_from_90_degrees_height_must_be_greater_than_0, "Εάν οι γωνίες είναι διαφορετικές από 90 μοίρες, το ύψος πρέπει να είναι μεγαλύτερο από 0.");
	strcpy(s_Ignore, "Αγνοώ");
	strcpy(s_Incorrect_value, "Λανθασμένη τιμή");
	strcpy(s_Info, "Πληροφορίες");
	strcpy(s_Interior, "μέσα");
	strcpy(s_Give_a_name, "Δώστε ένα όνομα.");
	strcpy(s_Group, "Ομαδοποιήστε το");
	strcpy(s_Header, "Επί κεφαλής");
	strcpy(s_Keep_it_as_it_is, "Κρατήστε το όπως είναι");
	strcpy(s_Level, "Level");
	strcpy(s_Licensee, "Κάτοχος άδειας");
	strcpy(s_List_separator, "Διαχωριστικό λίστας");
	strcpy(s_Made_with_love_in_Cugir_Romania, "Κατασκευασμένο, με αγάπη, στο: Cugir, Ρουμανία");
	strcpy(s_Made_in, "Κατασκευάζεται σε");
	strcpy(s_Manufacturer, "Κατασκευαστής");

	strcpy(s_Manual_arrange, "Χειροκίνητη τακτοποίηση");

	strcpy(s_Mixed, "Μικτός");
	strcpy(s_Multiple_shapes_detected_Next_rows_will_be_overwritten_Continue, "Εντοπίστηκαν περισσότερα από ένα σχήματα. Επομένως, οι επόμενες σειρές θα αντικατασταθούν. Να συνεχίσει?");
	strcpy(s_More, "Περισσότερο");
	strcpy(s_Multiple_values, "Πολλαπλές τιμές");
	strcpy(s_No_texture, "Χωρίς Υφή");
	strcpy(s_Number, "Αριθμός");
	strcpy(s_Number_of_images, "Αριθμός εικόνων");
	strcpy(s_Number_of_vertices, "Αριθμός κορυφών");
	strcpy(s_Offset, "Αντισταθμίζεται");
	strcpy(s_Only_the_currently_selected_items, "Μόνο τα επιλεγμένα στοιχεία.");
	strcpy(s_Optimizing_please_wait, "Βελτιστοποίηση... περιμένετε.");

	strcpy(s_Paste, "Paste");

	strcpy(s_Piece_label, "Εμφάνιση ετικέτας κομματιού");
	strcpy(s_Piece_size, "Εμφάνιση μέγεθος των κομματιών");
	strcpy(s_Please_contact_us_by_email_if_you_receive_this_error, "Εάν λάβετε αυτό το σφάλμα, επικοινωνήστε μαζί μας μέσω email.");
	strcpy(s_Please_save_it_first, "Παρακαλώ, αποθηκεύστε το πρώτα.");
	strcpy(s_Position, "Θέση");
	strcpy(s_Preview, "Προεπισκόπηση");
	strcpy(s_Rectangle, "Ορθογώνιο παραλληλόγραμμο");

	strcpy(s_Redo_the_last_operation, "Επαναφορά της τελευταίας λειτουργίας");
	strcpy(s_Regular_polygon, "Κανονικό πολύγωνο");

	strcpy(s_Reused, "Επαναχρησιμοποίηση");
	strcpy(s_Rotated, "Περιστρεφόμενο");
	strcpy(s_Save_all, "Αποθήκευση όλων");
	strcpy(s_Scrap_label, "Εμφάνιση ετικέτας φύρας");
	strcpy(s_Scrap_size, "Εμφάνιση μεγέθους της φύρας");
	strcpy(s_Semicolon, "Ανω τελεία");
	strcpy(s_Show_cut_index, "Εμφάνιση λίστας κοπής");
	strcpy(s_Show_information, "Εμφάνιση πληροφοριών");
	strcpy(s_Show_piece_label, "Εμφάνιση ετικέτας κομματιού");
	strcpy(s_Show_scrap_label, "Εμφάνιση ετικέτας φύρας");
	strcpy(s_Show_scrap_s_size_on_the_small_pieces, "Εμφάνιση μεγέθους θραύσματος στα μικρά κομμάτια");
	strcpy(s_Show_size_of_pieces, "Εμφάνιση μέγεθος των κομματιών");
	strcpy(s_Show_size_of_scrap, "Εμφάνιση μεγέθους της φύρας");
	strcpy(s_Show_sizes, "Εμφάνιση μεγεθών");
	strcpy(s_Show_label, "Εμφάνιση ετικέτας");
	strcpy(s_Show_length, "Εμφάνιση μήκους");

	strcpy(s_Some_numerical_values_are_incorrect_Should_I_fix_all_the_incorrect_values, "Ορισμένες αριθμητικές τιμές είναι λανθασμένες! Πρέπει να διορθώσω όλες τις εσφαλμένες τιμές;");
	strcpy(s_Some_invalid_values_have_been_removed, "Ορισμένες μη έγκυρες τιμές έχουν αφαιρεθεί.");
	strcpy(s_Sort_by, "Ταξινόμηση κατά");
	strcpy(s_Sort_ascending_by, "Ταξινόμηση αύξουσα κατά");
	strcpy(s_Sort_descending_by, "Ταξινόμηση φθίνουσα κατά");
	strcpy(s_Start, "Start");
	strcpy(s_Starting_angle, "Γωνία εκκίνησης");


	strcpy(s_Stock, "ΑΠΟΘΕΜΑ");
	strcpy(s_Stop, "Stop");

	strcpy(s_Tabular, "Πινακοειδής");
	strcpy(s_Total, "Σύνολο");
	strcpy(s_Total_size, "Συνολικό μέγεθος");
	strcpy(s_Terms_of_the_license, "Όροι της άδειας");
	strcpy(s_The_current_product_has_been_changed_Do_you_want_to_save_it_to_file, "Το τρέχον προϊόν έχει αλλάξει. Θέλετε να το αποθηκεύσετε στο αρχείο;");
	strcpy(s_The_value_is_out_of_the_allowed_range, "Η τιμή είναι εκτός του επιτρεπόμενου εύρους.");
	strcpy(s_The_value_must_be_a_real_or_fractional_number_Try_to_replace_the_comma_with_the_dot_if_you_want_to_enter_a_real_number, "Η τιμή πρέπει να είναι πραγματικός ή κλασματικός αριθμός. Δοκιμάστε να αντικαταστήσετε το κόμμα με την τελεία εάν θέλετε να εισαγάγετε έναν πραγματικό αριθμό.");
	strcpy(s_This_feature_is_not_implemented_yet, "Αυτή η δυνατότητα δεν έχει εφαρμοστεί ακόμη.");
	strcpy(s_This_operation_cannot_be_reversed, "Αυτή η λειτουργία δεν μπορεί να αντιστραφεί.");
	strcpy(s_Undo_the_last_operation, "Αναίρεση της τελευταίας λειτουργίας.");
	strcpy(s_Utilization, "Χρησιμοποίηση");
	strcpy(s_Utilized_Stock, "Χρησιμοποιημένο απόθεμα");
	strcpy(s_Version, "Εκδοχή");
	strcpy(s_Visible_columns, "Ορατές στήλες");
	strcpy(s_You_already_have_the_latest_version_installed, "Έχετε ήδη εγκαταστήσει την τελευταία έκδοση!");
	strcpy(s_What_is_exported, "Τι εξάγεται;");
	strcpy(s0meansanynumberofpieces, "Το μηδέν σημαίνει οποιοδήποτε αριθμό των τεμαχίων");
	strcpy(sAbout, "Περί");
	strcpy(sAccept, "Αποδέχομαι");
	strcpy(sAcceptall, "Αποδοχή όλων");
	strcpy(sAcceptthecurrentsolution, "Αποδοχή τρέχουσας λύσης");
	strcpy(sAdd, "Προσθήκη");
	strcpy(sAddapiece, "Προσθήκη κομματιού");
	strcpy(sAddasimpleproducttoDemand, "Προσθήκη προϊόντος στην υπάρχουσα ζήτηση.");
	strcpy(sAddgrindingthicknesstopartsize, "Προσθήκη πάχους φινιρίσματος στο μέγεθος του κομματιού");
	strcpy(sAddproductnametolabel, "Προσάρτηση όνομα του προϊόντος σε ετικέτα");
	strcpy(sAddress, "Διεύθυνση");
	strcpy(sAddselectedsizetoInventory, "Προσθήκη επιλεγμένου μεγέθους στο απόθεμα");
	strcpy(sAdhesivelabels, "Αυτοκόλλητες ετικέτες");
	strcpy(sAdhesivelabelwithinformationaboutpiecesinDemandCustomernameLabelSizeCurrentData, "Επικολλημένη ετικέτα με πληροφορίες σχετικά με τα κομμάτια της ζήτησης: Όνομα πελάτη, Ετικέτα, μέγεθος, τρέχοντα δεδομένα.");
	strcpy(sAdhesivelabelwithinformationaboutsheetsinInventory, "Επικολλημένη ετικέτα με πληροφορίες σχετικά με τα φύλλα στο απόθεμα");
	strcpy(sAll, "Ολα");
	strcpy(sAlloffcutswhichhavethesizegreaterthanthisvaluewillbeaddedtoInventory, "Όλες ρετάλια που έχουν το μέγεθος μεγαλύτερο από την τιμή αυτή θα προστίθεται στο απόθεμα");
	strcpy(sAllowMirroring, "Αφήστε κατοπτρισμού");
	strcpy(sAllowRotation, "Επιτρεπτή περιστροφή");
	strcpy(sAllPieces, "Όλα τα κομμάτια");
	strcpy(sAllpredefinedproducts, "Όλα τα προκαθορισμένα προϊόντα ");
	strcpy(sAnewwindowwillbedisplayedwheretheusercansettheedgebandsforeachedge, "Ένα νέο παράθυρο θα εμφανιστεί, όπου ο χρήστης μπορεί να ορίσει τις σοκοροταινίες για κάθε ακμή.");
	strcpy(sAnewwindowwillbedisplayedwheretheusercansetthegrindingvalueforeachedgeofthsheet, "Ένα νέο παράθυρο θα εμφανιστεί όπου ο χρήστης μπορεί να ρυθμίσει το μέγεθος φινιρίσματος για κάθε ακμή του τεμαχίου.");
	strcpy(sAnewwindowwillbedisplayedwheretheusercansetthetrimvalueforeachedgeofthsheet, "Ένα νέο παράθυρο θα εμφανιστεί όπου ο χρήστης μπορεί να ορίσει τις ατέλειες για κάθε ακμή του τεμαχίου.");
	strcpy(sAngle, "Γωνία");
	strcpy(sAngles, "Γωνίες");
	strcpy(sAnoptimizationparameterisarealnumber, "Μια παράμετρος βελτιστοποίησης είναι ένας πραγματικός αριθμός.");
	strcpy(sAnoptimizationparameterisfractionalnumber, "Μια παράμετρος βελτιστοποίησης είναι κλασματικός αριθμός.");
	strcpy(sAnyShape, "Οποιοδήποτε σχήμα");
	strcpy(sApolygonmusthaveatleast2vertices, "Ένα πολύγωνο πρέπει να έχει τουλάχιστον 2 κορυφές!");
	strcpy(sApolygonmusthaveatleast3vertices, "Ένα πολύγωνο πρέπει να έχει τουλάχιστον 3 κορυφές!");
	strcpy(sApplication_fails_to_initialize, "Το λογισμικό απέτυχε στην προετοιμασία.");
	strcpy(sArc, "Arc");
	strcpy(sArcLength, "Μήκος του τόξου");
	strcpy(sAreaofusedsheets, "Επιφάνεια χρησιμοποιημένων φύλλων");
	strcpy(sAshortdescriptionofthesheet, "Μια σύντομη περιγραφή του φύλλου");
	strcpy(sAtleastonepart, "Τουλάχιστον ένα τεμάχιο πρέπει να εισαχθεί.");
	strcpy(sAtTheMarginOfTheSheet, "Στην άκρη του φύλλου");
	strcpy(sBandtypes, "Τύποι σοκοροταινίας");
	strcpy(sBar, "Μπαρ / σωλήνες");
	strcpy(sBars, "Μπαρ / σωλήνες");
	strcpy(sBothsizesoftheoffcutsmustbegreaterthanthisvalue, "Αμφότερα τα μεγέθη των υπολειμμάτων πρέπει να είναι μεγαλύτερα από την τιμή αυτή.");
	strcpy(sBottom, "Κάτω");
	strcpy(sBottomcoordinateofthedefect, "Πλάτος κάτω ξελουρίσματος");
	strcpy(sBreakCut, "Σταμάτημα της κοπής");
	strcpy(sBrowse, "Αναζήτηση");
	strcpy(sBuy, "Αγορά");
	strcpy(sBuynow, "Αγοράστε τώρα ...");
	strcpy(sCancel, "Άκυρο");
	strcpy(sCannotBeEmpty, "δεν μπορεί να είναι άδειο!");
	strcpy(sCannotmovepartsbetweensheetswhenidenticalsheetsaregroupedPleaseungroupthesheetsfrommenu, "Δεν μπορείτε να μετακινήσετε τα μέρη από το ένα φύλλο στο άλλο, αν ομαδοποιούνται τα ίδια φύλλα. Παρακαλούμε ακυρώσετε την ομαδοποίηση των φύλλων από το μενού.");
	strcpy(sCannotSaveFile, "Δεν είναι δυνατή η αποθήκευση του αρχείου");
	strcpy(sCenter, "Κέντρο");

	strcpy(sChangeDirection, "Αλλάξτε την κατεύθυνση.");
	strcpy(sChoose, "Επιλέξτε");
	strcpy(sChooseProduct, "Επιλέξτε προϊόν");
	strcpy(sCircle, "Circle");
	strcpy(sCity, "Πόλη");
	strcpy(sClear, "Καθαρισμός");
	strcpy(sClockWise, "Δεξιόστροφα");
	strcpy(sClosewindow, "Κλείσιμο παραθύρου");
	strcpy(sColor, "Χρώμα");
	strcpy(sColorofedgeband, "Το χρώμα της σοκοροταινίας");
	strcpy(sColorPattern, "Χρώμα / Μοτίβο");
	strcpy(sColorpiecesandwastes, "Κομμάτια και χρωματισμένη φύρα");
	strcpy(sColumns, "Στήλες");
	strcpy(sComment, "Σχόλιο");
	strcpy(sCompanyname, "Επωνυμία");
	strcpy(sComplexMaterialExists, "Το όνομα του υλικού έχει ήδη ορστεί στον κατάλογο των σύνθετων υλικών. Παρακαλώ δώστε ένα νέο όνομα.");
	strcpy(sComputerCode, "Κωδικός υπολογιστή");
	strcpy(sComputerCodefromyourcomputer, "Κωδικός υπολογιστή (από τον υπολογιστή σας)");
	strcpy(sComputethetotalpriceofDemand, "Υπολογίσμός συνολικού ποσού της ζήτησης");
	strcpy(sContents, "Περιεχόμενα");
	strcpy(sContinutComanda, "Περιεχόμενα της ζήτησης την ημερομηνία");
	strcpy(sContinutDepozit, "Περιεχόμενα του αποθέματος την ημερομηνία");
	strcpy(sConversionIsDoneOnlyWhenSomePiecesHaveFractionalValues, "Η μετατροπή γίνεται μόνο όταν κάποια κομμάτια έχουν κλασματικές τιμές.");
	strcpy(sConvertsTheSizeOfWasteToAFractionalUnit, "Δείχνει το μέγεθος των αποβλήτων ως κλασματική τιμή.");
	strcpy(sCouldNotSaveFile1, "Δεν ήταν δυνατή η εγγραφή του αρχείου στον κατάλογο");
	strcpy(sCouldNotSaveFile2, "Μπορεί να μην έχετε αρκετά δικαιώματα. Παρακαλείστε να ελέγξετε ή να αλλάξετε το φάκελο εργασίας από το μενού Ρυθμίσεις | Φάκελος εργασίας σε ένα φάκελο στον οποίο έχετε δικαιώματα εγγραφής (για παράδειγμα, c:\\temp).");
	strcpy(sCreationdateYMDHMS, "Ημερομηνία δημιουργίας (Ε/Μ/Η-Ω:Λ:Δ)");
	strcpy(sCurrentDate, "Τρέχουσα Ημ/νία");
	strcpy(sCurrentDiagram, "Τρέχον διάγραμμα");
	strcpy(sCurrentMaterial, "Τρέχον Υλικό");
	strcpy(sCurrentversion, "Current version");
	strcpy(sCurve_not_closed_Try_increasing_DXF_linking_distance_parameter, "Το πολύγωνο δεν είναι κλειστό! Δοκιμάστε να αυξήσετε την παράμετρο απόσταση σύνδεσης DXF.");
	strcpy(sCustomer, "Πελάτης");
	strcpy(sCustomerName, "Όνομα του πελάτη");
	strcpy(sCustomMessage, "Προσαρμοσμένη μήνυμα");
	strcpy(sCutlength, "Το μήκος της κοπής");
	strcpy(sCut, "Τομή");
	strcpy(sCuts, "Κοπές");
	strcpy(sCutterThickness, "Πάχος κοπής");
	strcpy(sData, "Δεδομένα");
	strcpy(sDataCannotBeEmpty, "Τα δεδομένα δεν μπορούν να είναι κενά!");
	strcpy(sDateymdhms, "Ημερομηνία (ε / μ / η / ω / λ / δ)");
	strcpy(sDays_left_for_trial, "Ημέρες διαθέσιμα για τη δοκιμή ");
	strcpy(sDaysLeft, "Υπολειπόμενεςι ημέρες");
	strcpy(sStandard, "Προκαθορισμένο");
	strcpy(sDefaultInterface, "Προκαθορισμένο περιβάλλον");
	strcpy(sDefects, "Ελαττώματα");
	strcpy(sDefectsManager, "Διαχείριση ξελουρίσματος");
	strcpy(sDefectsofthematerialNopiecescanbeplacedinthefaultyzone, "Ελαττώματα του υλικού. Κανένα κομμάτι δεν μπορεί να τοποθετηθή στη ζώνη ξελουρίσματος.");
	strcpy(sDelete, "Διαγραφή");
	strcpy(sDeletePiece, "Διαγραφή κομματιού");
	strcpy(sDeleteRow, "Διαγραφή γραμμής");
	strcpy(sDemandutilization, "Αξιοποίηση ζήτησης");
	strcpy(sDepozitulmodificat, "Τα κομμάτια που χρησιμοποιούνται έχουν αφαιρεθεί. Τα υπολείμματα έχουν προστεθεί στο απόθεμα.");
	strcpy(sDepozitvid, "Το απόθεμα είναι άδειο");
	strcpy(sDesk, "γραφείο");
	strcpy(sDiagram, "Διάγραμμα");
	strcpy(sDiagrams, "Διαγράμματα");
	strcpy(sDiagramasatable, "Διάγραμμα ως πίνακας");
	strcpy(sDigits, "ψηφία");
	strcpy(sDimensiuniplaca, "Μέγεθος του φύλλου");
	strcpy(sDirection, "Κατεύθυνση");
	strcpy(sDistanceBetweenRows, "Απόσταση μεταξύ των γραμμών");
	strcpy(sDonotuseit, "Μην το χρησιμοποιείτε");
	strcpy(sDownload, "Κατεβάστε");
	strcpy(sDoYouWantToClearTheData, "Θέλετε να διαγράψετε τα δεδομένα;");
	strcpy(sDoYouWantToSaveDemand, "Τα κομμάτια έχουν αλλάξει! Θέλετε να αποθηκεύσετε τις αλλαγές;");
	strcpy(sDoYouWantToSaveParts, "Θέλετε να αποθηκεύσετε τα κομμάτια;");
	strcpy(sDoYouWantToSaveRepository, "Το απόθεμα έχει αλλάξει! Θέλετε να αποθηκεύσετε τις αλλαγές;");
	strcpy(sDrawing, "σχέδια");
	strcpy(sDrawthesolutioncolorful, "Πολύχρωμη σχεδίαση λύσης");
	strcpy(sDuplicateTypes, "Μερικοί τύποι έχουν διπλοεγγραφεί! Παρακαλώ αφαιρέστε τη διπλοεγγραφή");
	strcpy(sDuplicateTypesWithComplex, "Μερικά ονόματα των υλικών που υπάρχουν ήδη στη λίστα των σύνθετων τύπων! Παρακαλώ αφαιρέστε τα διπλότυπα");
	strcpy(sDuplicateValues, "Διπλές τιμές");
	strcpy(sEdgeband, "Σοκοροταινίες");
	strcpy(sEdgebandingwhichisplacedontheedgesofyourpiecePleasedefineedgebandingtypesfromMaterialsEdgeBandingmenu, "Σοκοροταινία η οποία τοποθετείται στις άκρες του κομματιού σας. Παρακαλώ ορίστε τη από το μενού υλικών.");
	strcpy(sEdgebandsthatwillbeappliedtoeachpart, "Σοκοροταινία που θα εφαρμόζεται σε κάθε κομμάτι.");
	strcpy(sEdgeBandTolerance, "Ανοχή για την σοκοροταινία");
	strcpy(sEdgesthatmustbecutduefaults, "Άκρα που πρέπει να κοπούν λόγω κτυπημάτων");
	strcpy(sEdgetoedge, "Από άκρη σε άκρη");
	strcpy(sEdit, "Επεξεργασία");
	strcpy(sEmail, "E-mail");
	strcpy(sEmptyData, "Δεν υπάρχουν δεδομένα!");
	strcpy(sEnabled, "Ενεργοποιήθηκε");
	strcpy(sEnabledisabledefectsoftheinventorysheets, "Ενεργοποίηση / απενεργοποίηση ξελουρισμάτων του αποθέματος");
	strcpy(sEnterLabel, "Εισάγετε ετικέτα");
	strcpy(sEnterTheMaterialName, "Εισάγετε το όνομα του υλικού");
	strcpy(sEnterTheProductName, "Πληκτρολογήστε το όνομα του προϊόντος");
	strcpy(sEvaluationError, "Σφάλματος για την αξιολόγηση της έκφρασης!");
	strcpy(sExit, "Έξοδος");
	strcpy(sExpired, "Το λογισμικό έχει λήξει! Παρακαλούμε να αγοράσετε το λογισμικό!");
	strcpy(sExport, "Εξαγωγή");
	strcpy(sExportAllDiagrams, "Εξαγωγή όλων των διαγραμμάτων");
	strcpy(sExportAllToASingleFile, "Εξαγωγή όλων σε ένα αρχείο");
	strcpy(sExportOptions, "Επιλογές εξαγωγής.");
	strcpy(sExporttoDXFformat, "Εξαγωγή σε μορφή DXF");
	strcpy(sExporttoExcel, "Εξαγωγή σε Excel");
	strcpy(sExpresieIncorecta, "Λανθασμένη μαθηματική έκφραση!");
	strcpy(sExtensions, "Επεκτάσεις");
	strcpy(sExtra, "Επιπλέον");
	strcpy(sExtraComponents, "Επιπλέον Εξαρτήματα");
	strcpy(sExtracomponentsattachedtoDemand, "Επιπλέον στοιχεία που συνδέονται με τα κομμάτια");
	strcpy(sFile, "Αρχείο");
	strcpy(sFileName, "Όνομα αρχείου");
	strcpy(sFillWastes, "Σχεδίαση φύρας με λοξές γραμμές");
	strcpy(sFindoptimalbarsheetsize, "Εύρεση βελτίστου μεγέθους για σωλήνες και φύλλα.");
	strcpy(sFindoptimalsizeofInventorypieces, "Ανεύρεση βελτίστου μεγέθους από τα κομμάτια αποθέματος");
	strcpy(sFirstcutMultiplestages, "Πρώτη κατεύθυνση κοπής - Πολλαπλά στάδια");
	strcpy(sFirstdirectionforcutishorizontal, "Η πρώτη διεύθυνση για κομμένα είναι οριζόντια.");
	strcpy(sFirstdirectionforcutisvertical, "Η πρώτη διεύθυνση για την κοπή είναι κάθετη.");
	strcpy(sFollowthecontourofpieces, "Ακολουθία του περιγράμματος των τεμαχίων");
	strcpy(sFont, "Γραμματοσειρά");
	strcpy(sFontsize, "Μέγεθος γραμματοσειράς");
	strcpy(sFullInfo, "Πλήρεις πληροφορίες");
	strcpy(sDisposedWaste, "Απορρίμματα");
	strcpy(sGeneral, "Γενικά");
	strcpy(sGenerateCNC, "Δημιουργία CNC");
	strcpy(sGrain, "Υφή");
	strcpy(sGraindirection, "Κατεύθυνση ινών");
	strcpy(sGraphic, "Γραφικά");
	strcpy(sGreaterorequalto, "Μεγαλύτερη ή ίση με");
	strcpy(sGrid, "πίνακες ");
	strcpy(sGrinding, "Λείανση");
	strcpy(sGrosimeTaieturaScalata, "Το πάχος κοπής από αυτήν την εικόνα μπορεί να είναι διαφορετικό από την πραγματικό, επειδή τα κομμάτια δεν εμφανίζονται στην πραγματική κλίμακα τους. Το γεγονός αυτό δεν επηρεάζει τα αποτελέσματα.");
	strcpy(sGroupidenticallayouts, "Ομαδοποίηση όμοιων φύλλων");
	strcpy(sGroupIdenticalParts, "Ομάδα πανομοιότυπα κομμάτια");
	strcpy(sGroupingOfIdenticalPiecesIntoOneRow, "Ομαδοποίηση ίδια κομμάτια σε μία σειρά.");
	strcpy(sGroupPartsAfterLoadingFromFile, "Ομάδα κομματιών μετά τη φόρτωση από αρχείο");
	strcpy(sHeight, "Ύψος");
	strcpy(sHeighttolerance, "Ανοχή ως προς το ύψος");
	strcpy(sHelp, "Βοήθεια");
	strcpy(sHistory, "Ιστορικό");
	strcpy(sHorizontal, "Οριζόντια");
	strcpy(sHowtodisplayprintedgebands, "Πώς να εμφανίζει τις σοκοροταινίες;");
	strcpy(sIfyousetthebandforoneedgeallwillreceivethesamevalue, "Εάν ρυθμίσετε την σοκοροταινία για μία άκρη, όλα θα έχουν την ίδια.");
	strcpy(sIfyousetthegrindingforoneedgeallwillreceivethesamevalue, "Εάν ορίσετε την τιμή λείανσης για μία άκρη, όλες οι ακμές θα έχουν την ίδια τιμή.");
	strcpy(sIfyousetthetrimforoneedgeallwillreceivethesamevalue, "Εάν ρυθμίσετε την αποκοπή για μία άκρη, όλες οι ακμές θα έχουν την ίδια τιμή.");
	strcpy(sImageBounds, "Όρια για την εικόνα");
	strcpy(sImageSize, "Μέγεθος εικόνας");
	strcpy(sImportData, "Εισαγωγή των δεδομένων.");
	strcpy(sIncorrectPassword, "Εσφαλμένος κωδικός πρόσβασης");
	strcpy(sIndex, "Λίστα");
	strcpy(sInformationaboutcustomer, "Πληροφορίες σχετικά με τον πελάτη");
	strcpy(sInputALanguageName, "Δώστε ένα όνομα για τη γλώσσα");
	strcpy(sInsert, "Εισαγωγή");
	strcpy(sInsertPiece, "Τοποθετήστε το κομμάτι");
	strcpy(sInterface, "Περιβάλλον");
	strcpy(sInterfaceSettings, "Ρυθμίσεις περιβάλλοντος");
	strcpy(sInvalidHardware, "Δεν θα μπορούσε να ανιχνεύσει το υλικό. Παρακαλούμε επικοινωνήστε μαζί μας στο contact@optimalprograms.com");
	strcpy(sInvalidNumber, "Μη έγκυρος αριθμός");
	strcpy(sInvalidOrderOfComputation, "Μια εντολή υπολογισμού μηκών δεν είναι αποδεκτή. Υπάρχουν κυκλικές σχέσεις στον ορισμό του προϊόντος!");
	strcpy(sInvalidRegistration, "Η εγγραφή είναι άκυρη!");
	strcpy(sInvalidTime, "Η ώρα του συστήματός σας δεν είναι έγκυρη.");
	strcpy(sInventory, "ΑΠΟΘΕΜΑ");
	strcpy(sisafractionalvalue, "είναι μια κλασματική τιμή.");
	strcpy(sIsArc, "Είναι τόξου");
	strcpy(sisarealvalue, "είναι μια πραγματική τιμή.");
	strcpy(sLabel, "Ετικέτα");
	strcpy(sLabels, "Ετικέτες");
	strcpy(sLanguage, "Γλώσσα");
	strcpy(sLatimeanumar0, "Το πλάτος πρέπει να είναι μεγαλύτερη από το 0!");
	strcpy(sLatimeanumarreal, "Το πλάτος πρέπει να είναι ένας πραγματικός αριθμός!");
	strcpy(sLayerName, "Όνομα επιπέδου");
	strcpy(sLeft, "Αριστερά");
	strcpy(sLeftcoordinateofthedefect, "Πλάτος αριστερού ξελουρίσματος");
	strcpy(sLength, "Μήκος");
	strcpy(sLengthofthepiecestocut, "Μέγεθος κομματιού για κοπή");
	strcpy(sLengthofthepiecestocutfrom, "Μέγεθος φύλλου για κοπή");
	strcpy(sLengthofusedbars, "Μέγεθος των χρησιμοποιούμενων ράβδων");
	strcpy(sLicenseAgreement, "Άδεια χρήσης");
	strcpy(sLinear, "Γραμμικός");
	strcpy(sLinethickness, "Πάχος του στυλό");
	strcpy(sLoadafileandappenddatatothecurrentDemand, "Φόρτωμα αρχείου και προσάρτηση των δεδομένων στην τρέχουσα ζήτηση.");
	strcpy(sLoadanexistingDemandfromafile, "Φόρτωμα υπάρχουσας ζήτησης από αρχείο.");
	strcpy(sLoadAppend, "Φόρτωμα και Προσάρτηση");
	strcpy(sLoadEverything, "Φόρτωμα όλων");
	strcpy(sLoadInventory, "Φόρτωμα αποθέματος");
	strcpy(sLoadInventoryandDemand, "Φόρτωμα αποθέματος και ζήτησης");
	strcpy(sLoadResults, "Φόρτωμα αποτελεσμάτων");
	strcpy(sLocked, "Κλειδωμένο");
	strcpy(sLogo, "Λογότυπο");
	strcpy(sLong, "Long");
	strcpy(sLongerexecutiontime, "Μεγαλύτερη διάρκεια εκτέλεσης");
	strcpy(sLungime, "Πλάτος");
	strcpy(sLungimeanumar0, "Το μήκος πρέπει να είναι μεγαλύτερη από 0!");
	strcpy(sLungimeanumarreal, "Το μήκος πρέπει να είναι ένας πραγματικός αριθμός!");
	strcpy(sLungimeaTotalaFolosita, "Συνολικό χρησιμοποιούμενο μήκος");
	strcpy(sMagnification, "Μεγέθυνση");
	strcpy(sMagnify, "Μεγέθυνση");
	strcpy(sMargins, "Περιθώρια");
	strcpy(sMarginsForPaper, "Περιθώρια για το χαρτί");
	strcpy(sMarginsOfTheLabel, "Περιθώρια της ετικέτας");
	strcpy(sMaterial, "Υλικό");
	strcpy(sMaterialName, "Όνομα του υλικού");
	strcpy(sMaterials, "Υλικά");
	strcpy(sMaterialstypes, "Τύποι υλικών");
	strcpy(sMax, "max");
	strcpy(sMaximalArea, "Μέγιστη επιφάνεια");
	strcpy(sMaximalCutLength, "Μέγιστο μήκος κοπής");
	strcpy(sMaxlength, "Μέγιστο μήκος");
	strcpy(sMaxPiecesperBar, "Μέγιστα κομμάτια ανά ράβδο");
	strcpy(sMaxwidth, "Μέγιστο πλάτος.");
	strcpy(sMeasurementUnit, "Μονάδα μέτρησης");
	strcpy(sMin, "μου");
	strcpy(sMinimalBreakSize, "Ελάχιστο μέγεθος ρήξης");
	strcpy(sMinimalUsefulSize, "Ελάχιστο χρήσιμο μέγεθος");
	strcpy(sMinimalwastesizetoInventory, "Ελάχιστο μέγεθος φύρας στην Αποθήκη");
	strcpy(s_What_to_minimize, "Τι να ελαχιστοποιήσετε;");
	strcpy(sMinlength, "Ελάχιστο μήκος");
	strcpy(sMinwidth, "Ελάχιστο πλάτος");
	strcpy(sMirror, "Αναστροφή");
	strcpy(sMirroring, "Mirroring");
	strcpy(sMiscellaneous, "Διάφορα");
	strcpy(sModify, "Τροποποίηση");
	strcpy(sModifytheselectedpiece, "Τροποποίηση επιλεγμένου κομματιού");
	strcpy(sMovePiece, "Μετακίνηση κομμάτι.");
	strcpy(sMultiplestages, "Πολλαπλά στάδια");
	strcpy(sName, "Όνομα");
	strcpy(sNameofedgeband, "Ονομασία σοκοροταινιών");
	strcpy(sNewDEMANDUnsaveddatawillbelost, "Νέα κομμάτια; Τα μη αποθηκευμένα δεδομένα θα χαθούν!");
	strcpy(sNewLanguage, "Νέα γλώσσα");
	strcpy(sNewMaterial, "Νέο Υλικό");
	strcpy(sNewPasswordincorectlyintroduced, "Λάθος εισαγωγής νέου κωδικού!");
	strcpy(sNewProduct, "Νέο προϊόν");
	strcpy(sNewversion, "Νέα έκδοση");
	strcpy(sNo, "Όχι");
	strcpy(sNumarBucati, "Αριθμός τεμαχίων");
	strcpy(sNumberOfCopies, "Αριθμός αντιγράφων");
	strcpy(sNumberofstages, "Αριθμός σταδίων");
	strcpy(sNusuficienteplacidepozit, "Δεν έχουν όλα τα κομμάτια έχουν βελτιστοποιηθεί. Πιθανές αιτίες: Δεν υπάρχουν αρκετά κομμάτια στο απόθεμα, Κομμάτι δεν χρησιμοποιείται στη βελτιστοποίηση? Τα υλικά ζήτησης και Αποθήκης δεν ταιριάζουν? Άλλες παράμετροι έχουν ρυθμιστεί λάθος.");
	strcpy(sOfficeNotInstaled, "Το Microsoft Office δεν είναι εγκατεστημένο ή μια μη συμβατή έκδοση είναι εγκατεστημένη!");
	strcpy(sOldpassworddoesnotmatch, "Ο παλιός κωδικός δεν ταιριάζει!");
	strcpy(sOnlinehelp, "Online βοήθεια");
	strcpy(sOnlypiecesofthesameheightinthelaststage, "Κομμάτια από το ίδιο ύψος με το τελευταίο στάδιο");
	strcpy(sOpen, "Άνοιγμα");
	strcpy(sOptimization, "Βελτιστοποίηση");
	strcpy(sOptimizationDone, "Η βελτιστοποίηση έγινε! Μπορείτε να εκτυπώσετε ή να αποθηκεύσετε τα διαγράμματα που προκύπτουν. Πατήστε το κουμπί Αποδοχή εάν είστε ικανοποιημένοι με την τρέχουσα λύση. Διαφορετικά, πατήστε Έναρξη και πάλι.");
	strcpy(sOptimizationType, "Τύπος βελτιστοποίησης");
	strcpy(sOptions, "Επιλογές");
	strcpy(sOptionsrelatedtotheinterface, "Επιλογές που σχετίζονται με το περιβάλλον");
	strcpy(sor, "ή");
	strcpy(sOthercomponents, "Άλλα εξαρτήματα");
	strcpy(sOthers, "Άλλα");
	strcpy(sOtherstatistics, "Άλλα στατιστικά στοιχεία");
	strcpy(sOverrideExcelCSVfiles, "Παράκαμψη Excel / CSV αρχεία");
	strcpy(sParameter, "Παράμετρος");
	strcpy(sParts, "ΚΟΜΜΑΤΙΑ");
	strcpy(sPattern, "Διαγράμμιση");
	strcpy(sPatternforwaste, "Διαγράμμιση φύρας");
	strcpy(sPerimeter, "Περίμετρος");
	strcpy(sPermitedRotationAngle, "Η επιτρεπόμενη γωνία περιστροφής.");
	strcpy(sPhone, "Τηλέφωνο");
	strcpy(sPicture, "Εικόνα");
	strcpy(sPiece, "Κομμάτι");
	strcpy(sPieceindex, "Λίστα κομματιών");
	strcpy(sPieces, "Κομμάτια");
	strcpy(sPiecesize, "Μέγεθος κομματικού");
	strcpy(sPiecesizelabeledgebandwillbeprinted, "Το μέγεθος, η ετικέτα και οι σοκοροταινίες του κομματικού θα εκτυπωθούν.");
	strcpy(sPierdere, "Φύρα");
	strcpy(sPixels, "pixels");
	strcpy(sPlacilefolositeDepozit, "Χρησιμοποιούμενα κομμάτια από την Αποθήκη.");
	strcpy(sPlease_contact_us_at_contact_nestingtechnologies_com, "Παρακαλούμε επικοινωνήστε μαζί μας στο contact@nesting-technologies.com");
	strcpy(sPlease_contact_us_at_contact_optimalprograms_com, "Παρακαλούμε επικοινωνήστε μαζί μας στο contact@optimalprograms.com");
	strcpy(sPleaseenteralldataeitherasfractionalorrealDonotmixthem, "Παρακαλώ εισάγετε όλα τα δεδομένα είτε ως κλασματικά ή δεκαδικά! Μην τους αναμιγνύετε όμως!");
	strcpy(sPleaseEnterSomeTypesOfMaterials, "Δεν έχει οριστεί κανένας τύπος υλικού. Μπορείτε να τους ορίσετε από το μενού υλικών.");
	strcpy(sPleasesendtheNameandtheCodetotheaddresscontactoptimalprogramscominordertoobtaintheRegistrationKey, "Για να αποκτήετε το κλειδί εγγραφής παρακαλούμε να στείλετε το Όνομα και τον Κωδικό στο: contact@optimalprograms.com.");
	strcpy(sPolygon, "Πολύγωνο");
	strcpy(sPolygonsCircles, "Πολύγωνα, κύκλοι");
	strcpy(sPrecision, "ακρίβεια");
	strcpy(sPretulnumar0, "Η τιμή πρέπει να είναι μεγαλύτερη από το 0!");
	strcpy(sPretulnumarreal, "Η τιμή πρέπει να είναι ένας πραγματικός αριθμός!");
	strcpy(sPreview, "προεπισκόπηση");
	strcpy(sPrice, "Τιμή");
	strcpy(sPriceMustBeGreaterThanZero, "Τιμή πρέπει να είναι μεγαλύτερη από το μηδέν");
	strcpy(sPriceofbars, "Τιμή ράβδου");
	strcpy(sPriceperbar, "Τιμή ανά ράβδο");
	strcpy(sPricepersheet, "Τιμή ανά φύλλο");
	strcpy(sPricepersquareunitofmaterial, "Τιμή ανά τετραγωνικό υλικού.");
	strcpy(sPriceperunit, "Τιμή ανά Μονάδα");
	strcpy(sPrint, "Εκτύπωση");
	strcpy(sPrintdiagramsastables, "Εκτύπωση διαγράμματα με τη μορφή πινάκων.");
	strcpy(sPrinter, "Εκτυπωτής");
	strcpy(sPrinterBounds, "Περιθώρια του εκτυπωτή");
	strcpy(sPrinting, "Εκτύπωση");
	strcpy(sPrintonlyutilizedarea, "Εκτύπωση μόνο της χρησιμοποιούμενης επιφάνειας");
	strcpy(sPrintthecontentsoftheDemand, "Εκτύπωση των περιεχομένων της ζήτησης.");
	strcpy(sPrintthecontentsoftheInventory, "Εκτύπωση του περιεχομένου του αποθέματος.");
	strcpy(sPrintthecurrentsolution, "Εκτύπωση της τρέχουσας λύσης.");
	strcpy(sPriority, "Προτεραιότητα");
	strcpy(sPrioritytocutapieceZero0isthehighestpriority, "Προτεραιότητα κοπής ένος κομματιού. Μηδέν (0) είναι η ύψιστη προτεραιότητα.");
	strcpy(sProcentul0100, "Το ποσοστό πρέπει να είναι μεγαλύτερο του 0 και μικρότερο ή ίσο με 100!");
	strcpy(sProcentulnumarreal, "Το ποσοστό πρέπει να είναι ένας πραγματικός αριθμός!");
	strcpy(sProductdefinition, "Ορισμός προϊόντος");
	strcpy(sProductExists, "Το προϊόν υπάρχει ήδη. Επιλέξτε ένα άλλο όνομα.");
	strcpy(sProductName, "Όνομα προϊόντος");
	strcpy(sProducts, "Προϊόν");
	strcpy(sProducts, "Προϊόντα");
	strcpy(sProject, "σχέδιο");
	strcpy(sProperties, "Ακίνητα");
	strcpy(sProperty, "ιδιοκτησία");
	strcpy(sQuantity, "Ποσότητα");
	strcpy(sQuantitynumberofsheetsofthistype, "Αριθμός των φύλλων αυτού του τύπου");
	strcpy(sRadius, "Ακτίνας");
	strcpy(sRectangular, "Ορθογώνια");
	strcpy(sRedefinetypesofedgeband, "Επανακαθορισμός των τύπων σοκοροταινίας");
	strcpy(sRedefinetypesofmaterial, "Επανακαθορισμός τύπων υλικού");
	strcpy(sRegistration, "Εγγραφή");
	strcpy(sRegistrationKeyfromOptimalPrograms, "Κλειδί εγγραφής");
	strcpy(sRegistrationSuccessful, "Επιτυχής εγγραφή!");
	strcpy(sRemoveallpiecesinInventory, "Αφαιρέστε όλα τα κομμάτια στην αποθήκη");
	strcpy(sRemoveCut, "Διαγραφή κοπής");
	strcpy(sRemovetheselectedpiece, "Αφαιρέστε το επιλεγμένο κομμάτι");
	strcpy(sReports, "Αναφορές");
	strcpy(sRequestedMaterial, "Ζητούμενο Υλικό");
	strcpy(sRestore, "Επαναφορά");
	strcpy(sResults, "Αποτελέσματα");
	strcpy(sReusedwaste, "Χρήσιμη φύρα");
	strcpy(sRight, "Δεξιά");
	strcpy(sRightcoordinateofthedefect, "Πλάτος δεξιού ξελουρίσματος");
	strcpy(sRotation, "Περιστρεφόμενη");
	strcpy(sRotationAngle, "Περιστροφή γωνία");
	strcpy(sRotationStep, "Περιστροφή βήμα.");
	strcpy(sRoundAllFractionsTo, "Οι κλασματικές τιμές πρέπει να είναι στρογγυλοποιημένες σε");
	strcpy(sRow, "γραμμή");
	strcpy(sRows, "Γραμμές");
	strcpy(sRun, "Τελευταίες λύσεις");
	strcpy(sRunningtime, "χρόνος εκτέλεσης");
	strcpy(sSameforall, "Το ίδιο για όλα");
	strcpy(sSave, "Αποθήκευση");
	strcpy(sSaveAllImages, "Αποθήκευση όλων των εικόνων");
	strcpy(sSaveAs, "Αποθήκευση ως");
	strcpy(sSaveChanges, "Η ζήτηση έχει αλλάξει. Θέλετε να αποθηκεύσετε;");
	strcpy(sSaveCurrentImage, "Αποθήκευση τρέχουσας εικόνας");
	strcpy(sSavedataparameters, "Αποθηκεύστε τα δεδομένα και τις παραμέτρους");
	strcpy(sSaveEverything, "Αποθήκευση όλων");
	strcpy(sSaveInventory, "Αποθήκευση Αποθήκης");
	strcpy(sSaveInventoryandDemand, "Αποθήκευση Αποθήκης και Ζήτησης");
	strcpy(sSaveResults, "Αποθήκευση Αποτελεσμάτων");
	strcpy(sSaveStatisticsinafile, "Αποθήκευση στατιστικών στοιχείων σε ένα αρχείο");
	strcpy(sSavethecurrentimage, "Αποθήκευση της τρέχουσας εικόνας");
	strcpy(sSavethecurrentimageorstatistic, "Αποθηκεύστε την τρέχουσα εικόνα ή τα στατιστικά");
	strcpy(sSavetheDEMANDinafile, "Αποθήκευση σε αρχείο");
	strcpy(sSavetheDemandinafilewithadifferentname, "Αποθηκεύστε τη ζήτηση σε ένα αρχείο με διαφορετικό όνομα.");
	strcpy(sSavetheREPOSITORYinafile, "Αποθήκευση ΑΠΟΘΕΜΑΤΟΣ σε αρχείο");
	strcpy(sSerialNumber, "Κλειδί εγγραφής");
	strcpy(sService, "Υποστήριξη");
	strcpy(sSetDefaultValues, "Αυτό θα επαναφέρει όλες τις παραμέτρους στις προεπιλογές.Οι ρυθμίσεις σας θα χαθούν. Είστε βέβαιοι ότι το θέλετε;");
	strcpy(sSetedgeband, "Ορισμός σοκοροταινίας");
	strcpy(sSetedgetrim, "Ρύθμιση ξελουρίσματος των ακμών");
	strcpy(sSetthesameedgebandforalledges, "Ρύθμιση ίδιας σοκοροταινίας για όλα τα άκρα");
	strcpy(sSetthesamegrindingforalledges, "Ρύθμιση ίδιας λείανσης για όλα τα άκρα");
	strcpy(sSetthesametrimforalledges, "Ρύθμιση ίδιας κοπής ξελουρίσματος για όλες τις άκρες");
	strcpy(sSettings, "Ρυθμίσεις");
	strcpy(sShape, "Σχήμα");
	strcpy(sSheet, "Φύλλο");
	strcpy(sSheetsBarstypes, "Τύποι φύλλων_σωλήνων");
	strcpy(sSheetSize, "Μέγεθος του φύλλου");
	strcpy(sSheetsperPage, "Φύλλα ανά σελίδα");
	strcpy(sShort, "Short");
	strcpy(sShorterexecutiontime, "Ταξινόμιση χρόνου εκτέλεσης");
	strcpy(sShowallsimpleproducts, "Εμφάνιση όλων των απλών προϊόντα");
	strcpy(sShowcustomername, "Εμφάνιση του ονόματος του πελάτη");
	strcpy(sShowCustomTextOnEachPiece, "Εμφάνιση προσαρμοσμένου κειμένου για κάθε κομμάτι");
	strcpy(sShowdiagramasatable, "Εμφάνιση διαγράμματος με τη μορφή πίνακα.");
	strcpy(sShowedgeband, "Εμφάνιση σοκοροταινιών");
	strcpy(sShowedgebandssettinginanewwindow, "Εμφάνιση ρυθμίσεων σοκοροταινιών σε ένα νέο παράθυρο");
	strcpy(sShowgrindingsettingsinanewwindow, "Εμφάνιση ρυθμίσεων λείανσης σε ένα νέο παράθυρο");
	strcpy(sShowHorizontalLabelsAlways, "Εμφάνιση ετικετών πάντα οριζόντια");
	strcpy(sShowRemovethesizeofthepiecesinthecurrentsolution, "Εμφάνιση / Απόκρυψη του μεγέθους των κομματιών στην τρέχουσα λύση.");
	strcpy(sShowRemovethesizeofthewastesinthecurrentsolution, "Εμφάνιση / Απόκρυψη του μεγέθους της φύρας στην τρέχουσα λύση.");
	strcpy(sShowtotalcutlength, "Εμφάνιση συνολικό μήκος κοπής");
	strcpy(sShowtrimedgesettingsinanewwindow, "Δείτε τις ρυθμίσεις των ελαττωμάτων σε ένα νέο παράθυρο");
	strcpy(sSimpleMaterialExists, "Το όνομα του υλικού έχει ήδη οριστεί στον κατάλογο των υλικών. Παρακαλώ δώστε ένα νέο όνομα.");
	strcpy(sSinglePieceStrips, "Λωρίδες από ένα τεμάχιο");
	strcpy(sSizes, "Διαστάσεις");
	strcpy(sSmallerorequalto, "Μικρότερη ή ίση");
	strcpy(sSort, "Είδος");
	strcpy(sSortAscendingByArea, "Αύξνουσα ταξινόμηση ανά επιφάνεια");
	strcpy(sSortDescendingByArea, "Φθίνουσα ταξινόμηση ανά επιφάνεια");
	strcpy(sSpecifyhowdifferentthepiecesinthelaststagecanbeValue0meansnodifference, "Καθορίστε πόσο διαφορετικά μπορεί να είναι τα κομμάτια στο τελευταίο στάδιο. Η τιμή 0 σημαίνει να μην υπάρχει διαφορά.");
	strcpy(sSpecifyifpiecesinthelaststagecanbedifferentornotdepeultimaetapapotfidiferitesaunucadimensiune, "Ορίστε αν τα κομμάτια στο τελευταίο στάδιο μπορεί να είναι διαφορετικά ή όχι");
	strcpy(sSpecifyifthepiececanberotatedornotIfnotitwillbecutinthesamewayasitwasintroducedinDemandLengthofthepieceparalleltothelengthofthesheet, "Ορίστε αν το κομμάτι μπορεί να περιστραφεί ή όχι. Αν όχι, θα πρέπει να κοπεί με τον ίδιο τρόπο όπως εισήχθη (το μήκος του παραλλήλο με το μήκος του φύλλου),");
	strcpy(sSpecifyinhowmanystageswemakethecutsDuringastageallcutshavethesamedirection, "Καθορίστε σε πόσα στάδια θα γίνουν οι κοπές.");
	strcpy(sStartthesearchprocess, "Έναρξη αναζήτησης");
	strcpy(sStatistics, "Στατιστικά");
	strcpy(sStatisticsE, "Αναφορές Extra");
	strcpy(sStatisticsforeachtypeofmaterial, "Στατιστικά για κάθε τύπο υλικού");
	strcpy(sStep, "Βήμα");
	strcpy(sStergeDepozit, "Θέλετε να διαγράψετε την καταγραφή υλικοών;");
	strcpy(sStergeMaterial, "Διαγραφή υλικού;");
	strcpy(sStergePiesele, "Θέλετε να διαγράψετε το κομμάτι;");
	strcpy(sStergePiesa, "Θέλετε να διαγράψετε το κομμάτι;");
	strcpy(sStopthesearchprocess, "Σταμάτημα της διαδικασίας αναζήτησης");
	strcpy(sStrongoptimization, "Ισχυρή βελτιστοποίηση");
	strcpy(sSubtractthebandthicknessfrompiecesize, "Μείωση των διαστάσεων του κομματιού με το πάχος της σοκοροταινίας");
	strcpy(sSummary, "περίληψη");
	strcpy(sSuprafataTotalaFolosita, "Συνολική χρησιμοποιούμενη επιφάνεια");
	strcpy(sSuprafatautilizata, "Χρησιμοποίηση");
	strcpy(sSwitchbetweenfiberandrotationoption, "Εναλλαγή επιλογής μεταξύ ευθείας και περιστροφής.");
	strcpy(sTechnical, "Τεχνικά");
	strcpy(sTechnicalsettings, "Τεχνικές ρυθμίσεις");
	strcpy(sTemporaryPanelHint, "Προσωρινός πίνακας για μετακίνηση κοματιών μεταξύ των φύλλων.");
	strcpy(sText, "Κείμενο");
	strcpy(sThe_application_has_expired, "Το πρόγραμμα έχει λήξει.");
	strcpy(sThe_application_is_not_registered, "Το λογισμικό δεν έχει καταχωρηθεί.");
	strcpy(sThe_application_was_first_started_on, "Το λογισμικό ξεκίνησε για πρώτη φορά στις.");
	strcpy(sThecutsareperformedfromasidetotheothersideofthematerial, "Η χρέωση γίνεταιι από τη μία πλευρά έως την άλλη πλευρά του υλικού.");
	strcpy(sThecuttingmachinecanfollowtheshapeofthematerial, "Το κοπτικό μηχάνημα μπορεί να ακολουθήσει το σχήμα του τεμαχίου.");
	strcpy(sTheedgesofsheetsthatmustbetrimedduefaults, "Οι άκρες των φύλλων που πρέπει να ξελουριστούν εξαιτίας ελλατωμάτων");
	strcpy(sTheLargestSize, "Το μεγαλύτερο μέγεθος");
	strcpy(sThenameofthecustomerforwhichyoucutthepiece, "Το όνομα του πελάτη για τον οποίο κόψετε το κομμάτι.");
	strcpy(sThenameofyourcustomer, "Το όνομα του πελάτη σας");
	strcpy(sThepiececanberotated, "Το κομμάτι μπορεί να περιστραφεί");
	strcpy(sTheprogramtriestoavoidwasteswhichhavebothsizeslessthanthisvalue, "Το πρόγραμμα προσπαθεί να αποφύγει φύρα που έχει και στις δυο διαστάσεις μικρότερη από την τιμή αυτή");
	strcpy(sThereAreNoProducts, "Δεν έχουν ακόμη οριστεί εργασίες");
	strcpy(sThestockofmaterialhasbeenpreviouslyloadedfromanExcelorCSVformatPleaseloaditagain, "Το απόθεμα του υλικού έχει ήδη φορτωθεί από μια μορφή Excel ή CSV. Παρακαλώ τοποθετήστε το ξανά αν θέλετε να εργάζονται σε αυτό.");
	strcpy(sThetotallengthofcutting, "Το συνολικό μήκος της κοπής");
	strcpy(sThewidthofthecuttingsawForglasscuttingoptimizationitcanbe0Forwooditshouldbegreaterthan0, "Το πάχος του πριονιού. Για την κοπή γυαλιού μπορεί να είναι 0. Για ξύλο θα πρέπει να είναι μεγαλύτερο από μηδέν.");
	strcpy(sThewidthofthecuttingsawforlinearpieces, "Το πάχος του πριονιού για γραμμικά κομμάτια.");
	strcpy(sThickness, "Πάχος");
	strcpy(sThischaracterisusedforfillingthewasterectanglesIfyoudonotwantfilledwastejustremovethischaracter, "Αυτό το σύμβολο χρησιμοποιείται για την πλήρωση της φύρας ορθογώνια. Αν δεν θέλετε απλά αφαιρέστε το.");
	strcpy(sThisindexhasvaluebetween1andthenumberofpieces, "Ο δείκτης αυτός έχει τιμή μεταξύ 1 και τον αριθμό των τεμαχίων.");
	strcpy(sThisOptionWillOverrideTheInventoryFileIfLoadedFromExcelOrCsvFiles, "Αυτή η επιλογή θα αντικαταστήσει το αρχείο απογραφής, αν φορτώνονται από το Excel ή CSV αρχεία.");
	strcpy(sThisProgramisLicensedTo, "Αυτό το πρόγραμμα ανοίκει στον(ην)");
	strcpy(sThisvaluewillbeaddedtotheedgebandingmaterialoneachside, "Αυτή η τιμή θα πρέπει να προστεθεί σαν πάχος σοκοροταινίας σε κάθε πλευρά");
	strcpy(sTipNevid, "Ο τύπος του υλικού δεν μπορεί να είναι κενό.");
	strcpy(sTitle, "Τίτλος");
	strcpy(sTools, "Εργαλεία");
	strcpy(sTop, "Κορυφή");
	strcpy(sTopcoordinateofthedefect, "Πλάτος πάνω ξελουρίσματος.");
	strcpy(sTotalGarbageWaste, "Όλη η άχρηστη φύρα");
	strcpy(sTotalInventoryWaste, "Σύνολο αποθεμάτων φύρας");
	strcpy(sTotalRecycledWaste, "Όλα η ανακυκλωμένη φύρα");
	strcpy(sTotalusedarea, "Συνολική έκταση που χρησιμοποιείται");
	strcpy(sTotalusedlength, "Συνολικό μήκος που χρησιμοποιείται");
	strcpy(sTrigonometric, "Τριγωνομετρικές");
	strcpy(sTrim, "Αποκοπή");
	strcpy(sTrimalledgesatthebeginning, "Αποκοπή όλων των ακμών κατά την έναρξη");
	strcpy(sTrimEdge, "Αποκοπή της άκρης");
	strcpy(sTwoPanels, "2 φύλλα");
	strcpy(sType, "τύπος");
	strcpy(sTypeofmaterialfromwhichtocut, "Είδος υλικού από το οποίο να κοπεί");
	strcpy(sTypesAreNotMatched, "Η κοπή δεν γίνεται! Τα κομμάτια θα κοπούν από αποθηκευμένα φύλλα του ίδιου υλικού. Τώρα απόθεμα δεν υπάρχει με τέτοιο υλικό! Αλλάξτε κάποια υλικά από την αντίστοιχη στήλη!");
	strcpy(sUndo, "Αναίρεση");
	strcpy(sUndoAccept, "Αποδοχή αναίρεσης");
	strcpy(sUnits, "μονάδες");
	strcpy(sUnregisteredVersion, "Μη καταχωτημένος");
	strcpy(sUpdates, "εκσυγχρονίζω");
	strcpy(sUsefulforwoodfurniture, "Χρήσιμο για ξύλινα έπιπλα");
	strcpy(sUseit, "Προς χρήση");
	strcpy(sUsePieceinOptimization, "Χρησιμοποιήστε το κομμάτι στη βελτιστοποίηση");
	strcpy(sUserName, "Όνομα χρήστη");
	strcpy(sUtilizationandWastes, "Αξιοποίηση και Φύρα");
	strcpy(sUtilizedArea, "Επιφάνεια χρησιμοποιούμενων κοματιών");
	strcpy(sUtilizedBars, "Χρησιμοποιούμενες ράβδοι");
	strcpy(sUtilizeddemandcount, "Αριθμός χρησιμοποιούνται κομμάτια.");
	strcpy(sUtilizedParts, "Χρησιμοποιούμενη κομάτια");
	strcpy(sUtilizedPieces, "Χρησιμοποιούμενη κομμάτια");
	strcpy(sUtilizedSheets, "Χρησιμοποιούμενη φύλλα");
	strcpy(sValue, "Τιμή");
	strcpy(sValueGreaterEqualToZero, "Η τιμή πρέπει να είναι μεγαλύτερη ή ίση με μηδέν");
	strcpy(sValueGreaterThanZero, "Η τιμή πρέπει να είναι μεγαλύτερη από το μηδέν");
	strcpy(sValueIntegerNumber, "Η τιμή πρέπει να είναι ακέραιος αριθμός!");
	strcpy(sValueRealNumber, "Η τιμή πρέπει να είναι ένας πραγματικός αριθμός. Ίσως έχετε χρησιμοποιήσει τον αντίστροφο. Παρακαλώ να διορθωθεί!");
	strcpy(s_The_number_is_too_big_or_it_has_too_many_digits_after_decimal_separator, "Ο αριθμός είναι πολύ μεγάλος ή έχει πάρα πολλά ψηφία μετά το δεκαδικό διαχωριστικό!");
	strcpy(s_The_number_is_too_big, "Ο αριθμός είναι πολύ μεγάλος!");
	strcpy(sVertical, "Κάθετα");
	strcpy(sWaste, "Φύρα");
	strcpy(sWastes, "Φύρα");
	strcpy(sWasteAddedToWarehouse, "Τα ρετάλια προστέθηκαν στην αποθήκη");
	strcpy(sWastelimits, "όρια της φύρας");
	strcpy(sWasteType, "Τύπος της φύρας");
	strcpy(sWeakoptimization, "Η χειρότερη βελτιστοποίηση");
	strcpy(sWhattoprint, "Τι θα εκτυπωθεί");
	strcpy(s_What_to_print_or_save_to_file, "Τι να εκτυπώσετε ή να αποθηκεύσετε στο αρχείο");
	strcpy(sWhattoprintoneachpiece, "Τι εκτυπώνεται σε κάθε κομμάτι");
	strcpy(sWhattoshowoneachpiece, "Τι φαίνεται σε κάθε κομμάτι;");
	strcpy(sWidth, "Πλάτος");
	strcpy(sWood, "ξύλο");
	strcpy(sWorkingDirectory, "Φάκελος εργασίας");
	strcpy(sWrongKey, "Λάθος κωδικός εγγραφής!");
	strcpy(sYes, "Ναί");
	strcpy(sYoucannotchooseblackblueorredcolors, "You cannot choose black, blue or red colors.");
	strcpy(sYouCannotMixFractionalDataWithDecimalOnes, "Δεν μπορείτε να αναμίξετε κλασματικές τιμές με δεκαδικές!");
	strcpy(sYourcompany, "Η εταιρεία σας");
	strcpy(sZip, "Ταχυδρομικός κώδικας");
	strcpy(s_Set_the_origin_and_the_direction_of_the_axes, "Ορίστε την αρχή και την κατεύθυνση των αξόνων των συντεταγμένων.");

}

