// Language strings: Slovak
// Author: Optimal Programs
// License: MIT License
//---------------------------------------------------------------------------
#include <string.h>
//---------------------------------------------------------------------------
#include "language_string_id.h"
//---------------------------------------------------------------------------
void set_sk(void)
{
	//Slovak
	//did not check manually
	// last update on: 2025.9.25.0
	strcpy(s_Area, "Plocha");
	strcpy(s_Mass, "Hmotnosť");
	strcpy(s_Advanced, "Pokročilé");
	strcpy(s_Relative_coordinates, "Relatívne súradnice");
	strcpy(s_Absolute_coordinates, "Absolútne súradnice");
	strcpy(s_Append_more_rows, "Pripojte ďalšie riadky");

	strcpy(s_Add_to_parts, "Pridajte k častiam.");
	strcpy(s_Additional, "Dodatočné");
	strcpy(s_All_results, "Všetky výsledky.");
	strcpy(s_Allow_movement_of_pieces, "Umožnite pohyb kusov");
	strcpy(s_Allow_part_in_part, "Nechajte kus v kuse");
	strcpy(s_Invalid_piece_Angles_are_too_small_or_too_big_or_height_is_too_small, "Neplatný kus! Uhly sú príliš malé alebo príliš veľké, alebo je príliš malá výška.");
	strcpy(s_Append, "Pripojiť");
	strcpy(s_As_it_is, "Ako to je");
	strcpy(s_As_text, "Ako text");
	strcpy(s_Ascending, "stúpajúca");
	strcpy(s_Automatic, "Automatický");
	strcpy(s_Cannot_connect_to_the_Internet_Please_visit_our_website_from_a_browser, "Nedá sa pripojiť na internet! Navštívte náš web z prehliadača.");
	strcpy(s_Cannot_copy_or_move_the_files, "Súbory nie je možné kopírovať alebo presunúť!");
	strcpy(s_Cannot_delete_the_file, "Súbor nie je možné odstrániť!");
	strcpy(s_Cannot_modify_old_results, "Nie je možné upraviť staré výsledky!");
	strcpy(s_To_change_click_inside_a_cell_or_press_0_1_or_2, "Ak to chcete zmeniť, kliknite do bunky alebo stlačte 0, 1 alebo 2.");
	strcpy(s_Cell, "Bunka");
	strcpy(s_Click_on_the_table_header_to_change_the_columns, "Kliknutím na hlavičku tabuľky zmeníte stĺpce.");
	strcpy(s_Close, "Zavri to");
	strcpy(s_Contact_us, "Kontaktuj nás");
	strcpy(s_Column, "Stĺpec");
	strcpy(s_Comma, "Čiarka");
	strcpy(s_The_comma_symbol_cannot_simultaneously_be_the_list_separator_and_the_decimal_separator, "Čiarka nemôže byť súčasne oddeľovačom zoznamu a desatinným oddeľovačom!");
	strcpy(s_Copy, "Kópia");
	strcpy(s_Copy_for_move, "Kopírovať na presun");
	strcpy(s_Cut_higher_level_strips_first, "Najprv odrežte pásy vyššej úrovne");
	strcpy(s_Cut_index, "Zobraziť index rezanie");

	strcpy(s_The_data_have_been_changed_Do_you_want_to_save_them_to_a_file, "Údaje boli zmenené. Chcete ich uložiť do súboru?");
	strcpy(s_Decimal_separator, "Oddeľovač desatinných miest");
	strcpy(s_Restore_default_settings, "Obnovte predvolené nastavenia");
	strcpy(s_Delete_fiber, "Odstrániť vlákno");
	strcpy(s_Descending, "zostupne");
	strcpy(s_Discard_changes, "Zrušiť zmeny");

	strcpy(s_Delete_all_data, "Chcete odstrániť všetky údaje?");
	strcpy(s_Dot, "Bodka");
	strcpy(s_Do_you_want_to_delete_the_picture, "Prajete si vymazať obrázok?");
	strcpy(s_Do_you_want_to_delete_the_product, "Chcete produkt vymazať?");
	strcpy(s_Duplicate_and_append, "Duplikovať a pripojiť.");
	strcpy(s_Duplicate_values_are_ignored, "Duplicitné hodnoty boli ignorované!");
	strcpy(s_Error, "Chyba");
	strcpy(s_Error_loading_file, "Chyba pri načítaní súboru.");
	strcpy(s_export_everything, "Exportovať všetko");
	strcpy(s_Fit_to_screen, "Prispôsobiť obrazovke.");
	strcpy(s_Force_fixed_height, "Nakreslite kúsky s pevnou výškou.");
	strcpy(s_Flipped, "Prevrátené");
	strcpy(s_Import, "Import");
	strcpy(s_If_angles_are_different_from_90_degrees_height_must_be_greater_than_0, "Ak sa uhly líšia od 90 stupňov, výška musí byť väčšia ako 0.");
	strcpy(s_Ignore, "Ignorovať");
	strcpy(s_Incorrect_value, "Nesprávna hodnota");
	strcpy(s_Info, "Информация");
	strcpy(s_Interior, "vnútri");
	strcpy(s_Give_a_name, "Dajte meno.");
	strcpy(s_Group, "Zoskupte to");
	strcpy(s_Header, "Hlavička");
	strcpy(s_Keep_it_as_it_is, "Nechaj to tak, ako je");
	strcpy(s_Level, "Level");
	strcpy(s_Licensee, "koncesionár");
	strcpy(s_List_separator, "Oddeľovač zoznamu");
	strcpy(s_Made_with_love_in_Cugir_Romania, "Vyrobené s láskou v: Cugir, Rumunsko");
	strcpy(s_Made_in, "Vyrobené v");
	strcpy(s_Manufacturer, "Výrobca");

	strcpy(s_Manual_arrange, "Manuálne usporiadanie");

	strcpy(s_Mixed, "zmiešaný");
	strcpy(s_Multiple_shapes_detected_Next_rows_will_be_overwritten_Continue, "Bol zistený viac ako jeden tvar. Preto budú nasledujúce riadky prepísané. Ďalej?");
	strcpy(s_More, "Viac");
	strcpy(s_Multiple_values, "Viaceré hodnoty");
	strcpy(s_No_texture, "Žiadna textúra");
	strcpy(s_Number, "Číslo");
	strcpy(s_Number_of_images, "Počet obrázkov");
	strcpy(s_Number_of_vertices, "Počet vrcholov");
	strcpy(s_Offset, "Offset");
	strcpy(s_Only_the_currently_selected_items, "Iba aktuálne vybrané položky.");
	strcpy(s_Optimizing_please_wait, "Prebieha optimalizácia... čakajte prosím.");

	strcpy(s_Paste, "Paste");

	strcpy(s_Piece_label, "Zobraziť kus štítok");
	strcpy(s_Piece_size, "Zobraziť veľkosti kusov");
	strcpy(s_Please_contact_us_by_email_if_you_receive_this_error, "Ak sa zobrazí táto chyba, kontaktujte nás e-mailom.");
	strcpy(s_Please_save_it_first, "Najskôr si ho uložte.");
	strcpy(s_Position, "Pozícia");
	strcpy(s_Preview, "Náhľad");
	strcpy(s_Rectangle, "Obdĺžnik");

	strcpy(s_Redo_the_last_operation, "Obnovte poslednú operáciu");
	strcpy(s_Regular_polygon, "Pravidelný mnohouholník");

	strcpy(s_Reused, "Opätovne použité");
	strcpy(s_Rotated, "Otočený");
	strcpy(s_Save_all, "Uložiť všetko");
	strcpy(s_Scrap_label, "Zobraziť odpadu štítok");
	strcpy(s_Scrap_size, "Zobrazí veľkosť odpadov");
	strcpy(s_Semicolon, "Bodkočiarka");
	strcpy(s_Show_cut_index, "Zobraziť index rezanie");
	strcpy(s_Show_information, "Zobraziť informácie");
	strcpy(s_Show_piece_label, "Zobraziť kus štítok");
	strcpy(s_Show_scrap_label, "Zobraziť odpadu štítok");
	strcpy(s_Show_scrap_s_size_on_the_small_pieces, "Zobraziť veľkosť šrotu malých kúskov");
	strcpy(s_Show_size_of_pieces, "Zobraziť veľkosti kusov");
	strcpy(s_Show_size_of_scrap, "Zobrazí veľkosť odpadov");
	strcpy(s_Show_sizes, "Zobraziť veľkosti");
	strcpy(s_Show_label, "Zobraziť štítok");
	strcpy(s_Show_length, "Zobraziť dĺžku");

	strcpy(s_Some_numerical_values_are_incorrect_Should_I_fix_all_the_incorrect_values, "Niektoré číselné hodnoty sú nesprávne! Mal by som opraviť všetky nesprávne hodnoty?");
	strcpy(s_Some_invalid_values_have_been_removed, "Niektoré neplatné hodnoty boli odstránené.");
	strcpy(s_Sort_by, "Triediť podľa");
	strcpy(s_Sort_ascending_by, "Zoradiť vzostupne");
	strcpy(s_Sort_descending_by, "Zoradiť zostupne podľa");
	strcpy(s_Start, "Start");
	strcpy(s_Starting_angle, "Štartovací uhol");


	strcpy(s_Stock, "Inventár");
	strcpy(s_Stop, "Stop");
	strcpy(s_System_setting, "Nastavenie systému");
	strcpy(s_Tabular, "Tabuľkový");
	strcpy(s_Total, "Celkom");
	strcpy(s_Total_size, "Celková velkosť");
	strcpy(s_Terms_of_the_license, "Podmienky licencie");
	strcpy(s_The_current_product_has_been_changed_Do_you_want_to_save_it_to_file, "Aktuálny produkt bol upravený. Chcete ho uložiť do súboru?");
	strcpy(s_The_value_is_out_of_the_allowed_range, "Hodnota je mimo povoleného rozsahu.");
	strcpy(s_The_value_must_be_a_real_or_fractional_number_Try_to_replace_the_comma_with_the_dot_if_you_want_to_enter_a_real_number, "Hodnota musí byť skutočné alebo zlomkové číslo. Ak chcete zadať skutočné číslo, skúste nahradiť čiarku bodkou.");
	strcpy(s_This_feature_is_not_implemented_yet, "Táto funkcia ešte nie je implementovaná.");
	strcpy(s_This_operation_cannot_be_reversed, "Túto operáciu nie je možné vrátiť späť.");
	strcpy(s_Undo_the_last_operation, "Vráťte poslednú operáciu.");
	strcpy(s_Utilization, "Využitie");
	strcpy(s_Utilized_Stock, "Použité zásoby");
	strcpy(s_Version, "Verzia");
	strcpy(s_Visible_columns, "Viditeľné stĺpce");
	strcpy(s_You_already_have_the_latest_version_installed, "Už máte nainštalovanú najnovšiu verziu!");
	strcpy(s_What_is_exported, "Čo sa vyváža?");
	strcpy(s0meansanynumberofpieces, "Nula znamená ľubovoľný počet kusov");
	strcpy(sAbout, "O");
	strcpy(sAccept, "Prijať");
	strcpy(sAcceptall, "Prijať všetky");
	strcpy(sAcceptthecurrentsolution, "Prijať aktuálne riešenie");
	strcpy(sAdd, "Pripojiť");
	strcpy(sAddapiece, "Pridať kus");
	strcpy(sAddasimpleproducttoDemand, "Pridanie produktu na existujúci dopyt.");
	strcpy(sAddgrindingthicknesstopartsize, "Pridať brúsenie hrúbku ks veľkosť");
	strcpy(sAddproductnametolabel, "Pripojiť názvu výrobku so značkou");
	strcpy(sAddress, "Sídlo");
	strcpy(sAddselectedsizetoInventory, "Pridať vybranú veľkosť do zoznamu");
	strcpy(sAdhesivelabels, "Samolepiace štítky");
	strcpy(sAdhesivelabelwithinformationaboutpiecesinDemandCustomernameLabelSizeCurrentData, "Nálepka s informáciami o kúsky dopytu: meno zákazníka, etikiet, veľkosť, aktuálne údaje.");
	strcpy(sAdhesivelabelwithinformationaboutsheetsinInventory, "Nálepka s informáciami o listov v inventári.");
	strcpy(sAll, "všetko");
	strcpy(sAlloffcutswhichhavethesizegreaterthanthisvaluewillbeaddedtoInventory, "Všetky odrezky, ktoré majú veľkosť väčšia ako táto hodnota bude pridaná do zásob");
	strcpy(sAllowMirroring, "Povoliť zrkadlenie");
	strcpy(sAllowRotation, "Povoliť rotácie");
	strcpy(sAllPieces, "Všetky kusy");
	strcpy(sAllpredefinedproducts, "Všetky preddefinované produkty");
	strcpy(sAnewwindowwillbedisplayedwheretheusercansettheedgebandsforeachedge, "nové okno sa okno, v ktorom môže používateľ nastaviť pásma pre každú hranu.");
	strcpy(sAnewwindowwillbedisplayedwheretheusercansetthegrindingvalueforeachedgeofthsheet, "nové okno sa okno, v ktorom môže používateľ nastaviť brúsny hodnotu pre každý okraj kusu.");
	strcpy(sAnewwindowwillbedisplayedwheretheusercansetthetrimvalueforeachedgeofthsheet, "nové okno sa zobrazí v ktorom môže používateľ nastaviť vady na každej hrany kusu.");
	strcpy(sAngle, "Uho");
	strcpy(sAngles, "uhly");
	strcpy(sAnoptimizationparameterisarealnumber, "Optimalizácia parameter je reálne číslo.");
	strcpy(sAnoptimizationparameterisfractionalnumber, "Optimalizácia parameter je frakčnou číslo.");
	strcpy(sAnyShape, "Akýkoľvek tvar");
	strcpy(sApolygonmusthaveatleast2vertices, "Mnohoúhelník musí mať najmenej 2 vrcholy!");
	strcpy(sApolygonmusthaveatleast2vertices, "Mnohoúhelník musí mať najmenej 3 vrcholy!");
	strcpy(sApplication_fails_to_initialize, "Softvéru zlyhala inicializácia.");
	strcpy(sArc, "Arc");
	strcpy(sArcLength, "Dĺžka oblúka");
	strcpy(sAreaofusedsheets, "Oblasť použitých listov");
	strcpy(sAshortdescriptionofthesheet, "Stručný opis listu");
	strcpy(sAtleastonepart, "Aspoň jeden kus, musí byť zavedený.");
	strcpy(sAtTheMarginOfTheSheet, "Na okraji listu");
	strcpy(sBandtypes, "Typy hrán kapely.");
	strcpy(sBar, "Tyče / Rúrky");
	strcpy(sBars, "Tyče / Rúrky");
	strcpy(sBothsizesoftheoffcutsmustbegreaterthanthisvalue, "Obe Veľkosti odrezkov musia byť väčšie ako táto hodnota.");
	strcpy(sBottom, "Spodná");
	strcpy(sBottomcoordinateofthedefect, "Spodná Súradnice vady");
	strcpy(sBreakCut, "Break rez");
	strcpy(sBrowse, "Prehliadať");
	strcpy(sBuy, "Kúpiť");
	strcpy(sBuynow, "Kúp teraz ...");
	strcpy(sCancel, "Zrušiť ju");
	strcpy(sCannotBeEmpty, "nemôže byť prázdny!");
	strcpy(sCannotmovepartsbetweensheetswhenidenticalsheetsaregroupedPleaseungroupthesheetsfrommenu, "Nemožno presunúť diely z jedného listu do druhého, ak sú totožné listy sú zoskupené prosím zrušiť zoskupenie listov z ponuky ..");
	strcpy(sCannotSaveFile, "Nemožno uložiť súbor");
	strcpy(sCenter, "Center");

	strcpy(sChangeDirection, "Zmeňte smer.");
	strcpy(sChoose, "Vybrať");
	strcpy(sChooseProduct, "Vyberte produkt");
	strcpy(sCircle, "Circle");
	strcpy(sCity, "Mesto");
	strcpy(sClear, "Vymazať");
	strcpy(sClockWise, "V smere hodinových ručičiek");
	strcpy(sClosewindow, "Zavrieť okno");
	strcpy(sColor, "Farba");
	strcpy(sColorofedgeband, "Farba okraja pásma");
	strcpy(sColorPattern, "Farba / vzor");
	strcpy(sColorpiecesandwastes, "Kusy a odpady farebné.");
	strcpy(sColumns, "Stĺpce");
	strcpy(sComment, "Komentár");
	strcpy(sCompanyname, "Názov spoločnosti");
	strcpy(sComplexMaterialExists, "Názov materiálu je už definovaný v zozname komplexných materiálov. Prosím, dať mu nové meno.");
	strcpy(sComputerCode, "Počítačový kód");
	strcpy(sComputerCodefromyourcomputer, "Computer kód (z počítača)");
	strcpy(sComputethetotalpriceofDemand, "Spočítať celkovú cenu Demand");
	strcpy(sContents, "Obsah");
	strcpy(sContinutComanda, "Obsah Demand na deň");
	strcpy(sContinutDepozit, "Obsah Inventory v dátume");
	strcpy(sConversionIsDoneOnlyWhenSomePiecesHaveFractionalValues, "Konverzia sa vykonáva len vtedy, keď niektoré kúsky majú nepatrnej hodnoty.");
	strcpy(sConvertsTheSizeOfWasteToAFractionalUnit, "Zobrazuje veľkosť odpadu ako frakčnej hodnotu.");
	strcpy(sCouldNotSaveFile1, "Nemožno zapísať súbor v adresári");
	strcpy(sCouldNotSaveFile2, "Nesmiete mať dostatočné práva. Skontrolujte alebo zmeňte pracovný adresár z menu Nastavenia | Pracovný adresár do zložky, kde máte práva pre zápis (napr. c:\\temp).");
	strcpy(sCreationdateYMDHMS, "Dátum vytvorenia (Y / M / D, H: M: S)");
	strcpy(sCurrentDate, "aktuálny dátum");
	strcpy(sCurrentDiagram, "Aktuálny diagram");
	strcpy(sCurrentMaterial, "Aktuálne Materiá");
	strcpy(sCurrentversion, "Aktuálna verzia");
	strcpy(sCurve_not_closed_Try_increasing_DXF_linking_distance_parameter, "Polygón nie je uzavretý! Skúste zväčšiť parameter DXF linking distance.");
	strcpy(sCustomer, "Zákazník");
	strcpy(sCustomerName, "Meno zákazníka");
	strcpy(sCustomMessage, "Vlastné správa");
	strcpy(sCutlength, "Dĺžka rezu");
	strcpy(sCut, "Vystrihnúť");
	strcpy(sCuts, "Rezy");
	strcpy(sCutterThickness, "Hrúbka rezu");
	strcpy(sData, "Údaje");
	strcpy(sDataCannotBeEmpty, "Dáta nemôžu byť prázdne!");
	strcpy(sDateymdhms, "Dátum (y / m / d / h / m / s)");
	strcpy(sDays_left_for_trial, "K dispozícii pre testovanie Days ");
	strcpy(sDaysLeft, "Zvyšné dni");
	strcpy(sStandard, "Štandardné");
	strcpy(sDefaultInterface, "predvolené rozhranie");
	strcpy(sDefects, "Chyby");
	strcpy(sDefectsManager, "Správa vady");
	strcpy(sDefectsofthematerialNopiecescanbeplacedinthefaultyzone, "Vady materiálu. Žiadne kusy môžu byť umiestnené v chybného zóne.");
	strcpy(sDelete, "Vymazať");
	strcpy(sDeletePiece, "Odstrániť kus");
	strcpy(sDeleteRow, "zmazať riadok");
	strcpy(sDemandutilization, "Využitie dopytu");
	strcpy(sDepozitulmodificat, "Used kusy boli odstránené. Ostatky boli pridané do zásoby.");
	strcpy(sDepozitvid, "Populácia je prázdny");
	strcpy(sDesk, "písací stô");
	strcpy(sDiagram, "Diagram");
	strcpy(sDiagrams, "Schémy");
	strcpy(sDiagramasatable, "Diagram ako stô");
	strcpy(sDigits, "číslice");
	strcpy(sDimensiuniplaca, "Veľkosť listu");
	strcpy(sDirection, "Smer");
	strcpy(sDistanceBetweenRows, "Vzdialenosť medzi riadkami");
	strcpy(sDonotuseit, "Nepoužívajte ho");
	strcpy(sDownload, "Stiahnuť");
	strcpy(sDoYouWantToClearTheData, "Ak chcete odstrániť dáta?");
	strcpy(sDoYouWantToSaveDemand, "Diely boli zmenené! Ak chcete uložiť zmeny?");
	strcpy(sDoYouWantToSaveParts, "Chcete ušetriť časti?");
	strcpy(sDoYouWantToSaveRepository, "Fotografia bola zmenená! Ak chcete uložiť zmeny?");
	strcpy(sDrawing, "kresby");
	strcpy(sDrawthesolutioncolorful, "Nakreslite riešenie pestré");
	strcpy(sDuplicateTypes, "Niektoré typy sú duplikované! Prosím odstránenie duplicít");
	strcpy(sDuplicateTypesWithComplex, "Niektoré názvy materiálov už existujú v zozname komplexných typov! Prosím, odstráňte duplicity");
	strcpy(sDuplicateValues, "Duplicitné hodnoty");
	strcpy(sEdgeband, "Kapely na okrajoch");
	strcpy(sEdgebandingwhichisplacedontheedgesofyourpiecePleasedefineedgebandingtypesfromMaterialsEdgeBandingmenu, "Olepovanie, ktorý je umiestnený na okrajoch kusu. Prosím definujte olepovanie typy z materiálov menu.");
	strcpy(sEdgebandsthatwillbeappliedtoeachpart, "Edge kapely, ktoré budú použité pre každú časť.");
	strcpy(sEdgeBandTolerance, "Tolerancia pre olepovanie hrán");
	strcpy(sEdgesthatmustbecutduefaults, "Hrany, ktoré musí byť narezané v dôsledku chyby.");
	strcpy(sEdgetoedge, "Od okraja k okraju");
	strcpy(sEdit, "Upraviť");
	strcpy(sEmail, "E-mail");
	strcpy(sEmptyData, "Údaje sú prázdne!");
	strcpy(sEnabled, "Povolené");
	strcpy(sEnabledisabledefectsoftheinventorysheets, "Zapnúť / vypnúť vady na sklade");
	strcpy(sEnterLabel, "Vstup štítok");
	strcpy(sEnterTheMaterialName, "Vstupné meno materiálu");
	strcpy(sEnterTheProductName, "Zadajte názov produktu");
	strcpy(sEvaluationError, "Chyba na vyhodnotenie výrazu!");
	strcpy(sExit, "Odchod");
	strcpy(sExpired, "Softvér už vypršala! Prosím zaregistrujte sa softvér!");
	strcpy(sExport, "Export");
	strcpy(sExportAllDiagrams, "Exportujte všetky diagramy");
	strcpy(sExportAllToASingleFile, "Exportovať všetko do jedného súboru");
	strcpy(sExportOptions, "Možnosti exportu.");
	strcpy(sExporttoDXFformat, "Export do formátu DXF");
	strcpy(sExporttoExcel, "Export do Excelu");
	strcpy(sExpresieIncorecta, "Nesprávne matematický výraz!");
	strcpy(sExtensions, "rozšírenie");
	strcpy(sExtra, "Extra");
	strcpy(sExtraComponents, "Extra Components");
	strcpy(sExtracomponentsattachedtoDemand, "Extra komponenty upevnené k častiam");
	strcpy(sFile, "Súbor");
	strcpy(sFileName, "Názov súboru");
	strcpy(sFillWastes, "Remíza odpad s šikmých čiar");
	strcpy(sFindoptimalbarsheetsize, "Nájsť optimálnu veľkosť pre trubky a plechy.");
	strcpy(sFindoptimalsizeofInventorypieces, "Nájsť optimálnu veľkosť skladom kusov");
	strcpy(sFirstcutMultiplestages, "Prvé rezanie smer - Viac Priebeh");
	strcpy(sFirstdirectionforcutishorizontal, "Prvý smer rezu je horizontálne.");
	strcpy(sFirstdirectionforcutisvertical, "Prvý smer rezu je vertikálny.");
	strcpy(sFollowthecontourofpieces, "Sledujte obrys kusov");
	strcpy(sFont, "Font");
	strcpy(sFontsize, "Veľkosť písma");
	strcpy(sFullInfo, "Kompletné informácie");
	strcpy(sDisposedWaste, "Likvidovaný odpad");
	strcpy(sGeneral, "Genera");
	strcpy(sGenerateCNC, "Generovať CNC");
	strcpy(sGrain, "Textúra");
	strcpy(sGraindirection, "Smer textúry");
	strcpy(sGraphic, "Grafický");
	strcpy(sGreaterorequalto, "Väčšie alebo rovné");
	strcpy(sGrid, "tabuľky ");
	strcpy(sGrinding, "brúsenie hrúbka");
	strcpy(sGrosimeTaieturaScalata, "Hrúbka rezu z obrázka sa môže líšiť od skutočného jedného, ​​pretože kusy nie sú zastúpení v ich skutočnom merítku. Táto skutočnosť nemá vplyv na výsledky.");
	strcpy(sGroupidenticallayouts, "Zoskupovanie rovnakých listov");
	strcpy(sGroupIdenticalParts, "Rovnaké diely zoskupené.");
	strcpy(sGroupingOfIdenticalPiecesIntoOneRow, "Zoskupovanie rovnakých kusov do jedného riadku.");
	strcpy(sGroupPartsAfterLoadingFromFile, "Zoskupenie časti po načítaní zo súboru");
	strcpy(sHeight, "Výška");
	strcpy(sHeighttolerance, "Tolerancia pre výšku");
	strcpy(sHelp, "Pomoc");
	strcpy(sHistory, "História");
	strcpy(sHorizontal, "Horizontálne");
	strcpy(sHowtodisplayprintedgebands, "Ako sa zobrazí hrany kapely?");
	strcpy(sIfyousetthebandforoneedgeallwillreceivethesamevalue, "Ak nastavíte pásmo pre jednu hranu, budú všetci dostávajú rovnakú hodnotu.");
	strcpy(sIfyousetthegrindingforoneedgeallwillreceivethesamevalue, "Ak nastavíte hodnotu brúsenie pre jedného okraja, všetky hrany dostane rovnakú hodnotu.");
	strcpy(sIfyousetthetrimforoneedgeallwillreceivethesamevalue, "Ak nastavíte čistiace hodnotu pre jedného okraja, všetky hrany dostane rovnakú hodnotu.");
	strcpy(sImageBounds, "Hranice pre obraz");
	strcpy(sImageSize, "Veľkosť obrazu");
	strcpy(sImportData, "Import dát");
	strcpy(sIncorrectPassword, "Nesprávne heslo");
	strcpy(sIndex, "Index");
	strcpy(sInformationaboutcustomer, "Informácie o zákazníkovi");
	strcpy(sInputALanguageName, "Zadajte názov do jazyka");
	strcpy(sInsert, "Vložiť");
	strcpy(sInsertPiece, "Vložiť kus");
	strcpy(sInterface, "Rozhranie");
	strcpy(sInterfaceSettings, "Nastavenie rozhrania");
	strcpy(sInvalidHardware, "Nemohol som rozpoznať hardware. Prosím, kontaktujte nás na adrese contact@optimalprograms.com ~ ~ pobj");
	strcpy(sInvalidNumber, "Neplatné číslo");
	strcpy(sInvalidOrderOfComputation, "Aby pre výpočet dĺžky nemožno zistiť. Tam sú kruhové vzťahy v definície výrobku!");
	strcpy(sInvalidRegistration, "Registrácia je neplatný!");
	strcpy(sInvalidTime, "Čas vášho systému je neplatná.");
	strcpy(sInventory, "Inventár");
	strcpy(sisafractionalvalue, "je desatinná hodnota.");
	strcpy(sIsArc, "Je oblúku");
	strcpy(sisarealvalue, "je reálna hodnota.");
	strcpy(sLabel, "Štítok");
	strcpy(sLabels, "Etikety");
	strcpy(sLanguage, "Jazyk");
	strcpy(sLatimeanumar0, "Šírka musí byť väčšia ako 0!");
	strcpy(sLatimeanumarreal, "Šírka musí byť reálne číslo!");
	strcpy(sLayerName, "Názov vrstvy");
	strcpy(sLeft, "Ľavý");
	strcpy(sLeftcoordinateofthedefect, "Ľavé súradnice vady");
	strcpy(sLength, "Dĺžka");
	strcpy(sLengthofthepiecestocut, "Ks veľkosť pre rezanie");
	strcpy(sLengthofthepiecestocutfrom, "Rozmer pre rezanie");
	strcpy(sLengthofusedbars, "Veľkosť použitých tyčí");
	strcpy(sLicenseAgreement, "Licenčná zmluva");
	strcpy(sLinear, "Linear");
	strcpy(sLinethickness, "Hrúbka pera");
	strcpy(sLoadafileandappenddatatothecurrentDemand, "Načítať súbor a pripojiť údaje k aktuálnej dopytu.");
	strcpy(sLoadanexistingDemandfromafile, "Načítať existujúci dopytu zo súboru.");
	strcpy(sLoadAppend, "Načítať a Pripojiť");
	strcpy(sLoadEverything, "load všetko");
	strcpy(sLoadInventory, "Vložte tovar");
	strcpy(sLoadInventoryandDemand, "Vložte tovar a dopytu");
	strcpy(sLoadResults, "Vložte výsledkov");
	strcpy(sLocked, "zamknutý");
	strcpy(sLogo, "logo");
	strcpy(sLong, "Long");
	strcpy(sLongerexecutiontime, "Dlhšia doba realizácie");
	strcpy(sLungime, "Šírka");
	strcpy(sLungimeanumar0, "Dĺžka musí byť väčšia ako 0!");
	strcpy(sLungimeanumarreal, "Dĺžka musí byť reálne číslo!");
	strcpy(sLungimeaTotalaFolosita, "Celková využívaná dĺžka");
	strcpy(sMagnification, "Zväčšenie");
	strcpy(sMagnify, "Zväčšiť");
	strcpy(sMargins, "Okraje");
	strcpy(sMarginsForPaper, "Okraje pre papier");
	strcpy(sMarginsOfTheLabel, "Okraje štítku");
	strcpy(sMaterial, "Materiá");
	strcpy(sMaterialName, "Názov materiálu");
	strcpy(sMaterials, "materiály");
	strcpy(sMaterialstypes, "Materiály typy");
	strcpy(sMax, "Max");
	strcpy(sMaximalArea, "Maximálna plocha");
	strcpy(sMaximalCutLength, "Maximálna dĺžka rezu");
	strcpy(sMaxlength, "Maximálna dĺžka");
	strcpy(sMaxPiecesperBar, "Max Pocet kusov Bar");
	strcpy(sMaxwidth, "Maximálna šírka.");
	strcpy(sMeasurementUnit, "Jednotka merania");
	strcpy(sMin, "min");
	strcpy(sMinimalBreakSize, "Minimálna veľkosť prasknutie");
	strcpy(sMinimalUsefulSize, "Minimálna užitočné veľkosť");
	strcpy(sMinimalwastesizetoInventory, "Minimálny odpad veľkosť, aby zásob");
	strcpy(s_What_to_minimize, "Čo minimalizovať?");
	strcpy(sMinlength, "Minimálna dĺžka");
	strcpy(sMinwidth, "Minimálna šírka");
	strcpy(sMirror, "Zrkadlo");
	strcpy(sMirroring, "Zrkadlenie");
	strcpy(sMiscellaneous, "Zmiešaný");
	strcpy(sModify, "Upraviť");
	strcpy(sModifytheselectedpiece, "Upraviť vybraný kus");
	strcpy(sMovePiece, "Presunúť kúsok.");
	strcpy(sMultiplestages, "Viac Priebeh");
	strcpy(sName, "Meno");
	strcpy(sNameofedgeband, "Názov okrajových pásiem");
	strcpy(sNewDEMANDUnsaveddatawillbelost, "Nové diely? Neuložené dáta budú stratené!");
	strcpy(sNewLanguage, "Nový jazyk");
	strcpy(sNewMaterial, "Nový materiá");
	strcpy(sNewPasswordincorectlyintroduced, "Nové heslo nesprávne zavedený!");
	strcpy(sNewProduct, "Nový produkt");
	strcpy(sNewversion, "Nová verzia");
	strcpy(sNo, "Nie");
	strcpy(sNumarBucati, "Počet kusov");
	strcpy(sNumberOfCopies, "Počet kópií");
	strcpy(sNumberofstages, "Počet stupňov");
	strcpy(sNusuficienteplacidepozit, "Nie všetky kusy boli optimalizované. Možné príčiny: nie je dostatok kusov v inventári), Piece nie sú využité v optimalizácii), Typy kusov z Dopyt a inventúra nie sú uzavreté), ostatné parametre boli nesprávne nastavený. Ak nemôžete nájsť dôvod, prečo môžete poslať nám správu pomocou prístupu k menu Pomocník | Služby | Uložiť všetko. Prosím pošlite nám, e-mailom, generované súboru.");
	strcpy(sOfficeNotInstaled, "Microsoft Office nie je nainštalovaný na vašom počítači alebo verziu zlým je nainštalovaný!");
	strcpy(sOldpassworddoesnotmatch, "Staré heslo nesúhlasí!");
	strcpy(sOnlinehelp, "Online nápoveda");
	strcpy(sOnlypiecesofthesameheightinthelaststage, "Kúsky v rovnakej výške v poslednom štádiu.");
	strcpy(sOpen, "Otvoriť");
	strcpy(sOptimization, "Optimalizácia");
	strcpy(sOptimizationDone, "Optimalizácia vykonané! Môžete vytlačiť alebo uložiť získané diagramy. Stlačte tlačidlo Prijať, ak ste spokojní s aktuálnym riešením. V opačnom prípade stlačte Začať znova.");
	strcpy(sOptimizationType, "Typ optimalizácia");
	strcpy(sOptions, "možnosti");
	strcpy(sOptionsrelatedtotheinterface, "Voľby týkajúce sa rozhrania");
	strcpy(sor, "alebo");
	strcpy(sOthercomponents, "Ostatné komponenty");
	strcpy(sOthers, "Ostatné");
	strcpy(sOtherstatistics, "Ďalšie štatistiky");
	strcpy(sOverrideExcelCSVfiles, "Prepísať Excel / CSV súborov");
	strcpy(sParameter, "Parameter");
	strcpy(sParts, "DIELY");
	strcpy(sPattern, "Vzor");
	strcpy(sPatternforwaste, "Vzorka na odpad");
	strcpy(sPerimeter, "Obvod");
	strcpy(sPermitedRotationAngle, "Povolený uhol otočenia.");
	strcpy(sPhone, "Telefón");
	strcpy(sPicture, "obrázok");
	strcpy(sPiece, "Kus");
	strcpy(sPieceindex, "Kusové index");
	strcpy(sPieces, "Ks");
	strcpy(sPiecesize, "Kus má veľkosť");
	strcpy(sPiecesizelabeledgebandwillbeprinted, "Kus veľkosť,, štítok hrán pásma budú vytlačené.");
	strcpy(sPierdere, "Odpad");
	strcpy(sPixels, "pixelov");
	strcpy(sPlacilefolositeDepozit, "Využité kusy z inventára.");
	strcpy(sPlease_contact_us_at_contact_nestingtechnologies_com, "Prosím, kontaktujte nás na contact@nesting-technologies.com");
	strcpy(sPlease_contact_us_at_contact_optimalprograms_com, "Prosím, kontaktujte nás na contact@optimalprograms.com");
	strcpy(sPleaseenteralldataeitherasfractionalorrealDonotmixthem, "Zadajte prosím všetky údaje buď ako nepatrné, alebo skutočné Nemiešajte je!");
	strcpy(sPleaseEnterSomeTypesOfMaterials, "Neexistuje žiadny typ materiálu definovaného. Môžete definovať z materiálov menu.");
	strcpy(sPleasesendtheNameandtheCodetotheaddresscontactoptimalprogramscominordertoobtaintheRegistrationKey, "Za účelom získania registračného kľúča pošlite prosím názov a kód: contact@optimalprograms.com ~ ~ HEAD = dobj.");
	strcpy(sPolygon, "Polygon");
	strcpy(sPolygonsCircles, "Polygóny, kruhy");
	strcpy(sPrecision, "Presnosť");
	strcpy(sPretulnumar0, "Cena musí byť väčšia ako 0!");
	strcpy(sPretulnumarreal, "Cena musí byť reálne číslo!");
	strcpy(sPreview, "Náhľad");
	strcpy(sPrice, "Cena");
	strcpy(sPriceMustBeGreaterThanZero, "Cena musí byť väčší ako nula");
	strcpy(sPriceofbars, "Cena barov");
	strcpy(sPriceperbar, "Cena za barom");
	strcpy(sPricepersheet, "Cena za list");
	strcpy(sPricepersquareunitofmaterial, "Cena za štvorcový jednotku materiálu.");
	strcpy(sPriceperunit, "Cena za jednotku");
	strcpy(sPriceperunit, "Cena za jednotku");
	strcpy(sPrint, "Vytlačiť");
	strcpy(sPrintdiagramsastables, "Tlač diagramy vo forme tabuliek.");
	strcpy(sPrinter, "Tlačiareň");
	strcpy(sPrinterBounds, "Okraje pre tlačiareň");
	strcpy(sPrintonlyutilizedarea, "Tlač iba obhospodarovanej pôdy");
	strcpy(sPrintthecontentsoftheDemand, "Vytlačiť obsah Demand.");
	strcpy(sPrintthecontentsoftheInventory, "Vytlačiť obsah populácie.");
	strcpy(sPrintthecurrentsolution, "Tlač aktuálneho riešenia.");
	strcpy(sPriority, "Priorita");
	strcpy(sPrioritytocutapieceZero0isthehighestpriority, "Priorita znížiť kus. Nula (0) je najvyššou prioritou.");
	strcpy(sProcentul0100, "Tieto percent musí byť väčšia ako 0 a menší alebo rovný 100!");
	strcpy(sProcentulnumarreal, "Tieto percent musí byť reálne číslo!");
	strcpy(sProductdefinition, "Definícia výrobku");
	strcpy(sProductExists, "Produkt už existuje. Zvoľte iný názov.");
	strcpy(sProductName, "Názov výrobku");
	strcpy(sProducts, "Produkt");
	strcpy(sProducts, "Produkty");
	strcpy(sProject, "Projekt");
	strcpy(sProperties, "vlastnosti");
	strcpy(sProperty, "nehnuteľnosť");
	strcpy(sQuantity, "Množstvo");
	strcpy(sQuantitynumberofsheetsofthistype, "Počet listov tohto typu");
	strcpy(sRadius, "Polomer");
	strcpy(sRectangular, "Obdĺžnikový");
	strcpy(sRedefinetypesofedgeband, "Predefinovať typy hrán kapely");
	strcpy(sRedefinetypesofmaterial, "Predefinovať typov materiálov");
	strcpy(sRegistration, "Registrácia");
	strcpy(sRegistrationKeyfromOptimalPrograms, "Registračný kľúč");
	strcpy(sRegistrationSuccessful, "Registrácia prebehla úspešne!");
	strcpy(sRemoveallpiecesinInventory, "Odstráňte všetky kúsky v inventári.");
	strcpy(sRemoveCut, "Odstrániť rez");
	strcpy(sRemovetheselectedpiece, "Odstrániť vybranú kus");
	strcpy(sReports, "Správy");
	strcpy(sRequestedMaterial, "Požadované Materiá");
	strcpy(sRestore, "Obnoviť");
	strcpy(sResults, "Výsledky");
	strcpy(sReusedwaste, "Využitých odpadov");
	strcpy(sRight, "Právo");
	strcpy(sRightcoordinateofthedefect, "Súradnice defektu z pravej");
	strcpy(sRotation, "Rotácia");
	strcpy(sRotationAngle, "Uhol natočenia");
	strcpy(sRotationStep, "Rotácia krok.");
	strcpy(sRoundAllFractionsTo, "Tieto nepatrnej hodnoty musia byť zaokrúhlené na");
	strcpy(sRow, "riadok");
	strcpy(sRows, "Riadky");
	strcpy(sRun, "Najnovšie riešenie");
	strcpy(sRunningtime, "Doba chodu");
	strcpy(sSameforall, "Rovnaké pre všetky");
	strcpy(sSave, "Uložiť");
	strcpy(sSaveAllImages, "Uložiť všetky obrázky");
	strcpy(sSaveAs, "Uložiť ako");
	strcpy(sSaveChanges, "Dopyt bol zmenený. Chcete ušetriť?");
	strcpy(sSaveCurrentImage, "Uložiť aktuálny obrázok");
	strcpy(sSavedataparameters, "Uložiť dáta a parametre");
	strcpy(sSaveEverything, "uložiť všetko");
	strcpy(sSaveInventory, "Uložiť Inventory");
	strcpy(sSaveInventoryandDemand, "Uložiť zásob a dopyt");
	strcpy(sSaveResults, "Uložiť výsledky");
	strcpy(sSaveStatisticsinafile, "Uložiť štatistiky do súboru");
	strcpy(sSavethecurrentimage, "Uložiť aktuálny obrázok");
	strcpy(sSavethecurrentimageorstatistic, "Uložiť aktuálny obrázok alebo štatistických");
	strcpy(sSavetheDEMANDinafile, "Uložiť do súboru");
	strcpy(sSavetheDemandinafilewithadifferentname, "Uložte dopytu v súbore s iným názvom.");
	strcpy(sSavetheREPOSITORYinafile, "Uložiť úložiska v súbore");
	strcpy(sSerialNumber, "Registračný kľúč");
	strcpy(sService, "služba");
	strcpy(sSetDefaultValues, "To obnoví všetky parametre na ich predvolené hodnoty. Všetky vaše nastavenia budú stratené. Ste si istí, že to chcete urobiť?");
	strcpy(sSetedgeband, "Nastaviť hrany pásmo");
	strcpy(sSetedgetrim, "Nastavte rezanie za vady hrán");
	strcpy(sSetthesameedgebandforalledges, "Nastavte rovnakú hrany pásmo pre všetky hrany");
	strcpy(sSetthesamegrindingforalledges, "Nastavte rovnaké brúsenie pre všetky hrany.");
	strcpy(sSetthesametrimforalledges, "Nastavte rovnakú rezanie za vady pre všetky hrany");
	strcpy(sSettings, "Nastavenie");
	strcpy(sShape, "Tvar");
	strcpy(sSheet, "List");
	strcpy(sSheetsBarstypes, "Listy_koncovky typy");
	strcpy(sSheetSize, "Veľkosť listu");
	strcpy(sSheetsperPage, "Listov na stránke");
	strcpy(sShort, "Krátky");
	strcpy(sShorterexecutiontime, "Krátka doba chodu");
	strcpy(sShowallsimpleproducts, "Zobraziť všetky jednoduché produkty");
	strcpy(sShowcustomername, "Zobraziť meno zákazníka");
	strcpy(sShowCustomTextOnEachPiece, "Zobraziť vlastného textu na každom kuse");
	strcpy(sShowdiagramasatable, "Zobraziť diagram ako stôl.");
	strcpy(sShowedgeband, "Zobraziť okrajov pásiem");
	strcpy(sShowedgebandssettinginanewwindow, "Zobraziť nastavenia krajných pásmach v novom okne.");
	strcpy(sShowgrindingsettingsinanewwindow, "seriály brúsenie nastavenia v novom okne.");
	strcpy(sShowHorizontalLabelsAlways, "Show vždy horizontálne štítky");
	strcpy(sShowRemovethesizeofthepiecesinthecurrentsolution, "Zobraziť / Odobrať veľkosti kusov v aktuálnom riešení.");
	strcpy(sShowRemovethesizeofthewastesinthecurrentsolution, "Zobraziť / Odobrať o veľkosti odpadov v aktuálnom riešení.");
	strcpy(sShowtotalcutlength, "Zobraziť celkovú reznú dĺžku");
	strcpy(sShowtrimedgesettingsinanewwindow, "Zobraziť nastavenia vád v novom okne.");
	strcpy(sSimpleMaterialExists, "Názov materiálu je už definovaný v zozname materiálov. Prosím, dať mu nové meno.");
	strcpy(sSinglePieceStrips, "Stripes jedného kusu.");
	strcpy(sSizes, "Veľkosti");
	strcpy(sSmallerorequalto, "Menšie alebo rovné");
	strcpy(sSort, "druh");
	strcpy(sSortAscendingByArea, "Zoradiť vzostupne podľa oblasti");
	strcpy(sSortDescendingByArea, "Zoradiť zostupne podľa plochy");
	strcpy(sSpecifyhowdifferentthepiecesinthelaststagecanbeValue0meansnodifference, "Určite, ako rôzne môžu byť kusy v poslednej fáze. Hodnota 0 znamená žiadny rozdiel.,");
	strcpy(sSpecifyifpiecesinthelaststagecanbedifferentornotdepeultimaetapapotfidiferitesaunucadimensiune, "Určite, či kusy v poslednej fáze môže byť odlišná, alebo nie");
	strcpy(sSpecifyifthepiececanberotatedornotIfnotitwillbecutinthesamewayasitwasintroducedinDemandLengthofthepieceparalleltothelengthofthesheet, "Určenie prípade, že kus môže byť otočený alebo nie. Ak nie, bude narezaný rovnakým spôsobom, ako to bolo zavedené v Demand (dĺžka kusu súbežne s dĺžkou listu),");
	strcpy(sSpecifyinhowmanystageswemakethecutsDuringastageallcutshavethesamedirection, "Určite, v koľkých fázach robíme škrty.");
	strcpy(sStartthesearchprocess, "Spustiť proces hľadania");
	strcpy(sStatistics, "Štatistika");
	strcpy(sStatisticsE, "Správy Extra");
	strcpy(sStatisticsforeachtypeofmaterial, "Štatistika pre každý typ materiálu");
	strcpy(sStep, "Krok");
	strcpy(sStergeDepozit, "Ak chcete odstrániť zásob?");
	strcpy(sStergeMaterial, "Odstrániť materiál?");
	strcpy(sStergePiesele, "Ak chcete odstrániť skladbu?");
	strcpy(sStergePiesa, "Ak chcete odstrániť skladbu?");
	strcpy(sStopthesearchprocess, "Zastavte proces hľadania");
	strcpy(sStrongoptimization, "Silný optimalizácia");
	strcpy(sSubtractthebandthicknessfrompiecesize, "Zmenšenie kus veľkosti s kapelami hrúbke.");
	strcpy(sSummary, "Zhrnutie");
	strcpy(sSuprafataTotalaFolosita, "Celkom používa plocha");
	strcpy(sSuprafatautilizata, "Využitie");
	strcpy(sSwitchbetweenfiberandrotationoption, "Prepínanie medzi vlákna a možnosť striedania.");
	strcpy(sTechnical, "Technický");
	strcpy(sTechnicalsettings, "Technické nastavenie");
	strcpy(sTemporaryPanelHint, "Dočasné panel pre pohyblivé časti medzi listami.");
	strcpy(sText, "text");
	strcpy(sThe_application_has_expired, "Program vypršala.");
	strcpy(sThe_application_is_not_registered, "Softvér nie je registrovaný.");
	strcpy(sThe_application_was_first_started_on, "Softvér bol prvýkrát spustený.");
	strcpy(sThecutsareperformedfromasidetotheothersideofthematerial, "Inkaso sa vykonáva z boku na druhej strane materiálu.");
	strcpy(sThecuttingmachinecanfollowtheshapeofthematerial, "Rezačka môžu sledovať tvar kusu.");
	strcpy(sTheedgesofsheetsthatmustbetrimedduefaults, "Okraje listov, ktoré musia byť orezané z dôvodu porúch");
	strcpy(sTheLargestSize, "Najväčšiu veľkosť");
	strcpy(sThenameofthecustomerforwhichyoucutthepiece, "Meno zákazníka, pre ktoré časti ste kosiť kus.");
	strcpy(sThenameofyourcustomer, "Meno zákazníka");
	strcpy(sThepiececanberotated, "Kus možno otáčať");
	strcpy(sTheprogramtriestoavoidwasteswhichhavebothsizeslessthanthisvalue, "Program sa snaží, aby sa zabránilo odpady, ktoré majú obe veľkosti menšia ako táto hodnota");
	strcpy(sThereAreNoProducts, "Zatiaľ nie sú žiadne produkty zatiaľ");
	strcpy(sThestockofmaterialhasbeenpreviouslyloadedfromanExcelorCSVformatPleaseloaditagain, "Zásoby materiálu už nahraný z programu Excel alebo CSV formáte. Prosím, vložte ju znova, ak chcete pracovať na ňom.");
	strcpy(sThetotallengthofcutting, "Celková dĺžka rezu");
	strcpy(sThewidthofthecuttingsawForglasscuttingoptimizationitcanbe0Forwooditshouldbegreaterthan0, "Hrúbka píly. Pre rezanie skla môže byť 0. Na drevo by malo byť väčšie ako 0,.");
	strcpy(sThewidthofthecuttingsawforlinearpieces, "Hrúbka píly pre lineárne kusy.");
	strcpy(sThickness, "Hrúbka");
	strcpy(sThischaracterisusedforfillingthewasterectanglesIfyoudonotwantfilledwastejustremovethischaracter, "Tento symbol sa používa na vyplnenie odpadových obdĺžniky. Ak nechcete, aby vyplnený odpad len odstrániť to.");
	strcpy(sThisindexhasvaluebetween1andthenumberofpieces, "Tento index má hodnotu medzi 1 a počet kusov.");
	strcpy(sThisOptionWillOverrideTheInventoryFileIfLoadedFromExcelOrCsvFiles, "Táto voľba prepíše súbor obsahujúci zásobu ak populácie je načítaný z programu Excel alebo CSV súborov.");
	strcpy(sThisProgramisLicensedTo, "Tento program je licencovaný na");
	strcpy(sThisvaluewillbeaddedtotheedgebandingmaterialoneachside, "Táto hodnota sa pridá k olepovanie materiálu na každej strane");
	strcpy(sTipNevid, "Typ materiálu nemôže byť prázdny.");
	strcpy(sTitle, "Názov");
	strcpy(sTools, "náradie");
	strcpy(sTop, "Top");
	strcpy(sTopcoordinateofthedefect, "Horná Súradnice vady.");
	strcpy(sTotalGarbageWaste, "Všetky zlikvidovať odpad");
	strcpy(sTotalInventoryWaste, "Úplná odpad");
	strcpy(sTotalRecycledWaste, "Všetky recyklovaný odpad");
	strcpy(sTotalusedarea, "Celková plocha použitá");
	strcpy(sTotalusedlength, "Celková dĺžka použiť");
	strcpy(sTrigonometric, "Goniometrické");
	strcpy(sTrim, "Zastrihnúť");
	strcpy(sTrimalledgesatthebeginning, "Orežte všetky hrany na začiatku");
	strcpy(sTrimEdge, "Orežte okraj");
	strcpy(sTwoPanels, "2 panely");
	strcpy(sType, "typ");
	strcpy(sTypeofmaterialfromwhichtocut, "Typ materiálu, z ktorého sa znížiť");
	strcpy(sTypesAreNotMatched, "Optimalizácia sa nevykonala! Materiály z tabuliek Diely a Sklad sa nezhodujú! Dielec je možné vyrezať iba z materiálu s rovnakým názvom v sklade. Zmeňte názvy materiálov z príslušných stĺpcov!");
	strcpy(sUndo, "Zrušiť");
	strcpy(sUndoAccept, "Vrátiť Prijať");
	strcpy(sUnits, "jednotky");
	strcpy(sUnregisteredVersion, "Neregistrovaný");
	strcpy(sUpdates, "Aktualizácie");
	strcpy(sUsefulforwoodfurniture, "Vhodné pre drevený nábytok");
	strcpy(sUseit, "Použite ho");
	strcpy(sUsePieceinOptimization, "Použite kus v optimalizácii");
	strcpy(sUserName, "Užívateľské meno");
	strcpy(sUtilizationandWastes, "Využitie a Odpady");
	strcpy(sUtilizedArea, "Oblasť využívaných častí");
	strcpy(sUtilizedBars, "Využil tyče");
	strcpy(sUtilizeddemandcount, "Počet použitých kusov.");
	strcpy(sUtilizedParts, "Využil diely");
	strcpy(sUtilizedPieces, "Využité kusov");
	strcpy(sUtilizedSheets, "Využil listov");
	strcpy(sValue, "Hodnota");
	strcpy(sValueGreaterEqualToZero, "Hodnota musí byť väčšia alebo rovná nule");
	strcpy(sValueGreaterThanZero, "Hodnota musí byť väčšia ako nula");
	strcpy(sValueIntegerNumber, "Hodnota musí byť celé číslo!");
	strcpy(sValueRealNumber, "Hodnota musí byť reálne číslo. Možno ste použili, miesto. alebo obrátene. Opravte ich prosím!");
	strcpy(s_The_number_is_too_big_or_it_has_too_many_digits_after_decimal_separator, "Číslo je príliš veľké alebo má príliš veľa číslic za desatinnou čiarkou!");
	strcpy(s_The_number_is_too_big, "Číslo je príliš veľké!");
	strcpy(sVertical, "Vertikálne");
	strcpy(sWaste, "Odpad");
	strcpy(sWastes, "Odpad");
	strcpy(sWasteAddedToWarehouse, "Odpadové pridaný do skladu");
	strcpy(sWastelimits, "limity pre vypúšťanie odpadových");
	strcpy(sWasteType, "Druh odpadu");
	strcpy(sWeakoptimization, "Najslabší optimalizácia");
	strcpy(sWhattoprint, "Čo by som mal vytlačiť");
	strcpy(s_What_to_print_or_save_to_file, "Čo vytlačiť alebo uložiť do súboru");
	strcpy(sWhattoprintoneachpiece, "Čo tlačiť na každý kus");
	strcpy(sWhattoshowoneachpiece, "Čo pre zobrazenie na každom kuse?");
	strcpy(sWidth, "Šírka");
	strcpy(sWood, "drevo");
	strcpy(sWorkingDirectory, "Pracovný adresár");
	strcpy(sWrongKey, "Zle Registračné kľúč!");
	strcpy(sYes, "Áno");
	strcpy(sYoucannotchooseblackblueorredcolors, "You cannot choose black, blue or red colors.");
	strcpy(sYouCannotMixFractionalDataWithDecimalOnes, "Nemožno kombinovať nepatrnej hodnoty sa skutočnými hodnotami!");
	strcpy(sYourcompany, "Vaša spoločnosť");
	strcpy(sZip, "PSČ");
	strcpy(s_Set_the_origin_and_the_direction_of_the_axes, "Nastavte počiatok a smer osí súradníc.");










	strcpy(s_Number_of_digits_after_the_decimal_separator, "Počet číslic za oddeľovačom desatinných miest");
	strcpy(s_Percentages, "Percentá");
}

