// Language strings: Indonesian
// Author: Optimal Programs
// License: MIT License
//---------------------------------------------------------------------------
#include <string.h>
//---------------------------------------------------------------------------
#include "language_string_id.h"
//---------------------------------------------------------------------------
void set_id(void)
{
	//Indonesian
	//automatic translation
	//2025.3.29.0
	strcpy(s_Advanced, "Canggih");
	strcpy(s_Relative_coordinates, "Koordinat relatif");
	strcpy(s_Absolute_coordinates, "Koordinat absolut");
	strcpy(s_Append_more_rows, "Tambahkan lebih banyak baris");

	strcpy(s_Add_to_parts, "Tambahkan ke bagian.");
	strcpy(s_Additional, "Tambahan");
	strcpy(s_All_results, "Semua hasil.");
	strcpy(s_Allow_movement_of_pieces, "Izinkan gerakan potongan");
	strcpy(s_Allow_part_in_part, "Biarkan sepotong demi sepotong");
	strcpy(s_Invalid_piece_Angles_are_too_small_or_too_big_or_height_is_too_small, "Potongan tidak valid! Sudutnya terlalu kecil atau terlalu besar, atau tingginya terlalu kecil.");
	strcpy(s_Append, "Menambahkan");
	strcpy(s_As_it_is, "Apa adanya");
	strcpy(s_As_text, "Sebagai teks");
	strcpy(s_Ascending, "Naik");
	strcpy(s_Automatic, "Otomatis");
	strcpy(s_Cannot_connect_to_the_Internet_Please_visit_our_website_from_a_browser, "Tidak dapat terhubung ke Internet! Silakan kunjungi situs web kami dari browser.");
	strcpy(s_Cannot_copy_or_move_the_files, "Tidak dapat menyalin atau memindahkan file!");
	strcpy(s_Cannot_delete_the_file, "Tidak dapat menghapus file!");
	strcpy(s_Cannot_modify_old_results, "Tidak dapat mengubah hasil lama!");
	strcpy(s_To_change_click_inside_a_cell_or_press_0_1_or_2, "Untuk mengubahnya, klik di dalam sel atau tekan 0, 1, atau 2.");
	strcpy(s_Cell, "Sel");
	strcpy(s_Click_on_the_table_header_to_change_the_columns, "Klik pada header tabel untuk mengubah kolom.");
	strcpy(s_Close, "Tutup itu");
	strcpy(s_Contact_us, "Hubungi kami");
	strcpy(s_Column, "Kolom");
	strcpy(s_Comma, "Koma");

	strcpy(s_Copy, "Salinan");
	strcpy(s_Copy_for_move, "Salin untuk pindah");
	strcpy(s_Cut_higher_level_strips_first, "Potong strip tingkat tinggi terlebih dahulu");
	strcpy(s_Cut_index, "Potong indeks");

	strcpy(s_The_data_have_been_changed_Do_you_want_to_save_them_to_a_file, "Datanya telah diubah. Apakah Anda ingin menyimpannya ke file?");
	strcpy(s_Decimal_separator, "Pemisah desimal");
	strcpy(s_Restore_default_settings, "Mengembalikan pengaturan default");
	strcpy(s_Delete_fiber, "Hapus serat");
	strcpy(s_Descending, "Menurun");
	strcpy(s_Discard_changes, "Membuang perubahan");

	strcpy(s_Delete_all_data, "Hapus semua data?");
	strcpy(s_Dot, "Dot");
	strcpy(s_Do_you_want_to_delete_the_picture, "Apakah Anda ingin menghapus gambar?");
	strcpy(s_Do_you_want_to_delete_the_product, "Apakah Anda ingin menghapus produk?");
	strcpy(s_Duplicate_and_append, "Gandakan dan tambahkan.");
	strcpy(s_Duplicate_values_are_ignored, "Nilai duplikat telah diabaikan!");
	strcpy(s_Error, "Kesalahan");
	strcpy(s_Error_loading_file, "Terjadi kesalahan saat memuat file.");
	strcpy(s_export_everything, "Ekspor semuanya");
	strcpy(s_Fit_to_screen, "Pas dengan layar.");
	strcpy(s_Force_fixed_height, "Gambarlah potongan-potongan dengan ketinggian tetap.");
	strcpy(s_Flipped, "Terbalik");
	strcpy(s_Import, "Impor");
	strcpy(s_If_angles_are_different_from_90_degrees_height_must_be_greater_than_0, "Jika sudutnya berbeda dari 90 derajat, tingginya harus lebih besar dari 0.");
	strcpy(s_Ignore, "Mengabaikan");
	strcpy(s_Incorrect_value, "Nilai salah");
	strcpy(s_Info, "info");
	strcpy(s_Interior, "Pedalaman");
	strcpy(s_Give_a_name, "Beri nama.");
	strcpy(s_Group, "Kelompokkan itu");
	strcpy(s_Header, "Tajuk");
	strcpy(s_Keep_it_as_it_is, "Tetap seperti itu");
	strcpy(s_Level, "Level");
	strcpy(s_Licensee, "Penerima Lisensi");
	strcpy(s_List_separator, "pemisah daftar");
	strcpy(s_Made_with_love_in_Cugir_Romania, "Dibuat dengan cinta di Cugir, Rumania");
	strcpy(s_Made_in, "Diproduksi di");
	strcpy(s_Manufacturer, "Pabrikan");

	strcpy(s_Manual_arrange, "Pengaturan manual");

	strcpy(s_Mixed, "Campuran");
	strcpy(s_Multiple_shapes_detected_Next_rows_will_be_overwritten_Continue, "Lebih dari satu bentuk terdeteksi. Oleh karena itu, baris berikutnya akan ditimpa. Melanjutkan?");
	strcpy(s_More, "Lagi");
	strcpy(s_Multiple_values, "Banyak nilai");
	strcpy(s_No_texture, "Tanpa Tekstur");
	strcpy(s_Number, "Jumlah");
	strcpy(s_Number_of_images, "Jumlah gambar");
	strcpy(s_Number_of_vertices, "Jumlah simpul");
	strcpy(s_Offset, "Mengimbangi");
	strcpy(s_Only_the_currently_selected_items, "Hanya item yang dipilih saat ini.");
	strcpy(s_Optimizing_please_wait, "Mengoptimalkan ... harap tunggu.");

	strcpy(s_Paste, "Paste");

	strcpy(s_Piece_label, "Label bagian");
	strcpy(s_Piece_size, "Ukuran potongan");
	strcpy(s_Please_contact_us_by_email_if_you_receive_this_error, "Silakan hubungi kami melalui email jika Anda menerima kesalahan ini.");
	strcpy(s_Please_save_it_first, "Tolong simpan dulu.");
	strcpy(s_Position, "Posisi");
	strcpy(s_Preview, "Pratinjau");
	strcpy(s_Rectangle, "Empat persegi panjang");

	strcpy(s_Redo_the_last_operation, "Kembalikan operasi terakhir");
	strcpy(s_Regular_polygon, "Poligon beraturan");

	strcpy(s_Reused, "Digunakan kembali");
	strcpy(s_Rotated, "Diputar");
	strcpy(s_Save_all, "Simpan semua");
	strcpy(s_Scrap_label, "Label Scrap");
	strcpy(s_Scrap_size, "Ukuran memo");
	strcpy(s_Semicolon, "Titik koma");
	strcpy(s_Show_cut_index, "Tampilkan indeks cut");
	strcpy(s_Show_information, "Tampilkan info");
	strcpy(s_Show_piece_label, "Tampilkan label bagian");
	strcpy(s_Show_scrap_label, "Tampilkan label memo");
	strcpy(s_Show_scrap_s_size_on_the_small_pieces, "Tampilkan ukuran memo pada potongan-potongan kecil");
	strcpy(s_Show_size_of_pieces, "Tampilkan ukuran barang");
	strcpy(s_Show_size_of_scrap, "Tampilkan ukuran memo");
	strcpy(s_Show_sizes, "Tampilkan ukuran");
	strcpy(s_Show_label, "Tampilkan label");
	strcpy(s_Show_length, "Tampilkan panjang");

	strcpy(s_Some_numerical_values_are_incorrect_Should_I_fix_all_the_incorrect_values, "Beberapa nilai numerik salah! Haruskah saya memperbaiki semua nilai yang salah?");
	strcpy(s_Some_invalid_values_have_been_removed, "Beberapa nilai yang tidak valid telah dihapus.");
	strcpy(s_Sort_by, "Sortir dengan");
	strcpy(s_Sort_ascending_by, "Sortir naik menurut");
	strcpy(s_Sort_descending_by, "Sortir turun menurut");
	strcpy(s_Start, "Start");
	strcpy(s_Starting_angle, "Sudut mulai");


	strcpy(s_Stock, "Persediaan");
	strcpy(s_Stop, "Stop");

	strcpy(s_Tabular, "Datar");
	strcpy(s_Total, "Total");
	strcpy(s_Total_size, "Ukuran total");
	strcpy(s_Terms_of_the_license, "Ketentuan lisensi");
	strcpy(s_The_current_product_has_been_changed_Do_you_want_to_save_it_to_file, "Produk saat ini telah diubah. Apakah Anda ingin menyimpannya ke file?");
	strcpy(s_The_value_is_out_of_the_allowed_range, "Nilainya di luar rentang yang diizinkan.");
	strcpy(s_The_value_must_be_a_real_or_fractional_number_Try_to_replace_the_comma_with_the_dot_if_you_want_to_enter_a_real_number, "Nilai harus berupa angka nyata atau fraksional. Coba ganti koma dengan titik jika Anda ingin memasukkan bilangan real.");
	strcpy(s_This_feature_is_not_implemented_yet, "Fitur ini belum diterapkan.");
	strcpy(s_This_operation_cannot_be_reversed, "Operasi ini tidak dapat dibatalkan.");
	strcpy(s_Undo_the_last_operation, "Membatalkan operasi terakhir.");
	strcpy(s_Utilization, "Pemanfaatan");
	strcpy(s_Utilized_Stock, "Stok yang Digunakan");
	strcpy(s_Version, "Versi: kapan");
	strcpy(s_Visible_columns, "Kolom yang terlihat");
	strcpy(s_You_already_have_the_latest_version_installed, "Anda sudah menginstal versi terbaru!");
	strcpy(s_What_is_exported, "Apa yang diekspor?");
	strcpy(s0meansanynumberofpieces, "Nol berarti jumlah potongan");
	strcpy(sAbout, "Tentang");
	strcpy(sAccept, "Menerima");
	strcpy(sAcceptall, "Terima semua");
	strcpy(sAcceptthecurrentsolution, "Terima solusi saat ini");
	strcpy(sAdd, "Menambahkan");
	strcpy(sAddapiece, "Tambahkan sepotong");
	strcpy(sAddasimpleproducttoDemand, "Tambahkan produk ke bagian yang ada.");
	strcpy(sAddgrindingthicknesstopartsize, "Tambahkan ketebalan gerinda ke ukuran potong");
	strcpy(sAddproductnametolabel, "Tambahkan nama produk ke label");
	strcpy(sAddress, "Alamat");
	strcpy(sAddselectedsizetoInventory, "Tambahkan ukuran yang dipilih ke stok");
	strcpy(sAdhesivelabels, "Label perekat");
	strcpy(sAdhesivelabelwithinformationaboutpiecesinDemandCustomernameLabelSizeCurrentData, "Label perekat dengan informasi tentang potongan: Nama pelanggan, Label, Ukuran, Data Saat Ini dll.");
	strcpy(sAdhesivelabelwithinformationaboutsheetsinInventory, "Label berperekat dengan informasi tentang lembar stok.");
	strcpy(sAll, "Semua");
	strcpy(sAlloffcutswhichhavethesizegreaterthanthisvaluewillbeaddedtoInventory, "Semua memo yang lebih besar dari nilai ini akan ditambahkan ke stok");
	strcpy(sAllowMirroring, "Bolehkan membalik");
	strcpy(sAllowRotation, "Izinkan rotasi");
	strcpy(sAllPieces, "Semua bagian");
	strcpy(sAllpredefinedproducts, "Semua produk yang telah ditentukan");
	strcpy(sAnewwindowwillbedisplayedwheretheusercansettheedgebandsforeachedge, "Jendela baru akan ditampilkan di mana pengguna dapat mengatur pita tepi untuk setiap sisi.");
	strcpy(sAnewwindowwillbedisplayedwheretheusercansetthegrindingvalueforeachedgeofthsheet, "Jendela baru akan ditampilkan di mana pengguna dapat mengatur ukuran gerinda untuk setiap sisi potongan.");
	strcpy(sAnewwindowwillbedisplayedwheretheusercansetthetrimvalueforeachedgeofthsheet, "Jendela baru akan ditampilkan di mana pengguna dapat mengatur nilai trim untuk setiap sisi potongan.");
	strcpy(sAngle, "Sudut");
	strcpy(sAngles, "Sudut");
	strcpy(sAnoptimizationparameterisarealnumber, "Parameter optimisasi adalah bilangan real.");
	strcpy(sAnoptimizationparameterisfractionalnumber, "Parameter optimisasi adalah angka pecahan.");
	strcpy(sAnyShape, "Bentuk sejati");
	strcpy(sApolygonmusthaveatleast2vertices, "Poligon harus memiliki setidaknya 2 simpul!");
	strcpy(sApolygonmusthaveatleast3vertices, "Poligon harus memiliki setidaknya 3 simpul!");
	strcpy(sApplication_fails_to_initialize, "Aplikasi gagal diinisialisasi!");
	strcpy(sArc, "Busur");
	strcpy(sArcLength, "Panjang busur");
	strcpy(sAreaofusedsheets, "Luas lembar yang digunakan");
	strcpy(sAshortdescriptionofthesheet, "Penjelasan singkat dari lembar tersebut");
	strcpy(sAtleastonepart, "Anda harus memasukkan setidaknya satu potong.");
	strcpy(sAtTheMarginOfTheSheet, "Di tepi lembaran");
	strcpy(sBandtypes, "Jenis pita tepi");
	strcpy(sBar, "Bar");
	strcpy(sBars, "Bar");
	strcpy(sBothsizesoftheoffcutsmustbegreaterthanthisvalue, "Kedua ukuran memo harus lebih besar dari nilai ini.");
	strcpy(sBottom, "Bawah");
	strcpy(sBottomcoordinateofthedefect, "Koordinat bawah cacat");
	strcpy(sBreakCut, "Hancurkan luka");
	strcpy(sBrowse, "Telusuri");
	strcpy(sBuy, "Membeli");
	strcpy(sBuynow, "Beli sekarang ...");
	strcpy(sCancel, "Batalkan");
	strcpy(sCannotBeEmpty, "tidak boleh kosong!");
	strcpy(sCannotmovepartsbetweensheetswhenidenticalsheetsaregroupedPleaseungroupthesheetsfrommenu, "Tidak dapat memindahkan bagian dari satu lembar ke lembar lainnya jika lembar yang sama dikelompokkan. Harap batalkan pengelompokan lembaran dari menu.");
	strcpy(sCannotSaveFile, "Tidak dapat menyimpan file");
	strcpy(sCenter, "Pusat");

	strcpy(sChangeDirection, "Ubah arah pemotongan");
	strcpy(sChoose, "Memilih");
	strcpy(sChooseProduct, "Pilih produk");
	strcpy(sCircle, "Lingkaran");
	strcpy(sCity, "Kota");
	strcpy(sClear, "Bersih");
	strcpy(sClockWise, "Searah jarum jam");
	strcpy(sClosewindow, "Tutup jendela");
	strcpy(sColor, "Warna");
	strcpy(sColorofedgeband, "Warna pita tepi");
	strcpy(sColorPattern, "Warna / pola");
	strcpy(sColorpiecesandwastes, "Potongan dan limbah berwarna");
	strcpy(sColumns, "Kolom");
	strcpy(sComment, "Komentar");
	strcpy(sCompanyname, "Nama Perusahaan");
	strcpy(sComplexMaterialExists, "Nama bahan sudah didefinisikan dalam daftar bahan kompleks. Tolong beri nama baru.");
	strcpy(sComputerCode, "Kode komputer");
	strcpy(sComputerCodefromyourcomputer, "Kode Komputer (dari komputer Anda)");
	strcpy(sComputethetotalpriceofDemand, "Hitung harga total Bagian");
	strcpy(sContents, "Isi");
	strcpy(sContinutComanda, "Konten Bagian dalam tanggal");
	strcpy(sContinutDepozit, "Konten Stok pada tanggal tersebut");
	strcpy(sConversionIsDoneOnlyWhenSomePiecesHaveFractionalValues, "Konversi dilakukan hanya ketika beberapa potong memiliki nilai fraksional.");
	strcpy(sConvertsTheSizeOfWasteToAFractionalUnit, "Memperlihatkan ukuran memo sebagai nilai fraksional.");
	strcpy(sCouldNotSaveFile1, "Tidak dapat menulis file di direktori");
	strcpy(sCouldNotSaveFile2, "Anda mungkin tidak memiliki hak yang cukup. Silakan periksa atau ubah direktori kerja dari menu Pengaturan | Direktori kerja ke folder tempat Anda memiliki hak untuk menulis (misalnya c: \\ temp).");
	strcpy(sCreationdateYMDHMS, "Tanggal pembuatan (Y / M / D- H: M: S)");
	strcpy(sCurrentDate, "Tanggal sekarang");
	strcpy(sCurrentDiagram, "Diagram saat ini");
	strcpy(sCurrentMaterial, "Bahan saat ini");
	strcpy(sCurrentversion, "Versi sekarang");
	strcpy(sCurve_not_closed_Try_increasing_DXF_linking_distance_parameter, "Poligon tidak ditutup! Coba tambah parameter jarak penautan DXF.");
	strcpy(sCustomer, "Pelanggan");
	strcpy(sCustomerName, "Nama Pelanggan");
	strcpy(sCustomMessage, "Pesan khusus");
	strcpy(sCutlength, "Panjang luka");
	strcpy(sCut, "Memotong");
	strcpy(sCuts, "Pemotongan");
	strcpy(sCutterThickness, "Ketebalan potong");
	strcpy(sData, "Data");
	strcpy(sDataCannotBeEmpty, "Data tidak boleh kosong!");
	strcpy(sDateymdhms, "Tanggal (y / m / d / h / m / s)");
	strcpy(sDays_left_for_trial, "Hari yang tersisa untuk diadili");
	strcpy(sDaysLeft, "hari yang tersisa");
	strcpy(sStandard, "Default");
	strcpy(sDefaultInterface, "Antarmuka Default");
	strcpy(sDefects, "Cacat");
	strcpy(sDefectsManager, "Kelola cacat");
	strcpy(sDefectsofthematerialNopiecescanbeplacedinthefaultyzone, "Kerusakan material. Tidak ada potongan yang dapat ditempatkan di zona yang salah.");
	strcpy(sDelete, "Menghapus");
	strcpy(sDeletePiece, "Hapus bagian");
	strcpy(sDeleteRow, "Hapus baris");
	strcpy(sDemandutilization, "Pemanfaatan bagian");
	strcpy(sDepozitulmodificat, "Potongan-potongan yang digunakan telah dihapus. Memo telah ditambahkan ke stok.");
	strcpy(sDepozitvid, "Stok kosong");
	strcpy(sDesk, "meja tulis");
	strcpy(sDiagram, "Diagram");
	strcpy(sDiagrams, "Diagram");
	strcpy(sDiagramasatable, "Diagram sebagai tabel");
	strcpy(sDigits, "digit");
	strcpy(sDimensiuniplaca, "Ukuran lembar");
	strcpy(sDirection, "Arah");
	strcpy(sDistanceBetweenRows, "Jarak antar baris");
	strcpy(sDonotuseit, "Jangan gunakan itu");
	strcpy(sDownload, "Unduh");
	strcpy(sDoYouWantToClearTheData, "Apakah Anda ingin menghapus data?");
	strcpy(sDoYouWantToSaveDemand, "Bagian-bagian telah diubah! Apakah Anda ingin menyimpan perubahan?");
	strcpy(sDoYouWantToSaveParts, "Apakah Anda ingin menyimpan bagian?");
	strcpy(sDoYouWantToSaveRepository, "Stok telah berubah! Apakah Anda ingin menyimpan perubahan?");
	strcpy(sDrawing, "Gambar");
	strcpy(sDrawthesolutioncolorful, "Gambarkan solusinya dengan penuh warna");
	strcpy(sDuplicateTypes, "Beberapa jenis digandakan! Harap hapus duplikat");
	strcpy(sDuplicateTypesWithComplex, "Beberapa nama bahan sudah ada dalam daftar jenis kompleks! Harap hapus duplikat");
	strcpy(sDuplicateValues, "Nilai duplikat");
	strcpy(sEdgeband, "Band tepi");
	strcpy(sEdgebandingwhichisplacedontheedgesofyourpiecePleasedefineedgebandingtypesfromMaterialsEdgeBandingmenu, "Pita tepi ditempatkan di tepi potongan Anda. Silakan tentukan band tepi di menu Bahan.");
	strcpy(sEdgebandsthatwillbeappliedtoeachpart, "Pita tepi yang diterapkan untuk masing-masing bagian.");
	strcpy(sEdgeBandTolerance, "Toleransi untuk pita tepi");
	strcpy(sEdgesthatmustbecutduefaults, "Tepi yang harus dipotong karena cacat.");
	strcpy(sEdgetoedge, "Dari ujung ke ujung");
	strcpy(sEdit, "Edit");
	strcpy(sEmail, "Surel");
	strcpy(sEmptyData, "Data kosong!");
	strcpy(sEnabled, "Diaktifkan");
	strcpy(sEnabledisabledefectsoftheinventorysheets, "Mengaktifkan / menonaktifkan cacat stok");
	strcpy(sEnterLabel, "Masukkan label");
	strcpy(sEnterTheMaterialName, "Masukkan nama materi");
	strcpy(sEnterTheProductName, "Masukkan nama produk");
	strcpy(sEvaluationError, "Kesalahan evaluasi evaluasi!");
	strcpy(sExit, "Keluar");
	strcpy(sExpired, "Perangkat lunak telah kedaluwarsa! Silakan daftarkan perangkat lunak!");
	strcpy(sExport, "Ekspor");
	strcpy(sExportAllDiagrams, "Ekspor semua diagram");
	strcpy(sExportAllToASingleFile, "Ekspor semua ke satu file");
	strcpy(sExportOptions, "Opsi ekspor");
	strcpy(sExporttoDXFformat, "Ekspor ke format DXF");
	strcpy(sExporttoExcel, "Ekspor ke Excel");
	strcpy(sExpresieIncorecta, "Ungkapan matematika salah!");
	strcpy(sExtensions, "Ekstensi");
	strcpy(sExtra, "Tambahan");
	strcpy(sExtraComponents, "Komponen Ekstra");
	strcpy(sExtracomponentsattachedtoDemand, "Komponen ekstra melekat pada bagian");
	strcpy(sFile, "Mengajukan");
	strcpy(sFileName, "Nama file");
	strcpy(sFillWastes, "Gambarlah sampah dengan garis miring");
	strcpy(sFindoptimalbarsheetsize, "Temukan ukuran optimal untuk batang dan lembaran.");
	strcpy(sFindoptimalsizeofInventorypieces, "Temukan ukuran optimal stok barang");
	strcpy(sFirstcutMultiplestages, "Arah pemotongan pertama untuk optimalisasi beberapa tahap.");
	strcpy(sFirstdirectionforcutishorizontal, "Arah pertama untuk memotong adalah horisontal.");
	strcpy(sFirstdirectionforcutisvertical, "Arah pertama untuk memotong adalah vertikal.");
	strcpy(sFollowthecontourofpieces, "Ikuti kontur potongan");
	strcpy(sFont, "Font");
	strcpy(sFontsize, "Ukuran huruf");
	strcpy(sFullInfo, "Informasi lengkap");
	strcpy(sDisposedWaste, "Limbah yang dibuang");
	strcpy(sGeneral, "Umum");
	strcpy(sGenerateCNC, "Hasilkan CNC");
	strcpy(sGrain, "Tekstur");
	strcpy(sGraindirection, "Arah serat");
	strcpy(sGraphic, "Grafis");
	strcpy(sGreaterorequalto, "Lebih besar atau sama dengan");
	strcpy(sGrid, "Tabel");
	strcpy(sGrinding, "Penggilingan");
	strcpy(sGrosimeTaieturaScalata, "Ketebalan potongan dari gambar ini mungkin berbeda dari yang asli karena potongan tidak terwakili pada skala sebenarnya. Fakta ini tidak mempengaruhi hasil.");
	strcpy(sGroupidenticallayouts, "Kelompokkan lembaran identik");
	strcpy(sGroupIdenticalParts, "Kelompokkan bagian yang identik");
	strcpy(sGroupingOfIdenticalPiecesIntoOneRow, "Kelompokkan bagian-bagian yang identik menjadi satu baris.");
	strcpy(sGroupPartsAfterLoadingFromFile, "Kelompokkan bagian saat memuat dari file");
	strcpy(sHeight, "Tinggi");
	strcpy(sHeighttolerance, "Toleransi untuk tinggi badan");
	strcpy(sHelp, "Tolong");
	strcpy(sHistory, "Sejarah");
	strcpy(sHorizontal, "Horisontal");
	strcpy(sHowtodisplayprintedgebands, "Bagaimana pita tepi ditampilkan?");
	strcpy(sIfyousetthebandforoneedgeallwillreceivethesamevalue, "Jika Anda mengatur band untuk satu tepi, semua tepi akan menerima nilai yang sama.");
	strcpy(sIfyousetthegrindingforoneedgeallwillreceivethesamevalue, "Jika Anda mengatur nilai penggilingan untuk satu tepi, semua tepi akan menerima nilai yang sama.");
	strcpy(sIfyousetthetrimforoneedgeallwillreceivethesamevalue, "Jika Anda mengatur pemangkasan untuk satu tepi, semua tepi akan menerima nilai yang sama.");
	strcpy(sImageBounds, "Batas untuk gambar");
	strcpy(sImageSize, "Ukuran gambar");
	strcpy(sImportData, "Impor data");
	strcpy(sIncorrectPassword, "kata kunci Salah");
	strcpy(sIndex, "Indeks");
	strcpy(sInformationaboutcustomer, "Informasi tentang pelanggan");
	strcpy(sInputALanguageName, "Masukkan nama bahasa");
	strcpy(sInsert, "Memasukkan");
	strcpy(sInsertPiece, "Masukkan bagian");
	strcpy(sInterface, "Antarmuka");
	strcpy(sInterfaceSettings, "Pengaturan antarmuka");
	strcpy(sInvalidHardware, "Saya tidak dapat mendeteksi perangkat kerasnya. Silakan hubungi kami di contact@optimalprograms.com");
	strcpy(sInvalidNumber, "Nomor tidak valid");
	strcpy(sInvalidOrderOfComputation, "Pesanan untuk menghitung panjang tidak dapat dibuat. Ada hubungan sirkuler dalam definisi produk!");
	strcpy(sInvalidRegistration, "Registrasi tidak valid!");
	strcpy(sInvalidTime, "Waktu sistem Anda tidak valid.");
	strcpy(sInventory, "PERSEDIAAN");
	strcpy(sisafractionalvalue, "adalah nilai fraksional.");
	strcpy(sIsArc, "Apakah busur");
	strcpy(sisarealvalue, "adalah nilai nyata.");
	strcpy(sLabel, "Label");
	strcpy(sLabels, "Label");
	strcpy(sLanguage, "Bahasa");
	strcpy(sLatimeanumar0, "Lebar harus lebih besar dari 0!");
	strcpy(sLatimeanumarreal, "Lebar harus berupa bilangan real!");
	strcpy(sLayerName, "Nama layer");
	strcpy(sLeft, "Kiri");
	strcpy(sLeftcoordinateofthedefect, "Koordinat kiri cacat");
	strcpy(sLength, "Panjangnya");
	strcpy(sLengthofthepiecestocut, "Ukuran potong untuk memotong");
	strcpy(sLengthofthepiecestocutfrom, "Ukuran lembar untuk memotong");
	strcpy(sLengthofusedbars, "Ukuran batang yang digunakan");
	strcpy(sLicenseAgreement, "Perjanjian lisensi");
	strcpy(sLinear, "Linier");
	strcpy(sLinethickness, "Ketebalan pena");
	strcpy(sLoadafileandappenddatatothecurrentDemand, "Muat file dan tambahkan data ke bagian saat ini.");
	strcpy(sLoadanexistingDemandfromafile, "Muat bagian yang ada dari file.");
	strcpy(sLoadAppend, "Muat dan tambahkan");
	strcpy(sLoadEverything, "Muat semuanya");
	strcpy(sLoadInventory, "Masukkan stok");
	strcpy(sLoadInventoryandDemand, "Masukkan stok dan bagian-bagiannya");
	strcpy(sLoadResults, "Muat hasilnya");
	strcpy(sLocked, "Terkunci");
	strcpy(sLogo, "Logo");
	strcpy(sLong, "Panjang");
	strcpy(sLongerexecutiontime, "Waktu berlari lebih lama");
	strcpy(sLungime, "Panjangnya");
	strcpy(sLungimeanumar0, "Panjangnya harus lebih dari 0!");
	strcpy(sLungimeanumarreal, "Panjangnya harus berupa bilangan real!");
	strcpy(sLungimeaTotalaFolosita, "Total panjang yang digunakan");
	strcpy(sMagnification, "Pembesaran");
	strcpy(sMagnify, "Memperbesar");
	strcpy(sMargins, "Batas");
	strcpy(sMarginsForPaper, "Margin untuk kertas");
	strcpy(sMarginsOfTheLabel, "Margin label");
	strcpy(sMaterial, "Bahan");
	strcpy(sMaterialName, "Nama bahannya");
	strcpy(sMaterials, "Material");
	strcpy(sMaterialstypes, "Jenis bahan");
	strcpy(sMax, "Maks");
	strcpy(sMaximalArea, "Area maksimal");
	strcpy(sMaximalCutLength, "Panjang potong maksimal");
	strcpy(sMaxlength, "Panjang maksimal");
	strcpy(sMaxPiecesperBar, "Jumlah maksimum potongan per batang");
	strcpy(sMaxwidth, "Lebar maks");
	strcpy(sMeasurementUnit, "Unit pengukuran");
	strcpy(sMin, "Min");
	strcpy(sMinimalBreakSize, "Ukuran istirahat minimal");
	strcpy(sMinimalUsefulSize, "Ukuran bermanfaat minimal");
	strcpy(sMinimalwastesizetoInventory, "Ukuran memo minimum ditambahkan ke stok.");
	strcpy(s_What_to_minimize, "Apa yang harus diminimalkan?");
	strcpy(sMinlength, "Panjang minimal");
	strcpy(sMinwidth, "Lebar minimal");
	strcpy(sMirror, "Cermin");
	strcpy(sMirroring, "Mirroring");
	strcpy(sMiscellaneous, "Statistik lainnya");
	strcpy(sModify, "Memodifikasi");
	strcpy(sModifytheselectedpiece, "Ubah karya yang dipilih");
	strcpy(sMovePiece, "Pindahkan bagian");
	strcpy(sMultiplestages, "Beberapa tahap");
	strcpy(sName, "Nama");
	strcpy(sNameofedgeband, "Nama band tepi");
	strcpy(sNewDEMANDUnsaveddatawillbelost, "Bagian baru? Data yang tidak disimpan akan hilang!");
	strcpy(sNewLanguage, "Bahasa baru");
	strcpy(sNewMaterial, "Materi Baru");
	strcpy(sNewPasswordincorectlyintroduced, "Kata sandi baru salah diperkenalkan!");
	strcpy(sNewProduct, "Produk baru");
	strcpy(sNewversion, "Versi baru");
	strcpy(sNo, "Tidak");
	strcpy(sNumarBucati, "Jumlah potongan");
	strcpy(sNumberOfCopies, "Jumlah salinan");
	strcpy(sNumberofstages, "Jumlah tahapan");
	strcpy(sNusuficienteplacidepozit, "Tidak semua bagian telah dioptimalkan. Kemungkinan penyebabnya: Stok tidak cukup; Potongan tidak diaktifkan; Bahan potongan dan Stok berbeda; Parameter lain salah diatur.");
	strcpy(sOfficeNotInstaled, "Microsoft Office tidak diinstal ke komputer Anda atau versi yang salah diinstal!");
	strcpy(sOldpassworddoesnotmatch, "Kata sandi lama tidak cocok!");
	strcpy(sOnlinehelp, "Bantuan online");
	strcpy(sOnlypiecesofthesameheightinthelaststage, "Potongan-potongan dengan ketinggian yang sama di tahap terakhir");
	strcpy(sOpen, "Buka");
	strcpy(sOptimization, "Optimasi");
	strcpy(sOptimizationDone, "Optimasi dilakukan! Anda dapat mencetak atau menyimpan diagram yang diperoleh. Tekan tombol Terima jika Anda puas dengan solusi saat ini. Kalau tidak, tekan Mulai lagi.");
	strcpy(sOptimizationType, "Jenis optimasi");
	strcpy(sOptions, "Pilihan");
	strcpy(sOptionsrelatedtotheinterface, "Opsi terkait dengan antarmuka");
	strcpy(sor, "atau");
	strcpy(sOthercomponents, "Komponen lainnya");
	strcpy(sOthers, "Lainnya");
	strcpy(sOtherstatistics, "Statistik lainnya");
	strcpy(sOverrideExcelCSVfiles, "Ganti file Excel / CSV");
	strcpy(sParameter, "Parameter");
	strcpy(sParts, "Potongan");
	strcpy(sPattern, "Pola");
	strcpy(sPatternforwaste, "Pola untuk memo");
	strcpy(sPerimeter, "Perimeter");
	strcpy(sPermitedRotationAngle, "Sudut rotasi yang diizinkan");
	strcpy(sPhone, "Telepon");
	strcpy(sPicture, "Gambar");
	strcpy(sPiece, "Bagian");
	strcpy(sPieceindex, "Indeks bagian");
	strcpy(sPieces, "Potongan");
	strcpy(sPiecesize, "Ukuran potongan");
	strcpy(sPiecesizelabeledgebandwillbeprinted, "Ukuran potongan, label, pita tepi akan dicetak.");
	strcpy(sPierdere, "Membatalkan");
	strcpy(sPixels, "piksel");
	strcpy(sPlacilefolositeDepozit, "Potongan-potongan yang digunakan dari Stock.");
	strcpy(sPlease_contact_us_at_contact_nestingtechnologies_com, "Silakan hubungi kami di contact@nesting-technologies.com");
	strcpy(sPlease_contact_us_at_contact_optimalprograms_com, "Silakan hubungi kami di contact@optimalprograms.com");
	strcpy(sPleaseenteralldataeitherasfractionalorrealDonotmixthem, "Silakan masukkan semua data baik sebagai nilai fraksional atau nilai nyata! Jangan campur mereka!");
	strcpy(sPleaseEnterSomeTypesOfMaterials, "Tidak ada jenis bahan yang didefinisikan. Anda dapat menentukannya dari menu Material.");
	strcpy(sPleasesendtheNameandtheCodetotheaddresscontactoptimalprogramscominordertoobtaintheRegistrationKey, "Untuk mendapatkan Kunci Pendaftaran, silakan kirim Nama dan Kode ke: contact@optimalprograms.com.");
	strcpy(sPolygon, "Poligon");
	strcpy(sPolygonsCircles, "Poligon, lingkaran");
	strcpy(sPrecision, "Presisi");
	strcpy(sPretulnumar0, "Harganya harus lebih dari 0!");
	strcpy(sPretulnumarreal, "Harga harus berupa bilangan real!");
	strcpy(sPreview, "Pratinjau");
	strcpy(sPrice, "Harga");
	strcpy(sPriceMustBeGreaterThanZero, "Harga harus lebih besar dari nol");
	strcpy(sPriceofbars, "Harga bar");
	strcpy(sPriceperbar, "Harga per bar");
	strcpy(sPricepersheet, "Harga per lembar");
	strcpy(sPricepersquareunitofmaterial, "Harga per unit persegi bahan");
	strcpy(sPriceperunit, "Harga per unit");
	strcpy(sPrint, "Mencetak");
	strcpy(sPrintdiagramsastables, "Cetak diagram sebagai tabel.");
	strcpy(sPrinter, "Pencetak");
	strcpy(sPrinterBounds, "Margin untuk printer");
	strcpy(sPrinting, "Pencetakan");
	strcpy(sPrintonlyutilizedarea, "Cetak hanya area yang digunakan");
	strcpy(sPrintthecontentsoftheDemand, "Cetak isi bagian.");
	strcpy(sPrintthecontentsoftheInventory, "Cetak isi stok.");
	strcpy(sPrintthecurrentsolution, "Cetak solusi saat ini.");
	strcpy(sPriority, "Prioritas");
	strcpy(sPrioritytocutapieceZero0isthehighestpriority, "Prioritas untuk memotong sepotong. Nol (0) adalah prioritas tertinggi.");
	strcpy(sProcentul0100, "Persen harus lebih besar dari 0 dan kurang dari atau sama dengan 100!");
	strcpy(sProcentulnumarreal, "Persennya harus bilangan real!");
	strcpy(sProductdefinition, "Definisi produk");
	strcpy(sProductExists, "Produk sudah ada. Pilih nama lain.");
	strcpy(sProductName, "Nama Produk");
	strcpy(sProducts, "Produk");
	strcpy(sProducts, "Produk");
	strcpy(sProject, "Proyek");
	strcpy(sProperties, "Properti");
	strcpy(sProperty, "Properti");
	strcpy(sQuantity, "Kuantitas");
	strcpy(sQuantitynumberofsheetsofthistype, "Jumlah lembar jenis ini");
	strcpy(sRadius, "Radius");
	strcpy(sRectangular, "Persegi panjang");
	strcpy(sRedefinetypesofedgeband, "Tentukan kembali jenis band tepi");
	strcpy(sRedefinetypesofmaterial, "Tentukan kembali jenis bahan");
	strcpy(sRegistration, "Registrasi");
	strcpy(sRegistrationKeyfromOptimalPrograms, "Kunci registrasi");
	strcpy(sRegistrationSuccessful, "Pendaftaran berhasil!");
	strcpy(sRemoveallpiecesinInventory, "Hapus semua bagian dalam Inventaris.");
	strcpy(sRemoveCut, "Hapus cut");
	strcpy(sRemovetheselectedpiece, "Hapus karya yang dipilih");
	strcpy(sReports, "Laporan");
	strcpy(sRequestedMaterial, "Materi yang diminta");
	strcpy(sRestore, "Mengembalikan");
	strcpy(sResults, "Hasil");
	strcpy(sReusedwaste, "Limbah yang digunakan kembali");
	strcpy(sRight, "Kanan");
	strcpy(sRightcoordinateofthedefect, "Koordinat cacat dari sisi kanan");
	strcpy(sRotation, "Rotasi");
	strcpy(sRotationAngle, "Sudut rotasi");
	strcpy(sRotationStep, "Langkah rotasi");
	strcpy(sRoundAllFractionsTo, "Nilai fraksional harus dibulatkan menjadi");
	strcpy(sRow, "baris");
	strcpy(sRows, "Baris");
	strcpy(sRun, "Solusi terbaru");
	strcpy(sRunningtime, "Durasi");
	strcpy(sSameforall, "Sama untuk semua");
	strcpy(sSave, "Menyimpan");
	strcpy(sSaveAllImages, "Simpan semua gambar");
	strcpy(sSaveAs, "Simpan sebagai");
	strcpy(sSaveChanges, "Bagian-bagian telah diubah. Apakah Anda ingin menyimpannya?");
	strcpy(sSaveCurrentImage, "Simpan gambar saat ini");
	strcpy(sSavedataparameters, "Simpan data dan parameter");
	strcpy(sSaveEverything, "Simpan semuanya");
	strcpy(sSaveInventory, "Simpan Inventaris");
	strcpy(sSaveInventoryandDemand, "Simpan stok dan bagiannya");
	strcpy(sSaveResults, "Simpan hasil");
	strcpy(sSaveStatisticsinafile, "Simpan statistik dalam file");
	strcpy(sSavethecurrentimage, "Simpan gambar saat ini");
	strcpy(sSavethecurrentimageorstatistic, "Simpan gambar saat ini atau statistik");
	strcpy(sSavetheDEMANDinafile, "Simpan ke file");
	strcpy(sSavetheDemandinafilewithadifferentname, "Simpan Bagian dalam file dengan nama yang berbeda.");
	strcpy(sSavetheREPOSITORYinafile, "Simpan Stok dalam file");
	strcpy(sSerialNumber, "Kunci registrasi");
	strcpy(sService, "Layanan");
	strcpy(sSetDefaultValues, "Ini akan mengembalikan semua parameter ke nilai standarnya. Semua pengaturan Anda akan hilang. Anda yakin ingin melakukan ini?");
	strcpy(sSetedgeband, "Atur band tepi");
	strcpy(sSetedgetrim, "Atur ukuran potongan untuk cacat margin");
	strcpy(sSetthesameedgebandforalledges, "Atur band tepi yang sama untuk semua sisi");
	strcpy(sSetthesamegrindingforalledges, "Atur gerinda yang sama untuk semua sisi");
	strcpy(sSetthesametrimforalledges, "Atur pemotongan yang sama untuk cacat untuk semua tepi");
	strcpy(sSettings, "Pengaturan");
	strcpy(sShape, "Bentuk");
	strcpy(sSheet, "Lembar");
	strcpy(sSheetsBarstypes, "Jenis lembar_batang");
	strcpy(sSheetSize, "Ukuran lembar");
	strcpy(sSheetsperPage, "Lembar per halaman");
	strcpy(sShort, "Pendek");
	strcpy(sShorterexecutiontime, "Waktu berjalan yang singkat");
	strcpy(sShowallsimpleproducts, "Tampilkan semua produk sederhana");
	strcpy(sShowcustomername, "Tampilkan nama pelanggan");
	strcpy(sShowCustomTextOnEachPiece, "Tampilkan teks khusus pada setiap bagian");
	strcpy(sShowdiagramasatable, "Tampilkan diagram sebagai tabel.");
	strcpy(sShowedgeband, "Tampilkan band tepi");
	strcpy(sShowedgebandssettinginanewwindow, "Tampilkan pengaturan band tepi di jendela baru");
	strcpy(sShowgrindingsettingsinanewwindow, "Menampilkan pengaturan penggilingan di jendela baru");
	strcpy(sShowHorizontalLabelsAlways, "Tampilkan label horizontal selalu");
	strcpy(sShowRemovethesizeofthepiecesinthecurrentsolution, "Tampilkan / sembunyikan ukuran potongan.");
	strcpy(sShowRemovethesizeofthewastesinthecurrentsolution, "Tampilkan / sembunyikan ukuran memo.");
	strcpy(sShowtotalcutlength, "Tampilkan total panjang pemotongan");
	strcpy(sShowtrimedgesettingsinanewwindow, "Tampilkan pengaturan cacat di jendela baru");
	strcpy(sSimpleMaterialExists, "Nama bahan sudah didefinisikan dalam daftar bahan. Tolong beri nama baru.");
	strcpy(sSinglePieceStrips, "Garis-garis utuh");
	strcpy(sSizes, "Ukuran");
	strcpy(sSmallerorequalto, "Lebih kecil atau sama dengan");
	strcpy(sSort, "Menyortir");
	strcpy(sSortAscendingByArea, "Urutkan berdasarkan area dalam urutan menaik");
	strcpy(sSortDescendingByArea, "Urutkan berdasarkan area dalam urutan menurun");
	strcpy(sSpecifyhowdifferentthepiecesinthelaststagecanbeValue0meansnodifference, "Tentukan seberapa berbedanya potongan pada tahap terakhir. Nilai 0 berarti tidak ada perbedaan.");
	strcpy(sSpecifyifpiecesinthelaststagecanbedifferentornotdepeultimaetapapotfidiferitesaunucadimensiune, "Tentukan apakah potongan pada tahap terakhir bisa berbeda atau tidak");
	strcpy(sSpecifyifthepiececanberotatedornotIfnotitwillbecutinthesamewayasitwasintroducedinDemandLengthofthepieceparalleltothelengthofthesheet, "Tentukan apakah potongan dapat diputar atau tidak. Jika tidak, itu ditempatkan dengan cara yang sama seperti yang diperkenalkan (panjang potongan sejajar dengan panjang lembaran), ");
	strcpy(sSpecifyinhowmanystageswemakethecutsDuringastageallcutshavethesamedirection, "Tentukan dalam berapa banyak tahap kami melakukan pemotongan.");
	strcpy(sStartthesearchprocess, "Mulai proses pencarian");
	strcpy(sStatistics, "Statistik");
	strcpy(sStatisticsE, "Laporan Ekstra");
	strcpy(sStatisticsforeachtypeofmaterial, "Statistik untuk setiap jenis bahan");
	strcpy(sStep, "Langkah");
	strcpy(sStergeDepozit, "Apakah Anda ingin menghapus Inventaris?");
	strcpy(sStergeMaterial, "Apakah Anda ingin menghapus materi?");
	strcpy(sStergePiesele, "Apakah Anda ingin menghapus bagian itu?");
	strcpy(sStergePiesa, "Apakah Anda ingin menghapus bagian itu?");
	strcpy(sStopthesearchprocess, "Hentikan proses pencarian");
	strcpy(sStrongoptimization, "Optimasi yang kuat");
	strcpy(sSubtractthebandthicknessfrompiecesize, "Kurangi ukuran potongan dengan ketebalan pita tepi");
	strcpy(sSummary, "Ringkasan");
	strcpy(sSuprafataTotalaFolosita, "Total permukaan yang digunakan");
	strcpy(sSuprafatautilizata, "Pemanfaatan");
	strcpy(sSwitchbetweenfiberandrotationoption, "Beralih di antara opsi serat dan rotasi.");
	strcpy(sTechnical, "Teknis");
	strcpy(sTechnicalsettings, "Pengaturan teknis");
	strcpy(sTemporaryPanelHint, "Panel sementara untuk memindahkan bagian di antara lembaran.");
	strcpy(sText, "Teks");
	strcpy(sThe_application_has_expired, "Aplikasi telah kedaluwarsa.");
	strcpy(sThe_application_is_not_registered, "Aplikasi tidak terdaftar.");
	strcpy(sThe_application_was_first_started_on, "Aplikasi pertama kali dimulai");
	strcpy(sThecutsareperformedfromasidetotheothersideofthematerial, "Potongan dibuat dari satu sisi ke sisi lain dari bahan.");
	strcpy(sThecuttingmachinecanfollowtheshapeofthematerial, "Mesin pemotong dapat mengikuti bentuk potongan.");
	strcpy(sTheedgesofsheetsthatmustbetrimedduefaults, "Tepi lembaran yang harus dipangkas karena kesalahan");
	strcpy(sTheLargestSize, "Ukuran terbesar");
	strcpy(sThenameofthecustomerforwhichyoucutthepiece, "Nama pelanggan yang Anda potong.");
	strcpy(sThenameofyourcustomer, "Nama pelanggan Anda");
	strcpy(sThepiececanberotated, "Sepotong bisa diputar");
	strcpy(sTheprogramtriestoavoidwasteswhichhavebothsizeslessthanthisvalue, "Program mencoba menghindari memo yang lebih kecil dari nilai ini");
	strcpy(sThereAreNoProducts, "Belum ada produk yang ditentukan");
	strcpy(sThestockofmaterialhasbeenpreviouslyloadedfromanExcelorCSVformatPleaseloaditagain, "Stok materi sebelumnya telah dimuat dari format Excel atau CSV. Harap muat lagi jika Anda ingin mengerjakannya.");
	strcpy(sThetotallengthofcutting, "Total panjang pemotongan");
	strcpy(sThewidthofthecuttingsawForglasscuttingoptimizationitcanbe0Forwooditshouldbegreaterthan0, "Ketebalan gergaji. Untuk memotong kaca itu bisa 0. Untuk kayu itu harus lebih besar dari 0.");
	strcpy(sThewidthofthecuttingsawforlinearpieces, "Ketebalan gergaji untuk potongan linear.");
	strcpy(sThickness, "Ketebalan");
	strcpy(sThischaracterisusedforfillingthewasterectanglesIfyoudonotwantfilledwastejustremovethischaracter, "Simbol ini digunakan untuk mengisi persegi panjang limbah. Jika Anda tidak ingin sampah terisi, buang saja.");
	strcpy(sThisindexhasvaluebetween1andthenumberofpieces, "Indeks ini memiliki nilai antara 1 dan jumlah karya.");
	strcpy(sThisOptionWillOverrideTheInventoryFileIfLoadedFromExcelOrCsvFiles, "Opsi ini akan menimpa file inventaris jika diambil dari file excel atau csv.");
	strcpy(sThisProgramisLicensedTo, "Program ini dilisensikan kepada");
	strcpy(sThisvaluewillbeaddedtotheedgebandingmaterialoneachside, "Nilai ini akan ditambahkan ke pita tepi di setiap sisi");
	strcpy(sTipNevid, "Jenis bahan tidak boleh kosong.");
	strcpy(sTitle, "Judul");
	strcpy(sTools, "Alat");
	strcpy(sTop, "Puncak");
	strcpy(sTopcoordinateofthedefect, "Koordinat atas cacat.");
	strcpy(sTotalGarbageWaste, "Semua memo yang dibuang");
	strcpy(sTotalInventoryWaste, "Memo stok total.");
	strcpy(sTotalRecycledWaste, "Semua memo bekas");
	strcpy(sTotalusedarea, "Total area yang digunakan");
	strcpy(sTotalusedlength, "Total panjang yang digunakan");
	strcpy(sTrigonometric, "Trigonometri");
	strcpy(sTrim, "Memangkas");
	strcpy(sTrimalledgesatthebeginning, "Potong semua ujungnya di awal");
	strcpy(sTrimEdge, "Potong ujungnya");
	strcpy(sTwoPanels, "2 panel");
	strcpy(sType, "Tipe");
	strcpy(sTypeofmaterialfromwhichtocut, "Jenis bahan yang akan dipotong");
	strcpy(sTypesAreNotMatched, "Optimalisasi tidak dilakukan! Saat ini, tidak ada bahan seperti itu dalam stok! Potongan dapat dipotong dari lembaran dari bahan yang sama. Ubah beberapa materi dari kolom yang sesuai!");
	strcpy(sUndo, "Membuka");
	strcpy(sUndoAccept, "Batalkan Terima");
	strcpy(sUnits, "unit");
	strcpy(sUnregisteredVersion, "Tidak terdaftar");
	strcpy(sUpdates, "Pembaruan");
	strcpy(sUsefulforwoodfurniture, "Berguna untuk furnitur kayu");
	strcpy(sUseit, "Gunakan");
	strcpy(sUsePieceinOptimization, "Gunakan bagian dalam optimasi");
	strcpy(sUserName, "Nama pengguna");
	strcpy(sUtilizationandWastes, "Pemanfaatan dan memo");
	strcpy(sUtilizedArea, "Area bagian yang digunakan");
	strcpy(sUtilizedBars, "Bar yang digunakan");
	strcpy(sUtilizeddemandcount, "Jumlah bagian yang digunakan");
	strcpy(sUtilizedParts, "Bagian yang digunakan");
	strcpy(sUtilizedPieces, "Potongan yang digunakan");
	strcpy(sUtilizedSheets, "Lembar yang digunakan");
	strcpy(sValue, "Nilai");
	strcpy(sValueGreaterEqualToZero, "Nilai harus lebih besar atau sama dengan nol");
	strcpy(sValueGreaterThanZero, "Nilai harus lebih besar dari nol");
	strcpy(sValueIntegerNumber, "Nilainya harus bilangan bulat!");
	strcpy(sValueRealNumber, "Nilai harus berupa bilangan real. Mungkin Anda menggunakan koma sebagai ganti titik atau sebaliknya. Tolong perbaiki!");
	strcpy(s_The_number_is_too_big_or_it_has_too_many_digits_after_decimal_separator, "Jumlahnya terlalu besar atau memiliki terlalu banyak digit setelah pemisah desimal!");
	strcpy(s_The_number_is_too_big, "Jumlahnya terlalu besar!");
	strcpy(sVertical, "Vertikal");
	strcpy(sWaste, "Membatalkan");
	strcpy(sWastes, "Membatalkan");
	strcpy(sWasteAddedToWarehouse, "Memo ditambahkan ke stok");
	strcpy(sWastelimits, "Rentang untuk memo");
	strcpy(sWasteType, "Jenis memo");
	strcpy(sWeakoptimization, "Optimalisasi terlemah");
	strcpy(sWhattoprint, "Apa yang harus saya cetak");
	strcpy(s_What_to_print_or_save_to_file, "Apa yang akan dicetak atau disimpan ke file");
	strcpy(sWhattoprintoneachpiece, "Apa yang harus dicetak pada setiap bagian");
	strcpy(sWhattoshowoneachpiece, "Apa yang harus ditampilkan pada setiap bagian?");
	strcpy(sWidth, "Lebar");
	strcpy(sWood, "kayu");
	strcpy(sWorkingDirectory, "Folder kerja");
	strcpy(sWrongKey, "Kunci pendaftaran salah!");
	strcpy(sYes, "Iya");
	strcpy(sYoucannotchooseblackblueorredcolors, "Anda tidak dapat memilih warna hitam, biru atau merah.");
	strcpy(sYouCannotMixFractionalDataWithDecimalOnes, "Anda tidak dapat mencampur nilai fraksional dengan nilai nyata!");
	strcpy(sYourcompany, "Perusahaan Anda");
	strcpy(sZip, "Kode Pos");
	strcpy(s_Set_the_origin_and_the_direction_of_the_axes, "Tetapkan asal dan arah sumbu koordinat.");

}
