// Language strings: Hindi
// Author: Optimal Programs
// License: MIT License
//---------------------------------------------------------------------------
#include <string.h>
//---------------------------------------------------------------------------
#include "language_string_id.h"
//---------------------------------------------------------------------------
void set_hindi(void)
{
	//Hindi
	//automatic translation
	//2025.3.29.0
	strcpy(s_Advanced, "विकसित");
	strcpy(s_Relative_coordinates, "सापेक्ष निर्देशांक");
	strcpy(s_Absolute_coordinates, "निरपेक्ष निर्देशांक");
	strcpy(s_Append_more_rows, "अधिक पंक्तियाँ जोड़ें");

	strcpy(s_Add_to_parts, "भागों में जोड़ें।");
	strcpy(s_Additional, "अतिरिक्त");
	strcpy(s_All_results, "सभी परिणाम।");
	strcpy(s_Allow_movement_of_pieces, "टुकड़ों की आवाजाही की अनुमति दें");
	strcpy(s_Allow_part_in_part, "टुकड़े टुकड़े की अनुमति दें");
	strcpy(s_Invalid_piece_Angles_are_too_small_or_too_big_or_height_is_too_small, "अमान्य टुकड़ा! कोण बहुत छोटे या बहुत बड़े हैं, या ऊंचाई बहुत छोटी है।");
	strcpy(s_Append, "संलग्न");
	strcpy(s_As_it_is, "ज्यों का त्यों");
	strcpy(s_As_text, "पाठ के रूप में");
	strcpy(s_Ascending, "आरोही");
	strcpy(s_Automatic, "स्वचालित");
	strcpy(s_Cannot_connect_to_the_Internet_Please_visit_our_website_from_a_browser, "इंटरनेट से कनेक्ट नहीं हो सकता है! कृपया एक ब्राउज़र से हमारी वेबसाइट पर जाएँ।");
	strcpy(s_Cannot_copy_or_move_the_files, "फ़ाइलों को कॉपी या स्थानांतरित नहीं किया जा सकता है!");
	strcpy(s_Cannot_delete_the_file, "फ़ाइल को हटा नहीं सकता!");
	strcpy(s_Cannot_modify_old_results, "पुराने परिणाम संशोधित नहीं किये जा सकते!");
	strcpy(s_To_change_click_inside_a_cell_or_press_0_1_or_2, "बदलने के लिए, सेल के अंदर क्लिक करें या 0, 1, या 2 दबाएं।");
	strcpy(s_Cell, "कक्ष");
	strcpy(s_Click_on_the_table_header_to_change_the_columns, "कॉलम बदलने के लिए टेबल हेडर पर क्लिक करें।");
	strcpy(s_Close, "बंद करे");
	strcpy(s_Contact_us, "संपर्क करें");
	strcpy(s_Column, "स्तंभ");
	strcpy(s_Comma, "अल्पविराम");

	strcpy(s_Copy, "प्रतिलिपि");
	strcpy(s_Copy_for_move, "चाल के लिए कॉपी करें");
	strcpy(s_Cut_higher_level_strips_first, "पहले उच्च-स्तर की पट्टियाँ काटें");
	strcpy(s_Cut_index, "कट सूचकांक");

	strcpy(s_The_data_have_been_changed_Do_you_want_to_save_them_to_a_file, "डेटा बदल दिया गया है। क्या आप उन्हें फ़ाइल में सहेजना चाहते हैं?");
	strcpy(s_Decimal_separator, "दशमलव विभाजक");
	strcpy(s_Restore_default_settings, "डिफाल्ट सेटिंग रिस्टोर करो");
	strcpy(s_Delete_fiber, "फाइबर हटाएं");
	strcpy(s_Descending, "अवरोही");
	strcpy(s_Discard_changes, "परिवर्तनों को निरस्त करें");

	strcpy(s_Delete_all_data, "सभी डेटा हटाएँ?");
	strcpy(s_Dot, "डॉट");
	strcpy(s_Do_you_want_to_delete_the_picture, "क्या आप चित्र हटाना चाहते हैं?");
	strcpy(s_Do_you_want_to_delete_the_product, "क्या आप उत्पाद हटाना चाहते हैं?");
	strcpy(s_Duplicate_and_append, "डुप्लिकेट और परिशिष्ट।");
	strcpy(s_Duplicate_values_are_ignored, "डुप्लिकेट मानों पर ध्यान नहीं दिया गया!");
	strcpy(s_Error, "त्रुटि");
	strcpy(s_Error_loading_file, "फ़ाइल लोड करने में त्रुटि हुई।");
	strcpy(s_export_everything, "सब कुछ निर्यात करें");
	strcpy(s_Fit_to_screen, "स्क्रीन में फिट।");
	strcpy(s_Force_fixed_height, "टुकड़ों को एक निश्चित ऊंचाई पर बनाएं।");
	strcpy(s_Flipped, "रूप से फ़्लिप");
	strcpy(s_Import, "आयात");
	strcpy(s_If_angles_are_different_from_90_degrees_height_must_be_greater_than_0, "");
	strcpy(s_Ignore, "नज़रअंदाज़ करना");
	strcpy(s_Incorrect_value, "गलत मान");
	strcpy(s_Info, "जानकारी");
	strcpy(s_Interior, "आंतरिक");
	strcpy(s_Give_a_name, "नाम देना।");
	strcpy(s_Group, "इसे ग्रुप करें");
	strcpy(s_Header, "हैडर");
	strcpy(s_Keep_it_as_it_is, "जैसा है वैसा ही रखो");
	strcpy(s_Level, "Level");
	strcpy(s_Licensee, "लाइसेंसधारी");
	strcpy(s_List_separator, "सूची विभाजक");
	strcpy(s_Made_with_love_in_Cugir_Romania, "प्यार से बनाया गया: कुगिर, रोमानिया");
	strcpy(s_Made_in, "में निर्मित");
	strcpy(s_Manufacturer, "उत्पादक");

	strcpy(s_Manual_arrange, "मैनुअल व्यवस्था");

	strcpy(s_Mixed, "मिश्रित");
	strcpy(s_Multiple_shapes_detected_Next_rows_will_be_overwritten_Continue, "एक से अधिक आकृतियों का पता चला था। इसलिए, बाद की पंक्तियों को अधिलेखित कर दिया जाएगा। जारी रखें?");
	strcpy(s_More, "अधिक");
	strcpy(s_Multiple_values, "एकाधिक मान");
	strcpy(s_No_texture, "कोई बनावट नहीं");
	strcpy(s_Number, "नंबर");
	strcpy(s_Number_of_images, "छवियों की संख्या");
	strcpy(s_Number_of_vertices, "संख्या की संख्या");
	strcpy(s_Offset, "ओफ़्सेट");
	strcpy(s_Only_the_currently_selected_items, "केवल वर्तमान में चयनित आइटम।");
	strcpy(s_Optimizing_please_wait, "अनुकूलन ... कृपया प्रतीक्षा करें।");

	strcpy(s_Paste, "Paste");

	strcpy(s_Piece_label, "टुकड़ा का लेबल");
	strcpy(s_Piece_size, "टुकड़े का आकार");
	strcpy(s_Please_contact_us_by_email_if_you_receive_this_error, "यदि आपको यह त्रुटि मिलती है तो कृपया हमें ईमेल से संपर्क करें।");
	strcpy(s_Please_save_it_first, "कृपया, इसे पहले सहेजें।");
	strcpy(s_Position, "पद");
	strcpy(s_Preview, "पूर्वावलोकन");
	strcpy(s_Rectangle, "आयत");

	strcpy(s_Redo_the_last_operation, "पिछले ऑपरेशन को फिर से करें");
	strcpy(s_Regular_polygon, "नियमित बहुभुज");

	strcpy(s_Reused, "पुन: उपयोग");
	strcpy(s_Rotated, "घुमाया गया");
	strcpy(s_Save_all, "सभी को सुरक्षित करें");
	strcpy(s_Scrap_label, "स्क्रैप का लेबल");
	strcpy(s_Scrap_size, "स्क्रैप का आकार");
	strcpy(s_Semicolon, "सेमीकोलन");
	strcpy(s_Show_cut_index, "कट का सूचकांक दिखाएं");
	strcpy(s_Show_information, "जानकारी दिखाएँ");
	strcpy(s_Show_piece_label, "टुकड़े का लेबल दिखाएं");
	strcpy(s_Show_scrap_label, "स्क्रैप का लेबल दिखाएं");
	strcpy(s_Show_scrap_s_size_on_the_small_pieces, "छोटे टुकड़ों पर स्क्रैप का आकार दिखाएं");
	strcpy(s_Show_size_of_pieces, "टुकड़े का आकार दिखाएं");
	strcpy(s_Show_size_of_scrap, "स्क्रैप का आकार दिखाएं");
	strcpy(s_Show_sizes, "आकार दिखाएं");
	strcpy(s_Show_label, "लेबल दिखाएं");
	strcpy(s_Show_length, "लंबाई दिखाएं");

	strcpy(s_Some_numerical_values_are_incorrect_Should_I_fix_all_the_incorrect_values, "कुछ संख्यात्मक मान गलत हैं! क्या मुझे सभी गलत मूल्यों को ठीक करना चाहिए?");
	strcpy(s_Some_invalid_values_have_been_removed, "कुछ अमान्य मान हटा दिए गए हैं।");
	strcpy(s_Sort_by, "इसके अनुसार क्रमबद्ध करें");
	strcpy(s_Sort_ascending_by, "द्वारा आरोही क्रमबद्ध करें");
	strcpy(s_Sort_descending_by, "द्वारा अवरोही क्रमबद्ध करें");
	strcpy(s_Start, "Start");
	strcpy(s_Starting_angle, "कोण शुरू करना");


	strcpy(s_Stock, "भण्डार");
	strcpy(s_Stop, "Stop");

	strcpy(s_Tabular, "तालिका का");
	strcpy(s_Total, "संपूर्ण");
	strcpy(s_Total_size, "कुल आकार");
	strcpy(s_Terms_of_the_license, "लाइसेंस की शर्तें");
	strcpy(s_The_current_product_has_been_changed_Do_you_want_to_save_it_to_file, "वर्तमान उत्पाद को बदल दिया गया है। क्या आप इसे फ़ाइल करने के लिए सहेजना चाहते हैं?");
	strcpy(s_The_value_is_out_of_the_allowed_range, "मान अनुमत सीमा से बाहर है।");
	strcpy(s_The_value_must_be_a_real_or_fractional_number_Try_to_replace_the_comma_with_the_dot_if_you_want_to_enter_a_real_number, "मान एक वास्तविक या आंशिक संख्या होना चाहिए। यदि आप वास्तविक संख्या दर्ज करना चाहते हैं, तो अल्पविराम को डॉट से बदलने का प्रयास करें।");
	strcpy(s_This_feature_is_not_implemented_yet, "यह सुविधा अभी तक लागू नहीं हुई है।");
	strcpy(s_This_operation_cannot_be_reversed, "इस ऑपरेशन को उलटा नहीं किया जा सकता है।");
	strcpy(s_Undo_the_last_operation, "अंतिम ऑपरेशन को पूर्ववत करें");
	strcpy(s_Utilization, "उपयोग");
	strcpy(s_Utilized_Stock, "उपयोग किया गया स्टॉक");
	strcpy(s_Version, "संस्करण");
	strcpy(s_Visible_columns, "देखने योग्य स्तंभ");
	strcpy(s_You_already_have_the_latest_version_installed, "आपके पास पहले से ही नवीनतम संस्करण स्थापित है!");
	strcpy(s_What_is_exported, "क्या निर्यात किया जाता है?");
	strcpy(s0meansanynumberofpieces, "शून्य का अर्थ है किसी भी संख्या में टुकड़े");
	strcpy(sAbout, "के बारे में");
	strcpy(sAccept, "स्वीकार करना");
	strcpy(sAcceptall, "सभी स्वीकार करो");
	strcpy(sAcceptthecurrentsolution, "वर्तमान समाधान स्वीकार करें");
	strcpy(sAdd, "संलग्न");
	strcpy(sAddapiece, "एक टुकड़ा जोड़ें");
	strcpy(sAddasimpleproducttoDemand, "मौजूदा भागों में एक उत्पाद जोड़ें।");
	strcpy(sAddgrindingthicknesstopartsize, "पीस मोटाई को आकार में जोड़ें");
	strcpy(sAddproductnametolabel, "लेबल करने के लिए उत्पाद का नाम जोड़ें");
	strcpy(sAddress, "पता");
	strcpy(sAddselectedsizetoInventory, "स्टॉक के लिए चयनित आकार को जोड़ें");
	strcpy(sAdhesivelabels, "चिपकने वाला लेबल");
	strcpy(sAdhesivelabelwithinformationaboutpiecesinDemandCustomernameLabelSizeCurrentData, "टुकड़ों के बारे में जानकारी के साथ चिपकने वाला लेबल: ग्राहक का नाम, लेबल, आकार, वर्तमान डेटा आदि।");
	strcpy(sAdhesivelabelwithinformationaboutsheetsinInventory, "स्टॉक में शीट के बारे में जानकारी के साथ चिपकने वाला लेबल।");
	strcpy(sAll, "सब");
	strcpy(sAlloffcutswhichhavethesizegreaterthanthisvaluewillbeaddedtoInventory, "इस मूल्य से अधिक के सभी स्क्रैप स्टॉक में जोड़े जाएंगे");
	strcpy(sAllowMirroring, "फ़्लिपिंग की अनुमति दें");
	strcpy(sAllowRotation, "रोटेशन की अनुमति दें");
	strcpy(sAllPieces, "सभी टुकड़े");
	strcpy(sAllpredefinedproducts, "सभी पूर्वनिर्धारित उत्पाद");
	strcpy(sAnewwindowwillbedisplayedwheretheusercansettheedgebandsforeachedge, "एक नई विंडो प्रदर्शित की जाएगी जहां उपयोगकर्ता प्रत्येक पक्ष के लिए किनारे बैंड सेट कर सकता है।");
	strcpy(sAnewwindowwillbedisplayedwheretheusercansetthegrindingvalueforeachedgeofthsheet, "एक नई विंडो प्रदर्शित की जाएगी जहां उपयोगकर्ता टुकड़ा के प्रत्येक पक्ष के लिए पीस आकार निर्धारित कर सकता है।");
	strcpy(sAnewwindowwillbedisplayedwheretheusercansetthetrimvalueforeachedgeofthsheet, "एक नई विंडो प्रदर्शित की जाएगी जहां उपयोगकर्ता टुकड़ा के प्रत्येक पक्ष के लिए ट्रिम मूल्य निर्धारित कर सकता है।");
	strcpy(sAngle, "कोण");
	strcpy(sAngles, "कोण");
	strcpy(sAnoptimizationparameterisarealnumber, "एक अनुकूलन पैरामीटर एक वास्तविक संख्या है।");
	strcpy(sAnoptimizationparameterisfractionalnumber, "एक अनुकूलन पैरामीटर भिन्नात्मक संख्या है।");
	strcpy(sAnyShape, "सही आकार");
	strcpy(sApolygonmusthaveatleast2vertices, "एक बहुभुज में कम से कम 2 कोने होने चाहिए!");
	strcpy(sApolygonmusthaveatleast3vertices, "एक बहुभुज में कम से कम 3 कोने होने चाहिए!");
	strcpy(sApplication_fails_to_initialize, "एप्लिकेशन प्रारंभ करने में विफल रहा!");
	strcpy(sArc, "आर्क");
	strcpy(sArcLength, "चाप की लम्बाई");
	strcpy(sAreaofusedsheets, "उपयोग की गई चादरों का क्षेत्र");
	strcpy(sAshortdescriptionofthesheet, "चादर का संक्षिप्त विवरण");
	strcpy(sAtleastonepart, "आपको कम से कम एक टुकड़ा दर्ज करना होगा।");
	strcpy(sAtTheMarginOfTheSheet, "शीट के मार्जिन पर");
	strcpy(sBandtypes, "धार बैंड के प्रकार");
	strcpy(sBar, "सलाखों");
	strcpy(sBars, "सलाखों");
	strcpy(sBothsizesoftheoffcutsmustbegreaterthanthisvalue, "दोनों स्क्रैप आकार इस मूल्य से अधिक होना चाहिए।");
	strcpy(sBottom, "तल");
	strcpy(sBottomcoordinateofthedefect, "नीचे दोष का समन्वय");
	strcpy(sBreakCut, "कट को तोड़ो");
	strcpy(sBrowse, "ब्राउज़");
	strcpy(sBuy, "खरीदें");
	strcpy(sBuynow, "अभी खरीदें ...");
	strcpy(sCancel, "इसे रद्द करें");
	strcpy(sCannotBeEmpty, "खाली नहीं किया जा सकता!");
	strcpy(sCannotmovepartsbetweensheetswhenidenticalsheetsaregroupedPleaseungroupthesheetsfrommenu, "यदि समान शीटों को समूहीकृत किया जाता है तो भागों को एक शीट से दूसरे में नहीं ले जाया जा सकता है। कृपया मेनू से चादरों के समूहन को रद्द करें।");
	strcpy(sCannotSaveFile, "फ़ाइल को सहेज नहीं सकता");
	strcpy(sCenter, "केंद्र");

	strcpy(sChangeDirection, "कट दिशा बदलें");
	strcpy(sChoose, "चुनें");
	strcpy(sChooseProduct, "उत्पाद चुनें");
	strcpy(sCircle, "वृत्त");
	strcpy(sCity, "Faridabad");
	strcpy(sClear, "स्पष्ट");
	strcpy(sClockWise, "दक्षिणावर्त");
	strcpy(sClosewindow, "विंडो बंद करें");
	strcpy(sColor, "रंग");
	strcpy(sColorofedgeband, "एज बैंड्स का रंग");
	strcpy(sColorPattern, "रंग / पैटर्न");
	strcpy(sColorpiecesandwastes, "रंगीन टुकड़े और अपशिष्ट");
	strcpy(sColumns, "कॉलम");
	strcpy(sComment, "टिप्पणी");
	strcpy(sCompanyname, "कंपनी का नाम");
	strcpy(sComplexMaterialExists, "सामग्री का नाम पहले से ही जटिल सामग्रियों की सूची में परिभाषित किया गया है। कृपया इसे एक नया नाम दें।");
	strcpy(sComputerCode, "कंप्यूटर कोड");
	strcpy(sComputerCodefromyourcomputer, "कंप्यूटर कोड (आपके कंप्यूटर से)");
	strcpy(sComputethetotalpriceofDemand, "भागों की कुल कीमत की गणना करें");
	strcpy(sContents, "अंतर्वस्तु");
	strcpy(sContinutComanda, "तारीख में भागों की सामग्री");
	strcpy(sContinutDepozit, "दिनांक में स्टॉक की सामग्री");
	strcpy(sConversionIsDoneOnlyWhenSomePiecesHaveFractionalValues, "रूपांतरण केवल तब किया जाता है जब कुछ टुकड़ों में आंशिक मूल्य होते हैं।");
	strcpy(sConvertsTheSizeOfWasteToAFractionalUnit, "आंशिक मूल्य के रूप में स्क्रैप का आकार दिखाता है।");
	strcpy(sCouldNotSaveFile1, "निर्देशिका में फ़ाइल नहीं लिख सका");
	strcpy(sCouldNotSaveFile2, "आपके पास पर्याप्त अधिकार नहीं हो सकते हैं। कृपया मेन्यू सेटिंग से वर्किंग डायरेक्टरी को चेक या चेंज करें | किसी फ़ोल्डर में कार्यशील निर्देशिका जहां आपके पास लिखने के अधिकार हैं (उदाहरण के लिए c: \\ अस्थायी)।");
	strcpy(sCreationdateYMDHMS, "निर्माण तिथि (Y / M / D-H: M: S)");
	strcpy(sCurrentDate, "आज की तारीख");
	strcpy(sCurrentDiagram, "वर्तमान आरेख");
	strcpy(sCurrentMaterial, "वर्तमान सामग्री");
	strcpy(sCurrentversion, "वर्तमान संस्करण");
	strcpy(sCurve_not_closed_Try_increasing_DXF_linking_distance_parameter, "बहुभुज बंद नहीं है! दूरी पैरामीटर को जोड़ने वाले DXF को बढ़ाने का प्रयास करें।");
	strcpy(sCustomer, "ग्राहक");
	strcpy(sCustomerName, "ग्राहक का नाम");
	strcpy(sCustomMessage, "सीमा शुल्क संदेश");
	strcpy(sCutlength, "कट की लंबाई");
	strcpy(sCut, "कट गया");
	strcpy(sCuts, "कटौती");
	strcpy(sCutterThickness, "मोटाई में कटौती");
	strcpy(sData, "डेटा");
	strcpy(sDataCannotBeEmpty, "डेटा खाली नहीं हो सकता!");
	strcpy(sDateymdhms, "तिथि (y / d / m / एच / m / s)");
	strcpy(sDays_left_for_trial, "परीक्षण के लिए दिन बचे हैं");
	strcpy(sDaysLeft, "दिन शेष");
	strcpy(sStandard, "मानक");
	strcpy(sDefaultInterface, "डिफ़ॉल्ट इंटरफ़ेस");
	strcpy(sDefects, "दोष के");
	strcpy(sDefectsManager, "दोषों का प्रबंधन");
	strcpy(sDefectsofthematerialNopiecescanbeplacedinthefaultyzone, "सामग्री के दोष। किसी भी टुकड़े को दोषपूर्ण क्षेत्र में नहीं रखा जा सकता है।");
	strcpy(sDelete, "हटाएं");
	strcpy(sDeletePiece, "टुकड़ा हटाओ");
	strcpy(sDeleteRow, "पंक्ति को हटाएं");
	strcpy(sDemandutilization, "भागों का उपयोग");
	strcpy(sDepozitulmodificat, "उपयोग किए गए टुकड़े हटा दिए गए हैं। स्क्रैप को स्टॉक में जोड़ा गया है।");
	strcpy(sDepozitvid, "स्टॉक खाली है");
	strcpy(sDesk, "डेस्क");
	strcpy(sDiagram, "आरेख");
	strcpy(sDiagrams, "चित्र");
	strcpy(sDiagramasatable, "तालिका के रूप में आरेख");
	strcpy(sDigits, "अंक");
	strcpy(sDimensiuniplaca, "चादर का आकार");
	strcpy(sDirection, "दिशा");
	strcpy(sDistanceBetweenRows, "पंक्तियों के बीच की दूरी");
	strcpy(sDonotuseit, "इसका प्रयोग न करें");
	strcpy(sDownload, "डाउनलोड");
	strcpy(sDoYouWantToClearTheData, "क्या आप डेटा हटाना चाहते हैं?");
	strcpy(sDoYouWantToSaveDemand, "भागों को बदल दिया गया है! क्या आप किये गए बदलाव को सुरक्षित करना चाहते है?");
	strcpy(sDoYouWantToSaveParts, "क्या आप भागों को बचाना चाहते हैं?");
	strcpy(sDoYouWantToSaveRepository, "स्टॉक बदल दिया गया है! क्या आप किये गए बदलाव को सुरक्षित करना चाहते है?");
	strcpy(sDrawing, "चित्रकारी");
	strcpy(sDrawthesolutioncolorful, "घोल को रंगीन बनाएं");
	strcpy(sDuplicateTypes, "कुछ प्रकार नकल कर रहे हैं! कृपया डुप्लिकेट निकालें");
	strcpy(sDuplicateTypesWithComplex, "सामग्री के कुछ नाम पहले से ही जटिल प्रकारों की सूची में मौजूद हैं! कृपया डुप्लिकेट निकालें");
	strcpy(sDuplicateValues, "डुप्लिकेट मान");
	strcpy(sEdgeband, "एज बैंड");
	strcpy(sEdgebandingwhichisplacedontheedgesofyourpiecePleasedefineedgebandingtypesfromMaterialsEdgeBandingmenu, "एज बैंड को आपके टुकड़े के हाशिये पर रखा जाता है। कृपया सामग्री मेनू में किनारे बैंड को परिभाषित करें।");
	strcpy(sEdgebandsthatwillbeappliedtoeachpart, "प्रत्येक बैंड पर लागू होने वाले किनारे बैंड।");
	strcpy(sEdgeBandTolerance, "बढ़त बैंड के लिए सहिष्णुता");
	strcpy(sEdgesthatmustbecutduefaults, "दोष के कारण कट जाने वाली धारें।");
	strcpy(sEdgetoedge, "किनारे से किनारे तक");
	strcpy(sEdit, "संपादित करें");
	strcpy(sEmail, "ईमेल");
	strcpy(sEmptyData, "डेटा खाली हैं!");
	strcpy(sEnabled, "सक्रिय");
	strcpy(sEnabledisabledefectsoftheinventorysheets, "स्टॉक के दोषों को सक्षम / अक्षम करें");
	strcpy(sEnterLabel, "लेबल इनपुट करें");
	strcpy(sEnterTheMaterialName, "सामग्री का नाम इनपुट करें");
	strcpy(sEnterTheProductName, "उत्पाद का नाम दर्ज करें");
	strcpy(sEvaluationError, "अभिव्यक्ति मूल्यांकन में त्रुटि!");
	strcpy(sExit, "बाहर जाएं");
	strcpy(sExpired, "सॉफ्टवेयर की समय सीमा समाप्त हो गई है! कृपया सॉफ्टवेयर को पंजीकृत करें!");
	strcpy(sExport, "निर्यात");
	strcpy(sExportAllDiagrams, "सभी आरेखों का निर्यात करें");
	strcpy(sExportAllToASingleFile, "सभी को एक फ़ाइल में निर्यात करें");
	strcpy(sExportOptions, "निर्यात विकल्प");
	strcpy(sExporttoDXFformat, "DXF प्रारूप में निर्यात करें");
	strcpy(sExporttoExcel, "एक्सेल में भेजे");
	strcpy(sExpresieIncorecta, "गलत गणितीय अभिव्यक्ति!");
	strcpy(sExtensions, "एक्सटेंशन");
	strcpy(sExtra, "अतिरिक्त");
	strcpy(sExtraComponents, "अतिरिक्त घटक");
	strcpy(sExtracomponentsattachedtoDemand, "भागों से जुड़े अतिरिक्त घटक");
	strcpy(sFile, "फ़ाइल");
	strcpy(sFileName, "फ़ाइल का नाम");
	strcpy(sFillWastes, "तिरछी रेखाओं के साथ अपशिष्ट खींचें");
	strcpy(sFindoptimalbarsheetsize, "बार और शीट के लिए इष्टतम आकार का पता लगाएं।");
	strcpy(sFindoptimalsizeofInventorypieces, "स्टॉक टुकड़ों के इष्टतम आकार का पता लगाएं");
	strcpy(sFirstcutMultiplestages, "कई चरण अनुकूलन के लिए पहली कट दिशा।");
	strcpy(sFirstdirectionforcutishorizontal, "कट के लिए पहली दिशा क्षैतिज है।");
	strcpy(sFirstdirectionforcutisvertical, "कट के लिए पहली दिशा ऊर्ध्वाधर है।");
	strcpy(sFollowthecontourofpieces, "टुकड़ों के समोच्च का पालन करें");
	strcpy(sFont, "फ़ॉन्ट");
	strcpy(sFontsize, "फ़ॉन्ट आकार");
	strcpy(sFullInfo, "पूरी जानकारी");
	strcpy(sDisposedWaste, "निस्तारित कचरा");
	strcpy(sGeneral, "सामान्य");
	strcpy(sGenerateCNC, "सीएनसी उत्पन्न करें");
	strcpy(sGrain, "बनावट");
	strcpy(sGraindirection, "बनावट की दिशा");
	strcpy(sGraphic, "ग्राफिक");
	strcpy(sGreaterorequalto, "के बराबर या उससे अधिक");
	strcpy(sGrid, "टेबल्स");
	strcpy(sGrinding, "पिसाई");
	strcpy(sGrosimeTaieturaScalata, "इस चित्र से कट की मोटाई वास्तविक से भिन्न हो सकती है क्योंकि टुकड़ों का उनके वास्तविक पैमाने पर प्रतिनिधित्व नहीं किया जाता है। यह तथ्य परिणामों को प्रभावित नहीं करता है।");
	strcpy(sGroupidenticallayouts, "समूह समान चादरें");
	strcpy(sGroupIdenticalParts, "समूह समान भागों");
	strcpy(sGroupingOfIdenticalPiecesIntoOneRow, "एक पंक्ति में समान भागों को समूहित करें।");
	strcpy(sGroupPartsAfterLoadingFromFile, "फ़ाइल से लोड करते समय समूह भागों");
	strcpy(sHeight, "ऊंचाई");
	strcpy(sHeighttolerance, "ऊंचाई के लिए सहिष्णुता");
	strcpy(sHelp, "मदद");
	strcpy(sHistory, "इतिहास");
	strcpy(sHorizontal, "क्षैतिज");
	strcpy(sHowtodisplayprintedgebands, "बढ़त बैंड कैसे प्रदर्शित होते हैं?");
	strcpy(sIfyousetthebandforoneedgeallwillreceivethesamevalue, "यदि आप एक किनारे के लिए बैंड सेट करते हैं, तो सभी किनारों को समान मूल्य प्राप्त होगा।");
	strcpy(sIfyousetthegrindingforoneedgeallwillreceivethesamevalue, "यदि आप एक किनारे के लिए पीस मूल्य निर्धारित करते हैं, तो सभी किनारों को समान मूल्य प्राप्त होगा।");
	strcpy(sIfyousetthetrimforoneedgeallwillreceivethesamevalue, "यदि आप एक किनारे के लिए ट्रिमिंग सेट करते हैं, तो सभी किनारों को समान मूल्य प्राप्त होगा।");
	strcpy(sImageBounds, "छवि के लिए सीमा");
	strcpy(sImageSize, "छवि का आकार");
	strcpy(sImportData, "डेटा आयात करें");
	strcpy(sIncorrectPassword, "गलत पासवर्ड");
	strcpy(sIndex, "सूची");
	strcpy(sInformationaboutcustomer, "ग्राहक के बारे में जानकारी");
	strcpy(sInputALanguageName, "भाषा का नाम इनपुट करें");
	strcpy(sInsert, "सम्मिलित करें");
	strcpy(sInsertPiece, "टुकड़ा डालें");
	strcpy(sInterface, "इंटरफेस");
	strcpy(sInterfaceSettings, "इंटरफ़ेस सेटिंग्स");
	strcpy(sInvalidHardware, "मैं हार्डवेयर का पता नहीं लगा सका। कृपया हमसे contact@optimalprograms.com पर संपर्क करें");
	strcpy(sInvalidNumber, "अमान्य संख्या");
	strcpy(sInvalidOrderOfComputation, "लंबाई की गणना के लिए एक आदेश स्थापित नहीं किया जा सकता है। उत्पाद की परिभाषा में परिपत्र रिश्ते हैं!");
	strcpy(sInvalidRegistration, "पंजीकरण अमान्य है!");
	strcpy(sInvalidTime, "आपके सिस्टम का समय अमान्य है।");
	strcpy(sInventory, "भण्डार");
	strcpy(sisafractionalvalue, "एक भिन्नात्मक मूल्य है।");
	strcpy(sIsArc, "चाप है");
	strcpy(sisarealvalue, "एक वास्तविक मूल्य है।");
	strcpy(sLabel, "लेबल");
	strcpy(sLabels, "लेबल");
	strcpy(sLanguage, "भाषा: हिन्दी");
	strcpy(sLatimeanumar0, "चौड़ाई 0 से अधिक होनी चाहिए!");
	strcpy(sLatimeanumarreal, "चौड़ाई एक वास्तविक संख्या होनी चाहिए!");
	strcpy(sLayerName, "परत का नाम");
	strcpy(sLeft, "बाएं");
	strcpy(sLeftcoordinateofthedefect, "दोष का बायाँ समन्वय");
	strcpy(sLength, "लंबाई");
	strcpy(sLengthofthepiecestocut, "काटने के लिए टुकड़े का आकार");
	strcpy(sLengthofthepiecestocutfrom, "काटने के लिए शीट का आकार");
	strcpy(sLengthofusedbars, "प्रयुक्त सलाखों का आकार");
	strcpy(sLicenseAgreement, "लाइसेंस समझौता");
	strcpy(sLinear, "रैखिक");
	strcpy(sLinethickness, "कलम की मोटाई");
	strcpy(sLoadafileandappenddatatothecurrentDemand, "एक फ़ाइल लोड करें और वर्तमान भागों में डेटा संलग्न करें।");
	strcpy(sLoadanexistingDemandfromafile, "मौजूदा भागों को एक फ़ाइल से लोड करें।");
	strcpy(sLoadAppend, "लोड और परिशिष्ट");
	strcpy(sLoadEverything, "सब कुछ लोड करें");
	strcpy(sLoadInventory, "स्टॉक लोड करें");
	strcpy(sLoadInventoryandDemand, "स्टॉक और भागों को लोड करें");
	strcpy(sLoadResults, "परिणाम लोड करें");
	strcpy(sLocked, "बंद");
	strcpy(sLogo, "प्रतीक चिन्ह");
	strcpy(sLong, "लंबा");
	strcpy(sLongerexecutiontime, "लंबे समय तक चलने वाला समय");
	strcpy(sLungime, "लंबाई");
	strcpy(sLungimeanumar0, "लंबाई 0 से अधिक होनी चाहिए!");
	strcpy(sLungimeanumarreal, "लंबाई एक वास्तविक संख्या होनी चाहिए!");
	strcpy(sLungimeaTotalaFolosita, "कुल उपयोग की गई लंबाई");
	strcpy(sMagnification, "बढ़ाई");
	strcpy(sMagnify, "आवर्धक");
	strcpy(sMargins, "मार्जिन");
	strcpy(sMarginsForPaper, "कागज के लिए मार्जिन");
	strcpy(sMarginsOfTheLabel, "लेबल का मार्जिन");
	strcpy(sMaterial, "सामग्री");
	strcpy(sMaterialName, "सामग्री का नाम");
	strcpy(sMaterials, "सामग्री");
	strcpy(sMaterialstypes, "सामग्री के प्रकार");
	strcpy(sMax, "मैक्स");
	strcpy(sMaximalArea, "अधिकतम क्षेत्र");
	strcpy(sMaximalCutLength, "अधिकतम कट लंबाई");
	strcpy(sMaxlength, "अधिकतम लंबाई");
	strcpy(sMaxPiecesperBar, "प्रति बार टुकड़ों की अधिकतम संख्या");
	strcpy(sMaxwidth, "अधिकतम चौड़ाई");
	strcpy(sMeasurementUnit, "मापन इकाई");
	strcpy(sMin, "मिन");
	strcpy(sMinimalBreakSize, "न्यूनतम विराम आकार");
	strcpy(sMinimalUsefulSize, "न्यूनतम उपयोगी आकार");
	strcpy(sMinimalwastesizetoInventory, "न्यूनतम स्क्रैप आकार स्टॉक में जोड़ा गया।");
	strcpy(s_What_to_minimize, "क्या कम करें?");
	strcpy(sMinlength, "न्यूनतम लंबाई");
	strcpy(sMinwidth, "न्यूनतम चौड़ाई");
	strcpy(sMirror, "आईना");
	strcpy(sMirroring, "मिररिंग");
	strcpy(sMiscellaneous, "अन्य आँकड़े");
	strcpy(sModify, "संशोधित");
	strcpy(sModifytheselectedpiece, "चयनित टुकड़े को संशोधित करें");
	strcpy(sMovePiece, "चल टुकड़ा");
	strcpy(sMultiplestages, "कई चरणों");
	strcpy(sName, "नाम");
	strcpy(sNameofedgeband, "एज बैंड का नाम");
	strcpy(sNewDEMANDUnsaveddatawillbelost, "नए भागों? खोया हुआ डेटा खो जाएगा!");
	strcpy(sNewLanguage, "नई भाषा");
	strcpy(sNewMaterial, "नई सामग्री");
	strcpy(sNewPasswordincorectlyintroduced, "नया पासवर्ड गलत पेश किया गया!");
	strcpy(sNewProduct, "नया उत्पाद");
	strcpy(sNewversion, "नया संस्करण");
	strcpy(sNo, "नहीं");
	strcpy(sNumarBucati, "टुकड़ों की संख्या");
	strcpy(sNumberOfCopies, "प्रतियों की संख्या");
	strcpy(sNumberofstages, "चरणों की संख्या");
	strcpy(sNusuficienteplacidepozit, "सभी टुकड़ों को अनुकूलित नहीं किया गया है। संभावित कारण: स्टॉक में पर्याप्त टुकड़े नहीं हैं। टुकड़े सक्षम नहीं हैं। टुकड़ों और स्टॉक की सामग्री अलग हैं। अन्य मापदंडों को गलत तरीके से सेट किया गया है।");
	strcpy(sOfficeNotInstaled, "Microsoft Office आपके कंप्यूटर पर स्थापित नहीं है या एक गलत संस्करण स्थापित है!");
	strcpy(sOldpassworddoesnotmatch, "पुराना पासवर्ड मेल नहीं खाता!");
	strcpy(sOnlinehelp, "ऑनलाइन सहायता");
	strcpy(sOnlypiecesofthesameheightinthelaststage, "अंतिम चरण में समान ऊंचाई के टुकड़े");
	strcpy(sOpen, "खुला हुआ");
	strcpy(sOptimization, "अनुकूलन");
	strcpy(sOptimizationDone, "अनुकूलन प्रदर्शन किया! आप प्राप्त आरेखों को प्रिंट या सहेज सकते हैं। प्रेस बटन स्वीकार करें यदि आप वर्तमान समाधान से संतुष्ट हैं। अन्यथा फिर से प्रारंभ दबाएं।");
	strcpy(sOptimizationType, "अनुकूलन प्रकार");
	strcpy(sOptions, "विकल्प");
	strcpy(sOptionsrelatedtotheinterface, "इंटरफ़ेस से संबंधित विकल्प");
	strcpy(sor, "या");
	strcpy(sOthercomponents, "अन्य घटक");
	strcpy(sOthers, "अन्य");
	strcpy(sOtherstatistics, "अन्य आँकड़े");
	strcpy(sOverrideExcelCSVfiles, "Excel / CSV फ़ाइलों को ओवरराइड करें");
	strcpy(sParameter, "पैरामीटर");
	strcpy(sParts, "टुकड़े");
	strcpy(sPattern, "पैटर्न");
	strcpy(sPatternforwaste, "स्क्रैप के लिए पैटर्न");
	strcpy(sPerimeter, "परिमाप");
	strcpy(sPermitedRotationAngle, "अनुमति रोटेशन कोण");
	strcpy(sPhone, "फ़ोन");
	strcpy(sPicture, "छवि");
	strcpy(sPiece, "टुकड़ा");
	strcpy(sPieceindex, "टुकड़ा का सूचकांक");
	strcpy(sPieces, "टुकड़े");
	strcpy(sPiecesize, "टुकड़ा का आकार");
	strcpy(sPiecesizelabeledgebandwillbeprinted, "टुकड़ा आकार, लेबल, किनारे बैंड मुद्रित किया जाएगा।");
	strcpy(sPierdere, "रद्दी माल");
	strcpy(sPixels, "पिक्सल");
	strcpy(sPlacilefolositeDepozit, "स्टॉक से उपयोग किए गए टुकड़े।");
	strcpy(sPlease_contact_us_at_contact_nestingtechnologies_com, "कृपया हमसे contact@nesting-technologies.com पर संपर्क करें");
	strcpy(sPlease_contact_us_at_contact_optimalprograms_com, "कृपया हमसे contact@optimalprograms.com पर संपर्क करें");
	strcpy(sPleaseenteralldataeitherasfractionalorrealDonotmixthem, "कृपया सभी संख्याओं को भिन्नात्मक मानों या वास्तविक मानों के रूप में दर्ज करें! उन्हें मिश्रण मत करो!");
	strcpy(sPleaseEnterSomeTypesOfMaterials, "किसी भी प्रकार की सामग्री परिभाषित नहीं है। आप उन्हें सामग्री मेनू से परिभाषित कर सकते हैं।");
	strcpy(sPleasesendtheNameandtheCodetotheaddresscontactoptimalprogramscominordertoobtaintheRegistrationKey, "पंजीकरण कुंजी प्राप्त करने के लिए कृपया contact@optimalprograms.com पर नाम और कोड भेजें।");
	strcpy(sPolygon, "बहुभुज");
	strcpy(sPolygonsCircles, "बहुभुज, मंडलियां");
	strcpy(sPrecision, "शुद्धता");
	strcpy(sPretulnumar0, "कीमत 0 से अधिक होनी चाहिए!");
	strcpy(sPretulnumarreal, "कीमत एक वास्तविक संख्या होनी चाहिए!");
	strcpy(sPreview, "पूर्वावलोकन");
	strcpy(sPrice, "कीमत");
	strcpy(sPriceMustBeGreaterThanZero, "कीमत शून्य से अधिक होनी चाहिए");
	strcpy(sPriceofbars, "सलाखों की कीमत");
	strcpy(sPriceperbar, "मूल्य प्रति बार");
	strcpy(sPricepersheet, "प्रति शीट मूल्य");
	strcpy(sPricepersquareunitofmaterial, "सामग्री की प्रति वर्ग इकाई कीमत");
	strcpy(sPriceperunit, "प्रति इकाई मूल्य");
	strcpy(sPrint, "छाप");
	strcpy(sPrintdiagramsastables, "आरेखों को तालिकाओं के रूप में प्रिंट करें।");
	strcpy(sPrinter, "मुद्रक");
	strcpy(sPrinterBounds, "प्रिंटर के लिए मार्जिन");
	strcpy(sPrinting, "मुद्रण");
	strcpy(sPrintonlyutilizedarea, "केवल उपयोग किए गए क्षेत्र को प्रिंट करें");
	strcpy(sPrintthecontentsoftheDemand, "भागों की सामग्री मुद्रित करें।");
	strcpy(sPrintthecontentsoftheInventory, "स्टॉक की सामग्री को प्रिंट करें।");
	strcpy(sPrintthecurrentsolution, "वर्तमान समाधान प्रिंट करें।");
	strcpy(sPriority, "प्राथमिकता");
	strcpy(sPrioritytocutapieceZero0isthehighestpriority, "एक टुकड़ा काटने की प्राथमिकता। शून्य (0) सर्वोच्च प्राथमिकता है।");
	strcpy(sProcentul0100, "पर्केंट्स 0 से अधिक और कम या 100 के बराबर होना चाहिए!");
	strcpy(sProcentulnumarreal, "Percents एक वास्तविक संख्या होनी चाहिए!");
	strcpy(sProductdefinition, "उत्पाद का निर्धारण");
	strcpy(sProductExists, "उत्पाद पहले से मौजूद है। कोई दूसरा नाम चुनें।");
	strcpy(sProductName, "उत्पाद का नाम");
	strcpy(sProducts, "उत्पाद");
	strcpy(sProducts, "उत्पाद");
	strcpy(sProject, "परियोजना");
	strcpy(sProperties, "गुण");
	strcpy(sProperty, "संपत्ति");
	strcpy(sQuantity, "मात्रा");
	strcpy(sQuantitynumberofsheetsofthistype, "इस प्रकार की चादरों की संख्या");
	strcpy(sRadius, "त्रिज्या");
	strcpy(sRectangular, "आयताकार");
	strcpy(sRedefinetypesofedgeband, "बढ़त बैंड के प्रकार को फिर से परिभाषित करें");
	strcpy(sRedefinetypesofmaterial, "सामग्री को फिर से परिभाषित करें");
	strcpy(sRegistration, "पंजीकरण");
	strcpy(sRegistrationKeyfromOptimalPrograms, "पंजीकरण कुंजी");
	strcpy(sRegistrationSuccessful, "पंजीकरण सफल रहा!");
	strcpy(sRemoveallpiecesinInventory, "इन्वेंटरी में सभी टुकड़े निकालें।");
	strcpy(sRemoveCut, "कट हटाएं");
	strcpy(sRemovetheselectedpiece, "चुने हुए टुकड़े को हटा दें");
	strcpy(sReports, "रिपोर्ट");
	strcpy(sRequestedMaterial, "आवश्यक सामग्री");
	strcpy(sRestore, "पुनर्स्थापित");
	strcpy(sResults, "परिणाम");
	strcpy(sReusedwaste, "पुन: उपयोग किया हुआ कचरा");
	strcpy(sRight, "सही");
	strcpy(sRightcoordinateofthedefect, "दाईं ओर से दोष का निर्देशांक");
	strcpy(sRotation, "रोटेशन");
	strcpy(sRotationAngle, "वर्तन कोण");
	strcpy(sRotationStep, "रोटेशन कदम");
	strcpy(sRoundAllFractionsTo, "भिन्नात्मक मूल्यों को गोल किया जाना चाहिए");
	strcpy(sRow, "पंक्ति");
	strcpy(sRows, "पंक्तियाँ");
	strcpy(sRun, "नवीनतम समाधान");
	strcpy(sRunningtime, "कार्यकारी समय");
	strcpy(sSameforall, "सभी के लिए समान");
	strcpy(sSave, "सहेजें");
	strcpy(sSaveAllImages, "सभी छवियों को सहेजें");
	strcpy(sSaveAs, "के रूप रक्षित करें");
	strcpy(sSaveChanges, "भागों को बदल दिया गया है। क्या आप उन्हें बचाना चाहते हैं?");
	strcpy(sSaveCurrentImage, "वर्तमान छवि सहेजें");
	strcpy(sSavedataparameters, "डेटा और पैरामीटर सहेजें");
	strcpy(sSaveEverything, "सब कुछ बचा लो");
	strcpy(sSaveInventory, "इन्वेंटरी को बचाएं");
	strcpy(sSaveInventoryandDemand, "स्टॉक और भागों को बचाएं");
	strcpy(sSaveResults, "परिणाम सहेजें");
	strcpy(sSaveStatisticsinafile, "किसी फ़ाइल में आँकड़े सहेजें");
	strcpy(sSavethecurrentimage, "वर्तमान छवि सहेजें");
	strcpy(sSavethecurrentimageorstatistic, "वर्तमान छवि या आँकड़े सहेजें");
	strcpy(sSavetheDEMANDinafile, "फाइल में बचाएं");
	strcpy(sSavetheDemandinafilewithadifferentname, "एक अलग नाम के साथ भागों को फ़ाइल में सहेजें।");
	strcpy(sSavetheREPOSITORYinafile, "स्टॉक को किसी फ़ाइल में सहेजें");
	strcpy(sSerialNumber, "पंजीकरण कुंजी");
	strcpy(sService, "सर्विस");
	strcpy(sSetDefaultValues, "यह सभी मापदंडों को उनके डिफ़ॉल्ट मानों को पुनर्स्थापित करेगा। आपकी सभी सेटिंग्स खो जाएगी। क्या आप वास्तव में इसे करना चाहते हैं?");
	strcpy(sSetedgeband, "एज बैंड सेट करें");
	strcpy(sSetedgetrim, "हाशिये के दोषों के लिए कट आकार निर्धारित करें");
	strcpy(sSetthesameedgebandforalledges, "सभी पक्षों के लिए एक ही एज बैंड सेट करें");
	strcpy(sSetthesamegrindingforalledges, "सभी किनारों के लिए एक ही पीस सेट करें");
	strcpy(sSetthesametrimforalledges, "सभी किनारों के दोषों के लिए एक ही कटिंग सेट करें");
	strcpy(sSettings, "समायोजन");
	strcpy(sShape, "आकार");
	strcpy(sSheet, "चादर");
	strcpy(sSheetsBarstypes, "चादरें_बार प्रकार");
	strcpy(sSheetSize, "चादर का आकार");
	strcpy(sSheetsperPage, "प्रति पृष्ठ चादरें");
	strcpy(sShort, "कम");
	strcpy(sShorterexecutiontime, "शॉर्ट रनिंग टाइम");
	strcpy(sShowallsimpleproducts, "सभी सरल उत्पाद दिखाएं");
	strcpy(sShowcustomername, "ग्राहक का नाम दिखाएं");
	strcpy(sShowCustomTextOnEachPiece, "प्रत्येक टुकड़े पर कस्टम टेक्स्ट दिखाएं");
	strcpy(sShowdiagramasatable, "आरेख को तालिका के रूप में दिखाएं।");
	strcpy(sShowedgeband, "एज बैंड दिखाओ");
	strcpy(sShowedgebandssettinginanewwindow, "एक नई विंडो में एज बैंड की सेटिंग दिखाएं");
	strcpy(sShowgrindingsettingsinanewwindow, "एक नई विंडो में पीस सेटिंग्स दिखाता है");
	strcpy(sShowHorizontalLabelsAlways, "हमेशा क्षैतिज लेबल दिखाएं");
	strcpy(sShowRemovethesizeofthepiecesinthecurrentsolution, "टुकड़ों के आकार को दिखाएं / छिपाएँ।");
	strcpy(sShowRemovethesizeofthewastesinthecurrentsolution, "स्क्रैप का आकार दिखाएँ / छिपाएँ।");
	strcpy(sShowtotalcutlength, "कुल काटने की लंबाई दिखाएं");
	strcpy(sShowtrimedgesettingsinanewwindow, "एक नई विंडो में दोषों की सेटिंग दिखाएं");
	strcpy(sSimpleMaterialExists, "सामग्री का नाम पहले से ही सामग्री की सूची में परिभाषित किया गया है। कृपया इसे एक नया नाम दें।");
	strcpy(sSinglePieceStrips, "एक टुकड़े की धारियाँ");
	strcpy(sSizes, "आकार");
	strcpy(sSmallerorequalto, "छोटा या बराबर");
	strcpy(sSort, "तरह");
	strcpy(sSortAscendingByArea, "आरोही क्रम में क्षेत्र द्वारा क्रमबद्ध करें");
	strcpy(sSortDescendingByArea, "अवरोही क्रम में क्षेत्र द्वारा क्रमबद्ध करें");
	strcpy(sSpecifyhowdifferentthepiecesinthelaststagecanbeValue0meansnodifference, "निर्दिष्ट करें कि अंतिम चरण में टुकड़े कितने अलग हो सकते हैं। मान 0 का मतलब कोई अंतर नहीं है।");
	strcpy(sSpecifyifpiecesinthelaststagecanbedifferentornotdepeultimaetapapotfidiferitesaunucadimensiune, "निर्दिष्ट करें कि अंतिम चरण के टुकड़े अलग-अलग हो सकते हैं या नहीं");
	strcpy(sSpecifyifthepiececanberotatedornotIfnotitwillbecutinthesamewayasitwasintroducedinDemandLengthofthepieceparalleltothelengthofthesheet, "निर्दिष्ट करें कि टुकड़ा घुमाया जा सकता है या नहीं। यदि नहीं, तो इसे उसी तरह रखा गया है जैसे इसे पेश किया गया था (शीट की लंबाई के साथ समानांतर की लंबाई), ");
	strcpy(sSpecifyinhowmanystageswemakethecutsDuringastageallcutshavethesamedirection, "निर्दिष्ट करें कि हम कितने चरणों में कटौती करते हैं।");
	strcpy(sStartthesearchprocess, "खोज प्रक्रिया शुरू करें");
	strcpy(sStatistics, "आंकड़े");
	strcpy(sStatisticsE, "रिपोर्ट अतिरिक्त");
	strcpy(sStatisticsforeachtypeofmaterial, "प्रत्येक प्रकार की सामग्री के लिए आँकड़े");
	strcpy(sStep, "चरण");
	strcpy(sStergeDepozit, "क्या आप इन्वेंटरी को हटाना चाहते हैं?");
	strcpy(sStergeMaterial, "क्या आप सामग्री हटाना चाहते हैं?");
	strcpy(sStergePiesele, "क्या आप टुकड़ा हटाना चाहते हैं?");
	strcpy(sStergePiesa, "क्या आप टुकड़ा हटाना चाहते हैं?");
	strcpy(sStopthesearchprocess, "खोज प्रक्रिया रोकें");
	strcpy(sStrongoptimization, "मजबूत अनुकूलन");
	strcpy(sSubtractthebandthicknessfrompiecesize, "किनारे की मोटाई के साथ टुकड़ों का आकार घटाएं");
	strcpy(sSummary, "सारांश");
	strcpy(sSuprafataTotalaFolosita, "कुल उपयोग की सतह");
	strcpy(sSuprafatautilizata, "उपयोग");
	strcpy(sSwitchbetweenfiberandrotationoption, "फाइबर और रोटेशन विकल्प के बीच स्विच करें।");
	strcpy(sTechnical, "तकनीकी");
	strcpy(sTechnicalsettings, "तकनीकी सेटिंग्स");
	strcpy(sTemporaryPanelHint, "चादरों के बीच बढ़ते भागों के लिए अस्थायी पैनल।");
	strcpy(sText, "टेक्स्ट");
	strcpy(sThe_application_has_expired, "आवेदन की समय सीमा समाप्त हो गई है।");
	strcpy(sThe_application_is_not_registered, "आवेदन पंजीकृत नहीं है।");
	strcpy(sThe_application_was_first_started_on, "सबसे पहले आवेदन शुरू किया गया था");
	strcpy(sThecutsareperformedfromasidetotheothersideofthematerial, "कटौती एक तरफ से सामग्री के दूसरी तरफ की जाती है।");
	strcpy(sThecuttingmachinecanfollowtheshapeofthematerial, "काटने की मशीन टुकड़ा के आकार का पालन कर सकती है।");
	strcpy(sTheedgesofsheetsthatmustbetrimedduefaults, "चादरों के किनारों को दोष के कारण छंटनी चाहिए");
	strcpy(sTheLargestSize, "सबसे बड़ा आकार");
	strcpy(sThenameofthecustomerforwhichyoucutthepiece, "ग्राहक का नाम जिसके लिए आपने टुकड़ा काटा।");
	strcpy(sThenameofyourcustomer, "आपके ग्राहक का नाम");
	strcpy(sThepiececanberotated, "टुकड़ा घुमाया जा सकता है");
	strcpy(sTheprogramtriestoavoidwasteswhichhavebothsizeslessthanthisvalue, "कार्यक्रम स्क्रैप से बचने की कोशिश करता है जो इस मूल्य से छोटा है");
	strcpy(sThereAreNoProducts, "अभी तक कोई परिभाषित उत्पाद नहीं हैं");
	strcpy(sThestockofmaterialhasbeenpreviouslyloadedfromanExcelorCSVformatPleaseloaditagain, "सामग्री का स्टॉक पहले एक एक्सेल या सीएसवी प्रारूप से लोड किया गया है। यदि आप इस पर काम करना चाहते हैं तो कृपया इसे फिर से लोड करें।");
	strcpy(sThetotallengthofcutting, "काटने की कुल लंबाई");
	strcpy(sThewidthofthecuttingsawForglasscuttingoptimizationitcanbe0Forwooditshouldbegreaterthan0, "आरी की मोटाई। कांच काटने के लिए यह 0. हो सकता है। लकड़ी के लिए यह 0 से अधिक होना चाहिए।");
	strcpy(sThewidthofthecuttingsawforlinearpieces, "रैखिक टुकड़ों के लिए आरा की मोटाई।");
	strcpy(sThickness, "मोटाई");
	strcpy(sThischaracterisusedforfillingthewasterectanglesIfyoudonotwantfilledwastejustremovethischaracter, "इस प्रतीक का उपयोग अपशिष्ट आयतों को भरने के लिए किया जाता है। यदि आप नहीं चाहते कि भरा हुआ कचरा इसे हटा दें।");
	strcpy(sThisindexhasvaluebetween1andthenumberofpieces, "इस सूचकांक में 1 और टुकड़ों की संख्या के बीच मूल्य है।");
	strcpy(sThisOptionWillOverrideTheInventoryFileIfLoadedFromExcelOrCsvFiles, "एक्सेल या सीएसवी फाइलों से लोड होने पर यह विकल्प इन्वेंट्री फाइल को ओवरराइड कर देगा।");
	strcpy(sThisProgramisLicensedTo, "इस कार्यक्रम के लिए लाइसेंस प्राप्त है");
	strcpy(sThisvaluewillbeaddedtotheedgebandingmaterialoneachside, "यह मान हर तरफ किनारे के बैंड में जोड़ा जाएगा");
	strcpy(sTipNevid, "सामग्री का प्रकार खाली नहीं हो सकता।");
	strcpy(sTitle, "शीर्षक");
	strcpy(sTools, "उपकरण");
	strcpy(sTop, "ऊपर");
	strcpy(sTopcoordinateofthedefect, "दोष का शीर्ष समन्वय।");
	strcpy(sTotalGarbageWaste, "सभी ने स्क्रैप छोड़ दिया");
	strcpy(sTotalInventoryWaste, "कुल स्टॉक स्क्रैप");
	strcpy(sTotalRecycledWaste, "सभी पुन: उपयोग स्क्रैप");
	strcpy(sTotalusedarea, "कुल इस्तेमाल किया क्षेत्र");
	strcpy(sTotalusedlength, "कुल प्रयुक्त लंबाई");
	strcpy(sTrigonometric, "त्रिकोणमितीय");
	strcpy(sTrim, "ट्रिम");
	strcpy(sTrimalledgesatthebeginning, "शुरुआत में सभी किनारों को ट्रिम करें");
	strcpy(sTrimEdge, "किनारे को छाँटो");
	strcpy(sTwoPanels, "2 पैनल");
	strcpy(sType, "प्रकार");
	strcpy(sTypeofmaterialfromwhichtocut, "सामग्री का प्रकार जिसमें से कटौती करना है");
	strcpy(sTypesAreNotMatched, "अनुकूलन प्रदर्शन नहीं किया गया था! वर्तमान में, स्टॉक में ऐसी कोई सामग्री नहीं है! उसी सामग्री की शीट से टुकड़ों को काटा जा सकता है। संबंधित कॉलम से कुछ सामग्री बदलें!");
	strcpy(sUndo, "पूर्ववत करें");
	strcpy(sUndoAccept, "पूर्ववत स्वीकार करें");
	strcpy(sUnits, "इकाइयों");
	strcpy(sUnregisteredVersion, "अपंजीकृत");
	strcpy(sUpdates, "अपडेट");
	strcpy(sUsefulforwoodfurniture, "लकड़ी के फर्नीचर के लिए उपयोगी");
	strcpy(sUseit, "इसका इस्तेमाल करें");
	strcpy(sUsePieceinOptimization, "अनुकूलन में टुकड़े का उपयोग करें");
	strcpy(sUserName, "उपयोगकर्ता नाम");
	strcpy(sUtilizationandWastes, "उपयोग और स्क्रैप");
	strcpy(sUtilizedArea, "उपयोग किए गए भागों का क्षेत्र");
	strcpy(sUtilizedBars, "उपयोग किए गए बार");
	strcpy(sUtilizeddemandcount, "उपयोग किए गए भागों की संख्या");
	strcpy(sUtilizedParts, "उपयोग किए गए भाग");
	strcpy(sUtilizedPieces, "उपयोग किए गए टुकड़े");
	strcpy(sUtilizedSheets, "उपयोग की गई चादरें");
	strcpy(sValue, "मूल्य");
	strcpy(sValueGreaterEqualToZero, "मान शून्य से अधिक या बराबर होना चाहिए");
	strcpy(sValueGreaterThanZero, "मान शून्य से अधिक होना चाहिए");
	strcpy(sValueIntegerNumber, "मान एक पूर्णांक संख्या होना चाहिए!");
	strcpy(sValueRealNumber, "मान एक वास्तविक संख्या होनी चाहिए। हो सकता है कि आपने पीरियड या वाइसवर्स की जगह कॉमा का इस्तेमाल किया हो। कृपया इसे ठीक करे!");
	strcpy(s_The_number_is_too_big_or_it_has_too_many_digits_after_decimal_separator, "संख्या बहुत बड़ी है या इसमें दशमलव विभाजक के बाद बहुत अधिक अंक हैं!");
	strcpy(s_The_number_is_too_big, "संख्या बहुत बड़ी है!");
	strcpy(sVertical, "खड़ा");
	strcpy(sWaste, "रद्दी माल");
	strcpy(sWastes, "रद्दी माल");
	strcpy(sWasteAddedToWarehouse, "स्टॉक में स्क्रैप जोड़ा गया");
	strcpy(sWastelimits, "स्क्रैप के लिए सीमा");
	strcpy(sWasteType, "स्क्रैप का प्रकार");
	strcpy(sWeakoptimization, "सबसे कमजोर अनुकूलन");
	strcpy(sWhattoprint, "मुझे क्या छापना चाहिए");
	strcpy(s_What_to_print_or_save_to_file, "क्या प्रिंट करना है या फ़ाइल में सेव करना है");
	strcpy(sWhattoprintoneachpiece, "प्रत्येक टुकड़े पर क्या छपना है");
	strcpy(sWhattoshowoneachpiece, "प्रत्येक टुकड़े पर क्या दिखाना है?");
	strcpy(sWidth, "चौड़ाई");
	strcpy(sWood, "लकड़ी");
	strcpy(sWorkingDirectory, "वर्किंग फोल्डर");
	strcpy(sWrongKey, "गलत पंजीकरण कुंजी!");
	strcpy(sYes, "हाँ");
	strcpy(sYoucannotchooseblackblueorredcolors, "आप काले, नीले या लाल रंग नहीं चुन सकते।");
	strcpy(sYouCannotMixFractionalDataWithDecimalOnes, "आप वास्तविक मूल्यों के साथ भिन्नात्मक मूल्यों को नहीं मिला सकते हैं!");
	strcpy(sYourcompany, "आपकी कंपनी");
	strcpy(sZip, "डाक कोड");
	strcpy(s_Set_the_origin_and_the_direction_of_the_axes, "निर्देशांकों के अक्षों की उत्पत्ति और दिशा निर्धारित करें।");

}
