// Language strings: Hungarian
// Author: Optimal Programs
// License: MIT License
//---------------------------------------------------------------------------
#include <string.h>
//---------------------------------------------------------------------------
#include "language_string_id.h"
//---------------------------------------------------------------------------
void set_hu(void)
{
	//Hungarian
	//checked by a customer
	//2025.3.29.0
	strcpy(s_Advanced, "Fejlett");
	strcpy(s_Relative_coordinates, "Relatív koordináták");
	strcpy(s_Absolute_coordinates, "Abszolút koordináták");
	strcpy(s_Append_more_rows, "További sorok hozzáfűzése");

	strcpy(s_Add_to_parts, "Hozzáadás az alkatrészekhez.");
	strcpy(s_Additional, "További");
	strcpy(s_All_results, "Minden eredmény.");
	strcpy(s_Allow_movement_of_pieces, "Engedélyezze a darabok mozgását");
	strcpy(s_Allow_part_in_part, "Engedje darabonként");
	strcpy(s_Invalid_piece_Angles_are_too_small_or_too_big_or_height_is_too_small, "Érvénytelen darab! A szögek túl kicsik vagy túl nagyok, vagy a magasság túl kicsi.");
	strcpy(s_Append, "Hozzáfűzése");
	strcpy(s_As_it_is, "Ahogy van");
	strcpy(s_As_text, "Szövegként");
	strcpy(s_Ascending, "növekvő");
	strcpy(s_Automatic, "Automatikus");
	strcpy(s_Cannot_connect_to_the_Internet_Please_visit_our_website_from_a_browser, "Nem lehet csatlakozni az internethez! Kérjük, látogasson el webhelyünkre egy böngészőből.");
	strcpy(s_Cannot_copy_or_move_the_files, "A fájlokat nem lehet másolni vagy áthelyezni!");
	strcpy(s_Cannot_delete_the_file, "Nem törölhető a fájl!");
	strcpy(s_Cannot_modify_old_results, "A régi eredmények nem módosíthatók!");
	strcpy(s_To_change_click_inside_a_cell_or_press_0_1_or_2, "A módosításhoz kattintson egy cellán belülre, vagy nyomja meg a 0, 1 vagy 2 gombot.");
	strcpy(s_Cell, "Sejt");
	strcpy(s_Click_on_the_table_header_to_change_the_columns, "Kattintson a táblázat fejlécére az oszlopok megváltoztatásához.");
	strcpy(s_Close, "Csukd be");
	strcpy(s_Contact_us, "Lépjen kapcsolatba velünk");
	strcpy(s_Column, "Oszlop");
	strcpy(s_Comma, "Vessző");

	strcpy(s_Copy, "Másolat");
	strcpy(s_Copy_for_move, "Másolás a mozgatáshoz");
	strcpy(s_Cut_higher_level_strips_first, "Először vágja le a magasabb szintű csíkokat");
	strcpy(s_Cut_index, "Megjelenítés index vágási");

	strcpy(s_The_data_have_been_changed_Do_you_want_to_save_them_to_a_file, "Az adatok megváltoztak. Fájlba akarja menteni őket?");
	strcpy(s_Decimal_separator, "Tizedes elválasztó");
	strcpy(s_Restore_default_settings, "Az alapértelmezett beállítások visszaállítása");
	strcpy(s_Delete_fiber, "Törölje a rostot");
	strcpy(s_Descending, "Csökkenő");
	strcpy(s_Discard_changes, "Módosítások elvetése");

	strcpy(s_Delete_all_data, "Törli az összes adatot?");
	strcpy(s_Dot, "Pont");
	strcpy(s_Do_you_want_to_delete_the_picture, "Törli a képet?");
	strcpy(s_Do_you_want_to_delete_the_product, "Törli a terméket?");
	strcpy(s_Duplicate_and_append, "Másolat és melléklet.");
	strcpy(s_Duplicate_values_are_ignored, "Az ismétlődő értékeket figyelmen kívül hagyták!");
	strcpy(s_Error, "Hiba");
	strcpy(s_Error_loading_file, "Hiba történt a fájl betöltésekor.");
	strcpy(s_export_everything, "Exportáljon mindent");
	strcpy(s_Fit_to_screen, "Képernyőhöz igazítva.");
	strcpy(s_Force_fixed_height, "Rajzolja meg a darabokat rögzített magassággal.");
	strcpy(s_Flipped, "Megfordítva");
	strcpy(s_Import, "Import");
	strcpy(s_If_angles_are_different_from_90_degrees_height_must_be_greater_than_0, "Ha a szögek eltérnek 90 foktól, a magasságnak 0-nál nagyobbnak kell lennie.");
	strcpy(s_Ignore, "Mellőz");
	strcpy(s_Incorrect_value, "Helytelen érték");
	strcpy(s_Info, "Info");
	strcpy(s_Interior, "Belül");
	strcpy(s_Give_a_name, "Adj nevet.");
	strcpy(s_Group, "Csoportosítsa");
	strcpy(s_Header, "Fejléc");
	strcpy(s_Keep_it_as_it_is, "Tartsa úgy, ahogy van");
	strcpy(s_Level, "Level");
	strcpy(s_Licensee, "Engedélyes");
	strcpy(s_List_separator, "Lista elválasztó");
	strcpy(s_Made_with_love_in_Cugir_Romania, "Készült, szeretettel, itt: Cugir, Románia");
	strcpy(s_Made_in, "ban gyártva");
	strcpy(s_Manufacturer, "Gyártó");

	strcpy(s_Manual_arrange, "Kézi rendezés");

	strcpy(s_Mixed, "Vegyes");
	strcpy(s_Multiple_shapes_detected_Next_rows_will_be_overwritten_Continue, "Egynél több alakzatot észleltünk. Ezért a következő sorok felülíródnak. Folytatni?");
	strcpy(s_More, "Több");
	strcpy(s_Multiple_values, "Több érték");
	strcpy(s_No_texture, "Nincs textúra");
	strcpy(s_Number, "Szám");
	strcpy(s_Number_of_images, "Képek száma");
	strcpy(s_Number_of_vertices, "Csúcsok száma");
	strcpy(s_Offset, "Offset");
	strcpy(s_Only_the_currently_selected_items, "Csak az aktuálisan kiválasztott elemek.");
	strcpy(s_Optimizing_please_wait, "Optimalizálás... kérem, várjon.");

	strcpy(s_Paste, "Paste");

	strcpy(s_Piece_label, "Mutasd darab címke");
	strcpy(s_Piece_size, "Mutasd a darabok mérete");
	strcpy(s_Please_contact_us_by_email_if_you_receive_this_error, "Kérjük, lépjen velünk kapcsolatba e-mailben, ha ezt a hibát kapja.");
	strcpy(s_Please_save_it_first, "Kérjük, először mentse el.");
	strcpy(s_Position, "Pozíció");
	strcpy(s_Preview, "Előnézet");
	strcpy(s_Rectangle, "Téglalap");

	strcpy(s_Redo_the_last_operation, "Állítsa vissza az utolsó műveletet");
	strcpy(s_Regular_polygon, "Normál sokszög");

	strcpy(s_Reused, "Újra felhasznált");
	strcpy(s_Rotated, "Elforgatott");
	strcpy(s_Save_all, "Összes mentése");
	strcpy(s_Scrap_label, "Mutasd hulladék címke");
	strcpy(s_Scrap_size, "Mutasd mérete hulladékok");
	strcpy(s_Semicolon, "Pontosvessző");
	strcpy(s_Show_cut_index, "Megjelenítés index vágási");
	strcpy(s_Show_information, "Információk megjelenítése");
	strcpy(s_Show_piece_label, "Mutasd darab címke");
	strcpy(s_Show_scrap_label, "Mutasd hulladék címke");
	strcpy(s_Show_scrap_s_size_on_the_small_pieces, "Mutassa be a darabka méretét a kis darabokra");
	strcpy(s_Show_size_of_pieces, "Mutasd a darabok mérete");
	strcpy(s_Show_size_of_scrap, "Mutasd mérete hulladékok");
	strcpy(s_Show_sizes, "Méretek megjelenítése");
	strcpy(s_Show_label, "Címke megjelenítése");
	strcpy(s_Show_length, "Hossza megjelenítése");

	strcpy(s_Some_numerical_values_are_incorrect_Should_I_fix_all_the_incorrect_values, "Néhány numerikus érték helytelen! Javítanom kellene az összes helytelen értéket?");
	strcpy(s_Some_invalid_values_have_been_removed, "Néhány érvénytelen érték eltávolítva.");
	strcpy(s_Sort_by, "Sorrend");
	strcpy(s_Sort_ascending_by, "Rendezés növekvő sorrend szerint");
	strcpy(s_Sort_descending_by, "Rendezés csökkenő szerint");
	strcpy(s_Start, "Start");
	strcpy(s_Starting_angle, "Kiindulási szög");


	strcpy(s_Stock, "Raktar");
	strcpy(s_Stop, "Stop");

	strcpy(s_Tabular, "Táblázatos");
	strcpy(s_Total, "Teljes");
	strcpy(s_Total_size, "Teljes méret");
	strcpy(s_Terms_of_the_license, "A licenc feltételei");
	strcpy(s_The_current_product_has_been_changed_Do_you_want_to_save_it_to_file, "A jelenlegi termék megváltozott. Szeretné fájlba menteni?");
	strcpy(s_The_value_is_out_of_the_allowed_range, "Az érték kívül esik a megengedett tartományon.");
	strcpy(s_The_value_must_be_a_real_or_fractional_number_Try_to_replace_the_comma_with_the_dot_if_you_want_to_enter_a_real_number, "Az értéknek valós vagy tört számnak kell lennie. Ha valódi számot akar beírni, próbáljon cserélni a vesszőt a pontra.");
	strcpy(s_This_feature_is_not_implemented_yet, "Ez a funkció még nincs implementálva.");
	strcpy(s_This_operation_cannot_be_reversed, "Ez a művelet nem vonható vissza.");
	strcpy(s_Undo_the_last_operation, "Visszavonja az utolsó műveletet.");
	strcpy(s_Utilization, "Hasznosítás");
	strcpy(s_Utilized_Stock, "Felhasznált készlet");
	strcpy(s_Version, "Változat");
	strcpy(s_Visible_columns, "Látható oszlopok");
	strcpy(s_You_already_have_the_latest_version_installed, "Már telepítve van a legújabb verzió!");
	strcpy(s_What_is_exported, "Mit exportálnak?");
	strcpy(s0meansanynumberofpieces, "Zero: bármely darabszám");
	strcpy(sAbout, "Körülbelü");
	strcpy(sAccept, "Elfogadom");
	strcpy(sAcceptall, "Elfogad minden");
	strcpy(sAcceptthecurrentsolution, "Fogadja el a jelenlegi megoldás");
	strcpy(sAdd, "Hozzáadás");
	strcpy(sAddapiece, "Adjon hozzá egy darabot");
	strcpy(sAddasimpleproducttoDemand, "Adjon hozzá egy terméket a meglévő alkatrészekhez.");
	strcpy(sAddgrindingthicknesstopartsize, "Hozzáadás köszörülés vastagságú darab méret");
	strcpy(sAddproductnametolabel, "A termék nevét csatolja a címkéhez");
	strcpy(sAddress, "Cím");
	strcpy(sAddselectedsizetoInventory, "A kiválasztott méretet csatolja a készlethez");
	strcpy(sAdhesivelabels, "Öntapadós címkék");
	strcpy(sAdhesivelabelwithinformationaboutpiecesinDemandCustomernameLabelSizeCurrentData, "Öntapadós címke tájékoztatást darab Demand: Megrendel? neve, címke, méret, aktuális adatokról.");
	strcpy(sAdhesivelabelwithinformationaboutsheetsinInventory, "Öntapadós címke tájékoztatást lapok Inventory.");
	strcpy(sAll, "Minden");
	strcpy(sAlloffcutswhichhavethesizegreaterthanthisvaluewillbeaddedtoInventory, "Minden maradék anyagokat, amelyeknek a mérete nagyobb, mint ez az érték bekerül Inventory");
	strcpy(sAllowMirroring, "Engedélyezése tükrözés");
	strcpy(sAllowRotation, "Hagyjuk Rotation");
	strcpy(sAllPieces, "Minden darab");
	strcpy(sAllpredefinedproducts, "Minden előre definiált termék");
	strcpy(sAnewwindowwillbedisplayedwheretheusercansettheedgebandsforeachedge, "Egy új ablak jelenik meg, amelyben a felhasználó állíthatja be a zenekar minden egyes él.");
	strcpy(sAnewwindowwillbedisplayedwheretheusercansetthegrindingvalueforeachedgeofthsheet, "Egy új ablak jelenik meg, amelyben a felhasználó állíthatja be a csiszolás értéket minden egyes éle a darab.");
	strcpy(sAnewwindowwillbedisplayedwheretheusercansetthetrimvalueforeachedgeofthsheet, "Egy új ablak jelenik meg, amelyben a felhasználó állíthatja be a hibák egyes éle a darab.");
	strcpy(sAngle, "Szög");
	strcpy(sAngles, "Szög");
	strcpy(sAnoptimizationparameterisarealnumber, "Az optimalizálás paraméter egy valós szám.");
	strcpy(sAnoptimizationparameterisfractionalnumber, "Az optimalizálás paraméter tört szám.");
	strcpy(sAnyShape, "Bármely alak");
	strcpy(sApolygonmusthaveatleast2vertices, "A sokszögnek legalább 2 csúcsnak kell lennie!");
	strcpy(sApolygonmusthaveatleast3vertices, "A sokszögnek legalább 3 csúcsnak kell lennie!");
	strcpy(sApplication_fails_to_initialize, "A szoftver nem tudott elindulni.");
	strcpy(sArc, "Ív");
	strcpy(sArcLength, "Ívhossz");
	strcpy(sAreaofusedsheets, "Terület használt lapok");
	strcpy(sAshortdescriptionofthesheet, "Egy rövid leírás a lap");
	strcpy(sAtleastonepart, "Legalább egy darab kell bevezetni.");
	strcpy(sAtTheMarginOfTheSheet, "Szélén a lemez");
	strcpy(sBandtypes, "Típusai él zenekart.");
	strcpy(sBar, "Bar / vezetékek");
	strcpy(sBars, "Bars / vezetékek");
	strcpy(sBothsizesoftheoffcutsmustbegreaterthanthisvalue, "Mind mérete vágásmaradékokra nagyobbnak kell lennie, mint ez az érték.");
	strcpy(sBottom, "Alsó");
	strcpy(sBottomcoordinateofthedefect, "Az alsó koordinátája a hiba");
	strcpy(sBreakCut, "Törd meg a vágást");
	strcpy(sBrowse, "böngészik");
	strcpy(sBuy, "Megvesz");
	strcpy(sBuynow, "Vásárlás most ...");
	strcpy(sCancel, "Mégsem ez");
	strcpy(sCannotBeEmpty, "nem lehet üres!");
	strcpy(sCannotmovepartsbetweensheetswhenidenticalsheetsaregroupedPleaseungroupthesheetsfrommenu, "Nem lehet mozgatni az alkatrészeket az egyik lapot a másikra, ha az azonos lapok vannak csoportosítva. Kérjük, törölje az egyesülés a lapok menüből.");
	strcpy(sCannotSaveFile, "Nem lehet menteni a fájlt");
	strcpy(sCenter, "Központ");

	strcpy(sChangeDirection, "A változás irányát");
	strcpy(sChoose, "Válasszon");
	strcpy(sChooseProduct, "Válasszon terméket");
	strcpy(sCircle, "Kör");
	strcpy(sCity, "Város");
	strcpy(sClear, "Töröljük");
	strcpy(sClockWise, "Jobbra");
	strcpy(sClosewindow, "Ablak bezárása");
	strcpy(sColor, "Szín");
	strcpy(sColorofedgeband, "A sáv színe é");
	strcpy(sColorPattern, "Szín / textúra");
	strcpy(sColorpiecesandwastes, "Darab színes és hulladékok.");
	strcpy(sColumns, "Oszlopok");
	strcpy(sComment, "Hozzászólás");
	strcpy(sCompanyname, "Cégnév");
	strcpy(sComplexMaterialExists, "Nevét, az anyag már meg van határozva a listában az összetett anyagok. Kérjük, hogy ez egy új nevet.");
	strcpy(sComputerCode, "Számítógép-kód");
	strcpy(sComputerCodefromyourcomputer, "Számítógép-kód (a számítógépen)");
	strcpy(sComputethetotalpriceofDemand, "Számítsuk ki a teljes árat a kereslet");
	strcpy(sContents, "Tartalom");
	strcpy(sContinutComanda, "Tartalma a kereslet dátum");
	strcpy(sContinutDepozit, "Tartalma a leltár dátum");
	strcpy(sConversionIsDoneOnlyWhenSomePiecesHaveFractionalValues, "Átalakítás történik csak néhány darab van tört értékeket.");
	strcpy(sConvertsTheSizeOfWasteToAFractionalUnit, "Méretét mutatja hulladék tört értéket.");
	strcpy(sCouldNotSaveFile1, "Nem lehet írni a fájlt a könyvtárban");
	strcpy(sCouldNotSaveFile2, "Lehet, hogy nincs elég joga. Kérjük, ellen?rizze, illetve módosítsa az aktuális könyvtárat a Beállítások menü | Munka könyvtár a mappát, ahol van joga írni (például C:\\temp).");
	strcpy(sCreationdateYMDHMS, "Létrehozás dátuma (Y / M / D, H: M: S)");
	strcpy(sCurrentDate, "Aktuális dátum");
	strcpy(sCurrentDiagram, "Jelenlegi ábra");
	strcpy(sCurrentMaterial, "Aktuális anyag");
	strcpy(sCurrentversion, "Jelenlegi verzió");
	strcpy(sCurve_not_closed_Try_increasing_DXF_linking_distance_parameter, "A sokszög nincs bezárva! Próbálja meg növelni a DXF összekötési távolság paramétert.");
	strcpy(sCustomer, "Vevő");
	strcpy(sCustomerName, "Ügyfél neve");
	strcpy(sCustomMessage, "Egyéni üzenet");
	strcpy(sCutlength, "A hossza a vágás");
	strcpy(sCut, "Vágott");
	strcpy(sCuts, "Vágások");
	strcpy(sCutterThickness, "Vágási vastagság");
	strcpy(sData, "Az adatok");
	strcpy(sDataCannotBeEmpty, "Az adatok nem lehetnek üresek!");
	strcpy(sDateymdhms, "Dátum (Y / M / D / h / m / s)");
	strcpy(sDays_left_for_trial, "Nap áll a tesztelésre ");
	strcpy(sDaysLeft, "nap van hátra");
	strcpy(sStandard, "Alapértelmezett");
	strcpy(sDefaultInterface, "Alapértelmezett interfész");
	strcpy(sDefects, "Hibák");
	strcpy(sDefectsManager, "Hibák kezelése");
	strcpy(sDefectsofthematerialNopiecescanbeplacedinthefaultyzone, "Hibák az anyag. Nem darab lehet helyezni a hibás zónát.");
	strcpy(sDelete, "Törö");
	strcpy(sDeletePiece, "Törlés darab");
	strcpy(sDeleteRow, "sor törlése");
	strcpy(sDemandutilization, "Hasznosítása a kereslet");
	strcpy(sDepozitulmodificat, "A felhasznált darabokat eltávolították. A maradványok b?vült az állomány.");
	strcpy(sDepozitvid, "Az állomány üres");
	strcpy(sDesk, "íróaszta");
	strcpy(sDiagram, "Diagram");
	strcpy(sDiagrams, "Diagramok");
	strcpy(sDiagramasatable, "Diagram táblaként");
	strcpy(sDigits, "számjegyek");
	strcpy(sDimensiuniplaca, "Lap méret");
	strcpy(sDirection, "Irányba");
	strcpy(sDistanceBetweenRows, "Sorok közötti távolság");
	strcpy(sDonotuseit, "Ne használd");
	strcpy(sDownload, "Letöltés");
	strcpy(sDoYouWantToClearTheData, "Azt akarod, hogy törli az adatokat?");
	strcpy(sDoYouWantToSaveDemand, "A részek már megváltozott! Meg akarja menteni a változásokat?");
	strcpy(sDoYouWantToSaveParts, "Szeretné menteni a részeket?");
	strcpy(sDoYouWantToSaveRepository, "Az állomány megváltozott! Meg akarja menteni a változásokat?");
	strcpy(sDrawing, "rajzok");
	strcpy(sDrawthesolutioncolorful, "Döntetlen a megoldás színes");
	strcpy(sDuplicateTypes, "Néhány típus megismétlődik! Kérjük, távolítsa el az ismétlődéseket.");
	strcpy(sDuplicateTypesWithComplex, "Néhány név az anyagok már létezik a listában az összetett típusok! Kérjük, távolítsa el az ismétl?déseket");
	strcpy(sDuplicateValues, "Duplikált értékek");
	strcpy(sEdgeband, "Zenekarok esetében élek");
	strcpy(sEdgebandingwhichisplacedontheedgesofyourpiecePleasedefineedgebandingtypesfromMaterialsEdgeBandingmenu, "Élzáró amely helyezett a szélén, a darab. Kérjük, határozza meg, élzáró anyagok típusait a menüben.");
	strcpy(sEdgebandsthatwillbeappliedtoeachpart, "Él zenekarok fogják alkalmazni minden egyes részét.");
	strcpy(sEdgeBandTolerance, "Tolerancia az élzáró");
	strcpy(sEdgesthatmustbecutduefaults, "Élek, hogy el kell vágni hibák miatt.");
	strcpy(sEdgetoedge, "Széltől szélig");
	strcpy(sEdit, "Szerkesztése");
	strcpy(sEmail, "E-mail");
	strcpy(sEmptyData, "Az adatok üres!");
	strcpy(sEnabled, "képessé tesz");
	strcpy(sEnabledisabledefectsoftheinventorysheets, "Engedélyezése / tiltása hibák az állomány");
	strcpy(sEnterLabel, "Input címke");
	strcpy(sEnterTheMaterialName, "Adja meg a nevét, az anyag");
	strcpy(sEnterTheProductName, "Írja be a nevét, a termék");
	strcpy(sEvaluationError, "Hiba, hogy a kifejezés értékelés!");
	strcpy(sExit, "Kilépés");
	strcpy(sExpired, "A szoftver lejárt! Kérjük, regisztráljon a szoftvert!");
	strcpy(sExport, "Export");
	strcpy(sExportAllDiagrams, "Exportálja az összes ábrát");
	strcpy(sExportAllToASingleFile, "Az összes exportálása egyetlen fájlba");
	strcpy(sExportOptions, "Export lehetőségeket.");
	strcpy(sExporttoDXFformat, "Exportálás DXF formátumba");
	strcpy(sExporttoExcel, "Exportálás Excel");
	strcpy(sExpresieIncorecta, "Hibás matematikai kifejezést!");
	strcpy(sExtensions, "Extensions");
	strcpy(sExtra, "Extra");
	strcpy(sExtraComponents, "Extra alkatrészek");
	strcpy(sExtracomponentsattachedtoDemand, "Extra alkatrészek csatolt részek");
	strcpy(sFile, "Fáj");
	strcpy(sFileName, "Fájlnév");
	strcpy(sFillWastes, "Döntetlen hulladék ferde");
	strcpy(sFindoptimalbarsheetsize, "Keresse meg a rudak és lapok optimális méretét.");
	strcpy(sFindoptimalsizeofInventorypieces, "Keresse meg a készlet optimális méretét");
	strcpy(sFirstcutMultiplestages, "Első vágási irány a többfokozatú optimalizáláshoz.");
	strcpy(sFirstdirectionforcutishorizontal, "Az első vágási irány vízszintes.");
	strcpy(sFirstdirectionforcutisvertical, "Az első vágási irány függőleges.");
	strcpy(sFollowthecontourofpieces, "Kövesse a kontúrt a darabok");
	strcpy(sFont, "Betűtípus");
	strcpy(sFontsize, "Betűméret");
	strcpy(sFullInfo, "Teljes információ");
	strcpy(sDisposedWaste, "निस्तारित कचरा");
	strcpy(sGeneral, "Tábornok");
	strcpy(sGenerateCNC, "Generálása CNC");
	strcpy(sGrain, "Rost");
	strcpy(sGraindirection, "Rost irány");
	strcpy(sGraphic, "Grafikus");
	strcpy(sGreaterorequalto, "Nagyobb vagy egyenl?");
	strcpy(sGrid, "asztalok ");
	strcpy(sGrinding, "köszörülés vastagság");
	strcpy(sGrosimeTaieturaScalata, "A vágás vastagság kép eltérhet az igazit, mert a darabokat nem képviseltette magát a valós mértékét. Ez a tény nem befolyásolja az eredményeket.");
	strcpy(sGroupidenticallayouts, "Csoportosítása azonos lapok");
	strcpy(sGroupIdenticalParts, "Azonos alkatrészek csoportosítva.");
	strcpy(sGroupingOfIdenticalPiecesIntoOneRow, "Csoportosítása azonos darabokat egy sorban.");
	strcpy(sGroupPartsAfterLoadingFromFile, "Csoportosítása a részek betöltése után fájlbó");
	strcpy(sHeight, "Magasság");
	strcpy(sHeighttolerance, "Tolerancia a magasság");
	strcpy(sHelp, "Segítség");
	strcpy(sHistory, "Történelem");
	strcpy(sHorizontal, "Vízszintes");
	strcpy(sHowtodisplayprintedgebands, "Hogyan jeleníti széle zenekarok?");
	strcpy(sIfyousetthebandforoneedgeallwillreceivethesamevalue, "Ha beállítja a zenekar egyik szélén, mindenki megkapja ugyanazt az értéket.");
	strcpy(sIfyousetthegrindingforoneedgeallwillreceivethesamevalue, "Ha a csiszolás értéket egyik szélén, az összes élek megkapja ugyanazt az értéket.");
	strcpy(sIfyousetthetrimforoneedgeallwillreceivethesamevalue, "Ha a vágás egy él, az összes élek megkapja ugyanazt az értéket.");
	strcpy(sImageBounds, "Bounds a kép");
	strcpy(sImageSize, "Képméretet");
	strcpy(sImportData, "Importálja az adatokat.");
	strcpy(sIncorrectPassword, "Hibás jelszó");
	strcpy(sIndex, "Index");
	strcpy(sInformationaboutcustomer, "Információ ügyfé");
	strcpy(sInputALanguageName, "Adj nevet a nyelv");
	strcpy(sInsert, "Helyezze");
	strcpy(sInsertPiece, "Helyezze darab");
	strcpy(sInterface, "Felület");
	strcpy(sInterfaceSettings, "Interfész beállítások");
	strcpy(sInvalidHardware, "Nem tudtam felismerni a hardvert. Kérjük, vegye fel velünk a contact@optimalprograms.com");
	strcpy(sInvalidNumber, "Érvénytelen szám");
	strcpy(sInvalidOrderOfComputation, "A megrendelés kiszámoló hossza nem állapítható meg. Vannak körkörös kapcsolatok az érintett termék fogalmába!");
	strcpy(sInvalidRegistration, "A regisztráció érvénytelen!");
	strcpy(sInvalidTime, "A rendszer ideje érvénytelen.");
	strcpy(sInventory, "RAKTÁR");
	strcpy(sisafractionalvalue, "egy relatív érték.");
	strcpy(sIsArc, "Az arc");
	strcpy(sisarealvalue, "egy igazi érték.");
	strcpy(sLabel, "Címke");
	strcpy(sLabels, "Címkék");
	strcpy(sLanguage, "Nyelv");
	strcpy(sLatimeanumar0, "A szélesség nagyobbnak kell lennie 0-nál!");
	strcpy(sLatimeanumarreal, "A szélesség legyen valós szám!");
	strcpy(sLayerName, "Réteg neve");
	strcpy(sLeft, "Ba");
	strcpy(sLeftcoordinateofthedefect, "A bal oldali koordináta a hiba");
	strcpy(sLength, "Hossz");
	strcpy(sLengthofthepiecestocut, "Darab méret vágására");
	strcpy(sLengthofthepiecestocutfrom, "Lapméret vágására");
	strcpy(sLengthofusedbars, "Méret használt rudak");
	strcpy(sLicenseAgreement, "licencszerződés");
	strcpy(sLinear, "Lineáris");
	strcpy(sLinethickness, "Vastagsága tol");
	strcpy(sLoadafileandappenddatatothecurrentDemand, "Töltsön be egy fájlt, és csatolja az adatokat az aktuális részekhez.");
	strcpy(sLoadanexistingDemandfromafile, "Töltse be a meglévő alkatrészeket egy fájlból.");
	strcpy(sLoadAppend, "Betöltés és csatolás");
	strcpy(sLoadEverything, "Load mindent");
	strcpy(sLoadInventory, "Betöltése az állomány");
	strcpy(sLoadInventoryandDemand, "Betöltése az állomány és a kereslet");
	strcpy(sLoadResults, "Töltse be az eredményt");
	strcpy(sLocked, "zárt");
	strcpy(sLogo, "Logo");
	strcpy(sLong, "Hosszú");
	strcpy(sLongerexecutiontime, "Hosszú ideig futhatnak");
	strcpy(sLungime, "Szélesség");
	strcpy(sLungimeanumar0, "A hossz nagyobbnak kell lennie 0-nál!");
	strcpy(sLungimeanumarreal, "A hosszúnak kell lennie egy igazi szám!");
	strcpy(sLungimeaTotalaFolosita, "Hasznosítású összes hossza");
	strcpy(sMagnification, "Nagyítás");
	strcpy(sMagnify, "Nagyítás");
	strcpy(sMargins, "Margók");
	strcpy(sMarginsForPaper, "Margók papír");
	strcpy(sMarginsOfTheLabel, "Margók A címke");
	strcpy(sMaterial, "Anyag");
	strcpy(sMaterialName, "Az anyag neve");
	strcpy(sMaterials, "anyagok");
	strcpy(sMaterialstypes, "Anyagtípusok");
	strcpy(sMax, "Max");
	strcpy(sMaximalArea, "Maximális terület");
	strcpy(sMaximalCutLength, "Maximális vágási hossz");
	strcpy(sMaxlength, "Maximális hossz");
	strcpy(sMaxPiecesperBar, "Max Darabok per Bar");
	strcpy(sMaxwidth, "Maximális szélesség.");
	strcpy(sMeasurementUnit, "Mértékegység");
	strcpy(sMin, "My");
	strcpy(sMinimalBreakSize, "Minimális szünetméret");
	strcpy(sMinimalUsefulSize, "Minimális hasznos méret");
	strcpy(sMinimalwastesizetoInventory, "Minimális hulladék mérete Inventory");
	strcpy(s_What_to_minimize, "Mit kell minimalizálni?");
	strcpy(sMinlength, "Minimális hossz");
	strcpy(sMinwidth, "Minimális szélesség");
	strcpy(sMirror, "Tükör");
	strcpy(sMirroring, "Tükrözése");
	strcpy(sMiscellaneous, "Vegyes");
	strcpy(sModify, "Módosítása");
	strcpy(sModifytheselectedpiece, "Módosíthatja a kiválasztott darab");
	strcpy(sMovePiece, "Mozogni darab.");
	strcpy(sMultiplestages, "Több szakaszban");
	strcpy(sName, "Név");
	strcpy(sNameofedgeband, "Neve él zenekarok");
	strcpy(sNewDEMANDUnsaveddatawillbelost, "Új alkatrész? A nem mentett adatok elvesznek!");
	strcpy(sNewLanguage, "Új nyelv");
	strcpy(sNewMaterial, "Új anyag");
	strcpy(sNewPasswordincorectlyintroduced, "Új jelszó helytelenül vezetett!");
	strcpy(sNewProduct, "Új termék");
	strcpy(sNewversion, "Új verzió");
	strcpy(sNo, "Nincs");
	strcpy(sNumarBucati, "Darabszám");
	strcpy(sNumberOfCopies, "Másolatok száma");
	strcpy(sNumberofstages, "A fokozatok száma");
	strcpy(sNusuficienteplacidepozit, "Nem minden darab lettek optimalizálva. Lehetséges okok: Nincs elegendő darab raktáron, Piece nem használt optimalizálás; származó anyagok Demand és Készletezési nem illeszkedik; Egyéb paraméterek is rosszul van beállítva.");
	strcpy(sOfficeNotInstaled, "A Microsoft Office nincs telepítve a számítógépére, vagy egy incorect verzió van telepítve!");
	strcpy(sOldpassworddoesnotmatch, "Régi jelszó nem egyezik!");
	strcpy(sOnlinehelp, "Online segítség");
	strcpy(sOnlypiecesofthesameheightinthelaststage, "Darab azonos magasságú utolsó szakaszában");
	strcpy(sOpen, "Nyitva");
	strcpy(sOptimization, "Optimalizálás");
	strcpy(sOptimizationDone, "Optimalizálás végzett! Lehet, kinyomtathatja vagy mentheti a kapott diagramok. Nyomja meg a gombot, ha fogadni elégedett a jelenlegi megoldás. Ellenkez? esetben nyomja meg ismét a Start gombot.");
	strcpy(sOptimizationType, "Típusa optimalizálás");
	strcpy(sOptions, "Opciók");
	strcpy(sOptionsrelatedtotheinterface, "Kapcsolatos opciók a felület");
	strcpy(sor, "vagy");
	strcpy(sOthercomponents, "Egyéb alkatrészek");
	strcpy(sOthers, "Egyéb");
	strcpy(sOtherstatistics, "Egyéb statisztikák");
	strcpy(sOverrideExcelCSVfiles, "Felülbírálása Excel / CSV fájlok");
	strcpy(sParameter, "Paraméter");
	strcpy(sParts, "ALKATRÉSZEK");
	strcpy(sPattern, "Minta");
	strcpy(sPatternforwaste, "Minta a hulladék");
	strcpy(sPerimeter, "Kerület");
	strcpy(sPermitedRotationAngle, "A megengedett elfordulási szög.");
	strcpy(sPhone, "Telefon");
	strcpy(sPicture, "Kép");
	strcpy(sPiece, "Darab");
	strcpy(sPieceindex, "Darab index");
	strcpy(sPieces, "Darabok");
	strcpy(sPiecesize, "Darab méret");
	strcpy(sPiecesizelabeledgebandwillbeprinted, "Darab méret, címke, EDGE zenekarok kerül kiírásra.");
	strcpy(sPierdere, "Hulladék");
	strcpy(sPixels, "pixe");
	strcpy(sPlacilefolositeDepozit, "Hasznosított darabjait a leltár.");
	strcpy(sPlease_contact_us_at_contact_nestingtechnologies_com, "Kérjük, vegye fel velünk a contact@nesting-technologies.com");
	strcpy(sPlease_contact_us_at_contact_optimalprograms_com, "Kérjük, vegye fel velünk a contact@optimalprograms.com");
	strcpy(sPleaseenteralldataeitherasfractionalorrealDonotmixthem, "Kérem, adja meg adatait akár tört vagy igazi! Ne keverje meg őket!");
	strcpy(sPleaseEnterSomeTypesOfMaterials, "Nincs meghatározva semmilyen típusú anyag. Az Anyagok menüben definiálhatja őket.");
	strcpy(sPleasesendtheNameandtheCodetotheaddresscontactoptimalprogramscominordertoobtaintheRegistrationKey, "Annak érdekében, hogy a regisztrációs kulcsot, kérjük küldje el a neve és a Kód: contact@optimalprograms.com.");
	strcpy(sPolygon, "Poligon");
	strcpy(sPolygonsCircles, "Sokszögek, körök");
	strcpy(sPrecision, "Pontosság");
	strcpy(sPretulnumar0, "Az ár nagyobbnak kell lennie 0-nál!");
	strcpy(sPretulnumarreal, "Az ár kell lennie egy igazi szám!");
	strcpy(sPreview, "Előnézet");
	strcpy(sPrice, "Ár");
	strcpy(sPriceMustBeGreaterThanZero, "Ár nagyobbnak kell lennie, mint nulla");
	strcpy(sPriceofbars, "Ár bárok");
	strcpy(sPriceperbar, "Ár bar");
	strcpy(sPricepersheet, "Ár laponként");
	strcpy(sPricepersquareunitofmaterial, "Ár négyzetméterenkénti egységnyi anyag.");
	strcpy(sPriceperunit, "Egységár");
	strcpy(sPrint, "Nyomtatás");
	strcpy(sPrintdiagramsastables, "Nyomtassa diagramok táblázatos formában.");
	strcpy(sPrinter, "Nyomtató");
	strcpy(sPrinterBounds, "Margó a nyomtató");
	strcpy(sPrinting, "Nyomtatás");
	strcpy(sPrintonlyutilizedarea, "Nyomtatása csak a hasznosított terület");
	strcpy(sPrintthecontentsoftheDemand, "Nyomtassa ki a tartalmát a kereslet.");
	strcpy(sPrintthecontentsoftheInventory, "Nyomtassa ki a tartalmát az állomány.");
	strcpy(sPrintthecurrentsolution, "Nyomtassa ki a jelenlegi megoldás.");
	strcpy(sPriority, "Prioritás");
	strcpy(sPrioritytocutapieceZero0isthehighestpriority, "Prioritás vágni egy darabot. Nulla (0) a legnagyobb prioritást.");
	strcpy(sProcentul0100, "A százalékoknak nagyobbnak kell lenniük 0-nál, és kisebbnek vagy egyenlőnek kell lenniük 100-zal!");
	strcpy(sProcentulnumarreal, "A százalékot kell lennie egy igazi szám!");
	strcpy(sProductdefinition, "A termék meghatározása");
	strcpy(sProductExists, "A termék már létezik. Válasszon egy másik nevet.");
	strcpy(sProductName, "A termék neve");
	strcpy(sProducts, "Termék");
	strcpy(sProducts, "Termékek");
	strcpy(sProject, "Projekt");
	strcpy(sProperties, "tulajdonságok");
	strcpy(sProperty, "ingatlan");
	strcpy(sQuantity, "Mennyiség");
	strcpy(sQuantitynumberofsheetsofthistype, "Lapok száma az ilyen típusú");
	strcpy(sRadius, "Rádiusz");
	strcpy(sRectangular, "Szögletes");
	strcpy(sRedefinetypesofedgeband, "Újradefiniálása típusú sáv szélén");
	strcpy(sRedefinetypesofmaterial, "Újradefiniálása anyagra");
	strcpy(sRegistration, "Bejegyzés");
	strcpy(sRegistrationKeyfromOptimalPrograms, "Regisztrációs kulcsot");
	strcpy(sRegistrationSuccessful, "Regisztráció sikeres!");
	strcpy(sRemoveallpiecesinInventory, "Vegye ki az összes darabot a leltár.");
	strcpy(sRemoveCut, "Törlés vágott");
	strcpy(sRemovetheselectedpiece, "Távolítsuk el a kiválasztott darab");
	strcpy(sReports, "Jelentések");
	strcpy(sRequestedMaterial, "A kért anyag");
	strcpy(sRestore, "Visszaállítása");
	strcpy(sResults, "Eredmények");
	strcpy(sReusedwaste, "Újrafelhasznált hulladék");
	strcpy(sRight, "Jobb");
	strcpy(sRightcoordinateofthedefect, "Koordinátái a hiba jobbró");
	strcpy(sRotation, "Forgás");
	strcpy(sRotationAngle, "Forgatási szög");
	strcpy(sRotationStep, "Rotation lépést");
	strcpy(sRoundAllFractionsTo, "A tört számokra kell kerekíteni");
	strcpy(sRow, "sor");
	strcpy(sRows, "Sorok");
	strcpy(sRun, "Legújabb megoldások");
	strcpy(sRunningtime, "Futási idő");
	strcpy(sSameforall, "Ugyanaz minden");
	strcpy(sSave, "Kivéve");
	strcpy(sSaveAllImages, "Az összes kép mentése");
	strcpy(sSaveAs, "Mentés másként");
	strcpy(sSaveChanges, "A kereslet már megváltozott. Szeretné menteni?");
	strcpy(sSaveCurrentImage, "Kép mentése Aktuális");
	strcpy(sSavedataparameters, "Mentse adatok és paraméterek");
	strcpy(sSaveEverything, "Mentés mindent");
	strcpy(sSaveInventory, "Készlet mentése");
	strcpy(sSaveInventoryandDemand, "Mentse Inventory és a kereslet");
	strcpy(sSaveResults, "Eredmény mentése");
	strcpy(sSaveStatisticsinafile, "Mentse statisztikák egy fájlban");
	strcpy(sSavethecurrentimage, "A jelenlegi kép mentéséhez");
	strcpy(sSavethecurrentimageorstatistic, "Mentse az aktuális kép vagy statisztika");
	strcpy(sSavetheDEMANDinafile, "Mentés fájlba");
	strcpy(sSavetheDemandinafilewithadifferentname, "Mentse el a kereslet egy fájlt egy másik nevet.");
	strcpy(sSavetheREPOSITORYinafile, "Az adattár mentése egy fájlban");
	strcpy(sSerialNumber, "Regisztrációs kulcs");
	strcpy(sService, "szolgáltatás");
	strcpy(sSetDefaultValues, "Ez visszaállítja az összes paramétert a gyári értékre. Minden beállítás elvész. Biztos benne, hogy ezt szeretné?");
	strcpy(sSetedgeband, "Állítsa sáv szélén");
	strcpy(sSetedgetrim, "Állítsa be a vágás hibáit élek");
	strcpy(sSetthesameedgebandforalledges, "Állítsa be ugyanazt a zenekar minden szélén élek");
	strcpy(sSetthesamegrindingforalledges, "Állítsa be ugyanazt a csiszolás minden élek");
	strcpy(sSetthesametrimforalledges, "Állítsa be ugyanazt a vágási hibák minden élek");
	strcpy(sSettings, "Beállítások");
	strcpy(sShape, "Alak");
	strcpy(sSheet, "Lap");
	strcpy(sSheetsBarstypes, "Lapok_csövek típusai");
	strcpy(sSheetSize, "Lap méret");
	strcpy(sSheetsperPage, "Lapok laponként");
	strcpy(sShort, "Rövid");
	strcpy(sShorterexecutiontime, "Rövid futási idő");
	strcpy(sShowallsimpleproducts, "Az összes egyszerű termék megjelenítése");
	strcpy(sShowcustomername, "Mutasd ügyfél neve");
	strcpy(sShowCustomTextOnEachPiece, "Megjelenítés Egyéni szöveg minden darab");
	strcpy(sShowdiagramasatable, "Megjelenítés diagram, mint egy asztal.");
	strcpy(sShowedgeband, "Mutasd szélén zenekarok");
	strcpy(sShowedgebandssettinginanewwindow, "Megmutatja a beállításokat az él zenekar egy új ablakban");
	strcpy(sShowgrindingsettingsinanewwindow, "Megmutatja őrlés beállításokat egy új ablakban");
	strcpy(sShowHorizontalLabelsAlways, "Megjelenítés mindig vízszintes címkék");
	strcpy(sShowRemovethesizeofthepiecesinthecurrentsolution, "Mutasd / eltávolítása a méret a darabokat a jelenlegi megoldás.");
	strcpy(sShowRemovethesizeofthewastesinthecurrentsolution, "Mutasd / eltávolítása a méret a hulladékok a jelenlegi megoldás.");
	strcpy(sShowtotalcutlength, "Mutasd teljes vágási hossz");
	strcpy(sShowtrimedgesettingsinanewwindow, "Megmutatja a beállításokat a hibák egy új ablakban");
	strcpy(sSimpleMaterialExists, "Az anyag neve már meghatározott anyagok listáját. Kérjük, hogy ez egy új nevet.");
	strcpy(sSinglePieceStrips, "Stripes egy darab");
	strcpy(sSizes, "Méretek");
	strcpy(sSmallerorequalto, "A hulladéknak kisebbnek vagy egyenlőnek kell lennie");
	strcpy(sSort, "Rendez");
	strcpy(sSortAscendingByArea, "Rendezés növekvő területenként");
	strcpy(sSortDescendingByArea, "Rendezés csökkenő területenként");
	strcpy(sSpecifyhowdifferentthepiecesinthelaststagecanbeValue0meansnodifference, "Adja meg, mennyire különbözhetnek egymástól az utolsó szakasz darabjai. A 0 érték azt jelenti, hogy minden darabnak azonos méretűnek kell lennie.");
	strcpy(sSpecifyifpiecesinthelaststagecanbedifferentornotdepeultimaetapapotfidiferitesaunucadimensiune, "Adja meg, hogy az utolsó szakasz darabjai eltérhetnek-e vagy sem");
	strcpy(sSpecifyifthepiececanberotatedornotIfnotitwillbecutinthesamewayasitwasintroducedinDemandLengthofthepieceparalleltothelengthofthesheet, "Adja meg a darab lehet forgatni, vagy sem. Ha nem, akkor kell vágni, ugyanúgy, mint vezették a kereslet (a hossza a darab párhuzamosan a hossza a lap),");
	strcpy(sSpecifyinhowmanystageswemakethecutsDuringastageallcutshavethesamedirection, "Határozza meg, hogy hány szakaszban tesszük a vágások.");
	strcpy(sStartthesearchprocess, "Indítsa el a keresési folyamat");
	strcpy(sStatistics, "Statisztika");
	strcpy(sStatisticsE, "Jelentések Extra");
	strcpy(sStatisticsforeachtypeofmaterial, "Statisztika az egyes anyagfajták");
	strcpy(sStep, "Lépés");
	strcpy(sStergeDepozit, "Törölni szeretné a leltár?");
	strcpy(sStergeMaterial, "Törlés anyagot?");
	strcpy(sStergePiesele, "Törölni szeretné a darabot?");
	strcpy(sStergePiesa, "Törölni szeretné a darabot?");
	strcpy(sStopthesearchprocess, "Állítsa meg a keresési folyamat");
	strcpy(sStrongoptimization, "Erős optimalizálás");
	strcpy(sSubtractthebandthicknessfrompiecesize, "Csökkentse a darab méretét a sávok vastagsága");
	strcpy(sSummary, "összegzés");
	strcpy(sSuprafataTotalaFolosita, "Összes felhasznált terület");
	strcpy(sSuprafatautilizata, "Hasznosítás");
	strcpy(sSwitchbetweenfiberandrotationoption, "Váltás a rost és forgatás lehetőséget.");
	strcpy(sTechnical, "Műszaki");
	strcpy(sTechnicalsettings, "Műszaki beállítások");
	strcpy(sTemporaryPanelHint, "Ideiglenes panel a mozgó alkatrészek között lapokat.");
	strcpy(sText, "Szöveg");
	strcpy(sThe_application_has_expired, "A program lejárt.");
	strcpy(sThe_application_is_not_registered, "A szoftver nem regisztrált.");
	strcpy(sThe_application_was_first_started_on, "A szoftver először indult.");
	strcpy(sThecutsareperformedfromasidetotheothersideofthematerial, "A terhelési végzik egy oldalról a másik oldalra az anyag.");
	strcpy(sThecuttingmachinecanfollowtheshapeofthematerial, "A vágógép képes követni az alak a darab.");
	strcpy(sTheedgesofsheetsthatmustbetrimedduefaults, "A lapok széleit, hogy meg kell faragni, mert a hibák");
	strcpy(sTheLargestSize, "A legnagyobb méretű");
	strcpy(sThenameofthecustomerforwhichyoucutthepiece, "A név az ügyfél számára, amely megvágta a darab.");
	strcpy(sThenameofyourcustomer, "Az ügyfél neve");
	strcpy(sThepiececanberotated, "A darab lehet forgatni");
	strcpy(sTheprogramtriestoavoidwasteswhichhavebothsizeslessthanthisvalue, "A program megpróbálja elkerülni az ennél kisebb selejtezést.");
	strcpy(sThereAreNoProducts, "Nincs meghatározott termékeket még");
	strcpy(sThestockofmaterialhasbeenpreviouslyloadedfromanExcelorCSVformatPleaseloaditagain, "Az állomány anyag korábban betöltött egy Excel vagy CSV formátumban. Kérjük, töltse be újra, ha akarsz dolgozni rajta.");
	strcpy(sThetotallengthofcutting, "A teljes vágási hossz");
	strcpy(sThewidthofthecuttingsawForglasscuttingoptimizationitcanbe0Forwooditshouldbegreaterthan0, "A vágófűrész vastagsága. Üvegvágáskor 0 lehet. Fa vágásakor nagyobbnak kell lennie, mint 0.");
	strcpy(sThewidthofthecuttingsawforlinearpieces, "A fűrész vastagsága lineáris darabokhoz.");
	strcpy(sThickness, "Vastagság");
	strcpy(sThischaracterisusedforfillingthewasterectanglesIfyoudonotwantfilledwastejustremovethischaracter, "Ez a jel feltöltésére használt a hulladék téglalapok. Ha nem szeretné kitölteni hulladékot csak eltávolítani.");
	strcpy(sThisindexhasvaluebetween1andthenumberofpieces, "Ez az index értéke 1 és a darabszám.");
	strcpy(sThisOptionWillOverrideTheInventoryFileIfLoadedFromExcelOrCsvFiles, "Ez az opció felülírja a fájlt, ha leltár betöltött Excel vagy CSV fájlokat.");
	strcpy(sThisProgramisLicensedTo, "Ez a program engedéllye");
	strcpy(sThisvaluewillbeaddedtotheedgebandingmaterialoneachside, "Ez az érték bekerül az élzáró anyag mindkét oldalon");
	strcpy(sTipNevid, "Az anyag típusa nem lehet üres.");
	strcpy(sTitle, "Címet");
	strcpy(sTools, "Eszközök");
	strcpy(sTop, "Felül");
	strcpy(sTopcoordinateofthedefect, "A hiba felső koordinátája.");
	strcpy(sTotalGarbageWaste, "Minden eldobott hulladékot");
	strcpy(sTotalInventoryWaste, "Teljes állomány hulladék");
	strcpy(sTotalRecycledWaste, "Minden újrahasznosított hulladék");
	strcpy(sTotalusedarea, "Összes felhasznált terület");
	strcpy(sTotalusedlength, "Összes felhasznált hossz");
	strcpy(sTrigonometric, "Trigonometrikus");
	strcpy(sTrim, "Vágja");
	strcpy(sTrimalledgesatthebeginning, "Vágja le a széleit az elején");
	strcpy(sTrimEdge, "Vágja le a széle");
	strcpy(sTwoPanels, "2 lemez");
	strcpy(sType, "típus");
	strcpy(sTypeofmaterialfromwhichtocut, "Az anyag típusa, ahonnan vágni");
	strcpy(sTypesAreNotMatched, "Az optimalizálást nem hajtották végre! Jelenleg nincs ilyen anyag a készletben! Darabokat lehet vágni azonos anyagú lapokból. Módosítson néhány anyagot a megfelelő oszlopból.");
	strcpy(sUndo, "Visszavonás");
	strcpy(sUndoAccept, "Visszavonás elfogadása");
	strcpy(sUnits, "egységek");
	strcpy(sUnregisteredVersion, "Nem regisztrált");
	strcpy(sUpdates, "Frissítés");
	strcpy(sUsefulforwoodfurniture, "Hasznos fa bútorok");
	strcpy(sUseit, "Használd");
	strcpy(sUsePieceinOptimization, "Használja a darab optimalizálási");
	strcpy(sUserName, "Felhasználónév");
	strcpy(sUtilizationandWastes, "Hasznosítás és hulladékok");
	strcpy(sUtilizedArea, "Hasznosított terület részei");
	strcpy(sUtilizedBars, "Igénybevett bárok");
	strcpy(sUtilizeddemandcount, "Száma használt darab.");
	strcpy(sUtilizedParts, "Felhasznált alkatrészek");
	strcpy(sUtilizedPieces, "Hasznosított darab");
	strcpy(sUtilizedSheets, "Igénybevett lapok");
	strcpy(sValue, "Érték");
	strcpy(sValueGreaterEqualToZero, "Az értéknek nagyobbnak vagy nullának kell lennie");
	strcpy(sValueGreaterThanZero, "Érték nagyobbnak kell lennie nulláná");
	strcpy(sValueIntegerNumber, "Az értéknek egész számnak kell lennie!");
	strcpy(sValueRealNumber, "Értéket kell valós szám. Talán eddig használt helyett. vagy fordítva. Kérjük, javítsa ki!");
	strcpy(s_The_number_is_too_big_or_it_has_too_many_digits_after_decimal_separator, "A szám túl nagy, vagy túl sok számjegy van a decimális elválasztó után!");
	strcpy(s_The_number_is_too_big, "A szám túl nagy!");
	strcpy(sVertical, "Függőleges");
	strcpy(sWaste, "Hulladék");
	strcpy(sWastes, "Hulladék");
	strcpy(sWasteAddedToWarehouse, "Fémhulladék hozzá raktár");
	strcpy(sWastelimits, "határértékeket hulladék");
	strcpy(sWasteType, "A hulladék típusa");
	strcpy(sWeakoptimization, "A leggyengébb optimalizálás");
	strcpy(sWhattoprint, "Mit kell nyomtatni");
	strcpy(s_What_to_print_or_save_to_file, "Mit kell nyomtatni vagy fájlba menteni");
	strcpy(sWhattoprintoneachpiece, "Mit kíván nyomtatni egy darab");
	strcpy(sWhattoshowoneachpiece, "Mit mutat, minden darab?");
	strcpy(sWidth, "Szélesség");
	strcpy(sWood, "erdő");
	strcpy(sWorkingDirectory, "Munka könyvtár");
	strcpy(sWrongKey, "Rossz regisztrációs kulcsot!");
	strcpy(sYes, "Igen");
	strcpy(sYoucannotchooseblackblueorredcolors, "You cannot choose black, blue or red colors.");
	strcpy(sYouCannotMixFractionalDataWithDecimalOnes, "Nem lehet összekeverni tört értékek valós értékek!");
	strcpy(sYourcompany, "Az Ön vállalata");
	strcpy(sZip, "Irányítószám");
	strcpy(s_Set_the_origin_and_the_direction_of_the_axes, "Állítsa be a koordinátatengelyek origóját és irányát.");

}
