// Language strings: Spanish
// Author: Optimal Programs
// License: MIT License
//---------------------------------------------------------------------------
#include <string.h>
//---------------------------------------------------------------------------
#include "language_string_id.h"
//---------------------------------------------------------------------------
void set_es(void)
{
	// Spanish
	// checked manually with GT
	// last update on: 2025.11.01.0
	
	strcpy(s_Area, "Área");
	strcpy(s_Mass, "Masa");
	strcpy(s_Advanced, "Avanzada");
	strcpy(s_Relative_coordinates, "Coordenadas relativas");
	strcpy(s_Absolute_coordinates, "Coordenadas absolutas");
	strcpy(s_Append_more_rows, "Agregar más filas");
	strcpy(s_Append_to_stock, "Agregar al stock.");
	strcpy(s_Add_to_parts, "Agregar a las partes.");
	strcpy(s_Additional, "Adicional");
	strcpy(s_All_results, "Todos los resultados.");
	strcpy(s_Allow_movement_of_pieces, "Permitir el movimiento de piezas");
	strcpy(s_Allow_part_in_part, "Permitir parte en parte");
	strcpy(s_Invalid_piece_Angles_are_too_small_or_too_big_or_height_is_too_small, "¡Pieza no válida! Los ángulos son demasiado pequeños o demasiado grandes, o la altura es demasiado pequeña.");
	strcpy(s_Append, "Adjuntar");
	strcpy(s_As_it_is, "Como están las cosas");
	strcpy(s_As_text, "como texto");
	strcpy(s_Ascending, "Ascendente");
	strcpy(s_Automatic, "Automática");
	strcpy(s_Cannot_connect_to_the_Internet_Please_visit_our_website_from_a_browser, "¡No se puede conectar a Internet! Visite nuestro sitio web desde un navegador.");
	strcpy(s_Cannot_copy_or_move_the_files, "¡No se pueden copiar ni mover los archivos!");
	strcpy(s_Cannot_delete_the_file, "¡No se puede borrar el archivo!");
	strcpy(s_Cannot_modify_old_results, "¡No se pueden modificar resultados antiguos!");
	strcpy(s_To_change_click_inside_a_cell_or_press_0_1_or_2, "Para cambiar, haga clic dentro de una celda o presione 0, 1 o 2.");
	strcpy(s_Cell, "Celúla");
	strcpy(s_Click_on_the_table_header_to_change_the_columns, "Haga clic en el encabezado de la tabla para cambiar las columnas.");
	strcpy(s_Close, "Cierralo");
	strcpy(s_Contact_us, "Contacta con nosotras");
	strcpy(s_Column, "Columna");
	strcpy(s_Comma, "Coma");
	strcpy(s_The_comma_symbol_cannot_simultaneously_be_the_list_separator_and_the_decimal_separator, "¡El símbolo de coma no puede ser simultáneamente separador de lista y separador decimal!");
	strcpy(s_Copy, "Copiar");
	strcpy(s_Copy_for_move, "Copiar para mover");
	strcpy(s_Cut_higher_level_strips_first, "Corte primero las tiras de nivel superior");
	strcpy(s_Cut_index, "índice de corte");
	strcpy(s_Cuts_may_overlap, "Los cortes pueden superponerse");
	strcpy(s_The_data_have_been_changed_Do_you_want_to_save_them_to_a_file, "Se han modificado los datos. ¿Quieres guardarlos en un archivo?");
	strcpy(s_Decimal_separator, "Separador decimal");
	strcpy(s_Restore_default_settings, "Restaurar la configuración predeterminada");
	strcpy(s_Delete_fiber, "Eliminar fibra");
	strcpy(s_Descending, "Descendente");
	strcpy(s_Discard_changes, "Descartar los cambios");

	strcpy(s_Delete_all_data, "¿Borrar todos los datos?");
	strcpy(s_Dot, "Punto");
	strcpy(s_Do_you_want_to_delete_the_picture, "¿Quieres borrar la imagen?");
	strcpy(s_Do_you_want_to_delete_the_product, "¿Quieres eliminar el producto?");
	strcpy(s_Duplicate_and_append, "Duplicar y adjuntar.");
	strcpy(s_Duplicate_values_are_ignored, "¡Se ignoraron los valores duplicados!");
	strcpy(s_Error, "Error");
	strcpy(s_Error_loading_file, "Error al cargar el archivo.");
	strcpy(s_export_everything, "Exportar todo");
	strcpy(s_Fit_to_screen, "Ajustar a la pantalla.");
	strcpy(s_Force_fixed_height, "Dibuja las piezas con una altura fija.");
	strcpy(s_Flipped, "volteado");
	strcpy(s_Import, "Importar");
	strcpy(s_If_angles_are_different_from_90_degrees_height_must_be_greater_than_0, "Si los ángulos son diferentes de 90 grados, la altura debe ser mayor que 0.");
	strcpy(s_Ignore, "Ignorar");
	strcpy(s_Incorrect_value, "Valor incorrecto");
	strcpy(s_Info, "Información");
	strcpy(s_Interior, "dentro");
	strcpy(s_Give_a_name, "Dame un nombre.");
	strcpy(s_Group, "Združite ga");
	strcpy(s_Header, "Encabezamiento");
	strcpy(s_Keep_it_as_it_is, "Mantenlo como está");
	strcpy(s_Level, "Level");
	strcpy(s_Licensee, "Concesionario");
	strcpy(s_List_separator, "Separadora de listas");
	strcpy(s_Made_with_love_in_Cugir_Romania, "Hecho con amor en: Cugir, Rumania");
	strcpy(s_Made_in, "Fabricado en");
	strcpy(s_Manufacturer, "Fabricante");
	strcpy(s_Maximum_distance_between_2_linked_segments, "Distancia máxima entre 2 segmentos conectados");
	strcpy(s_Manual_arrange, "Organización manual");
	strcpy(s_Mix_layers, "Considere entidades de todas las capas");
	strcpy(s_Mixed, "Mezclada");
	strcpy(s_Multiple_shapes_detected_Next_rows_will_be_overwritten_Continue, "Se detectó más de una forma. Por lo tanto, las filas posteriores se sobrescribirán. ¿Continuar?");
	strcpy(s_More, "Más");
	strcpy(s_Multiple_values, "Múltiples valores");
	strcpy(s_No_texture, "Sin textura");
	strcpy(s_Number, "Número");
	strcpy(s_Number_of_images, "Numero de imagenes");
	strcpy(s_Number_of_vertices, "Numero de vértices");
	strcpy(s_Offset, "Compensar");
	strcpy(s_Only_the_currently_selected_items, "Solo los elementos seleccionados actualmente.");
	strcpy(s_Optimizing_please_wait, "Optimizando... por favor espere.");

	strcpy(s_Paste, "Paste");

	strcpy(s_Piece_label, "Mostrar la etiqueta de la pieza");
	strcpy(s_Piece_size, "Tamaño de pieza");
	strcpy(s_Please_contact_us_by_email_if_you_receive_this_error, "Por favor contáctenos por correo electrónico si recibe este error.");
	strcpy(s_Please_save_it_first, "Por favor, guárdelo primero.");
	strcpy(s_Position, "Posición");
	strcpy(s_Preview, "Avance");
	strcpy(s_Rectangle, "Rectángulo");
	strcpy(s_Resolution, "Resolución");
	strcpy(s_Redo_the_last_operation, "Restaurar la última operación.");
	strcpy(s_Regular_polygon, "Polígono regular");

	strcpy(s_Reused, "Reutilizada");
	strcpy(s_Rotated, "Rotada");
	strcpy(s_Save_all, "Salvar a todos");
	strcpy(s_Scrap_label, "Etiqueta de chatarra");
	strcpy(s_Scrap_size, "Tamaño de la chatarra");
	strcpy(s_Semicolon, "Punto y coma");
	strcpy(s_Show_cut_index, "índice de corte");
	strcpy(s_Show_information, "Muestra información");
	strcpy(s_Show_piece_label, "Mostrar la etiqueta de la pieza");
	strcpy(s_Show_scrap_label, "Etiqueta de chatarra");
	strcpy(s_Show_scrap_s_size_on_the_small_pieces, "Mostrar el tamaño de la chatarra en las piezas pequeñas");
	strcpy(s_Show_size_of_pieces, "Tamaño de pieza");
	strcpy(s_Show_size_of_scrap, "Tamaño de la chatarra");
	strcpy(s_Show_sizes, "Mostrar tallas");
	strcpy(s_Show_label, "Mostrar etiqueta");
	strcpy(s_Show_length, "Mostrar longitud");

	strcpy(s_Some_numerical_values_are_incorrect_Should_I_fix_all_the_incorrect_values, "¡Algunos valores numéricos son incorrectos! ¿Debo corregir todos los valores incorrectos?");
	strcpy(s_Some_invalid_values_have_been_removed, "Se han eliminado algunos valores no válidos.");
	strcpy(s_Sort_by, "Ordenar por");
	strcpy(s_Sort_ascending_by, "Ordenar ascendente por");
	strcpy(s_Sort_descending_by, "Ordenar descendiendo por");
	strcpy(s_Start, "Start");
	strcpy(s_Starting_angle, "Ángulo de inicio");
	strcpy(s_Starting_corner, "Esquina inicial");
	strcpy(s_Starting_direction, "Dirección de inicio");
	strcpy(s_Sticker, "Etiqueta");

	strcpy(s_Stock, "Inventario");
	strcpy(s_Stop, "Stop");
	
	strcpy(s_System_setting, "Configuración del sistema");
	strcpy(s_Tabular, "Tabular");
	strcpy(s_Total, "Total");
	strcpy(s_Total_size, "Tamaño total");
	strcpy(s_Terms_of_the_license, "Términos de la licencia");
	strcpy(s_The_current_product_has_been_changed_Do_you_want_to_save_it_to_file, "El producto actual ha sido modificado. ¿Quieres guardarlo en un archivo?");
	strcpy(s_The_value_is_out_of_the_allowed_range, "El valor está fuera del rango permitido.");
	strcpy(s_The_value_must_be_a_real_or_fractional_number_Try_to_replace_the_comma_with_the_dot_if_you_want_to_enter_a_real_number, "El valor debe ser un número real o fraccionario. Intente reemplazar la coma con el punto si desea ingresar un número real.");
	strcpy(s_This_feature_is_not_implemented_yet, "Esta función aún no está implementada.");
	strcpy(s_This_operation_cannot_be_reversed, "Esta operación no se puede revertir.");
	strcpy(s_Undo_the_last_operation, "Deshacer la última operación.");
	strcpy(s_Utilization, "Utilización");
	strcpy(s_Utilized_Stock, "Stock utilizado");
	strcpy(s_Version, "Versión");
	strcpy(s_Visible_columns, "Columnas visibles");
	strcpy(s_You_already_have_the_latest_version_installed, "¡Ya tienes instalada la última versión!");
	strcpy(s_What_is_exported, "¿Qué se exporta?");
	strcpy(s0meansanynumberofpieces, "Cero significa cualquier número de piezas");
	strcpy(sAbout, "Acerca de");
	strcpy(sAccept, "Aceptar");
	strcpy(sAcceptall, "Aceptar todo");
	strcpy(sAcceptthecurrentsolution, "Acepta solo la corriente.");
	strcpy(sAdd, "Adjuntar");
	strcpy(sAddapiece, "Añadir una pieza");
	strcpy(sAddasimpleproducttoDemand, "Añadir un producto al stock existente");
	strcpy(sAddgrindingthicknesstopartsize, "Añadir el grosor de pulido al tamaño de pieza");
	strcpy(sAddproductnametolabel, "Añadir el nombre del producto a la etiqueta");
	strcpy(sAddress, "Dirección");
	strcpy(sAddselectedsizetoInventory, "Añadir el tamaño seleccionado al inventario");
	strcpy(sAdhesivelabels, "Etiquetas adhesivas");
	strcpy(sAdhesivelabelwithinformationaboutpiecesinDemandCustomernameLabelSizeCurrentData, "Etiqueta adhesiva con información sobre las piezas: Nombre del cliente, Etiqueta, Tamaño, Datos corrientes.");
	strcpy(sAdhesivelabelwithinformationaboutsheetsinInventory, "Etiqueta adhesiva con información sobre hojas en Inventario");
	strcpy(sAll, "Todas");
	strcpy(sAlloffcutswhichhavethesizegreaterthanthisvaluewillbeaddedtoInventory, "Todos los retales que tengan mayor tamaño que este valor serán añadidos al Inventario");
	strcpy(sAllowMirroring, "Permitir reflejo");
	strcpy(sAllowRotation, "Permitir rotación");
	strcpy(sAllPieces, "Todas las piezas");
	strcpy(sAllpredefinedproducts, "Todos los productos predefinidos");
	strcpy(sAnewwindowwillbedisplayedwheretheusercansettheedgebandsforeachedge, "Una nueva ventana será mostrada donde el usuario puede poner las franjas de borde para cada borde.");
	strcpy(sAnewwindowwillbedisplayedwheretheusercansetthegrindingvalueforeachedgeofthsheet, "Una nueva ventana será mostrada donde el usuario puede poner el tamaño de pulido para cada borde de la pieza.");
	strcpy(sAnewwindowwillbedisplayedwheretheusercansetthetrimvalueforeachedgeofthsheet, "Una nueva ventana será mostrada donde el usuario puede poner los defectos de cada borde de la pieza");
	strcpy(sAngle, "Ángulo");
	strcpy(sAngles, "Ángulos");
	strcpy(sAnoptimizationparameterisarealnumber, "Un parámetro de optimización es un número decimal.");
	strcpy(sAnoptimizationparameterisfractionalnumber, "Un parámetro de optimización es  número fraccionario.");
	strcpy(sAnyShape, "¡Cualquier forma!");
	strcpy(sApolygonmusthaveatleast2vertices, "¡Un poligono debe tener al menos 2 vértices!");
	strcpy(sApolygonmusthaveatleast3vertices, "¡Un poligono debe tener al menos 3 vértices!");
	strcpy(sApplication_fails_to_initialize, "El software no inicialización.");
	strcpy(sArc, "Arco");
	strcpy(sArcLength, "Longitud de arco");
	strcpy(sAreaofusedsheets, "Área de sábanas utilizadas");
	strcpy(sAshortdescriptionofthesheet, "Breve descripción de la hoja.");
	strcpy(sAtleastonepart, "Al menos debe introducirse una pieza.");
	strcpy(sAtTheMarginOfTheSheet, "En el borde de la hoja");
	strcpy(sBandtypes, "Tipos de bandas de borde.");
	strcpy(sBar, "Barras / tuberías");
	strcpy(sBars, "Barras / tuberías");
	strcpy(sBothsizesoftheoffcutsmustbegreaterthanthisvalue, "Ambos tamaños de residuos deben ser mayores que este valor.");
	strcpy(sBottom, "Abajo");
	strcpy(sBottomcoordinateofthedefect, "La coordenada inferior del defecto");
	strcpy(sBreakCut, "Romper el corte.");
	strcpy(sBrowse, "Explorar");
	strcpy(sBuy, "Comprar");
	strcpy(sBuynow, "Comprar ahora…");
	strcpy(sCancel, "Cancelar");
	strcpy(sCannotBeEmpty, "¡No puede estar vacio!");
	strcpy(sCannotmovepartsbetweensheetswhenidenticalsheetsaregroupedPleaseungroupthesheetsfrommenu, "No puede mover las partes de una hoja a otra si las hojas idénticas estan agrupadas. Por favor cancele la agrupación de las hojas desde el menú.");
	strcpy(sCannotSaveFile, "No puede guardar el archivo");
	strcpy(sCenter, "Centro");

	strcpy(sChangeDirection, "Cambie la dirección");
	strcpy(sChoose, "Elegir");
	strcpy(sChooseProduct, "Elegir producto");
	strcpy(sCircle, "Círculo");
	strcpy(sCity, "Ciudad");
	strcpy(sClear, "Limpiar");
	strcpy(sClockWise, "En sentido de las agujas del reloj");
	strcpy(sClosewindow, "Cerrar ventana");
	strcpy(sColor, "Color");
	strcpy(sColorofedgeband, "El color de las bandas de borde.");
	strcpy(sColorPattern, "Color/Patrón");
	strcpy(sColorpiecesandwastes, "Piezas y retales coloreados");
	strcpy(sColumns, "Columnas");
	strcpy(sComment, "Comentario");
	strcpy(sCompanyname, "Nombre de la compañía");
	strcpy(sComplexMaterialExists, "Nombre del material ya definido en la lista de materiales complejos. Por favor déle un nuevo nombre.");
	strcpy(sComputerCode, "Código del ordenador");
	strcpy(sComputerCodefromyourcomputer, "Código del ordenador (de su ordenador)");
	strcpy(sComputethetotalpriceofDemand, "Calcular el precio total de la Demanda");
	strcpy(sContents, "Contenidos");
	strcpy(sContinutComanda, "Contenidos de la Demanda para una fecha");
	strcpy(sContinutDepozit, "Contenidos del Inventario para una fecha");
	strcpy(sConversionIsDoneOnlyWhenSomePiecesHaveFractionalValues, "La conversión se hace sólo cuando algunas piezas tienen valores fraccionarios");
	strcpy(sConvertsTheSizeOfWasteToAFractionalUnit, "Muestra el tamaño del retal como un valor fraccionario.");
	strcpy(sCouldNotSaveFile1, "No se puede escribir el archivo en el directorio");
	strcpy(sCouldNotSaveFile2, "No  tiene suficientes permisos. Por favor compruebe o cambie el directorio de trabajo desde el menú Ajustes / Directorio de trabajo a una carpeta donde usted tenga permisos de escritura (por ejemplo c: \\temp).");
	strcpy(sCreationdateYMDHMS, "Fecha de creacion (A/M/D-H:M:S)");
	strcpy(sCurrentDate, "Fecha actua");
	strcpy(sCurrentDiagram, "Diagrama actual");
	strcpy(sCurrentMaterial, "Material actual");
	strcpy(sCurrentversion, "Versión actual");
	strcpy(sCurve_not_closed_Try_increasing_DXF_linking_distance_parameter, "¡El polígono no está cerrado! Intente aumentar el parámetro Distancia de enlace DXF.");
	strcpy(sCustomer, "Cliente");
	strcpy(sCustomerName, "Nombre del cliente");
	strcpy(sCustomMessage, "Mensaje personalizado");
	strcpy(sCutlength, "Longitud del corte");
	strcpy(sCut, "Corte");
	strcpy(sCuts, "Cortes");
	strcpy(sCutterThickness, "Grosor del corte");
	strcpy(sData, "Datos");
	strcpy(sDataCannotBeEmpty, "¡Los datos no pueden estar vacíos!");
	strcpy(sDateymdhms, "Fecha (a/m/d/h/m/s)");
	strcpy(sDays_left_for_trial, "Días disponibles para la prueba");
	strcpy(sDaysLeft, "días restantes");
	strcpy(sStandard, "Por defecto");
	strcpy(sDefaultInterface, "Interfaz por defecto");
	strcpy(sDefects, "Defectos");
	strcpy(sDefectsManager, "Gestión de defectos");
	strcpy(sDefectsofthematerialNopiecescanbeplacedinthefaultyzone, "Defectos en el material. Las  piezas no pueden ser colocadas en las zonas con defectos.");
	strcpy(sDelete, "Borrar");
	strcpy(sDeletePiece, "Borrar pieza");
	strcpy(sDeleteRow, "eliminar fila");
	strcpy(sDemandutilization, "Utilización de piezas.");
	strcpy(sDepozitulmodificat, "Las piezas utilizadas han sido quitadas. Los retales han sido añadidos al stock.");
	strcpy(sDepozitvid, "El stock esta vacio");
	strcpy(sDesk, "escritorio");
	strcpy(sDiagram, "Diagrama");
	strcpy(sDiagrams, "Diagramas");
	strcpy(sDiagramasatable, "Diagrama como tabla");
	strcpy(sDigits, "dígitos");
	strcpy(sDimensiuniplaca, "Tamaño de hoja");
	strcpy(sDirection, "Dirección");
	strcpy(sDistanceBetweenRows, "Distancia entre filas");
	strcpy(sDonotuseit, "No usar");
	strcpy(sDownload, "Descargar");
	strcpy(sDoYouWantToClearTheData, "¿Quiere borrar los datos?");
	strcpy(sDoYouWantToSaveDemand, "¡Las partes se han cambiado! ¿Quiere guardar los cambios?");
	strcpy(sDoYouWantToSaveParts, "¿Quiere guardar las partes?");
	strcpy(sDoYouWantToSaveRepository, "¡El stock se ha cambiado! ¿Quiere guardar los cambios?");
	strcpy(sDrawing, "Dibujos");
	strcpy(sDrawthesolutioncolorful, "Dibujar la solución coloreada");
	strcpy(sDuplicateTypes, "¡Algunos tipos estan duplicados! Por favor quite los duplicados");
	strcpy(sDuplicateTypesWithComplex, "¡Algunos nombres de materiales ya existen en la lista de tipos complejos! Por favor quite los duplicados");
	strcpy(sDuplicateValues, "Valores duplicados");
	strcpy(sEdgeband, "Bandas para bordes");
	strcpy(sEdgebandingwhichisplacedontheedgesofyourpiecePleasedefineedgebandingtypesfromMaterialsEdgeBandingmenu, "Bandas de borde que se colocan en los bordes de su pieza. Defina los tipos de bandas de borde en el menú Materiales.");
	strcpy(sEdgebandsthatwillbeappliedtoeachpart, "Bandas de borde que se aplican a cada parte.");
	strcpy(sEdgeBandTolerance, "Tolerancia para bandas de borde.");
	strcpy(sEdgesthatmustbecutduefaults, "Bordes que deben cortarse debido a defectos.");
	strcpy(sEdgetoedge, "De borde a borde");
	strcpy(sEdit, "Editar");
	strcpy(sEmail, "Emai");
	strcpy(sEmptyData, "¡Los datos estan vacíos!");
	strcpy(sEnabled, "Habilitado");
	strcpy(sEnabledisabledefectsoftheinventorysheets, "Permitir/denegar defectos en el stock");
	strcpy(sEnterLabel, "Ingrese la etiqueta.");
	strcpy(sEnterTheMaterialName, "Ingrese el nombre del material.");
	strcpy(sEnterTheProductName, "Introduzca el nombre de producto");
	strcpy(sEvaluationError, "¡Error en la evaluación de la expresión!");
	strcpy(sExit, "Salir");
	strcpy(sExpired, "¡El sofware ha expirado! ¡Por favor registre el software!");
	strcpy(sExport, "Exportar");
	strcpy(sExportAllDiagrams, "Exportar todos los diagramas");
	strcpy(sExportAllToASingleFile, "Exportar todo a un solo archivo");
	strcpy(sExportOptions, "Exportar opciones");
	strcpy(sExporttoDXFformat, "Exportar a formato DXF");
	strcpy(sExporttoExcel, "Exportar a Excel");
	strcpy(sExpresieIncorecta, "¡Expresión matemática incorrecta!");
	strcpy(sExtensions, "Extensions");
	strcpy(sExtra, "Otros");
	strcpy(sExtraComponents, "Componentes adicionales");
	strcpy(sExtracomponentsattachedtoDemand, "Componentes adicionales unidos a partes");
	strcpy(sFile, "Archivo");
	strcpy(sFileName, "Nombre de archivo");
	strcpy(sFillWastes, "Dibujar retales con líneas oblicuas");
	strcpy(sFindoptimalbarsheetsize, "Encontrar el tamaño óptimo para barras y hojas.");
	strcpy(sFindoptimalsizeofInventorypieces, "Encontrar el tamaño optimo para el stock de piezas");
	strcpy(sFirstcutMultiplestages, "Primera dirección de corte - Múltiples etapas");
	strcpy(sFirstdirectionforcutishorizontal, "La primera dirección de corte es horizonta");
	strcpy(sFirstdirectionforcutisvertical, "La primera dirección de corte es vertica");
	strcpy(sFollowthecontourofpieces, "Seguir el contorno de las piezas");
	strcpy(sFont, "Fuente");
	strcpy(sFontsize, "Tamaño de fuente");
	strcpy(sFullInfo, "Información completa");
	strcpy(sDisposedWaste, "Residuos eliminados");
	strcpy(sGeneral, "General");
	strcpy(sGenerateCNC, "Generar CNC");
	strcpy(sGrain, "Textura");
	strcpy(sGraindirection, "Dirección de la textura");
	strcpy(sGraphic, "Gráfico");
	strcpy(sGreaterorequalto, "Mayor o igual que");
	strcpy(sGrid, "Tablas");
	strcpy(sGrinding, "Espesor de pulido");
	strcpy(sGrosimeTaieturaScalata, "El grosor de corte de esta imagen podría ser diferente del real porque las piezas no están representadas en su escala verdadera. Este hecho no afecta a los resultados.");
	strcpy(sGroupidenticallayouts, "Agrupacion de hojas idénticas.");
	strcpy(sGroupIdenticalParts, "Agrupar partes idénticas");
	strcpy(sGroupingOfIdenticalPiecesIntoOneRow, "Agrupación de partes  identicas en una fila");
	strcpy(sGroupPartsAfterLoadingFromFile, "Agrupar partes tras cargar del archivo");
	strcpy(sHeight, "Altura");
	strcpy(sHeighttolerance, "Tolerancia para la altura");
	strcpy(sHelp, "Ayuda");
	strcpy(sHistory, "Historia");
	strcpy(sHorizontal, "Horizontal");
	strcpy(sHowtodisplayprintedgebands, "¿Cómo se muestran las bandas de borde?");
	strcpy(sIfyousetthebandforoneedgeallwillreceivethesamevalue, "Si configura la banda para un borde, todos los bordes recibirán el mismo valor.");
	strcpy(sIfyousetthegrindingforoneedgeallwillreceivethesamevalue, "Si pone el valor de pulido para un borde, todos los bordes recibirán el mismo valor.");
	strcpy(sIfyousetthetrimforoneedgeallwillreceivethesamevalue, "Si pone el recortado para un borde, todos los bordes recibirán el mismo valor");
	strcpy(sImageBounds, "Límites de la imagen");
	strcpy(sImageSize, "Tamaño de la imagen");
	strcpy(sImportData, "Importar los datos");
	strcpy(sIncorrectPassword, "Contraseña incorrecta");
	strcpy(sIndex, "Índice");
	strcpy(sInformationaboutcustomer, "Información sobre el cliente");
	strcpy(sInputALanguageName, "Ingrese el nombre del idioma.");
	strcpy(sInsert, "Insertar");
	strcpy(sInsertPiece, "Insertar pieza");
	strcpy(sInterface, "Interfaz");
	strcpy(sInterfaceSettings, "Ajustes de interfaz");
	strcpy(sInvalidHardware, "No se pudo detectar el hardware. Por favor póngase en contacto con nosotros a través de contact@optimalprograms.com");
	strcpy(sInvalidNumber, "Número inválido");
	strcpy(sInvalidOrderOfComputation, "No se puede establecer un orden para calcular las longitudes ¡Hay relaciones circulares en la definición de producto!");
	strcpy(sInvalidRegistration, "¡El registro es inválido!");
	strcpy(sInvalidTime, "La hora de su sistema es inválida");
	strcpy(sInventory, "Inventario");
	strcpy(sisafractionalvalue, "Es un valor fraccionario");
	strcpy(sIsArc, "Es arco");
	strcpy(sisarealvalue, "Es un valor decima");
	strcpy(sLabel, "Etiqueta");
	strcpy(sLabels, "Etiquetas");
	strcpy(sLanguage, "Idioma");
	strcpy(sLatimeanumar0, "¡La anchura debe ser mayor que 0!");
	strcpy(sLatimeanumarreal, "¡La anchura debe ser un numero decimal!");
	strcpy(sLayerName, "Nombre de la capa");
	strcpy(sLeft, "Izquierda");
	strcpy(sLeftcoordinateofthedefect, "La coordenada izquierda del defecto");
	strcpy(sLength, "Longitud");
	strcpy(sLengthofthepiecestocut, "Tamaño de pieza para corte");
	strcpy(sLengthofthepiecestocutfrom, "Tamaño de hoja para corte");
	strcpy(sLengthofusedbars, "Tamaño de barras usadas");
	strcpy(sLicenseAgreement, "Acuerdo de licencia");
	strcpy(sLinear, "Linea");
	strcpy(sLinethickness, "Tamaño del lápiz");
	strcpy(sLoadafileandappenddatatothecurrentDemand, "Cargar un archivo y añadir los datos a la demanda actua");
	strcpy(sLoadanexistingDemandfromafile, "Cargar una demanda existente desde archivo");
	strcpy(sLoadAppend, "Cargar y añadir");
	strcpy(sLoadEverything, "Cargar todo");
	strcpy(sLoadInventory, "Cargar el stock");
	strcpy(sLoadInventoryandDemand, "Cargar el stock y la demanda");
	strcpy(sLoadResults, "Cargar los resultados");
	strcpy(sLocked, "Bloqueado");
	strcpy(sLogo, "Logo");
	strcpy(sLong, "Largo");
	strcpy(sLongerexecutiontime, "Mayor tiempo de ejecución");
	strcpy(sLungime, "Ancho");
	strcpy(sLungimeanumar0, "¡La longitud debe ser mayor que 0!");
	strcpy(sLungimeanumarreal, "¡La longitud deber ser un número decimal!");
	strcpy(sLungimeaTotalaFolosita, "Longitud total utilizada");
	strcpy(sMagnification, "Amplificación");
	strcpy(sMagnify, "Agrandar");
	strcpy(sMargins, "Márgenes");
	strcpy(sMarginsForPaper, "Márgenes para pape");
	strcpy(sMarginsOfTheLabel, "Márgenes de la etiqueta");
	strcpy(sMaterial, "Materia");
	strcpy(sMaterialName, "Nombre del materia");
	strcpy(sMaterials, "Materiales");
	strcpy(sMaterialstypes, "Tipos de materia");
	strcpy(sMax, "Máximo");
	strcpy(sMaximalArea, "Área máxima");
	strcpy(sMaximalCutLength, "Longitud de corte máxima");
	strcpy(sMaxlength, "Longitud máxima");
	strcpy(sMaxPiecesperBar, "Máximo número de piezas por barra");
	strcpy(sMaxwidth, "Anchura máxima");
	strcpy(sMeasurementUnit, "Unidad de medida");
	strcpy(sMin, "Mínimo");
	strcpy(sMinimalBreakSize, "Tamaño de ruptura minimo");
	strcpy(sMinimalUsefulSize, "Tamaño útil mínimo");
	strcpy(sMinimalwastesizetoInventory, "Tamaño de retal mínimo para inventario");
	strcpy(s_What_to_minimize, "¿Qué minimizar?");
	strcpy(sMinlength, "Longitud mínima");
	strcpy(sMinwidth, "Ancho mínimo");
	strcpy(sMirror, "Reflejar");
	strcpy(sMirroring, "Reflejar");
	strcpy(sMiscellaneous, "Otras estadísticas");
	strcpy(sModify, "Modificar");
	strcpy(sModifytheselectedpiece, "Modificar la pieza seleccionada");
	strcpy(sMovePiece, "Mover pieza.");
	strcpy(sMultiplestages, "Múltiples etapas");
	strcpy(sName, "Nombre");
	strcpy(sNameofedgeband, "Nombre de las franjas de borde");
	strcpy(sNewDEMANDUnsaveddatawillbelost, "¿Partes nuevas? ¡Los datos no guardados se perderán!");
	strcpy(sNewLanguage, "Nuevo idioma");
	strcpy(sNewMaterial, "Nuevo material");
	strcpy(sNewPasswordincorectlyintroduced, "¡Nueva contraseña introducida incorrectamente!");
	strcpy(sNewProduct, "Nuevo producto");
	strcpy(sNewversion, "Nowa wersja");
	strcpy(sNo, "¡No!");
	strcpy(sNumarBucati, "Número de piezas");
	strcpy(sNumberOfCopies, "Número de copias");
	strcpy(sNumberofstages, "Número de etapas");
	strcpy(sNusuficienteplacidepozit, "No todas las piezas han sido optimizadas. Causas posibles: No hay bastantes piezas en el STOCK. La pieza no se  utiliza en la optimización. Los tipos de la pieza de la Demanda y el Stock no coinciden. Otros parámetros  han sido establecidos incorrectamente.");
	strcpy(sOfficeNotInstaled, "¡Microsoft Office no está instalado en su ordenador o la versión es incorrecta!");
	strcpy(sOldpassworddoesnotmatch, "¡La antigua contraseña no coincide!");
	strcpy(sOnlinehelp, "Ayuda online");
	strcpy(sOnlypiecesofthesameheightinthelaststage, "Piezas de la misma altura en la última etapa");
	strcpy(sOpen, "Abrir");
	strcpy(sOptimization, "Optimización");
	strcpy(sOptimizationDone, "¡Optimización realizada! Puede imprimir o guardar los diagramas obtenidos. Pulse el botón Aceptar si está satisfecho con la solución actual. En caso contrario pulse de nuevo Empezar.");
	strcpy(sOptimizationType, "Tipo de optimización");
	strcpy(sOptions, "Opciones");
	strcpy(sOptionsrelatedtotheinterface, "Opciones relacionadas con la interfaz");
	strcpy(sor, "o");
	strcpy(sOthercomponents, "Otros componentes");
	strcpy(sOthers, "Otros");
	strcpy(sOtherstatistics, "Otras estadísticas");
	strcpy(sOverrideExcelCSVfiles, "Sobreescribir archivos Excel/CSV");
	strcpy(sParameter, "Parámetro");
	strcpy(sParts, "PARTES");
	strcpy(sPattern, "Patrón");
	strcpy(sPatternforwaste, "Patrón para retales");
	strcpy(sPerimeter, "Perímetro");
	strcpy(sPermitedRotationAngle, "Ángulo de rotación permitido");
	strcpy(sPhone, "Teléfono");
	strcpy(sPicture, "Imagen");
	strcpy(sPiece, "Pieza");
	strcpy(sPieceindex, "Índice de piezas");
	strcpy(sPieces, "Piezas");
	strcpy(sPiecesize, "Tamaño de pieza");
	strcpy(sPiecesizelabeledgebandwillbeprinted, "El tamaño de pieza, etiqueta y las franjas de borde se imprimirán");
	strcpy(sPierdere, "Desecho");
	strcpy(sPixels, "Píxels");
	strcpy(sPlacilefolositeDepozit, "Piezas utilizadas del inventario");
	strcpy(sPlease_contact_us_at_contact_nestingtechnologies_com, "Por favor contacte con nosotros en contact@nesting-technologies.com");
	strcpy(sPlease_contact_us_at_contact_optimalprograms_com, "Por favor contacte con nosotros en contact@optimalprograms.com");
	strcpy(sPleaseenteralldataeitherasfractionalorrealDonotmixthem, "¡Por favor introduzca  todos los datos como fraccionarios o decimales! ¡No los mezcle!");
	strcpy(sPleaseEnterSomeTypesOfMaterials, "No hay tipo de material definido.Tiene que definirlo desde el menú de Materiales.");
	strcpy(sPleasesendtheNameandtheCodetotheaddresscontactoptimalprogramscominordertoobtaintheRegistrationKey, "Para obtener la Clave de Registro por favor envíe el Nombre y el Código a: contact@optimalprograms.com.");
	strcpy(sPolygon, "Polígono");
	strcpy(sPolygonsCircles, "Polígonos, círculos");
	strcpy(sPrecision, "Precisión");
	strcpy(sPretulnumar0, "¡El precio debe ser mayor que 0 !");
	strcpy(sPretulnumarreal, "¡El precio debe ser un número decimal!");
	strcpy(sPreview, "Previsualización");
	strcpy(sPrice, "Precio");
	strcpy(sPriceMustBeGreaterThanZero, "Precio debe ser mayor que 0");
	strcpy(sPriceofbars, "Precio de las barras");
	strcpy(sPriceperbar, "Precio por barra");
	strcpy(sPricepersheet, "Precio por hoja");
	strcpy(sPricepersquareunitofmaterial, "Precio por unidad cuadrada de material.");
	strcpy(sPriceperunit, "Precio por unidad");
	strcpy(sPrint, "Imprimir");
	strcpy(sPrintdiagramsastables, "Imprimir diagramas en forma de tablas");
	strcpy(sPrinter, "Impresora");
	strcpy(sPrinterBounds, "Márgenes de impresora");
	strcpy(sPrinting, "Impresión");
	strcpy(sPrintonlyutilizedarea, "Imprimir sólo el área utilizada");
	strcpy(sPrintthecontentsoftheDemand, "Imprimir los contenidos de la Demanda");
	strcpy(sPrintthecontentsoftheInventory, "Imprimir los contenidos del stock");
	strcpy(sPrintthecurrentsolution, "Imprimir la solución actual");
	strcpy(sPriority, "Prioridad");
	strcpy(sPrioritytocutapieceZero0isthehighestpriority, "Prioridad para cortar una pieza. Cero (0) es la mayor prioridad");
	strcpy(sProcentul0100, "¡Los porcentajes deben ser mayores que 0 y menores o iguales a 100!");
	strcpy(sProcentulnumarreal, "¡Los porcentajes deben ser un número decimal!");
	strcpy(sProductdefinition, "Definicion del producto");
	strcpy(sProductExists, "El producto ya existe. Elija otro nombre.");
	strcpy(sProductName, "Nombre del producto");
	strcpy(sProducts, "Producto");
	strcpy(sProducts, "Productos");
	strcpy(sProject, "Proyecto");
	strcpy(sProperties, "Propiedades");
	strcpy(sProperty, "Propiedad");
	strcpy(sQuantity, "Cantidad");
	strcpy(sQuantitynumberofsheetsofthistype, "Número de hojas de este tipo");
	strcpy(sRadius, "Radio");
	strcpy(sRectangular, "Rectangular");
	strcpy(sRedefinetypesofedgeband, "Redefinir tipos de franja de borde");
	strcpy(sRedefinetypesofmaterial, "Redefinir tipos de materia");
	strcpy(sRegistration, "Registro");
	strcpy(sRegistrationKeyfromOptimalPrograms, "Clave de registro");
	strcpy(sRegistrationSuccessful, "¡Registro completado!");
	strcpy(sRemoveallpiecesinInventory, "Eliminar todas las piezas del Inventario.");
	strcpy(sRemoveCut, "Borrar corte");
	strcpy(sRemovetheselectedpiece, "Eliminar la pieza seleccionada");
	strcpy(sReports, "Informes");
	strcpy(sRequestedMaterial, "Material solicitado");
	strcpy(sRestore, "Restaurar");
	strcpy(sResults, "Resultados");
	strcpy(sReusedwaste, "Retales reutilizados");
	strcpy(sRight, "Derecha");
	strcpy(sRightcoordinateofthedefect, "Coordenadas del defecto por la derecha");
	strcpy(sRotation, "Rotación");
	strcpy(sRotationAngle, "Ángulo de rotación");
	strcpy(sRotationStep, "Etapa de rotación");
	strcpy(sRoundAllFractionsTo, "Los valores fraccionarios deben ser redondeados a");
	strcpy(sRow, "fila");
	strcpy(sRows, "Filas");
	strcpy(sRun, "Últimas soluciones");
	strcpy(sRunningtime, "Duración");
	strcpy(sSameforall, "Igual para todo");
	strcpy(sSave, "Guardar");
	strcpy(sSaveAllImages, "Guardar todas las imágenes");
	strcpy(sSaveAs, "Guardar como");
	strcpy(sSaveChanges, "La Demanda ha sido cambiada. ¿Quiere guardar los cambios?");
	strcpy(sSaveCurrentImage, "Guardar imagen actua");
	strcpy(sSavedataparameters, "Guardar datos y parámetros");
	strcpy(sSaveEverything, "Guardar todo");
	strcpy(sSaveInventory, "Guardar Inventario");
	strcpy(sSaveInventoryandDemand, "Guardar Inventario y Demanda");
	strcpy(sSaveResults, "Guardar Resultados");
	strcpy(sSaveStatisticsinafile, "Guardar estadísticas en un archivo");
	strcpy(sSavethecurrentimage, "Guardar la imagen actua");
	strcpy(sSavethecurrentimageorstatistic, "Guardar la imagen o estadística actua");
	strcpy(sSavetheDEMANDinafile, "Guardar al archivo");
	strcpy(sSavetheDemandinafilewithadifferentname, "Guardar la Demanda en un archivo con nombre diferente");
	strcpy(sSavetheREPOSITORYinafile, "Guardar el STOCK en un archivo");
	strcpy(sSerialNumber, "Clave de registro");
	strcpy(sService, "Servicio");
	strcpy(sSetDefaultValues, "Esto restaurará todos los parámetros a sus valores por defecto. Todos sus ajustes se perderán. ¿Está seguro de que quiere hacer esto?");
	strcpy(sSetedgeband, "Establecer franja de borde");
	strcpy(sSetedgetrim, "Establecer el recorte para los defectos en los bordes");
	strcpy(sSetthesameedgebandforalledges, "Establecer la misma franja de borde para todos los bordes");
	strcpy(sSetthesamegrindingforalledges, "Establecer el mismo pulido para todos los bordes");
	strcpy(sSetthesametrimforalledges, "Establecer el mismo recorte para defectos en todos los bordes");
	strcpy(sSettings, "Ajustes");
	strcpy(sShape, "Forma");
	strcpy(sSheet, "Hoja");
	strcpy(sSheetsBarstypes, "Hojas_Tipos de barra");
	strcpy(sSheetSize, "Tamaño de hoja");
	strcpy(sSheetsperPage, "Hojas por página");
	strcpy(sShort, "Corto");
	strcpy(sShorterexecutiontime, "Tiempo de ejecución corto");
	strcpy(sShowallsimpleproducts, "Mostrar todos los productos simples");
	strcpy(sShowcustomername, "Mostrar el nombre del cliente");
	strcpy(sShowCustomTextOnEachPiece, "Mostrar el texto personalizado en cada pieza");
	strcpy(sShowdiagramasatable, "Mostrar diagrama como tabla");
	strcpy(sShowedgeband, "Mostrar franjas de borde");
	strcpy(sShowedgebandssettinginanewwindow, "Mostrar ajustes de franjas de borde en una nueva ventana");
	strcpy(sShowgrindingsettingsinanewwindow, "Mostrar ajustes de pulido en una nueva ventana");
	strcpy(sShowHorizontalLabelsAlways, "Mostrar siempre etiquetas horizontales");
	strcpy(sShowRemovethesizeofthepiecesinthecurrentsolution, "Mostrar/Eliminar el tamaño de las piezas en la solución actual.");
	strcpy(sShowRemovethesizeofthewastesinthecurrentsolution, "Mostrar/Eliminar el tamaño de los retales en la solución actual.");
	strcpy(sShowtotalcutlength, "Mostrar la longitud total de los cortes");
	strcpy(sShowtrimedgesettingsinanewwindow, "Mostrar los ajustes de los defectos en una nueva ventana");
	strcpy(sSimpleMaterialExists, "El nombre de material ya está definido en la lista de materiales. Por favor asigne un nuevo nombre");
	strcpy(sSinglePieceStrips, "Rayas de una pieza");
	strcpy(sSizes, "Tamaños");
	strcpy(sSmallerorequalto, "Mas pequeño o igual a");
	strcpy(sSort, "Ordenar");
	strcpy(sSortAscendingByArea, "Ordenar por área de forma ascendente");
	strcpy(sSortDescendingByArea, "Ordenar por área de forma descendiente");
	strcpy(sSpecifyhowdifferentthepiecesinthelaststagecanbeValue0meansnodifference, "Especifique cómo de diferentes pueden ser las piezas en la última etapa.  Valor 0 significa sin ninguna diferencia.");
	strcpy(sSpecifyifpiecesinthelaststagecanbedifferentornotdepeultimaetapapotfidiferitesaunucadimensiune, "Especifique si la piezas en la ultima etapa pueden ser diferentes o no.");
	strcpy(sSpecifyifthepiececanberotatedornotIfnotitwillbecutinthesamewayasitwasintroducedinDemandLengthofthepieceparalleltothelengthofthesheet, "Especifique si la pieza se puede rotar o no. Si no, debe ser cortada de la misma manera que fue introducida en Demanda (la longitud de la pieza paralela a la longitud de la hoja)");
	strcpy(sSpecifyinhowmanystageswemakethecutsDuringastageallcutshavethesamedirection, "Especifique en cuantas etapas se harán los cortes");
	strcpy(sStartthesearchprocess, "Empezar el proceso de búsqueda");
	strcpy(sStatistics, "Estadísticas");
	strcpy(sStatisticsE, "Informes extra");
	strcpy(sStatisticsforeachtypeofmaterial, "Estadísticas por cada tipo de materia");
	strcpy(sStep, "Paso");
	strcpy(sStergeDepozit, "¿Quiere borrar el Inventario?");
	strcpy(sStergeMaterial, "¿Borrar material?");
	strcpy(sStergePiesele, "¿Quiere borrar la pieza?");
	strcpy(sStergePiesa, "¿Quiere borrar la pieza?");
	strcpy(sStopthesearchprocess, "Detener el proceso de busqueda");
	strcpy(sStrongoptimization, "Optimizacion alta");
	strcpy(sSubtractthebandthicknessfrompiecesize, "Disminuir el tamaño de la pieza con el grosor de las franjas");
	strcpy(sSummary, "Resumen");
	strcpy(sSuprafataTotalaFolosita, "Superficie total utilizada");
	strcpy(sSuprafatautilizata, "Utilización");
	strcpy(sSwitchbetweenfiberandrotationoption, "Cambiar entre fibra y opción de rotación");
	strcpy(sTechnical, "Técnico");
	strcpy(sTechnicalsettings, "Ajustes técnicos");
	strcpy(sTemporaryPanelHint, "Panel temporal para mover partes entre hojas");
	strcpy(sText, "Texto");
	strcpy(sThe_application_has_expired, "El programa ha expirado.");
	strcpy(sThe_application_is_not_registered, "El software no se ha registrado.");
	strcpy(sThe_application_was_first_started_on, "El software se inició por primera vez.");
	strcpy(sThecutsareperformedfromasidetotheothersideofthematerial, "Los cortes se realizan de lado a lado del material.");
	strcpy(sThecuttingmachinecanfollowtheshapeofthematerial, "La máquina de corte puede seguir la forma de la pieza");
	strcpy(sTheedgesofsheetsthatmustbetrimedduefaults, "Los bordes de las hojas que deben ser recortados debido a los defectos");
	strcpy(sTheLargestSize, "El tamaño mas grande");
	strcpy(sThenameofthecustomerforwhichyoucutthepiece, "El nombre  del cliente para el que se corta la pieza");
	strcpy(sThenameofyourcustomer, "El nombre de su cliente");
	strcpy(sThepiececanberotated, "La pieza puede ser rotada");
	strcpy(sTheprogramtriestoavoidwasteswhichhavebothsizeslessthanthisvalue, "El programa trata de evitar los retales que tienen ambos tamaños menores que este valor");
	strcpy(sThereAreNoProducts, "Aun no hay productos definidos");
	strcpy(sThestockofmaterialhasbeenpreviouslyloadedfromanExcelorCSVformatPleaseloaditagain, "El stock de material  ha sido cargado previamente en formato CSV o  Excel. Por favor cárguelo otra vez si desea trabajar en él.");
	strcpy(sThetotallengthofcutting, "Longitud total de corte");
	strcpy(sThewidthofthecuttingsawForglasscuttingoptimizationitcanbe0Forwooditshouldbegreaterthan0, "El grosor de la sierra. Para el corte de vidrio puede ser 0. Para la madera debería ser mayor que 0.");
	strcpy(sThewidthofthecuttingsawforlinearpieces, "Grosor de la sierra para piezas lineales");
	strcpy(sThickness, "Grosor");
	strcpy(sThischaracterisusedforfillingthewasterectanglesIfyoudonotwantfilledwastejustremovethischaracter, "Este símbolo se usa para rellenar los rectángulos de los retales. Si no quiere rellenar retales simplemente elimínelo.");
	strcpy(sThisindexhasvaluebetween1andthenumberofpieces, "El índice toma valor entre 1 y el número de piezas.");
	strcpy(sThisOptionWillOverrideTheInventoryFileIfLoadedFromExcelOrCsvFiles, "Esta opción sobreescribirá el archivo de inventario si fue cargado desde archivos Excel o csv.");
	strcpy(sThisProgramisLicensedTo, "Este programa está licenciado a");
	strcpy(sThisvaluewillbeaddedtotheedgebandingmaterialoneachside, "Este valor será añadido a las franjas del borde del material en cada lado");
	strcpy(sTipNevid, "El tipo de material no puede estar vacio");
	strcpy(sTitle, "Título");
	strcpy(sTools, "Herramientas");
	strcpy(sTop, "Arriba");
	strcpy(sTopcoordinateofthedefect, "La coordenada superior del defecto");
	strcpy(sTotalGarbageWaste, "Todos los retales desechados");
	strcpy(sTotalInventoryWaste, "Stock total de retales");
	strcpy(sTotalRecycledWaste, "Todos los retales recliclados");
	strcpy(sTotalusedarea, "Área utilizada en tota");
	strcpy(sTotalusedlength, "Longitud utilizada en tota");
	strcpy(sTrigonometric, "Trigonométrico");
	strcpy(sTrim, "Recortar");
	strcpy(sTrimalledgesatthebeginning, "Recortar todos los bordes al principio");
	strcpy(sTrimEdge, "Recortar el borde");
	strcpy(sTwoPanels, "2 paneles");
	strcpy(sType, "tipo");
	strcpy(sTypeofmaterialfromwhichtocut, "Tipo de material del que cortar");
	strcpy(sTypesAreNotMatched, "¡No se realizó la optimización! Los materiales de las tablas de Piezas y Stock no coinciden. Solo se puede cortar una pieza del material con el mismo nombre en stock. Cambie el nombre de los materiales en las columnas correspondientes.");
	strcpy(sUndo, "Deshacer");
	strcpy(sUndoAccept, "Deshacer aceptar");
	strcpy(sUnits, "unidades");
	strcpy(sUnregisteredVersion, "No registrado");
	strcpy(sUpdates, "Actualizaciones");
	strcpy(sUsefulforwoodfurniture, "Útil para muebles de madera");
	strcpy(sUseit, "Utilícelo");
	strcpy(sUsePieceinOptimization, "Usar la pieza en optimizacion");
	strcpy(sUserName, "Nombre del usuario");
	strcpy(sUtilizationandWastes, "Utilización y retales");
	strcpy(sUtilizedArea, "Área de las partes utilizadas");
	strcpy(sUtilizedBars, "Barras utilizadas");
	strcpy(sUtilizeddemandcount, "Numero de partes utilizadas");
	strcpy(sUtilizedParts, "Partes utilizadas");
	strcpy(sUtilizedPieces, "Piezas utilizadas");
	strcpy(sUtilizedSheets, "Hojas utilizadas");
	strcpy(sValue, "Valor");
	strcpy(sValueGreaterEqualToZero, "Valor debe ser mayor o igual a cero");
	strcpy(sValueGreaterThanZero, "Valor debe ser mayor que cero");
	strcpy(sValueIntegerNumber, "¡El valor debe ser un número entero!");
	strcpy(sValueRealNumber, "Valor debe ser un numero decimal. Tal vez haya utilizado , en vez de . o viceversa. ¡Por favor arréglelo!");
	strcpy(s_The_number_is_too_big_or_it_has_too_many_digits_after_decimal_separator, "¡El número es demasiado grande o tiene demasiados dígitos después del separador decimal!");
	strcpy(s_The_number_is_too_big, "¡El número es demasiado grande!");
	strcpy(sVertical, "Vertica");
	strcpy(sWaste, "Chatarra");
	strcpy(sWastes, "Chatarra");
	strcpy(sWasteAddedToWarehouse, "La chatarra agregada al stock");
	strcpy(sWastelimits, "Limites para reta");
	strcpy(sWasteType, "Tipo de residuo");
	strcpy(sWeakoptimization, "Menor optimización");
	strcpy(sWhattoprint, "Qué debería imprimir");
	strcpy(s_What_to_print_or_save_to_file, "Qué imprimir o guardar en un archivo");
	strcpy(sWhattoprintoneachpiece, "Qué imprimir en cada pieza");
	strcpy(sWhattoshowoneachpiece, "¿Qué mostrar en cada pieza?");
	strcpy(sWidth, "Ancho");
	strcpy(sWood, "Madera");
	strcpy(sWorkingDirectory, "Directorio de trabajo");
	strcpy(sWrongKey, "Clave de registro incorrecta!");
	strcpy(sYes, "Sí");
	strcpy(sYoucannotchooseblackblueorredcolors, "No puede escoger colores negros, azules o rojos.");
	strcpy(sYouCannotMixFractionalDataWithDecimalOnes, "¡No puede mezclar valores fraccionarios con valores decimales!");
	strcpy(sYourcompany, "Su compañía");
	strcpy(sZip, "Código posta");
	strcpy(s_Set_the_origin_and_the_direction_of_the_axes, "Establecer el origen y la dirección de los ejes de coordenadas.");










	strcpy(s_Number_of_digits_after_the_decimal_separator, "Número de dígitos después del separador decimal");
	strcpy(s_Percentages, "Porcentajes");
}

