// Language strings: Vietnamese
// Author: Optimal Programs
// License: MIT License
//---------------------------------------------------------------------------
#include <string.h>
//---------------------------------------------------------------------------
#include "language_string_id.h"
//---------------------------------------------------------------------------
void set_vn(void)
{
	// Vietnamese
	// translated by a distributor
	// last update on: 2025.11.01.0
	
	strcpy(s_Area, "Diện tích");
	strcpy(s_Mass, "Khối lượng");
	strcpy(s_Advanced, "Trình độ cao");
	strcpy(s_Relative_coordinates, "Tọa độ tương đối");
	strcpy(s_Absolute_coordinates, "Tọa độ tuyệt đối");
	strcpy(s_Append_more_rows, "Nối thêm hàng");

	strcpy(s_Add_to_parts, "Thêm vào các bộ phận.");
	strcpy(s_Additional, "Thêm vào");
	strcpy(s_All_results, "Tất cả kết quả.");
	strcpy(s_Allow_movement_of_pieces, "Cho phép di chuyển các mảnh");
	strcpy(s_Allow_part_in_part, "Cho phép từng mảnh");
	strcpy(s_Invalid_piece_Angles_are_too_small_or_too_big_or_height_is_too_small, "Mảnh ghép không hợp lệ! Góc quá nhỏ hoặc quá lớn, hoặc chiều cao quá nhỏ.");
	strcpy(s_Append, "Nối thêm");
	strcpy(s_As_it_is, "Như nó là");
	strcpy(s_As_text, "Dưới dạng văn bản");
	strcpy(s_Ascending, "Tăng dần");
	strcpy(s_Automatic, "Tự động");
	strcpy(s_Cannot_connect_to_the_Internet_Please_visit_our_website_from_a_browser, "Không thể kết nối Internet! Vui lòng truy cập trang web của chúng tôi từ một trình duyệt.");
	strcpy(s_Cannot_copy_or_move_the_files, "Không thể sao chép hoặc di chuyển các tệp!");
	strcpy(s_Cannot_delete_the_file, "Không thể xóa tệp!");
	strcpy(s_Cannot_modify_old_results, "Không thể sửa đổi kết quả cũ!");
	strcpy(s_To_change_click_inside_a_cell_or_press_0_1_or_2, "Để thay đổi, hãy nhấp vào bên trong một ô hoặc nhấn 0, 1 hoặc 2.");
	strcpy(s_Cell, "Tế bào");
	strcpy(s_Click_on_the_table_header_to_change_the_columns, "Bấm vào tiêu đề bảng để thay đổi các cột.");
	strcpy(s_Close, "Đóng nó lại");
	strcpy(s_Contact_us, "Liên hệ chúng tôi");
	strcpy(s_Column, "Cột");
	strcpy(s_Comma, "dấu phẩy");
	strcpy(s_The_comma_symbol_cannot_simultaneously_be_the_list_separator_and_the_decimal_separator, "Dấu phẩy không thể vừa là dấu phân cách danh sách vừa là dấu phân cách thập phân!");
	strcpy(s_Copy, "Sao chép");
	strcpy(s_Copy_for_move, "Sao chép để di chuyển");
	strcpy(s_Cut_higher_level_strips_first, "Cắt các dải ở mức cao hơn trước");
	strcpy(s_Cut_index, "Hiển thị STT đường cắt");

	strcpy(s_The_data_have_been_changed_Do_you_want_to_save_them_to_a_file, "Dữ liệu đã được thay đổi. Bạn có muốn lưu chúng vào một tệp không?");
	strcpy(s_Decimal_separator, "Phân số thập phân");
	strcpy(s_Restore_default_settings, "Khôi phục cài đặt mặc định");
	strcpy(s_Delete_fiber, "Xóa sợi");
	strcpy(s_Descending, "Giảm dần");
	strcpy(s_Discard_changes, "Loại bỏ những thay đổi");

	strcpy(s_Delete_all_data, "Xóa tất cả dữ liệu?");
	strcpy(s_Dot, "chấm");
	strcpy(s_Do_you_want_to_delete_the_picture, "Bạn có muốn xóa hình ảnh?");
	strcpy(s_Do_you_want_to_delete_the_product, "Bạn có muốn xóa sản phẩm?");
	strcpy(s_Duplicate_and_append, "Nhân bản và nối thêm.");
	strcpy(s_Duplicate_values_are_ignored, "Các giá trị trùng lặp đã bị bỏ qua!");
	strcpy(s_Error, "lỗi");
	strcpy(s_Error_loading_file, "Lỗi khi tải tệp.");
	strcpy(s_export_everything, "Xuất mọi thứ");
	strcpy(s_Fit_to_screen, "Phù hợp với màn hình.");
	strcpy(s_Force_fixed_height, "Vẽ các mảnh có chiều cao cố định.");
	strcpy(s_Flipped, "lật");
	strcpy(s_Import, "Nhập khẩu");
	strcpy(s_If_angles_are_different_from_90_degrees_height_must_be_greater_than_0, "Nếu góc khác 90 độ thì chiều cao phải lớn hơn 0.");
	strcpy(s_Ignore, "Phớt lờ");
	strcpy(s_Incorrect_value, "Giá trị không chính xác");
	strcpy(s_Info, "Thông tin");
	strcpy(s_Interior, "Đồ nội thất");
	strcpy(s_Give_a_name, "Đưa một cái tên.");
	strcpy(s_Group, "Nhóm nó");
	strcpy(s_Header, "tiêu đề");
	strcpy(s_Keep_it_as_it_is, "Giữ nó như nó là");
	strcpy(s_Level, "Level");
	strcpy(s_Licensee, "Người được cấp phép");
	strcpy(s_List_separator, "Danh sách tách");
	strcpy(s_Made_with_love_in_Cugir_Romania, "Được thực hiện bằng tình yêu tại: Cugir, Romania");
	strcpy(s_Made_in, "Sản xuất tại");
	strcpy(s_Manufacturer, "nhà chế tạo");

	strcpy(s_Manual_arrange, "sắp xếp thủ công");

	strcpy(s_Mixed, "Trộn");
	strcpy(s_Multiple_shapes_detected_Next_rows_will_be_overwritten_Continue, "Nhiều hơn một hình dạng đã được phát hiện. Do đó, các hàng tiếp theo sẽ bị ghi đè. Tiếp tục?");
	strcpy(s_More, "Hơn");
	strcpy(s_Multiple_values, "Nhiều giá trị");
	strcpy(s_No_texture, "Không có kết cấu");
	strcpy(s_Number, "Con số");
	strcpy(s_Number_of_images, "Số lượng hình ảnh");
	strcpy(s_Number_of_vertices, "Số đỉnh");
	strcpy(s_Offset, "Bù lại");
	strcpy(s_Only_the_currently_selected_items, "Chỉ các mục hiện được chọn.");
	strcpy(s_Optimizing_please_wait, "Đang tối ưu hóa ... vui lòng đợi.");

	strcpy(s_Paste, "Paste");

	strcpy(s_Piece_label, "Nhãn");
	strcpy(s_Piece_size, "Kích thước mảnh");
	strcpy(s_Please_contact_us_by_email_if_you_receive_this_error, "Vui lòng liên hệ với chúng tôi qua email nếu bạn nhận được lỗi này.");
	strcpy(s_Please_save_it_first, "Làm ơn, lưu nó trước.");
	strcpy(s_Position, "Позиція");
	strcpy(s_Preview, "Xem trước");
	strcpy(s_Rectangle, "Hình chữ nhật");

	strcpy(s_Redo_the_last_operation, "Khôi phục thao tác cuối cùng");
	strcpy(s_Regular_polygon, "Đa giác đều");

	strcpy(s_Reused, "Tái sử dụng");
	strcpy(s_Rotated, "Xoay");
	strcpy(s_Save_all, "Lưu tất cả");
	strcpy(s_Scrap_label, "Nhãn của mảnh phế liệu");
	strcpy(s_Scrap_size, "Kích thước phế liệu");
	strcpy(s_Semicolon, "dấu chấm phẩy");
	strcpy(s_Show_cut_index, "Hiển thị STT đường cắt");
	strcpy(s_Show_information, "Hiển thị thông tin");
	strcpy(s_Show_piece_label, "Nhãn");
	strcpy(s_Show_scrap_label, "Nhãn của mảnh phế liệu");
	strcpy(s_Show_scrap_s_size_on_the_small_pieces, "Hiển thị kích thước phế liệu trên các mảnh nhỏ");
	strcpy(s_Show_size_of_pieces, "Kích thước mảnh");
	strcpy(s_Show_size_of_scrap, "Kích thước phế liệu");
	strcpy(s_Show_sizes, "Hiển thị kích thước");
	strcpy(s_Show_label, "Hiển thị nhãn");
	strcpy(s_Show_length, "Hiển thị thời lượng");

	strcpy(s_Some_numerical_values_are_incorrect_Should_I_fix_all_the_incorrect_values, "Một số giá trị số không chính xác! Tôi có nên sửa tất cả các giá trị không chính xác không?");
	strcpy(s_Some_invalid_values_have_been_removed, "Một số giá trị không hợp lệ đã bị xóa.");
	strcpy(s_Sort_by, "Sắp xếp theo");
	strcpy(s_Sort_ascending_by, "Sắp xếp tăng dần theo");
	strcpy(s_Sort_descending_by, "Sắp xếp giảm dần theo");
	strcpy(s_Start, "Start");
	strcpy(s_Starting_angle, "Góc bắt đầu");

	strcpy(s_Sticker, "Nhãn dán");
	strcpy(s_Stock, "TỒN KHO");
	strcpy(s_Stop, "Stop");
	strcpy(s_System_setting, "Cài đặt hệ thống");
	strcpy(s_Tabular, "Bảng");
	strcpy(s_Total, "Toàn bộ");
	strcpy(s_Total_size, "Tổng kích thước");
	strcpy(s_Terms_of_the_license, "Điều khoản của giấy phép");
	strcpy(s_The_current_product_has_been_changed_Do_you_want_to_save_it_to_file, "Sản phẩm hiện tại đã được sửa đổi. Bạn có muốn lưu nó vào tệp không?");
	strcpy(s_The_value_is_out_of_the_allowed_range, "Giá trị nằm ngoài phạm vi cho phép.");
	strcpy(s_The_value_must_be_a_real_or_fractional_number_Try_to_replace_the_comma_with_the_dot_if_you_want_to_enter_a_real_number, "Giá trị phải là số thực hoặc số phân số. Hãy thử thay thế dấu phẩy bằng dấu chấm nếu bạn muốn nhập số thực.");
	strcpy(s_This_feature_is_not_implemented_yet, "Tính năng này chưa được triển khai.");
	strcpy(s_This_operation_cannot_be_reversed, "Không thể hoàn tác thao tác này.");
	strcpy(s_Undo_the_last_operation, "Hoàn tác thao tác cuối cùng.");
	strcpy(s_Utilization, "Sử dụng");
	strcpy(s_Utilized_Stock, "Cổ phiếu sử dụng");
	strcpy(s_Version, "Phiên bản");
	strcpy(s_Visible_columns, "Cột có thể nhìn thấy");
	strcpy(s_You_already_have_the_latest_version_installed, "Bạn đã cài đặt phiên bản mới nhất!");
	strcpy(s_What_is_exported, "Cái gì được xuất khẩu?");
	strcpy(s0meansanynumberofpieces, "Số 0 có nghĩa là bất kỳ số lượng các mảnh cắt");
	strcpy(sAbout, "Thông tin sản phẩm");
	strcpy(sAccept, "Chấp nhận");
	strcpy(sAcceptall, "Chấp nhận tất cả");
	strcpy(sAcceptthecurrentsolution, "Chấp nhận giải pháp hiện tại");
	strcpy(sAdd, "Thêm");
	strcpy(sAddapiece, "Thêm mảnh cắt");
	strcpy(sAddasimpleproducttoDemand, "Thêm một sản phẩm vào danh sách bộ phận hiện có.");
	strcpy(sAddgrindingthicknesstopartsize, "Thêm độ dày lớp mài vào kích thước của mảnh cắt");
	strcpy(sAddproductnametolabel, "Thêm tên sản phẩm vào nhãn");
	strcpy(sAddress, "Địa chỉ");
	strcpy(sAddselectedsizetoInventory, "Thêm kích thước đã chọn vào tồn kho.");
	strcpy(sAdhesivelabels, "Nhãn dính");
	strcpy(sAdhesivelabelwithinformationaboutpiecesinDemandCustomernameLabelSizeCurrentData, "Nhãn dính về mảnh cắt bao gồm các thông tin: Tên khách hàng, Nhãn, Kích thước, Dữ liệu hiện tại, v.v.");
	strcpy(sAdhesivelabelwithinformationaboutsheetsinInventory, "Nhãn dính về các tấm vật liệu trong danh sách tồn kho");
	strcpy(sAll, "Tất cả");
	strcpy(sAlloffcutswhichhavethesizegreaterthanthisvaluewillbeaddedtoInventory, "Tất cả các mảnh vật liệu lớn hơn giá trị này sẽ được thêm vào Danh sách tồn kho");
	strcpy(sAllowMirroring, "Cho phép lật");
	strcpy(sAllowRotation, "Cho phép xoay");
	strcpy(sAllPieces, "Tất cả các mảnh cắt");
	strcpy(sAllpredefinedproducts, "Tất cả các sản phẩm được xác định trước");
	strcpy(sAnewwindowwillbedisplayedwheretheusercansettheedgebandsforeachedge, "Một cửa sổ mới sẽ được hiển thị nơi người dùng có thể đặt độ dày dải cạnh cho mỗi cạnh.");
	strcpy(sAnewwindowwillbedisplayedwheretheusercansetthegrindingvalueforeachedgeofthsheet, "Một cửa sổ mới sẽ được hiển thị nơi người dùng có thể đặt kích thước cần mài cho mỗi cạnh của mảnh cắt.");
	strcpy(sAnewwindowwillbedisplayedwheretheusercansetthetrimvalueforeachedgeofthsheet, "Một cửa sổ mới sẽ được hiển thị nơi người dùng có thể đặt giá trị cắt bỏ cho mỗi cạnh của mảnh.");
	strcpy(sAngle, "Góc");
	strcpy(sAngles, "Các góc");
	strcpy(sAnoptimizationparameterisarealnumber, "Tham số tối ưu hóa là một số thực.");
	strcpy(sAnoptimizationparameterisfractionalnumber, "Tham số tối ưu hóa là số phân số.");
	strcpy(sAnyShape, "Hình dạng thật");
	strcpy(sApolygonmusthaveatleast2vertices, "Một đa giác phải có ít nhất 2 đỉnh!");
	strcpy(sApolygonmusthaveatleast3vertices, "Một đa giác phải có ít nhất 3 đỉnh!");
	strcpy(sApplication_fails_to_initialize, "Ứng dụng không khởi chạy được!");
	strcpy(sArc, "Cung");
	strcpy(sArcLength, "Độ dài cung");
	strcpy(sAreaofusedsheets, "Diện tích sử dụng tấm vật liệu");
	strcpy(sAshortdescriptionofthesheet, "Mô tả ngắn về tấm vật liệu");
	strcpy(sAtleastonepart, "Bạn phải nhập ít nhất thông tin của một mảnh cắt.");
	strcpy(sAtTheMarginOfTheSheet, "Tại lề của tấm vật liệu");
	strcpy(sBandtypes, "Các loại dải cạnh");
	strcpy(sBar, "Thanh vật liệu");
	strcpy(sBars, "Thanh vật liệu");
	strcpy(sBothsizesoftheoffcutsmustbegreaterthanthisvalue, "Cả hai kích thước của mảnh phế liệu phải lớn hơn giá trị này.");
	strcpy(sBottom, "Dưới");
	strcpy(sBottomcoordinateofthedefect, "Tọa độ cạnh dưới của vùng khuyết tật");
	strcpy(sBreakCut, "Hủy đường cắt");
	strcpy(sBrowse, "Duyệt");
	strcpy(sBuy, "Mua");
	strcpy(sBuynow, "Mua ngay ...");
	strcpy(sCancel, "Hủy");
	strcpy(sCannotBeEmpty, "không được để trống");
	strcpy(sCannotmovepartsbetweensheetswhenidenticalsheetsaregroupedPleaseungroupthesheetsfrommenu, "Không thể di chuyển các bộ phận từ tấm này sang tấm khác nếu các tấm vật liệu giống hệt nhau được nhóm lại. Vui lòng hủy nhóm các tấm vật liệu từ menu.");
	strcpy(sCannotSaveFile, "Không thể lưu tệp");
	strcpy(sCenter, "Tâm");

	strcpy(sChangeDirection, "Thay đổi hướng cắt");
	strcpy(sChoose, "Chọn");
	strcpy(sChooseProduct, "Chọn sản phẩm");
	strcpy(sCircle, "Hình tròn");
	strcpy(sCity, "Thành phố");
	strcpy(sClear, "Xóa");
	strcpy(sClockWise, "Theo chiều kim đồng hồ");
	strcpy(sClosewindow, "Đóng cửa sổ");
	strcpy(sColor, "Màu sắc");
	strcpy(sColorofedgeband, "Màu của các dải cạnh");
	strcpy(sColorPattern, "Màu sắc/ Họa tiết");
	strcpy(sColorpiecesandwastes, "Tô màu các mảnh cắt và phế liệu");
	strcpy(sColumns, "Cột");
	strcpy(sComment, "Ghi chú");
	strcpy(sCompanyname, "Tên công ty");
	strcpy(sComplexMaterialExists, "Tên của vật liệu đã được khai báo trong danh sách các vật liệu. Xin vui lòng cho nó một tên mới.");
	strcpy(sComputerCode, "Mã máy tính");
	strcpy(sComputerCodefromyourcomputer, "Mã máy tính (từ máy tính của bạn)");
	strcpy(sComputethetotalpriceofDemand, "Tính tổng giá của các bộ phận");
	strcpy(sContents, "Nội dung");
	strcpy(sContinutComanda, "Nội dung của các bộ phận được cắt trong ngày");
	strcpy(sContinutDepozit, "Nội dung của danh sách tồn kho trong ngày");
	strcpy(sConversionIsDoneOnlyWhenSomePiecesHaveFractionalValues, "Chuyển đổi chỉ được thực hiện khi các mảnh cắt có giá trị phân số.");
	strcpy(sConvertsTheSizeOfWasteToAFractionalUnit, "Hiển thị kích thước của phế liệu dưới dạng giá trị phân số.");
	strcpy(sCouldNotSaveFile1, "Không thể ghi tập tin trong thư mục");
	strcpy(sCouldNotSaveFile2, "Bạn có thể không có đủ quyền. Vui lòng kiểm tra hoặc thay đổi thư mục làm việc từ menu Cài đặt | Thư mục làm việc vào một thư mục khác mà bạn có quyền ghi (ví dụ: c: \\ temp).");
	strcpy(sCreationdateYMDHMS, "Ngày tạo (Y / M / D H: M: S)");
	strcpy(sCurrentDate, "Ngay hiện tại");
	strcpy(sCurrentDiagram, "Sơ đồ hiện tại");
	strcpy(sCurrentMaterial, "Vật liệu hiện đang sử dụng");
	strcpy(sCurrentversion, "Phiên bản hiện tại");
	strcpy(sCurve_not_closed_Try_increasing_DXF_linking_distance_parameter, "Đường bao mảnh cắt không được khép kín! Hãy thử tăng tham số khoảng cách liên kết DXF.");
	strcpy(sCustomer, "khách hàng");
	strcpy(sCustomerName, "Tên khách hàng");
	strcpy(sCustomMessage, "Thông báo tùy chỉnh");
	strcpy(sCutlength, "Chiều dài của đường cắt");
	strcpy(sCut, "Cắt");
	strcpy(sCuts, "Đường cắt");
	strcpy(sCutterThickness, "Độ rộng đường cắt");
	strcpy(sData, "Dữ liệu");
	strcpy(sDataCannotBeEmpty, "Dữ liệu không thể để trống!");
	strcpy(sDateymdhms, "Ngày (y / m / d / h / m / s)");
	strcpy(sDays_left_for_trial, "Ngày còn lại để dùng thử");
	strcpy(sDaysLeft, "ngày còn lại");
	strcpy(sStandard, "Mặc định");
	strcpy(sDefaultInterface, "Giao diện mặc định");
	strcpy(sDefects, "Vùng khuyết tật");
	strcpy(sDefectsManager, "Quản lý vùng khuyết tật");
	strcpy(sDefectsofthematerialNopiecescanbeplacedinthefaultyzone, "Các vùng khuyết tật của vật liệu. Không được đặt các mảnh cắt trong vùng khuyết tật.");
	strcpy(sDelete, "Xóa");
	strcpy(sDeletePiece, "Xóa mảnh cắt");
	strcpy(sDeleteRow, "Xóa dòng");
	strcpy(sDemandutilization, "Sử dụng các mảnh cắt bộ phận");
	strcpy(sDepozitulmodificat, "Các mảnh cắt được sử dụng đã được gỡ bỏ. Các phế liệu đã được thêm vào danh sách tồn kho.");
	strcpy(sDepozitvid, "Không có tồn kho");
	strcpy(sDesk, "bàn");
	strcpy(sDiagram, "Sơ đồ cắt");
	strcpy(sDiagrams, "Sơ đồ");
	strcpy(sDiagramasatable, "Sơ đồ cắt dạng bảng");
	strcpy(sDigits, "chữ số");
	strcpy(sDimensiuniplaca, "Kích thước của tấm vật liệu");
	strcpy(sDirection, "Hướng cắt");
	strcpy(sDistanceBetweenRows, "Khoảng cách giữa các dòng");
	strcpy(sDonotuseit, "Không được sử dụng");
	strcpy(sDownload, "Tải xuống");
	strcpy(sDoYouWantToClearTheData, "Bạn có muốn xóa dữ liệu?");
	strcpy(sDoYouWantToSaveDemand, "Danh sách các mảnh cắt bộ phận đã thay đổi! Bạn có muốn lưu các thay đổi?");
	strcpy(sDoYouWantToSaveParts, "Bạn có muốn lưu danh sách các mảnh cắt bộ phận?");
	strcpy(sDoYouWantToSaveRepository, "Danh sách tồn kho đã được thay đổi! Bạn muốn lưu các thay đổi?");
	strcpy(sDrawing, "Đang vẽ");
	strcpy(sDrawthesolutioncolorful, "Vẽ giải pháp đầy màu sắc");
	strcpy(sDuplicateTypes, "Một số loại bị trùng lặp! Vui lòng loại bỏ");
	strcpy(sDuplicateTypesWithComplex, "Một số tên của vật liệu đã tồn tại trong danh sách vật liệu hiện có! Vui lòng loại bỏ sự trùng lặp");
	strcpy(sDuplicateValues, "Giá trị bị trùng lặp");
	strcpy(sEdgeband, "Dải cạnh");
	strcpy(sEdgebandingwhichisplacedontheedgesofyourpiecePleasedefineedgebandingtypesfromMaterialsEdgeBandingmenu, "Các dải cạnh được dán trên lề của mảnh cắt. Vui lòng khai báo thông tin các dải cạnh trong menu Vật liệu.");
	strcpy(sEdgebandsthatwillbeappliedtoeachpart, "Các dải cạnh được áp dụng cho mỗi mảnh cắt.");
	strcpy(sEdgeBandTolerance, "Dung sai cho các dải cạnh");
	strcpy(sEdgesthatmustbecutduefaults, "Các cạnh phải được cắt bỏ vì các khuyết tật.");
	strcpy(sEdgetoedge, "Từ cạnh này sang cạnh kia");
	strcpy(sEdit, "Chỉnh sửa");
	strcpy(sEmail, "E-mail");
	strcpy(sEmptyData, "Dữ liệu trống rỗng!");
	strcpy(sEnabled, "Đã bật");
	strcpy(sEnabledisabledefectsoftheinventorysheets, "Kích hoạt / vô hiệu hóa các mảnh vật liệu khuyết tật của danh sách tồn kho");
	strcpy(sEnterLabel, "Nhập thẻ thông tin");
	strcpy(sEnterTheMaterialName, "Nhập tên của vật liệu");
	strcpy(sEnterTheProductName, "Nhập tên của sản phẩm");
	strcpy(sEvaluationError, "Lỗi biểu thức!");
	strcpy(sExit, "Thoát");
	strcpy(sExpired, "Phiên bản dùng thử đã hết hạn! Vui lòng đăng ký phần mềm!");
	strcpy(sExport, "Xuất dữ liệu");
	strcpy(sExportAllDiagrams, "Xuất tất cả các sơ đồ cắt");
	strcpy(sExportAllToASingleFile, "Xuất tất cả vào một tệp");
	strcpy(sExportOptions, "Tùy chọn xuất dữ liệu");
	strcpy(sExporttoDXFformat, "Xuất sang định dạng DXF");
	strcpy(sExporttoExcel, "Xuất sang Excel");
	strcpy(sExpresieIncorecta, "Biểu thức toán học không chính xác!");
	strcpy(sExtensions, "Extensions");
	strcpy(sExtra, "Phụ kiện");
	strcpy(sExtraComponents, "Phụ kiện");
	strcpy(sExtracomponentsattachedtoDemand, "Phụ kiện đi kèm với các bộ phận");
	strcpy(sFile, "Tập tin");
	strcpy(sFileName, "Tên tệp");
	strcpy(sFillWastes, "Vẽ các mảnh phế liệu với các đường xiên");
	strcpy(sFindoptimalbarsheetsize, "Tìm kích thước tối ưu cho thanh và tấm vật liệu.");
	strcpy(sFindoptimalsizeofInventorypieces, "Tìm kích thước tối ưu của các mảnh cắt được lưu kho");
	strcpy(sFirstcutMultiplestages, "Hướng cắt đầu tiên để tối ưu khi cắt nhiều giai đoạn.");
	strcpy(sFirstdirectionforcutishorizontal, "Hướng đầu tiên để cắt là ngang.");
	strcpy(sFirstdirectionforcutisvertical, "Hướng đầu tiên để cắt là dọc.");
	strcpy(sFollowthecontourofpieces, "Theo đường bao của các mảnh cắt");
	strcpy(sFont, "Phông chữ");
	strcpy(sFontsize, "Cỡ chữ");
	strcpy(sFullInfo, "Toàn bộ thông tin");
	strcpy(sDisposedWaste, "xử lý chất thải");
	strcpy(sGeneral, "Chung");
	strcpy(sGenerateCNC, "Tạo CNC");
	strcpy(sGrain, "Thớ gỗ");
	strcpy(sGraindirection, "Sợi");
	strcpy(sGraphic, "Đồ họa");
	strcpy(sGreaterorequalto, "Lớn hơn hoặc bằng");
	strcpy(sGrid, "Bảng");
	strcpy(sGrinding, "Mài");
	strcpy(sGrosimeTaieturaScalata, "Độ dày đường cắt từ hình ảnh này có thể khác với thực tế vì các mảnh cắt không được thể hiện ở quy mô thực của chúng. Thực tế này không ảnh hưởng đến kết quả.");
	strcpy(sGroupidenticallayouts, "Nhóm các tấm vật liệu giống hệt nhau");
	strcpy(sGroupIdenticalParts, "Nhóm mảnh cắt bộ phận giống hệt nhau");
	strcpy(sGroupingOfIdenticalPiecesIntoOneRow, "Nhóm các mảnh cắt bộ phận giống hệt nhau thành một hàng.");
	strcpy(sGroupPartsAfterLoadingFromFile, "Nhóm các mảnh cắt bộ phận khi tải từ tập tin");
	strcpy(sHeight, "Cao");
	strcpy(sHeighttolerance, "Dung sai cho chiều cao");
	strcpy(sHelp, "Trợ giúp");
	strcpy(sHistory, "Lịch sử");
	strcpy(sHorizontal, "Ngang");
	strcpy(sHowtodisplayprintedgebands, "Cách hiển thị các dải cạnh?");
	strcpy(sIfyousetthebandforoneedgeallwillreceivethesamevalue, "Nếu bạn đặt độ dày dải cạnh cho một cạnh, tất cả các cạnh còn lại sẽ nhận được cùng một giá trị.");
	strcpy(sIfyousetthegrindingforoneedgeallwillreceivethesamevalue, "Nếu bạn đặt giá trị độ dày cần mài cho một cạnh, tất cả các cạnh sẽ nhận được cùng một giá trị.");
	strcpy(sIfyousetthetrimforoneedgeallwillreceivethesamevalue, "Nếu bạn đặt độ rộng cần cắt bỏ cho một cạnh, tất cả các cạnh sẽ nhận được cùng một giá trị.");
	strcpy(sImageBounds, "Đường viền cho hình ảnh");
	strcpy(sImageSize, "Kích thước ảnh");
	strcpy(sImportData, "Nhập dữ liệu");
	strcpy(sIncorrectPassword, "mật khẩu không đúng");
	strcpy(sIndex, "STT");
	strcpy(sInformationaboutcustomer, "Thông tin về khách hàng");
	strcpy(sInputALanguageName, "Nhập tên của ngôn ngữ");
	strcpy(sInsert, "Chèn");
	strcpy(sInsertPiece, "Chèn mảnh cắt");
	strcpy(sInterface, "Giao diện");
	strcpy(sInterfaceSettings, "Cài đặt giao diện");
	strcpy(sInvalidHardware, "Tôi không thể phát hiện phần cứng. Vui lòng liên hệ với chúng tôi tại contact@optimalprograms.com");
	strcpy(sInvalidNumber, "Giá trị nhập không hợp lệ");
	strcpy(sInvalidOrderOfComputation, "Một trình tự để tính toán độ dài không thể được thiết lập. Có những mối quan hệ khép kín trong định nghĩa sản phẩm!");
	strcpy(sInvalidRegistration, "Đăng ký không hợp lệ!");
	strcpy(sInvalidTime, "Thời gian hệ thống của bạn không hợp lệ.");
	strcpy(sInventory, "TỒN KHO");
	strcpy(sisafractionalvalue, "là một giá trị phân số.");
	strcpy(sIsArc, "Là một cung");
	strcpy(sisarealvalue, "là một số thực.");
	strcpy(sLabel, "Nhãn");
	strcpy(sLabels, "Nhãn");
	strcpy(sLanguage, "Ngôn ngữ");
	strcpy(sLatimeanumar0, "Chiều rộng phải lớn hơn 0!");
	strcpy(sLatimeanumarreal, "Chiều rộng phải là một số thực!");
	strcpy(sLayerName, "Tên lớp cắt");
	strcpy(sLeft, "Trái");
	strcpy(sLeftcoordinateofthedefect, "Các tọa độ bên trái của vùng khuyết tật");
	strcpy(sLength, "Chiều dài");
	strcpy(sLengthofthepiecestocut, "Kích thước mảnh cắt");
	strcpy(sLengthofthepiecestocutfrom, "Kích thước tấm vật liệu để cắt");
	strcpy(sLengthofusedbars, "Kích thước của các thanh vật liệu được sử dụng");
	strcpy(sLicenseAgreement, "Thỏa thuận cấp phép");
	strcpy(sLinear, "Đoạn thẳng");
	strcpy(sLinethickness, "Độ rộng của nét bút");
	strcpy(sLoadafileandappenddatatothecurrentDemand, "Tải một tập tin và nối dữ liệu vào danh sách các bộ phận hiện tại.");
	strcpy(sLoadanexistingDemandfromafile, "Tải danh sách các bộ phận hiện có từ tập tin.");
	strcpy(sLoadAppend, "Tải và nối thêm");
	strcpy(sLoadEverything, "Tải tất cả mọi thứ");
	strcpy(sLoadInventory, "Tải danh sách tồn kho");
	strcpy(sLoadInventoryandDemand, "Tải danh sách tồn kho và các bộ phận");
	strcpy(sLoadResults, "Tải kết quả");
	strcpy(sLocked, "Đã khóa");
	strcpy(sLogo, "Logo");
	strcpy(sLong, "Dài");
	strcpy(sLongerexecutiontime, "Thời gian chạy lâu hơn");
	strcpy(sLungime, "Chiều dài");
	strcpy(sLungimeanumar0, "Độ dài phải lớn hơn 0!");
	strcpy(sLungimeanumarreal, "Độ dài phải là một số thực!");
	strcpy(sLungimeaTotalaFolosita, "Tổng chiều dài sử dụng");
	strcpy(sMagnification, "Độ phóng đại");
	strcpy(sMagnify, "Phóng đại");
	strcpy(sMargins, "Lề");
	strcpy(sMarginsForPaper, "Lề giấy in");
	strcpy(sMarginsOfTheLabel, "Lề của nhãn in");
	strcpy(sMaterial, "Vật liệu");
	strcpy(sMaterialName, "Tên của vật liệu");
	strcpy(sMaterials, "Nguyên vật liệu");
	strcpy(sMaterialstypes, "Các loại vật liệu");
	strcpy(sMax, "Tối đa");
	strcpy(sMaximalArea, "Diện tích tối đa");
	strcpy(sMaximalCutLength, "Chiều dài cắt tối đa");
	strcpy(sMaxlength, "Độ dài tối đa");
	strcpy(sMaxPiecesperBar, "Số lượng cắt tối đa trên mỗi thanh vật liệu");
	strcpy(sMaxwidth, "chiều rộng tối đa");
	strcpy(sMeasurementUnit, "Đơn vị đo lường");
	strcpy(sMin, "Tối thiểu");
	strcpy(sMinimalBreakSize, "Kích thước phá vỡ tối thiểu");
	strcpy(sMinimalUsefulSize, "Kích thước có thể sử dụng tối thiểu");
	strcpy(sMinimalwastesizetoInventory, "Kích thước phế liệu tối thiểu được thêm vào danh sách tồn kho.");
	strcpy(s_What_to_minimize, "Những gì để giảm thiểu?");
	strcpy(sMinlength, "Chiều dài tối thiểu");
	strcpy(sMinwidth, "Chiều rộng tối thiểu");
	strcpy(sMirror, "Đối xứng");
	strcpy(sMirroring, "Lấy đối xứng");
	strcpy(sMiscellaneous, "Các kết quả thống kê khác");
	strcpy(sModify, "Sửa đổi");
	strcpy(sModifytheselectedpiece, "Sửa đổi mảnh cắt đã chọn");
	strcpy(sMovePiece, "Di chuyển mảnh cắt");
	strcpy(sMultiplestages, "Thực hiện cắt nhiều giai đoạn");
	strcpy(sName, "Tên");
	strcpy(sNameofedgeband, "Tên của dải cạnh");
	strcpy(sNewDEMANDUnsaveddatawillbelost, "Có phát sinh mảnh cắt bộ phận mới? Dữ liệu chưa lưu sẽ bị mất!");
	strcpy(sNewLanguage, "Ngôn ngữ mới");
	strcpy(sNewMaterial, "Vật liệu mới");
	strcpy(sNewPasswordincorectlyintroduced, "Mật khẩu mới được giới thiệu không chính xác!");
	strcpy(sNewProduct, "Sản phẩm mới");
	strcpy(sNewversion, "Phiên bản mới");
	strcpy(sNo, "Không");
	strcpy(sNumarBucati, "Số lượng các mảnh cắt");
	strcpy(sNumberOfCopies, "Số bản sao");
	strcpy(sNumberofstages, "Số giai đoạn cắt");
	strcpy(sNusuficienteplacidepozit, "Không phải tất cả các mảnh cắt đã được tối ưu hóa. Nguyên nhân có thể: Không có đủ mảnh cắt trong danh sách tồn kho; Các mảnh cắt không được kích hoạt; Chất liệu của các mảnh cắt và tồn kho là khác nhau; Các thông số khác đã được đặt không chính xác.");
	strcpy(sOfficeNotInstaled, "Microsoft Office chưa được cài đặt vào máy tính của bạn hoặc cài đặt phiên bản không chính xác!");
	strcpy(sOldpassworddoesnotmatch, "Mật khẩu cũ không khớp!");
	strcpy(sOnlinehelp, "Trợ giúp trực tuyến");
	strcpy(sOnlypiecesofthesameheightinthelaststage, "Những mảnh cắt có cùng chiều cao sẽ được cắt trong giai đoạn cuối");
	strcpy(sOpen, "Mở");
	strcpy(sOptimization, "Tối ưu hóa");
	strcpy(sOptimizationDone, "Đã thực hiện tối ưu hóa! Bạn có thể in hoặc lưu các sơ đồ cắt thu được. Nhấn nút Chấp nhận nếu bạn hài lòng với giải pháp hiện tại. Nếu không, nhấn Bắt đầu lại.");
	strcpy(sOptimizationType, "Loại tối ưu hóa");
	strcpy(sOptions, "Tùy chọn");
	strcpy(sOptionsrelatedtotheinterface, "Các tùy chọn liên quan đến giao diện");
	strcpy(sor, "hoặc là");
	strcpy(sOthercomponents, "Các thành phần khác");
	strcpy(sOthers, "Khác");
	strcpy(sOtherstatistics, "Thống kê khác");
	strcpy(sOverrideExcelCSVfiles, "Ghi đè tệp Excel / CSV");
	strcpy(sParameter, "Tham số");
	strcpy(sParts, "MẢNH CẮT");
	strcpy(sPattern, "Họa tiết nền");
	strcpy(sPatternforwaste, "Họa tiết nền đối với các mảnh phế liệu");
	strcpy(sPerimeter, "Chu vi");
	strcpy(sPermitedRotationAngle, "Góc quay được phép");
	strcpy(sPhone, "Điện thoại");
	strcpy(sPicture, "Hình ảnh");
	strcpy(sPiece, "Mảnh cắt");
	strcpy(sPieceindex, "Số thứ tự mảnh cắt");
	strcpy(sPieces, "Mảnh cắt");
	strcpy(sPiecesize, "Kích thước mảnh cắt");
	strcpy(sPiecesizelabeledgebandwillbeprinted, "Kích thước mảnh cắt, nhãn, dải cạnh sẽ được in.");
	strcpy(sPierdere, "Phế liệu");
	strcpy(sPixels, "điểm ảnh");
	strcpy(sPlacilefolositeDepozit, "Tận dụng các mảnh vật liệu từ tồn kho.");
	strcpy(sPlease_contact_us_at_contact_nestingtechnologies_com, "Vui lòng liên hệ với chúng tôi tại contact@nesting-technology.com");
	strcpy(sPlease_contact_us_at_contact_optimalprograms_com, "Vui lòng liên hệ với chúng tôi tại contact@optimalprograms.com");
	strcpy(sPleaseenteralldataeitherasfractionalorrealDonotmixthem, "Vui lòng nhập tất cả dữ liệu dưới dạng phân số hoặc số thực! Đừng trộn lẫn chúng!");
	strcpy(sPleaseEnterSomeTypesOfMaterials, "Không có loại vật liệu được bạn chỉ định. Bạn có thể khai báo chúng từ menu Vật liệu.");
	strcpy(sPleasesendtheNameandtheCodetotheaddresscontactoptimalprogramscominordertoobtaintheRegistrationKey, "Để có được Khóa đăng ký, vui lòng gửi Tên và Mã tới: contact@optimalprograms.com.");
	strcpy(sPolygon, "Đa giác");
	strcpy(sPolygonsCircles, "Đa giác, hình tròn");
	strcpy(sPrecision, "Độ chính xác");
	strcpy(sPretulnumar0, "Giá phải là một số lớn hơn 0!");
	strcpy(sPretulnumarreal, "Giá phải là một số thực!");
	strcpy(sPreview, "Xem trước");
	strcpy(sPrice, "Giá");
	strcpy(sPriceMustBeGreaterThanZero, "Giá phải là một số lớn hơn 0!");
	strcpy(sPriceofbars, "Giá các thanh vật liệu");
	strcpy(sPriceperbar, "Giá mỗi thanh vật liệu");
	strcpy(sPricepersheet, "Giá mỗi tấm vật liệu");
	strcpy(sPricepersquareunitofmaterial, "Giá mỗi đơn vị diện tích của vật liệu");
	strcpy(sPriceperunit, "Giá mỗi đơn vị theo chiều dài");
	strcpy(sPrint, "In");
	strcpy(sPrintdiagramsastables, "In sơ đồ cắt dưới dạng bảng.");
	strcpy(sPrinter, "Máy in");
	strcpy(sPrinterBounds, "Lề cho máy in");
	strcpy(sPrinting, "In ấn");
	strcpy(sPrintonlyutilizedarea, "Chỉ in khu vực vật liệu sử dụng");
	strcpy(sPrintthecontentsoftheDemand, "In nội dung của danh sách các mảnh cắt bộ phận.");
	strcpy(sPrintthecontentsoftheInventory, "In nội dung của danh sách tồn kho.");
	strcpy(sPrintthecurrentsolution, "In các giải pháp hiện tại.");
	strcpy(sPriority, "Mức độ ưu tiên");
	strcpy(sPrioritytocutapieceZero0isthehighestpriority, "Mức độ ưu tiên cắt đối với một mảnh cắt. Không (0) là ưu tiên cao nhất.");
	strcpy(sProcentul0100, "Phần trăm phải lớn hơn 0 và nhỏ hơn hoặc bằng 100!");
	strcpy(sProcentulnumarreal, "Phần trăm phải là số thực!");
	strcpy(sProductdefinition, "Khai báo sản phẩm");
	strcpy(sProductExists, "Sản phẩm đã tồn tại. Chọn một tên khác.");
	strcpy(sProductName, "Tên sản phẩm");
	strcpy(sProducts, "Sản phẩm");
	strcpy(sProducts, "Sản phẩm");
	strcpy(sProject, "Dự án");
	strcpy(sProperties, "Các thuộc tính");
	strcpy(sProperty, "Thuộc tính");
	strcpy(sQuantity, "Số lượng");
	strcpy(sQuantitynumberofsheetsofthistype, "Số tấm vật liệu loại này");
	strcpy(sRadius, "Bán kính");
	strcpy(sRectangular, "Hình chữ nhật");
	strcpy(sRedefinetypesofedgeband, "Xác định lại các loại dải cạnh");
	strcpy(sRedefinetypesofmaterial, "Xác định lại các loại vật liệu");
	strcpy(sRegistration, "Đăng ký");
	strcpy(sRegistrationKeyfromOptimalPrograms, "Mã đăng kí");
	strcpy(sRegistrationSuccessful, "Đăng ký đã thành công!");
	strcpy(sRemoveallpiecesinInventory, "Loại bỏ tất cả các mảnh vật liệu trong danh sách tồn kho.");
	strcpy(sRemoveCut, "Xóa đường cắt");
	strcpy(sRemovetheselectedpiece, "Xóa mảnh cắt đã chọn");
	strcpy(sReports, "Báo cáo");
	strcpy(sRequestedMaterial, "Vật liệu yêu cầu");
	strcpy(sRestore, "Khôi phục");
	strcpy(sResults, "Kết quả");
	strcpy(sReusedwaste, "Các mảnh vật liệu thừa có thể tái sử dụng");
	strcpy(sRight, "Phải");
	strcpy(sRightcoordinateofthedefect, "Tọa độ bên phải của vùng khuyết tật");
	strcpy(sRotation, "Quay");
	strcpy(sRotationAngle, "Góc quay");
	strcpy(sRotationStep, "Bước quay");
	strcpy(sRoundAllFractionsTo, "Các giá trị phân số phải được làm tròn thành");
	strcpy(sRow, "dòng");
	strcpy(sRows, "Dòng");
	strcpy(sRun, "Giải pháp mới nhất");
	strcpy(sRunningtime, "thời gian chạy");
	strcpy(sSameforall, "Giống nhau cho tất cả");
	strcpy(sSave, "Lưu");
	strcpy(sSaveAllImages, "Lưu tất cả hình ảnh");
	strcpy(sSaveAs, "Lưu thành");
	strcpy(sSaveChanges, "Các mảnh cắt bộ phận đã được thay đổi. Bạn có muốn lưu chúng không?");
	strcpy(sSaveCurrentImage, "Lưu hình ảnh hiện tại");
	strcpy(sSavedataparameters, "Lưu dữ liệu và tham số");
	strcpy(sSaveEverything, "Lưu tất cả mọi thứ");
	strcpy(sSaveInventory, "Lưu kho");
	strcpy(sSaveInventoryandDemand, "Lưu kho và các bộ phận");
	strcpy(sSaveResults, "Lưu kết quả");
	strcpy(sSaveStatisticsinafile, "Lưu số liệu thống kê vào một tập tin");
	strcpy(sSavethecurrentimage, "Lưu hình ảnh hiện tại");
	strcpy(sSavethecurrentimageorstatistic, "Lưu hình ảnh hiện tại hoặc số liệu thống kê");
	strcpy(sSavetheDEMANDinafile, "Lưu vào tập tin");
	strcpy(sSavetheDemandinafilewithadifferentname, "Lưu các danh sách các mảnh cắt bộ phận trong một tập tin với một tên khác.");
	strcpy(sSavetheREPOSITORYinafile, "Lưu danh sách tồn kho vào một tập tin");
	strcpy(sSerialNumber, "Mã đăng kí");
	strcpy(sService, "Dịch vụ");
	strcpy(sSetDefaultValues, "Điều này sẽ khôi phục tất cả các tham số về giá trị mặc định của họ. Tất cả các cài đặt của bạn sẽ bị mất. Bạn có chắc chắn muốn làm điều này?");
	strcpy(sSetedgeband, "Đặt độ dày dải cạnh");
	strcpy(sSetedgetrim, "Đặt kích thước cắt bỏ cho các khuyết tật của rìa tấm vật liệu");
	strcpy(sSetthesameedgebandforalledges, "Đặt cùng một độ dày dải cạnh cho tất cả các cạnh");
	strcpy(sSetthesamegrindingforalledges, "Đặt cùng một độ dày cần mài cho tất cả các cạnh");
	strcpy(sSetthesametrimforalledges, "Đặt cùng một đường cắt cho các khuyết tật ở tất cả các cạnh");
	strcpy(sSettings, "Cài đặt");
	strcpy(sShape, "Hình dạng");
	strcpy(sSheet, "Tấm");
	strcpy(sSheetsBarstypes, "Các loại tấm_thanh vật liệu");
	strcpy(sSheetSize, "Kích thước của tấm vật liệu");
	strcpy(sSheetsperPage, "Nhiều tấm vật liệu trên một trang");
	strcpy(sShort, "Ngắn");
	strcpy(sShorterexecutiontime, "Thời gian chạy ngắn");
	strcpy(sShowallsimpleproducts, "Hiển thị tất cả các sản phẩm đơn giản");
	strcpy(sShowcustomername, "Hiển thị tên khách hàng");
	strcpy(sShowCustomTextOnEachPiece, "Hiển thị văn bản tùy chỉnh trên mỗi mảnh cắt");
	strcpy(sShowdiagramasatable, "Hiển thị sơ đồ cắt dưới dạng bảng.");
	strcpy(sShowedgeband, "Hiển thị các dải cạnh");
	strcpy(sShowedgebandssettinginanewwindow, "Hiển thị các cài đặt của các dải cạnh trong một cửa sổ mới");
	strcpy(sShowgrindingsettingsinanewwindow, "Hiển thị cài đặt độ dày cần mài trong một cửa sổ mới");
	strcpy(sShowHorizontalLabelsAlways, "Hiển thị nhãn luôn nằm ngang");
	strcpy(sShowRemovethesizeofthepiecesinthecurrentsolution, "Hiển thị / ẩn kích thước của các mảnh cắt.");
	strcpy(sShowRemovethesizeofthewastesinthecurrentsolution, "Hiển thị / ẩn kích thước của các mảnh phế liệu.");
	strcpy(sShowtotalcutlength, "Hiển thị tổng chiều dài cắt");
	strcpy(sShowtrimedgesettingsinanewwindow, "Hiển thị các cài đặt của các vùng khiếm khuyết trong một cửa sổ mới");
	strcpy(sSimpleMaterialExists, "Tên của vật liệu đã có trong danh sách vật liệu. Xin vui lòng cho nó một tên mới.");
	strcpy(sSinglePieceStrips, "Các vạch sọc trên mảnh cắt");
	strcpy(sSizes, "Kích cỡ");
	strcpy(sSmallerorequalto, "Nhỏ hơn hoặc bằng");
	strcpy(sSort, "Sắp xếp");
	strcpy(sSortAscendingByArea, "Sắp xếp theo diện tích mảnh cắt theo thứ tự tăng dần");
	strcpy(sSortDescendingByArea, "Sắp xếp theo diện tích mảnh cắt theo thứ tự giảm dần");
	strcpy(sSpecifyhowdifferentthepiecesinthelaststagecanbeValue0meansnodifference, "");
	strcpy(sSpecifyifpiecesinthelaststagecanbedifferentornotdepeultimaetapapotfidiferitesaunucadimensiune, "Chỉ định các mảnh cắt trong giai đoạn cuối có thể khác nhau về kích thước hay không");
	strcpy(sSpecifyifthepiececanberotatedornotIfnotitwillbecutinthesamewayasitwasintroducedinDemandLengthofthepieceparalleltothelengthofthesheet, "Chỉ định mảnh cắt có thể được phép xoay hoặc không. Nếu không, nó được đặt theo cách đã được khai báo (chiều dài của mảnh song song với chiều dài của tấm), ");
	strcpy(sSpecifyinhowmanystageswemakethecutsDuringastageallcutshavethesamedirection, "Chỉ định số giai đoạn cần để thực hiện việc cắt tấm vật liệu.");
	strcpy(sStartthesearchprocess, "Bắt đầu quá trình tìm kiếm");
	strcpy(sStatistics, "Thống kê");
	strcpy(sStatisticsE, "Báo cáo phụ");
	strcpy(sStatisticsforeachtypeofmaterial, "Thống kê cho từng loại vật liệu");
	strcpy(sStep, "Bước");
	strcpy(sStergeDepozit, "Bạn có muốn xóa danh sách tồn kho?");
	strcpy(sStergeMaterial, "Bạn có muốn xóa vật liệu ?");
	strcpy(sStergePiesele, "Bạn có muốn xóa mảnh cắt?");
	strcpy(sStergePiesa, "Bạn có muốn xóa mảnh cắt?");
	strcpy(sStopthesearchprocess, "Dừng quá trình tìm kiếm");
	strcpy(sStrongoptimization, "Tối ưu hóa mạnh mẽ.");
	strcpy(sSubtractthebandthicknessfrompiecesize, "Giảm kích thước của các mảnh với độ dày dải cạnh");
	strcpy(sSummary, "Tóm tắt");
	strcpy(sSuprafataTotalaFolosita, "Tổng bề mặt sử dụng");
	strcpy(sSuprafatautilizata, "Sử dụng");
	strcpy(sSwitchbetweenfiberandrotationoption, "Chuyển đổi giữa đường vân và tùy chọn xoay.");
	strcpy(sTechnical, "Kỹ thuật");
	strcpy(sTechnicalsettings, "Cài đặt kỹ thuật");
	strcpy(sTemporaryPanelHint, "Bảng tạm thời để di chuyển các mảnh cắt bộ phận giữa các tấm vật liệu.");
	strcpy(sText, "Văn bản");
	strcpy(sThe_application_has_expired, "Ứng dụng đã hết hạn.");
	strcpy(sThe_application_is_not_registered, "Ứng dụng này chưa được đăng ký.");
	strcpy(sThe_application_was_first_started_on, "Ứng dụng này chạy lần đầu tiên vào");
	strcpy(sThecutsareperformedfromasidetotheothersideofthematerial, "Các vết cắt được thực hiện từ mặt này sang mặt kia của vật liệu.");
	strcpy(sThecuttingmachinecanfollowtheshapeofthematerial, "Máy cắt có thể thực hiện đường cắt theo hình dạng của mảnh cắt.");
	strcpy(sTheedgesofsheetsthatmustbetrimedduefaults, "Các cạnh của tấm vật liệu phải được cắt bỏ vì các lỗi");
	strcpy(sTheLargestSize, "Kích thước lớn nhất");
	strcpy(sThenameofthecustomerforwhichyoucutthepiece, "Tên của khách hàng mà bạn cắt mảnh vật liệu cho họ.");
	strcpy(sThenameofyourcustomer, "Tên của khách hàng của bạn");
	strcpy(sThepiececanberotated, "Các mảnh có thể xoay");
	strcpy(sTheprogramtriestoavoidwasteswhichhavebothsizeslessthanthisvalue, "Phần mềm cố gắng tối ưu để tránh phế liệu nhỏ hơn giá trị này");
	strcpy(sThereAreNoProducts, "Không có sản phẩm nào được khai báo");
	strcpy(sThestockofmaterialhasbeenpreviouslyloadedfromanExcelorCSVformatPleaseloaditagain, "Danh sách tồn kho vật liệu đã được tải trước đó từ định dạng Excel hoặc CSV. Vui lòng tải lại nếu bạn muốn làm việc với nó.");
	strcpy(sThetotallengthofcutting, "Tổng chiều dài cắt");
	strcpy(sThewidthofthecuttingsawForglasscuttingoptimizationitcanbe0Forwooditshouldbegreaterthan0, "Độ dày của lưỡi cưa. Đối với cắt kính có thể là 0. Đối với gỗ, nó phải lớn hơn 0.");
	strcpy(sThewidthofthecuttingsawforlinearpieces, "Độ dày của lưỡi cưa cho các mảnh cắt thẳng hàng.");
	strcpy(sThickness, "Độ dày");
	strcpy(sThischaracterisusedforfillingthewasterectanglesIfyoudonotwantfilledwastejustremovethischaracter, "Biểu tượng này được sử dụng để điền vào các hình chữ nhật là mảnh phế liệu. Nếu bạn không muốn thấy nhiều biểu tượng này, chỉ cần loại bỏ nó.");
	strcpy(sThisindexhasvaluebetween1andthenumberofpieces, "Chỉ số này có giá trị bắt đầu từ 1 đến cuối cùng là số lượng mảnh cắt.");
	strcpy(sThisOptionWillOverrideTheInventoryFileIfLoadedFromExcelOrCsvFiles, "Tùy chọn này sẽ ghi đè tệp danh sách tồn kho nếu được tải từ tệp excel hoặc csv.");
	strcpy(sThisProgramisLicensedTo, "Chương trình này được cấp phép để");
	strcpy(sThisvaluewillbeaddedtotheedgebandingmaterialoneachside, "Giá trị này sẽ được thêm vào các dải cạnh ở mỗi phía");
	strcpy(sTipNevid, "Thông tin về loại vật liệu không thể để trống.");
	strcpy(sTitle, "Tiêu đề");
	strcpy(sTools, "Công cụ");
	strcpy(sTop, "Trên");
	strcpy(sTopcoordinateofthedefect, "Tọa độ phía trên cùng của vùng khuyết tật.");
	strcpy(sTotalGarbageWaste, "Hủy toàn bộ các mảnh phế liệu");
	strcpy(sTotalInventoryWaste, "Tổng số phế liệu tồn kho");
	strcpy(sTotalRecycledWaste, "Tái sử dụng tất cả các mảnh phế liệu.");
	strcpy(sTotalusedarea, "Tổng diện tích sử dụng");
	strcpy(sTotalusedlength, "Tổng chiều dài sử dụng");
	strcpy(sTrigonometric, "Lượng giác");
	strcpy(sTrim, "Phần cắt bỏ");
	strcpy(sTrimalledgesatthebeginning, "Cắt bỏ tất cả các cạnh ngay khi bắt đầu");
	strcpy(sTrimEdge, "Cắt bỏ");
	strcpy(sTwoPanels, "2 tấm");
	strcpy(sType, "Kiểu");
	strcpy(sTypeofmaterialfromwhichtocut, "Loại vật liệu để cắt");
	strcpy(sTypesAreNotMatched, "Việc tối ưu hóa không được thực hiện! Vật liệu từ bảng Linh kiện và Bảng Kho không khớp nhau! Chỉ có thể cắt Linh kiện từ vật liệu có cùng tên trong kho. Hãy đổi tên vật liệu từ các cột tương ứng!");
	strcpy(sUndo, "Hoàn tác");
	strcpy(sUndoAccept, "Chấp nhận hoàn tác");
	strcpy(sUnits, "các đơn vị");
	strcpy(sUnregisteredVersion, "Chưa đăng ký");
	strcpy(sUpdates, "Cập nhật");
	strcpy(sUsefulforwoodfurniture, "Hữu ích cho đồ gỗ");
	strcpy(sUseit, "Sử dụng nó");
	strcpy(sUsePieceinOptimization, "Sử dụng mảnh cắt trong sự tối ưu hóa");
	strcpy(sUserName, "Tên tài khoản");
	strcpy(sUtilizationandWastes, "Sử dụng và phế liệu");
	strcpy(sUtilizedArea, "Diện tích các mảnh cắt bộ phận sử dụng");
	strcpy(sUtilizedBars, "Các thanh vật liệu được sử dụng");
	strcpy(sUtilizeddemandcount, "Số lượng các mảnh cắt bộ phận sử dụng");
	strcpy(sUtilizedParts, "Các mảnh cắt bộ phận được sử dụng");
	strcpy(sUtilizedPieces, "Các mảnh cắt được sử dụng");
	strcpy(sUtilizedSheets, "Các tấm vật liệu được sử dụng");
	strcpy(sValue, "Giá trị");
	strcpy(sValueGreaterEqualToZero, "Giá trị phải lớn hơn hoặc bằng 0");
	strcpy(sValueGreaterThanZero, "Giá trị phải lớn hơn 0");
	strcpy(sValueIntegerNumber, "Giá trị phải là một số nguyên!");
	strcpy(sValueRealNumber, "Giá trị nhập phải là một số thực. Có thể bạn đã sử dụng dấu phẩy thay vì dấu chấm hoặc ngược lại. Hãy sửa chữa nó!");
	strcpy(s_The_number_is_too_big_or_it_has_too_many_digits_after_decimal_separator, "Số quá lớn hoặc có quá nhiều chữ số sau dấu phân cách thập phân!");
	strcpy(s_The_number_is_too_big, "Con số quá lớn!");
	strcpy(sVertical, "Dọc");
	strcpy(sWaste, "Phế liệu");
	strcpy(sWastes, "Phế liệu");
	strcpy(sWasteAddedToWarehouse, "Các phế liệu được thêm vào danh sách tồn kho");
	strcpy(sWastelimits, "Dải kích thước quy định là phế liệu");
	strcpy(sWasteType, "Loại phế liệu");
	strcpy(sWeakoptimization, "Tối ưu hóa yếu nhất");
	strcpy(sWhattoprint, "Tôi nên in cái gì");
	strcpy(s_What_to_print_or_save_to_file, "Những gì để in hoặc lưu vào tập tin");
	strcpy(sWhattoprintoneachpiece, "Những gì để in trên mỗi mảnh");
	strcpy(sWhattoshowoneachpiece, "Những gì hiển thị trên mỗi mảnh?");
	strcpy(sWidth, "Chiều rộng");
	strcpy(sWood, "gỗ");
	strcpy(sWorkingDirectory, "Thư mục làm việc");
	strcpy(sWrongKey, "Mã đăng ký sai!");
	strcpy(sYes, "Đúng");
	strcpy(sYoucannotchooseblackblueorredcolors, "Bạn không thể chọn màu đen, xanh hoặc đỏ.");
	strcpy(sYouCannotMixFractionalDataWithDecimalOnes, "Bạn không thể trộn lẫn các giá trị phân số với các giá trị thực!");
	strcpy(sYourcompany, "Công ty của bạn");
	strcpy(sZip, "Mã bưu điện");
	strcpy(s_Set_the_origin_and_the_direction_of_the_axes, "Đặt gốc tọa độ và hướng của các trục tọa độ.");










	strcpy(s_Number_of_digits_after_the_decimal_separator, "Số chữ số sau dấu phân cách thập phân");
	strcpy(s_Percentages, "Phần trăm");
}

