// Language strings: Slovenian
// Author: Optimal Programs
// License: MIT License
//---------------------------------------------------------------------------
#include <string.h>
//---------------------------------------------------------------------------
#include "language_string_id.h"
//---------------------------------------------------------------------------
void set_sl(void)
{
	//Slovenian
	//translated by a customer
	//2025.3.29.0
	strcpy(s_Advanced, "Napredno");
	strcpy(s_Relative_coordinates, "Relativne koordinate");
	strcpy(s_Absolute_coordinates, "Absolutne koordinate");
	strcpy(s_Append_more_rows, "Dodajte več vrstic");

	strcpy(s_Add_to_parts, "Dodaj v deli.");
	strcpy(s_Additional, "Dodatno");
	strcpy(s_All_results, "Vsi rezultati.");
	strcpy(s_Allow_movement_of_pieces, "Dovoli premikanje kosov");
	strcpy(s_Allow_part_in_part, "Dovoli kos v kosu");
	strcpy(s_Invalid_piece_Angles_are_too_small_or_too_big_or_height_is_too_small, "Neveljaven kos! Koti so premajhni ali preveliki ali pa je višina premajhna.");
	strcpy(s_Append, "Dodaj/priloži");
	strcpy(s_As_it_is, "Kot je");
	strcpy(s_As_text, "Kot besedilo");
	strcpy(s_Ascending, "Naraščajoče");
	strcpy(s_Automatic, "Samodejno");
	strcpy(s_Cannot_connect_to_the_Internet_Please_visit_our_website_from_a_browser, "Povezave ni mogoče vzpostaviti. Prosimo, obiščite naše spletno mesto z brskalnikom!");
	strcpy(s_Cannot_copy_or_move_the_files, "Datotek ni mogoče kopirati ali premakniti!");
	strcpy(s_Cannot_delete_the_file, "Datoteke ni mogoče izbrisati!");
	strcpy(s_Cannot_modify_old_results, "Starih rezultatov ni mogoče spreminjati!");
	strcpy(s_To_change_click_inside_a_cell_or_press_0_1_or_2, "Za spremembo kliknite znotraj celice ali pritisnite 0, 1 ali 2.");
	strcpy(s_Cell, "Celica");
	strcpy(s_Click_on_the_table_header_to_change_the_columns, "Kliknite na glavo tabele, da spremenite stolpce.");
	strcpy(s_Column, "Stolpec");
	strcpy(s_Contact_us, "Kontaktiraj nas");
	strcpy(s_Copy, "Kopirati");
	strcpy(s_Comma, "Vejica");

	strcpy(s_Copy_for_move, "Kopija za premik");
	strcpy(s_Cut_index, "Pokaži indeks rez");
	strcpy(s_Cut_higher_level_strips_first, "Najprej odrežite trakove višje ravni");
	strcpy(s_Cuts_may_overlap, "Rezi se lahko pokrivajo");
	strcpy(s_The_data_have_been_changed_Do_you_want_to_save_them_to_a_file, "Podatki so bili spremenjeni. Ali jih želite shraniti v datoteko?");
	strcpy(s_Delete_fiber, "Izbrišite vlakno");
	strcpy(s_Decimal_separator, "Decimalno ločilo");
	strcpy(s_Restore_default_settings, "Obnovi privzete nastavitve");
	strcpy(s_Descending, "Padajoče");
	strcpy(s_Discard_changes, "Zavrzi spremembe");
	strcpy(s_Delete_all_data, "Želite izbrisati vse podatke?");

	strcpy(s_Do_you_want_to_delete_the_picture, "Ali želite izbrisati sliko?");
	strcpy(s_Dot, "Pika");
	strcpy(s_Do_you_want_to_delete_the_product, "Ali želite izbrisati izdelek?");
	strcpy(s_Do_you_want_to_delete_the_product, "Czy chcesz usunąć produkt?");
	strcpy(s_Duplicate_and_append, "Podvoji in dodaj.");
	strcpy(s_Duplicate_values_are_ignored, "Podvojene vrednosti so bile prezrte!");
	strcpy(s_Error, "Napaka");
	strcpy(s_Error_loading_file, "Napaka pri nalaganju datoteke.");
	strcpy(s_export_everything, "Izvozi vse");
	strcpy(s_Fit_to_screen, "Prilagodi zaslonu.");
	strcpy(s_Force_fixed_height, "Narišite kose s fiksno višino.");
	strcpy(s_Flipped, "Obrnjeno");
	strcpy(s_Import, "Uvoz");
	strcpy(s_If_angles_are_different_from_90_degrees_height_must_be_greater_than_0, "Če se koti razlikujejo od 90 stopinj, mora biti višina večja od 0.");
	strcpy(s_Ignore, "Prezri");
	strcpy(s_Incorrect_value, "Nepravilna vrednost");
	strcpy(s_Info, "Informacije");
	strcpy(s_Interior, "Notranjost");
	strcpy(s_Give_a_name, "Dodeli ime.");
	strcpy(s_Group, "Skupina");
	strcpy(s_Header, "Glava");
	strcpy(s_Keep_it_as_it_is, "Ohrani kot je");
	strcpy(s_Level, "Raven/stopnja");
	strcpy(s_Licensee, "Licenca");
	strcpy(s_List_separator, "Ločilo seznama");
	strcpy(s_Made_with_love_in_Cugir_Romania, "Izdelano z ljubeznijo v: Cugir, Romunija");
	strcpy(s_Made_in, "Proizvedeno v");
	strcpy(s_Manufacturer, "Proizvajalec");
	strcpy(s_Maximum_distance_between_2_linked_segments, "Maksimalna razdalja med 2 povezanima segmentoma");
	strcpy(s_Manual_arrange, "Ročna ureditev");
	strcpy(s_Mix_layers, "Upoštevaj entitete iz vseh plasti");
	strcpy(s_Mixed, "Mešano");
	strcpy(s_Multiple_shapes_detected_Next_rows_will_be_overwritten_Continue, "Zaznana je bila več kot ena oblika. Zato bodo naslednje vrstice prepisane. Nadaljevati?");
	strcpy(s_More, "Več");
	strcpy(s_Multiple_values, "Več vrednosti");
	strcpy(s_No_texture, "Brez teksture");
	strcpy(s_Number, "Število");
	strcpy(s_Number_of_images, "Število slik");
	strcpy(s_Number_of_vertices, "Število vozliščnih točk");
	strcpy(s_Offset, "Odmik");
	strcpy(s_Only_the_currently_selected_items, "Samo trenutno izbrani elementi.");
	strcpy(s_Optimizing_please_wait, "Optimiziram ... počakajte.");

	strcpy(s_Paste, "Prilepi");
	strcpy(s_Paste_from_Clipboard, "Prilepi iz odložišča");
	strcpy(s_Piece_label, "Oznaka kosa");
	strcpy(s_Piece_size, "Velikost kosa");
	strcpy(s_Please_contact_us_by_email_if_you_receive_this_error, "Če se prikaže ta napaka, nas kontaktirajte po e-pošti.");
	strcpy(s_Please_save_it_first, "Prosimo, najprej shranite.");
	strcpy(s_Position, "Pozicija");
	strcpy(s_Preview, "Predogled");
	strcpy(s_Rectangle, "Pravokotnik");
	strcpy(s_Resolution, "Resolucija");
	strcpy(s_Redo_the_last_operation, "Obnovi zadnjo operacijo");
	strcpy(s_Regular_polygon, "Navadni poligon");
	strcpy(s_Relative, "Sorodno");
	strcpy(s_Reused, "Ponovno uporabljeno");
	strcpy(s_Rotated, "Obrnjeno");
	strcpy(s_Save_all, "Shrani vse");
	strcpy(s_Scrap_label, "Oznaka odpada");
	strcpy(s_Scrap_size, "Velikost odpadkov");
	strcpy(s_Semicolon, "Podpičje");
	strcpy(s_Show_cut_index, "Pokaži indeks rezanja");
	strcpy(s_Show_information, "Pokaži informacije");
	strcpy(s_Show_piece_label, "Prikaži oznako kosa");
	strcpy(s_Show_scrap_label, "Prikaži oznako odpada");
	strcpy(s_Show_scrap_s_size_on_the_small_pieces, "Pokaži velikost ostankov majhnih kosov");
	strcpy(s_Show_size_of_pieces, "Pokaži velikosti kosov");
	strcpy(s_Show_size_of_scrap, "Pokaži velikost odpadkov");
	strcpy(s_Show_sizes, "Pokaži velikosti");
	strcpy(s_Show_label, "Prikaži oznako");
	strcpy(s_Show_length, "Prikaži dolžino");

	strcpy(s_Some_numerical_values_are_incorrect_Should_I_fix_all_the_incorrect_values, "Nekatere številčne vrednosti so napačne! Ali naj popravim vse napačne vrednosti?");
	strcpy(s_Some_invalid_values_have_been_removed, "Nekatere neveljavne vrednosti so bile odstranjene.");
	strcpy(s_Sort_by, "Razvrsti po");
	strcpy(s_Sort_ascending_by, "Razvrsti naraščajoče po");
	strcpy(s_Sort_descending_by, "Razvrsti padajoče po");
	strcpy(s_Start, "Start");
	strcpy(s_Starting_angle, "Začetni kot");
	strcpy(s_Starting_corner, "Začetni vogal");
	strcpy(s_Starting_direction, "Začetna smer");
	strcpy(s_Stock, "Zaloga");
	strcpy(s_Stop, "Stop");

	strcpy(s_Tabular, "Tablično");
	strcpy(s_Total, "Skupaj");
	strcpy(s_Total_size, "Skupna velikost");
	strcpy(s_Terms_of_the_license, "Pogoji licence");
	strcpy(s_The_current_product_has_been_changed_Do_you_want_to_save_it_to_file, "Trenutni izdelek je bil spremenjen. Ali ga želite shraniti v datoteko?");
	strcpy(s_The_value_is_out_of_the_allowed_range, "Vrednost je izven dovoljenega obsega.");
	strcpy(s_The_value_must_be_a_real_or_fractional_number_Try_to_replace_the_comma_with_the_dot_if_you_want_to_enter_a_real_number, "Vrednost mora biti celo ali decimalno število. Poskusite zamenjati vejico s piko, če želite vnesti decimalno število.");
	strcpy(s_This_feature_is_not_implemented_yet, "Ta funkcija še ni implementirana.");
	strcpy(s_This_operation_cannot_be_reversed, "Te operacije ni mogoče razveljaviti.");
	strcpy(s_Undo_the_last_operation, "Razveljavi zadnjo operacijo.");
	strcpy(s_Utilization, "Poraba");
	strcpy(s_Utilized_Stock, "Porabljena zaloga");
	strcpy(s_Version, "Različica");
	strcpy(s_Visible_columns, "Vidni stolpci");
	strcpy(s_You_already_have_the_latest_version_installed, "Nameščeno imate zadnjo različico!");
	strcpy(s_What_is_exported, "Kaj se izvaža?");
	strcpy(s0meansanynumberofpieces, "Nič pomeni poljubno število kosov");
	strcpy(sAbout, "Približno");
	strcpy(sAccept, "Sprejmi");
	strcpy(sAcceptall, "Sprejmi vse");
	strcpy(sAcceptthecurrentsolution, "Sprejmi trenutno rešitev");
	strcpy(sAdd, "Priloži");
	strcpy(sAddapiece, "Dodaj kos");
	strcpy(sAddasimpleproducttoDemand, "Dodaj izdelek obstoječim delom");
	strcpy(sAddgrindingthicknesstopartsize, "Dodaj debelino brušenja velikosti kosa");
	strcpy(sAddproductnametolabel, "Pripni ime izdelka na oznako");
	strcpy(sAddress, "Naslov");
	strcpy(sAddselectedsizetoInventory, "Dodaj izbrano velikost v zalogo");
	strcpy(sAdhesivelabels, "Nalepke");
	strcpy(sAdhesivelabelwithinformationaboutpiecesinDemandCustomernameLabelSizeCurrentData, "Nalepka s podatki o kosih: Ime stranke, oznaka, velikost, tekoči podatki, itd.");
	strcpy(sAdhesivelabelwithinformationaboutsheetsinInventory, "Nalepka s podatki o zalogi.");
	strcpy(sAll, "Vse");
	strcpy(sAlloffcutswhichhavethesizegreaterthanthisvaluewillbeaddedtoInventory, "Vse ostanki, ki imajo večjo velikost od te vrednosti, bodo dodani na seznam");
	strcpy(sAllowMirroring, "Omogoči obračanje");
	strcpy(sAllowRotation, "Dovoli Rotacijo");
	strcpy(sAllPieces, "Vsi kosi");
	strcpy(sAllpredefinedproducts, "Vsi vnaprej določeni izdelki");
	strcpy(sAnewwindowwillbedisplayedwheretheusercansettheedgebandsforeachedge, "Prikazano bo novo okno, kjer lahko nastavite robni pas za vsako stran.");
	strcpy(sAnewwindowwillbedisplayedwheretheusercansetthegrindingvalueforeachedgeofthsheet, "Prikazano bo novo okno, kjer lahko nastavite debelino brušenja za vsako stran kosa.");
	strcpy(sAnewwindowwillbedisplayedwheretheusercansetthetrimvalueforeachedgeofthsheet, "Prikazano bo novo okno, kjer lahko nastavite debelino reza za vsako stran kosov.");
	strcpy(sAngle, "Kot");
	strcpy(sAngles, "koti");
	strcpy(sAnoptimizationparameterisarealnumber, "Optimizacijski parameter je celo število.");
	strcpy(sAnoptimizationparameterisfractionalnumber, "Optimizacijski parameter je decimalno število.");
	strcpy(sAnyShape, "Pravilne oblike");
	strcpy(sApolygonmusthaveatleast2vertices, "Poligon mora imeti vsaj 2 vozliščni točki!");
	strcpy(sApolygonmusthaveatleast3vertices, "Poligon mora imeti vsaj 3 vozliščne točke!");
	strcpy(sApplication_fails_to_initialize, "Inicializacija aplikacije ni uspela!");
	strcpy(sArc, "Krožni lok");
	strcpy(sArcLength, "Dolžina krožnega loka");
	strcpy(sAreaofusedsheets, "Površina uporabljenih plošč");
	strcpy(sAshortdescriptionofthesheet, "Kratk opis plošče");

	strcpy(sAtleastonepart, "Vnesti je potrebno vsaj en kos.");
	strcpy(sAtTheMarginOfTheSheet, "Ob robu plošča");
	strcpy(sBandtypes, "Vrste robnih trakov");
	strcpy(sBar, "Palica / cev");
	strcpy(sBars, "Palice / cevi");
	strcpy(sBothsizesoftheoffcutsmustbegreaterthanthisvalue, "Obe velikosti ostanka morata biti večji od te vrednosti.");
	strcpy(sBottom, "Spodaj");
	strcpy(sBottomcoordinateofthedefect, "Spodnja koordinata ima napako");
	strcpy(sBreakCut, "Prelom reza");
	strcpy(sBrowse, "Brskaj");
	strcpy(sBuy, "Nakup");
	strcpy(sBuynow, "Kupi zdaj ...");
	strcpy(sCancel, "Prekliči");
	strcpy(sCannotBeEmpty, "Ne sme biti prazno!");
	strcpy(sCannotmovepartsbetweensheetswhenidenticalsheetsaregroupedPleaseungroupthesheetsfrommenu, "Delov ni mogoče premakniti iz ene ploščea na drugo, če so enake plošče združene. Prekliči združevanje plošč v meniju.");
	strcpy(sCannotSaveFile, "Ne morem shraniti datoteke");
	strcpy(sCenter, "Geometrijska sredina");
	strcpy(sChangeDirection, "Spremeni smer reza");
	strcpy(sChoose, "Izberi");
	strcpy(sChooseProduct, "Izberi izdelek");
	strcpy(sCircle, "Krog");
	strcpy(sCity, "Mesto");
	strcpy(sClear, "Počisti");
	strcpy(sClockWise, "V smeri urinega kazalca");
	strcpy(sClosewindow, "Zapri okno");
	strcpy(sColor, "Barva");
	strcpy(sColorofedgeband, "Barva robnega traku");
	strcpy(sColorPattern, "Barva / vzorec");
	strcpy(sColorpiecesandwastes, "Pobarvani kosi in ostanki");
	strcpy(sColumns, "Stolpci");
	strcpy(sComment, "Komentar");
	strcpy(sCompanyname, "Ime podjetja");
	strcpy(sComplexMaterialExists, "Ime materiala je že opredeljeno v seznamu kompleksnih materialov. Prosim, dodeli novo ime.");
	strcpy(sComputerCode, "Računalniška koda");
	strcpy(sComputerCodefromyourcomputer, "Računalniška koda (od vašega računalnika)");
	strcpy(sComputethetotalpriceofDemand, "Izračunaj skupno ceno delov");
	strcpy(sContents, "Vsebina");
	strcpy(sContinutComanda, "Vsebina delov po datumu");
	strcpy(sContinutDepozit, "Vsebina zaloge po datumu");
	strcpy(sConversionIsDoneOnlyWhenSomePiecesHaveFractionalValues, "Pretvarjanje se izvede samo, ko imajo nekateri kosi imajo decimalne vrednosti.");
	strcpy(sConvertsTheSizeOfWasteToAFractionalUnit, "Prikazuje velikosti odpadkov kot delno vrednost.");
	strcpy(sCouldNotSaveFile1, "Ne morem zapisati datoteke v direktorij.");
	strcpy(sCouldNotSaveFile2, "Morda nimate dovolj pravic. Prosimo, preverite, ali spremenite delovni direktorij v meniju Nastavitve | Delovni direktorij v mapo, kjer imate pravice za pisanje (na primer c:\\temp).");
	strcpy(sCreationdateYMDHMS, "Datum (Y / M / D, H: M: S)");
	strcpy(sCurrentDate, "Danes");
	strcpy(sCurrentDiagram, "Trenutni diagram");
	strcpy(sCurrentMaterial, "Trenutni material");
	strcpy(sCurrentversion, "Trenutna verzija");
	strcpy(sCurve_not_closed_Try_increasing_DXF_linking_distance_parameter, "Poligon ni zaprt! Poskusite povečati parameter povezovalne razdalje DXF.");
	strcpy(sCustomer, "Stranka");
	strcpy(sCustomerName, "Ime stranke");
	strcpy(sCustomMessage, "Sporočilo po meri");
	strcpy(sCutlength, "Dolžina reza");
	strcpy(sCut, "Rez");
	strcpy(sCuts, "Kosi");
	strcpy(sCutterThickness, "Debelina rezanja");
	strcpy(sData, "Podatki");
	strcpy(sDataCannotBeEmpty, "Podatki ne morejo biti prazni!");
	strcpy(sDateymdhms, "Datum (y / m / d / h / m / s)");
	strcpy(sDays_left_for_trial, "Prestali dnevi preizkusa");
	strcpy(sDaysLeft, "Preostali dnevi");
	strcpy(sStandard, "Standardno");
	strcpy(sDefaultInterface, "Privzeti vmesnik");
	strcpy(sDefects, "Napake");
	strcpy(sDefectsManager, "Upravljanje napak");
	strcpy(sDefectsofthematerialNopiecescanbeplacedinthefaultyzone, "Napake na materialu. Na območje ni mogoče postaviti kosov.");
	strcpy(sDelete, "Izbriši");
	strcpy(sDeletePiece, "Izbriši kos");
	strcpy(sDeleteRow, "Izbriši vrstico");
	strcpy(sDemandutilization, "Uporaba delov");
	strcpy(sDepozitulmodificat, "Uporabljeni deli so bili odstranjeni. Ostanke je bil dodan v zalogo.");
	strcpy(sDepozitvid, "Zaloga je prazna");
	strcpy(sDesk, "Miza");
	strcpy(sDiagram, "Diagram");
	strcpy(sDiagrams, "Diagrami");
	strcpy(sDiagramasatable, "Diagram kot tabela");
	strcpy(sDigits, "Cifre");
	strcpy(sDimensiuniplaca, "Velikost plošče");
	strcpy(sDirection, "Smer");
	strcpy(sDistanceBetweenRows, "Razdalja med vrstami");
	strcpy(sDonotuseit, "Ne uporabljajte");
	strcpy(sDownload, "Prenesi");
	strcpy(sDoYouWantToClearTheData, "Ali želiš izbrisati podatke?");
	strcpy(sDoYouWantToSaveDemand, "Deli so bili spremenjeni! Ali želite shraniti spremembe?");
	strcpy(sDoYouWantToSaveParts, "Ali želite shraniti dele?");
	strcpy(sDoYouWantToSaveRepository, "Zaloga se je spremenila! Ali želite shraniti spremembe?");
	strcpy(sDrawing, "Risba");
	strcpy(sDrawthesolutioncolorful, "Izriši rešitev v barvah");
	strcpy(sDuplicateTypes, "Nekatere vrste so podvojene! Prosimo, odstranite dvojnike");
	strcpy(sDuplicateTypesWithComplex, "Nekatera imena materiala jže obstajajo v seznamu kompleksnih materialov. Prosim, odstani duplikate.");
	strcpy(sDuplicateValues, "Podvojene vrednosti");
	strcpy(sEdgeband, "Robni trakovi");
	strcpy(sEdgebandingwhichisplacedontheedgesofyourpiecePleasedefineedgebandingtypesfromMaterialsEdgeBandingmenu, "Robni trakovi so nameščeni na robovih vašega kosa. Določite robne trakove v meniju Materiali.");
	strcpy(sEdgebandsthatwillbeappliedtoeachpart, "Robni trakovi, ki so uporabljeni na vsakem kosu");
	strcpy(sEdgeBandTolerance, "Toleranca za robne trakove");
	strcpy(sEdgesthatmustbecutduefaults, "Robovi, ki jih je treba rezati zaradi napake.");
	strcpy(sEdgetoedge, "Od roba do roba");
	strcpy(sEdit, "Urejanje");
	strcpy(sEmail, "E-pošta");
	strcpy(sEmptyData, "Podatki so prazni!");
	strcpy(sEnabled, "Omogočeno");
	strcpy(sEnabledisabledefectsoftheinventorysheets, "Omogoči / onemogoči napake na zalogi");
	strcpy(sEnterLabel, "Vstavi oznako");
	strcpy(sEnterTheMaterialName, "Vnesite ime materiala");
	strcpy(sEnterTheProductName, "Vnesite ime izdelka");
	strcpy(sEvaluationError, "Napaka v izrazu ocene!");
	strcpy(sExit, "Izhod");
	strcpy(sExpired, "Programska oprema je potekla! Prosimo registrirajte programsko opremo!");
	strcpy(sExport, "Izvozi");
	strcpy(sExportAllDiagrams, "Izvozi vse diagrame");
	strcpy(sExportAllToASingleFile, "Izvozi vse v eno datoteko");
	strcpy(sExportOptions, "Možnosti izvoza");
	strcpy(sExporttoDXFformat, "Izvoz v DXF formatu");
	strcpy(sExporttoExcel, "Izvoz v Excel");
	strcpy(sExpresieIncorecta, "Nepravilen matematični izraz!");
	strcpy(sExtensions, "Podaljški");
	strcpy(sExtra, "Dodatno");
	strcpy(sExtraComponents, "Dodatne komponente");
	strcpy(sExtracomponentsattachedtoDemand, "Dodatne komponente dodane delom");
	strcpy(sFile, "Datoteka");
	strcpy(sFileName, "Ime datoteke");
	strcpy(sFillWastes, "Nariši odpad z poševnimi črtami");
	strcpy(sFindoptimalbarsheetsize, "Iskanje optimalnih velikosti za palice in ​​plošče");
	strcpy(sFindoptimalsizeofInventorypieces, "Iskanje optimalne velikosti kosov iz zaloge");
	strcpy(sFirstcutMultiplestages, "Prva smer rezanja za večstopenjsko optimizacijo");
	strcpy(sFirstdirectionforcutishorizontal, "Prva smer reza je vodoravna.");
	strcpy(sFirstdirectionforcutisvertical, "Prva smer reza je navpično.");
	strcpy(sFollowthecontourofpieces, "Sledi konturi kosov");
	strcpy(sFont, "Pisava");
	strcpy(sFontsize, "Velikost pisave");
	strcpy(sFullInfo, "Popolne informacije");
	strcpy(sDisposedWaste, "Odloženi odpadki");
	strcpy(sGeneral, "Splošno");
	strcpy(sGenerateCNC, "Generiraj CNC");
	strcpy(sGrain, "Tekstura");
	strcpy(sGraindirection, "Smer teksture");
	strcpy(sGraphic, "Grafični");
	strcpy(sGreaterorequalto, "Odpad mora biti večji ali enak");
	strcpy(sGrid, "Tabele");
	strcpy(sGrinding, "Brušenje");
	strcpy(sGrosimeTaieturaScalata, "Debelina reza na tej sliki se lahko razlikuje od dejanske, ker kosi niso predstavljeni v pravem merilu. To dejstvo ne vpliva na rezultate.");
	strcpy(sGroupidenticallayouts, "Združi enake plošče");
	strcpy(sGroupIdenticalParts, "Združi enake dele");
	strcpy(sGroupingOfIdenticalPiecesIntoOneRow, "Združi enake dele v vrsto");
	strcpy(sGroupPartsAfterLoadingFromFile, "Združi dele iz naložene datoteke");
	strcpy(sHeight, "Višina");
	strcpy(sHeighttolerance, "Toleranca za višino");
	strcpy(sHelp, "Pomoč");
	strcpy(sHistory, "Zgodovina");
	strcpy(sHorizontal, "Vodoravno");
	strcpy(sHowtodisplayprintedgebands, "Kako so prikazani robni trakovi?");
	strcpy(sIfyousetthebandforoneedgeallwillreceivethesamevalue, "Če nastavite trak za en rob, bodo vsi robovi prejeli isto vrednost.");
	strcpy(sIfyousetthegrindingforoneedgeallwillreceivethesamevalue, "Če nastavite vrednost za brušenje enem robu, bodo vsi robovi prejmejo enako vrednost.");
	strcpy(sIfyousetthetrimforoneedgeallwillreceivethesamevalue, "Če nastavite vrednost za čiščenje enem robu, bodo vsi robovi prejeli enako vrednost.");
	strcpy(sImageBounds, "Omejitve za slike");
	strcpy(sImageSize, "Velikost slike.");
	strcpy(sImportData, "Uvoz podatkov");
	strcpy(sIncorrectPassword, "Nepravilno geslo");
	strcpy(sIndex, "Kazalnik");
	strcpy(sInformationaboutcustomer, "Podatki o kupcu");
	strcpy(sInputALanguageName, "Poimenujte jezik");
	strcpy(sInsert, "Vstavi");
	strcpy(sInsertPiece, "Vstavite kos");
	strcpy(sInterface, "Vmesnik");
	strcpy(sInterfaceSettings, "Vmesnik nastavitve");
	strcpy(sInvalidHardware, "Strojna oprema ni zaznana. Prosimo, pišite nam na contact@optimalprograms.com");
	strcpy(sInvalidNumber, "Neveljavna številka");
	strcpy(sInvalidOrderOfComputation, "Vrstnega reda za izračun dolžin ni mogoče vzpostaviti. V definiciji izdelka so krožna razmerja!");
	strcpy(sInvalidRegistration, "Registracija je neveljavna!");
	strcpy(sInvalidTime, "Sistemski čas je neveljaven.");
	strcpy(sInventory, "Zaloga");
	strcpy(sisafractionalvalue, "je delna vrednost.");
	strcpy(sIsArc, "Je lok");
	strcpy(sisarealvalue, "je dejanska vrednost.");
	strcpy(sLabel, "Oznaka");
	strcpy(sLabels, "Nalepke");
	strcpy(sLanguage, "Jezik");
	strcpy(sLatimeanumar0, "Širina mora biti večja od 0!");
	strcpy(sLatimeanumarreal, "Širina mora biti realno število!");
	strcpy(sLayerName, "Ime sloja");
	strcpy(sLeft, "Levo");
	strcpy(sLeftcoordinateofthedefect, "Leva koordinata napačna");
	strcpy(sLength, "Dolžina");
	strcpy(sLengthofthepiecestocut, "Velikost kosa za rezanje");
	strcpy(sLengthofthepiecestocutfrom, "Velikost plošče za rezanje");
	strcpy(sLengthofusedbars, "Velikost uporabljenih palic");
	strcpy(sLicenseAgreement, "Licenčna pogodba");
	strcpy(sLinear, "Linearno");
	strcpy(sLinethickness, "Debelina peresa");
	strcpy(sLoadafileandappenddatatothecurrentDemand, "Naložite datoteko in dodajte podatke trenutnim kosom");
	strcpy(sLoadanexistingDemandfromafile, "Naloži obstoječe kose iz datoteke");
	strcpy(sLoadAppend, "Naloži in Dodaj");
	strcpy(sLoadEverything, "Naloži vse");
	strcpy(sLoadInventory, "Naloži zalogo");
	strcpy(sLoadInventoryandDemand, "Naloži zalogo in dele");
	strcpy(sLoadResults, "Nalaganje rezultatov");
	strcpy(sLocked, "Zaklenjen");
	strcpy(sLogo, "Logo");
	strcpy(sLong, "Dolgo");
	strcpy(sLongerexecutiontime, "Daljši čas izvajanja");
	strcpy(sLungime, "Dolžina");
	strcpy(sLungimeanumar0, "Dolžina mora biti večja od 0!");
	strcpy(sLungimeanumarreal, "Dolžina mora biti realno število!");
	strcpy(sLungimeaTotalaFolosita, "Skupna uporabljena dožina");
	strcpy(sMagnification, "Povečava");
	strcpy(sMagnify, "Povečaj");
	strcpy(sMargins, "Robovi");
	strcpy(sMarginsForPaper, "Robovi za papir");
	strcpy(sMarginsOfTheLabel, "Robovi nalepke");
	strcpy(sMaterial, "Material");
	strcpy(sMaterialName, "Ime materiala");
	strcpy(sMaterials, "Materiali");
	strcpy(sMaterialstypes, "Vrste materialov");
	strcpy(sMax, "Maksimalno");
	strcpy(sMaximalArea, "Maksimalna površina");
	strcpy(sMaximalCutLength, "Maksimalna dolžina reza");
	strcpy(sMaxlength, "Maksimalna dolžina");
	strcpy(sMaxPiecesperBar, "Maksimalno število kosov na palici");
	strcpy(sMaxwidth, "Maksimalna širina");
	strcpy(sMeasurementUnit, "Merska enota");
	strcpy(sMin, "Minimalno");
	strcpy(sMinimalBreakSize, "Minimalna velikost preloma");
	strcpy(sMinimalUsefulSize, "Minimalna koristna površina");
	strcpy(sMinimalwastesizetoInventory, "Minimalna velikost ostankov dodanih v zalogo");
	strcpy(s_What_to_minimize, "Kaj minimizirati?");
	strcpy(sMinlength, "Minimalna dolžina");
	strcpy(sMinwidth, "Minimalna širina");
	strcpy(sMirror, "Zrcalno");
	strcpy(sMirroring, "Zrcaljenje");
	strcpy(sMiscellaneous, "Druga statistika");
	strcpy(sModify, "Prilagodi");
	strcpy(sModifytheselectedpiece, "Prilagodi izbrani kos");
	strcpy(sMovePiece, "Premakni kos");
	strcpy(sMultiplestages, "Več stopenj");
	strcpy(sName, "Ime");
	strcpy(sNameofedgeband, "Ime robnega traku");
	strcpy(sNewDEMANDUnsaveddatawillbelost, "Novi deli? Neshranjene podatki bodo izgubljeni!");
	strcpy(sNewLanguage, "Nov jezik");
	strcpy(sNewMaterial, "Nov material");
	strcpy(sNewPasswordincorectlyintroduced, "Novo geslo je napačno vneseno!");
	strcpy(sNewProduct, "Nov izdelek");
	strcpy(sNewversion, "Nova različica");
	strcpy(sNo, "Št.");
	strcpy(sNumarBucati, "Število kosov");
	strcpy(sNumberOfCopies, "Število kopij");
	strcpy(sNumberofstages, "Število stopenj");
	strcpy(sNusuficienteplacidepozit, "Vsi deli niso bili optimizirani. Možni vzroki: Na zalogi ni dovolj kosov. Kosi niso omogočeni. Materiali kosov in zaloga sta različna. Drugi parametri so bili nepravilno nastavljeni.");
	strcpy(sOfficeNotInstaled, "Microsoft Office ni nameščen na vašem računalniku ali pa je nameščena napačna različica!");
	strcpy(sOldpassworddoesnotmatch, "Staro geslo se ne ujema!");
	strcpy(sOnlinehelp, "Spletna pomoč");
	strcpy(sOnlypiecesofthesameheightinthelaststage, "Kosi iste višine, v zadnji fazi.");
	strcpy(sOpen, "Odpri");
	strcpy(sOptimization, "Optimizacija");
	strcpy(sOptimizationDone, "Optimizacija izvedena! Dobljene diagrame lahko natisnete ali shranite. Pritisnite gumb Sprejmi, če ste zadovoljni s trenutno rešitvijo. V nasprotnem primeru znova pritisnite Start");
	strcpy(sOptimizationType, "Vrsta optimizacije");
	strcpy(sOptions, "Možnosti");
	strcpy(sOptionsrelatedtotheinterface, "Možnosti, povezane z vmesnikom");
	strcpy(sor, "ali");
	strcpy(sOthercomponents, "Drugi komponente");
	strcpy(sOthers, "Drugo");
	strcpy(sOtherstatistics, "Drugi statistični podatki");
	strcpy(sOverrideExcelCSVfiles, "Povozi Excel/CSV datoteke");
	strcpy(sParameter, "Parameter");
	strcpy(sParts, "DELI");
	strcpy(sPattern, "Vzorec");
	strcpy(sPatternforwaste, "Vzorec za odpad");
	strcpy(sPerimeter, "Perimeter");
	strcpy(sPermitedRotationAngle, "Dovoljen kot vrtenja.");
	strcpy(sPhone, "Telefon");
	strcpy(sPicture, "Slika");
	strcpy(sPiece, "Kos");
	strcpy(sPieceindex, "Indeks kosa");
	strcpy(sPieces, "Kosov");
	strcpy(sPiecesize, "Velikost kosa");
	strcpy(sPiecesizelabeledgebandwillbeprinted, "Velikost kosa, oznaka, robni trakovi bodo natisnjeni");
	strcpy(sPierdere, "Odpad");
	strcpy(sPixels, "slikovnih pik");
	strcpy(sPlacilefolositeDepozit, "Rabljeni kosi iz zaloge");
	strcpy(sPlease_contact_us_at_contact_nestingtechnologies_com, "Prosimo, pišite nam na contact@nesting-technologies.com");
	strcpy(sPlease_contact_us_at_contact_optimalprograms_com, "Prosimo, pišite nam na contact@optimalprograms.com");
	strcpy(sPleaseenteralldataeitherasfractionalorrealDonotmixthem, "Prosimo, da vsa števila vnesete kot decimalne ali cele vrednosti! Ne mešajte jih!");
	strcpy(sPleaseEnterSomeTypesOfMaterials, "Vrste materiala niso določena. Določite jih v meniju Materiali");
	strcpy(sPleasesendtheNameandtheCodetotheaddresscontactoptimalprogramscominordertoobtaintheRegistrationKey, "Če želite pridobiti registracijski ključ, pošljite ime in kodo na: contact@optimalprograms.com.");
	strcpy(sPolygon, "Poligon");
	strcpy(sPolygonsCircles, "Poligoni, krogi");
	strcpy(sPrecision, "Preciznost");
	strcpy(sPretulnumar0, "Cena mora biti večja od 0!");
	strcpy(sPretulnumarreal, "Cena mora biti realno število!");
	strcpy(sPreview, "Predogled");
	strcpy(sPrice, "Cena");
	strcpy(sPriceMustBeGreaterThanZero, "Cena mora biti večja od nič");
	strcpy(sPriceofbars, "Cene palic");
	strcpy(sPriceperbar, "Cena po palici");
	strcpy(sPricepersheet, "Cena po plošči");
	strcpy(sPricepersquareunitofmaterial, "Cena po kvadratni enoti materiala.");
	strcpy(sPriceperunit, "Cena na enoto");
	strcpy(sPrint, "Natisni");
	strcpy(sPrintdiagramsastables, "Natisni diagrame v obliki tabel.");
	strcpy(sPrinter, "Tiskalnik");
	strcpy(sPrinterBounds, "Robovi za tiskalnik");
	strcpy(sPrinting, "Tiskanje");
	strcpy(sPrintonlyutilizedarea, "Natisni samo izkoriščen prostor");
	strcpy(sPrintthecontentsoftheDemand, "Natisni vsebino delov.");
	strcpy(sPrintthecontentsoftheInventory, "Natisni vsebino zaloge.");
	strcpy(sPrintthecurrentsolution, "Natisni trenutno rešitev.");
	strcpy(sPriority, "Prednost");
	strcpy(sPrioritytocutapieceZero0isthehighestpriority, "Prednostni kos. NIČ (0) je najvišja prioriteta.");
	strcpy(sProcentul0100, "odstotki morajo biti večji od 0 in manjši ali enaki 100!");
	strcpy(sProcentulnumarreal, "Odstotki morajo biti realno število!");
	strcpy(sProductdefinition, "Opredelitev izdelka");
	strcpy(sProductExists, "Izdelek že obstaja. Izberite drugo ime.");
	strcpy(sProductName, "Ime izdelka");
	strcpy(sProduct, "Izdelek");
	strcpy(sProducts, "Izdelki");
	strcpy(sProject, "Projekt");
	strcpy(sProperties, "Lastnosti");
	strcpy(sProperty, "Lastnost");
	strcpy(sQuantity, "Količina");
	strcpy(sQuantitynumberofsheetsofthistype, "Število listov te vrste");
	strcpy(sRadius, "Polmer");
	strcpy(sRectangular, "Pravokotni");
	strcpy(sRedefinetypesofedgeband, "Ponovno določi vrste robnih trakov");
	strcpy(sRedefinetypesofmaterial, "Ponovno določi vrste materialov");
	strcpy(sRegistration, "Registracija");
	strcpy(sRegistrationKeyfromOptimalPrograms, "Registracijski ključ");
	strcpy(sRegistrationSuccessful, "Registracija uspešna!");
	strcpy(sRemoveallpiecesinInventory, "Odstrani vse dele v inventraju");
	strcpy(sRemoveCut, "Izbriši rez");
	strcpy(sRemovetheselectedpiece, "Izbriši izbrani kos");
	strcpy(sReports, "Poročila");
	strcpy(sRequestedMaterial, "Zahtevani material");
	strcpy(sRestore, "Obnovi");
	strcpy(sResults, "Rezultati");
	strcpy(sReusedwaste, "Ponovno uporabljen odpad");
	strcpy(sRight, "Desno");
	strcpy(sRightcoordinateofthedefect, "Koordinate napake iz desne strani");
	strcpy(sRotation, "Rotacija");
	strcpy(sRotationAngle, "Kot zasuka");
	strcpy(sRotationStep, "Korak zasuka");
	strcpy(sRoundAllFractionsTo, "Decimalne vrednosti morajo biti zaokrožene");
	strcpy(sRow, "vrstica");
	strcpy(sRows, "Vrstice");
	strcpy(sRun, "Najnovejše rešitve");
	strcpy(sRunningtime, "čas delovanja");
	strcpy(sSameforall, "Isto velja za vse");
	strcpy(sSave, "Shrani");
	strcpy(sSaveAllImages, "Shrani vse slike");
	strcpy(sSaveAs, "Shrani kot");
	strcpy(sSaveChanges, "Deli so bili spremenjeni! Ali želite shraniti spremembe?");
	strcpy(sSaveCurrentImage, "Shrani trenutno sliko");
	strcpy(sSavedataparameters, "Shrani podatke in parametre");
	strcpy(sSaveEverything, "Shrani vse");
	strcpy(sSaveInventory, "Shrani inventar");
	strcpy(sSaveInventoryandDemand, "Shrani zalogo in dele");
	strcpy(sSaveResults, "Shrani rezultate");
	strcpy(sSaveStatisticsinafile, "Shrani statistiko v datoteko");
	strcpy(sSavethecurrentimage, "Shrani trenutno sliko");
	strcpy(sSavethecurrentimageorstatistic, "Shrani trenutno sliko ali statistiko");
	strcpy(sSavetheDEMANDinafile, "Shrani v datoteko");
	strcpy(sSavetheDemandinafilewithadifferentname, "Shrani dele v datotetko z drugim imenom");
	strcpy(sSavetheREPOSITORYinafile, "Shrani zalogo v datoteko");
	strcpy(sSerialNumber, "Registracijski ključ");
	strcpy(sService, "Storitev");
	strcpy(sSetDefaultValues, "S tem boste obnovili vse parametre na privzete vrednosti. Vse vaše nastavitve bodo izgubljene. Ste prepričani, da želite nadaljevati?");
	strcpy(sSetedgeband, "Nastavi robni trak");
	strcpy(sSetedgetrim, "Nastavite velikost reza za napake na robovih");
	strcpy(sSetthesameedgebandforalledges, "Nastavi enak robni trak za vse strani");
	strcpy(sSetthesamegrindingforalledges, "Nastavite enako brušenje za vse robove");
	strcpy(sSetthesametrimforalledges, "Nastavite enako rezanje za napake za vse robove");
	strcpy(sSettings, "Nastavitve");
	strcpy(sShape, "Oblika");
	strcpy(sSheet, "Plošče");
	strcpy(sSheetsBarstypes, "Vrste plošč/palic");
	strcpy(sSheetSize, "Velikost plošče");
	strcpy(sSheetsperPage, "plošč na stran");
	strcpy(sShort, "Kratko");
	strcpy(sShorterexecutiontime, "Kratek čas delovanja");
	strcpy(sShowallsimpleproducts, "Prikaži vse enostavne produkte");
	strcpy(sShowcustomername, "Pokaži ime stranke");
	strcpy(sShowCustomTextOnEachPiece, "Pokaži besedilo po meri za vsak kos");
	strcpy(sShowdiagramasatable, "Pokaži diagram kot tabelo.");
	strcpy(sShowedgeband, "Pokaži robne trakove");
	strcpy(sShowedgebandssettinginanewwindow, "Pokaži nastavitve robnih trakov v novem oknu.");
	strcpy(sShowgrindingsettingsinanewwindow, "Pokaži nastavitve brušenja robov v novem oknu.");
	strcpy(sShowHorizontalLabelsAlways, "Vedno prikaži horizontalne oznake");
	strcpy(sShowRemovethesizeofthepiecesinthecurrentsolution, "Pokaži/skrij velikost kosov.");
	strcpy(sShowRemovethesizeofthewastesinthecurrentsolution, "Pokaži/skrij velikosti odpada.");
	strcpy(sShowtotalcutlength, "Pokaži celotno dolžino rezov");
	strcpy(sShowtrimedgesettingsinanewwindow, "Pokaži nastavitve napak v novem oknu");
	strcpy(sSimpleMaterialExists, "Ime materiala je že uporabljeno v seznamu materiala. Prosim dodeli novo ime.");
	strcpy(sSinglePieceStrips, "Traki iz enega kosa");
	strcpy(sSizes, "Velikosti");
	strcpy(sSmallerorequalto, "Odpad mora biti manjši ali enak");
	strcpy(sSort, "Razvrsti");
	strcpy(sSortAscendingByArea, "Razvrsti po površini naraščajoče");
	strcpy(sSortDescendingByArea, "Razvrsti po površini padajoče");
	strcpy(sSpecifyhowdifferentthepiecesinthelaststagecanbeValue0meansnodifference, "Določite, kako različni so lahko kosi v zadnji fazi. Vrednost 0 pomeni, da morajo biti vsi kosi enake velikosti.");
	strcpy(sSpecifyifpiecesinthelaststagecanbedifferentornotdepeultimaetapapotfidiferitesaunucadimensiune, "Določite, ali so deli v zadnji fazi lahko drugačni ali ne");
	strcpy(sSpecifyifthepiececanberotatedornotIfnotitwillbecutinthesamewayasitwasintroducedinDemandLengthofthepieceparalleltothelengthofthesheet, "Določite, ali je del mogoče vrteti ali ne. Če ni, se namesti na enak način, kot je bil uveden (dolžina kosa vzporedna z dolžino lista).");
	strcpy(sSpecifyinhowmanystageswemakethecutsDuringastageallcutshavethesamedirection, "Določi, v koliko stopnjah se naredijo rezi");
	strcpy(sStartthesearchprocess, "Začni postopek iskanja");
	strcpy(sStatistics, "Statistika");
	strcpy(sStatisticsE, "Dodatna poročila");
	strcpy(sStatisticsforeachtypeofmaterial, "Statistika za vsak tip materiala");
	strcpy(sStep, "Korak");
	strcpy(sStergeDepozit, "Ali želiti izbrisati inventar?");
	strcpy(sStergeMaterial, "Ali želite izbrisati material?");
	strcpy(sStergePiesele, "Ali želite izbrisati kose?");
	strcpy(sStergePiesa, "Ali želite izbrisati kos?");
	strcpy(sStopthesearchprocess, "Ustavi postopek iskanja");
	strcpy(sStrongoptimization, "Močna optimizacija");
	strcpy(sSubtractthebandthicknessfrompiecesize, "Zmanjšaj velikost kosov za debelino robnega traku");
	strcpy(sSummary, "Povzetek");
	strcpy(sSuprafataTotalaFolosita, "Skupna uporabljena površina");
	strcpy(sSuprafatautilizata, "Izkoristek");
	strcpy(sSwitchbetweenfiberandrotationoption, "Preklopi med možnostjo vlaken in obračanjem.");
	strcpy(sTechnical, "Tehnična");
	strcpy(sTechnicalsettings, "Tehnične nastavitve");
	strcpy(sTemporaryPanelHint, "Začasna plošča za premikanje delov med ploščami.");
	strcpy(sText, "Besedilo");
	strcpy(sThe_application_has_expired, "Aplikacija se je iztekla.");
	strcpy(sThe_application_is_not_registered, "Aplikacija ni registrirana.");
	strcpy(sThe_application_was_first_started_on, "Aplikacija je bila prvič zagnana");
	strcpy(sThecutsareperformedfromasidetotheothersideofthematerial, "Rezi so narejeni iz ene do druge strani materiala");
	strcpy(sThecuttingmachinecanfollowtheshapeofthematerial, "Stroj lahko sledi obliki kosa.");
	strcpy(sTheedgesofsheetsthatmustbetrimedduefaults, "Robovi plošče morajo biti odrezani zaradi napak");
	strcpy(sTheLargestSize, "Največja velikost.");
	strcpy(sThenameofthecustomerforwhichyoucutthepiece, "Ime stranke, za katero je odrezan kos.");
	strcpy(sThenameofyourcustomer, "Ime vaše stranke");
	strcpy(sThepiececanberotated, "Kos se lahko zavrti");
	strcpy(sTheprogramtriestoavoidwasteswhichhavebothsizeslessthanthisvalue, "Program se skuša izogniti odpadu ki je manjši od te vrednosti");
	strcpy(sThereAreNoProducts, "Izdelki še niso definirani");
	strcpy(sThestockofmaterialhasbeenpreviouslyloadedfromanExcelorCSVformatPleaseloaditagain, "Zaloga je predhodno naložena iz formata Excel ali CSV. Če želite delati na njem, ga znova naložite.");
	strcpy(sThetotallengthofcutting, "Skupna dolžina rezanja");
	strcpy(sThewidthofthecuttingsawForglasscuttingoptimizationitcanbe0Forwooditshouldbegreaterthan0, "Debelina rezalnega lista. Za steklo je lahko 0, za les mora biti večja od 0.");
	strcpy(sThewidthofthecuttingsawforlinearpieces, "Debelina reza za linearni razrez kosov");
	strcpy(sThickness, "Debelina");
	strcpy(sThischaracterisusedforfillingthewasterectanglesIfyoudonotwantfilledwastejustremovethischaracter, "Ta simbol se uporablja za polnjenje pravokotnikov za odpadke. Če ne želite polnih odpadkov, jih preprosto odstranite.");
	strcpy(sThisindexhasvaluebetween1andthenumberofpieces, "Ta indeks ima vrednost med 1 in število kosov.");
	strcpy(sThisOptionWillOverrideTheInventoryFileIfLoadedFromExcelOrCsvFiles, "Ta možnost bo povozila datoteko inventarja, če je naložena iz datotek excel ali csv.");
	strcpy(sThisProgramisLicensedTo, "Ta program je licenciran za");
	strcpy(sThisvaluewillbeaddedtotheedgebandingmaterialoneachside, "Ta vrednost bo dodana robnim trakovom na vsaki strani");
	strcpy(sTipNevid, "Vrsta materiala ne more biti prazna");
	strcpy(sTitle, "Naslov");
	strcpy(sTools, "Orodja");
	strcpy(sTop, "Na vrh");
	strcpy(sTopcoordinateofthedefect, "Zgornja koordinata napačna");
	strcpy(sTotalGarbageWaste, "Ves zavržen odpad");
	strcpy(sTotalInventoryWaste, "Skupna zaloga odpada");
	strcpy(sTotalRecycledWaste, "Ves ponovno uporabljen odpad");
	strcpy(sTotalusedarea, "Skupna uporabljena površina");
	strcpy(sTotalusedlength, "Skupna uporabljena dolžina");
	strcpy(sTrigonometric, "Trigonometrično");
	strcpy(sTrim, "Porezati");
	strcpy(sTrimalledgesatthebeginning, "Na začetku poreži vse robove");
	strcpy(sTrimEdge, "Poreži rob");
	strcpy(sTwoPanels, "Dva delovna panela");
	strcpy(sType, "Tip");
	strcpy(sTypeofmaterialfromwhichtocut, "Tip materiala iz katerega režemo");
	strcpy(sTypesAreNotMatched, "Optimizacija ni bila izvedena! Trenutno tega materiala ni na zalogi! Kose lahko izrežete iz listov istega materiala. Spremenite nekaj materialov iz ustreznega stolpca!");
	strcpy(sUndo, "Razveljavi");
	strcpy(sUndoAccept, "Razveljavi Sprejmi");
	strcpy(sUnits, "Enote");
	strcpy(sUnregisteredVersion, "Neregistrirani");
	strcpy(sUpdates, "Posodobitve");
	strcpy(sUsefulforwoodfurniture, "Uporabno za leseno pohištvo");
	strcpy(sUseit, "Uporabite ga");
	strcpy(sUsePieceinOptimization, "Uporabite kos v optimizaciji");
	strcpy(sUserName, "Uporabniško ime");
	strcpy(sUtilizationandWastes, "Izkoristek in odpad");
	strcpy(sUtilizedArea, "Območje izkoriščenih delov");
	strcpy(sUtilizedBars, "Izkoriščene palice");
	strcpy(sUtilizeddemandcount, "Število izkoriščenih delov");
	strcpy(sUtilizedParts, "Izkoriščenih delov");
	strcpy(sUtilizedPieces, "Izkoriščenih kosov");
	strcpy(sUtilizedSheets, "Izkoriščenih plošč");
	strcpy(sValue, "Vrednost");
	strcpy(sValueGreaterEqualToZero, "Vrednost mora biti večja ali enaka nič");
	strcpy(sValueGreaterThanZero, "Vrednost mora biti večja od nič");
	strcpy(sValueIntegerNumber, "Vrednost mora biti celo število!");
	strcpy(sValueRealNumber, "Vrednost mora biti realno število. Morda ste uporabili vejico namesto pike ali obratno. Prosimo, popravite!");
	strcpy(s_The_number_is_too_big_or_it_has_too_many_digits_after_decimal_separator, "Število je preveliko ali pa ima preveč decimalnih mest!");
	strcpy(s_The_number_is_too_big, "Število je preveliko!");
	strcpy(sVertical, "Navpično");
	strcpy(sWaste, "Odpadki");
	strcpy(sWastes, "Odpadki");
	strcpy(sWasteAddedToWarehouse, "Ostanke dodaj v zalogo");
	strcpy(sWastelimits, "Razpon za odpad");
	strcpy(sWasteType, "Vrsta odpada");
	strcpy(sWeakoptimization, "Najšibkejša optimizacija");
	strcpy(sWhattoprint, "Kaj naj natisnem?");
	strcpy(s_What_to_print_or_save_to_file, "Kaj natisniti ali shraniti v datoteko");
	strcpy(sWhattoprintoneachpiece, "Kaj natisniti na vsakem kos?");
	strcpy(sWhattoshowoneachpiece, "Kaj pokazati na vsakem kosu?");
	strcpy(sWidth, "Širina");
	strcpy(sWood, "les");
	strcpy(sWorkingDirectory, "Delovni imenik");
	strcpy(sWrongKey, "Napačen registracijski ključ");
	strcpy(sYes, "Da");
	strcpy(sYoucannotchooseblackblueorredcolors, "Ne morete izbrati črne, modre ali rdeče barve.");
	strcpy(sYouCannotMixFractionalDataWithDecimalOnes, "Ne morete mešati ulomkov z dejanskimi vrednostmi!");
	strcpy(sYourcompany, "Vaše podjetje");
	strcpy(sZip, "Poštna številka");
	strcpy(s_Set_the_origin_and_the_direction_of_the_axes, "Nastavite izhodišče in smer koordinatnih osi.");

}
