// Language strings: Turkish
// Author: Optimal Programs
// License: MIT License
//---------------------------------------------------------------------------
#include <string.h>
//---------------------------------------------------------------------------
#include "language_string_id.h"
//---------------------------------------------------------------------------
void set_tr(void)
{
	// Turkish
	// did not check manually
	// last update on: 2025.11.01.0

	strcpy(s_Area, "Alan");
	strcpy(s_Mass, "Kütle");
	strcpy(s_Advanced, "Gelişmiş");
	strcpy(s_Relative_coordinates, "Bağıl koordinatlar");
	strcpy(s_Absolute_coordinates, "Mutlak koordinatlar");
	strcpy(s_Append_more_rows, "Daha fazla satır ekle");

	strcpy(s_Add_to_parts, "Parçalara ekleyin.");
	strcpy(s_Additional, "Ek olarak");
	strcpy(s_All_results, "Tüm sonuçlar.");
	strcpy(s_Allow_movement_of_pieces, "Parçaların hareketine izin ver");
	strcpy(s_Allow_part_in_part, "Parça parça izin ver");
	strcpy(s_Invalid_piece_Angles_are_too_small_or_too_big_or_height_is_too_small, "Geçersiz parça! Açılar çok küçük veya çok büyük, veya yükseklik çok küçük.");
	strcpy(s_Append, "ekleme");
	strcpy(s_As_it_is, "Olduğu gibi");
	strcpy(s_As_text, "metin olarak");
	strcpy(s_Ascending, "yükselen");
	strcpy(s_Automatic, "Otomatik");
	strcpy(s_Cannot_connect_to_the_Internet_Please_visit_our_website_from_a_browser, "İnternete bağlanılamıyor! Lütfen bir tarayıcıdan web sitemizi ziyaret edin.");
	strcpy(s_Cannot_copy_or_move_the_files, "Dosyaları kopyalayamaz veya taşıyamazsınız!");
	strcpy(s_Cannot_delete_the_file, "Dosya silinemez!");
	strcpy(s_Cannot_modify_old_results, "Eski sonuçlar değiştirilemiyor!");
	strcpy(s_To_change_click_inside_a_cell_or_press_0_1_or_2, "Değiştirmek için bir hücrenin içini tıklayın veya 0, 1 veya 2'ye basın.");
	strcpy(s_Cell, "Hücre");
	strcpy(s_Click_on_the_table_header_to_change_the_columns, "Sütunları değiştirmek için tablo başlığına tıklayın.");
	strcpy(s_Close, "Kapat onu");
	strcpy(s_Contact_us, "Bize Ulaşın");
	strcpy(s_Column, "Kolon");
	strcpy(s_Comma, "Virgül");
	strcpy(s_The_comma_symbol_cannot_simultaneously_be_the_list_separator_and_the_decimal_separator, "Virgül simgesi aynı anda hem liste ayırıcısı hem de ondalık ayırıcısı olamaz!");
	strcpy(s_Copy, "Kopyala");
	strcpy(s_Copy_for_move, "Taşınmak için kopyala");
	strcpy(s_Cut_higher_level_strips_first, "Önce daha yüksek seviyedeki şeritleri kesin");
	strcpy(s_Cut_index, "Kesme indeksi göster");

	strcpy(s_The_data_have_been_changed_Do_you_want_to_save_them_to_a_file, "Veriler değiştirildi. Onları bir dosyaya kaydetmek istiyor musunuz?");
	strcpy(s_Decimal_separator, "ondalık ayırıcı");
	strcpy(s_Restore_default_settings, "Varsayılan ayarları geri yükle");
	strcpy(s_Delete_fiber, "Lifleri sil");
	strcpy(s_Descending, "Azalan");
	strcpy(s_Discard_changes, "Değişiklikleri gözardı et");

	strcpy(s_Delete_all_data, "Tüm veriler silinsin mi?");
	strcpy(s_Dot, "Nokta");
	strcpy(s_Do_you_want_to_delete_the_picture, "Resmi silmek istiyor musunuz?");
	strcpy(s_Do_you_want_to_delete_the_product, "Ürünü silmek istiyor musunuz?");
	strcpy(s_Duplicate_and_append, "Çoğaltın ve ekleyin.");
	strcpy(s_Duplicate_values_are_ignored, "Yinelenen değerler göz ardı edildi!");
	strcpy(s_Error, "Hata");
	strcpy(s_Error_loading_file, "Dosya yüklenirken hata oluştu.");
	strcpy(s_export_everything, "Her şeyi dışa aktar");
	strcpy(s_Fit_to_screen, "Ekrana sığdır.");
	strcpy(s_Force_fixed_height, "Parçaları sabit yükseklikte çizin.");
	strcpy(s_Flipped, "Ters çevrilmiş");
	strcpy(s_Import, "İthalat");
	strcpy(s_If_angles_are_different_from_90_degrees_height_must_be_greater_than_0, "Açılar 90 dereceden farklı ise yükseklik 0'dan büyük olmalıdır.");
	strcpy(s_Ignore, "Görmezden gelmek");
	strcpy(s_Incorrect_value, "yanlış değer");
	strcpy(s_Info, "Bilgi");
	strcpy(s_Interior, "içeride");
	strcpy(s_Give_a_name, "İsim ver.");
	strcpy(s_Group, "gruplayın");
	strcpy(s_Header, "Başlık");
	strcpy(s_Keep_it_as_it_is, "Olduğu gibi tut");
	strcpy(s_Level, "Level");
	strcpy(s_Licensee, "Lisans Sahibi");
	strcpy(s_List_separator, "Liste ayırıcı");
	strcpy(s_Made_with_love_in_Cugir_Romania, "Sevgiyle üretildi: Cugir, Romanya");
	strcpy(s_Made_in, "Üretildi");
	strcpy(s_Manufacturer, "Üretici firma");

	strcpy(s_Manual_arrange, "Manuel düzenleme");

	strcpy(s_Mixed, "Karışık");
	strcpy(s_Multiple_shapes_detected_Next_rows_will_be_overwritten_Continue, "Birden fazla şekil algılandı. Bu nedenle, sonraki satırların üzerine yazılacaktır. Devam et?");
	strcpy(s_More, "Daha");
	strcpy(s_Multiple_values, "Birden çok değer");
	strcpy(s_No_texture, "Doku Yok");
	strcpy(s_Number, "Numara");
	strcpy(s_Number_of_images, "Görüntü sayısı");
	strcpy(s_Number_of_vertices, "Köşe sayısı");
	strcpy(s_Offset, "Telafi etmek");
	strcpy(s_Only_the_currently_selected_items, "Yalnızca şu anda seçili olan öğeler.");
	strcpy(s_Optimizing_please_wait, "Optimize ediliyor ... lütfen bekleyin.");

	strcpy(s_Paste, "Paste");

	strcpy(s_Piece_label, "Parça etiketi göster");
	strcpy(s_Piece_size, "Parçaların boyut göster");
	strcpy(s_Please_contact_us_by_email_if_you_receive_this_error, "Bu hatayı alırsanız lütfen bize e-posta ile ulaşın.");
	strcpy(s_Please_save_it_first, "Lütfen önce onu kaydedin.");
	strcpy(s_Position, "Durum");
	strcpy(s_Preview, "Ön izleme");
	strcpy(s_Rectangle, "Dikdörtgen");

	strcpy(s_Redo_the_last_operation, "Son işlemi geri yükle");
	strcpy(s_Regular_polygon, "Düzenli çokgen");

	strcpy(s_Reused, "Yeniden kullanmak");
	strcpy(s_Rotated, "Döndürülmüş");
	strcpy(s_Save_all, "Hepsini kaydet");
	strcpy(s_Scrap_label, "Atık etiketi göster");
	strcpy(s_Scrap_size, "Atıkların boyutunu göster");
	strcpy(s_Semicolon, "Noktalı virgül");
	strcpy(s_Show_cut_index, "Kesme indeksi göster");
	strcpy(s_Show_information, "Bilgi göster");
	strcpy(s_Show_piece_label, "Parça etiketi göster");
	strcpy(s_Show_scrap_label, "Atık etiketi göster");
	strcpy(s_Show_scrap_s_size_on_the_small_pieces, "Küçük parçalarda hurda boyutunu göster");
	strcpy(s_Show_size_of_pieces, "Parçaların boyut göster");
	strcpy(s_Show_size_of_scrap, "Atıkların boyutunu göster");
	strcpy(s_Show_sizes, "Boyutları göster");
	strcpy(s_Show_label, "etiketi göster");
	strcpy(s_Show_length, "Uzunluğu göster");

	strcpy(s_Some_numerical_values_are_incorrect_Should_I_fix_all_the_incorrect_values, "Bazı sayısal değerler yanlış! Tüm yanlış değerleri düzeltmeli miyim?");
	strcpy(s_Some_invalid_values_have_been_removed, "Bazı geçersiz değerler kaldırıldı.");
	strcpy(s_Sort_by, "Göre sırala");
	strcpy(s_Sort_ascending_by, "Sıralama ölçütü");
	strcpy(s_Sort_descending_by, "Azalanlara göre sırala");
	strcpy(s_Start, "Start");
	strcpy(s_Starting_angle, "Başlangıç açısı");
	strcpy(s_Sticker, "Çıkartma");

	strcpy(s_Stock, "Envanter");
	strcpy(s_Stop, "Stop");
	strcpy(s_System_setting, "Sistem ayarı");
	strcpy(s_Tabular, "tablo şeklinde");
	strcpy(s_Total, "Toplam");
	strcpy(s_Total_size, "Toplam boyut");
	strcpy(s_Terms_of_the_license, "Lisans koşulları");
	strcpy(s_The_current_product_has_been_changed_Do_you_want_to_save_it_to_file, "Mevcut ürün değiştirildi. Dosyaya kaydetmek istiyor musunuz?");
	strcpy(s_The_value_is_out_of_the_allowed_range, "Değer, izin verilen aralığın dışında.");
	strcpy(s_The_value_must_be_a_real_or_fractional_number_Try_to_replace_the_comma_with_the_dot_if_you_want_to_enter_a_real_number, "Değer, gerçek veya kesirli bir sayı olmalıdır. Gerçek bir sayı girmek istiyorsanız virgül ile nokta değiştirmeyi deneyin.");
	strcpy(s_This_feature_is_not_implemented_yet, "Bu özellik henüz uygulanmadı.");
	strcpy(s_This_operation_cannot_be_reversed, "Bu işlem geri alınamaz.");
	strcpy(s_Undo_the_last_operation, "Son işlemi geri al.");
	strcpy(s_Utilization, "kullanım");
	strcpy(s_Utilized_Stock, "Kullanılan Stok");
	strcpy(s_Version, "Sürüm");
	strcpy(s_Visible_columns, "Görünür sütunlar");
	strcpy(s_You_already_have_the_latest_version_installed, "En son sürüm zaten kurulu!");
	strcpy(s_What_is_exported, "Ne ihraç edilir?");
	strcpy(s0meansanynumberofpieces, "Sıfır parçalar manasına gelir");
	strcpy(sAbout, "Hakkında");
	strcpy(sAccept, "Kabul etmek");
	strcpy(sAcceptall, "Tüm kabu");
	strcpy(sAcceptthecurrentsolution, "Geçerli çözüm kabu");
	strcpy(sAdd, "Ekle");
	strcpy(sAddapiece, "Bir parça ekleme");
	strcpy(sAddasimpleproducttoDemand, "Mevcut talep bir ürün ekleyin.");
	strcpy(sAddgrindingthicknesstopartsize, "parça boyutu öğütme kalınlığı Ekle");
	strcpy(sAddproductnametolabel, "Etiket ürün adı ekleyin");
	strcpy(sAddress, "Adres");
	strcpy(sAddselectedsizetoInventory, "Envanter seçilen boyut ekleyin");
	strcpy(sAdhesivelabels, "Yapışkan etiketler");
	strcpy(sAdhesivelabelwithinformationaboutpiecesinDemandCustomernameLabelSizeCurrentData, "Müşteri adı, Etiket, Boyut, Current Data: Talep parçalar hakkında bilgi yapışkanlı etiket.");
	strcpy(sAdhesivelabelwithinformationaboutsheetsinInventory, "Stok sayfaları hakkında bilgi yapışkanlı etiket.");
	strcpy(sAll, "Herşey");
	strcpy(sAlloffcutswhichhavethesizegreaterthanthisvaluewillbeaddedtoInventory, "Bu değerden daha büyük boyutta Stok tüm artıkları ilave edilecektir");
	strcpy(sAllowMirroring, "Yansıtma izin ver");
	strcpy(sAllowRotation, "Rotasyonuna izin vermektedir");
	strcpy(sAllPieces, "Tüm adettir");
	strcpy(sAllpredefinedproducts, "Tüm önceden tanımlanmış ürünler");
	strcpy(sAnewwindowwillbedisplayedwheretheusercansettheedgebandsforeachedge, "yeni bir pencere kullanıcı her kenar bantları ayarlayabilirsiniz hangi gösterilecektir.");
	strcpy(sAnewwindowwillbedisplayedwheretheusercansetthegrindingvalueforeachedgeofthsheet, "yeni bir pencere kullanıcı parçasının her kenar için taşlama değeri ayarlayabilirsiniz hangi gösterilecektir.");
	strcpy(sAnewwindowwillbedisplayedwheretheusercansetthetrimvalueforeachedgeofthsheet, "Kullanıcı parçasının her kenar için kusurları ayarlayabileceğiniz yeni bir pencere açılacaktır.");
	strcpy(sAngle, "Açı");
	strcpy(sAngles, "Açılar");
	strcpy(sAnoptimizationparameterisarealnumber, "bir optimizasyon parametresi bir gerçek sayıdır.");
	strcpy(sAnoptimizationparameterisfractionalnumber, "bir optimizasyon parametresi kesirli sayıdır.");
	strcpy(sAnyShape, "Herhangi bir şekil");
	strcpy(sApolygonmusthaveatleast2vertices, "Bir çokgenin en az 2 köşesi olmalıdır!");
	strcpy(sApolygonmusthaveatleast3vertices, "Bir çokgenin en az 3 köşesi olmalıdır!");
	strcpy(sApplication_fails_to_initialize, "Yazılım başlatma başarısız oldu.");
	strcpy(sArc, "Ark");
	strcpy(sArcLength, "Yay uzunluğu");
	strcpy(sAreaofusedsheets, "Kullanılan yaprak Alanı");
	strcpy(sAshortdescriptionofthesheet, "Sayfasının kısa açıklaması");
	strcpy(sAtleastonepart, "En az bir parça devreye sokulmalıdır.");
	strcpy(sAtTheMarginOfTheSheet, "Sayfanın kenarında");
	strcpy(sBandtypes, "Kenar bandı çeşitleri.");
	strcpy(sBar, "Çubuklar / boru");
	strcpy(sBars, "Çubuklar / boru");
	strcpy(sBothsizesoftheoffcutsmustbegreaterthanthisvalue, "Offcuts Her iki boyutları bu değerden daha büyük olmalıdır.");
	strcpy(sBottom, "Alt");
	strcpy(sBottomcoordinateofthedefect, "Defekt alt koordinat");
	strcpy(sBreakCut, "Kesme kırmak");
	strcpy(sBrowse, "Gözat");
	strcpy(sBuy, "Satın almak");
	strcpy(sBuynow, "Şimdi satın al ...");
	strcpy(sCancel, "Bunu ipta");
	strcpy(sCannotBeEmpty, "boş olamaz!");
	strcpy(sCannotmovepartsbetweensheetswhenidenticalsheetsaregroupedPleaseungroupthesheetsfrommenu, "özdeş sayfaları gruplanmış olup olmadığını başka bir sacdan parçaları taşınamaz menüden yaprak gruplama iptal ediniz..");
	strcpy(sCannotSaveFile, "Dosyayı kaydedilemiyor");
	strcpy(sCenter, "Merkezi");

	strcpy(sChangeDirection, "Yönünü değiştirin");
	strcpy(sChoose, "Seçmek");
	strcpy(sChooseProduct, "Ürün Seçin");
	strcpy(sCircle, "Daire");
	strcpy(sCity, "Şehir");
	strcpy(sClear, "Temizle");
	strcpy(sClockWise, "Saat yönünde");
	strcpy(sClosewindow, "Pencereyi kapat");
	strcpy(sColor, "Renk");
	strcpy(sColorofedgeband, "Kenar bandı rengi");
	strcpy(sColorPattern, "Renk / Desen");
	strcpy(sColorpiecesandwastes, "Parçalar ve atıklar renkli.");
	strcpy(sColumns, "Sütunlar");
	strcpy(sComment, "Yorumlamak");
	strcpy(sCompanyname, "Şirket adı");
	strcpy(sComplexMaterialExists, "Malzemenin Adı zaten karmaşık malzemeler listesinde tanımlanır. Yeni bir ad verin.");
	strcpy(sComputerCode, "Bilgisayar kodu");
	strcpy(sComputerCodefromyourcomputer, "Bilgisayar Kodu (bilgisayarınızdan)");
	strcpy(sComputethetotalpriceofDemand, "Talep toplam tutarı hesaplayınız");
	strcpy(sContents, "Içindekiler");
	strcpy(sContinutComanda, "Tarihi Talep İçeriği");
	strcpy(sContinutDepozit, "Tarihi Envanter İçeriği");
	strcpy(sConversionIsDoneOnlyWhenSomePiecesHaveFractionalValues, "Bazı parçaları kesirli değerler olduğunda dönüşümü yapılır.");
	strcpy(sConvertsTheSizeOfWasteToAFractionalUnit, "Küçük bir değer olarak atık boyutunu gösterir.");
	strcpy(sCouldNotSaveFile1, "Dizinde dosyayı yazamadı");
	strcpy(sCouldNotSaveFile2, "Yeterince haklara sahip olmayabilirsiniz. Sana yazmak için haklar (örneğin c:\\temp) sahip olduğu bir klasöre Çalışma dizini | menüsünden Ayarlar çalışma dizinini kontrol edin veya değiştirin.");
	strcpy(sCreationdateYMDHMS, "Oluşturma tarihi (Y / M / D, H: M: S)");
	strcpy(sCurrentDate, "Güncel tarih");
	strcpy(sCurrentDiagram, "Mevcut diyagram");
	strcpy(sCurrentMaterial, "Mevcut Malzeme");
	strcpy(sCurrentversion, "Current version");
	strcpy(sCurve_not_closed_Try_increasing_DXF_linking_distance_parameter, "Çokgen kapalı değil! DXF bağlantı mesafesi parametresini artırmayı deneyin.");
	strcpy(sCustomer, "Müşteri");
	strcpy(sCustomerName, "Müşteri Adı");
	strcpy(sCustomMessage, "Özel mesaj");
	strcpy(sCutlength, "Kesme uzunluğu");
	strcpy(sCut, "Kesmek");
	strcpy(sCuts, "Cuts");
	strcpy(sCutterThickness, "Kesme kalınlığı");
	strcpy(sData, "Veri");
	strcpy(sDataCannotBeEmpty, "Veri boş olamaz!");
	strcpy(sDateymdhms, "Tarih (y / m / d / s / m / s)");
	strcpy(sDays_left_for_trial, "Test için kullanılabilir Günler ");
	strcpy(sDaysLeft, "gün kaldı");
	strcpy(sStandard, "Standart");
	strcpy(sDefaultInterface, "Standart arayüz");
	strcpy(sDefects, "Kusurlar");
	strcpy(sDefectsManager, "Kusurları yönet");
	strcpy(sDefectsofthematerialNopiecescanbeplacedinthefaultyzone, "Malzemenin arızalar. Resim parçalar hatalı bölge içinde yerleştirilebilir.");
	strcpy(sDelete, "Silmek");
	strcpy(sDeletePiece, "Parça silme");
	strcpy(sDeleteRow, "satır Si");
	strcpy(sDemandutilization, "Talebin Kullanımı");
	strcpy(sDepozitulmodificat, "Kullanılan parçalar kaldırıldı. Kalıntıları stok eklenmiştir.");
	strcpy(sDepozitvid, "Stok boş");
	strcpy(sDesk, "büro");
	strcpy(sDiagram, "Diyagram");
	strcpy(sDiagrams, "Diyagramlar");
	strcpy(sDiagramasatable, "Bir tablo olarak Diyagramı");
	strcpy(sDigits, "Rakamlar");
	strcpy(sDimensiuniplaca, "Levha boyutları");
	strcpy(sDirection, "Yön");
	strcpy(sDistanceBetweenRows, "Satırlar arasındaki mesafe");
	strcpy(sDonotuseit, "Kullanmak etmeyin");
	strcpy(sDownload, "İndir");
	strcpy(sDoYouWantToClearTheData, "Siz verileri silmek istediğinizden?");
	strcpy(sDoYouWantToSaveDemand, "Parça değiştirildi! Sen değişiklikleri kaydetmek istiyor?");
	strcpy(sDoYouWantToSaveParts, "Eğer parça kaydetmek istiyor musunuz?");
	strcpy(sDoYouWantToSaveRepository, "Stokta değiştirildi! Sen değişiklikleri kaydetmek istiyor?");
	strcpy(sDrawing, "Çizimler");
	strcpy(sDrawthesolutioncolorful, "Renkli çözelti çizme");
	strcpy(sDuplicateTypes, "Bazı türleri çoğaltılır! Yinelenenleri kaldırmak Lütfen");
	strcpy(sDuplicateTypesWithComplex, "Malzemelerin Bazı isimleri zaten karmaşık türleri listesinde mevcut! Yinelenenleri kaldırmak Lütfen");
	strcpy(sDuplicateValues, "Yinelenen değerler");
	strcpy(sEdgeband, "Kenarları için Gruplar");
	strcpy(sEdgebandingwhichisplacedontheedgesofyourpiecePleasedefineedgebandingtypesfromMaterialsEdgeBandingmenu, "Edge sizin parçasının kenarlarına yerleştirildiği bantlama. Malzemeler menüden kenar bantlama türlerini belirtiniz.");
	strcpy(sEdgebandsthatwillbeappliedtoeachpart, "Her bir kısım için geçerli olacaktır kenar bantları.");
	strcpy(sEdgeBandTolerance, "Kenar bantlama Tolerans");
	strcpy(sEdgesthatmustbecutduefaults, "Nedeniyle arızalar kesilmelidir Kenarlarını.");
	strcpy(sEdgetoedge, "Uçtan bir uca");
	strcpy(sEdit, "Düzenle");
	strcpy(sEmail, "E-posta");
	strcpy(sEmptyData, "Veri boş!");
	strcpy(sEnabled, "Etkin");
	strcpy(sEnabledisabledefectsoftheinventorysheets, "Stokunun kusurları Etkinleştir / devre dışı");
	strcpy(sEnterLabel, "Input labe");
	strcpy(sEnterTheMaterialName, "Malzeme girişi isim");
	strcpy(sEnterTheProductName, "Ürünün adını girmek");
	strcpy(sEvaluationError, "Ifade değerlendirme için Hata!");
	strcpy(sExit, "Çıkış");
	strcpy(sExpired, "Yazılımınızın süresi doldu! Yazılım kayıt olun!");
	strcpy(sExport, "İhracat");
	strcpy(sExportAllDiagrams, "Tüm diyagramları dışa aktar");
	strcpy(sExportAllToASingleFile, "Tümünü tek bir dosyaya aktar");
	strcpy(sExportOptions, "İhracat seçenekleri.");
	strcpy(sExporttoDXFformat, "DXF formatında Aktar");
	strcpy(sExporttoExcel, "Excel'e Aktar");
	strcpy(sExpresieIncorecta, "Yanlış matematiksel ifade!");
	strcpy(sExtensions, "Uzantıları");
	strcpy(sExtra, "Ilave");
	strcpy(sExtraComponents, "Ekstra Bileşenleri");
	strcpy(sExtracomponentsattachedtoDemand, "İlave bileşenler parçalar eklenmiş");
	strcpy(sFile, "Dosya");
	strcpy(sFileName, "Dosya adı");
	strcpy(sFillWastes, "Oblik hatları ile atık Berabere");
	strcpy(sFindoptimalbarsheetsize, "Boru ve levha için en uygun boyutu bulun.");
	strcpy(sFindoptimalsizeofInventorypieces, "Stokta adet optimal boyutu bulun");
	strcpy(sFirstcutMultiplestages, "İlk kesim yönü - Çoklu aşamaları");
	strcpy(sFirstdirectionforcutishorizontal, "Kesim için Birinci yönü yataydır.");
	strcpy(sFirstdirectionforcutisvertical, "Kesim için Birinci yönü dikey.");
	strcpy(sFollowthecontourofpieces, "Adet kontur izleyin");
	strcpy(sFont, "Yazı");
	strcpy(sFontsize, "Yazı tipi boyutu");
	strcpy(sFullInfo, "Tam bilgi");
	strcpy(sDisposedWaste, "Bertaraf edilmiş atık");
	strcpy(sGeneral, "gene");
	strcpy(sGenerateCNC, "CNC Oluştur");
	strcpy(sGrain, "Lif");
	strcpy(sGraindirection, "Doku yönü");
	strcpy(sGraphic, "Grafik");
	strcpy(sGreaterorequalto, "Büyük veya eşit");
	strcpy(sGrid, "Tablolar ");
	strcpy(sGrinding, "taşlama kalınlığındaki");
	strcpy(sGrosimeTaieturaScalata, "Adet gerçek ölçekte temsil edilmemektedir çünkü bu resimden kesim kalınlığı gerçek birinden farklı olabilir. Bu gerçek sonuçları etkilemez.");
	strcpy(sGroupidenticallayouts, "Özdeş sayfaları gruplandırma");
	strcpy(sGroupIdenticalParts, "Özdeş parçaları gruplandırılmış.");
	strcpy(sGroupingOfIdenticalPiecesIntoOneRow, "Bir satır içine aynı adet gruplama.");
	strcpy(sGroupPartsAfterLoadingFromFile, "Dosyadan yükledikten sonra parçaları Gruplandırma");
	strcpy(sHeight, "Yükseklik");
	strcpy(sHeighttolerance, "Yükseklik Tolerans");
	strcpy(sHelp, "Yardım");
	strcpy(sHistory, "Tarih");
	strcpy(sHorizontal, "Yatay");
	strcpy(sHowtodisplayprintedgebands, "Bu kenar bantları görüntüler nasıl?");
	strcpy(sIfyousetthebandforoneedgeallwillreceivethesamevalue, "Bir kenar bandı ayarlarsanız, hepsi aynı değerini alacaktır.");
	strcpy(sIfyousetthegrindingforoneedgeallwillreceivethesamevalue, "Bir kenar taşlama değeri ayarlarsanız, bütün kenarları aynı değeri alacaktır.");
	strcpy(sIfyousetthetrimforoneedgeallwillreceivethesamevalue, "Bir kenar temizleme değeri ayarlarsanız, bütün kenarları aynı değeri alacaktır.");
	strcpy(sImageBounds, "Görüntü için Bounds");
	strcpy(sImageSize, "Görüntü boyutu.");
	strcpy(sImportData, "veri alma");
	strcpy(sIncorrectPassword, "Yanlış şifre");
	strcpy(sIndex, "Index");
	strcpy(sInformationaboutcustomer, "Müşteri ile ilgili bilgiler");
	strcpy(sInputALanguageName, "Dil için bir isim verin");
	strcpy(sInsert, "Yerleştirin");
	strcpy(sInsertPiece, "Parça ekleme");
	strcpy(sInterface, "Arayüz");
	strcpy(sInterfaceSettings, "Arayüz ayarları");
	strcpy(sInvalidHardware, "Ben donanım tespit edilememiştir. Contact@optimalprograms.com bize ulaşın");
	strcpy(sInvalidNumber, "Geçersiz numara");
	strcpy(sInvalidOrderOfComputation, "Uzunlukları hesaplamak için bir düzeni tesis edilemez. Ürün tanımı dairesel ilişkiler vardır!");
	strcpy(sInvalidRegistration, "Kayıt geçersizdir!");
	strcpy(sInvalidTime, "Sisteminizin saat geçersiz.");
	strcpy(sInventory, "Envanter");
	strcpy(sisafractionalvalue, "kesirli bir değerdir.");
	strcpy(sIsArc, "Yay");
	strcpy(sisarealvalue, "gerçek bir değerdir.");
	strcpy(sLabel, "Etiket");
	strcpy(sLabels, "Etiketler");
	strcpy(sLanguage, "Di");
	strcpy(sLatimeanumar0, "Genişliği 0'dan büyük olmalı!");
	strcpy(sLatimeanumarreal, "Genişliği gerçek sayı olmalıdır!");
	strcpy(sLayerName, "Katman adı");
	strcpy(sLeft, "So");
	strcpy(sLeftcoordinateofthedefect, "Defekt sol koordinat");
	strcpy(sLength, "Uzunluk");
	strcpy(sLengthofthepiecestocut, "Kesme Parça boyutu");
	strcpy(sLengthofthepiecestocutfrom, "Kesme Levha boyutu");
	strcpy(sLengthofusedbars, "Kullanılan çubukların Boyutu");
	strcpy(sLicenseAgreement, "Lisans anlaşması");
	strcpy(sLinear, "Doğrusa");
	strcpy(sLinethickness, "Kalem kalınlığı");
	strcpy(sLoadafileandappenddatatothecurrentDemand, "Bir dosya yükleyin ve güncel Talebi veri eklenecek.");
	strcpy(sLoadanexistingDemandfromafile, "Bir dosyadan varolan Talep yükleyin.");
	strcpy(sLoadAppend, "Yük ve Append");
	strcpy(sLoadEverything, "Yük herşey");
	strcpy(sLoadInventory, "Stoğu yükleyin");
	strcpy(sLoadInventoryandDemand, "Stok ve talep yükleyin");
	strcpy(sLoadResults, "Sonuçlar Yük");
	strcpy(sLocked, "kilitli");
	strcpy(sLogo, "logo");
	strcpy(sLong, "Uzun");
	strcpy(sLongerexecutiontime, "Uzun yürütme zamanı");
	strcpy(sLungime, "Genişlik");
	strcpy(sLungimeanumar0, "Uzunluğu 0'dan büyük olmalı!");
	strcpy(sLungimeanumarreal, "Uzunluğu gerçek sayı olmalıdır!");
	strcpy(sLungimeaTotalaFolosita, "Toplam kullanılan uzunluk");
	strcpy(sMagnification, "Büyütme");
	strcpy(sMagnify, "Büyütmek");
	strcpy(sMargins, "Kenar Boşlukları");
	strcpy(sMarginsForPaper, "Kağıt için Kenar Boşlukları");
	strcpy(sMarginsOfTheLabel, "Etiketin Kenar");
	strcpy(sMaterial, "Malzeme");
	strcpy(sMaterialName, "Malzeme Adı");
	strcpy(sMaterials, "Malzemeler");
	strcpy(sMaterialstypes, "Malzeme türleri");
	strcpy(sMax, "maksimum");
	strcpy(sMaximalArea, "Maksimal alanı");
	strcpy(sMaximalCutLength, "Maksimal kesme uzunluğu");
	strcpy(sMaxlength, "Maksimal uzunluk");
	strcpy(sMaxPiecesperBar, "Bar başına maksimum Adet");
	strcpy(sMaxwidth, "Maksimal genişliği.");
	strcpy(sMeasurementUnit, "Ölçü birimi");
	strcpy(sMin, "Min");
	strcpy(sMinimalBreakSize, "Minimal rüptürü boyutu");
	strcpy(sMinimalUsefulSize, "Minimal kullanışlı boyutu");
	strcpy(sMinimalwastesizetoInventory, "Envanter için minimum atık boyutu");
	strcpy(s_What_to_minimize, "Neyi en aza indirmeli?");
	strcpy(sMinlength, "Minimal uzunluğu");
	strcpy(sMinwidth, "Minimal genişliği");
	strcpy(sMirror, "Ayna");
	strcpy(sMirroring, "Yansıtma");
	strcpy(sMiscellaneous, "Çeşitli");
	strcpy(sModify, "Değiştirmek");
	strcpy(sModifytheselectedpiece, "Seçilen parçası değiştirin");
	strcpy(sMovePiece, "Parça taşıyın.");
	strcpy(sMultiplestages, "Çoklu aşamalar");
	strcpy(sName, "Isim");
	strcpy(sNameofedgeband, "Kenar bantları Adı");
	strcpy(sNewDEMANDUnsaveddatawillbelost, "Yeni parçalar? Kaydedilmemiş veriler kaybolacaktır!");
	strcpy(sNewLanguage, "Yeni di");
	strcpy(sNewMaterial, "Yeni Malzeme");
	strcpy(sNewPasswordincorectlyintroduced, "Yeni şifre yanlış tanıttı!");
	strcpy(sNewProduct, "Yeni ürün");
	strcpy(sNewversion, "Yeni sürüm");
	strcpy(sNo, "Hayır");
	strcpy(sNumarBucati, "Parça sayısı");
	strcpy(sNumberOfCopies, "Kopya sayısı");
	strcpy(sNumberofstages, "Kademe sayısı");
	strcpy(sNusuficienteplacidepozit, "Tüm parçaları optimize edilmiştir değil. Olası nedenler: stokta yeterli adettir değildir; Adet optimizasyon kullanılan değildir; Talep ve envanterinden Malzemeler uyumlu değildir; Diğer parametreler yanlış ayarlanmış edilmiştir.");
	strcpy(sOfficeNotInstaled, "Bilgisayarınızda Microsoft Office veya incorect sürüm yüklenmez yüklü!");
	strcpy(sOldpassworddoesnotmatch, "Eski şifre eşleşmiyor!");
	strcpy(sOnlinehelp, "Online yardım");
	strcpy(sOnlypiecesofthesameheightinthelaststage, "Son aşamada aynı yükseklikte Adet");
	strcpy(sOpen, "Açık");
	strcpy(sOptimization, "Optimizasyon");
	strcpy(sOptimizationDone, "Optimizasyon uygulandı! Sen elde diyagramları yazdırabilir veya kaydedebilirsiniz. Eğer geçerli çözüm memnun iseniz düğmesine basın Kabul. Aksi takdirde, yine Başlat düğmesine basın.");
	strcpy(sOptimizationType, "Optimizasyon Türü");
	strcpy(sOptions, "Seçenekler");
	strcpy(sOptionsrelatedtotheinterface, "Arayüz ile ilgili seçenekler");
	strcpy(sor, "veya");
	strcpy(sOthercomponents, "Diğer bileşenler");
	strcpy(sOthers, "Diğerleri");
	strcpy(sOtherstatistics, "Diğer istatistikler");
	strcpy(sOverrideExcelCSVfiles, "Excel / CSV dosyaları geçersiz kılma");
	strcpy(sParameter, "Parametre");
	strcpy(sParts, "PARÇA");
	strcpy(sPattern, "Mode");
	strcpy(sPatternforwaste, "Atık Desen");
	strcpy(sPerimeter, "Çevre");
	strcpy(sPermitedRotationAngle, "İzin verilen dönme açısı.");
	strcpy(sPhone, "Telefon");
	strcpy(sPicture, "görüntü");
	strcpy(sPiece, "Parça");
	strcpy(sPieceindex, "Adet dizin");
	strcpy(sPieces, "Parçalar");
	strcpy(sPiecesize, "Parça boyutu");
	strcpy(sPiecesizelabeledgebandwillbeprinted, "Parça boyutu, etiket, kenar bantları basılacaktır.");
	strcpy(sPierdere, "Atık");
	strcpy(sPixels, "pikse");
	strcpy(sPlacilefolositeDepozit, "Envanter parçalar kullanılmıştır.");
	strcpy(sPlease_contact_us_at_contact_nestingtechnologies_com, "contact@nesting-technologies.com adresinden bizimle irtibata geçiniz");
	strcpy(sPlease_contact_us_at_contact_optimalprograms_com, "contact@optimalprograms.com adresinden bizimle irtibata geçiniz");
	strcpy(sPleaseenteralldataeitherasfractionalorrealDonotmixthem, "gibi kesirli veya gerçek ya da tüm verileri giriniz onları karıştırmayın!");
	strcpy(sPleaseEnterSomeTypesOfMaterials, "Tanımlanmış hiçbir materyal türü vardır. Sen Malzemeleri menüsünden bunları tanımlayabilirsiniz.");
	strcpy(sPleasesendtheNameandtheCodetotheaddresscontactoptimalprogramscominordertoobtaintheRegistrationKey, "Contact@optimalprograms.com: Kayıt Anahtarı elde edebilmek için Ad ve Kod gönderin.");
	strcpy(sPolygon, "Poligon");
	strcpy(sPolygonsCircles, "Çokgenler, daireler");
	strcpy(sPrecision, "Hassas");
	strcpy(sPretulnumar0, "Fiyat 0'dan büyük olmalı!");
	strcpy(sPretulnumarreal, "Fiyat gerçek sayı olmalıdır!");
	strcpy(sPreview, "önizleme");
	strcpy(sPrice, "Fiyat");
	strcpy(sPriceMustBeGreaterThanZero, "Fiyat sıfırdan büyük olmalıdır");
	strcpy(sPriceofbars, "Çubuklarının Et");
	strcpy(sPriceperbar, "Bar başına fiyat");
	strcpy(sPricepersheet, "Sayfa başına fiyat");
	strcpy(sPricepersquareunitofmaterial, "Malzeme kare birim başına fiyat.");
	strcpy(sPriceperunit, "Birim fiyat");
	strcpy(sPrint, "Baskı");
	strcpy(sPrintdiagramsastables, "Tablo şeklinde diyagramları yazdırma.");
	strcpy(sPrinter, "Yazıcı");
	strcpy(sPrinterBounds, "Yazıcı için Kenar Boşlukları");
	strcpy(sPrinting, "Baskı");
	strcpy(sPrintonlyutilizedarea, "Ancak kullanılan alan yazdırma");
	strcpy(sPrintthecontentsoftheDemand, "Talep içeriğini yazdırın.");
	strcpy(sPrintthecontentsoftheInventory, "Stok içeriğini yazdırın.");
	strcpy(sPrintthecurrentsolution, "Geçerli çözüm yazdırın.");
	strcpy(sPriority, "Öncelik");
	strcpy(sPrioritytocutapieceZero0isthehighestpriority, "Öncelik bir parça kesmek için. Sıfır (0) en yüksek önceliktir.");
	strcpy(sProcentul0100, "Yüzdeler 0'dan büyük ve küçük veya 100'e eşit olmalıdır!");
	strcpy(sProcentulnumarreal, "Yüzdeler gerçek sayı olmalıdır!");
	strcpy(sProductdefinition, "Ürün tanımı");
	strcpy(sProductExists, "Ürünü zaten var. Başka bir isim seçin.");
	strcpy(sProductName, "Ürün adı");
	strcpy(sProducts, "Ürün");
	strcpy(sProducts, "Ürünler");
	strcpy(sProject, "Proje");
	strcpy(sProperties, "Özellikler");
	strcpy(sProperty, "özellik");
	strcpy(sQuantity, "Miktar");
	strcpy(sQuantitynumberofsheetsofthistype, "Bu tür bir yaprak sayısı");
	strcpy(sRadius, "Yarıçapı");
	strcpy(sRectangular, "Dikdörtgen");
	strcpy(sRedefinetypesofedgeband, "Kenar bandı türleri Redefine");
	strcpy(sRedefinetypesofmaterial, "Malzeme tipleri Redefine");
	strcpy(sRegistration, "Kayıt");
	strcpy(sRegistrationKeyfromOptimalPrograms, "Kayıt Anahtarı");
	strcpy(sRegistrationSuccessful, "Kayıt başarılı!");
	strcpy(sRemoveallpiecesinInventory, "Envanter tüm parçaları çıkarın.");
	strcpy(sRemoveCut, "Kesilmiş Si");
	strcpy(sRemovetheselectedpiece, "Seçilen parçası çıkarın");
	strcpy(sReports, "Raporlar");
	strcpy(sRequestedMaterial, "İstenen Malzeme");
	strcpy(sRestore, "Restore");
	strcpy(sResults, "Sonuçlar");
	strcpy(sReusedwaste, "Yeniden kullanılan atık");
	strcpy(sRight, "Sağ");
	strcpy(sRightcoordinateofthedefect, "Sağdan defekt Koordinatları");
	strcpy(sRotation, "Dönme");
	strcpy(sRotationAngle, "Dönme açısı");
	strcpy(sRotationStep, "Rotasyon adım");
	strcpy(sRoundAllFractionsTo, "Kesirli değerler yuvarlanır gerekir");
	strcpy(sRow, "satır");
	strcpy(sRows, "Satırlar");
	strcpy(sRun, "Yeni çözümler");
	strcpy(sRunningtime, "çalışma süresi");
	strcpy(sSameforall, "Herkes için aynı");
	strcpy(sSave, "Kurtarmak");
	strcpy(sSaveAllImages, "Tüm görüntüleri Kaydet");
	strcpy(sSaveAs, "Olarak kaydet");
	strcpy(sSaveChanges, "Talep değiştirildi. Kaydetmek istiyor musunuz?");
	strcpy(sSaveCurrentImage, "Cari Kaydet");
	strcpy(sSavedataparameters, "Veri ve parametreleri kaydet");
	strcpy(sSaveEverything, "Herşeyden tasarruf");
	strcpy(sSaveInventory, "Envanter kaydet");
	strcpy(sSaveInventoryandDemand, "Envanter ve Talep kaydet");
	strcpy(sSaveResults, "Sonuçlar kaydet");
	strcpy(sSaveStatisticsinafile, "Bir dosyaya istatistikleri kaydedin");
	strcpy(sSavethecurrentimage, "Geçerli görüntü kaydetme");
	strcpy(sSavethecurrentimageorstatistic, "Geçerli görüntü veya istatistik kaydet");
	strcpy(sSavetheDEMANDinafile, "Dosyaya kaydet");
	strcpy(sSavetheDemandinafilewithadifferentname, "Farklı bir adla bir dosya Talep kaydedin.");
	strcpy(sSavetheREPOSITORYinafile, "Bir dosya içinde DEPOSU katılım");
	strcpy(sSerialNumber, "Kayıt anahtarı");
	strcpy(sService, "hizmet");
	strcpy(sSetDefaultValues, "Bu varsayılan değerlerine tüm parametreleri geri olacaktır. Tüm ayarlarınız kaybolacaktır. Bunu yapmak istediğinizden emin misiniz?");
	strcpy(sSetedgeband, "Kenar bandı ayarlayın");
	strcpy(sSetedgetrim, "Kenarlarının kusurları için kesme ayarlama");
	strcpy(sSetthesameedgebandforalledges, "Tüm kenarlar için aynı kenar bandı ayarlayın");
	strcpy(sSetthesamegrindingforalledges, "Tüm kenarlar için taşlama aynı ayarlayın");
	strcpy(sSetthesametrimforalledges, "Tüm kenarlar için kusurları için aynı kesme ayarlayın");
	strcpy(sSettings, "Ayarlar");
	strcpy(sShape, "Şeki");
	strcpy(sSheet, "Levha");
	strcpy(sSheetsBarstypes, "Levha_boru tipi");
	strcpy(sSheetSize, "Levha boyutları");
	strcpy(sSheetsperPage, "Sayfa başına Levhalar");
	strcpy(sShort, "Kısa");
	strcpy(sShorterexecutiontime, "Kısa çalışma süresi");
	strcpy(sShowallsimpleproducts, "Tüm basit ürünleri göster");
	strcpy(sShowcustomername, "Müşteri adı Göster");
	strcpy(sShowCustomTextOnEachPiece, "Her parça üzerinde özel metin göster");
	strcpy(sShowdiagramasatable, "Bir tablo olarak diyagramı göster.");
	strcpy(sShowedgeband, "Kenar bantları göster");
	strcpy(sShowedgebandssettinginanewwindow, "Yeni bir pencerede kenar bantları ayarlarını göster");
	strcpy(sShowgrindingsettingsinanewwindow, "yeni bir pencerede taşlama ayarlarını gösterir");
	strcpy(sShowHorizontalLabelsAlways, "Daima yatay etiketleri göster");
	strcpy(sShowRemovethesizeofthepiecesinthecurrentsolution, "Mevcut çözelti içinde büyüklüğünde parçalar ABS / çıkarın.");
	strcpy(sShowRemovethesizeofthewastesinthecurrentsolution, "Mevcut çözelti içinde atıkların boyut ABS / çıkarın.");
	strcpy(sShowtotalcutlength, "Toplam kesme uzunluğu göster");
	strcpy(sShowtrimedgesettingsinanewwindow, "Yeni bir pencerede kusurların ayarlarını göster");
	strcpy(sSimpleMaterialExists, "Malzemenin adı önceden malzeme listesi içinde tanımlanmıştır. Yeni bir ad verin.");
	strcpy(sSinglePieceStrips, "Tek parça Stripes");
	strcpy(sSizes, "Boyutları");
	strcpy(sSmallerorequalto, "Küçük veya eşittir");
	strcpy(sSort, "Çeşit");
	strcpy(sSortAscendingByArea, "Sıralama bölgelere göre artan");
	strcpy(sSortDescendingByArea, "Sıralama bölgelere göre azalan");
	strcpy(sSpecifyhowdifferentthepiecesinthelaststagecanbeValue0meansnodifference, "Nasıl farklı son aşamasında parçaları olabilir belirtin. 0 değeri, hiçbir fark anlamına gelir.,");
	strcpy(sSpecifyifpiecesinthelaststagecanbedifferentornotdepeultimaetapapotfidiferitesaunucadimensiune, "Son aşamada adet farklı olabilir ya da olmayabilir belirtin");
	strcpy(sSpecifyifthepiececanberotatedornotIfnotitwillbecutinthesamewayasitwasintroducedinDemandLengthofthepieceparalleltothelengthofthesheet, "Parça döndürülmüş olabilir veya olamaz belirtin. Eğer değilse o (levha uzunluğu ile paralel parça uzunluğu) Talep başlandı gibi, aynı şekilde kesilir,");
	strcpy(sSpecifyinhowmanystageswemakethecutsDuringastageallcutshavethesamedirection, "Biz kesimler yapmak kaç aşamada belirtin.");
	strcpy(sStartthesearchprocess, "Arama işlemini başlatın");
	strcpy(sStatistics, "Istatistik");
	strcpy(sStatisticsE, "Ekstra Raporları");
	strcpy(sStatisticsforeachtypeofmaterial, "Her malzeme tipi için İstatistik");
	strcpy(sStep, "Adım");
	strcpy(sStergeDepozit, "Sen Envanter silmek istediğinizden?");
	strcpy(sStergeMaterial, "Materyal silinsin mi?");
	strcpy(sStergePiesele, "Sen parça silmek istediğinizden?");
	strcpy(sStergePiesa, "Sen parça silmek istediğinizden?");
	strcpy(sStopthesearchprocess, "Arama işlemi durdurun");
	strcpy(sStrongoptimization, "Güçlü optimizasyonu");
	strcpy(sSubtractthebandthicknessfrompiecesize, "Bantları kalınlığında parça boyutunu azaltın");
	strcpy(sSummary, "özet");
	strcpy(sSuprafataTotalaFolosita, "Toplam kullanılan yüzey");
	strcpy(sSuprafatautilizata, "Kullanım");
	strcpy(sSwitchbetweenfiberandrotationoption, "Lif ve dönme seçeneği arasında geçiş yapma.");
	strcpy(sTechnical, "Teknik");
	strcpy(sTechnicalsettings, "Teknik ayarları");
	strcpy(sTemporaryPanelHint, "Sayfaları arasında hareketli parçalar için Geçici paneli.");
	strcpy(sText, "Metin");
	strcpy(sThe_application_has_expired, "Program süresi doldu.");
	strcpy(sThe_application_is_not_registered, "Yazılım kayıtlı değil.");
	strcpy(sThe_application_was_first_started_on, "Yazılım ilk başlandı.");
	strcpy(sThecutsareperformedfromasidetotheothersideofthematerial, "Borçlandırma bir taraftan malzemenin diğer tarafına uygulanmaktadır.");
	strcpy(sThecuttingmachinecanfollowtheshapeofthematerial, "Kesme makinası parçasının şeklini takip edebilir.");
	strcpy(sTheedgesofsheetsthatmustbetrimedduefaults, "Çünkü fayların kesilmiş olmalıdır yaprak kenarları");
	strcpy(sTheLargestSize, "Büyük boyutu.");
	strcpy(sThenameofthecustomerforwhichyoucutthepiece, "Müşterinin adı kendisi için bir parça kesti.");
	strcpy(sThenameofyourcustomer, "Müşterinizin adı");
	strcpy(sThepiececanberotated, "Parça döndürülebilir");
	strcpy(sTheprogramtriestoavoidwasteswhichhavebothsizeslessthanthisvalue, "Program bu değerden hem boyutları az olması atıkların kaçınmaya çalışır");
	strcpy(sThereAreNoProducts, "Tanımlanmış bir ürün henüz bulunmamaktadır");
	strcpy(sThestockofmaterialhasbeenpreviouslyloadedfromanExcelorCSVformatPleaseloaditagain, "Malzeme stok daha önce bir Excel veya CSV formatında yüklenmiş. Bunu çalışmak istiyorsanız tekrar yükleyin lütfen.");
	strcpy(sThetotallengthofcutting, "Kesme toplam uzunluk");
	strcpy(sThewidthofthecuttingsawForglasscuttingoptimizationitcanbe0Forwooditshouldbegreaterthan0, "Testere kalınlığı. Cam kesme için 0 olabilir. Ahşap için 0'dan büyük olmalıdır.");
	strcpy(sThewidthofthecuttingsawforlinearpieces, "Lineer adet testere kalınlığı.");
	strcpy(sThickness, "Kalınlık");
	strcpy(sThischaracterisusedforfillingthewasterectanglesIfyoudonotwantfilledwastejustremovethischaracter, "Bu sembol atık dikdörtgenler doldurulması için kullanılır. Eğer dolu atık istemiyorsanız sadece çıkarın.");
	strcpy(sThisindexhasvaluebetween1andthenumberofpieces, "Bu indeks 1 arasında değer ve parça numarası vardır.");
	strcpy(sThisOptionWillOverrideTheInventoryFileIfLoadedFromExcelOrCsvFiles, "Hisse senedi excel veya csv dosyaları yüklenir, bu seçenek hisse senedi içeren dosyayı geçersiz kılar.");
	strcpy(sThisProgramisLicensedTo, "Bu program için lisanslı");
	strcpy(sThisvaluewillbeaddedtotheedgebandingmaterialoneachside, "Bu değer, her yan üzerinde kenar bandı malzemesi eklenir");
	strcpy(sTipNevid, "Malzemenin türü boş olamaz.");
	strcpy(sTitle, "Başlık");
	strcpy(sTools, "Araçlar");
	strcpy(sTop, "Üst");
	strcpy(sTopcoordinateofthedefect, "Defektin üst koordinatı.");
	strcpy(sTotalGarbageWaste, "Tüm atıklar atılır");
	strcpy(sTotalInventoryWaste, "Toplam stok atık");
	strcpy(sTotalRecycledWaste, "Tüm geri dönüşümlü atık");
	strcpy(sTotalusedarea, "Toplam kullanılan alan");
	strcpy(sTotalusedlength, "Toplam kullanılan uzunluk");
	strcpy(sTrigonometric, "Trigonometrik");
	strcpy(sTrim, "Süs");
	strcpy(sTrimalledgesatthebeginning, "Başlangıçta bütün kenarları Trim");
	strcpy(sTrimEdge, "Kenar Trim");
	strcpy(sTwoPanels, "2 paneller");
	strcpy(sType, "tip");
	strcpy(sTypeofmaterialfromwhichtocut, "Malzeme tipi kesmek için hangi");
	strcpy(sTypesAreNotMatched, "Optimizasyon gerçekleştirilemedi! Parça ve Stok tablolarındaki malzemeler eşleşmiyor! Bir Parça yalnızca stokta aynı adı taşıyan malzemeden kesilebilir. Malzemelerin adını ilgili sütunlardan değiştirin!");
	strcpy(sUndo, "Undo");
	strcpy(sUndoAccept, "Kabul Undo");
	strcpy(sUnits, "üniteleri");
	strcpy(sUnregisteredVersion, "Kayıtsız");
	strcpy(sUpdates, "Güncelleme");
	strcpy(sUsefulforwoodfurniture, "Ahşap mobilya için Faydalı");
	strcpy(sUseit, "Kullanın");
	strcpy(sUsePieceinOptimization, "Optimizasyon parça kullanın");
	strcpy(sUserName, "Kullanıcı adı");
	strcpy(sUtilizationandWastes, "Kullanımı ve Atıklar");
	strcpy(sUtilizedArea, "Kullanılan parçaların Alanı");
	strcpy(sUtilizedBars, "Kullanılan çubuklar");
	strcpy(sUtilizeddemandcount, "Kullanılan parça sayısı.");
	strcpy(sUtilizedParts, "Kullanılan parçalar");
	strcpy(sUtilizedPieces, "Kullanılan adettir");
	strcpy(sUtilizedSheets, "Kullanılan yaprak");
	strcpy(sValue, "Değer");
	strcpy(sValueGreaterEqualToZero, "Değer sıfırdan büyük veya eşit olmalıdır");
	strcpy(sValueGreaterThanZero, "Değer sıfırdan büyük olmalıdır");
	strcpy(sValueIntegerNumber, "Değer bir tam sayı olmalıdır!");
	strcpy(sValueRealNumber, "Değer gerçek sayı olmalıdır. Belki yerine kullandık. ya da tersine. Bunu düzeltmek Lütfen!");
	strcpy(s_The_number_is_too_big_or_it_has_too_many_digits_after_decimal_separator, "Sayı çok büyük veya ondalık ayırıcıdan sonra çok fazla basamak var!");
	strcpy(s_The_number_is_too_big, "Sayı çok büyük!");
	strcpy(sVertical, "Dikey");
	strcpy(sWaste, "Atık");
	strcpy(sWastes, "Atık");
	strcpy(sWasteAddedToWarehouse, "Hurda depo eklenir");
	strcpy(sWastelimits, "atık limitleri");
	strcpy(sWasteType, "Atık Türü");
	strcpy(sWeakoptimization, "Zayıf optimizasyonu");
	strcpy(sWhattoprint, "Ne yazdırmak gerekir");
	strcpy(s_What_to_print_or_save_to_file, "Ne yazdırılmalı veya dosyaya kaydedilmeli");
	strcpy(sWhattoprintoneachpiece, "Her parçasına yazdırmanız neler");
	strcpy(sWhattoshowoneachpiece, "Ne her parça göstermek için?");
	strcpy(sWidth, "Genişlik");
	strcpy(sWood, "ahşap");
	strcpy(sWorkingDirectory, "Dizin Çalışma");
	strcpy(sWrongKey, "Yanlış Kayıt Anahtarı!");
	strcpy(sYes, "Evet");
	strcpy(sYoucannotchooseblackblueorredcolors, "You cannot choose black, blue or red colors.");
	strcpy(sYouCannotMixFractionalDataWithDecimalOnes, "Gerçek değerleri ile kesirli değerler getiremezsiniz!");
	strcpy(sYourcompany, "Firmanız");
	strcpy(sZip, "Posta kodu");
	strcpy(s_Set_the_origin_and_the_direction_of_the_axes, "Koordinat eksenlerinin orijinini ve yönünü ayarlayın.");










	strcpy(s_Number_of_digits_after_the_decimal_separator, "Ondalık ayırıcısından sonraki basamak sayısı");
	strcpy(s_Percentages, "Yüzdeler");
}

