// Language strings: Russian
// Author: Optimal Programs
// License: MIT License
//---------------------------------------------------------------------------
#include <string.h>
//---------------------------------------------------------------------------
#include "language_string_id.h"
//---------------------------------------------------------------------------
void set_ru(void)
{
	//Russian
	//translated by a customer
	//2025.3.29.0
	strcpy(s_Advanced, "Передовой");
	strcpy(s_Relative_coordinates, "Относительные координаты");
	strcpy(s_Absolute_coordinates, "Абсолютные координаты");
	strcpy(s_Append_more_rows, "Добавить больше строк");

	strcpy(s_Add_to_parts, "Добавить в запчасти.");
	strcpy(s_Additional, "Дополнительный");
	strcpy(s_All_results, "Все результаты.");
	strcpy(s_Allow_movement_of_pieces, "Разрешить движение фигур");
	strcpy(s_Allow_part_in_part, "Разрешить кусок в кусок");
	strcpy(s_Invalid_piece_Angles_are_too_small_or_too_big_or_height_is_too_small, "Недопустимая деталь! Углы слишком малы или слишком велики, или высота слишком мала.");
	strcpy(s_Append, "Добавлять");
	strcpy(s_As_it_is, "Как оно есть");
	strcpy(s_As_text, "Как текст");
	strcpy(s_Ascending, "по возрастанию");
	strcpy(s_Automatic, "автоматическая");
	strcpy(s_Cannot_connect_to_the_Internet_Please_visit_our_website_from_a_browser, "Не удается подключиться к интернету! Пожалуйста, посетите наш сайт из браузера.");
	strcpy(s_Cannot_copy_or_move_the_files, "Невозможно скопировать или переместить файлы!");
	strcpy(s_Cannot_delete_the_file, "Невозможно удалить файл!");
	strcpy(s_Cannot_modify_old_results, "Невозможно изменить старые результаты!");
	strcpy(s_To_change_click_inside_a_cell_or_press_0_1_or_2, "Чтобы изменить, щелкните внутри ячейки или нажмите 0, 1 или 2.");
	strcpy(s_Cell, "Клетка");
	strcpy(s_Click_on_the_table_header_to_change_the_columns, "Нажмите на заголовок таблицы, чтобы изменить столбцы.");
	strcpy(s_Close, "Закрой его");
	strcpy(s_Contact_us, "Связаться с нами");
	strcpy(s_Column, "Столбец");
	strcpy(s_Comma, "Запятая");

	strcpy(s_Copy, "Копировать");
	strcpy(s_Copy_for_move, "Копировать для переезда");
	strcpy(s_Cut_higher_level_strips_first, "Сначала отрежьте полосы более высокого уровня.");
	strcpy(s_Cut_index, "Индекс п/п реза");

	strcpy(s_The_data_have_been_changed_Do_you_want_to_save_them_to_a_file, "Данные были изменены. Вы хотите сохранить их в файл?");
	strcpy(s_Decimal_separator, "Десятичный разделитель");
	strcpy(s_Restore_default_settings, "Восстановить настройки по умолчанию");
	strcpy(s_Delete_fiber, "Удалить волокно");
	strcpy(s_Descending, "По убыванию");
	strcpy(s_Discard_changes, "Отменить изменения");

	strcpy(s_Delete_all_data, "Удалить все данные?");
	strcpy(s_Dot, "точка");
	strcpy(s_Do_you_want_to_delete_the_picture, "Вы хотите удалить картинку?");
	strcpy(s_Do_you_want_to_delete_the_product, "Вы хотите удалить товар?");
	strcpy(s_Duplicate_and_append, "Дублировать и добавлять.");
	strcpy(s_Duplicate_values_are_ignored, "Повторяющиеся значения игнорировались!");
	strcpy(s_Error, "ошибка");
	strcpy(s_Error_loading_file, "Ошибка загрузки файла.");
	strcpy(s_export_everything, "Экспортировать все");
	strcpy(s_Fit_to_screen, "По размеру экрана.");
	strcpy(s_Force_fixed_height, "Нарисуйте фигуры фиксированной высоты.");
	strcpy(s_Flipped, "Перевернутый");
	strcpy(s_Import, "импорт");
	strcpy(s_If_angles_are_different_from_90_degrees_height_must_be_greater_than_0, "Если углы отличны от 90 градусов, высота должна быть больше 0.");
	strcpy(s_Ignore, "Игнорировать");
	strcpy(s_Incorrect_value, "Неверное значение");
	strcpy(s_Info, "Информация");
	strcpy(s_Interior, "внутри");
	strcpy(s_Give_a_name, "Дайте имя.");
	strcpy(s_Group, "Сгруппировать");
	strcpy(s_Header, "Заголовок");
	strcpy(s_Keep_it_as_it_is, "Оставь как есть");
	strcpy(s_Level, "Level");
	strcpy(s_Licensee, "Лицензиат");
	strcpy(s_List_separator, "Разделитель списка");
	strcpy(s_Made_with_love_in_Cugir_Romania, "Сделано с любовью в: Кужир, Румыния");
	strcpy(s_Made_in, "Изготовлено в");
	strcpy(s_Manufacturer, "Производитель");

	strcpy(s_Manual_arrange, "Ручная аранжировка");

	strcpy(s_Mixed, "смешанный");
	strcpy(s_Multiple_shapes_detected_Next_rows_will_be_overwritten_Continue, "Было обнаружено более одной формы. Поэтому последующие строки будут перезаписаны. Продолжать?");
	strcpy(s_More, "Более");
	strcpy(s_Multiple_values, "Несколько значений");
	strcpy(s_No_texture, "Нет текстуры");
	strcpy(s_Number, "Число");
	strcpy(s_Number_of_images, "Количество изображений");
	strcpy(s_Number_of_vertices, "Количество вершин");
	strcpy(s_Offset, "Компенсировать");
	strcpy(s_Only_the_currently_selected_items, "Только выбранные в данный момент элементы.");
	strcpy(s_Optimizing_please_wait, "Оптимизация... подождите.");

	strcpy(s_Paste, "Paste");

	strcpy(s_Piece_label, "Метки деталей");
	strcpy(s_Piece_size, "Размеры деталей");
	strcpy(s_Please_contact_us_by_email_if_you_receive_this_error, "Пожалуйста, свяжитесь с нами по электронной почте, если вы получите эту ошибку.");
	strcpy(s_Please_save_it_first, "Пожалуйста, сначала сохраните его.");
	strcpy(s_Position, "Позиция");
	strcpy(s_Preview, "Предварительный просмотр");
	strcpy(s_Rectangle, "Прямоугольник");

	strcpy(s_Redo_the_last_operation, "Восстановить последнюю операцию");
	strcpy(s_Regular_polygon, "Правильный многоугольник");

	strcpy(s_Reused, "Повторно использованный");
	strcpy(s_Rotated, "повернутого");
	strcpy(s_Save_all, "Сохранить все");
	strcpy(s_Scrap_label, "Метки остатков");
	strcpy(s_Scrap_size, "Размеры остатков");
	strcpy(s_Semicolon, "Точка с запятой");
	strcpy(s_Show_cut_index, "Индекс п/п реза");
	strcpy(s_Show_information, "Показать информацию");
	strcpy(s_Show_piece_label, "Метки деталей");
	strcpy(s_Show_scrap_label, "Метки остатков");
	strcpy(s_Show_scrap_s_size_on_the_small_pieces, "Покажите размер лома на маленьких кусочках");
	strcpy(s_Show_size_of_pieces, "Размеры деталей");
	strcpy(s_Show_size_of_scrap, "Размеры остатков");
	strcpy(s_Show_sizes, "Показать размеры");
	strcpy(s_Show_label, "Показать ярлык");
	strcpy(s_Show_length, "Показать длину");

	strcpy(s_Some_numerical_values_are_incorrect_Should_I_fix_all_the_incorrect_values, "Некоторые числовые значения неверны! Стоит ли исправить все неверные значения?");
	strcpy(s_Some_invalid_values_have_been_removed, "Некоторые недопустимые значения были удалены.");
	strcpy(s_Sort_by, "Сортировать по");
	strcpy(s_Sort_ascending_by, "Сортировать по возрастанию");
	strcpy(s_Sort_descending_by, "Сортировать по убыванию");
	strcpy(s_Start, "Start");
	strcpy(s_Starting_angle, "Начальный угол");


	strcpy(s_Stock, "СКЛАД");
	strcpy(s_Stop, "Stop");

	strcpy(s_Tabular, "Табличный");
	strcpy(s_Total, "Всего");
	strcpy(s_Total_size, "Общий размер");
	strcpy(s_Terms_of_the_license, "Условия лицензии");
	strcpy(s_The_current_product_has_been_changed_Do_you_want_to_save_it_to_file, "Текущий продукт был изменен. Вы хотите сохранить его в файл?");
	strcpy(s_The_value_is_out_of_the_allowed_range, "Значение находится вне допустимого диапазона.");
	strcpy(s_The_value_must_be_a_real_or_fractional_number_Try_to_replace_the_comma_with_the_dot_if_you_want_to_enter_a_real_number, "Значение должно быть действительным или дробным числом. Попробуйте заменить запятую на точку, если вы хотите ввести действительное число.");
	strcpy(s_This_feature_is_not_implemented_yet, "Эта функция еще не реализована.");
	strcpy(s_This_operation_cannot_be_reversed, "Эту операцию нельзя отменить.");
	strcpy(s_Undo_the_last_operation, "Отмените последнюю операцию.");
	strcpy(s_Utilization, "Использование");
	strcpy(s_Utilized_Stock, "Используемый запас");
	strcpy(s_Version, "Версия");
	strcpy(s_Visible_columns, "Видимые столбцы");
	strcpy(s_You_already_have_the_latest_version_installed, "У вас уже установлена последняя версия!");
	strcpy(s_What_is_exported, "Что экспортируется?");
	strcpy(s0meansanynumberofpieces, "Ноль означает любое количество деталей");
	strcpy(sAbout, "О программе..");
	strcpy(sAccept, "Утвердить");
	strcpy(sAcceptall, "Утвердить все");
	strcpy(sAcceptthecurrentsolution, "Утвердить текущее решение");
	strcpy(sAdd, "Добавить");
	strcpy(sAddapiece, "Добавить деталь в Заказ");
	strcpy(sAddasimpleproducttoDemand, "Добавить в Заказ простое изделие");
	strcpy(sAddgrindingthicknesstopartsize, "Добавить толщину шлифовки к размеру детали");
	strcpy(sAddproductnametolabel, "Внести имя изделия в метку");
	strcpy(sAddress, "Адрес");
	strcpy(sAddselectedsizetoInventory, "Добавить выбранный размер в Склад");
	strcpy(sAdhesivelabels, "Самоклеющиеся этикетки");
	strcpy(sAdhesivelabelwithinformationaboutpiecesinDemandCustomernameLabelSizeCurrentData, "Клейкие этикетки с информацией о деталях в Заказе: Имя заказчика, Метка, Размер, Текущие данные");
	strcpy(sAdhesivelabelwithinformationaboutsheetsinInventory, "Клейкие этикетки с информацией о листах в Складе");
	strcpy(sAll, "Все");
	strcpy(sAlloffcutswhichhavethesizegreaterthanthisvaluewillbeaddedtoInventory, "Все остатки у которых хотя бы одна сторона больше чем это значение, будут отправлены на Склад");
	strcpy(sAllowMirroring, "Разрешить зеркалирования.");
	strcpy(sAllowRotation, "Разрешить вращение");
	strcpy(sAllPieces, "Все фигуры");
	strcpy(sAllpredefinedproducts, "Все предопределенные изделия");
	strcpy(sAnewwindowwillbedisplayedwheretheusercansettheedgebandsforeachedge, "Появится новое окно, где пользователь может установить кромку для каждого края листа");
	strcpy(sAnewwindowwillbedisplayedwheretheusercansetthegrindingvalueforeachedgeofthsheet, "Появится новое окно, где пользователь может установить значения шлифовки для каждого края детали");
	strcpy(sAnewwindowwillbedisplayedwheretheusercansetthetrimvalueforeachedgeofthsheet, "Появится новое окно, где пользователь может установить значение обрезки для каждого края листа");
	strcpy(sAngle, "Угол");
	strcpy(sAngles, "Углы");
	strcpy(sAnoptimizationparameterisarealnumber, "Параметр оптимизации является действительным числом");
	strcpy(sAnoptimizationparameterisfractionalnumber, "Параметр оптимизации является дробным числом");
	strcpy(sAnyShape, "Любая форма");
	strcpy(sApolygonmusthaveatleast2vertices, "Полигон должен иметь как минимум 2 вершины!");
	strcpy(sApolygonmusthaveatleast3vertices, "Полигон должен иметь как минимум 3 вершины!");
	strcpy(sApplication_fails_to_initialize, "Программное обеспечение Сбой при инициализации.");
	strcpy(sArc, "Д'Арк");
	strcpy(sArcLength, "Длина дуги");
	strcpy(sAreaofusedsheets, "Площадь использованных листов");
	strcpy(sAshortdescriptionofthesheet, "Короткое описание листа");
	strcpy(sAtleastonepart, "Необходимо представить минимум одну деталь");
	strcpy(sAtTheMarginOfTheSheet, "В край листа");
	strcpy(sBandtypes, "Типы кромки");
	strcpy(sBar, "Бары / трубы");
	strcpy(sBars, "Бары / трубы");
	strcpy(sBothsizesoftheoffcutsmustbegreaterthanthisvalue, "Обе стороны остатка должны быть больше чем это значение");
	strcpy(sBottom, "Внизу");
	strcpy(sBottomcoordinateofthedefect, "Нижняя координата дефекта");
	strcpy(sBreakCut, "Прервать рез");
	strcpy(sBrowse, "Обзор..");
	strcpy(sBuy, "Купить");
	strcpy(sBuynow, "Купить сейчас...");
	strcpy(sCancel, "Отменить");
	strcpy(sCannotBeEmpty, "не может быть пустым!");
	strcpy(sCannotmovepartsbetweensheetswhenidenticalsheetsaregroupedPleaseungroupthesheetsfrommenu, "Нельзя перемещать детали с одного листа на другой, если идентичные листы сгруппированы. Пожалуйста, отмените группировка листов");
	strcpy(sCannotSaveFile, "Не удается сохранить файл");
	strcpy(sCenter, "Центр");

	strcpy(sChangeDirection, "Измените направление");
	strcpy(sChoose, "Выберите");
	strcpy(sChooseProduct, "Выберите Изделие");
	strcpy(sCircle, "Кругом");
	strcpy(sCity, "Город");
	strcpy(sClear, "Очистить");
	strcpy(sClockWise, "По часовой стрелке");
	strcpy(sClosewindow, "Закрыть окно");
	strcpy(sColor, "Цвет");
	strcpy(sColorofedgeband, "Цвет кромки");
	strcpy(sColorPattern, "Цвет/Текстура");
	strcpy(sColorpiecesandwastes, "Цвет деталей и остатков");
	strcpy(sColumns, "Колонки");
	strcpy(sComment, "Комментарий");
	strcpy(sCompanyname, "Имя Вашей компании");
	strcpy(sComplexMaterialExists, "Имя материала уже есть в списке сложных материалов. Дайте другое имя");
	strcpy(sComputerCode, "Код компьютера");
	strcpy(sComputerCodefromyourcomputer, "Код");
	strcpy(sComputethetotalpriceofDemand, "Подсчет общей стоимости Заказа");
	strcpy(sContents, "Содержание");
	strcpy(sContinutComanda, "Содержание Заказа по состоянию на ");
	strcpy(sContinutDepozit, "Содержание Склада по состоянию на ");
	strcpy(sConversionIsDoneOnlyWhenSomePiecesHaveFractionalValues, "Преобразование выполняется только тогда, когда некоторые части имеют дробные значения.");
	strcpy(sConvertsTheSizeOfWasteToAFractionalUnit, "Показывает размер отходов в качестве дробного значения.");
	strcpy(sCouldNotSaveFile1, "Невозможно записать файл в папке: ");
	strcpy(sCouldNotSaveFile2, "У вас может быть не достаточно прав. Пожалуйста, проверьте это или измените рабочий каталог в меню Настройки | Рабочая папка на папку, где у вас есть права на запись (например - C:\\Temp).");
	strcpy(sCreationdateYMDHMS, "Дата создания (Г/М/Д ч:м:с)");
	strcpy(sCurrentDate, "Текущая дата");
	strcpy(sCurrentDiagram, "Текущая диаграмма");
	strcpy(sCurrentMaterial, "Текущий тип");
	strcpy(sCurrentversion, "Current version");
	strcpy(sCurve_not_closed_Try_increasing_DXF_linking_distance_parameter, "Полигон не закрыт! Попробуйте увеличить параметр DXF linking distance.");
	strcpy(sCustomer, "Заказчик");
	strcpy(sCustomerName, "Заказчик");
	strcpy(sCustomMessage, "Пользовательские сообщения");
	strcpy(sCutlength, "Длина пропила");
	strcpy(sCut, "Резать");
	strcpy(sCuts, "Список резов");
	strcpy(sCutterThickness, "Ширина пропила");
	strcpy(sData, "Данные");
	strcpy(sDataCannotBeEmpty, "Данные не могут быть пустыми!");
	strcpy(sDateymdhms, "Дата (Г/М/Д/ ч/м/с)");
	strcpy(sDays_left_for_trial, "Дни, доступные для тестирования ");
	strcpy(sDaysLeft, "дней осталось");
	strcpy(sStandard, "По умолч.");
	strcpy(sDefaultInterface, "Сброс Настроек");
	strcpy(sDefects, "Дефекты");
	strcpy(sDefectsManager, "Менеджер дефектов");
	strcpy(sDefectsofthematerialNopiecescanbeplacedinthefaultyzone, "Дефекты на материале. Детали не будут расположены в испорченной зоне");
	strcpy(sDelete, "Удалить");
	strcpy(sDeletePiece, "Удалить деталь");
	strcpy(sDeleteRow, "Удалить строку");
	strcpy(sDemandutilization, "Выполнено Заказа %");
	strcpy(sDepozitulmodificat, "Использованные детали и листы были убраны с Заказа и Склада. Деловые остатки были добавлены на Склад");
	strcpy(sDepozitvid, "Склад пуст");
	strcpy(sDesk, "стол");
	strcpy(sDiagram, "Схема");
	strcpy(sDiagrams, "Диаграммы");
	strcpy(sDiagramasatable, "Схема таблицей");
	strcpy(sDigits, "цифры");
	strcpy(sDimensiuniplaca, "Размер листа");
	strcpy(sDirection, "Направление");
	strcpy(sDistanceBetweenRows, "Интервал между строками");
	strcpy(sDonotuseit, "Не использовать");
	strcpy(sDownload, "Скачать");
	strcpy(sDoYouWantToClearTheData, "Вы хотите удалить данные?");
	strcpy(sDoYouWantToSaveDemand, "Заказ был изменен! Хотите сохранить изменения?");
	strcpy(sDoYouWantToSaveParts, "Хотите сохранить детали?");
	strcpy(sDoYouWantToSaveRepository, "Склад был изменен! Хотите сохранить изменения?");
	strcpy(sDrawing, "рисунки");
	strcpy(sDrawthesolutioncolorful, "Отрисовка схемы в цвете");
	strcpy(sDuplicateTypes, "Некоторые типы продублированы. Пожалуйста уберите дубликаты");
	strcpy(sDuplicateTypesWithComplex, "Некоторые имена материалов уже существуют в списке сложных типов! Пожалуйста уберите дубликаты");
	strcpy(sDuplicateValues, "Дублированные значения");
	strcpy(sEdgeband, "Кромка");
	strcpy(sEdgebandingwhichisplacedontheedgesofyourpiecePleasedefineedgebandingtypesfromMaterialsEdgeBandingmenu, "Кромка, которая крепится к краям вашей детали. Определяйте типы кромки в меню Материалы | Кромка");
	strcpy(sEdgebandsthatwillbeappliedtoeachpart, "Кромка, что будет применена к каждой детали");
	strcpy(sEdgeBandTolerance, "Добавить длину кромки");
	strcpy(sEdgesthatmustbecutduefaults, "Края которые должны быть обрезаны из-за дефектов");
	strcpy(sEdgetoedge, "Сквозной");
	strcpy(sEdit, "Правка");
	strcpy(sEmail, "E-mail");
	strcpy(sEmptyData, "Данных нет!");
	strcpy(sEnabled, "разрешать");
	strcpy(sEnabledisabledefectsoftheinventorysheets, "Вкл/Выкл дефекты на листах склада");
	strcpy(sEnterLabel, "Введите метку");
	strcpy(sEnterTheMaterialName, "Введите имя материала");
	strcpy(sEnterTheProductName, "Введите имя изделия");
	strcpy(sEvaluationError, "Ошибка в подсчете выражения!");
	strcpy(sExit, "Выход");
	strcpy(sExpired, "Пробный период закончился! Пожалуйста зарегистрируйтесь");
	strcpy(sExport, "Экспорт");
	strcpy(sExportAllDiagrams, "Экспортировать все диаграммы");
	strcpy(sExportAllToASingleFile, "Экспортировать все в один файл");
	strcpy(sExportOptions, "Параметры экспорта.");
	strcpy(sExporttoDXFformat, "Экспорт в формат DXF");
	strcpy(sExporttoExcel, "Экспорт в Excel");
	strcpy(sExpresieIncorecta, "Некорректное выражение!");
	strcpy(sExtensions, "расширения");
	strcpy(sExtra, "Экстра");
	strcpy(sExtraComponents, "Дополнительные компоненты");
	strcpy(sExtracomponentsattachedtoDemand, "Дополнительные компоненты Заказа (фурнитура)");
	strcpy(sFile, "Файл");
	strcpy(sFileName, "Имя файла");
	strcpy(sFillWastes, "Рисовать остатки с косыми линиями");
	strcpy(sFindoptimalbarsheetsize, "Найти оптимальные размеры для полос/листов");
	strcpy(sFindoptimalsizeofInventorypieces, "Найти оптимальные размеры листов Склада");
	strcpy(sFirstcutMultiplestages, "Первый рез (в многошаговом)");
	strcpy(sFirstdirectionforcutishorizontal, "Первое направление реза будет Горизонтальным");
	strcpy(sFirstdirectionforcutisvertical, "Первое направление реза будет Вертикальным");
	strcpy(sFollowthecontourofpieces, "Не сквозной");
	strcpy(sFont, "Шрифт");
	strcpy(sFontsize, "Размер шрифта");
	strcpy(sFullInfo, "Вся информация");
	strcpy(sDisposedWaste, "Утилизированные отходы");
	strcpy(sGeneral, "Общий");
	strcpy(sGenerateCNC, "Создавать комманды ЧПУ (многошаговый режим)");
	strcpy(sGrain, "Волокно");
	strcpy(sGraindirection, "Волокно");
	strcpy(sGraphic, "Карта");
	strcpy(sGreaterorequalto, "Больше или равно");
	strcpy(sGrid, "Столы ");
	strcpy(sGrinding, "Шлифовка");
	strcpy(sGrosimeTaieturaScalata, "Ширина пропила на схеме может отличаться от реальной потому, что карта раскроя не представляет реальный масштаб элементов. В любом случае это не влияет на результат работы");
	strcpy(sGroupidenticallayouts, "Группировать идентичные раскрои");
	strcpy(sGroupIdenticalParts, "Группировать одинаковые детали");
	strcpy(sGroupingOfIdenticalPiecesIntoOneRow, "Группировка одинаковых частей в одну строку.");
	strcpy(sGroupPartsAfterLoadingFromFile, "Группировать детали после загрузки файла");
	strcpy(sHeight, "Высота");
	strcpy(sHeighttolerance, "Допуски высоты");
	strcpy(sHelp, "Помощь");
	strcpy(sHistory, "История");
	strcpy(sHorizontal, "Горизонтально");
	strcpy(sHowtodisplayprintedgebands, "Как отображать кромку?");
	strcpy(sIfyousetthebandforoneedgeallwillreceivethesamevalue, "При установке кромки для одного края, остальные получат ту же");
	strcpy(sIfyousetthegrindingforoneedgeallwillreceivethesamevalue, "Если вы установите значение шлифовки для одного края, все остальные получат то же значение");
	strcpy(sIfyousetthetrimforoneedgeallwillreceivethesamevalue, "Если вы установите значение обрезки для одного края, все остальные получат то же значение");
	strcpy(sImageBounds, "Границы для изображения");
	strcpy(sImageSize, "Размер изображения.");
	strcpy(sImportData, "Импорт данных");
	strcpy(sIncorrectPassword, "Неправильный пароль");
	strcpy(sIndex, "Индекс");
	strcpy(sInformationaboutcustomer, "Информация о заказчике");
	strcpy(sInputALanguageName, "Дайте имя языку");
	strcpy(sInsert, "Вставить");
	strcpy(sInsertPiece, "Вставить деталь");
	strcpy(sInterface, "Внешний вид");
	strcpy(sInterfaceSettings, "Настройки интерфейса и результатов");
	strcpy(sInvalidHardware, "Не возможно определить аппаратное обеспечение. Свяжитесь с нами: contact@cutting.com.ua");
	strcpy(sInvalidNumber, "Неправильное число");
	strcpy(sInvalidOrderOfComputation, "Не возможно осуществить подсчет. Существуют циклические зависимости в определении изделия!");
	strcpy(sInvalidRegistration, "Ошибка регистрации!");
	strcpy(sInvalidTime, "Время в вашей системе выставлено неправильно");
	strcpy(sInventory, "СКЛАД");
	strcpy(sisafractionalvalue, "является дробным значением");
	strcpy(sIsArc, "Является дуги");
	strcpy(sisarealvalue, "является реальным значением");
	strcpy(sLabel, "Метка");
	strcpy(sLabels, "Этикетки");
	strcpy(sLanguage, "Язык");
	strcpy(sLatimeanumar0, "Ширина должна быть больше 0!");
	strcpy(sLatimeanumarreal, "Ширина должна быть натуральным числом!");
	strcpy(sLayerName, "Имя слоя");
	strcpy(sLeft, "Слева");
	strcpy(sLeftcoordinateofthedefect, "Левая координата дефекта");
	strcpy(sLength, "длина");
	strcpy(sLengthofthepiecestocut, "Размеры деталей для раскроя");
	strcpy(sLengthofthepiecestocutfrom, "Размеры исходных листов и остатков");
	strcpy(sLengthofusedbars, "Размеры использованных полос");
	strcpy(sLicenseAgreement, "Лицензионное соглашение");
	strcpy(sLinear, "Линейный");
	strcpy(sLinethickness, "Отрисовка толщины линий");
	strcpy(sLoadafileandappenddatatothecurrentDemand, "Открыть файл и добавить данные к текущему Заказу");
	strcpy(sLoadanexistingDemandfromafile, "Открыть существующий Заказ из файла");
	strcpy(sLoadAppend, "Добавить к текущему Заказу");
	strcpy(sLoadEverything, "Загрузить Всё..");
	strcpy(sLoadInventory, "Открыть Склад");
	strcpy(sLoadInventoryandDemand, "Открыть Склад и Заказ");
	strcpy(sLoadResults, "Открыть Результаты");
	strcpy(sLocked, "запертый");
	strcpy(sLogo, "Логотип");
	strcpy(sLong, "Лонг");
	strcpy(sLongerexecutiontime, "БОЛЬШЕ ВРЕМЕНИ");
	strcpy(sLungime, "Ширина");
	strcpy(sLungimeanumar0, "Длина должна быть больше 0!");
	strcpy(sLungimeanumarreal, "Длина должна быть натуральным числом!");
	strcpy(sLungimeaTotalaFolosita, "Вся использованная длина: ");
	strcpy(sMagnification, "Увеличение");
	strcpy(sMagnify, "Увеличить");
	strcpy(sMargins, "Поля");
	strcpy(sMarginsForPaper, "Поля для бумаги");
	strcpy(sMarginsOfTheLabel, "Поля для этикетки");
	strcpy(sMaterial, "Материалы");
	strcpy(sMaterialName, "Имя материала");
	strcpy(sMaterials, "материалы");
	strcpy(sMaterialstypes, "Типы материала");
	strcpy(sMax, "Макс");
	strcpy(sMaximalArea, "Максимальная площадь");
	strcpy(sMaximalCutLength, "MAX длина пропила");
	strcpy(sMaxlength, "Макс длина");
	strcpy(sMaxPiecesperBar, " MAX деталей на полосу");
	strcpy(sMaxwidth, "Макс ширина");
	strcpy(sMeasurementUnit, "Единица измерения");
	strcpy(sMin, "Мин");
	strcpy(sMinimalBreakSize, "Min размер разрыва");
	strcpy(sMinimalUsefulSize, "Min полезный размер");
	strcpy(sMinimalwastesizetoInventory, "Min остаток на Склад");
	strcpy(s_What_to_minimize, "Что минимизировать?");
	strcpy(sMinlength, "Min длина");
	strcpy(sMinwidth, "Min ширина");
	strcpy(sMirror, "Зеркально");
	strcpy(sMirroring, "Oтражающий");
	strcpy(sMiscellaneous, "Общая статистика по раскрою");
	strcpy(sModify, "Изменить");
	strcpy(sModifytheselectedpiece, "Изменить текущую деталь");
	strcpy(sMovePiece, "Перемещение части.");
	strcpy(sMultiplestages, "Многошаговый");
	strcpy(sName, "Имя");
	strcpy(sNameofedgeband, "Имя кромки");
	strcpy(sNewDEMANDUnsaveddatawillbelost, "Новые детали? Несохраненные данные будут утеряны!");
	strcpy(sNewLanguage, "Новый язык");
	strcpy(sNewMaterial, "Новый материал");
	strcpy(sNewPasswordincorectlyintroduced, "Новый пароль введен неверно!");
	strcpy(sNewProduct, "Новое изделие");
	strcpy(sNewversion, "Новая версия");
	strcpy(sNo, "Нет");
	strcpy(sNumarBucati, "Число деталей ");
	strcpy(sNumberOfCopies, "Число копий");
	strcpy(sNumberofstages, "Число шагов");
	strcpy(sNusuficienteplacidepozit, "Не все детали были раскроены. Возможные причины: Не хватает листов на Складе;  Детали не используются в оптимизации;  Тип деталей Заказа и листов Склада НЕ СОВПАДАЮТ;  Некоторые другие параметры установлены неверно.");
	strcpy(sOfficeNotInstaled, "Microsoft Office не установлен или установлена неверная версия!");
	strcpy(sOldpassworddoesnotmatch, "Старый пароль не совпадает!");
	strcpy(sOnlinehelp, "Помощь онлайн");
	strcpy(sOnlypiecesofthesameheightinthelaststage, "Только детали одинаковой высоты на последнем шаге");
	strcpy(sOpen, "Открыть");
	strcpy(sOptimization, "Оптимизация");
	strcpy(sOptimizationDone, "Расчет закончен. Вы можете распечатать / сохранить полученные схемы. Нажмите <Принять> если вы удовлетворены этим решением. Иначе нажмите <<Пуск>> опять");
	strcpy(sOptimizationType, "Тип оптимизации");
	strcpy(sOptions, "Параметры");
	strcpy(sOptionsrelatedtotheinterface, "Параметры связанные с интерфейсом");
	strcpy(sor, "или");
	strcpy(sOthercomponents, "Другие компоненты");
	strcpy(sOthers, "Дополнительно");
	strcpy(sOtherstatistics, "Общая");
	strcpy(sOverrideExcelCSVfiles, "отменять Excel / CSV файлов");
	strcpy(sParameter, "Параметр");
	strcpy(sParts, "ЗАКАЗ");
	strcpy(sPattern, "Текстура");
	strcpy(sPatternforwaste, "Текстура для печати");
	strcpy(sPerimeter, "Периметр");
	strcpy(sPermitedRotationAngle, "Допустимый угол поворота.");
	strcpy(sPhone, "Телефон");
	strcpy(sPicture, "Образ");
	strcpy(sPiece, "Деталь");
	strcpy(sPieceindex, "№ п/п детали");
	strcpy(sPieces, "детали");
	strcpy(sPiecesize, "Размер детали");
	strcpy(sPiecesizelabeledgebandwillbeprinted, "Размер детали, метка и кромка будут напечатаны");
	strcpy(sPierdere, "Остаток");
	strcpy(sPixels, "пикселей");
	strcpy(sPlacilefolositeDepozit, "Использованные листы Склада");
	strcpy(sPlease_contact_us_at_contact_nestingtechnologies_com, "Пожалуйста, свяжитесь с нами по contact@nesting-technologies.com");
	strcpy(sPlease_contact_us_at_contact_optimalprograms_com, "Пожалуйста, свяжитесь с нами по contact@optimalprograms.com");
	strcpy(sPleaseenteralldataeitherasfractionalorrealDonotmixthem, "Пожалуйста, введите все данные либо в виде дробных или реальных Не смешивайте их!");
	strcpy(sPleaseEnterSomeTypesOfMaterials, "Не определен тип материала. Вы можете определить необходимые материалы в меню Материалы|Листы и Полосы");
	strcpy(sPleasesendtheNameandtheCodetotheaddresscontactoptimalprogramscominordertoobtaintheRegistrationKey, "Пожалуйста вышлите на contact@cutting.com.ua  Имя и Код чтобы получить Регистрационный Ключ");
	strcpy(sPolygon, "Полигон");
	strcpy(sPolygonsCircles, "Полигоны, круги");
	strcpy(sPrecision, "точность");
	strcpy(sPretulnumar0, "Цена должна быть больше 0!");
	strcpy(sPretulnumarreal, "Цена должна быть реальным числом!");
	strcpy(sPreview, "Предосмотр");
	strcpy(sPrice, "Цена");
	strcpy(sPriceMustBeGreaterThanZero, "Цена должна быть больше нуля");
	strcpy(sPriceofbars, "Цена баров");
	strcpy(sPriceperbar, "Цена за бар");
	strcpy(sPricepersheet, "Цена за лист");
	strcpy(sPricepersquareunitofmaterial, "Цена за квадратную единицу материала");
	strcpy(sPriceperunit, "Цена за еденицу");
	strcpy(sPrint, "Печать");
	strcpy(sPrintdiagramsastables, "Печать схемы таблицей");
	strcpy(sPrinter, "Принтер");
	strcpy(sPrinterBounds, "Границы для принтера");
	strcpy(sPrinting, "печать");
	strcpy(sPrintonlyutilizedarea, "Печать только использованных листов");
	strcpy(sPrintthecontentsoftheDemand, "Распечатать содержимое Заказа");
	strcpy(sPrintthecontentsoftheInventory, "Распечатать содержимое Склада");
	strcpy(sPrintthecurrentsolution, "Печать текущего решения");
	strcpy(sPriority, "Приоритет");
	strcpy(sPrioritytocutapieceZero0isthehighestpriority, "Приоритет раскроя детали. Ноль (0) это наивысший приоритет");
	strcpy(sProcentul0100, "Процент должен быть больше 0 и меньше или равен 100");
	strcpy(sProcentulnumarreal, "Процент должен быть реальным числом!");
	strcpy(sProductdefinition, "Описание изделия");
	strcpy(sProductExists, "Изделие с таким именем уже существует. Выберите другое имя");
	strcpy(sProductName, "Название изделия");
	strcpy(sProducts, "Изделия");
	strcpy(sProducts, "Изделия");
	strcpy(sProject, "проект");
	strcpy(sProperties, "свойства");
	strcpy(sProperty, "свойство");
	strcpy(sQuantity, "Количество");
	strcpy(sQuantitynumberofsheetsofthistype, "Количество (число) листов этого типа");
	strcpy(sRadius, "Радиус");
	strcpy(sRectangular, "Прямоугольный");
	strcpy(sRedefinetypesofedgeband, "Переопределить типы кромки");
	strcpy(sRedefinetypesofmaterial, "Переопределить типы материала");
	strcpy(sRegistration, "Регистрация");
	strcpy(sRegistrationKeyfromOptimalPrograms, "Регистрационный Ключ");
	strcpy(sRegistrationSuccessful, "Регистрация прошла успешно!");
	strcpy(sRemoveallpiecesinInventory, "Убрать все элементы со Склада");
	strcpy(sRemoveCut, "Убрать рез");
	strcpy(sRemovetheselectedpiece, "Убрать выбранную деталь");
	strcpy(sReports, "Отчеты");
	strcpy(sRequestedMaterial, "Требуемый тип");
	strcpy(sRestore, "Восстановить");
	strcpy(sResults, "Результаты");
	strcpy(sReusedwaste, "Деловой остаток");
	strcpy(sRight, "Справа");
	strcpy(sRightcoordinateofthedefect, "Правая координата дефекта");
	strcpy(sRotation, "Вращение.");
	strcpy(sRotationAngle, "Угол поворота.");
	strcpy(sRotationStep, "Вращение шаг");
	strcpy(sRoundAllFractionsTo, "Дробные значения должны быть округлены к");
	strcpy(sRow, "строка");
	strcpy(sRows, "Строки");
	strcpy(sRun, "Последние решения");
	strcpy(sRunningtime, "Время работы");
	strcpy(sSameforall, "То же для всех");
	strcpy(sSave, "Сохранить");
	strcpy(sSaveAllImages, "Сохранить Все Изображения");
	strcpy(sSaveAs, "Сохранить как");
	strcpy(sSaveChanges, "Заказ был изменен. Хотите сохранить?");
	strcpy(sSaveCurrentImage, "Сохранить текущее изображение");
	strcpy(sSavedataparameters, "Сохранить данные + параметры");
	strcpy(sSaveEverything, "Сохранить Всё..");
	strcpy(sSaveInventory, "Сохранить Склад");
	strcpy(sSaveInventoryandDemand, "Сохранить Склад и Заказ");
	strcpy(sSaveResults, "Сохранить Результаты");
	strcpy(sSaveStatisticsinafile, "Сохранить статистику в файл");
	strcpy(sSavethecurrentimage, "Сохранить текущее изображение");
	strcpy(sSavethecurrentimageorstatistic, "Сохранить текущее изображение или статистику");
	strcpy(sSavetheDEMANDinafile, "Сохранить в файл");
	strcpy(sSavetheDemandinafilewithadifferentname, "Сохранить Заказ в файле под другим именем");
	strcpy(sSavetheREPOSITORYinafile, "Сохранить Склад в файле");
	strcpy(sSerialNumber, "Регистрационный Ключ");
	strcpy(sService, "Сервис");
	strcpy(sSetDefaultValues, "Это сбросит все параметры к их значениям по умолчанию. Все настройки будут утеряны. Вы точно хотите сделать это?");
	strcpy(sSetedgeband, "Установка кромки");
	strcpy(sSetedgetrim, "Установка обрезки краев");
	strcpy(sSetthesameedgebandforalledges, "Установить ту же кромку для каждого края");
	strcpy(sSetthesamegrindingforalledges, "Установить ту же шлифовку для всех сторон");
	strcpy(sSetthesametrimforalledges, "Установить ту же обрезку для всех сторон");
	strcpy(sSettings, "Настройки");
	strcpy(sShape, "Shape");
	strcpy(sSheet, "Лист");
	strcpy(sSheetsBarstypes, "Листы и Полосы");
	strcpy(sSheetSize, "Размер листа");
	strcpy(sSheetsperPage, "Листов на Страницу");
	strcpy(sShort, "Short");
	strcpy(sShorterexecutiontime, "меньше времени");
	strcpy(sShowallsimpleproducts, "Показать все простые изделия");
	strcpy(sShowcustomername, "Имя заказчика");
	strcpy(sShowCustomTextOnEachPiece, "Произвольный текст на каждой детали Заказа");
	strcpy(sShowdiagramasatable, "Показать схему таблицей");
	strcpy(sShowedgeband, "Кромку");
	strcpy(sShowedgebandssettinginanewwindow, "Настройки кромки в новом окне");
	strcpy(sShowgrindingsettingsinanewwindow, "Параметры шлифовки в новом окне");
	strcpy(sShowHorizontalLabelsAlways, "Метки всегда горизонтально");
	strcpy(sShowRemovethesizeofthepiecesinthecurrentsolution, "Показать/Убрать размеры деталей в текущем решении");
	strcpy(sShowRemovethesizeofthewastesinthecurrentsolution, "Показать/Убрать размеры остатков в текущем решении");
	strcpy(sShowtotalcutlength, "Общую длину пропила");
	strcpy(sShowtrimedgesettingsinanewwindow, "Настройки обрезки края в новом окне");
	strcpy(sSimpleMaterialExists, "Имя материала уже есть в списке материалов. Дайте другое имя");
	strcpy(sSinglePieceStrips, "Одно-детальные полосы");
	strcpy(sSizes, "Размеры");
	strcpy(sSmallerorequalto, "Меньше или равно");
	strcpy(sSort, "Сортировать");
	strcpy(sSortAscendingByArea, "По возрастанию площади");
	strcpy(sSortDescendingByArea, "По убыванию площади");
	strcpy(sSpecifyhowdifferentthepiecesinthelaststagecanbeValue0meansnodifference, "Указывает насколько разными по высоте могут быть детали последнего шага. Значение 0 значит, что без разницы");
	strcpy(sSpecifyifpiecesinthelaststagecanbedifferentornotdepeultimaetapapotfidiferitesaunucadimensiune, "Указывает могут ли детали на последнем шаге быть разными или нет");
	strcpy(sSpecifyifthepiececanberotatedornotIfnotitwillbecutinthesamewayasitwasintroducedinDemandLengthofthepieceparalleltothelengthofthesheet, "Указывает может вращаться деталь или нет.  Если нет, она будет  раскроена так-же как представлена в заказе (длина детали параллельна длине листа)");
	strcpy(sSpecifyinhowmanystageswemakethecutsDuringastageallcutshavethesamedirection, "Укажите сколько шагов порезки возможно. На каждом шаге все пропилы будут иметь одно направление");
	strcpy(sStartthesearchprocess, "Запуск процесса поиска");
	strcpy(sStatistics, "Статистика");
	strcpy(sStatisticsE, "Отчеты: Дополнительно");
	strcpy(sStatisticsforeachtypeofmaterial, "По типу материала");
	strcpy(sStep, "Шаг");
	strcpy(sStergeDepozit, "Вы хотите очистить Склад?");
	strcpy(sStergeMaterial, "Удалить материал?");
	strcpy(sStergePiesele, "Удалить деталь?");
	strcpy(sStergePiesa, "Удалить деталь?");
	strcpy(sStopthesearchprocess, "Остановить процесс поиска");
	strcpy(sStrongoptimization, "СИЛЬНАЯ");
	strcpy(sSubtractthebandthicknessfrompiecesize, "Вычесть толщину кромки из размеров деталей");
	strcpy(sSummary, "резюме");
	strcpy(sSuprafataTotalaFolosita, "Вся использованная площадь");
	strcpy(sSuprafatautilizata, "Использовано");
	strcpy(sSwitchbetweenfiberandrotationoption, "Переключение между режимами направления текстуры и вращением");
	strcpy(sTechnical, "Технические");
	strcpy(sTechnicalsettings, "Технические параметры");
	strcpy(sTemporaryPanelHint, "Временная панель для переноса деталей между листами");
	strcpy(sText, "Текст");
	strcpy(sThe_application_has_expired, "Программа истек.");
	strcpy(sThe_application_is_not_registered, "Программное обеспечение не зарегистрированы.");
	strcpy(sThe_application_was_first_started_on, "Программное обеспечение было впервые начал на.");
	strcpy(sThecutsareperformedfromasidetotheothersideofthematerial, "Рез производится от одной стороны материала к другой");
	strcpy(sThecuttingmachinecanfollowtheshapeofthematerial, "Машина порезки может следовать форме деталей");
	strcpy(sTheedgesofsheetsthatmustbetrimedduefaults, "Край листа, что должен быть обрезан из-за повреждений");
	strcpy(sTheLargestSize, "Наибольший размер.");
	strcpy(sThenameofthecustomerforwhichyoucutthepiece, "Имя заказчика, для которого вы делаете порезку");
	strcpy(sThenameofyourcustomer, "Имя Вашего заказчика");
	strcpy(sThepiececanberotated, "Деталь может вращаться");
	strcpy(sTheprogramtriestoavoidwasteswhichhavebothsizeslessthanthisvalue, "Все остатки, у которых оба размера меньше чем это значение, будут проигнорированы");
	strcpy(sThereAreNoProducts, "Пока что не определенно ни одного изделия");
	strcpy(sThestockofmaterialhasbeenpreviouslyloadedfromanExcelorCSVformatPleaseloaditagain, "Запасы материальных ранее была загружена из формата Excel или CSV. Пожалуйста, загрузите его снова, если вы хотите работать на нем.");
	strcpy(sThetotallengthofcutting, "Общая длина пропила");
	strcpy(sThewidthofthecuttingsawForglasscuttingoptimizationitcanbe0Forwooditshouldbegreaterthan0, "Ширина пропила. Для раскроя стекла может быть 0. Для остальных всегда больше нуля");
	strcpy(sThewidthofthecuttingsawforlinearpieces, "Ширина пропила для линейного материала");
	strcpy(sThickness, "Толщина");
	strcpy(sThischaracterisusedforfillingthewasterectanglesIfyoudonotwantfilledwastejustremovethischaracter, "Этот символ используется для заполнения площади остатков. Если Вы не хотите этого - просто уберите его");
	strcpy(sThisindexhasvaluebetween1andthenumberofpieces, "Этот номер имеет значение от 1 и до числа деталей");
	strcpy(sThisOptionWillOverrideTheInventoryFileIfLoadedFromExcelOrCsvFiles, "Этот параметр заменяет файл, содержащий запас, если фондовый загружается из Excel или CSV файлах.");
	strcpy(sThisProgramisLicensedTo, "Программа зарегистрирована на");
	strcpy(sThisvaluewillbeaddedtotheedgebandingmaterialoneachside, "Эта длина будет добавляться к каждому отрезу кромки для удобства поклейки на материал");
	strcpy(sTipNevid, "Тип материала не может быть пустым");
	strcpy(sTitle, "Title");
	strcpy(sTools, "инструменты");
	strcpy(sTop, "Сверху");
	strcpy(sTopcoordinateofthedefect, "Верхняя координата дефекта");
	strcpy(sTotalGarbageWaste, "Всего отходных остатков");
	strcpy(sTotalInventoryWaste, "Всего остатков Склада");
	strcpy(sTotalRecycledWaste, "Всего переработанных остатков");
	strcpy(sTotalusedarea, "Вся использованная Площадь");
	strcpy(sTotalusedlength, "Вся использованная Длина");
	strcpy(sTrigonometric, "Тригонометрические");
	strcpy(sTrim, "Обрезка");
	strcpy(sTrimalledgesatthebeginning, "Обрезка каждого края в начале");
	strcpy(sTrimEdge, "Обрезка краев");
	strcpy(sTwoPanels, "2 панели");
	strcpy(sType, "тип");
	strcpy(sTypeofmaterialfromwhichtocut, "Тип исходного материала для раскроя");
	strcpy(sTypesAreNotMatched, "Раскрой не произведен!!! Детали Заказа кроятся из листов Склада имеющих тот-же тип материала. Сейчас на Складе  нет листов требуемого в Заказе типа! Проверьте и измените тип в колонке Материал!");
	strcpy(sUndo, "Откат");
	strcpy(sUndoAccept, "Отмена Решения");
	strcpy(sUnits, "единиц");
	strcpy(sUnregisteredVersion, "Незарегистрированно");
	strcpy(sUpdates, "Обновить");
	strcpy(sUsefulforwoodfurniture, "Полезно для корпусной мебели");
	strcpy(sUseit, "Использовать");
	strcpy(sUsePieceinOptimization, "Использовать деталь в раскрое");
	strcpy(sUserName, "Имя пользователя");
	strcpy(sUtilizationandWastes, "Использовано и Остатки");
	strcpy(sUtilizedArea, "Площадь раскроенных деталей");
	strcpy(sUtilizedBars, "Использованные полосы");
	strcpy(sUtilizeddemandcount, "Число раскроенных деталей Заказа");
	strcpy(sUtilizedParts, "Раскроенные детали");
	strcpy(sUtilizedPieces, "Используемые части");
	strcpy(sUtilizedSheets, "Использованные листы");
	strcpy(sValue, "Значение");
	strcpy(sValueGreaterEqualToZero, "Значение должно быть больше или равно 0");
	strcpy(sValueGreaterThanZero, "Значение должно быть больше 0");
	strcpy(sValueIntegerNumber, "Значение должно быть целым числом!");
	strcpy(sValueRealNumber, "Значение должно быть реальным числом");
	strcpy(s_The_number_is_too_big_or_it_has_too_many_digits_after_decimal_separator, "Число слишком велико или имеет слишком много цифр после десятичного разделителя!");
	strcpy(s_The_number_is_too_big, "Число слишком велико!");
	strcpy(sVertical, "Вертикально");
	strcpy(sWaste, "Остаток");
	strcpy(sWastes, "Остаток");
	strcpy(sWasteAddedToWarehouse, "Остатки добавленные на Склад");
	strcpy(sWastelimits, "Ограничения  для остатков");
	strcpy(sWasteType, "Тип остатка");
	strcpy(sWeakoptimization, "слабая");
	strcpy(sWhattoprint, "Что печатать");
	strcpy(s_What_to_print_or_save_to_file, "Что распечатать или сохранить в файл");
	strcpy(sWhattoprintoneachpiece, "Что печатать на каждой детали");
	strcpy(sWhattoshowoneachpiece, "Что показывать на каждой детали?");
	strcpy(sWidth, "Ширина");
	strcpy(sWood, "дерево");
	strcpy(sWorkingDirectory, "Рабочая папка");
	strcpy(sWrongKey, "Неверный ключ регистрации!");
	strcpy(sYes, "Да");
	strcpy(sYoucannotchooseblackblueorredcolors, "You cannot choose black, blue or red colors.");
	strcpy(sYouCannotMixFractionalDataWithDecimalOnes, "Вы не можете использовать дробные значения со значениями с десятичной точкой!");
	strcpy(sYourcompany, "Ваша компания");
	strcpy(sZip, "Почтовый индекс");
	strcpy(s_Set_the_origin_and_the_direction_of_the_axes, "Установите начало координат и направление осей координат.");

}
