// Language strings: German
// Author: Optimal Programs
// License: MIT License
//---------------------------------------------------------------------------
#include <string.h>
//---------------------------------------------------------------------------
#include "language_string_id.h"
//---------------------------------------------------------------------------
void set_de(void)
{
	// German
	// checked manually, but needs human revision
	// last update on: 2025.11.01.0
	
	strcpy(s_Area, "Fläche");
	strcpy(s_Mass, "Masse");
	strcpy(s_Advanced, "Fortschrittlich");
	strcpy(s_Relative_coordinates, "Relative Koordinaten");
	strcpy(s_Absolute_coordinates, "Absolute Koordinaten");
	strcpy(s_Append_more_rows, "Fügen Sie weitere Zeilen hinzu");

	strcpy(s_Add_to_parts, "Zu Teilen hinzufügen.");
	strcpy(s_Additional, "Zusätzlich");
	strcpy(s_All_results, "Alle Ergebnisse.");
	strcpy(s_Allow_movement_of_pieces, "Bewegung von Teilen zulassen");
	strcpy(s_Allow_part_in_part, "Stück für Stück zulassen");
	strcpy(s_Invalid_piece_Angles_are_too_small_or_too_big_or_height_is_too_small, "Ungültiges Teil! Die Winkel sind zu klein oder zu groß, oder die Höhe ist zu gering.");
	strcpy(s_Append, "Anhängen");
	strcpy(s_As_it_is, "Wie es ist");
	strcpy(s_As_text, "Als Texte");
	strcpy(s_Ascending, "Aufsteigend");
	strcpy(s_Automatic, "Automatisch");
	strcpy(s_Cannot_connect_to_the_Internet_Please_visit_our_website_from_a_browser, "Es kann keine Verbindung zum Internet hergestellt werden! Bitte besuchen Sie unsere Website über einen Browser.");
	strcpy(s_Cannot_copy_or_move_the_files, "Dateien können nicht kopiert oder verschoben werden!");
	strcpy(s_Cannot_delete_the_file, "Datei kann nicht gelöscht werden!");
	strcpy(s_Cannot_modify_old_results, "Alte Ergebnisse können nicht geändert werden!");
	strcpy(s_To_change_click_inside_a_cell_or_press_0_1_or_2, "Klicken Sie zum Ändern in eine Zelle oder drücken Sie 0, 1 oder 2.");
	strcpy(s_Cell, "Zelle");
	strcpy(s_Click_on_the_table_header_to_change_the_columns, "Klicken Sie auf den Tabellenkopf, um die Spalten zu ändern.");
	strcpy(s_Close, "Schließe es");
	strcpy(s_Contact_us, "Kontaktiere uns");
	strcpy(s_Column, "Spalte");
	strcpy(s_Comma, "Komma");
	strcpy(s_The_comma_symbol_cannot_simultaneously_be_the_list_separator_and_the_decimal_separator, "Das Komma-Symbol kann nicht gleichzeitig Listentrennzeichen und Dezimaltrennzeichen sein!");
	strcpy(s_Copy, "Kopieren");
	strcpy(s_Copy_for_move, "Zum Verschieben kopieren");
	strcpy(s_Cut_higher_level_strips_first, "Schneiden Sie zuerst die höherwertigen Streifen");
	strcpy(s_Cut_index, "Schnittindex");

	strcpy(s_The_data_have_been_changed_Do_you_want_to_save_them_to_a_file, "Die Daten wurden geändert. Möchten Sie sie in einer Datei speichern?");
	strcpy(s_Decimal_separator, "Dezimaltrennzeichen");
	strcpy(s_Restore_default_settings, "Standardeinstellungen wiederherstellen");
	strcpy(s_Delete_fiber, "Faser löschen");
	strcpy(s_Descending, "Absteigend");
	strcpy(s_Discard_changes, "Änderungen verwerfen");

	strcpy(s_Delete_all_data, "Alle Daten löschen?");
	strcpy(s_Dot, "Punkt");
	strcpy(s_Do_you_want_to_delete_the_picture, "Möchten Sie das Bild löschen?");
	strcpy(s_Do_you_want_to_delete_the_product, "Möchten Sie das Produkt löschen?");
	strcpy(s_Duplicate_and_append, "Duplizieren und anhängen.");
	strcpy(s_Duplicate_values_are_ignored, "Doppelte Werte wurden ignoriert!");
	strcpy(s_Error, "Error");
	strcpy(s_Error_loading_file, "Fehler beim Laden der Datei.");
	strcpy(s_export_everything, "Alles exportieren");
	strcpy(s_Fit_to_screen, "Vollbild.");
	strcpy(s_Force_fixed_height, "Zeichnen Sie die Teile mit einer festen Höhe.");
	strcpy(s_Flipped, "Umgedreht");
	strcpy(s_Import, "Importieren");
	strcpy(s_If_angles_are_different_from_90_degrees_height_must_be_greater_than_0, "Wenn die Winkel von 90 Grad abweichen, muss die Höhe größer als 0 sein.");
	strcpy(s_Ignore, "Ignorieren");
	strcpy(s_Incorrect_value, "Falscher Wert");
	strcpy(s_Info, "Die Info");
	strcpy(s_Interior, "innen");
	strcpy(s_Give_a_name, "Gib einen Namen.");
	strcpy(s_Group, "Gruppieren Sie es");
	strcpy(s_Header, "Header");
	strcpy(s_Keep_it_as_it_is, "Behalte es wie es ist");
	strcpy(s_Level, "Level");
	strcpy(s_Licensee, "Lizenznehmer");
	strcpy(s_List_separator, "Listentrennzeichen");
	strcpy(s_Made_with_love_in_Cugir_Romania, "Hergestellt mit Liebe in: Cugir, Rumänien");
	strcpy(s_Made_in, "Hergestellt in");
	strcpy(s_Manufacturer, "Hersteller");

	strcpy(s_Manual_arrange, "Manuell anordnen");

	strcpy(s_Mixed, "Gemischt");
	strcpy(s_Multiple_shapes_detected_Next_rows_will_be_overwritten_Continue, "Es wurde mehr als eine Form erkannt. Daher werden die nachfolgenden Zeilen überschrieben. Weitermachen?");
	strcpy(s_More, "Mehr");
	strcpy(s_Multiple_values, "Mehrere Werte");
	strcpy(s_No_texture, "Keine Textur");
	strcpy(s_Number, "Nummer");
	strcpy(s_Number_of_images, "Anzahl der Bilder");
	strcpy(s_Number_of_vertices, "Anzahl der Eckpunkte");
	strcpy(s_Offset, "Versatz");
	strcpy(s_Only_the_currently_selected_items, "Nur die aktuell ausgewählten Elemente.");
	strcpy(s_Optimizing_please_wait, "Optimierung ... bitte warten.");

	strcpy(s_Paste, "Paste");

	strcpy(s_Piece_label, "Teile Etiketten anzeigen");
	strcpy(s_Piece_size, "Stückgröße");
	strcpy(s_Please_contact_us_by_email_if_you_receive_this_error, "Bitte kontaktieren Sie uns per E-Mail, wenn Sie diesen Fehler erhalten.");
	strcpy(s_Please_save_it_first, "Bitte speichern Sie es zuerst.");
	strcpy(s_Position, "Position");
	strcpy(s_Preview, "Vorschau");
	strcpy(s_Rectangle, "Rechteck");

	strcpy(s_Redo_the_last_operation, "Stellen Sie den letzten Vorgang wieder her");
	strcpy(s_Regular_polygon, "Regelmäßiges Vieleck");

	strcpy(s_Reused, "Wiederverwendet");
	strcpy(s_Rotated, "Gedreht");
	strcpy(s_Save_all, "Rette alle");
	strcpy(s_Scrap_label, "Schrottetikett");
	strcpy(s_Scrap_size, "Schrottgröße");
	strcpy(s_Semicolon, "Semikolon");
	strcpy(s_Show_cut_index, "Schnittindex");
	strcpy(s_Show_information, "Informationen anzeigen");
	strcpy(s_Show_piece_label, "Teile Etiketten anzeigen");
	strcpy(s_Show_scrap_label, "Schrottetikett");
	strcpy(s_Show_scrap_s_size_on_the_small_pieces, "Zeigen Sie die Größe des Schrotts auf den kleinen Stücken");
	strcpy(s_Show_size_of_pieces, "Stückgröße");
	strcpy(s_Show_size_of_scrap, "Schrottgröße");
	strcpy(s_Show_sizes, "Größen anzeigen");
	strcpy(s_Show_label, "Etikett anzeigen");
	strcpy(s_Show_length, "Länge anzeigen");

	strcpy(s_Some_numerical_values_are_incorrect_Should_I_fix_all_the_incorrect_values, "Einige Zahlenwerte sind falsch! Sollte ich alle falschen Werte korrigieren?");
	strcpy(s_Some_invalid_values_have_been_removed, "Einige ungültige Werte wurden entfernt.");
	strcpy(s_Sort_by, "Sortiere nach");
	strcpy(s_Sort_ascending_by, "Aufsteigend sortieren nach");
	strcpy(s_Sort_descending_by, "Absteigend sortieren nach");
	strcpy(s_Start, "Start");
	strcpy(s_Starting_angle, "Startwinkel");

	strcpy(s_Sticker, "Aufkleber");
	strcpy(s_Stock, "Warenhaus");
	strcpy(s_Stop, "Stop");
	strcpy(s_System_setting, "Systemeinstellung");
	strcpy(s_Tabular, "Tabellarisch");
	strcpy(s_Total, "Gesamt");
	strcpy(s_Total_size, "Gesamtgröße");
	strcpy(s_Terms_of_the_license, "Bedingungen der Lizenz");
	strcpy(s_The_current_product_has_been_changed_Do_you_want_to_save_it_to_file, "Das aktuelle Produkt wurde geändert. Möchten Sie es in einer Datei speichern?");
	strcpy(s_The_value_is_out_of_the_allowed_range, "Der Wert liegt außerhalb des zulässigen Bereichs.");
	strcpy(s_The_value_must_be_a_real_or_fractional_number_Try_to_replace_the_comma_with_the_dot_if_you_want_to_enter_a_real_number, "Der Wert muss eine reelle oder gebrochene Zahl sein. Versuchen Sie, das Komma durch den Punkt zu ersetzen, wenn Sie eine reelle Zahl eingeben möchten.");
	strcpy(s_This_feature_is_not_implemented_yet, "Diese Funktion ist noch nicht implementiert.");
	strcpy(s_This_operation_cannot_be_reversed, "Dieser Vorgang kann nicht rückgängig gemacht werden.");
	strcpy(s_Undo_the_last_operation, "Machen Sie den letzten Vorgang rückgängig.");
	strcpy(s_Utilization, "Nutzung");
	strcpy(s_Utilized_Stock, "Gebrauchter Bestand");
	strcpy(s_Version, "Ausführung");
	strcpy(s_Visible_columns, "Sichtbare Spalten");
	strcpy(s_You_already_have_the_latest_version_installed, "Sie haben bereits die neueste Version installiert!");
	strcpy(s_What_is_exported, "Was wird exportiert?");
	strcpy(s0meansanynumberofpieces, "Null bedeutet eine beliebige Anzahl von Stücken");
	strcpy(sAbout, "Über");
	strcpy(sAccept, "Akzeptieren");
	strcpy(sAcceptall, "Alle akzeptieren");
	strcpy(sAcceptthecurrentsolution, "Akzeptieren Sie die aktuelle Lösung");
	strcpy(sAdd, "Anhängen");
	strcpy(sAddapiece, "Teil anfügen");
	strcpy(sAddasimpleproducttoDemand, "Fügen Sie den vorhandenen Teilen ein Produkt hinzu.");
	strcpy(sAddgrindingthicknesstopartsize, "Fügen Sie der Stückgröße die Schleifdicke hinzu");
	strcpy(sAddproductnametolabel, "Name zu Etikett hinzufügen");
	strcpy(sAddress, "Adresse");
	strcpy(sAddselectedsizetoInventory, "Hängen Sie die ausgewählte Größe an Lager an");
	strcpy(sAdhesivelabels, "Haftetiketten");
	strcpy(sAdhesivelabelwithinformationaboutpiecesinDemandCustomernameLabelSizeCurrentData, "Klebeetikett mit Informationen zu Teilen: Kundenname, Etikett, Größe, aktuelle Daten usw.");
	strcpy(sAdhesivelabelwithinformationaboutsheetsinInventory, "Klebeetiketten mit Informationen zu vorrätigen Blättern.");
	strcpy(sAll, "Alle");
	strcpy(sAlloffcutswhichhavethesizegreaterthanthisvaluewillbeaddedtoInventory, "Verschnitt, der größer als dieser Wert hist, im Inventar hinzugefügen");
	strcpy(sAllowMirroring, "Umdrehen zulassen");
	strcpy(sAllowRotation, "Drehung zulassen");
	strcpy(sAllPieces, "Alle Stücke");
	strcpy(sAllpredefinedproducts, "Alle vordefinierten Produkte");
	strcpy(sAnewwindowwillbedisplayedwheretheusercansettheedgebandsforeachedge, "Ein neues Fenster wird angezeigt, um die Rand-Bands für jede Kante einstellen zu können");
	strcpy(sAnewwindowwillbedisplayedwheretheusercansetthegrindingvalueforeachedgeofthsheet, "Ein neues Fenster wird angezeigt, in dem der Benutzer die Schleifgröße für jede Kante des Stücks einstellen kann.");
	strcpy(sAnewwindowwillbedisplayedwheretheusercansetthetrimvalueforeachedgeofthsheet, "Ein neues Fenster wird angezeigt, um die Fehler für jede Kante des Teiles setzen zu können.");
	strcpy(sAngle, "Winke");
	strcpy(sAngles, "Winke");
	strcpy(sAnoptimizationparameterisarealnumber, "Ist der Optimierungsparameters eine reelle Zahl ist.");
	strcpy(sAnoptimizationparameterisfractionalnumber, "Optimierung Parameter ist eine Bruch Zahl.");
	strcpy(sAnyShape, "Jede form");
	strcpy(sApolygonmusthaveatleast2vertices, "Ein Polygon muss mindestens 2 Ecken haben!");
	strcpy(sApolygonmusthaveatleast3vertices, "Ein Polygon muss mindestens 3 Ecken haben!");
	strcpy(sApplication_fails_to_initialize, "Die Software konnte nicht initialisiert werden.");
	strcpy(sArc, "Bogen");
	strcpy(sArcLength, "Bogen Länge");
	strcpy(sAreaofusedsheets, "Fläche der verwendeten Platten");
	strcpy(sAshortdescriptionofthesheet, "Kurze Beschreibung der Platte");
	strcpy(sAtleastonepart, "Mindestens ein Teil muß in Liste stehen.");
	strcpy(sAtTheMarginOfTheSheet, "An der Kante der Platte");
	strcpy(sBandtypes, "Arten von Kantenbändern.");
	strcpy(sBar, "Stangen / Rohre");
	strcpy(sBars, "Stangen / Rohre");
	strcpy(sBothsizesoftheoffcutsmustbegreaterthanthisvalue, "Verschnittgröße. Der Verschnitt muss größer als dieser Wert sein.");
	strcpy(sBottom, "Unterseite");
	strcpy(sBottomcoordinateofthedefect, "Die untere Koordinate des Mangels");
	strcpy(sBreakCut, "Brechen Sie den Schnitt");
	strcpy(sBrowse, "Durchsuchen");
	strcpy(sBuy, "Kaufen");
	strcpy(sBuynow, "Jetzt kaufen ...");
	strcpy(sCancel, "Abbrechen");
	strcpy(sCannotBeEmpty, "darf nicht leer sein!");
	strcpy(sCannotmovepartsbetweensheetswhenidenticalsheetsaregroupedPleaseungroupthesheetsfrommenu, "Teile können nicht von einer Platte zu einer anderen Verschoben werden , wenn die Platten gruppiert sind. Bitte streichen Sie die Gruppierung der Platten aus dem Menü..");
	strcpy(sCannotSaveFile, "Kann die Datei nicht speichern");
	strcpy(sCenter, "Zentrum");

	strcpy(sChangeDirection, "Ändern Sie die Richtung.");
	strcpy(sChoose, "Wählen");
	strcpy(sChooseProduct, "Produkt wählen");
	strcpy(sCircle, "Kreis");
	strcpy(sCity, "Ort");
	strcpy(sClear, "Löschen");
	strcpy(sClockWise, "Uhrzeigersinn");
	strcpy(sClosewindow, "Fenster schliessen");
	strcpy(sColor, "Farbe");
	strcpy(sColorofedgeband, "Die Farbe der Umleimer");
	strcpy(sColorPattern, "Farbe / Muster");
	strcpy(sColorpiecesandwastes, "Teile und Abfälle bunt.");
	strcpy(sColumns, "Spalten");
	strcpy(sComment, "Kommentar");
	strcpy(sCompanyname, "Firmenname");
	strcpy(sComplexMaterialExists, "Name des Materials ist bereits in der Liste von komplexen Materialien definiert. Bitte geben ihm einen neuen Namen.");
	strcpy(sComputerCode, "Computer-Code");
	strcpy(sComputerCodefromyourcomputer, "Computer-Code (vom Computer)");
	strcpy(sComputethetotalpriceofDemand, "Berechnen Sie den Gesamtpreis der Nachfrage");
	strcpy(sContents, "Inhalt");
	strcpy(sContinutComanda, "Aktueller Inhalt der benötigten Teile");
	strcpy(sContinutDepozit, "Aktuerller Inhalt des Lagers");
	strcpy(sConversionIsDoneOnlyWhenSomePiecesHaveFractionalValues, "Die Konvertierung erfolgt nur, wenn einige Stücke Bruch Werte haben.");
	strcpy(sConvertsTheSizeOfWasteToAFractionalUnit, "Abfallabmessungen als Bruchwert anzeigen.");
	strcpy(sCouldNotSaveFile1, "Datei kann nicht in dem Verzeichnis erstellt werden");
	strcpy(sCouldNotSaveFile2, "Möglicherweise haben Sie nicht genügend Rechte. Bitte überprüfen oder ändern Sie das Arbeitsverzeichnis aus dem Menü Einstellungen | Arbeitsverzeichnis in einem Ordner, in dem Sie die Rechte zum Schreiben (zum Beispiel c:\\temp) haben.");
	strcpy(sCreationdateYMDHMS, "Erstellungsdatum (Y / M / T, H: M: S)");
	strcpy(sCurrentDate, "Aktuelles Datum");
	strcpy(sCurrentDiagram, "Aktuelles Diagramm");
	strcpy(sCurrentMaterial, "Aktuelles material");
	strcpy(sCurrentversion, "Aktuelle Version");
	strcpy(sCurve_not_closed_Try_increasing_DXF_linking_distance_parameter, "Das Polygon ist nicht geschlossen! Versuchen Sie, den Parameter DXF-Verbindungsabstand zu erhöhen.");
	strcpy(sCustomer, "Kunde");
	strcpy(sCustomerName, "Name des Kunden");
	strcpy(sCustomMessage, "Benutzerdefinierte Meldung");
	strcpy(sCutlength, "Länge des Schnitts");
	strcpy(sCut, "Schnitt");
	strcpy(sCuts, "Schnitte");
	strcpy(sCutterThickness, "Schnittstärke");
	strcpy(sData, "Die Daten");
	strcpy(sDataCannotBeEmpty, "Daten können nicht leer sein!");
	strcpy(sDateymdhms, "Datum (J / M / d / h / m / s)");
	strcpy(sDays_left_for_trial, "Tage zum Testen zur Verfügung ");
	strcpy(sDaysLeft, "Tage Zeit,");
	strcpy(sStandard, "Default");
	strcpy(sDefaultInterface, "Standard-Schnittstelle");
	strcpy(sDefects, "Defekt");
	strcpy(sDefectsManager, "Verwalten von Mängeln");
	strcpy(sDefectsofthematerialNopiecescanbeplacedinthefaultyzone, "Mängel des Materials. Keine teile können in der fehlerhaften Zone platziert werden.");
	strcpy(sDelete, "Löschen");
	strcpy(sDeletePiece, "Stück löschen");
	strcpy(sDeleteRow, "Zeile löschen");
	strcpy(sDemandutilization, "Verwendung von Teilen");
	strcpy(sDepozitulmodificat, "Die verwendeten Teile wurden entfernt. Der Abfall wurde dem Lager hinzugefügt.");
	strcpy(sDepozitvid, "Das Lager ist leer");
	strcpy(sDesk, "Schreibtisch");
	strcpy(sDiagram, "Diagramm");
	strcpy(sDiagrams, "Diagramme");
	strcpy(sDiagramasatable, "Diagramm als Tabelle");
	strcpy(sDigits, "Kommastellen");
	strcpy(sDimensiuniplaca, "Größe der Platte");
	strcpy(sDirection, "Richtung");
	strcpy(sDistanceBetweenRows, "Abstand zwischen den Reihen");
	strcpy(sDonotuseit, "Verwenden Sie es nicht");
	strcpy(sDownload, "Herunterladen");
	strcpy(sDoYouWantToClearTheData, "Sie möchten die Daten löschen?");
	strcpy(sDoYouWantToSaveDemand, "Die Teile wurden geändert! Wollen Sie die Änderungen speichern?");
	strcpy(sDoYouWantToSaveParts, "Wollen Sie die Teile speichern?");
	strcpy(sDoYouWantToSaveRepository, "Das Lager wurde geändert! Wollen Sie die Änderungen speichern?");
	strcpy(sDrawing, "Zeichnungen");
	strcpy(sDrawthesolutioncolorful, "Zeichnen Sie die Lösung bunt");
	strcpy(sDuplicateTypes, "Einige Arten sind doppelt ausgeführt! Bitte entfernen Sie Duplikate");
	strcpy(sDuplicateTypesWithComplex, "Einige Namen von Materialien gibt es bereits in der Plattenliste! Bitte entfernen Sie die Duplikate");
	strcpy(sDuplicateValues, "Doppelte Werte");
	strcpy(sEdgeband, "Bands für Kanten");
	strcpy(sEdgebandingwhichisplacedontheedgesofyourpiecePleasedefineedgebandingtypesfromMaterialsEdgeBandingmenu, "Kantenbänder, die an den Kanten Ihres Stücks platziert werden. Bitte definieren Sie Kantenbänder im Menü Materialien.");
	strcpy(sEdgebandsthatwillbeappliedtoeachpart, "Edge-Bands, die für jeden Teil angewendet wird.");
	strcpy(sEdgeBandTolerance, "Toleranz für Kantenanleimmaschinen");
	strcpy(sEdgesthatmustbecutduefaults, "Kanten, die durch Verwerfungen geschnitten werden müssen.");
	strcpy(sEdgetoedge, "Von Kante zu Kante");
	strcpy(sEdit, "Bearbeiten");
	strcpy(sEmail, "E-Mail");
	strcpy(sEmptyData, "Die Daten sind leer!");
	strcpy(sEnabled, "Aktiviert");
	strcpy(sEnabledisabledefectsoftheinventorysheets, "Aktivieren / Deaktivieren der Mängel des Bestandes");
	strcpy(sEnterLabel, "Geben Sie das Etikett ein.");
	strcpy(sEnterTheMaterialName, "Materialnamen eingeben");
	strcpy(sEnterTheProductName, "Produktname eingeben");
	strcpy(sEvaluationError, "Fehler auf der Auswertung von Ausdrücken!");
	strcpy(sExit, "Beenden");
	strcpy(sExpired, "Die Freigabe ist abgelaufen! Bitte registrieren Sie die Software!");
	strcpy(sExport, "Exportieren");
	strcpy(sExportAllDiagrams, "Exportieren Sie alle Diagramme");
	strcpy(sExportAllToASingleFile, "Exportieren Sie alle in eine einzelne Datei");
	strcpy(sExportOptions, "Exportoptionen.");
	strcpy(sExporttoDXFformat, "Export in DXF-Format");
	strcpy(sExporttoExcel, "Export nach Excel");
	strcpy(sExpresieIncorecta, "Falscher mathematischer Ausdruck!");
	strcpy(sExtensions, "Extensions");
	strcpy(sExtra, "Extra");
	strcpy(sExtraComponents, "Zusätzliche Komponenten");
	strcpy(sExtracomponentsattachedtoDemand, "Zusätzliche Komponenten, Teile angehängt");
	strcpy(sFile, "Datei");
	strcpy(sFileName, "Dateiname");
	strcpy(sFillWastes, "Abfälle mit schrägen Linien zeichnen");
	strcpy(sFindoptimalbarsheetsize, "Finden Sie die optimale Größe für Rohre und Bleche.");
	strcpy(sFindoptimalsizeofInventorypieces, "Finden Sie die optimale Größe der Lagerstücke");
	strcpy(sFirstcutMultiplestages, "Erste Schnittrichtung - Mehrere Stufen");
	strcpy(sFirstdirectionforcutishorizontal, "Erste Schnittrichtung ist horizontal.");
	strcpy(sFirstdirectionforcutisvertical, "Erste Schnittrichtung ist vertikal.");
	strcpy(sFollowthecontourofpieces, "Der Kontur der Teile folgen");
	strcpy(sFont, "Schriftart");
	strcpy(sFontsize, "Schriftgröße");
	strcpy(sFullInfo, "Vollständige Informationen");
	strcpy(sDisposedWaste, "Entsorgter Abfall");
	strcpy(sGeneral, "General");
	strcpy(sGenerateCNC, "Generieren CNC");
	strcpy(sGrain, "Textur");
	strcpy(sGraindirection, "Faserrichtung");
	strcpy(sGraphic, "Grafik");
	strcpy(sGreaterorequalto, "Größer oder gleich");
	strcpy(sGrid, "Tabellen ");
	strcpy(sGrinding, "Schleifen Dicke");
	strcpy(sGrosimeTaieturaScalata, "Angezeigte Schnittbreite kann sich von der Realität unterscheiden, weil die Stücke nicht an ihre wahren Größe angezeigt werden. Dieser Umstand hat keinen Einfluss auf die Ergebnisse.");
	strcpy(sGroupidenticallayouts, "Gruppierung von identischen Platten");
	strcpy(sGroupIdenticalParts, "Gruppieren Sie identische Teile");
	strcpy(sGroupingOfIdenticalPiecesIntoOneRow, "Gruppierung von identischen Teilen in einer Zeile.");
	strcpy(sGroupPartsAfterLoadingFromFile, "Gruppieren Sie Teile beim Laden aus einer Datei.");
	strcpy(sHeight, "Höhe");
	strcpy(sHeighttolerance, "Toleranz für die Höhe");
	strcpy(sHelp, "Hilfe");
	strcpy(sHistory, "Geschichte");
	strcpy(sHorizontal, "Horizontale");
	strcpy(sHowtodisplayprintedgebands, "Wie werden Kantenbänder gezeigt?");
	strcpy(sIfyousetthebandforoneedgeallwillreceivethesamevalue, "Wenn Sie das Band für eine Kante einstellen, erhalten alle Kanten den gleichen Wert..");
	strcpy(sIfyousetthegrindingforoneedgeallwillreceivethesamevalue, "Wenn Sie den Schleifwert für eine Kante festlegen, erhalten alle Kanten den gleichen Wert.");
	strcpy(sIfyousetthetrimforoneedgeallwillreceivethesamevalue, "Wenn Sie den Trimmwert für eine Kante festlegen, erhalten alle Kanten den gleichen Wert.");
	strcpy(sImageBounds, "Bildeinstellungen");
	strcpy(sImageSize, "Bildgröße");
	strcpy(sImportData, "Importieren Sie die Daten");
	strcpy(sIncorrectPassword, "Falsches Passwort");
	strcpy(sIndex, "Index");
	strcpy(sInformationaboutcustomer, "Kundeninformation");
	strcpy(sInputALanguageName, "Name für die Sprache eingeben");
	strcpy(sInsert, "Einfügen");
	strcpy(sInsertPiece, "Einsatzstück");
	strcpy(sInterface, "Schnittstelle");
	strcpy(sInterfaceSettings, "Interface-Einstellungen");
	strcpy(sInvalidHardware, "Ich konnte die Harware nicht erkennen. Bitte kontaktieren Sie uns unter contact@optimalprograms.com");
	strcpy(sInvalidNumber, "Ungültige Anzah");
	strcpy(sInvalidOrderOfComputation, "Ein Auftrag für die Berechnung der Längen kann nicht gemacht werden. Es sind Zirkelbezüge in der Produkt-Definition!");
	strcpy(sInvalidRegistration, "Die Registrierung ist ungültig!");
	strcpy(sInvalidTime, "Ihre Systemzeit ist ungültig.");
	strcpy(sInventory, "Warenhaus");
	strcpy(sisafractionalvalue, "eine Bruchwert.");
	strcpy(sIsArc, "ist ein Bogen");
	strcpy(sisarealvalue, "ist ein echter Wert.");
	strcpy(sLabel, "Etikett");
	strcpy(sLabels, "Etiketten");
	strcpy(sLanguage, "Sprache");
	strcpy(sLatimeanumar0, "Die Breite muss größer als 0 sein!");
	strcpy(sLatimeanumarreal, "Die Breite muss eine reelle Zahl sein!");
	strcpy(sLayerName, "Ebenenname");
	strcpy(sLeft, "Links");
	strcpy(sLeftcoordinateofthedefect, "Die linke Koordinate des Mangels");
	strcpy(sLength, "Länge");
	strcpy(sLengthofthepiecestocut, "Teil größe zum Schneiden");
	strcpy(sLengthofthepiecestocutfrom, "Blattgröße zum Schneiden");
	strcpy(sLengthofusedbars, "Größe der verwendeten Balken");
	strcpy(sLicenseAgreement, "Lizenzvereinbarung");
	strcpy(sLinear, "Linear");
	strcpy(sLinethickness, "Liniendicke");
	strcpy(sLoadafileandappenddatatothecurrentDemand, "Datei laden und anhängen an aktuelle Teileliste.");
	strcpy(sLoadanexistingDemandfromafile, "Laden Sie die benötigten Teile aus einer Datei.");
	strcpy(sLoadAppend, "Laden und Anhängen");
	strcpy(sLoadEverything, "Alles laden");
	strcpy(sLoadInventory, "Laden Sie das Lagers");
	strcpy(sLoadInventoryandDemand, "Material und Nachfrage laden");
	strcpy(sLoadResults, "Ergebnisse laden");
	strcpy(sLocked, "verschlossen");
	strcpy(sLogo, "Logo");
	strcpy(sLong, "Long");
	strcpy(sLongerexecutiontime, "Längere Ausführungszeit");
	strcpy(sLungime, "Breite");
	strcpy(sLungimeanumar0, "Die Länge muss größer als 0 sein!");
	strcpy(sLungimeanumarreal, "Die Länge muss eine reelle Zahl sein!");
	strcpy(sLungimeaTotalaFolosita, "Insgesamt genutzte Länge");
	strcpy(sMagnification, "Vergrößerung");
	strcpy(sMagnify, "Vergrößern");
	strcpy(sMargins, "Ränder");
	strcpy(sMarginsForPaper, "Ränder für Papier");
	strcpy(sMarginsOfTheLabel, "Ränder des Etiketts");
	strcpy(sMaterial, "Material");
	strcpy(sMaterialName, "Materialbezeichnung");
	strcpy(sMaterials, "Materialien");
	strcpy(sMaterialstypes, "Material-Typen");
	strcpy(sMax, "max");
	strcpy(sMaximalArea, "Maximaler Bereich");
	strcpy(sMaximalCutLength, "Maximale Schnittlänge");
	strcpy(sMaxlength, "Maximale Länge");
	strcpy(sMaxPiecesperBar, "Max Stück pro Stange");
	strcpy(sMaxwidth, "Maximale Breite.");
	strcpy(sMeasurementUnit, "Maßeinheit");
	strcpy(sMin, "Minimum");
	strcpy(sMinimalBreakSize, "Minimale Größe Bruch");
	strcpy(sMinimalUsefulSize, "Minimale Größe nützlich");
	strcpy(sMinimalwastesizetoInventory, "Maximale Größe für Abfälle");
	strcpy(s_What_to_minimize, "Was sollte minimiert werden?");
	strcpy(sMinlength, "Minimale Länge");
	strcpy(sMinwidth, "Minimale Breite");
	strcpy(sMirror, "Spiege");
	strcpy(sMirroring, "Spiegeln");
	strcpy(sMiscellaneous, "Andere Statistiken");
	strcpy(sModify, "Ändern");
	strcpy(sModifytheselectedpiece, "Ändern Sie das ausgewählte Stück");
	strcpy(sMovePiece, "Bewegen Stück.");
	strcpy(sMultiplestages, "Mehrere Stufen");
	strcpy(sName, "Name");
	strcpy(sNameofedgeband, "Name des Kantenbänder");
	strcpy(sNewDEMANDUnsaveddatawillbelost, "Neue Teile? Nicht gespeicherte Daten gehen verloren!");
	strcpy(sNewLanguage, "Neue Sprache");
	strcpy(sNewMaterial, "Neues Material");
	strcpy(sNewPasswordincorectlyintroduced, "Neues Passwort falsch eingegeben!");
	strcpy(sNewProduct, "Neues Produkt");
	strcpy(sNewversion, "Nouvelle version");
	strcpy(sNo, "Nein");
	strcpy(sNumarBucati, "Anzahl der Stücke");
	strcpy(sNumberOfCopies, "Anzah");
	strcpy(sNumberofstages, "Anzahl der Stufen");
	strcpy(sNusuficienteplacidepozit, "Nicht alle Stücke wurden optimiert. Mögliche Ursachen: Es gibt nicht genügend Stück im Lager; Typen der Stücke der Nachfrage und Vorrat stiimmen nicht überein; Andere Parameter wurden falsch eingestellt.");
	strcpy(sOfficeNotInstaled, "Microsoft Office ist nicht auf Ihrem Computer oder einer falschen Version installiert worden!");
	strcpy(sOldpassworddoesnotmatch, "Altes Passwort stimmt nicht überein!");
	strcpy(sOnlinehelp, "Online-Hilfe");
	strcpy(sOnlypiecesofthesameheightinthelaststage, "Teile mit gleicher Höhe in der letzten Stufe");
	strcpy(sOpen, "öffnen");
	strcpy(sOptimization, "Optimierung");
	strcpy(sOptimizationDone, "Optimierung durchgeführt! Sie können die erhaltenen Diagramme drucken oder speichern. Drücken Sie die Taste Annehmen, wenn Sie mit der aktuellen Lösung zufrieden sind. Ansonsten drücken Sie erneut Starten.");
	strcpy(sOptimizationType, "Optimierungstyp");
	strcpy(sOptions, "Optionen");
	strcpy(sOptionsrelatedtotheinterface, "Optionen im Zusammenhang mit der Schnittstelle");
	strcpy(sor, "oder");
	strcpy(sOthercomponents, "Andere Komponenten");
	strcpy(sOthers, "Andere");
	strcpy(sOtherstatistics, "Andere Statistiken");
	strcpy(sOverrideExcelCSVfiles, "Excel / CSV-Dateien überschreiben");
	strcpy(sParameter, "Parameter");
	strcpy(sParts, "TEILE");
	strcpy(sPattern, "Muster");
	strcpy(sPatternforwaste, "Muster für Abfälle");
	strcpy(sPerimeter, "Perimeter");
	strcpy(sPermitedRotationAngle, "Zulässiger Drehwinkel.");
	strcpy(sPhone, "Telefon");
	strcpy(sPicture, "Bild");
	strcpy(sPiece, "Stück");
	strcpy(sPieceindex, "Teile-Index");
	strcpy(sPieces, "Teile");
	strcpy(sPiecesize, "Teil Größe");
	strcpy(sPiecesizelabeledgebandwillbeprinted, "Teil Größe, label, wird Kantenbänder gedruckt werden.");
	strcpy(sPierdere, "Abfal");
	strcpy(sPixels, "Pixe");
	strcpy(sPlacilefolositeDepozit, "Verwendete Teile aus dem Lager.");
	strcpy(sPlease_contact_us_at_contact_nestingtechnologies_com, "Bitte kontaktieren Sie uns contact@nesting-technologies.com");
	strcpy(sPlease_contact_us_at_contact_optimalprograms_com, "Bitte kontaktieren Sie uns contact@optimalprograms.com");
	strcpy(sPleaseenteralldataeitherasfractionalorrealDonotmixthem, "Daten entweder als Bruch oder Zahl eingeben. Nicht mischen!");
	strcpy(sPleaseEnterSomeTypesOfMaterials, "Es ist keine Materialart definiert. Sie können sie im Materialien Menü definieren.");
	strcpy(sPleasesendtheNameandtheCodetotheaddresscontactoptimalprogramscominordertoobtaintheRegistrationKey, "Um den Freischaltcode zu erhalten senden Sie bitte den Namen und den Code zu: contact@optimalprograms.com.");
	strcpy(sPolygon, "Polygon");
	strcpy(sPolygonsCircles, "Polygone, Kreise");
	strcpy(sPrecision, "Präzision");
	strcpy(sPretulnumar0, "Der Preis muss größer als 0 sein!");
	strcpy(sPretulnumarreal, "Der Preis muss eine reelle Zahl sein!");
	strcpy(sPreview, "Vorschau");
	strcpy(sPrice, "Preis");
	strcpy(sPriceMustBeGreaterThanZero, "Preis muss größer als Nul");
	strcpy(sPriceofbars, "Preis von Stangen");
	strcpy(sPriceperbar, "Preis pro bar");
	strcpy(sPricepersheet, "Preis pro Platte");
	strcpy(sPricepersquareunitofmaterial, "Preis pro Flächeneinheit des Materials.");
	strcpy(sPriceperunit, "Preis pro Einheit");
	strcpy(sPrint, "Drucken");
	strcpy(sPrintdiagramsastables, "Drucken Diagramme in Form von Tabellen.");
	strcpy(sPrinter, "Drucker");
	strcpy(sPrinterBounds, "Die Margen für Drucker");
	strcpy(sPrinting, "Drucken");
	strcpy(sPrintonlyutilizedarea, "Drucken Sie nur die genutzte Fläche");
	strcpy(sPrintthecontentsoftheDemand, "Drucken Sie den Inhalt des Demand.");
	strcpy(sPrintthecontentsoftheInventory, "Drucken Sie den Inhalt der Aktie.");
	strcpy(sPrintthecurrentsolution, "Drucken Sie die aktuelle Lösung.");
	strcpy(sPriority, "Priorität");
	strcpy(sPrioritytocutapieceZero0isthehighestpriority, "Schnittpriortät. Null (0) ist die höchste Priorität.");
	strcpy(sProcentul0100, "Die Prozentangaben muss größer als 0 und kleiner oder gleich 100 sein!");
	strcpy(sProcentulnumarreal, "Die Prozente muss eine reelle Zahl sein!");
	strcpy(sProductdefinition, "Produktdefinition");
	strcpy(sProductExists, "Das Produkt ist bereits vorhanden. Wählen Sie einen anderen Namen.");
	strcpy(sProductName, "Produktname");
	strcpy(sProducts, "Produkt");
	strcpy(sProducts, "Produkte");
	strcpy(sProject, "Projekt");
	strcpy(sProperties, "Eigenschaften");
	strcpy(sProperty, "Eigentum");
	strcpy(sQuantity, "Menge");
	strcpy(sQuantitynumberofsheetsofthistype, "Anzahl der Plattenart");
	strcpy(sRadius, "Radius");
	strcpy(sRectangular, "Rechteck");
	strcpy(sRedefinetypesofedgeband, "Umleimerarten neu definieren");
	strcpy(sRedefinetypesofmaterial, "Materialarten neu definieren");
	strcpy(sRegistration, "Anmeldung");
	strcpy(sRegistrationKeyfromOptimalPrograms, "Registrierungsschlüssel");
	strcpy(sRegistrationSuccessful, "Anmeldung erfolgreich!");
	strcpy(sRemoveallpiecesinInventory, "Entfernen Sie alle Teile aus dem Lager.");
	strcpy(sRemoveCut, "Schnitte löschen");
	strcpy(sRemovetheselectedpiece, "Entfernen Sie das ausgewählte Teile");
	strcpy(sReports, "Berichte");
	strcpy(sRequestedMaterial, "Angefordertes Material");
	strcpy(sRestore, "Wiederherstellen");
	strcpy(sResults, "Ergebnisse");
	strcpy(sReusedwaste, "Abfall wiederverwenden");
	strcpy(sRight, "Rechts");
	strcpy(sRightcoordinateofthedefect, "Die Koordinaten des Mangels von rechts");
	strcpy(sRotation, "Rotation");
	strcpy(sRotationAngle, "Drehwinke");
	strcpy(sRotationStep, "Rotationsschritt.");
	strcpy(sRoundAllFractionsTo, "Bruch-Werte müssen abgerundet sein");
	strcpy(sRow, "Zeile");
	strcpy(sRows, "Zeilen");
	strcpy(sRun, "Neueste Lösungen");
	strcpy(sRunningtime, "Laufzeit");
	strcpy(sSameforall, "Das Gleiche gilt für alle");
	strcpy(sSave, "Speichern");
	strcpy(sSaveAllImages, "Alle Bilder speichern");
	strcpy(sSaveAs, "Speichern unter");
	strcpy(sSaveChanges, "Die Teile wurden geändert. Möchten Sie sie speichern?");
	strcpy(sSaveCurrentImage, "Aktuelles Bild speichern");
	strcpy(sSavedataparameters, "Daten speichern und Parameter");
	strcpy(sSaveEverything, "Alles speichern");
	strcpy(sSaveInventory, "Lager speichern");
	strcpy(sSaveInventoryandDemand, "Speichern Sie das Inventar und Teile");
	strcpy(sSaveResults, "Ergebnisse speichern");
	strcpy(sSaveStatisticsinafile, "Statistiken in einer Datei speichern");
	strcpy(sSavethecurrentimage, "Aktuelles Bild speichern");
	strcpy(sSavethecurrentimageorstatistic, "Aktuelles Bild oder Statistik speichern");
	strcpy(sSavetheDEMANDinafile, "In Datei speichern");
	strcpy(sSavetheDemandinafilewithadifferentname, "Speichern Sie die benötigten Teile in einer Datei mit einem anderen Namen.");
	strcpy(sSavetheREPOSITORYinafile, "Speichern Sie den Inhalt in einer Datei");
	strcpy(sSerialNumber, "Freischaltcode");
	strcpy(sService, "Service");
	strcpy(sSetDefaultValues, "Damit werden alle Parameter auf ihre Standardwerte zurückzusetzen. Alle Einstellungen gehen verloren. Sind Sie sicher, dass Sie dies tun möchten?");
	strcpy(sSetedgeband, "Umleimer Einstellen");
	strcpy(sSetedgetrim, "Stellen Sie die Trimmung ein");
	strcpy(sSetthesameedgebandforalledges, "Stellen Sie den gleichen Rand-Band für alle Kanten");
	strcpy(sSetthesamegrindingforalledges, "Stellen Sie den gleichen Schleifen für alle Kanten");
	strcpy(sSetthesametrimforalledges, "Stellen Sie den gleichen Schnitt für Mängel, für alle Kanten");
	strcpy(sSettings, "Einstellungen");
	strcpy(sShape, "Form");
	strcpy(sSheet, "Platte");
	strcpy(sSheetsBarstypes, "Platten_Rohr Typen");
	strcpy(sSheetSize, "Größe der Platte");
	strcpy(sSheetsperPage, "Platten pro Seite");
	strcpy(sShort, "Short");
	strcpy(sShorterexecutiontime, "Kurze Laufzeit");
	strcpy(sShowallsimpleproducts, "Alle einfachen Produkte");
	strcpy(sShowcustomername, "Kundenname anzeigen");
	strcpy(sShowCustomTextOnEachPiece, "Kundenspezifischen Text auf jedem Stück anzeigen");
	strcpy(sShowdiagramasatable, "Diagramm als Tabelle anzeigen.");
	strcpy(sShowedgeband, "Kantenbänder zeigen");
	strcpy(sShowedgebandssettinginanewwindow, "Einstellungen der Rand-Bands in einem neuen Fenster anzeigen");
	strcpy(sShowgrindingsettingsinanewwindow, "Mahleinstellungen in einem neuen Fenster anzeigen");
	strcpy(sShowHorizontalLabelsAlways, "Etiketten immer Horizontal anzeigen");
	strcpy(sShowRemovethesizeofthepiecesinthecurrentsolution, "Ein- / Ausblenden der Größe der Teile.");
	strcpy(sShowRemovethesizeofthewastesinthecurrentsolution, "Größe der Abfälle ein- / ausblenden.");
	strcpy(sShowtotalcutlength, "Insgesamte Schnittlänge zeigen");
	strcpy(sShowtrimedgesettingsinanewwindow, "Einstellungen für die Mängel in einem neuen Fenster anzeigen");
	strcpy(sSimpleMaterialExists, "Name des Materials ist bereits in der Liste der Materialien definiert. Bitte geben ihm einen neuen Namen.");
	strcpy(sSinglePieceStrips, "Streifen aus einem Stück");
	strcpy(sSizes, "Größen");
	strcpy(sSmallerorequalto, "Kleiner oder gleich");
	strcpy(sSort, "Sortieren");
	strcpy(sSortAscendingByArea, "Nach Bereich in aufsteigender Reihenfolge sortieren");
	strcpy(sSortDescendingByArea, "Nach Bereich in absteigender Reihenfolge sortieren");
	strcpy(sSpecifyhowdifferentthepiecesinthelaststagecanbeValue0meansnodifference, "Angeben, wie unterschiedlich Teile in der letzten Stufe sein können. Der Wert 0 bedeutet keinen Unterschied.,");
	strcpy(sSpecifyifpiecesinthelaststagecanbedifferentornotdepeultimaetapapotfidiferitesaunucadimensiune, "Angeben, ob Teile in der letzten Stufe unterschiedlich sein können oder nicht");
	strcpy(sSpecifyifthepiececanberotatedornotIfnotitwillbecutinthesamewayasitwasintroducedinDemandLengthofthepieceparalleltothelengthofthesheet, "Geben Sie an, ob das Teil gedreht werden kann oder nicht. Wenn nicht, wird es auf die gleiche Weise platziert, wie es eingeführt wurde (die Länge des Stücks parallel zur Länge des Blattes),");
	strcpy(sSpecifyinhowmanystageswemakethecutsDuringastageallcutshavethesamedirection, "Geben Sie an, in wie vielen Schritten wir die Schnitte ausführen.");
	strcpy(sStartthesearchprocess, "Starten Sie den Suchvorgang");
	strcpy(sStatistics, "Statistik");
	strcpy(sStatisticsE, "Zusätzliche Reports");
	strcpy(sStatisticsforeachtypeofmaterial, "Materialart Statistik");
	strcpy(sStep, "Schritt");
	strcpy(sStergeDepozit, "Sie wollen das Lager löschen?");
	strcpy(sStergeMaterial, "Material löschen?");
	strcpy(sStergePiesele, "Möchten Sie das Teil löschen?");
	strcpy(sStergePiesa, "Möchten Sie das Teil löschen?");
	strcpy(sStopthesearchprocess, "Stoppen Sie den Suchprozess");
	strcpy(sStrongoptimization, "Starke Optimierung");
	strcpy(sSubtractthebandthicknessfrompiecesize, "Verringern Sie die Größe der Teile mit der Kantenbanddicke");
	strcpy(sSummary, "Zusammenfassung");
	strcpy(sSuprafataTotalaFolosita, "Insgesamt verwendete Oberfläche");
	strcpy(sSuprafatautilizata, "Nutzung");
	strcpy(sSwitchbetweenfiberandrotationoption, "Zwischen Holzrichtung und Rotation Option umschalten.");
	strcpy(sTechnical, "Technisch");
	strcpy(sTechnicalsettings, "Technische Einstellungen");
	strcpy(sTemporaryPanelHint, "Temporäre Panel für bewegliche Teile zwischen den Blättern.");
	strcpy(sText, "Text");
	strcpy(sThe_application_has_expired, "Das Programm ist abgelaufen.");
	strcpy(sThe_application_is_not_registered, "Die Software ist nicht registriert.");
	strcpy(sThe_application_was_first_started_on, "Die Software wurde anfing auf.");
	strcpy(sThecutsareperformedfromasidetotheothersideofthematerial, "Die Schnitte werden von einer Seite zur anderen Seite des Materials ausgeführt.");
	strcpy(sThecuttingmachinecanfollowtheshapeofthematerial, "Schneidemaschinen können der Form des Stückes folgen.");
	strcpy(sTheedgesofsheetsthatmustbetrimedduefaults, "Die Kanten der Platten, die aufgrund der Fehler getrimmt werden müssen");
	strcpy(sTheLargestSize, "Die größte Größe");
	strcpy(sThenameofthecustomerforwhichyoucutthepiece, "Kundenname, für die Sie das Teil schneiden.");
	strcpy(sThenameofyourcustomer, "Name des Kunden");
	strcpy(sThepiececanberotated, "Das Stück kann gedreht werden");
	strcpy(sTheprogramtriestoavoidwasteswhichhavebothsizeslessthanthisvalue, "Das Programm versucht, Abfälle, die in beiden Dimensionen kleiner als dieser Wert sind, zu vermeiden");
	strcpy(sThereAreNoProducts, "Es gibt noch keine definierten Produkte");
	strcpy(sThestockofmaterialhasbeenpreviouslyloadedfromanExcelorCSVformatPleaseloaditagain, "Der Bestand an Material wurde zuvor aus einer Excel-oder CSV-Format geladen. Bitte laden Sie es erneut, wenn Sie daran arbeiten wollen.");
	strcpy(sThetotallengthofcutting, "Die Gesamtlänge der Schnitte");
	strcpy(sThewidthofthecuttingsawForglasscuttingoptimizationitcanbe0Forwooditshouldbegreaterthan0, "Dicke der Säge. Zum Zuschneiden von Glas kann es 0 sein. Für Holz sollte es größer als 0 sein.");
	strcpy(sThewidthofthecuttingsawforlinearpieces, "Dicke der Säge für lineare Stücke.");
	strcpy(sThickness, "Dicke");
	strcpy(sThischaracterisusedforfillingthewasterectanglesIfyoudonotwantfilledwastejustremovethischaracter, "Dieses Symbol wird für die Füllung der Abfall Rechtecke verwendet. Wenn Sie nicht möchten, dass Abfall gefüllt, nimm sie einfach.");
	strcpy(sThisindexhasvaluebetween1andthenumberofpieces, "Dieser Index hat einen Wert zwischen 1 und der Anzahl der Stücke.");
	strcpy(sThisOptionWillOverrideTheInventoryFileIfLoadedFromExcelOrCsvFiles, "Diese Option überschreibt die Datei, wenn Lager aus Excel-oder CSV-Dateien geladen wird.");
	strcpy(sThisProgramisLicensedTo, "Dieses Programm wird lizenziert");
	strcpy(sThisvaluewillbeaddedtotheedgebandingmaterialoneachside, "Dieser Wert wird an den Rand Banderoliermaterial auf jeder Seite hinzugefügt werden");
	strcpy(sTipNevid, "Materialart darf nicht leer sein.");
	strcpy(sTitle, "Tite");
	strcpy(sTools, "Werkzeuge");
	strcpy(sTop, "Oben");
	strcpy(sTopcoordinateofthedefect, "Die obere Koordinate des Mangels.");
	strcpy(sTotalGarbageWaste, "Alle Abfälle");
	strcpy(sTotalInventoryWaste, "Insgesamt Lager Abfall");
	strcpy(sTotalRecycledWaste, "Alle wiederverwendeten Abfälle");
	strcpy(sTotalusedarea, "Insgesamt genutzte Fläche");
	strcpy(sTotalusedlength, "Insgesamt verwendete Länge");
	strcpy(sTrigonometric, "Trigonometrie");
	strcpy(sTrim, "Trimmen");
	strcpy(sTrimalledgesatthebeginning, "Trimmen aller Kanten zu Beginn");
	strcpy(sTrimEdge, "Rand schneiden");
	strcpy(sTwoPanels, "2 Platten");
	strcpy(sType, "Art");
	strcpy(sTypeofmaterialfromwhichtocut, "Zu schneiudende Materialart");
	strcpy(sTypesAreNotMatched, "Die Optimierung wurde nicht durchgeführt! Die Materialien aus den Teile- und Lagertabellen stimmen nicht überein! Ein Teil kann nur aus dem gleichnamigen Material aus dem Lager gefertigt werden. Ändern Sie die Materialnamen in den entsprechenden Spalten!");
	strcpy(sUndo, "Rückgängig machen");
	strcpy(sUndoAccept, "Rückgängig Akzeptieren");
	strcpy(sUnits, "Einheiten");
	strcpy(sUnregisteredVersion, "Nicht registriert");
	strcpy(sUpdates, "Aktualisierung");
	strcpy(sUsefulforwoodfurniture, "Nützlich für Holzmöbe");
	strcpy(sUseit, "Verwenden");
	strcpy(sUsePieceinOptimization, "Verwenden Sie das Stück in der Optimierung");
	strcpy(sUserName, "Benutzername");
	strcpy(sUtilizationandWastes, "Die Inanspruchnahme und Abfälle");
	strcpy(sUtilizedArea, "Bereich der verwendeten Teile");
	strcpy(sUtilizedBars, "Genutzt Bars");
	strcpy(sUtilizeddemandcount, "Anzahl der verwendeten Teile.");
	strcpy(sUtilizedParts, "Verwendete Teile");
	strcpy(sUtilizedPieces, "Verwendetes Stück");
	strcpy(sUtilizedSheets, "Benutzte Platten");
	strcpy(sValue, "Wert");
	strcpy(sValueGreaterEqualToZero, "Der Wert muss größer oder gleich Null sein");
	strcpy(sValueGreaterThanZero, "Der Wert muss größer als Null sein");
	strcpy(sValueIntegerNumber, "Der Wert muss eine ganze Zahl sein!");
	strcpy(sValueRealNumber, "Der Wert muss eine reelle Zahl sein. Bitte korrigieren Sie es!");
	strcpy(s_The_number_is_too_big_or_it_has_too_many_digits_after_decimal_separator, "Die Zahl ist zu groß oder hat nach dem Dezimaltrennzeichen zu viele Stellen!");
	strcpy(s_The_number_is_too_big, "Die Anzahl ist zu groß!");
	strcpy(sVertical, "Vertikale");
	strcpy(sWaste, "Schrott");
	strcpy(sWastes, "Schrott");
	strcpy(sWasteAddedToWarehouse, "Der Schrott wurde dem Lager hinzugefügt");
	strcpy(sWastelimits, "Grenzwerte für Abfälle");
	strcpy(sWasteType, "Art der Abfälle");
	strcpy(sWeakoptimization, "Das schwächste Optimierung");
	strcpy(sWhattoprint, "Was soll ich drucken");
	strcpy(s_What_to_print_or_save_to_file, "Was soll gedruckt oder in einer Datei gespeichert werden?");
	strcpy(sWhattoprintoneachpiece, "Was soll auf jedem Teil gedruckt werden");
	strcpy(sWhattoshowoneachpiece, "Was auf jedem Stück zu zeigen?");
	strcpy(sWidth, "Breite");
	strcpy(sWood, "Holz");
	strcpy(sWorkingDirectory, "Arbeitsverzeichnis");
	strcpy(sWrongKey, "Falscher Freischaltcode!");
	strcpy(sYes, "Ja");
	strcpy(sYoucannotchooseblackblueorredcolors, "Farbe nicht auswählbar.");
	strcpy(sYouCannotMixFractionalDataWithDecimalOnes, "Sie können keine Bruchzahlen mit echten Werten kombinieren!");
	strcpy(sYourcompany, "Ihr Unternehmen");
	strcpy(sZip, "Postleitzah");
	strcpy(s_Set_the_origin_and_the_direction_of_the_axes, "Legen Sie den Ursprung und die Richtung der Koordinatenachsen fest.");










	strcpy(s_Number_of_digits_after_the_decimal_separator, "Anzahl der Ziffern nach dem Dezimaltrennzeichen");
	strcpy(s_Percentages, "Prozentsätze");
}

