// Language strings: Lithuanian
// Author: Optimal Programs
// License: MIT License
//---------------------------------------------------------------------------
#include <string.h>
//---------------------------------------------------------------------------
#include "language_string_id.h"
//---------------------------------------------------------------------------
void set_lt(void)
{
	// Lithuanian
	// translated by a customer on 2020.07.28
	// last update on: 2025.11.01.0
	
	strcpy(s_Area, "Plotas");
	strcpy(s_Mass, "Masė");
	strcpy(s_Advanced, "Išplėstinė");
	strcpy(s_Relative_coordinates, "Santykinės koordinatės");
	strcpy(s_Absolute_coordinates, "Absoliučios koordinatės");
	strcpy(s_Append_more_rows, "Pridėti daugiau eilučių");

	strcpy(s_Add_to_parts, "Pridėti prie dalių.");
	strcpy(s_Additional, "Papildomas");
	strcpy(s_All_results, "Visi rezultatai.");
	strcpy(s_Allow_movement_of_pieces, "Leiskite dalims judėti");
	strcpy(s_Allow_part_in_part, "Leisti gabalėliu");
	strcpy(s_Invalid_piece_Angles_are_too_small_or_too_big_or_height_is_too_small, "Netinkamas gabalas! Kampai per maži arba per dideli, arba aukštis per mažas.");
	strcpy(s_Append, "Pridėti");
	strcpy(s_As_it_is, "Taip kaip yra");
	strcpy(s_As_text, "Kaip tekstas");
	strcpy(s_Ascending, "Didėjančia tvarka");
	strcpy(s_Automatic, "Automatinis");
	strcpy(s_Cannot_connect_to_the_Internet_Please_visit_our_website_from_a_browser, "Neįmanoma prisijungti prie interneto! Apsilankykite mūsų svetainėje iš naršyklės.");
	strcpy(s_Cannot_copy_or_move_the_files, "Negalima nukopijuoti ar perkelti failų!");
	strcpy(s_Cannot_delete_the_file, "Negalima ištrinti failo!");
	strcpy(s_Cannot_modify_old_results, "Negalima keisti senų rezultatų!");
	strcpy(s_To_change_click_inside_a_cell_or_press_0_1_or_2, "Norėdami pakeisti, spustelėkite langelio viduje arba paspauskite 0, 1 arba 2.");
	strcpy(s_Cell, "Ląstelė");
	strcpy(s_Click_on_the_table_header_to_change_the_columns, "Spustelėkite lentelės antraštę, kad pakeistumėte stulpelius.");
	strcpy(s_Close, "Uždaryk tai");
	strcpy(s_Contact_us, "Susisiekite su mumis");
	strcpy(s_Column, "Stulpelis");
	strcpy(s_Comma, "Kablelis");
	strcpy(s_The_comma_symbol_cannot_simultaneously_be_the_list_separator_and_the_decimal_separator, "Kablelis negali vienu metu būti sąrašo skirtuku ir dešimtainio skirtuko simboliu!");
	strcpy(s_Copy, "Kopijuoti");
	strcpy(s_Copy_for_move, "Kopijuoti judesiui");
	strcpy(s_Cut_higher_level_strips_first, "Pirmiausia nupjaukite aukštesnio lygio juosteles");
	strcpy(s_Cut_index, "Cut indeksas");

	strcpy(s_The_data_have_been_changed_Do_you_want_to_save_them_to_a_file, "Duomenys buvo pakeisti. Ar norite juos išsaugoti faile?");
	strcpy(s_Decimal_separator, "Dešimtainis skyriklis");
	strcpy(s_Restore_default_settings, "Atkurti numatytuosius nustatymus");
	strcpy(s_Delete_fiber, "Ištrinti pluoštą");
	strcpy(s_Descending, "Mažėjančia tvarka");
	strcpy(s_Discard_changes, "Atsisakyti pakeitimų");

	strcpy(s_Delete_all_data, "Ištrinti visus duomenis?");
	strcpy(s_Dot, "Taškas");
	strcpy(s_Do_you_want_to_delete_the_picture, "Ar norite ištrinti paveikslėlį?");
	strcpy(s_Do_you_want_to_delete_the_product, "Ar norite ištrinti produktą?");
	strcpy(s_Duplicate_and_append, "Kopijuoti ir pridėti.");
	strcpy(s_Duplicate_values_are_ignored, "Nepaisyta pasikartojančių verčių!");
	strcpy(s_Error, "Klaida");
	strcpy(s_Error_loading_file, "Įkeliant failą įvyko klaida.");
	strcpy(s_export_everything, "Eksportuoti viską");
	strcpy(s_Fit_to_screen, "Talpinti ekrane.");
	strcpy(s_Force_fixed_height, "Nubrėžkite gabalus fiksuotu aukščiu.");
	strcpy(s_Flipped, "Apversta");
	strcpy(s_Import, "Importuoti");
	strcpy(s_If_angles_are_different_from_90_degrees_height_must_be_greater_than_0, "Jei kampai skiriasi nuo 90 laipsnių, aukštis turi būti didesnis nei 0.");
	strcpy(s_Ignore, "Ignoruoti");
	strcpy(s_Incorrect_value, "Neteisinga vertė");
	strcpy(s_Info, "Informacija");
	strcpy(s_Interior, "Interjeras");
	strcpy(s_Give_a_name, "Duokite vardą.");
	strcpy(s_Group, "Sugrupuokite jį");
	strcpy(s_Header, "Antraštė");
	strcpy(s_Keep_it_as_it_is, "Palikti kaip yra");
	strcpy(s_Level, "Level");
	strcpy(s_Licensee, "Licenciatas");
	strcpy(s_List_separator, "Sąrašo skyriklis");
	strcpy(s_Made_with_love_in_Cugir_Romania, "Pagaminta su meile: Cugir, Rumunija");
	strcpy(s_Made_in, "Pagaminta m");
	strcpy(s_Manufacturer, "Gamintojas");

	strcpy(s_Manual_arrange, "Rankinis išdėstymas");

	strcpy(s_Mixed, "Mišrus");
	strcpy(s_Multiple_shapes_detected_Next_rows_will_be_overwritten_Continue, "Aptikta daugiau nei viena forma. Todėl kitos eilutės bus perrašytos. Tęsti?");
	strcpy(s_More, "Daugiau");
	strcpy(s_Multiple_values, "Kelios vertės");
	strcpy(s_No_texture, "Nėra tekstūros");
	strcpy(s_Number, "Skaičius");
	strcpy(s_Number_of_images, "Vaizdų skaičius");
	strcpy(s_Number_of_vertices, "Viršūnių skaičius");
	strcpy(s_Offset, "Užskaita");
	strcpy(s_Only_the_currently_selected_items, "Tik šiuo metu pasirinkti elementai.");
	strcpy(s_Optimizing_please_wait, "Optimizuojama... palaukite.");

	strcpy(s_Paste, "Paste");

	strcpy(s_Piece_label, "Detalės etiketė");
	strcpy(s_Piece_size, "Detalės dydis");
	strcpy(s_Please_contact_us_by_email_if_you_receive_this_error, "Jei gausite šią klaidą, susisiekite su mumis el. Paštu.");
	strcpy(s_Please_save_it_first, "Pirmiausia išsaugokite jį.");
	strcpy(s_Position, "Pozicija");
	strcpy(s_Preview, "Peržiūra");
	strcpy(s_Rectangle, "Stačiakampis");

	strcpy(s_Redo_the_last_operation, "Atkurkite paskutinę operaciją");
	strcpy(s_Regular_polygon, "Taisyklingas daugiakampis");

	strcpy(s_Reused, "Pakartotinai panaudota");
	strcpy(s_Rotated, "Pasukta");
	strcpy(s_Save_all, "Išsaugoti viską");
	strcpy(s_Scrap_label, "Atliekos etiketė");
	strcpy(s_Scrap_size, "Atliekos dydis");
	strcpy(s_Semicolon, "Kabliataškis");
	strcpy(s_Show_cut_index, "Rodyti pjovimo indeksą");
	strcpy(s_Show_information, "Rodyti informaciją");
	strcpy(s_Show_piece_label, "Rodyti detalės etiketę");
	strcpy(s_Show_scrap_label, "Rodyti atliekos etiketę");
	strcpy(s_Show_scrap_s_size_on_the_small_pieces, "Parodykite atliekų dydį ant mažų detalių");
	strcpy(s_Show_size_of_pieces, "Rodyti detalės dydis");
	strcpy(s_Show_size_of_scrap, "Rodyti atliekų dydį");
	strcpy(s_Show_sizes, "Rodyti dydžius");
	strcpy(s_Show_label, "Rodyti etiketę");
	strcpy(s_Show_length, "Rodyti ilgį");

	strcpy(s_Some_numerical_values_are_incorrect_Should_I_fix_all_the_incorrect_values, "Kai kurios skaitinės vertės yra klaidingos! Ar turėčiau ištaisyti visas neteisingas reikšmes?");
	strcpy(s_Some_invalid_values_have_been_removed, "Kai kurios netinkamos vertės buvo pašalintos.");
	strcpy(s_Sort_by, "Rūšiuoti pagal");
	strcpy(s_Sort_ascending_by, "Rūšiuoti didėjančia tvarka pagal");
	strcpy(s_Sort_descending_by, "Rūšiuoti mažėjančia tvarka pagal");
	strcpy(s_Start, "Start");
	strcpy(s_Starting_angle, "Pradinis kampas");
	strcpy(s_Sticker, "Lipdukas");

	strcpy(s_Stock, "Atliekos");
	strcpy(s_Stop, "Stop");
	strcpy(s_System_setting, "Sistemos nustatymas");
	strcpy(s_Tabular, "Lentelinis");
	strcpy(s_Total, "Iš viso");
	strcpy(s_Total_size, "Visas dydis");
	strcpy(s_Terms_of_the_license, "Licencijos sąlygos");
	strcpy(s_The_current_product_has_been_changed_Do_you_want_to_save_it_to_file, "Dabartinis produktas buvo pakeistas. Ar norite jį išsaugoti faile?");
	strcpy(s_The_value_is_out_of_the_allowed_range, "Vertė nepatenka į leistiną diapazoną.");
	strcpy(s_The_value_must_be_a_real_or_fractional_number_Try_to_replace_the_comma_with_the_dot_if_you_want_to_enter_a_real_number, "Vertė turi būti tikrasis arba trupmeninis skaičius. Pabandykite pakeisti kablelį tašku, jei norite įvesti tikrąjį skaičių.");
	strcpy(s_This_feature_is_not_implemented_yet, "Ši funkcija dar neįdiegta.");
	strcpy(s_This_operation_cannot_be_reversed, "Šios operacijos negalima pakeisti.");
	strcpy(s_Undo_the_last_operation, "Atšaukite paskutinę operaciją.");
	strcpy(s_Utilization, "Panaudojimas");
	strcpy(s_Utilized_Stock, "Naudotos atsargos");
	strcpy(s_Version, "Versija");
	strcpy(s_Visible_columns, "Matomi stulpeliai");
	strcpy(s_You_already_have_the_latest_version_installed, "Jau turite įdiegtą naujausią versiją!");
	strcpy(s_What_is_exported, "Kas eksportuojama?");
	strcpy(s0meansanynumberofpieces, "Nulis reiškia bet kokį skaičių detalių");
	strcpy(sAbout, "Apie");
	strcpy(sAccept, "Priimti");
	strcpy(sAcceptall, "Priimti viską");
	strcpy(sAcceptthecurrentsolution, "Priimkite dabartinį sprendimą");
	strcpy(sAdd, "Pridėti");
	strcpy(sAddapiece, "Pridėkite detalę");
	strcpy(sAddasimpleproducttoDemand, "Pridėkite gaminį prie esamų dalių.");
	strcpy(sAddgrindingthicknesstopartsize, "Pridėkite šlifavimo storį prie detalės dydžio");
	strcpy(sAddproductnametolabel, "Pridėkite produkto pavadinimą į etiketę");
	strcpy(sAddress, "Adresas");
	strcpy(sAddselectedsizetoInventory, "Pridėkite pasirinktą dydį prie atsargų");
	strcpy(sAdhesivelabels, "Lipnios etiketės");
	strcpy(sAdhesivelabelwithinformationaboutpiecesinDemandCustomernameLabelSizeCurrentData, "Lipni etiketė su informacija apie detales: kliento vardas, etiketė, dydis, dabartiniai duomenys ir kt.");
	strcpy(sAdhesivelabelwithinformationaboutsheetsinInventory, "Lipnios etiketės su informacija apie sandėlyje esančius lakštus.");
	strcpy(sAll, "Visi");
	strcpy(sAlloffcutswhichhavethesizegreaterthanthisvaluewillbeaddedtoInventory, "Visos atliekos didesnės už šią vertę bus pridėtos prie atsargų");
	strcpy(sAllowMirroring, "Leisti apversti");
	strcpy(sAllowRotation, "Leisti pasukti");
	strcpy(sAllPieces, "Visi visos detalės");
	strcpy(sAllpredefinedproducts, "Visi iš anksto nustatyti produktai");
	strcpy(sAnewwindowwillbedisplayedwheretheusercansettheedgebandsforeachedge, "Bus parodytas naujas langas, kuriame vartotojas galės nustatyti kraštų juostą kiekvienai pusei.");
	strcpy(sAnewwindowwillbedisplayedwheretheusercansetthegrindingvalueforeachedgeofthsheet, "Bus parodytas naujas langas, kuriame vartotojas galės nustatyti šlifavimo dydį kiekvienai detalės pusei.");
	strcpy(sAnewwindowwillbedisplayedwheretheusercansetthetrimvalueforeachedgeofthsheet, "Bus parodytas naujas langas, kuriame vartotojas galės nustatyti kiekvienos kūrinio pusės apdailos vertę.");
	strcpy(sAngle, "Kampas");
	strcpy(sAngles, "Kampai");
	strcpy(sAnoptimizationparameterisarealnumber, "Optimizavimo parametras yra realusis skaičius.");
	strcpy(sAnoptimizationparameterisfractionalnumber, "Optimizavimo parametras yra trupmeninis skaičius.");
	strcpy(sAnyShape, "Tikra forma");
	strcpy(sApolygonmusthaveatleast2vertices, "Poligonas turi būti bent 2 viršūnių!");
	strcpy(sApolygonmusthaveatleast3vertices, "Poligonas turi būti bent 3 viršūnių!");
	strcpy(sApplication_fails_to_initialize, "Nepavyko paleisti programos!");
	strcpy(sArc, "Arka");
	strcpy(sArcLength, "Arkos ilgis");
	strcpy(sAreaofusedsheets, "Panaudotų lakštų plotas");
	strcpy(sAshortdescriptionofthesheet, "Trumpas lakšto aprašymas");
	strcpy(sAtleastonepart, "Turite įvesti bent vieną detalę.");
	strcpy(sAtTheMarginOfTheSheet, "Prie lakšto kraštinės");
	strcpy(sBandtypes, "Briaunų juostų tipai");
	strcpy(sBar, "Juostelės");
	strcpy(sBars, "Juostelės");
	strcpy(sBothsizesoftheoffcutsmustbegreaterthanthisvalue, "Abu atliekų dydžiai turi būti didesni už šią vertę.");
	strcpy(sBottom, "Apačia");
	strcpy(sBottomcoordinateofthedefect, "Apatinė defekto koordinatė");
	strcpy(sBreakCut, "Nupjaukite pjūvį");
	strcpy(sBrowse, "Naršykite");
	strcpy(sBuy, "Pirkti");
	strcpy(sBuynow, "Pirkti dabar ...");
	strcpy(sCancel, "Atšaukti");
	strcpy(sCannotBeEmpty, "negali būti tuščias!");
	strcpy(sCannotmovepartsbetweensheetswhenidenticalsheetsaregroupedPleaseungroupthesheetsfrommenu, "Negalima perkelti dalių iš vieno lakšto į kitą, jei vienodi lapai yra sugrupuoti. Atšaukite lakštū grupavimą iš meniu.");
	strcpy(sCannotSaveFile, "Neįmanoma išsaugoti failo");
	strcpy(sCenter, "Centras");

	strcpy(sChangeDirection, "Pakeiskite pjovimo kryptį");
	strcpy(sChoose, "Pasirinkite");
	strcpy(sChooseProduct, "Pasirinkite produktą");
	strcpy(sCircle, "Apskritimas");
	strcpy(sCity, "Miestas");
	strcpy(sClear, "Išvalyti");
	strcpy(sClockWise, "Pagal laikrodžio rodyklę");
	strcpy(sClosewindow, "Uždaryti langą");
	strcpy(sColor, "Spalva");
	strcpy(sColorofedgeband, "Briaunų juostų spalva");
	strcpy(sColorPattern, "Spalva / raštas");
	strcpy(sColorpiecesandwastes, "Spalvotos detalės ir atliekos");
	strcpy(sColumns, "Stulpeliai");
	strcpy(sComment, "Komentuok");
	strcpy(sCompanyname, "Įmonės pavadinimas");
	strcpy(sComplexMaterialExists, "Medžiagos pavadinimas jau yra apibrėžtas sudėtingų medžiagų sąraše. Prašau suteikti jai naują vardą.");
	strcpy(sComputerCode, "Kompiuterio kodas");
	strcpy(sComputerCodefromyourcomputer, "Kompiuterio kodas (iš jūsų kompiuterio)");
	strcpy(sComputethetotalpriceofDemand, "Apskaičiuokite bendrą dalių kainą");
	strcpy(sContents, "Turinys");
	strcpy(sContinutComanda, "Dalių turinys nurodytoje datoje");
	strcpy(sContinutDepozit, "Atsargų kiekis nurodytoje datoje");
	strcpy(sConversionIsDoneOnlyWhenSomePiecesHaveFractionalValues, "Konversija atliekama tik tada, kai kai kurios detalės turi trupmenines vertes.");
	strcpy(sConvertsTheSizeOfWasteToAFractionalUnit, "Parodo atliekų dydį kaip trupmeninę vertę.");
	strcpy(sCouldNotSaveFile1, "Nepavyko išsaugoti failo kataloge");
	strcpy(sCouldNotSaveFile2, "Jums gali neužtekti teisių. Patikrinkite arba pakeiskite darbinį katalogą meniu „Nustatymai |“ Darbinis katalogas aplanke, kuriame turite rašymo teises (pavyzdžiui, c: \\ temp).");
	strcpy(sCreationdateYMDHMS, "sukūtimo data (M:M:D)");
	strcpy(sCurrentDate, "Dabartinė data");
	strcpy(sCurrentDiagram, "Dabartinė schema");
	strcpy(sCurrentMaterial, "Dabartinė medžiaga");
	strcpy(sCurrentversion, "Dabartinė versija");
	strcpy(sCurve_not_closed_Try_increasing_DXF_linking_distance_parameter, "Poligonas neuždarytas! Pabandykite padidinti parametrą DXF susiejimo atstumas.");
	strcpy(sCustomer, "Klientas");
	strcpy(sCustomerName, "Kliento pavadinimas");
	strcpy(sCustomMessage, "Individualizuotas pranešimas");
	strcpy(sCutlength, "Pjūvio ilgis");
	strcpy(sCut, "Pjūvia");
	strcpy(sCuts, "Pjūviai");
	strcpy(sCutterThickness, "Pjūvio storis");
	strcpy(sData, "Duomenys");
	strcpy(sDataCannotBeEmpty, "Duomenys negali būti tušti!");
	strcpy(sDateymdhms, "Data (metai / mėnuo / diena/valandos / minutės/sekundės)");
	strcpy(sDays_left_for_trial, "Bandomoji versija galioja iki");
	strcpy(sDaysLeft, "Liko dienų");
	strcpy(sStandard, "Numatytas");
	strcpy(sDefaultInterface, "Numatytoji sąsaja");
	strcpy(sDefects, "Defektai");
	strcpy(sDefectsManager, "Tvarkykite defektus");
	strcpy(sDefectsofthematerialNopiecescanbeplacedinthefaultyzone, "Medžiagos trūkumai. Pažeistoje zonoje negalima dėti jokių detalių.");
	strcpy(sDelete, "Ištrinti");
	strcpy(sDeletePiece, "Ištrinti detalę");
	strcpy(sDeleteRow, "Ištrinti eilutę");
	strcpy(sDemandutilization, "Dalių panaudojimas");
	strcpy(sDepozitulmodificat, "Panaudotos detalės buvo pašalintos. Atliekos buvo pridėtos prie atsargų.");
	strcpy(sDepozitvid, "Atsargos tuščios");
	strcpy(sDesk, "stalas");
	strcpy(sDiagram, "Diagrama");
	strcpy(sDiagrams, "Diagramos");
	strcpy(sDiagramasatable, "Diagrama kaip lentelė");
	strcpy(sDigits, "skaitmenų");
	strcpy(sDimensiuniplaca, "Lakšto dydis");
	strcpy(sDirection, "Kryptis");
	strcpy(sDistanceBetweenRows, "Atstumas tarp eilučių");
	strcpy(sDonotuseit, "Nenaudokite jo");
	strcpy(sDownload, "parsisiųsti");
	strcpy(sDoYouWantToClearTheData, "Ar norite ištrinti duomenis?");
	strcpy(sDoYouWantToSaveDemand, "Dalys buvo pakeistos! Ar norite išsaugoti pakeitimus?");
	strcpy(sDoYouWantToSaveParts, "Ar norite išsaugoti dalis?");
	strcpy(sDoYouWantToSaveRepository, "Atsargos buvo pakeistos! Ar norite išsaugoti pakeitimus?");
	strcpy(sDrawing, "Piešimas");
	strcpy(sDrawthesolutioncolorful, "Nupieškite spalvotą sprendimą");
	strcpy(sDuplicateTypes, "Kai kurios rūšys yra dubliuojamos! Pašalinkite dublikatus");
	strcpy(sDuplicateTypesWithComplex, "Kai kurie medžiagų pavadinimai jau yra sudėtingų rūšių sąraše! Pašalinkite dublikatus");
	strcpy(sDuplicateValues, "Dublikuotos vertės");
	strcpy(sEdgeband, "Briaunos juostos");
	strcpy(sEdgebandingwhichisplacedontheedgesofyourpiecePleasedefineedgebandingtypesfromMaterialsEdgeBandingmenu, "Krašto juostos dedamos ant jūsų detalių kraštinių. Apibrėžkite kraštų juostas meniu Medžiagų meniu.");
	strcpy(sEdgebandsthatwillbeappliedtoeachpart, "Briaunos juostos, kurios yra pridedamos prie kiekvienos detalės.");
	strcpy(sEdgeBandTolerance, "Briaunų juostų tolerancija");
	strcpy(sEdgesthatmustbecutduefaults, "Kraštai, kuriuos reikia nupjauti dėl pažeidimų.");
	strcpy(sEdgetoedge, "Nuo krašto iki krašto");
	strcpy(sEdit, "Redaguoti");
	strcpy(sEmail, "Pašto adresas");
	strcpy(sEmptyData, "Nėra duomenų!");
	strcpy(sEnabled, "Įjungtas");
	strcpy(sEnabledisabledefectsoftheinventorysheets, "Įgalinti / išjungti atsargų trūkumus");
	strcpy(sEnterLabel, "Įveskite etiketę");
	strcpy(sEnterTheMaterialName, "Įveskite medžiagos pavadinimą");
	strcpy(sEnterTheProductName, "Įveskite produkto pavadinimą");
	strcpy(sEvaluationError, "Išraiškos vertinimo klaida!");
	strcpy(sExit, "Išeiti");
	strcpy(sExpired, "Programinės įrangos galiojimo laikas pasibaigė! Prašome užregistruoti programinę įrangą!");
	strcpy(sExport, "Eksportuoti");
	strcpy(sExportAllDiagrams, "Eksportuoti visas schemas");
	strcpy(sExportAllToASingleFile, "Eksportuokite viską į vieną failą");
	strcpy(sExportOptions, "Eksporto parinktys");
	strcpy(sExporttoDXFformat, "Eksportuoti į DXF formatą");
	strcpy(sExporttoExcel, "Eksportuoti į „Excel“");
	strcpy(sExpresieIncorecta, "Neteisinga matematinė išraiška!");
	strcpy(sExtensions, "Plėtiniai");
	strcpy(sExtra, "Papildoma");
	strcpy(sExtraComponents, "Papildomi komponentai");
	strcpy(sExtracomponentsattachedtoDemand, "Papildomos komponentai, pritvirtinti prie dalių");
	strcpy(sFile, "Dokumentas");
	strcpy(sFileName, "Dokumento pavadinimas");
	strcpy(sFillWastes, "Atliekas nubrėžkite pasvirusiomis linijomis");
	strcpy(sFindoptimalbarsheetsize, "Raskite optimalų juostų ir lakštų dydį.");
	strcpy(sFindoptimalsizeofInventorypieces, "Raskite optimalų atsargų dydį");
	strcpy(sFirstcutMultiplestages, "Pirmoji pjūvio kryptis optimizuojant kelis etapus.");
	strcpy(sFirstdirectionforcutishorizontal, "Pirmojo pjovimo kryptis yra horizontali.");
	strcpy(sFirstdirectionforcutisvertical, "Pirmojo pjovimo kryptis yra vertikali.");
	strcpy(sFollowthecontourofpieces, "Pagal detalės kontūrą");
	strcpy(sFont, "Šriftas");
	strcpy(sFontsize, "Šrifto dydis");
	strcpy(sFullInfo, "Išsami informacija");
	strcpy(sDisposedWaste, "Išmestos atliekos");
	strcpy(sGeneral, "Bendras");
	strcpy(sGenerateCNC, "Sukurti CNC");
	strcpy(sGrain, "Tekstūros");
	strcpy(sGraindirection, "Tekstūros krypti");
	strcpy(sGraphic, "Grafinis");
	strcpy(sGreaterorequalto, "Didesnis ar lygus");
	strcpy(sGrid, "Stalai");
	strcpy(sGrinding, "Šlifavimas");
	strcpy(sGrosimeTaieturaScalata, "Pjūvio storis šiame paveikslėlyje gali skirtis nuo tikrojo, nes gabalėliai nėra pavaizduoti tikruoju masteliu. Šis faktas neturi įtakos rezultatams.");
	strcpy(sGroupidenticallayouts, "Sugrupuoti identiškus lakštus");
	strcpy(sGroupIdenticalParts, "Sugrupuoti identiškas dalis");
	strcpy(sGroupingOfIdenticalPiecesIntoOneRow, "Sugrupuoti idnetiškas dalis į vieną eilę.");
	strcpy(sGroupPartsAfterLoadingFromFile, "Sugrupuoti dalis įkeliant iš documento");
	strcpy(sHeight, "Aukštis");
	strcpy(sHeighttolerance, "Tolerancija aukščiui");
	strcpy(sHelp, "Pagalba");
	strcpy(sHistory, "Istorija");
	strcpy(sHorizontal, "Horizontalus");
	strcpy(sHowtodisplayprintedgebands, "Kaip rodomos kraštinės juostos?");
	strcpy(sIfyousetthebandforoneedgeallwillreceivethesamevalue, "Jei nustatysite juostą vienam kraštui, visi kraštai gaus tą pačią vertę");
	strcpy(sIfyousetthegrindingforoneedgeallwillreceivethesamevalue, "Jei nustatysite šlifavimo vertę vienam kraštui, visi kraštai gaus tą pačią vertę.");
	strcpy(sIfyousetthetrimforoneedgeallwillreceivethesamevalue, "Jei nustatysite vieno krašto apipjaustymą, visi kraštai gaus tą pačią vertę.");
	strcpy(sImageBounds, "Vaizdo ribos");
	strcpy(sImageSize, "Paveikslėlio dydis");
	strcpy(sImportData, "Importuokite duomenis");
	strcpy(sIncorrectPassword, "Neteisingas slaptažodis");
	strcpy(sIndex, "Indeksas");
	strcpy(sInformationaboutcustomer, "Informacija apie klientą");
	strcpy(sInputALanguageName, "Įveskite kalbos pavadinimą");
	strcpy(sInsert, "Įterpti");
	strcpy(sInsertPiece, "Įterpti detalę");
	strcpy(sInterface, "Sąsaja");
	strcpy(sInterfaceSettings, "Sąsajos nustatymai");
	strcpy(sInvalidHardware, "Nepavyko aptikti aparatinės įrangos. Prašome susisiekti su mumis adresu contact@optimalprograms.com");
	strcpy(sInvalidNumber, "Neteisingas numeris");
	strcpy(sInvalidOrderOfComputation, "Neįmanoma nustatyti ilgių skaičiavimo tvarkos. Produkto apibrėžime yra žiediniai ryšiai!");
	strcpy(sInvalidRegistration, "Registracija negalioja!");
	strcpy(sInvalidTime, "Jūsų sistemos laikas netinkamas.");
	strcpy(sInventory, "ATLIEKOS");
	strcpy(sisafractionalvalue, "yra trupmeninė reikšmė.");
	strcpy(sIsArc, "Ar lankas");
	strcpy(sisarealvalue, "yra tikroji reikšmė");
	strcpy(sLabel, "Etiketė");
	strcpy(sLabels, "Etiketės");
	strcpy(sLanguage, "Kalba");
	strcpy(sLatimeanumar0, "Plotis turi būti didesnis nei 0!");
	strcpy(sLatimeanumarreal, "Plotis turi būti tikras skaičius!");
	strcpy(sLayerName, "Sluoksnio vardas");
	strcpy(sLeft, "Kairė");
	strcpy(sLeftcoordinateofthedefect, "Kairioji defekto koordinatė");
	strcpy(sLength, "Ilgis");
	strcpy(sLengthofthepiecestocut, "Detalės dydis pjovimui");
	strcpy(sLengthofthepiecestocutfrom, "Lakšto dydis pjovimui");
	strcpy(sLengthofusedbars, "Naudotų juostų dydis");
	strcpy(sLicenseAgreement, "Licencijos sutartis");
	strcpy(sLinear, "Linijinis");
	strcpy(sLinethickness, "Rašiklio storis");
	strcpy(sLoadafileandappenddatatothecurrentDemand, "Įkelkite dokumentą ir pridėkite duomenis prie esamų dalių.");
	strcpy(sLoadanexistingDemandfromafile, "Įkelkite esamas dalis iš dokumento.");
	strcpy(sLoadAppend, "Įkelkite ir pridėkite");
	strcpy(sLoadEverything, "Įkelk viską");
	strcpy(sLoadInventory, "Įkelkite atsargas");
	strcpy(sLoadInventoryandDemand, "Įkelkite atsargas ir dalis");
	strcpy(sLoadResults, "Įkelkite rezultatus");
	strcpy(sLocked, "Užrakinta");
	strcpy(sLogo, "Logotipas");
	strcpy(sLong, "Ilgai");
	strcpy(sLongerexecutiontime, "Ilgesnis bėgimo laikas");
	strcpy(sLungime, "Ilgis");
	strcpy(sLungimeanumar0, "Ilgis turi būti didesnis nei 0!");
	strcpy(sLungimeanumarreal, "Ilgis turi būti tikras skaičius!");
	strcpy(sLungimeaTotalaFolosita, "Bendras panaudotas ilgis");
	strcpy(sMagnification, "Didinimas");
	strcpy(sMagnify, "Padidinkite");
	strcpy(sMargins, "Paraštės");
	strcpy(sMarginsForPaper, "Popieriaus paraštės");
	strcpy(sMarginsOfTheLabel, "Etiketės paraštės");
	strcpy(sMaterial, "Medžiaga");
	strcpy(sMaterialName, "Medžiagos pavadinimas");
	strcpy(sMaterials, "Medžiagos");
	strcpy(sMaterialstypes, "Medžiagų rūšys");
	strcpy(sMax, "Daugiausia");
	strcpy(sMaximalArea, "Maksimalus plotas");
	strcpy(sMaximalCutLength, "Maksimalus pjūvio ilgis");
	strcpy(sMaxlength, "Maksimalus ilgis");
	strcpy(sMaxPiecesperBar, "Maksimalus vienetų skaičius vienoje juostoje");
	strcpy(sMaxwidth, "Maksimalus plotis");
	strcpy(sMeasurementUnit, "Matavimo vienetas");
	strcpy(sMin, "Mažiausia");
	strcpy(sMinimalBreakSize, "Minimalus lūžio dydis");
	strcpy(sMinimalUsefulSize, "Minimalus naudingas dydis");
	strcpy(sMinimalwastesizetoInventory, "Mažiausias į atsargas dedamos atliekos dydis.");
	strcpy(s_What_to_minimize, "Ką sumažinti?");
	strcpy(sMinlength, "Mažiausias ilgis");
	strcpy(sMinwidth, "Mažiausias plotis");
	strcpy(sMirror, "Veidrodis");
	strcpy(sMirroring, "Veidrodinis");
	strcpy(sMiscellaneous, "Kita statistika");
	strcpy(sModify, "Pakeisti");
	strcpy(sModifytheselectedpiece, "Pakeiskite pasirinktą detalę");
	strcpy(sMovePiece, "Perkelti detalę");
	strcpy(sMultiplestages, "Keli etapai");
	strcpy(sName, "vardas");
	strcpy(sNameofedgeband, "Briaunos juostos pavadinimas");
	strcpy(sNewDEMANDUnsaveddatawillbelost, "Naujos dalys? Neišsaugoti duomenys bus prarasti!");
	strcpy(sNewLanguage, "Nauja kalba");
	strcpy(sNewMaterial, "Nauja medžiaga");
	strcpy(sNewPasswordincorectlyintroduced, "Naujas slaptažodis įvestas neteisingai!");
	strcpy(sNewProduct, "Naujas produktas");
	strcpy(sNewversion, "Nauja versija");
	strcpy(sNo, "Ne");
	strcpy(sNumarBucati, "Dalių skaičius");
	strcpy(sNumberOfCopies, "Kopijų skaičius");
	strcpy(sNumberofstages, "Etapų skaičius");
	strcpy(sNusuficienteplacidepozit, "Ne visos detalės buvo optimizuotos. Galimos priežastys: sandėlyje nepakanka vienetų. Gabalai neįgalinti. Detalių ir atsargų medžiagos skiriasi. Kiti parametrai buvo neteisingai nustatyti.");
	strcpy(sOfficeNotInstaled, "„Microsoft Office“ neįdiegta jūsų kompiuteryje arba įdiegta neteisinga versija!");
	strcpy(sOldpassworddoesnotmatch, "Senas slaptažodis nesutampa!");
	strcpy(sOnlinehelp, "Pagalba internete");
	strcpy(sOnlypiecesofthesameheightinthelaststage, "To paties aukščio detalės paskutiniame etape");
	strcpy(sOpen, "Atidaryti");
	strcpy(sOptimization, "Optimizavimas");
	strcpy(sOptimizationDone, "Atlikta optimizacija! Galite atspausdinti arba išsaugoti gautas diagramas. Paspauskite mygtuką Priimti, jei esate patenkintas dabartiniu sprendimu. Priešingu atveju dar kartą paspauskite Pradėti.");
	strcpy(sOptimizationType, "Optimizacijos tipas");
	strcpy(sOptions, "Pasirinktys");
	strcpy(sOptionsrelatedtotheinterface, "Parinktys, susijusios su sąsaja");
	strcpy(sor, "arba");
	strcpy(sOthercomponents, "Kiti komponentai");
	strcpy(sOthers, "Kiti");
	strcpy(sOtherstatistics, "Kita statistika");
	strcpy(sOverrideExcelCSVfiles, "Nepaisykite „Excel“ / CSV failų");
	strcpy(sParameter, "Parametras");
	strcpy(sParts, "Detalės");
	strcpy(sPattern, "Raštas");
	strcpy(sPatternforwaste, "Atliekų raštas");
	strcpy(sPerimeter, "Perimetras");
	strcpy(sPermitedRotationAngle, "Leistinas pasukimo kampas");
	strcpy(sPhone, "Telefonas");
	strcpy(sPicture, "Vaizdas");
	strcpy(sPiece, "Detalė");
	strcpy(sPieceindex, "Detalės indexas");
	strcpy(sPieces, "Detalės");
	strcpy(sPiecesize, "detalės dydis");
	strcpy(sPiecesizelabeledgebandwillbeprinted, "Bus atspausdintas etiketės dydis, etiketė, kraštinės juostos.");
	strcpy(sPierdere, "Atliekos");
	strcpy(sPixels, "pikselių");
	strcpy(sPlacilefolositeDepozit, "Panaudoti detalės iš atsargų.");
	strcpy(sPlease_contact_us_at_contact_nestingtechnologies_com, "Prašome susisiekti su mumis adresu contact@nesting-technologies.com");
	strcpy(sPlease_contact_us_at_contact_optimalprograms_com, "Prašome susisiekti su mumis adresu contact@optimalprograms.com");
	strcpy(sPleaseenteralldataeitherasfractionalorrealDonotmixthem, "Įveskite visus duomenis trupmeninėmis arba tikromis vertėmis! Nemaišykite jų!");
	strcpy(sPleaseEnterSomeTypesOfMaterials, "Medžiagos tipas nėra apibrėžtas. Galite juos apibrėžti meniu Medžiagos.");
	strcpy(sPleasesendtheNameandtheCodetotheaddresscontactoptimalprogramscominordertoobtaintheRegistrationKey, "Norėdami gauti registracijos raktą, atsiųskite vardą ir kodą adresu: contact@optimalprograms.com.");
	strcpy(sPolygon, "Daugiakampis");
	strcpy(sPolygonsCircles, "Daugiakampiai, apskritimai");
	strcpy(sPrecision, "Tikslumas");
	strcpy(sPretulnumar0, "Kaina turi būti didesnė nei 0!");
	strcpy(sPretulnumarreal, "Kaina turi būti tikras skaičius!");
	strcpy(sPreview, "Peržiūra");
	strcpy(sPrice, "Kaina");
	strcpy(sPriceMustBeGreaterThanZero, "Kaina turi būti didesnė už nulį");
	strcpy(sPriceofbars, "Juostos kaina");
	strcpy(sPriceperbar, "Kaina už juostą");
	strcpy(sPricepersheet, "Kaina už lakštą");
	strcpy(sPricepersquareunitofmaterial, "Medžiagos kvadratinio vieneto kaina");
	strcpy(sPriceperunit, "Vieneto kaina");
	strcpy(sPrint, "Spausdinti");
	strcpy(sPrintdiagramsastables, "Spausdinkite diagramas kaip lenteles.");
	strcpy(sPrinter, "Spausdintuvas");
	strcpy(sPrinterBounds, "Spausdintuvo paraštės");
	strcpy(sPrinting, "Spausdinimas");
	strcpy(sPrintonlyutilizedarea, "Spausdinkite tik panaudotą plotą");
	strcpy(sPrintthecontentsoftheDemand, "Atspausdinkite dalių turinį.");
	strcpy(sPrintthecontentsoftheInventory, "Atspausdinkite atsargų turinį.");
	strcpy(sPrintthecurrentsolution, "Atspausdinkite dabartinį sprendimą.");
	strcpy(sPriority, "Prioritetas");
	strcpy(sPrioritytocutapieceZero0isthehighestpriority, "Pirmenybė supjaustyti gabalą. Nulis (0) yra aukščiausias prioritetas.");
	strcpy(sProcentul0100, "Procentai turi būti didesni nei 0, bet mažesni ar lygūs 100!");
	strcpy(sProcentulnumarreal, "Procentai turi būti tikras skaičius!");
	strcpy(sProductdefinition, "Produkto apibrėžimas");
	strcpy(sProductExists, "Toks produktas jau egzistuoja. Pasirinkite kitą vardą.");
	strcpy(sProductName, "Produkto pavadinimas");
	strcpy(sProducts, "Produktas");
	strcpy(sProducts, "Produktai");
	strcpy(sProject, "Projektas");
	strcpy(sProperties, "Savybės");
	strcpy(sProperty, "Nuosavybė");
	strcpy(sQuantity, "Kiekis");
	strcpy(sQuantitynumberofsheetsofthistype, "Šio tipo lakštų skaičius");
	strcpy(sRadius, "Spindulys");
	strcpy(sRectangular, "Stačiakampis");
	strcpy(sRedefinetypesofedgeband, "Iš naujo apibrėžkite kraštinės juostos tipus");
	strcpy(sRedefinetypesofmaterial, "Iš naujo apibrėžkite medžiagų rūšis");
	strcpy(sRegistration, "Registracija");
	strcpy(sRegistrationKeyfromOptimalPrograms, "Registracijos raktas");
	strcpy(sRegistrationSuccessful, "Registracija buvo sėkminga!");
	strcpy(sRemoveallpiecesinInventory, "Pašalinkite visas detales iš inventoriaus");
	strcpy(sRemoveCut, "Ištrinti pjovimą");
	strcpy(sRemovetheselectedpiece, "Ištrinkite pasirinktą detalę");
	strcpy(sReports, "Ataskaitos");
	strcpy(sRequestedMaterial, "Reikalinga medžiaga");
	strcpy(sRestore, "Atkurti");
	strcpy(sResults, "Rezultatai");
	strcpy(sReusedwaste, "Pakartotinai panaudotos atliekos");
	strcpy(sRight, "Dešinė");
	strcpy(sRightcoordinateofthedefect, "Defekto koordinatės iš dešinės pusės");
	strcpy(sRotation, "Pasukimas");
	strcpy(sRotationAngle, "Pasukimo kampas");
	strcpy(sRotationStep, "Pasukimo žingsnis");
	strcpy(sRoundAllFractionsTo, "Trupmeninės vertės turi būti suapvalintos iki");
	strcpy(sRow, "Eilutė");
	strcpy(sRows, "Eilutės");
	strcpy(sRun, "Naujausi sprendimai");
	strcpy(sRunningtime, "veikimo laikas");
	strcpy(sSameforall, "Visiems tas pats");
	strcpy(sSave, "Išsaugoti");
	strcpy(sSaveAllImages, "Išsaugokite visus vaizdus");
	strcpy(sSaveAs, "Išsaugoti kaip");
	strcpy(sSaveChanges, "Dalys buvo pakeistos. Ar norite juos išsaugoti?");
	strcpy(sSaveCurrentImage, "Išsaugokite dabartinį vaizdą");
	strcpy(sSavedataparameters, "Išsaugokite duomenis ir parametrus");
	strcpy(sSaveEverything, "Išsaugokite viską");
	strcpy(sSaveInventory, "Išsaugoti inventorių");
	strcpy(sSaveInventoryandDemand, "Sutaupykite atsargas ir dalis");
	strcpy(sSaveResults, "Išsaugokite rezultatus");
	strcpy(sSaveStatisticsinafile, "Išsaugokite statistiką dokumente");
	strcpy(sSavethecurrentimage, "Išsaugokite dabartinį vaizdą");
	strcpy(sSavethecurrentimageorstatistic, "Išsaugokite dabartinį vaizdą arba statistiką");
	strcpy(sSavetheDEMANDinafile, "Išsaugoti dokumente");
	strcpy(sSavetheDemandinafilewithadifferentname, "Išsaugokite dalis dokumente kitu pavadinimu.");
	strcpy(sSavetheREPOSITORYinafile, "Išsaugokite atsargas dokumente");
	strcpy(sSerialNumber, "Registracijos raktas");
	strcpy(sService, "Aptarnavimas");
	strcpy(sSetDefaultValues, "Bus atkurti visi numatytieji parametrų nustatymai. Visi jūsų nustatymai bus prarasti. Ar tikrai norite tai padaryti?");
	strcpy(sSetedgeband, "Nustatykite krašto juostą");
	strcpy(sSetedgetrim, "Nustatykite pakraščių trūkumų pjovimo dydį");
	strcpy(sSetthesameedgebandforalledges, "Iš visų pusių nustatykite tą pačią krašto juostą");
	strcpy(sSetthesamegrindingforalledges, "Visus kraštus nustatykite vienodai");
	strcpy(sSetthesametrimforalledges, "Visų kraštų defektų pjaustymą nustatykite vienodai");
	strcpy(sSettings, "Nustatymai");
	strcpy(sShape, "Forma");
	strcpy(sSheet, "Lakštas");
	strcpy(sSheetsBarstypes, "Lakštų_juostų tipai");
	strcpy(sSheetSize, "Lakšto dydis");
	strcpy(sSheetsperPage, "Lakštai viename puslapyje");
	strcpy(sShort, "Trumpas");
	strcpy(sShorterexecutiontime, "Trumpas bėgimo laikas");
	strcpy(sShowallsimpleproducts, "Rodyti visus paprastus produktus");
	strcpy(sShowcustomername, "Rodyti kliento vardą");
	strcpy(sShowCustomTextOnEachPiece, "Rodyti pasirinktinį tekstą ant kiekvienos detalės");
	strcpy(sShowdiagramasatable, "Parodykite diagramą kaip lentelę.");
	strcpy(sShowedgeband, "Rodyti kraštines juostas");
	strcpy(sShowedgebandssettinginanewwindow, "Parodykite kraštų juostų parametrus naujame lange");
	strcpy(sShowgrindingsettingsinanewwindow, "Parodo šlifavimo parametrus naujame lange");
	strcpy(sShowHorizontalLabelsAlways, "Visada rodyti horizontalias etiketes");
	strcpy(sShowRemovethesizeofthepiecesinthecurrentsolution, "Parodykite / paslėpkite gabalų dydį.");
	strcpy(sShowRemovethesizeofthewastesinthecurrentsolution, "Rodyti / slėpti atliekų dydį.");
	strcpy(sShowtotalcutlength, "Rodyti bendrą pjovimo ilgį");
	strcpy(sShowtrimedgesettingsinanewwindow, "Parodykite defektų parametrus naujame lange");
	strcpy(sSimpleMaterialExists, "Medžiagos pavadinimas jau yra apibrėžtas medžiagų sąraše. Prašau suteikti jai naują vardą.");
	strcpy(sSinglePieceStrips, "Vieno gabalo juostelės");
	strcpy(sSizes, "Dydžiai");
	strcpy(sSmallerorequalto, "Mažesnis ar lygus");
	strcpy(sSort, "Rūšiuoti");
	strcpy(sSortAscendingByArea, "Rūšiuokite pagal plotą didėjančia tvarka");
	strcpy(sSortDescendingByArea, "Rūšiuokite pagal plotą mažėjančia tvarka");
	strcpy(sSpecifyhowdifferentthepiecesinthelaststagecanbeValue0meansnodifference, "Nurodykite, kiek gali skirtis detalės paskutiniame etape. 0 vertė reiškia, kad nėra skirtumo.");
	strcpy(sSpecifyifpiecesinthelaststagecanbedifferentornotdepeultimaetapapotfidiferitesaunucadimensiune, "Nurodykite, ar paskutiniojo etapo detalės gali būti skirtingos");
	strcpy(sSpecifyifthepiececanberotatedornotIfnotitwillbecutinthesamewayasitwasintroducedinDemandLengthofthepieceparalleltothelengthofthesheet, "Nurodykite, ar detalę galima pasukti. Jei ne, ji dedama taip, kaip įkelta (detalės ilgis lygiagretus lakšto ilgiui), ");
	strcpy(sSpecifyinhowmanystageswemakethecutsDuringastageallcutshavethesamedirection, "Nurodykite, per kiek etapų atliksime pjūvius.");
	strcpy(sStartthesearchprocess, "Pradėkite paieškos procesą");
	strcpy(sStatistics, "Statistika");
	strcpy(sStatisticsE, "Ataskaitos papildomos");
	strcpy(sStatisticsforeachtypeofmaterial, "Kiekvienos rūšies medžiagos statistika");
	strcpy(sStep, "Žingsnis");
	strcpy(sStergeDepozit, "Ar norite ištrinti inventorių?");
	strcpy(sStergeMaterial, "Ar norite ištrinti medžiagą?");
	strcpy(sStergePiesele, "Ar norite ištrinti detalę?");
	strcpy(sStergePiesa, "Ar norite ištrinti detalę?");
	strcpy(sStopthesearchprocess, "Sustabdykite paieškos procesą");
	strcpy(sStrongoptimization, "Stiprus optimizavimas");
	strcpy(sSubtractthebandthicknessfrompiecesize, "Sumažinkite detalės dydį kraštinės juostos storiu");
	strcpy(sSummary, "Santrauka");
	strcpy(sSuprafataTotalaFolosita, "Bendras panaudotas paviršius");
	strcpy(sSuprafatautilizata, "Panaudojimas");
	strcpy(sSwitchbetweenfiberandrotationoption, "Perjunkite pluošto ir sukimosi parinktis.");
	strcpy(sTechnical, "Techninis");
	strcpy(sTechnicalsettings, "Techniniai parametrai");
	strcpy(sTemporaryPanelHint, "Laikinas skydas judančioms dalims tarp lakštų.");
	strcpy(sText, "Tekstas");
	strcpy(sThe_application_has_expired, "Programos galiojimo laikas pasibaigė.");
	strcpy(sThe_application_is_not_registered, "Programa neregistruota.");
	strcpy(sThe_application_was_first_started_on, "Pirmasis programos paleidimas");
	strcpy(sThecutsareperformedfromasidetotheothersideofthematerial, "Pjūviai yra daromi iš vienos pusės į kitą.");
	strcpy(sThecuttingmachinecanfollowtheshapeofthematerial, "Pjaustymo mašina gali sekti detalės formą.");
	strcpy(sTheedgesofsheetsthatmustbetrimedduefaults, "Lakštų kraštai, kuriuos reikia nupjauti dėl pažeidimų");
	strcpy(sTheLargestSize, "Didžiausias dydis");
	strcpy(sThenameofthecustomerforwhichyoucutthepiece, "Kliento, kuriam pjaustėte detalė, pavadinimas");
	strcpy(sThenameofyourcustomer, "Jūsų kliento pavadinimas");
	strcpy(sThepiececanberotated, "Detalę galima pasukti");
	strcpy(sTheprogramtriestoavoidwasteswhichhavebothsizeslessthanthisvalue, "Programa stengiasi išvengti už šią vertę mažesnių atliekų");
	strcpy(sThereAreNoProducts, "Dar nėra aprašytų produktų");
	strcpy(sThestockofmaterialhasbeenpreviouslyloadedfromanExcelorCSVformatPleaseloaditagain, "Medžiagos atsargos anksčiau buvo įkeltos iš „Excel“ arba CSV formato. Įkelkite jį dar kartą, jei norite su jomis dirbti.");
	strcpy(sThetotallengthofcutting, "Bendras pjovimo ilgis");
	strcpy(sThewidthofthecuttingsawForglasscuttingoptimizationitcanbe0Forwooditshouldbegreaterthan0, "Pjūklo storis. Stiklo pjaustymui jis gali būti 0. Medienos pjovimo atveju jis turėtų būti didesnis nei 0.");
	strcpy(sThewidthofthecuttingsawforlinearpieces, "Pjūklo storis linijiniams gabalams.");
	strcpy(sThickness, "Storis");
	strcpy(sThischaracterisusedforfillingthewasterectanglesIfyoudonotwantfilledwastejustremovethischaracter, "Šis simbolis naudojamas užpildyti atliekų stačiakampius. Jei nenorite užpildyti atliekų, tiesiog jį pašalinkite.");
	strcpy(sThisindexhasvaluebetween1andthenumberofpieces, "Šio indekso vertė yra nuo 1 iki detalių skaičiaus.");
	strcpy(sThisOptionWillOverrideTheInventoryFileIfLoadedFromExcelOrCsvFiles, "Ši pasirinkimas nepaisys inventoriaus failo, jei jis bus įkeltas iš „Excel“ arba CSV failų.");
	strcpy(sThisProgramisLicensedTo, "Ši programa licencijuota");
	strcpy(sThisvaluewillbeaddedtotheedgebandingmaterialoneachside, "Ši vertė bus pridėta prie kraštų juostų kiekvienoje pusėje");
	strcpy(sTipNevid, "Medžiagos rūšis negali būti tuščia.");
	strcpy(sTitle, "Pavadinimas");
	strcpy(sTools, "Įrankiai");
	strcpy(sTop, "Viršus");
	strcpy(sTopcoordinateofthedefect, "Viršutinė defekto koordinatė.");
	strcpy(sTotalGarbageWaste, "Visas išmestos atliekos");
	strcpy(sTotalInventoryWaste, "Bendros atliekų atsargos");
	strcpy(sTotalRecycledWaste, "Visos pakartotinai panaudotos atliekos");
	strcpy(sTotalusedarea, "Bendras panaudotas plotas");
	strcpy(sTotalusedlength, "Bendras panaudotas ilgis");
	strcpy(sTrigonometric, "Trigonometrinis");
	strcpy(sTrim, "Apipjaustyti");
	strcpy(sTrimalledgesatthebeginning, "Apipjaustykite visus kraštus pradžioje");
	strcpy(sTrimEdge, "Apipjaustykite kraštą");
	strcpy(sTwoPanels, "2 skydai");
	strcpy(sType, "Tipas");
	strcpy(sTypeofmaterialfromwhichtocut, "Medžiagos rūšis iš kurios reikia pjaustyti");
	strcpy(sTypesAreNotMatched, "Optimizavimas nebuvo atliktas! Medžiagos iš detalių ir atsargų lentelių nesutampa! Detalę galima pjauti tik iš to paties pavadinimo medžiagos, esančios sandėlyje. Pakeiskite medžiagos pavadinimą atitinkamuose stulpeliuose!");
	strcpy(sUndo, "Anuliuoti");
	strcpy(sUndoAccept, "Anuliuoti sutikimą");
	strcpy(sUnits, "vienetų");
	strcpy(sUnregisteredVersion, "Neregistruota");
	strcpy(sUpdates, "Atnaujinimai");
	strcpy(sUsefulforwoodfurniture, "Naudinga mediniams baldams");
	strcpy(sUseit, "Panaudok tai");
	strcpy(sUsePieceinOptimization, "Naudokite atlieką optimizuodami");
	strcpy(sUserName, "Vartotojo vardas");
	strcpy(sUtilizationandWastes, "Panaudojimas ir atliekos");
	strcpy(sUtilizedArea, "Panaudotų dalių plotas");
	strcpy(sUtilizedBars, "Panaudotos juostos");
	strcpy(sUtilizeddemandcount, "Panaudotų dalių skaičius");
	strcpy(sUtilizedParts, "Panaudotos dalys");
	strcpy(sUtilizedPieces, "Panaudotos detalės");
	strcpy(sUtilizedSheets, "Panaudoti lakštai");
	strcpy(sValue, "Vertė");
	strcpy(sValueGreaterEqualToZero, "Vertė turi būti didesnė ar lygi nuliui");
	strcpy(sValueGreaterThanZero, "Vertė turi būti didesnė už nulį");
	strcpy(sValueIntegerNumber, "Reikšmė turi būti sveikasis skaičius!");
	strcpy(sValueRealNumber, "Vertė turi būti tikras skaičius. Galbūt vietoj kablelio panaudojote tašką ar atvirkščiai. Pataisykite!");
	strcpy(s_The_number_is_too_big_or_it_has_too_many_digits_after_decimal_separator, "Skaičius yra per didelis arba jame yra per daug skaitmenų po kablelio!");
	strcpy(s_The_number_is_too_big, "Skaičius per didelis!");
	strcpy(sVertical, "Vertikalus");
	strcpy(sWaste, "Atliekos");
	strcpy(sWastes, "Atliekos");
	strcpy(sWasteAddedToWarehouse, "Atliekos pridėtos prie atsargų");
	strcpy(sWastelimits, "Atliekų diapazonas");
	strcpy(sWasteType, "Atliekų rūšis");
	strcpy(sWeakoptimization, "Silpniausias optimizavimas");
	strcpy(sWhattoprint, "Ką turėčiau spausdinti");
	strcpy(s_What_to_print_or_save_to_file, "Ką spausdinti arba išsaugoti faile");
	strcpy(sWhattoprintoneachpiece, "Ką atspausdinti ant kiekvienos detalės");
	strcpy(sWhattoshowoneachpiece, "Ką parodyti ant kiekvienos detalės?");
	strcpy(sWidth, "Plotis");
	strcpy(sWood, "mediena");
	strcpy(sWorkingDirectory, "Darbinis aplankas");
	strcpy(sWrongKey, "Neteisingas registracijos raktas!");
	strcpy(sYes, "Taip");
	strcpy(sYoucannotchooseblackblueorredcolors, "Negalite pasirinkti juodos, mėlynos ar raudonos spalvos.");
	strcpy(sYouCannotMixFractionalDataWithDecimalOnes, "Negalite maišyti trupmeninių verčių su tikromis vertėmis!");
	strcpy(sYourcompany, "Tavo įmonė");
	strcpy(sZip, "Pašto kodas");
	strcpy(s_Set_the_origin_and_the_direction_of_the_axes, "Nustatykite koordinačių ašių kilmę ir kryptį.");










	strcpy(s_Number_of_digits_after_the_decimal_separator, "Skaičių skaičius po dešimtainio skyriklio");
	strcpy(s_Percentages, "Procenti");
}

