// Language strings: Romanian
// Author: Optimal Programs
// License: MIT License
//---------------------------------------------------------------------------
#include <string.h>
//---------------------------------------------------------------------------
#include "language_string_id.h"
//---------------------------------------------------------------------------
void set_ro(void)
{
	//Romanian
	//OK
	// last update on: 2025.9.25.0
	strcpy(s_Area, "Aria");
	strcpy(s_Mass, "Masă");
	strcpy(s_Advanced, "Avansat");
	strcpy(s_Relative_coordinates, "Coordonatele relative");
	strcpy(s_Absolute_coordinates, "Coordonatele absolute");
	strcpy(s_Append_more_rows, "Adaugă mai multe rânduri");
	strcpy(s_Append_to_stock, "Adăugați la stoc");
	strcpy(s_Add_to_parts, "Adaugă la piese");
	strcpy(s_Additional, "Adiţional");
	strcpy(s_All_results, "Toate rezultatele.");
	strcpy(s_Allow_movement_of_pieces, "Permite mutarea pieselor");
	strcpy(s_Allow_part_in_part, "Permiteți piese în găurile altor piese");
	strcpy(s_Invalid_piece_Angles_are_too_small_or_too_big_or_height_is_too_small, "Piesă invalidă! Unghiurile sunt prea mici sau prea mari sau înălțimea este prea mică.");
	strcpy(s_Append, "Adăugă");
	strcpy(s_As_it_is, "Așa cum este");
	strcpy(s_As_text, "Ca și text");
	strcpy(s_Ascending, "Crescător");
	strcpy(s_Automatic, "Automat");
	strcpy(s_Cannot_connect_to_the_Internet_Please_visit_our_website_from_a_browser, "Nu se poate conecta la Internet! Vă rugăm să vizitați site-ul nostru web dintr-un browser.");
	strcpy(s_Cannot_copy_or_move_the_files, "Nu pot copia sau muta fișierele!");
	strcpy(s_Cannot_delete_the_file, "Nu se poate șterge fișierul!");
	strcpy(s_Cannot_modify_old_results, "Nu se pot modifica rezultatele vechi!");
	strcpy(s_To_change_click_inside_a_cell_or_press_0_1_or_2, "Pentru a modifica, faceți clic în interiorul unei celule sau apăsați 0, 1 sau 2.");
	strcpy(s_Cell, "Celulă");
	strcpy(s_Click_on_the_table_header_to_change_the_columns, "Faceți clic pe antetul tabelului pentru a schimba coloanele.");
	strcpy(s_Close, "Închide");
	strcpy(s_Contact_us, "Contactaţi-ne");
	strcpy(s_Column, "Coloana");
	strcpy(s_Comma, "Virgulă");
	strcpy(s_The_comma_symbol_cannot_simultaneously_be_the_list_separator_and_the_decimal_separator, "Simbolul virgulă nu poate fi simultan separatorul de listă și separatorul zecimal!");
	strcpy(s_Copy, "Copiază");
	strcpy(s_Copy_for_move, "Copiază pentru mutare");
	strcpy(s_Cut_higher_level_strips_first, "Debitează mai întâi benzile de nivel superior");
	strcpy(s_Cut_index, "Indice tăietură");

	strcpy(s_The_data_have_been_changed_Do_you_want_to_save_them_to_a_file, "Datele au fost modificate. Doriți să le salvați într-un fișier?");
	strcpy(s_Decimal_separator, "Separator zecimal");
	strcpy(s_Restore_default_settings, "Restabilește setările implicite");
	strcpy(s_Delete_fiber, "Șterge fibra");
	strcpy(s_Descending, "Descrescător");
	strcpy(s_Discard_changes, "Renunțați la modificări");

	strcpy(s_Delete_all_data, "Ștergeți toate datele?");
	strcpy(s_Dot, "Punct");
	strcpy(s_Do_you_want_to_delete_the_picture, "Doriți să ștergeți poza?");
	strcpy(s_Do_you_want_to_delete_the_product, "Doriți să ștergeți produsul?");
	strcpy(s_Duplicate_and_append, "Duplicați și adăugați.");
	strcpy(s_Duplicate_values_are_ignored, "Valorile duplicate au fost ignorate!");
	strcpy(s_Error, "Eroare");
	strcpy(s_Error_loading_file, "Eroare la încărcarea fișierului.");
	strcpy(s_export_everything, "Exportați totul");
	strcpy(s_Fit_to_screen, "Incadrează în ecran.");
	strcpy(s_Force_fixed_height, "Desenați piesele cu o înălțime fixă.");
	strcpy(s_Flipped, "Oglindit");
	strcpy(s_Import, "Importă");
	strcpy(s_If_angles_are_different_from_90_degrees_height_must_be_greater_than_0, "Dacă unghiurile sunt diferite de 90 de grade, înălțimea trebuie să fie mai mare decât 0.");
	strcpy(s_Ignore, "Ignoră");
	strcpy(s_Incorrect_value, "Valoare incorectă");
	strcpy(s_Info, "Info");
	strcpy(s_Interior, "Interior");
	strcpy(s_Give_a_name, "Dați un nume.");
	strcpy(s_Group, "Grupează");
	strcpy(s_Header, "Antet");
	strcpy(s_Keep_it_as_it_is, "Păstrează așa cum este");
	strcpy(s_Level, "Nivel");
	strcpy(s_Licensee, "Licențiat");
	strcpy(s_List_separator, "Separator de liste");
	strcpy(s_Made_with_love_in_Cugir_Romania, "Fabricat, cu dragoste, la Cugir, România");
	strcpy(s_Made_in, "Fabricat în");
	strcpy(s_Manufacturer, "Fabricant");

	strcpy(s_Manual_arrange, "Aranjare manuală");

	strcpy(s_Mixed, "Mixt");
	strcpy(s_Multiple_shapes_detected_Next_rows_will_be_overwritten_Continue, "Au fost detectate mai multe forme. Prin urmare, rândurile următoare vor fi suprascrise. Continua?");
	strcpy(s_More, "Mai mult");
	strcpy(s_Multiple_values, "Valori multiple");
	strcpy(s_No_texture, "Fără fibră");
	strcpy(s_Number, "Număr");
	strcpy(s_Number_of_images, "Numărul de imagini");
	strcpy(s_Number_of_vertices, "Număr de noduri");
	strcpy(s_Offset, "Deplasament");
	strcpy(s_Only_the_currently_selected_items, "Doar articolele selectate în prezent.");
	strcpy(s_Optimizing_please_wait, "Se optimizează... așteptați.");
	strcpy(s_part_number, "Part Number");
	strcpy(s_Paste, "Paste");
	strcpy(s_Paste_from_Clipboard, "Mută din Clipboard");
	strcpy(s_Piece_label, "Etichetă piesă");
	strcpy(s_Piece_size, "Dimensiunea pieselor");
	strcpy(s_Please_contact_us_by_email_if_you_receive_this_error, "Vă rugăm să ne contactați prin e-mail dacă primiți această eroare.");
	strcpy(s_Please_save_it_first, "Vă rog, salvați-l mai întâi.");
	strcpy(s_Position, "Poziția");
	strcpy(s_Preview, "Previzualizare");
	strcpy(s_Rectangle, "Dreptunghi");

	strcpy(s_Redo_the_last_operation, "Restaurați ultima operație");
	strcpy(s_Regular_polygon, "Poligon regulat");
	strcpy(s_Relative, "Relativ");
	strcpy(s_Reused, "Reutilizat");
	strcpy(s_Rotated, "Rotit");
	strcpy(s_Save_all, "Salvează tot");
	strcpy(s_Scrap_label, "Eticheta resturilor");
	strcpy(s_Scrap_size, "Dimensiunea resturilor");
	strcpy(s_Semicolon, "Punct şi virgulă");
	strcpy(s_Show_cut_index, "Arată indice tăietură");
	strcpy(s_Show_information, "Afișează informații");
	strcpy(s_Show_piece_label, "Arată etichetă piesă");
	strcpy(s_Show_scrap_label, "Arată eticheta deșeurilor");
	strcpy(s_Show_scrap_s_size_on_the_small_pieces, "Afișează dimensiunile resturilor mici");
	strcpy(s_Show_size_of_pieces, "Arata dimensiunea pieselor");
	strcpy(s_Show_size_of_scrap, "Arată dimensiunea resturilor");
	strcpy(s_Show_sizes, "Arată dimensiuni");
	strcpy(s_Show_label, "Afișați eticheta");
	strcpy(s_Show_length, "Arată lungimea");
	strcpy(s_Space, "Spațiu");
	strcpy(s_Some_numerical_values_are_incorrect_Should_I_fix_all_the_incorrect_values, "Unele valori numerice sunt incorecte! Ar trebui să repar toate valorile incorecte?");
	strcpy(s_Some_invalid_values_have_been_removed, "Unele valori nevalide au fost eliminate.");
	strcpy(s_Sort_by, "Sortează după");
	strcpy(s_Sort_ascending_by, "Sortează ascendent după");
	strcpy(s_Sort_descending_by, "Sortează descendent după");
	strcpy(s_Start, "Start");
	strcpy(s_Starting_angle, "Unghi de start");


	strcpy(s_Stock, "Magazie");
	strcpy(s_Stop, "Stop");
	strcpy(s_System_setting, "Setarea sistemului");
	strcpy(s_Tabular, "Tabelar");
	strcpy(s_Total, "Total");
	strcpy(s_Total_size, "Mărimea totală");
	strcpy(s_Terms_of_the_license, "Condițiile licenței");
	strcpy(s_The_current_product_has_been_changed_Do_you_want_to_save_it_to_file, "Produsul curent a fost modificat. Doriți să îl salvați în fișier?");
	strcpy(s_The_value_is_out_of_the_allowed_range, "Valoarea este în afara intervalului permis.");
	strcpy(s_The_value_must_be_a_real_or_fractional_number_Try_to_replace_the_comma_with_the_dot_if_you_want_to_enter_a_real_number, "Valoarea trebuie să fie un număr real sau fracțional. Încercați să înlocuiți virgula cu punctul dacă doriți să introduceți un număr real.");
	strcpy(s_This_feature_is_not_implemented_yet, "Această funcție nu este încă implementată.");
	strcpy(s_This_operation_cannot_be_reversed, "Această operațiune nu poate fi inversată.");
	strcpy(s_Undo_the_last_operation, "Anulați ultima operație.");
	strcpy(s_Utilization, "Utilizare");
	strcpy(s_Utilized_Stock, "Stoc utilizat");
	strcpy(s_Version, "Versiune");
	strcpy(s_Visible_columns, "Coloane vizibile");
	strcpy(s_You_already_have_the_latest_version_installed, "Aveți deja instalată cea mai recentă versiune!");
	strcpy(s_What_is_exported, "Ce se exportă?");
	strcpy(s0meansanynumberofpieces, "Zero înseamnă orice număr de bucăți");
	strcpy(sAbout, "Despre");
	strcpy(sAccept, "Acceptă");
	strcpy(sAcceptall, "Acceptă toate");
	strcpy(sAcceptthecurrentsolution, "Acceptă soluția curentă");
	strcpy(sAdd, "Adaugă");
	strcpy(sAddapiece, "Adaugă o bucată");
	strcpy(sAddasimpleproducttoDemand, "Adaugă un produs la comanda existentă.");
	strcpy(sAddgrindingthicknesstopartsize, "Adaugă grosime de șlefuire la dimensiunea piesei");
	strcpy(sAddproductnametolabel, "Adăugați numele produsului la etichetă");
	strcpy(sAddress, "Adresa");
	strcpy(sAddselectedsizetoInventory, "Adaugă dimensiunea selectată în magazie");
	strcpy(sAdhesivelabels, "Etichete adezive");
	strcpy(sAdhesivelabelwithinformationaboutpiecesinDemandCustomernameLabelSizeCurrentData, "Etichetă adezivă cu informații despre piesele comenzii: numele clientului, eticheta, dimensiuni, data curentă.");
	strcpy(sAdhesivelabelwithinformationaboutsheetsinInventory, "Etichetă adezivă cu informații despre colile din magazie.");
	strcpy(sAll, "Toate");
	strcpy(sAlloffcutswhichhavethesizegreaterthanthisvaluewillbeaddedtoInventory, "Toate rebuturilor care au dimensiunea mai mare decât această valoare vor fi adăugate la magazie.");
	strcpy(sAllowMirroring, "Permiteți oglindire");
	strcpy(sAllowRotation, "Permiteți rotire");
	strcpy(sAllPieces, "Toate piesele");
	strcpy(sAllpredefinedproducts, "Toate produsele predefinite");
	strcpy(sAnewwindowwillbedisplayedwheretheusercansettheedgebandsforeachedge, "O nouă fereastră va fi afișată, în care utilizatorul poate seta cantul pentru fiecare muchie.");
	strcpy(sAnewwindowwillbedisplayedwheretheusercansetthegrindingvalueforeachedgeofthsheet, "O nouă fereastră va fi afișată, în care utilizatorul poate seta valoarea de polizare pentru fiecare margine a piesei.");
	strcpy(sAnewwindowwillbedisplayedwheretheusercansetthetrimvalueforeachedgeofthsheet, "O nouă fereastră va fi afișată, în care utilizatorul poate seta defectele, pentru fiecare margine a piesei.");
	strcpy(sAngle, "Unghi");
	strcpy(sAngles, "Unghiuri");
	strcpy(sAnoptimizationparameterisarealnumber, "Un parametru de optimizare este un număr real.");
	strcpy(sAnoptimizationparameterisfractionalnumber, "Un parametru de optimizare este număr fracționar.");
	strcpy(sAnyShape, "Orice formă");
	strcpy(sApolygonmusthaveatleast2vertices, "Un poligon trebuie să aibă minim 2 vârfuri!");
	strcpy(sApolygonmusthaveatleast3vertices, "Un poligon trebuie să aibă minim 3 vârfuri!");
	strcpy(sApplication_fails_to_initialize, "Programul nu reușește să se inițializeze.");
	strcpy(sArc, "Arc");
	strcpy(sArcLength, "Lungimea arcului");
	strcpy(sAreaofusedsheets, "Aria colilor utilizate");
	strcpy(sAshortdescriptionofthesheet, "O scurtă descriere a colii");
	strcpy(sAtleastonepart, "Cel puțin o piesă trebuie introdusă.");
	strcpy(sAtTheMarginOfTheSheet, "La marginea colii");
	strcpy(sBandtypes, "Tipuri de cant");
	strcpy(sBar, "Bară");
	strcpy(sBars, "Bare");
	strcpy(sBothsizesoftheoffcutsmustbegreaterthanthisvalue, "Ambele dimensiuni ale resturilor trebuie să fie mai mari decât această valoare.");
	strcpy(sBottom, "Jos");
	strcpy(sBottomcoordinateofthedefect, "Coordonatele de jos a defectului");
	strcpy(sBreakCut, "Rupe tăietura");
	strcpy(sBrowse, "Caută");
	strcpy(sBuy, "Cumpără");
	strcpy(sBuynow, "Cumpără acum ...");
	strcpy(sCancel, "Anulează");
	strcpy(sCannotBeEmpty, "nu poate fi gol!");
	strcpy(sCannotmovepartsbetweensheetswhenidenticalsheetsaregroupedPleaseungroupthesheetsfrommenu, "Nu se pot muta piesele de la o foaie la alta în cazul în care foile identice sunt grupate. Vă rugăm să anulați gruparea foilor din meniul..");
	strcpy(sCannotSaveFile, "Nu se poate salva fișierul");
	strcpy(sCenter, "Centru");
	strcpy(s_Centering, "Centrare");
	strcpy(sChangeDirection, "Schimbă direcție tăietură");
	strcpy(sChoose, "Alege");
	strcpy(sChooseProduct, "Alege produse");
	strcpy(sCircle, "Cerc");
	strcpy(sCity, "Oraș");
	strcpy(sClear, "Golește");
	strcpy(sClockWise, "Sensul acelor de ceasornic");
	strcpy(sClosewindow, "Inchide fereastra");
	strcpy(sColor, "Culoare");
	strcpy(sColorofedgeband, "Culoarea cantului");
	strcpy(sColorPattern, "Culoare / model");
	strcpy(sColorpiecesandwastes, "Piese și deșeuri colorate");
	strcpy(sColumns, "Coloane");
	strcpy(sComment, "Comentariu");
	strcpy(sCompanyname, "Numele companiei");
	strcpy(sComplexMaterialExists, "Numele materialului este deja definit în lista de materiale complexe. Vă rugăm să dați un nume nou.");
	strcpy(sComputerCode, "Codul calculatorului");
	strcpy(sComputerCodefromyourcomputer, "Cod de calculator");
	strcpy(sComputethetotalpriceofDemand, "Calculați prețul total al comenzii");
	strcpy(sContents, "Conținut");
	strcpy(sContinutComanda, "Conținutul comenzii în data de");
	strcpy(sContinutDepozit, "Conținutul stocului în data de");
	strcpy(sConversionIsDoneOnlyWhenSomePiecesHaveFractionalValues, "Conversia se face numai atunci când unele piese au valori fracționare.");
	strcpy(sConvertsTheSizeOfWasteToAFractionalUnit, "Arată dimensiunea resturilor ca o valoare fracționară.");
	strcpy(sCouldNotSaveFile1, "Nu am putut scrie fișierul în directorul");
	strcpy(sCouldNotSaveFile2, "Este posibil să nu aveți destule drepturi de scriere. Vă rugăm să verificați sau să schimbați directorul de lucru din meniul Setări | Director de lucru la un folder în care aveți drept de scriere (de exemplu C:\\temp).");
	strcpy(sCreationdateYMDHMS, "Data creării (Y / M / D, H: M: S)");
	strcpy(sCurrentDate, "Data curentă");
	strcpy(sCurrentDiagram, "Diagrama curentă");
	strcpy(sCurrentMaterial, "Materialul actual");
	strcpy(sCurrentversion, "Versiunea curentă");
	strcpy(sCurve_not_closed_Try_increasing_DXF_linking_distance_parameter, "Poligon deschis. Incercați să creșteți distanța de legare a DXF.");
	strcpy(sCustomer, "Client");
	strcpy(sCustomerName, "Nume client");
	strcpy(sCustomMessage, "Mesaj personalizat");
	strcpy(sCutlength, "Lungimea tăieturilor");
	strcpy(sCut, "Tăietură");
	strcpy(sCuts, "Tăieturi");
	strcpy(sCutterThickness, "Grosimea lamei de tăiere");
	strcpy(sData, "Date");
	strcpy(sDataCannotBeEmpty, "Datele nu pot fi vide!");
	strcpy(sDateymdhms, "Data (a / l / z / h / m / s)");
	strcpy(sDays_left_for_trial, "Zile disponibile pentru testare ");
	strcpy(sDaysLeft, "zile rămase");
	strcpy(sStandard, "Implicit");
	strcpy(sDefaultInterface, "Interfață implicită");
	strcpy(sDefects, "Defecte");
	strcpy(sDefectsManager, "Administrează defecte");
	strcpy(sDefectsofthematerialNopiecescanbeplacedinthefaultyzone, "Defectele materialului. Piesele nu pot fi plasate în zona cu defect.");
	strcpy(sDelete, "Șterge");
	strcpy(sDeletePiece, "Ștergeți piesa");
	strcpy(sDeleteRow, "Șterge linie");
	strcpy(sDemandutilization, "Utilizarea comenzii");
	strcpy(sDepozitulmodificat, "Piesele utilizate au fost eliminate. Resturile au fost adăugate în magazie.");
	strcpy(sDepozitvid, "Stocul este gol");
	strcpy(sDesk, "birou");
	strcpy(sDiagram, "Diagramă");
	strcpy(sDiagrams, "Diagrame");
	strcpy(sDiagramasatable, "Diagrama ca un tabel");
	strcpy(sDigits, "cifre");
	strcpy(sDimensiuniplaca, "Dimensiunea piesei");
	strcpy(sDirection, "Direcție");
	strcpy(sDistanceBetweenRows, "Distanța între rânduri");
	strcpy(sDonotuseit, "Nu-l utilizați");
	strcpy(sDownload, "Descarcă");
	strcpy(sDoYouWantToClearTheData, "Doriți să ștergeți datele?");
	strcpy(sDoYouWantToSaveDemand, "Piesele au fost modificate! Doriți să salvați modificările?");
	strcpy(sDoYouWantToSaveParts, "Doriți să salvați piesele?");
	strcpy(sDoYouWantToSaveRepository, "Stocul a fost modificat! Doriți să salvați modificările?");
	strcpy(sDrawing, "Desen");
	strcpy(sDrawthesolutioncolorful, "Desenați soluția în culori");
	strcpy(sDuplicateTypes, "Unele tipuri sunt dublate! Vă rugăm să eliminați duplicatele.");
	strcpy(sDuplicateTypesWithComplex, "Unele nume de materiale există deja în lista de materiale complexe! Vă rugăm să eliminați dublurile");
	strcpy(sDuplicateValues, "Valori dublate");
	strcpy(sEdgeband, "Cant");
	strcpy(sEdgebandingwhichisplacedontheedgesofyourpiecePleasedefineedgebandingtypesfromMaterialsEdgeBandingmenu, "Aplicare cant. Vă rugăm să definiți tipurile de cant din meniul Materiale.");
	strcpy(sEdgebandsthatwillbeappliedtoeachpart, "Cantul aplicat pe fiecare piesă în parte.");
	strcpy(sEdgeBandTolerance, "Toleranță pentru cant");
	strcpy(sEdgesthatmustbecutduefaults, "Marginile care trebuie tăiate din cauza defectelor.");
	strcpy(sEdgetoedge, "De la o margine la alta");
	strcpy(sEdit, "Editează");
	strcpy(sEmail, "E-mail");
	strcpy(sEmptyData, "Datele sunt vide!");
	strcpy(sEnabled, "Activat");
	strcpy(sEnabledisabledefectsoftheinventorysheets, "Activare / dezactivare defecte ale stocului");
	strcpy(sEnterLabel, "Introduceți etichetă");
	strcpy(sEnterTheMaterialName, "Introduceți numele materialului");
	strcpy(sEnterTheProductName, "Introduceți numele produsului");
	strcpy(sEvaluationError, "Eroare la evaluarea expresiei!");
	strcpy(sExit, "Ieșire");
	strcpy(sExpired, "Programul a expirat! Vă rugăm să înregistrați programul!");
	strcpy(sExport, "Export");
	strcpy(sExportAllDiagrams, "Exportați toate diagramele");
	strcpy(sExportAllToASingleFile, "Exportați toate într-un singur fișier");
	strcpy(sExportOptions, "Opțiuni export");
	strcpy(sExporttoDXFformat, "Export în format DXF");
	strcpy(sExporttoExcel, "Export in Excel");
	strcpy(sExpresieIncorecta, "Expresie matematică incorectă!");
	strcpy(sExtensions, "Extensii");
	strcpy(sExtra, "Extra");
	strcpy(sExtraComponents, "Componente suplimentare");
	strcpy(sExtracomponentsattachedtoDemand, "Componente suplimentare atașate la comandă");
	strcpy(sFile, "Fișier");
	strcpy(sFileName, "Nume de fișier");
	strcpy(sFillWastes, "Desenați deșeuri cu linii oblice");
	strcpy(sFindoptimalbarsheetsize, "Găsiți dimensiunea optimă pentru țevi și coli.");
	strcpy(sFindoptimalsizeofInventorypieces, "Găsiți dimensiunea optimă a pieselor din magazie.");
	strcpy(sFirstcutMultiplestages, "Prima direcție de tăiere");
	strcpy(sFirstdirectionforcutishorizontal, "Prima direcție de tăiere este orizontală.");
	strcpy(sFirstdirectionforcutisvertical, "Prima direcție de tăiere este verticală.");
	strcpy(sFollowthecontourofpieces, "Urmează conturul pieselor");
	strcpy(sFont, "Font");
	strcpy(sFontsize, "Dimensiunea fontului");
	strcpy(sFullInfo, "Complete");
	strcpy(sDisposedWaste, "Deșeuri eliminate");
	strcpy(sGeneral, "General");
	strcpy(sGenerateCNC, "Generează CNC");
	strcpy(sGrain, "Fibră");
	strcpy(sGraindirection, "Direcția fibrei");
	strcpy(sGraphic, "Grafic");
	strcpy(sGreaterorequalto, "Mai mare sau egal cu");
	strcpy(sGrid, "Tabele");
	strcpy(sGrinding, "Polizare");
	strcpy(sGrosimeTaieturaScalata, "Grosimea tăieturii în această imagine ar putea fi diferită de cea reală, deoarece piesele nu sunt reprezentate la scara adevarată. Acest fapt nu afecteaza rezultatele!");
	strcpy(sGroupidenticallayouts, "Grupează colile identice");
	strcpy(sGroupIdenticalParts, "Grupează piese identice");
	strcpy(sGroupingOfIdenticalPiecesIntoOneRow, "Grupează părțile identice din comandă");
	strcpy(sGroupPartsAfterLoadingFromFile, "Grupare piese după încărcare din fișier");
	strcpy(sHeight, "Înălțime");
	strcpy(sHeighttolerance, "Toleranța pe înălțime");
	strcpy(sHelp, "Ajutor");
	strcpy(sHistory, "Istoric");
	strcpy(sHorizontal, "Orizontală");
	strcpy(sHowtodisplayprintedgebands, "Cum se afișează cantul?");
	strcpy(sIfyousetthebandforoneedgeallwillreceivethesamevalue, "Dacă setați cantul pentru o margine, toate celelalte margini vor primi aceeași valoare.");
	strcpy(sIfyousetthegrindingforoneedgeallwillreceivethesamevalue, "Dacă setați valoarea de șlefuire pentru o margine, toate marginile vor primi aceeași valoare.");
	strcpy(sIfyousetthetrimforoneedgeallwillreceivethesamevalue, "Dacă setați tundere pentru o margine, toate marginile vor primi aceeași valoare.");
	strcpy(sImageBounds, "Limite pentru dimensiune imagine");
	strcpy(sImageSize, "Dimensiunea imaginii");
	strcpy(sImportData, "Importă datele");
	strcpy(sIncorrectPassword, "Parola incorectă");
	strcpy(sIndex, "Index");
	strcpy(sInformationaboutcustomer, "Informații despre client");
	strcpy(sInputALanguageName, "Introduceți un nume de limbă");
	strcpy(sInsert, "Inserare");
	strcpy(sInsertPiece, "Inserează piesă");
	strcpy(sInterface, "Interfață");
	strcpy(sInterfaceSettings, "Setări interfață");
	strcpy(sInvalidHardware, "Nu am putut detecta hardware-ul. Vă rugăm să ne contactați la contact@optimalprograms.com");
	strcpy(sInvalidNumber, "Număr invalid");
	strcpy(sInvalidOrderOfComputation, "O ordine de calcul a dimensiunilor nu poate fi stabilită. Există relații circulare în definiția produsului!");
	strcpy(sInvalidRegistration, "Înregistrarea este invalidă!");
	strcpy(sInvalidTime, "Timpul sistemului este invalid!");
	strcpy(sInventory, "MAGAZIE");
	strcpy(sisafractionalvalue, "este o valoare fracționară.");
	strcpy(sIsArc, "Este arc");
	strcpy(sisarealvalue, "este o valoare reală.");
	strcpy(sLabel, "Etichetă");
	strcpy(sLabels, "Etichete");
	strcpy(sLanguage, "Limba");
	strcpy(sLatimeanumar0, "Lățimea trebuie să fie mai mare decât 0!");
	strcpy(sLatimeanumarreal, "Lățimea trebuie să fie un număr real!");
	strcpy(sLayerName, "Numele stratului");
	strcpy(sLeft, "Stânga");
	strcpy(sLeftcoordinateofthedefect, "Coordonatele din stânga ale defectului");
	strcpy(sLength, "Lungime");
	strcpy(sLengthofthepiecestocut, "Dimensiune piesă pentru debitat");
	strcpy(sLengthofthepiecestocutfrom, "Dimensiune coală pentru debitat");
	strcpy(sLengthofusedbars, "Dimensiunea barelor folosite");
	strcpy(sLicenseAgreement, "Acord de licență");
	strcpy(sLinear, "Linear");
	strcpy(sLinethickness, "Grosime linie desenare");
	strcpy(sLoadafileandappenddatatothecurrentDemand, "Încărcați un fișier și adăugați datele la comanda actuală.");
	strcpy(sLoadanexistingDemandfromafile, "Încarcați o comandă existentă dintr-un fișier.");
	strcpy(sLoadAppend, "Încărcați și adăugați");
	strcpy(sLoadEverything, "Încărcați totul");
	strcpy(sLoadInventory, "Încărcați stocul");
	strcpy(sLoadInventoryandDemand, "Încărcați magazia și comandă");
	strcpy(sLoadResults, "Încărcați rezultatele");
	strcpy(sLocked, "Blocat");
	strcpy(sLogo, "Logo");
	strcpy(sLong, "Lung");
	strcpy(sLongerexecutiontime, "Timp mare de rulare");
	strcpy(sLungime, "Lungime");
	strcpy(sLungimeanumar0, "Lungimea trebuie să fie mai mare decât 0!");
	strcpy(sLungimeanumarreal, "Lungimea trebuie să fie un număr real!");
	strcpy(sLungimeaTotalaFolosita, "Lungimea totală utilizată");
	strcpy(sMagnification, "Mărire");
	strcpy(sMagnify, "Mărește");
	strcpy(sMargins, "Margini");
	strcpy(sMarginsForPaper, "Margini pentru hârtie");
	strcpy(sMarginsOfTheLabel, "Marginile etichetei");
	strcpy(sMaterial, "Material");
	strcpy(sMaterialName, "Numele materialului");
	strcpy(sMaterials, "Materiale");
	strcpy(sMaterialstypes, "Tipuri de materiale");
	strcpy(sMax, "max");
	strcpy(sMaximalArea, "Arie maximă");
	strcpy(sMaximalCutLength, "Lungimea maximă de tăiere");
	strcpy(sMaxlength, "Lungime maximă");
	strcpy(sMaxPiecesperBar, "Număr maxim de piese pe bară");
	strcpy(sMaxwidth, "Lățime maximă");
	strcpy(sMeasurementUnit, "Unitatea de măsură");
	strcpy(sMin, "min");
	strcpy(sMinimalBreakSize, "Dimensiunea minimă de rupere");
	strcpy(sMinimalUsefulSize, "Dimensiunea minimă utilă");
	strcpy(sMinimalwastesizetoInventory, "Dimensiunea minimă a resturilor adăugate în magazie");
	strcpy(s_What_to_minimize, "Ce se minimizează?");
	strcpy(sMinlength, "Lungime minimă");
	strcpy(sMinwidth, "Lățime minimă");
	strcpy(sMirror, "Oglindire");
	strcpy(sMirroring, "Oglindire");
	strcpy(sMiscellaneous, "Diverse");
	strcpy(sModify, "Modifică");
	strcpy(sModifytheselectedpiece, "Modificare piesa selectată");
	strcpy(sMovePiece, "Mută piesa");
	strcpy(sMultiplestages, "Mai multe etape");
	strcpy(sName, "Nume");
	strcpy(sNameofedgeband, "Denumire cant");
	strcpy(sNewDEMANDUnsaveddatawillbelost, "Piese noi? Datele nesalvate se vor pierde!");
	strcpy(sNewLanguage, "Limbă nouă");
	strcpy(sNewMaterial, "Material nou");
	strcpy(sNewPasswordincorectlyintroduced, "Parola nouă introdusă incorect!");
	strcpy(sNewProduct, "Produs nou");
	strcpy(sNewversion, "Versiune nouă");
	strcpy(sNo, "Nu");
	strcpy(sNumarBucati, "Numărul de piese");
	strcpy(sNumberOfCopies, "Numărul de exemplare");
	strcpy(sNumberofstages, "Numărul de etape");
	strcpy(sNusuficienteplacidepozit, "Nu toate piesele au fost optimizate. Cauze posibile: Nu sunt destule piese în stoc, piesele nu sunt utilizate în optimizare; Materialele din comandă și stoc nu se potrivesc; Alți parametri au fost incorect setați.");
	strcpy(sOfficeNotInstaled, "Microsoft Office nu este instalat pe calculatorul dvs. sau o versiune incorectă este instalată!");
	strcpy(sOldpassworddoesnotmatch, "Parola veche nu se potrivește!");
	strcpy(sOnlinehelp, "Ajutor online");
	strcpy(sOnlypiecesofthesameheightinthelaststage, "Piese de aceeași înălțime în ultima etapă");
	strcpy(sOpen, "Deschide");
	strcpy(sOptimization, "Optimizare");
	strcpy(sOptimizationDone, "Optimizare efectuată! Puteți tipări sau salva diagramele obținute. Apăsați butonul Acceptă, dacă sunteți mulțumit de soluția actuală. În caz contrar, apăsați Start din nou.");
	strcpy(sOptimizationType, "Tip optimizare");
	strcpy(sOptions, "Opțiuni");
	strcpy(sOptionsrelatedtotheinterface, "Opțiuni referitoare la interfață");
	strcpy(sor, "sau");
	strcpy(sOthercomponents, "Alte componente");
	strcpy(sOthers, "Altele");
	strcpy(sOtherstatistics, "Alte statistici");
	strcpy(sOverrideExcelCSVfiles, "Suprascrie fișierele Excel / CSV");
	strcpy(sParameter, "Parametru");
	strcpy(sParts, "PIESE");
	strcpy(sPattern, "Model");
	strcpy(sPatternforwaste, "Model pentru deșeuri");
	strcpy(sPerimeter, "Perimetru");
	strcpy(sPermitedRotationAngle, "Unghiul de rotație permis");
	strcpy(sPhone, "Telefon");
	strcpy(sPicture, "Imagine");
	strcpy(sPiece, "Piesă");
	strcpy(sPieceindex, "Indexul piesei");
	strcpy(sPieces, "Piese");
	strcpy(sPiecesize, "Dimensiunea piesei");
	strcpy(sPiecesizelabeledgebandwillbeprinted, "Dimensiunea piesei, eticheta și cantul vor fi tipărite.");
	strcpy(sPierdere, "Resturi");
	strcpy(sPixels, "pixeli");
	strcpy(sPlacilefolositeDepozit, "Piesele folosite din magazie.");
	strcpy(sPlease_contact_us_at_contact_nestingtechnologies_com, "Vă rugăm să ne contactați la contact@nesting-technologies.com");
	strcpy(sPlease_contact_us_at_contact_optimalprograms_com, "Vă rugăm să ne contactați la contact@optimalprograms.com");
	strcpy(sPleaseenteralldataeitherasfractionalorrealDonotmixthem, "Vă rugăm să introduceți toate datele, fie numere fracționare fie numere reale. Nu le amestecați!");
	strcpy(sPleaseEnterSomeTypesOfMaterials, "Nu este nici un tip de material de definit. Le puteți defini din meniul Materiale.");
	strcpy(sPleasesendtheNameandtheCodetotheaddresscontactoptimalprogramscominordertoobtaintheRegistrationKey, "În scopul de a obtine cheia de inregistrare va rugam sa trimiteti numele si codul de: contact@optimalprograms.com.");
	strcpy(sPolygon, "Poligon");
	strcpy(sPolygonsCircles, "Poligoane, cercuri");
	strcpy(sPrecision, "Precizie");
	strcpy(sPretulnumar0, "Prețul trebuie să fie mai mare decât 0!");
	strcpy(sPretulnumarreal, "Prețul trebuie să fie un număr real!");
	strcpy(sPreview, "Previzualizare");
	strcpy(sPrice, "Preț");
	strcpy(sPriceMustBeGreaterThanZero, "Prețul trebuie să fie mai mare decât zero");
	strcpy(sPriceofbars, "Prețul barelor");
	strcpy(sPriceperbar, "Prețul pe bară");
	strcpy(sPricepersheet, "Preț pe coală");
	strcpy(sPricepersquareunitofmaterial, "Preț pe unitate pătrată de material.");
	strcpy(sPriceperunit, "Preț pe unitate");
	strcpy(sPrint, "Tipărește");
	strcpy(sPrintdiagramsastables, "Tipărește diagramele sub formă de tabele.");
	strcpy(sPrinter, "Imprimantă");
	strcpy(sPrinterBounds, "Margini pentru imprimantă");
	strcpy(sPrinting, "Tipărire");
	strcpy(sPrintonlyutilizedarea, "Tipărește numai aria utilizată");
	strcpy(sPrintthecontentsoftheDemand, "Tipărește conținutul comenzii.");
	strcpy(sPrintthecontentsoftheInventory, "Tipărește conținutul magaziei.");
	strcpy(sPrintthecurrentsolution, "Tipărește soluția curentă.");
	strcpy(sPriority, "Prioritate");
	strcpy(sPrioritytocutapieceZero0isthehighestpriority, "Prioritatea să se debiteze o piesă. Zero (0) este cea mai mare prioritate.");
	strcpy(sProcentul0100, "Procentele trebuie să fie mai mari decât 0 și mai mici sau egale cu 100!");
	strcpy(sProcentulnumarreal, "Procentul trebuie să fie un număr real!");
	strcpy(sProductdefinition, "Definiția produsului");
	strcpy(sProductExists, "Produsul există deja. Alegeți un alt nume.");
	strcpy(sProductName, "Numele produsului");
	strcpy(sProducts, "Produs");
	strcpy(sProducts, "Produse");
	strcpy(sProject, "Proiect");
	strcpy(sProperties, "Proprietăți");
	strcpy(sProperty, "Proprietate");
	strcpy(sQuantity, "Cantitate");
	strcpy(sQuantitynumberofsheetsofthistype, "Numărul de coli de acest tip");
	strcpy(sRadius, "Raza");
	strcpy(sRectangular, "Rectangular");
	strcpy(sRedefinetypesofedgeband, "Redefinire tipuri de cant");
	strcpy(sRedefinetypesofmaterial, "Redefinire tipuri de materiale");
	strcpy(sRegistration, "Înregistrare");
	strcpy(sRegistrationKeyfromOptimalPrograms, "Cheia de inregistrare");
	strcpy(sRegistrationSuccessful, "Înregistrare cu succes!");
	strcpy(sRemoveallpiecesinInventory, "Ștergeți toate piesele din Magazie.");
	strcpy(sRemoveCut, "Stergeți tăietura");
	strcpy(sRemovetheselectedpiece, "Stergeți piesa selectată");
	strcpy(sReports, "Rapoarte");
	strcpy(sRequestedMaterial, "Material solicitat");
	strcpy(sRestore, "Restabiliți");
	strcpy(sResults, "Rezultate");
	strcpy(sReusedwaste, "Resturi refolosite");
	strcpy(sRight, "Dreapta");
	strcpy(sRightcoordinateofthedefect, "Coordonatele din dreapta ale defectului");
	strcpy(sRotation, "Rotație");
	strcpy(sRotationAngle, "Unghiul de rotație");
	strcpy(sRotationStep, "Pas rotație");
	strcpy(sRoundAllFractionsTo, "Valorile fracționare trebuie să fie rotunjite la");
	strcpy(sRow, "Rând");
	strcpy(sRows, "Rânduri");
	strcpy(sRun, "Ultimele soluții");
	strcpy(sRunningtime, "Timp de optimizare");
	strcpy(sSameforall, "Aceeași pentru toate");
	strcpy(sSave, "Salvează");
	strcpy(sSaveAllImages, "Salvează toate imaginile");
	strcpy(sSaveAs, "Salvează ca");
	strcpy(sSaveChanges, "Datele au fost modificate. Doriți să salvați?");
	strcpy(sSaveCurrentImage, "Salvați imaginea curentă");
	strcpy(sSavedataparameters, "Salvați datele și parametrii");
	strcpy(sSaveEverything, "Salvați totul");
	strcpy(sSaveInventory, "Salvare stocuri");
	strcpy(sSaveInventoryandDemand, "Salvați Magazia și Comanda");
	strcpy(sSaveResults, "Salvați rezultatele");
	strcpy(sSaveStatisticsinafile, "Salvați statisticile într-un fișier");
	strcpy(sSavethecurrentimage, "Salvați imaginea curentă");
	strcpy(sSavethecurrentimageorstatistic, "Salvați imaginea curentă sau statistica");
	strcpy(sSavetheDEMANDinafile, "Salvați în fișier");
	strcpy(sSavetheDemandinafilewithadifferentname, "Salvați comanda într-un fișier cu un nume diferit.");
	strcpy(sSavetheREPOSITORYinafile, "Salvați magazia într-un fișier");
	strcpy(sSerialNumber, "Cheia de înregistrare");
	strcpy(sService, "Serviciu");
	strcpy(sSetDefaultValues, "Acest lucru va restabili toți parametrii la valorile lor implicite. Toate setările vor fi pierdute. Sunteți sigur că doriți să continuați?");
	strcpy(sSetedgeband, "Setați cantul");
	strcpy(sSetedgetrim, "Setați curățirea pentru defecte ale marginilor");
	strcpy(sSetthesameedgebandforalledges, "Setați același cant pentru toate marginile");
	strcpy(sSetthesamegrindingforalledges, "Setați aceeași șlefuire pentru toate marginile");
	strcpy(sSetthesametrimforalledges, "Setați curățirea defectelor la fel pentru toate marginile");
	strcpy(sSettings, "Setări");
	strcpy(sShape, "Formă");
	strcpy(sSheet, "Foaie");
	strcpy(sSheetsBarstypes, "Tipuri coli_țevi");
	strcpy(sSheetSize, "Dimensiune coală");
	strcpy(sSheetsperPage, "Foi pe pagină");
	strcpy(sShort, "Scurt");
	strcpy(sShorterexecutiontime, "Timp scurt de rulare");
	strcpy(sShowallsimpleproducts, "Afișare produsele simple");
	strcpy(sShowcustomername, "Afișare nume client");
	strcpy(sShowCustomTextOnEachPiece, "Afișare text personalizat pe fiecare bucată");
	strcpy(sShowdiagramasatable, "Afișare diagramă ca tabel");
	strcpy(sShowedgeband, "Arată cant");
	strcpy(sShowedgebandssettinginanewwindow, "Arată setările de cant într-o fereastră nouă");
	strcpy(sShowgrindingsettingsinanewwindow, "Afișează setările de rectificat într-o fereastră nouă");
	strcpy(sShowHorizontalLabelsAlways, "Arată etichetele întotdeauna orizontal");
	strcpy(sShowRemovethesizeofthepiecesinthecurrentsolution, "Arată / ascunde dimensiunea pieselor din soluția curentă.");
	strcpy(sShowRemovethesizeofthewastesinthecurrentsolution, "Arată / ascunde dimensiunea deșeurilor din soluția curentă.");
	strcpy(sShowtotalcutlength, "Arată lungime totală tăieturi");
	strcpy(sShowtrimedgesettingsinanewwindow, "Arată setările defectelor într-o fereastră nouă");
	strcpy(sSimpleMaterialExists, "Numele materialului este deja definit în lista de materiale. Vă rugăm să dați un nume nou.");
	strcpy(sSinglePieceStrips, "Benzi dintr-o singură piesă");
	strcpy(sSizes, "Dimensiuni");
	strcpy(sSmallerorequalto, "Mai mic sau egal cu");
	strcpy(sSort, "Sortare");
	strcpy(sSortAscendingByArea, "Sorteaza crescător după arie");
	strcpy(sSortDescendingByArea, "Sortează descrescător după arie");
	strcpy(sSpecifyhowdifferentthepiecesinthelaststagecanbeValue0meansnodifference, "Specificați cât de diferită pot fi piesele din ultima etapă. Valoarea 0 înseamnă că nici o diferență nu este permisă.");
	strcpy(sSpecifyifpiecesinthelaststagecanbedifferentornotdepeultimaetapapotfidiferitesaunucadimensiune, "Specificați dacă piesele din ultima etapă pot fi diferite sau nu");
	strcpy(sSpecifyifthepiececanberotatedornotIfnotitwillbecutinthesamewayasitwasintroducedinDemandLengthofthepieceparalleltothelengthofthesheet, "Specificați dacă piesa poate fi rotită sau nu. Dacă nu, va fi tăiată în același mod cum a fost introdusă în comandă (lungimea piesei paralelă cu lungimea colii).");
	strcpy(sSpecifyinhowmanystageswemakethecutsDuringastageallcutshavethesamedirection, "Precizați, în câte etape se vor face tăierile.");
	strcpy(sStartthesearchprocess, "Începeți procesul de căutare");
	strcpy(sStatistics, "Statistici");
	strcpy(sStatisticsE, "Rapoarte suplimentare");
	strcpy(sStatisticsforeachtypeofmaterial, "Statistici pentru fiecare tip de material");
	strcpy(sStep, "Pas");
	strcpy(sStergeDepozit, "Doriți sa ștergeți Magazia?");
	strcpy(sStergeMaterial, "Stergeți materialul?");
	strcpy(sStergePiesele, "Doriți să ștergeți piesa?");
	strcpy(sStergePiesa, "Doriți să ștergeți piesa?");
	strcpy(sStopthesearchprocess, "Oprește procesul de căutare");
	strcpy(sStrongoptimization, "Optimizare puternică");
	strcpy(sSubtractthebandthicknessfrompiecesize, "Scade grosimea cantului din dimensiunea piesei");
	strcpy(sSummary, "Sumar");
	strcpy(sSuprafataTotalaFolosita, "Suprafață totală utilizată");
	strcpy(sSuprafatautilizata, "Utilizare");
	strcpy(sSwitchbetweenfiberandrotationoption, "Comută între fibre și opțiunea de rotație.");
	strcpy(sTechnical, "Tehnic");
	strcpy(sTechnicalsettings, "Setări tehnice");
	strcpy(sTemporaryPanelHint, "Panou temporar pentru piesele în mișcare între coli.");
	strcpy(sText, "Text");
	strcpy(sThe_application_has_expired, "Programul a expirat.");
	strcpy(sThe_application_is_not_registered, "Programul nu este înregistrat.");
	strcpy(sThe_application_was_first_started_on, "Programul a fost pornit prima dată în ");
	strcpy(sThecutsareperformedfromasidetotheothersideofthematerial, "Debitarile sunt efectuate dintr-o parte în cealaltă a materialului.");
	strcpy(sThecuttingmachinecanfollowtheshapeofthematerial, "Mașina de debitat poate urmări forma piesei.");
	strcpy(sTheedgesofsheetsthatmustbetrimedduefaults, "Marginile de coli care trebuie să fie curățate din cauza defectelor");
	strcpy(sTheLargestSize, "Cea mai mare dimensiune");
	strcpy(sThenameofthecustomerforwhichyoucutthepiece, "Numele de client pentru care ați debitat piesa.");
	strcpy(sThenameofyourcustomer, "Numele clientului");
	strcpy(sThepiececanberotated, "Piesa poate fi rotită");
	strcpy(sTheprogramtriestoavoidwasteswhichhavebothsizeslessthanthisvalue, "Programul încearcă să evite deșeuri, care au ambele dimensiuni mai mici decât această valoare");
	strcpy(sThereAreNoProducts, "Nu sunt produse definite încă");
	strcpy(sThestockofmaterialhasbeenpreviouslyloadedfromanExcelorCSVformatPleaseloaditagain, "Stocul de material a fost încărcat anterior dintr-un format Excel sau CSV. Vă rugăm să-l încărcați din nou, în cazul în care doriți să lucrați pe el.");
	strcpy(sThetotallengthofcutting, "Lungime totală a tăieturilor");
	strcpy(sThewidthofthecuttingsawForglasscuttingoptimizationitcanbe0Forwooditshouldbegreaterthan0, "Grosimea de tăiere. Pentru tăiere sticlă poate fi 0. Pentru lemn ar trebui să fie mai mare decât 0.");
	strcpy(sThewidthofthecuttingsawforlinearpieces, "Grosime de debitare pentru piese liniare.");
	strcpy(sThickness, "Grosime");
	strcpy(sThischaracterisusedforfillingthewasterectanglesIfyoudonotwantfilledwastejustremovethischaracter, "Acest simbol este folosit pentru umplerea dreptunghiurile de deșeuri. Dacă nu doriți hașurarea deșeurilor eliminați-l.");
	strcpy(sThisindexhasvaluebetween1andthenumberofpieces, "Acest indice are o valoare între 1 și numărul de piese.");
	strcpy(sThisOptionWillOverrideTheInventoryFileIfLoadedFromExcelOrCsvFiles, "Această opțiune va înlocui magazia daca se încarcă din fișiere Excel sau CSV.");
	strcpy(sThisProgramisLicensedTo, "Acest program este licențiat lui");
	strcpy(sThisvaluewillbeaddedtotheedgebandingmaterialoneachside, "Această valoare va fi adaugată la cantul pe fiecare latură.");
	strcpy(sTipNevid, "Tipul de material nu poate fi vid.");
	strcpy(sTitle, "Titlu");
	strcpy(sTools, "Unelte");
	strcpy(sTop, "Sus");
	strcpy(sTopcoordinateofthedefect, "Coordonatele de sus ale defectului.");
	strcpy(sTotalGarbageWaste, "Toate deșeurile aruncate");
	strcpy(sTotalInventoryWaste, "Stocul total de deșeuri");
	strcpy(sTotalRecycledWaste, "Toate resturile refolosite");
	strcpy(sTotalusedarea, "Aria totală folosită");
	strcpy(sTotalusedlength, "Lungimea totală folosită");
	strcpy(sTrigonometric, "Trigonometrice");
	strcpy(sTrim, "Curăță margini");
	strcpy(sTrimalledgesatthebeginning, "Curățați toate marginile de la început");
	strcpy(sTrimEdge, "Curătați marginea");
	strcpy(sTwoPanels, "2 panouri");
	strcpy(sType, "Tip");
	strcpy(sTypeofmaterialfromwhichtocut, "Tipul de material din care se debitează");
	strcpy(sTypesAreNotMatched, "Optimizarea nu a fost efectuată! Materialele din tabelele de piese și stoc nu se potrivesc! Se poate tăia o piesă doar din materialul cu același nume din stoc. Schimbați numele materialelor din coloanele corespunzătoare!");
	strcpy(sUndo, "Anulează");
	strcpy(sUndoAccept, "Anulare Acceptă");
	strcpy(sUnits, "de unități");
	strcpy(sUnregisteredVersion, "Neînregistrat");
	strcpy(sUpdates, "Actualizări");
	strcpy(sUsefulforwoodfurniture, "Utile pentru debitări din lemn");
	strcpy(sUseit, "Folosit");
	strcpy(sUsePieceinOptimization, "Utilizare piesă în optimizare");
	strcpy(sUserName, "Nume utilizator");
	strcpy(sUtilizationandWastes, "Utilizare și deșeuri");
	strcpy(sUtilizedArea, "Aria pieselor utilizate");
	strcpy(sUtilizedBars, "Bare utilizate");
	strcpy(sUtilizeddemandcount, "Numărul pieselor utilizate");
	strcpy(sUtilizedParts, "Piese utilizate");
	strcpy(sUtilizedPieces, "Piesele utilizate");
	strcpy(sUtilizedSheets, "Foi utilizate");
	strcpy(sValue, "Valoare");
	strcpy(sValueGreaterEqualToZero, "Valoarea trebuie să fie mai mare sau egală cu zero");
	strcpy(sValueGreaterThanZero, "Valoarea trebuie să fie mai mare decât zero");
	strcpy(sValueIntegerNumber, "Valoarea trebuie să fie un număr întreg!");
	strcpy(sValueRealNumber, "Valoarea trebuie să fie un număr real. Poate că ați folosit , in loc de . sau viceversa. Vă rugăm să modificați!");
	strcpy(s_The_number_is_too_big_or_it_has_too_many_digits_after_decimal_separator, "Numărul este prea mare sau are prea multe cifre după separatorul zecimal!");
	strcpy(s_The_number_is_too_big, "Numărul este prea mare!");
	strcpy(sVertical, "Vertical");
	strcpy(sWaste, "Rest");
	strcpy(sWastes, "Resturi");
	strcpy(sWasteAddedToWarehouse, "Resturi de adăugat la depozit");
	strcpy(sWastelimits, "Limitele pentru resturi");
	strcpy(sWasteType, "Tip de resturi");
	strcpy(sWeakoptimization, "Optimizare slabă");
	strcpy(sWhattoprint, "Ce ar trebui să se tipărească");
	strcpy(s_What_to_print_or_save_to_file, "Ce să imprimați sau să salvați în fișier");
	strcpy(sWhattoprintoneachpiece, "Ce se tipărește pe fiecare piesă");
	strcpy(sWhattoshowoneachpiece, "Ce se afișeză pe fiecare piesă?");
	strcpy(sWidth, "Lăţime");
	strcpy(sWood, "lemn");
	strcpy(sWorkingDirectory, "Directorul de lucru");
	strcpy(sWrongKey, "Cheie de înregistrare greșită!");
	strcpy(sYes, "Da");
	strcpy(sYoucannotchooseblackblueorredcolors, "Nu puteți alege culorile negru, roșu și albastru.");
	strcpy(sYouCannotMixFractionalDataWithDecimalOnes, "Nu puteți amesteca valori fracționare cu valori reale!");
	strcpy(sYourcompany, "Compania dvs.");
	strcpy(sZip, "Cod poștal");
	strcpy(s_Set_the_origin_and_the_direction_of_the_axes, "Setați originea și direcția axelor de coordonate.");
	strcpy(s_license_agreement_text, "Programul este oferit așa cum este în versiunea de încercare care se poate descărca de pe site-ul nostru.\nVă rugăm încercați toate funcționalitățile înainte de achiziție!\nLicența, pentru versiunea curentă (achiziționată), este pe viață.\nProgramul se poate instala pe un număr de calculatoare egal cu numărul de licențe achiziționate.\nProgramul nu poate fi utilizat de mai multe persoane în același timp.\nDacă se dorește mutarea programului pe un alt calculator, atunci acesta trebuie șters de pe calculatorul curent.\nVersiunile viitoare nu sunt incluse in preț.\nNu se garantează funcționarea programului pe orice calculator. Vă rugăm să testați înainte de achiziție.\nNu se oferă servicii conexe (instalare, configurare, devirusare calculator etc).\nNu se garantează optimizare perfectă în toate cazurile.\nEventualele probleme se pot semnala doar prin email. Nu se oferă suport prin telefon, fax, teamviewer, la sediul clientului etc.");









	strcpy(s_Number_of_digits_after_the_decimal_separator, "Numărul de cifre după separatorul zecimal");
	strcpy(s_Percentages, "Procente");
}

