// Language strings: Estonian
// Author: Optimal Programs
// License: MIT License
//---------------------------------------------------------------------------
#include <string.h>
//---------------------------------------------------------------------------
#include "language_string_id.h"
//---------------------------------------------------------------------------
void set_et(void)
{
	//Estonian
	//did not check manually
	// last update on: 2025.9.25.0
	strcpy(s_Area, "Pindala");
	strcpy(s_Mass, "mass");
	strcpy(s_Advanced, "Täpsemalt");
	strcpy(s_Relative_coordinates, "Suhtelised koordinaadid");
	strcpy(s_Absolute_coordinates, "Absoluutsed koordinaadid");
	strcpy(s_Append_more_rows, "Lisage rohkem ridu");

	strcpy(s_Add_to_parts, "Lisage osadele.");
	strcpy(s_Additional, "Lisaks");
	strcpy(s_All_results, "Kõik tulemused.");
	strcpy(s_Allow_movement_of_pieces, "Luba tükkide liikumist");
	strcpy(s_Allow_part_in_part, "Luba tükk tükki");
	strcpy(s_Invalid_piece_Angles_are_too_small_or_too_big_or_height_is_too_small, "Vigane tükk! Nurgad on liiga väikesed või liiga suured või kõrgus on liiga väike.");
	strcpy(s_Append, "Lisage");
	strcpy(s_As_it_is, "Nagu praegu");
	strcpy(s_As_text, "Tekstina");
	strcpy(s_Ascending, "Tõusev");
	strcpy(s_Automatic, "Automaatne");
	strcpy(s_Cannot_connect_to_the_Internet_Please_visit_our_website_from_a_browser, "Interneti-ühendust ei saa luua! Külastage brauseri kaudu meie veebisaiti.");
	strcpy(s_Cannot_copy_or_move_the_files, "Faile ei saa kopeerida ega teisaldada!");
	strcpy(s_Cannot_delete_the_file, "Faili ei saa kustutada!");
	strcpy(s_Cannot_modify_old_results, "Vanu tulemusi ei saa muuta!");
	strcpy(s_To_change_click_inside_a_cell_or_press_0_1_or_2, "Muutmiseks klõpsake lahtris või vajutage 0, 1 või 2.");
	strcpy(s_Cell, "Kamber");
	strcpy(s_Click_on_the_table_header_to_change_the_columns, "Veergude muutmiseks klõpsake tabeli päisel.");
	strcpy(s_Close, "Sulge see");
	strcpy(s_Contact_us, "Võta meiega ühendust");
	strcpy(s_Column, "Veerg");
	strcpy(s_Comma, "Koma");
	strcpy(s_The_comma_symbol_cannot_simultaneously_be_the_list_separator_and_the_decimal_separator, "Koma ei saa samaaegselt olla nii loendi eraldajaks kui ka kümnendkoha eraldajaks!");
	strcpy(s_Copy, "Kopeeri");
	strcpy(s_Copy_for_move, "Kopeeri liikumiseks");
	strcpy(s_Cut_higher_level_strips_first, "Kõigepealt lõigake kõrgema taseme ribad");
	strcpy(s_Cut_index, "Näita indeks lõikamine");

	strcpy(s_The_data_have_been_changed_Do_you_want_to_save_them_to_a_file, "Andmeid on muudetud. Kas soovite need faili salvestada?");
	strcpy(s_Decimal_separator, "Kümnendkoha eraldaja");
	strcpy(s_Restore_default_settings, "Taasta vaikesätted");
	strcpy(s_Delete_fiber, "Kustutage kiud");
	strcpy(s_Descending, "Laskudes");
	strcpy(s_Discard_changes, "Loobu muudatustest");

	strcpy(s_Delete_all_data, "Kas kustutada kõik andmed?");
	strcpy(s_Dot, "Punkt");
	strcpy(s_Do_you_want_to_delete_the_picture, "Kas soovite pildi kustutada?");
	strcpy(s_Do_you_want_to_delete_the_product, "Kas soovite toote kustutada?");
	strcpy(s_Duplicate_and_append, "Kopeeri ja lisa.");
	strcpy(s_Duplicate_values_are_ignored, "Korduvaid väärtusi eirati!");
	strcpy(s_Error, "Viga");
	strcpy(s_Error_loading_file, "Viga faili laadimisel.");
	strcpy(s_export_everything, "Ekspordi kõik");
	strcpy(s_Fit_to_screen, "Sobib ekraanile.");
	strcpy(s_Force_fixed_height, "Joonistage fikseeritud kõrgusega tükid.");
	strcpy(s_Flipped, "Pööratud");
	strcpy(s_Import, "Import");
	strcpy(s_If_angles_are_different_from_90_degrees_height_must_be_greater_than_0, "Kui nurgad erinevad 90 kraadist, peab kõrgus olema suurem kui 0.");
	strcpy(s_Ignore, "Ignoreeri");
	strcpy(s_Incorrect_value, "Vale väärtus");
	strcpy(s_Info, "Info");
	strcpy(s_Interior, "Sees");
	strcpy(s_Give_a_name, "Pange nimi.");
	strcpy(s_Group, "Rühmitage see");
	strcpy(s_Header, "Päis");
	strcpy(s_Keep_it_as_it_is, "Hoidke seda sellisena, nagu ta on");
	strcpy(s_Level, "Level");
	strcpy(s_Licensee, "Litsentsisaaja");
	strcpy(s_List_separator, "Loendi eraldaja");
	strcpy(s_Made_with_love_in_Cugir_Romania, "Valmistatud armastusega, asukohas: Cugir, Rumeenia");
	strcpy(s_Made_in, "Toodetud aastal");
	strcpy(s_Manufacturer, "Tootja");

	strcpy(s_Manual_arrange, "Käsitsi korraldamine");

	strcpy(s_Mixed, "Segatud");
	strcpy(s_Multiple_shapes_detected_Next_rows_will_be_overwritten_Continue, "Tuvastati rohkem kui üks kuju. Seetõttu kirjutatakse järgmised read üle. Kas jätkata?");
	strcpy(s_More, "Rohkem");
	strcpy(s_Multiple_values, "Mitu väärtust");
	strcpy(s_No_texture, "Tekstuuri pole");
	strcpy(s_Number, "Arv");
	strcpy(s_Number_of_images, "Piltide arv");
	strcpy(s_Number_of_vertices, "Tippude arv");
	strcpy(s_Offset, "Nihe");
	strcpy(s_Only_the_currently_selected_items, "Ainult hetkel valitud üksused.");
	strcpy(s_Optimizing_please_wait, "Optimeerimine ... palun oodake.");

	strcpy(s_Paste, "Paste");

	strcpy(s_Piece_label, "Näita tükk etikett");
	strcpy(s_Piece_size, "Näita suurus tükki");
	strcpy(s_Please_contact_us_by_email_if_you_receive_this_error, "Selle vea korral võtke meiega ühendust e-posti teel.");
	strcpy(s_Please_save_it_first, "Palun salvestage see kõigepealt.");
	strcpy(s_Position, "Positsioon");
	strcpy(s_Preview, "Eelvaade");
	strcpy(s_Rectangle, "Ristkülik");

	strcpy(s_Redo_the_last_operation, "Taastage viimane toiming");
	strcpy(s_Regular_polygon, "Regulaarne hulknurk");

	strcpy(s_Reused, "Taaskasutatud");
	strcpy(s_Rotated, "Pööratud");
	strcpy(s_Save_all, "Salvesta kõik");
	strcpy(s_Scrap_label, "Näita jäätmete etikett");
	strcpy(s_Scrap_size, "Näita suurus jäätmed");
	strcpy(s_Semicolon, "Semikoolon");
	strcpy(s_Show_cut_index, "Näita indeks lõikamine");
	strcpy(s_Show_information, "Näita teavet");
	strcpy(s_Show_piece_label, "Näita tükk etikett");
	strcpy(s_Show_scrap_label, "Näita jäätmete etikett");
	strcpy(s_Show_scrap_s_size_on_the_small_pieces, "Näita jääkide suurust väikeste tükkidena");
	strcpy(s_Show_size_of_pieces, "Näita suurus tükki");
	strcpy(s_Show_size_of_scrap, "Näita suurus jäätmed");
	strcpy(s_Show_sizes, "Näita suurusi");
	strcpy(s_Show_label, "Kuva silt");
	strcpy(s_Show_length, "Näita pikkust");

	strcpy(s_Some_numerical_values_are_incorrect_Should_I_fix_all_the_incorrect_values, "Mõned arvväärtused on valed! Kas peaksin parandama kõik valed väärtused?");
	strcpy(s_Some_invalid_values_have_been_removed, "Mõned kehtetud väärtused on eemaldatud.");
	strcpy(s_Sort_by, "Sorteerima");
	strcpy(s_Sort_ascending_by, "Sorteeri kasvavalt");
	strcpy(s_Sort_descending_by, "Sorteeri kahanevalt");
	strcpy(s_Start, "Start");
	strcpy(s_Starting_angle, "Stardinurk");


	strcpy(s_Stock, "Ladu");
	strcpy(s_Stop, "Stop");
	strcpy(s_System_setting, "Süsteemi seadistus");
	strcpy(s_Tabular, "Tabelikujuline");
	strcpy(s_Total, "Kokku");
	strcpy(s_Total_size, "Kogu suurus");
	strcpy(s_Terms_of_the_license, "Litsentsi tingimused");
	strcpy(s_The_current_product_has_been_changed_Do_you_want_to_save_it_to_file, "Praegune toode on muudetud. Kas soovite selle faili salvestada?");
	strcpy(s_The_value_is_out_of_the_allowed_range, "Väärtus on väljaspool lubatud vahemikku.");
	strcpy(s_The_value_must_be_a_real_or_fractional_number_Try_to_replace_the_comma_with_the_dot_if_you_want_to_enter_a_real_number, "Väärtus peab olema tegelik või murdarv. Kui soovite sisestada pärisnumbri, proovige koma asendada punktiga.");
	strcpy(s_This_feature_is_not_implemented_yet, "Seda funktsiooni pole veel rakendatud.");
	strcpy(s_This_operation_cannot_be_reversed, "Seda toimingut ei saa tagasi pöörata.");
	strcpy(s_Undo_the_last_operation, "Tühistage viimane toiming.");
	strcpy(s_Utilization, "Kasutamine");
	strcpy(s_Utilized_Stock, "Kasutatud varu");
	strcpy(s_Version, "Versioon");
	strcpy(s_Visible_columns, "Nähtavad veerud");
	strcpy(s_You_already_have_the_latest_version_installed, "Teil on juba uusim versioon installitud!");
	strcpy(s_What_is_exported, "Mida eksporditakse?");
	strcpy(s0meansanynumberofpieces, "Null tähendab tükkide arv");
	strcpy(sAbout, "Umbes");
	strcpy(sAccept, "Vastu võtma");
	strcpy(sAcceptall, "Aktsepteerima kõik");
	strcpy(sAcceptthecurrentsolution, "Nõus praegune lahendus");
	strcpy(sAdd, "Lisa");
	strcpy(sAddapiece, "Lisa tükk");
	strcpy(sAddasimpleproducttoDemand, "Lisa toode olemasolevat nõudlust.");
	strcpy(sAddgrindingthicknesstopartsize, "Lisa lihvimine paksus tükk suurus");
	strcpy(sAddproductnametolabel, "Lisada toote nime silt");
	strcpy(sAddress, "Aadress");
	strcpy(sAddselectedsizetoInventory, "Lisa valitud suurus Inventory");
	strcpy(sAdhesivelabels, "Isekleepuvaid etikette");
	strcpy(sAdhesivelabelwithinformationaboutpiecesinDemandCustomernameLabelSizeCurrentData, "Isekleepuvat teavet tükki Demand: Kliendi nimi, Label Size jooksvad andmed.");
	strcpy(sAdhesivelabelwithinformationaboutsheetsinInventory, "Isekleepuvat teavet lehed Inventory.");
	strcpy(sAll, "Kõik");
	strcpy(sAlloffcutswhichhavethesizegreaterthanthisvaluewillbeaddedtoInventory, "Kõik lõikejääkide mis on suurem kui see väärtus lisandub Inventory");
	strcpy(sAllowMirroring, "Laske peegeldamine.");
	strcpy(sAllowRotation, "Luba pööramine");
	strcpy(sAllPieces, "Kõik nupud");
	strcpy(sAllpredefinedproducts, "Kõik eelnevalt tooteid");
	strcpy(sAnewwindowwillbedisplayedwheretheusercansettheedgebandsforeachedge, "uues aknas kuvatakse kus kasutaja saab määrata kindlaks sagedusalad, igast servast.");
	strcpy(sAnewwindowwillbedisplayedwheretheusercansetthegrindingvalueforeachedgeofthsheet, "uues aknas kuvatakse kus kasutaja saab määrata lihvimine väärtus iga serva tükk.");
	strcpy(sAnewwindowwillbedisplayedwheretheusercansetthetrimvalueforeachedgeofthsheet, "uues aknas kuvatakse kus kasutaja saab määrata vead iga serva tükk.");
	strcpy(sAngle, "Nurk");
	strcpy(sAngles, "Nurk");
	strcpy(sAnoptimizationparameterisarealnumber, "optimeerimine parameeter on reaalne number.");
	strcpy(sAnoptimizationparameterisfractionalnumber, "optimeerimine parameeter on murdarv.");
	strcpy(sAnyShape, "Mis tahes kuju");
	strcpy(sApolygonmusthaveatleast2vertices, "Polügoonil peab olema vähemalt 2 tippu!");
	strcpy(sApolygonmusthaveatleast2vertices, "Polügoonil peab olema vähemalt 3 tippu!");
	strcpy(sApplication_fails_to_initialize, "Tarkvara ebaõnnestunud ettekanne.");
	strcpy(sArc, "Arc");
	strcpy(sArcLength, "Kaare pikkus");
	strcpy(sAreaofusedsheets, "Ala, mida kasutatakse lehed");
	strcpy(sAshortdescriptionofthesheet, "Lühikirjeldus lehed");
	strcpy(sAtleastonepart, "Vähemalt ühes tükis tuleb ette.");
	strcpy(sAtTheMarginOfTheSheet, "Servas lehe");
	strcpy(sBandtypes, "Tüübid serva bänd.");
	strcpy(sBar, "Vardad / torud");
	strcpy(sBars, "Vardad / torud");
	strcpy(sBothsizesoftheoffcutsmustbegreaterthanthisvalue, "Mõlemad suurused lõikejääkide peab olema suurem kui see väärtus.");
	strcpy(sBottom, "Põhi");
	strcpy(sBottomcoordinateofthedefect, "Alt koordinaat viga");
	strcpy(sBreakCut, "Murda lõigatud");
	strcpy(sBrowse, "sirvima");
	strcpy(sBuy, "Ostma");
	strcpy(sBuynow, "Osta kohe ...");
	strcpy(sCancel, "Tühistada");
	strcpy(sCannotBeEmpty, "ei saa olla tühi!");
	strcpy(sCannotmovepartsbetweensheetswhenidenticalsheetsaregroupedPleaseungroupthesheetsfrommenu, "Ei saa liigutada osad ühest lehest teise kui identne lehed on grupeeritud. Palun tühistage rühmituse lehed menüü.");
	strcpy(sCannotSaveFile, "Ei saa salvestada faili");
	strcpy(sCenter, "Center");

	strcpy(sChangeDirection, "Muuda suunda");
	strcpy(sChoose, "Valima");
	strcpy(sChooseProduct, "Vali toode");
	strcpy(sCircle, "Circle");
	strcpy(sCity, "Linn");
	strcpy(sClear, "Kustuta");
	strcpy(sClockWise, "Päripäeva");
	strcpy(sClosewindow, "Sulge aken");
	strcpy(sColor, "Värv");
	strcpy(sColorofedgeband, "Värvi serv bänd");
	strcpy(sColorPattern, "Värv / muster");
	strcpy(sColorpiecesandwastes, "Tükid ja jäätmed värvikas.");
	strcpy(sColumns, "Veerud");
	strcpy(sComment, "Kommentaar");
	strcpy(sCompanyname, "Firma nimi");
	strcpy(sComplexMaterialExists, "Nimi materjali on juba määratletud nimekirja keerulisi materjale. Palun anna uus nimi.");
	strcpy(sComputerCode, "Arvuti kood");
	strcpy(sComputerCodefromyourcomputer, "Arvuti kood (arvuti)");
	strcpy(sComputethetotalpriceofDemand, "Arvuta hind kokku Demand");
	strcpy(sContents, "Sisu");
	strcpy(sContinutComanda, "Sisu nõudluse kuupäev");
	strcpy(sContinutDepozit, "Sisu Inventari kuupäev");
	strcpy(sConversionIsDoneOnlyWhenSomePiecesHaveFractionalValues, "Tulemus on tehtud alles siis, kui mõni nupp on murdarvud.");
	strcpy(sConvertsTheSizeOfWasteToAFractionalUnit, "Näitab suurus jäätmete murdosa väärtus.");
	strcpy(sCouldNotSaveFile1, "Ei saa kirjutada faili kataloogis");
	strcpy(sCouldNotSaveFile2, "Sa ei pruugi olla piisavalt õigusi. Palun kontrollige või muutke töökataloogi menüüst Settings | Töö kataloogi kausta, kus teil on õigus kirjutada (näiteks c:\\temp).");
	strcpy(sCreationdateYMDHMS, "Loomise kuupäev (Y / M / D, H: M: S)");
	strcpy(sCurrentDate, "Praegune kuupäev");
	strcpy(sCurrentDiagram, "Praegune diagramm");
	strcpy(sCurrentMaterial, "Praegune materja");
	strcpy(sCurrentversion, "Praegune versioon");
	strcpy(sCurve_not_closed_Try_increasing_DXF_linking_distance_parameter, "Polügoon pole suletud! Proovige suurendada parameetrit DXF-i ühendamiskaugus.");
	strcpy(sCustomer, "Klient");
	strcpy(sCustomerName, "Kliendi nimi");
	strcpy(sCustomMessage, "Kohandatud sõnum");
	strcpy(sCutlength, "Pikkus lõigatud");
	strcpy(sCut, "Lõika");
	strcpy(sCuts, "Jaotustükid");
	strcpy(sCutterThickness, "Lõikamine paksus");
	strcpy(sData, "Andmed");
	strcpy(sDataCannotBeEmpty, "Andmed ei tohi olla tühjad!");
	strcpy(sDateymdhms, "Kuupäev (y / m / d / h / m / s)");
	strcpy(sDays_left_for_trial, "Päeva testimiseks kättesaadav ");
	strcpy(sDaysLeft, "päeva jäänud");
	strcpy(sStandard, "Vaikimisi");
	strcpy(sDefaultInterface, "vaikimisi Interface");
	strcpy(sDefects, "Defektide");
	strcpy(sDefectsManager, "Hallata vigu");
	strcpy(sDefectsofthematerialNopiecescanbeplacedinthefaultyzone, "Defekte materjali. Ei tükki saab panna vigase tsooni.");
	strcpy(sDelete, "Kustutama");
	strcpy(sDeletePiece, "Kustuta tükk");
	strcpy(sDeleteRow, "rea kustutamine");
	strcpy(sDemandutilization, "Kasutamise nõudlus");
	strcpy(sDepozitulmodificat, "Kasutatud tükid on eemaldatud. Jäänused on lisatud stock.");
	strcpy(sDepozitvid, "Varu on tühi");
	strcpy(sDesk, "kirjutuslaud");
	strcpy(sDiagram, "Diagramm");
	strcpy(sDiagrams, "Skeemid");
	strcpy(sDiagramasatable, "Skeem kui laud");
	strcpy(sDigits, "numbrit");
	strcpy(sDimensiuniplaca, "Suurus leht");
	strcpy(sDirection, "Suund");
	strcpy(sDistanceBetweenRows, "Ridade vahekaugus");
	strcpy(sDonotuseit, "Ärge kasutage seda");
	strcpy(sDownload, "Lae alla");
	strcpy(sDoYouWantToClearTheData, "Soovite kustutada andmed?");
	strcpy(sDoYouWantToSaveDemand, "Osad on muutunud! Sa tahad salvestada muudatused?");
	strcpy(sDoYouWantToSaveParts, "Kas soovite salvestada osad?");
	strcpy(sDoYouWantToSaveRepository, "Varu on muutunud! Sa tahad salvestada muudatused?");
	strcpy(sDrawing, "joonised");
	strcpy(sDrawthesolutioncolorful, "Tõmmake lahus värvikas");
	strcpy(sDuplicateTypes, "Mõned liigid on dubleeritud! Palun eemaldada duplikaadid");
	strcpy(sDuplicateTypesWithComplex, "Mõned nimed materjalid on juba olemas nimekiri keeruline tüüpi! Palun eemaldada duplikaadid");
	strcpy(sDuplicateValues, "Dubleeritud väärtused");
	strcpy(sEdgeband, "Lint servi");
	strcpy(sEdgebandingwhichisplacedontheedgesofyourpiecePleasedefineedgebandingtypesfromMaterialsEdgeBandingmenu, "Edge banding, mis asetatakse serva oma tükk. Palun määrata serv banding tüüpi materjalidest menüü.");
	strcpy(sEdgebandsthatwillbeappliedtoeachpart, "Edge bändid, mida kohaldatakse iga osa.");
	strcpy(sEdgeBandTolerance, "Sallivus serv banding");
	strcpy(sEdgesthatmustbecutduefaults, "Servad, et tuleb lõigata tingitud vigu.");
	strcpy(sEdgetoedge, "Äärest ääreni");
	strcpy(sEdit, "Muuda");
	strcpy(sEmail, "E-mail");
	strcpy(sEmptyData, "Andmed on tühi!");
	strcpy(sEnabled, "Lubatud");
	strcpy(sEnabledisabledefectsoftheinventorysheets, "Võimalda / blokeeri vead börsi");
	strcpy(sEnterLabel, "Sisend etikett");
	strcpy(sEnterTheMaterialName, "Sisesta nimi materjali");
	strcpy(sEnterTheProductName, "Sisestage toote nimetus");
	strcpy(sEvaluationError, "Viga tuua hindamine!");
	strcpy(sExit, "Väljapääs");
	strcpy(sExpired, "Tarkvara on aegunud! Palun registreeri tarkvara!");
	strcpy(sExport, "Eksport");
	strcpy(sExportAllDiagrams, "Ekspordi kõik diagrammid");
	strcpy(sExportAllToASingleFile, "Ekspordi kõik ühte faili");
	strcpy(sExportOptions, "Ekspordi võimalusi.");
	strcpy(sExporttoDXFformat, "Ekspordi DXF formaadis");
	strcpy(sExporttoExcel, "Eksportida Excel");
	strcpy(sExpresieIncorecta, "Vale matemaatiline väljendus!");
	strcpy(sExtensions, "Laiendused");
	strcpy(sExtra, "Extra");
	strcpy(sExtraComponents, "Extra komponendid");
	strcpy(sExtracomponentsattachedtoDemand, "Extra komponentide külge osad");
	strcpy(sFile, "Fai");
	strcpy(sFileName, "Faili nimi");
	strcpy(sFillWastes, "Joonista jäätmete kaldus jooned");
	strcpy(sFindoptimalbarsheetsize, "Leia optimaalne suurus torud ja lehed.");
	strcpy(sFindoptimalsizeofInventorypieces, "Leia optimaalne suurus aktsia tükki");
	strcpy(sFirstcutMultiplestages, "Esimene lõikamine suunas - Mitu etappi");
	strcpy(sFirstdirectionforcutishorizontal, "Esimene suund cut on horisontaalne.");
	strcpy(sFirstdirectionforcutisvertical, "Esimene suund cut on vertikaalne.");
	strcpy(sFollowthecontourofpieces, "Järgige kontuuri tükki");
	strcpy(sFont, "Font");
	strcpy(sFontsize, "Fondi suurus");
	strcpy(sFullInfo, "Täielik teave");
	strcpy(sDisposedWaste, "Kõrvaldatud jäätmed");
	strcpy(sGeneral, "peasekretär");
	strcpy(sGenerateCNC, "Loo CNC");
	strcpy(sGrain, "Tekstuur");
	strcpy(sGraindirection, "Kiudude suund");
	strcpy(sGraphic, "Graafiline");
	strcpy(sGreaterorequalto, "Suurem või võrdne");
	strcpy(sGrid, "Tabelid ");
	strcpy(sGrinding, "lihvimise paksus");
	strcpy(sGrosimeTaieturaScalata, "Cut paksus see pilt võib olla erinev reaalne, sest tükid ei esinda nende tegeliku ulatuse. See asjaolu ei mõjuta tulemusi.");
	strcpy(sGroupidenticallayouts, "Rühmitamine identsed lehed");
	strcpy(sGroupIdenticalParts, "Identsete osadega grupeeritud.");
	strcpy(sGroupingOfIdenticalPiecesIntoOneRow, "Rühmitamine identne tükki ühte ritta.");
	strcpy(sGroupPartsAfterLoadingFromFile, "Rühmitamine osad pärast laadimist faili");
	strcpy(sHeight, "Kõrgus");
	strcpy(sHeighttolerance, "Tolerance kõrguse");
	strcpy(sHelp, "Aitama");
	strcpy(sHistory, "Ajalugu");
	strcpy(sHorizontal, "Horisontaalne");
	strcpy(sHowtodisplayprintedgebands, "Kuidas see näitab serva paelte?");
	strcpy(sIfyousetthebandforoneedgeallwillreceivethesamevalue, "Kui seate sagedusala 1 serva, kõik saavad sama väärtusega.");
	strcpy(sIfyousetthegrindingforoneedgeallwillreceivethesamevalue, "Kui seate lihvimine raha ühest servast, kõik servad saavad sama väärtusega.");
	strcpy(sIfyousetthetrimforoneedgeallwillreceivethesamevalue, "Kui seate korrastamist ühe serva, kõik servad saavad sama väärtusega.");
	strcpy(sImageBounds, "Piire kujutise");
	strcpy(sImageSize, "Pildi suurus");
	strcpy(sImportData, "Impordi andmed");
	strcpy(sIncorrectPassword, "Vale paroo");
	strcpy(sIndex, "Indeks");
	strcpy(sInformationaboutcustomer, "Teavet kliendi");
	strcpy(sInputALanguageName, "Nimi anda kee");
	strcpy(sInsert, "Lisa");
	strcpy(sInsertPiece, "Sisestage tükk");
	strcpy(sInterface, "Interface");
	strcpy(sInterfaceSettings, "Interface seaded");
	strcpy(sInvalidHardware, "Ma ei suutnud tuvastada riistvara. Palun võtke meiega contact@optimalprograms.com");
	strcpy(sInvalidNumber, "Vale number");
	strcpy(sInvalidOrderOfComputation, "Et arvuti pikkusega ei saa kehtestada. On ümmarguse suhted toote määratluse!");
	strcpy(sInvalidRegistration, "Registreerimine on kehtetu!");
	strcpy(sInvalidTime, "Ajal teie süsteem on vigane.");
	strcpy(sInventory, "LADU");
	strcpy(sisafractionalvalue, "on murdosa väärtus.");
	strcpy(sIsArc, "Kas kaar");
	strcpy(sisarealvalue, "on tõeline väärtus.");
	strcpy(sLabel, "Etikett");
	strcpy(sLabels, "Labels");
	strcpy(sLanguage, "Kee");
	strcpy(sLatimeanumar0, "Laius peab olema suurem kui 0!");
	strcpy(sLatimeanumarreal, "Laius peab olema tegelik number!");
	strcpy(sLayerName, "Kihi nimi");
	strcpy(sLeft, "Vasak");
	strcpy(sLeftcoordinateofthedefect, "Vasakul koordinaat viga");
	strcpy(sLength, "Pikkus");
	strcpy(sLengthofthepiecestocut, "Tükk suurus lõikamiseks");
	strcpy(sLengthofthepiecestocutfrom, "Sheet suurus lõikamiseks");
	strcpy(sLengthofusedbars, "Suurust kasutada baarid");
	strcpy(sLicenseAgreement, "litsentsileping");
	strcpy(sLinear, "Linear");
	strcpy(sLinethickness, "Paksus pen");
	strcpy(sLoadafileandappenddatatothecurrentDemand, "Laadige fail ning lisada andmeid jooksva nõudluse.");
	strcpy(sLoadanexistingDemandfromafile, "Laadi olemasolevat nõudlust failist.");
	strcpy(sLoadAppend, "Load ja lisab");
	strcpy(sLoadEverything, "Laadi kõik");
	strcpy(sLoadInventory, "Laadi börsi");
	strcpy(sLoadInventoryandDemand, "Laadi varude ja nõudluse");
	strcpy(sLoadResults, "Laadi tulemused");
	strcpy(sLocked, "Kinni");
	strcpy(sLogo, "logo");
	strcpy(sLong, "Long");
	strcpy(sLongerexecutiontime, "Pikemad tegemise aeg");
	strcpy(sLungime, "Laius");
	strcpy(sLungimeanumar0, "Pikkus peab olema suurem kui 0!");
	strcpy(sLungimeanumarreal, "Pikkus peab olema tegelik number!");
	strcpy(sLungimeaTotalaFolosita, "Kokku kasutati pikkus");
	strcpy(sMagnification, "Suurendus");
	strcpy(sMagnify, "Liialdama");
	strcpy(sMargins, "Veerised");
	strcpy(sMarginsForPaper, "Marginaalid paber");
	strcpy(sMarginsOfTheLabel, "Veerised märgistuse");
	strcpy(sMaterial, "Materja");
	strcpy(sMaterialName, "Nimi materjali");
	strcpy(sMaterials, "Materjalid");
	strcpy(sMaterialstypes, "Materjalide liigid");
	strcpy(sMax, "Max");
	strcpy(sMaximalArea, "Maksimaalne ala");
	strcpy(sMaximalCutLength, "Maximal lõigatud pikkus");
	strcpy(sMaxlength, "Maksimaalne pikkus");
	strcpy(sMaxPiecesperBar, "Max Tükki Bar");
	strcpy(sMaxwidth, "Maksimaalne laius.");
	strcpy(sMeasurementUnit, "Mõõtühik");
	strcpy(sMin, "minu");
	strcpy(sMinimalBreakSize, "Minimaalne rebeneda suurus");
	strcpy(sMinimalUsefulSize, "Minimaalne vajalik maht");
	strcpy(sMinimalwastesizetoInventory, "Minimaalset jäätmete suurus Inventory");
	strcpy(s_What_to_minimize, "Mida minimeerida?");
	strcpy(sMinlength, "Minimaalne pikkus");
	strcpy(sMinwidth, "Minimaalne laius");
	strcpy(sMirror, "Peege");
	strcpy(sMirroring, "Peegeldamist");
	strcpy(sMiscellaneous, "Muu");
	strcpy(sModify, "Muutma");
	strcpy(sModifytheselectedpiece, "Muuda valitud nupuga");
	strcpy(sMovePiece, "Liiguta tükk.");
	strcpy(sMultiplestages, "Mitu etappi");
	strcpy(sName, "Nimi");
	strcpy(sNameofedgeband, "Nimi serva paelte");
	strcpy(sNewDEMANDUnsaveddatawillbelost, "Uusi osi? Salvestamata andmed lähevad kaduma!");
	strcpy(sNewLanguage, "Uus kee");
	strcpy(sNewMaterial, "Uus materja");
	strcpy(sNewPasswordincorectlyintroduced, "Uus parool valesti sisse!");
	strcpy(sNewProduct, "Uus toode");
	strcpy(sNewversion, "Uus versioon");
	strcpy(sNo, "Ei");
	strcpy(sNumarBucati, "Arv tükkides");
	strcpy(sNumberOfCopies, "Koopiate arvu");
	strcpy(sNumberofstages, "Mitmes etapis");
	strcpy(sNusuficienteplacidepozit, "Mitte kõik tükid on optimeeritud. Võimalikud põhjused: ei ole piisavalt tükki laos; Tükk ei ole kasutatud optimeerimine; Materjalid nõudluse ja laoseisu ei ole vastavuses; Muud näitajad on valesti seatud.");
	strcpy(sOfficeNotInstaled, "Microsoft Office ei ole installitud arvutisse või incorect versioon on installitud!");
	strcpy(sOldpassworddoesnotmatch, "Vana parool ei sobi!");
	strcpy(sOnlinehelp, "Online help");
	strcpy(sOnlypiecesofthesameheightinthelaststage, "Tükki samal kõrgusel viimases staadiumis.");
	strcpy(sOpen, "Avatud");
	strcpy(sOptimization, "Optimeerimine");
	strcpy(sOptimizationDone, "Optimeerimise läbi! Sa võid printida või salvestada saadud diagrammid. Vajutage nuppu Accept, kui olete rahul praeguse lahenduse. Vastasel juhul vajutage uuesti alustada.");
	strcpy(sOptimizationType, "Optimeerimine Type");
	strcpy(sOptions, "Valikud");
	strcpy(sOptionsrelatedtotheinterface, "Valikud, mis on seotud liidese");
	strcpy(sor, "või");
	strcpy(sOthercomponents, "Muud osad");
	strcpy(sOthers, "Teised");
	strcpy(sOtherstatistics, "Muu statistika");
	strcpy(sOverrideExcelCSVfiles, "Alistamine Excel / CSV failid");
	strcpy(sParameter, "Parameeter");
	strcpy(sParts, "PARTS");
	strcpy(sPattern, "Muster");
	strcpy(sPatternforwaste, "Muster jäätmete");
	strcpy(sPerimeter, "Perimeeter");
	strcpy(sPermitedRotationAngle, "Pöördenurk, mis on lubatud.");
	strcpy(sPhone, "Telefon");
	strcpy(sPicture, "Pilt");
	strcpy(sPiece, "Tükk");
	strcpy(sPieceindex, "Tükk indeks");
	strcpy(sPieces, "Tükke");
	strcpy(sPiecesize, "Tükk suurus");
	strcpy(sPiecesizelabeledgebandwillbeprinted, "Tükk suurus, etikett, serva paelte trükitakse.");
	strcpy(sPierdere, "Jäätmed");
	strcpy(sPixels, "pixels");
	strcpy(sPlacilefolositeDepozit, "Kasutatud tükki Inventory.");
	strcpy(sPlease_contact_us_at_contact_nestingtechnologies_com, "Palun võtke meiega contact@nesting-technologies.com");
	strcpy(sPlease_contact_us_at_contact_optimalprograms_com, "Palun võtke meiega contact@optimalprograms.com");
	strcpy(sPleaseenteralldataeitherasfractionalorrealDonotmixthem, "Palun sisesta andmed kas osaliseks või reaalne! Ärge segage neid!");
	strcpy(sPleaseEnterSomeTypesOfMaterials, "Ei ole materjali liik määratlemata. Võite määratleda need materjalid menüü.");
	strcpy(sPleasesendtheNameandtheCodetotheaddresscontactoptimalprogramscominordertoobtaintheRegistrationKey, "Et saada Registreerimine Key saatke nimi ja kood on: contact@optimalprograms.com.");
	strcpy(sPolygon, "Polygon");
	strcpy(sPolygonsCircles, "Polügoonid, ringid");
	strcpy(sPrecision, "Täpsus");
	strcpy(sPretulnumar0, "Hind peab olema suurem kui 0!");
	strcpy(sPretulnumarreal, "Hind peab olema tegelik number!");
	strcpy(sPreview, "Eelvaade");
	strcpy(sPrice, "Hind");
	strcpy(sPriceMustBeGreaterThanZero, "Hind peab olema suurem kui nul");
	strcpy(sPriceofbars, "Hind baarid");
	strcpy(sPriceperbar, "Hind inimese baar");
	strcpy(sPricepersheet, "Hind per sheet");
	strcpy(sPricepersquareunitofmaterial, "Hind ruutmeetri ühiku kohta materjali.");
	strcpy(sPriceperunit, "Hind ühiku kohta");
	strcpy(sPriceperunit, "Hind ühiku kohta");
	strcpy(sPrint, "Prindi");
	strcpy(sPrintdiagramsastables, "Prindi diagrammide vormis tabeleid.");
	strcpy(sPrinter, "Printer");
	strcpy(sPrinterBounds, "Marginaalid printer");
	strcpy(sPrintonlyutilizedarea, "Trüki ainult kasutamata maad");
	strcpy(sPrintthecontentsoftheDemand, "Prindi sisu Demand.");
	strcpy(sPrintthecontentsoftheInventory, "Prindi sisu stock.");
	strcpy(sPrintthecurrentsolution, "Prindi praegune lahendus.");
	strcpy(sPriority, "Prioriteet");
	strcpy(sPrioritytocutapieceZero0isthehighestpriority, "Prioriteet lõigatud tükk. Zero (0) on kõrgeim prioriteet.");
	strcpy(sProcentul0100, "Protsent peab olema suurem kui 0 ja väiksem või võrdne 100!");
	strcpy(sProcentulnumarreal, "Protsent peab olema tegelik number!");
	strcpy(sProductdefinition, "Toote määratlemine");
	strcpy(sProductExists, "Toode on juba olemas. Vali teine ??nimi.");
	strcpy(sProductName, "Toote nimi");
	strcpy(sProducts, "Toote");
	strcpy(sProducts, "Tooted");
	strcpy(sProject, "Projekt");
	strcpy(sProperties, "omadused");
	strcpy(sProperty, "kinnisvara");
	strcpy(sQuantity, "Kogus");
	strcpy(sQuantitynumberofsheetsofthistype, "Lehtede arv seda tüüpi");
	strcpy(sRadius, "Raadiuses");
	strcpy(sRectangular, "ristkülik");
	strcpy(sRedefinetypesofedgeband, "Uuesti tüüpi äär bänd");
	strcpy(sRedefinetypesofmaterial, "Uuesti tüüpi materjali");
	strcpy(sRegistration, "Registreerimine");
	strcpy(sRegistrationKeyfromOptimalPrograms, "Registreerimine Key");
	strcpy(sRegistrationSuccessful, "Registreerimine õnnestus!");
	strcpy(sRemoveallpiecesinInventory, "Eemalda kõik tükid Inventory.");
	strcpy(sRemoveCut, "Kustuta lõigatud");
	strcpy(sRemovetheselectedpiece, "Eemalda valitud nupuga");
	strcpy(sReports, "Aruanded");
	strcpy(sRequestedMaterial, "Soovitud Materia");
	strcpy(sRestore, "Taastama");
	strcpy(sResults, "Tulemused");
	strcpy(sReusedwaste, "Taaskasutada jäätmeid");
	strcpy(sRight, "Parem");
	strcpy(sRightcoordinateofthedefect, "Koordinaadid defekt paremalt");
	strcpy(sRotation, "Pööramine");
	strcpy(sRotationAngle, "Pöördenurk.");
	strcpy(sRotationStep, "Rotation samm");
	strcpy(sRoundAllFractionsTo, "Osaline väärtused tuleb ümardada");
	strcpy(sRow, "rida");
	strcpy(sRows, "Rida");
	strcpy(sRun, "Viimased lahendused");
	strcpy(sRunningtime, "Etenduse kestus");
	strcpy(sSameforall, "Sama kõigi");
	strcpy(sSave, "Välja arvatud");
	strcpy(sSaveAllImages, "Salvesta kõik pildid");
	strcpy(sSaveAs, "Salvesta");
	strcpy(sSaveChanges, "Nõudlus on muutunud. Kas soovite salvestada?");
	strcpy(sSaveCurrentImage, "Salvesta Current Image");
	strcpy(sSavedataparameters, "Salvesta andmed ja parameetrid");
	strcpy(sSaveEverything, "Salvesta kõik");
	strcpy(sSaveInventory, "Salvesta Inventory");
	strcpy(sSaveInventoryandDemand, "Salvesta Inventory ja nõudluse");
	strcpy(sSaveResults, "Save Results");
	strcpy(sSaveStatisticsinafile, "Salvesta statistika faili");
	strcpy(sSavethecurrentimage, "Salvestada pildi");
	strcpy(sSavethecurrentimageorstatistic, "Salvestada pildi ja statistika");
	strcpy(sSavetheDEMANDinafile, "Salvesta faili");
	strcpy(sSavetheDemandinafilewithadifferentname, "Salvesta nõudluse faili nimi.");
	strcpy(sSavetheREPOSITORYinafile, "Salvesta hoidla faili");
	strcpy(sSerialNumber, "Registreerimise võti");
	strcpy(sService, "teenus");
	strcpy(sSetDefaultValues, "See taastab kõik parameetrid algsed. Kõik sinu sätted lähevad kaduma. Oled sa kindel, et soovid seda teha?");
	strcpy(sSetedgeband, "Määra serva bänd");
	strcpy(sSetedgetrim, "Seadke lõikamise jaoks vead servi");
	strcpy(sSetthesameedgebandforalledges, "Määrata sama serv sagedusala kõik servad");
	strcpy(sSetthesamegrindingforalledges, "Määrake sama jahvatamise kõik servad.");
	strcpy(sSetthesametrimforalledges, "Määrata sama lõikamine puuduste eest, kõik servad");
	strcpy(sSettings, "Seaded");
	strcpy(sShape, "Kuju");
	strcpy(sSheet, "Leht");
	strcpy(sSheetsBarstypes, "Sheets_torude liigid");
	strcpy(sSheetSize, "Suurus leht");
	strcpy(sSheetsperPage, "Poognat Page");
	strcpy(sShort, "Lühike");
	strcpy(sShorterexecutiontime, "Lühike tööaeg");
	strcpy(sShowallsimpleproducts, "Näita kõiki lihtsaid tooteid");
	strcpy(sShowcustomername, "Näita kliendi nimi");
	strcpy(sShowCustomTextOnEachPiece, "Näita kohandatud teksti iga tükk");
	strcpy(sShowdiagramasatable, "Näita diagramm tabelina.");
	strcpy(sShowedgeband, "Näita serva paelte");
	strcpy(sShowedgebandssettinginanewwindow, "Näita seadete serva paelte uues aknas.");
	strcpy(sShowgrindingsettingsinanewwindow, "Näitab lihvimine seaded uues aknas.");
	strcpy(sShowHorizontalLabelsAlways, "Näita alati horisontaalne sildid");
	strcpy(sShowRemovethesizeofthepiecesinthecurrentsolution, "Näita / Remove suurust tükki praegune lahendus.");
	strcpy(sShowRemovethesizeofthewastesinthecurrentsolution, "Näita / Remove suurust jäätmete praegune lahendus.");
	strcpy(sShowtotalcutlength, "Näita kogu lõikepikkus");
	strcpy(sShowtrimedgesettingsinanewwindow, "Näita seadete defekte uues aknas.");
	strcpy(sSimpleMaterialExists, "Nimi materjali on juba määratletud materjalide loetelu. Palun anna uus nimi.");
	strcpy(sSinglePieceStrips, "Triibud ühes tükis.");
	strcpy(sSizes, "Suurused");
	strcpy(sSmallerorequalto, "Väiksem või võrdne");
	strcpy(sSort, "Sorteeri");
	strcpy(sSortAscendingByArea, "Järjesta kasvavalt ala");
	strcpy(sSortDescendingByArea, "Järjesta kahanevalt ala");
	strcpy(sSpecifyhowdifferentthepiecesinthelaststagecanbeValue0meansnodifference, "Täpsustada, kuidas erinevad võivad olla tükki viimasel etapil. Väärtus 0 tähendab mingit vahet.,");
	strcpy(sSpecifyifpiecesinthelaststagecanbedifferentornotdepeultimaetapapotfidiferitesaunucadimensiune, "Täpsustada, kas tükki viimases staadiumis võib olla erinev või mitte");
	strcpy(sSpecifyifthepiececanberotatedornotIfnotitwillbecutinthesamewayasitwasintroducedinDemandLengthofthepieceparalleltothelengthofthesheet, "Täpsustada, kas tükk saab pöörata või mitte. Kui ei, siis lõigatakse samamoodi nagu see võeti kasutusele Demand (pikkus tükk paralleelselt pikkus sheet),");
	strcpy(sSpecifyinhowmanystageswemakethecutsDuringastageallcutshavethesamedirection, "Täpsustada, kui palju etappe me teeme kärpeid.");
	strcpy(sStartthesearchprocess, "Alusta otsingu protsess");
	strcpy(sStatistics, "Statistika");
	strcpy(sStatisticsE, "Aruanded Extra");
	strcpy(sStatisticsforeachtypeofmaterial, "Statistics iga materjali");
	strcpy(sStep, "Samm");
	strcpy(sStergeDepozit, "Soovite kustutada Inventory?");
	strcpy(sStergeMaterial, "Kustuta materjali?");
	strcpy(sStergePiesele, "Soovite kustutada tükk?");
	strcpy(sStergePiesa, "Soovite kustutada tükk?");
	strcpy(sStopthesearchprocess, "Peata otsing protsess");
	strcpy(sStrongoptimization, "Tugev optimeerimine");
	strcpy(sSubtractthebandthicknessfrompiecesize, "Vähendage tükk suurusega ribad paksusega.");
	strcpy(sSummary, "kokkuvõte");
	strcpy(sSuprafataTotalaFolosita, "Kokku kasutatakse pinna");
	strcpy(sSuprafatautilizata, "Kasutamine");
	strcpy(sSwitchbetweenfiberandrotationoption, "Vaheldumisi kiudaineid ja rotatsiooni võimalus.");
	strcpy(sTechnical, "Tehniline");
	strcpy(sTechnicalsettings, "Tehnilised seaded");
	strcpy(sTemporaryPanelHint, "Ajutine paneel liikuvate osade vahel lehed.");
	strcpy(sText, "Tekst");
	strcpy(sThe_application_has_expired, "Programm on aegunud.");
	strcpy(sThe_application_is_not_registered, "Tarkvara ei ole registreeritud.");
	strcpy(sThe_application_was_first_started_on, "Tarkvara esmakordselt alustada.");
	strcpy(sThecutsareperformedfromasidetotheothersideofthematerial, "Debiteerimise tehakse alates küljelt teisel pool materjalist.");
	strcpy(sThecuttingmachinecanfollowtheshapeofthematerial, "Lõikamismasin saab jälgida kuju tükk.");
	strcpy(sTheedgesofsheetsthatmustbetrimedduefaults, "Servad lehed, mida tuleb ilma tõttu vigu");
	strcpy(sTheLargestSize, "Suurim suurus");
	strcpy(sThenameofthecustomerforwhichyoucutthepiece, "Kliendi nimel, mille jaoks te lõigatud tükk.");
	strcpy(sThenameofyourcustomer, "Nime oma kliendi");
	strcpy(sThepiececanberotated, "Tükk saab pöörata");
	strcpy(sTheprogramtriestoavoidwasteswhichhavebothsizeslessthanthisvalue, "Programm püüab vältida jäätmetest, mis on nii väiksemad kui see väärtus");
	strcpy(sThereAreNoProducts, "Puuduvad määratletud tooteid vee");
	strcpy(sThestockofmaterialhasbeenpreviouslyloadedfromanExcelorCSVformatPleaseloaditagain, "Stock materjali on varem laaditud Excel või CSV formaadis. Palun uuesti laadida, kui soovite tööd selle kallal.");
	strcpy(sThetotallengthofcutting, "Kogupikkus lõikamine");
	strcpy(sThewidthofthecuttingsawForglasscuttingoptimizationitcanbe0Forwooditshouldbegreaterthan0, "Paksust nägin. Klaasi lõikamine võib olla 0. Puidu see peaks olema suurem kui 0.");
	strcpy(sThewidthofthecuttingsawforlinearpieces, "Paksus nägin lineaarsete tükkidena.");
	strcpy(sThickness, "Paksus");
	strcpy(sThischaracterisusedforfillingthewasterectanglesIfyoudonotwantfilledwastejustremovethischaracter, "See sümbol täitmisel kasutatakse jäätmete ristkülikud. Kui te ei soovi täita jäätmete lihtsalt eemaldada.");
	strcpy(sThisindexhasvaluebetween1andthenumberofpieces, "See indeks on vahemikus 1 ja tükkide arv.");
	strcpy(sThisOptionWillOverrideTheInventoryFileIfLoadedFromExcelOrCsvFiles, "See võimalus alistada inventuuri faili, kui laaditud Excel või CSV faile.");
	strcpy(sThisProgramisLicensedTo, "See programm on litsentseeritud");
	strcpy(sThisvaluewillbeaddedtotheedgebandingmaterialoneachside, "See väärtus lisatakse serva banding materjali mõlemal külje");
	strcpy(sTipNevid, "Materjali tüübist ei saa olla tühi.");
	strcpy(sTitle, "Pealkiri");
	strcpy(sTools, "Tööriistad");
	strcpy(sTop, "Ülemine");
	strcpy(sTopcoordinateofthedefect, "Top koordinaat viga.");
	strcpy(sTotalGarbageWaste, "Kõik visata jäätmeid");
	strcpy(sTotalInventoryWaste, "Üldkogumi hulka");
	strcpy(sTotalRecycledWaste, "Kõik ringlussevõetud jäätmeid");
	strcpy(sTotalusedarea, "Kokku kasutatud ala");
	strcpy(sTotalusedlength, "Kokku kasutati pikkus");
	strcpy(sTrigonometric, "Trigonomeetriliste");
	strcpy(sTrim, "Kärpima");
	strcpy(sTrimalledgesatthebeginning, "Kärbi kõik servad alguses");
	strcpy(sTrimEdge, "Kärbi serva");
	strcpy(sTwoPanels, "2 paneeli");
	strcpy(sType, "tüüp");
	strcpy(sTypeofmaterialfromwhichtocut, "Materjali liik, kust kärpida");
	strcpy(sTypesAreNotMatched, "Optimeerimist ei teostatud! Detailide ja laoseisu tabelite materjalid ei ühti! Detailit saab lõigata ainult samanimelisest materjalist, mis on laos olemas. Muutke materjalide nimesid vastavates veergudes!");
	strcpy(sUndo, "Undo");
	strcpy(sUndoAccept, "Võta Nõustu");
	strcpy(sUnits, "üksused");
	strcpy(sUnregisteredVersion, "Registreerimata");
	strcpy(sUpdates, "Uuendused");
	strcpy(sUsefulforwoodfurniture, "Kasulik puidust mööbe");
	strcpy(sUseit, "Kasutage seda");
	strcpy(sUsePieceinOptimization, "Kasutage tükk optimeerimine");
	strcpy(sUserName, "Kasutajanimi");
	strcpy(sUtilizationandWastes, "Kasutamise ja jäätmete");
	strcpy(sUtilizedArea, "Ala kasutatud osad");
	strcpy(sUtilizedBars, "Kasutatud baarid");
	strcpy(sUtilizeddemandcount, "Number kasutatavat tükki.");
	strcpy(sUtilizedParts, "Kasutamata osa");
	strcpy(sUtilizedPieces, "Kasutatud tükki");
	strcpy(sUtilizedSheets, "Kasutatud lehed");
	strcpy(sValue, "Väärtus");
	strcpy(sValueGreaterEqualToZero, "Väärtus peab olema suurem või võrdne nulliga");
	strcpy(sValueGreaterThanZero, "Väärtus peab olema suurem kui nul");
	strcpy(sValueIntegerNumber, "Väärtus peab olema täisarv!");
	strcpy(sValueRealNumber, "Väärtus peab olema tegelik number. Võibolla olete kasutanud asemel. või viceversa. Palun parandage!");
	strcpy(s_The_number_is_too_big_or_it_has_too_many_digits_after_decimal_separator, "Number on liiga suur või on pärast koma eraldajat liiga palju numbreid!");
	strcpy(s_The_number_is_too_big, "Arv on liiga suur!");
	strcpy(sVertical, "Vertikaalne");
	strcpy(sWaste, "Jäätmed");
	strcpy(sWastes, "Jäätmed");
	strcpy(sWasteAddedToWarehouse, "Vanametalli lisatud ladu");
	strcpy(sWastelimits, "piirangud jäätmete");
	strcpy(sWasteType, "Jäätmete liik");
	strcpy(sWeakoptimization, "Nõrgim optimeerimine");
	strcpy(sWhattoprint, "Mida ma peaksin printida");
	strcpy(s_What_to_print_or_save_to_file, "Mida printida või faili salvestada");
	strcpy(sWhattoprintoneachpiece, "Mis printida igale");
	strcpy(sWhattoshowoneachpiece, "Mida näitavad iga tükk?");
	strcpy(sWidth, "Laius");
	strcpy(sWood, "puit");
	strcpy(sWorkingDirectory, "Töökataloogi");
	strcpy(sWrongKey, "Vale Registreerimine Key!");
	strcpy(sYes, "Jah");
	strcpy(sYoucannotchooseblackblueorredcolors, "You cannot choose black, blue or red colors.");
	strcpy(sYouCannotMixFractionalDataWithDecimalOnes, "Sa ei saa segada osaline väärtuste tegelik väärtus!");
	strcpy(sYourcompany, "Oma firma");
	strcpy(sZip, "Postiindeks");
	strcpy(s_Set_the_origin_and_the_direction_of_the_axes, "Määrake koordinaatide telgede alguspunkt ja suund.");










	strcpy(s_Number_of_digits_after_the_decimal_separator, "Numbrite arv pärast kümnendkoha eraldajat");
	strcpy(s_Percentages, "Protsendid");
}

