// Language strings: Afrikaans
// Author: Optimal Programs
// License: MIT License
//---------------------------------------------------------------------------
#include <string.h>
//---------------------------------------------------------------------------
#include "language_string_id.h"
//---------------------------------------------------------------------------
void set_af(void)
{
	//Afrikaans
	//did not checked manually
	// last update on: 2025.9.25.0
	strcpy(s_Area, "Oppervlakte");
	strcpy(s_Mass, "Massa");
	strcpy(s_Advanced, "Gevorderd");
	strcpy(s_Relative_coordinates, "Relatiewe koördinate");
	strcpy(s_Absolute_coordinates, "Absolute koördinate");
	strcpy(s_Append_more_rows, "Voeg meer rye by");

	strcpy(s_Add_to_parts, "Voeg by dele.");
	strcpy(s_Additional, "Bykomende");
	strcpy(s_All_results, "Alle resultate.");
	strcpy(s_Allow_movement_of_pieces, "Laat beweging van stukke toe");
	strcpy(s_Allow_part_in_part, "Laat stuk in stuk toe");
	strcpy(s_Invalid_piece_Angles_are_too_small_or_too_big_or_height_is_too_small, "Ongeldige stuk. Hoeke is te klein of te groot, of die hoogte is te klein.");
	strcpy(s_Append, "aanhegnavraag");
	strcpy(s_As_it_is, "Soos dit is");
	strcpy(s_As_text, "As teks");
	strcpy(s_Ascending, "stygende");
	strcpy(s_Automatic, "Outomatiese");
	strcpy(s_Cannot_connect_to_the_Internet_Please_visit_our_website_from_a_browser, "Kan nie aan die internet koppel nie! Besoek ons webwerf vanaf 'n blaaier.");
	strcpy(s_Cannot_copy_or_move_the_files, "Kan nie die lêers kopieer of skuif nie!");
	strcpy(s_Cannot_delete_the_file, "Kan nie die lêer verwyder nie!");
	strcpy(s_Cannot_modify_old_results, "Kan nie ou resultate wysig nie!");
	strcpy(s_To_change_click_inside_a_cell_or_press_0_1_or_2, "Om te verander, klik in 'n sel of druk 0, 1 of 2.");
	strcpy(s_Cell, "Sel");
	strcpy(s_Click_on_the_table_header_to_change_the_columns, "Klik op die tabelopskrif om die kolomme te verander.");
	strcpy(s_Close, "Maak dit toe");
	strcpy(s_Contact_us, "Kontak Ons");
	strcpy(s_Column, "Kolom");
	strcpy(s_Comma, "Komma");
	strcpy(s_The_comma_symbol_cannot_simultaneously_be_the_list_separator_and_the_decimal_separator, "Die kommasimbool kan nie gelyktydig die lysskeier en die desimale skeier wees nie!");
	strcpy(s_Copy, "Kopieer");
	strcpy(s_Copy_for_move, "Kopieer vir skuif");
	strcpy(s_Cut_higher_level_strips_first, "Sny eers hoër-vlak stroke");
	strcpy(s_Cut_index, "Wys indeks van sny");

	strcpy(s_The_data_have_been_changed_Do_you_want_to_save_them_to_a_file, "Die data is verander. Wil u dit in 'n lêer stoor?");
	strcpy(s_Decimal_separator, "Desimale skeiding");
	strcpy(s_Restore_default_settings, "Herstel verstekinstellings");
	strcpy(s_Delete_fiber, "Vee vesel uit");
	strcpy(s_Descending, "Neerdaal");
	strcpy(s_Discard_changes, "Ignoreer veranderinge");

	strcpy(s_Delete_all_data, "Vee alle data uit?");
	strcpy(s_Dot, "Punt");
	strcpy(s_Do_you_want_to_delete_the_picture, "Wil u die prentjie uitvee?");
	strcpy(s_Do_you_want_to_delete_the_product, "Wil u die produk uitvee?");
	strcpy(s_Duplicate_and_append, "Dupliseer en voeg by.");
	strcpy(s_Duplicate_values_are_ignored, "Dubbele waardes word geïgnoreer!");
	strcpy(s_Error, "Fout");
	strcpy(s_Error_loading_file, "Kon nie lêer laai nie.");
	strcpy(s_export_everything, "Voer alles uit");
	strcpy(s_Fit_to_screen, "Pas op die skerm.");
	strcpy(s_Force_fixed_height, "Teken die stukke met 'n vaste hoogte.");
	strcpy(s_Flipped, "Omgedraai");
	strcpy(s_Import, "invoer");
	strcpy(s_If_angles_are_different_from_90_degrees_height_must_be_greater_than_0, "As hoeke verskil van 90 grade, moet hoogte groter as 0 wees.");
	strcpy(s_Ignore, "Ignoreer");
	strcpy(s_Incorrect_value, "Verkeerde waarde");
	strcpy(s_Info, "Inligting");
	strcpy(s_Interior, "binne");
	strcpy(s_Give_a_name, "Gee 'n naam.");
	strcpy(s_Group, "Groepeer dit");
	strcpy(s_Header, "Opskrif");
	strcpy(s_Keep_it_as_it_is, "Hou dit soos dit is");
	strcpy(s_Level, "Level");
	strcpy(s_Licensee, "Lisensiehouer");
	strcpy(s_List_separator, "Lys skeier");
	strcpy(s_Made_with_love_in_Cugir_Romania, "Met liefde gemaak in Cugir, Roemenië");
	strcpy(s_Made_in, "Vervaardig in");
	strcpy(s_Manufacturer, "Vervaardiger");

	strcpy(s_Manual_arrange, "Handmatig reël");

	strcpy(s_Mixed, "Gemengde");
	strcpy(s_Multiple_shapes_detected_Next_rows_will_be_overwritten_Continue, "Meer as een vorm is opgespoor. Daarom sal die daaropvolgende rye oorskryf word. Aanhou?");
	strcpy(s_More, "Meer");
	strcpy(s_Multiple_values, "Veelvuldige waardes");
	strcpy(s_No_texture, "Geen tekstuur nie");
	strcpy(s_Number, "Nommer");
	strcpy(s_Number_of_images, "Aantal beelde");
	strcpy(s_Number_of_vertices, "Aantal hoekpunte");
	strcpy(s_Offset, "Offset");
	strcpy(s_Only_the_currently_selected_items, "Slegs die items wat tans gekies is.");
	strcpy(s_Optimizing_please_wait, "Optimaliseer ... wag asseblief.");

	strcpy(s_Paste, "Paste");

	strcpy(s_Piece_label, "Wys stuk etiket");
	strcpy(s_Piece_size, "Dui die grootte van die stukke");
	strcpy(s_Please_contact_us_by_email_if_you_receive_this_error, "Kontak ons per e-pos as u hierdie fout ontvang.");
	strcpy(s_Please_save_it_first, "Stoor dit asseblief eers.");
	strcpy(s_Position, "Posisie");
	strcpy(s_Preview, "Voorskou");
	strcpy(s_Rectangle, "Reghoek");

	strcpy(s_Redo_the_last_operation, "Herstel die laaste bewerking");
	strcpy(s_Regular_polygon, "Gereelde veelhoek");

	strcpy(s_Reused, "Hergebruik");
	strcpy(s_Rotated, "Geroteerde");
	strcpy(s_Save_all, "Stoor almal");
	strcpy(s_Scrap_label, "Wys afval etiket");
	strcpy(s_Scrap_size, "Dui die grootte van die puinhope");
	strcpy(s_Semicolon, "Kommapunt");
	strcpy(s_Show_cut_index, "Wys indeks van sny");
	strcpy(s_Show_information, "Wys inligting");
	strcpy(s_Show_piece_label, "Wys stuk etiket");
	strcpy(s_Show_scrap_label, "Wys afval etiket");
	strcpy(s_Show_scrap_s_size_on_the_small_pieces, "Toon die grootte van die afval op die klein stukkies");
	strcpy(s_Show_size_of_pieces, "Dui die grootte van die stukke");
	strcpy(s_Show_size_of_scrap, "Dui die grootte van die puinhope");
	strcpy(s_Show_sizes, "Wys groottes");
	strcpy(s_Show_label, "Wys etiket");
	strcpy(s_Show_length, "Wys lengte");

	strcpy(s_Some_numerical_values_are_incorrect_Should_I_fix_all_the_incorrect_values, "Sommige numeriese waardes is verkeerd! Moet ek al die verkeerde waardes regmaak?");
	strcpy(s_Some_invalid_values_have_been_removed, "Sommige ongeldige waardes is verwyder.");
	strcpy(s_Sort_by, "Sorteer Volgens");
	strcpy(s_Sort_ascending_by, "Sorteer volgens stygende");
	strcpy(s_Sort_descending_by, "Sorteer volgens dalende");
	strcpy(s_Start, "Start");
	strcpy(s_Starting_angle, "Beginhoek");


	strcpy(s_Stock, "Voorraad");
	strcpy(s_Stop, "Stop");
	strcpy(s_System_setting, "Stelselinstelling");
	strcpy(s_Tabular, "Tabel");
	strcpy(s_Total, "Totaal");
	strcpy(s_Total_size, "Totale grootte");
	strcpy(s_Terms_of_the_license, "Voorwaardes van die lisensie");
	strcpy(s_The_current_product_has_been_changed_Do_you_want_to_save_it_to_file, "Die huidige produk is verander. Wil u dit stoor?");
	strcpy(s_The_value_is_out_of_the_allowed_range, "Die waarde is buite die toegelate reeks.");
	strcpy(s_The_value_must_be_a_real_or_fractional_number_Try_to_replace_the_comma_with_the_dot_if_you_want_to_enter_a_real_number, "Die waarde moet 'n reële of breukgetal wees. Probeer om die komma met die punt te vervang as u 'n regte nommer wil invoer.");
	strcpy(s_This_feature_is_not_implemented_yet, "Hierdie kenmerk is nog nie geïmplementeer nie.");
	strcpy(s_This_operation_cannot_be_reversed, "Hierdie bewerking kan nie omgekeer word nie.");
	strcpy(s_Undo_the_last_operation, "Ontdoen die laaste bewerking.");
	strcpy(s_Utilization, "Benutting");
	strcpy(s_Utilized_Stock, "Gebruikte voorraad");
	strcpy(s_Version, "Weergawe");
	strcpy(s_Visible_columns, "Sigbare kolomme");
	strcpy(s_You_already_have_the_latest_version_installed, "U het reeds die nuutste weergawe geïnstalleer!");
	strcpy(s_What_is_exported, "Wat word uitgevoer?");
	strcpy(s0meansanynumberofpieces, "Zero enige aantal stukke");
	strcpy(sAbout, "Oor");
	strcpy(sAccept, "Aanvaar");
	strcpy(sAcceptall, "Aanvaar alle");
	strcpy(sAcceptthecurrentsolution, "Aanvaar die huidige oplossing");
	strcpy(sAdd, "Voeg");
	strcpy(sAddapiece, "Voeg 'n stuk");
	strcpy(sAddasimpleproducttoDemand, "Voeg 'n produk aan die bestaande vraag.");
	strcpy(sAddgrindingthicknesstopartsize, "Voeg maal dikte aan die stuk grootte");
	strcpy(sAddproductnametolabel, "Heg produk se naam op die etiket");
	strcpy(sAddress, "Adres");
	strcpy(sAddselectedsizetoInventory, "Voeg geselekteerde grootte van die inventaris");
	strcpy(sAdhesivelabels, "Zelfklevende etiketten");
	strcpy(sAdhesivelabelwithinformationaboutpiecesinDemandCustomernameLabelSizeCurrentData, "Gom etiket met inligting oor die stukke in die vraag: naam van die kliënt, etiket, Grootte, huidige data.");
	strcpy(sAdhesivelabelwithinformationaboutsheetsinInventory, "Gom etiket met inligting oor die velle in voorraad.");
	strcpy(sAll, "Almal");
	strcpy(sAlloffcutswhichhavethesizegreaterthanthisvaluewillbeaddedtoInventory, "Alle offcuts wat die grootte groter is as die waarde toegevoeg word tot voorraad");
	strcpy(sAllowMirroring, "Laat spieë");
	strcpy(sAllowRotation, "Laat Rotasie");
	strcpy(sAllPieces, "Alle stukke");
	strcpy(sAllpredefinedproducts, "Alle gedefinieerde produkte");
	strcpy(sAnewwindowwillbedisplayedwheretheusercansettheedgebandsforeachedge, "'N nuwe venster vertoon sal word wat die gebruiker kan die bande vir elke rand.");
	strcpy(sAnewwindowwillbedisplayedwheretheusercansetthegrindingvalueforeachedgeofthsheet, "'N nuwe venster vertoon sal word wat die gebruiker kan die maal waarde vir elke rand van die stuk stel.");
	strcpy(sAnewwindowwillbedisplayedwheretheusercansetthetrimvalueforeachedgeofthsheet, "'N nuwe venster vertoon sal word waar die gebruiker kan die foute vir elke rand van die stuk.");
	strcpy(sAngle, "Hoek");
	strcpy(sAngles, "hoeke");
	strcpy(sAnoptimizationparameterisarealnumber, "'n optimalisering parameter is 'n reële getal is.");
	strcpy(sAnoptimizationparameterisfractionalnumber, "'n optimalisering parameter is fraksionele nommer.");
	strcpy(sAnyShape, "Enige vorm");
	strcpy(sApolygonmusthaveatleast2vertices, "'N Veelhoek moet ten minste 2 hoekpunte hê!");
	strcpy(sApolygonmusthaveatleast3vertices, "'N Veelhoek moet ten minste 3 hoekpunte hê!");
	strcpy(sApplication_fails_to_initialize, "Die sagteware versuim te begin.");
	strcpy(sArc, "Arc");
	strcpy(sArcLength, "Booglengte");
	strcpy(sAreaofusedsheets, "Oppervlakte van die gebruik van velle");
	strcpy(sAshortdescriptionofthesheet, "'N kort beskrywing van die blad");
	strcpy(sAtleastonepart, "Ten minste een stuk moet ingestel word.");
	strcpy(sAtTheMarginOfTheSheet, "Op die rand van die blad");
	strcpy(sBandtypes, "Tipes van die rand band.");
	strcpy(sBar, "Bars / pype");
	strcpy(sBars, "Bars / pype");
	strcpy(sBothsizesoftheoffcutsmustbegreaterthanthisvalue, "Beide groottes van die offcuts moet groter wees as die waarde.");
	strcpy(sBottom, "Bottom");
	strcpy(sBottomcoordinateofthedefect, "Die onderste koördinaat van die gebrek");
	strcpy(sBreakCut, "Breek die snit");
	strcpy(sBrowse, "Browse");
	strcpy(sBuy, "Koop");
	strcpy(sBuynow, "Koop nou ...");
	strcpy(sCancel, "Kanselleer");
	strcpy(sCannotBeEmpty, "kan nie leeg wees!");
	strcpy(sCannotmovepartsbetweensheetswhenidenticalsheetsaregroupedPleaseungroupthesheetsfrommenu, "Kan nie beweeg nie die dele van een blad na 'n ander as die identiese velle word gegroepeer kanselleer asseblief die groepering van die velle van die spyskaart.");
	strcpy(sCannotSaveFile, "Kan nie stoor die lêer");
	strcpy(sCenter, "Sentrum");

	strcpy(sChangeDirection, "Verander die rigting");
	strcpy(sChoose, "Kies");
	strcpy(sChooseProduct, "Kies 'n produk");
	strcpy(sCircle, "Sirke");
	strcpy(sCity, "City");
	strcpy(sClear, "Duidelik");
	strcpy(sClockWise, "Kloksgewys");
	strcpy(sClosewindow, "Sluit venster");
	strcpy(sColor, "Kleur");
	strcpy(sColorofedgeband, "Die kleur van die rand-band");
	strcpy(sColorPattern, "Kleur / patroon");
	strcpy(sColorpiecesandwastes, "Stukke en afval kleurvolle.");
	strcpy(sColumns, "Kolomme");
	strcpy(sComment, "Kommentaar");
	strcpy(sCompanyname, "Maatskappy se naam");
	strcpy(sComplexMaterialExists, "Naam van die materiaal is reeds gedefinieer in die lys van komplekse materiale. Gee dit asseblief 'n nuwe naam.");
	strcpy(sComputerCode, "Rekenaar kode");
	strcpy(sComputerCodefromyourcomputer, "Rekenaar kode (vanaf jou rekenaar)");
	strcpy(sComputethetotalpriceofDemand, "Bereken die totale prys van die vraag");
	strcpy(sContents, "Inhoud");
	strcpy(sContinutComanda, "Inhoud van die vraag in die datum");
	strcpy(sContinutDepozit, "Inhoud van die voorraad in die datum");
	strcpy(sConversionIsDoneOnlyWhenSomePiecesHaveFractionalValues, "Omskakeling word slegs wanneer 'n paar stukkies het fraksionele waardes.");
	strcpy(sConvertsTheSizeOfWasteToAFractionalUnit, "Toon die grootte van afval as 'n breukdeel waarde.");
	strcpy(sCouldNotSaveFile1, "Kon nie skryf lêer in die gids");
	strcpy(sCouldNotSaveFile2, "Jy het dalk nie genoeg regte. Let asseblief kontroleer of verander die werk gids stel vanaf die menu Stellings | Werk gids tot 'n gids waar jy die regte te skryf (byvoorbeeld C:\\Temp).");
	strcpy(sCreationdateYMDHMS, "Creation date (Y / M / D, H: M: S)");
	strcpy(sCurrentDate, "Huidige datum");
	strcpy(sCurrentDiagram, "Huidige diagram");
	strcpy(sCurrentMaterial, "Huidige materiaa");
	strcpy(sCurrentversion, "Huidige weergawe");
	strcpy(sCurve_not_closed_Try_increasing_DXF_linking_distance_parameter, "Die veelhoek is nie gesluit nie! Probeer om die parameter DXF-skakelafstand te verhoog.");
	strcpy(sCustomer, "Kliënt");
	strcpy(sCustomerName, "Kliënt Naam");
	strcpy(sCustomMessage, "Persoonlike boodskap");
	strcpy(sCutlength, "Die lengte van die snit");
	strcpy(sCut, "Sny");
	strcpy(sCuts, "Snitte");
	strcpy(sCutterThickness, "Sny dik");
	strcpy(sData, "Die data");
	strcpy(sDataCannotBeEmpty, "Die data kan nie leeg wees nie!");
	strcpy(sDateymdhms, "Datum (y / m / d / h / m / s)");
	strcpy(sDays_left_for_trial, "Dae beskikbaar vir die toets ");
	strcpy(sDaysLeft, "dae oor");
	strcpy(sStandard, "Standard");
	strcpy(sDefaultInterface, "Default interface");
	strcpy(sDefects, "Defekte");
	strcpy(sDefectsManager, "Bestuur defekte");
	strcpy(sDefectsofthematerialNopiecescanbeplacedinthefaultyzone, "Defekte van die materiaal. Geen stukke geplaas kan word in die foutiewe sone.");
	strcpy(sDelete, "Verwyder");
	strcpy(sDeletePiece, "Verwyder stuk");
	strcpy(sDeleteRow, "verwyder ry");
	strcpy(sDemandutilization, "Benutting van die vraag");
	strcpy(sDepozitulmodificat, "Die gebruik stukke verwyder is. Die oorblyfsels is bygevoeg tot voorraad.");
	strcpy(sDepozitvid, "Die voorraad is leeg");
	strcpy(sDesk, "lessenaar");
	strcpy(sDiagram, "Diagram");
	strcpy(sDiagrams, "Diagramme");
	strcpy(sDiagramasatable, "Diagram as 'n tafe");
	strcpy(sDigits, "syfers");
	strcpy(sDimensiuniplaca, "Grootte van die ve");
	strcpy(sDirection, "Rigting");
	strcpy(sDistanceBetweenRows, "Afstand tussen rye");
	strcpy(sDonotuseit, "Moet dit nie gebruik");
	strcpy(sDownload, "Aflaai");
	strcpy(sDoYouWantToClearTheData, "Jy wil die data te verwyder?");
	strcpy(sDoYouWantToSaveDemand, "Die dele verander! Jy wil die veranderinge te red?");
	strcpy(sDoYouWantToSaveParts, "Wil jy die dele te red?");
	strcpy(sDoYouWantToSaveRepository, "Die voorraad is verander! Jy wil die veranderinge te red?");
	strcpy(sDrawing, "tekening");
	strcpy(sDrawthesolutioncolorful, "Trek die oplossing kleurvolle");
	strcpy(sDuplicateTypes, "Sommige tipes is gedupliseer! Duplikate verwyder");
	strcpy(sDuplicateTypesWithComplex, "Sommige name van die materiaal wat reeds bestaan ??in die lys van komplekse tipes! Verwyder asseblief die duplikate");
	strcpy(sDuplicateValues, "Dubbel waardes");
	strcpy(sEdgeband, "Bande vir rande");
	strcpy(sEdgebandingwhichisplacedontheedgesofyourpiecePleasedefineedgebandingtypesfromMaterialsEdgeBandingmenu, "Kantenaanlijmmachines wat geplaas word op die rand van jou stuk. Asseblief definieer Kantenaanlijmmachines tipes van Materiale spyskaart.");
	strcpy(sEdgebandsthatwillbeappliedtoeachpart, "Edge bands wat aan elke deel toegepas word.");
	strcpy(sEdgeBandTolerance, "Verdraagsaamheid vir Kantenaanlijmmachines");
	strcpy(sEdgesthatmustbecutduefaults, "Rande wat moet uitgeroei word as gevolg van foute.");
	strcpy(sEdgetoedge, "Van rand tot rand");
	strcpy(sEdit, "Verander");
	strcpy(sEmail, "E-post");
	strcpy(sEmptyData, "Die data is leeg!");
	strcpy(sEnabled, "Aangeskakel");
	strcpy(sEnabledisabledefectsoftheinventorysheets, "Aktiveer / deaktiveer defekte van die voorraad");
	strcpy(sEnterLabel, "Inset-etiket");
	strcpy(sEnterTheMaterialName, "Die Input die naam van die materiaa");
	strcpy(sEnterTheProductName, "Tik die naam van die produk");
	strcpy(sEvaluationError, "Fout aan die uitdrukking evaluering!");
	strcpy(sExit, "Verlaat");
	strcpy(sExpired, "Die sagteware verstryk het! Registreer asseblief die sagteware!");
	strcpy(sExport, "Uitvoer");
	strcpy(sExportAllDiagrams, "Voer alle diagramme uit");
	strcpy(sExportAllToASingleFile, "Voer alles na 'n enkele lêer uit");
	strcpy(sExportOptions, "Uitvoer opsies.");
	strcpy(sExporttoDXFformat, "Uitvoer na DXF formaat");
	strcpy(sExporttoExcel, "Uitvoer na Excel");
	strcpy(sExpresieIncorecta, "Verkeerde wiskundige uitdrukking!");
	strcpy(sExtensions, "uitbreidings");
	strcpy(sExtra, "Extra");
	strcpy(sExtraComponents, "Ekstra komponente");
	strcpy(sExtracomponentsattachedtoDemand, "Ekstra komponente wat aan dele");
	strcpy(sFile, "Lêer");
	strcpy(sFileName, "File name");
	strcpy(sFillWastes, "Teken afval met skuins lyne");
	strcpy(sFindoptimalbarsheetsize, "Vind die optimale grootte vir pype en velle.");
	strcpy(sFindoptimalsizeofInventorypieces, "Vind die optimale grootte van voorraad stukke");
	strcpy(sFirstcutMultiplestages, "Eerste sny rigting - verskeie stadiums");
	strcpy(sFirstdirectionforcutishorizontal, "Eerste rigting vir die sny horisontaal is.");
	strcpy(sFirstdirectionforcutisvertical, "Eerste rigting vir die sny is vertikale.");
	strcpy(sFollowthecontourofpieces, "Volg die kontoer van die stukke");
	strcpy(sFont, "Lettertipe");
	strcpy(sFontsize, "Lettergrootte");
	strcpy(sFullInfo, "Volledige inligting");
	strcpy(sDisposedWaste, "Weggegooi afval");
	strcpy(sGeneral, "Algemeen");
	strcpy(sGenerateCNC, "Genereer CNC");
	strcpy(sGrain, "Tekstuur");
	strcpy(sGraindirection, "Tekstuurrigting");
	strcpy(sGraphic, "Grafiese");
	strcpy(sGreaterorequalto, "Groter of gelyk aan");
	strcpy(sGrid, "tafels");
	strcpy(sGrinding, "maal dikte");
	strcpy(sGrosimeTaieturaScalata, "Die cut dikte van hierdie prentjie kan anders wees van die ware een, omdat die stukke is nie verteenwoordig is by hul ware skaal. Hierdie feit het geen invloed op die resultate.");
	strcpy(sGroupidenticallayouts, "Groepering van identiese blaaie");
	strcpy(sGroupIdenticalParts, "Identiese dele gegroepeer.");
	strcpy(sGroupingOfIdenticalPiecesIntoOneRow, "Groepering van identiese stukke in 'n ry.");
	strcpy(sGroupPartsAfterLoadingFromFile, "Groepering van die dele na die laai van lêer");
	strcpy(sHeight, "Lengte");
	strcpy(sHeighttolerance, "Toleransie vir hoogte");
	strcpy(sHelp, "Help");
	strcpy(sHistory, "Geskiedenis");
	strcpy(sHorizontal, "Horisontale");
	strcpy(sHowtodisplayprintedgebands, "Hoe dit vertoon rand bands?");
	strcpy(sIfyousetthebandforoneedgeallwillreceivethesamevalue, "As jy die band vir die een kant, sal dieselfde waarde.");
	strcpy(sIfyousetthegrindingforoneedgeallwillreceivethesamevalue, "As jy die maal waarde vir die een kant, sal alle kante dieselfde waarde ontvang.");
	strcpy(sIfyousetthetrimforoneedgeallwillreceivethesamevalue, "As jy die snoei vir die een kant, sal alle kante dieselfde waarde ontvang.");
	strcpy(sImageBounds, "Grense vir die beeld");
	strcpy(sImageSize, "Beeld grootte");
	strcpy(sImportData, "Voer die data.");
	strcpy(sIncorrectPassword, "Ongeldige wagwoord");
	strcpy(sIndex, "Index");
	strcpy(sInformationaboutcustomer, "Inligting oor die kliënt");
	strcpy(sInputALanguageName, "Gee 'n naam vir die taa");
	strcpy(sInsert, "Voeg");
	strcpy(sInsertPiece, "Voeg stuk");
	strcpy(sInterface, "Interface");
	strcpy(sInterfaceSettings, "Interface instellings");
	strcpy(sInvalidHardware, "Ek kon dit nie opspoor nie die hardeware. Kontak ons ??asseblief by contact@optimalprograms.com");
	strcpy(sInvalidNumber, "Ongeldige aanta");
	strcpy(sInvalidOrderOfComputation, "'N bevel vir die berekening van die lengte kan nie bevestig word nie. Daar is die omsendbrief verhoudings in die produk definisie!");
	strcpy(sInvalidRegistration, "Registrasie is ongeldig!");
	strcpy(sInvalidTime, "Die tyd van jou stelsel is ongeldig.");
	strcpy(sInventory, "Voorraad");
	strcpy(sisafractionalvalue, "is 'n fraksionele waarde.");
	strcpy(sIsArc, "Is boog");
	strcpy(sisarealvalue, "is 'n reële waarde.");
	strcpy(sLabel, "Label");
	strcpy(sLabels, "Labels");
	strcpy(sLanguage, "Taa");
	strcpy(sLatimeanumar0, "Die wydte moet groter as 0!");
	strcpy(sLatimeanumarreal, "Die wydte moet 'n reële getal sal wees!");
	strcpy(sLayerName, "Laagnaam");
	strcpy(sLeft, "Links");
	strcpy(sLeftcoordinateofthedefect, "Die linker koördinaat van die gebrek");
	strcpy(sLength, "Lengte");
	strcpy(sLengthofthepiecestocut, "Stuk grootte vir die sny");
	strcpy(sLengthofthepiecestocutfrom, "Sheet grootte vir die sny");
	strcpy(sLengthofusedbars, "Grootte van gebruik bars");
	strcpy(sLicenseAgreement, "lisensie-ooreenkoms");
	strcpy(sLinear, "lineêre");
	strcpy(sLinethickness, "Dikte van die pen");
	strcpy(sLoadafileandappenddatatothecurrentDemand, "Laai 'n lêer en voeg die data na die huidige vraag.");
	strcpy(sLoadanexistingDemandfromafile, "Laai 'n vraag van 'n lêer.");
	strcpy(sLoadAppend, "Laai en voeg");
	strcpy(sLoadEverything, "Load alles");
	strcpy(sLoadInventory, "Laai die lêer");
	strcpy(sLoadInventoryandDemand, "Laai die voorraad en die vraag");
	strcpy(sLoadResults, "Laai die resultate");
	strcpy(sLocked, "gesluit");
	strcpy(sLogo, "Logo");
	strcpy(sLong, "Lank");
	strcpy(sLongerexecutiontime, "Langer uitvoering tyd");
	strcpy(sLungime, "Breedte");
	strcpy(sLungimeanumar0, "Die lengte moet wees groter as 0!");
	strcpy(sLungimeanumarreal, "Die lengte moet 'n reële getal sal wees!");
	strcpy(sLungimeaTotalaFolosita, "Totale aangewend lengte");
	strcpy(sMagnification, "Vergroting");
	strcpy(sMagnify, "Vergroten");
	strcpy(sMargins, "Marges");
	strcpy(sMarginsForPaper, "Marges vir papier");
	strcpy(sMarginsOfTheLabel, "Kantlyne van die etiket");
	strcpy(sMaterial, "Materiaa");
	strcpy(sMaterialName, "Naam van die materiaa");
	strcpy(sMaterials, "Materiaa");
	strcpy(sMaterialstypes, "Materiaal tipes");
	strcpy(sMax, "Max");
	strcpy(sMaximalArea, "Herstel area");
	strcpy(sMaximalCutLength, "Herstel sny lengte");
	strcpy(sMaxlength, "Herstel lengte");
	strcpy(sMaxPiecesperBar, "Max Pieces per Bar");
	strcpy(sMaxwidth, "Maksimale wydte.");
	strcpy(sMeasurementUnit, "Meet eenheid");
	strcpy(sMin, "min");
	strcpy(sMinimalBreakSize, "Lig breuk grootte");
	strcpy(sMinimalUsefulSize, "Minimale bruikbare grootte");
	strcpy(sMinimalwastesizetoInventory, "Minimale afval grootte tot voorraad");
	strcpy(s_What_to_minimize, "Wat om te minimaliseer?");
	strcpy(sMinlength, "Minimale lengte");
	strcpy(sMinwidth, "Minimale breedte");
	strcpy(sMirror, "Mirror");
	strcpy(sMirroring, "Mirroring");
	strcpy(sMiscellaneous, "Diverse");
	strcpy(sModify, "Verander");
	strcpy(sModifytheselectedpiece, "Verander die geselekteerde stuk");
	strcpy(sMovePiece, "Beweeg stuk");
	strcpy(sMultiplestages, "Verskeie stadiums");
	strcpy(sName, "Naam");
	strcpy(sNameofedgeband, "Naam van die rand bands");
	strcpy(sNewDEMANDUnsaveddatawillbelost, "Nuwe items? Ongebergde data sal verlore gaan!");
	strcpy(sNewLanguage, "Nuwe taa");
	strcpy(sNewMaterial, "Nuwe materiaa");
	strcpy(sNewPasswordincorectlyintroduced, "Nuwe wagwoord verkeerd ingestel!");
	strcpy(sNewProduct, "Nuwe produk");
	strcpy(sNewversion, "Nuwe weergawe");
	strcpy(sNo, "Geen");
	strcpy(sNumarBucati, "Aantal stukke");
	strcpy(sNumberOfCopies, "Aantal kopieë");
	strcpy(sNumberofstages, "Aantal stadia");
	strcpy(sNusuficienteplacidepozit, "Nie al die stukke is geoptimaliseer. Moontlike oorsake: Daar is nie genoeg stukke in die voorraad; Stuk word nie gebruik in die optimalisering; Materiaal van Demand and Inventory nie ooreenstem; Ander parameters het verkeerd is ingestel.");
	strcpy(sOfficeNotInstaled, "Microsoft Office is nie op jou rekenaar of 'n incorect weergawe geïnstalleer is geinstalleer!");
	strcpy(sOldpassworddoesnotmatch, "Ou wagwoord stem nie ooreen!");
	strcpy(sOnlinehelp, "Online hulp");
	strcpy(sOnlypiecesofthesameheightinthelaststage, "Stukke van dieselfde hoogte in die laaste stadium");
	strcpy(sOpen, "Oop");
	strcpy(sOptimization, "Optimization");
	strcpy(sOptimizationDone, "Optimization uitgevoer! Jy mag stoor of druk die verkry diagramme. Press knoppie aanvaar as jy tevrede is met die huidige oplossing. Andersins druk begin weer.");
	strcpy(sOptimizationType, "Tipe van optimalisering");
	strcpy(sOptions, "opsies");
	strcpy(sOptionsrelatedtotheinterface, "Opsies wat verband hou met die koppelvlak");
	strcpy(sor, "of");
	strcpy(sOthercomponents, "Ander komponente");
	strcpy(sOthers, "Ander");
	strcpy(sOtherstatistics, "Ander statistieke");
	strcpy(sOverrideExcelCSVfiles, "Ignoreer Excel / CSV lêers");
	strcpy(sParameter, "Parameter");
	strcpy(sParts, "PARTS");
	strcpy(sPattern, "Patroon");
	strcpy(sPatternforwaste, "Patroon vir afva");
	strcpy(sPerimeter, "Omtrek");
	strcpy(sPermitedRotationAngle, "Rotasie-hoek wat toegelaat word");
	strcpy(sPhone, "Phone");
	strcpy(sPicture, "beeld");
	strcpy(sPiece, "Stuk");
	strcpy(sPieceindex, "Stuk se indeks");
	strcpy(sPieces, "Stukke");
	strcpy(sPiecesize, "Die Piece se grootte");
	strcpy(sPiecesizelabeledgebandwillbeprinted, "Grootte van die stuk, etiket, rand bands gedruk word.");
	strcpy(sPierdere, "Waste");
	strcpy(sPixels, "pixels");
	strcpy(sPlacilefolositeDepozit, "Stukke van die inventaris gebruik.");
	strcpy(sPlease_contact_us_at_contact_nestingtechnologies_com, "Kontak ons asseblief by contact@nesting-technologies.com");
	strcpy(sPlease_contact_us_at_contact_optimalprograms_com, "Kontak ons asseblief by contact@optimalprograms.com");
	strcpy(sPleaseenteralldataeitherasfractionalorrealDonotmixthem, "Voer alle data óf as fraksionele of werklike meng nie hulle!");
	strcpy(sPleaseEnterSomeTypesOfMaterials, "Daar is geen tipe materiaal wat gedefinieer word. Jy kan bepaal hulle van materiaal spyskaart.");
	strcpy(sPleasesendtheNameandtheCodetotheaddresscontactoptimalprogramscominordertoobtaintheRegistrationKey, "Ten einde die registrasie sleutel te kry, stuur die naam en die Kode: contact@optimalprograms.com.");
	strcpy(sPolygon, "Veelhoek");
	strcpy(sPolygonsCircles, "Veelhoeke, sirkels");
	strcpy(sPrecision, "Precision");
	strcpy(sPretulnumar0, "Die prys moet groter as 0!");
	strcpy(sPretulnumarreal, "Die prys moet 'n reële getal sal wees!");
	strcpy(sPreview, "voorskou");
	strcpy(sPrice, "Prys");
	strcpy(sPriceMustBeGreaterThanZero, "Prys moet groter as nu");
	strcpy(sPriceofbars, "Prys van bars");
	strcpy(sPriceperbar, "Prys per bar");
	strcpy(sPricepersheet, "Prys per ve");
	strcpy(sPricepersquareunitofmaterial, "Prys per vierkante eenheid van die materiaal.");
	strcpy(sPriceperunit, "Prys per eenheid");
	strcpy(sPrint, "Print");
	strcpy(sPrintdiagramsastables, "Druk diagramme in die vorm van tabelle.");
	strcpy(sPrinter, "Drukker");
	strcpy(sPrinterBounds, "Marges vir drukker");
	strcpy(sPrinting, "druk");
	strcpy(sPrintonlyutilizedarea, "Druk slegs die gebruik gebied");
	strcpy(sPrintthecontentsoftheDemand, "Druk die inhoud van die vraag.");
	strcpy(sPrintthecontentsoftheInventory, "Druk die inhoud van die voorraad.");
	strcpy(sPrintthecurrentsolution, "Druk die huidige oplossing.");
	strcpy(sPriority, "Prioriteit");
	strcpy(sPrioritytocutapieceZero0isthehighestpriority, "Prioriteit 'n stuk te sny. Nul (0) is die hoogste prioriteit.");
	strcpy(sProcentul0100, "Die Procenten groter as 0 en kleiner of gelyk aan 100 moet wees!");
	strcpy(sProcentulnumarreal, "Die Procenten moet 'n reële getal sal wees!");
	strcpy(sProductdefinition, "Produk definisie");
	strcpy(sProductExists, "Die produk bestaan ??reeds. Kies 'n ander naam.");
	strcpy(sProductName, "Produk se naam");
	strcpy(sProducts, "Produk");
	strcpy(sProducts, "Produkte");
	strcpy(sProject, "Projek");
	strcpy(sProperties, "eiendomme");
	strcpy(sProperty, "eiendom");
	strcpy(sQuantity, "Hoeveelheid");
	strcpy(sQuantitynumberofsheetsofthistype, "Aantal velle van hierdie tipe");
	strcpy(sRadius, "Radius");
	strcpy(sRectangular, "Reghoekige");
	strcpy(sRedefinetypesofedgeband, "Redefine tipes van rand band");
	strcpy(sRedefinetypesofmaterial, "Redefine tipes materiaa");
	strcpy(sRegistration, "Registrasie");
	strcpy(sRegistrationKeyfromOptimalPrograms, "Registrasie Sleute");
	strcpy(sRegistrationSuccessful, "Registrasie suksesvol!");
	strcpy(sRemoveallpiecesinInventory, "Verwyder alle stukke in voorraad.");
	strcpy(sRemoveCut, "Verwyder sny");
	strcpy(sRemovetheselectedpiece, "Verwyder die geselekteerde stuk");
	strcpy(sReports, "Verslae");
	strcpy(sRequestedMaterial, "Versoek Materiaa");
	strcpy(sRestore, "Herste");
	strcpy(sResults, "Resultate");
	strcpy(sReusedwaste, "Hergebruik afva");
	strcpy(sRight, "Reg");
	strcpy(sRightcoordinateofthedefect, "Koördinate van die gebrek van regs");
	strcpy(sRotation, "Rotasie");
	strcpy(sRotationAngle, "Rotasie-hoek");
	strcpy(sRotationStep, "Rotasie stap");
	strcpy(sRoundAllFractionsTo, "Die fraksionele waardes moet afgerond word tot");
	strcpy(sRow, "ry");
	strcpy(sRows, "Rye");
	strcpy(sRun, "Jongste oplossings");
	strcpy(sRunningtime, "looptyd");
	strcpy(sSameforall, "Dieselfde vir alle");
	strcpy(sSave, "Stoor");
	strcpy(sSaveAllImages, "Slaan alle beelde");
	strcpy(sSaveAs, "Stoor as");
	strcpy(sSaveChanges, "Die vraag is verander. Wil jy te red?");
	strcpy(sSaveCurrentImage, "Stoor die huidige prent");
	strcpy(sSavedataparameters, "Slaan data en parameters");
	strcpy(sSaveEverything, "Slaan alles");
	strcpy(sSaveInventory, "Slaan Inventaris");
	strcpy(sSaveInventoryandDemand, "Slaan Inventaris en aanbod");
	strcpy(sSaveResults, "Slaan Results");
	strcpy(sSaveStatisticsinafile, "Slaan statistieke in 'n lêer");
	strcpy(sSavethecurrentimage, "Stoor die huidige beeld");
	strcpy(sSavethecurrentimageorstatistic, "Stoor die huidige beeld of statistiek");
	strcpy(sSavetheDEMANDinafile, "Stoor");
	strcpy(sSavetheDemandinafilewithadifferentname, "Stoor die vraag in 'n lêer met 'n ander naam.");
	strcpy(sSavetheREPOSITORYinafile, "Stoor die bewaarplek in 'n lêer");
	strcpy(sSerialNumber, "Registrasie sleute");
	strcpy(sService, "diens");
	strcpy(sSetDefaultValues, "Dit sal die herstel van al die parameters hul verstekwaardes. Al jou verstellings sal verlore wees. Is jy seker jy wil om dit te doen?");
	strcpy(sSetedgeband, "Stel rand groep");
	strcpy(sSetedgetrim, "Stel die sny vir die gebreke van die kante");
	strcpy(sSetthesameedgebandforalledges, "Stel die rand band vir alle kante");
	strcpy(sSetthesamegrindingforalledges, "Stel die dieselfde maal vir alle kante");
	strcpy(sSetthesametrimforalledges, "Stel dieselfde sny vir defekte vir alle kante");
	strcpy(sSettings, "Stellings");
	strcpy(sShape, "Vorm");
	strcpy(sSheet, "Sheet");
	strcpy(sSheetsBarstypes, "Sheets_pype tipes");
	strcpy(sSheetSize, "Grootte van die ve");
	strcpy(sSheetsperPage, "Velle per bladsy");
	strcpy(sShort, "Kort");
	strcpy(sShorterexecutiontime, "Kort hardloop tyd");
	strcpy(sShowallsimpleproducts, "Wys alle eenvoudige produkte");
	strcpy(sShowcustomername, "Wys kliënt naam");
	strcpy(sShowCustomTextOnEachPiece, "Wys persoonlike teks op elke stuk");
	strcpy(sShowdiagramasatable, "Wys diagram as 'n tafel.");
	strcpy(sShowedgeband, "Wys rand bands");
	strcpy(sShowedgebandssettinginanewwindow, "Wys die instellings van die rand bands in 'n nuwe venster");
	strcpy(sShowgrindingsettingsinanewwindow, "Toon maal instellings in 'n nuwe venster");
	strcpy(sShowHorizontalLabelsAlways, "Wys altyd horisontale etikette");
	strcpy(sShowRemovethesizeofthepiecesinthecurrentsolution, "Wys / Verwyder die grootte van die stukke in die huidige oplossing.");
	strcpy(sShowRemovethesizeofthewastesinthecurrentsolution, "Wys / Verwyder die grootte van die afval in die huidige oplossing.");
	strcpy(sShowtotalcutlength, "Wys totale snylengte");
	strcpy(sShowtrimedgesettingsinanewwindow, "Wys die instellings van die gebreke in 'n nuwe venster");
	strcpy(sSimpleMaterialExists, "Naam van die materiaal is reeds gedefinieer in die lys van materiale. Gee dit asseblief 'n nuwe naam.");
	strcpy(sSinglePieceStrips, "Strepe, uit een stuk");
	strcpy(sSizes, "Groottes");
	strcpy(sSmallerorequalto, "Kleiner of gelyk aan");
	strcpy(sSort, "Soort");
	strcpy(sSortAscendingByArea, "Sorteer stygende deur die gebied");
	strcpy(sSortDescendingByArea, "Aflopend sorteer deur die gebied");
	strcpy(sSpecifyhowdifferentthepiecesinthelaststagecanbeValue0meansnodifference, "Spesifiseer hoe anders kan wees om die stukke in die laaste stadium. Waarde 0 beteken nie 'n verskil nie.");
	strcpy(sSpecifyifpiecesinthelaststagecanbedifferentornotdepeultimaetapapotfidiferitesaunucadimensiune, "Spesifiseer indien stukke in die laaste stadium kan anders wees of nie");
	strcpy(sSpecifyifthepiececanberotatedornotIfnotitwillbecutinthesamewayasitwasintroducedinDemandLengthofthepieceparalleltothelengthofthesheet, "Spesifiseer indien die stuk kan nie gedraai word of nie. Indien nie, sal uitgeroei word in dieselfde manier as dit is in aanvraag (die lengte van die stuk parallel met die lengte van die blad)");
	strcpy(sSpecifyinhowmanystageswemakethecutsDuringastageallcutshavethesamedirection, "Spesifiseer hoeveel stadiums ons maak die snitte.");
	strcpy(sStartthesearchprocess, "Begin die soektog proses");
	strcpy(sStatistics, "Statistiek");
	strcpy(sStatisticsE, "Verslae Ekstra");
	strcpy(sStatisticsforeachtypeofmaterial, "Statistiek vir elke tipe materiaa");
	strcpy(sStep, "Stap");
	strcpy(sStergeDepozit, "Jy wil die voorraad te verwyder?");
	strcpy(sStergeMaterial, "Verwyder materiaal?");
	strcpy(sStergePiesele, "Jy wil die stuk te verwyder?");
	strcpy(sStergePiesa, "Jy wil die stuk te verwyder?");
	strcpy(sStopthesearchprocess, "Stop die soektog proses");
	strcpy(sStrongoptimization, "Sterk optimalisering");
	strcpy(sSubtractthebandthicknessfrompiecesize, "Verlaag die stuk grootte met die bands dikte");
	strcpy(sSummary, "opsomming");
	strcpy(sSuprafataTotalaFolosita, "Totale gebruik oppervlak");
	strcpy(sSuprafatautilizata, "Benutting");
	strcpy(sSwitchbetweenfiberandrotationoption, "Skakel tussen vesel en rotasie opsie.");
	strcpy(sTechnical, "Tegniese");
	strcpy(sTechnicalsettings, "Tegniese instellings");
	strcpy(sTemporaryPanelHint, "Tydelike paneel vir die bewegende dele tussen die blaaie.");
	strcpy(sText, "teks");
	strcpy(sThe_application_has_expired, "Die program het verval.");
	strcpy(sThe_application_is_not_registered, "Die sagteware is nie geregistreer nie.");
	strcpy(sThe_application_was_first_started_on, "Die sagteware is die eerste keer begin op.");
	strcpy(sThecutsareperformedfromasidetotheothersideofthematerial, "Die debitering van 'n kant aan die ander kant van die materiaal.");
	strcpy(sThecuttingmachinecanfollowtheshapeofthematerial, "Die snymasjien kan volg die vorm van die stuk.");
	strcpy(sTheedgesofsheetsthatmustbetrimedduefaults, "Die kante van velle wat moet afgewerk word as gevolg van die foute");
	strcpy(sTheLargestSize, "Die grootste grootte");
	strcpy(sThenameofthecustomerforwhichyoucutthepiece, "Die naam van die kliënt wat jy sny die stuk.");
	strcpy(sThenameofyourcustomer, "Die naam van jou kliënt");
	strcpy(sThepiececanberotated, "Die stuk kan nie gedraai word");
	strcpy(sTheprogramtriestoavoidwasteswhichhavebothsizeslessthanthisvalue, "Die program probeer om te verhoed dat afval wat beide groottes minder as die waarde");
	strcpy(sThereAreNoProducts, "Daar is geen gedefinieerde produkte");
	strcpy(sThestockofmaterialhasbeenpreviouslyloadedfromanExcelorCSVformatPleaseloaditagain, "Die voorraad van die materiaal wat voorheen gelaai is uit 'n Excel of CSV formaat. Let laai dit weer as jy wil om te werk aan dit.");
	strcpy(sThetotallengthofcutting, "Die totale lengte van die sny");
	strcpy(sThewidthofthecuttingsawForglasscuttingoptimizationitcanbe0Forwooditshouldbegreaterthan0, "Die dikte van die saag. Vir glas sny dit kan 0 wees. Vir hout moet wees groter as 0.");
	strcpy(sThewidthofthecuttingsawforlinearpieces, "Die dikte van die saag vir lineêre stukke.");
	strcpy(sThickness, "Dikte");
	strcpy(sThischaracterisusedforfillingthewasterectanglesIfyoudonotwantfilledwastejustremovethischaracter, "Hierdie simbool word gebruik vir die vul van die afval reghoeke. As jy nie gevul afval wil net dit verwyder.");
	strcpy(sThisindexhasvaluebetween1andthenumberofpieces, "Dié indeks het 'n waarde tussen 1 en die aantal stukke.");
	strcpy(sThisOptionWillOverrideTheInventoryFileIfLoadedFromExcelOrCsvFiles, "Hierdie opsie sal die inventaris lêer ignoreer wanneer dit laai van Excel of CSV lêers.");
	strcpy(sThisProgramisLicensedTo, "Hierdie program is gelisensieer");
	strcpy(sThisvaluewillbeaddedtotheedgebandingmaterialoneachside, "Hierdie waarde word bygevoeg word aan die rand ringe materiaal aan elke kant");
	strcpy(sTipNevid, "Die tipe materiaal kan nie leeg wees nie.");
	strcpy(sTitle, "Tite");
	strcpy(sTools, "gereedskap");
	strcpy(sTop, "Top");
	strcpy(sTopcoordinateofthedefect, "Die top-koördinaat van die gebrek.");
	strcpy(sTotalGarbageWaste, "Alle weggegooi afval");
	strcpy(sTotalInventoryWaste, "Totale voorraad afval");
	strcpy(sTotalRecycledWaste, "Alle herwinbare afval");
	strcpy(sTotalusedarea, "Totale vir die gebied");
	strcpy(sTotalusedlength, "Totale gebruik lengte");
	strcpy(sTrigonometric, "Trigonometriese");
	strcpy(sTrim, "Sny");
	strcpy(sTrimalledgesatthebeginning, "Sny al die kante aan die begin");
	strcpy(sTrimEdge, "Sny die rand");
	strcpy(sTwoPanels, "2 panele");
	strcpy(sType, "tipe");
	strcpy(sTypeofmaterialfromwhichtocut, "Tipe materiaal uit te sny");
	strcpy(sTypesAreNotMatched, "Die optimalisering is nie uitgevoer nie! Materiaal van Onderdele en Voorraadtabelle stem nie ooreen nie! 'n Onderdeel kan slegs gesny word uit die materiaal met dieselfde naam in voorraad. Verander die materiaal se naam van die ooreenstemmende kolomme!");
	strcpy(sUndo, "Maak ongedaan");
	strcpy(sUndoAccept, "Herroep Aanvaar");
	strcpy(sUnits, "eenhede");
	strcpy(sUnregisteredVersion, "Ongeregistreerde");
	strcpy(sUpdates, "Opdateer");
	strcpy(sUsefulforwoodfurniture, "Nuttig vir hout meubels");
	strcpy(sUseit, "Gebruik dit");
	strcpy(sUsePieceinOptimization, "Gebruik die stuk in die optimalisering");
	strcpy(sUserName, "User name");
	strcpy(sUtilizationandWastes, "Benutting en afva");
	strcpy(sUtilizedArea, "Area van gebruik dele");
	strcpy(sUtilizedBars, "Gebruik bars");
	strcpy(sUtilizeddemandcount, "Aantal benut stukke");
	strcpy(sUtilizedParts, "Gebruik dele");
	strcpy(sUtilizedPieces, "Aangewend stukke");
	strcpy(sUtilizedSheets, "Gebruik velle");
	strcpy(sValue, "Waarde");
	strcpy(sValueGreaterEqualToZero, "Waarde moet groter of gelyk aan nu");
	strcpy(sValueGreaterThanZero, "Waarde moet groter wees as nu");
	strcpy(sValueIntegerNumber, "Die waarde moet 'n heelgetal getal wees!");
	strcpy(sValueRealNumber, "Die waarde moet 'n reële getal sal wees. Miskien het jy al gebruik word, in plaas van. of vice versa. Los dit asseblief!");
	strcpy(s_The_number_is_too_big_or_it_has_too_many_digits_after_decimal_separator, "Die getal is te groot of dit het te veel syfers na die desimale skeier!");
	strcpy(s_The_number_is_too_big, "Die getal is te groot!");
	strcpy(sVertical, "Vertikale");
	strcpy(sWaste, "Afval");
	strcpy(sWastes, "Afval");
	strcpy(sWasteAddedToWarehouse, "Scrap bygevoeg pakhuis");
	strcpy(sWastelimits, "perke vir afva");
	strcpy(sWasteType, "Soort afva");
	strcpy(sWeakoptimization, "Die swakste optimalisering");
	strcpy(sWhattoprint, "Wat moet ek druk");
	strcpy(s_What_to_print_or_save_to_file, "Wat om te druk of in lêer te stoor");
	strcpy(sWhattoprintoneachpiece, "Wat om te druk op elke stuk");
	strcpy(sWhattoshowoneachpiece, "Wat gebeur op elke stuk om te wys?");
	strcpy(sWidth, "Breedte");
	strcpy(sWood, "hout");
	strcpy(sWorkingDirectory, "Werk gids");
	strcpy(sWrongKey, "Verkeerde registrasie sleutel!");
	strcpy(sYes, "Ja");
	strcpy(sYoucannotchooseblackblueorredcolors, "You cannot choose black, blue or red colors.");
	strcpy(sYouCannotMixFractionalDataWithDecimalOnes, "Jy kan nie meng die fraksionele waardes met die werklike waardes!");
	strcpy(sYourcompany, "Jou maatskappy");
	strcpy(sZip, "Poskode");
	strcpy(s_Set_the_origin_and_the_direction_of_the_axes, "Stel die oorsprong en die rigting van die asse van koördinate.");










	strcpy(s_Number_of_digits_after_the_decimal_separator, "Aantal syfers na die desimale skeiding");
	strcpy(s_Percentages, "Persentasies");
}

