// Language strings: Finnish
// Author: Optimal Programs
// License: MIT License
//---------------------------------------------------------------------------
#include <string.h>
//---------------------------------------------------------------------------
#include "language_string_id.h"
//---------------------------------------------------------------------------
void set_fi(void)
{
	//finish
	//did not check manually
	// last update on: 2025.9.25.0
	strcpy(s_Area, "pinta-ala");
	strcpy(s_Mass, "Massa");
	strcpy(s_Advanced, "Edistynyt");
	strcpy(s_Relative_coordinates, "Suhteelliset koordinaatit");
	strcpy(s_Absolute_coordinates, "Absoluuttiset koordinaatit");
	strcpy(s_Append_more_rows, "Liitä lisää rivejä");

	strcpy(s_Add_to_parts, "Lisää osiin.");
	strcpy(s_Additional, "Lisätiedot");
	strcpy(s_All_results, "Kaikki tulokset.");
	strcpy(s_Allow_movement_of_pieces, "Salli kappaleiden liikkuminen");
	strcpy(s_Allow_part_in_part, "Anna pala palassa");
	strcpy(s_Invalid_piece_Angles_are_too_small_or_too_big_or_height_is_too_small, "Virheellinen kappale! Kulmat ovat liian pieniä tai liian suuria tai korkeus on liian pieni.");
	strcpy(s_Append, "Liitä");
	strcpy(s_As_it_is, "Niin kuin se on");
	strcpy(s_As_text, "Tekstinä");
	strcpy(s_Ascending, "nouseva");
	strcpy(s_Automatic, "Automaattinen");
	strcpy(s_Cannot_connect_to_the_Internet_Please_visit_our_website_from_a_browser, "Internet-yhteys ei onnistu! Käy verkkosivustollamme selaimesta.");
	strcpy(s_Cannot_copy_or_move_the_files, "Tiedostoja ei voi kopioida tai siirtää!");
	strcpy(s_Cannot_delete_the_file, "Tiedostoa ei voi poistaa!");
	strcpy(s_Cannot_modify_old_results, "Vanhoja tuloksia ei voi muokata!");
	strcpy(s_To_change_click_inside_a_cell_or_press_0_1_or_2, "Muuta napsauttamalla solun sisällä tai painamalla 0, 1 tai 2.");
	strcpy(s_Cell, "Cell");
	strcpy(s_Click_on_the_table_header_to_change_the_columns, "Napsauta taulukon otsikkoa muuttaaksesi sarakkeita.");
	strcpy(s_Close, "Sulje se");
	strcpy(s_Contact_us, "Ota meihin yhteyttä");
	strcpy(s_Column, "Sarake");
	strcpy(s_Comma, "Pilkku");
	strcpy(s_The_comma_symbol_cannot_simultaneously_be_the_list_separator_and_the_decimal_separator, "Pilkkumerkkiä ei voi käyttää samanaikaisesti luetteloerottimena ja desimaalierottimena!");
	strcpy(s_Copy, "Kopio");
	strcpy(s_Copy_for_move, "Kopeeri liikumiseks");
	strcpy(s_Cut_higher_level_strips_first, "Leikkaa ensin korkeamman tason nauhat");
	strcpy(s_Cut_index, "Näytä indeksi leikkaus");

	strcpy(s_The_data_have_been_changed_Do_you_want_to_save_them_to_a_file, "Tietoja on muutettu. Haluatko tallentaa ne tiedostoon?");
	strcpy(s_Decimal_separator, "Desimaalierotin");
	strcpy(s_Restore_default_settings, "Palauta oletusasetukset");
	strcpy(s_Delete_fiber, "Poista kuitu");
	strcpy(s_Descending, "Laskeva");
	strcpy(s_Discard_changes, "Hylkää muutokset");

	strcpy(s_Delete_all_data, "Poistetaanko kaikki tiedot?");
	strcpy(s_Dot, "Piste");
	strcpy(s_Do_you_want_to_delete_the_picture, "Haluatko poistaa kuvan?");
	strcpy(s_Do_you_want_to_delete_the_product, "Haluatko poistaa tuotteen?");
	strcpy(s_Duplicate_and_append, "Kopioi ja liitä.");
	strcpy(s_Duplicate_values_are_ignored, "Päällekkäiset arvot jätettiin huomiotta!");
	strcpy(s_Error, "Virhe");
	strcpy(s_Error_loading_file, "Virhe tiedoston lataamisessa.");
	strcpy(s_export_everything, "Vie kaikki");
	strcpy(s_Fit_to_screen, "Sovita näytölle.");
	strcpy(s_Force_fixed_height, "Piirrä palat kiinteällä korkeudella.");
	strcpy(s_Flipped, "Käännetty");
	strcpy(s_Import, "Tuonti");
	strcpy(s_If_angles_are_different_from_90_degrees_height_must_be_greater_than_0, "Jos kulmat poikkeavat 90 astetta, korkeuden on oltava suurempi kuin 0.");
	strcpy(s_Ignore, "Jättää huomiotta");
	strcpy(s_Incorrect_value, "Väärä arvo");
	strcpy(s_Info, "Tiedot");
	strcpy(s_Interior, "sisällä");
	strcpy(s_Give_a_name, "Anna nimi.");
	strcpy(s_Group, "Ryhmittele se");
	strcpy(s_Header, "Otsikko");
	strcpy(s_Keep_it_as_it_is, "Pidä se sellaisena kuin se on");
	strcpy(s_Level, "Level");
	strcpy(s_Licensee, "Lisenssinsaaja");
	strcpy(s_List_separator, "Listan erotin");
	strcpy(s_Made_with_love_in_Cugir_Romania, "Valmistettu rakkaudella: Cugir, Romania");
	strcpy(s_Made_in, "Valmistettu vuonna");
	strcpy(s_Manufacturer, "Valmistaja");

	strcpy(s_Manual_arrange, "Manuaalinen järjestys");

	strcpy(s_Mixed, "sekoitettu");
	strcpy(s_Multiple_shapes_detected_Next_rows_will_be_overwritten_Continue, "Useampi kuin yksi muoto havaittiin. Siksi seuraavat rivit korvataan. Jatkaa?");
	strcpy(s_More, "Lisää");
	strcpy(s_Multiple_values, "Useita arvoja");
	strcpy(s_No_texture, "Ei tekstuuria");
	strcpy(s_Number, "Määrä");
	strcpy(s_Number_of_images, "Kuvien määrä");
	strcpy(s_Number_of_vertices, "Kärkien lukumäärä");
	strcpy(s_Offset, "Offset");
	strcpy(s_Only_the_currently_selected_items, "Vain tällä hetkellä valitut kohteet.");
	strcpy(s_Optimizing_please_wait, "Optimoidaan... odota.");

	strcpy(s_Paste, "Paste");

	strcpy(s_Piece_label, "Näytä pala labe");
	strcpy(s_Piece_size, "Osoittavat koko kappaletta");
	strcpy(s_Please_contact_us_by_email_if_you_receive_this_error, "Ota yhteyttä sähköpostitse, jos saat tämän virheen.");
	strcpy(s_Please_save_it_first, "Tallenna se ensin.");
	strcpy(s_Position, "Sijainti");
	strcpy(s_Preview, "Esikatselu");
	strcpy(s_Rectangle, "Suorakulmio");

	strcpy(s_Redo_the_last_operation, "Palauta viimeinen toimenpide");
	strcpy(s_Regular_polygon, "Normaali monikulmio");

	strcpy(s_Reused, "Uudelleen käytetty");
	strcpy(s_Rotated, "Käännetty");
	strcpy(s_Save_all, "Tallenna kaikki");
	strcpy(s_Scrap_label, "Näytä jäte labe");
	strcpy(s_Scrap_size, "Osoittavat koko jätteiden");
	strcpy(s_Semicolon, "Puolipiste");
	strcpy(s_Show_cut_index, "Näytä indeksi leikkaus");
	strcpy(s_Show_information, "Näytä tiedot");
	strcpy(s_Show_piece_label, "Näytä pala labe");
	strcpy(s_Show_scrap_label, "Näytä jäte labe");
	strcpy(s_Show_scrap_s_size_on_the_small_pieces, "Näytä pienen kappaleen romun koko");
	strcpy(s_Show_size_of_pieces, "Osoittavat koko kappaletta");
	strcpy(s_Show_size_of_scrap, "Osoittavat koko jätteiden");
	strcpy(s_Show_sizes, "Näytä koot");
	strcpy(s_Show_label, "Näytä tunniste");
	strcpy(s_Show_length, "Näytä pituus");

	strcpy(s_Some_numerical_values_are_incorrect_Should_I_fix_all_the_incorrect_values, "Jotkut numeeriset arvot ovat vääriä! Pitäisikö minun korjata kaikki väärät arvot?");
	strcpy(s_Some_invalid_values_have_been_removed, "Jotkut virheelliset arvot on poistettu.");
	strcpy(s_Sort_by, "Järjestä");
	strcpy(s_Sort_ascending_by, "Lajittele nousevasti");
	strcpy(s_Sort_descending_by, "Lajittele laskevasti");
	strcpy(s_Start, "Start");
	strcpy(s_Starting_angle, "Lähtökulma");


	strcpy(s_Stock, "Varasto");
	strcpy(s_Stop, "Stop");
	strcpy(s_System_setting, "Järjestelmän asetukset");
	strcpy(s_Tabular, "Taulukkomainen");
	strcpy(s_Total, "Kaikki yhteensä");
	strcpy(s_Total_size, "Koko");
	strcpy(s_Terms_of_the_license, "Lisenssin ehdot");
	strcpy(s_The_current_product_has_been_changed_Do_you_want_to_save_it_to_file, "Nykyinen tuote on muutettu. Haluatko tallentaa sen tiedostoon?");
	strcpy(s_The_value_is_out_of_the_allowed_range, "Arvo on sallitun alueen ulkopuolella.");
	strcpy(s_The_value_must_be_a_real_or_fractional_number_Try_to_replace_the_comma_with_the_dot_if_you_want_to_enter_a_real_number, "Arvon on oltava todellinen tai murto-osa. Kokeile korvata pilkku pisteellä, jos haluat antaa todellisen luvun.");
	strcpy(s_This_feature_is_not_implemented_yet, "Tätä ominaisuutta ei ole vielä otettu käyttöön.");
	strcpy(s_This_operation_cannot_be_reversed, "Tätä toimintoa ei voi peruuttaa.");
	strcpy(s_Undo_the_last_operation, "Kumoa viimeinen toimenpide.");
	strcpy(s_Utilization, "Käyttö");
	strcpy(s_Utilized_Stock, "Käytetty varasto");
	strcpy(s_Version, "Versio");
	strcpy(s_Visible_columns, "Näkyvät sarakkeet");
	strcpy(s_You_already_have_the_latest_version_installed, "Sinulla on jo uusin versio asennettuna!");
	strcpy(s_What_is_exported, "Mitä viedään?");
	strcpy(s0meansanynumberofpieces, "Nolla tarkoittaa kappalemäärä");
	strcpy(sAbout, "Noin");
	strcpy(sAccept, "Hyväksyä");
	strcpy(sAcceptall, "Hyväksy kaikki");
	strcpy(sAcceptthecurrentsolution, "Hyväksy nykyisen ratkaisun");
	strcpy(sAdd, "Liitä");
	strcpy(sAddapiece, "Lisää pala");
	strcpy(sAddasimpleproducttoDemand, "Lisää tuote olevaan kysyntään.");
	strcpy(sAddgrindingthicknesstopartsize, "Lisää hionta paksuus pala kokoon");
	strcpy(sAddproductnametolabel, "Liitä tuotteen nimi tarran");
	strcpy(sAddress, "Osoite");
	strcpy(sAddselectedsizetoInventory, "Lisää valitut koon Inventory");
	strcpy(sAdhesivelabels, "Liima tarrat");
	strcpy(sAdhesivelabelwithinformationaboutpiecesinDemandCustomernameLabelSizeCurrentData, "Tarra tietoja kappaletta kysyntää: Asiakkaan nimi, Label, koko, Current Data.");
	strcpy(sAdhesivelabelwithinformationaboutsheetsinInventory, "Tarra tietoja arkkia Inventory.");
	strcpy(sAll, "Kaikki");
	strcpy(sAlloffcutswhichhavethesizegreaterthanthisvaluewillbeaddedtoInventory, "Kaikki palat jotka ovat kooltaan suurempia kuin tämä arvo lisätään Inventory");
	strcpy(sAllowMirroring, "Salli peilaus.");
	strcpy(sAllowRotation, "Salli Rotation");
	strcpy(sAllPieces, "Kaikki palaset");
	strcpy(sAllpredefinedproducts, "Kaikki ennalta tuotteet");
	strcpy(sAnewwindowwillbedisplayedwheretheusercansettheedgebandsforeachedge, "Uusi ikkuna avautuu, jossa käyttäjä voi asettaa reuna bändejä kunkin reunan");
	strcpy(sAnewwindowwillbedisplayedwheretheusercansetthegrindingvalueforeachedgeofthsheet, "uusi ikkuna tulee näkyviin, johon käyttäjä voi asettaa hionta-arvo kullekin reunan pala.");
	strcpy(sAnewwindowwillbedisplayedwheretheusercansetthetrimvalueforeachedgeofthsheet, "Uusi ikkuna avautuu, jossa käyttäjä voi määrittää vikoja kullekin reuna pala.");
	strcpy(sAngle, "Kulma");
	strcpy(sAngles, "Angles");
	strcpy(sAnoptimizationparameterisarealnumber, "optimointi parametri on todellinen numero.");
	strcpy(sAnoptimizationparameterisfractionalnumber, "optimointi parametri on murtoluku.");
	strcpy(sAnyShape, "Mikä tahansa muoto");
	strcpy(sApolygonmusthaveatleast2vertices, "Monikulmion on oltava vähintään 2 kärkipistettä!");
	strcpy(sApolygonmusthaveatleast2vertices, "Monikulmion on oltava vähintään 3 kärkipistettä!");
	strcpy(sApplication_fails_to_initialize, "Ohjelmisto epäonnistui alustus.");
	strcpy(sArc, "Arc");
	strcpy(sArcLength, "Kaaren pituus");
	strcpy(sAreaofusedsheets, "Alue käytettyjen levyjen");
	strcpy(sAshortdescriptionofthesheet, "Lyhyt kuvaus levyn");
	strcpy(sAtleastonepart, "Ainakin yksi kappale on otettava käyttöön.");
	strcpy(sAtTheMarginOfTheSheet, "Reunalla levyn");
	strcpy(sBandtypes, "Tyypit reuna bändi.");
	strcpy(sBar, "Baarit / putket");
	strcpy(sBars, "Baarit / putket");
	strcpy(sBothsizesoftheoffcutsmustbegreaterthanthisvalue, "Sekä koot palat on oltava suurempi kuin tämä arvo.");
	strcpy(sBottom, "Pohja");
	strcpy(sBottomcoordinateofthedefect, "Pohja-koordinaatti vika");
	strcpy(sBreakCut, "Riko leikkaus");
	strcpy(sBrowse, "selailla");
	strcpy(sBuy, "Ostaa");
	strcpy(sBuynow, "Osta nyt ...");
	strcpy(sCancel, "Peruuta se");
	strcpy(sCannotBeEmpty, "ei voi olla tyhjä!");
	strcpy(sCannotmovepartsbetweensheetswhenidenticalsheetsaregroupedPleaseungroupthesheetsfrommenu, "ei voi siirtää osia yhdestä levyn toiseen, jos sama levyt ryhmitellään. Peruuta ryhmittely arkkeja valikosta.");
	strcpy(sCannotSaveFile, "Ei voi tallentaa tiedostoa");
	strcpy(sCenter, "Keskus");

	strcpy(sChangeDirection, "Vaihda suuntaa");
	strcpy(sChoose, "Valita");
	strcpy(sChooseProduct, "Valitse tuote");
	strcpy(sCircle, "Ympyrä");
	strcpy(sCity, "Kaupunki");
	strcpy(sClear, "Tyhjennä");
	strcpy(sClockWise, "Myötäpäivään");
	strcpy(sClosewindow, "Sulje ikkuna");
	strcpy(sColor, "Väri");
	strcpy(sColorofedgeband, "Väri reunan band");
	strcpy(sColorPattern, "Väri / Pattern");
	strcpy(sColorpiecesandwastes, "Pieces ja jätteet värikäs.");
	strcpy(sColumns, "Sarakkeet");
	strcpy(sComment, "Kommentti");
	strcpy(sCompanyname, "Yrityksen nimi");
	strcpy(sComplexMaterialExists, "Nimi materiaali on jo määritelty luettelossa monimutkaisia ??aineita. Anna sille uusi nimi.");
	strcpy(sComputerCode, "Tietokone code");
	strcpy(sComputerCodefromyourcomputer, "Tietokoneen koodi (tietokoneesta)");
	strcpy(sComputethetotalpriceofDemand, "Laske kokonaishinta Kysynnän");
	strcpy(sContents, "Sisältö");
	strcpy(sContinutComanda, "Sisältö kysyntä päivä");
	strcpy(sContinutDepozit, "Sisältö Inventory Saapumispäivä");
	strcpy(sConversionIsDoneOnlyWhenSomePiecesHaveFractionalValues, "Muuntaminen tehdään vain silloin, jotkut palaset ovat Murtolukuarvot.");
	strcpy(sConvertsTheSizeOfWasteToAFractionalUnit, "Näyttää koko jätteen murtoarvon.");
	strcpy(sCouldNotSaveFile1, "Ei voitu kirjoittaa tiedostoa hakemistoon");
	strcpy(sCouldNotSaveFile2, "Sinulla ei ehkä ole tarpeeksi oikeuksia. Tarkista tai muuta työhakemistoon valikossa Asetukset | Työskentely hakemistoon kansioon, johon sinulla on oikeudet kirjoittaa (esim. c:\\temp).");
	strcpy(sCreationdateYMDHMS, "Creation date (Y / M / D, H: M: S)");
	strcpy(sCurrentDate, "nykyinen päivämäärä");
	strcpy(sCurrentDiagram, "Nykyinen kaavio");
	strcpy(sCurrentMaterial, "Nykyinen materiaali");
	strcpy(sCurrentversion, "Nykyinen versio");
	strcpy(sCurve_not_closed_Try_increasing_DXF_linking_distance_parameter, "Monikulmio ei ole suljettu! Kokeile lisätä parametria DXF-linkitysetäisyys.");
	strcpy(sCustomer, "Asiakas");
	strcpy(sCustomerName, "Asiakkaan nimi");
	strcpy(sCustomMessage, "Mukautettu viesti");
	strcpy(sCutlength, "Pituus on leikattu");
	strcpy(sCut, "Leikata");
	strcpy(sCuts, "Leikata");
	strcpy(sCutterThickness, "Leikkauspaksuus");
	strcpy(sData, "Tietojen");
	strcpy(sDataCannotBeEmpty, "Tiedot eivät voi olla tyhjiä!");
	strcpy(sDateymdhms, "Date (y / m / d / h / m / s)");
	strcpy(sDays_left_for_trial, "Days käytettävissä testaus ");
	strcpy(sDaysLeft, "päivää jäljellä");
	strcpy(sStandard, "Oletusarvo");
	strcpy(sDefaultInterface, "oletusliittymä");
	strcpy(sDefects, "Viat");
	strcpy(sDefectsManager, "Hallitse vikoja");
	strcpy(sDefectsofthematerialNopiecescanbeplacedinthefaultyzone, "Virheitä materiaalista. Ei osat voidaan sijoittaa viallinen vyöhykkeellä.");
	strcpy(sDelete, "Poistaa");
	strcpy(sDeletePiece, "Poista pala");
	strcpy(sDeleteRow, "Poista rivi");
	strcpy(sDemandutilization, "Hyödyntäminen kysyntä");
	strcpy(sDepozitulmodificat, "Hyödynnettiin kappaleet on poistettu. Edelleen on lisätty varastossa.");
	strcpy(sDepozitvid, "Varastossa on tyhjä");
	strcpy(sDesk, "kirjoituspöytä");
	strcpy(sDiagram, "Kaavio");
	strcpy(sDiagrams, "Kaaviot");
	strcpy(sDiagramasatable, "Kaavio taulukkona");
	strcpy(sDigits, "numerot");
	strcpy(sDimensiuniplaca, "Koko arkin");
	strcpy(sDirection, "Suuntaan");
	strcpy(sDistanceBetweenRows, "Etäisyys rivien");
	strcpy(sDonotuseit, "Älä käytä sitä");
	strcpy(sDownload, "ladata");
	strcpy(sDoYouWantToClearTheData, "Haluat poistaa tiedot?");
	strcpy(sDoYouWantToSaveDemand, "Osat ovat muuttuneet! Haluatko tallentaa muutokset?");
	strcpy(sDoYouWantToSaveParts, "Haluatko säästää osiin?");
	strcpy(sDoYouWantToSaveRepository, "Varastossa on muuttunut! Haluatko tallentaa muutokset?");
	strcpy(sDrawing, "piirustukset");
	strcpy(sDrawthesolutioncolorful, "Piirrä ratkaisu värikäs");
	strcpy(sDuplicateTypes, "Jotkut tyypit ovat päällekkäisiä! Poista kaksoiskappaleet");
	strcpy(sDuplicateTypesWithComplex, "Jotkut ainesten nimet jo luettelossa monimutkaisia ??tyyppejä! Poista kaksoiskappaleet");
	strcpy(sDuplicateValues, "Kuvat näkyvät arvot");
	strcpy(sEdgeband, "Bändit ja reunat");
	strcpy(sEdgebandingwhichisplacedontheedgesofyourpiecePleasedefineedgebandingtypesfromMaterialsEdgeBandingmenu, "Edge ryhmittelyä joka asetetaan reunat pala. Ole hyvä ja reuna juovia tyyppejä Materiaalit valikosta.");
	strcpy(sEdgebandsthatwillbeappliedtoeachpart, "Edge bändejä, joita sovelletaan kuhunkin osaan.");
	strcpy(sEdgeBandTolerance, "Suvaitsevaisuus ja reuna juovia");
	strcpy(sEdgesthatmustbecutduefaults, "Reunat on leikattava, koska viat.");
	strcpy(sEdgetoedge, "Reunasta reunaan");
	strcpy(sEdit, "Muokata");
	strcpy(sEmail, "Sähköposti");
	strcpy(sEmptyData, "Tiedot ovat tyhjiä!");
	strcpy(sEnabled, "Käytössä");
	strcpy(sEnabledisabledefectsoftheinventorysheets, "Päälle / pois virheitä varastosta");
	strcpy(sEnterLabel, "Tulo labe");
	strcpy(sEnterTheMaterialName, "Tulo nimi materiaalin");
	strcpy(sEnterTheProductName, "Syötä tuotteen nimi");
	strcpy(sEvaluationError, "Virheen ilmaisun arviointia!");
	strcpy(sExit, "Uloskäynti");
	strcpy(sExpired, "Ohjelmisto on vanhentunut! Ilmoittautumiset ohjelmisto!");
	strcpy(sExport, "Vienti");
	strcpy(sExportAllDiagrams, "Vie kaikki kaaviot");
	strcpy(sExportAllToASingleFile, "Vie kaikki yhteen tiedostoon");
	strcpy(sExportOptions, "Vie vaihtoehtoja.");
	strcpy(sExporttoDXFformat, "Vie DXF");
	strcpy(sExporttoExcel, "Vie Exceliin");
	strcpy(sExpresieIncorecta, "Virheellinen matemaattinen lauseke!");
	strcpy(sExtensions, "laajennukset");
	strcpy(sExtra, "Extra");
	strcpy(sExtraComponents, "Lisäkomponenttien");
	strcpy(sExtracomponentsattachedtoDemand, "Lisäkomponenttien kiinnitetty osiin");
	strcpy(sFile, "Tiedosto");
	strcpy(sFileName, "Tiedoston nimi");
	strcpy(sFillWastes, "Piirrä jätteen vinoviivat");
	strcpy(sFindoptimalbarsheetsize, "Etsi optimaalinen koko putkien ja levyjen.");
	strcpy(sFindoptimalsizeofInventorypieces, "Etsi optimaalinen koko varastossa kp");
	strcpy(sFirstcutMultiplestages, "Ensimmäinen leikkaus suuntaan - Useita vaiheita");
	strcpy(sFirstdirectionforcutishorizontal, "Ensimmäinen suunta leikkaus on vaakasuora.");
	strcpy(sFirstdirectionforcutisvertical, "Ensimmäinen suunta leikkaus on pystysuora.");
	strcpy(sFollowthecontourofpieces, "Myötäilemään kappaletta");
	strcpy(sFont, "Font");
	strcpy(sFontsize, "Fonttikoko");
	strcpy(sFullInfo, "Täydelliset tiedot");
	strcpy(sDisposedWaste, "Hävitetty jäte");
	strcpy(sGeneral, "Genera");
	strcpy(sGenerateCNC, "Luo CNC");
	strcpy(sGrain, "Rakenne");
	strcpy(sGraindirection, "Kuitosuunta");
	strcpy(sGraphic, "Graafinen");
	strcpy(sGreaterorequalto, "Suurempi tai yhtä suuri kuin");
	strcpy(sGrid, "taulukot ");
	strcpy(sGrinding, "hionta paksuus");
	strcpy(sGrosimeTaieturaScalata, "Leikkaus paksuus tästä kuvasta saattaa olla erilainen kuin todellinen, koska palaset eivät ole edustettuina niiden todellisen laajuuden. Tämä seikka ei vaikuta tuloksiin.");
	strcpy(sGroupidenticallayouts, "Ryhmittely sama arkkia");
	strcpy(sGroupIdenticalParts, "Identtiset osat ryhmitellään.");
	strcpy(sGroupingOfIdenticalPiecesIntoOneRow, "Ryhmittely samanlaisia ​​paloiksi yhden rivin.");
	strcpy(sGroupPartsAfterLoadingFromFile, "Ryhmittely osat kuormituksen jälkeen tiedostosta");
	strcpy(sHeight, "Korkeus");
	strcpy(sHeighttolerance, "Suvaitsevaisuus ja korkeus");
	strcpy(sHelp, "Apua");
	strcpy(sHistory, "Historia");
	strcpy(sHorizontal, "Vaakasuora");
	strcpy(sHowtodisplayprintedgebands, "Miten se näkyy reuna bändejä?");
	strcpy(sIfyousetthebandforoneedgeallwillreceivethesamevalue, "Jos asetat yhtyeen toisessa reunassa, kaikki saavat saman arvon.");
	strcpy(sIfyousetthegrindingforoneedgeallwillreceivethesamevalue, "Jos asetat hionta arvon toiseen reunaan, kaikki reunat saavat saman arvon.");
	strcpy(sIfyousetthetrimforoneedgeallwillreceivethesamevalue, "Jos määrität rajauksen yksi reuna, kaikki reunat saavat saman arvon.");
	strcpy(sImageBounds, "Bounds kuvien");
	strcpy(sImageSize, "Kuvan koko");
	strcpy(sImportData, "Tuo tiedot");
	strcpy(sIncorrectPassword, "Väärä salasana");
	strcpy(sIndex, "indeksi");
	strcpy(sInformationaboutcustomer, "Tietoa asiakkaiden");
	strcpy(sInputALanguageName, "Anna nimi kieltä");
	strcpy(sInsert, "Aseta");
	strcpy(sInsertPiece, "Aseta pala");
	strcpy(sInterface, "Liitäntä");
	strcpy(sInterfaceSettings, "Liitäntäasetukset");
	strcpy(sInvalidHardware, "En voinut havaita laitteisto. Ota yhteyttä contact@optimalprograms.com");
	strcpy(sInvalidNumber, "Virheellinen numero");
	strcpy(sInvalidOrderOfComputation, "Jotta laskemaan pituuksia ei voida määrittää. On pyöreitä suhteet tuotteen määritelmään!");
	strcpy(sInvalidRegistration, "Rekisteröityminen on virheellinen!");
	strcpy(sInvalidTime, "Aika järjestelmä on pätemätön.");
	strcpy(sInventory, "VARASTO");
	strcpy(sisafractionalvalue, "on murto-arvo.");
	strcpy(sIsArc, "On kaari");
	strcpy(sisarealvalue, "on todellinen arvo.");
	strcpy(sLabel, "Etiketti");
	strcpy(sLabels, "Tarrat");
	strcpy(sLanguage, "Kieli");
	strcpy(sLatimeanumar0, "Leveyden tulee olla suurempi kuin 0!");
	strcpy(sLatimeanumarreal, "Leveyden on oltava reaaliluku!");
	strcpy(sLayerName, "Kerroksen nimi");
	strcpy(sLeft, "Vasen");
	strcpy(sLeftcoordinateofthedefect, "Vasemmalla koordinaatti vika");
	strcpy(sLength, "Pituus");
	strcpy(sLengthofthepiecestocut, "Piece koko leikkaus");
	strcpy(sLengthofthepiecestocutfrom, "Sheet size leikkaus");
	strcpy(sLengthofusedbars, "Koko käytettyjen baareja");
	strcpy(sLicenseAgreement, "Käyttöoikeussopimus");
	strcpy(sLinear, "Linear");
	strcpy(sLinethickness, "Paksuus kynä");
	strcpy(sLoadafileandappenddatatothecurrentDemand, "Lataa tiedosto ja liittää tiedot nykyistä kysyntää.");
	strcpy(sLoadanexistingDemandfromafile, "Aseta olemassa kysyntä tiedostosta.");
	strcpy(sLoadAppend, "Lataa ja Liitä");
	strcpy(sLoadEverything, "kuorman kaiken");
	strcpy(sLoadInventory, "Lataa varastosta");
	strcpy(sLoadInventoryandDemand, "Lataa varastosta ja kysynnän");
	strcpy(sLoadResults, "Kuorman tulokset");
	strcpy(sLocked, "kiinni");
	strcpy(sLogo, "logo");
	strcpy(sLong, "Pitkä");
	strcpy(sLongerexecutiontime, "Pidempi suoritusaika");
	strcpy(sLungime, "Leveys");
	strcpy(sLungimeanumar0, "Pituuden on oltava suurempi kuin 0!");
	strcpy(sLungimeanumarreal, "Pituuden on oltava reaaliluku!");
	strcpy(sLungimeaTotalaFolosita, "Käytössä oleva pituus");
	strcpy(sMagnification, "Suurennos");
	strcpy(sMagnify, "Suurentaa");
	strcpy(sMargins, "Marginaalit");
	strcpy(sMarginsForPaper, "Marginaalit paperin");
	strcpy(sMarginsOfTheLabel, "Marginaalit Merkinnän");
	strcpy(sMaterial, "Materiaali");
	strcpy(sMaterialName, "Nimi materiaalin");
	strcpy(sMaterials, "tarvikkeet");
	strcpy(sMaterialstypes, "Materiaalit tyypit");
	strcpy(sMax, "max");
	strcpy(sMaximalArea, "Maksimaalinen alue");
	strcpy(sMaximalCutLength, "Maksimaalinen lastuamispituus");
	strcpy(sMaxlength, "Suurin pituus");
	strcpy(sMaxPiecesperBar, "Max Kappaletta Bar");
	strcpy(sMaxwidth, "Maksimaalinen leveys.");
	strcpy(sMeasurementUnit, "Mittayksikkö");
	strcpy(sMin, "minun");
	strcpy(sMinimalBreakSize, "Minimal repeämä koko");
	strcpy(sMinimalUsefulSize, "Minimal hyödyllinen koko");
	strcpy(sMinimalwastesizetoInventory, "Vähän jätettä kooksi Inventory");
	strcpy(s_What_to_minimize, "Mitä minimoida?");
	strcpy(sMinlength, "Minimal pituus");
	strcpy(sMinwidth, "Minimal leveys");
	strcpy(sMirror, "Peili");
	strcpy(sMirroring, "Peilaus");
	strcpy(sMiscellaneous, "Muut");
	strcpy(sModify, "Muokata");
	strcpy(sModifytheselectedpiece, "Muokkaa valitun kappaleen");
	strcpy(sMovePiece, "Siirrä pala.");
	strcpy(sMultiplestages, "Useita vaiheita ja");
	strcpy(sName, "Nimi");
	strcpy(sNameofedgeband, "Nimi reuna bändejä");
	strcpy(sNewDEMANDUnsaveddatawillbelost, "Uudet osat? Tallentamattomat tiedot häviävät!");
	strcpy(sNewLanguage, "Uusi kieli");
	strcpy(sNewMaterial, "Uutta materiaalia");
	strcpy(sNewPasswordincorectlyintroduced, "Uusi salasana väärin käyttöön!");
	strcpy(sNewProduct, "Uusi tuote");
	strcpy(sNewversion, "Uusi versio");
	strcpy(sNo, "Ei");
	strcpy(sNumarBucati, "Kappalemäärä");
	strcpy(sNumberOfCopies, "Kopioiden määrä");
	strcpy(sNumberofstages, "Useampia vaiheita");
	strcpy(sNusuficienteplacidepozit, "Ei kaikki palaset on optimoitu. Mahdolliset syyt: Ei ole tarpeeksi kappaletta varastossa, Piece ei hyödynnetty optimointi; Materiaalit kysynnästä ja Inventory eivät vastaa; Muut parametrit on väärin asetettu.");
	strcpy(sOfficeNotInstaled, "Microsoft Office ei ole asennettu tietokoneelle tai incorect versio on asennettu!");
	strcpy(sOldpassworddoesnotmatch, "Vanha salasana ei täsmää!");
	strcpy(sOnlinehelp, "Online-ohjeet");
	strcpy(sOnlypiecesofthesameheightinthelaststage, "Kappaletta samalla korkeudella viimeisessä vaiheessa.");
	strcpy(sOpen, "Avoinna");
	strcpy(sOptimization, "Optimointi");
	strcpy(sOptimizationDone, "Optimointi tehdään! Voit tulostaa tai tallentaa saadut kaaviot. Paina painiketta Hyväksy jos olet tyytyväinen nykyiseen ratkaisuun. Muussa tapauksessa paina Start uudelleen.");
	strcpy(sOptimizationType, "Optimointi tyyppi");
	strcpy(sOptions, "vaihtoehdot");
	strcpy(sOptionsrelatedtotheinterface, "Asetukset liittyvät käyttöliittymä");
	strcpy(sor, "tai");
	strcpy(sOthercomponents, "Muut");
	strcpy(sOthers, "Muut");
	strcpy(sOtherstatistics, "Muut tilastot");
	strcpy(sOverrideExcelCSVfiles, "Ohita Excel / CSV-tiedostoja");
	strcpy(sParameter, "Parametri");
	strcpy(sParts, "OSAT");
	strcpy(sPattern, "Kuvio");
	strcpy(sPatternforwaste, "Pattern jätteiden");
	strcpy(sPerimeter, "Ympärysmitta");
	strcpy(sPermitedRotationAngle, "Kiertokulma, että on sallittua.");
	strcpy(sPhone, "Puhelin");
	strcpy(sPicture, "Kuva");
	strcpy(sPiece, "Pala");
	strcpy(sPieceindex, "Piece hakemistosta");
	strcpy(sPieces, "Kappaleita");
	strcpy(sPiecesize, "Piece koosta");
	strcpy(sPiecesizelabeledgebandwillbeprinted, "Piece koko, merkki, reuna bändejä tulostetaan.");
	strcpy(sPierdere, "Jätteet");
	strcpy(sPixels, "pikseliä");
	strcpy(sPlacilefolositeDepozit, "Käytetyt paloja Inventory.");
	strcpy(sPlease_contact_us_at_contact_nestingtechnologies_com, "Ota yhteyttä milloin contact@nesting-technologies.com");
	strcpy(sPlease_contact_us_at_contact_optimalprograms_com, "Ota yhteyttä milloin contact@optimalprograms.com");
	strcpy(sPleaseenteralldataeitherasfractionalorrealDonotmixthem, "Anna kaikki tiedot joko murto-tai todellista! Älä sekoita niitä!");
	strcpy(sPleaseEnterSomeTypesOfMaterials, "Ei ole mitään materiaalin tyyppi on määritelty. Voit määritellä ne materiaalit valikosta.");
	strcpy(sPleasesendtheNameandtheCodetotheaddresscontactoptimalprogramscominordertoobtaintheRegistrationKey, "Saadakseen Registration Key lähetä nimi ja säännöstön: contact@optimalprograms.com.");
	strcpy(sPolygon, "Polygon");
	strcpy(sPolygonsCircles, "Polygons, ympyrät");
	strcpy(sPrecision, "Tarkkuus");
	strcpy(sPretulnumar0, "Hinnan on oltava suurempi kuin 0!");
	strcpy(sPretulnumarreal, "Hinta pitää olla reaaliluku!");
	strcpy(sPreview, "Esikatselu");
	strcpy(sPrice, "Hinta");
	strcpy(sPriceMustBeGreaterThanZero, "Hinta on oltava suurempi kuin nolla");
	strcpy(sPriceofbars, "Hinta baareja");
	strcpy(sPriceperbar, "Hinta per bar");
	strcpy(sPricepersheet, "Hinta per arkki");
	strcpy(sPricepersquareunitofmaterial, "Hinta per neliö yksikköä materiaalia.");
	strcpy(sPriceperunit, "Yksikköhinta");
	strcpy(sPriceperunit, "Yksikköhinta");
	strcpy(sPrint, "Tulosta");
	strcpy(sPrintdiagramsastables, "Tulosta kaaviot taulukkomuodossa.");
	strcpy(sPrinter, "Kirjoitin");
	strcpy(sPrinterBounds, "Marginaalit tulostimen");
	strcpy(sPrintonlyutilizedarea, "Tulosta vain hyödyntää ala");
	strcpy(sPrintthecontentsoftheDemand, "Tulosta sisältö kysyntä.");
	strcpy(sPrintthecontentsoftheInventory, "Tulosta sisällön varastosta.");
	strcpy(sPrintthecurrentsolution, "Tulosta ratkaisulta.");
	strcpy(sPriority, "Prioriteetti");
	strcpy(sPrioritytocutapieceZero0isthehighestpriority, "Prioriteetti leikata pala. Nolla (0) on korkein prioriteetti.");
	strcpy(sProcentul0100, "Prosentit on oltava suurempi kuin 0 ja pienempi tai yhtäsuuri kuin 100!");
	strcpy(sProcentulnumarreal, "Prosentit pitää olla reaaliluku!");
	strcpy(sProductdefinition, "Tuotteen määritelmä");
	strcpy(sProductExists, "Tuote on jo olemassa. Valitse toinen nimi.");
	strcpy(sProductName, "Tuotteen nimi");
	strcpy(sProducts, "Tuote");
	strcpy(sProducts, "Tuotteet");
	strcpy(sProject, "Hanke");
	strcpy(sProperties, "Ominaisuudet");
	strcpy(sProperty, "omaisuus");
	strcpy(sQuantity, "Määrä");
	strcpy(sQuantitynumberofsheetsofthistype, "Arkkien Tämän tyyppinen");
	strcpy(sRadius, "Säde");
	strcpy(sRectangular, "Suorakulmainen");
	strcpy(sRedefinetypesofedgeband, "Määritä eri reuna bändi");
	strcpy(sRedefinetypesofmaterial, "Redefine materiaaleille");
	strcpy(sRegistration, "Rekisteröinti");
	strcpy(sRegistrationKeyfromOptimalPrograms, "Rekisteröinti Key");
	strcpy(sRegistrationSuccessful, "Ilmoittautuminen onnistuu!");
	strcpy(sRemoveallpiecesinInventory, "Poista kaikki palaset varaston.");
	strcpy(sRemoveCut, "Poista leikata");
	strcpy(sRemovetheselectedpiece, "Poista valittu kappale");
	strcpy(sReports, "Raportit");
	strcpy(sRequestedMaterial, "Pyydetty materiaali");
	strcpy(sRestore, "Palauttaa");
	strcpy(sResults, "Tulokset");
	strcpy(sReusedwaste, "Uudelleen jätteet");
	strcpy(sRight, "Oikein");
	strcpy(sRightcoordinateofthedefect, "Koordinaatit virhe oikealta");
	strcpy(sRotation, "Kierto");
	strcpy(sRotationAngle, "Kiertokulma.");
	strcpy(sRotationStep, "Kierto aske");
	strcpy(sRoundAllFractionsTo, "Murtolukuarvot on pyöristettävä");
	strcpy(sRow, "rivi");
	strcpy(sRows, "Rivit");
	strcpy(sRun, "Uusimmat ratkaisut");
	strcpy(sRunningtime, "käyntiaika");
	strcpy(sSameforall, "Sama kaikille");
	strcpy(sSave, "Säästää");
	strcpy(sSaveAllImages, "Tallenna kaikki kuvat");
	strcpy(sSaveAs, "Tallenna");
	strcpy(sSaveChanges, "Kysyntä on muutettu. Haluatko säästää?");
	strcpy(sSaveCurrentImage, "Tallenna tämä kuva");
	strcpy(sSavedataparameters, "Tallenna tiedot ja parametrit");
	strcpy(sSaveEverything, "Tallenna kaiken");
	strcpy(sSaveInventory, "Tallenna Inventory");
	strcpy(sSaveInventoryandDemand, "Tallenna Varaston ja kysyntä");
	strcpy(sSaveResults, "Tallenna tulokset");
	strcpy(sSaveStatisticsinafile, "Tallenna tilastot tiedostoon");
	strcpy(sSavethecurrentimage, "Tallenna nykyinen kuva");
	strcpy(sSavethecurrentimageorstatistic, "Tallenna nykyinen kuva tai tilastotieto");
	strcpy(sSavetheDEMANDinafile, "Tallenna tiedostoon");
	strcpy(sSavetheDemandinafilewithadifferentname, "Tallenna kysyntä tiedoston eri nimellä.");
	strcpy(sSavetheREPOSITORYinafile, "Tallenna kuvaustietokannan tiedostoon");
	strcpy(sSerialNumber, "Rekisteröinti avain");
	strcpy(sService, "palvelu");
	strcpy(sSetDefaultValues, "Tämä palauttaa kaikki parametrit niiden oletusarvoihin. Kaikki asetuksesi häviävät. Oletko varma että haluat tehdä tämän?");
	strcpy(sSetedgeband, "Aseta reuna bändi");
	strcpy(sSetedgetrim, "Aseta leikkaus vikojen osalta reunojen");
	strcpy(sSetthesameedgebandforalledges, "Aseta samasta reunasta bändin kaikki reunat");
	strcpy(sSetthesamegrindingforalledges, "Aseta sama hionta kaikkien reunojen.");
	strcpy(sSetthesametrimforalledges, "Säädä sama leikkaaminen virheistä kaikkien reunojen");
	strcpy(sSettings, "Asetukset");
	strcpy(sShape, "Muoto");
	strcpy(sSheet, "Arkki");
	strcpy(sSheetsBarstypes, "Sheets_putket tyypit");
	strcpy(sSheetSize, "Koko arkin");
	strcpy(sSheetsperPage, "Sheets per sivu");
	strcpy(sShort, "Lyhyt");
	strcpy(sShorterexecutiontime, "Lyhyt ajoaika");
	strcpy(sShowallsimpleproducts, "Näytä kaikki yksinkertaiset tuotteet");
	strcpy(sShowcustomername, "Show asiakkaan nimi");
	strcpy(sShowCustomTextOnEachPiece, "Näytä mukautetun tekstin kustakin");
	strcpy(sShowdiagramasatable, "Näytä kaavio niin pöytä.");
	strcpy(sShowedgeband, "Näytä reuna bändejä");
	strcpy(sShowedgebandssettinginanewwindow, "Näytä asetukset reuna bändejä uudessa ikkunassa.");
	strcpy(sShowgrindingsettingsinanewwindow, "Näyttää hionta asetukset uuteen ikkunaan.");
	strcpy(sShowHorizontalLabelsAlways, "Näytä aina vaaka tarrat");
	strcpy(sShowRemovethesizeofthepiecesinthecurrentsolution, "Osoittavat / poisto koko kappaletta nykyisen liuokseen.");
	strcpy(sShowRemovethesizeofthewastesinthecurrentsolution, "Osoittavat / poisto koon jätteiden nykyisen liuokseen.");
	strcpy(sShowtotalcutlength, "Näytä koko leikkauspituus");
	strcpy(sShowtrimedgesettingsinanewwindow, "Näytä asetukset vikoja uudessa ikkunassa.");
	strcpy(sSimpleMaterialExists, "Nimi materiaali on jo määritelty materiaalien luetteloon. Anna sille uusi nimi.");
	strcpy(sSinglePieceStrips, "Stripes yhdestä kappaleesta.");
	strcpy(sSizes, "Koot");
	strcpy(sSmallerorequalto, "Pienempi tai yhtä suuri kuin");
	strcpy(sSort, "Järjestellä");
	strcpy(sSortAscendingByArea, "Lajittele nousevasti alueittain");
	strcpy(sSortDescendingByArea, "Järjestä laskevasti alueittain");
	strcpy(sSpecifyhowdifferentthepiecesinthelaststagecanbeValue0meansnodifference, "Määritä, miten erilaiset voivat palaset viimeisessä vaiheessa. Arvo 0 tarkoittaa eroa.,");
	strcpy(sSpecifyifpiecesinthelaststagecanbedifferentornotdepeultimaetapapotfidiferitesaunucadimensiune, "Määritä, palat viime vaiheessa voi olla erilaisia ??tai ei");
	strcpy(sSpecifyifthepiececanberotatedornotIfnotitwillbecutinthesamewayasitwasintroducedinDemandLengthofthepieceparalleltothelengthofthesheet, "On mainittava, onko kappale voidaan pyörittää tai ei. Jos näin ei ole, se leikkaa samalla tavalla kuin se tuotiin kysyntä (pituus pala samanaikaisesti pituus arkki),");
	strcpy(sSpecifyinhowmanystageswemakethecutsDuringastageallcutshavethesamedirection, "Määritä, kuinka monta vaihetta voimme tehdä leikkauksia.");
	strcpy(sStartthesearchprocess, "Aloita haku");
	strcpy(sStatistics, "Tilasto");
	strcpy(sStatisticsE, "Raportit Extra");
	strcpy(sStatisticsforeachtypeofmaterial, "Tilasto kullekin aineiston");
	strcpy(sStep, "Vaihe");
	strcpy(sStergeDepozit, "Haluat poistaa Inventory?");
	strcpy(sStergeMaterial, "Poista materiaali?");
	strcpy(sStergePiesele, "Haluat poistaa pala?");
	strcpy(sStergePiesa, "Haluat poistaa pala?");
	strcpy(sStopthesearchprocess, "Lopeta hakuprosessia");
	strcpy(sStrongoptimization, "Vahva optimointi");
	strcpy(sSubtractthebandthicknessfrompiecesize, "Pienennä pala koon bändien paksuus.");
	strcpy(sSummary, "yhteenveto");
	strcpy(sSuprafataTotalaFolosita, "Yhteensä käytetyt pinta-");
	strcpy(sSuprafatautilizata, "Käyttö");
	strcpy(sSwitchbetweenfiberandrotationoption, "Siirtyminen kuidun ja kierto vaihtoehto.");
	strcpy(sTechnical, "Tekninen");
	strcpy(sTechnicalsettings, "Tekniset asetukset");
	strcpy(sTemporaryPanelHint, "Tilapäinen paneeli liikkuvia osia levyjen väliin.");
	strcpy(sText, "Teksti");
	strcpy(sThe_application_has_expired, "Ohjelma on päättynyt.");
	strcpy(sThe_application_is_not_registered, "Ohjelmisto ei ole rekisteröity.");
	strcpy(sThe_application_was_first_started_on, "Ohjelmisto oli ensimmäinen alkoi.");
	strcpy(sThecutsareperformedfromasidetotheothersideofthematerial, "Veloituksen suoritettavia puolelta sen toiselle puolelle materiaalista.");
	strcpy(sThecuttingmachinecanfollowtheshapeofthematerial, "Leikkuri voi seurata muodon pala.");
	strcpy(sTheedgesofsheetsthatmustbetrimedduefaults, "Reunat arkkeja, jotka on leikattu, koska vikojen");
	strcpy(sTheLargestSize, "Suurin koko");
	strcpy(sThenameofthecustomerforwhichyoucutthepiece, "Asiakkaan nimi, jota varten leikattu pala.");
	strcpy(sThenameofyourcustomer, "Nimi asiakkaan");
	strcpy(sThepiececanberotated, "Kappale voidaan kääntää");
	strcpy(sTheprogramtriestoavoidwasteswhichhavebothsizeslessthanthisvalue, "Ohjelma yrittää välttää jätteet, jotka on molemmat puolet pienempi kuin tämä arvo");
	strcpy(sThereAreNoProducts, "Ei ole määritelty tuotteita vielä");
	strcpy(sThestockofmaterialhasbeenpreviouslyloadedfromanExcelorCSVformatPleaseloaditagain, "Varastossa materiaalia on aiemmin ladataan Excel-tai CSV-muodossa. Ole hyvä ja lataa se uudelleen, jos haluat työstää sitä.");
	strcpy(sThetotallengthofcutting, "Kokonaiskesto leikkaus");
	strcpy(sThewidthofthecuttingsawForglasscuttingoptimizationitcanbe0Forwooditshouldbegreaterthan0, "Paksuus sahan. Lasinleikkausta se voi olla 0. Puun sen tulisi olla suurempi kuin 0.");
	strcpy(sThewidthofthecuttingsawforlinearpieces, "Paksuus sahan lineaarista osaa.");
	strcpy(sThickness, "Paksuus");
	strcpy(sThischaracterisusedforfillingthewasterectanglesIfyoudonotwantfilledwastejustremovethischaracter, "Tätä symbolia käytetään täyttämiseen jätteen poistossa. Jos et halua täynnä jätettä vain poistaa sen.");
	strcpy(sThisindexhasvaluebetween1andthenumberofpieces, "Tämä indeksi on arvo välillä 1 ja määrä kappaletta.");
	strcpy(sThisOptionWillOverrideTheInventoryFileIfLoadedFromExcelOrCsvFiles, "Tämä vaihtoehto korvaa varaston tiedosto, jos ladataan Excel-tai CSV-tiedostoja.");
	strcpy(sThisProgramisLicensedTo, "Tämä ohjelma on lisensoitu");
	strcpy(sThisvaluewillbeaddedtotheedgebandingmaterialoneachside, "Tämä arvo lisätään reuna juovia materiaalin molemmille puolille");
	strcpy(sTipNevid, "Tyyppinen materiaali ei voi olla tyhjä.");
	strcpy(sTitle, "Otsikko");
	strcpy(sTools, "Työkalut");
	strcpy(sTop, "Top");
	strcpy(sTopcoordinateofthedefect, "Top koordinaatti vika.");
	strcpy(sTotalGarbageWaste, "Kaikki romuksi");
	strcpy(sTotalInventoryWaste, "Yhteensä varastossa jätettä");
	strcpy(sTotalRecycledWaste, "Kaikki kierrätysjätteiden");
	strcpy(sTotalusedarea, "Yhteensä käytetty ala");
	strcpy(sTotalusedlength, "Yhteensä käytetty pituus");
	strcpy(sTrigonometric, "Trigonometriset");
	strcpy(sTrim, "Trimmata");
	strcpy(sTrimalledgesatthebeginning, "Leikata kaikki reunat alussa");
	strcpy(sTrimEdge, "Leikkaa reunan");
	strcpy(sTwoPanels, "2 paneelit");
	strcpy(sType, "tyyppi");
	strcpy(sTypeofmaterialfromwhichtocut, "Tyyppistä materiaalia, joka on leikattu");
	strcpy(sTypesAreNotMatched, "Optimointia ei suoritettu! Osa- ja varastotaulukoiden materiaalit eivät täsmää! Osan voi leikata vain samannimisestä varastossa olevasta materiaalista. Muuta materiaalien nimiä vastaavista sarakkeista!");
	strcpy(sUndo, "Kumoa");
	strcpy(sUndoAccept, "Kumoa Hyväksy");
	strcpy(sUnits, "yksiköt");
	strcpy(sUnregisteredVersion, "Rekisteröimätön");
	strcpy(sUpdates, "Päivitykset");
	strcpy(sUsefulforwoodfurniture, "Hyödyllinen puukalusteet");
	strcpy(sUseit, "Käytä sitä");
	strcpy(sUsePieceinOptimization, "Käytä pala optimointi");
	strcpy(sUserName, "Käyttäjätunnus");
	strcpy(sUtilizationandWastes, "Käyttöaste ja jätteet");
	strcpy(sUtilizedArea, "Alue hyödynnetään osia");
	strcpy(sUtilizedBars, "Käytetyt tangot");
	strcpy(sUtilizeddemandcount, "Määrä hyödynnetään kappaletta.");
	strcpy(sUtilizedParts, "Käytetyt osat");
	strcpy(sUtilizedPieces, "Hyödynnetään kappaletta");
	strcpy(sUtilizedSheets, "Käytetyt levyt");
	strcpy(sValue, "Arvo");
	strcpy(sValueGreaterEqualToZero, "Arvon on oltava suurempi tai yhtä suuri kuin nolla");
	strcpy(sValueGreaterThanZero, "Arvon on oltava suurempi kuin nolla");
	strcpy(sValueIntegerNumber, "Arvon on oltava kokonaisluku!");
	strcpy(sValueRealNumber, "Arvon on oltava reaaliluku. Ehkä olet käyttänyt sijaan. tai päin vastoin. Korjaa se!");
	strcpy(s_The_number_is_too_big_or_it_has_too_many_digits_after_decimal_separator, "Numero on liian iso tai siinä on liian monta numeroa desimaalierottimen jälkeen!");
	strcpy(s_The_number_is_too_big, "Määrä on liian iso!");
	strcpy(sVertical, "Pystysuora");
	strcpy(sWaste, "Jätteet");
	strcpy(sWastes, "Jätteet");
	strcpy(sWasteAddedToWarehouse, "Romu lisätään varastoon");
	strcpy(sWastelimits, "raja jätteiden");
	strcpy(sWasteType, "Jätelaji");
	strcpy(sWeakoptimization, "Heikoin optimointi");
	strcpy(sWhattoprint, "Mitä pitäisi tulostaa");
	strcpy(s_What_to_print_or_save_to_file, "Mitä tulostetaan tai tallennetaan tiedostoon");
	strcpy(sWhattoprintoneachpiece, "Mitä tulostaa jokaiseen");
	strcpy(sWhattoshowoneachpiece, "Mitä näyttää jokaisen palan?");
	strcpy(sWidth, "Leveys");
	strcpy(sWood, "puu");
	strcpy(sWorkingDirectory, "Työskentely hakemisto");
	strcpy(sWrongKey, "Väärä Rekisteröinti avain!");
	strcpy(sYes, "Kyllä");
	strcpy(sYoucannotchooseblackblueorredcolors, "You cannot choose black, blue or red colors.");
	strcpy(sYouCannotMixFractionalDataWithDecimalOnes, "Et voi sekoittaa Murtolukuarvot todellisia arvoja!");
	strcpy(sYourcompany, "Yritys");
	strcpy(sZip, "Postinumero");
	strcpy(s_Set_the_origin_and_the_direction_of_the_axes, "Aseta koordinaattiakselien origo ja suunta.");










	strcpy(s_Number_of_digits_after_the_decimal_separator, "Numeroiden lukumäärä desimaalierottimen jälkeen");
	strcpy(s_Percentages, "Prosentit");
}

