// Language strings: Italian
// Author: Optimal Programs
// License: MIT License
//---------------------------------------------------------------------------
#include <string.h>
//---------------------------------------------------------------------------
#include "language_string_id.h"
//---------------------------------------------------------------------------
void set_it(void)
{
	// Italian
	// translated by a customer on 2021.07.18
	// last update on: 2025.11.01.0
	
	strcpy(s_Area, "Area");
	strcpy(s_Mass, "Massa");
	strcpy(s_Advanced, "Avanzato");
	strcpy(s_Relative_coordinates, "Coordinate relative");
	strcpy(s_Absolute_coordinates, "Coordinate assolute");
	strcpy(s_Append_more_rows, "Aggiungi più righe");

	strcpy(s_Add_to_parts, "Aggiungi alle parti");
	strcpy(s_Additional, "Aggiuntiva");
	strcpy(s_All_results, "Tutti i risultati.");
	strcpy(s_Allow_movement_of_pieces, "Consenti il movimento dei pezzi");
	strcpy(s_Allow_part_in_part, "Consenti pezzo in pezzo");
	strcpy(s_Invalid_piece_Angles_are_too_small_or_too_big_or_height_is_too_small, "Pezzo non valido! Gli angoli sono troppo piccoli o troppo grandi, oppure l'altezza è troppo piccola.");
	strcpy(s_Append, "Aggiungi");
	strcpy(s_As_it_is, "Così com'è");
	strcpy(s_As_text, "Come testo");
	strcpy(s_Ascending, "Ascendente");
	strcpy(s_Automatic, "Automatico");
	strcpy(s_Cannot_connect_to_the_Internet_Please_visit_our_website_from_a_browser, "Impossibile connettersi a Internet! Si prega di visitare il nostro sito Web con un browser.");
	strcpy(s_Cannot_copy_or_move_the_files, "Impossibile copiare o spostare i file!");
	strcpy(s_Cannot_delete_the_file, "Impossibile eliminare il file!");
	strcpy(s_Cannot_modify_old_results, "Impossibile modificare i vecchi risultati!");
	strcpy(s_To_change_click_inside_a_cell_or_press_0_1_or_2, "Per modificare, fare clic all'interno di una cella o premere 0, 1 o 2.");
	strcpy(s_Cell, "Cellula");
	strcpy(s_Click_on_the_table_header_to_change_the_columns, "Fare clic sull'intestazione della tabella per modificare le colonne.");
	strcpy(s_Close, "Chiudi");
	strcpy(s_Contact_us, "Contattaci");
	strcpy(s_Column, "Colonna");
	strcpy(s_Comma, "Virgola");
	strcpy(s_The_comma_symbol_cannot_simultaneously_be_the_list_separator_and_the_decimal_separator, "Il simbolo della virgola non può essere contemporaneamente il separatore di elenco e il separatore decimale!");
	strcpy(s_Copy, "Copia");
	strcpy(s_Copy_for_move, "Copia per spostamento");
	strcpy(s_Cut_higher_level_strips_first, "Tagliare prima le strisce di livello superiore");
	strcpy(s_Cut_index, "Indice di taglio");

	strcpy(s_The_data_have_been_changed_Do_you_want_to_save_them_to_a_file, "I dati sono stati modificati. Vuoi salvarli in un file?");
	strcpy(s_Decimal_separator, "Separatore decimale");
	strcpy(s_Restore_default_settings, "Ripristinare le impostazioni predefinite");
	strcpy(s_Delete_fiber, "Elimina fibra");
	strcpy(s_Descending, "Discendente");
	strcpy(s_Discard_changes, "Non salvare le modifiche");

	strcpy(s_Delete_all_data, "Cancellare tutti i dati?");
	strcpy(s_Dot, "Punto");
	strcpy(s_Do_you_want_to_delete_the_picture, "Vuoi eliminare l'immagine?");
	strcpy(s_Do_you_want_to_delete_the_product, "Vuoi eliminare il prodotto?");
	strcpy(s_Duplicate_and_append, "Duplica e aggiungi.");
	strcpy(s_Duplicate_values_are_ignored, "I valori duplicati sono stati ignorati!");
	strcpy(s_Error, "Errore");
	strcpy(s_Error_loading_file, "Errore durante il caricamento del file.");
	strcpy(s_export_everything, "Esporta tutto");
	strcpy(s_Fit_to_screen, "Adatta allo schermo");
	strcpy(s_Force_fixed_height, "Disegna i pezzi con un'altezza fissa.");
	strcpy(s_Flipped, "Capovolto");
	strcpy(s_Import, "Importa");
	strcpy(s_If_angles_are_different_from_90_degrees_height_must_be_greater_than_0, "Se gli angoli sono diversi da 90 gradi, l'altezza deve essere maggiore di 0.");
	strcpy(s_Ignore, "Ignorare");
	strcpy(s_Incorrect_value, "Valore errato");
	strcpy(s_Info, "Informazioni");
	strcpy(s_Interior, "Dentro");
	strcpy(s_Give_a_name, "Dai un nome.");
	strcpy(s_Group, "Raggruppalo");
	strcpy(s_Header, "Intestazione");
	strcpy(s_Keep_it_as_it_is, "Tienilo così com'è");
	strcpy(s_Level, "Level");
	strcpy(s_Licensee, "Licenziataria");
	strcpy(s_List_separator, "Separatore di elenco");
	strcpy(s_Made_with_love_in_Cugir_Romania, "Fatto con amore a Cugir, Romania");
	strcpy(s_Made_in, "Prodotto in");
	strcpy(s_Manufacturer, "Produttore");

	strcpy(s_Manual_arrange, "Disposizione manuale");

	strcpy(s_Mixed, "Mista");
	strcpy(s_Multiple_shapes_detected_Next_rows_will_be_overwritten_Continue, "È stata rilevata più di una forma. Pertanto, le righe successive verranno sovrascritte. Continua?");
	strcpy(s_More, "Di più");
	strcpy(s_Multiple_values, "Valori multipli");
	strcpy(s_No_texture, "Nessuna trama");
	strcpy(s_Number, "Numero");
	strcpy(s_Number_of_images, "Numero di immagini");
	strcpy(s_Number_of_vertices, "Numero di vertici");
	strcpy(s_Offset, "Compensare");
	strcpy(s_Only_the_currently_selected_items, "Solo gli elementi attualmente selezionati.");
	strcpy(s_Optimizing_please_wait, "Ottimizzazione... attendere prego.");

	strcpy(s_Paste, "Incolla");

	strcpy(s_Piece_label, "Etichetta del pezzo");
	strcpy(s_Piece_size, "Dimensione del pezzo");
	strcpy(s_Please_contact_us_by_email_if_you_receive_this_error, "Contattaci via e-mail se ricevi questo errore.");
	strcpy(s_Please_save_it_first, "Per favore, salvalo prima.");
	strcpy(s_Position, "Posizione");
	strcpy(s_Preview, "Anteprima");
	strcpy(s_Rectangle, "Rettangolo");

	strcpy(s_Redo_the_last_operation, "Rifai l'ultima operazione");
	strcpy(s_Regular_polygon, "Poligono regolare");

	strcpy(s_Reused, "Riutilizzata");
	strcpy(s_Rotated, "Ruotata");
	strcpy(s_Save_all, "Salva tutto");
	strcpy(s_Scrap_label, "Etichetta dello scarto");
	strcpy(s_Scrap_size, "Dimensioni dello scarto");
	strcpy(s_Semicolon, "Punto e virgola");
	strcpy(s_Show_cut_index, "Mostra indice di taglio");
	strcpy(s_Show_information, "Mostra informazioni");
	strcpy(s_Show_piece_label, "Mostra l'etichetta del pezzo");
	strcpy(s_Show_scrap_label, "Mostra etichetta di scarto");
	strcpy(s_Show_scrap_s_size_on_the_small_pieces, "Mostra le dimensioni dello scarto sui piccoli pezzi");
	strcpy(s_Show_size_of_pieces, "Mostra dimensione del pezzo");
	strcpy(s_Show_size_of_scrap, "Mostra dimensioni dello scarto");
	strcpy(s_Show_sizes, "Mostra dimensioni");
	strcpy(s_Show_label, "Mostra etichetta");
	strcpy(s_Show_length, "Mostra lunghezza");

	strcpy(s_Some_numerical_values_are_incorrect_Should_I_fix_all_the_incorrect_values, "Alcuni valori numerici non sono corretti! Devo correggere tutti quelli errati?");
	strcpy(s_Some_invalid_values_have_been_removed, "Alcuni valori non validi sono stati rimossi.");
	strcpy(s_Sort_by, "Ordina per");
	strcpy(s_Sort_ascending_by, "Ordina crescente per");
	strcpy(s_Sort_descending_by, "Ordina decrescente per");
	strcpy(s_Start, "Inizio");
	strcpy(s_Starting_angle, "Angolo di partenza");

	strcpy(s_Sticker, "Adesivo");
	strcpy(s_Stock, "Giacenza");
	strcpy(s_Stop, "Fermare");
	strcpy(s_System_setting, "Impostazione del sistema");
	strcpy(s_Tabular, "tabulare");
	strcpy(s_Total, "Totale");
	strcpy(s_Total_size, "Dimensione totale");
	strcpy(s_Terms_of_the_license, "Termini della licenza");
	strcpy(s_The_current_product_has_been_changed_Do_you_want_to_save_it_to_file, "Il prodotto attuale è stato modificato. Vuoi salvarlo su file?");
	strcpy(s_The_value_is_out_of_the_allowed_range, "Il valore non è compreso nell'intervallo consentito.");
	strcpy(s_The_value_must_be_a_real_or_fractional_number_Try_to_replace_the_comma_with_the_dot_if_you_want_to_enter_a_real_number, "Il valore deve essere un numero reale o frazionario. Prova a sostituire la virgola con il punto se desideri inserire un numero reale.");
	strcpy(s_This_feature_is_not_implemented_yet, "Questa funzione non è ancora implementata.");
	strcpy(s_This_operation_cannot_be_reversed, "Questa operazione non può essere annullata.");
	strcpy(s_Undo_the_last_operation, "Annulla l'ultima operazione.");
	strcpy(s_Utilization, "Utilizzo");
	strcpy(s_Utilized_Stock, "Stock utilizzato");
	strcpy(s_Version, "Versione");
	strcpy(s_Visible_columns, "Colonne visibili");
	strcpy(s_You_already_have_the_latest_version_installed, "Hai già installato l'ultima versione!");
	strcpy(s_What_is_exported, "Cosa viene esportato?");
	strcpy(s0meansanynumberofpieces, "Zero, significa qualsiasi numero di pezzi");
	strcpy(sAbout, "Info su...");
	strcpy(sAccept, "Accetta");
	strcpy(sAcceptall, "Accetta tutte");
	strcpy(sAcceptthecurrentsolution, "Accetta la soluzione corrente");
	strcpy(sAdd, "Aggiungi");
	strcpy(sAddapiece, "Aggiungi un pezzo");
	strcpy(sAddasimpleproducttoDemand, "Aggiungi un prodotto alle parti esistenti");
	strcpy(sAddgrindingthicknesstopartsize, "Aggiungi spessore di rettifica alla dimensione del pezzo");
	strcpy(sAddproductnametolabel, "Aggiungi il nome del prodotto all'etichetta");
	strcpy(sAddress, "Indirizzo");
	strcpy(sAddselectedsizetoInventory, "Aggiungi la dimensione selezionata all'assortimento");
	strcpy(sAdhesivelabels, "Etichette adesive");
	strcpy(sAdhesivelabelwithinformationaboutpiecesinDemandCustomernameLabelSizeCurrentData, "Etichetta adesiva con informazioni sui pezzi: Nome del cliente, Etichetta, Dimensione, Data corrente, ecc.");
	strcpy(sAdhesivelabelwithinformationaboutsheetsinInventory, "Etichette adesive con informazioni sull'assortimento dei fogli");
	strcpy(sAll, "Tutti");
	strcpy(sAlloffcutswhichhavethesizegreaterthanthisvaluewillbeaddedtoInventory, "Tutto lo scarto superiore a questo valore verrà aggiunto all'assortimento");
	strcpy(sAllowMirroring, "Consenti il ribaltamento");
	strcpy(sAllowRotation, "Consenti la rotazione");
	strcpy(sAllPieces, "Tutti i pezzi");
	strcpy(sAllpredefinedproducts, "Tutti i prodotti predefiniti");
	strcpy(sAnewwindowwillbedisplayedwheretheusercansettheedgebandsforeachedge, "Verrà visualizzata una finestra per impostare le bande laterali per ciascun lato.");
	strcpy(sAnewwindowwillbedisplayedwheretheusercansetthegrindingvalueforeachedgeofthsheet, "Verrà visualizzata una finestra per impostare la dimensione della rettifica per ogni lato del pezzo.");
	strcpy(sAnewwindowwillbedisplayedwheretheusercansetthetrimvalueforeachedgeofthsheet, "Verrà visualizzata una finestra per impostare il valore di rifilatura per ogni lato del pezzo.");
	strcpy(sAngle, "Angolo");
	strcpy(sAngles, "Angoli");
	strcpy(sAnoptimizationparameterisarealnumber, "Un parametro di ottimizzazione è un numero reale.");
	strcpy(sAnoptimizationparameterisfractionalnumber, "Un parametro di ottimizzazione è un numero frazionario.");
	strcpy(sAnyShape, "Qualsiasi forma!");
	strcpy(sApolygonmusthaveatleast2vertices, "Un poligono deve avere almeno 2 vertici!");
	strcpy(sApolygonmusthaveatleast3vertices, "Un poligono deve avere almeno 3 vertici!");
	strcpy(sApplication_fails_to_initialize, "L'inizializzazione del programma è fallita.");
	strcpy(sArc, "Arco");
	strcpy(sArcLength, "Lunghezza dell'arco");
	strcpy(sAreaofusedsheets, "Area dei fogli usati");
	strcpy(sAshortdescriptionofthesheet, "Una breve descrizione del foglio");
	strcpy(sAtleastonepart, "Si deve inserire almeno un pezzo.");
	strcpy(sAtTheMarginOfTheSheet, "Al bordo del foglio");
	strcpy(sBandtypes, "Tipo di bande laterali");
	strcpy(sBar, "Barre");
	strcpy(sBars, "Barre");
	strcpy(sBothsizesoftheoffcutsmustbegreaterthanthisvalue, "Entrambe le dimensioni degli scarti devono superare questo valore.");
	strcpy(sBottom, "Sotto");
	strcpy(sBottomcoordinateofthedefect, "La coordinata inferiore del difetto");
	strcpy(sBreakCut, "Interrompi il taglio");
	strcpy(sBrowse, "Sfoglia");
	strcpy(sBuy, "Acquista");
	strcpy(sBuynow, "Acquista ora ...");
	strcpy(sCancel, "Annulla");
	strcpy(sCannotBeEmpty, "non può essere vuoto!");
	strcpy(sCannotmovepartsbetweensheetswhenidenticalsheetsaregroupedPleaseungroupthesheetsfrommenu, "Impossibile spostare le parti da un foglio all'altro se quelli identici sono raggruppati. Si prega di annullare il raggruppamento dei fogli dal menu.");
	strcpy(sCannotSaveFile, "Impossibile salvare il file");
	strcpy(sCenter, "Centro");

	strcpy(sChangeDirection, "Cambia direzione di taglio");
	strcpy(sChoose, "Scegli");
	strcpy(sChooseProduct, "Scegli il prodotto");
	strcpy(sCircle, "Cerchio");
	strcpy(sCity, "Città");
	strcpy(sClear, "Cancella");
	strcpy(sClockWise, "In senso orario");
	strcpy(sClosewindow, "Chiudi finestra");
	strcpy(sColor, "Colore");
	strcpy(sColorofedgeband, "Il colore delle bande laterali");
	strcpy(sColorPattern, "Colore/Motivo");
	strcpy(sColorpiecesandwastes, "Pezzi e scarti colorati");
	strcpy(sColumns, "Colonne");
	strcpy(sComment, "Commento");
	strcpy(sCompanyname, "Nome dell'azienda");
	strcpy(sComplexMaterialExists, "Il nome del materiale è già definito nella lista dei materiali complessi. Si prega di rinominarlo.");
	strcpy(sComputerCode, "Codice computer");
	strcpy(sComputerCodefromyourcomputer, "Codice Computer (dal tuo computer)");
	strcpy(sComputethetotalpriceofDemand, "Calcola il prezzo totale delle Parti");
	strcpy(sContents, "Contenuto");
	strcpy(sContinutComanda, "Contenuto delle Parti in data");
	strcpy(sContinutDepozit, "Contenuto dell'Assortimento nei dati");
	strcpy(sConversionIsDoneOnlyWhenSomePiecesHaveFractionalValues, "La conversione viene fatta solo quando alcuni pezzi hanno valori frazionari.");
	strcpy(sConvertsTheSizeOfWasteToAFractionalUnit, "Mostra le dimensioni degli scarti come un valore frazionario.");
	strcpy(sCouldNotSaveFile1, "Impossibile scrivere il file nella directory");
	strcpy(sCouldNotSaveFile2, "Potresti non avere diritti sufficienti. Per favore controlla o cambia la directory di lavoro, dal menu Impostazioni | Directory di lavoro, in una cartella senza restrizioni (ad esempio c:\\temp).");
	strcpy(sCreationdateYMDHMS, "Data di creazione (Y/M/D-H:M:S)");
	strcpy(sCurrentDate, "Data corrente");
	strcpy(sCurrentDiagram, "Diagramma corrente");
	strcpy(sCurrentMaterial, "Materiale corrente");
	strcpy(sCurrentversion, "Versione corrente");
	strcpy(sCurve_not_closed_Try_increasing_DXF_linking_distance_parameter, "Il poligono non è chiuso! Prova ad aumentare il parametro DXF linking distance.");
	strcpy(sCustomer, "Cliente");
	strcpy(sCustomerName, "Nome cliente");
	strcpy(sCustomMessage, "Messaggio personalizzato");
	strcpy(sCutlength, "La lunghezza del taglio");
	strcpy(sCut, "Taglio");
	strcpy(sCuts, "Tagli");
	strcpy(sCutterThickness, "Spessore di taglio");
	strcpy(sData, "Data");
	strcpy(sDataCannotBeEmpty, "La data non può essere vuota!");
	strcpy(sDateymdhms, "Data (y/m/d/h/m/s)");
	strcpy(sDays_left_for_trial, "Giorni rimasti per la prova");
	strcpy(sDaysLeft, "giorni restanti");
	strcpy(sStandard, "Predefinito");
	strcpy(sDefaultInterface, "Interfaccia predefinita");
	strcpy(sDefects, "Difetti");
	strcpy(sDefectsManager, "Gestione difetti");
	strcpy(sDefectsofthematerialNopiecescanbeplacedinthefaultyzone, "Difetti del materiale. I pezzi non possono essere collocati nella zona difettosa.");
	strcpy(sDelete, "Elimina");
	strcpy(sDeletePiece, "Elimina pezzo");
	strcpy(sDeleteRow, "Elimina riga");
	strcpy(sDemandutilization, "Utilizzo delle parti");
	strcpy(sDepozitulmodificat, "I pezzi utilizzati sono stati rimossi. Lo scarto è stato aggiunto all'assortimento.");
	strcpy(sDepozitvid, "L'assortimento è vuoto");
	strcpy(sDesk, "scrivania");
	strcpy(sDiagram, "Diagramma");
	strcpy(sDiagrams, "Diagrammi");
	strcpy(sDiagramasatable, "Diagramma tabellare");
	strcpy(sDigits, "cifre");
	strcpy(sDimensiuniplaca, "Dimensioni del foglio");
	strcpy(sDirection, "Direzione");
	strcpy(sDistanceBetweenRows, "Distanza tra le righe");
	strcpy(sDonotuseit, "Non utilizzarlo");
	strcpy(sDownload, "Scarica");
	strcpy(sDoYouWantToClearTheData, "Si desidera cancellare i dati?");
	strcpy(sDoYouWantToSaveDemand, "Le parti sono state modificate! Vuoi salvare le modifiche?");
	strcpy(sDoYouWantToSaveParts, "Vuoi salvare le parti?");
	strcpy(sDoYouWantToSaveRepository, "L'assortimento è cambiato! Vuoi salvare le modifiche?");
	strcpy(sDrawing, "Disegno");
	strcpy(sDrawthesolutioncolorful, "Disegna la soluzione colorata");
	strcpy(sDuplicateTypes, "Alcuni tipi sono duplicati! Si prega di rimuovere i duplicati");
	strcpy(sDuplicateTypesWithComplex, "Alcuni nomi di materiali esistono già nella lista dei tipi complessi! Per favore rimuovi i duplicati");
	strcpy(sDuplicateValues, "Valori duplicati");
	strcpy(sEdgeband, "Bande laterali");
	strcpy(sEdgebandingwhichisplacedontheedgesofyourpiecePleasedefineedgebandingtypesfromMaterialsEdgeBandingmenu, "Le bande laterali vengono posizionate ai margini del pezzo. Si prega di definirle nel menu Materiali.");
	strcpy(sEdgebandsthatwillbeappliedtoeachpart, "Le bande laterali che vengono applicate a ciascun pezzo.");
	strcpy(sEdgeBandTolerance, "Tolleranza per le bande laterali");
	strcpy(sEdgesthatmustbecutduefaults, "I bordi che devono essere tagliati a causa di difetti.");
	strcpy(sEdgetoedge, "Da bordo a bordo");
	strcpy(sEdit, "Modifica");
	strcpy(sEmail, "Email");
	strcpy(sEmptyData, "Dati assenti!");
	strcpy(sEnabled, "Abilitato");
	strcpy(sEnabledisabledefectsoftheinventorysheets, "Abilita / disabilita i difetti dell'assortimento");
	strcpy(sEnterLabel, "Inserisci etichetta");
	strcpy(sEnterTheMaterialName, "Inserisci il nome del materiale");
	strcpy(sEnterTheProductName, "Inserisci il nome del prodotto");
	strcpy(sEvaluationError, "Errore di valutazione dell'espressione!");
	strcpy(sExit, "Esci");
	strcpy(sExpired, "Il software è scaduto! Si prega di registrarlo!");
	strcpy(sExport, "Esporta");
	strcpy(sExportAllDiagrams, "Esporta tutti i diagrammi");
	strcpy(sExportAllToASingleFile, "Esporta tutto in un singolo file");
	strcpy(sExportOptions, "Opzioni di esportazione");
	strcpy(sExporttoDXFformat, "Esporta in formato DXF");
	strcpy(sExporttoExcel, "Esporta in formato Excel");
	strcpy(sExpresieIncorecta, "Espressione matematica errata!");
	strcpy(sExtensions, "Estensioni");
	strcpy(sExtra, "Extra");
	strcpy(sExtraComponents, "Componenti aggiuntivi");
	strcpy(sExtracomponentsattachedtoDemand, "Componenti aggiuntivi allegati alle parti");
	strcpy(sFile, "File");
	strcpy(sFileName, "Nome file");
	strcpy(sFillWastes, "Disegna scarti con linee oblique");
	strcpy(sFindoptimalbarsheetsize, "Trova dimensione ottimale per barre e fogli");
	strcpy(sFindoptimalsizeofInventorypieces, "Trova la dimensione ottimale dei pezzi nell'assortimento");
	strcpy(sFirstcutMultiplestages, "Prima direzione di taglio per fasi multiple");
	strcpy(sFirstdirectionforcutishorizontal, "Prima direzione di taglio orizzontale");
	strcpy(sFirstdirectionforcutisvertical, "Prima direzione di taglio verticale");
	strcpy(sFollowthecontourofpieces, "Segui il contorno dei pezzi");
	strcpy(sFont, "Carattere");
	strcpy(sFontsize, "Dimensione carattere");
	strcpy(sFullInfo, "Informazioni complete");
	strcpy(sDisposedWaste, "Rifiuti smaltiti");
	strcpy(sGeneral, "Generale");
	strcpy(sGenerateCNC, "Genera CNC");
	strcpy(sGrain, "Fibra");
	strcpy(sGraindirection, "Direzione della fibra");
	strcpy(sGraphic, "Grafico");
	strcpy(sGreaterorequalto, "Scarto maggiore o uguale a");
	strcpy(sGrid, "Tabelle");
	strcpy(sGrinding, "Rettifica");
	strcpy(sGrosimeTaieturaScalata, "Lo spessore di taglio di questa immagine potrebbe essere diversa da quella reale perché il pezzo non è rappresentato in dimensione reale. Questo non incide sui risultati.");
	strcpy(sGroupidenticallayouts, "Fogli identici raggruppati");
	strcpy(sGroupIdenticalParts, "Parti identici raggruppate");
	strcpy(sGroupingOfIdenticalPiecesIntoOneRow, "Parti identici raggruppate nella stessa riga.");
	strcpy(sGroupPartsAfterLoadingFromFile, "Parti raggruppate dopo il caricamento da file");
	strcpy(sHeight, "Altezza");
	strcpy(sHeighttolerance, "Tolleranza per l'altezza");
	strcpy(sHelp, "Guida");
	strcpy(sHistory, "Storico");
	strcpy(sHorizontal, "Orizzontale");
	strcpy(sHowtodisplayprintedgebands, "Come visualizzare le bande laterali?");
	strcpy(sIfyousetthebandforoneedgeallwillreceivethesamevalue, "Se si imposta il bordo per un lato, tutti bordi riceveranno lo stesso valore.");
	strcpy(sIfyousetthegrindingforoneedgeallwillreceivethesamevalue, "Se si imposta il valore di rettifica per un lato, tutti i lati riceveranno lo stesso valore.");
	strcpy(sIfyousetthetrimforoneedgeallwillreceivethesamevalue, "Se si imposta la rifilatura per un lato, tutti i lati riceveranno lo stesso valore.");
	strcpy(sImageBounds, "Limiti per l'immagine");
	strcpy(sImageSize, "Dimensioni immagine");
	strcpy(sImportData, "Importa i dati");
	strcpy(sIncorrectPassword, "Password errata");
	strcpy(sIndex, "Indice");
	strcpy(sInformationaboutcustomer, "Informazioni del cliente");
	strcpy(sInputALanguageName, "Dai un nome alla lingua");
	strcpy(sInsert, "Inserisci");
	strcpy(sInsertPiece, "Inserisci pezzo");
	strcpy(sInterface, "Interfaccia");
	strcpy(sInterfaceSettings, "Impostazioni interfaccia");
	strcpy(sInvalidHardware, "Impossibile rilevare l'hardware. Vi preghiamo di contattarci presso contact@optimalprograms.com");
	strcpy(sInvalidNumber, "Numero non valido");
	strcpy(sInvalidOrderOfComputation, "Non si riesce a calcolare un ordine per le lunghezze. Ci sono riferimenti circolari nella definizione dei prodotti!");
	strcpy(sInvalidRegistration, "La registrazione non è valida!");
	strcpy(sInvalidTime, "L'orologio di sistema non è corretto.");
	strcpy(sInventory, "GIACENZA");
	strcpy(sisafractionalvalue, "è un valore frazionario.");
	strcpy(sIsArc, "E' un'arco");
	strcpy(sisarealvalue, "è un valore reale.");
	strcpy(sLabel, "Etichetta");
	strcpy(sLabels, "Etichette");
	strcpy(sLanguage, "Lingua");
	strcpy(sLatimeanumar0, "La larghezza deve essere maggiore di 0!");
	strcpy(sLatimeanumarreal, "La larghezza deve essere un numero reale!");
	strcpy(sLayerName, "Nome del livello");
	strcpy(sLeft, "Sinistra");
	strcpy(sLeftcoordinateofthedefect, "La coordinata sinistra del difetto");
	strcpy(sLength, "Lunghezza");
	strcpy(sLengthofthepiecestocut, "Dimensioni del pezzo da tagliare");
	strcpy(sLengthofthepiecestocutfrom, "Dimensioni del foglio da tagliare");
	strcpy(sLengthofusedbars, "Dimensioni delle barre utilizzate");
	strcpy(sLicenseAgreement, "Contratto di licenza");
	strcpy(sLinear, "Lineare");
	strcpy(sLinethickness, "Spessore della penna");
	strcpy(sLoadafileandappenddatatothecurrentDemand, "Carica un file e aggiungilo ai dati delle parti correnti");
	strcpy(sLoadanexistingDemandfromafile, "Carica le parti esistenti da file");
	strcpy(sLoadAppend, "Carica ed aggiungi");
	strcpy(sLoadEverything, "Carica tutto");
	strcpy(sLoadInventory, "Carica l'assortimento");
	strcpy(sLoadInventoryandDemand, "Carica assortimento e parti");
	strcpy(sLoadResults, "Carica i risultati");
	strcpy(sLocked, "Bloccato");
	strcpy(sLogo, "Marchio");
	strcpy(sLong, "Lungo");
	strcpy(sLongerexecutiontime, "Tempo di esecuzione lungo");
	strcpy(sLungime, "Larghezza");
	strcpy(sLungimeanumar0, "La lunghezza dev'essere maggiore di 0!");
	strcpy(sLungimeanumarreal, "La lunghezza dev'essere un numero reale!");
	strcpy(sLungimeaTotalaFolosita, "Lunghezza totale utilizzata");
	strcpy(sMagnification, "Ingrandimento");
	strcpy(sMagnify, "Ingrandire");
	strcpy(sMargins, "Margini");
	strcpy(sMarginsForPaper, "Margini per la carta");
	strcpy(sMarginsOfTheLabel, "Margini dell'etichetta");
	strcpy(sMaterial, "Materiale");
	strcpy(sMaterialName, "Nome del materiale");
	strcpy(sMaterials, "Materiale");
	strcpy(sMaterialstypes, "Tipi di materiale");
	strcpy(sMax, "Massimo");
	strcpy(sMaximalArea, "Area massima");
	strcpy(sMaximalCutLength, "Lunghezza massima di taglio");
	strcpy(sMaxlength, "Lunghezza massima");
	strcpy(sMaxPiecesperBar, "Max pezzi per barra");
	strcpy(sMaxwidth, "Larghezza massima");
	strcpy(sMeasurementUnit, "Unità di misura");
	strcpy(sMin, "Minimo");
	strcpy(sMinimalBreakSize, "Dimensione minima di interruzione");
	strcpy(sMinimalUsefulSize, "Dimensione minima utile");
	strcpy(sMinimalwastesizetoInventory, "Dimensione minima dello scarto aggiunto all'assortimento");
	strcpy(s_What_to_minimize, "Cosa minimizzare?");
	strcpy(sMinlength, "Lunghezza minima");
	strcpy(sMinwidth, "Larghezza minima");
	strcpy(sMirror, "Specchio");
	strcpy(sMirroring, "Vista speculare");
	strcpy(sMiscellaneous, "Altre statistiche");
	strcpy(sModify, "Modifica");
	strcpy(sModifytheselectedpiece, "Modifica il pezzo selezionato");
	strcpy(sMovePiece, "Sposta pezzo");
	strcpy(sMultiplestages, "Fasi multiple");
	strcpy(sName, "Nome");
	strcpy(sNameofedgeband, "Nome delle bande laterali");
	strcpy(sNewDEMANDUnsaveddatawillbelost, "Nuove parti? I dati non salvati andranno persi!");
	strcpy(sNewLanguage, "Nuova lingua");
	strcpy(sNewMaterial, "Nuovo materiale");
	strcpy(sNewPasswordincorectlyintroduced, "Nuova password errata!");
	strcpy(sNewProduct, "Nuovo prodotto");
	strcpy(sNewversion, "Nuova versione");
	strcpy(sNo, "No");
	strcpy(sNumarBucati, "Numero di pezzi");
	strcpy(sNumberOfCopies, "Numero di copie");
	strcpy(sNumberofstages, "Numero di fasi");
	strcpy(sNusuficienteplacidepozit, "Non tutti i pezzi sono stati ottimizzati. Possibili cause: Non ci sono abbastanza pezzi nell'Assortimento. I pezzi non sono abilitati. I materiali delle parti e della Giacenza sono diversi. Altri parametri sono stati impostati in modo errato.");
	strcpy(sOfficeNotInstaled, "Microsoft Office non è installato nel computer, oppure è una versione incompatibile.");
	strcpy(sOldpassworddoesnotmatch, "La vecchia password non corrisponde!");
	strcpy(sOnlinehelp, "Guida in linea");
	strcpy(sOnlypiecesofthesameheightinthelaststage, "Pezzi della stessa altezza nell'ultima fase");
	strcpy(sOpen, "Apri");
	strcpy(sOptimization, "Ottimizzazione");
	strcpy(sOptimizationDone, "Ottimizzazione eseguita! Puoi stampare o salvare i diagrammi ottenuti. Premi il pulsante Accetta se sei soddisfatto del risultato. Altrimenti premi nuovamente Avvia.");
	strcpy(sOptimizationType, "Tipo di ottimizzazione");
	strcpy(sOptions, "Opzioni");
	strcpy(sOptionsrelatedtotheinterface, "Opzioni relative all'interfaccia");
	strcpy(sor, "o");
	strcpy(sOthercomponents, "Altri componenti");
	strcpy(sOthers, "Altri");
	strcpy(sOtherstatistics, "Altre statistiche");
	strcpy(sOverrideExcelCSVfiles, "Sovrascrivi il file Excel/CSV");
	strcpy(sParameter, "Parametro");
	strcpy(sParts, "PEZZI");
	strcpy(sPattern, "Motivo");
	strcpy(sPatternforwaste, "Motivo per lo scarto");
	strcpy(sPerimeter, "Perimetro");
	strcpy(sPermitedRotationAngle, "Angolo di rotazione ammesso");
	strcpy(sPhone, "Telefono");
	strcpy(sPicture, "Immagine");
	strcpy(sPiece, "Pezzo");
	strcpy(sPieceindex, "Indice del pezzo");
	strcpy(sPieces, "Pezzi");
	strcpy(sPiecesize, "Dimensione del pezzo");
	strcpy(sPiecesizelabeledgebandwillbeprinted, "Verranno stampate le dimensioni, l'etichetta e le bande laterali del pezzo.");
	strcpy(sPierdere, "Spreco");
	strcpy(sPixels, "pixel");
	strcpy(sPlacilefolositeDepozit, "Pezzi utilizzati dall'Assortimento.");
	strcpy(sPlease_contact_us_at_contact_nestingtechnologies_com, "Vi preghiamo di contattarci a contact@nesting-technologies.com");
	strcpy(sPlease_contact_us_at_contact_optimalprograms_com, "Vi preghiamo di contattarci a contact@optimalprograms.com");
	strcpy(sPleaseenteralldataeitherasfractionalorrealDonotmixthem, "Si prega di inserire solo dati frazionari o reali! Senza mescolarli!");
	strcpy(sPleaseEnterSomeTypesOfMaterials, "Non vi è alcun tipo di materiale definito. E' possibile definirli dal menu Materiali.");
	strcpy(sPleasesendtheNameandtheCodetotheaddresscontactoptimalprogramscominordertoobtaintheRegistrationKey, "Per ottenere la chiave di registrazione si prega di inviare Nome e Codice a: contact@optimalprograms.com.");
	strcpy(sPolygon, "Poligono");
	strcpy(sPolygonsCircles, "Poligoni, cerchi");
	strcpy(sPrecision, "Precisione");
	strcpy(sPretulnumar0, "Il prezzo deve essere maggiore di 0!");
	strcpy(sPretulnumarreal, "Il prezzo deve essere un numero reale!");
	strcpy(sPreview, "Anteprima");
	strcpy(sPrice, "Prezzo");
	strcpy(sPriceMustBeGreaterThanZero, "Il prezzo deve essere maggiore di zero");
	strcpy(sPriceofbars, "Prezzo delle barre");
	strcpy(sPriceperbar, "Prezzo per barra");
	strcpy(sPricepersheet, "Prezzo per foglio");
	strcpy(sPricepersquareunitofmaterial, "Prezzo per unità quadrata del materiale");
	strcpy(sPriceperunit, "Prezzo per unità");
	strcpy(sPrint, "Stampa");
	strcpy(sPrintdiagramsastables, "Stampa i diagrammi come tabelle.");
	strcpy(sPrinter, "Stampante");
	strcpy(sPrinterBounds, "Margini per stampante");
	strcpy(sPrinting, "Stampa");
	strcpy(sPrintonlyutilizedarea, "Stampa solo la superficie utilizzata");
	strcpy(sPrintthecontentsoftheDemand, "Stampa il contenuto delle parti");
	strcpy(sPrintthecontentsoftheInventory, "Stampa il contenuto dell'assortimento");
	strcpy(sPrintthecurrentsolution, "Stampa la soluzione corrente");
	strcpy(sPriority, "Priorità");
	strcpy(sPrioritytocutapieceZero0isthehighestpriority, "Priorità per tagliare un pezzo. Zero (0) è quella massima.");
	strcpy(sProcentul0100, "Le percentuali devono essere maggiori di 0 e minori o uguali a 100!");
	strcpy(sProcentulnumarreal, "Le percentuali devono essere un numero reale!");
	strcpy(sProductdefinition, "Definizione del prodotto");
	strcpy(sProductExists, "Il prodotto esiste già. Scegliere un'altro nome.");
	strcpy(sProductName, "Nome del prodotto");
	strcpy(sProducts, "Prodotto");
	strcpy(sProducts, "Prodotti");
	strcpy(sProject, "Progetto");
	strcpy(sProperties, "Proprietà");
	strcpy(sProperty, "Proprietà");
	strcpy(sQuantity, "Quantità");
	strcpy(sQuantitynumberofsheetsofthistype, "Numero di fogli di questo tipo");
	strcpy(sRadius, "Raggio");
	strcpy(sRectangular, "Rettangolare");
	strcpy(sRedefinetypesofedgeband, "Ridefinire i tipi di banda laterale");
	strcpy(sRedefinetypesofmaterial, "Ridefinire i tipi di materiale");
	strcpy(sRegistration, "Registrazione");
	strcpy(sRegistrationKeyfromOptimalPrograms, "Chiave di registrazione");
	strcpy(sRegistrationSuccessful, "Registrazione effettuata!");
	strcpy(sRemoveallpiecesinInventory, "Rimuovi tutti i pezzi nell'Inventario");
	strcpy(sRemoveCut, "Elimina taglio");
	strcpy(sRemovetheselectedpiece, "Rimuovi il pezzo selezionato");
	strcpy(sReports, "Rapporti");
	strcpy(sRequestedMaterial, "Materiale richiesto");
	strcpy(sRestore, "Ripristina");
	strcpy(sResults, "Risultati");
	strcpy(sReusedwaste, "Scarti riutilizzati");
	strcpy(sRight, "Destra");
	strcpy(sRightcoordinateofthedefect, "Coordinate del difetto da destra");
	strcpy(sRotation, "Rotazione");
	strcpy(sRotationAngle, "Angolo di rotazione");
	strcpy(sRotationStep, "Passo di rotazione");
	strcpy(sRoundAllFractionsTo, "I valori frazionari devono essere arrotondati a");
	strcpy(sRow, "riga");
	strcpy(sRows, "Righe");
	strcpy(sRun, "Ultime soluzioni");
	strcpy(sRunningtime, "Tempo di esecuzione");
	strcpy(sSameforall, "Uguale per tutti");
	strcpy(sSave, "Salva");
	strcpy(sSaveAllImages, "Salva tutte le immagini");
	strcpy(sSaveAs, "Salva come");
	strcpy(sSaveChanges, "Le parti sono state modificate. Vuoi salvarle?");
	strcpy(sSaveCurrentImage, "Salva l'immagine corrente");
	strcpy(sSavedataparameters, "Salva dati e parametri");
	strcpy(sSaveEverything, "Salva tutto");
	strcpy(sSaveInventory, "Salva Inventario");
	strcpy(sSaveInventoryandDemand, "Salva assortimento e parti");
	strcpy(sSaveResults, "Salva i risultati");
	strcpy(sSaveStatisticsinafile, "Salva le statistiche in un file");
	strcpy(sSavethecurrentimage, "Salva l'immagine corrente");
	strcpy(sSavethecurrentimageorstatistic, "Salva l'immagine corrente o le statistiche");
	strcpy(sSavetheDEMANDinafile, "Salva su file");
	strcpy(sSavetheDemandinafilewithadifferentname, "Salva le Parti in un file con un'altro nome.");
	strcpy(sSavetheREPOSITORYinafile, "Salva l'Assortimento in un file");
	strcpy(sSerialNumber, "Chiave di registrazione");
	strcpy(sService, "Servizio");
	strcpy(sSetDefaultValues, "Questo ripristinerà tutti i parametri ai valori predefiniti. Tutte le tue impostazioni andranno perse. Sei sicuro di voler questo?");
	strcpy(sSetedgeband, "Imposta la banda laterale");
	strcpy(sSetedgetrim, "Imposta il taglio per i difetti dei bordi");
	strcpy(sSetthesameedgebandforalledges, "Imposta la stessa banda laterale per tutti i lati");
	strcpy(sSetthesamegrindingforalledges, "Imposta la stessa rettifica per tutti i bordi");
	strcpy(sSetthesametrimforalledges, "Imposta lo stesso taglio di difetti per tutti i bordi");
	strcpy(sSettings, "Impostazioni");
	strcpy(sShape, "Forma");
	strcpy(sSheet, "Foglio");
	strcpy(sSheetsBarstypes, "Tipi fogli_barre");
	strcpy(sSheetSize, "Dimensioni del foglio");
	strcpy(sSheetsperPage, "Fogli per pagina");
	strcpy(sShort, "Breve");
	strcpy(sShorterexecutiontime, "Tempo di esecuzione breve");
	strcpy(sShowallsimpleproducts, "Mostra tutti i prodotti semplici");
	strcpy(sShowcustomername, "Mostra il nome del cliente");
	strcpy(sShowCustomTextOnEachPiece, "Mostra testo personalizzato su ogni pezzo");
	strcpy(sShowdiagramasatable, "Mostra diagramma tabellare.");
	strcpy(sShowedgeband, "Mostra le bande laterali");
	strcpy(sShowedgebandssettinginanewwindow, "Mostra le impostazioni delle bande laterali in una nuova finestra");
	strcpy(sShowgrindingsettingsinanewwindow, "Mostra le impostazioni di rettifica in una nuova finestra");
	strcpy(sShowHorizontalLabelsAlways, "Mostra sempre le etichette orizzontalmente");
	strcpy(sShowRemovethesizeofthepiecesinthecurrentsolution, "Mostra / nascondi la dimensione dei pezzi.");
	strcpy(sShowRemovethesizeofthewastesinthecurrentsolution, "Mostra / nascondi la dimensione dello scarto.");
	strcpy(sShowtotalcutlength, "Mostra lunghezza totale di taglio");
	strcpy(sShowtrimedgesettingsinanewwindow, "Mostra le impostazioni dei difetti in una nuova finestra");
	strcpy(sSimpleMaterialExists, "Il nome del materiale è già definito nella lista dei materiali. Si prega di usarne un'altro.");
	strcpy(sSinglePieceStrips, "Strisce di un pezzo");
	strcpy(sSizes, "Dimensioni");
	strcpy(sSmallerorequalto, "Scarto minore o uguale a");
	strcpy(sSort, "Ordina");
	strcpy(sSortAscendingByArea, "In ordine crescente per area");
	strcpy(sSortDescendingByArea, "In ordine decrescente per area");
	strcpy(sSpecifyhowdifferentthepiecesinthelaststagecanbeValue0meansnodifference, "Specifica quanto possano essere diversi i pezzi nell'ultima fase. Il valore 0 significa che devono avere la stessa dimensione.");
	strcpy(sSpecifyifpiecesinthelaststagecanbedifferentornotdepeultimaetapapotfidiferitesaunucadimensiune, "Specifica se i pezzi nell'ultima fase possono essere diversi oppure no.");
	strcpy(sSpecifyifthepiececanberotatedornotIfnotitwillbecutinthesamewayasitwasintroducedinDemandLengthofthepieceparalleltothelengthofthesheet, "Specifica se il pezzo può essere ruotato o no. Se no, verrà messo nello stesso verso dell'inserimento (la lunghezza del pezzo parallela alla lunghezza del foglio), ");
	strcpy(sSpecifyinhowmanystageswemakethecutsDuringastageallcutshavethesamedirection, "Specifica in quante fasi effettuare i tagli.");
	strcpy(sStartthesearchprocess, "Avvia il processo di ricerca");
	strcpy(sStatistics, "Statistiche");
	strcpy(sStatisticsE, "Rapporti extra");
	strcpy(sStatisticsforeachtypeofmaterial, "Statistiche per ogni tipo di materiale");
	strcpy(sStep, "Fase");
	strcpy(sStergeDepozit, "Desideri eliminare l'Inventario?");
	strcpy(sStergeMaterial, "Desideri eliminare il materiale?");
	strcpy(sStergePiesele, "Desideri eliminare il pezzo?");
	strcpy(sStergePiesa, "Desideri eliminare il pezzo?");
	strcpy(sStopthesearchprocess, "Arresta il processo di ricerca");
	strcpy(sStrongoptimization, "Ottimizzazione forte");
	strcpy(sSubtractthebandthicknessfrompiecesize, "Diminuisci la dimensione dei pezzi con lo spessore del bordo");
	strcpy(sSummary, "Sommario");
	strcpy(sSuprafataTotalaFolosita, "Superficie totale utilizzata");
	strcpy(sSuprafatautilizata, "Utilizzo");
	strcpy(sSwitchbetweenfiberandrotationoption, "Scambia tra fibra e opzione di rotazione.");
	strcpy(sTechnical, "Tecniche");
	strcpy(sTechnicalsettings, "Impostazioni tecniche");
	strcpy(sTemporaryPanelHint, "Pannello temporaneo per spostare parti tra i fogli.");
	strcpy(sText, "Testo");
	strcpy(sThe_application_has_expired, "Il programma è scaduto.");
	strcpy(sThe_application_is_not_registered, "Il programma non è registrato.");
	strcpy(sThe_application_was_first_started_on, "Il programma è già stato avviato.");
	strcpy(sThecutsareperformedfromasidetotheothersideofthematerial, "I tagli vengono fatti da un lato all'altro del materiale.");
	strcpy(sThecuttingmachinecanfollowtheshapeofthematerial, "La macchina da taglio può seguire la forma del pezzo.");
	strcpy(sTheedgesofsheetsthatmustbetrimedduefaults, "I bordi del foglio che devono essere rifilati a causa di difetti");
	strcpy(sTheLargestSize, "La dimensione più grande");
	strcpy(sThenameofthecustomerforwhichyoucutthepiece, "Il nome del cliente per il quale si taglia il pezzo.");
	strcpy(sThenameofyourcustomer, "Il nome del tuo cliente");
	strcpy(sThepiececanberotated, "Il pezzo può essere ruotato");
	strcpy(sTheprogramtriestoavoidwasteswhichhavebothsizeslessthanthisvalue, "Il programma cerca di evitare sprechi che siano inferiori a questo valore");
	strcpy(sThereAreNoProducts, "Non sono stati ancora definiti i prodotti");
	strcpy(sThestockofmaterialhasbeenpreviouslyloadedfromanExcelorCSVformatPleaseloaditagain, "L'assortimento di materiale è stato caricato in precedenza da Excel o da file CSV. Ricaricalo nuovamente se desideri lavorare con quello.");
	strcpy(sThetotallengthofcutting, "La lunghezza totale di taglio");
	strcpy(sThewidthofthecuttingsawForglasscuttingoptimizationitcanbe0Forwooditshouldbegreaterthan0, "Lo spessore della sega. Per il taglio del vetro che può essere 0. Per il legno dovrebbe essere maggiore di 0.");
	strcpy(sThewidthofthecuttingsawforlinearpieces, "Lo spessore della sega per pezzi lineari.");
	strcpy(sThickness, "Spessore");
	strcpy(sThischaracterisusedforfillingthewasterectanglesIfyoudonotwantfilledwastejustremovethischaracter, "Questo simbolo viene usato per riempire i rettangoli di scarto. Se non desideri riempire gli scarti basta rimuoverlo.");
	strcpy(sThisindexhasvaluebetween1andthenumberofpieces, "L'indice ha un valore compreso tra 1 e il numero di pezzi.");
	strcpy(sThisOptionWillOverrideTheInventoryFileIfLoadedFromExcelOrCsvFiles, "Questa opzione sovrascrive il file di giacenza se caricato da Excel o file CSV.");
	strcpy(sThisProgramisLicensedTo, "Questo programma è concesso in licenza a");
	strcpy(sThisvaluewillbeaddedtotheedgebandingmaterialoneachside, "Questo valore verrà aggiunto al materiale di bordatura su ciascun lato");
	strcpy(sTipNevid, "Il tipo di materiale non può essere vuoto.");
	strcpy(sTitle, "Titolo");
	strcpy(sTools, "Strumenti");
	strcpy(sTop, "Sopra");
	strcpy(sTopcoordinateofthedefect, "La coordinata superiore del difetto.");
	strcpy(sTotalGarbageWaste, "Tutti gli sprechi scartati");
	strcpy(sTotalInventoryWaste, "Assortimento scarto totale");
	strcpy(sTotalRecycledWaste, "Tutti gli scarti riciclati");
	strcpy(sTotalusedarea, "Superficie totale utilizzata");
	strcpy(sTotalusedlength, "Lunghezza totale utilizzata");
	strcpy(sTrigonometric, "Trigonometrico");
	strcpy(sTrim, "Rifila");
	strcpy(sTrimalledgesatthebeginning, "Rifila tutti i bordi all'inizio");
	strcpy(sTrimEdge, "Rifila il bordo");
	strcpy(sTwoPanels, "2 pannelli");
	strcpy(sType, "Tipo");
	strcpy(sTypeofmaterialfromwhichtocut, "Tipo di materiale da cui tagliare");
	strcpy(sTypesAreNotMatched, "L'ottimizzazione non è stata eseguita! I materiali delle tabelle Parti e Scorte non corrispondono! È possibile tagliare una Parte solo dal materiale con lo stesso nome presente in magazzino. Modificare il nome dei materiali dalle colonne corrispondenti!");
	strcpy(sUndo, "Annulla");
	strcpy(sUndoAccept, "Annulla Accetta");
	strcpy(sUnits, "unità");
	strcpy(sUnregisteredVersion, "Non registrato");
	strcpy(sUpdates, "Aggiornamenti");
	strcpy(sUsefulforwoodfurniture, "Utile per mobili in legno");
	strcpy(sUseit, "Usalo");
	strcpy(sUsePieceinOptimization, "Usa il pezzo nell'ottimizzazione");
	strcpy(sUserName, "Nome utente");
	strcpy(sUtilizationandWastes, "Utilizzo e scarto");
	strcpy(sUtilizedArea, "Area delle parti utilizzata");
	strcpy(sUtilizedBars, "Barre utilizzate");
	strcpy(sUtilizeddemandcount, "Numero di parti utilizzate");
	strcpy(sUtilizedParts, "Parti utilizzate");
	strcpy(sUtilizedPieces, "Pezzi utilizzati");
	strcpy(sUtilizedSheets, "Fogli utilizzati");
	strcpy(sValue, "Valore");
	strcpy(sValueGreaterEqualToZero, "Il valore dev'essere maggiore o uguale a zero");
	strcpy(sValueGreaterThanZero, "Il valore deve'essere maggiore di zero");
	strcpy(sValueIntegerNumber, "Il valore deve essere un numero intero!");
	strcpy(sValueRealNumber, "Il valore dev'essere un numero reale, forse hai inserito virgole al posto dei punti o viceversa. Correggerlo, prego!");
	strcpy(s_The_number_is_too_big_or_it_has_too_many_digits_after_decimal_separator, "Il numero è troppo grande o ha troppe cifre dopo il separatore decimale!");
	strcpy(s_The_number_is_too_big, "Il numero è troppo grande!");
	strcpy(sVertical, "Verticale");
	strcpy(sWaste, "Scarto");
	strcpy(sWastes, "Scarto");
	strcpy(sWasteAddedToWarehouse, "Lo scarto aggiunto all'assortimento");
	strcpy(sWastelimits, "I limiti per lo scarto");
	strcpy(sWasteType, "Tipo di scarto");
	strcpy(sWeakoptimization, "Ottimizzazione debole");
	strcpy(sWhattoprint, "Cosa devo stampare");
	strcpy(s_What_to_print_or_save_to_file, "Cosa stampare o salvare su file");
	strcpy(sWhattoprintoneachpiece, "Cosa stampare su ogni pezzo");
	strcpy(sWhattoshowoneachpiece, "Cosa mostrare su ogni pezzo?");
	strcpy(sWidth, "Larghezza");
	strcpy(sWood, "legno");
	strcpy(sWorkingDirectory, "Directory di lavoro");
	strcpy(sWrongKey, "Chiave di registrazione errata!");
	strcpy(sYes, "Sì");
	strcpy(sYoucannotchooseblackblueorredcolors, "Non puoi scegliere i colori nero blu o rosso.");
	strcpy(sYouCannotMixFractionalDataWithDecimalOnes, "Non è possibile combinare i valori frazionari con valori reali!");
	strcpy(sYourcompany, "La tua azienda");
	strcpy(sZip, "Codice postale");
	strcpy(s_Set_the_origin_and_the_direction_of_the_axes, "Impostare l'origine e la direzione degli assi delle coordinate.");










	strcpy(s_Number_of_digits_after_the_decimal_separator, "Numero di cifre dopo il separatore decimale");
	strcpy(s_Percentages, "Percentuali");
}

