// Language strings: Dutch
// Author: Optimal Programs
// License: MIT License
//---------------------------------------------------------------------------
#include <string.h>
//---------------------------------------------------------------------------
#include "language_string_id.h"
//---------------------------------------------------------------------------
void set_nl(void)
{
	//Dutch
	//translated by a customer on 2022.12.22
	// last update on: 2025.9.25.0
	strcpy(s_Area, "Oppervlakte");
	strcpy(s_Mass, "Massa");
	strcpy(s_Advanced, "Geavanceerd");
	strcpy(s_Relative_coordinates, "Relatieve coördinaten");
	strcpy(s_Absolute_coordinates, "Absolute coördinaten");
	strcpy(s_Append_more_rows, "Voeg meer rijen toe");

	strcpy(s_Add_to_parts, "Toevoegen aan Onderdelen");
	strcpy(s_Additional, "Aanvullend");
	strcpy(s_All_results, "Alle resultaten.");
	strcpy(s_Allow_movement_of_pieces, "Verplaatsen Onderdelen toestaan");
	strcpy(s_Allow_part_in_part, "Onderdeel in Onderdeel toestaan");
	strcpy(s_Invalid_piece_Angles_are_too_small_or_too_big_or_height_is_too_small, "Ongeldig stuk! Hoeken zijn te klein of te groot, of de hoogte is te klein.");
	strcpy(s_Append, "Aanvullend");
	strcpy(s_As_it_is, "Zoals het is");
	strcpy(s_As_text, "Als tekst");
	strcpy(s_Ascending, "Oplopend");
	strcpy(s_Automatic, "Automatisch");
	strcpy(s_Cannot_connect_to_the_Internet_Please_visit_our_website_from_a_browser, "Kan geen verbinding maken met internet! Bezoek onze website vanuit een browser.");
	strcpy(s_Cannot_copy_or_move_the_files, "Kan de bestanden niet kopiëren of verplaatsen!");
	strcpy(s_Cannot_delete_the_file, "Kan het bestand niet verwijderen!");
	strcpy(s_Cannot_modify_old_results, "Oude resultaten kunnen niet worden gewijzigd!");
	strcpy(s_To_change_click_inside_a_cell_or_press_0_1_or_2, "Om te wijzigen, klik in een cel of druk op 0, 1 of 2.");
	strcpy(s_Cell, "Cel");
	strcpy(s_Click_on_the_table_header_to_change_the_columns, "Klik op de tabelkop om de kolommen te wijzigen.");
	strcpy(s_Close, "Sluiten");
	strcpy(s_Contact_us, "Neem contact met ons op");
	strcpy(s_Column, "Kolom");
	strcpy(s_Comma, "Komma");
	strcpy(s_The_comma_symbol_cannot_simultaneously_be_the_list_separator_and_the_decimal_separator, "Het kommasymbool kan niet tegelijkertijd lijstscheidingsteken en decimaalscheidingsteken zijn!");
	strcpy(s_Copy, "Kopiëren");
	strcpy(s_Copy_for_move, "Kopieer om te verplaatsen");
	strcpy(s_Cut_higher_level_strips_first, "Snijd eerst de stroken van het hogere niveau");
	strcpy(s_Cut_index, "Snede index");
	strcpy(s_Cuts_may_overlap, "Sneden mogen overlappen");
	strcpy(s_The_data_have_been_changed_Do_you_want_to_save_them_to_a_file, "De gegevens zijn gewijzigd. Wilt u ze opslaan?");
	strcpy(s_Decimal_separator, "Decimaalscheidingsteken");
	strcpy(s_Restore_default_settings, "Standaardinstellingen herstellen");
	strcpy(s_Delete_fiber, "Textuur verwijderen");
	strcpy(s_Descending, "Aflopend");
	strcpy(s_Discard_changes, "Veranderingen ongedaan maken");

	strcpy(s_Delete_all_data, "Alle gegevens verwijderen?");
	strcpy(s_Dot, "Punt");
	strcpy(s_Do_you_want_to_delete_the_picture, "Wilt u de afbeelding verwijderen?");
	strcpy(s_Do_you_want_to_delete_the_product, "Wilt u het Product verwijderen?");
	strcpy(s_Duplicate_and_append, "Kopieer en voeg toe");
	strcpy(s_Duplicate_values_are_ignored, "Dubbele waarden werden genegeerd!");
	strcpy(s_Error, "Fout");
	strcpy(s_Error_loading_file, "Fout bij laden van bestand.");
	strcpy(s_export_everything, "Alles exporteren");
	strcpy(s_Fit_to_screen, "Passend op scherm");
	strcpy(s_Force_fixed_height, "Teken de stukken met een vaste hoogte.");
	strcpy(s_Flipped, "Omgedraaid");
	strcpy(s_Import, "Importeren");
	strcpy(s_If_angles_are_different_from_90_degrees_height_must_be_greater_than_0, "Als de hoeken afwijken van 90 graden, moet de hoogte groter zijn dan 0.");
	strcpy(s_Ignore, "Negeren");
	strcpy(s_Incorrect_value, "Onjuiste waarde");
	strcpy(s_Info, "Info");
	strcpy(s_Interior, "Interieur");
	strcpy(s_Give_a_name, "Ken een naam toe.");
	strcpy(s_Group, "Groep");
	strcpy(s_Header, "Koptekst");
	strcpy(s_Keep_it_as_it_is, "Houd het zoals het is.");
	strcpy(s_Level, "Niveau");
	strcpy(s_Licensee, "Licentiehouder");
	strcpy(s_List_separator, "Lijstscheidingsteken");
	strcpy(s_Made_with_love_in_Cugir_Romania, "Gemaakt, met liefde, in Cugir, Roemenië");
	strcpy(s_Made_in, "Vervaardigd in");
	strcpy(s_Manufacturer, "Fabrikant");
	strcpy(s_Maximum_distance_between_2_linked_segments, "Maximale afstand tussen 2 gekoppelde segmenten");
	strcpy(s_Manual_arrange, "Handmatig regelen");
	strcpy(s_Mix_layers, "Houd rekening met entiteiten uit alle lagen");
	strcpy(s_Mixed, "Gemengd");
	strcpy(s_Multiple_shapes_detected_Next_rows_will_be_overwritten_Continue, "Er is meer dan één vorm gedetecteerd. Daarom worden de volgende rijen overschreven. Doorgaan?");
	strcpy(s_More, "Meer");
	strcpy(s_Multiple_values, "Meerdere waarden");
	strcpy(s_No_texture, "Geen textuur");
	strcpy(s_Number, "Aantal");
	strcpy(s_Number_of_images, "Aantal afbeeldingen");
	strcpy(s_Number_of_vertices, "Aantal hoekpunten");
	strcpy(s_Offset, "Verschuiving");
	strcpy(s_Only_the_currently_selected_items, "Alleen de momenteel geselecteerde items.");
	strcpy(s_Optimizing_please_wait, "Optimaliseren ... even geduld.");

	strcpy(s_Paste, "Plakken");
	strcpy(s_Paste_from_Clipboard, "Plakken van klembord");
	strcpy(s_Piece_label, "Toon Onderdeel etiket");
	strcpy(s_Piece_size, "Onderdeel afmeting");
	strcpy(s_Please_contact_us_by_email_if_you_receive_this_error, "Neem contact met ons op via e-mail als u deze foutmelding ontvangt.");
	strcpy(s_Please_save_it_first, "Sla het eerst op.");
	strcpy(s_Position, "Positie");
	strcpy(s_Preview, "Voorbeeld");
	strcpy(s_Rectangle, "Rechthoek");
	strcpy(s_Resolution, "Resolutie");
	strcpy(s_Redo_the_last_operation, "Herstel de laatste bewerking");
	strcpy(s_Regular_polygon, "Regelmatige veelhoek");
	strcpy(s_Relative, "Relatief");
	strcpy(s_Reused, "Hergebruikt");
	strcpy(s_Rotated, "Gedraaid");
	strcpy(s_Save_all, "Alles opslaan");
	strcpy(s_Scrap_label, "Gedraaid");
	strcpy(s_Scrap_size, "Afval-/reststuk afmeting");
	strcpy(s_Semicolon, "Puntkomma");
	strcpy(s_Show_cut_index, "Toon snede index");
	strcpy(s_Show_information, "Gedraaid");
	strcpy(s_Show_piece_label, "Toon Onderdeel etiketten");
	strcpy(s_Show_scrap_label, "Toon afval-/restlabel");
	strcpy(s_Show_scrap_s_size_on_the_small_pieces, "Toon reststuk-afmeting op kleine stukjes");
	strcpy(s_Show_size_of_pieces, "Toon Onderdeel afmeting");
	strcpy(s_Show_size_of_scrap, "Toon afval-/reststuk-afmeting");
	strcpy(s_Show_sizes, "Toon maten");
	strcpy(s_Show_label, "Etiket tonen");
	strcpy(s_Show_length, "Toon lengte");

	strcpy(s_Some_numerical_values_are_incorrect_Should_I_fix_all_the_incorrect_values, "Gedraaid");
	strcpy(s_Some_invalid_values_have_been_removed, "Sommige onjuiste waarden zijn verwijderd.");
	strcpy(s_Sort_by, "Gedraaid");
	strcpy(s_Sort_ascending_by, "Sorteer oplopend");
	strcpy(s_Sort_descending_by, "Sorteer aflopend");
	strcpy(s_Start, "Start");
	strcpy(s_Starting_angle, "Starthoek graden");
	strcpy(s_Starting_corner, "Beginhoek");
	strcpy(s_Starting_direction, "Startrichting");
	strcpy(s_Stock, "VOORRAAD");
	strcpy(s_Stop, "Stop");
	strcpy(s_System_setting, "Systeeminstelling");
	strcpy(s_Tabular, "Tabelvorm");
	strcpy(s_Total, "Totaal");
	strcpy(s_Total_size, "Totaal afmeting");
	strcpy(s_Terms_of_the_license, "Licentie voorwaarden");
	strcpy(s_The_current_product_has_been_changed_Do_you_want_to_save_it_to_file, "Het huidige Product is gewijzigd. Wilt u het opslaan?");
	strcpy(s_The_value_is_out_of_the_allowed_range, "De waarde valt buiten het toegestane bereik.");
	strcpy(s_The_value_must_be_a_real_or_fractional_number_Try_to_replace_the_comma_with_the_dot_if_you_want_to_enter_a_real_number, "De waarde moet een reëel _,__ of breukgetal zijn. Probeer de punt te vervangen door een komma, of omgekeerd.");
	strcpy(s_This_feature_is_not_implemented_yet, "Deze functie is nog niet geïmplementeerd.");
	strcpy(s_This_operation_cannot_be_reversed, "Deze bewerking kan niet ongedaan worden gemaakt.");
	strcpy(s_Undo_the_last_operation, "Maak de laatste bewerking ongedaan.");
	strcpy(s_Utilization, "Gebruik");
	strcpy(s_Utilized_Stock, "Gebruikte Voorraad");
	strcpy(s_Version, "Versie");
	strcpy(s_Visible_columns, "Zichtbare kolommen");
	strcpy(s_You_already_have_the_latest_version_installed, "Je hebt al de laatste versie geïnstalleerd!");
	strcpy(s_What_is_exported, "Wat wordt geëxporteerd?");
	strcpy(s0meansanynumberofpieces, "Nul betekent: elk aantal");
	strcpy(sAbout, "Over");
	strcpy(sAccept, "Accepteren");
	strcpy(sAcceptall, "Accepteer alles");
	strcpy(sAcceptthecurrentsolution, "Accepteer de huidige optimalisatie");
	strcpy(sAdd, "Toevoegen");
	strcpy(sAddapiece, "Voeg Onderdeel toe");
	strcpy(sAddasimpleproducttoDemand, "Voeg een Product toe aan de bestaande Onderdelen");
	strcpy(sAddgrindingthicknesstopartsize, "Voeg slijpdikte toe aan de Onderdeel afmeting");
	strcpy(sAddproductnametolabel, "Voeg de productnaam toe aan het label");
	strcpy(sAddress, "Adres");
	strcpy(sAddselectedsizetoInventory, "Voeg de geselecteerde afmeting toe aan de Voorraad");
	strcpy(sAdhesivelabels, "Zelfklevende labels");
	strcpy(sAdhesivelabelwithinformationaboutpiecesinDemandCustomernameLabelSizeCurrentData, "Zelfklevend label met Onderdeel infomatie: Naam van de klant, materiaal, afmeting, aanvullende gegevens.");
	strcpy(sAdhesivelabelwithinformationaboutsheetsinInventory, "Zelfklevend label met Voorraad informatie.");
	strcpy(sAll, "Allemaal");
	strcpy(sAlloffcutswhichhavethesizegreaterthanthisvaluewillbeaddedtoInventory, "Alle reststukken die de groter zijn dan deze waarde worden toegevoegd aan de Voorraad");
	strcpy(sAllowMirroring, "Spiegelen toestaan");
	strcpy(sAllowRotation, "Draaien toestaan");
	strcpy(sAllPieces, "Alle Onderdelen");
	strcpy(sAllpredefinedproducts, "Vooraf gedefinieerde Producten");
	strcpy(sAnewwindowwillbedisplayedwheretheusercansettheedgebandsforeachedge, "Een nieuw venster wordt geopend waarin de gebruiker het randband voor elke rand kan instellen.");
	strcpy(sAnewwindowwillbedisplayedwheretheusercansetthegrindingvalueforeachedgeofthsheet, "Een nieuw venster wordt geopend waarin de gebruiker de slijpmaat voor elke rand kan instellen.");
	strcpy(sAnewwindowwillbedisplayedwheretheusercansetthetrimvalueforeachedgeofthsheet, "Een nieuw venster wordt geopend waarin de gebruiker de trim-/gebrekbreedte voor elke rand kan instellen.");
	strcpy(sAngle, "Hoek");
	strcpy(sAngles, "Hoeken");
	strcpy(sAnoptimizationparameterisarealnumber, "Een optimalisatie parameter is een reëel getal.");
	strcpy(sAnoptimizationparameterisfractionalnumber, "Een optimalisatie parameter is breukgetal.");
	strcpy(sAnyShape, "Ware grootte");
	strcpy(sApolygonmusthaveatleast2vertices, "Een polygoon moet minimaal 2 hoekpunten hebben!");
	strcpy(sApolygonmusthaveatleast3vertices, "Een polygoon moet minimaal 3 hoekpunten hebben!");
	strcpy(sApplication_fails_to_initialize, "De applicatie kon niet worden geïnitialiseerd.");
	strcpy(sArc, "Boog");
	strcpy(sArcLength, "Booglengte");
	strcpy(sAreaofusedsheets, "Plaatoppervlak gebruikt");
	strcpy(sAshortdescriptionofthesheet, "Een korte omschrijving van de plaat");
	strcpy(sAtleastonepart, "Ten minste één Onderdeel invoeren.");
	strcpy(sAtTheMarginOfTheSheet, "Aan de rand van de plaat");
	strcpy(sBandtypes, "Randband soorten");
	strcpy(sBar, "Staaf/buis");
	strcpy(sBars, "Staven/buizen");
	strcpy(sBothsizesoftheoffcutsmustbegreaterthanthisvalue, "Lengte en breedte van het reststuk moeten groter zijn dan deze waarde.");
	strcpy(sBottom, "Onder");
	strcpy(sBottomcoordinateofthedefect, "Het onderzijde coördinaat van het gebrek");
	strcpy(sBreakCut, "Onderbreek de snede");
	strcpy(sBrowse, "Bladeren");
	strcpy(sBuy, "Kopen");
	strcpy(sBuynow, "Koop nu ...");
	strcpy(sCancel, "Annuleren");
	strcpy(sCannotBeEmpty, "Mag niet leeg zijn!");
	strcpy(sCannotmovepartsbetweensheetswhenidenticalsheetsaregroupedPleaseungroupthesheetsfrommenu, "Kan Onderdelen niet verplaatsen van het ene blad naar het andere als de identieke platen gegroepeerd zijn. Annuleren het groeperen van de platen uit het menu.");
	strcpy(sCannotSaveFile, "Kan het bestand niet opslaan");
	strcpy(sCenter, "Middelpunt");
	strcpy(s_Centering, "Centreren");
	strcpy(sChangeDirection, "Wijzig snederichting");
	strcpy(sChoose, "Kies");
	strcpy(sChooseProduct, "Kies Product");
	strcpy(sCircle, "Cirkel");
	strcpy(sCity, "Plaats");
	strcpy(sClear, "Wis");
	strcpy(sClockWise, "Met de klok mee");
	strcpy(sClosewindow, "Sluit venster");
	strcpy(sColor, "Kleur");
	strcpy(sColorofedgeband, "De kleur van randband");
	strcpy(sColorPattern, "Kleur/patroon");
	strcpy(sColorpiecesandwastes, "Gekleurde Onderdelen en afval");
	strcpy(sColumns, "Kolommen");
	strcpy(sComment, "Commentaar");
	strcpy(sCompanyname, "Bedrijfsnaam");
	strcpy(sComplexMaterialExists, "Naam van het materiaal is reeds in de lijst van complexe materialen. Geef het een nieuwe naam.");
	strcpy(sComputerCode, "Computer-code");
	strcpy(sComputerCodefromyourcomputer, "Computer code (van uw computer)");
	strcpy(sComputethetotalpriceofDemand, "Bereken de Onderdelen totaalprijs");
	strcpy(sContents, "Inhoud");
	strcpy(sContinutComanda, "Inhoudsopgave Onderdelen op datum");
	strcpy(sContinutDepozit, "Inhoudsopgave Voorraad op datum");
	strcpy(sConversionIsDoneOnlyWhenSomePiecesHaveFractionalValues, "Conversie wordt alleen uitgevoerd als sommige Onderdelen een breukgetal hebben.");
	strcpy(sConvertsTheSizeOfWasteToAFractionalUnit, "Toont de afval-/reststuk-afmeting als een breukgetal.");
	strcpy(sCouldNotSaveFile1, "Kan het bestand niet in de map plaatsen.");
	strcpy(sCouldNotSaveFile2, "U heeft wellicht onvoldoende rechten. Controleer en/of wijzig de Werkmap in het menu Instellingen in een map met schrijfrechten, bijvoorbeeld C:\\gebruikers");
	strcpy(sCreationdateYMDHMS, "Aanmaakdatum (Y / M / D, H: M: S)");
	strcpy(sCurrentDate, "Huidige datum");
	strcpy(sCurrentDiagram, "Huidig snedetekening of statistiek opslaan");
	strcpy(sCurrentMaterial, "Huidig Materiaal");
	strcpy(sCurrentversion, "Huidige versie");
	strcpy(sCurve_not_closed_Try_increasing_DXF_linking_distance_parameter, "De veelhoek is niet gesloten! Probeer de parameter DXF-verbindingsafstand te vergroten.");
	strcpy(sCustomer, "Klant");
	strcpy(sCustomerName, "Naam van de klant");
	strcpy(sCustomMessage, "Aangepaste melding");
	strcpy(sCutlength, "Snede-lengte");
	strcpy(sCut, "Snede");
	strcpy(sCuts, "Sneden");
	strcpy(sCutterThickness, "Snededikte");
	strcpy(sData, "Gegevens");
	strcpy(sDataCannotBeEmpty, "De gegevens mogen niet leeg zijn!");
	strcpy(sDateymdhms, "Datum (y/m/d/h:m:s)");
	strcpy(sDays_left_for_trial, "Dagen beschikbaar voor testen");
	strcpy(sDaysLeft, "dagen over");
	strcpy(sStandard, "Standaard");
	strcpy(sDefaultInterface, "Standaard Interface");
	strcpy(sDefects, "Gebreken");
	strcpy(sDefectsManager, "Gebreken beheer");
	strcpy(sDefectsofthematerialNopiecescanbeplacedinthefaultyzone, "Gebreken van het materiaal. Onderdelen kunnen niet in de gebrekenzone worden geplaatst.");
	strcpy(sDelete, "Verwijder");
	strcpy(sDeletePiece, "Verwijder Onderdeel");
	strcpy(sDeleteRow, "Verwijderen rij");
	strcpy(sDemandutilization, "Optimalisering van Onderdelen");
	strcpy(sDepozitulmodificat, "De gebruikte Voorraad is verwijderd. De reststukken zijn toegevoegd aan de Voorraad.");
	strcpy(sDepozitvid, "De Voorraad is leeg");
	strcpy(sDesk, "Bureaublad");
	strcpy(sDiagram, "Snedetekening");
	strcpy(sDiagrams, "Snedetekeningen");
	strcpy(sDiagramasatable, "Snedeplan in tabel");
	strcpy(sDigits, "cijfers");
	strcpy(sDimensiuniplaca, "Plaatafmeting");
	strcpy(sDirection, "Richting");
	strcpy(sDistanceBetweenRows, "Afstand tussen rijen");
	strcpy(sDonotuseit, "Gebruik het niet");
	strcpy(sDownload, "Downloaden");
	strcpy(sDoYouWantToClearTheData, "Wilt U de gegevens verwijderen?");
	strcpy(sDoYouWantToSaveDemand, "De Onderdelen zijn gewijzigd! U wilt de wijzigingen opslaan?");
	strcpy(sDoYouWantToSaveParts, "Wilt u de Onderdelen opslaan?");
	strcpy(sDoYouWantToSaveRepository, "De Voorraad is gewijzigd! U wilt de wijzigingen opslaan?");
	strcpy(sDrawing, "Tekening");
	strcpy(sDrawthesolutioncolorful, "Teken de optimalisatie in kleur");
	strcpy(sDuplicateTypes, "Enkele soorten zijn dubbel! Verwijder duplicaten.");
	strcpy(sDuplicateTypesWithComplex, "Enkele materiaalnamen bestaan al in de lijst van complexe types! Verwijder de duplicaten.");
	strcpy(sDuplicateValues, "Dubbele waarden");
	strcpy(sEdgeband, "Randband");
	strcpy(sEdgebandingwhichisplacedontheedgesofyourpiecePleasedefineedgebandingtypesfromMaterialsEdgeBandingmenu, "Randband komt aan één of meerdere randen van het Onderdeel. Specificeer het randband in het menu Materialen.");
	strcpy(sEdgebandsthatwillbeappliedtoeachpart, "De randbanden die worden toegepast op elk Onderdeel.");
	strcpy(sEdgeBandTolerance, "Overmaat voor randband");
	strcpy(sEdgesthatmustbecutduefaults, "De randen die gesneden moeten worden i.v.m. randgebreken.");
	strcpy(sEdgetoedge, "Van rand tot rand");
	strcpy(sEdit, "Wijzigen");
	strcpy(sEmail, "E-mail");
	strcpy(sEmptyData, "De gegevens zijn leeg!");
	strcpy(sEnabled, "Ingeschakeld");
	strcpy(sEnabledisabledefectsoftheinventorysheets, "Inschakelen / uitschakelen gebreken van de Voorraad");
	strcpy(sEnterLabel, "Voer het label in");
	strcpy(sEnterTheMaterialName, "Voer de naam van het materiaal in");
	strcpy(sEnterTheProductName, "Voer de naam van het Product in");
	strcpy(sEvaluationError, "Fout om de uitdrukking evaluatie!");
	strcpy(sExit, "Uitgang");
	strcpy(sExpired, "De licentie is verlopen! Registreer de software!");
	strcpy(sExport, "Exporteren");
	strcpy(sExportAllDiagrams, "Exporteer alle snedetekeningen");
	strcpy(sExportAllToASingleFile, "Exporteer alles naar één bestand");
	strcpy(sExportOptions, "Opties exporteren");
	strcpy(sExporttoDXFformat, "Exporteer naar DXF-formaat");
	strcpy(sExporttoExcel, "Exporteer naar Excel");
	strcpy(sExpresieIncorecta, "Verkeerde wiskundige formule!");
	strcpy(sExtensions, "Extensie");
	strcpy(sExtra, "Extra");
	strcpy(sExtraComponents, "Extra componenten");
	strcpy(sExtracomponentsattachedtoDemand, "Extra componenten bij Onderdelen");
	strcpy(sFile, "Bestand");
	strcpy(sFileName, "Bestandsnaam");
	strcpy(sFillWastes, "Arceer afval-/reststuk met schuine stepen");
	strcpy(sFindoptimalbarsheetsize, "Zoek de optimale afmeting voor staven/buizen en platen.");
	strcpy(sFindoptimalsizeofInventorypieces, "Zoek de optimale Voorraad staven/buizen en platen.");
	strcpy(sFirstcutMultiplestages, "Eerste snederichting bij meerdere fasen");
	strcpy(sFirstdirectionforcutishorizontal, "Eerste snederichting in horizontale-/lengte richting.");
	strcpy(sFirstdirectionforcutisvertical, "Eerste snederichting in verticale-/dwars richting.");
	strcpy(sFollowthecontourofpieces, "Volg de contour van de Onderdelen.");
	strcpy(sFont, "Lettertype");
	strcpy(sFontsize, "Lettergrootte");
	strcpy(sFullInfo, "Volledige informatie");
	strcpy(sDisposedWaste, "Afgedankt afval");
	strcpy(sGeneral, "Algemeen");
	strcpy(sGenerateCNC, "Genereer CNC");
	strcpy(sGrain, "Textuur");
	strcpy(sGraindirection, "Textuur richting");
	strcpy(sGraphic, "Grafisch");
	strcpy(sGreaterorequalto, "Afval moet groter dan of gelijk zijn aan:");
	strcpy(sGrid, "Tabellen");
	strcpy(sGrinding, "Slijpdikte");
	strcpy(sGrosimeTaieturaScalata, "De snededikte in de afbeelding kan afwijken van de werkelijke dikte, omdat de Onderdelen niet op schaal getekend zijn. Dit heeft geen invloed op de resultaten.");
	strcpy(sGroupidenticallayouts, "Groepeer identieke platen");
	strcpy(sGroupIdenticalParts, "Groepeer identieke Onderdelen");
	strcpy(sGroupingOfIdenticalPiecesIntoOneRow, "Groepeer identieke Onderdelen in één rij");
	strcpy(sGroupPartsAfterLoadingFromFile, "Groepeer Onderdelen bij laden uit bestand");
	strcpy(sHeight, "Breedte");
	strcpy(sHeighttolerance, "Tolerantie voor de breedte");
	strcpy(sHelp, "Help");
	strcpy(sHistory, "Geschiedenis");
	strcpy(sHorizontal, "Horizontaal/lengte");
	strcpy(sHowtodisplayprintedgebands, "Hoe randbanden aangeven?");
	strcpy(sIfyousetthebandforoneedgeallwillreceivethesamevalue, "Als u randband voor een zijde geeft, krijgen alle zijden dezelfde randbandwaarde.");
	strcpy(sIfyousetthegrindingforoneedgeallwillreceivethesamevalue, "Als u de slijpmaat voor een zijde geeft, krijgen alle zijden dezelfde waarde.");
	strcpy(sIfyousetthetrimforoneedgeallwillreceivethesamevalue, "Als u de trim-/gebrekbreedte voor een zijde geeft, krijgen alle zijden dezelfde waarde.");
	strcpy(sImageBounds, "Grenzen voor afbeelding");
	strcpy(sImageSize, "Afbeelding grootte");
	strcpy(sImportData, "Importeer de gegevens");
	strcpy(sIncorrectPassword, "Onjuist wachtwoord");
	strcpy(sIndex, "Index");
	strcpy(sInformationaboutcustomer, "Informatie over klant");
	strcpy(sInputALanguageName, "Geef de naam van de taal");
	strcpy(sInsert, "Invoegen");
	strcpy(sInsertPiece, "Voeg Onderdeel in");
	strcpy(sInterface, "Beeld");
	strcpy(sInterfaceSettings, "Beeldinstellingen");
	strcpy(sInvalidHardware, "Kan de hardware niet detecteren. Neem contact op met: contact@optimalprograms.com");
	strcpy(sInvalidNumber, "Ongeldig getal");
	strcpy(sInvalidOrderOfComputation, "Een optimalisatie van de lengte niet kan worden uitgevoerd. Er zijn kringverwijzingen in de omschrijving van het Product!");
	strcpy(sInvalidRegistration, "Registratie is ongeldig!");
	strcpy(sInvalidTime, "De tijd van uw systeem is ongeldig.");
	strcpy(sInventory, "VOORRAAD");
	strcpy(sisafractionalvalue, "is een breukgetal.");
	strcpy(sIsArc, "Is boog");
	strcpy(sisarealvalue, "Is een reëel getal");
	strcpy(sLabel, "Specificatie");
	strcpy(sLabels, "Labels");
	strcpy(sLanguage, "Taal");
	strcpy(sLatimeanumar0, "De breedte moet groter zijn dan 0!");
	strcpy(sLatimeanumarreal, "De breedte moet reëel getal zijn!");
	strcpy(sLayerName, "Laagnaam");
	strcpy(sLeft, "Links");
	strcpy(sLeftcoordinateofthedefect, "Het linker-coördinaat van het gebrek");
	strcpy(sLength, "Lengte");
	strcpy(sLengthofthepiecestocut, "Staaf-/buislengte voor het zagen");
	strcpy(sLengthofthepiecestocutfrom, "Plaatafmeting voor het zagen");
	strcpy(sLengthofusedbars, "Staaf-/buislengte gebruikt");
	strcpy(sLicenseAgreement, "Licentieovereenkomst");
	strcpy(sLinear, "Recht");
	strcpy(sLinethickness, "Pendikte");
	strcpy(sLoadafileandappenddatatothecurrentDemand, "Laad een bestand en voeg de gegevens toe aan de huidige ONDERDELEN.");
	strcpy(sLoadanexistingDemandfromafile, "Laad bestaande Onderdelen uit een bestand.");
	strcpy(sLoadAppend, "Laden en toevoegen");
	strcpy(sLoadEverything, "Laad alles");
	strcpy(sLoadInventory, "Laad de VOORRAAD");
	strcpy(sLoadInventoryandDemand, "Laad de VOORRAAD en de ONDERDELEN");
	strcpy(sLoadResults, "Laad de resultaten");
	strcpy(sLocked, "Vergrendeld");
	strcpy(sLogo, "Logo");
	strcpy(sLong, "Lang");
	strcpy(sLongerexecutiontime, "Langere optimaliseringstijd");
	strcpy(sLungime, "Lengte");
	strcpy(sLungimeanumar0, "De lengte moet groter zijn dan 0!");
	strcpy(sLungimeanumarreal, "De lengte moet reëel getal zijn!");
	strcpy(sLungimeaTotalaFolosita, "Totaal benutte lengte");
	strcpy(sMagnification, "Vergroting");
	strcpy(sMagnify, "Vergroten");
	strcpy(sMargins, "Marges");
	strcpy(sMarginsForPaper, "Marges voor papier");
	strcpy(sMarginsOfTheLabel, "Marges voor label");
	strcpy(sMaterial, "Materiaal");
	strcpy(sMaterialName, "Naam van het materiaal");
	strcpy(sMaterials, "Materialen");
	strcpy(sMaterialstypes, "Materialen soorten");
	strcpy(sMax, "Max");
	strcpy(sMaximalArea, "Maximaal oppervlak");
	strcpy(sMaximalCutLength, "Maximale Snijlengte");
	strcpy(sMaxlength, "Maximale lengte");
	strcpy(sMaxPiecesperBar, "Maximaal aantal Onderdelen per staaf/buis");
	strcpy(sMaxwidth, "Maximale breedte");
	strcpy(sMeasurementUnit, "Meeteenheid");
	strcpy(sMin, "Min");
	strcpy(sMinimalBreakSize, "Minimale afval-afmeting");
	strcpy(sMinimalUsefulSize, "Minimale Onderdeel afmeting");
	strcpy(sMinimalwastesizetoInventory, "Minimale reststuk afmeting toegevoegd aan Voorraad");
	strcpy(s_What_to_minimize, "Wat te minimaliseren?");
	strcpy(sMinlength, "Minimale lengte");
	strcpy(sMinwidth, "Minimale breedte");
	strcpy(sMirror, "Spiegelbeeld");
	strcpy(sMirroring, "Spiegelen");
	strcpy(sMiscellaneous, "Andere statistieken");
	strcpy(sModify, "Wijzigen");
	strcpy(sModifytheselectedpiece, "Wijzig het geselecteerde Onderdeel");
	strcpy(sMovePiece, "Verplaatsen");
	strcpy(sMultiplestages, "Meerdere fasen");
	strcpy(sName, "Naam");
	strcpy(sNameofedgeband, "Naam van randband");
	strcpy(sNewDEMANDUnsaveddatawillbelost, "Nieuwe Onderdelen? Niet-opgeslagen gegevens gaan verloren!");
	strcpy(sNewLanguage, "Nieuwe taal");
	strcpy(sNewMaterial, "Nieuw Materiaal");
	strcpy(sNewPasswordincorectlyintroduced, "Nieuw wachtwoord onjuist ingevoerd!");
	strcpy(sNewProduct, "Nieuw Product");
	strcpy(sNewversion, "Nieuwe versie");
	strcpy(sNo, "Nee");
	strcpy(sNumarBucati, "Aantal Onderdelen");
	strcpy(sNumberOfCopies, "Aantal exemplaren");
	strcpy(sNumberofstages, "Aantal fasen");
	strcpy(sNusuficienteplacidepozit, "Niet alle stukken zijn geoptimaliseerd. Mogelijke oorzaken: Er is onvoldoende Voorraad.");
	strcpy(sOfficeNotInstaled, "Microsoft Office is niet geïnstalleerd op uw computer of een incorrect versie is geïstalleerd!");
	strcpy(sOldpassworddoesnotmatch, "Oud wachtwoord, onjuist!");
	strcpy(sOnlinehelp, "Online hulp");
	strcpy(sOnlypiecesofthesameheightinthelaststage, "Onderdelen met dezelfde breedte in de laatste fase");
	strcpy(sOpen, "Open");
	strcpy(sOptimization, "Optimalisatie");
	strcpy(sOptimizationDone, "Optimalisatie uitgevoerd! U kunt het snedetekening afdrukken en/of opslaan. Druk op de knop Accept als u tevreden bent met de huidige oplossing. Anders drukt u opnieuw op Start.");
	strcpy(sOptimizationType, "Optimalisatie type");
	strcpy(sOptions, "Opties");
	strcpy(sOptionsrelatedtotheinterface, "Opties met betrekking tot de beeldinstellingen");
	strcpy(sor, "of");
	strcpy(sOthercomponents, "Andere componenten");
	strcpy(sOthers, "Diverse");
	strcpy(sOtherstatistics, "Diverse statistieken");
	strcpy(sOverrideExcelCSVfiles, "Overschrijven Excel-/CSV-bestanden");
	strcpy(sParameter, "Parameter");
	strcpy(sParts, "ONDERDELEN");
	strcpy(sPattern, "Patroon");
	strcpy(sPatternforwaste, "Patroon voor afval/reststuk");
	strcpy(sPerimeter, "Omtrek");
	strcpy(sPermitedRotationAngle, "Toegestane draaihoek");
	strcpy(sPhone, "Telefoon");
	strcpy(sPicture, "Afbeelding");
	strcpy(sPiece, "Onderdeel");
	strcpy(sPieceindex, "Onderdelen index");
	strcpy(sPieces, "Onderdelen");
	strcpy(sPiecesize, "Onderdeel-afmeting");
	strcpy(sPiecesizelabeledgebandwillbeprinted, "Onderdeel-afmeting, etiket en randband worden afgedrukt.");
	strcpy(sPierdere, "Afval");
	strcpy(sPixels, "pixels");
	strcpy(sPlacilefolositeDepozit, "Gebruikte staven/buizen uit de Voorraad.");
	strcpy(sPlease_contact_us_at_contact_nestingtechnologies_com, "Neem contact met ons op via: contact@nesting-technologies.com");
	strcpy(sPlease_contact_us_at_contact_optimalprograms_com, "Neem contact met ons op via: contact@optimalprograms.com");
	strcpy(sPleaseenteralldataeitherasfractionalorrealDonotmixthem, "Vul alle getallen in óf als reëel- óf als breukgetal. Niet door elkaar gebruiken!");
	strcpy(sPleaseEnterSomeTypesOfMaterials, "Er is geen materiaal gegeven. U kunt dit opgeven bij het Materialen menu.");
	strcpy(sPleasesendtheNameandtheCodetotheaddresscontactoptimalprogramscominordertoobtaintheRegistrationKey, "Om de Registratie sleutel te krijgen mailt u de Naam en de Code naar: contact@optimalprograms.com.");
	strcpy(sPolygon, "Veelhoek");
	strcpy(sPolygonsCircles, "Veelhoeken, cirkels");
	strcpy(sPrecision, "Nauwkeurigheid");
	strcpy(sPretulnumar0, "De prijs moet groter zijn dan 0!");
	strcpy(sPretulnumarreal, "De prijs moet een reëel getal zijn!");
	strcpy(sPreview, "Voorbeeld");
	strcpy(sPrice, "Prijs");
	strcpy(sPriceMustBeGreaterThanZero, "De prijs moet groter zijn dan nul");
	strcpy(sPriceofbars, "Prijs van staven/buizen");
	strcpy(sPriceperbar, "Prijs per staaf/buis");
	strcpy(sPricepersheet, "Prijs per plaat");
	strcpy(sPricepersquareunitofmaterial, "Prijs per vierkante eenheid");
	strcpy(sPriceperunit, "Prijs per lengte eenheid");
	strcpy(sPrint, "Afdrukken");
	strcpy(sPrintdiagramsastables, "Print snedeplan in tabelvorm");
	strcpy(sPrinter, "Printer");
	strcpy(sPrinterBounds, "Printer marges");
	strcpy(sPrinting, "Afdrukken");
	strcpy(sPrintonlyutilizedarea, "Druk alleen het geoptimaliseerde oppervlak af");
	strcpy(sPrintthecontentsoftheDemand, "Druk de Onderdelen af.");
	strcpy(sPrintthecontentsoftheInventory, "Druk de Voorraad af.");
	strcpy(sPrintthecurrentsolution, "Druk de huidige optimalisatie af.");
	strcpy(sPriority, "Prioriteit");
	strcpy(sPrioritytocutapieceZero0isthehighestpriority, "Prioriteit bij snijden. Nul (0) is de hoogste prioriteit.");
	strcpy(sProcentul0100, "Het percentage moet groter dan 0 en kleiner of gelijk aan 100 zijn!");
	strcpy(sProcentulnumarreal, "Het percentage moet een reëel getal zijn!");
	strcpy(sProductdefinition, "Omschrijving van het Product");
	strcpy(sProductExists, "Het Product bestaat reeds. Kies een andere naam.");
	strcpy(sProductName, "Productnaam");
	strcpy(sProduct, "Product");
	strcpy(sProducts, "Producten");
	strcpy(sProject, "Project");
	strcpy(sProperties, "Eigenschappen");
	strcpy(sProperty, "Eigenschap");
	strcpy(sQuantity, "Aantal");
	strcpy(sQuantitynumberofsheetsofthistype, "Aantal platen van dit type");
	strcpy(sRadius, "Straal");
	strcpy(sRectangular, "Rechthoekig");
	strcpy(sRedefinetypesofedgeband, "Herdefinieer randband soorten");
	strcpy(sRedefinetypesofmaterial, "Herdefinieer materiaal soorten");
	strcpy(sRegistration, "Registratie");
	strcpy(sRegistrationKeyfromOptimalPrograms, "Registratiesleutel");
	strcpy(sRegistrationSuccessful, "Registratie succesvol!");
	strcpy(sRemoveallpiecesinInventory, "Verwijder alles uit de Voorraad.");
	strcpy(sRemoveCut, "Verwijder snede");
	strcpy(sRemovetheselectedpiece, "Verwijder de geselecteerde regel");
	strcpy(sReports, "Rapporten");
	strcpy(sRequestedMaterial, "Benodigd materiaal");
	strcpy(sRestore, "Herstellen");
	strcpy(sResults, "Resultaten");
	strcpy(sReusedwaste, "Reststuk voor hergebruik");
	strcpy(sRight, "Rechts");
	strcpy(sRightcoordinateofthedefect, "Coördinaten van het gebrek vanaf rechts");
	strcpy(sRotation, "Draaiing");
	strcpy(sRotationAngle, "Draaihoek");
	strcpy(sRotationStep, "Draaistap");
	strcpy(sRoundAllFractionsTo, "De breukwaarde worden afgerond op");
	strcpy(sRow, "rij");
	strcpy(sRows, "Rijen");
	strcpy(sRun, "Laatste optimalisatie");
	strcpy(sRunningtime, "Optimalisatietijd");
	strcpy(sSameforall, "Hetzelfde voor alles");
	strcpy(sSave, "Opslaan");
	strcpy(sSaveAllImages, "Sla alle snedetekening op");
	strcpy(sSaveAs, "Opslaan als");
	strcpy(sSaveChanges, "De Onderdelen zijn gewijzigd. Wil je ze bewaren?");
	strcpy(sSaveCurrentImage, "Sla de huidige snedetekening op");
	strcpy(sSavedataparameters, "Gegevens en parameters opslaan");
	strcpy(sSaveEverything, "Alles opslaan");
	strcpy(sSaveInventory, "Voorraad opslaan");
	strcpy(sSaveInventoryandDemand, "Voorraad en Onderdelen opslaan");
	strcpy(sSaveResults, "Resultaten opslaan");
	strcpy(sSaveStatisticsinafile, "Statistieken opslaan");
	strcpy(sSavethecurrentimage, "Huidige snedetekening opslaan");
	strcpy(sSavethecurrentimageorstatistic, "Huidige snedetekening of statistieken opslaan");
	strcpy(sSavetheDEMANDinafile, "Opslaan");
	strcpy(sSavetheDemandinafilewithadifferentname, "Onderdelen opslaan als ...");
	strcpy(sSavetheREPOSITORYinafile, "Voorraad opslaan in een bestand");
	strcpy(sSerialNumber, "Registratiesleutel");
	strcpy(sService, "Onderhoud");
	strcpy(sSetDefaultValues, "Dit brengt alle parameters terug naar hun standaardwaarden. Alle instellingen gaan verloren. Weet je zeker dat je dit wilt doen?");
	strcpy(sSetedgeband, "Stel randband in");
	strcpy(sSetedgetrim, "Stel de snedebreedte in voor randgebreken");
	strcpy(sSetthesameedgebandforalledges, "Stel voor alle randen hetzelfde randband in");
	strcpy(sSetthesamegrindingforalledges, "Stel voor alle randen dezelfde slijpdikte in");
	strcpy(sSetthesametrimforalledges, "Stel voor alle randen dezelde snedebreedte voor randgebreken in");
	strcpy(sSettings, "Instellingen");
	strcpy(sShape, "Vorm");
	strcpy(sSheet, "Platen");
	strcpy(sSheetsBarstypes, "Platen en staven_pijpen");
	strcpy(sSheetSize, "Plaatafmeting");
	strcpy(sSheetsperPage, "Plaat per pagina");
	strcpy(sShort, "Kort");
	strcpy(sShorterexecutiontime, "Korte optimalisatietijd");
	strcpy(sShowallsimpleproducts, "Toon alle enkelvoudige Producten");
	strcpy(sShowcustomername, "Toon naam van de klant");
	strcpy(sShowCustomTextOnEachPiece, "Toon volgende tekst op elk Onderdeel:");
	strcpy(sShowdiagramasatable, "Toon het snedeplan in tabelvorm");
	strcpy(sShowedgeband, "Toon randband");
	strcpy(sShowedgebandssettinginanewwindow, "Toon de instellingen van de randbanden in een nieuw venster");
	strcpy(sShowgrindingsettingsinanewwindow, "Toon slijpinstellingen in een nieuw venster");
	strcpy(sShowHorizontalLabelsAlways, "Toon etiket altijd horizontale");
	strcpy(sShowRemovethesizeofthepiecesinthecurrentsolution, "Toon / verberg de afmeting van de stukken.");
	strcpy(sShowRemovethesizeofthewastesinthecurrentsolution, "Toon / verberg de afmeting van het afval/reststuk.");
	strcpy(sShowtotalcutlength, "Toon totale snedelengte");
	strcpy(sShowtrimedgesettingsinanewwindow, "Toon de instellingen van de gebreken in een nieuw venster");
	strcpy(sSimpleMaterialExists, "Naam van het materiaal staat reeds in de lijst van materialen. Geef het een nieuwe naam.");
	strcpy(sSinglePieceStrips, "Arcering van een Onderdeel");
	strcpy(sSizes, "Afmetingen");
	strcpy(sSmallerorequalto, "Het afval moet kleiner dan of gelijk zijn aan");
	strcpy(sSort, "Sorteer");
	strcpy(sSortAscendingByArea, "Sorteer op oppervlak in oplopende volgorde");
	strcpy(sSortDescendingByArea, "Sorteer op oppervlak in aflopende volgorde");
	strcpy(sSpecifyhowdifferentthepiecesinthelaststagecanbeValue0meansnodifference, "Geef aan hoe verschillend de onderdelen mogen zijn na de laatste fase. Waarde 0 betekent dat er geen verschil mag zijn");
	strcpy(sSpecifyifpiecesinthelaststagecanbedifferentornotdepeultimaetapapotfidiferitesaunucadimensiune, "Geef aan of onderdelen na de laatste fase verschillend mogen zijn of niet.");
	strcpy(sSpecifyifthepiececanberotatedornotIfnotitwillbecutinthesamewayasitwasintroducedinDemandLengthofthepieceparalleltothelengthofthesheet, "Geef aan of het onderdeel gedraaid mag worden of niet. Zo niet, dan word het gesneden op dezelfde wijze als werd opgegeven (de lengte van het onderdeel evenwijdig aan de lengte van de plaat),");
	strcpy(sSpecifyinhowmanystageswemakethecutsDuringastageallcutshavethesamedirection, "Geef aan in hoeveel fasen de sneden gemaakt mogen worden.");
	strcpy(sStartthesearchprocess, "Start de optimalisatie");
	strcpy(sStatistics, "Statistieken");
	strcpy(sStatisticsE, "Rapporteer Extra");
	strcpy(sStatisticsforeachtypeofmaterial, "Statistieken voor elk materiaal");
	strcpy(sStep, "Stap");
	strcpy(sStergeDepozit, "Wilt U de Voorraad verwijderen?");
	strcpy(sStergeMaterial, "Wilt U dit Voorraadmateriaal verwijderen?");
	strcpy(sStergePiesele, "Wilt U de Onderdelen verwijderen?");
	strcpy(sStergePiesa, "Wilt U dit Onderdeel verwijderen?");
	strcpy(sStopthesearchprocess, "Stop het zoekproces");
	strcpy(sStrongoptimization, "Sterke optimalisatie");
	strcpy(sSubtractthebandthicknessfrompiecesize, "Verlaag de Onderdeel afmeting met de randband dikte");
	strcpy(sSummary, "Samenvatting");
	strcpy(sSuprafataTotalaFolosita, "Oppervlak gebruikte Voorraad");
	strcpy(sSuprafatautilizata, "Rendement");
	strcpy(sSwitchbetweenfiberandrotationoption, "Wisselen tussen textuur en draai-optie.");
	strcpy(sTechnical, "Technisch");
	strcpy(sTechnicalsettings, "Technische instellingen");
	strcpy(sTemporaryPanelHint, "Tijdelijke paneel voor verplaatsen onderdelen tussen platen.");
	strcpy(sText, "Tekst");
	strcpy(sThe_application_has_expired, "Het programma is verlopen.");
	strcpy(sThe_application_is_not_registered, "Het programma is niet geregistreerd.");
	strcpy(sThe_application_was_first_started_on, "Het programma werd voor het eerst gebruikt op");
	strcpy(sThecutsareperformedfromasidetotheothersideofthematerial, "De snede worden gemaakt van ene naar de andere zijde van de plaat.");
	strcpy(sThecuttingmachinecanfollowtheshapeofthematerial, "De snijmachine kan de vorm van het onderdeel volgen.");
	strcpy(sTheedgesofsheetsthatmustbetrimedduefaults, "De randen van platen die moeten worden getrimd/afgesneden i.v.m. gebreken");
	strcpy(sTheLargestSize, "De grootste maat.");
	strcpy(sThenameofthecustomerforwhichyoucutthepiece, "De naam van de klant voor wie je het Onderdeel snijdt.");
	strcpy(sThenameofyourcustomer, "De naam van uw klant");
	strcpy(sThepiececanberotated, "Het Onderdeel kan worden gedraaid");
	strcpy(sTheprogramtriestoavoidwasteswhichhavebothsizeslessthanthisvalue, "Het programma probeert afval te voorkomen dat kleiner is dan deze waarde");
	strcpy(sThereAreNoProducts, "Er zijn nog geen gedefinieerde Producten.");
	strcpy(sThestockofmaterialhasbeenpreviouslyloadedfromanExcelorCSVformatPleaseloaditagain, "De Voorraad van het materiaal is geladen met een Excel- of CSV-bestand. Laad het opnieuw als u er in wilt werken.");
	strcpy(sThetotallengthofcutting, "De totale snijlengte");
	strcpy(sThewidthofthecuttingsawForglasscuttingoptimizationitcanbe0Forwooditshouldbegreaterthan0, "De dikte van de zaag. Voor glas snijden kan het 0 zijn. Voor hout moet het groter dan 0 zijn.");
	strcpy(sThewidthofthecuttingsawforlinearpieces, "De dikte van de zaag voor rechte stukken.");
	strcpy(sThickness, "Dikte");
	strcpy(sThischaracterisusedforfillingthewasterectanglesIfyoudonotwantfilledwastejustremovethischaracter, "Dit symbool wordt gebruikt voor het vullen van de afval rechthoeken. Als u geen gevuld afval wens, gewoon verwijderen.");
	strcpy(sThisindexhasvaluebetween1andthenumberofpieces, "Deze index heeft een waarde tussen 1 en het aantal onderdelen.");
	strcpy(sThisOptionWillOverrideTheInventoryFileIfLoadedFromExcelOrCsvFiles, "Deze optie vervangt het Voorraad bestand als deze geladen is met een Excel- of CSV-bestand.");
	strcpy(sThisProgramisLicensedTo, "Dit programma is in licentie gegeven aan");
	strcpy(sThisvaluewillbeaddedtotheedgebandingmaterialoneachside, "Deze waarde wordt toegevoegd aan de randbanden aan elke zijde");
	strcpy(sTipNevid, "Het type materiaal kan niet leeg zijn.");
	strcpy(sTitle, "Onderwerp");
	strcpy(sTools, "Hulpmiddelen");
	strcpy(sTop, "Boven");
	strcpy(sTopcoordinateofthedefect, "Het bovenste coördinaat van het gebrek.");
	strcpy(sTotalGarbageWaste, "Alle verwijderd afval");
	strcpy(sTotalInventoryWaste, "Totaal voorraad afval");
	strcpy(sTotalRecycledWaste, "Alle reststukken voor hergebruik");
	strcpy(sTotalusedarea, "Totaal Onderdelen-oppervlak geoptimaliseerd");
	strcpy(sTotalusedlength, "Totaal Onderdelen-lengte geoptimaliseerd");
	strcpy(sTrigonometric, "Trigonometrische");
	strcpy(sTrim, "Trimmen");
	strcpy(sTrimalledgesatthebeginning, "Trim/snij alle randen aan het begin");
	strcpy(sTrimEdge, "Trim/snijd de rand");
	strcpy(sTwoPanels, "2 panelen");
	strcpy(sType, "Soort");
	strcpy(sTypeofmaterialfromwhichtocut, "Soort materiaal om te snijden");
	strcpy(sTypesAreNotMatched, "De optimalisatie is niet uitgevoerd! De materialen uit de onderdelen- en voorraadtabellen komen niet overeen! Een onderdeel kan alleen worden gesneden uit het materiaal met dezelfde naam dat op voorraad is. Wijzig de materiaalnaam in de overeenkomstige kolommen!");
	strcpy(sUndo, "Ongedaan maken");
	strcpy(sUndoAccept, "Ongedaan maken Accepteer");
	strcpy(sUnits, "Eenheden");
	strcpy(sUnregisteredVersion, "Niet-geregistreerd");
	strcpy(sUpdates, "Revisie");
	strcpy(sUsefulforwoodfurniture, "Handig voor houten meubels");
	strcpy(sUseit, "Gebruik het");
	strcpy(sUsePieceinOptimization, "Gebruik het onderdeel in de optimalisatie");
	strcpy(sUserName, "Gebruikersnaam");
	strcpy(sUtilizationandWastes, "Geoptimaliseerd en afval");
	strcpy(sUtilizedArea, "Oppervlak van geoptimaliseerde Onderdelen");
	strcpy(sUtilizedBars, "Gebruikte staven/buizen");
	strcpy(sUtilizeddemandcount, "Aantal Onderdelen geoptimaliseerd");
	strcpy(sUtilizedParts, "Onderdelen geoptimaliseerd");
	strcpy(sUtilizedPieces, "Gebruikte Voorraad");
	strcpy(sUtilizedSheets, "Gebruikte Voorraad");
	strcpy(sValue, "Totaal");
	strcpy(sValueGreaterEqualToZero, "De waarde moet groter dan of gelijk zijn aan nul.");
	strcpy(sValueGreaterThanZero, "De waarde moet groter zijn dan nul.");
	strcpy(sValueIntegerNumber, "De waarde moet een geheel getal zijn!");
	strcpy(sValueRealNumber, "De waarde moet een reëel getal zijn. Misschien heb je een komma gebruikt, in plaats van punt, of andersom. Corrigeer dit!");
	strcpy(s_The_number_is_too_big_or_it_has_too_many_digits_after_decimal_separator, "Het getal is te groot of het heeft te veel cijfers achter het decimaalteken!");
	strcpy(s_The_number_is_too_big, "Het getal is te groot!");
	strcpy(sVertical, "Verticaal");
	strcpy(sWaste, "Rest");
	strcpy(sWastes, "Rest");
	strcpy(sWasteAddedToWarehouse, "Reststuk toegevoegd aan Voorraad");
	strcpy(sWastelimits, "Lengte van het afval");
	strcpy(sWasteType, "Keuze afval-/reststuk");
	strcpy(sWeakoptimization, "De zwakste optimalisatie");
	strcpy(sWhattoprint, "Wat moet ik afdrukken?");
	strcpy(s_What_to_print_or_save_to_file, "Wat te printen of op te slaan in een bestand");
	strcpy(sWhattoprintoneachpiece, "Wat afdrukken op elke Onderdeel?");
	strcpy(sWhattoshowoneachpiece, "Wat tonen op elk onderdeel?");
	strcpy(sWidth, "Breedte");
	strcpy(sWood, "hout");
	strcpy(sWorkingDirectory, "Werkmap");
	strcpy(sWrongKey, "Verkeerde registratiesleutel!");
	strcpy(sYes, "Ja");
	strcpy(sYoucannotchooseblackblueorredcolors, "Je kunt geen zwart, blauw of rood kiezen.");
	strcpy(sYouCannotMixFractionalDataWithDecimalOnes, "Je kunt geen breukgetallen en reele getallen door elkaar gebruiken!");
	strcpy(sYourcompany, "Uw bedrijf");
	strcpy(sZip, "Postcode");
	strcpy(s_Set_the_origin_and_the_direction_of_the_axes, "Stel de oorsprong en de richting van de coördinatenassen in.");










	strcpy(s_Number_of_digits_after_the_decimal_separator, "Aantal cijfers na het decimaalteken");
	strcpy(s_Percentages, "Percentages");
}

