// Language strings: Koreean
// Author: Optimal Programs
// License: MIT License
//---------------------------------------------------------------------------
#include <string.h>
//---------------------------------------------------------------------------
#include "language_string_id.h"
//---------------------------------------------------------------------------
void set_kr(void)
{
	//Koreean
	// translated by a customer
	// last update on: 2025.9.25.0
	strcpy(s_Area, "면적");
	strcpy(s_Mass, "질량");
	strcpy(s_Advanced, "고급의");
	strcpy(s_Relative_coordinates, "상대 좌표");
	strcpy(s_Absolute_coordinates, "절대 좌표");
	strcpy(s_Append_more_rows, "더 많은 행 추가");

	strcpy(s_Add_to_parts, "부품에 추가하십시오.");
	strcpy(s_Additional, "추가의");
	strcpy(s_All_results, "모든 결과.");
	strcpy(s_Allow_movement_of_pieces, "조각 이동 허용");
	strcpy(s_Allow_part_in_part, "조각 허용");
	strcpy(s_Invalid_piece_Angles_are_too_small_or_too_big_or_height_is_too_small, "잘못된 조각! 각도가 너무 작거나 너무 크거나 높이가 너무 작습니다.");
	strcpy(s_Append, "추가");
	strcpy(s_As_it_is, "그대로");
	strcpy(s_As_text, "텍스트로");
	strcpy(s_Ascending, "오름차순");
	strcpy(s_Automatic, "자동적 인");
	strcpy(s_Cannot_connect_to_the_Internet_Please_visit_our_website_from_a_browser, "인터넷에 연결할 수 없습니다! 브라우저에서 웹 사이트를 방문하십시오.");
	strcpy(s_Cannot_copy_or_move_the_files, "파일을 복사하거나 이동할 수 없습니다!");
	strcpy(s_Cannot_delete_the_file, "파일을 삭제할 수 없습니다!");
	strcpy(s_Cannot_modify_old_results, "이전 결과는 수정할 수 없습니다!");
	strcpy(s_To_change_click_inside_a_cell_or_press_0_1_or_2, "변경하려면 셀 내부를 클릭하거나 0, 1 또는 2를 누릅니다.");
	strcpy(s_Cell, "셀");
	strcpy(s_Click_on_the_table_header_to_change_the_columns, "열을 변경하려면 표 머리글을 클릭하십시오.");
	strcpy(s_Close, "닫아");
	strcpy(s_Contact_us, "문의하기");
	strcpy(s_Column, "열");
	strcpy(s_Comma, "반점");
	strcpy(s_The_comma_symbol_cannot_simultaneously_be_the_list_separator_and_the_decimal_separator, "쉼표 기호는 동시에 목록 구분 기호와 소수 구분 기호로 사용될 수 없습니다!");
	strcpy(s_Copy, "부");
	strcpy(s_Copy_for_move, "이동을 위해 복사");
	strcpy(s_Cut_higher_level_strips_first, "먼저 상위 레벨의 스트립을 잘라내세요");
	strcpy(s_Cut_index, "절단 순서 표시");

	strcpy(s_The_data_have_been_changed_Do_you_want_to_save_them_to_a_file, "데이터가 변경되었습니다. 파일에 저장 하시겠습니까?");
	strcpy(s_Decimal_separator, "소수 구분 기호");
	strcpy(s_Restore_default_settings, "기본 설정 복원");
	strcpy(s_Delete_fiber, "섬유 삭제");
	strcpy(s_Descending, "내림차순");
	strcpy(s_Discard_changes, "변경 사항을 취소");

	strcpy(s_Delete_all_data, "모든 데이터를 삭제하시겠습니까?");
	strcpy(s_Dot, "점");
	strcpy(s_Do_you_want_to_delete_the_picture, "사진을 삭제 하시겠습니까?");
	strcpy(s_Do_you_want_to_delete_the_product, "제품을 삭제 하시겠습니까?");
	strcpy(s_Duplicate_and_append, "복제하고 추가합니다.");
	strcpy(s_Duplicate_values_are_ignored, "중복 값이 무시되었습니다!");
	strcpy(s_Error, "오류");
	strcpy(s_Error_loading_file, "파일을로드하는 중에 오류가 발생했습니다.");
	strcpy(s_export_everything, "모든 것을 내보내기");
	strcpy(s_Fit_to_screen, "화면에 맞추기.");
	strcpy(s_Force_fixed_height, "고정된 높이로 조각을 그립니다.");
	strcpy(s_Flipped, "뒤집힌");
	strcpy(s_Import, "가져오기");
	strcpy(s_If_angles_are_different_from_90_degrees_height_must_be_greater_than_0, "각도가 90도가 아닌 경우 높이는 0보다 커야 합니다.");
	strcpy(s_Ignore, "무시하다");
	strcpy(s_Incorrect_value, "잘못된 값");
	strcpy(s_Info, "정보");
	strcpy(s_Interior, "내부");
	strcpy(s_Give_a_name, "이름을 지어주세요.");
	strcpy(s_Group, "그룹화");
	strcpy(s_Header, "머리글");
	strcpy(s_Keep_it_as_it_is, "그대로 유지");
	strcpy(s_Level, "Level");
	strcpy(s_Licensee, "면허 받은 사람");
	strcpy(s_List_separator, "목록 구분 기호");
	strcpy(s_Made_with_love_in_Cugir_Romania, "루마니아 쿠기르에서 사랑으로 만들어졌습니다.");
	strcpy(s_Made_in, "에서 제조");
	strcpy(s_Manufacturer, "제조사");

	strcpy(s_Manual_arrange, "수동 정렬");

	strcpy(s_Mixed, "혼합");
	strcpy(s_Multiple_shapes_detected_Next_rows_will_be_overwritten_Continue, "둘 이상의 모양이 감지되었습니다. 따라서 후속 행을 덮어씁니다. 계속하다?");
	strcpy(s_More, "더");
	strcpy(s_Multiple_values, "여러 값");
	strcpy(s_No_texture, "텍스처 없음");
	strcpy(s_Number, "번호");
	strcpy(s_Number_of_images, "이미지 수");
	strcpy(s_Number_of_vertices, "꼭짓점 수");
	strcpy(s_Offset, "오프셋");
	strcpy(s_Only_the_currently_selected_items, "현재 선택된 항목만.");
	strcpy(s_Optimizing_please_wait, "최적화 중... 잠시만 기다려 주십시오.");

	strcpy(s_Paste, "Paste");

	strcpy(s_Piece_label, "조각 라벨");
	strcpy(s_Piece_size, "조각의 크기");
	strcpy(s_Please_contact_us_by_email_if_you_receive_this_error, "이 오류가 발생하면 이메일로 문의하십시오.");
	strcpy(s_Please_save_it_first, "먼저 저장하십시오.");
	strcpy(s_Position, "위치");
	strcpy(s_Preview, "시사");
	strcpy(s_Rectangle, "사각형");

	strcpy(s_Redo_the_last_operation, "마지막 작업 복원");
	strcpy(s_Regular_polygon, "정다각형");

	strcpy(s_Reused, "재사용");
	strcpy(s_Rotated, "회전");
	strcpy(s_Save_all, "모두 저장");
	strcpy(s_Scrap_label, "스크랩 라벨");
	strcpy(s_Scrap_size, "스크랩의 크기");
	strcpy(s_Semicolon, "세미콜론");
	strcpy(s_Show_cut_index, "절단 순서 표시");
	strcpy(s_Show_information, "정보 표시");
	strcpy(s_Show_piece_label, "조각 라벨");
	strcpy(s_Show_scrap_label, "스크랩 라벨");
	strcpy(s_Show_scrap_s_size_on_the_small_pieces, "작은 조각에 스크랩 크기 표시");
	strcpy(s_Show_size_of_pieces, "조각의 크기");
	strcpy(s_Show_size_of_scrap, "스크랩의 크기");
	strcpy(s_Show_sizes, "크기 표시");
	strcpy(s_Show_label, "레이블 표시");
	strcpy(s_Show_length, "쇼 길이");

	strcpy(s_Some_numerical_values_are_incorrect_Should_I_fix_all_the_incorrect_values, "일부 수치가 잘못되었습니다! 잘못된 값을 모두 수정해야합니까?");
	strcpy(s_Some_invalid_values_have_been_removed, "일부 유효하지 않은 값이 제거되었습니다.");
	strcpy(s_Sort_by, "정렬 기준");
	strcpy(s_Sort_ascending_by, "오름차순 정렬");
	strcpy(s_Sort_descending_by, "내림차순 정렬");
	strcpy(s_Start, "Start");
	strcpy(s_Starting_angle, "시작 각도");


	strcpy(s_Stock, "재고");
	strcpy(s_Stop, "Stop");
	strcpy(s_System_setting, "시스템 설정");
	strcpy(s_Tabular, "표의");
	strcpy(s_Total, "총");
	strcpy(s_Total_size, "총합 크기");
	strcpy(s_Terms_of_the_license, "라이센스 조건");
	strcpy(s_The_current_product_has_been_changed_Do_you_want_to_save_it_to_file, "현재 제품이 변경되었습니다. 파일에 저장 하시겠습니까?");
	strcpy(s_The_value_is_out_of_the_allowed_range, "값이 허용 범위를 벗어났습니다.");
	strcpy(s_The_value_must_be_a_real_or_fractional_number_Try_to_replace_the_comma_with_the_dot_if_you_want_to_enter_a_real_number, "값은 실수 또는 소수 여야합니다. 실수를 입력하려면 쉼표를 점으로 바꾸십시오.");
	strcpy(s_This_feature_is_not_implemented_yet, "이 기능은 아직 구현되지 않았습니다.");
	strcpy(s_This_operation_cannot_be_reversed, "이 작업은 되돌릴 수 없습니다.");
	strcpy(s_Undo_the_last_operation, "마지막 작업을 취소하십시오.");
	strcpy(s_Utilization, "이용");
	strcpy(s_Utilized_Stock, "사용 재고");
	strcpy(s_Version, "버전");
	strcpy(s_Visible_columns, "보이는 열");
	strcpy(s_You_already_have_the_latest_version_installed, "최신 버전이 이미 설치되어 있습니다!");
	strcpy(s_What_is_exported, "무엇을 내보내나요?");
	strcpy(s0meansanynumberofpieces, "0은 임의 개수의 조각을 의미합니다");
	strcpy(sAbout, "정보");
	strcpy(sAccept, "수락하기");
	strcpy(sAcceptall, "모두 수락하기");
	strcpy(sAcceptthecurrentsolution, "현재 솔루션 수락");
	strcpy(sAdd, "추가");
	strcpy(sAddapiece, "조각 추가");
	strcpy(sAddasimpleproducttoDemand, "기존 파트에 제품 추가하기");
	strcpy(sAddgrindingthicknesstopartsize, "조각 크기에 연삭 두께 추가하기");
	strcpy(sAddproductnametolabel, "레이블에 제품 이름 추가하기");
	strcpy(sAddress, "주소");
	strcpy(sAddselectedsizetoInventory, "선택한 크기를 재고에 추가하기");
	strcpy(sAdhesivelabels, "접착 라벨");
	strcpy(sAdhesivelabelwithinformationaboutpiecesinDemandCustomernameLabelSizeCurrentData, "고객명, 레이블, 크기, 현재 데이터 등 조각에 대한 정보가있는 접착 라벨");
	strcpy(sAdhesivelabelwithinformationaboutsheetsinInventory, "용지에 대한 정보가 있는 접착 라벨");
	strcpy(sAll, "모두");
	strcpy(sAlloffcutswhichhavethesizegreaterthanthisvaluewillbeaddedtoInventory, "이 값보다 큰 모든 스크랩이 재고에 추가됩니다.");
	strcpy(sAllowMirroring, "뒤집기 허용");
	strcpy(sAllowRotation, "회전 허용");
	strcpy(sAllPieces, "모든 조각");
	strcpy(sAllpredefinedproducts, "사전 정의 된 모든 제품");
	strcpy(sAnewwindowwillbedisplayedwheretheusercansettheedgebandsforeachedge, "사용자가 각면의 엣지 밴드를 설정할 수있는 새 창이 표시됩니다.");
	strcpy(sAnewwindowwillbedisplayedwheretheusercansetthegrindingvalueforeachedgeofthsheet, "사용자가 조각의 각면에 대한 연삭 크기를 설정할 수있는 새 창이 표시됩니다.");
	strcpy(sAnewwindowwillbedisplayedwheretheusercansetthetrimvalueforeachedgeofthsheet, "사용자가 조각의 각면에 대한 트림 값을 설정할 수있는 새 창이 표시됩니다.");
	strcpy(sAngle, "각도");
	strcpy(sAngles, "각도");
	strcpy(sAnoptimizationparameterisarealnumber, "최적화 매개 변수는 실수입니다.");
	strcpy(sAnoptimizationparameterisfractionalnumber, "최적화 매개 변수는 분수입니다.");
	strcpy(sAnyShape, "진정한 모양");
	strcpy(sApolygonmusthaveatleast2vertices, "다각형에는 꼭짓점이 2 개 이상 있어야합니다!");
	strcpy(sApolygonmusthaveatleast3vertices, "다각형에는 꼭짓점이 3 개 이상 있어야합니다!");
	strcpy(sApplication_fails_to_initialize, "응용 프로그램을 초기화하지 못했습니다!");
	strcpy(sArc, "아크");
	strcpy(sArcLength, "아크 길이");
	strcpy(sAreaofusedsheets, "활용된 시트 영역");
	strcpy(sAshortdescriptionofthesheet, "시트에 대한 간단한 설명");
	strcpy(sAtleastonepart, "최소한 한 장을 입력해야 합니다.");
	strcpy(sAtTheMarginOfTheSheet, "시트의 여백");
	strcpy(sBandtypes, "엣지 밴드의 종류");
	strcpy(sBar, "바");
	strcpy(sBars, "바");
	strcpy(sBothsizesoftheoffcutsmustbegreaterthanthisvalue, "두 스크랩의 크기는 이 값보다 커야합니다.");
	strcpy(sBottom, "하단");
	strcpy(sBottomcoordinateofthedefect, "결함의 하단 좌표");
	strcpy(sBreakCut, "컷 구분");
	strcpy(sBrowse, "검색");
	strcpy(sBuy, "구입");
	strcpy(sBuynow, "지금 구매 ...");
	strcpy(sCancel, "취소");
	strcpy(sCannotBeEmpty, "비워 둘 수 없습니다!");
	strcpy(sCannotmovepartsbetweensheetswhenidenticalsheetsaregroupedPleaseungroupthesheetsfrommenu, "동일한 시트가 그룹화되어 있으면 한 시트에서 다른 시트로 부품을 이동할 수 없습니다. 메뉴에서 시트 그룹화를 취소하십시오.");
	strcpy(sCannotSaveFile, "파일을 저장할 수 없습니다 ");
	strcpy(sCenter, "센터");

	strcpy(sChangeDirection, "절단 방향 변경");
	strcpy(sChoose, "선택");
	strcpy(sChooseProduct, "제품을 선택하십시오");
	strcpy(sCircle, "원");
	strcpy(sCity, "도시");
	strcpy(sClear, "지우기");
	strcpy(sClockWise, "시계 방향");
	strcpy(sClosewindow, "창 닫기");
	strcpy(sColor, "색깔");
	strcpy(sColorofedgeband, "엣지 밴드의 색");
	strcpy(sColorPattern, "컬러 / 패턴");
	strcpy(sColorpiecesandwastes, "착색 된 조각 및 여분");
	strcpy(sColumns, "열");
	strcpy(sComment, "코멘트");
	strcpy(sCompanyname, "회사 이름");
	strcpy(sComplexMaterialExists, "해당이름이 이미 목록에 정의되어 있습니다. 새 이름을 지정하십시오.");
	strcpy(sComputerCode, "컴퓨터 코드");
	strcpy(sComputerCodefromyourcomputer, "컴퓨터 코드 (사용자컴퓨터)");
	strcpy(sComputethetotalpriceofDemand, "파트의 총 가격 계산");
	strcpy(sContents, "내용");
	strcpy(sContinutComanda, "날짜의 파트 내용");
	strcpy(sContinutDepozit, "날짜의 재고 내용");
	strcpy(sConversionIsDoneOnlyWhenSomePiecesHaveFractionalValues, "일부 조각에 분수 값이있는 경우에만 변환이 수행됩니다.");
	strcpy(sConvertsTheSizeOfWasteToAFractionalUnit, "스크랩 크기를 분수 값으로 표시합니다.");
	strcpy(sCouldNotSaveFile1, "디렉토리에 파일을 쓸 수 없습니다 ");
	strcpy(sCouldNotSaveFile2, "충분한 권한이 없을 수 있습니다. 메뉴에서 작업 디렉토리를 확인하거나 변경하십시오. 설정 | 쓰기 권한이있는 폴더에 대한 작업 디렉토리 (예 : c : \\ temp).");
	strcpy(sCreationdateYMDHMS, "작성일 (Y / M / D- H : M : S)");
	strcpy(sCurrentDate, "현재 날짜");
	strcpy(sCurrentDiagram, "현재 다이어그램");
	strcpy(sCurrentMaterial, "현재 자재");
	strcpy(sCurrentversion, "현재 버전");
	strcpy(sCurve_not_closed_Try_increasing_DXF_linking_distance_parameter, "모양이 닫히지 않았습니다! DXF 연결 거리 매개 변수를 늘리십시오.");
	strcpy(sCustomer, "고객");
	strcpy(sCustomerName, "고객명");
	strcpy(sCustomMessage, "맞춤 메시지");
	strcpy(sCutlength, "절단 길이");
	strcpy(sCut, "절단");
	strcpy(sCuts, "컷");
	strcpy(sCutterThickness, "절단 두께");
	strcpy(sData, "데이터");
	strcpy(sDataCannotBeEmpty, "데이터는 비워 둘 수 없습니다!");
	strcpy(sDateymdhms, "날짜 (y / m / d / h / m / s)");
	strcpy(sDays_left_for_trial, "무료사용기간");
	strcpy(sDaysLeft, "남은 일수");
	strcpy(sStandard, "기본");
	strcpy(sDefaultInterface, "기본 인터페이스");
	strcpy(sDefects, "결함");
	strcpy(sDefectsManager, "결함 관리");
	strcpy(sDefectsofthematerialNopiecescanbeplacedinthefaultyzone, "자재 결함. 결함이 있는 영역에는 조각을 놓을 수 없습니다.");
	strcpy(sDelete, "삭제");
	strcpy(sDeletePiece, "조각 삭제");
	strcpy(sDeleteRow, "행 삭제");
	strcpy(sDemandutilization, "파트 활용");
	strcpy(sDepozitulmodificat, "사용 된 조각이 제거되었습니다. 스크랩이 재고에 추가되었습니다.");
	strcpy(sDepozitvid, "재고가 없습니다");
	strcpy(sDesk, "책상");
	strcpy(sDiagram, "도표");
	strcpy(sDiagram, "도표");
	strcpy(sDiagramasatable, "테이블로 다이어그램");
	strcpy(sDigits, "자릿수");
	strcpy(sDimensiuniplaca, "시트의 크기");
	strcpy(sDirection, "방향");
	strcpy(sDistanceBetweenRows, "줄 사이의 거리");
	strcpy(sDonotuseit, "사용하지 마십시오");
	strcpy(sDownload, "다운로드");
	strcpy(sDoYouWantToClearTheData, "데이터를 삭제 하시겠습니까?");
	strcpy(sDoYouWantToSaveDemand, "파트가 변경되었습니다! 변경 사항을 저장 하시겠습니까?");
	strcpy(sDoYouWantToSaveParts, "파트를 저장 하시겠습니까?");
	strcpy(sDoYouWantToSaveRepository, "재고가 변경되었습니다! 변경 사항을 저장 하시겠습니까?");
	strcpy(sDrawing, "그림");
	strcpy(sDrawthesolutioncolorful, "솔루션을 다채롭게 그리기");
	strcpy(sDuplicateTypes, "일부 유형이 중복되었습니다! 중복된 항목을 제거하십시오");
	strcpy(sDuplicateTypesWithComplex, "일부 자재 이름이 이미 존재합니다! 중복된 항목을 제거하십시오");
	strcpy(sDuplicateValues, "중복 된 값");
	strcpy(sEdgeband, "엣지 밴드");
	strcpy(sEdgebandingwhichisplacedontheedgesofyourpiecePleasedefineedgebandingtypesfromMaterialsEdgeBandingmenu, "엣지 밴드는 조각의 여백에 배치됩니다. 자재 메뉴에서 엣지 밴드를 정의하십시오.");
	strcpy(sEdgebandsthatwillbeappliedtoeachpart, "각 조각에 적용되는 엣지 밴드.");
	strcpy(sEdgeBandTolerance, "엣지 밴드에 대한 공차");
	strcpy(sEdgesthatmustbecutduefaults, "결함으로 인해 절단되어야하는 가장자리.");
	strcpy(sEdgetoedge, "끝에서 끝으로");
	strcpy(sEdit, "편집");
	strcpy(sEmail, "이메일");
	strcpy(sEmptyData, "데이터가 비어 있습니다!");
	strcpy(sEnabled, "가능");
	strcpy(sEnabledisabledefectsoftheinventorysheets, "재고 결함 활성화 / 비활성화");
	strcpy(sEnterLabel, "라벨 입력");
	strcpy(sEnterTheMaterialName, "자재의 이름을 입력하십시오");
	strcpy(sEnterTheProductName, "제품 이름을 입력하십시오");
	strcpy(sEvaluationError, "식 평가 오류!");
	strcpy(sExit, "나가기");
	strcpy(sExpired, "소프트웨어가 만료되었습니다! 정품 등록하십시오!");
	strcpy(sExport, "내보내기");
	strcpy(sExportAllDiagrams, "모든 다이어그램 내보내기");
	strcpy(sExportAllToASingleFile, "모두 단일 파일로 내보내기");
	strcpy(sExportOptions, "내보내기 옵션");
	strcpy(sExporttoDXFformat, "DXF 형식으로 내보내기");
	strcpy(sExporttoExcel, "Excel로 내보내기");
	strcpy(sExpresieIncorecta, "수학적 표현이 잘못되었습니다!");
	strcpy(sExtensions, "확장");
	strcpy(sExtra, "추가 요소");
	strcpy(sExtraComponents, "추가 구성 요소");
	strcpy(sExtracomponentsattachedtoDemand, "파트에 부착 된 추가 구성품");
	strcpy(sFile, "파일");
	strcpy(sFileName, "파일 이름");
	strcpy(sFillWastes, "비스듬한 선으로 여분을 그립니다.");
	strcpy(sFindoptimalbarsheetsize, "최적의 바와 시트 크기 찾기");
	strcpy(sFindoptimalsizeofInventorypieces, "최적의 재고 크기 찾기");
	strcpy(sFirstcutMultiplestages, "다단계 최적화를 위한 첫 번째 절단 방향");
	strcpy(sFirstdirectionforcutishorizontal, "첫 번째 절단 방향은 수평입니다.");
	strcpy(sFirstdirectionforcutisvertical, "첫 번째 절단 방향은 수직입니다.");
	strcpy(sFollowthecontourofpieces, "조각의 윤곽을 따라서");
	strcpy(sFont, "폰트");
	strcpy(sFontsize, "폰트 사이즈");
	strcpy(sFullInfo, "모든 정보");
	strcpy(sDisposedWaste, "폐기된 폐기물");
	strcpy(sGeneral, "일반사항");
	strcpy(sGenerateCNC, "CNC 생성");
	strcpy(sGrain, "결 방향");
	strcpy(sGraindirection, "섬유");
	strcpy(sGraphic, "그래픽");
	strcpy(sGreaterorequalto, "크거나 같음");
	strcpy(sGrid, "테이블");
	strcpy(sGrinding, "연마");
	strcpy(sGrosimeTaieturaScalata, "이 그림의 절단 두께는 실제 크기와 다르게 표현되므로 실제 두께와 다를 수 있습니다. 이 사실은 결과에 영향을 미치지 않습니다.");
	strcpy(sGroupidenticallayouts, "동일한 시트 그룹화");
	strcpy(sGroupIdenticalParts, "동일한 파트 그룹화");
	strcpy(sGroupingOfIdenticalPiecesIntoOneRow, "동일한 파트를 한 행으로 그룹화합니다.");
	strcpy(sGroupPartsAfterLoadingFromFile, "파일에서 로드할 때 파트 그룹화");
	strcpy(sHeight, "높이");
	strcpy(sHeighttolerance, "높이에 대한 공차");
	strcpy(sHelp, "도움말");
	strcpy(sHistory, "히스토리");
	strcpy(sHorizontal, "수평");
	strcpy(sHowtodisplayprintedgebands, "엣지 밴드는 어떻게 표시됩니까?");
	strcpy(sIfyousetthebandforoneedgeallwillreceivethesamevalue, "한 모서리에 대해 밴드를 설정하면 모든 모서리에 동일한 값이 적용됩니다.");
	strcpy(sIfyousetthegrindingforoneedgeallwillreceivethesamevalue, "한 모서리에 대해 연삭 값을 설정하면 모든 모서리에 동일한 값이 적용됩니다.");
	strcpy(sIfyousetthetrimforoneedgeallwillreceivethesamevalue, "한 모서리에 트리밍을 설정하면 모든 모서리에 동일한 값이 적용됩니다.");
	strcpy(sImageBounds, "이미지의 경계");
	strcpy(sImageSize, "이미지 크기");
	strcpy(sImportData, "데이터 가져 오기");
	strcpy(sIncorrectPassword, "잘못된 비밀번호");
	strcpy(sIndex, "인덱스");
	strcpy(sInformationaboutcustomer, "고객 정보");
	strcpy(sInputALanguageName, "언어의 종류 입력하기");
	strcpy(sInsert, "삽입");
	strcpy(sInsertPiece, "조각 삽입");
	strcpy(sInterface, "인터페이스");
	strcpy(sInterfaceSettings, "인터페이스 설정");
	strcpy(sInvalidHardware, "하드웨어를 감지 할 수 없습니다. contact@optimalprograms.com으로 문의하십시오");
	strcpy(sInvalidNumber, "잘못된 번호");
	strcpy(sInvalidOrderOfComputation, "길이 계산 순서를 설정할 수 없습니다. 제품 정의에는 순환 관계가 있습니다!");
	strcpy(sInvalidRegistration, "제품등록이 유효하지 않습니다!");
	strcpy(sInvalidTime, "시스템 시간이 유효하지 않습니다.");
	strcpy(sInventory, "재고");
	strcpy(sisafractionalvalue, "분수 값입니다.");
	strcpy(sIsArc, "아크");
	strcpy(sisarealvalue, "실제 값입니다.");
	strcpy(sLabel, "라벨");
	strcpy(sLabels, "라벨");
	strcpy(sLanguage, "언어");
	strcpy(sLatimeanumar0, "너비는 0보다 커야합니다!");
	strcpy(sLatimeanumarreal, "너비는 실수 여야합니다!");
	strcpy(sLayerName, "레이어 이름");
	strcpy(sLeft, "좌단");
	strcpy(sLeftcoordinateofthedefect, "결함의 왼쪽 좌표");
	strcpy(sLength, "길이");
	strcpy(sLengthofthepiecestocut, "절단을 위한 조각 크기");
	strcpy(sLengthofthepiecestocutfrom, "절단용 시트 크기");
	strcpy(sLengthofusedbars, "사용한 바의 크기");
	strcpy(sLicenseAgreement, "라이센스 계약");
	strcpy(sLinear, "선형");
	strcpy(sLinethickness, "펜의 두께");
	strcpy(sLoadafileandappenddatatothecurrentDemand, "파일을 불러오고 현재 파트에 데이터를 추가합니다.");
	strcpy(sLoadanexistingDemandfromafile, "파일에서 기존 파트를 불러옵니다.");
	strcpy(sLoadAppend, "불러오기 및 추가하기");
	strcpy(sLoadEverything, "모두 불러오기");
	strcpy(sLoadInventory, "재고 불러오기");
	strcpy(sLoadInventoryandDemand, "재고 및 파트 불러오기");
	strcpy(sLoadResults, "결과 불러오기");
	strcpy(sLocked, "잠김");
	strcpy(sLogo, "로고");
	strcpy(sLong, "긴");
	strcpy(sLongerexecutiontime, "긴 실행 시간");
	strcpy(sLungime, "길이");
	strcpy(sLungimeanumar0, "길이는 0보다 커야합니다!");
	strcpy(sLungimeanumarreal, "길이는 실수 여야합니다!");
	strcpy(sLungimeaTotalaFolosita, "총 활용 길이");
	strcpy(sMagnification, "확대");
	strcpy(sMagnify, "확대");
	strcpy(sMargins, "여백");
	strcpy(sMarginsForPaper, "종이 여백");
	strcpy(sMarginsOfTheLabel, "라벨의 여백");
	strcpy(sMaterial, "자재");
	strcpy(sMaterialName, "자재명");
	strcpy(sMaterials, "기재");
	strcpy(sMaterialstypes, "자재 유형");
	strcpy(sMax, "최대");
	strcpy(sMaximalArea, "최대 면적");
	strcpy(sMaximalCutLength, "최대 절단 길이");
	strcpy(sMaxlength, "최대 길이");
	strcpy(sMaxPiecesperBar, "바(bar)당 최대 개수");
	strcpy(sMaxwidth, "최대 폭");
	strcpy(sMeasurementUnit, "측정 단위");
	strcpy(sMin, "최소");
	strcpy(sMinimalBreakSize, "최소 휴식 크기");
	strcpy(sMinimalUsefulSize, "최소한의 유용한 크기");
	strcpy(sMinimalwastesizetoInventory, "재고에 추가될 최소 스크랩 크기");
	strcpy(s_What_to_minimize, "무엇을 최소화할 것인가?");
	strcpy(sMinlength, "최소 길이");
	strcpy(sMinwidth, "최소 폭");
	strcpy(sMirror, "대칭회전");
	strcpy(sMirroring, "미러링");
	strcpy(sMiscellaneous, "기타 통계");
	strcpy(sModify, "수정");
	strcpy(sModifytheselectedpiece, "선택한 조각 수정");
	strcpy(sMovePiece, "조각 이동");
	strcpy(sMultiplestages, "여러 단계");
	strcpy(sName, "이름");
	strcpy(sNameofedgeband, "엣지 밴드의 이름");
	strcpy(sNewDEMANDUnsaveddatawillbelost, "새로운 파트? 저장하지 않은 데이터는 손실됩니다!");
	strcpy(sNewLanguage, "새로운 언어");
	strcpy(sNewMaterial, "새로운 자재");
	strcpy(sNewPasswordincorectlyintroduced, "새 비밀번호가 잘못 소개되었습니다!");
	strcpy(sNewProduct, "새로운 제품");
	strcpy(sNewversion, "새로운 버전");
	strcpy(sNo, "아니요");
	strcpy(sNumarBucati, "개수");
	strcpy(sNumberOfCopies, "매수");
	strcpy(sNumberofstages, "단계 수");
	strcpy(sNusuficienteplacidepozit, "모든 부분이 최적화 된 것은 아닙니다. 가능한 원인 : 재고에 조각이 충분하지 않습니다. 조각이 활성화되지 않았습니다. 조각의 자재와 재고가 다릅니다. 다른 매개 변수가 잘못 설정되었습니다.");
	strcpy(sOfficeNotInstaled, "컴퓨터에 Microsoft Office가 설치되어 있지 않거나 잘못된 버전이 설치되었습니다!");
	strcpy(sOldpassworddoesnotmatch, "이전 비밀번호가 일치하지 않습니다!");
	strcpy(sOnlinehelp, "온라인 도움말");
	strcpy(sOnlypiecesofthesameheightinthelaststage, "마지막 단계에서 같은 높이의 조각");
	strcpy(sOpen, "열기");
	strcpy(sOptimization, "최적화");
	strcpy(sOptimizationDone, "최적화 수행! 획득 한 다이어그램을 인쇄하거나 저장할 수 있습니다. 현재 솔루션에 만족하면 수락 버튼을 누릅니다. 그렇지 않으면 시작을 다시 누릅니다.");
	strcpy(sOptimizationType, "최적화 유형");
	strcpy(sOptions, "옵션");
	strcpy(sOptionsrelatedtotheinterface, "인터페이스 관련 옵션");
	strcpy(sor, "또는");
	strcpy(sOthercomponents, "기타 구성 요소");
	strcpy(sOthers, "기타");
	strcpy(sOtherstatistics, "기타 통계");
	strcpy(sOverrideExcelCSVfiles, "Excel / CSV 파일 재정의");
	strcpy(sParameter, "모수");
	strcpy(sParts, "조각");
	strcpy(sPattern, "패턴");
	strcpy(sPatternforwaste, "스크랩 패턴");
	strcpy(sPerimeter, "둘레");
	strcpy(sPermitedRotationAngle, "허용 회전 각도");
	strcpy(sPhone, "전화번호");
	strcpy(sPicture, "영상");
	strcpy(sPiece, "조각");
	strcpy(sPieceindex, "조각의 인덱스");
	strcpy(sPieces, "조각");
	strcpy(sPiecesize, "조각 크기");
	strcpy(sPiecesizelabeledgebandwillbeprinted, "조각 크기, 라벨, 엣지 밴드가 인쇄됩니다.");
	strcpy(sPierdere, "스크랩");
	strcpy(sPixels, "픽셀");
	strcpy(sPlacilefolositeDepozit, "재고에서 사용 된 조각.");
	strcpy(sPlease_contact_us_at_contact_nestingtechnologies_com, "contact@nesting-technologies.com으로 문의하시기 바랍니다");
	strcpy(sPlease_contact_us_at_contact_optimalprograms_com, "contact@optimalprograms.com으로 문의하시기 바랍니다");
	strcpy(sPleaseenteralldataeitherasfractionalorrealDonotmixthem, "모든 데이터를 분수 값 또는 실수 값으로 입력하십시오! 혼합하지 마십시오!");
	strcpy(sPleaseEnterSomeTypesOfMaterials, "정의 된 자재 유형이 없습니다. 자재 메뉴에서 정의 할 수 있습니다.");
	strcpy(sPleasesendtheNameandtheCodetotheaddresscontactoptimalprogramscominordertoobtaintheRegistrationKey, "등록 키를 얻으려면 contact@optimalprograms.com으로 이름과 코드를 보내십시오.");
	strcpy(sPolygon, "다각형");
	strcpy(sPolygonsCircles, "다각형, 원");
	strcpy(sPrecision, "정도");
	strcpy(sPretulnumar0, "가격은 0보다 커야합니다!");
	strcpy(sPretulnumarreal, "가격은 실수 여야합니다!");
	strcpy(sPreview, "미리보기");
	strcpy(sPrice, "가격");
	strcpy(sPriceMustBeGreaterThanZero, "가격은 0보다 커야합니다");
	strcpy(sPriceofbars, "바의 가격");
	strcpy(sPriceperbar, "바 당 가격");
	strcpy(sPricepersheet, "시트 당 가격");
	strcpy(sPricepersquareunitofmaterial, "자재의 제곱 단위당 가격");
	strcpy(sPriceperunit, "단위 당 가격");
	strcpy(sPrint, "인쇄");
	strcpy(sPrintdiagramsastables, "도표를 표로 인쇄하기");
	strcpy(sPrinter, "프린터");
	strcpy(sPrinterBounds, "프린터 여백");
	strcpy(sPrinting, "인쇄");
	strcpy(sPrintonlyutilizedarea, "활용 영역 만 인쇄");
	strcpy(sPrintthecontentsoftheDemand, "부품의 내용을 인쇄하십시오.");
	strcpy(sPrintthecontentsoftheInventory, "재고의 내용을 인쇄하십시오.");
	strcpy(sPrintthecurrentsolution, "현재 솔루션을 인쇄하십시오.");
	strcpy(sPriority, "우선 순위");
	strcpy(sPrioritytocutapieceZero0isthehighestpriority, "조각을 자르는 우선 순위. 0이 가장 높은 우선 순위입니다.");
	strcpy(sProcentul0100, "퍼센트는 0보다 크고 100보다 작거나 같아야합니다!");
	strcpy(sProcentulnumarreal, "퍼센트는 실수 여야합니다!");
	strcpy(sProductdefinition, "제품 정의");
	strcpy(sProductExists, "제품이 이미 존재합니다. 다른 이름을 선택하십시오.");
	strcpy(sProductName, "제품명");
	strcpy(sProducts, "제품");
	strcpy(sProducts, "제품");
	strcpy(sProject, "프로젝트");
	strcpy(sProperties, "속성");
	strcpy(sProperty, "특성");
	strcpy(sQuantity, "수량");
	strcpy(sQuantitynumberofsheetsofthistype, "이 유형의 매수");
	strcpy(sRadius, "반지름");
	strcpy(sRectangular, "직사각형");
	strcpy(sRedefinetypesofedgeband, "에지 밴드의 재정의 유형");
	strcpy(sRedefinetypesofmaterial, "자재유형 재정의");
	strcpy(sRegistration, "제품등록");
	strcpy(sRegistrationKeyfromOptimalPrograms, "제품등록 키");
	strcpy(sRegistrationSuccessful, "제품등록이 완료되었습니다!");
	strcpy(sRemoveallpiecesinInventory, "재고에서 모든 조각을 제거하십시오.");
	strcpy(sRemoveCut, "컷 삭제");
	strcpy(sRemovetheselectedpiece, "선택한 작품을 삭제");
	strcpy(sReports, "보고서");
	strcpy(sRequestedMaterial, "요청 된 자재");
	strcpy(sRestore, "복원");
	strcpy(sResults, "결과");
	strcpy(sReusedwaste, "사용가능한 스크랩");
	strcpy(sRight, "우단");
	strcpy(sRightcoordinateofthedefect, "오른쪽에서 결함의 좌표");
	strcpy(sRotation, "회전");
	strcpy(sRotationAngle, "회전 각도");
	strcpy(sRotationStep, "회전 단계");
	strcpy(sRoundAllFractionsTo, "분수 값은 다음과 같이 반올림되어야합니다.");
	strcpy(sRow, "열");
	strcpy(sRows, "행");
	strcpy(sRun, "최신 솔루션");
	strcpy(sRunningtime, "러닝타임");
	strcpy(sSameforall, "모두 동일");
	strcpy(sSave, "저장");
	strcpy(sSaveAllImages, "모든 이미지 저장");
	strcpy(sSaveAs, "다른 이름으로 저장");
	strcpy(sSaveChanges, "파트가 변경되었습니다. 저장 하시겠습니까?");
	strcpy(sSaveCurrentImage, "현재 이미지를 저장");
	strcpy(sSavedataparameters, "데이터 및 파라미터 저장");
	strcpy(sSaveEverything, "모두 저장하기");
	strcpy(sSaveInventory, "재고 저장");
	strcpy(sSaveInventoryandDemand, "재고 및 파트 저장");
	strcpy(sSaveResults, "결과 저장");
	strcpy(sSaveStatisticsinafile, "통계를 파일로 저장");
	strcpy(sSavethecurrentimage, "현재 이미지를 저장");
	strcpy(sSavethecurrentimageorstatistic, "현재 이미지 또는 통계 저장");
	strcpy(sSavetheDEMANDinafile, "파일로 저장");
	strcpy(sSavetheDemandinafilewithadifferentname, "파트를 다른 이름으로 파일에 저장하십시오.");
	strcpy(sSavetheREPOSITORYinafile, "재고를 파일로 저장");
	strcpy(sSerialNumber, "등록 키");
	strcpy(sService, "서비스");
	strcpy(sSetDefaultValues, "모든 매개 변수를 기본값으로 복원합니다. 모든 설정이 손실됩니다. 이 작업을 수행 하시겠습니까?");
	strcpy(sSetedgeband, "에지 밴드 설정");
	strcpy(sSetedgetrim, "여백 결함에 대한 절단 크기 설정");
	strcpy(sSetthesameedgebandforalledges, "모든 면에 동일한 엣지 밴드를 설정하십시오");
	strcpy(sSetthesamegrindingforalledges, "모든 모서리에 대해 동일한 연삭을 설정하십시오");
	strcpy(sSetthesametrimforalledges, "모든 모서리의 결함에 대해 동일한 절단 설정");
	strcpy(sSettings, "설정");
	strcpy(sShape, "모양");
	strcpy(sSheet, "시트");
	strcpy(sSheetsBarstypes, "시트_바 타입");
	strcpy(sSheetSize, "장의 크기");
	strcpy(sSheetsperPage, "페이지 당 시트");
	strcpy(sShort, "짧은");
	strcpy(sShorterexecutiontime, "짧은 실행 시간");
	strcpy(sShowallsimpleproducts, "모든 제품 표시");
	strcpy(sShowcustomername, "고객명 표시");
	strcpy(sShowCustomTextOnEachPiece, "각 조각에 사용자 정의 텍스트 표시");
	strcpy(sShowdiagramasatable, "다이어그램을 표로 표시하십시오.");
	strcpy(sShowedgeband, "엣지 밴드 표시");
	strcpy(sShowedgebandssettinginanewwindow, "엣지 밴드의 설정을 새 창에 표시하십시오");
	strcpy(sShowgrindingsettingsinanewwindow, "연삭 설정을 새 창에 표시합니다");
	strcpy(sShowHorizontalLabelsAlways, "항상 가로 레이블 표시");
	strcpy(sShowRemovethesizeofthepiecesinthecurrentsolution, "조각의 크기를 표시하거나 숨 깁니다.");
	strcpy(sShowRemovethesizeofthewastesinthecurrentsolution, "스크랩 크기를 표시하거나 숨 깁니다.");
	strcpy(sShowtotalcutlength, "총 절단 길이 표시");
	strcpy(sShowtrimedgesettingsinanewwindow, "결함 설정을 새 창에 표시하십시오");
	strcpy(sSimpleMaterialExists, "자재 이름이 이미 목록에 정의되어 있습니다. 새 이름을 지정하십시오.");
	strcpy(sSinglePieceStrips, "조각의 줄무늬");
	strcpy(sSizes, "크기");
	strcpy(sSmallerorequalto, "작거나 같음");
	strcpy(sSort, "종류");
	strcpy(sSortAscendingByArea, "오름차순으로 정렬");
	strcpy(sSortDescendingByArea, "내림차순으로 정렬");
	strcpy(sSpecifyhowdifferentthepiecesinthelaststagecanbeValue0meansnodifference, "마지막 단계에서 조각이 얼마나 다른지 지정하십시오. 값 0은 차이가 없음을 의미합니다.");
	strcpy(sSpecifyifpiecesinthelaststagecanbedifferentornotdepeultimaetapapotfidiferitesaunucadimensiune, "마지막 단계의 조각이 다를 수 있는지 여부를 지정하십시오.");
	strcpy(sSpecifyifthepiececanberotatedornotIfnotitwillbecutinthesamewayasitwasintroducedinDemandLengthofthepieceparalleltothelengthofthesheet, "조각을 회전시킬 수 있는지 여부를 지정하십시오. 그렇지 않은 경우, 입력된 방향 그대로 배치됩니다 (시트의 길이와 조각의 길이가 같은 방향으로 설정).");
	strcpy(sSpecifyinhowmanystageswemakethecutsDuringastageallcutshavethesamedirection, "자르는 단계 수를 지정하십시오.");
	strcpy(sStartthesearchprocess, "검색 프로세스를 시작하십시오");
	strcpy(sStatistics, "통계");
	strcpy(sStatisticsE, "추가 보고서");
	strcpy(sStatisticsforeachtypeofmaterial, "각 자재 유형에 대한 통계");
	strcpy(sStep, "단계");
	strcpy(sStergeDepozit, "재고를 삭제 하시겠습니까?");
	strcpy(sStergeMaterial, "자재정보를 삭제 하시겠습니까?");
	strcpy(sStergePiesele, "조각을 삭제 하시겠습니까?");
	strcpy(sStergePiesa, "조각을 삭제 하시겠습니까?");
	strcpy(sStopthesearchprocess, "검색 프로세스를 중지");
	strcpy(sStrongoptimization, "강력한 최적화");
	strcpy(sSubtractthebandthicknessfrompiecesize, "엣지 밴드 두께로 조각의 크기를 줄입니다");
	strcpy(sSummary, "요약");
	strcpy(sSuprafataTotalaFolosita, "사용 된 총 표면");
	strcpy(sSuprafatautilizata, "활용");
	strcpy(sSwitchbetweenfiberandrotationoption, "섬유와 회전 옵션 사이를 전환하십시오.");
	strcpy(sTechnical, "테크니컬 설정");
	strcpy(sTechnicalsettings, "테크니컬 설정");
	strcpy(sTemporaryPanelHint, "시트 사이에서 부품을 이동시키기 위한 임시 패널.");
	strcpy(sText, "설명");
	strcpy(sThe_application_has_expired, "응용 프로그램이 만료되었습니다.");
	strcpy(sThe_application_is_not_registered, "응용 프로그램이 등록되지 않았습니다.");
	strcpy(sThe_application_was_first_started_on, "응용 프로그램이 처음 시작되었습니다");
	strcpy(sThecutsareperformedfromasidetotheothersideofthematerial, "절단은 자재의 한 쪽에서 반대쪽 방향으로 이루어집니다.");
	strcpy(sThecuttingmachinecanfollowtheshapeofthematerial, "절단기가 조각의 모양을 따를 수 있는 경우");
	strcpy(sTheedgesofsheetsthatmustbetrimedduefaults, "결함으로 인해 트리밍해야하는 용지의 엣지");
	strcpy(sTheLargestSize, "가장 큰 크기");
	strcpy(sThenameofthecustomerforwhichyoucutthepiece, "조각을 자른 고객의 이름입니다.");
	strcpy(sThenameofyourcustomer, "고객의 이름");
	strcpy(sThepiececanberotated, "조각 회전 가능");
	strcpy(sTheprogramtriestoavoidwasteswhichhavebothsizeslessthanthisvalue, "프로그램은 이 값보다 작은 스크랩을 피하려고합니다.");
	strcpy(sThereAreNoProducts, "아직 정의 된 제품이 없습니다");
	strcpy(sThestockofmaterialhasbeenpreviouslyloadedfromanExcelorCSVformatPleaseloaditagain, "자재 재고는 이전에 Excel 또는 CSV 형식으로 로드되었습니다. 작업하려면 다시 로드하십시오.");
	strcpy(sThetotallengthofcutting, "총 절단 길이");
	strcpy(sThewidthofthecuttingsawForglasscuttingoptimizationitcanbe0Forwooditshouldbegreaterthan0, "톱의 두께. 유리 절단의 경우 0이 될 수 있습니다. 목재의 경우 0보다 커야합니다.");
	strcpy(sThewidthofthecuttingsawforlinearpieces, "선형 조각에 대한 톱의 두께.");
	strcpy(sThickness, "두께");
	strcpy(sThischaracterisusedforfillingthewasterectanglesIfyoudonotwantfilledwastejustremovethischaracter, "이 기호는 폐기물 사각형을 채우는 데 사용됩니다. 채워진 폐기물을 원하지 않으면 제거하십시오.");
	strcpy(sThisindexhasvaluebetween1andthenumberofpieces, "이 색인의 값은 1과 조각 수 사이입니다.");
	strcpy(sThisOptionWillOverrideTheInventoryFileIfLoadedFromExcelOrCsvFiles, "이 옵션은 Excel 또는 csv 파일에서로드 된 경우 인벤토리 파일을 재정의합니다.");
	strcpy(sThisProgramisLicensedTo, "이 프로그램은 라이센스");
	strcpy(sThisvaluewillbeaddedtotheedgebandingmaterialoneachside, "이 값은 각 측면의 엣지 밴드에 추가됩니다");
	strcpy(sTipNevid, "자재 유형은 비워 둘 수 없습니다.");
	strcpy(sTitle, "표제");
	strcpy(sTools, "도구");
	strcpy(sTop, "상단");
	strcpy(sTopcoordinateofthedefect, "결함의 상단 좌표입니다.");
	strcpy(sTotalGarbageWaste, "폐기된 스크랩");
	strcpy(sTotalInventoryWaste, "총 재고 스크랩");
	strcpy(sTotalRecycledWaste, "사용가능한 스크랩");
	strcpy(sTotalusedarea, "사용된 영역");
	strcpy(sTotalusedlength, "사용된 총 길이");
	strcpy(sTrigonometric, "삼각법");
	strcpy(sTrim, "다듬기");
	strcpy(sTrimalledgesatthebeginning, "처음에 모든 엣지 다듬기");
	strcpy(sTrimEdge, "엣지 다듬기");
	strcpy(sTwoPanels, "2 개 패널");
	strcpy(sType, "유형");
	strcpy(sTypeofmaterialfromwhichtocut, "절단 할 자재의 유형");
	strcpy(sTypesAreNotMatched, "최적화가 수행되지 않았습니다! 부품 테이블과 재고 테이블의 재료가 일치하지 않습니다! 재고에 있는 동일한 이름의 재료에서만 부품을 절단할 수 있습니다. 해당 열에서 재료 이름을 변경하세요!");
	strcpy(sUndo, "실행 취소");
	strcpy(sUndoAccept, "수락 취소");
	strcpy(sUnits, "단위");
	strcpy(sUnregisteredVersion, "미등록");
	strcpy(sUpdates, "업데이트");
	strcpy(sUsefulforwoodfurniture, "목제 가구에 유용");
	strcpy(sUseit, "사용하기");
	strcpy(sUsePieceinOptimization, "최적화에서 조각 사용");
	strcpy(sUserName, "사용자 이름");
	strcpy(sUtilizationandWastes, "활용 및 스크랩");
	strcpy(sUtilizedArea, "생성된 파트 영역");
	strcpy(sUtilizedBars, "사용된 바");
	strcpy(sUtilizeddemandcount, "생성된 파트 수");
	strcpy(sUtilizedParts, "생성된 파트");
	strcpy(sUtilizedPieces, "생성된 조각");
	strcpy(sUtilizedSheets, "사용된 시트");
	strcpy(sValue, "값");
	strcpy(sValueGreaterEqualToZero, "값은 0보다 크거나 같아야합니다.");
	strcpy(sValueGreaterThanZero, "값은 0보다 커야합니다");
	strcpy(sValueIntegerNumber, "값은 정수여야 합니다!");
	strcpy(sValueRealNumber, "값은 실수 여야합니다. 소수점 대신 콤마를 사용했을 수도 있습니다. 고쳐주세요!");
	strcpy(s_The_number_is_too_big_or_it_has_too_many_digits_after_decimal_separator, "소수점 구분 기호 뒤에 숫자가 너무 크거나 숫자가 너무 많습니다!");
	strcpy(s_The_number_is_too_big, "숫자가 너무 큽니다!");
	strcpy(sVertical, "수직");
	strcpy(sWaste, "스크랩");
	strcpy(sWastes, "스크랩");
	strcpy(sWasteAddedToWarehouse, "스크랩이 재고에 추가됨");
	strcpy(sWastelimits, "스크랩의 범위");
	strcpy(sWasteType, "스크랩의 종류");
	strcpy(sWeakoptimization, "가장 약한 최적화");
	strcpy(sWhattoprint, "무엇을 인쇄해야합니까");
	strcpy(s_What_to_print_or_save_to_file, "인쇄하거나 파일에 저장할 내용");
	strcpy(sWhattoprintoneachpiece, "각 조각에 인쇄 할 내용");
	strcpy(sWhattoshowoneachpiece, "각 조각에 무엇을 보여줄까요?");
	strcpy(sWidth, "폭");
	strcpy(sWood, "나무");
	strcpy(sWorkingDirectory, "작업 폴더");
	strcpy(sWrongKey, "등록 키가 잘못되었습니다!");
	strcpy(sYes, "예");
	strcpy(sYoucannotchooseblackblueorredcolors, "검은 색, 파란색 또는 빨간색을 선택할 수 없습니다.");
	strcpy(sYouCannotMixFractionalDataWithDecimalOnes, "분수 값과 실수 값을 혼합 할 수 없습니다!");
	strcpy(sYourcompany, "사용자 정보");
	strcpy(sZip, "우편 번호");
	strcpy(s_Set_the_origin_and_the_direction_of_the_axes, "좌표축의 원점과 방향을 설정합니다.");










	strcpy(s_Number_of_digits_after_the_decimal_separator, "소수점 구분 기호 뒤의 숫자 개수");
	strcpy(s_Percentages, "백분율");
}

