// Language strings: Latvian
// Author: Optimal Programs
// License: MIT License
//---------------------------------------------------------------------------
#include <string.h>
//---------------------------------------------------------------------------
#include "language_string_id.h"
//---------------------------------------------------------------------------
void set_lv(void)
{
	//latvian
	//did not check manually
	// last update on: 2025.9.25.0
	strcpy(s_Area, "laukums");
	strcpy(s_Mass, "masa");
	strcpy(s_Advanced, "Papildu");
	strcpy(s_Relative_coordinates, "Relatīvās koordinātas");
	strcpy(s_Absolute_coordinates, "Absolūtās koordinātas");
	strcpy(s_Append_more_rows, "Pievienot vairāk rindu");

	strcpy(s_Add_to_parts, "Pievienot daļām.");
	strcpy(s_Additional, "Papildu");
	strcpy(s_All_results, "Visi rezultāti.");
	strcpy(s_Allow_movement_of_pieces, "Atļaut detaļu kustību");
	strcpy(s_Allow_part_in_part, "Ļauj pa gabalu");
	strcpy(s_Invalid_piece_Angles_are_too_small_or_too_big_or_height_is_too_small, "Nederīgs gabals! Leņķi ir pārāk mazi vai pārāk lieli, vai augstums ir pārāk mazs.");
	strcpy(s_Append, "Papildināt");
	strcpy(s_As_it_is, "Tā kā tas ir");
	strcpy(s_As_text, "Kā teksts");
	strcpy(s_Ascending, "Augoši");
	strcpy(s_Automatic, "Automatico");
	strcpy(s_Cannot_connect_to_the_Internet_Please_visit_our_website_from_a_browser, "Nevar izveidot savienojumu ar internetu! Lūdzu, apmeklējiet mūsu vietni no pārlūka.");
	strcpy(s_Cannot_copy_or_move_the_files, "Nevar kopēt vai pārvietot failus!");
	strcpy(s_Cannot_delete_the_file, "Nevar izdzēst failu!");
	strcpy(s_Cannot_modify_old_results, "Nevar mainīt vecos rezultātus!");
	strcpy(s_To_change_click_inside_a_cell_or_press_0_1_or_2, "Lai mainītu, noklikšķiniet šūnā vai nospiediet 0, 1 vai 2.");
	strcpy(s_Cell, "Šūna");
	strcpy(s_Click_on_the_table_header_to_change_the_columns, "Noklikšķiniet uz tabulas galvenes, lai mainītu kolonnas.");
	strcpy(s_Close, "Aizveriet to");
	strcpy(s_Contact_us, "Sazinies ar mums");
	strcpy(s_Column, "Kolonna");
	strcpy(s_Comma, "Komats");
	strcpy(s_The_comma_symbol_cannot_simultaneously_be_the_list_separator_and_the_decimal_separator, "Komata simbols nevar vienlaikus būt gan saraksta atdalītājs, gan decimālskaitļu atdalītājs!");
	strcpy(s_Copy, "Kopēt");
	strcpy(s_Copy_for_move, "Kopēt pārvietošanai");
	strcpy(s_Cut_higher_level_strips_first, "Vispirms izgrieziet augstāka līmeņa sloksnes");
	strcpy(s_Cut_index, "Parādīt griešanas indeksu");

	strcpy(s_The_data_have_been_changed_Do_you_want_to_save_them_to_a_file, "Dati ir mainīti. Vai vēlaties tos saglabāt failā?");
	strcpy(s_Decimal_separator, "Decimāldaļas atdalītājs");
	strcpy(s_Restore_default_settings, "Atjaunot noklusējuma iestatījumus");
	strcpy(s_Delete_fiber, "Dzēst šķiedru");
	strcpy(s_Descending, "Dilstošā secībā");
	strcpy(s_Discard_changes, "Atmest izmaiņas");

	strcpy(s_Delete_all_data, "Vai dzēst visus datus?");
	strcpy(s_Dot, "Punkts");
	strcpy(s_Do_you_want_to_delete_the_picture, "Vai vēlaties izdzēst attēlu?");
	strcpy(s_Do_you_want_to_delete_the_product, "Vai vēlaties izdzēst produktu?");
	strcpy(s_Duplicate_and_append, "Kopēt un pievienot.");
	strcpy(s_Duplicate_values_are_ignored, "Vērtību dublikāti tika ignorēti!");
	strcpy(s_Error, "Kļūda");
	strcpy(s_Error_loading_file, "Ielādējot failu, radās kļūda.");
	strcpy(s_export_everything, "Eksportējiet visu");
	strcpy(s_Fit_to_screen, "Ietilpināt ekrānā.");
	strcpy(s_Force_fixed_height, "Zīmējiet gabalus ar fiksētu augstumu.");
	strcpy(s_Flipped, "Apgriezts");
	strcpy(s_Import, "Importēt");
	strcpy(s_If_angles_are_different_from_90_degrees_height_must_be_greater_than_0, "Ja leņķi atšķiras no 90 grādiem, augstumam ir jābūt lielākam par 0.");
	strcpy(s_Ignore, "Ignorēt");
	strcpy(s_Incorrect_value, "Nepareiza vērtība");
	strcpy(s_Info, "Informācija");
	strcpy(s_Interior, "iekšā");
	strcpy(s_Give_a_name, "Dodiet vārdu.");
	strcpy(s_Group, "Grupējiet to");
	strcpy(s_Header, "Virsraksts");
	strcpy(s_Keep_it_as_it_is, "Saglabājiet to tādu, kāds tas ir");
	strcpy(s_Level, "Level");
	strcpy(s_Licensee, "Licenciāts");
	strcpy(s_List_separator, "Saraksta atdalītājs");
	strcpy(s_Made_with_love_in_Cugir_Romania, "Ražots ar mīlestību Cugir, Rumānijā");
	strcpy(s_Made_in, "Ražots");
	strcpy(s_Manufacturer, "Ražotājs");

	strcpy(s_Manual_arrange, "Manuāla kārtošana");

	strcpy(s_Mixed, "Sajaukts");
	strcpy(s_Multiple_shapes_detected_Next_rows_will_be_overwritten_Continue, "Tika konstatēta vairāk nekā viena forma. Tāpēc nākamās rindas tiks pārrakstītas. Turpināt?");
	strcpy(s_More, "Vairāk");
	strcpy(s_Multiple_values, "Vairākas vērtības");
	strcpy(s_No_texture, "Nav tekstūras");
	strcpy(s_Number, "Skaits");
	strcpy(s_Number_of_images, "Attēlu skaits");
	strcpy(s_Number_of_vertices, "Virsotņu skaits");
	strcpy(s_Offset, "Ofseta");
	strcpy(s_Only_the_currently_selected_items, "Tikai pašlaik atlasītie vienumi.");
	strcpy(s_Optimizing_please_wait, "Optimizēšana... lūdzu, uzgaidiet.");

	strcpy(s_Paste, "Paste");

	strcpy(s_Piece_label, "Parādīt gabala uzlīmi");
	strcpy(s_Piece_size, "Parādīt gabalu izmēru");
	strcpy(s_Please_contact_us_by_email_if_you_receive_this_error, "Lūdzu, sazinieties ar mums pa e-pastu, ja saņemat šo kļūdu.");
	strcpy(s_Please_save_it_first, "Lūdzu, vispirms saglabājiet to.");
	strcpy(s_Position, "Pozīcija");
	strcpy(s_Preview, "Priekšskatījums");
	strcpy(s_Rectangle, "Taisnstūris");

	strcpy(s_Redo_the_last_operation, "Atjaunojiet pēdējo darbību");
	strcpy(s_Regular_polygon, "Regulārs daudzstūris");

	strcpy(s_Reused, "Atkārtoti izmantots");
	strcpy(s_Rotated, "Pagriezts");
	strcpy(s_Save_all, "Saglabāt visu");
	strcpy(s_Scrap_label, "Parādīt atlikumu uzlīmi");
	strcpy(s_Scrap_size, "Parādīt atlikumu izmēru");
	strcpy(s_Semicolon, "Semikols");
	strcpy(s_Show_cut_index, "Parādīt griešanas indeksu");
	strcpy(s_Show_information, "Rādīt informāciju");
	strcpy(s_Show_piece_label, "Parādīt gabala uzlīmi");
	strcpy(s_Show_scrap_label, "Parādīt atlikumu uzlīmi");
	strcpy(s_Show_scrap_s_size_on_the_small_pieces, "Parādiet sīku gabalu izmēru");
	strcpy(s_Show_size_of_pieces, "Parādīt gabalu izmēru");
	strcpy(s_Show_size_of_scrap, "Parādīt atlikumu izmēru");
	strcpy(s_Show_sizes, "Rādīt izmērus");
	strcpy(s_Show_label, "Rādīt etiķeti");
	strcpy(s_Show_length, "Rādīt garumu");

	strcpy(s_Some_numerical_values_are_incorrect_Should_I_fix_all_the_incorrect_values, "Dažas skaitliskās vērtības nav pareizas! Vai man vajadzētu novērst visas nepareizās vērtības?");
	strcpy(s_Some_invalid_values_have_been_removed, "Dažas nederīgas vērtības ir noņemtas.");
	strcpy(s_Sort_by, "Kārtot pēc");
	strcpy(s_Sort_ascending_by, "Kārtot augoši pēc");
	strcpy(s_Sort_descending_by, "Kārtot dilstoši pēc");
	strcpy(s_Start, "Start");
	strcpy(s_Starting_angle, "Sākuma leņķis");


	strcpy(s_Stock, "Uzkrajums");
	strcpy(s_Stop, "Stop");
	strcpy(s_System_setting, "Sistēmas iestatījums");
	strcpy(s_Tabular, "Tabulveida");
	strcpy(s_Total, "Kopā");
	strcpy(s_Total_size, "Kopējais lielums");
	strcpy(s_Terms_of_the_license, "Licences noteikumi");
	strcpy(s_The_current_product_has_been_changed_Do_you_want_to_save_it_to_file, "Pašreizējais produkts ir mainīts. Vai vēlaties to saglabāt failā?");
	strcpy(s_The_value_is_out_of_the_allowed_range, "Vērtība ir ārpus atļautā diapazona.");
	strcpy(s_The_value_must_be_a_real_or_fractional_number_Try_to_replace_the_comma_with_the_dot_if_you_want_to_enter_a_real_number, "Vērtībai jābūt reālai vai daļējai daļai. Ja vēlaties ievadīt reālu skaitli, mēģiniet aizstāt komatu ar punktu.");
	strcpy(s_This_feature_is_not_implemented_yet, "Šī funkcija vēl nav ieviesta.");
	strcpy(s_This_operation_cannot_be_reversed, "Šo darbību nevar atcelt.");
	strcpy(s_Undo_the_last_operation, "Atsauciet pēdējo darbību.");
	strcpy(s_Utilization, "Izmantošana");
	strcpy(s_Utilized_Stock, "Izmantotais krājums");
	strcpy(s_Version, "Versija");
	strcpy(s_Visible_columns, "Redzamas kolonnas");
	strcpy(s_You_already_have_the_latest_version_installed, "Jums jau ir instalēta jaunākā versija!");
	strcpy(s_What_is_exported, "Kas tiek eksportēts?");
	strcpy(s0meansanynumberofpieces, "Nulle nozīmē jebkuru vienību skaitu");
	strcpy(sAbout, "Par");
	strcpy(sAccept, "Pieņemt");
	strcpy(sAcceptall, "Pieņemt visus");
	strcpy(sAcceptthecurrentsolution, "Pieņemt sekojošo risinājumu");
	strcpy(sAdd, "Pievienot");
	strcpy(sAddapiece, "Pievienot gabalu");
	strcpy(sAddasimpleproducttoDemand, "Pievienot produktu esošajam pieprasījumam.");
	strcpy(sAddgrindingthicknesstopartsize, "Pievienot slīpēšanas biezumu priekš gabala izmēra");
	strcpy(sAddproductnametolabel, "Pievienot produkta nosaukumu uz etiķetes");
	strcpy(sAddress, "Adrese");
	strcpy(sAddselectedsizetoInventory, "Pievienot izvēlēto izmēru inventāram");
	strcpy(sAdhesivelabels, "Pašlīmējošās etiķetes");
	strcpy(sAdhesivelabelwithinformationaboutpiecesinDemandCustomernameLabelSizeCurrentData, "Uzlīme ar informāciju par gabaliem pieprasījumā: Klienta nosaukums, Etiķete, Izmērs, Pašreizējie Dati.");
	strcpy(sAdhesivelabelwithinformationaboutsheetsinInventory, "Uzlīme ar informāciju par loksnēm inventārā.");
	strcpy(sAll, "Visi");
	strcpy(sAlloffcutswhichhavethesizegreaterthanthisvaluewillbeaddedtoInventory, "Visi atgriezumi, kuriem ir lielāks izmērs par šo vērtību, tiks pievienoti inventāram");
	strcpy(sAllowMirroring, "Atļaut atspoguļošanu");
	strcpy(sAllowRotation, "Atļaut rotāciju");
	strcpy(sAllPieces, "Visi gabali");
	strcpy(sAllpredefinedproducts, "Visas iepriekš noteiktie produkti");
	strcpy(sAnewwindowwillbedisplayedwheretheusercansettheedgebandsforeachedge, "Jaunais logs tiks parādīts, kurā lietotājs var iestatīt malu apmales katrai malai");
	strcpy(sAnewwindowwillbedisplayedwheretheusercansetthegrindingvalueforeachedgeofthsheet, "Jauns logs tiks parādīts, kurā lietotājs var iestatīt defektus katrai malai priekš gabala.");
	strcpy(sAnewwindowwillbedisplayedwheretheusercansetthetrimvalueforeachedgeofthsheet, "Leņķi");
	strcpy(sAngle, "Leņķis");
	strcpy(sAngles, "Leņķi");
	strcpy(sAnoptimizationparameterisarealnumber, "Jebkāda forma!");
	strcpy(sAnoptimizationparameterisfractionalnumber, "Daudzstūrim jābūt vismaz trim virsotnēm!");
	strcpy(sAnyShape, "Jebkura forma");
	strcpy(sApolygonmusthaveatleast2vertices, "Monikulmion on oltava vähintään 2 kärkipistettä!");
	strcpy(sApolygonmusthaveatleast2vertices, "Monikulmion on oltava vähintään 3 kärkipistettä!");
	strcpy(sApplication_fails_to_initialize, "Programmatūra neizdevās formatēšanu.");
	strcpy(sArc, "Loks");
	strcpy(sArcLength, "Loka garums");
	strcpy(sAreaofusedsheets, "Platība priekš izmantotām loksnēm");
	strcpy(sAshortdescriptionofthesheet, "Īss apraksts priekš loksnes");
	strcpy(sAtleastonepart, "Vismaz vienam gabalam jābūt pievienotam.");
	strcpy(sAtTheMarginOfTheSheet, "Loksnes malā");
	strcpy(sBandtypes, "Malu apmaļu veidi.");
	strcpy(sBar, "Stieņi / caurules");
	strcpy(sBars, "Stieņi / caurules");
	strcpy(sBothsizesoftheoffcutsmustbegreaterthanthisvalue, "Atgriezumu abu malu izmēri jābūt lielāki par šo vērtību.");
	strcpy(sBottom, "Apakša");
	strcpy(sBottomcoordinateofthedefect, "Apakšējā defekta koordināta");
	strcpy(sBreakCut, "Pārtraukt griezumu");
	strcpy(sBrowse, "pārlūkot");
	strcpy(sBuy, "Nopirkt");
	strcpy(sBuynow, "Pirkt tagad ...");
	strcpy(sCancel, "Atcelt");
	strcpy(sCannotBeEmpty, "nevar būt tukšs!");
	strcpy(sCannotmovepartsbetweensheetswhenidenticalsheetsaregroupedPleaseungroupthesheetsfrommenu, "Nevar pārvietot gabalus no vienas lapas uz citu, ja identiskās loksnes tika sagrupētas. Lūdzam atcelt grupēšanu no izvēlnes priekš loksnēm.");
	strcpy(sCannotSaveFile, "Nav iespējams saglabāt failu");
	strcpy(sCenter, "Centrs");

	strcpy(sChangeDirection, "Mainīt virzienu");
	strcpy(sChoose, "Izvēlies");
	strcpy(sChooseProduct, "Izvēlies produktu");
	strcpy(sCircle, "Aplis");
	strcpy(sCity, "Pilsēta");
	strcpy(sClear, "Notīrīt");
	strcpy(sClockWise, "Pulksteņrādītāja virzienā");
	strcpy(sClosewindow, "Aizvērt logu");
	strcpy(sColor, "Krāsa");
	strcpy(sColorofedgeband, "Malas apmales krāsa");
	strcpy(sColorPattern, "Krāsa/Veids");
	strcpy(sColorpiecesandwastes, "Gabalus un atgriezumus krāsainus.");
	strcpy(sColumns, "Kolonnas");
	strcpy(sComment, "Komentēt");
	strcpy(sCompanyname, "Uzņēmuma nosaukums");
	strcpy(sComplexMaterialExists, "Materiāla nosaukums jau ir aizņemts komplekso materiālu sarakstā. Lūdzu ievadiet citu nosaukumu.");
	strcpy(sComputerCode, "Datora kods");
	strcpy(sComputerCodefromyourcomputer, "Dators kods (no jūsu datora)");
	strcpy(sComputethetotalpriceofDemand, "Aprēķināt pieprasījuma kopējo cenu");
	strcpy(sContents, "Saturs");
	strcpy(sContinutComanda, "Pieprasījuma saturs pēc datuma");
	strcpy(sContinutDepozit, "Inventāra saturs pēc datuma");
	strcpy(sConversionIsDoneOnlyWhenSomePiecesHaveFractionalValues, "Konversija notiek tikai tad, kad dažiem gabaliem ir daļējas vērtības.");
	strcpy(sConvertsTheSizeOfWasteToAFractionalUnit, "Parāda lielumu, atkritumu kā frakcionālu vērtību.");
	strcpy(sCouldNotSaveFile1, "Neizdevās ierakstīt failu direktorijā");
	strcpy(sCouldNotSaveFile2, "Jums iespējams nav pietiekami daudz tiesību. Lūdzu, pārbaudiet vai nomainat darba direktoriju no izvēlnes Iestatījumi - Darba direktoriju uz mapi, kur jums ir tiesības ierakstīt (piemēram c:\\temp).");
	strcpy(sCreationdateYMDHMS, "Izveides datums (G/M/D-H:M:S)");
	strcpy(sCurrentDate, "Pašreizējais datums");
	strcpy(sCurrentDiagram, "Pašreizējā diagramma");
	strcpy(sCurrentMaterial, "Pašreizējais Materiāls");
	strcpy(sCurrentversion, "Pašreizējā versija");
	strcpy(sCurve_not_closed_Try_increasing_DXF_linking_distance_parameter, "Daudzstūris nav slēgts! Mēģiniet palielināt parametru DXF saistīšanas attālums.");
	strcpy(sCustomer, "Klients");
	strcpy(sCustomerName, "Klienta nosaukums");
	strcpy(sCustomMessage, "Izvēles ziņa");
	strcpy(sCutlength, "Griešanas garums");
	strcpy(sCut, "Griezt");
	strcpy(sCuts, "Griezumi");
	strcpy(sCutterThickness, "Griešanas biezums");
	strcpy(sData, "Dati");
	strcpy(sDataCannotBeEmpty, "Dati nevar būt tukši!");
	strcpy(sDateymdhms, "Datums (g/m/d/h/m/s)");
	strcpy(sDays_left_for_trial, "Dienas pieejami testēšanas ");
	strcpy(sDaysLeft, "dienas atlikušas");
	strcpy(sStandard, "Pēc noklusējuma");
	strcpy(sDefaultInterface, "Noklusējuma interfeis");
	strcpy(sDefects, "Defekti");
	strcpy(sDefectsManager, "Pārvaldīt defektus");
	strcpy(sDefectsofthematerialNopiecescanbeplacedinthefaultyzone, "Materiālu defekti. Nav iespējams gabalus novietot kļūdainā zonā.");
	strcpy(sDelete, "Izdzēst");
	strcpy(sDeletePiece, "Dzēst gabalu");
	strcpy(sDeleteRow, "dzēst rindu");
	strcpy(sDemandutilization, "Pieprasījuma utilizācija");
	strcpy(sDepozitulmodificat, "Utilizētie gabali tika izņemti. Pārpalikumi tika pievienoti uzkrājumā.");
	strcpy(sDepozitvid, "Uzkrājums ir tukšs");
	strcpy(sDesk, "rakstāmgalds");
	strcpy(sDiagram, "Diagramma");
	strcpy(sDiagrams, "Diagrammas");
	strcpy(sDiagramasatable, "Diagramma kā tabula");
	strcpy(sDigits, "cipari");
	strcpy(sDimensiuniplaca, "Loksnes izmērs");
	strcpy(sDirection, "Virziens");
	strcpy(sDistanceBetweenRows, "Attālums starp rindām");
	strcpy(sDonotuseit, "Nelietojiet to");
	strcpy(sDownload, "Lejupielādēt");
	strcpy(sDoYouWantToClearTheData, "Jūs vēlaties dzēst datus?");
	strcpy(sDoYouWantToSaveDemand, "Detaļas tika mainītas! Jūs vēlaties saglabāt izmaiņas?");
	strcpy(sDoYouWantToSaveParts, "Vai jūs vēlaties saglabāt gabalus?");
	strcpy(sDoYouWantToSaveRepository, "Uzkrājums tika mainīts! Jūs vēlaties saglabāt izmaiņas?");
	strcpy(sDrawing, "zīmējumi");
	strcpy(sDrawthesolutioncolorful, "Nokrāsot risinājumu krāsainu");
	strcpy(sDuplicateTypes, "Daži veidi ir dublēti! Lūdzu noņemt dublikātus");
	strcpy(sDuplicateTypesWithComplex, "Daži materiālu nosaukumi jau atrodas komplekso veidu sarakstā! Lūdzu noņemt dublikātus");
	strcpy(sDuplicateValues, "Duplicētās vērtības");
	strcpy(sEdgeband, "Malu apmales");
	strcpy(sEdgebandingwhichisplacedontheedgesofyourpiecePleasedefineedgebandingtypesfromMaterialsEdgeBandingmenu, "Maliņu aplīmēšanas kuras ir uzliktas jūsu gabala malām. Lūdzu definē maliņu aplīmēšanas veidus no Materiāli izvēlnes.");
	strcpy(sEdgebandsthatwillbeappliedtoeachpart, "Malu apmales, kas tiks pievienotas katram gabalam.");
	strcpy(sEdgeBandTolerance, "Pielaide priekš malu aplīmēšanas");
	strcpy(sEdgesthatmustbecutduefaults, "Malas, kuras ir nepieciešams apgriezt dēļ kļūdām.");
	strcpy(sEdgetoedge, "No malas līdz malai");
	strcpy(sEdit, "Rediģēt");
	strcpy(sEmail, "E-pasts");
	strcpy(sEmptyData, "Dati ir tukši!");
	strcpy(sEnabled, "Iespējots");
	strcpy(sEnabledisabledefectsoftheinventorysheets, "Ieslēgt / Atslēgt defektus priekš uzkrājuma");
	strcpy(sEnterLabel, "Ievades etiķete");
	strcpy(sEnterTheMaterialName, "Ievadiet materiāla nosaukumu");
	strcpy(sEnterTheProductName, "Ievadiet produkta nosaukumu");
	strcpy(sEvaluationError, "Kļūda izpildot izteiksmi!");
	strcpy(sExit, "Iziet");
	strcpy(sExpired, "Programmatūras derīguma termiņš ir beidzies! Lūdzu reģistrējat programmatūru!");
	strcpy(sExport, "Eksportēt");
	strcpy(sExportAllDiagrams, "Eksportēt visas diagrammas");
	strcpy(sExportAllToASingleFile, "Eksportējiet visus vienā failā");
	strcpy(sExportOptions, "Eksporta iespējas.");
	strcpy(sExporttoDXFformat, "Eksportēt DXF formātā");
	strcpy(sExporttoExcel, "Eksportēt uz Excel");
	strcpy(sExpresieIncorecta, "Nepareiza matemātiska izteiksme!");
	strcpy(sExtensions, "Paplašinājumi");
	strcpy(sExtra, "Papildu");
	strcpy(sExtraComponents, "Papildu komponenti");
	strcpy(sExtracomponentsattachedtoDemand, "Papildu komponenti pievienoti gabaliem");
	strcpy(sFile, "Fails");
	strcpy(sFileName, "Faila nosaukums");
	strcpy(sFillWastes, "Atzīmēt atlikumus ar slīp svītrām");
	strcpy(sFindoptimalbarsheetsize, "Atrastu optimālo izmēru priekš sijām un loksnēm.");
	strcpy(sFindoptimalsizeofInventorypieces, "Atrast optimālo izmēru no uzkrājuma gabaliem");
	strcpy(sFirstcutMultiplestages, "Pirmais griešana virziens - Vairāki posmi");
	strcpy(sFirstdirectionforcutishorizontal, "Pirmais griezuma virziens ir horizontāls.");
	strcpy(sFirstdirectionforcutisvertical, "Pirmais griezuma virziens ir vertikāls.");
	strcpy(sFollowthecontourofpieces, "Sekot gabalu kontūrām");
	strcpy(sFont, "Fonts");
	strcpy(sFontsize, "Fonta lielums");
	strcpy(sFullInfo, "Pilnīga informācija");
	strcpy(sDisposedWaste, "Likvidētie atkritumi");
	strcpy(sGeneral, "Ģenerāls");
	strcpy(sGenerateCNC, "Ģenerēt CNC");
	strcpy(sGrain, "Tekstūra");
	strcpy(sGraindirection, "Šķiedras virziens");
	strcpy(sGraphic, "Grafisks");
	strcpy(sGreaterorequalto, "Lielāks vai vienāds ar");
	strcpy(sGrid, "galdi ");
	strcpy(sGrinding, "Slīpēšanas biezums");
	strcpy(sGrosimeTaieturaScalata, "Griezuma biezums no šī attēla var atšķirties no reālā biezuma, jo gabali nav atspoguļoti patiesā mērogā. Šis fakts neietekmē rezultātus.");
	strcpy(sGroupidenticallayouts, "Identisko lokšņu grupēšana");
	strcpy(sGroupIdenticalParts, "Sagrupēt Identiskos gabalus");
	strcpy(sGroupingOfIdenticalPiecesIntoOneRow, "Sagrupēt identiskos gabalus vienā rindā.");
	strcpy(sGroupPartsAfterLoadingFromFile, "Apvienojot gabalus pēc ielādēšanas no faila");
	strcpy(sHeight, "Augstums");
	strcpy(sHeighttolerance, "Augstuma pielaide");
	strcpy(sHelp, "Palīdzēt");
	strcpy(sHistory, "Vēsture");
	strcpy(sHorizontal, "Horizontāls");
	strcpy(sHowtodisplayprintedgebands, "Kā tas parāda malu apmales?");
	strcpy(sIfyousetthebandforoneedgeallwillreceivethesamevalue, "Ja iestatāt apmali vienai malai, tad visas malas saņems to pašu vērtību.");
	strcpy(sIfyousetthegrindingforoneedgeallwillreceivethesamevalue, "Ja iestatāt slīpēšanas vērtību vienai malai, tad visas malas saņems to pašu vērtību.");
	strcpy(sIfyousetthetrimforoneedgeallwillreceivethesamevalue, "Ja jūs iestatāt apgriešanas vērtību ​​vienai malai, tad visas malas saņems to pašu vērtību.");
	strcpy(sImageBounds, "Attēla robežas");
	strcpy(sImageSize, "Attēla izmērs");
	strcpy(sImportData, "Importēt datus");
	strcpy(sIncorrectPassword, "Nepareiza parole");
	strcpy(sIndex, "Indekss");
	strcpy(sInformationaboutcustomer, "Informācija par klientu");
	strcpy(sInputALanguageName, "Dodiet nosaukumu valodai");
	strcpy(sInsert, "Ievietot");
	strcpy(sInsertPiece, "Ievietot gabalu");
	strcpy(sInterface, "Interfeiss");
	strcpy(sInterfaceSettings, "Interfeisa uzstādījumi");
	strcpy(sInvalidHardware, "Es nevarēju noteikt datora dzelžus. Lūdzu, sazinieties ar mums contact@optimalprograms.com");
	strcpy(sInvalidNumber, "Nepareizs numurs");
	strcpy(sInvalidOrderOfComputation, "Nevar noteikt skaitļošanas kārtību priekš garumiem. Šeit ir cirkulāra attiecības produkta definīcijā!");
	strcpy(sInvalidRegistration, "Reģistrācija ir nederīga!");
	strcpy(sInvalidTime, "Jūsu sistēmas laiks ir nederīgs.");
	strcpy(sInventory, "UZKRĀJUMS");
	strcpy(sisafractionalvalue, "ir dalītas vērtības.");
	strcpy(sIsArc, "Ir loka");
	strcpy(sisarealvalue, "ir reāla vērtība.");
	strcpy(sLabel, "Etiķete");
	strcpy(sLabels, "Etiķetes");
	strcpy(sLanguage, "Valoda");
	strcpy(sLatimeanumar0, "Platumam jābūt lielākam par 0!");
	strcpy(sLatimeanumarreal, "Platumam jābūt reālam skaitlim!");
	strcpy(sLayerName, "Slāņa nosaukums");
	strcpy(sLeft, "Pa kreisi");
	strcpy(sLeftcoordinateofthedefect, "Kreisā defekta koordināta");
	strcpy(sLength, "Garums");
	strcpy(sLengthofthepiecestocut, "Gabala griešanas izmērs");
	strcpy(sLengthofthepiecestocutfrom, "Loksnes griešanas izmērs");
	strcpy(sLengthofusedbars, "Izmantoto bāru izmērs");
	strcpy(sLicenseAgreement, "licences vienošanās");
	strcpy(sLinear, "Lineārs");
	strcpy(sLinethickness, "Pildspalvas biezums");
	strcpy(sLoadafileandappenddatatothecurrentDemand, "Ielādēt failu un apvienot datus no faila priekš asošā pieprasījuma.");
	strcpy(sLoadanexistingDemandfromafile, "Ielādēt esošo pieprasījumu no faila.");
	strcpy(sLoadAppend, "Ielādēt un apvienot");
	strcpy(sLoadEverything, "Ielādēt visu");
	strcpy(sLoadInventory, "Ielādēt uzkrājumu");
	strcpy(sLoadInventoryandDemand, "Ielādēt uzkrājumu un pieprasījumu");
	strcpy(sLoadResults, "Ielādēt rezultātus");
	strcpy(sLocked, "Slēgts");
	strcpy(sLogo, "logotips");
	strcpy(sLong, "Garš");
	strcpy(sLongerexecutiontime, "Ilgāks izpildes laiks");
	strcpy(sLungime, "Platums");
	strcpy(sLungimeanumar0, "Garumam jābūt lielākam par 0!");
	strcpy(sLungimeanumarreal, "Garumam jābūt reālam skaitlim!");
	strcpy(sLungimeaTotalaFolosita, "Kopējais izlietotais garums");
	strcpy(sMagnification, "Palielināšana");
	strcpy(sMagnify, "Palielināt");
	strcpy(sMargins, "Piemales");
	strcpy(sMarginsForPaper, "Papīra piemales");
	strcpy(sMarginsOfTheLabel, "Uzlīmju piemales");
	strcpy(sMaterial, "Materiāls");
	strcpy(sMaterialName, "Materiāla nosaukums");
	strcpy(sMaterials, "Materiāli");
	strcpy(sMaterialstypes, "Materiālu veidi");
	strcpy(sMax, "Maksimālais");
	strcpy(sMaximalArea, "Maksimālā platība");
	strcpy(sMaximalCutLength, "Maksimālais griešanas garums");
	strcpy(sMaxlength, "Maksimālais garums");
	strcpy(sMaxPiecesperBar, "Maksimālais gabalu daudzums uz bāru");
	strcpy(sMaxwidth, "Maksimālais platums.");
	strcpy(sMeasurementUnit, "Mērierīce");
	strcpy(sMin, "Minimālais");
	strcpy(sMinimalBreakSize, "Minimālais plīsuma izmērs");
	strcpy(sMinimalUsefulSize, "Minimālais izmantojamā izmērs");
	strcpy(sMinimalwastesizetoInventory, "Minimālais inventāra atlikumu apjoms");
	strcpy(s_What_to_minimize, "Ko samazināt?");
	strcpy(sMinlength, "Minimālais garuma");
	strcpy(sMinwidth, "Minimālais platums");
	strcpy(sMirror, "Spogulis");
	strcpy(sMirroring, "Spoguļošana");
	strcpy(sMiscellaneous, "Dažādi");
	strcpy(sModify, "Modificēt");
	strcpy(sModifytheselectedpiece, "Modificēt izvēlēto gabalu");
	strcpy(sMovePiece, "Pārvietot gabalu.");
	strcpy(sMultiplestages, "Vairāki posmi");
	strcpy(sName, "Nosaukums");
	strcpy(sNameofedgeband, "Nosaukums priekš malu apmalēm");
	strcpy(sNewDEMANDUnsaveddatawillbelost, "Jauni gabali? Nesaglabātie dati tiks zaudēti!");
	strcpy(sNewLanguage, "Jauna valoda");
	strcpy(sNewMaterial, "Jauns materiāls");
	strcpy(sNewPasswordincorectlyintroduced, "Jaunā parole nepareizi ievadīta!");
	strcpy(sNewProduct, "Jauns produkts");
	strcpy(sNewversion, "Jauna versija");
	strcpy(sNo, "Nē");
	strcpy(sNumarBucati, "Gabalu skaits");
	strcpy(sNumberOfCopies, "Kopiju skaits");
	strcpy(sNumberofstages, "Posmu skaits");
	strcpy(sNusuficienteplacidepozit, "Ne visi gabali ir optimizēti. Iespējamie iemesli: Nav pietiekami daudz gabalu inventārā; gabals netika izlietots optimizācijā; Materiāli no pieprasījuma un inventāra nesakrita; citi parametri tika nepareizi noteikti. Ja jūs nevarat atrast iemeslu, tad jūs varat nosūtīt mums reportu atverot izvēlni -> Palīdzība -> Serviss -> Saglabāt visu.  Lūdzu nosūtiet mums uz e-pastu uzģenerēto failu.");
	strcpy(sOfficeNotInstaled, "Microsoft Office nav uzstādītas uz jūsu datora vai incorect versija ir instalēta!");
	strcpy(sOldpassworddoesnotmatch, "Iepriekšējā parole nesakrīt!");
	strcpy(sOnlinehelp, "Tiešsaistes palīdzība");
	strcpy(sOnlypiecesofthesameheightinthelaststage, "Vienāda garuma gabali pēdējā posmā.");
	strcpy(sOpen, "Atvērt");
	strcpy(sOptimization, "Optimizācija");
	strcpy(sOptimizationDone, "Optimizācija tika veikta! Jūs varat izdrukāt vai saglabāt iegūtās diagrammas. Nospiediet pogu Pieņemt ja esat apmierināts ar pašreizējo risinājumu. Pretējā gadījumā nospiediet Sākt vēlreiz.");
	strcpy(sOptimizationType, "Optimizācija Tips");
	strcpy(sOptions, "Iespējas");
	strcpy(sOptionsrelatedtotheinterface, "Iespējas attiecībā uz interfeisu");
	strcpy(sor, "vai");
	strcpy(sOthercomponents, "Citi komponenti");
	strcpy(sOthers, "Citi");
	strcpy(sOtherstatistics, "Citas statistikas");
	strcpy(sOverrideExcelCSVfiles, "Ignorēt Excel/CSV failus");
	strcpy(sParameter, "Parametrs");
	strcpy(sParts, "GABALI");
	strcpy(sPattern, "Šablons");
	strcpy(sPatternforwaste, "Atlikumu šablons");
	strcpy(sPerimeter, "Perimetrs");
	strcpy(sPermitedRotationAngle, "Pieļaujamais rotācijas leņķis.");
	strcpy(sPhone, "Telefons");
	strcpy(sPicture, "Bilde");
	strcpy(sPiece, "Gabals");
	strcpy(sPieceindex, "Gabala indekss");
	strcpy(sPieces, "Gabali");
	strcpy(sPiecesize, "Gabala izmērs");
	strcpy(sPiecesizelabeledgebandwillbeprinted, "Gabala izmērs, uzlīme, malu apmales tiks izdrukātas.");
	strcpy(sPierdere, "Atlikumi");
	strcpy(sPixels, "pikseļi");
	strcpy(sPlacilefolositeDepozit, "Izlietotie gabali no inventāra.");
	strcpy(sPlease_contact_us_at_contact_nestingtechnologies_com, "Lūdzu, sazinieties ar mums contact@nesting-technologies.com");
	strcpy(sPlease_contact_us_at_contact_optimalprograms_com, "Lūdzu, sazinieties ar mums contact@optimalprograms.com");
	strcpy(sPleaseenteralldataeitherasfractionalorrealDonotmixthem, "Lūdzu ievadiet visus datus kā frakcionētus vai reālus. Nejauciet viņus kopā!");
	strcpy(sPleaseEnterSomeTypesOfMaterials, "Nav noteikts materiāla veids. Jūs varat definēt tos izvēlnes Materiāli.");
	strcpy(sPleasesendtheNameandtheCodetotheaddresscontactoptimalprogramscominordertoobtaintheRegistrationKey, "Lai iegūtu reģistrācijas atslēgu, lūdzu nosūtiet vārdu un kodu uz: contact@optimalprograms.com.");
	strcpy(sPolygon, "Daudzstūris");
	strcpy(sPolygonsCircles, "Daudzstūri, apļi");
	strcpy(sPrecision, "Precizitāte");
	strcpy(sPretulnumar0, "Cenai jābūt lielākai par 0!");
	strcpy(sPretulnumarreal, "Cenai jābūt reālam skaitlim!");
	strcpy(sPreview, "Priekšskatījums");
	strcpy(sPrice, "Cena");
	strcpy(sPriceMustBeGreaterThanZero, "Cenai jābūt lielākai par nulli");
	strcpy(sPriceofbars, "Bāru cena");
	strcpy(sPriceperbar, "Cena par bāru");
	strcpy(sPricepersheet, "Cena par loksni");
	strcpy(sPricepersquareunitofmaterial, "Cena par vienu materiāla kvadrātmetru.");
	strcpy(sPriceperunit, "Cena par vienību");
	strcpy(sPriceperunit, "Cena par vienību");
	strcpy(sPrint, "Drukāt");
	strcpy(sPrintdiagramsastables, "Drukāt diagrammas tabulu veidā.");
	strcpy(sPrinter, "Printeris");
	strcpy(sPrinterBounds, "Piemales priekš printera");
	strcpy(sPrintonlyutilizedarea, "Drukāt tikai izlietoto platību");
	strcpy(sPrintthecontentsoftheDemand, "Drukāt saturu no pieprasījuma.");
	strcpy(sPrintthecontentsoftheInventory, "Drukāt saturu no uzkrājuma.");
	strcpy(sPrintthecurrentsolution, "Drukāt pašreizējo risinājumu.");
	strcpy(sPriority, "Prioritāte");
	strcpy(sPrioritytocutapieceZero0isthehighestpriority, "Prioritāte, lai sagrieztu gabalu. Nulle (0) ir augstākā prioritāte.");
	strcpy(sProcentul0100, "Procentiem ir jābūt lielākiem par 0 un mazākiem vai vienādiem ar 100!");
	strcpy(sProcentulnumarreal, "Procentiem ir jābūt reāliem skaitļiem!");
	strcpy(sProductdefinition, "Produkta definīcija");
	strcpy(sProductExists, "Produkts jau eksistē. Izvēlieties citu nosaukumu.");
	strcpy(sProductName, "Produkta nosaukums");
	strcpy(sProducts, "Produkts");
	strcpy(sProducts, "Produkti");
	strcpy(sProject, "Projekts");
	strcpy(sProperties, "īpašums");
	strcpy(sProperty, "īpašums");
	strcpy(sQuantity, "Daudzums");
	strcpy(sQuantitynumberofsheetsofthistype, "Šī tipa lokšņu skaits");
	strcpy(sRadius, "Rādiuss");
	strcpy(sRectangular, "Taisnstūra");
	strcpy(sRedefinetypesofedgeband, "Pārdefinēt malu apmaļu veidus");
	strcpy(sRedefinetypesofmaterial, "Pārdefinēt materiālu veidus");
	strcpy(sRegistration, "Reģistrācija");
	strcpy(sRegistrationKeyfromOptimalPrograms, "Reģistrācijas atslēga");
	strcpy(sRegistrationSuccessful, "Reģistrācija veiksmīga!");
	strcpy(sRemoveallpiecesinInventory, "Noņemt visus gabalus no inventāra.");
	strcpy(sRemoveCut, "Dzēst griezumu");
	strcpy(sRemovetheselectedpiece, "Noņemt izvēlēto gabalu");
	strcpy(sReports, "Reporti");
	strcpy(sRequestedMaterial, "Pieprasītais Materiāls");
	strcpy(sRestore, "Atjaunot");
	strcpy(sResults, "Rezultāti");
	strcpy(sReusedwaste, "Atkārtoti atlikumi");
	strcpy(sRight, "Labajā");
	strcpy(sRightcoordinateofthedefect, "Koordinātas no defektu no labās puses");
	strcpy(sRotation, "Grozāms");
	strcpy(sRotationAngle, "Rotācijas leņķis");
	strcpy(sRotationStep, "Rotācija solis");
	strcpy(sRoundAllFractionsTo, "Frakcionētās vērtības jānoapaļo līdz");
	strcpy(sRow, "rinda");
	strcpy(sRows, "Rindas");
	strcpy(sRun, "Pēdējie risinājumi");
	strcpy(sRunningtime, "darbības laiks");
	strcpy(sSameforall, "To pašu priekš visiem");
	strcpy(sSave, "Saglabāt");
	strcpy(sSaveAllImages, "Saglabāt visus attēlus");
	strcpy(sSaveAs, "Saglabāt kā");
	strcpy(sSaveChanges, "Pieprasījums tika mainīts. Vai jūs vēlaties saglabāt?");
	strcpy(sSaveCurrentImage, "Saglabāt pašreizējo attēlu");
	strcpy(sSavedataparameters, "Saglabāt datus un parametrus");
	strcpy(sSaveEverything, "saglabāt visu");
	strcpy(sSaveInventory, "Saglabāt Inventāru");
	strcpy(sSaveInventoryandDemand, "Saglabāt Inventāru un pieprasījumu");
	strcpy(sSaveResults, "Saglabāt rezultātus");
	strcpy(sSaveStatisticsinafile, "Saglabāt statistiku failā");
	strcpy(sSavethecurrentimage, "Saglabāt pašreizējo attēlu");
	strcpy(sSavethecurrentimageorstatistic, "Saglabāt pašreizējo attēlu vai statistisku");
	strcpy(sSavetheDEMANDinafile, "Saglabāt failā");
	strcpy(sSavetheDemandinafilewithadifferentname, "Saglabāt pieprasījumu failā ar citu nosaukumu.");
	strcpy(sSavetheREPOSITORYinafile, "Saglabāt uzkrātuvi failā");
	strcpy(sSerialNumber, "Reģistrācijas atslēga");
	strcpy(sService, "Pakalpojums");
	strcpy(sSetDefaultValues, "Šis atjaunos visus parametrus uz noklusētajām vērtībām. Visi jūsu iestatījumi tiks zaudēti. Vai tiešām vēlaties to darīt?");
	strcpy(sSetedgeband, "Uzstādīt malu apmali");
	strcpy(sSetedgetrim, "Uzstādīt defektu malām griezumu");
	strcpy(sSetthesameedgebandforalledges, "Uzstādīt tās pašas malu apmali priekš visām malām");
	strcpy(sSetthesamegrindingforalledges, "Uzstādīt to pašu slīpēšanas vērtību priekš visām malām.");
	strcpy(sSetthesametrimforalledges, "Uzstādīt defektu malām to pašu griezumu");
	strcpy(sSettings, "Iestatījumi");
	strcpy(sShape, "Forma");
	strcpy(sSheet, "Loksne");
	strcpy(sSheetsBarstypes, "Lokšņu_Bāru veidi");
	strcpy(sSheetSize, "Loksnes izmērs");
	strcpy(sSheetsperPage, "Lokšņu skaits lapā");
	strcpy(sShort, "Īss");
	strcpy(sShorterexecutiontime, "Īss darbības laiks");
	strcpy(sShowallsimpleproducts, "Parādīt visus elementāros produktus");
	strcpy(sShowcustomername, "Parādīt klienta nosaukuma");
	strcpy(sShowCustomTextOnEachPiece, "Parādīt izvēles tekstu katram gabalam");
	strcpy(sShowdiagramasatable, "Parādīt diagrammu kā tabulu.");
	strcpy(sShowedgeband, "Parādīt malu apmales");
	strcpy(sShowedgebandssettinginanewwindow, "Parādīt iestatījumus malu apmalēm jaunā logā.");
	strcpy(sShowgrindingsettingsinanewwindow, "Parāda slīpēšanas iestatījumus jaunā logā.");
	strcpy(sShowHorizontalLabelsAlways, "Rādīt vienmēr horizontālās uzlīmes");
	strcpy(sShowRemovethesizeofthepiecesinthecurrentsolution, "Parādīt/Noņemt izmēru pašreizējā risinājuma gabaliem.");
	strcpy(sShowRemovethesizeofthewastesinthecurrentsolution, "Parādīt/Noņemt izmēru pašreizējā risinājuma atlikumiem.");
	strcpy(sShowtotalcutlength, "Parādīt kopējo griešanas garumu");
	strcpy(sShowtrimedgesettingsinanewwindow, "Parādīt uzstādījumus priekš defektiem jaunā logā.");
	strcpy(sSimpleMaterialExists, "Materiāla nosaukums jau ir noteikts materiālu sarakstā. Lūdzu sniegt tam jaunu nosaukumu.");
	strcpy(sSinglePieceStrips, "Viena gabala svītras.");
	strcpy(sSizes, "Izmēri");
	strcpy(sSmallerorequalto, "Mazāks vai vienāds ar");
	strcpy(sSort, "Kārtot");
	strcpy(sSortAscendingByArea, "Kārtot augošā secībā pēc platības");
	strcpy(sSortDescendingByArea, "Kārtot dilstošā secībā pēc platības");
	strcpy(sSpecifyhowdifferentthepiecesinthelaststagecanbeValue0meansnodifference, "Norādiet, cik dažādi var būt gabali pēdējā posmā. Vērtība 0 nozīmē, ka bez atšķirībām.,");
	strcpy(sSpecifyifpiecesinthelaststagecanbedifferentornotdepeultimaetapapotfidiferitesaunucadimensiune, "Norādiet vai gabali pēdējā posmā var būt atšķirīgi, vai nevar būt atšķirīgi");
	strcpy(sSpecifyifthepiececanberotatedornotIfnotitwillbecutinthesamewayasitwasintroducedinDemandLengthofthepieceparalleltothelengthofthesheet, "Norādiet vai gabals var rotēt(pielāgoties) vai nevar. Ja nevar, tad tas tiks ievietots tādā veidā, kā tas tika ieviests pieprasījumā (gabala garums paralēli lapas garumam),");
	strcpy(sSpecifyinhowmanystageswemakethecutsDuringastageallcutshavethesamedirection, "Norādiet, cik daudz posmos mēs veicamam griezumus.");
	strcpy(sStartthesearchprocess, "Sāktu meklēšanas procesu");
	strcpy(sStatistics, "Statistika");
	strcpy(sStatisticsE, "Papildus Reporti");
	strcpy(sStatisticsforeachtypeofmaterial, "Statistika priekš katra veida materiāliem");
	strcpy(sStep, "Solis");
	strcpy(sStergeDepozit, "Jūs vēlaties dzēst inventāru?");
	strcpy(sStergeMaterial, "Dzēst materiālu?");
	strcpy(sStergePiesele, "Jūs vēlaties dzēst gabalu?");
	strcpy(sStergePiesa, "Jūs vēlaties dzēst gabalu?");
	strcpy(sStopthesearchprocess, "Apturēt meklēšanas procesu");
	strcpy(sStrongoptimization, "Spēcīga optimizācija");
	strcpy(sSubtractthebandthicknessfrompiecesize, "Samazināt gabala izmēru ar apmaļu biezumu.");
	strcpy(sSummary, "Kopsavilkums");
	strcpy(sSuprafataTotalaFolosita, "Kopējā izmantotā virsma");
	strcpy(sSuprafatautilizata, "Izlietošana");
	strcpy(sSwitchbetweenfiberandrotationoption, "Pārslēgties starp šķiedru un rotācijas iespēju.");
	strcpy(sTechnical, "Tehniski");
	strcpy(sTechnicalsettings, "Tehniskie iestatījumi");
	strcpy(sTemporaryPanelHint, "Pagaidu panelis priekš pārvietošanas starp loksnēm.");
	strcpy(sText, "Teksts");
	strcpy(sThe_application_has_expired, "Programma ir beidzies.");
	strcpy(sThe_application_is_not_registered, "Programmatūra nav reģistrēta.");
	strcpy(sThe_application_was_first_started_on, "Programmatūra pirmo reizi tika uzsākta.");
	strcpy(sThecutsareperformedfromasidetotheothersideofthematerial, "Debetēšana tiek veikta no vienas materiāla puses uz otru pusi.");
	strcpy(sThecuttingmachinecanfollowtheshapeofthematerial, "Griešanas mašīna var sekot gabala formai.");
	strcpy(sTheedgesofsheetsthatmustbetrimedduefaults, "Lokšņu malas, kuras jāapgriež dēļ nederīguma.");
	strcpy(sTheLargestSize, "Lielākais izmērs");
	strcpy(sThenameofthecustomerforwhichyoucutthepiece, "Klienta nosaukums, priekš kura jūs griežat gabalu.");
	strcpy(sThenameofyourcustomer, "Jūsu klienta nsaukums");
	strcpy(sThepiececanberotated, "Gabals var tikt rotēts (pielāgots)");
	strcpy(sTheprogramtriestoavoidwasteswhichhavebothsizeslessthanthisvalue, "Programma mēģina izvairīties no atlikumiem, kuriem abi izmēri mazāki par šo vērtību");
	strcpy(sThereAreNoProducts, "Vēl nav definētu produktu");
	strcpy(sThestockofmaterialhasbeenpreviouslyloadedfromanExcelorCSVformatPleaseloaditagain, "Materiāla uzkrājumi tika iepriekš ielādēti no Excel vai CSV formāta. Lūdzu, ielādēt vēlreiz, ja jūs vēlaties strādāt ar to.");
	strcpy(sThetotallengthofcutting, "Kopējais griešanas garums");
	strcpy(sThewidthofthecuttingsawForglasscuttingoptimizationitcanbe0Forwooditshouldbegreaterthan0, "Zāģa griezuma biezums. Priekš stikla griešanas biezums var būt 0. Priekš koka griezšnas biezumam jābūt lielākam par 0.");
	strcpy(sThewidthofthecuttingsawforlinearpieces, "Zāģa griezuma biezums priekš lineāriem gabaliem.");
	strcpy(sThickness, "Biezums");
	strcpy(sThischaracterisusedforfillingthewasterectanglesIfyoudonotwantfilledwastejustremovethischaracter, "Šis simbols tiek izmantots priekš aizpildīšanas atlikumu taisnstūru laukumiem. Ja jūs nevēlaties aizpildītus atlikumus, tad vienkārši noņemat viņu.");
	strcpy(sThisindexhasvaluebetween1andthenumberofpieces, "Šim indeksam ir vērtība starp 1 un gabalu skaitu.");
	strcpy(sThisOptionWillOverrideTheInventoryFileIfLoadedFromExcelOrCsvFiles, "Šī opcija ignorēs inventāra failu, ja ielādēts no Excel vai CSV failiem.");
	strcpy(sThisProgramisLicensedTo, "Šī programma ir licencēta uz");
	strcpy(sThisvaluewillbeaddedtotheedgebandingmaterialoneachside, "Šī vērtība tiks pievienota malas aplīmēšanas materiālam katrā pusē");
	strcpy(sTipNevid, "Materiāla veids nevar būt tukšs.");
	strcpy(sTitle, "Virsraksts");
	strcpy(sTools, "Rīki");
	strcpy(sTop, "Augša");
	strcpy(sTopcoordinateofthedefect, "Augšējā defekta koordināta.");
	strcpy(sTotalGarbageWaste, "Visi nederīgie atlikumi");
	strcpy(sTotalInventoryWaste, "Uzkrājumā kopējais atlikumu daudzums");
	strcpy(sTotalRecycledWaste, "Visi izmestie atlikumi");
	strcpy(sTotalusedarea, "Kopējā izmantotā platība");
	strcpy(sTotalusedlength, "Kopējais izmantotais garums");
	strcpy(sTrigonometric, "Trigonometriskais");
	strcpy(sTrim, "Apgriezt");
	strcpy(sTrimalledgesatthebeginning, "Apgriezt visas malas sākumā");
	strcpy(sTrimEdge, "Apgriezt malas");
	strcpy(sTwoPanels, "2 paneļi");
	strcpy(sType, "tips");
	strcpy(sTypeofmaterialfromwhichtocut, "Materiāla veids, no kura griezt");
	strcpy(sTypesAreNotMatched, "Optimizācija netika veikta! Materiāli no detaļu un noliktavas tabulām nesakrīt! Detaļu var izgriezt tikai no materiāla ar tādu pašu nosaukumu noliktavā. Mainiet materiāla nosaukumu atbilstošajās kolonnās!");
	strcpy(sUndo, "Atsaukt");
	strcpy(sUndoAccept, "Atsaukt Apstiprinājumu");
	strcpy(sUnits, "vienības");
	strcpy(sUnregisteredVersion, "Nereģistrēts");
	strcpy(sUpdates, "Atjauninājumi");
	strcpy(sUsefulforwoodfurniture, "Noderīgs priekš koka mēbelēm");
	strcpy(sUseit, "Izmantojiet to");
	strcpy(sUsePieceinOptimization, "Izmanto gabalu optimizācijā");
	strcpy(sUserName, "Lietotāja vārds");
	strcpy(sUtilizationandWastes, "Izlietošana un atlikumi");
	strcpy(sUtilizedArea, "Izlietoto daļu platība");
	strcpy(sUtilizedBars, "Izlietotie bāri");
	strcpy(sUtilizeddemandcount, "Izlietoto gabalu skaits");
	strcpy(sUtilizedParts, "Izlietotās daļas");
	strcpy(sUtilizedPieces, "Izlietotie gabali");
	strcpy(sUtilizedSheets, "Izlietotās loksnes");
	strcpy(sValue, "Vērtība");
	strcpy(sValueGreaterEqualToZero, "Vērtībai jābūt lielākai vai vienādai ar nulli");
	strcpy(sValueGreaterThanZero, "Vērtībai jābūt lielākai par nulli");
	strcpy(sValueIntegerNumber, "Vērtībai ir jābūt veselam skaitlim!");
	strcpy(sValueRealNumber, "Vērtībai jābūt reālam skaitlis. Varbūt jūs esat izmantojis, nevis. vai otrādāk. Lūdzu salabojat!");
	strcpy(s_The_number_is_too_big_or_it_has_too_many_digits_after_decimal_separator, "Skaitlis ir pārāk liels vai tam ir pārāk daudz ciparu aiz komata atdalītāja!");
	strcpy(s_The_number_is_too_big, "Skaits ir pārāk liels!");
	strcpy(sVertical, "Vertikāls");
	strcpy(sWaste, "Atlikumi");
	strcpy(sWastes, "Atlikumi");
	strcpy(sWasteAddedToWarehouse, "Atkritumi pievienoti noliktavai");
	strcpy(sWastelimits, "ierobežojumi atkritumiem");
	strcpy(sWasteType, "Atkritumu veids");
	strcpy(sWeakoptimization, "Vājākā optimizācija");
	strcpy(sWhattoprint, "Ko man nepieciešams drukāt");
	strcpy(s_What_to_print_or_save_to_file, "Ko drukāt vai saglabāt failā");
	strcpy(sWhattoprintoneachpiece, "Ko drukāt uz katra gabala");
	strcpy(sWhattoshowoneachpiece, "Ko rādīt uz katra gabala?");
	strcpy(sWidth, "Platums");
	strcpy(sWood, "koks");
	strcpy(sWorkingDirectory, "Darba direktorija");
	strcpy(sWrongKey, "Nepareiza reģistrācijas atslēga!");
	strcpy(sYes, "Jā");
	strcpy(sYoucannotchooseblackblueorredcolors, "Jūs nevarat izvēlēties melno, zilo vai sarkano krāsu.");
	strcpy(sYouCannotMixFractionalDataWithDecimalOnes, "Jūs nevarat sajaukt dalītās vērtības ar reālām vērtībām!");
	strcpy(sYourcompany, "Jūsu uzņēmums");
	strcpy(sZip, "Pasta indekss");
	strcpy(s_Set_the_origin_and_the_direction_of_the_axes, "Iestatiet koordinātu asu sākumpunktu un virzienu.");










	strcpy(s_Number_of_digits_after_the_decimal_separator, "Ciparu skaits aiz decimāldaļas atdalītāja");
	strcpy(s_Percentages, "Procenti");
}

