// Language strings: Bulgarian
// Author: Optimal Programs
// License: MIT License
//---------------------------------------------------------------------------
#include <string.h>
//---------------------------------------------------------------------------
#include "language_string_id.h"
//---------------------------------------------------------------------------
void set_bg(void)
{
	//Bulgarian
	// translated by a customer
	// last update on: 2025.9.25.0
	strcpy(s_Area, "Площ");
	strcpy(s_Mass, "Маса");
	strcpy(s_Advanced, "Разширено");
	strcpy(s_Relative_coordinates, "Относителни координати");
	strcpy(s_Absolute_coordinates, "Абсолютни координати");
	strcpy(s_Append_more_rows, "Добавете още редове");

	strcpy(s_Add_to_parts, "Добави детайл.");
	strcpy(s_Additional, "Допълнителен");
	strcpy(s_All_results, "Всички резултати.");
	strcpy(s_Allow_movement_of_pieces, "Позволете движение на парчета");
	strcpy(s_Allow_part_in_part, "Позволете парче в парче");
	strcpy(s_Invalid_piece_Angles_are_too_small_or_too_big_or_height_is_too_small, "Невалидно парче! Ъглите са твърде малки или твърде големи, или височината е твърде малка.");
	strcpy(s_Append, "Добавяне");
	strcpy(s_As_it_is, "Както е");
	strcpy(s_As_text, "Като текст");
	strcpy(s_Ascending, "Възходящ");
	strcpy(s_Automatic, "Автоматичен");
	strcpy(s_Cannot_connect_to_the_Internet_Please_visit_our_website_from_a_browser, "Няма връзка с интернет! Моля, посетете нашия уебсайт от браузър.");
	strcpy(s_Cannot_copy_or_move_the_files, "Не можете да копирате или премествате файловете!");
	strcpy(s_Cannot_delete_the_file, "Не можете да изтриете файла!");
	strcpy(s_Cannot_modify_old_results, "Не могат да се променят стари резултати!");
	strcpy(s_To_change_click_inside_a_cell_or_press_0_1_or_2, "За да промените, щракнете в клетка или натиснете 0, 1 или 2.");
	strcpy(s_Cell, "клетка");
	strcpy(s_Click_on_the_table_header_to_change_the_columns, "Кликнете върху заглавката на таблицата, за да промените колоните.");
	strcpy(s_Close, "Затвори");
	strcpy(s_Contact_us, "Свържете се с нас");
	strcpy(s_Column, "Колона");
	strcpy(s_Comma, "Запетая");
	strcpy(s_The_comma_symbol_cannot_simultaneously_be_the_list_separator_and_the_decimal_separator, "Символът запетая не може едновременно да бъде разделител за списък и десетичен разделител!");
	strcpy(s_Copy, "Копирай");
	strcpy(s_Copy_for_move, "Копирай за преместване");
	strcpy(s_Cut_higher_level_strips_first, "Първо изрежете ленти с по-високо ниво");
	strcpy(s_Cut_index, "Покажи индекса на срязовете");

	strcpy(s_The_data_have_been_changed_Do_you_want_to_save_them_to_a_file, "Данните са променени. Искате ли да ги запазите във файл?");
	strcpy(s_Decimal_separator, "Десетичен разделител");
	strcpy(s_Restore_default_settings, "Възстановете настройките по подразбиране");
	strcpy(s_Delete_fiber, "Изтрий фладера");
	strcpy(s_Descending, "Низходящ");
	strcpy(s_Discard_changes, "Откажи промените");

	strcpy(s_Delete_all_data, "Да се изтрият ли всички данни?");
	strcpy(s_Dot, "Точка");
	strcpy(s_Do_you_want_to_delete_the_picture, "Искате ли да изтриете изображението?");
	strcpy(s_Do_you_want_to_delete_the_product, "Искате ли да изтриете продукта?");
	strcpy(s_Duplicate_and_append, "Дублирай и добави.");
	strcpy(s_Duplicate_values_are_ignored, "Дублираните стойности бяха игнорирани!");
	strcpy(s_Error, "Грешка");
	strcpy(s_Error_loading_file, "Грешка при зареждането на файла.");
	strcpy(s_export_everything, "Експортирайте всичко");
	strcpy(s_Fit_to_screen, "Оразмери по екрана.");
	strcpy(s_Force_fixed_height, "Начертайте парчетата с фиксирана височина.");
	strcpy(s_Flipped, "Обърнато");
	strcpy(s_Import, "Импортирай");
	strcpy(s_If_angles_are_different_from_90_degrees_height_must_be_greater_than_0, "Ако ъглите са различни от 90 градуса, височината трябва да е по-голяма от 0.");
	strcpy(s_Ignore, "Игнорирайте");
	strcpy(s_Incorrect_value, "Неправилна стойност");
	strcpy(s_Info, "информация");
	strcpy(s_Interior, "Вътре");
	strcpy(s_Give_a_name, "Наименование.");
	strcpy(s_Group, "Групиране");
	strcpy(s_Header, "Заглавка");
	strcpy(s_Keep_it_as_it_is, "Дръжте го такъв, какъвто е");
	strcpy(s_Level, "Level");
	strcpy(s_Licensee, "Лицензополучател");
	strcpy(s_List_separator, "Разделител на списък");
	strcpy(s_Made_with_love_in_Cugir_Romania, "Произведено с любов в: Кугир, Румъния");
	strcpy(s_Made_in, "Произведено в");
	strcpy(s_Manufacturer, "производител");

	strcpy(s_Manual_arrange, "Ръчно подреждане");

	strcpy(s_Mixed, "Смесен");
	strcpy(s_Multiple_shapes_detected_Next_rows_will_be_overwritten_Continue, "Открита е повече от една форма. Следователно следващите редове ще бъдат презаписани. Продължи?");
	strcpy(s_More, "Повече");
	strcpy(s_Multiple_values, "Множество стойности");
	strcpy(s_No_texture, "Без текстура");
	strcpy(s_Number, "Брой");
	strcpy(s_Number_of_images, "Брой изображения");
	strcpy(s_Number_of_vertices, "Брой върхове");
	strcpy(s_Offset, "Изместване");
	strcpy(s_Only_the_currently_selected_items, "Само текущо избраните елементи.");
	strcpy(s_Optimizing_please_wait, "Оптимизиране... моля изчакайте.");

	strcpy(s_Paste, "Вмъкни");
	strcpy(s_Paste_from_Clipboard, "поставяне от клипборда");
	strcpy(s_Piece_label, "Покажи името на детайла");
	strcpy(s_Piece_size, "Покажи размера на детайла");
	strcpy(s_Please_contact_us_by_email_if_you_receive_this_error, "Моля, свържете се с нас по имейл, ако получите тази грешка.");
	strcpy(s_Please_save_it_first, "Моля, запазете го първо.");
	strcpy(s_Position, "Позиция");
	strcpy(s_Preview, "Визуализация");
	strcpy(s_Rectangle, "Правоъгълник");

	strcpy(s_Redo_the_last_operation, "Възстановете последната операция");
	strcpy(s_Regular_polygon, "Полигон");
	strcpy(s_Relative, "Относителна");
	strcpy(s_Reused, "Използван");
	strcpy(s_Rotated, "Завъртян");
	strcpy(s_Save_all, "Запази всичко");
	strcpy(s_Scrap_label, "Покажи отпадъците");
	strcpy(s_Scrap_size, "Покажи размера на отпадъците");
	strcpy(s_Semicolon, "точка и запетая");
	strcpy(s_Show_cut_index, "Покажи индекса на срязовете");
	strcpy(s_Show_information, "Покажи забележката");
	strcpy(s_Show_piece_label, "Покажи името на детайла");
	strcpy(s_Show_scrap_label, "Покажи етикета със загубите");
	strcpy(s_Show_scrap_s_size_on_the_small_pieces, "Покажете размера на скрап на малките парчета");
	strcpy(s_Show_size_of_pieces, "Покажи размера на парчетата");
	strcpy(s_Show_size_of_scrap, "Покажи размера на загубите");
	strcpy(s_Show_sizes, "Показване на размери");
	strcpy(s_Show_label, "Показване на етикет");
	strcpy(s_Show_length, "Показване на дължина");

	strcpy(s_Some_numerical_values_are_incorrect_Should_I_fix_all_the_incorrect_values, "Някои числови стойности са неправилни! Трябва ли да коригирам всички неправилни стойности?");
	strcpy(s_Some_invalid_values_have_been_removed, "Някои невалидни стойности бяха премахнати.");
	strcpy(s_Sort_by, "Сортиране по");
	strcpy(s_Sort_ascending_by, "Сортиране възходящо по");
	strcpy(s_Sort_descending_by, "Сортиране по низходящ по");
	strcpy(s_Start, "Start");
	strcpy(s_Starting_angle, "Начален ъгъл");


	strcpy(s_Stock, "НАЛИЧНОСТ");
	strcpy(s_Stop, "Stop");
	strcpy(s_System_setting, "Системна настройка");
	strcpy(s_Tabular, "Табличен");
	strcpy(s_Total, "Обща сума");
	strcpy(s_Total_size, "Общият размер");
	strcpy(s_Terms_of_the_license, "Условия на лиценза");
	strcpy(s_The_current_product_has_been_changed_Do_you_want_to_save_it_to_file, "Текущият продукт е променен. Искате ли да го запишете във файл?");
	strcpy(s_The_value_is_out_of_the_allowed_range, "Стойността е извън допустимия диапазон.");
	strcpy(s_The_value_must_be_a_real_or_fractional_number_Try_to_replace_the_comma_with_the_dot_if_you_want_to_enter_a_real_number, "Стойността трябва да е реално или дробно число. Опитайте да замените запетаята с точката, ако искате да въведете истинско число.");
	strcpy(s_This_feature_is_not_implemented_yet, "Тази функция все още не е внедрена.");
	strcpy(s_This_operation_cannot_be_reversed, "Тази операция не може да бъде обърната.");
	strcpy(s_Undo_the_last_operation, "Отменете последната операция.");
	strcpy(s_Utilization, "Използване");
	strcpy(s_Utilized_Stock, "Използван склад");
	strcpy(s_Version, "Версия");
	strcpy(s_Visible_columns, "Видими колони");
	strcpy(s_You_already_have_the_latest_version_installed, "Вече имате инсталирана последната версия!");
	strcpy(s_What_is_exported, "Какво се изнася?");
	strcpy(s0meansanynumberofpieces, "Нула означава произволен брой детайли");
	strcpy(sAbout, "За програмата");
	strcpy(sAccept, "Приемам");
	strcpy(sAcceptall, "Приеми всички");
	strcpy(sAcceptthecurrentsolution, "Приемете текущото решение");
	strcpy(sAdd, "Добави");
	strcpy(sAddapiece, "Добави част");
	strcpy(sAddasimpleproducttoDemand, "Добави продукт в съществуващото търсене.");
	strcpy(sAddgrindingthicknesstopartsize, "Добави дебелина на към размера на частта");
	strcpy(sAddproductnametolabel, "Добавяне на името на продукта към етикета");
	strcpy(sAddress, "Адрес");
	strcpy(sAddselectedsizetoInventory, "Добави избрания размер към инвентара");
	strcpy(sAdhesivelabels, "Самозалепващи етикети");
	strcpy(sAdhesivelabelwithinformationaboutpiecesinDemandCustomernameLabelSizeCurrentData, "Самозалепващи се етикети с информация за броя на търсенето: име на клиент, етикет, размер, текущи данни.");
	strcpy(sAdhesivelabelwithinformationaboutsheetsinInventory, "Самозалепващи се етикети с информация за листовете в инвентара.");
	strcpy(sAll, "всичко");
	strcpy(sAlloffcutswhichhavethesizegreaterthanthisvaluewillbeaddedtoInventory, "Всички изрезки, които имат размер по-голям от тази стойност ще бъде добавен към инвентара");
	strcpy(sAllowMirroring, "Позволете отразявайки");
	strcpy(sAllowRotation, "Позволете въртене");
	strcpy(sAllPieces, "Всички детайли");
	strcpy(sAllpredefinedproducts, "Всички предварително определени продукти");
	strcpy(sAnewwindowwillbedisplayedwheretheusercansettheedgebandsforeachedge, "Ще се покаже нов прозорец, където потребителят може да настрои канта за всяка страна");
	strcpy(sAnewwindowwillbedisplayedwheretheusercansetthegrindingvalueforeachedgeofthsheet, "Ще се покаже нов прозорец, където потребителят може да настрои надмярката за всяка страна.");
	strcpy(sAnewwindowwillbedisplayedwheretheusercansetthetrimvalueforeachedgeofthsheet, "Ще се покаже нов прозорец, където потребителят може да настрои окрайчването за всяка страна.");
	strcpy(sAngle, "Ъгъл");
	strcpy(sAngles, "Ъгли");
	strcpy(sAnoptimizationparameterisarealnumber, "Оптимизационният параметър е реално число.");
	strcpy(sAnoptimizationparameterisfractionalnumber, "Оптимизационният параметър е относително число.");
	strcpy(sAnyShape, "Всяка форма");
	strcpy(sApolygonmusthaveatleast2vertices, "Полигонът трябва да има най-малко 2 върха!");
	strcpy(sApolygonmusthaveatleast3vertices, "Полигонът трябва да има най-малко 3 върха!");
	strcpy(sApplication_fails_to_initialize, "Софтуерът не може да се инициализира.");
	strcpy(sArc, "Дъга");
	strcpy(sArcLength, "Дължината на дъгата");
	strcpy(sAreaofusedsheets, "Площ на използваните плоскости");
	strcpy(sAshortdescriptionofthesheet, "Кратко описание на плоскостта");
	strcpy(sAtleastonepart, "Добавете поне един детайл!");
	strcpy(sAtTheMarginOfTheSheet, "По краищата на плоскостта");
	strcpy(sBandtypes, "Вид кант.");
	strcpy(sBar, "Профили / Тръби");
	strcpy(sBars, "Профили / Тръби");
	strcpy(sBothsizesoftheoffcutsmustbegreaterthanthisvalue, "Двата размера на изрезките трябва да бъдат по-голями от тази стойност.");
	strcpy(sBottom, "Долна част");
	strcpy(sBottomcoordinateofthedefect, "Долната координата на дефекта");
	strcpy(sBreakCut, "Прекъснете сряза");
	strcpy(sBrowse, "Търси");
	strcpy(sBuy, "Купи");
	strcpy(sBuynow, "Купи сега...");
	strcpy(sCancel, "Откажи");
	strcpy(sCannotBeEmpty, "Не може да бъде празно!");
	strcpy(sCannotmovepartsbetweensheetswhenidenticalsheetsaregroupedPleaseungroupthesheetsfrommenu, "Не може да се местят детайли от един разкрой на друг, ако идентичните разкрои са групирани. Моля, отменете групирането на разкроите от менюто.");
	strcpy(sCannotSaveFile, "Не можете да запишете файла");
	strcpy(sCenter, "Център");

	strcpy(sChangeDirection, "Промяна на посоката");
	strcpy(sChoose, "Избeри");
	strcpy(sChooseProduct, "Избери продукт");
	strcpy(sCircle, "Кръг");
	strcpy(sCity, "Град");
	strcpy(sClear, "Изчисти");
	strcpy(sClockWise, "По часовниковата стрелка");
	strcpy(sClosewindow, "Затвори прозореца");
	strcpy(sColor, "Цвят");
	strcpy(sColorofedgeband, "Цвят на канта");
	strcpy(sColorPattern, "Цвят / Код");
	strcpy(sColorpiecesandwastes, "Оцветени детайли и отпадъци.");
	strcpy(sColumns, "Колони");
	strcpy(sComment, "Коментар");
	strcpy(sCompanyname, "Име на фирма");
	strcpy(sComplexMaterialExists, "Името на материала вече е посочено в списъка на сложни материали. Моля, посочете ново име.");
	strcpy(sComputerCode, "Компютърен код");
	strcpy(sComputerCodefromyourcomputer, "Компютърен код (от компютъра)");
	strcpy(sComputethetotalpriceofDemand, "Изчисляване на общата цена на детайлите");
	strcpy(sContents, "Съдържание");
	strcpy(sContinutComanda, "Съдържание на търсенето по дата");
	strcpy(sContinutDepozit, "Съдържание на инвентара по дата");
	strcpy(sConversionIsDoneOnlyWhenSomePiecesHaveFractionalValues, "Преобразуванто се прави само тогава, когато някои детайли имат дробни стойности.");
	strcpy(sConvertsTheSizeOfWasteToAFractionalUnit, "Показва размера на загубите като относителна стойност.");
	strcpy(sCouldNotSaveFile1, "Не мога да запиша файла в директорията");
	strcpy(sCouldNotSaveFile2, "Може да нямате достатъчно права. Моля, проверете или променете работната директория от менюто настройки | работна директория в папка, където имате права за записване (например C:\\Temp).");
	strcpy(sCreationdateYMDHMS, "Дата на създаване (Y / M / D- H: M: S)");
	strcpy(sCurrentDate, "Текущата дата");
	strcpy(sCurrentDiagram, "Текуща диаграма");
	strcpy(sCurrentMaterial, "Настоящият материал");
	strcpy(sCurrentversion, "Сегашна версия");
	strcpy(sCurve_not_closed_Try_increasing_DXF_linking_distance_parameter, "Полигонът не е затворен! Опитайте да увеличите параметъра DXF свързващо разстояние.");
	strcpy(sCustomer, "Клиент");
	strcpy(sCustomerName, "Име на клиент");
	strcpy(sCustomMessage, "Персонализирано съобщение");
	strcpy(sCutlength, "Дължината на рязането");
	strcpy(sCut, "Разрез");
	strcpy(sCuts, "Pазрези");
	strcpy(sCutterThickness, "Дебелина на нарязване");
	strcpy(sData, "Данни");
	strcpy(sDataCannotBeEmpty, "Данните не могат да бъдат празни!");
	strcpy(sDateymdhms, "Дата (г / м / г / ч / м / сек)");
	strcpy(sDays_left_for_trial, "Оставащи дни за тестване");
	strcpy(sDaysLeft, "Оставащи дни");
	strcpy(sStandard, "По подразбиране");
	strcpy(sDefaultInterface, "Интерфейс по подразбиране");
	strcpy(sDefects, "Дефекти");
	strcpy(sDefectsManager, "Управление на дефектите");
	strcpy(sDefectsofthematerialNopiecescanbeplacedinthefaultyzone, "Дефекти на материала. Никакви детайли не могат да бъдат поставени в зоната за дефекти.");
	strcpy(sDelete, "Изтрий");
	strcpy(sDeletePiece, "Изтриване на детайл");
	strcpy(sDeleteRow, "Изтриване на реда");
	strcpy(sDemandutilization, "Използвани детайли");
	strcpy(sDepozitulmodificat, "Използваните детайли за премахнати. Останките са били добавени към склада.");
	strcpy(sDepozitvid, "Складът е празен");
	strcpy(sDesk, "Бюро");
	strcpy(sDiagram, "Диаграма");
	strcpy(sDiagrams, "Диаграми");
	strcpy(sDiagramasatable, "Диаграма като таблица");
	strcpy(sDigits, "Цифри");
	strcpy(sDimensiuniplaca, "Размер на листа");
	strcpy(sDirection, "Посока");
	strcpy(sDistanceBetweenRows, "Разстояние между редовете");
	strcpy(sDonotuseit, "Не го използвайте");
	strcpy(sDownload, "Изтегли");
	strcpy(sDoYouWantToClearTheData, "Наистина ли сте сигурни, че желаете да изтриете данните?");
	strcpy(sDoYouWantToSaveDemand, "Детайлите са променени! Желаете ли да запазите промените?");
	strcpy(sDoYouWantToSaveParts, "Искате ли да съхраните детайлите?");
	strcpy(sDoYouWantToSaveRepository, "Наличността в склада е променена! Желаете ли да запазите промените?");
	strcpy(sDrawing, "Рисунки");
	strcpy(sDrawthesolutioncolorful, "Изобрази в цвят");
	strcpy(sDuplicateTypes, "Някои видове са дублирани! Моля, премахнете дублираните.");
	strcpy(sDuplicateTypesWithComplex, "Някои имена на материали вече съществуват в списъка на сложни типове! Моля, премахнете дублираните.");
	strcpy(sDuplicateValues, "Дублирани стойности");
	strcpy(sEdgeband, "Кантове");
	strcpy(sEdgebandingwhichisplacedontheedgesofyourpiecePleasedefineedgebandingtypesfromMaterialsEdgeBandingmenu, "Кантирането е по краищата на детайла. Моля, въведете кантовете от менюто с материали..");
	strcpy(sEdgebandsthatwillbeappliedtoeachpart, "Кантовете, които ще се прилагат за всеки детйл.");
	strcpy(sEdgeBandTolerance, "Толеранс за кантиране");
	strcpy(sEdgesthatmustbecutduefaults, "Страните, които трябва да бъдат окрайчени поради дефекти.");
	strcpy(sEdgetoedge, "От край до край");
	strcpy(sEdit, "Редактирай");
	strcpy(sEmail, "имейл");
	strcpy(sEmptyData, "Няма данни!");
	strcpy(sEnabled, "Включен");
	strcpy(sEnabledisabledefectsoftheinventorysheets, "Включване / изключване на дефекти в склада");
	strcpy(sEnterLabel, "Въвеждане на етикет");
	strcpy(sEnterTheMaterialName, "Въведете името на материала");
	strcpy(sEnterTheProductName, "Въведете името на продукта");
	strcpy(sEvaluationError, "Грешка при изчисленията!");
	strcpy(sExit, "Изход");
	strcpy(sExpired, "Лицензът е изтекъл! Моля, регистрирайте софтуера!");
	strcpy(sExport, "Експорт");
	strcpy(sExportAllDiagrams, "Експортирайте всички разкрои");
	strcpy(sExportAllToASingleFile, "Експортирайте всички в един файл");
	strcpy(sExportOptions, "Опции за експорт.");
	strcpy(sExporttoDXFformat, "Експорт в DXF формат");
	strcpy(sExporttoExcel, "Експорт в Excel");
	strcpy(sExpresieIncorecta, "Неправилен математически израз!");
	strcpy(sExtensions, "Разширения");
	strcpy(sExtra, "Допълнително");
	strcpy(sExtraComponents, "Допълнителни компоненти");
	strcpy(sExtracomponentsattachedtoDemand, "Допълнителни елементи към детайлите");
	strcpy(sFile, "Файл");
	strcpy(sFileName, "Име на файла");
	strcpy(sFillWastes, "Чертане на приравнени с наклонени линии загуби");
	strcpy(sFindoptimalbarsheetsize, "Намерете оптималния размер за греди и плоскости.");
	strcpy(sFindoptimalsizeofInventorypieces, "Намерете оптималния размер на детайлите в склада");
	strcpy(sFirstcutMultiplestages, "Посока на първоначално рязане - множество стадии");
	strcpy(sFirstdirectionforcutishorizontal, "Посоката на първоначално рязане е хоризонтална.");
	strcpy(sFirstdirectionforcutisvertical, "Посоката на първоначално рязане е вертикална.");
	strcpy(sFollowthecontourofpieces, "Следвайте контура на детайла");
	strcpy(sFont, "Шрифт");
	strcpy(sFontsize, "Размер на шрифта");
	strcpy(sFullInfo, "Подробна информация");
	strcpy(sDisposedWaste, "Депонирани отпадъци");
	strcpy(sGeneral, "Общ");
	strcpy(sGenerateCNC, "Генериране на CNC");
	strcpy(sGrain, "Фладер");
	strcpy(sGraindirection, "Посока на фладера");
	strcpy(sGraphic, "Графичен");
	strcpy(sGreaterorequalto, "Голямо или равно на");
	strcpy(sGrid, "Маси");
	strcpy(sGrinding, "Надмярка");
	strcpy(sGrosimeTaieturaScalata, "Дебелина на разреза от тази картинка може да е различен от истинския, защото детайлите не са представени в истинският им размер. Този факт не се отразява на резултатите.");
	strcpy(sGroupidenticallayouts, "Групиране на еднаквите плоскости");
	strcpy(sGroupIdenticalParts, "Групиране на еднаквите детайли");
	strcpy(sGroupingOfIdenticalPiecesIntoOneRow, "Групиране на еднаквите детайли в един ред.");
	strcpy(sGroupPartsAfterLoadingFromFile, "Групиране на детайлите след зареждане от файл");
	strcpy(sHeight, "Височина");
	strcpy(sHeighttolerance, "Толеранс за височина");
	strcpy(sHelp, "Помощ");
	strcpy(sHistory, "История");
	strcpy(sHorizontal, "Хоризонтален");
	strcpy(sHowtodisplayprintedgebands, "Как да се изобразяват кантовете?");
	strcpy(sIfyousetthebandforoneedgeallwillreceivethesamevalue, "Ако зададете канта на едната страна, всички останали страни ще се кантират с този кант.");
	strcpy(sIfyousetthegrindingforoneedgeallwillreceivethesamevalue, "Ако зададете надмярка на едната страна, всички останали страни ще имат същата надмярка.");
	strcpy(sIfyousetthetrimforoneedgeallwillreceivethesamevalue, "Ако зададете окрайчване на едната страна, всички останали страни също ще се окрайчат.");
	strcpy(sImageBounds, "Граници на изображението");
	strcpy(sImageSize, "Размер на изображението.");
	strcpy(sImportData, "Импортиране на данните.");
	strcpy(sIncorrectPassword, "Грешна парола");
	strcpy(sIndex, "Индекс");
	strcpy(sInformationaboutcustomer, "Информация за клиента");
	strcpy(sInputALanguageName, "Посочете език");
	strcpy(sInsert, "Поставете");
	strcpy(sInsertPiece, "Вмъкнете детайл");
	strcpy(sInterface, "Интерфейс");
	strcpy(sInterfaceSettings, "Настройки на интерфейса");
	strcpy(sInvalidHardware, "Не може да се открие хардуера. Моля, свържете се с нас contact@optimalprograms.com");
	strcpy(sInvalidNumber, "Невалиден номер");
	strcpy(sInvalidOrderOfComputation, "Заявка за изчисляване на дължините не може да бъде установена. Има кръгови връзки в определението на продукта!");
	strcpy(sInvalidRegistration, "Регистрацията е невалидна!");
	strcpy(sInvalidTime, "Времето на вашата система е невалидно.");
	strcpy(sInventory, "НАЛИЧНОСТ");
	strcpy(sisafractionalvalue, "е относителна стойност.");
	strcpy(sIsArc, "Има дъга");
	strcpy(sisarealvalue, "е реална стойност.");
	strcpy(sLabel, "Етикет");
	strcpy(sLabels, "Етикети");
	strcpy(sLanguage, "Език");
	strcpy(sLatimeanumar0, "Ширината трябва да бъде по-голяма от 0!");
	strcpy(sLatimeanumarreal, "Ширината трябва да е реално число!");
	strcpy(sLayerName, "Име на слой");
	strcpy(sLeft, "Ляво");
	strcpy(sLeftcoordinateofthedefect, "Лявата координата на дефекта");
	strcpy(sLength, "Дължина");
	strcpy(sLengthofthepiecestocut, "Размерът за рязане на частта");
	strcpy(sLengthofthepiecestocutfrom, "Размерът за рязане на листа");
	strcpy(sLengthofusedbars, "Размер на използваните барове");
	strcpy(sLicenseAgreement, "Лицензно споразумение");
	strcpy(sLinear, "Линеен");
	strcpy(sLinethickness, "Дебелина на контура");
	strcpy(sLoadafileandappenddatatothecurrentDemand, "Заредете файл и го добавете към моментното търсене.");
	strcpy(sLoadanexistingDemandfromafile, "заредете съществуващото търсене от файл.");
	strcpy(sLoadAppend, "Заредете и прикрепете");
	strcpy(sLoadEverything, "заредете всичко");
	strcpy(sLoadInventory, "Заредете наличност");
	strcpy(sLoadInventoryandDemand, "Заредете наличността, както и търсенето");
	strcpy(sLoadResults, "Заредете резултатите");
	strcpy(sLocked, "заключен");
	strcpy(sLogo, "лого");
	strcpy(sLong, "Дълго");
	strcpy(sLongerexecutiontime, "По-дълъг срок за изпълнение");
	strcpy(sLungime, "Широчина");
	strcpy(sLungimeanumar0, "Дължината трябва да бъде по-голяма от 0!");
	strcpy(sLungimeanumarreal, "Дължината трябва да е реално число!");
	strcpy(sLungimeaTotalaFolosita, "Цялата използвана дължина");
	strcpy(sMagnification, "Увеличение");
	strcpy(sMagnify, "Увеличавам");
	strcpy(sMargins, "предели");
	strcpy(sMarginsForPaper, "предели за хартия");
	strcpy(sMarginsOfTheLabel, "Предели за етикета");
	strcpy(sMaterial, "Материал");
	strcpy(sMaterialName, "Име на материала");
	strcpy(sMaterials, "материали");
	strcpy(sMaterialstypes, "Видове материали");
	strcpy(sMax, "максимално");
	strcpy(sMaximalArea, "Максимална площ");
	strcpy(sMaximalCutLength, "Максимална отрязана дължина");
	strcpy(sMaxlength, "Максимална дължина");
	strcpy(sMaxPiecesperBar, "Макс брои на парче");
	strcpy(sMaxwidth, "Максимална ширина.");
	strcpy(sMeasurementUnit, "Измервателна единица");
	strcpy(sMin, "минимално");
	strcpy(sMinimalBreakSize, "Минимален размер на скъсване");
	strcpy(sMinimalUsefulSize, "минимална полезна площ");
	strcpy(sMinimalwastesizetoInventory, "Минимален размер на отпадъци към инвентара");
	strcpy(s_What_to_minimize, "Какво да сведем до минимум?");
	strcpy(sMinlength, "Минимална дължина на");
	strcpy(sMinwidth, "Минимална ширина");
	strcpy(sMirror, "Огледало");
	strcpy(sMirroring, "отразяване");
	strcpy(sMiscellaneous, "Разни");
	strcpy(sModify, "Промени");
	strcpy(sModifytheselectedpiece, "Променете избраното парче");
	strcpy(sMovePiece, "Преместете парче.");
	strcpy(sMultiplestages, "Множество етапи");
	strcpy(sName, "Име");
	strcpy(sNameofedgeband, "Име на крайните кантове");
	strcpy(sNewDEMANDUnsaveddatawillbelost, "Нови детайли? Незапазените данни ще бъдат загубени!");
	strcpy(sNewLanguage, "Нов език");
	strcpy(sNewMaterial, "Нов материал");
	strcpy(sNewPasswordincorectlyintroduced, "Новата парола е неправилно въведена!");
	strcpy(sNewProduct, "Нов продукт");
	strcpy(sNewversion, "Нова версия");
	strcpy(sNo, "Не");
	strcpy(sNumarBucati, "Брой детайли");
	strcpy(sNumberOfCopies, "Брой копия");
	strcpy(sNumberofstages, "Брой на етапите");
	strcpy(sNusuficienteplacidepozit, "Не всички детайли са разкроени. Възможни причини: Няма достатъчно материали)");
	strcpy(sOfficeNotInstaled, "Microsoft Office не е инсталиран на компютъра ви или има инсталирана неподържана версия!");
	strcpy(sOldpassworddoesnotmatch, "Старата парола не съвпада!");
	strcpy(sOnlinehelp, "Онлайн помощ");
	strcpy(sOnlypiecesofthesameheightinthelaststage, "Парчета от една и съща височина в последния етап");
	strcpy(sOpen, "Отвори");
	strcpy(sOptimization, "Оптимизация");
	strcpy(sOptimizationDone, "Оптимизацията е извършена! Можете да отпечатате или да запазите получените диаграми. Натиснете бутона приеми, ако сте доволни от настоящото решение. В противен случай натиснете бутона за започване отначало.");
	strcpy(sOptimizationType, "Тип Оптимизация");
	strcpy(sOptions, "Настроики");
	strcpy(sOptionsrelatedtotheinterface, "Опции, свързани с интерфейса");
	strcpy(sor, "или");
	strcpy(sOthercomponents, "Други компоненти");
	strcpy(sOthers, "Други");
	strcpy(sOtherstatistics, "Други статистически данни");
	strcpy(sOverrideExcelCSVfiles, "презапиши на Excel / CSV файлове");
	strcpy(sParameter, "Параметър");
	strcpy(sParts, "ДЕТАЙЛИ");
	strcpy(sPattern, "Щриховка");
	strcpy(sPatternforwaste, "Щриховка за отпадъка");
	strcpy(sPerimeter, "Периметър");
	strcpy(sPermitedRotationAngle, "Ъгъл на въртене, който е позволен");
	strcpy(sPhone, "Телефон");
	strcpy(sPicture, "Изображение");
	strcpy(sPiece, "Детайл");
	strcpy(sPieceindex, "Индекс на детайла");
	strcpy(sPieces, "Детайли");
	strcpy(sPiecesize, "Размери на детайла");
	strcpy(sPiecesizelabeledgebandwillbeprinted, "Размера на детайла, името и кантовете ще бъдат отпечатани.");
	strcpy(sPierdere, "Отпадък");
	strcpy(sPixels, "Пиксели");
	strcpy(sPlacilefolositeDepozit, "Взети плоскости от склада.");
	strcpy(sPlease_contact_us_at_contact_nestingtechnologies_com, "Моля, свържете се с нас на contact@nesting-technologies.com");
	strcpy(sPlease_contact_us_at_contact_optimalprograms_com, "Моля, свържете се с нас на contact@optimalprograms.com");
	strcpy(sPleaseenteralldataeitherasfractionalorrealDonotmixthem, "Моля, въведете всички данни като дробни или реални! Моля, не ги смесвайте!");
	strcpy(sPleaseEnterSomeTypesOfMaterials, "Не е определен вида материал. Можете да ги определят от менюто с материалите.");
	strcpy(sPleasesendtheNameandtheCodetotheaddresscontactoptimalprogramscominordertoobtaintheRegistrationKey, "С цел получаване на регистрационен ключ, моля изпратете името и кода: contact@optimalprograms.com.");
	strcpy(sPolygon, "Многоъгълник");
	strcpy(sPolygonsCircles, "Полигони, кръгове");
	strcpy(sPrecision, "Точност");
	strcpy(sPretulnumar0, "Цената трябва да бъде по-голяма от 0!");
	strcpy(sPretulnumarreal, "Цената трябва да е реално число!");
	strcpy(sPreview, "Визуализация и предварителен преглед");
	strcpy(sPrice, "Цена");
	strcpy(sPriceMustBeGreaterThanZero, "Цената трябва да бъде по-голяма от нула");
	strcpy(sPriceofbars, "Цена на парчета");
	strcpy(sPriceperbar, "Цена на парче");
	strcpy(sPricepersheet, "Цена на лист");
	strcpy(sPricepersquareunitofmaterial, "Цена на квадратна единица от материал.");
	strcpy(sPriceperunit, "Цена за единица");
	strcpy(sPrint, "Печат");
	strcpy(sPrintdiagramsastables, "Отпечатай диаграмите във вид на таблици.");
	strcpy(sPrinter, "принтер");
	strcpy(sPrinterBounds, "предели за принтер");
	strcpy(sPrinting, "печатане");
	strcpy(sPrintonlyutilizedarea, "Печат само на използваната площ");
	strcpy(sPrintthecontentsoftheDemand, "Печат на съдържанието на търсене.");
	strcpy(sPrintthecontentsoftheInventory, "Печат на съдържанието на наличността.");
	strcpy(sPrintthecurrentsolution, "Печат на текущото решение.");
	strcpy(sPriority, "Приоритет");
	strcpy(sPrioritytocutapieceZero0isthehighestpriority, "Приоритет на отрежете парче. Нула (0) е най-висок приоритет.");
	strcpy(sProcentul0100, "Процентите трябва да бъдат по-големи от 0 и по-малко или равни на 100!");
	strcpy(sProcentulnumarreal, "Процентите трябва да са реално число!");
	strcpy(sProductdefinition, "Дефиниция на продукта");
	strcpy(sProductExists, "Продуктът вече съществува. Изберете друго име.");
	strcpy(sProductName, "Име на продукта");
	strcpy(sProducts, "Продукт");
	strcpy(sProducts, "Продукти");
	strcpy(sProject, "проект");
	strcpy(sProperties, "Имоти");
	strcpy(sProperty, "имот");
	strcpy(sQuantity, "Количество");
	strcpy(sQuantitynumberofsheetsofthistype, "Брой на листове от този тип");
	strcpy(sRadius, "Радиус");
	strcpy(sRectangular, "Правоъгълен");
	strcpy(sRedefinetypesofedgeband, "Повторно дефиниране на вида на границата на лентата");
	strcpy(sRedefinetypesofmaterial, "Повторно дефиниране на видовете материали");
	strcpy(sRegistration, "Регистрация");
	strcpy(sRegistrationKeyfromOptimalPrograms, "Регистрационен ключ");
	strcpy(sRegistrationSuccessful, "Регистрацията беше успешна!");
	strcpy(sRemoveallpiecesinInventory, "Отмяна на всички парчета в инвентара.");
	strcpy(sRemoveCut, "Изтрий нарязаните");
	strcpy(sRemovetheselectedpiece, "Премахване на избраното парче");
	strcpy(sReports, "отчети");
	strcpy(sRequestedMaterial, "Изисквания материал");
	strcpy(sRestore, "възстанови");
	strcpy(sResults, "Резултати");
	strcpy(sReusedwaste, "Повторно използвани отпадъци");
	strcpy(sRight, "Право");
	strcpy(sRightcoordinateofthedefect, "Координати на дефект от дясно");
	strcpy(sRotation, "Въртене");
	strcpy(sRotationAngle, "Ъгъл на въртене");
	strcpy(sRotationStep, "въртене стъпка.");
	strcpy(sRoundAllFractionsTo, "Фракционните стойностите трябва да бъдат закръглени до");
	strcpy(sRow, "ред");
	strcpy(sRows, "Редове");
	strcpy(sRun, "Най-новите решения");
	strcpy(sRunningtime, "времето за работа");
	strcpy(sSameforall, "Същото важи и за всички");
	strcpy(sSave, "съхрани");
	strcpy(sSaveAllImages, "запази всички изображения");
	strcpy(sSaveAs, "Запази като");
	strcpy(sSaveChanges, "Търсенето е било променено. Искате ли да го съхраните?");
	strcpy(sSaveCurrentImage, "Запазване на текущото изображение");
	strcpy(sSavedataparameters, "Запазване на данни и параметри");
	strcpy(sSaveEverything, "Запишете всичко");
	strcpy(sSaveInventory, "Запази инвентар");
	strcpy(sSaveInventoryandDemand, "Запази инвентара и търсенето");
	strcpy(sSaveResults, "Запази резултати");
	strcpy(sSaveStatisticsinafile, "Запази статистика във файл");
	strcpy(sSavethecurrentimage, "Запазване на текущото изображение");
	strcpy(sSavethecurrentimageorstatistic, "Запазване на текущото изображение или статистика");
	strcpy(sSavetheDEMANDinafile, "Съхрани във файл");
	strcpy(sSavetheDemandinafilewithadifferentname, "Запази търсенето във файл с друго име.");
	strcpy(sSavetheREPOSITORYinafile, "Запазване на хранилището във файл");
	strcpy(sSerialNumber, "Регистрационен ключ");
	strcpy(sService, "Услуга");
	strcpy(sSetDefaultValues, "Това ще възстанови всички параметри на техните стойности по подразбиране. Всички ваши настройки ще бъдат загубени. Сигурни ли сте че искате да направите това?");
	strcpy(sSetedgeband, "Определете кантоване на ръба");
	strcpy(sSetedgetrim, "Посочете рязането на дефекти на ръбове");
	strcpy(sSetthesameedgebandforalledges, "Определете същата честотна лента за всички ръбове");
	strcpy(sSetthesamegrindingforalledges, "Задайте същото шлифоване на всички ръбове");
	strcpy(sSetthesametrimforalledges, "Задайте същото рязане на дефекти за всички ръбове");
	strcpy(sSettings, "Настройки");
	strcpy(sShape, "Оформете");
	strcpy(sSheet, "Лист");
	strcpy(sSheetsBarstypes, "листа_видове части");
	strcpy(sSheetSize, "Размер на листа");
	strcpy(sSheetsperPage, "Брои листове на страница");
	strcpy(sShort, "Кратко");
	strcpy(sShorterexecutiontime, "Кратко време на работа");
	strcpy(sShowallsimpleproducts, "Покажи всички прости продукти");
	strcpy(sShowcustomername, "Покажи името на клиента");
	strcpy(sShowCustomTextOnEachPiece, "Покажи текста на поръчката върху всяко парче");
	strcpy(sShowdiagramasatable, "Покажи диаграма и таблица.");
	strcpy(sShowedgeband, "Покажи крайните ленти");
	strcpy(sShowedgebandssettinginanewwindow, "Покажи настройките на крайните групи в нов прозорец");
	strcpy(sShowgrindingsettingsinanewwindow, "Покажи настройките за шлифоване в нов прозорец");
	strcpy(sShowHorizontalLabelsAlways, "Покажи винаги хоризонтални етикети");
	strcpy(sShowRemovethesizeofthepiecesinthecurrentsolution, "Покажи / отстрани размера на парчетата в текущото решение.");
	strcpy(sShowRemovethesizeofthewastesinthecurrentsolution, "Покажи / отстрани размера на загубите в текущото решение.");
	strcpy(sShowtotalcutlength, "Покажи общата дължина на рязане");
	strcpy(sShowtrimedgesettingsinanewwindow, "Покажи настройките на дефекти в нов прозорец");
	strcpy(sSimpleMaterialExists, "Име на материала, който вече е определен в списъка на суровините. Моля, дайте го с ново име.");
	strcpy(sSinglePieceStrips, "райета на едно парче");
	strcpy(sSizes, "Размери");
	strcpy(sSmallerorequalto, "По-малък или равен на");
	strcpy(sSort, "Вид");
	strcpy(sSortAscendingByArea, "Възходящ ред по област");
	strcpy(sSortDescendingByArea, "В низходящ ред по област");
	strcpy(sSpecifyhowdifferentthepiecesinthelaststagecanbeValue0meansnodifference, "Посочете колко различни могат да бъдат парчетата в последния етап. Стойност 0 означава, че няма разлика., ");
	strcpy(sSpecifyifpiecesinthelaststagecanbedifferentornotdepeultimaetapapotfidiferitesaunucadimensiune, "Посочете, ако броя в последния етап може да бъде различно или не");
	strcpy(sSpecifyifthepiececanberotatedornotIfnotitwillbecutinthesamewayasitwasintroducedinDemandLengthofthepieceparalleltothelengthofthesheet, "Посочете, ако парчето може да се върти или не. Ако не, ще бъдат намалени по същия начин, както бяха въведени в търсенето (дължината на парче успоредно с дължината на листа), ");
	strcpy(sSpecifyinhowmanystageswemakethecutsDuringastageallcutshavethesamedirection, "Посочете в колко етапи ние да направим рязането.");
	strcpy(sStartthesearchprocess, "Стартирайте процеса на търсене");
	strcpy(sStatistics, "Статистика");
	strcpy(sStatisticsE, "Отчети екстра");
	strcpy(sStatisticsforeachtypeofmaterial, "Статистика за всеки вид материал");
	strcpy(sStep, "Стъпка");
	strcpy(sStergeDepozit, "Наистина ли желаете да изтриете етикетирането?");
	strcpy(sStergeMaterial, "Наистина ли желаете да изтриите материала?");
	strcpy(sStergePiesele, "Наистина ли желаете да изтриете това парче?");
	strcpy(sStergePiesa, "Наистина ли желаете да изтриете това парче?");
	strcpy(sStopthesearchprocess, "Прекратява се процеса на търсене");
	strcpy(sStrongoptimization, "Силна оптимизация");
	strcpy(sSubtractthebandthicknessfrompiecesize, "Намаляване на размера парче с дебелина ленти");
	strcpy(sSummary, "Обобщение");
	strcpy(sSuprafataTotalaFolosita, "Общо използвана повърхност");
	strcpy(sSuprafatautilizata, "Оползотворяване");
	strcpy(sSwitchbetweenfiberandrotationoption, "Превключване между влакна и опция въртене.");
	strcpy(sTechnical, "Технически");
	strcpy(sTechnicalsettings, "Технически настройки");
	strcpy(sTemporaryPanelHint, "Временен панел за движещите се части между листовете.");
	strcpy(sText, "Текст");
	strcpy(sThe_application_has_expired, "Програмата е с изтекъл срок.");
	strcpy(sThe_application_is_not_registered, "Софтуерът не е регистриран.");
	strcpy(sThe_application_was_first_started_on, "Софтуерът първо се започва на.");
	strcpy(sThecutsareperformedfromasidetotheothersideofthematerial, "Дебитирането се извършва от страна на другата страна на материала.");
	strcpy(sThecuttingmachinecanfollowtheshapeofthematerial, "Машината за рязане може да следват формата на парчето.");
	strcpy(sTheedgesofsheetsthatmustbetrimedduefaults, "Ръбовете на листовете, които трябва да се почистват, защото има грешки");
	strcpy(sTheLargestSize, "Най-големият размер.");
	strcpy(sThenameofthecustomerforwhichyoucutthepiece, "Името на клиента, за когото ще направите рязането на парче.");
	strcpy(sThenameofyourcustomer, "Името на вашия клиент");
	strcpy(sThepiececanberotated, "Парчето може да се върти");
	strcpy(sTheprogramtriestoavoidwasteswhichhavebothsizeslessthanthisvalue, "Програмата се опитва да избегне загуби, които от двата размера са по-малки от тази стойност");
	strcpy(sThereAreNoProducts, "Не са открити продукти, които още не са определени");
	strcpy(sThestockofmaterialhasbeenpreviouslyloadedfromanExcelorCSVformatPleaseloaditagain, "Книжата на материал е бил предварително зареден от Excel или CSV формат. Моля, да го заредите отново, ако искате да работите върху него.");
	strcpy(sThetotallengthofcutting, "Общата дължина на рязане");
	strcpy(sThewidthofthecuttingsawForglasscuttingoptimizationitcanbe0Forwooditshouldbegreaterthan0, "Дебелината на триона. За рязане на стъкло може да бъде 0. За дървен материал трябва да бъде по-голяма от 0.");
	strcpy(sThewidthofthecuttingsawforlinearpieces, "Дебелината на триона за линейни парчета.");
	strcpy(sThickness, "Дебелина");
	strcpy(sThischaracterisusedforfillingthewasterectanglesIfyoudonotwantfilledwastejustremovethischaracter, "Този символ се използва за запълване на правоъгълниците със загуби. Ако не искате пълни отпадъци просто го премахнете.");
	strcpy(sThisindexhasvaluebetween1andthenumberofpieces, "Този индекс има стойност между 1 и броя на парчетата.");
	strcpy(sThisOptionWillOverrideTheInventoryFileIfLoadedFromExcelOrCsvFiles, "Тази опция ще замени файла инвентар, ако зарежда от Excel или CSV файлове.");
	strcpy(sThisProgramisLicensedTo, "Тази програма е лицензирана за");
	strcpy(sThisvaluewillbeaddedtotheedgebandingmaterialoneachside, "Тази стойност ще бъде добавена към кантиране на материал от всяка страна");
	strcpy(sTipNevid, "Полето за вид на материала не може да бъде празно.");
	strcpy(sTitle, "Дял");
	strcpy(sTools, "Инструменти");
	strcpy(sTop, "Най-горната част(връх)");
	strcpy(sTopcoordinateofthedefect, "Най-горната координата на дефекта.");
	strcpy(sTotalGarbageWaste, "Всички изхвърлени загуби");
	strcpy(sTotalInventoryWaste, "Общо наличност отпадъци");
	strcpy(sTotalRecycledWaste, "Всички рециклирани загуби");
	strcpy(sTotalusedarea, "Общо използвана площ");
	strcpy(sTotalusedlength, "Общо използвана дължина");
	strcpy(sTrigonometric, "Тригонометрична");
	strcpy(sTrim, "изрежи");
	strcpy(sTrimalledgesatthebeginning, "Изрежете всички краища в началото");
	strcpy(sTrimEdge, "Подстригване на ръба");
	strcpy(sTwoPanels, "2 панела");
	strcpy(sType, "тип");
	strcpy(sTypeofmaterialfromwhichtocut, "Вид на материала, от който да се изрежат");
	strcpy(sTypesAreNotMatched, "Оптимизацията не е извършена! Материалите от таблиците „Части“ и „Наличност“ не съвпадат! Може да се изреже детайл само от материал със същото име на склад. Променете името на материалите от съответните колони!");
	strcpy(sUndo, "Върни обратно");
	strcpy(sUndoAccept, "Отмени приемането");
	strcpy(sUnits, "единици");
	strcpy(sUnregisteredVersion, "Нерегистриран");
	strcpy(sUpdates, "Обновить");
	strcpy(sUsefulforwoodfurniture, "Полезно за дървени мебели");
	strcpy(sUseit, "Използвайте го");
	strcpy(sUsePieceinOptimization, "Използвайте парче в оптимизация");
	strcpy(sUserName, "Потребителско име");
	strcpy(sUtilizationandWastes, "Рециклиране и загуби");
	strcpy(sUtilizedArea, "Площ на използваните части");
	strcpy(sUtilizedBars, "Усвоени части");
	strcpy(sUtilizeddemandcount, "Брой на използваните парчета");
	strcpy(sUtilizedParts, "Усвоени части");
	strcpy(sUtilizedPieces, "Използвано парчета");
	strcpy(sUtilizedSheets, "Усвоени листове");
	strcpy(sValue, "Стойност");
	strcpy(sValueGreaterEqualToZero, "Стойността трябва да е по-голямо или равна на нула");
	strcpy(sValueGreaterThanZero, "Стойността трябва да е по-голяма от нула");
	strcpy(sValueIntegerNumber, "Стойността трябва да е цяло число!");
	strcpy(sValueRealNumber, "Стойността трябва да е реално число. Може би сте използвали, вместо. или ОБРАТНО. Моля, поправете го!");
	strcpy(s_The_number_is_too_big_or_it_has_too_many_digits_after_decimal_separator, "Числото е твърде голямо или има твърде много цифри след десетичен разделител!");
	strcpy(s_The_number_is_too_big, "Броят е твърде голям!");
	strcpy(sVertical, "Вертикален");
	strcpy(sWaste, "загуби");
	strcpy(sWastes, "загуби");
	strcpy(sWasteAddedToWarehouse, "Скрап добавена в склада");
	strcpy(sWastelimits, "Срокове за загуби");
	strcpy(sWasteType, "Тип на загубите");
	strcpy(sWeakoptimization, "Най-слабата оптимизация");
	strcpy(sWhattoprint, "Какво трябва да отпечатате");
	strcpy(s_What_to_print_or_save_to_file, "Какво да отпечатате или запишете във файл");
	strcpy(sWhattoprintoneachpiece, "Какво да се отпечата на всяка част");
	strcpy(sWhattoshowoneachpiece, "Какво да се показва на всяко парче?");
	strcpy(sWidth, "Широчина");
	strcpy(sWood, "дърво");
	strcpy(sWorkingDirectory, "Работната директория");
	strcpy(sWrongKey, "грешен регистрационен ключ!");
	strcpy(sYes, "Да");
	strcpy(sYoucannotchooseblackblueorredcolors, "You cannot choose black, blue or red colors.");
	strcpy(sYouCannotMixFractionalDataWithDecimalOnes, "Не можете да смесвате дробни стойности с реалните стойности!");
	strcpy(sYourcompany, "Вашата фирма");
	strcpy(sZip, "Пощенски код");
	strcpy(s_Set_the_origin_and_the_direction_of_the_axes, "Задайте началото и посоката на координатните оси.");










	strcpy(s_Number_of_digits_after_the_decimal_separator, "Брой цифри след десетичния разделител");
	strcpy(s_Percentages, "Проценти");
}
