// Language strings: English
// Author: Optimal Programs
// License: MIT License
//---------------------------------------------------------------------------
#include <string.h>
//---------------------------------------------------------------------------
#include "language_string_id.h"
//---------------------------------------------------------------------------
void set_en(void)
{
	//English 
	//checked manually
	//2025.4.19.0
	strcpy(s_Advanced, "Advanced");
	strcpy(s_Relative_coordinates, "Relative coordinates");
	strcpy(s_Absolute_coordinates, "Absolute coordinates");
	strcpy(s_Append_more_rows, "Append more rows");
	strcpy(s_Append_to_stock, "Append to stock");
	strcpy(s_Add_to_parts, "Append to parts");
	strcpy(s_Additional, "Additional");
	strcpy(s_All_results, "All results.");
	strcpy(s_Allow_movement_of_pieces, "Allow movement of pieces");
	strcpy(s_Allow_part_in_part, "Allow part in part");
	strcpy(s_Invalid_piece_Angles_are_too_small_or_too_big_or_height_is_too_small, "Invalid piece! Angles are too small or too big, or the height is too small.");
	strcpy(s_Append, "Append");
	strcpy(s_As_it_is, "As it is");
	strcpy(s_As_text, "As text");
	strcpy(s_Ascending, "Ascending");
	strcpy(s_Automatic, "Automatic");
	strcpy(s_Cannot_connect_to_the_Internet_Please_visit_our_website_from_a_browser, "Cannot connect to the Internet! Please visit our website from a browser.");
	strcpy(s_Cannot_copy_or_move_the_files, "Cannot copy or move the files!");
	strcpy(s_Cannot_delete_the_file, "Cannot delete the file!");
	strcpy(s_Cannot_modify_old_results, "Cannot modify old results!");
	strcpy(s_To_change_click_inside_a_cell_or_press_0_1_or_2, "To change, click inside a cell or press 0, 1, or 2.");
	strcpy(s_Cell, "Cell");
	strcpy(s_Click_on_the_table_header_to_change_the_columns, "Click on the table header to change the columns.");
	strcpy(s_Close, "Close");
	strcpy(s_Contact_us, "Contact us");
	strcpy(s_Column, "Column");
	strcpy(s_Comma, "Comma");
	strcpy(s_The_comma_symbol_cannot_simultaneously_be_the_list_separator_and_the_decimal_separator, "The comma symbol cannot simultaneously be the list separator and the decimal separator!");
	strcpy(s_Copy, "Copy");
	strcpy(s_Copy_for_move, "Copy for move");
	strcpy(s_Cut_higher_level_strips_first, "Cut higher-level strips first");
	strcpy(s_Cut_index, "Cut index");
	strcpy(s_Cuts_may_overlap, "Cuts may overlap");
	strcpy(s_The_data_have_been_changed_Do_you_want_to_save_them_to_a_file, "The data have been changed. Do you want to save them to a file?");
	strcpy(s_Decimal_separator, "Decimal separator");
	strcpy(s_Restore_default_settings, "Restore default settings");
	strcpy(s_Delete_fiber, "Delete fiber");
	strcpy(s_Descending, "Descending");
	strcpy(s_Discard_changes, "Discard changes");
	strcpy(s_default_value, "Default value");
	strcpy(s_Delete_all_data, "Delete all data?");
	strcpy(s_Dot, "Dot");
	strcpy(s_Do_you_want_to_delete_the_picture, "Do you want to delete the picture?");
	strcpy(s_Do_you_want_to_delete_the_product, "Do you want to delete the product?");
	strcpy(s_Duplicate_and_append, "Duplicate and append");
	strcpy(s_Duplicate_values_are_ignored, "Duplicate values are ignored!");
	strcpy(s_Error, "Error");
	strcpy(s_Error_loading_file, "Error loading file.");
	strcpy(s_export_everything, "Export everything");
	strcpy(s_Fit_to_screen, "Fit to screen");
	strcpy(s_Force_fixed_height, "Draw the pieces with a fixed height.");
	strcpy(s_Flipped, "Flipped");
	strcpy(s_Import, "Import");
	strcpy(s_If_angles_are_different_from_90_degrees_height_must_be_greater_than_0, "If angles are different from 90 degrees, height must be greater than 0.");
	strcpy(s_Ignore, "Ignore");
	strcpy(s_Incorrect_value, "Incorrect value");
	strcpy(s_Info, "Info");
	strcpy(s_Interior, "Interior");
	strcpy(s_Give_a_name, "Assign a name.");
	strcpy(s_Group, "Group it");
	strcpy(s_Header, "Header");
	strcpy(s_Keep_it_as_it_is, "Keep it as it is");
	strcpy(s_Level, "Level");
	strcpy(s_Licensee, "Licensee");
	strcpy(s_List_separator, "List separator");
	strcpy(s_Made_with_love_in_Cugir_Romania, "Made, with love, in Cugir, Romania");
	strcpy(s_Made_in, "Made in");
	strcpy(s_Manufacturer, "Manufacturer");
	strcpy(s_Maximum_distance_between_2_linked_segments, "Maximum distance between 2 connected segments");
	strcpy(s_Manual_arrange, "Manual arrange");
	strcpy(s_Mix_layers, "Consider entities from all layers");
	strcpy(s_Mixed, "Mixed");
	strcpy(s_Multiple_shapes_detected_Next_rows_will_be_overwritten_Continue, "More than one shape was detected. Therefore, the subsequent rows will be overwritten. Continue?");
	strcpy(s_More, "More");
	strcpy(s_Multiple_values, "Multiple values");
	strcpy(s_No_texture, "No Texture");
	strcpy(s_Number, "Number");
	strcpy(s_Number_of_images, "Number of images");
	strcpy(s_Number_of_vertices, "Number of vertices");
	strcpy(s_Offset, "Offset");
	strcpy(s_Only_the_currently_selected_items, "Only the currently selected items.");
	strcpy(s_Optimizing_please_wait, "Optimizing ... please wait.");
	strcpy(s_part_number, "Part Number");
	strcpy(s_Paste, "Paste");
	strcpy(s_Paste_from_Clipboard, "Paste from Clipboard");
	strcpy(s_Piece_label, "Piece's label");
	strcpy(s_Piece_size, "Piece's size");
	strcpy(s_Please_contact_us_by_email_if_you_receive_this_error, "Please contact us by email if you receive this error.");
	strcpy(s_Please_save_it_first, "Please, save it first.");
	strcpy(s_Position, "Position");
	strcpy(s_Preview, "Preview");
	strcpy(s_Rectangle, "Rectangle");
	strcpy(s_Resolution, "Resolution");
	strcpy(s_Redo_the_last_operation, "Redo the last operation");
	strcpy(s_Regular_polygon, "Regular polygon");
	strcpy(s_Relative, "Relative");
	strcpy(s_Reused, "Reused");
	strcpy(s_Rotated, "Rotated");
	strcpy(s_Save_all, "Save all");
	strcpy(s_Scrap_label, "Waste's label");
	strcpy(s_Scrap_size, "Waste's size");
	strcpy(s_Semicolon, "Semicolon");
	strcpy(s_Show_cut_index, "Show cut's index");
	strcpy(s_Show_information, "Show info");
	strcpy(s_Show_piece_label, "Show piece's label");
	strcpy(s_Show_scrap_label, "Show waste's label");
	strcpy(s_Show_scrap_s_size_on_the_small_pieces, "Show waste's size on the small pieces");
	strcpy(s_Show_size_of_pieces, "Show piece's size");
	strcpy(s_Show_size_of_scrap, "Show waste's size");
	strcpy(s_Show_sizes, "Show sizes");
	strcpy(s_Show_label, "Show label");
	strcpy(s_Show_length, "Show length");
	strcpy(s_Space, "Space");
	strcpy(s_Some_numerical_values_are_incorrect_Should_I_fix_all_the_incorrect_values, "Some numerical values are incorrect! Should I fix all the incorrect values?");
	strcpy(s_Some_invalid_values_have_been_removed, "Some invalid values have been removed.");
	strcpy(s_Sort_by, "Sort by");
	strcpy(s_Sort_ascending_by, "Sort ascending by");
	strcpy(s_Sort_descending_by, "Sort descending by");
	strcpy(s_Start, "Start");
	strcpy(s_Starting_angle, "Starting angle");
	strcpy(s_Starting_corner, "Starting corner");
	strcpy(s_Starting_direction, "Starting direction");
	strcpy(s_Stock, "Stock");
	strcpy(s_Stop, "Stop");
	strcpy(s_System_setting, "System setting");
	strcpy(s_Tabular, "Tabular");
	strcpy(s_Total, "Total");
	strcpy(s_Total_size, "Total size");
	strcpy(s_Terms_of_the_license, "Terms of the license");
	strcpy(s_The_current_product_has_been_changed_Do_you_want_to_save_it_to_file, "The current product has been changed. Do you want to save it to a file?");
	strcpy(s_The_value_is_out_of_the_allowed_range, "The value is out of the allowed range.");
	strcpy(s_The_value_must_be_a_real_or_fractional_number_Try_to_replace_the_comma_with_the_dot_if_you_want_to_enter_a_real_number, "The value must be a real or fractional number. Try to replace the comma with the dot if you want to enter a real number.");
	strcpy(s_This_feature_is_not_implemented_yet, "This function is not implemented yet.");
	strcpy(s_This_operation_cannot_be_reversed, "This operation cannot be reversed.");
	strcpy(s_Undo_the_last_operation, "Undo the last operation");
	strcpy(s_Utilization, "Utilization");
	strcpy(s_Utilized_Stock, "Utilized Stock");
	strcpy(s_Version, "Version");
	strcpy(s_Visible_columns, "Visible columns");
	strcpy(s_You_already_have_the_latest_version_installed, "You already have the latest version installed!");
	strcpy(s_What_is_exported, "What is exported?");
	strcpy(s0meansanynumberofpieces, "Zero means any number of pieces");
	strcpy(sAbout, "About");
	strcpy(sAccept, "Accept");
	strcpy(sAcceptall, "Accept all");
	strcpy(sAcceptthecurrentsolution, "Accept the current solution");
	strcpy(sAdd, "Append");
	strcpy(sAddapiece, "Add a piece");
	strcpy(sAddasimpleproducttoDemand, "Add a product to the existing parts.");
	strcpy(sAddgrindingthicknesstopartsize, "Add grinding thickness to piece size");
	strcpy(sAddproductnametolabel, "Append product name to label");
	strcpy(sAddress, "Address");
	strcpy(sAddselectedsizetoInventory, "Append selected size to stock");
	strcpy(sAdhesivelabels, "Adhesive labels");
	strcpy(sAdhesivelabelwithinformationaboutpiecesinDemandCustomernameLabelSizeCurrentData, "Adhesive label with information about pieces: Customer name, Label, Size, Current Data etc.");
	strcpy(sAdhesivelabelwithinformationaboutsheetsinInventory, "Adhesive labels with information about sheets in stock.");
	strcpy(sAll, "All");
	strcpy(sAlloffcutswhichhavethesizegreaterthanthisvaluewillbeaddedtoInventory, "All waste greater than this value will be added to stock");
	strcpy(sAllowMirroring, "Allow flipping");
	strcpy(sAllowRotation, "Allow rotation");
	strcpy(sAllPieces, "All pieces");
	strcpy(sAllpredefinedproducts, "All predefined products");
	strcpy(sAnewwindowwillbedisplayedwheretheusercansettheedgebandsforeachedge, "A new window will be displayed where the user can set the edge band for each side.");
	strcpy(sAnewwindowwillbedisplayedwheretheusercansetthegrindingvalueforeachedgeofthsheet, "A new window will be displayed where the user can set the grinding size for each side of the piece.");
	strcpy(sAnewwindowwillbedisplayedwheretheusercansetthetrimvalueforeachedgeofthsheet, "A new window will be displayed where the user can set the trim value for each side of the piece.");
	strcpy(sAngle, "Angle");
	strcpy(sAngles, "Angles");
	strcpy(sAnoptimizationparameterisarealnumber, "An optimization parameter is a real number.");
	strcpy(sAnoptimizationparameterisfractionalnumber, "An optimization parameter is a fractional number.");
	strcpy(sAnyShape, "True shape");
	strcpy(sApolygonmusthaveatleast2vertices, "A polygon must have at least 2 vertices!");
	strcpy(sApolygonmusthaveatleast3vertices, "A polygon must have at least 3 vertices!");
	strcpy(sApplication_fails_to_initialize, "The application failed to initialize!");
	strcpy(sArc, "Arc");
	strcpy(sArcLength, "Arc length");
	strcpy(sAreaofusedsheets, "Area of utilized sheets");
	strcpy(sAshortdescriptionofthesheet, "A short description of the sheet");
	strcpy(sAtleastonepart, "You must enter at least one piece.");
	strcpy(sAtTheMarginOfTheSheet, "At the margin of the sheet");
	strcpy(sBandtypes, "Types of edge bands");
	strcpy(sBar, "Bar");
	strcpy(sBars, "Bars");
	strcpy(sBothsizesoftheoffcutsmustbegreaterthanthisvalue, "Both waste's sizes must be greater than this value.");
	strcpy(sBottom, "Bottom");
	strcpy(sBottomcoordinateofthedefect, "The bottom coordinate of the defect");
	strcpy(sBreakCut, "Break the cut");
	strcpy(sBrowse, "Browse");
	strcpy(sBuy, "Buy");
	strcpy(sBuynow, "Buy now ...");
	strcpy(sCancel, "Cancel");
	strcpy(sCannotBeEmpty, "cannot be empty!");
	strcpy(sCannotmovepartsbetweensheetswhenidenticalsheetsaregroupedPleaseungroupthesheetsfrommenu, "Cannot move the parts from one sheet to another if the identical sheets are grouped. Please cancel the grouping of the sheets from menu.");
	strcpy(sCannotSaveFile, "Cannot save the file");
	strcpy(sCenter, "Center");
	strcpy(s_Centering, "Centering");
	strcpy(sChangeDirection, "Change cut direction");
	strcpy(sChoose, "Choose");
	strcpy(sChooseProduct, "Choose product");
	strcpy(sCircle, "Circle");
	strcpy(sCity, "City");
	strcpy(sClear, "Clear");
	strcpy(sClockWise, "Clockwise");
	strcpy(sClosewindow, "Close window");
	strcpy(sColor, "Color");
	strcpy(sColorofedgeband, "The color of edge bands");
	strcpy(sColorPattern, "Color/Pattern");
	strcpy(sColorpiecesandwastes, "Colored pieces and wastes");
	strcpy(sColumns, "Columns");
	strcpy(sComment, "Comment");
	strcpy(sCompanyname, "Company name");
	strcpy(sComplexMaterialExists, "The name of the material is already defined in the list of complex materials. Please give it a new name.");
	strcpy(sComputerCode, "Computer code");
	strcpy(sComputerCodefromyourcomputer, "Computer Code (from your computer)");
	strcpy(sComputethetotalpriceofDemand, "Compute the total price of Parts");
	strcpy(sContents, "Contents");
	strcpy(sContinutComanda, "Content of the Parts in date");
	strcpy(sContinutDepozit, "Content of the Stock in the date");
	strcpy(sConversionIsDoneOnlyWhenSomePiecesHaveFractionalValues, "Conversion is done only when some pieces have fractional values.");
	strcpy(sConvertsTheSizeOfWasteToAFractionalUnit, "Shows the size of waste as a fractional value.");
	strcpy(sCouldNotSaveFile1, "Could not write the file in the directory");
	strcpy(sCouldNotSaveFile2, "You may not have enough rights. Please check or change the working directory from menu Settings | Working directory to a folder where you have rights to write (for instance c:\\temp).");
	strcpy(sCreationdateYMDHMS, "Creation date (Y/M/D-H:M:S)");
	strcpy(sCurrentDate, "Current Date");
	strcpy(sCurrentDiagram, "Current diagram");
	strcpy(sCurrentMaterial, "Current material");
	strcpy(sCurrentversion, "Current version");
	strcpy(sCurve_not_closed_Try_increasing_DXF_linking_distance_parameter, "The polygon is not closed! Try increasing DXF linking distance parameter.");
	strcpy(sCustomer, "Customer");
	strcpy(sCustomerName, "Customer name");
	strcpy(sCustomMessage, "Custom message");
	strcpy(sCutlength, "Length of cuts");
	strcpy(sCut, "Cut");
	strcpy(sCuts, "Cuts");
	strcpy(sCutterThickness, "Cut thickness");
	strcpy(sData, "Data");
	strcpy(sDataCannotBeEmpty, "The data cannot be empty!");
	strcpy(sDateymdhms, "Date(y/m/d/h/m/s)");
	strcpy(sDays_left_for_trial, "Days left for trial ");
	strcpy(sDaysLeft, "days left");
	strcpy(sStandard, "Standard");
	strcpy(sDefaultInterface, "Default interface");
	strcpy(sDefects, "Defects");
	strcpy(sDefectsManager, "Manage defects");
	strcpy(sDefectsofthematerialNopiecescanbeplacedinthefaultyzone, "Defects of the material. No pieces can be placed in the faulty zone.");
	strcpy(sDelete, "Delete");
	strcpy(sDeletePiece, "Delete piece");
	strcpy(sDeleteRow, "Delete row");
	strcpy(sDemandutilization, "Utilization of parts");
	strcpy(sDepozitulmodificat, "The utilized pieces have been removed. The waste has been added to stock.");
	strcpy(sDepozitvid, "The stock is empty");
	strcpy(sDesk, "desk");
	strcpy(sDiagram, "Diagram");
	strcpy(sDiagrams, "Diagrams");
	strcpy(sDiagramasatable, "Diagram as a table");
	strcpy(sDigits, "digits");
	strcpy(sDimensiuniplaca, "Size of sheet");
	strcpy(sDirection, "Direction");
	strcpy(sDistanceBetweenRows, "Distance between rows");
	strcpy(sDonotuseit, "Do not use it");
	strcpy(sDownload, "Download");
	strcpy(sDoYouWantToClearTheData, "Do you want to delete the data?");
	strcpy(sDoYouWantToSaveDemand, "The parts have been changed! Do you want to save the changes?");
	strcpy(sDoYouWantToSaveParts, "Do you want to save the parts?");
	strcpy(sDoYouWantToSaveRepository, "The stock has been changed! Do you want to save the changes?");
	strcpy(sDrawing, "Drawing");
	strcpy(sDrawthesolutioncolorful, "Draw the solution colorful");
	strcpy(sDuplicateTypes, "Some types are duplicated! Please remove duplicates.");
	strcpy(sDuplicateTypesWithComplex, "Some names of materials already exist in the list of complex types! Please remove the duplicates");
	strcpy(sDuplicateValues, "Duplicated values");
	strcpy(sEdgeband, "Edge bands");
	strcpy(sEdgebandingwhichisplacedontheedgesofyourpiecePleasedefineedgebandingtypesfromMaterialsEdgeBandingmenu, "Edge bands are placed on the margins of your piece. Please define edge bands in the Materials menu.");
	strcpy(sEdgebandsthatwillbeappliedtoeachpart, "The edge bands that are applied to each piece.");
	strcpy(sEdgeBandTolerance, "Tolerance for edge bands");
	strcpy(sEdgesthatmustbecutduefaults, "Edges that must be cut because of the defects.");
	strcpy(sEdgetoedge, "From edge to edge");
	strcpy(sEdit, "Edit");
	strcpy(sEmail, "Email");
	strcpy(sEmptyData, "The data are empty!");
	strcpy(sEnabled, "Enabled");
	strcpy(sEnabledisabledefectsoftheinventorysheets, "Enable / disable defects of the stock");
	strcpy(sEnterLabel, "Input the label");
	strcpy(sEnterTheMaterialName, "Input the name of the material");
	strcpy(sEnterTheProductName, "Enter the name of the product");
	strcpy(sEvaluationError, "Error to the expression evaluation!");
	strcpy(sExit, "Exit");
	strcpy(sExpired, "The software has expired! Please register the software!");
	strcpy(sExport, "Export");
	strcpy(sExportAllDiagrams, "Export all diagrams");
	strcpy(sExportAllToASingleFile, "Export all to a single file");
	strcpy(sExportOptions, "Export options");
	strcpy(sExporttoDXFformat, "Export to DXF format");
	strcpy(sExporttoExcel, "Export to Excel");
	strcpy(sExpresieIncorecta, "Incorrect mathematical expression!");
	strcpy(sExtensions, "Extensions");
	strcpy(sExtra, "Extra");
	strcpy(sExtraComponents, "Extra Components");
	strcpy(sExtracomponentsattachedtoDemand, "Extra components attached to parts");
	strcpy(sFile, "File");
	strcpy(sFileName, "File name");
	strcpy(sFillWastes, "Draw waste with oblique lines");
	strcpy(sFindoptimalbarsheetsize, "Find the optimal size for bars and sheets.");
	strcpy(sFindoptimalsizeofInventorypieces, "Find the optimal size of stock pieces");
	strcpy(sFirstcutMultiplestages, "First cut direction for multiple stage optimization.");
	strcpy(sFirstdirectionforcutishorizontal, "The first direction for cut is horizontal.");
	strcpy(sFirstdirectionforcutisvertical, "The first direction for cut is vertical.");
	strcpy(sFollowthecontourofpieces, "Follow the contour of the pieces");
	strcpy(sFont, "Font");
	strcpy(sFontsize, "Font size");
	strcpy(sFullInfo, "Complete information");
	strcpy(sDisposedWaste, "Disposed waste");
	strcpy(sGeneral, "General");
	strcpy(sGenerateCNC, "Generate CNC");
	strcpy(sGrain, "Texture");
	strcpy(sGraindirection, "Texture direction");
	strcpy(sGraphic, "Graphic");
	strcpy(sGreaterorequalto, "The waste must be greater or equal to");
	strcpy(sGrid, "Tables");
	strcpy(sGrinding, "Grinding");
	strcpy(sGrosimeTaieturaScalata, "The cut thickness from this picture might be different from the real one because the pieces are not represented at their true scale. This fact does not affect the results.");
	strcpy(sGroupidenticallayouts, "Group identical sheets");
	strcpy(sGroupIdenticalParts, "Group identical parts");
	strcpy(sGroupingOfIdenticalPiecesIntoOneRow, "Group identical parts into one row.");
	strcpy(sGroupPartsAfterLoadingFromFile, "Group parts when loading from file");
	strcpy(sHeight, "Height");
	strcpy(sHeighttolerance, "Tolerance for height");
	strcpy(sHelp, "Help");
	strcpy(sHistory, "History");
	strcpy(sHorizontal, "Horizontal");
	strcpy(sHowtodisplayprintedgebands, "How are the edge bands displayed?");
	strcpy(sIfyousetthebandforoneedgeallwillreceivethesamevalue, "If you set the band for one edge, all edges will receive the same value.");
	strcpy(sIfyousetthegrindingforoneedgeallwillreceivethesamevalue, "If you set the grinding value for one edge, all edges  will receive the same value.");
	strcpy(sIfyousetthetrimforoneedgeallwillreceivethesamevalue, "If you set the trimming for one edge, all edges will receive the same value.");
	strcpy(sImageBounds, "Bounds for image");
	strcpy(sImageSize, "Image size");
	strcpy(sImportData, "Import the data");
	strcpy(sIncorrectPassword, "Incorrect password");
	strcpy(sIndex, "Index");
	strcpy(sInformationaboutcustomer, "Information about customer");
	strcpy(sInputALanguageName, "Input the name of the language");
	strcpy(sInsert, "Insert");
	strcpy(sInsertPiece, "Insert piece");
	strcpy(sInterface, "Interface");
	strcpy(sInterfaceSettings, "Interface settings");
	strcpy(sInvalidHardware, "I could not detect the hardware. Please contact us at contact@optimalprograms.com");
	strcpy(sInvalidNumber, "Invalid number");
	strcpy(sInvalidOrderOfComputation, "An order for computing the lengths cannot be established. There are circular relationships in the product definition!");
	strcpy(sInvalidRegistration, "Registration is invalid!");
	strcpy(sInvalidTime, "The time of your system is invalid.");
	strcpy(sInventory, "STOCK");
	strcpy(sisafractionalvalue, "is a fractional value.");
	strcpy(sIsArc, "Is arc");
	strcpy(sisarealvalue, "is a real value.");
	strcpy(sLabel, "Label");
	strcpy(sLabels, "Labels");
	strcpy(sLanguage, "Language");
	strcpy(sLatimeanumar0, "The width must be greater than 0!");
	strcpy(sLatimeanumarreal, "The width must be a real number!");
	strcpy(sLayerName, "Layer's name");
	strcpy(sLeft, "Left");
	strcpy(sLeftcoordinateofthedefect, "The left coordinate of the defect");
	strcpy(sLength, "Length");
	strcpy(sLengthofthepiecestocut, "Piece size for cutting");
	strcpy(sLengthofthepiecestocutfrom, "Sheet size for cutting");
	strcpy(sLengthofusedbars, "Size of used bars");
	strcpy(sLicenseAgreement, "License agreement");
	strcpy(sLinear, "Linear");
	strcpy(sLinethickness, "Thickness of pen");
	strcpy(sLoadafileandappenddatatothecurrentDemand, "Load a file and append the data to the current parts.");
	strcpy(sLoadanexistingDemandfromafile, "Load existing parts from a file.");
	strcpy(sLoadAppend, "Load and append");
	strcpy(sLoadEverything, "Load everything");
	strcpy(sLoadInventory, "Load the stock");
	strcpy(sLoadInventoryandDemand, "Load the stock and the parts");
	strcpy(sLoadResults, "Load the results");
	strcpy(sLocked, "Locked");
	strcpy(sLogo, "Logo");
	strcpy(sLong, "Long");
	strcpy(sLongerexecutiontime, "Longer running time");
	strcpy(sLungime, "Length");
	strcpy(sLungimeanumar0, "The length must be greater than 0!");
	strcpy(sLungimeanumarreal, "The length must be a real number!");
	strcpy(sLungimeaTotalaFolosita, "Total utilized length");
	strcpy(sMagnification, "Magnification");
	strcpy(sMagnify, "Magnify");
	strcpy(sMargins, "Margins");
	strcpy(sMarginsForPaper, "Margins for paper");
	strcpy(sMarginsOfTheLabel, "Margins of the label");
	strcpy(sMaterial, "Material");
	strcpy(sMaterialName, "Name of the material");
	strcpy(sMaterials, "Materials");
	strcpy(sMaterialstypes, "Materials types");
	strcpy(sMax, "Max");
	strcpy(sMaximalArea, "Maximal area");
	strcpy(sMaximalCutLength, "Maximal cut length");
	strcpy(sMaxlength, "Maximal length");
	strcpy(sMaxPiecesperBar, "Maximum number of pieces per bar");
	strcpy(sMaxwidth, "Max width");
	strcpy(sMeasurementUnit, "Measurement unit");
	strcpy(sMin, "Min");
	strcpy(sMinimalBreakSize, "Minimal break size");
	strcpy(sMinimalUsefulSize, "Minimal useful size");
	strcpy(sMinimalwastesizetoInventory, "Minimum waste size added to stock.");
	strcpy(s_What_to_minimize, "What to minimize?");
	strcpy(sMinlength, "Minimal length");
	strcpy(sMinwidth, "Minimal width");
	strcpy(sMirror, "Mirror");
	strcpy(sMirroring, "Mirroring");
	strcpy(sMiscellaneous, "Other statistics");
	strcpy(sModify, "Modify");
	strcpy(sModifytheselectedpiece, "Modify the selected piece");
	strcpy(sMovePiece, "Move piece");
	strcpy(sMultiplestages, "Multiple stages");
	strcpy(sName, "Name");
	strcpy(sNameofedgeband, "Name of edge band");
	strcpy(sNewDEMANDUnsaveddatawillbelost, "New parts? Unsaved data will be lost!");
	strcpy(sNewLanguage, "New language");
	strcpy(sNewMaterial, "New Material");
	strcpy(sNewPasswordincorectlyintroduced, "New password incorrectly introduced!");
	strcpy(sNewProduct, "New product");
	strcpy(sNewversion, "New version");
	strcpy(sNo, "No");
	strcpy(sNumarBucati, "Number of pieces");
	strcpy(sNumberOfCopies, "Number of copies");
	strcpy(sNumberofstages, "Number of stages");
	strcpy(sNusuficienteplacidepozit, "Not all pieces have been optimized. Possible causes: There are not enough pieces in the Stock. Pieces are not enabled. Material of the pieces and Stock are different. Other parameters have been incorrectly set.");
	strcpy(sOfficeNotInstaled, "Microsoft Office is not installed onto your computer or an incorrect version is installed!");
	strcpy(sOldpassworddoesnotmatch, "Old password does not match!");
	strcpy(sOnlinehelp, "Online help");
	strcpy(sOnlypiecesofthesameheightinthelaststage, "Pieces of the same height in the last stage");
	strcpy(sOpen, "Open");
	strcpy(sOptimization, "Optimization");
	strcpy(sOptimizationDone, "Optimization performed! You may print or save the obtained diagrams. Press button Accept if you are satisfied with the current solution. Otherwise press Start again.");
	strcpy(sOptimizationType, "Optimization type");
	strcpy(sOptions, "Options");
	strcpy(sOptionsrelatedtotheinterface, "Options related to the interface");
	strcpy(sor, "or");
	strcpy(sOthercomponents, "Other components");
	strcpy(sOthers, "Others");
	strcpy(sOtherstatistics, "Other statistics");
	strcpy(sOverrideExcelCSVfiles, "Override Excel/CSV files");
	strcpy(sParameter, "Parameter");
	strcpy(sParts, "PIECES");
	strcpy(sPattern, "Pattern");
	strcpy(sPatternforwaste, "Pattern for waste");
	strcpy(sPerimeter, "Perimeter");
	strcpy(sPermitedRotationAngle, "Allowed rotation angle");
	strcpy(sPhone, "Phone");
	strcpy(sPicture, "Image");
	strcpy(sPiece, "Piece");
	strcpy(sPieceindex, "Piece's index");
	strcpy(sPieces, "Pieces");
	strcpy(sPiecesize, "Piece size");
	strcpy(sPiecesizelabeledgebandwillbeprinted, "Piece size, label, edge bands will be printed.");
	strcpy(sPierdere, "Scrap");
	strcpy(sPixels, "pixels");
	strcpy(sPlacilefolositeDepozit, "Utilized pieces from the Stock.");
	strcpy(sPlease_contact_us_at_contact_nestingtechnologies_com, "Please contact us at contact@nesting-technologies.com");
	strcpy(sPlease_contact_us_at_contact_optimalprograms_com, "Please contact us at contact@optimalprograms.com");
	strcpy(sPleaseenteralldataeitherasfractionalorrealDonotmixthem, "Please enter all numbers either as fractional values or real values! Do not mix them!");
	strcpy(sPleaseEnterSomeTypesOfMaterials, "There is no type of material defined. You may define them from the Materials menu.");
	strcpy(sPleasesendtheNameandtheCodetotheaddresscontactoptimalprogramscominordertoobtaintheRegistrationKey, "In order to obtain the Registration Key please send the Name and the Code to: contact@optimalprograms.com.");
	strcpy(sPolygon, "Polygon");
	strcpy(sPolygonsCircles, "Polygons, circles");
	strcpy(sPrecision, "Precision");
	strcpy(sPretulnumar0, "The price must be greater than 0!");
	strcpy(sPretulnumarreal, "The price must be a real number!");
	strcpy(sPreview, "Preview");
	strcpy(sPrice, "Price");
	strcpy(sPriceMustBeGreaterThanZero, "The price must be greater than zero");
	strcpy(sPriceofbars, "Price of bars");
	strcpy(sPriceperbar, "Price per bar");
	strcpy(sPricepersheet, "Price per sheet");
	strcpy(sPricepersquareunitofmaterial, "Price per square unit of material");
	strcpy(sPriceperunit, "Price per unit");
	strcpy(sPrint, "Print");
	strcpy(sPrintdiagramsastables, "Print diagrams as tables.");
	strcpy(sPrinter, "Printer");
	strcpy(sPrinterBounds, "Margins for printer");
	strcpy(sPrinting, "Printing");
	strcpy(sPrintonlyutilizedarea, "Print only the utilized area");
	strcpy(sPrintthecontentsoftheDemand, "Print the contents of the parts.");
	strcpy(sPrintthecontentsoftheInventory, "Print the contents of the stock.");
	strcpy(sPrintthecurrentsolution, "Print the current solution.");
	strcpy(sPriority, "Priority");
	strcpy(sPrioritytocutapieceZero0isthehighestpriority, "Priority to cut a piece. Zero (0) is the highest priority.");
	strcpy(sProcentul0100, "The percents must be greater than 0 and less or equal to 100!");
	strcpy(sProcentulnumarreal, "The percents must be a real number!");
	strcpy(sProductdefinition, "Product definition");
	strcpy(sProductExists, "The product already exists. Choose another name.");
	strcpy(sProductName, "Product name");
	strcpy(sProduct, "Product");
	strcpy(sProducts, "Products");
	strcpy(sProject, "Project");
	strcpy(sProperties, "Properties");
	strcpy(sProperty, "Property");
	strcpy(sQuantity, "Quantity");
	strcpy(sQuantitynumberofsheetsofthistype, "Number of sheets of this type");
	strcpy(sRadius, "Radius");
	strcpy(sRectangular, "Rectangular");
	strcpy(sRedefinetypesofedgeband, "Redefine types of edge band");
	strcpy(sRedefinetypesofmaterial, "Redefine types of materials");
	strcpy(sRegistration, "Registration");
	strcpy(sRegistrationKeyfromOptimalPrograms, "Registration key");
	strcpy(sRegistrationSuccessful, "Registration was successful!");
	strcpy(sRemoveallpiecesinInventory, "Remove all pieces in Inventory.");
	strcpy(sRemoveCut, "Delete cut");
	strcpy(sRemovetheselectedpiece, "Delete the selected piece");
	strcpy(sReports, "Reports");
	strcpy(sRequestedMaterial, "Requested material");
	strcpy(sRestore, "Restore");
	strcpy(sResults, "Results");
	strcpy(sReusedwaste, "Reused waste");
	strcpy(sRight, "Right");
	strcpy(sRightcoordinateofthedefect, "Coordinates of the defect from the right side");
	strcpy(sRotation, "Rotation");
	strcpy(sRotationAngle, "Rotation angle");
	strcpy(sRotationStep, "Rotation step");
	strcpy(sRoundAllFractionsTo, "The fractional values must be rounded to");
	strcpy(sRow, "Row");
	strcpy(sRows, "Rows");
	strcpy(sRun, "Latest solutions");
	strcpy(sRunningtime, "Running time");
	strcpy(sSameforall, "The same for all");
	strcpy(sSave, "Save");
	strcpy(sSaveAllImages, "Save all images");
	strcpy(sSaveAs, "Save As");
	strcpy(sSaveChanges, "The parts have been changed. Do you want to save them?");
	strcpy(sSaveCurrentImage, "Save the current image");
	strcpy(sSavedataparameters, "Save data and parameters");
	strcpy(sSaveEverything, "Save everything");
	strcpy(sSaveInventory, "Save Inventory");
	strcpy(sSaveInventoryandDemand, "Save the stock and parts");
	strcpy(sSaveResults, "Save results");
	strcpy(sSaveStatisticsinafile, "Save statistics in a file");
	strcpy(sSavethecurrentimage, "Save the current image");
	strcpy(sSavethecurrentimageorstatistic, "Save the current image or the statistics");
	strcpy(sSavetheDEMANDinafile, "Save to file");
	strcpy(sSavetheDemandinafilewithadifferentname, "Save the Parts in a file with a different name.");
	strcpy(sSavetheREPOSITORYinafile, "Save the Stock in a file");
	strcpy(sSerialNumber, "Registration key");
	strcpy(sService, "Service");
	strcpy(sSetDefaultValues, "This will restore all parameters to their default values. All your settings will be lost. Are you sure you want to do this?");
	strcpy(sSetedgeband, "Set the edge band");
	strcpy(sSetedgetrim, "Set the cut size for defects of margins");
	strcpy(sSetthesameedgebandforalledges, "Set the same edge band for all sides");
	strcpy(sSetthesamegrindingforalledges, "Set the same grinding for all edges");
	strcpy(sSetthesametrimforalledges, "Set the same cutting for defects for all edges");
	strcpy(sSettings, "Settings");
	strcpy(sShape, "Shape");
	strcpy(sSheet, "Sheet");
	strcpy(sSheetsBarstypes, "Sheets_bars types");
	strcpy(sSheetSize, "Size of sheet");
	strcpy(sSheetsperPage, "Sheets per page");
	strcpy(sShort, "Short");
	strcpy(sShorterexecutiontime, "Short running time");
	strcpy(sShowallsimpleproducts, "Show all simple products");
	strcpy(sShowcustomername, "Show customer name");
	strcpy(sShowCustomTextOnEachPiece, "Show custom text on each piece");
	strcpy(sShowdiagramasatable, "Show the diagram as a table.");
	strcpy(sShowedgeband, "Show edge bands");
	strcpy(sShowedgebandssettinginanewwindow, "Show the settings of the edge bands in a new window");
	strcpy(sShowgrindingsettingsinanewwindow, "Shows grinding settings in a new window");
	strcpy(sShowHorizontalLabelsAlways, "Show horizontal labels always");
	strcpy(sShowRemovethesizeofthepiecesinthecurrentsolution, "Show / hide the size of the pieces.");
	strcpy(sShowRemovethesizeofthewastesinthecurrentsolution, "Show / hide the size of waste.");
	strcpy(sShowtotalcutlength, "Show total cutting length");
	strcpy(sShowtrimedgesettingsinanewwindow, "Show the settings of the defects in a new window");
	strcpy(sSimpleMaterialExists, "The name of the material is already defined in the list of materials. Please give it a new name.");
	strcpy(sSinglePieceStrips, "Stripes of one piece");
	strcpy(sSizes, "Sizes");
	strcpy(sSmallerorequalto, "The waste must be smaller or equal to");
	strcpy(sSort, "Sort");
	strcpy(sSortAscendingByArea, "Sort by area in ascending order");
	strcpy(sSortDescendingByArea, "Sort by area in descending order");
	strcpy(sSpecifyhowdifferentthepiecesinthelaststagecanbeValue0meansnodifference, "Specify how different can be the pieces in the last stage. Value 0 means that all pieces must have the same size.");
	strcpy(sSpecifyifpiecesinthelaststagecanbedifferentornotdepeultimaetapapotfidiferitesaunucadimensiune, "Specify if pieces in the last stage can be different or not");
	strcpy(sSpecifyifthepiececanberotatedornotIfnotitwillbecutinthesamewayasitwasintroducedinDemandLengthofthepieceparalleltothelengthofthesheet, "Specify if the piece can be rotated or not. If not, it is placed in the same way as it was introduced (the length of the piece parallel with the length of the sheet),");
	strcpy(sSpecifyinhowmanystageswemakethecutsDuringastageallcutshavethesamedirection, "Specify in how many stages we make the cuts.");
	strcpy(sStartthesearchprocess, "Start the search process");
	strcpy(sStatistics, "Statistics");
	strcpy(sStatisticsE, "Reports Extra");
	strcpy(sStatisticsforeachtypeofmaterial, "Statistics for each type of material");
	strcpy(sStep, "Step");
	strcpy(sStergeDepozit, "Do you want to delete the Inventory?");
	strcpy(sStergeMaterial, "Do you want to delete the material?");
	strcpy(sStergePiesele, "Do you want to delete the pieces?");
	strcpy(sStergePiesa, "Do you want to delete the piece?");
	strcpy(sStopthesearchprocess, "Stop the search process");
	strcpy(sStrongoptimization, "Strong optimization");
	strcpy(sSubtractthebandthicknessfrompiecesize, "Decrease the size of pieces with the edge band thickness");
	strcpy(sSummary, "Summary");
	strcpy(sSuprafataTotalaFolosita, "Total used surface");
	strcpy(sSuprafatautilizata, "Utilization");
	strcpy(sSwitchbetweenfiberandrotationoption, "Switch between fiber and rotation option.");
	strcpy(sTechnical, "Technical");
	strcpy(sTechnicalsettings, "Technical settings");
	strcpy(sTemporaryPanelHint, "Temporary panel for moving parts between sheets.");
	strcpy(sText, "Text");
	strcpy(sThe_application_has_expired, "The application has expired.");
	strcpy(sThe_application_is_not_registered, "The application is not registered.");
	strcpy(sThe_application_was_first_started_on, "The application was first started on");
	strcpy(sThecutsareperformedfromasidetotheothersideofthematerial, "The cuts are made from a side to the other side of the material.");
	strcpy(sThecuttingmachinecanfollowtheshapeofthematerial, "The cutting machine can follow the shape of the piece.");
	strcpy(sTheedgesofsheetsthatmustbetrimedduefaults, "The edges of sheets that must be trimmed because of the faults");
	strcpy(sTheLargestSize, "The largest size");
	strcpy(sThenameofthecustomerforwhichyoucutthepiece, "The name of the customer for which you cut the piece.");
	strcpy(sThenameofyourcustomer, "The name of your customer");
	strcpy(sThepiececanberotated, "The piece can be rotated");
	strcpy(sTheprogramtriestoavoidwasteswhichhavebothsizeslessthanthisvalue, "The program tries to avoid scrap that is smaller than this value");
	strcpy(sThereAreNoProducts, "There are no defined products yet");
	strcpy(sThestockofmaterialhasbeenpreviouslyloadedfromanExcelorCSVformatPleaseloaditagain, "The stock of material has been previously loaded from an Excel or CSV format. Please load it again if you want to work on it.");
	strcpy(sThetotallengthofcutting, "The total length of cutting");
	strcpy(sThewidthofthecuttingsawForglasscuttingoptimizationitcanbe0Forwooditshouldbegreaterthan0, "The thickness of the cutting saw. When cutting glass, it can be 0. When cutting wood, it should be greater than 0.");
	strcpy(sThewidthofthecuttingsawforlinearpieces, "The thickness of the saw for linear pieces.");
	strcpy(sThickness, "Thickness");
	strcpy(sThischaracterisusedforfillingthewasterectanglesIfyoudonotwantfilledwastejustremovethischaracter, "This symbol is used for filling the waste rectangles. If you do not want filled waste just remove it.");
	strcpy(sThisindexhasvaluebetween1andthenumberofpieces, "This index has a value between 1 and the number of pieces.");
	strcpy(sThisOptionWillOverrideTheInventoryFileIfLoadedFromExcelOrCsvFiles, "This option will override the inventory file if loaded from excel or csv files.");
	strcpy(sThisProgramisLicensedTo, "This program is licensed to");
	strcpy(sThisvaluewillbeaddedtotheedgebandingmaterialoneachside, "This value will be added to the edge bands on each side");
	strcpy(sTipNevid, "The type of material cannot be empty.");
	strcpy(sTitle, "Title");
	strcpy(sTools, "Tools");
	strcpy(sTop, "Top");
	strcpy(sTopcoordinateofthedefect, "The top coordinate of the defect.");
	strcpy(sTotalGarbageWaste, "All discarded scrap");
	strcpy(sTotalInventoryWaste, "Total stock waste");
	strcpy(sTotalRecycledWaste, "All reused waste");
	strcpy(sTotalusedarea, "Total used area");
	strcpy(sTotalusedlength, "Total used length");
	strcpy(sTrigonometric, "Trigonometric");
	strcpy(sTrim, "Trim");
	strcpy(sTrimalledgesatthebeginning, "Trim all the edges at the beginning");
	strcpy(sTrimEdge, "Trim the edge");
	strcpy(sTwoPanels, "Two panels");
	strcpy(sType, "Type");
	strcpy(sTypeofmaterialfromwhichtocut, "Type of material from which to cut");
	strcpy(sTypesAreNotMatched, "The optimization was not performed! Currently, there is no such material in the stock! Pieces can be cut from sheets of the same material. Change some materials from the corresponding column!");
	strcpy(sUndo, "Undo");
	strcpy(sUndoAccept, "Undo Accept");
	strcpy(sUnits, "units");
	strcpy(sUnregisteredVersion, "Unregistered");
	strcpy(sUpdates, "Updates");
	strcpy(sUsefulforwoodfurniture, "Useful for wood furniture");
	strcpy(sUseit, "Use it");
	strcpy(sUsePieceinOptimization, "Use the piece in optimization");
	strcpy(sUserName, "User name");
	strcpy(sUtilizationandWastes, "Utilization and waste");
	strcpy(sUtilizedArea, "Area of utilized parts");
	strcpy(sUtilizedBars, "Utilized bars");
	strcpy(sUtilizeddemandcount, "Number of utilized parts");
	strcpy(sUtilizedParts, "Utilized parts");
	strcpy(sUtilizedPieces, "Utilized pieces");
	strcpy(sUtilizedSheets, "Utilized sheets");
	strcpy(sValue, "Value");
	strcpy(sValueGreaterEqualToZero, "The value must be greater or equal to zero");
	strcpy(sValueGreaterThanZero, "The value must be greater than zero");
	strcpy(sValueIntegerNumber, "The value must be an integer number!");
	strcpy(sValueRealNumber, "The value must be a real number. Maybe you have used a comma instead of a period or viceversa. Please fix it!");
	strcpy(s_The_number_is_too_big_or_it_has_too_many_digits_after_decimal_separator, "The number is too big or it has too many digits after the decimal separator!");
	strcpy(s_The_number_is_too_big, "The number is too big!");
	strcpy(sVertical, "Vertical");
	strcpy(sWaste, "Waste");
	strcpy(sWastes, "Waste");
	strcpy(sWasteAddedToWarehouse, "The waste added to stock");
	strcpy(sWastelimits, "The range for waste");
	strcpy(sWasteType, "Type of waste");
	strcpy(sWeakoptimization, "The weakest optimization");
	strcpy(sWhattoprint, "What should I print");
	strcpy(s_What_to_print_or_save_to_file, "What to print or save to file");
	strcpy(sWhattoprintoneachpiece, "What to print on each piece");
	strcpy(sWhattoshowoneachpiece, "What to show on each piece?");
	strcpy(sWidth, "Width");
	strcpy(sWood, "wood");
	strcpy(sWorkingDirectory, "Working folder");
	strcpy(sWrongKey, "Wrong registration key!");
	strcpy(sYes, "Yes");
	strcpy(sYoucannotchooseblackblueorredcolors, "You cannot choose black, blue or red colors.");
	strcpy(sYouCannotMixFractionalDataWithDecimalOnes, "You cannot mix fractional values with real values!");
	strcpy(sYourcompany, "Your company");
	strcpy(sZip, "Postal code");
	strcpy(s_Set_the_origin_and_the_direction_of_the_axes, "Set the origin and the direction of the axes of coordinates.");
	strcpy(s_license_agreement_text, "Terms of the license:\nSoftware is offered <<as it is>>. Please test all of its features before purchase.\nLicense is forever (for the purchased version).\nFuture, major versions, are not included in price.\nThe software can be installed on a number of computers equal to the number of purchased licenses.\nOne license cannot be used by multiple users in the same time.\n If the program is moved on a new computer, it must be deleted from the current computer.\nThe manufacturer of the software cannot be made responsible for the losses suffered due to the use of the program.\nSupport can be provided by email only.\nIf you have any question concerning this License Agreement, Software, or registration details, please contact us by email.");
	strcpy(s_Parameters, "Parameters");
	strcpy(s_Input_the_name_of_the_parameter, "Input the name of the parameter");
	strcpy(s_Defined_product, "Defined product");
	strcpy(s_Computed_product, "Computed product");
	strcpy(s_Parameter_already_exists, "The parameter is already defined!");
	strcpy(s_Error_parsing_expression, "Error parsing expression");
	strcpy(s_Error_evaluating_expression, "Error evaluating expression");
	strcpy(s_Parameterized_products, "Parameterized products");
	strcpy(s_Simple_products, "Simple products");
	strcpy(s_Number_of_digits_after_the_decimal_separator, "Number of digits after the decimal separator");
	strcpy(s_Percentages, "Percentages");
}
