// Language strings: Danish
// Author: Optimal Programs
// License: MIT License
//---------------------------------------------------------------------------
#include <string.h>
//---------------------------------------------------------------------------
#include "language_string_id.h"
//---------------------------------------------------------------------------
void set_da(void)
{
	// Danish
	// Translated with the latest version of google translate (2020.07.03)
	// last update on: 2025.11.01.0
	
	strcpy(s_Area, "Areal");
	strcpy(s_Mass, "Masse");
	strcpy(s_Advanced, "Fremskreden");
	strcpy(s_Relative_coordinates, "Relative koordinater");
	strcpy(s_Absolute_coordinates, "Absolutte koordinater");
	strcpy(s_Append_more_rows, "Tilføj flere rækker");

	strcpy(s_Add_to_parts, "Føj til dele.");
	strcpy(s_Additional, "Ekstra");
	strcpy(s_All_results, "Alle resultater.");
	strcpy(s_Allow_movement_of_pieces, "Tillad bevægelse af brikker");
	strcpy(s_Allow_part_in_part, "Tillad stykke i stykke");
	strcpy(s_Invalid_piece_Angles_are_too_small_or_too_big_or_height_is_too_small, "Ugyldigt stykke! Vinklerne er for små eller for store, eller højden er for lille.");
	strcpy(s_Append, "Tilføj");
	strcpy(s_As_it_is, "Som det er");
	strcpy(s_As_text, "Som tekst");
	strcpy(s_Ascending, "stigende");
	strcpy(s_Automatic, "Automatisk");
	strcpy(s_Cannot_connect_to_the_Internet_Please_visit_our_website_from_a_browser, "Kan ikke oprette forbindelse til Internettet! Besøg vores hjemmeside fra en browser.");
	strcpy(s_Cannot_copy_or_move_the_files, "Kan ikke kopiere eller flytte filerne!");
	strcpy(s_Cannot_delete_the_file, "Kan ikke slette filen!");
	strcpy(s_Cannot_modify_old_results, "Kan ikke ændre gamle resultater!");
	strcpy(s_To_change_click_inside_a_cell_or_press_0_1_or_2, "For at ændre skal du klikke inde i en celle eller trykke på 0, 1 eller 2.");
	strcpy(s_Cell, "Celle");
	strcpy(s_Click_on_the_table_header_to_change_the_columns, "Klik på tabeloverskriften for at ændre kolonnerne.");
	strcpy(s_Close, "Luk det");
	strcpy(s_Contact_us, "Kontakt os");
	strcpy(s_Column, "Kolonne");
	strcpy(s_Comma, "Komma");
	strcpy(s_The_comma_symbol_cannot_simultaneously_be_the_list_separator_and_the_decimal_separator, "Kommategnet kan ikke samtidig være listeseparator og decimalseparator!");
	strcpy(s_Copy, "Kopi");
	strcpy(s_Copy_for_move, "Kopiér til flytning");
	strcpy(s_Cut_higher_level_strips_first, "Skær strimler på højere niveau først");
	strcpy(s_Cut_index, "Klip indeks");

	strcpy(s_The_data_have_been_changed_Do_you_want_to_save_them_to_a_file, "Dataene er blevet ændret. Vil du gemme dem i en fil?");
	strcpy(s_Decimal_separator, "Decimalskilletegn");
	strcpy(s_Restore_default_settings, "Gendan standardindstillinger");
	strcpy(s_Delete_fiber, "Slet fiber");
	strcpy(s_Descending, "Aftagende");
	strcpy(s_Discard_changes, "Kassér ændringer");

	strcpy(s_Delete_all_data, "Vil du slette alle data?");
	strcpy(s_Dot, "Prik");
	strcpy(s_Do_you_want_to_delete_the_picture, "Vil du slette billedet?");
	strcpy(s_Do_you_want_to_delete_the_product, "Vil du slette produktet?");
	strcpy(s_Duplicate_and_append, "Kopier og tilføj.");
	strcpy(s_Duplicate_values_are_ignored, "Duplikatværdier blev ignoreret!");
	strcpy(s_Error, "Fejl");
	strcpy(s_Error_loading_file, "Fejl ved indlæsning af fil.");
	strcpy(s_export_everything, "Eksporter alt");
	strcpy(s_Fit_to_screen, "Tilpas til skærmen.");
	strcpy(s_Force_fixed_height, "Tegn brikkerne med en fast højde.");
	strcpy(s_Flipped, "Vendte");
	strcpy(s_Import, "Importere");
	strcpy(s_If_angles_are_different_from_90_degrees_height_must_be_greater_than_0, "Hvis vinklerne er forskellige fra 90 grader, skal højden være større end 0.");
	strcpy(s_Ignore, "Ignorere");
	strcpy(s_Incorrect_value, "Forkert værdi");
	strcpy(s_Info, "Info");
	strcpy(s_Interior, "Interiør");
	strcpy(s_Give_a_name, "Giv et navn.");
	strcpy(s_Group, "Grupper det");
	strcpy(s_Header, "Header");
	strcpy(s_Keep_it_as_it_is, "Hold det som det er");
	strcpy(s_Level, "Level");
	strcpy(s_Licensee, "Licenstager");
	strcpy(s_List_separator, "Listeadskiller");
	strcpy(s_Made_with_love_in_Cugir_Romania, "Fremstillet med kærlighed i Cugir, Rumænien");
	strcpy(s_Made_in, "Fremstillet i");
	strcpy(s_Manufacturer, "Fabrikant");

	strcpy(s_Manual_arrange, "Manuel arrangement");

	strcpy(s_Mixed, "Blandet");
	strcpy(s_Multiple_shapes_detected_Next_rows_will_be_overwritten_Continue, "Der blev fundet mere end én form. Derfor vil de efterfølgende rækker blive overskrevet. Blive ved?");
	strcpy(s_More, "Mere");
	strcpy(s_Multiple_values, "Flere værdier");
	strcpy(s_No_texture, "Ingen tekstur");
	strcpy(s_Number, "Nummer");
	strcpy(s_Number_of_images, "Antal billeder");
	strcpy(s_Number_of_vertices, "Antal højdepunkter");
	strcpy(s_Offset, "Offset");
	strcpy(s_Only_the_currently_selected_items, "Kun de aktuelt valgte elementer.");
	strcpy(s_Optimizing_please_wait, "Optimerer ... vent venligst.");

	strcpy(s_Paste, "Paste");

	strcpy(s_Piece_label, "Stykke etiket");
	strcpy(s_Piece_size, "Stykke størrelse");
	strcpy(s_Please_contact_us_by_email_if_you_receive_this_error, "Kontakt os venligst via e-mail, hvis du modtager denne fejl.");
	strcpy(s_Please_save_it_first, "Gem det først.");
	strcpy(s_Position, "Position");
	strcpy(s_Preview, "Eksempel");
	strcpy(s_Rectangle, "Rektangel");

	strcpy(s_Redo_the_last_operation, "Gendan den sidste handling");
	strcpy(s_Regular_polygon, "Regelmæssig polygon");

	strcpy(s_Reused, "Genbrugt");
	strcpy(s_Rotated, "Roteret");
	strcpy(s_Save_all, "Gem alle");
	strcpy(s_Scrap_label, "Skrotens etiket");
	strcpy(s_Scrap_size, "Skrotens størrelse");
	strcpy(s_Semicolon, "Semikolon");
	strcpy(s_Show_cut_index, "Klip indeks");
	strcpy(s_Show_information, "Vis info");
	strcpy(s_Show_piece_label, "Stykke etiket");
	strcpy(s_Show_scrap_label, "Skrotens etiket");
	strcpy(s_Show_scrap_s_size_on_the_small_pieces, "Vis skrotets størrelse på de små stykker");
	strcpy(s_Show_size_of_pieces, "Stykke størrelse");
	strcpy(s_Show_size_of_scrap, "Skrotens størrelse");
	strcpy(s_Show_sizes, "Vis størrelser");
	strcpy(s_Show_label, "Vis etiket");
	strcpy(s_Show_length, "Vis længde");

	strcpy(s_Some_numerical_values_are_incorrect_Should_I_fix_all_the_incorrect_values, "Nogle numeriske værdier er forkerte! Skal jeg rette alle de forkerte værdier?");
	strcpy(s_Some_invalid_values_have_been_removed, "Nogle ugyldige værdier er blevet fjernet.");
	strcpy(s_Sort_by, "Sorter efter");
	strcpy(s_Sort_ascending_by, "Sorter stigende efter");
	strcpy(s_Sort_descending_by, "Sorter faldende efter");
	strcpy(s_Start, "Start");
	strcpy(s_Starting_angle, "Startvinkel");
	strcpy(s_Sticker, "Klistermærke");

	strcpy(s_Stock, "Lager");
	strcpy(s_Stop, "Stop");
	strcpy(s_System_setting, "Systemindstilling");
	strcpy(s_Tabular, "Tabel");
	strcpy(s_Total, "Total");
	strcpy(s_Total_size, "Total størrelse");
	strcpy(s_Terms_of_the_license, "Licensens vilkår");
	strcpy(s_The_current_product_has_been_changed_Do_you_want_to_save_it_to_file, "Det aktuelle produkt er ændret. Vil du gemme den til fil?");
	strcpy(s_The_value_is_out_of_the_allowed_range, "Værdien er uden for det tilladte interval.");
	strcpy(s_The_value_must_be_a_real_or_fractional_number_Try_to_replace_the_comma_with_the_dot_if_you_want_to_enter_a_real_number, "Værdien skal være et reelt eller delvis tal. Prøv at erstatte komma med prikken, hvis du vil indtaste et reelt tal.");
	strcpy(s_This_feature_is_not_implemented_yet, "Denne funktion er ikke implementeret endnu.");
	strcpy(s_This_operation_cannot_be_reversed, "Denne handling kan ikke vendes.");
	strcpy(s_Undo_the_last_operation, "Fortryd den sidste handling.");
	strcpy(s_Utilization, "Udnyttelse");
	strcpy(s_Utilized_Stock, "Udnyttet lager");
	strcpy(s_Version, "Version");
	strcpy(s_Visible_columns, "Synlige kolonner");
	strcpy(s_You_already_have_the_latest_version_installed, "Du har allerede installeret den nyeste version!");
	strcpy(s_What_is_exported, "Hvad eksporteres?");
	strcpy(s0meansanynumberofpieces, "0 betyder ethvert antal stykker");
	strcpy(sAbout, "Om");
	strcpy(sAccept, "Accepter");
	strcpy(sAcceptall, "Accepter alle");
	strcpy(sAcceptthecurrentsolution, "Accepter den nuværende løsning");
	strcpy(sAdd, "Tilføj");
	strcpy(sAddapiece, "Tilføj et stykke");
	strcpy(sAddasimpleproducttoDemand, "Føj et produkt til de eksisterende dele.");
	strcpy(sAddgrindingthicknesstopartsize, "Tilføj slibning tykkelse til stykke størrelse");
	strcpy(sAddproductnametolabel, "Tilføj produktnavnet til etiketten");
	strcpy(sAddress, "Adresse");
	strcpy(sAddselectedsizetoInventory, "Tilføj den valgte størrelse på lageret");
	strcpy(sAdhesivelabels, "Selvklæbende etiketter");
	strcpy(sAdhesivelabelwithinformationaboutpiecesinDemandCustomernameLabelSizeCurrentData, "Selvklæbende etiket med oplysninger om brikker i efterspørgslen: Kundens navn, mærke, størrelse og aktuelle data.");
	strcpy(sAdhesivelabelwithinformationaboutsheetsinInventory, "Selvklæbende etiket med oplysninger om ark i Inventory.");
	strcpy(sAll, "Alle");
	strcpy(sAlloffcutswhichhavethesizegreaterthanthisvaluewillbeaddedtoInventory, "Alle afskæringer, som har størrelse større end denne værdi vil blive tilføjet til Inventory");
	strcpy(sAllowMirroring, "Lad vende");
	strcpy(sAllowRotation, "Tillade drejning");
	strcpy(sAllPieces, "Alle stykker");
	strcpy(sAllpredefinedproducts, "Alle foruddefinerede produkter");
	strcpy(sAnewwindowwillbedisplayedwheretheusercansettheedgebandsforeachedge, "Et nyt vindue vil blive vist, hvor brugeren kan indstille bands for hver kant.");
	strcpy(sAnewwindowwillbedisplayedwheretheusercansetthegrindingvalueforeachedgeofthsheet, "Et nyt vindue vil blive vist, hvor brugeren kan indstille slibning værdi for hver kant af stykket.");
	strcpy(sAnewwindowwillbedisplayedwheretheusercansetthetrimvalueforeachedgeofthsheet, "Et nyt vindue vil blive vist, hvor brugeren kan angive fejl for hver kant af stykket.");
	strcpy(sAngle, "Vinkel");
	strcpy(sAngles, "Vinkler");
	strcpy(sAnoptimizationparameterisarealnumber, "En optimering parameter er et reelt tal.");
	strcpy(sAnoptimizationparameterisfractionalnumber, "En optimeringsparameter er fraktioneret antal.");
	strcpy(sAnyShape, "Enhver form");
	strcpy(sApolygonmusthaveatleast2vertices, "En polygon skal have mindst 2 hjørner!");
	strcpy(sApolygonmusthaveatleast2vertices, "En polygon skal have mindst 3 hjørner!");
	strcpy(sApplication_fails_to_initialize, "Softwaren mislykkedes initialisering.");
	strcpy(sArc, "Bue");
	strcpy(sArcLength, "Bue længde");
	strcpy(sAreaofusedsheets, "Område af brugte plader");
	strcpy(sAshortdescriptionofthesheet, "En kort beskrivelse af arket");
	strcpy(sAtleastonepart, "Du skal indtaste mindst et stykke.");
	strcpy(sAtTheMarginOfTheSheet, "På kanten af ​​arket");
	strcpy(sBandtypes, "Typer kant båndet.");
	strcpy(sBar, "Barer / rør");
	strcpy(sBars, "Barer / rør");
	strcpy(sBothsizesoftheoffcutsmustbegreaterthanthisvalue, "Begge skrotstørrelser skal være større end denne værdi.");
	strcpy(sBottom, "Bund");
	strcpy(sBottomcoordinateofthedefect, "Den nederste koordinat for defekten");
	strcpy(sBreakCut, "Bryde snittet");
	strcpy(sBrowse, "Gennemse");
	strcpy(sBuy, "Købe");
	strcpy(sBuynow, "Køb nu ...");
	strcpy(sCancel, "Annuller det");
	strcpy(sCannotBeEmpty, "kan ikke være tom!");
	strcpy(sCannotmovepartsbetweensheetswhenidenticalsheetsaregroupedPleaseungroupthesheetsfrommenu, "Kan ikke flytte delene fra et ark til en anden, hvis de identiske plader er grupperet venligst annullere grupperingen af ​​arkene fra menu..");
	strcpy(sCannotSaveFile, "Kan ikke gemme filen");
	strcpy(sCenter, "Centrum");

	strcpy(sChangeDirection, "Skift skæreretning");
	strcpy(sChoose, "Vælg");
	strcpy(sChooseProduct, "Vælg produkt");
	strcpy(sCircle, "Cirkel");
	strcpy(sCity, "By");
	strcpy(sClear, "Ryd");
	strcpy(sClockWise, "Med uret");
	strcpy(sClosewindow, "Luk vindue");
	strcpy(sColor, "Farve");
	strcpy(sColorofedgeband, "Farven på kantbånd");
	strcpy(sColorPattern, "Farve / Mønster");
	strcpy(sColorpiecesandwastes, "Farvede stykker og affald");
	strcpy(sColumns, "Kolonner");
	strcpy(sComment, "Kommentar");
	strcpy(sCompanyname, "Firmanavn");
	strcpy(sComplexMaterialExists, "Materialets navn er allerede defineret på listen over komplekse materialer. Giv det et nyt navn.");
	strcpy(sComputerCode, "Computer-koden");
	strcpy(sComputerCodefromyourcomputer, "Computer kode (fra din computer)");
	strcpy(sComputethetotalpriceofDemand, "Beregn den samlede pris på dele");
	strcpy(sContents, "Indhold");
	strcpy(sContinutComanda, "Indhold af dele i dato");
	strcpy(sContinutDepozit, "Indholdet af bestanden i datoen");
	strcpy(sConversionIsDoneOnlyWhenSomePiecesHaveFractionalValues, "Konvertering udføres kun, når nogle stykker har brøkdele.");
	strcpy(sConvertsTheSizeOfWasteToAFractionalUnit, "Viser størrelsen på skrot som en brøkværdi.");
	strcpy(sCouldNotSaveFile1, "Kunne ikke skrive fil i mappen");
	strcpy(sCouldNotSaveFile2, "Du har muligvis ikke nok rettigheder. Kontroller eller ændre arbejdsmiljøet mappe fra menuen Indstillinger | Arbejde mappe til en mappe, hvor du har rettigheder til at skrive (for eksempel c:\\Temp).");
	strcpy(sCreationdateYMDHMS, "Oprettelsesdato (Y / M / D, H: M: S)");
	strcpy(sCurrentDate, "Nuværende dato");
	strcpy(sCurrentDiagram, "Aktuelt diagram");
	strcpy(sCurrentMaterial, "Nuværende Materiale");
	strcpy(sCurrentversion, "Nuværende version");
	strcpy(sCurve_not_closed_Try_increasing_DXF_linking_distance_parameter, "Polygonen er ikke lukket! Prøv at øge parameteren 'DXF-linkafstand'.");
	strcpy(sCustomer, "Kunde");
	strcpy(sCustomerName, "Kundenavn");
	strcpy(sCustomMessage, "Brugerdefineret besked");
	strcpy(sCutlength, "Længden på udskæringerne");
	strcpy(sCut, "Skære");
	strcpy(sCuts, "Skære");
	strcpy(sCutterThickness, "Skær tykkelse");
	strcpy(sData, "Data");
	strcpy(sDataCannotBeEmpty, "Dataene kan ikke være tomme!");
	strcpy(sDateymdhms, "Dato (y / m / d / h / m / s)");
	strcpy(sDays_left_for_trial, "Dage tilbage til retssag");
	strcpy(sDaysLeft, "dage tilbage");
	strcpy(sStandard, "Standard");
	strcpy(sDefaultInterface, "Standardgrænseflade");
	strcpy(sDefects, "mangler");
	strcpy(sDefectsManager, "Håndter defekter");
	strcpy(sDefectsofthematerialNopiecescanbeplacedinthefaultyzone, "Mangler ved materialet. Ingen stykker kan placeres i den defekte zone.");
	strcpy(sDelete, "Slet");
	strcpy(sDeletePiece, "Slet stykke");
	strcpy(sDeleteRow, "Slet række");
	strcpy(sDemandutilization, "Brug af dele");
	strcpy(sDepozitulmodificat, "De anvendte stykker er blevet fjernet. Skrotet er føjet til på lager.");
	strcpy(sDepozitvid, "Bestanden er tom");
	strcpy(sDesk, "skrivebord");
	strcpy(sDiagram, "Diagram");
	strcpy(sDiagrams, "Diagrammer");
	strcpy(sDiagramasatable, "Diagram som en tabel");
	strcpy(sDigits, "cifre");
	strcpy(sDimensiuniplaca, "Størrelse på arket");
	strcpy(sDirection, "Retning");
	strcpy(sDistanceBetweenRows, "Afstand mellem rækker");
	strcpy(sDonotuseit, "Brug ikke den");
	strcpy(sDownload, "Hent");
	strcpy(sDoYouWantToClearTheData, "Vil du slette dataene?");
	strcpy(sDoYouWantToSaveDemand, "Delene er ændret! Vil du gemme ændringerne?");
	strcpy(sDoYouWantToSaveParts, "Vil du gemme delene?");
	strcpy(sDoYouWantToSaveRepository, "Bestanden er ændret! Vil du gemme ændringerne?");
	strcpy(sDrawing, "Tegning");
	strcpy(sDrawthesolutioncolorful, "Tegn løsningen farverig");
	strcpy(sDuplicateTypes, "Nogle typer duplikeres! Fjern duplikater");
	strcpy(sDuplicateTypesWithComplex, "Nogle materialenavne findes allerede på listen over komplekse typer! Fjern duplikaterne");
	strcpy(sDuplicateValues, "Duplicerede værdier");
	strcpy(sEdgeband, "Kantbånd");
	strcpy(sEdgebandingwhichisplacedontheedgesofyourpiecePleasedefineedgebandingtypesfromMaterialsEdgeBandingmenu, "Kantbånd er placeret i kanten af ​​dit stykke. Definer venligst kantbånd i menuen Materialer.");
	strcpy(sEdgebandsthatwillbeappliedtoeachpart, "Kantbåndene, der påføres på hvert stykke.");
	strcpy(sEdgeBandTolerance, "Tolerance for kantbånd");
	strcpy(sEdgesthatmustbecutduefaults, "Kanter, der skal skæres på grund af manglerne.");
	strcpy(sEdgetoedge, "Fra kant til kant");
	strcpy(sEdit, "Redigere");
	strcpy(sEmail, "E-mail");
	strcpy(sEmptyData, "Dataene er tomme!");
	strcpy(sEnabled, "Aktiveret");
	strcpy(sEnabledisabledefectsoftheinventorysheets, "Aktiver / deaktiver defekter på bestanden");
	strcpy(sEnterLabel, "Indtast etiketten");
	strcpy(sEnterTheMaterialName, "Indtast navnet på materialet");
	strcpy(sEnterTheProductName, "Indtast navnet på produktet");
	strcpy(sEvaluationError, "Fejl i udtrykevalueringen!");
	strcpy(sExit, "Afslut");
	strcpy(sExpired, "Softwaren er udløbet! Registrer venligst softwaren!");
	strcpy(sExport, "Eksport");
	strcpy(sExportAllDiagrams, "Eksporter alle diagrammer");
	strcpy(sExportAllToASingleFile, "Eksporter alle til en enkelt fil");
	strcpy(sExportOptions, "Eksportindstillinger");
	strcpy(sExporttoDXFformat, "Eksporter til DXF-format");
	strcpy(sExporttoExcel, "Eksporter til Excel");
	strcpy(sExpresieIncorecta, "Forkert matematisk udtryk!");
	strcpy(sExtensions, "Udvidelser");
	strcpy(sExtra, "ekstra");
	strcpy(sExtraComponents, "Ekstra komponenter");
	strcpy(sExtracomponentsattachedtoDemand, "Ekstra komponenter fastgjort til dele");
	strcpy(sFile, "Fil");
	strcpy(sFileName, "Filnavn");
	strcpy(sFillWastes, "Tegn affald med skrå linjer");
	strcpy(sFindoptimalbarsheetsize, "Find den optimale størrelse til stænger og ark.");
	strcpy(sFindoptimalsizeofInventorypieces, "Find den optimale størrelse på lagerstykker");
	strcpy(sFirstcutMultiplestages, "Første klipretning for optimering af flere trin.");
	strcpy(sFirstdirectionforcutishorizontal, "Første retning for skæring er vandret.");
	strcpy(sFirstdirectionforcutisvertical, "Første retning for skæring er lodret.");
	strcpy(sFollowthecontourofpieces, "Følg stykkernes kontur");
	strcpy(sFont, "Skrifttype");
	strcpy(sFontsize, "Skriftstørrelse");
	strcpy(sFullInfo, "Komplet information");
	strcpy(sDisposedWaste, "Bortskaffet affald");
	strcpy(sGeneral, "Generel");
	strcpy(sGenerateCNC, "Generer CNC");
	strcpy(sGrain, "Vævning");
	strcpy(sGraindirection, "Fiberretning");
	strcpy(sGraphic, "Grafisk");
	strcpy(sGreaterorequalto, "Større eller lig med");
	strcpy(sGrid, "Borde");
	strcpy(sGrinding, "Slibning");
	strcpy(sGrosimeTaieturaScalata, "Snittetykkelsen fra dette billede kan være anderledes end den ægte, fordi brikkerne ikke er repræsenteret i deres rigtige skala. Denne kendsgerning påvirker ikke resultaterne.");
	strcpy(sGroupidenticallayouts, "Grupper identiske ark");
	strcpy(sGroupIdenticalParts, "Grupper identiske dele");
	strcpy(sGroupingOfIdenticalPiecesIntoOneRow, "Grupp identiske dele i en række.");
	strcpy(sGroupPartsAfterLoadingFromFile, "Gruppér dele, når du indlæser fra filen");
	strcpy(sHeight, "Højde");
	strcpy(sHeighttolerance, "Tolerance for højde");
	strcpy(sHelp, "Hjælp");
	strcpy(sHistory, "Historie");
	strcpy(sHorizontal, "Vandret");
	strcpy(sHowtodisplayprintedgebands, "Hvordan vises kantbåndene?");
	strcpy(sIfyousetthebandforoneedgeallwillreceivethesamevalue, "Hvis du indstiller båndet til en kant, får alle kanter den samme værdi.");
	strcpy(sIfyousetthegrindingforoneedgeallwillreceivethesamevalue, "Hvis du indstiller slibeværdien for en kant, får alle kanter den samme værdi.");
	strcpy(sIfyousetthetrimforoneedgeallwillreceivethesamevalue, "Hvis du indstiller beskæringen til en kant, får alle kanter den samme værdi.");
	strcpy(sImageBounds, "Grænser for billede");
	strcpy(sImageSize, "Billedestørrelse");
	strcpy(sImportData, "Importer dataene");
	strcpy(sIncorrectPassword, "forkert kodeord");
	strcpy(sIndex, "Indeks");
	strcpy(sInformationaboutcustomer, "Oplysninger om kunde");
	strcpy(sInputALanguageName, "Indtast navnet på sproget");
	strcpy(sInsert, "Indsæt");
	strcpy(sInsertPiece, "Indsæt stykke");
	strcpy(sInterface, "grænseflade");
	strcpy(sInterfaceSettings, "Interfaceindstillinger");
	strcpy(sInvalidHardware, "Jeg kunne ikke registrere hardware. Kontakt os på contact@optimalprograms.com");
	strcpy(sInvalidNumber, "Ugyldigt nummer");
	strcpy(sInvalidOrderOfComputation, "En ordre til beregning af længderne kan ikke etableres. Der er cirkulære forhold i produktdefinitionen!");
	strcpy(sInvalidRegistration, "Registrering er ugyldig!");
	strcpy(sInvalidTime, "Dit systems tid er ugyldig.");
	strcpy(sInventory, "Lager");
	strcpy(sisafractionalvalue, "er en brøkværdi.");
	strcpy(sIsArc, "Er lysbue");
	strcpy(sisarealvalue, "er en reel værdi.");
	strcpy(sLabel, "Etiket");
	strcpy(sLabels, "Etiketter");
	strcpy(sLanguage, "Sprog");
	strcpy(sLatimeanumar0, "Bredden skal være større end 0!");
	strcpy(sLatimeanumarreal, "Bredden skal være et reelt tal!");
	strcpy(sLayerName, "Lagets navn");
	strcpy(sLeft, "Venstre");
	strcpy(sLeftcoordinateofthedefect, "Den venstre koordinat for defekten");
	strcpy(sLength, "Længde");
	strcpy(sLengthofthepiecestocut, "Stykke størrelse til skæring");
	strcpy(sLengthofthepiecestocutfrom, "Arkstørrelse til skæring");
	strcpy(sLengthofusedbars, "Størrelse på brugte søjler");
	strcpy(sLicenseAgreement, "Licensaftale");
	strcpy(sLinear, "Lineær");
	strcpy(sLinethickness, "Pen tykkelse");
	strcpy(sLoadafileandappenddatatothecurrentDemand, "Ilæg en fil, og tilføj dataene til de aktuelle dele.");
	strcpy(sLoadanexistingDemandfromafile, "Indlæs eksisterende dele fra en fil.");
	strcpy(sLoadAppend, "Læg og tilføj");
	strcpy(sLoadEverything, "Indlæs alt");
	strcpy(sLoadInventory, "Læg bestanden");
	strcpy(sLoadInventoryandDemand, "Læg materiel og dele");
	strcpy(sLoadResults, "Indlæs resultaterne");
	strcpy(sLocked, "Låst");
	strcpy(sLogo, "Logo");
	strcpy(sLong, "Lang");
	strcpy(sLongerexecutiontime, "Længere køretid");
	strcpy(sLungime, "Længde");
	strcpy(sLungimeanumar0, "Længden skal være større end 0!");
	strcpy(sLungimeanumarreal, "Længden skal være et reelt tal!");
	strcpy(sLungimeaTotalaFolosita, "Samlet udnyttet længde");
	strcpy(sMagnification, "Forstørrelse");
	strcpy(sMagnify, "Forstørre");
	strcpy(sMargins, "Margener");
	strcpy(sMarginsForPaper, "Marginer til papir");
	strcpy(sMarginsOfTheLabel, "Marginalerne på etiketten");
	strcpy(sMaterial, "Materiale");
	strcpy(sMaterialName, "Materialets navn");
	strcpy(sMaterials, "Materialer");
	strcpy(sMaterialstypes, "Materialetyper");
	strcpy(sMax, "Max");
	strcpy(sMaximalArea, "Maksimalt område");
	strcpy(sMaximalCutLength, "Maksimal snitlængde");
	strcpy(sMaxlength, "Maksimal længde");
	strcpy(sMaxPiecesperBar, "Maksimalt antal stykker pr. Bar");
	strcpy(sMaxwidth, "Maks bredde");
	strcpy(sMeasurementUnit, "Måleenhed");
	strcpy(sMin, "Min");
	strcpy(sMinimalBreakSize, "Minimal brudstørrelse");
	strcpy(sMinimalUsefulSize, "Minimal nyttig størrelse");
	strcpy(sMinimalwastesizetoInventory, "Minimum skrotstørrelse tilføjet til lager.");
	strcpy(s_What_to_minimize, "Hvad skal man minimere?");
	strcpy(sMinlength, "Minimal længde");
	strcpy(sMinwidth, "Minimal bredde");
	strcpy(sMirror, "Spejl");
	strcpy(sMirroring, "Spejling");
	strcpy(sMiscellaneous, "Andre statistikker");
	strcpy(sModify, "Modificere");
	strcpy(sModifytheselectedpiece, "Rediger det valgte stykke");
	strcpy(sMovePiece, "Flyt stykke");
	strcpy(sMultiplestages, "Flere faser");
	strcpy(sName, "Navn");
	strcpy(sNameofedgeband, "Navn på kantbånd");
	strcpy(sNewDEMANDUnsaveddatawillbelost, "Nye dele? Ikke-gemte data vil gå tabt!");
	strcpy(sNewLanguage, "Nyt sprog");
	strcpy(sNewMaterial, "Nyt materiale");
	strcpy(sNewPasswordincorectlyintroduced, "Ny adgangskode forkert introduceret!");
	strcpy(sNewProduct, "Nyt produkt");
	strcpy(sNewversion, "Ny version");
	strcpy(sNo, "Ingen");
	strcpy(sNumarBucati, "Antal stykker");
	strcpy(sNumberOfCopies, "Antal kopier");
	strcpy(sNumberofstages, "Antal stadier");
	strcpy(sNusuficienteplacidepozit, "Ikke alle stykker er optimeret. Mulige årsager: Der er ikke nok stykker på lageret; Stykker er ikke aktiveret; Stoffets og lagerets materiale er forskellige; Andre parametre er forkert indstillet.");
	strcpy(sOfficeNotInstaled, "Microsoft Office er ikke installeret på din computer, eller en forkert version er installeret!");
	strcpy(sOldpassworddoesnotmatch, "Det gamle kodeord stemmer ikke overens!");
	strcpy(sOnlinehelp, "Online hjælp");
	strcpy(sOnlypiecesofthesameheightinthelaststage, "Stykker med samme højde i det sidste trin");
	strcpy(sOpen, "Åben");
	strcpy(sOptimization, "Optimering");
	strcpy(sOptimizationDone, "Optimering udført! Du kan udskrive eller gemme de opnåede diagrammer. Tryk på knappen Accepter, hvis du er tilfreds med den nuværende løsning. Ellers skal du trykke på Start igen.");
	strcpy(sOptimizationType, "Optimeringstype");
	strcpy(sOptions, "Muligheder");
	strcpy(sOptionsrelatedtotheinterface, "Indstillinger relateret til grænsefladen");
	strcpy(sor, "eller");
	strcpy(sOthercomponents, "Andre komponenter");
	strcpy(sOthers, "Andre");
	strcpy(sOtherstatistics, "Andre statistikker");
	strcpy(sOverrideExcelCSVfiles, "Overstyr Excel / CSV-filer");
	strcpy(sParameter, "Parameter");
	strcpy(sParts, "STYKKER");
	strcpy(sPattern, "Mønster");
	strcpy(sPatternforwaste, "Mønster til skrot");
	strcpy(sPerimeter, "Omkreds");
	strcpy(sPermitedRotationAngle, "Tilladt rotationsvinkel");
	strcpy(sPhone, "telefon");
	strcpy(sPicture, "Billede");
	strcpy(sPiece, "Stykke");
	strcpy(sPieceindex, "Stykke indeks");
	strcpy(sPieces, "Stykker");
	strcpy(sPiecesize, "Stykke størrelse");
	strcpy(sPiecesizelabeledgebandwillbeprinted, "Stykke størrelse, etiket, kantbånd udskrives.");
	strcpy(sPierdere, "skrot");
	strcpy(sPixels, "pixel");
	strcpy(sPlacilefolositeDepozit, "Brugte stykker fra bestanden.");
	strcpy(sPlease_contact_us_at_contact_nestingtechnologies_com, "Kontakt os på contact@nesting-technologies.com");
	strcpy(sPlease_contact_us_at_contact_optimalprograms_com, "Kontakt os på contact@optimalprograms.com");
	strcpy(sPleaseenteralldataeitherasfractionalorrealDonotmixthem, "Indtast alle data enten som brøkværdier eller reelle værdier! Bland dem ikke!");
	strcpy(sPleaseEnterSomeTypesOfMaterials, "Der er ingen type materiale defineret. Du kan definere dem fra menuen Materialer.");
	strcpy(sPleasesendtheNameandtheCodetotheaddresscontactoptimalprogramscominordertoobtaintheRegistrationKey, "For at få registreringsnøglen, send navn og kode til: contact@optimalprograms.com.");
	strcpy(sPolygon, "Polygon");
	strcpy(sPolygonsCircles, "Polygoner, cirkler");
	strcpy(sPrecision, "Præcision");
	strcpy(sPretulnumar0, "Prisen skal være større end 0!");
	strcpy(sPretulnumarreal, "Prisen skal være et reelt tal!");
	strcpy(sPreview, "Eksempel");
	strcpy(sPrice, "Pris");
	strcpy(sPriceMustBeGreaterThanZero, "Prisen skal være større end nul");
	strcpy(sPriceofbars, "Pris på søjler");
	strcpy(sPriceperbar, "Pris pr. Bar");
	strcpy(sPricepersheet, "Pris pr. Ark");
	strcpy(sPricepersquareunitofmaterial, "Pris pr. Kvadratisk enhed af materiale");
	strcpy(sPriceperunit, "Pris pr. Enhed");
	strcpy(sPrint, "Print");
	strcpy(sPrintdiagramsastables, "Udskriv diagrammer som tabeller.");
	strcpy(sPrinter, "Printer");
	strcpy(sPrinterBounds, "Marginer til printer");
	strcpy(sPrinting, "Trykning");
	strcpy(sPrintonlyutilizedarea, "Udskriv kun det anvendte område");
	strcpy(sPrintthecontentsoftheDemand, "Udskriv indholdet af delene.");
	strcpy(sPrintthecontentsoftheInventory, "Udskriv lagerets indhold.");
	strcpy(sPrintthecurrentsolution, "Print den aktuelle løsning.");
	strcpy(sPriority, "Prioritet");
	strcpy(sPrioritytocutapieceZero0isthehighestpriority, "Prioritet at klippe et stykke. Nul (0) er den højeste prioritet.");
	strcpy(sProcentul0100, "Procenterne skal være større end 0 og mindre eller lig med 100!");
	strcpy(sProcentulnumarreal, "Procenterne skal være et reelt tal!");
	strcpy(sProductdefinition, "Produktdefinition");
	strcpy(sProductExists, "Produktet findes allerede. Vælg et andet navn.");
	strcpy(sProductName, "Produktnavn");
	strcpy(sProducts, "Produkt");
	strcpy(sProducts, "Produkter");
	strcpy(sProject, "Projekt");
	strcpy(sProperties, "Ejendomme");
	strcpy(sProperty, "Ejendom");
	strcpy(sQuantity, "Antal");
	strcpy(sQuantitynumberofsheetsofthistype, "Antal ark af denne type");
	strcpy(sRadius, "Radius");
	strcpy(sRectangular, "Rektangulær");
	strcpy(sRedefinetypesofedgeband, "Omdefinerer typer kantbånd");
	strcpy(sRedefinetypesofmaterial, "Omdefinerer typer materialer");
	strcpy(sRegistration, "Registrering");
	strcpy(sRegistrationKeyfromOptimalPrograms, "Registreringsnøgle");
	strcpy(sRegistrationSuccessful, "Registreringen var vellykket!");
	strcpy(sRemoveallpiecesinInventory, "Fjern alle stykker i lagerbeholdningen.");
	strcpy(sRemoveCut, "Slet klip");
	strcpy(sRemovetheselectedpiece, "Slet det valgte stykke");
	strcpy(sReports, "Rapporter");
	strcpy(sRequestedMaterial, "Ønsket materiale");
	strcpy(sRestore, "Gendan");
	strcpy(sResults, "Resultater");
	strcpy(sReusedwaste, "Genanvendt affald");
	strcpy(sRight, "Højre");
	strcpy(sRightcoordinateofthedefect, "Koordinater for defekten fra højre side");
	strcpy(sRotation, "Rotation");
	strcpy(sRotationAngle, "Rotationsvinkel");
	strcpy(sRotationStep, "Rotationstrin");
	strcpy(sRoundAllFractionsTo, "Fraktionsværdierne skal afrundes til");
	strcpy(sRow, "række");
	strcpy(sRows, "rækker");
	strcpy(sRun, "Seneste løsninger");
	strcpy(sRunningtime, "løbe tid");
	strcpy(sSameforall, "Det samme for alle");
	strcpy(sSave, "Gemme");
	strcpy(sSaveAllImages, "Gem alle billeder");
	strcpy(sSaveAs, "Gem som");
	strcpy(sSaveChanges, "Delene er ændret. Vil du gemme dem?");
	strcpy(sSaveCurrentImage, "Gem det aktuelle billede");
	strcpy(sSavedataparameters, "Gem data og parametre");
	strcpy(sSaveEverything, "Gem alt");
	strcpy(sSaveInventory, "Gem inventar");
	strcpy(sSaveInventoryandDemand, "Gem lager og dele");
	strcpy(sSaveResults, "Gem resultater");
	strcpy(sSaveStatisticsinafile, "Gem statistikker i en fil");
	strcpy(sSavethecurrentimage, "Gem det aktuelle billede");
	strcpy(sSavethecurrentimageorstatistic, "Gem det aktuelle billede eller statistikken");
	strcpy(sSavetheDEMANDinafile, "Gem til fil");
	strcpy(sSavetheDemandinafilewithadifferentname, "Gem delene i en fil med et andet navn.");
	strcpy(sSavetheREPOSITORYinafile, "Gem aktien i en fil");
	strcpy(sSerialNumber, "Registreringsnøgle");
	strcpy(sService, "Service");
	strcpy(sSetDefaultValues, "Dette gendanner alle parametre til deres standardværdier. Alle dine indstillinger vil gå tabt. Er du sikker på, at du vil gøre dette?");
	strcpy(sSetedgeband, "Indstil kantbåndet");
	strcpy(sSetedgetrim, "Indstil klippestørrelse for margenfejl");
	strcpy(sSetthesameedgebandforalledges, "Sæt det samme kantbånd til alle sider");
	strcpy(sSetthesamegrindingforalledges, "Indstil den samme slibning til alle kanter");
	strcpy(sSetthesametrimforalledges, "Indstil den samme skæring til defekter i alle kanter");
	strcpy(sSettings, "Indstillinger");
	strcpy(sShape, "Form");
	strcpy(sSheet, "Ark");
	strcpy(sSheetsBarstypes, "Ark_bjælke typer");
	strcpy(sSheetSize, "Størrelse på arket");
	strcpy(sSheetsperPage, "Ark pr. Side");
	strcpy(sShort, "Kort");
	strcpy(sShorterexecutiontime, "Kort køretid");
	strcpy(sShowallsimpleproducts, "Vis alle enkle produkter");
	strcpy(sShowcustomername, "Vis kundenavn");
	strcpy(sShowCustomTextOnEachPiece, "Vis tilpasset tekst på hvert stykke");
	strcpy(sShowdiagramasatable, "Vis diagrammet som en tabel.");
	strcpy(sShowedgeband, "Vis kantbånd");
	strcpy(sShowedgebandssettinginanewwindow, "Vis indstillingerne for kantbåndene i et nyt vindue");
	strcpy(sShowgrindingsettingsinanewwindow, "Viser slibingsindstillinger i et nyt vindue");
	strcpy(sShowHorizontalLabelsAlways, "Vis altid vandrette etiketter");
	strcpy(sShowRemovethesizeofthepiecesinthecurrentsolution, "Vis / skjul stykkernes størrelse.");
	strcpy(sShowRemovethesizeofthewastesinthecurrentsolution, "Vis / skjul størrelsen på skrot.");
	strcpy(sShowtotalcutlength, "Vis den samlede skærelængde");
	strcpy(sShowtrimedgesettingsinanewwindow, "Vis indstillingerne for manglerne i et nyt vindue");
	strcpy(sSimpleMaterialExists, "Materialets navn er allerede defineret på listen over materialer. Giv det et nyt navn.");
	strcpy(sSinglePieceStrips, "Striber af ét stykke");
	strcpy(sSizes, "Størrelser");
	strcpy(sSmallerorequalto, "Mindre eller lig med");
	strcpy(sSort, "Sortere");
	strcpy(sSortAscendingByArea, "Sorter efter område i stigende rækkefølge");
	strcpy(sSortDescendingByArea, "Sorter efter område i faldende rækkefølge");
	strcpy(sSpecifyhowdifferentthepiecesinthelaststagecanbeValue0meansnodifference, "Specificer, hvor forskellige kan være brikkerne i den sidste fase. Værdi 0 betyder ingen forskel.");
	strcpy(sSpecifyifpiecesinthelaststagecanbedifferentornotdepeultimaetapapotfidiferitesaunucadimensiune, "Angiv om brikker i den sidste fase kan være forskellige eller ikke");
	strcpy(sSpecifyifthepiececanberotatedornotIfnotitwillbecutinthesamewayasitwasintroducedinDemandLengthofthepieceparalleltothelengthofthesheet, "Angiv om stykket kan drejes eller ikke. Hvis ikke, placeres det på samme måde som det blev introduceret (længden af ​​stykket parallelt med arkets længde), ");
	strcpy(sSpecifyinhowmanystageswemakethecutsDuringastageallcutshavethesamedirection, "Angiv i hvor mange faser vi foretager udskæringerne.");
	strcpy(sStartthesearchprocess, "Start søgeprocessen");
	strcpy(sStatistics, "Statistikker");
	strcpy(sStatisticsE, "Rapporter Ekstra");
	strcpy(sStatisticsforeachtypeofmaterial, "Statistik for hver type materiale");
	strcpy(sStep, "Trin");
	strcpy(sStergeDepozit, "Vil du slette opgørelsen?");
	strcpy(sStergeMaterial, "Vil du slette materialet?");
	strcpy(sStergePiesele, "Vil du slette stykket?");
	strcpy(sStergePiesa, "Vil du slette stykket?");
	strcpy(sStopthesearchprocess, "Stop søgeprocessen");
	strcpy(sStrongoptimization, "Stærk optimering");
	strcpy(sSubtractthebandthicknessfrompiecesize, "Reducer størrelsen på stykker med kantbåndtykkelsen");
	strcpy(sSummary, "Resumé");
	strcpy(sSuprafataTotalaFolosita, "Samlet anvendt overflade");
	strcpy(sSuprafatautilizata, "Udnyttelse");
	strcpy(sSwitchbetweenfiberandrotationoption, "Skift mellem fiber og rotationsindstilling.");
	strcpy(sTechnical, "Teknisk");
	strcpy(sTechnicalsettings, "Tekniske indstillinger");
	strcpy(sTemporaryPanelHint, "Midlertidig panel til bevægelse af dele mellem arkene.");
	strcpy(sText, "Tekst");
	strcpy(sThe_application_has_expired, "Ansøgningen er udløbet.");
	strcpy(sThe_application_is_not_registered, "Ansøgningen er ikke registreret.");
	strcpy(sThe_application_was_first_started_on, "Ansøgningen blev først startet på");
	strcpy(sThecutsareperformedfromasidetotheothersideofthematerial, "Snittene er lavet fra en side til den anden side af materialet.");
	strcpy(sThecuttingmachinecanfollowtheshapeofthematerial, "Skæremaskinen kan følge formen på stykket.");
	strcpy(sTheedgesofsheetsthatmustbetrimedduefaults, "Kanterne på ark, der skal beskæres på grund af fejlene");
	strcpy(sTheLargestSize, "Den største størrelse");
	strcpy(sThenameofthecustomerforwhichyoucutthepiece, "Navnet på den kunde, som du klipper stykket til.");
	strcpy(sThenameofyourcustomer, "Navnet på din kunde");
	strcpy(sThepiececanberotated, "Stykket kan drejes");
	strcpy(sTheprogramtriestoavoidwasteswhichhavebothsizeslessthanthisvalue, "Programmet forsøger at undgå skrot, der er mindre end denne værdi");
	strcpy(sThereAreNoProducts, "Der er endnu ingen definerede produkter");
	strcpy(sThestockofmaterialhasbeenpreviouslyloadedfromanExcelorCSVformatPleaseloaditagain, "Beholdningen af ​​materiale er tidligere blevet indlæst fra et Excel- eller CSV-format. Indlæs det igen, hvis du vil arbejde på det.");
	strcpy(sThetotallengthofcutting, "Den samlede længde af skæring");
	strcpy(sThewidthofthecuttingsawForglasscuttingoptimizationitcanbe0Forwooditshouldbegreaterthan0, "Sagens tykkelse. Ved glasskæring kan det være 0. For træ skal det være større end 0.");
	strcpy(sThewidthofthecuttingsawforlinearpieces, "Sagens tykkelse for lineære stykker.");
	strcpy(sThickness, "Tykkelse");
	strcpy(sThischaracterisusedforfillingthewasterectanglesIfyoudonotwantfilledwastejustremovethischaracter, "Dette symbol bruges til udfyldning af affaldsrektangler. Hvis du ikke ønsker fyldt affald, skal du bare fjerne det.");
	strcpy(sThisindexhasvaluebetween1andthenumberofpieces, "Dette indeks har en værdi mellem 1 og antallet af stykker.");
	strcpy(sThisOptionWillOverrideTheInventoryFileIfLoadedFromExcelOrCsvFiles, "Denne indstilling tilsidesætter beholdningsfilen, hvis den indlæses fra excel- eller csv-filer.");
	strcpy(sThisProgramisLicensedTo, "Dette program er licenseret til");
	strcpy(sThisvaluewillbeaddedtotheedgebandingmaterialoneachside, "Denne værdi tilføjes kantbåndene på hver side");
	strcpy(sTipNevid, "Materialetypen kan ikke være tom.");
	strcpy(sTitle, "Titel");
	strcpy(sTools, "Værktøj");
	strcpy(sTop, "Top");
	strcpy(sTopcoordinateofthedefect, "Den øverste koordinat for defekten.");
	strcpy(sTotalGarbageWaste, "Alt kasseret skrot");
	strcpy(sTotalInventoryWaste, "Samlet lagerbeholdning");
	strcpy(sTotalRecycledWaste, "Alt genbrugt skrot");
	strcpy(sTotalusedarea, "Samlet brugt areal");
	strcpy(sTotalusedlength, "Samlet brugt længde");
	strcpy(sTrigonometric, "trigonometriske");
	strcpy(sTrim, "Trimme");
	strcpy(sTrimalledgesatthebeginning, "Trim alle kanter i begyndelsen");
	strcpy(sTrimEdge, "Trim kanten");
	strcpy(sTwoPanels, "2 paneler");
	strcpy(sType, "Type");
	strcpy(sTypeofmaterialfromwhichtocut, "Type materiale, hvorfra man skal skære");
	strcpy(sTypesAreNotMatched, "Optimeringen blev ikke udført! Materialerne fra dele- og lagertabellerne stemmer ikke overens! Man kan kun skære en del fra materialet med samme navn på lager. Skift materialenavnet fra de tilsvarende kolonner!");
	strcpy(sUndo, "Fortryd");
	strcpy(sUndoAccept, "Fortryd accept");
	strcpy(sUnits, "enheder");
	strcpy(sUnregisteredVersion, "Uregistreret");
	strcpy(sUpdates, "Opdateringer");
	strcpy(sUsefulforwoodfurniture, "Nyttigt til træmøbler");
	strcpy(sUseit, "Brug det");
	strcpy(sUsePieceinOptimization, "Brug stykket i optimering");
	strcpy(sUserName, "Brugernavn");
	strcpy(sUtilizationandWastes, "Brug og skrot");
	strcpy(sUtilizedArea, "Område med anvendte dele");
	strcpy(sUtilizedBars, "Brugte søjler");
	strcpy(sUtilizeddemandcount, "Antal anvendte dele");
	strcpy(sUtilizedParts, "Brugte dele");
	strcpy(sUtilizedPieces, "Brugte stykker");
	strcpy(sUtilizedSheets, "Brugte ark");
	strcpy(sValue, "Værdi");
	strcpy(sValueGreaterEqualToZero, "Værdien skal være større eller lig med nul");
	strcpy(sValueGreaterThanZero, "Værdien skal være større end nul");
	strcpy(sValueIntegerNumber, "Værdien skal være et heltal!");
	strcpy(sValueRealNumber, "Værdien skal være et reelt tal. Måske har du brugt komma i stedet for periode eller viceversa. Fix det venligst!");
	strcpy(s_The_number_is_too_big_or_it_has_too_many_digits_after_decimal_separator, "Antallet er for stort, eller det har for mange cifre efter decimalafskiller!");
	strcpy(s_The_number_is_too_big, "Antallet er for stort!");
	strcpy(sVertical, "Lodret");
	strcpy(sWaste, "Skrot");
	strcpy(sWastes, "Skrot");
	strcpy(sWasteAddedToWarehouse, "Skrotet føjes til på lager");
	strcpy(sWastelimits, "Området for skrot");
	strcpy(sWasteType, "Type skrot");
	strcpy(sWeakoptimization, "Den svageste optimering");
	strcpy(sWhattoprint, "Hvad skal jeg udskrive");
	strcpy(s_What_to_print_or_save_to_file, "Hvad skal du udskrive eller gemme til fil");
	strcpy(sWhattoprintoneachpiece, "Hvad skal udskrives på hvert stykke");
	strcpy(sWhattoshowoneachpiece, "Hvad skal jeg vise på hvert stykke?");
	strcpy(sWidth, "Bredde");
	strcpy(sWood, "træ");
	strcpy(sWorkingDirectory, "Arbejdsmappe");
	strcpy(sWrongKey, "Forkert registreringsnøgle!");
	strcpy(sYes, "Ja");
	strcpy(sYoucannotchooseblackblueorredcolors, "Du kan ikke vælge sorte, blå eller røde farver.");
	strcpy(sYouCannotMixFractionalDataWithDecimalOnes, "Du kan ikke blande fraktionsværdier med reelle værdier!");
	strcpy(sYourcompany, "Dit selskab");
	strcpy(sZip, "Postnummer");
	strcpy(s_Set_the_origin_and_the_direction_of_the_axes, "Indstil oprindelsen og retningen for koordinatakserne.");










	strcpy(s_Number_of_digits_after_the_decimal_separator, "Antal cifre efter decimaladskilleren");
	strcpy(s_Percentages, "Procentsatser");
}

