// Language strings: Portuguess
// Author: Optimal Programs
// License: MIT License
//---------------------------------------------------------------------------
#include <string.h>
//---------------------------------------------------------------------------
#include "language_string_id.h"
//---------------------------------------------------------------------------
void set_pt(void)
{
	//Portuguess
	//did not check manually
	// last update on: 2025.9.25.0
	strcpy(s_Area, "Área");
	strcpy(s_Mass, "Massa");
	strcpy(s_Advanced, "Avançada");
	strcpy(s_Relative_coordinates, "Coordenadas relativas");
	strcpy(s_Absolute_coordinates, "");
	strcpy(s_Append_more_rows, "Anexar mais linhas");

	strcpy(s_Add_to_parts, "Adicione às peças.");
	strcpy(s_Additional, "Adicional");
	strcpy(s_All_results, "Todos os resultados.");
	strcpy(s_Allow_movement_of_pieces, "Permitir movimento de peças");
	strcpy(s_Allow_part_in_part, "Permitir peça em peça");
	strcpy(s_Invalid_piece_Angles_are_too_small_or_too_big_or_height_is_too_small, "Peça inválida! Os ângulos são demasiado pequenos ou demasiado grandes, ou a altura é demasiado pequena.");
	strcpy(s_Append, "Acrescentar");
	strcpy(s_As_it_is, "Como isso é");
	strcpy(s_As_text, "Como texto");
	strcpy(s_Ascending, "Crescente");
	strcpy(s_Automatic, "Automática");
	strcpy(s_Cannot_connect_to_the_Internet_Please_visit_our_website_from_a_browser, "Não é possível conectar-se à Internet! Por favor, visite nosso site a partir de um navegador.");
	strcpy(s_Cannot_copy_or_move_the_files, "Não é possível copiar ou mover os arquivos!");
	strcpy(s_Cannot_delete_the_file, "Não é possível excluir o arquivo!");
	strcpy(s_Cannot_modify_old_results, "Não é possível modificar resultados antigos!");
	strcpy(s_To_change_click_inside_a_cell_or_press_0_1_or_2, "Para alterar, clique dentro de uma célula ou pressione 0, 1 ou 2.");
	strcpy(s_Cell, "Célula");
	strcpy(s_Click_on_the_table_header_to_change_the_columns, "Clique no cabeçalho da tabela para alterar as colunas.");
	strcpy(s_Close, "Fecha-o");
	strcpy(s_Contact_us, "Contate-nos");
	strcpy(s_Column, "Coluna");
	strcpy(s_Comma, "Vírgula");
	strcpy(s_The_comma_symbol_cannot_simultaneously_be_the_list_separator_and_the_decimal_separator, "O símbolo de vírgula não pode ser simultaneamente o separador de lista e o separador decimal!");
	strcpy(s_Copy, "cópia de");
	strcpy(s_Copy_for_move, "Cópia para mover");
	strcpy(s_Cut_higher_level_strips_first, "Corte primeiro as tiras de nível superior");
	strcpy(s_Cut_index, "índice de corte");

	strcpy(s_The_data_have_been_changed_Do_you_want_to_save_them_to_a_file, "Os dados foram alterados. Você quer salvá-los em um arquivo?");
	strcpy(s_Decimal_separator, "Separador decimal");
	strcpy(s_Restore_default_settings, "Restaurar configurações padrão");
	strcpy(s_Delete_fiber, "Excluir fibra");
	strcpy(s_Descending, "descendente");
	strcpy(s_Discard_changes, "Descartar mudanças");

	strcpy(s_Delete_all_data, "Excluir todos os dados?");
	strcpy(s_Dot, "Ponto");
	strcpy(s_Do_you_want_to_delete_the_picture, "Você quer deletar a foto?");
	strcpy(s_Do_you_want_to_delete_the_product, "Você quer deletar o produto?");
	strcpy(s_Duplicate_and_append, "Duplique e anexe.");
	strcpy(s_Duplicate_values_are_ignored, "Valores duplicados foram ignorados!");
	strcpy(s_Error, "Erro");
	strcpy(s_Error_loading_file, "Erro ao carregar o arquivo.");
	strcpy(s_export_everything, "Exportar tudo");
	strcpy(s_Fit_to_screen, "Ajustar a tela.");
	strcpy(s_Force_fixed_height, "Desenhe as peças com uma altura fixa.");
	strcpy(s_Flipped, "Invertida");
	strcpy(s_Import, "Importar");
	strcpy(s_If_angles_are_different_from_90_degrees_height_must_be_greater_than_0, "Se os ângulos forem diferentes de 90 graus, a altura deve ser maior que 0.");
	strcpy(s_Ignore, "Ignorar");
	strcpy(s_Incorrect_value, "Valor incorreto");
	strcpy(s_Info, "Informações");
	strcpy(s_Interior, "dentro");
	strcpy(s_Give_a_name, "Dê um nome.");
	strcpy(s_Group, "Agrupar");
	strcpy(s_Header, "Cabeçalho");
	strcpy(s_Keep_it_as_it_is, "Mantenha como está");
	strcpy(s_Level, "Level");
	strcpy(s_Licensee, "Licenciada");
	strcpy(s_List_separator, "Separador de lista");
	strcpy(s_Made_with_love_in_Cugir_Romania, "Feito, com amor, em: Cugir, Roménia");
	strcpy(s_Made_in, "Fabricado em");
	strcpy(s_Manufacturer, "Fabricante");

	strcpy(s_Manual_arrange, "arranjo manual");

	strcpy(s_Mixed, "Misturada");
	strcpy(s_Multiple_shapes_detected_Next_rows_will_be_overwritten_Continue, "Mais de uma forma foi detectada. Portanto, as linhas subseqüentes serão substituídas. Prosseguir?");
	strcpy(s_More, "Mais");
	strcpy(s_Multiple_values, "Vários valores");
	strcpy(s_No_texture, "Sem textura");
	strcpy(s_Number, "Número");
	strcpy(s_Number_of_images, "Número de imagens");
	strcpy(s_Number_of_vertices, "Número de vértices");
	strcpy(s_Offset, "Desvio");
	strcpy(s_Only_the_currently_selected_items, "Somente os itens atualmente selecionados.");
	strcpy(s_Optimizing_please_wait, "Otimizando... aguarde.");

	strcpy(s_Paste, "Paste");

	strcpy(s_Piece_label, "Etiqueta da peça");
	strcpy(s_Piece_size, "Tamanho da peça");
	strcpy(s_Please_contact_us_by_email_if_you_receive_this_error, "Entre em contato conosco por e-mail se receber esse erro.");
	strcpy(s_Please_save_it_first, "Por favor, salve primeiro.");
	strcpy(s_Position, "Posição");
	strcpy(s_Preview, "Antevisão");
	strcpy(s_Rectangle, "Retângulo");

	strcpy(s_Redo_the_last_operation, "Restaurar a última operação");
	strcpy(s_Regular_polygon, "Polígono regular");

	strcpy(s_Reused, "Reutilizado");
	strcpy(s_Rotated, "Rodada");
	strcpy(s_Save_all, "Salvar tudo");
	strcpy(s_Scrap_label, "Rótulo de sucata");
	strcpy(s_Scrap_size, "Tamanho da sucata");
	strcpy(s_Semicolon, "Ponto e vírgula");
	strcpy(s_Show_cut_index, "índice de corte");
	strcpy(s_Show_information, "Mostrar informações");
	strcpy(s_Show_piece_label, "Etiqueta da peça");
	strcpy(s_Show_scrap_label, "Rótulo de sucata");
	strcpy(s_Show_scrap_s_size_on_the_small_pieces, "Mostrar o tamanho da sucata nos pedaços pequenos");
	strcpy(s_Show_size_of_pieces, "Tamanho da peça");
	strcpy(s_Show_size_of_scrap, "Tamanho da sucata");
	strcpy(s_Show_sizes, "Mostrar tamanhos");
	strcpy(s_Show_label, "Mostrar etiqueta");
	strcpy(s_Show_length, "Mostrar comprimento");

	strcpy(s_Some_numerical_values_are_incorrect_Should_I_fix_all_the_incorrect_values, "Alguns valores numéricos estão incorretos! Devo corrigir todos os valores incorretos?");
	strcpy(s_Some_invalid_values_have_been_removed, "Alguns valores inválidos foram removidos.");
	strcpy(s_Sort_by, "Ordenar por");
	strcpy(s_Sort_ascending_by, "Classificar em ordem crescente por");
	strcpy(s_Sort_descending_by, "Classificar decrescente por");
	strcpy(s_Start, "Start");
	strcpy(s_Starting_angle, "Ângulo inicial");


	strcpy(s_Stock, "Armzem");
	strcpy(s_Stop, "Stop");
	strcpy(s_System_setting, "Configuração do sistema");
	strcpy(s_Tabular, "Tabular");
	strcpy(s_Total, "Total");
	strcpy(s_Total_size, "Tamanho total");
	strcpy(s_Terms_of_the_license, "Termos da licença");
	strcpy(s_The_current_product_has_been_changed_Do_you_want_to_save_it_to_file, "O produto atual foi alterado. Você deseja salvá-lo em um arquivo?");
	strcpy(s_The_value_is_out_of_the_allowed_range, "O valor está fora do intervalo permitido.");
	strcpy(s_The_value_must_be_a_real_or_fractional_number_Try_to_replace_the_comma_with_the_dot_if_you_want_to_enter_a_real_number, "O valor deve ser um número real ou fracionário. Tente substituir a vírgula pelo ponto se desejar inserir um número real.");
	strcpy(s_This_feature_is_not_implemented_yet, "Este recurso ainda não foi implementado.");
	strcpy(s_This_operation_cannot_be_reversed, "Esta operação não pode ser revertida.");
	strcpy(s_Undo_the_last_operation, "Desfazer a última operação.");
	strcpy(s_Utilization, "Utilização");
	strcpy(s_Utilized_Stock, "Estoque utilizado");
	strcpy(s_Version, "Versão");
	strcpy(s_Visible_columns, "Colunas visíveis");
	strcpy(s_You_already_have_the_latest_version_installed, "Você já tem a versão mais recente instalada!");
	strcpy(s_What_is_exported, "O que é exportado?");
	strcpy(s0meansanynumberofpieces, "Zero significa que qualquer número de peças");
	strcpy(sAbout, "Sobre");
	strcpy(sAccept, "Aceitar");
	strcpy(sAcceptall, "Aceitar tudo");
	strcpy(sAcceptthecurrentsolution, "Aceite a solução atual");
	strcpy(sAdd, "Acrescentar");
	strcpy(sAddapiece, "Adicionar uma peça");
	strcpy(sAddasimpleproducttoDemand, "Adicione um produto para a demanda existente.");
	strcpy(sAddgrindingthicknesstopartsize, "Adicione a espessura de moagem para tamanho da peça");
	strcpy(sAddproductnametolabel, "Acrescente o nome do produto para o rótulo");
	strcpy(sAddress, "Endereço");
	strcpy(sAddselectedsizetoInventory, "Adicione tamanho selecionado para o Inventário");
	strcpy(sAdhesivelabels, "As etiquetas adesivas");
	strcpy(sAdhesivelabelwithinformationaboutpiecesinDemandCustomernameLabelSizeCurrentData, "Etiqueta adesiva com as informações sobre peças de Demanda: nome do cliente, Etiqueta, Tamanho, os dados atuais.");
	strcpy(sAdhesivelabelwithinformationaboutsheetsinInventory, "Etiqueta adesiva com as informações sobre folhas em Estoque.");
	strcpy(sAll, "All");
	strcpy(sAlloffcutswhichhavethesizegreaterthanthisvaluewillbeaddedtoInventory, "Todos os resíduos cujo tamanho é maior que esse valor serão adicionados ao estoque");
	strcpy(sAllowMirroring, "Permitir espelhamento");
	strcpy(sAllowRotation, "Permitir a rotação");
	strcpy(sAllPieces, "Todas as peças");
	strcpy(sAllpredefinedproducts, "Todos os produtos predefinidos");
	strcpy(sAnewwindowwillbedisplayedwheretheusercansettheedgebandsforeachedge, "Uma nova janela será exibida onde o usuário pode definir a banda de borda para cada lado.");
	strcpy(sAnewwindowwillbedisplayedwheretheusercansetthegrindingvalueforeachedgeofthsheet, "Uma nova janela será exibida onde o usuário pode definir o tamanho da retificação para cada lado da peça.");
	strcpy(sAnewwindowwillbedisplayedwheretheusercansetthetrimvalueforeachedgeofthsheet, "A new window will appear where the user can define the defect size for each side of the part.");
	strcpy(sAngle, "Ângulo");
	strcpy(sAngles, "ângulos");
	strcpy(sAnoptimizationparameterisarealnumber, "Um parâmetro de otimização é um número real.");
	strcpy(sAnoptimizationparameterisfractionalnumber, "Um parâmetro de otimização é o número fracionário.");
	strcpy(sAnyShape, "Qualquer forma");
	strcpy(sApolygonmusthaveatleast2vertices, "A polygon must have at least 2 vertices!");
	strcpy(sApolygonmusthaveatleast3vertices, "A polygon must have at least 3 vertices!");
	strcpy(sApplication_fails_to_initialize, "O aplicativo falhou ao inicializar!");
	strcpy(sArc, "Arc");
	strcpy(sArcLength, "Comprimento do arco");
	strcpy(sAreaofusedsheets, "Área de folhas usadas");
	strcpy(sAshortdescriptionofthesheet, "Uma breve descrição da folha");
	strcpy(sAtleastonepart, "Pelo menos uma parte deve ser introduzido.");
	strcpy(sAtTheMarginOfTheSheet, "Na borda da folha");
	strcpy(sBandtypes, "Tipos de banda borda.");
	strcpy(sBar, "Barras / tubos");
	strcpy(sBars, "Barras / tubos");
	strcpy(sBothsizesoftheoffcutsmustbegreaterthanthisvalue, "Ambos os tamanhos dos resíduos devem ser maiores que esse valor.");
	strcpy(sBottom, "Fundo");
	strcpy(sBottomcoordinateofthedefect, "A coordenada fundo do defeito");
	strcpy(sBreakCut, "Quebre o corte");
	strcpy(sBrowse, "procurar");
	strcpy(sBuy, "Comprar");
	strcpy(sBuynow, "Compre agora ...");
	strcpy(sCancel, "Cancelá-lo");
	strcpy(sCannotBeEmpty, "não pode estar vazio!");
	strcpy(sCannotmovepartsbetweensheetswhenidenticalsheetsaregroupedPleaseungroupthesheetsfrommenu, "Não é possível mover as peças a partir de uma folha para outra se as folhas idênticos são agrupados por favor cancele o agrupamento das folhas de menu.");
	strcpy(sCannotSaveFile, "Não é possível salvar o arquivo");
	strcpy(sCenter, "Center");

	strcpy(sChangeDirection, "Mude a direção");
	strcpy(sChoose, "Escolher");
	strcpy(sChooseProduct, "Escolha produto");
	strcpy(sCircle, "Circle");
	strcpy(sCity, "Cidade");
	strcpy(sClear, "Limpar");
	strcpy(sClockWise, "No sentido horário");
	strcpy(sClosewindow, "Fechar a janela");
	strcpy(sColor, "Cor");
	strcpy(sColorofedgeband, "A cor de banda de borda");
	strcpy(sColorPattern, "Cor / Padrão");
	strcpy(sColorpiecesandwastes, "Peças e resíduos coloridos.");
	strcpy(sColumns, "Colunas");
	strcpy(sComment, "Comentar");
	strcpy(sCompanyname, "Nome da empresa");
	strcpy(sComplexMaterialExists, "Nome do material já está definido na lista de materiais complexos. Por favor, dê-lhe um novo nome.");
	strcpy(sComputerCode, "O código de computador");
	strcpy(sComputerCodefromyourcomputer, "Código de computador (de computador)");
	strcpy(sComputethetotalpriceofDemand, "Calcule o valor total da demanda");
	strcpy(sContents, "Conteúdo");
	strcpy(sContinutComanda, "Conteúdo da Demanda na data");
	strcpy(sContinutDepozit, "Conteúdo do inventário em data");
	strcpy(sConversionIsDoneOnlyWhenSomePiecesHaveFractionalValues, "A conversão é feita somente quando algumas peças têm valores fracionários.");
	strcpy(sConvertsTheSizeOfWasteToAFractionalUnit, "Mostra o tamanho dos resíduos como um valor fracionário.");
	strcpy(sCouldNotSaveFile1, "Não foi possível gravar o arquivo no diretório");
	strcpy(sCouldNotSaveFile2, "Você pode não ter direitos suficientes. Por favor, verificar ou alterar o diretório de trabalho a partir do menu Configurações | Diretório de trabalho para uma pasta onde você tem direitos de escrever (por exemplo, c:\\temp).");
	strcpy(sCreationdateYMDHMS, "Data de criação (Y / M / D, H: M: S)");
	strcpy(sCurrentDate, "data corrente");
	strcpy(sCurrentDiagram, "Diagrama atual");
	strcpy(sCurrentMaterial, "Material atual");
	strcpy(sCurrentversion, "Versão Atual");
	strcpy(sCurve_not_closed_Try_increasing_DXF_linking_distance_parameter, "O polígono não está fechado! Tente aumentar o parâmetro Distância de ligação DXF.");
	strcpy(sCustomer, "Cliente");
	strcpy(sCustomerName, "Nome do cliente");
	strcpy(sCustomMessage, "Mensagem personalizada");
	strcpy(sCutlength, "O comprimento do corte");
	strcpy(sCut, "Cortar");
	strcpy(sCuts, "Cortes");
	strcpy(sCutterThickness, "Espessura do corte");
	strcpy(sData, "Os dados");
	strcpy(sDataCannotBeEmpty, "Data cannot be empty!");
	strcpy(sDateymdhms, "Data (y / m / d / h / m / s)");
	strcpy(sDays_left_for_trial, "Dias disponíveis para o teste ");
	strcpy(sDaysLeft, "dias esquerda");
	strcpy(sStandard, "Omissão");
	strcpy(sDefaultInterface, "interface padrão");
	strcpy(sDefects, "Defeitos");
	strcpy(sDefectsManager, "Gerenciar defeitos");
	strcpy(sDefectsofthematerialNopiecescanbeplacedinthefaultyzone, "Defeitos do material. Sem as peças podem ser colocados na zona defeituosa.");
	strcpy(sDelete, "Excluir");
	strcpy(sDeletePiece, "Excluir pedaço");
	strcpy(sDeleteRow, "Excluir linha");
	strcpy(sDemandutilization, "Utilização da demanda");
	strcpy(sDepozitulmodificat, "As peças utilizadas foram removidos. Os restos foram adicionados ao estoque.");
	strcpy(sDepozitvid, "O estoque está vazio");
	strcpy(sDesk, "escrivaninha");
	strcpy(sDiagram, "Diagrama");
	strcpy(sDiagrams, "Diagramas");
	strcpy(sDiagramasatable, "Diagrama como uma tabela");
	strcpy(sDigits, "dígitos");
	strcpy(sDimensiuniplaca, "Tamanho da folha");
	strcpy(sDirection, "Direção");
	strcpy(sDistanceBetweenRows, "Distância entre linhas");
	strcpy(sDonotuseit, "Não usá-lo");
	strcpy(sDownload, "Baixar");
	strcpy(sDoYouWantToClearTheData, "Você deseja apagar os dados?");
	strcpy(sDoYouWantToSaveDemand, "As peças foram alteradas! Você quer salvar as alterações?");
	strcpy(sDoYouWantToSaveParts, "Você quer salvar as partes?");
	strcpy(sDoYouWantToSaveRepository, "O estoque foi alterado! Você quer salvar as alterações?");
	strcpy(sDrawing, "desenhos");
	strcpy(sDrawthesolutioncolorful, "Desenhe a solução colorida");
	strcpy(sDuplicateTypes, "Alguns tipos são duplicados! Por favor, remova duplicatas");
	strcpy(sDuplicateTypesWithComplex, "Alguns nomes de materiais já existem na lista de tipos complexos! Por favor, remova as duplicatas");
	strcpy(sDuplicateValues, "Valores duplicados");
	strcpy(sEdgeband, "Bandas para bordas");
	strcpy(sEdgebandingwhichisplacedontheedgesofyourpiecePleasedefineedgebandingtypesfromMaterialsEdgeBandingmenu, "Borda de bandas que é colocada nas bordas de sua parte. Por favor, defina os tipos de bandas de ponta a partir do menu de Materiais.");
	strcpy(sEdgebandsthatwillbeappliedtoeachpart, "Bandas de ponta que serão aplicados para cada parte.");
	strcpy(sEdgeBandTolerance, "Tolerância para bandas de borda");
	strcpy(sEdgesthatmustbecutduefaults, "Bordas que devem ser cortadas devido a defeitos.");
	strcpy(sEdgetoedge, "De ponta a ponta");
	strcpy(sEdit, "Editar");
	strcpy(sEmail, "E-mail");
	strcpy(sEmptyData, "Os dados estão vazios!");
	strcpy(sEnabled, "Ativado");
	strcpy(sEnabledisabledefectsoftheinventorysheets, "Ativar / desativar defeitos do estoque");
	strcpy(sEnterLabel, "Rótulo de Entrada");
	strcpy(sEnterTheMaterialName, "Enter the name of the material");
	strcpy(sEnterTheProductName, "Insira o nome do produto");
	strcpy(sEvaluationError, "Erro de avaliação da expressão!");
	strcpy(sExit, "Sair");
	strcpy(sExpired, "O software expirou! Por favor, registre o software!");
	strcpy(sExport, "Exportar");
	strcpy(sExportAllDiagrams, "Exportar todos os diagramas");
	strcpy(sExportAllToASingleFile, "Exportar tudo para um único arquivo");
	strcpy(sExportOptions, "Opções de exportação.");
	strcpy(sExporttoDXFformat, "Exportar para o formato DXF");
	strcpy(sExporttoExcel, "Exportar para Excel");
	strcpy(sExpresieIncorecta, "Expressão matemática incorreto!");
	strcpy(sExtensions, "Extensions");
	strcpy(sExtra, "Extra");
	strcpy(sExtraComponents, "Componentes extra");
	strcpy(sExtracomponentsattachedtoDemand, "Componentes extra ligada a partes");
	strcpy(sFile, "Arquivo");
	strcpy(sFileName, "O nome do arquivo");
	strcpy(sFillWastes, "Desenhar resíduos com linhas oblíquas");
	strcpy(sFindoptimalbarsheetsize, "Encontre o tamanho ideal para barras e chapas.");
	strcpy(sFindoptimalsizeofInventorypieces, "Encontre o tamanho ideal de peças de ações");
	strcpy(sFirstcutMultiplestages, "Primeira direção de corte para otimização de múltiplos estágios.");
	strcpy(sFirstdirectionforcutishorizontal, "Primeira direção para o corte é horizontal.");
	strcpy(sFirstdirectionforcutisvertical, "Primeira direção para o corte é vertical.");
	strcpy(sFollowthecontourofpieces, "Seguir o contorno das peças");
	strcpy(sFont, "Fonte");
	strcpy(sFontsize, "Tamanho da fonte");
	strcpy(sFullInfo, "Informações completas");
	strcpy(sDisposedWaste, "Lixo descartado");
	strcpy(sGeneral, "Geral");
	strcpy(sGenerateCNC, "Gerar CNC");
	strcpy(sGrain, "Textura");
	strcpy(sGraindirection, "Direção da textura");
	strcpy(sGraphic, "Gráfico");
	strcpy(sGreaterorequalto, "Maior ou igual a");
	strcpy(sGrid, "Tabelas ");
	strcpy(sGrinding, "espessura de moagem");
	strcpy(sGrosimeTaieturaScalata, "A espessura de corte a partir desta imagem pode ser diferente do real, porque as peças não estão representados na sua verdadeira escala. Este fato não afeta os resultados.");
	strcpy(sGroupidenticallayouts, "Agrupamento de folhas idênticas");
	strcpy(sGroupIdenticalParts, "As partes idênticas agrupadas.");
	strcpy(sGroupingOfIdenticalPiecesIntoOneRow, "Agrupamento de peças idênticas em uma linha.");
	strcpy(sGroupPartsAfterLoadingFromFile, "Agrupando as partes após o carregamento do arquivo");
	strcpy(sHeight, "Altura");
	strcpy(sHeighttolerance, "Tolerância para a altura");
	strcpy(sHelp, "Ajudar");
	strcpy(sHistory, "História");
	strcpy(sHorizontal, "Horizonta");
	strcpy(sHowtodisplayprintedgebands, "Como as bandas de borda são exibidas?");
	strcpy(sIfyousetthebandforoneedgeallwillreceivethesamevalue, "Se você definir a banda para um lado, todos receberão o mesmo valor.");
	strcpy(sIfyousetthegrindingforoneedgeallwillreceivethesamevalue, "Se você definir o valor de moagem para uma borda, todas as arestas receberão o mesmo valor.");
	strcpy(sIfyousetthetrimforoneedgeallwillreceivethesamevalue, "Se você definir o recorte de uma borda, todas as arestas receberão o mesmo valor.");
	strcpy(sImageBounds, "Limites para imagem");
	strcpy(sImageSize, "Tamanho da imagem");
	strcpy(sImportData, "Importe os dados");
	strcpy(sIncorrectPassword, "Senha incorreta");
	strcpy(sIndex, "Índice");
	strcpy(sInformationaboutcustomer, "Informações sobre cliente");
	strcpy(sInputALanguageName, "Dê um nome para o idioma");
	strcpy(sInsert, "Inserir");
	strcpy(sInsertPiece, "Insira pedaço");
	strcpy(sInterface, "Interface");
	strcpy(sInterfaceSettings, "Configurações da interface");
	strcpy(sInvalidHardware, "Eu não conseguia detectar o hardware. Por favor, entre em contato conosco contact@optimalprograms.com");
	strcpy(sInvalidNumber, "Número inválido");
	strcpy(sInvalidOrderOfComputation, "Uma ordem para calcular os comprimentos não pode ser estabelecida. Existem relações circulares na definição do produto!");
	strcpy(sInvalidRegistration, "O registo é inválido!");
	strcpy(sInvalidTime, "O tempo do seu sistema é inválido.");
	strcpy(sInventory, "ARMAZÉM");
	strcpy(sisafractionalvalue, "é um valor fraccional.");
	strcpy(sIsArc, "É arco");
	strcpy(sisarealvalue, "é um valor real.");
	strcpy(sLabel, "Etiqueta");
	strcpy(sLabels, "Etiquetas");
	strcpy(sLanguage, "Linguagem");
	strcpy(sLatimeanumar0, "A largura deve ser maior do que 0!");
	strcpy(sLatimeanumarreal, "A largura deve ser um número real!");
	strcpy(sLayerName, "Nome da camada");
	strcpy(sLeft, "Esquerda");
	strcpy(sLeftcoordinateofthedefect, "A coordenada esquerda do defeito");
	strcpy(sLength, "Comprimento");
	strcpy(sLengthofthepiecestocut, "Tamanho de peça para corte");
	strcpy(sLengthofthepiecestocutfrom, "Tamanho da folha para cortar");
	strcpy(sLengthofusedbars, "Tamanho de barras utilizados");
	strcpy(sLicenseAgreement, "acordo de licença");
	strcpy(sLinear, "Linear");
	strcpy(sLinethickness, "Espessura da caneta");
	strcpy(sLoadafileandappenddatatothecurrentDemand, "Carregar um arquivo e acrescentar os dados para a demanda atual.");
	strcpy(sLoadanexistingDemandfromafile, "Carregar peças existentes do arquivo.");
	strcpy(sLoadAppend, "Carregar e Append");
	strcpy(sLoadEverything, "Carregar tudo");
	strcpy(sLoadInventory, "Carregar o estoque");
	strcpy(sLoadInventoryandDemand, "Carregar o estoque e as peças");
	strcpy(sLoadResults, "Carregar os resultados");
	strcpy(sLocked, "Trancado");
	strcpy(sLogo, "logotipo");
	strcpy(sLong, "Comprida");
	strcpy(sLongerexecutiontime, "Tempo de execução");
	strcpy(sLungime, "Largura");
	strcpy(sLungimeanumar0, "O comprimento deve ser maior do que 0!");
	strcpy(sLungimeanumarreal, "O comprimento deve ser um número real!");
	strcpy(sLungimeaTotalaFolosita, "Comprimento total utilizada");
	strcpy(sMagnification, "Ampliação");
	strcpy(sMagnify, "Ampliar");
	strcpy(sMargins, "Margens");
	strcpy(sMarginsForPaper, "Margens para o papel");
	strcpy(sMarginsOfTheLabel, "Margens da etiqueta");
	strcpy(sMaterial, "Material");
	strcpy(sMaterialName, "Nome do material");
	strcpy(sMaterials, "Materiais");
	strcpy(sMaterialstypes, "Tipos de materiais");
	strcpy(sMax, "Max");
	strcpy(sMaximalArea, "Área máxima");
	strcpy(sMaximalCutLength, "Comprimento de corte máxima");
	strcpy(sMaxlength, "Comprimento máximo");
	strcpy(sMaxPiecesperBar, "Número máximo de peças por barra");
	strcpy(sMaxwidth, "Largura máxima.");
	strcpy(sMeasurementUnit, "Unidade de medida");
	strcpy(sMin, "Minima");
	strcpy(sMinimalBreakSize, "Tamanho mínimo de ruptura");
	strcpy(sMinimalUsefulSize, "Tamanho útil mínima");
	strcpy(sMinimalwastesizetoInventory, "Tamanho mínimo de desperdício de Inventário");
	strcpy(s_What_to_minimize, "O que minimizar?");
	strcpy(sMinlength, "Comprimento mínimo");
	strcpy(sMinwidth, "Largura mínima");
	strcpy(sMirror, "Espelho");
	strcpy(sMirroring, "Espelhando");
	strcpy(sMiscellaneous, "Miscelaneum");
	strcpy(sModify, "Modificar");
	strcpy(sModifytheselectedpiece, "Modificar a peça selecionada");
	strcpy(sMovePiece, "Mover a peça.");
	strcpy(sMultiplestages, "Múltiplos estágios");
	strcpy(sName, "Nome");
	strcpy(sNameofedgeband, "Nome da banda de borda");
	strcpy(sNewDEMANDUnsaveddatawillbelost, "Peças novas? Os dados não salvos serão perdidos!");
	strcpy(sNewLanguage, "Nova linguagem");
	strcpy(sNewMaterial, "Novo Material");
	strcpy(sNewPasswordincorectlyintroduced, "Nova senha incorretamente introduzido!");
	strcpy(sNewProduct, "Novo produto");
	strcpy(sNewversion, "Nowa wersja");
	strcpy(sNo, "Não");
	strcpy(sNumarBucati, "Número de peças");
	strcpy(sNumberOfCopies, "Número de cópias");
	strcpy(sNumberofstages, "Número de estágios");
	strcpy(sNusuficienteplacidepozit, "Nem todas as peças foram otimizados. Possíveis causas: Não existem peças suficientes no estoque; peça não são utilizados na otimização; Materiais de demanda e estoques não são correspondidos; Outros parâmetros foram definidos incorretamente.");
	strcpy(sOfficeNotInstaled, "Microsoft Office não está instalado no seu computador ou uma versão incorect está instalado!");
	strcpy(sOldpassworddoesnotmatch, "Senha antiga não corresponde!");
	strcpy(sOnlinehelp, "Ajuda on-line");
	strcpy(sOnlypiecesofthesameheightinthelaststage, "Pedaços de a mesma altura, na última fase");
	strcpy(sOpen, "Aberto");
	strcpy(sOptimization, "Otimização");
	strcpy(sOptimizationDone, "Otimização realizada! Você pode imprimir ou salvar os diagramas obtidos. Pressione o botão Aceitar se você está satisfeito com a solução atual. Caso contrário, prima Iniciar novamente.");
	strcpy(sOptimizationType, "Tipo de otimização");
	strcpy(sOptions, "Opções");
	strcpy(sOptionsrelatedtotheinterface, "Opções relacionadas com a interface");
	strcpy(sor, "ou");
	strcpy(sOthercomponents, "Outros componentes");
	strcpy(sOthers, "Outros");
	strcpy(sOtherstatistics, "Outras estatísticas");
	strcpy(sOverrideExcelCSVfiles, "Substituir arquivos do Excel / CSV");
	strcpy(sParameter, "Parâmetro");
	strcpy(sParts, "PEÇAS");
	strcpy(sPattern, "Padrão");
	strcpy(sPatternforwaste, "Padrão para resíduos");
	strcpy(sPerimeter, "Perímetro");
	strcpy(sPermitedRotationAngle, "O ângulo de rotação permitido.");
	strcpy(sPhone, "Telefone");
	strcpy(sPicture, "Imagem");
	strcpy(sPiece, "Peça");
	strcpy(sPieceindex, "Índice pedaço de");
	strcpy(sPieces, "Pedaços");
	strcpy(sPiecesize, "Tamanho da peça");
	strcpy(sPiecesizelabeledgebandwillbeprinted, "Tamanho Piece, etiqueta, fitas de borda será impresso.");
	strcpy(sPierdere, "Desperdiçar");
	strcpy(sPixels, "pixels");
	strcpy(sPlacilefolositeDepozit, "Utilizado peças do inventário.");
	strcpy(sPlease_contact_us_at_contact_nestingtechnologies_com, "Entre em contato no contact@nesting-technologies.com");
	strcpy(sPlease_contact_us_at_contact_optimalprograms_com, "Entre em contato no contact@optimalprograms.com");
	strcpy(sPleaseenteralldataeitherasfractionalorrealDonotmixthem, "Insira todos os dados como valores fracionários ou reais! Não os misture!");
	strcpy(sPleaseEnterSomeTypesOfMaterials, "Não há nenhum tipo de material definido. Você pode defini-los a partir do menu de Materiais.");
	strcpy(sPleasesendtheNameandtheCodetotheaddresscontactoptimalprogramscominordertoobtaintheRegistrationKey, "A fim de obter a Chave de Registro envie o nome eo código para: contact@optimalprograms.com.");
	strcpy(sPolygon, "Polígono");
	strcpy(sPolygonsCircles, "Polígonos, círculos");
	strcpy(sPrecision, "Precisão");
	strcpy(sPretulnumar0, "O preço deve ser maior do que 0!");
	strcpy(sPretulnumarreal, "O preço deve ser um número real!");
	strcpy(sPreview, "Visualização");
	strcpy(sPrice, "Preço");
	strcpy(sPriceMustBeGreaterThanZero, "Preço deve ser maior que zero");
	strcpy(sPriceofbars, "Preço de bares");
	strcpy(sPriceperbar, "Preço por bar");
	strcpy(sPricepersheet, "Preço por folha");
	strcpy(sPricepersquareunitofmaterial, "Preço por unidade quadrado de material.");
	strcpy(sPriceperunit, "Preço por unidade");
	strcpy(sPrint, "Imprimir");
	strcpy(sPrintdiagramsastables, "Imprimir diagramas em forma de tabelas.");
	strcpy(sPrinter, "Impressora");
	strcpy(sPrinterBounds, "Margens para impressora");
	strcpy(sPrinting, "Impressão");
	strcpy(sPrintonlyutilizedarea, "Imprimir apenas a área utilizada");
	strcpy(sPrintthecontentsoftheDemand, "Imprimir o conteúdo da Demand.");
	strcpy(sPrintthecontentsoftheInventory, "Imprimir o conteúdo do estoque.");
	strcpy(sPrintthecurrentsolution, "Imprimir a solução atual.");
	strcpy(sPriority, "Prioridade");
	strcpy(sPrioritytocutapieceZero0isthehighestpriority, "Prioridade para cortar um pedaço. Zero (0) é a maior prioridade.");
	strcpy(sProcentul0100, "As percentagens deve ser maior que 0 e menor ou igual a 100!");
	strcpy(sProcentulnumarreal, "Os percentuais deve ser um número real!");
	strcpy(sProductdefinition, "Definição do produto");
	strcpy(sProductExists, "O produto já existe. Escolha outro nome.");
	strcpy(sProductName, "Nome do produto");
	strcpy(sProducts, "Produtos");
	strcpy(sProducts, "Produtos");
	strcpy(sProject, "Projeto");
	strcpy(sProperties, "propriedades");
	strcpy(sProperty, "propriedade");
	strcpy(sQuantity, "Quantidade");
	strcpy(sQuantitynumberofsheetsofthistype, "Número de folhas de este tipo");
	strcpy(sRadius, "Raio");
	strcpy(sRectangular, "Retangular");
	strcpy(sRedefinetypesofedgeband, "Redefinir os tipos de banda borda");
	strcpy(sRedefinetypesofmaterial, "Redefinir os tipos de materia");
	strcpy(sRegistration, "Registro");
	strcpy(sRegistrationKeyfromOptimalPrograms, "Chave de Registro");
	strcpy(sRegistrationSuccessful, "Registo com sucesso!");
	strcpy(sRemoveallpiecesinInventory, "Remova todas as peças em estoque.");
	strcpy(sRemoveCut, "Excluir cortar");
	strcpy(sRemovetheselectedpiece, "Retire a peça selecionada");
	strcpy(sReports, "Relatórios");
	strcpy(sRequestedMaterial, "Material solicitado");
	strcpy(sRestore, "Restaurar");
	strcpy(sResults, "Resultados");
	strcpy(sReusedwaste, "Resíduos reutilizados");
	strcpy(sRight, "Direito");
	strcpy(sRightcoordinateofthedefect, "Coordenadas do defeito da direita");
	strcpy(sRotation, "Rotação");
	strcpy(sRotationAngle, "Ângulo de rotação");
	strcpy(sRotationStep, "Passo de rotação");
	strcpy(sRoundAllFractionsTo, "Os valores fracionários devem ser arredondados para");
	strcpy(sRow, "linha");
	strcpy(sRows, "Linhas");
	strcpy(sRun, "Últimas soluções");
	strcpy(sRunningtime, "tempo de corrida");
	strcpy(sSameforall, "Mesmo para todos");
	strcpy(sSave, "Salvar");
	strcpy(sSaveAllImages, "Salve todas as imagens");
	strcpy(sSaveAs, "Salvar como");
	strcpy(sSaveChanges, "A demanda foi alterado. Você quer salvar?");
	strcpy(sSaveCurrentImage, "Salve a imagem atual");
	strcpy(sSavedataparameters, "Salve os dados e parâmetros");
	strcpy(sSaveEverything, "Salve tudo");
	strcpy(sSaveInventory, "Salvar Inventory");
	strcpy(sSaveInventoryandDemand, "Salve Inventário e Demanda");
	strcpy(sSaveResults, "Salvar Resultados");
	strcpy(sSaveStatisticsinafile, "Salve estatísticas em um arquivo");
	strcpy(sSavethecurrentimage, "Salva a imagem atua");
	strcpy(sSavethecurrentimageorstatistic, "Salve a imagem atual ou as estatísticas");
	strcpy(sSavetheDEMANDinafile, "Salvar em arquivo");
	strcpy(sSavetheDemandinafilewithadifferentname, "Salve o Demand em um arquivo com um nome diferente.");
	strcpy(sSavetheREPOSITORYinafile, "Salve o repositório em um arquivo");
	strcpy(sSerialNumber, "Chave de registro");
	strcpy(sService, "serviço");
	strcpy(sSetDefaultValues, "Isso irá restaurar todos os parâmetros aos seus valores padrão. Todas as configurações serão perdidas. Tem certeza de que quer fazer isso?");
	strcpy(sSetedgeband, "Definir banda borda");
	strcpy(sSetedgetrim, "Defina o corte para defeitos de bordas");
	strcpy(sSetthesameedgebandforalledges, "Defina a mesma banda de borda para todos os lados");
	strcpy(sSetthesamegrindingforalledges, "Defina a mesma retificação para todas as arestas");
	strcpy(sSetthesametrimforalledges, "Defina o mesmo corte de defeitos para todas as arestas");
	strcpy(sSettings, "Configurações");
	strcpy(sShape, "Shape");
	strcpy(sSheet, "Folha");
	strcpy(sSheetsBarstypes, "Folhas_Canos tipos");
	strcpy(sSheetSize, "Tamanho da folha");
	strcpy(sSheetsperPage, "Folhas por Página");
	strcpy(sShort, "Short");
	strcpy(sShorterexecutiontime, "Tempo de execução curto");
	strcpy(sShowallsimpleproducts, "Mostrar todos os produtos simples");
	strcpy(sShowcustomername, "Mostrar o nome do cliente");
	strcpy(sShowCustomTextOnEachPiece, "Mostrar texto personalizado em cada peça");
	strcpy(sShowdiagramasatable, "Mostrar diagrama como uma tabela.");
	strcpy(sShowedgeband, "Mostrar fitas de borda");
	strcpy(sShowedgebandssettinginanewwindow, "Mostrar as configurações das fitas de borda em uma nova janela");
	strcpy(sShowgrindingsettingsinanewwindow, "Mostra as configurações de moagem em uma nova janela");
	strcpy(sShowHorizontalLabelsAlways, "Mostrar rótulos sempre horizontais");
	strcpy(sShowRemovethesizeofthepiecesinthecurrentsolution, "Mostrar / ocultar o tamanho das peças.");
	strcpy(sShowRemovethesizeofthewastesinthecurrentsolution, "Mostrar / ocultar o tamanho do recado.");
	strcpy(sShowtotalcutlength, "Mostrar comprimento total de corte");
	strcpy(sShowtrimedgesettingsinanewwindow, "Mostrar as configurações dos defeitos em uma nova janela");
	strcpy(sSimpleMaterialExists, "Nome do material já está definido na lista de materiais. Por favor, dê-lhe um novo nome.");
	strcpy(sSinglePieceStrips, "Listras de uma peça");
	strcpy(sSizes, "Tamanhos");
	strcpy(sSmallerorequalto, "Menor ou igual a");
	strcpy(sSort, "Ordenar");
	strcpy(sSortAscendingByArea, "Classificar por área em ordem crescente");
	strcpy(sSortDescendingByArea, "Classificar por área em ordem decrescente");
	strcpy(sSpecifyhowdifferentthepiecesinthelaststagecanbeValue0meansnodifference, "Especifique o quão diferente pode ser as peças da última fase. O valor 0 significa nenhuma diferença.,");
	strcpy(sSpecifyifpiecesinthelaststagecanbedifferentornotdepeultimaetapapotfidiferitesaunucadimensiune, "Especificar se peças na última etapa pode ser diferente ou não");
	strcpy(sSpecifyifthepiececanberotatedornotIfnotitwillbecutinthesamewayasitwasintroducedinDemandLengthofthepieceparalleltothelengthofthesheet, "Especificar se a peça pode ser girada ou não. Se não, ele será cortado da mesma maneira como foi introduzido em Demand (o comprimento do paralelo peça com o comprimento da folha),");
	strcpy(sSpecifyinhowmanystageswemakethecutsDuringastageallcutshavethesamedirection, "Especificar em quantos estágios que fazemos os cortes.");
	strcpy(sStartthesearchprocess, "Iniciar o processo de busca");
	strcpy(sStatistics, "Estatística");
	strcpy(sStatisticsE, "Relatórios extra");
	strcpy(sStatisticsforeachtypeofmaterial, "Estatísticas para cada tipo de materia");
	strcpy(sStep, "Passo");
	strcpy(sStergeDepozit, "Você quer apagar o inventário?");
	strcpy(sStergeMaterial, "Excluir material?");
	strcpy(sStergePiesele, "Você quer apagar o pedaço?");
	strcpy(sStergePiesa, "Você quer apagar o pedaço?");
	strcpy(sStopthesearchprocess, "Parar o processo de busca");
	strcpy(sStrongoptimization, "Otimização forte");
	strcpy(sSubtractthebandthicknessfrompiecesize, "Diminuir o tamanho da peça com a espessura de bandas");
	strcpy(sSummary, "resumo");
	strcpy(sSuprafataTotalaFolosita, "Superfície total utilizada");
	strcpy(sSuprafatautilizata, "Utilização");
	strcpy(sSwitchbetweenfiberandrotationoption, "Alternar entre fibra e opção de rotação.");
	strcpy(sTechnical, "Técnico");
	strcpy(sTechnicalsettings, "Definições técnicas");
	strcpy(sTemporaryPanelHint, "Painel temporário para partes móveis entre as folhas.");
	strcpy(sText, "Texto");
	strcpy(sThe_application_has_expired, "O programa expirou.");
	strcpy(sThe_application_is_not_registered, "O software não está registrado.");
	strcpy(sThe_application_was_first_started_on, "O software foi iniciado pela primeira vez.");
	strcpy(sThecutsareperformedfromasidetotheothersideofthematerial, "O débito são realizados a partir de um lado para o outro lado do material.");
	strcpy(sThecuttingmachinecanfollowtheshapeofthematerial, "A máquina de corte pode seguir a forma da peça.");
	strcpy(sTheedgesofsheetsthatmustbetrimedduefaults, "As bordas das folhas que devem ser aparadas por causa das falhas");
	strcpy(sTheLargestSize, "O maior tamanho");
	strcpy(sThenameofthecustomerforwhichyoucutthepiece, "O nome do cliente para o qual você cortar o pedaço.");
	strcpy(sThenameofyourcustomer, "O nome do seu cliente");
	strcpy(sThepiececanberotated, "A peça pode ser girado");
	strcpy(sTheprogramtriestoavoidwasteswhichhavebothsizeslessthanthisvalue, "O programa tenta evitar desperdícios que têm ambos os tamanhos inferior a este valor");
	strcpy(sThereAreNoProducts, "Não existem produtos definidos ainda");
	strcpy(sThestockofmaterialhasbeenpreviouslyloadedfromanExcelorCSVformatPleaseloaditagain, "O estoque de material foi previamente carregado a partir de um formato Excel ou CSV. Por favor, coloque-o novamente, se você quiser trabalhar com ele.");
	strcpy(sThetotallengthofcutting, "O comprimento total de corte");
	strcpy(sThewidthofthecuttingsawForglasscuttingoptimizationitcanbe0Forwooditshouldbegreaterthan0, "A espessura da serra. Para o corte de vidro que pode ser 0. Para madeira deverá ser superior a 0.");
	strcpy(sThewidthofthecuttingsawforlinearpieces, "A espessura da serra para peças lineares.");
	strcpy(sThickness, "Espessura");
	strcpy(sThischaracterisusedforfillingthewasterectanglesIfyoudonotwantfilledwastejustremovethischaracter, "Este símbolo é usado para o preenchimento dos retângulos de resíduos. Se você não quiser resíduos cheia basta removê-lo.");
	strcpy(sThisindexhasvaluebetween1andthenumberofpieces, "Este índice tem um valor entre 1 e do número de peças.");
	strcpy(sThisOptionWillOverrideTheInventoryFileIfLoadedFromExcelOrCsvFiles, "Esta opção irá substituir o arquivo de inventário se carregado a partir de arquivos Excel ou CSV.");
	strcpy(sThisProgramisLicensedTo, "Este programa é licenciado para");
	strcpy(sThisvaluewillbeaddedtotheedgebandingmaterialoneachside, "This value will be added to the edge bands on each side");
	strcpy(sTipNevid, "O tipo de material não pode ser vazio.");
	strcpy(sTitle, "Título");
	strcpy(sTools, "Ferramentas");
	strcpy(sTop, "Topo");
	strcpy(sTopcoordinateofthedefect, "A coordenada topo do defeito.");
	strcpy(sTotalGarbageWaste, "Todos descartados resíduos");
	strcpy(sTotalInventoryWaste, "Resíduos estoque total");
	strcpy(sTotalRecycledWaste, "Todos os resíduos reciclados");
	strcpy(sTotalusedarea, "Área utilizada tota");
	strcpy(sTotalusedlength, "Comprimento total utilizado");
	strcpy(sTrigonometric, "Trigonométricas");
	strcpy(sTrim, "Aparar");
	strcpy(sTrimalledgesatthebeginning, "Aparar todas as arestas no início");
	strcpy(sTrimEdge, "Apare a borda");
	strcpy(sTwoPanels, "2 painéis");
	strcpy(sType, "tipo");
	strcpy(sTypeofmaterialfromwhichtocut, "Tipo de material a partir do qual a cortar");
	strcpy(sTypesAreNotMatched, "A otimização não foi realizada! Os materiais das tabelas Peças e Stock não correspondem! É possível cortar uma peça apenas do material com o mesmo nome em stock. Altere o nome dos materiais nas colunas correspondentes!");
	strcpy(sUndo, "Desfazer");
	strcpy(sUndoAccept, "Desfazer Aceitar");
	strcpy(sUnits, "unidades");
	strcpy(sUnregisteredVersion, "Não registado");
	strcpy(sUpdates, "Atualizações");
	strcpy(sUsefulforwoodfurniture, "Útil para móveis de madeira");
	strcpy(sUseit, "Use-o");
	strcpy(sUsePieceinOptimization, "Use a peça na otimização");
	strcpy(sUserName, "Nome de usuário");
	strcpy(sUtilizationandWastes, "Utilização e Resíduos");
	strcpy(sUtilizedArea, "Área de peças utilizadas");
	strcpy(sUtilizedBars, "Barras utilizados");
	strcpy(sUtilizeddemandcount, "Número de peças utilizadas.");
	strcpy(sUtilizedParts, "Peças utilizadas");
	strcpy(sUtilizedPieces, "Peças utilizadas");
	strcpy(sUtilizedSheets, "Folhas utilizadas");
	strcpy(sValue, "Valor");
	strcpy(sValueGreaterEqualToZero, "Valor deve ser maior ou igual a zero");
	strcpy(sValueGreaterThanZero, "Valor deve ser maior do que zero");
	strcpy(sValueIntegerNumber, "O valor deve ser um número inteiro!");
	strcpy(sValueRealNumber, "O valor deve ser um número real. Talvez você tenha usado uma vírgula em vez de um ponto final ou vice-versa. Por favor, conserte!");
	strcpy(s_The_number_is_too_big_or_it_has_too_many_digits_after_decimal_separator, "O número é muito grande ou possui muitos dígitos após o separador decimal!");
	strcpy(s_The_number_is_too_big, "O número é muito grande!");
	strcpy(sVertical, "Vertical");
	strcpy(sWaste, "Sucatear");
	strcpy(sWastes, "Sucatear");
	strcpy(sWasteAddedToWarehouse, "O refugo adicionado ao estoque");
	strcpy(sWastelimits, "limites para resíduos");
	strcpy(sWasteType, "Tipo de resíduos");
	strcpy(sWeakoptimization, "O mais fraco de otimização");
	strcpy(sWhattoprint, "O que devo imprimir");
	strcpy(s_What_to_print_or_save_to_file, "O que imprimir ou salvar em arquivo");
	strcpy(sWhattoprintoneachpiece, "O que para imprimir em cada peça");
	strcpy(sWhattoshowoneachpiece, "O que mostrar em cada peça?");
	strcpy(sWidth, "Largura");
	strcpy(sWood, "madeira");
	strcpy(sWorkingDirectory, "Diretório de trabalho");
	strcpy(sWrongKey, "Chave de Registro errado!");
	strcpy(sYes, "Sim");
	strcpy(sYoucannotchooseblackblueorredcolors, "You cannot choose black, blue or red colors.");
	strcpy(sYouCannotMixFractionalDataWithDecimalOnes, "Você não pode misturar valores fracionários com valores reais!");
	strcpy(sYourcompany, "Sua empresa");
	strcpy(sZip, "Código posta");
	strcpy(s_Set_the_origin_and_the_direction_of_the_axes, "Defina a origem e a direção dos eixos de coordenadas.");










	strcpy(s_Number_of_digits_after_the_decimal_separator, "Número de dígitos após o separador decimal");
	strcpy(s_Percentages, "Porcentagens");
}

