// Language strings: Thai
// Author: Optimal Programs
// License: MIT License
//---------------------------------------------------------------------------
#include <string.h>
//---------------------------------------------------------------------------
#include "language_string_id.h"
//---------------------------------------------------------------------------
void set_th(void)
{
	//Thai
	//did not check manually
	// last update on: 2025.9.25.0
	strcpy(s_Area, "พื้นที่");
	strcpy(s_Mass, "มวล");
	strcpy(s_Advanced, "ขั้นสูง");
	strcpy(s_Relative_coordinates, "พิกัดสัมพันธ์");
	strcpy(s_Absolute_coordinates, "พิกัดสัมบูรณ์");
	strcpy(s_Append_more_rows, "ต่อท้ายแถวเพิ่มเติม");

	strcpy(s_Add_to_parts, "เพิ่มชิ้นส่วน");
	strcpy(s_Additional, "เพิ่มเติม");
	strcpy(s_All_results, "ผลลัพธ์ทั้งหมด");
	strcpy(s_Allow_movement_of_pieces, "อนุญาตให้เคลื่อนย้ายชิ้นส่วน");
	strcpy(s_Allow_part_in_part, "ปล่อยให้เป็นชิ้น ๆ");
	strcpy(s_Invalid_piece_Angles_are_too_small_or_too_big_or_height_is_too_small, "ชิ้นส่วนไม่ถูกต้อง! มุมเล็กเกินไปหรือใหญ่เกินไป หรือความสูงเล็กเกินไป");
	strcpy(s_Append, "ผนวก");
	strcpy(s_As_it_is, "ตามที่มันเป็น");
	strcpy(s_As_text, "เป็นข้อความ");
	strcpy(s_Ascending, "จากน้อยไปมาก");
	strcpy(s_Automatic, "อัตโนมัติ");
	strcpy(s_Cannot_connect_to_the_Internet_Please_visit_our_website_from_a_browser, "ไม่สามารถเชื่อมต่ออินเทอร์เน็ต! กรุณาเยี่ยมชมเว็บไซต์ของเราจากเบราว์เซอร์");
	strcpy(s_Cannot_copy_or_move_the_files, "ไม่สามารถคัดลอกหรือย้ายไฟล์ได้!");
	strcpy(s_Cannot_delete_the_file, "ไม่สามารถลบไฟล์ได้!");
	strcpy(s_Cannot_modify_old_results, "ไม่สามารถแก้ไขผลลัพธ์เก่าได้!");
	strcpy(s_To_change_click_inside_a_cell_or_press_0_1_or_2, "หากต้องการเปลี่ยนให้คลิกภายในเซลล์หรือกด 0, 1 หรือ 2");
	strcpy(s_Cell, "เซลล์");
	strcpy(s_Click_on_the_table_header_to_change_the_columns, "คลิกที่ส่วนหัวของตารางเพื่อเปลี่ยนคอลัมน์");
	strcpy(s_Close, "ปิดมัน");
	strcpy(s_Contact_us, "ติดต่อเรา");
	strcpy(s_Column, "คอลัมน์");
	strcpy(s_Comma, "เครื่องหมายจุลภาค");
	strcpy(s_The_comma_symbol_cannot_simultaneously_be_the_list_separator_and_the_decimal_separator, "เครื่องหมายจุลภาคไม่สามารถเป็นตัวคั่นรายการและตัวคั่นทศนิยมในเวลาเดียวกันได้!");
	strcpy(s_Copy, "สำเนา");
	strcpy(s_Copy_for_move, "คัดลอกเพื่อย้าย");
	strcpy(s_Cut_higher_level_strips_first, "ตัดแถบระดับสูงก่อน");
	strcpy(s_Cut_index, "ดัชนีของคัท");

	strcpy(s_The_data_have_been_changed_Do_you_want_to_save_them_to_a_file, "ข้อมูลมีการเปลี่ยนแปลง คุณต้องการบันทึกลงในไฟล์หรือไม่?");
	strcpy(s_Decimal_separator, "ตัวคั่นทศนิยม");
	strcpy(s_Restore_default_settings, "คืนค่าการตั้งค่าเริ่มต้น");
	strcpy(s_Delete_fiber, "ลบเส้นใย");
	strcpy(s_Descending, "Descending");
	strcpy(s_Discard_changes, "ยกเลิกการเปลี่ยนแปลง");

	strcpy(s_Delete_all_data, "ลบข้อมูลทั้งหมดหรือไม่");
	strcpy(s_Dot, "จุด");
	strcpy(s_Do_you_want_to_delete_the_picture, "คุณต้องการลบรูปภาพหรือไม่?");
	strcpy(s_Do_you_want_to_delete_the_product, "คุณต้องการลบสินค้าหรือไม่?");
	strcpy(s_Duplicate_and_append, "ทำซ้ำและต่อท้าย");
	strcpy(s_Duplicate_values_are_ignored, "ค่าที่ซ้ำกันถูกละเว้น!");
	strcpy(s_Error, "ข้อผิดพลาด");
	strcpy(s_Error_loading_file, "เกิดข้อผิดพลาดในการโหลดไฟล์");
	strcpy(s_export_everything, "ส่งออกทุกอย่าง");
	strcpy(s_Fit_to_screen, "พอดีกับหน้าจอ");
	strcpy(s_Force_fixed_height, "วาดชิ้นส่วนด้วยความสูงคงที่");
	strcpy(s_Flipped, "พลิกแล้ว");
	strcpy(s_Import, "นำเข้า");
	strcpy(s_If_angles_are_different_from_90_degrees_height_must_be_greater_than_0, "หากมุมต่างจาก 90 องศา ความสูงจะต้องมากกว่า 0");
	strcpy(s_Ignore, "ไม่สนใจ");
	strcpy(s_Incorrect_value, "ค่าไม่ถูกต้อง");
	strcpy(s_Info, "ข้อมูล");
	strcpy(s_Interior, "ภายใน");
	strcpy(s_Give_a_name, "ตั้งชื่อ.");
	strcpy(s_Group, "จัดกลุ่ม");
	strcpy(s_Header, "หัวข้อ");
	strcpy(s_Keep_it_as_it_is, "เก็บตามที่มันเป็น");
	strcpy(s_Level, "Level");
	strcpy(s_Licensee, "ผู้รับใบอนุญาต");
	strcpy(s_List_separator, "ตัวคั่นรายการ");
	strcpy(s_Made_with_love_in_Cugir_Romania, "สร้างขึ้นด้วยความรักใน: Cugir, โรมาเนีย");
	strcpy(s_Made_in, "ผลิตใน");
	strcpy(s_Manufacturer, "ผู้ผลิต");

	strcpy(s_Manual_arrange, "คู่มือการจัด");

	strcpy(s_Mixed, "ผสม");
	strcpy(s_Multiple_shapes_detected_Next_rows_will_be_overwritten_Continue, "ตรวจพบมากกว่าหนึ่งรูปร่าง ดังนั้น แถวต่อมาจะถูกเขียนทับ ดำเนินการต่อ?");
	strcpy(s_More, "มากกว่า");
	strcpy(s_Multiple_values, "หลายค่า");
	strcpy(s_No_texture, "ไม่มีพื้นผิว");
	strcpy(s_Number, "จำนวน");
	strcpy(s_Number_of_images, "จำนวนภาพ");
	strcpy(s_Number_of_vertices, "จำนวนจุดยอด");
	strcpy(s_Offset, "ออฟเซ็ต");
	strcpy(s_Only_the_currently_selected_items, "เฉพาะรายการที่เลือกในปัจจุบัน");
	strcpy(s_Optimizing_please_wait, "กำลังเพิ่มประสิทธิภาพ ... โปรดรอสักครู่");

	strcpy(s_Paste, "Paste");

	strcpy(s_Piece_label, "ฉลากของชิ้น");
	strcpy(s_Piece_size, "ขนาดของชิ้น");
	strcpy(s_Please_contact_us_by_email_if_you_receive_this_error, "โปรดติดต่อเราทางอีเมลหากคุณได้รับข้อผิดพลาดนี้");
	strcpy(s_Please_save_it_first, "กรุณาบันทึกไว้ก่อน");
	strcpy(s_Position, "ตำแหน่ง");
	strcpy(s_Preview, "ดูตัวอย่าง");
	strcpy(s_Rectangle, "สี่เหลี่ยมผืนผ้า");

	strcpy(s_Redo_the_last_operation, "กู้คืนการทำงานล่าสุด");
	strcpy(s_Regular_polygon, "รูปหลายเหลี่ยมปกติ");

	strcpy(s_Reused, "นำกลับมาใช้ใหม่");
	strcpy(s_Rotated, "หมุน");
	strcpy(s_Save_all, "บันทึกทั้งหมด");
	strcpy(s_Scrap_label, "ฉลากของเศษเหล็ก");
	strcpy(s_Scrap_size, "ขนาดของเศษซาก");
	strcpy(s_Semicolon, "อัฒภาค");
	strcpy(s_Show_cut_index, "ดัชนีของคัท");
	strcpy(s_Show_information, "แสดงข้อมูล");
	strcpy(s_Show_piece_label, "ฉลากของชิ้น");
	strcpy(s_Show_scrap_label, "ฉลากของเศษเหล็ก");
	strcpy(s_Show_scrap_s_size_on_the_small_pieces, "แสดงขนาดของเศษเหล็กบนชิ้นส่วนขนาดเล็ก");
	strcpy(s_Show_size_of_pieces, "ขนาดของชิ้น");
	strcpy(s_Show_size_of_scrap, "ขนาดของเศษซาก");
	strcpy(s_Show_sizes, "Visa storlekar");
	strcpy(s_Show_label, "แสดงฉลาก");
	strcpy(s_Show_length, "แสดงความยาว");

	strcpy(s_Some_numerical_values_are_incorrect_Should_I_fix_all_the_incorrect_values, "ค่าตัวเลขบางอย่างไม่ถูกต้อง! ฉันควรแก้ไขค่าที่ไม่ถูกต้องทั้งหมดหรือไม่");
	strcpy(s_Some_invalid_values_have_been_removed, "ลบค่าที่ไม่ถูกต้องบางค่าออกแล้ว");
	strcpy(s_Sort_by, "จัดเรียงตาม");
	strcpy(s_Sort_ascending_by, "เรียงจากน้อยไปมาก");
	strcpy(s_Sort_descending_by, "เรียงลำดับจากมากไปน้อย");
	strcpy(s_Start, "Start");
	strcpy(s_Starting_angle, "มุมเริ่มต้น");


	strcpy(s_Stock, "คลังสินค้า");
	strcpy(s_Stop, "Stop");
	strcpy(s_System_setting, "การตั้งค่าระบบ");
	strcpy(s_Tabular, "ตาราง");
	strcpy(s_Total, "รวม");
	strcpy(s_Total_size, "ขนาดทั้งหมด");
	strcpy(s_Terms_of_the_license, "เงื่อนไขการอนุญาต");
	strcpy(s_The_current_product_has_been_changed_Do_you_want_to_save_it_to_file, "ผลิตภัณฑ์ปัจจุบันได้รับการแก้ไขแล้ว คุณต้องการบันทึกลงในไฟล์หรือไม่?");
	strcpy(s_The_value_is_out_of_the_allowed_range, "ค่านี้อยู่นอกช่วงที่อนุญาต");
	strcpy(s_The_value_must_be_a_real_or_fractional_number_Try_to_replace_the_comma_with_the_dot_if_you_want_to_enter_a_real_number, "ค่าต้องเป็นตัวเลขจริงหรือเศษส่วน ลองแทนที่เครื่องหมายจุลภาคด้วยจุดถ้าคุณต้องการป้อนจำนวนจริง");
	strcpy(s_This_feature_is_not_implemented_yet, "คุณลักษณะนี้ยังไม่ได้ใช้งาน");
	strcpy(s_This_operation_cannot_be_reversed, "การดำเนินการนี้ไม่สามารถย้อนกลับได้");
	strcpy(s_Undo_the_last_operation, "เลิกทำการทำงานล่าสุด");
	strcpy(s_Utilization, "การใช้ประโยชน์");
	strcpy(s_Utilized_Stock, "ใช้สต็อก");
	strcpy(s_Version, "รุ่น");
	strcpy(s_Visible_columns, "คอลัมน์ที่มองเห็นได้");
	strcpy(s_You_already_have_the_latest_version_installed, "คุณได้ติดตั้งเวอร์ชันล่าสุดแล้ว!");
	strcpy(s_What_is_exported, "ส่งออกอะไร?");
	strcpy(s0meansanynumberofpieces, "ศูนย์หมายถึงจำนวนชิ้นใด ๆ");
	strcpy(sAbout, "เกี่ยวกับ");
	strcpy(sAccept, "ยอมรับ");
	strcpy(sAcceptall, "ยอมรับทั้งหมด");
	strcpy(sAcceptthecurrentsolution, "ยอมรับโซลูชันปัจจุบัน");
	strcpy(sAdd, "ผนวก");
	strcpy(sAddapiece, "เพิ่มชิ้นส่วน");
	strcpy(sAddasimpleproducttoDemand, "เพิ่มผลิตภัณฑ์ไปยังชิ้นส่วนที่มีอยู่");
	strcpy(sAddgrindingthicknesstopartsize, "เพิ่มความหนาการเจียรให้ได้ขนาดชิ้นงาน");
	strcpy(sAddproductnametolabel, "ผนวกชื่อผลิตภัณฑ์เพื่อติดป้ายกำกับ");
	strcpy(sAddress, "ที่อยู่");
	strcpy(sAddselectedsizetoInventory, "ผนวกขนาดที่เลือกไว้ลงในสต็อค");
	strcpy(sAdhesivelabels, "ฉลากกาว");
	strcpy(sAdhesivelabelwithinformationaboutpiecesinDemandCustomernameLabelSizeCurrentData, "ฉลากกาวที่มีข้อมูลเกี่ยวกับชิ้นส่วน: ชื่อลูกค้า, ฉลาก, ขนาด, ข้อมูลปัจจุบัน ฯลฯ");
	strcpy(sAdhesivelabelwithinformationaboutsheetsinInventory, "ฉลากกาวที่มีข้อมูลเกี่ยวกับแผ่นในสต็อก");
	strcpy(sAll, "ทั้งหมด");
	strcpy(sAlloffcutswhichhavethesizegreaterthanthisvaluewillbeaddedtoInventory, "เศษทั้งหมดที่มากกว่ามูลค่านี้จะถูกเพิ่มเข้าไปในสต็อก");
	strcpy(sAllowMirroring, "อนุญาตให้พลิก");
	strcpy(sAllowRotation, "อนุญาตให้หมุน");
	strcpy(sAllPieces, "ทุกชิ้น");
	strcpy(sAllpredefinedproducts, "ผลิตภัณฑ์ที่กำหนดไว้ล่วงหน้าทั้งหมด");
	strcpy(sAnewwindowwillbedisplayedwheretheusercansettheedgebandsforeachedge, "หน้าต่างใหม่จะปรากฏขึ้นที่ผู้ใช้สามารถตั้งค่าแถบขอบสำหรับแต่ละด้าน");
	strcpy(sAnewwindowwillbedisplayedwheretheusercansetthegrindingvalueforeachedgeofthsheet, "หน้าต่างใหม่จะปรากฏขึ้นที่ผู้ใช้สามารถกำหนดขนาดการเจียรสำหรับแต่ละด้านของชิ้นงาน");
	strcpy(sAnewwindowwillbedisplayedwheretheusercansetthetrimvalueforeachedgeofthsheet, "หน้าต่างใหม่จะปรากฏขึ้นซึ่งผู้ใช้สามารถตั้งค่าการตัดแต่งสำหรับแต่ละด้านของชิ้นส่วน");
	strcpy(sAngle, "มุม");
	strcpy(sAngles, "มุม");
	strcpy(sAnoptimizationparameterisarealnumber, "พารามิเตอร์การปรับให้เหมาะสมคือจำนวนจริง");
	strcpy(sAnoptimizationparameterisfractionalnumber, "พารามิเตอร์การปรับให้เหมาะสมคือตัวเลขที่เป็นเศษส่วน");
	strcpy(sAnyShape, "รูปร่างที่แท้จริง");
	strcpy(sApolygonmusthaveatleast2vertices, "รูปหลายเหลี่ยมต้องมีจุดยอดอย่างน้อย 2 จุด!");
	strcpy(sApolygonmusthaveatleast3vertices, "รูปหลายเหลี่ยมต้องมีจุดยอดอย่างน้อย 3 จุด!");
	strcpy(sApplication_fails_to_initialize, "แอปพลิเคชันไม่สามารถเริ่มต้นได้!");
	strcpy(sArc, "เส้นโค้ง");
	strcpy(sArcLength, "ความยาวส่วนโค้ง");
	strcpy(sAreaofusedsheets, "พื้นที่ของแผ่นที่ใช้แล้ว");
	strcpy(sAshortdescriptionofthesheet, "คำอธิบายสั้น ๆ ของแผ่นงาน");
	strcpy(sAtleastonepart, "คุณต้องป้อนอย่างน้อยหนึ่งชิ้น");
	strcpy(sAtTheMarginOfTheSheet, "ตรงขอบแผ่น");
	strcpy(sBandtypes, "ประเภทของขอบแถบ");
	strcpy(sBar, "ราว");
	strcpy(sBars, "ราว");
	strcpy(sBothsizesoftheoffcutsmustbegreaterthanthisvalue, "ขนาดของเศษทั้งสองจะต้องมากกว่าค่านี้");
	strcpy(sBottom, "ด้านล่าง");
	strcpy(sBottomcoordinateofthedefect, "พิกัดด้านล่างของข้อบกพร่อง");
	strcpy(sBreakCut, "ทำลายการตัด");
	strcpy(sBrowse, "หมวด");
	strcpy(sBuy, "ซื้อ");
	strcpy(sBuynow, "ซื้อเลย ...");
	strcpy(sCancel, "ยกเลิกมัน");
	strcpy(sCannotBeEmpty, "ต้องไม่ว่างเปล่า!");
	strcpy(sCannotmovepartsbetweensheetswhenidenticalsheetsaregroupedPleaseungroupthesheetsfrommenu, "ไม่สามารถย้ายชิ้นส่วนจากแผ่นหนึ่งไปยังอีกแผ่นหนึ่งได้หากมีการจัดกลุ่มแผ่นงานเหมือนกัน โปรดยกเลิกการจัดกลุ่มของแผ่นงานจากเมนู");
	strcpy(sCannotSaveFile, "ไม่สามารถบันทึกไฟล์");
	strcpy(sCenter, "ศูนย์");

	strcpy(sChangeDirection, "เปลี่ยนทิศทางการตัด");
	strcpy(sChoose, "เลือก");
	strcpy(sChooseProduct, "เลือกผลิตภัณฑ์");
	strcpy(sCircle, "วงกลม");
	strcpy(sCity, "เมือง");
	strcpy(sClear, "ชัดเจน");
	strcpy(sClockWise, "ตามเข็มนาฬิกา");
	strcpy(sClosewindow, "ปิดหน้าต่าง");
	strcpy(sColor, "สี");
	strcpy(sColorofedgeband, "สีของแถบขอบ");
	strcpy(sColorPattern, "สี / รูปแบบ");
	strcpy(sColorpiecesandwastes, "ชิ้นสีและของเสีย");
	strcpy(sColumns, "คอลัมน์");
	strcpy(sComment, "คิดเห็น");
	strcpy(sCompanyname, "ชื่อ บริษัท");
	strcpy(sComplexMaterialExists, "ชื่อวัสดุถูกกำหนดไว้แล้วในรายการวัสดุที่ซับซ้อน กรุณาตั้งชื่อใหม่");
	strcpy(sComputerCode, "รหัสคอมพิวเตอร์");
	strcpy(sComputerCodefromyourcomputer, "รหัสคอมพิวเตอร์ (จากคอมพิวเตอร์ของคุณ)");
	strcpy(sComputethetotalpriceofDemand, "คำนวณราคารวมของชิ้นส่วน");
	strcpy(sContents, "สารบัญ");
	strcpy(sContinutComanda, "เนื้อหาของชิ้นส่วนในวันที่");
	strcpy(sContinutDepozit, "เนื้อหาของหุ้นในวันที่");
	strcpy(sConversionIsDoneOnlyWhenSomePiecesHaveFractionalValues, "การแปลงจะทำได้ก็ต่อเมื่อบางชิ้นมีค่าเศษส่วน");
	strcpy(sConvertsTheSizeOfWasteToAFractionalUnit, "แสดงขนาดของเศษเหล็กเป็นค่าเศษส่วน");
	strcpy(sCouldNotSaveFile1, "ไม่สามารถเขียนไฟล์ในไดเรกทอรี");
	strcpy(sCouldNotSaveFile2, "คุณอาจมีสิทธิ์ไม่เพียงพอ โปรดตรวจสอบหรือเปลี่ยนไดเรกทอรีทำงานจากเมนูการตั้งค่า | ไดเรกทอรีทำงานไปยังโฟลเดอร์ที่คุณมีสิทธิ์เขียน (เช่น c: \\ temp)");
	strcpy(sCreationdateYMDHMS, "วันที่สร้าง (Y / M / D- H: M: S)");
	strcpy(sCurrentDate, "วันที่ปัจจุบัน");
	strcpy(sCurrentDiagram, "แผนภาพปัจจุบัน");
	strcpy(sCurrentMaterial, "วัสดุปัจจุบัน");
	strcpy(sCurrentversion, "รุ่นปัจจุบัน");
	strcpy(sCurve_not_closed_Try_increasing_DXF_linking_distance_parameter, "รูปหลายเหลี่ยมไม่ปิด! ลองเพิ่มพารามิเตอร์ ระยะทางเชื่อมโยง DXF");
	strcpy(sCustomer, "ลูกค้า");
	strcpy(sCustomerName, "ชื่อลูกค้า");
	strcpy(sCustomMessage, "ข้อความที่กำหนดเอง");
	strcpy(sCutlength, "ความยาวของการกรีด");
	strcpy(sCut, "ตัด");
	strcpy(sCuts, "ตัด");
	strcpy(sCutterThickness, "ตัดความหนา");
	strcpy(sData, "ข้อมูล");
	strcpy(sDataCannotBeEmpty, "ข้อมูลต้องไม่ว่างเปล่า!");
	strcpy(sDateymdhms, "วันที่ (y / d / m / H / m / s)");
	strcpy(sDays_left_for_trial, "เหลืออีกวันสำหรับทดลองใช้");
	strcpy(sDaysLeft, "วันที่เหลือ");
	strcpy(sStandard, "ค่าเริ่มต้น");
	strcpy(sDefaultInterface, "อินเตอร์เฟสเริ่มต้น");
	strcpy(sDefects, "ข้อบกพร่อง");
	strcpy(sDefectsManager, "จัดการข้อบกพร่อง");
	strcpy(sDefectsofthematerialNopiecescanbeplacedinthefaultyzone, "ข้อบกพร่องของวัสดุ ไม่สามารถวางชิ้นส่วนใด ๆ ในโซนที่ผิดปกติได้");
	strcpy(sDelete, "ลบ");
	strcpy(sDeletePiece, "ลบชิ้นส่วน");
	strcpy(sDeleteRow, "ลบแถว");
	strcpy(sDemandutilization, "การใช้ชิ้นส่วน");
	strcpy(sDepozitulmodificat, "นำชิ้นส่วนที่ใช้แล้วออกไป เพิ่มเศษเหล็กลงในสต็อคแล้ว");
	strcpy(sDepozitvid, "สต็อกว่างเปล่า");
	strcpy(sDesk, "เคาน์เตอร์");
	strcpy(sDiagram, "แผนภาพ");
	strcpy(sDiagrams, "ไดอะแกรม");
	strcpy(sDiagramasatable, "แผนภาพเป็นตาราง");
	strcpy(sDigits, "ตัวเลข");
	strcpy(sDimensiuniplaca, "ขนาดของแผ่น");
	strcpy(sDirection, "ทิศทาง");
	strcpy(sDistanceBetweenRows, "ระยะห่างระหว่างแถว");
	strcpy(sDonotuseit, "อย่าใช้มัน");
	strcpy(sDownload, "ดาวน์โหลด");
	strcpy(sDoYouWantToClearTheData, "คุณต้องการลบข้อมูลหรือไม่");
	strcpy(sDoYouWantToSaveDemand, "ชิ้นส่วนมีการเปลี่ยนแปลง! คุณต้องการบันทึกการเปลี่ยนแปลงหรือไม่?");
	strcpy(sDoYouWantToSaveParts, "คุณต้องการบันทึกชิ้นส่วนหรือไม่?");
	strcpy(sDoYouWantToSaveRepository, "หุ้นมีการเปลี่ยนแปลง! คุณต้องการบันทึกการเปลี่ยนแปลงหรือไม่?");
	strcpy(sDrawing, "การวาดภาพ");
	strcpy(sDrawthesolutioncolorful, "วาดวิธีแก้ปัญหาที่มีสีสัน");
	strcpy(sDuplicateTypes, "บางประเภทซ้ำกัน! โปรดลบรายการที่ซ้ำกัน");
	strcpy(sDuplicateTypesWithComplex, "มีชื่อวัสดุบางส่วนอยู่ในรายการประเภทที่ซับซ้อนแล้ว! โปรดลบรายการที่ซ้ำ");
	strcpy(sDuplicateValues, "ค่าซ้ำ");
	strcpy(sEdgeband, "แถบขอบ");
	strcpy(sEdgebandingwhichisplacedontheedgesofyourpiecePleasedefineedgebandingtypesfromMaterialsEdgeBandingmenu, "แถบขอบจะถูกวางไว้บนขอบของชิ้นของคุณ โปรดกำหนดแถบขอบในเมนูวัสดุ");
	strcpy(sEdgebandsthatwillbeappliedtoeachpart, "แถบขอบที่ใช้กับแต่ละชิ้น");
	strcpy(sEdgeBandTolerance, "ความอดทนสำหรับแถบขอบ");
	strcpy(sEdgesthatmustbecutduefaults, "ขอบที่ต้องถูกตัดเนื่องจากข้อบกพร่อง");
	strcpy(sEdgetoedge, "จากขอบจรดขอบ");
	strcpy(sEdit, "แก้ไข");
	strcpy(sEmail, "อีเมล์");
	strcpy(sEmptyData, "ข้อมูลว่างเปล่า!");
	strcpy(sEnabled, "เปิดการใช้งาน");
	strcpy(sEnabledisabledefectsoftheinventorysheets, "เปิด / ปิดการใช้งานข้อบกพร่องของหุ้น");
	strcpy(sEnterLabel, "ป้อนฉลาก");
	strcpy(sEnterTheMaterialName, "ป้อนชื่อของวัสดุ");
	strcpy(sEnterTheProductName, "ป้อนชื่อผลิตภัณฑ์");
	strcpy(sEvaluationError, "ข้อผิดพลาดในการประเมินผลการแสดงออก!");
	strcpy(sExit, "ทางออก");
	strcpy(sExpired, "ซอฟต์แวร์หมดอายุ! กรุณาลงทะเบียนซอฟต์แวร์!");
	strcpy(sExport, "ส่งออก");
	strcpy(sExportAllDiagrams, "ส่งออกไดอะแกรมทั้งหมด");
	strcpy(sExportAllToASingleFile, "ส่งออกทั้งหมดเป็นไฟล์เดียว");
	strcpy(sExportOptions, "ตัวเลือกการส่งออก");
	strcpy(sExporttoDXFformat, "ส่งออกเป็นรูปแบบ DXF");
	strcpy(sExporttoExcel, "ส่งออกไปยัง Excel");
	strcpy(sExpresieIncorecta, "การแสดงออกทางคณิตศาสตร์ไม่ถูกต้อง!");
	strcpy(sExtensions, "Extensions");
	strcpy(sExtra, "พิเศษ");
	strcpy(sExtraComponents, "ส่วนประกอบพิเศษ");
	strcpy(sExtracomponentsattachedtoDemand, "ส่วนประกอบพิเศษที่แนบมากับชิ้นส่วน");
	strcpy(sFile, "ไฟล์");
	strcpy(sFileName, "ชื่อไฟล์");
	strcpy(sFillWastes, "วาดของเสียด้วยเส้นเฉียง");
	strcpy(sFindoptimalbarsheetsize, "ค้นหาขนาดที่เหมาะสมที่สุดสำหรับบาร์และแผ่น");
	strcpy(sFindoptimalsizeofInventorypieces, "ค้นหาขนาดที่เหมาะสมที่สุดของชิ้นส่วนสต็อก");
	strcpy(sFirstcutMultiplestages, "ทิศทางการตัดแรกสำหรับการปรับให้เหมาะสมหลายขั้นตอน");
	strcpy(sFirstdirectionforcutishorizontal, "ทิศทางแรกสำหรับการตัดเป็นแนวนอน");
	strcpy(sFirstdirectionforcutisvertical, "ทิศทางแรกสำหรับการตัดเป็นแนวตั้ง");
	strcpy(sFollowthecontourofpieces, "ตามรูปร่างของชิ้น");
	strcpy(sFont, "ตัวอักษร");
	strcpy(sFontsize, "ขนาดตัวอักษร");
	strcpy(sFullInfo, "ข้อมูลที่สมบูรณ์");
	strcpy(sDisposedWaste, "กำจัดของเสีย");
	strcpy(sGeneral, "ทั่วไป");
	strcpy(sGenerateCNC, "สร้าง CNC");
	strcpy(sGrain, "เนื้อผ้า");
	strcpy(sGraindirection, "ทิศทางพื้นผิว");
	strcpy(sGraphic, "กราฟฟิค");
	strcpy(sGreaterorequalto, "มากกว่าหรือเท่ากับ");
	strcpy(sGrid, "ตาราง");
	strcpy(sGrinding, "ที่บด");
	strcpy(sGrosimeTaieturaScalata, "ความหนาในการตัดจากภาพนี้อาจแตกต่างจากของจริงเพราะชิ้นงานไม่ได้แสดงตามขนาดที่แท้จริง ความจริงนี้ไม่มีผลต่อผลลัพธ์");
	strcpy(sGroupidenticallayouts, "การจัดกลุ่มของแผ่นงานที่เหมือนกัน");
	strcpy(sGroupIdenticalParts, "จัดกลุ่มชิ้นส่วนที่เหมือนกัน");
	strcpy(sGroupingOfIdenticalPiecesIntoOneRow, "จัดกลุ่มชิ้นส่วนที่เหมือนกันเป็นหนึ่งแถว");
	strcpy(sGroupPartsAfterLoadingFromFile, "จัดกลุ่มชิ้นส่วนเมื่อโหลดจากไฟล์");
	strcpy(sHeight, "ความสูง");
	strcpy(sHeighttolerance, "ความอดทนต่อความสูง");
	strcpy(sHelp, "ช่วยด้วย");
	strcpy(sHistory, "ประวัติศาสตร์");
	strcpy(sHorizontal, "ตามแนวนอน");
	strcpy(sHowtodisplayprintedgebands, "แถบขอบจะแสดงอย่างไร?");
	strcpy(sIfyousetthebandforoneedgeallwillreceivethesamevalue, "หากคุณตั้งค่าแบนด์สำหรับขอบหนึ่งขอบทั้งหมดจะได้รับค่าเดียวกัน");
	strcpy(sIfyousetthegrindingforoneedgeallwillreceivethesamevalue, "หากคุณตั้งค่าการเจียรสำหรับขอบหนึ่งขอบทั้งหมดจะได้รับค่าเดียวกัน");
	strcpy(sIfyousetthetrimforoneedgeallwillreceivethesamevalue, "หากคุณตั้งค่าการตัดขอบสำหรับขอบหนึ่งขอบทั้งหมดจะได้รับค่าเดียวกัน");
	strcpy(sImageBounds, "ขอบเขตสำหรับรูปภาพ");
	strcpy(sImageSize, "ขนาดรูปภาพ");
	strcpy(sImportData, "นำเข้าข้อมูล");
	strcpy(sIncorrectPassword, "รหัสผ่านผิดพลาด");
	strcpy(sIndex, "ดัชนี");
	strcpy(sInformationaboutcustomer, "ข้อมูลเกี่ยวกับลูกค้า");
	strcpy(sInputALanguageName, "ป้อนชื่อของภาษา");
	strcpy(sInsert, "แทรก");
	strcpy(sInsertPiece, "ชิ้นส่วนแทรก");
	strcpy(sInterface, "อินเตอร์เฟซ");
	strcpy(sInterfaceSettings, "การตั้งค่าอินเตอร์เฟซ");
	strcpy(sInvalidHardware, "ฉันไม่สามารถตรวจพบฮาร์ดแวร์ กรุณาติดต่อเราได้ที่ contact@optimalprograms.com");
	strcpy(sInvalidNumber, "หมายเลขไม่ถูกต้อง");
	strcpy(sInvalidOrderOfComputation, "ไม่สามารถสร้างคำสั่งสำหรับคำนวณความยาวได้ มีความสัมพันธ์แบบวงกลมในการกำหนดผลิตภัณฑ์!");
	strcpy(sInvalidRegistration, "การลงทะเบียนไม่ถูกต้อง!");
	strcpy(sInvalidTime, "เวลาของระบบของคุณไม่ถูกต้อง");
	strcpy(sInventory, "คลังสินค้า");
	strcpy(sisafractionalvalue, "เป็นค่าเศษส่วน");
	strcpy(sIsArc, "เป็นส่วนโค้ง");
	strcpy(sisarealvalue, "เป็นมูลค่าที่แท้จริง");
	strcpy(sLabel, "ฉลาก");
	strcpy(sLabels, "ป้ายกำกับ");
	strcpy(sLanguage, "ภาษา");
	strcpy(sLatimeanumar0, "ความกว้างต้องมากกว่า 0!");
	strcpy(sLatimeanumarreal, "ความกว้างจะต้องเป็นจำนวนจริง!");
	strcpy(sLayerName, "ชื่อของเลเยอร์");
	strcpy(sLeft, "ซ้าย");
	strcpy(sLeftcoordinateofthedefect, "พิกัดด้านซ้ายของข้อบกพร่อง");
	strcpy(sLength, "ความยาว");
	strcpy(sLengthofthepiecestocut, "ขนาดชิ้นส่วนสำหรับตัด");
	strcpy(sLengthofthepiecestocutfrom, "ขนาดแผ่นสำหรับการตัด");
	strcpy(sLengthofusedbars, "ขนาดของแท่งที่ใช้แล้ว");
	strcpy(sLicenseAgreement, "ข้อตกลงใบอนุญาต");
	strcpy(sLinear, "เชิงเส้น");
	strcpy(sLinethickness, "ความหนาของปากกา");
	strcpy(sLoadafileandappenddatatothecurrentDemand, "โหลดไฟล์และผนวกข้อมูลไปยังส่วนปัจจุบัน");
	strcpy(sLoadanexistingDemandfromafile, "โหลดชิ้นส่วนที่มีอยู่จากไฟล์");
	strcpy(sLoadAppend, "โหลดและต่อท้าย");
	strcpy(sLoadEverything, "โหลดทุกอย่าง");
	strcpy(sLoadInventory, "โหลดสต็อก");
	strcpy(sLoadInventoryandDemand, "โหลดสต็อกและชิ้นส่วน");
	strcpy(sLoadResults, "โหลดผลลัพธ์");
	strcpy(sLocked, "ล็อค");
	strcpy(sLogo, "เครื่องหมาย");
	strcpy(sLong, "ยาว");
	strcpy(sLongerexecutiontime, "เวลาทำงานอีกต่อไป");
	strcpy(sLungime, "ความยาว");
	strcpy(sLungimeanumar0, "ความยาวต้องมากกว่า 0!");
	strcpy(sLungimeanumarreal, "ความยาวต้องเป็นจำนวนจริง!");
	strcpy(sLungimeaTotalaFolosita, "ความยาวที่ใช้ทั้งหมด");
	strcpy(sMagnification, "การขยายภาพ");
	strcpy(sMagnify, "ขยาย");
	strcpy(sMargins, "อัตรากำไรขั้นต้น");
	strcpy(sMarginsForPaper, "ระยะขอบสำหรับกระดาษ");
	strcpy(sMarginsOfTheLabel, "ระยะขอบของฉลาก");
	strcpy(sMaterial, "วัสดุ");
	strcpy(sMaterialName, "ชื่อของวัสดุ");
	strcpy(sMaterials, "วัสดุ");
	strcpy(sMaterialstypes, "ประเภทวัสดุ");
	strcpy(sMax, "แม็กซ์");
	strcpy(sMaximalArea, "พื้นที่สูงสุด");
	strcpy(sMaximalCutLength, "ความยาวตัดสูงสุด");
	strcpy(sMaxlength, "ความยาวสูงสุด");
	strcpy(sMaxPiecesperBar, "จำนวนชิ้นสูงสุดต่อบาร์");
	strcpy(sMaxwidth, "ความกว้างสูงสุด");
	strcpy(sMeasurementUnit, "หน่วยวัด");
	strcpy(sMin, "นาที");
	strcpy(sMinimalBreakSize, "ขนาดแตกหักน้อยที่สุด");
	strcpy(sMinimalUsefulSize, "ขนาดที่มีประโยชน์น้อยที่สุด");
	strcpy(sMinimalwastesizetoInventory, "เพิ่มขนาดเศษเหล็กขั้นต่ำในสต็อค");
	strcpy(s_What_to_minimize, "อะไรที่จะย่อขนาด?");
	strcpy(sMinlength, "ความยาวน้อยที่สุด");
	strcpy(sMinwidth, "ความกว้างน้อยที่สุด");
	strcpy(sMirror, "กระจกเงา");
	strcpy(sMirroring, "มิเรอร์");
	strcpy(sMiscellaneous, "สถิติอื่น ๆ");
	strcpy(sModify, "ปรับเปลี่ยน");
	strcpy(sModifytheselectedpiece, "แก้ไขชิ้นส่วนที่เลือก");
	strcpy(sMovePiece, "ย้ายชิ้นส่วน");
	strcpy(sMultiplestages, "หลายขั้นตอน");
	strcpy(sName, "ชื่อ");
	strcpy(sNameofedgeband, "ชื่อของแถบขอบ");
	strcpy(sNewDEMANDUnsaveddatawillbelost, "อะไหล่ใหม่ ข้อมูลที่ไม่ได้บันทึกจะสูญหายไป!");
	strcpy(sNewLanguage, "ภาษาใหม่");
	strcpy(sNewMaterial, "วัสดุใหม่");
	strcpy(sNewPasswordincorectlyintroduced, "รหัสผ่านใหม่ที่แนะนำไม่ถูกต้อง!");
	strcpy(sNewProduct, "ผลิตภัณฑ์ใหม่");
	strcpy(sNewversion, "เวอร์ชั่นใหม่");
	strcpy(sNo, "ไม่");
	strcpy(sNumarBucati, "จำนวนชิ้น");
	strcpy(sNumberOfCopies, "จำนวนสำเนา");
	strcpy(sNumberofstages, "จำนวนสเตจ");
	strcpy(sNusuficienteplacidepozit, "ไม่ใช่ทุกชิ้นที่ได้รับการปรับให้เหมาะสม สาเหตุที่เป็นไปได้: สต็อกสินค้ามีไม่เพียงพอ ไม่ได้เปิดใช้งานส่วนต่างๆ วัสดุของชิ้นส่วนและสต็อกจะแตกต่างกัน ตั้งค่าพารามิเตอร์อื่นไม่ถูกต้อง");
	strcpy(sOfficeNotInstaled, "ไม่ได้ติดตั้ง Microsoft Office ลงในคอมพิวเตอร์ของคุณหรือติดตั้งรุ่นที่ไม่ถูกต้อง!");
	strcpy(sOldpassworddoesnotmatch, "รหัสผ่านเก่าไม่ตรงกัน!");
	strcpy(sOnlinehelp, "ความช่วยเหลือออนไลน์");
	strcpy(sOnlypiecesofthesameheightinthelaststage, "ชิ้นส่วนของความสูงเดียวกันในระยะสุดท้าย");
	strcpy(sOpen, "เปิด");
	strcpy(sOptimization, "การเพิ่มประสิทธิภาพ");
	strcpy(sOptimizationDone, "ดำเนินการเพิ่มประสิทธิภาพ! คุณสามารถพิมพ์หรือบันทึกไดอะแกรมที่ได้รับ กดปุ่มยอมรับถ้าคุณพอใจกับโซลูชันปัจจุบัน มิฉะนั้นกดเริ่มอีกครั้ง");
	strcpy(sOptimizationType, "ประเภทการเพิ่มประสิทธิภาพ");
	strcpy(sOptions, "ตัวเลือก");
	strcpy(sOptionsrelatedtotheinterface, "ตัวเลือกที่เกี่ยวข้องกับอินเทอร์เฟซ");
	strcpy(sor, "หรือ");
	strcpy(sOthercomponents, "ส่วนประกอบอื่น ๆ");
	strcpy(sOthers, "คนอื่น ๆ");
	strcpy(sOtherstatistics, "สถิติอื่น ๆ");
	strcpy(sOverrideExcelCSVfiles, "แทนที่ไฟล์ Excel / CSV");
	strcpy(sParameter, "พารามิเตอร์");
	strcpy(sParts, "ชิ้น");
	strcpy(sPattern, "ลวดลาย");
	strcpy(sPatternforwaste, "ลวดลายสำหรับเศษเหล็ก");
	strcpy(sPerimeter, "ปริมณฑล");
	strcpy(sPermitedRotationAngle, "อนุญาตให้หมุนมุม");
	strcpy(sPhone, "โทรศัพท์");
	strcpy(sPicture, "ภาพ");
	strcpy(sPiece, "ชิ้น");
	strcpy(sPieceindex, "ดัชนีของชิ้น");
	strcpy(sPieces, "ชิ้น");
	strcpy(sPiecesize, "ขนาดชิ้น");
	strcpy(sPiecesizelabeledgebandwillbeprinted, "ขนาดชิ้นส่วนฉลากวงดนตรีขอบจะถูกพิมพ์");
	strcpy(sPierdere, "เศษ");
	strcpy(sPixels, "พิกเซล");
	strcpy(sPlacilefolositeDepozit, "ใช้ประโยชน์จากสต็อก");
	strcpy(sPlease_contact_us_at_contact_nestingtechnologies_com, "กรุณาติดต่อเราได้ที่ contact@nesting-technologies.com");
	strcpy(sPlease_contact_us_at_contact_optimalprograms_com, "กรุณาติดต่อเราได้ที่ contact@optimalprograms.com");
	strcpy(sPleaseenteralldataeitherasfractionalorrealDonotmixthem, "โปรดป้อนข้อมูลทั้งหมดไม่ว่าจะเป็นค่าเศษส่วนหรือค่าจริง! อย่าผสมพวกเขา!");
	strcpy(sPleaseEnterSomeTypesOfMaterials, "ไม่มีการกำหนดประเภทของวัสดุ คุณสามารถกำหนดได้จากเมนูวัสดุ");
	strcpy(sPleasesendtheNameandtheCodetotheaddresscontactoptimalprogramscominordertoobtaintheRegistrationKey, "ในการรับรหัสลงทะเบียนโปรดส่งชื่อและรหัสไปที่: contact@optimalprograms.com");
	strcpy(sPolygon, "รูปหลายเหลี่ยม");
	strcpy(sPolygonsCircles, "รูปหลายเหลี่ยมวงกลม");
	strcpy(sPrecision, "ความแม่นยำ");
	strcpy(sPretulnumar0, "ราคาจะต้องมากกว่า 0!");
	strcpy(sPretulnumarreal, "ราคาต้องเป็นจำนวนจริง!");
	strcpy(sPreview, "ดูตัวอย่าง");
	strcpy(sPrice, "ราคา");
	strcpy(sPriceMustBeGreaterThanZero, "ราคาจะต้องมากกว่าศูนย์");
	strcpy(sPriceofbars, "ราคาของบาร์");
	strcpy(sPriceperbar, "ราคาต่อบาร์");
	strcpy(sPricepersheet, "ราคาต่อแผ่น");
	strcpy(sPricepersquareunitofmaterial, "ราคาต่อหน่วยของวัสดุตาราง");
	strcpy(sPriceperunit, "ราคาต่อหน่วย");
	strcpy(sPrint, "พิมพ์");
	strcpy(sPrintdiagramsastables, "พิมพ์ไดอะแกรมเป็นตาราง");
	strcpy(sPrinter, "เครื่องพิมพ์");
	strcpy(sPrinterBounds, "ระยะขอบสำหรับเครื่องพิมพ์");
	strcpy(sPrinting, "การพิมพ์");
	strcpy(sPrintonlyutilizedarea, "พิมพ์เฉพาะพื้นที่ที่ใช้");
	strcpy(sPrintthecontentsoftheDemand, "พิมพ์เนื้อหาของชิ้นส่วน");
	strcpy(sPrintthecontentsoftheInventory, "พิมพ์เนื้อหาของหุ้น");
	strcpy(sPrintthecurrentsolution, "พิมพ์ทางออกปัจจุบัน");
	strcpy(sPriority, "ลำดับความสำคัญ");
	strcpy(sPrioritytocutapieceZero0isthehighestpriority, "ลำดับความสำคัญในการตัดชิ้นงาน ศูนย์ (0) เป็นลำดับความสำคัญสูงสุด");
	strcpy(sProcentul0100, "ร้อยละจะต้องมากกว่า 0 และน้อยกว่าหรือเท่ากับ 100!");
	strcpy(sProcentulnumarreal, "ร้อยละจะต้องเป็นจำนวนจริง!");
	strcpy(sProductdefinition, "คำจำกัดความของผลิตภัณฑ์");
	strcpy(sProductExists, "มีผลิตภัณฑ์อยู่แล้ว เลือกชื่ออื่น");
	strcpy(sProductName, "ชื่อผลิตภัณฑ์");
	strcpy(sProducts, "ผลิตภัณฑ์");
	strcpy(sProducts, "ผลิตภัณฑ์");
	strcpy(sProject, "โครงการ");
	strcpy(sProperties, "คุณสมบัติ");
	strcpy(sProperty, "คุณสมบัติ");
	strcpy(sQuantity, "ปริมาณ");
	strcpy(sQuantitynumberofsheetsofthistype, "จำนวนแผ่นประเภทนี้");
	strcpy(sRadius, "รัศมี");
	strcpy(sRectangular, "เป็นมุมฉาก");
	strcpy(sRedefinetypesofedgeband, "กำหนดวงขอบประเภทใหม่");
	strcpy(sRedefinetypesofmaterial, "กำหนดประเภทของวัสดุใหม่");
	strcpy(sRegistration, "การลงทะเบียน");
	strcpy(sRegistrationKeyfromOptimalPrograms, "รหัสลงทะเบียน");
	strcpy(sRegistrationSuccessful, "การลงทะเบียนสำเร็จ!");
	strcpy(sRemoveallpiecesinInventory, "ลบชิ้นส่วนทั้งหมดในสินค้าคงคลัง");
	strcpy(sRemoveCut, "ลบการตัด");
	strcpy(sRemovetheselectedpiece, "ลบชิ้นส่วนที่เลือก");
	strcpy(sReports, "รายงาน");
	strcpy(sRequestedMaterial, "วัสดุที่ร้องขอ");
	strcpy(sRestore, "ฟื้นฟู");
	strcpy(sResults, "ผล");
	strcpy(sReusedwaste, "ขยะนำกลับมาใช้ใหม่");
	strcpy(sRight, "ขวา");
	strcpy(sRightcoordinateofthedefect, "พิกัดของความบกพร่องจากด้านขวา");
	strcpy(sRotation, "การหมุน");
	strcpy(sRotationAngle, "มุมการหมุน");
	strcpy(sRotationStep, "ขั้นตอนการหมุน");
	strcpy(sRoundAllFractionsTo, "ค่าเศษส่วนต้องปัดเศษเป็น");
	strcpy(sRow, "แถว");
	strcpy(sRows, "แถว");
	strcpy(sRun, "โซลูชั่นล่าสุด");
	strcpy(sRunningtime, "เวลาทำงาน");
	strcpy(sSameforall, "เหมือนกันสำหรับทุกคน");
	strcpy(sSave, "บันทึก");
	strcpy(sSaveAllImages, "บันทึกภาพทั้งหมด");
	strcpy(sSaveAs, "บันทึกเป็น");
	strcpy(sSaveChanges, "ชิ้นส่วนมีการเปลี่ยนแปลง คุณต้องการที่จะบันทึกพวกเขา?");
	strcpy(sSaveCurrentImage, "บันทึกภาพปัจจุบัน");
	strcpy(sSavedataparameters, "บันทึกข้อมูลและพารามิเตอร์");
	strcpy(sSaveEverything, "บันทึกทุกอย่าง");
	strcpy(sSaveInventory, "บันทึกสินค้าคงคลัง");
	strcpy(sSaveInventoryandDemand, "บันทึกสต็อคและชิ้นส่วน");
	strcpy(sSaveResults, "บันทึกผลลัพธ์");
	strcpy(sSaveStatisticsinafile, "บันทึกสถิติในไฟล์");
	strcpy(sSavethecurrentimage, "บันทึกภาพปัจจุบัน");
	strcpy(sSavethecurrentimageorstatistic, "บันทึกภาพปัจจุบันหรือสถิติ");
	strcpy(sSavetheDEMANDinafile, "บันทึกลงไฟล์");
	strcpy(sSavetheDemandinafilewithadifferentname, "บันทึกชิ้นส่วนในไฟล์ด้วยชื่ออื่น");
	strcpy(sSavetheREPOSITORYinafile, "บันทึกสต็อคในไฟล์");
	strcpy(sSerialNumber, "รหัสลงทะเบียน");
	strcpy(sService, "บริการ");
	strcpy(sSetDefaultValues, "สิ่งนี้จะคืนค่าพารามิเตอร์ทั้งหมดเป็นค่าเริ่มต้น การตั้งค่าทั้งหมดของคุณจะหายไป คุณแน่ใจหรือว่าต้องการทำสิ่งนี้");
	strcpy(sSetedgeband, "ตั้งแถบขอบ");
	strcpy(sSetedgetrim, "กำหนดขนาดการตัดสำหรับข้อบกพร่องของระยะขอบ");
	strcpy(sSetthesameedgebandforalledges, "ตั้งแถบขอบที่เหมือนกันสำหรับทุกด้าน");
	strcpy(sSetthesamegrindingforalledges, "ตั้งค่าการเจียรแบบเดียวกันสำหรับทุกขอบ");
	strcpy(sSetthesametrimforalledges, "ตั้งค่าการตัดเดียวกันสำหรับข้อบกพร่องสำหรับขอบทั้งหมด");
	strcpy(sSettings, "การตั้งค่า");
	strcpy(sShape, "รูปร่าง");
	strcpy(sSheet, "แผ่น");
	strcpy(sSheetsBarstypes, "ประเภทแผ่น_บาร์");
	strcpy(sSheetSize, "ขนาดของแผ่น");
	strcpy(sSheetsperPage, "แผ่นต่อหน้า");
	strcpy(sShort, "สั้น");
	strcpy(sShorterexecutiontime, "ใช้เวลาสั้น ๆ");
	strcpy(sShowallsimpleproducts, "แสดงผลิตภัณฑ์ที่เรียบง่ายทั้งหมด");
	strcpy(sShowcustomername, "แสดงชื่อลูกค้า");
	strcpy(sShowCustomTextOnEachPiece, "แสดงข้อความที่กำหนดเองในแต่ละชิ้น");
	strcpy(sShowdiagramasatable, "แสดงแผนภาพเป็นตาราง");
	strcpy(sShowedgeband, "แสดงแถบขอบ");
	strcpy(sShowedgebandssettinginanewwindow, "แสดงการตั้งค่าของแถบขอบในหน้าต่างใหม่");
	strcpy(sShowgrindingsettingsinanewwindow, "แสดงการตั้งค่าที่คัฟในหน้าต่างใหม่");
	strcpy(sShowHorizontalLabelsAlways, "แสดงป้ายกำกับแนวนอนเสมอ");
	strcpy(sShowRemovethesizeofthepiecesinthecurrentsolution, "แสดง / ซ่อนขนาดของชิ้นส่วน");
	strcpy(sShowRemovethesizeofthewastesinthecurrentsolution, "แสดง / ซ่อนขนาดของเรื่องที่สนใจ");
	strcpy(sShowtotalcutlength, "แสดงความยาวตัดทั้งหมด");
	strcpy(sShowtrimedgesettingsinanewwindow, "แสดงการตั้งค่าข้อบกพร่องในหน้าต่างใหม่");
	strcpy(sSimpleMaterialExists, "มีการกำหนดชื่อวัสดุแล้วในรายการวัสดุ กรุณาตั้งชื่อใหม่");
	strcpy(sSinglePieceStrips, "ลายเส้นของชิ้นเดียว");
	strcpy(sSizes, "ขนาด");
	strcpy(sSmallerorequalto, "เล็กกว่าหรือเท่ากับ");
	strcpy(sSort, "ประเภท");
	strcpy(sSortAscendingByArea, "เรียงตามพื้นที่ในลำดับ");
	strcpy(sSortDescendingByArea, "เรียงตามพื้นที่ในลำดับถัดลงมา");
	strcpy(sSpecifyhowdifferentthepiecesinthelaststagecanbeValue0meansnodifference, "ระบุความแตกต่างของชิ้นส่วนในระยะสุดท้าย ค่า 0 หมายถึงไม่แตกต่างกัน");
	strcpy(sSpecifyifpiecesinthelaststagecanbedifferentornotdepeultimaetapapotfidiferitesaunucadimensiune, "ระบุว่าชิ้นส่วนในระยะสุดท้ายอาจแตกต่างกันหรือไม่");
	strcpy(sSpecifyifthepiececanberotatedornotIfnotitwillbecutinthesamewayasitwasintroducedinDemandLengthofthepieceparalleltothelengthofthesheet, "ระบุว่าชิ้นส่วนสามารถหมุนได้หรือไม่ หากไม่เป็นเช่นนั้นมันจะถูกวางในลักษณะเดียวกับที่แนะนำ (ความยาวของชิ้นขนานกับความยาวของแผ่น)");
	strcpy(sSpecifyinhowmanystageswemakethecutsDuringastageallcutshavethesamedirection, "ระบุจำนวนขั้นตอนที่เราทำการตัด");
	strcpy(sStartthesearchprocess, "เริ่มกระบวนการค้นหา");
	strcpy(sStatistics, "สถิติ");
	strcpy(sStatisticsE, "รายงานพิเศษ");
	strcpy(sStatisticsforeachtypeofmaterial, "สถิติสำหรับวัสดุแต่ละประเภท");
	strcpy(sStep, "ขั้นตอน");
	strcpy(sStergeDepozit, "คุณต้องการที่จะลบสินค้าคงคลังหรือไม่");
	strcpy(sStergeMaterial, "คุณต้องการลบเนื้อหาหรือไม่");
	strcpy(sStergePiesele, "คุณต้องการที่จะลบชิ้นส่วน?");
	strcpy(sStergePiesa, "คุณต้องการที่จะลบชิ้นส่วน?");
	strcpy(sStopthesearchprocess, "หยุดกระบวนการค้นหา");
	strcpy(sStrongoptimization, "การเพิ่มประสิทธิภาพที่แข็งแกร่ง");
	strcpy(sSubtractthebandthicknessfrompiecesize, "ลดขนาดของชิ้นงานด้วยความหนาของแถบขอบ");
	strcpy(sSummary, "สรุป");
	strcpy(sSuprafataTotalaFolosita, "พื้นผิวที่ใช้ทั้งหมด");
	strcpy(sSuprafatautilizata, "การใช้ประโยชน์");
	strcpy(sSwitchbetweenfiberandrotationoption, "สลับระหว่างตัวเลือกไฟเบอร์และการหมุน");
	strcpy(sTechnical, "วิชาการ");
	strcpy(sTechnicalsettings, "การตั้งค่าทางเทคนิค");
	strcpy(sTemporaryPanelHint, "แผงชั่วคราวสำหรับชิ้นส่วนที่เคลื่อนไหวระหว่างแผ่น");
	strcpy(sText, "ข้อความ");
	strcpy(sThe_application_has_expired, "แอปพลิเคชันหมดอายุ");
	strcpy(sThe_application_is_not_registered, "แอปพลิเคชันไม่ได้ลงทะเบียน");
	strcpy(sThe_application_was_first_started_on, "แอปพลิเคชันเริ่มขึ้นครั้งแรก");
	strcpy(sThecutsareperformedfromasidetotheothersideofthematerial, "การตัดทำจากด้านหนึ่งไปอีกด้านหนึ่งของวัสดุ");
	strcpy(sThecuttingmachinecanfollowtheshapeofthematerial, "เครื่องตัดสามารถตามรูปร่างของชิ้นงาน");
	strcpy(sTheedgesofsheetsthatmustbetrimedduefaults, "ขอบของแผ่นงานที่ต้องถูกเล็มเพราะความผิดพลาด");
	strcpy(sTheLargestSize, "ขนาดที่ใหญ่ที่สุด");
	strcpy(sThenameofthecustomerforwhichyoucutthepiece, "ชื่อของลูกค้าที่คุณตัดส่วน");
	strcpy(sThenameofyourcustomer, "ชื่อลูกค้าของคุณ");
	strcpy(sThepiececanberotated, "ชิ้นส่วนสามารถหมุนได้");
	strcpy(sTheprogramtriestoavoidwasteswhichhavebothsizeslessthanthisvalue, "โปรแกรมพยายามหลีกเลี่ยงเศษที่น้อยกว่าค่านี้");
	strcpy(sThereAreNoProducts, "ยังไม่มีสินค้าที่กำหนดไว้");
	strcpy(sThestockofmaterialhasbeenpreviouslyloadedfromanExcelorCSVformatPleaseloaditagain, "ก่อนหน้านี้มีการโหลดสต็อควัสดุจากรูปแบบ Excel หรือ CSV โปรดโหลดอีกครั้งหากคุณต้องการใช้งาน");
	strcpy(sThetotallengthofcutting, "ความยาวรวมของการตัด");
	strcpy(sThewidthofthecuttingsawForglasscuttingoptimizationitcanbe0Forwooditshouldbegreaterthan0, "ความหนาของเลื่อย สำหรับการตัดกระจกสามารถเป็น 0 สำหรับไม้ควรมากกว่า 0");
	strcpy(sThewidthofthecuttingsawforlinearpieces, "ความหนาของเลื่อยสำหรับชิ้นส่วนที่เป็นเส้นตรง");
	strcpy(sThickness, "ความหนา");
	strcpy(sThischaracterisusedforfillingthewasterectanglesIfyoudonotwantfilledwastejustremovethischaracter, "สัญลักษณ์นี้ใช้สำหรับเติมรูปสี่เหลี่ยมผืนผ้าของเสีย หากคุณไม่ต้องการขยะที่เต็มไปเพียงแค่เอามันออก");
	strcpy(sThisindexhasvaluebetween1andthenumberofpieces, "ดัชนีนี้มีค่าระหว่าง 1 และจำนวนชิ้น");
	strcpy(sThisOptionWillOverrideTheInventoryFileIfLoadedFromExcelOrCsvFiles, "ตัวเลือกนี้จะแทนที่ไฟล์คลังโฆษณาหากโหลดจากไฟล์ excel หรือ csv");
	strcpy(sThisProgramisLicensedTo, "โปรแกรมนี้ได้รับอนุญาตให้");
	strcpy(sThisvaluewillbeaddedtotheedgebandingmaterialoneachside, "ค่านี้จะถูกเพิ่มเข้าไปในแถบขอบในแต่ละด้าน");
	strcpy(sTipNevid, "ประเภทของวัสดุต้องไม่ว่างเปล่า");
	strcpy(sTitle, "หัวข้อ");
	strcpy(sTools, "เครื่องมือ");
	strcpy(sTop, "ด้านบน");
	strcpy(sTopcoordinateofthedefect, "พิกัดสูงสุดของข้อบกพร่อง");
	strcpy(sTotalGarbageWaste, "เรื่องที่สนใจทั้งหมดที่ถูกทิ้ง");
	strcpy(sTotalInventoryWaste, "เศษซากทั้งหมด");
	strcpy(sTotalRecycledWaste, "เศษที่นำกลับมาใช้ใหม่ทั้งหมด");
	strcpy(sTotalusedarea, "รวมพื้นที่ใช้แล้ว");
	strcpy(sTotalusedlength, "ความยาวที่ใช้ทั้งหมด");
	strcpy(sTrigonometric, "เกี่ยวกับวิชาตรีโกณมิติ");
	strcpy(sTrim, "การตัดแต่ง");
	strcpy(sTrimalledgesatthebeginning, "ตัดขอบทั้งหมดที่จุดเริ่มต้น");
	strcpy(sTrimEdge, "ตัดขอบ");
	strcpy(sTwoPanels, "2 แผง");
	strcpy(sType, "ชนิด");
	strcpy(sTypeofmaterialfromwhichtocut, "ประเภทของวัสดุที่ใช้ตัด");
	strcpy(sTypesAreNotMatched, "ไม่ได้ดำเนินการปรับแต่งให้เหมาะสม! ตารางวัสดุจากอะไหล่และสต๊อกไม่ตรงกัน! สามารถตัดชิ้นส่วนได้เฉพาะจากวัสดุที่มีชื่อเดียวกันในสต็อกเท่านั้น เปลี่ยนชื่อวัสดุจากคอลัมน์ที่เกี่ยวข้อง!");
	strcpy(sUndo, "เลิกทำ");
	strcpy(sUndoAccept, "เลิกทำยอมรับ");
	strcpy(sUnits, "หน่วย");
	strcpy(sUnregisteredVersion, "เชลยศักดิ์");
	strcpy(sUpdates, "อัพเดท");
	strcpy(sUsefulforwoodfurniture, "มีประโยชน์สำหรับเฟอร์นิเจอร์ไม้");
	strcpy(sUseit, "ใช้มัน");
	strcpy(sUsePieceinOptimization, "ใช้ชิ้นส่วนในการเพิ่มประสิทธิภาพ");
	strcpy(sUserName, "ชื่อผู้ใช้");
	strcpy(sUtilizationandWastes, "การใช้และเศษเหล็ก");
	strcpy(sUtilizedArea, "พื้นที่ของชิ้นส่วนที่ใช้แล้ว");
	strcpy(sUtilizedBars, "แท่งที่ใช้ประโยชน์");
	strcpy(sUtilizeddemandcount, "จำนวนชิ้นส่วนที่ใช้แล้ว");
	strcpy(sUtilizedParts, "ส่วนที่ใช้ประโยชน์");
	strcpy(sUtilizedPieces, "ชิ้นส่วนที่ใช้ประโยชน์");
	strcpy(sUtilizedSheets, "แผ่นที่ใช้ประโยชน์");
	strcpy(sValue, "ราคา");
	strcpy(sValueGreaterEqualToZero, "ค่าต้องมากกว่าหรือเท่ากับศูนย์");
	strcpy(sValueGreaterThanZero, "ค่าต้องมากกว่าศูนย์");
	strcpy(sValueIntegerNumber, "ค่าต้องเป็นจำนวนเต็ม!");
	strcpy(sValueRealNumber, "ค่าต้องเป็นตัวเลขจริง บางทีคุณอาจใช้เครื่องหมายจุลภาคแทนระยะเวลาหรือ viceversa โปรดแก้ไขมัน!");
	strcpy(s_The_number_is_too_big_or_it_has_too_many_digits_after_decimal_separator, "ตัวเลขมีขนาดใหญ่เกินไปหรือมีตัวเลขมากเกินไปหลังจากตัวแยกทศนิยม!");
	strcpy(s_The_number_is_too_big, "เบอร์ใหญ่เกินไป!");
	strcpy(sVertical, "แนวตั้ง");
	strcpy(sWaste, "เศษ");
	strcpy(sWastes, "เศษ");
	strcpy(sWasteAddedToWarehouse, "เรื่องที่สนใจถูกเพิ่มเข้าไปในสต็อก");
	strcpy(sWastelimits, "ช่วงสำหรับเศษเหล็ก");
	strcpy(sWasteType, "ประเภทของเศษเหล็ก");
	strcpy(sWeakoptimization, "การเพิ่มประสิทธิภาพที่อ่อนแอที่สุด");
	strcpy(sWhattoprint, "ฉันควรพิมพ์อะไร");
	strcpy(s_What_to_print_or_save_to_file, "สิ่งที่จะพิมพ์หรือบันทึกเป็นไฟล์");
	strcpy(sWhattoprintoneachpiece, "สิ่งที่ต้องพิมพ์ในแต่ละชิ้น");
	strcpy(sWhattoshowoneachpiece, "สิ่งที่จะแสดงในแต่ละชิ้น?");
	strcpy(sWidth, "ความกว้าง");
	strcpy(sWood, "ไม้");
	strcpy(sWorkingDirectory, "โฟลเดอร์การทำงาน");
	strcpy(sWrongKey, "รหัสลงทะเบียนผิด!");
	strcpy(sYes, "ใช่");
	strcpy(sYoucannotchooseblackblueorredcolors, "คุณไม่สามารถเลือกสีดำน้ำเงินหรือแดง");
	strcpy(sYouCannotMixFractionalDataWithDecimalOnes, "คุณไม่สามารถผสมค่าเศษส่วนกับค่าจริง!");
	strcpy(sYourcompany, "บริษัท ของคุณ");
	strcpy(sZip, "รหัสไปรษณีย์");
	strcpy(s_Set_the_origin_and_the_direction_of_the_axes, "กำหนดจุดกำเนิดและทิศทางของแกนพิกัด");










	strcpy(s_Number_of_digits_after_the_decimal_separator, "จำนวนหลักหลังตัวคั่นทศนิยม");
	strcpy(s_Percentages, "เปอร์เซ็นต์");
}

