// Language strings: Malaesian
// Author: Optimal Programs
// License: MIT License
//---------------------------------------------------------------------------
#include <string.h>
//---------------------------------------------------------------------------
#include "language_string_id.h"
//---------------------------------------------------------------------------
void set_ml(void)
{
	//Malaesian
	//automatic translation
	//2025.3.29.0
	strcpy(s_Advanced, "Maju");
	strcpy(s_Relative_coordinates, "Koordinat relatif");
	strcpy(s_Absolute_coordinates, "Koordinat mutlak");
	strcpy(s_Append_more_rows, "Tambahkan lebih banyak baris");

	strcpy(s_Add_to_parts, "Tambah ke bahagian.");
	strcpy(s_Additional, "Tambahan");
	strcpy(s_All_results, "Semua keputusan.");
	strcpy(s_Allow_movement_of_pieces, "Benarkan pergerakan kepingan");
	strcpy(s_Allow_part_in_part, "Benarkan sekeping sekeping");
	strcpy(s_Invalid_piece_Angles_are_too_small_or_too_big_or_height_is_too_small, "Sekeping tidak sah! Sudut terlalu kecil atau terlalu besar, atau ketinggian terlalu kecil.");
	strcpy(s_Append, "Tambah");
	strcpy(s_As_it_is, "Seperti sedia ada");
	strcpy(s_As_text, "Sebagai teks");
	strcpy(s_Ascending, "Menaik");
	strcpy(s_Automatic, "Automatik");
	strcpy(s_Cannot_connect_to_the_Internet_Please_visit_our_website_from_a_browser, "Tidak dapat menyambung ke Internet! Sila lawati laman web kami dari penyemak imbas.");
	strcpy(s_Cannot_copy_or_move_the_files, "Tidak dapat menyalin atau memindahkan fail!");
	strcpy(s_Cannot_delete_the_file, "Tidak dapat memadam fail!");
	strcpy(s_Cannot_modify_old_results, "Tidak boleh mengubah suai hasil lama!");
	strcpy(s_To_change_click_inside_a_cell_or_press_0_1_or_2, "Untuk menukar, klik di dalam sel atau tekan 0, 1, atau 2.");
	strcpy(s_Cell, "sel");
	strcpy(s_Click_on_the_table_header_to_change_the_columns, "Klik pada pengepala jadual untuk menukar lajur.");
	strcpy(s_Close, "Tutupkan ia");
	strcpy(s_Contact_us, "Hubungi Kami");
	strcpy(s_Column, "Kolum");
	strcpy(s_Comma, "Koma");

	strcpy(s_Copy, "Salinan");
	strcpy(s_Copy_for_move, "Salin untuk bergerak");
	strcpy(s_Cut_higher_level_strips_first, "Potong jalur peringkat lebih tinggi dahulu");
	strcpy(s_Cut_index, "indeks potong");

	strcpy(s_The_data_have_been_changed_Do_you_want_to_save_them_to_a_file, "Data telah diubah. Adakah anda mahu menyimpannya ke fail?");
	strcpy(s_Decimal_separator, "Pemisah perpuluhan");
	strcpy(s_Restore_default_settings, "Pulihkan tetapan lalai");
	strcpy(s_Delete_fiber, "Padamkan serat");
	strcpy(s_Descending, "Menurun");
	strcpy(s_Discard_changes, "Membuang perubahan");

	strcpy(s_Delete_all_data, "Padamkan semua data?");
	strcpy(s_Dot, "titik");
	strcpy(s_Do_you_want_to_delete_the_picture, "Adakah anda mahu memadam gambar?");
	strcpy(s_Do_you_want_to_delete_the_product, "Adakah anda mahu memadamkan produk?");
	strcpy(s_Duplicate_and_append, "Gandakan dan tambahkan.");
	strcpy(s_Duplicate_values_are_ignored, "Nilai pendua tidak dihiraukan!");
	strcpy(s_Error, "Ralat");
	strcpy(s_Error_loading_file, "Ralat memuatkan fail.");
	strcpy(s_export_everything, "Eksport semuanya");
	strcpy(s_Fit_to_screen, "Sesuai dengan skrin.");
	strcpy(s_Force_fixed_height, "Lukis kepingan dengan ketinggian tetap.");
	strcpy(s_Flipped, "Terbalik");
	strcpy(s_Import, "Import");
	strcpy(s_If_angles_are_different_from_90_degrees_height_must_be_greater_than_0, "Jika sudut berbeza daripada 90 darjah, ketinggian mestilah lebih besar daripada 0.");
	strcpy(s_Ignore, "Abai");
	strcpy(s_Incorrect_value, "Nilai yang salah");
	strcpy(s_Info, "info");
	strcpy(s_Interior, "Dalaman");
	strcpy(s_Give_a_name, "Beri nama.");
	strcpy(s_Group, "Kumpulannya");
	strcpy(s_Header, "Kepala");
	strcpy(s_Keep_it_as_it_is, "Simpan seperti sedia kala");
	strcpy(s_Level, "Level");
	strcpy(s_Licensee, "Pemegang lesen");
	strcpy(s_List_separator, "Pemisah senarai");
	strcpy(s_Made_with_love_in_Cugir_Romania, "Dibuat, dengan cinta, di: Cugir, Romania");
	strcpy(s_Made_in, "Dikilangkan di");
	strcpy(s_Manufacturer, "Pengeluar");

	strcpy(s_Manual_arrange, "Susun manual");

	strcpy(s_Mixed, "Bercampur");
	strcpy(s_Multiple_shapes_detected_Next_rows_will_be_overwritten_Continue, "Lebih daripada satu bentuk telah dikesan. Oleh itu, baris berikutnya akan ditimpa. teruskan?");
	strcpy(s_More, "Lagi");
	strcpy(s_Multiple_values, "Berbilang nilai");
	strcpy(s_No_texture, "Tiada Tekstur");
	strcpy(s_Number, "Nombor");
	strcpy(s_Number_of_images, "Bilangan gambar");
	strcpy(s_Number_of_vertices, "Bilangan simpang");
	strcpy(s_Offset, "Offset");
	strcpy(s_Only_the_currently_selected_items, "Hanya item yang dipilih pada masa ini.");
	strcpy(s_Optimizing_please_wait, "Mengoptimumkan ... sila tunggu.");

	strcpy(s_Paste, "Paste");

	strcpy(s_Piece_label, "Label Piece");
	strcpy(s_Piece_size, "Saiz kepingan");
	strcpy(s_Please_contact_us_by_email_if_you_receive_this_error, "Sila hubungi kami melalui e-mel sekiranya anda menerima ralat ini.");
	strcpy(s_Please_save_it_first, "Tolong, simpan dahulu.");
	strcpy(s_Position, "Kedudukan");
	strcpy(s_Preview, "Pratonton");
	strcpy(s_Rectangle, "Segi empat");

	strcpy(s_Redo_the_last_operation, "Pulihkan operasi terakhir");
	strcpy(s_Regular_polygon, "Poligon tetap");

	strcpy(s_Reused, "Digunakan semula");
	strcpy(s_Rotated, "Berputar");
	strcpy(s_Save_all, "Simpan semua");
	strcpy(s_Scrap_label, "Label sekerap");
	strcpy(s_Scrap_size, "Saiz Scrap");
	strcpy(s_Semicolon, "Titik bertitik");
	strcpy(s_Show_cut_index, "indeks potong");
	strcpy(s_Show_information, "Tunjukkan maklumat");
	strcpy(s_Show_piece_label, "Label Piece");
	strcpy(s_Show_scrap_label, "Label sekerap");
	strcpy(s_Show_scrap_s_size_on_the_small_pieces, "Tunjukkan ukuran sekerap pada kepingan kecil");
	strcpy(s_Show_size_of_pieces, "Saiz kepingan");
	strcpy(s_Show_size_of_scrap, "Saiz Scrap");
	strcpy(s_Show_sizes, "Rodyti dydžius");
	strcpy(s_Show_label, "Tunjukkan label");
	strcpy(s_Show_length, "Tunjukkan panjang");

	strcpy(s_Some_numerical_values_are_incorrect_Should_I_fix_all_the_incorrect_values, "Beberapa nilai berangka tidak betul! Perlukah saya memperbaiki semua nilai yang salah?");
	strcpy(s_Some_invalid_values_have_been_removed, "Beberapa nilai tidak sah telah dialih keluar.");
	strcpy(s_Sort_by, "Disusun mengikut");
	strcpy(s_Sort_ascending_by, "Isih menaik mengikut");
	strcpy(s_Sort_descending_by, "Susun turun mengikut");
	strcpy(s_Start, "Start");
	strcpy(s_Starting_angle, "Sudut permulaan");


	strcpy(s_Stock, "Stok");
	strcpy(s_Stop, "Stop");

	strcpy(s_Tabular, "Jadual");
	strcpy(s_Total, "Jumlah");
	strcpy(s_Total_size, "Jumlah saiz");
	strcpy(s_Terms_of_the_license, "Syarat-syarat lesen");
	strcpy(s_The_current_product_has_been_changed_Do_you_want_to_save_it_to_file, "Produk semasa telah diubah. Adakah anda mahu menyimpannya ke fail?");
	strcpy(s_The_value_is_out_of_the_allowed_range, "Nilai berada di luar julat yang dibenarkan.");
	strcpy(s_The_value_must_be_a_real_or_fractional_number_Try_to_replace_the_comma_with_the_dot_if_you_want_to_enter_a_real_number, "Nilai mestilah nombor nyata atau pecahan. Cuba ganti koma dengan titik jika anda ingin memasukkan nombor nyata.");
	strcpy(s_This_feature_is_not_implemented_yet, "Ciri ini belum dilaksanakan lagi.");
	strcpy(s_This_operation_cannot_be_reversed, "Operasi ini tidak dapat diterbalikkan.");
	strcpy(s_Undo_the_last_operation, "Buat asal operasi terakhir.");
	strcpy(s_Utilization, "Panaudojimas");
	strcpy(s_Utilized_Stock, "Stok Terpakai");
	strcpy(s_Version, "Versi");
	strcpy(s_Visible_columns, "Lajur yang kelihatan");
	strcpy(s_You_already_have_the_latest_version_installed, "Anda sudah memasang versi terbaru!");
	strcpy(s_What_is_exported, "Apakah yang dieksport?");
	strcpy(s0meansanynumberofpieces, "Zero bermakna bilangan keping");
	strcpy(sAbout, "Mengenai");
	strcpy(sAccept, "Terima");
	strcpy(sAcceptall, "Terima semua");
	strcpy(sAcceptthecurrentsolution, "Terima penyelesaian semasa");
	strcpy(sAdd, "Lampirkan");
	strcpy(sAddapiece, "Tambah sekeping");
	strcpy(sAddasimpleproducttoDemand, "Tambah produk ke bahagian yang ada.");
	strcpy(sAddgrindingthicknesstopartsize, "Tambah ketebalan pengisaran kepada saiz sepotong");
	strcpy(sAddproductnametolabel, "Tambah nama produk ke label");
	strcpy(sAddress, "Alamat");
	strcpy(sAddselectedsizetoInventory, "Tambah saiz yang dipilih ke stok");
	strcpy(sAdhesivelabels, "Label pelekat");
	strcpy(sAdhesivelabelwithinformationaboutpiecesinDemandCustomernameLabelSizeCurrentData, "Label pelekat dengan maklumat mengenai keping: Nama pelanggan, Label, Saiz, Data Terkini dll.");
	strcpy(sAdhesivelabelwithinformationaboutsheetsinInventory, "Label pelekat dengan maklumat mengenai helaian dalam stok.");
	strcpy(sAll, "Semua");
	strcpy(sAlloffcutswhichhavethesizegreaterthanthisvaluewillbeaddedtoInventory, "Semua skrap yang lebih besar daripada nilai ini akan ditambah ke stok");
	strcpy(sAllowMirroring, "Benarkan flipping");
	strcpy(sAllowRotation, "Benarkan putaran");
	strcpy(sAllPieces, "Semua keping");
	strcpy(sAllpredefinedproducts, "Semua produk yang telah ditetapkan");
	strcpy(sAnewwindowwillbedisplayedwheretheusercansettheedgebandsforeachedge, "Tetingkap baru akan dipaparkan di mana pengguna boleh menetapkan band kelebihan untuk setiap sisi.");
	strcpy(sAnewwindowwillbedisplayedwheretheusercansetthegrindingvalueforeachedgeofthsheet, "Tetingkap baru akan dipaparkan di mana pengguna boleh menetapkan saiz pengisaran untuk setiap bahagian sekeping.");
	strcpy(sAnewwindowwillbedisplayedwheretheusercansetthetrimvalueforeachedgeofthsheet, "Tetingkap baru akan dipaparkan di mana pengguna boleh menetapkan nilai trim untuk setiap bahagian sekeping.");
	strcpy(sAngle, "Sudut");
	strcpy(sAngles, "Sudut");
	strcpy(sAnoptimizationparameterisarealnumber, "Parameter pengoptimuman adalah nombor sebenar.");
	strcpy(sAnoptimizationparameterisfractionalnumber, "Parameter pengoptimuman ialah nombor pecahan.");
	strcpy(sAnyShape, "Bentuk yang benar");
	strcpy(sApolygonmusthaveatleast2vertices, "Poligon mesti mempunyai sekurang-kurangnya 2 simpul!");
	strcpy(sApolygonmusthaveatleast3vertices, "Poligon mesti mempunyai sekurang-kurangnya 3 titik!");
	strcpy(sApplication_fails_to_initialize, "Permohonan gagal dimulakan!");
	strcpy(sArc, "Arc");
	strcpy(sArcLength, "Panjang lengkok");
	strcpy(sAreaofusedsheets, "Kawasan lembaran yang digunakan");
	strcpy(sAshortdescriptionofthesheet, "Penerangan ringkas lembaran");
	strcpy(sAtleastonepart, "Anda mesti memasukkan sekurang-kurangnya satu keping.");
	strcpy(sAtTheMarginOfTheSheet, "Di margin lembaran");
	strcpy(sBandtypes, "Jenis band kelebihan");
	strcpy(sBar, "Bar");
	strcpy(sBars, "Bar");
	strcpy(sBothsizesoftheoffcutsmustbegreaterthanthisvalue, "Kedua-dua saiz sekerap mestilah lebih besar daripada nilai ini.");
	strcpy(sBottom, "Bawah");
	strcpy(sBottomcoordinateofthedefect, "Koordinat bawah cacat");
	strcpy(sBreakCut, "Pecahkan pemotongan");
	strcpy(sBrowse, "Semak imbas");
	strcpy(sBuy, "Beli");
	strcpy(sBuynow, "Beli sekarang ...");
	strcpy(sCancel, "Batalkannya");
	strcpy(sCannotBeEmpty, "tidak boleh kosong!");
	strcpy(sCannotmovepartsbetweensheetswhenidenticalsheetsaregroupedPleaseungroupthesheetsfrommenu, "Tidak dapat memindahkan bahagian dari satu hela kepada yang lain jika helaian yang sama dikelompokkan. Sila batalkan pengumpulan helaian dari menu.");
	strcpy(sCannotSaveFile, "Tidak dapat menyimpan fail");
	strcpy(sCenter, "Pusat");

	strcpy(sChangeDirection, "Tukar arahan potong");
	strcpy(sChoose, "Pilih");
	strcpy(sChooseProduct, "Pilih produk");
	strcpy(sCircle, "Circle");
	strcpy(sCity, "City");
	strcpy(sClear, "Jelas");
	strcpy(sClockWise, "Mengikut arah jam");
	strcpy(sClosewindow, "Tutup tingkap");
	strcpy(sColor, "Warna");
	strcpy(sColorofedgeband, "Warna jalur tepi");
	strcpy(sColorPattern, "Warna / Corak");
	strcpy(sColorpiecesandwastes, "Potongan berwarna dan sisa");
	strcpy(sColumns, "Lajur");
	strcpy(sComment, "Komen");
	strcpy(sCompanyname, "Nama syarikat");
	strcpy(sComplexMaterialExists, "Nama bahan sudah ditakrifkan dalam senarai bahan yang kompleks. Sila beri nama baru.");
	strcpy(sComputerCode, "Kod komputer");
	strcpy(sComputerCodefromyourcomputer, "Kod Komputer (dari komputer anda)");
	strcpy(sComputethetotalpriceofDemand, "Mengira jumlah harga Bahagian");
	strcpy(sContents, "Kandungan");
	strcpy(sContinutComanda, "Kandungan Bahagian pada tarikh");
	strcpy(sContinutDepozit, "Kandungan Stok pada tarikh tersebut");
	strcpy(sConversionIsDoneOnlyWhenSomePiecesHaveFractionalValues, "Penukaran dilakukan hanya apabila beberapa keping mempunyai nilai pecahan.");
	strcpy(sConvertsTheSizeOfWasteToAFractionalUnit, "Menunjukkan saiz sekerap sebagai nilai pecahan.");
	strcpy(sCouldNotSaveFile1, "Tidak dapat menulis fail dalam direktori");
	strcpy(sCouldNotSaveFile2, "Anda mungkin tidak mempunyai hak yang mencukupi. Sila semak atau ubah direktori kerja dari Tetapan menu | Direktori kerja ke folder di mana anda mempunyai hak untuk menulis (misalnya c: \\ temp).");
	strcpy(sCreationdateYMDHMS, "Tarikh penciptaan (Y / M / D- H: M: S)");
	strcpy(sCurrentDate, "Tarikh semasa");
	strcpy(sCurrentDiagram, "Gambar rajah semasa");
	strcpy(sCurrentMaterial, "Bahan semasa");
	strcpy(sCurrentversion, "Versi terkini");
	strcpy(sCurve_not_closed_Try_increasing_DXF_linking_distance_parameter, "Poligon tidak ditutup! Cuba tingkatkan parameter jarak penghubung DXF.");
	strcpy(sCustomer, "Pelanggan");
	strcpy(sCustomerName, "Nama Pelanggan");
	strcpy(sCustomMessage, "Mesej tersuai");
	strcpy(sCutlength, "Panjang potong");
	strcpy(sCut, "Potong");
	strcpy(sCuts, "Cuts");
	strcpy(sCutterThickness, "Ketebalan potong");
	strcpy(sData, "Data");
	strcpy(sDataCannotBeEmpty, "Data tidak boleh kosong!");
	strcpy(sDateymdhms, "Tarikh (y / m / d / h / m / s)");
	strcpy(sDays_left_for_trial, "Hari ditinggalkan untuk percubaan");
	strcpy(sDaysLeft, "hari lagi");
	strcpy(sStandard, "Lalai");
	strcpy(sDefaultInterface, "Antara muka lalai");
	strcpy(sDefects, "Kecacatan");
	strcpy(sDefectsManager, "Mengurus kecacatan");
	strcpy(sDefectsofthematerialNopiecescanbeplacedinthefaultyzone, "Kecacatan bahan. Tiada potongan boleh diletakkan di zon yang rosak.");
	strcpy(sDelete, "Padam");
	strcpy(sDeletePiece, "Padamkan bahagian");
	strcpy(sDeleteRow, "Padamkan baris");
	strcpy(sDemandutilization, "Pemakaian bahagian-bahagian");
	strcpy(sDepozitulmodificat, "Potongan yang digunakan telah dialih keluar. Sisa telah ditambah ke stok.");
	strcpy(sDepozitvid, "Stok kosong");
	strcpy(sDesk, "meja");
	strcpy(sDiagram, "Rajah");
	strcpy(sDiagrams, "Gambar rajah");
	strcpy(sDiagramasatable, "Rajah sebagai jadual");
	strcpy(sDigits, "digit");
	strcpy(sDimensiuniplaca, "Saiz helaian");
	strcpy(sDirection, "Arah");
	strcpy(sDistanceBetweenRows, "Jarak antara baris");
	strcpy(sDonotuseit, "Jangan gunakannya");
	strcpy(sDownload, "Muat turun");
	strcpy(sDoYouWantToClearTheData, "Adakah anda ingin memadam data?");
	strcpy(sDoYouWantToSaveDemand, "Bahagian telah berubah! Adakah anda ingin menyimpan perubahan?");
	strcpy(sDoYouWantToSaveParts, "Adakah anda ingin menyimpan bahagian?");
	strcpy(sDoYouWantToSaveRepository, "Stok telah berubah! Adakah anda ingin menyimpan perubahan?");
	strcpy(sDrawing, "Lukisan");
	strcpy(sDrawthesolutioncolorful, "Lukis penyelesaian berwarna-warni");
	strcpy(sDuplicateTypes, "Sesetengah jenis ditiru! Sila alih keluar pendua");
	strcpy(sDuplicateTypesWithComplex, "Beberapa nama bahan sudah ada dalam senarai jenis kompleks! Sila keluarkan pendua");
	strcpy(sDuplicateValues, "Nilai duplikat");
	strcpy(sEdgeband, "Band tepi");
	strcpy(sEdgebandingwhichisplacedontheedgesofyourpiecePleasedefineedgebandingtypesfromMaterialsEdgeBandingmenu, "Band tepi diletakkan pada margin bahagian anda. Sila nyatakan band kelebihan dalam menu Bahan.");
	strcpy(sEdgebandsthatwillbeappliedtoeachpart, "Band kelebihan yang digunakan untuk setiap bahagian.");
	strcpy(sEdgeBandTolerance, "Toleransi untuk band tepi");
	strcpy(sEdgesthatmustbecutduefaults, "Tepi yang mesti dipotong kerana kecacatan.");
	strcpy(sEdgetoedge, "Dari tepi ke tepi");
	strcpy(sEdit, "Edit");
	strcpy(sEmail, "E-mel");
	strcpy(sEmptyData, "Data kosong!");
	strcpy(sEnabled, "Dihidupkan");
	strcpy(sEnabledisabledefectsoftheinventorysheets, "Membolehkan / melumpuhkan kecacatan stok");
	strcpy(sEnterLabel, "Masukkan label");
	strcpy(sEnterTheMaterialName, "Masukkan nama bahan tersebut");
	strcpy(sEnterTheProductName, "Masukkan nama produk");
	strcpy(sEvaluationError, "Kesilapan penilaian ungkapan!");
	strcpy(sExit, "Keluar");
	strcpy(sExpired, "Perisian telah tamat tempoh! Sila daftarkan perisian!");
	strcpy(sExport, "Eksport");
	strcpy(sExportAllDiagrams, "Eksport semua gambar rajah");
	strcpy(sExportAllToASingleFile, "Eksport semua ke satu fail");
	strcpy(sExportOptions, "Pilihan eksport");
	strcpy(sExporttoDXFformat, "Eksport ke format DXF");
	strcpy(sExporttoExcel, "Eksport ke Excel");
	strcpy(sExpresieIncorecta, "Ungkapan matematik yang tidak betul!");
	strcpy(sExtensions, "Extensions");
	strcpy(sExtra, "Tambahan");
	strcpy(sExtraComponents, "Komponen tambahan");
	strcpy(sExtracomponentsattachedtoDemand, "Komponen tambahan yang dilampirkan pada bahagian");
	strcpy(sFile, "Fail");
	strcpy(sFileName, "Nama fail");
	strcpy(sFillWastes, "Lukiskan sisa dengan garis serong");
	strcpy(sFindoptimalbarsheetsize, "Cari saiz yang optimum untuk bar dan cadar.");
	strcpy(sFindoptimalsizeofInventorypieces, "Cari saiz optimum keping stok");
	strcpy(sFirstcutMultiplestages, "Arah pemotongan pertama untuk pengoptimuman pelbagai peringkat.");
	strcpy(sFirstdirectionforcutishorizontal, "Arah pertama untuk dipotong adalah mendatar.");
	strcpy(sFirstdirectionforcutisvertical, "Arah pertama untuk dipotong adalah menegak.");
	strcpy(sFollowthecontourofpieces, "Ikuti kontur kepingan");
	strcpy(sFont, "Fon");
	strcpy(sFontsize, "Saiz huruf");
	strcpy(sFullInfo, "Maklumat lengkap");
	strcpy(sDisposedWaste, "Sisa buangan");
	strcpy(sGeneral, "Ketua");
	strcpy(sGenerateCNC, "Menjana CNC");
	strcpy(sGrain, "Tekstur");
	strcpy(sGraindirection, "Arah tekstur");
	strcpy(sGraphic, "Grafik");
	strcpy(sGreaterorequalto, "Besar atau sama dengan");
	strcpy(sGrid, "Jadual");
	strcpy(sGrinding, "Pengisaran");
	strcpy(sGrosimeTaieturaScalata, "Ketebalan potongan dari gambar ini mungkin berbeza daripada yang sebenar kerana potongan tidak diwakili pada skala sebenar mereka. Fakta ini tidak menjejaskan keputusannya.");
	strcpy(sGroupidenticallayouts, "Pengumpulan lembaran yang sama");
	strcpy(sGroupIdenticalParts, "Bahagian yang sama kumpulan");
	strcpy(sGroupingOfIdenticalPiecesIntoOneRow, "Mengumpulkan bahagian yang sama ke dalam satu baris.");
	strcpy(sGroupPartsAfterLoadingFromFile, "Bahagian kumpulan apabila memuatkan dari fail");
	strcpy(sHeight, "Ketinggian");
	strcpy(sHeighttolerance, "Toleransi untuk ketinggian");
	strcpy(sHelp, "Bantuan");
	strcpy(sHistory, "Sejarah");
	strcpy(sHorizontal, "Mendatar");
	strcpy(sHowtodisplayprintedgebands, "Bagaimanakah jalur tepi dipaparkan?");
	strcpy(sIfyousetthebandforoneedgeallwillreceivethesamevalue, "Jika anda menetapkan jalur untuk satu tepi, semua tepi akan menerima nilai yang sama.");
	strcpy(sIfyousetthegrindingforoneedgeallwillreceivethesamevalue, "Jika anda menetapkan nilai pengisaran untuk satu tepi, semua tepi akan menerima nilai yang sama.");
	strcpy(sIfyousetthetrimforoneedgeallwillreceivethesamevalue, "Jika anda menetapkan pemangkasan untuk satu tepi, semua tepi akan menerima nilai yang sama.");
	strcpy(sImageBounds, "Bounds untuk imej");
	strcpy(sImageSize, "Saiz gambar");
	strcpy(sImportData, "Import data");
	strcpy(sIncorrectPassword, "kata laluan salah");
	strcpy(sIndex, "Indeks");
	strcpy(sInformationaboutcustomer, "Maklumat mengenai pelanggan");
	strcpy(sInputALanguageName, "Masukkan nama bahasa tersebut");
	strcpy(sInsert, "Masukkan");
	strcpy(sInsertPiece, "Masukkan sekeping");
	strcpy(sInterface, "Antara muka");
	strcpy(sInterfaceSettings, "Tetapan antara muka");
	strcpy(sInvalidHardware, "Saya tidak dapat mengesan perkakasan. Sila hubungi kami di contact@optimalprograms.com");
	strcpy(sInvalidNumber, "Nombor tidak sah");
	strcpy(sInvalidOrderOfComputation, "Pesanan untuk mengira panjang tidak dapat ditentukan. Terdapat hubungan bulat dalam definisi produk!");
	strcpy(sInvalidRegistration, "Pendaftaran tidak sah!");
	strcpy(sInvalidTime, "Masa sistem anda tidak sah.");
	strcpy(sInventory, "STOK");
	strcpy(sisafractionalvalue, "adalah nilai fraksional.");
	strcpy(sIsArc, "Adakah busur");
	strcpy(sisarealvalue, "adalah nilai sebenar.");
	strcpy(sLabel, "Label");
	strcpy(sLabels, "Label");
	strcpy(sLanguage, "Bahasa");
	strcpy(sLatimeanumar0, "Lebar mesti lebih besar daripada 0!");
	strcpy(sLatimeanumarreal, "Lebar mestilah nombor sebenar!");
	strcpy(sLayerName, "Nama lapisan");
	strcpy(sLeft, "Meninggalkan");
	strcpy(sLeftcoordinateofthedefect, "Koordinat kiri kecacatan");
	strcpy(sLength, "Panjang");
	strcpy(sLengthofthepiecestocut, "Saiz potong untuk pemotongan");
	strcpy(sLengthofthepiecestocutfrom, "Saiz lembaran untuk pemotongan");
	strcpy(sLengthofusedbars, "Saiz bar yang digunakan");
	strcpy(sLicenseAgreement, "Perjanjian Lesen");
	strcpy(sLinear, "Linear");
	strcpy(sLinethickness, "Ketebalan pen");
	strcpy(sLoadafileandappenddatatothecurrentDemand, "Muatkan fail dan masukkan data ke bahagian semasa.");
	strcpy(sLoadanexistingDemandfromafile, "Muatkan bahagian yang ada dari fail.");
	strcpy(sLoadAppend, "Muatkan dan masukkan");
	strcpy(sLoadEverything, "Muatkan segala-galanya");
	strcpy(sLoadInventory, "Muatkan stok");
	strcpy(sLoadInventoryandDemand, "Muatkan saham dan bahagian-bahagiannya");
	strcpy(sLoadResults, "Muatkan hasilnya");
	strcpy(sLocked, "Terkunci");
	strcpy(sLogo, "Logo");
	strcpy(sLong, "Lama");
	strcpy(sLongerexecutiontime, "Masa berjalan lebih lama");
	strcpy(sLungime, "Panjang");
	strcpy(sLungimeanumar0, "Panjang mestilah lebih besar daripada 0!");
	strcpy(sLungimeanumarreal, "Panjang mestilah nombor sebenar!");
	strcpy(sLungimeaTotalaFolosita, "Jumlah yang digunakan sepenuhnya");
	strcpy(sMagnification, "Pembesaran");
	strcpy(sMagnify, "Magnify");
	strcpy(sMargins, "Margin");
	strcpy(sMarginsForPaper, "Margin untuk kertas");
	strcpy(sMarginsOfTheLabel, "Margin label");
	strcpy(sMaterial, "Bahan");
	strcpy(sMaterialName, "Nama bahan");
	strcpy(sMaterials, "Bahan");
	strcpy(sMaterialstypes, "Jenis bahan");
	strcpy(sMax, "Maks");
	strcpy(sMaximalArea, "Kawasan maksima");
	strcpy(sMaximalCutLength, "Panjang potongan maksimum");
	strcpy(sMaxlength, "Panjang maksimum");
	strcpy(sMaxPiecesperBar, "Jumlah maksimum setiap bar");
	strcpy(sMaxwidth, "Lebar maksimum");
	strcpy(sMeasurementUnit, "Unit pengukuran");
	strcpy(sMin, "Min");
	strcpy(sMinimalBreakSize, "Saiz rehat minimum");
	strcpy(sMinimalUsefulSize, "Saiz yang berguna minimum");
	strcpy(sMinimalwastesizetoInventory, "Saiz sekerap minimum ditambah ke stok.");
	strcpy(s_What_to_minimize, "Apa yang perlu diminimumkan?");
	strcpy(sMinlength, "Panjang minimum");
	strcpy(sMinwidth, "Lebar minimum");
	strcpy(sMirror, "Cermin");
	strcpy(sMirroring, "Cermin");
	strcpy(sMiscellaneous, "Statistik lain");
	strcpy(sModify, "Ubah suai");
	strcpy(sModifytheselectedpiece, "Ubah suai bahagian yang dipilih");
	strcpy(sMovePiece, "Pindahkan sekeping");
	strcpy(sMultiplestages, "Pelbagai peringkat");
	strcpy(sName, "Nama");
	strcpy(sNameofedgeband, "Nama band tepi");
	strcpy(sNewDEMANDUnsaveddatawillbelost, "Bahagian baru? Data yang tidak disimpan akan hilang!");
	strcpy(sNewLanguage, "Bahasa baru");
	strcpy(sNewMaterial, "Bahan baru");
	strcpy(sNewPasswordincorectlyintroduced, "Kata laluan baru salah diperkenalkan!");
	strcpy(sNewProduct, "Produk baru");
	strcpy(sNewversion, "Versi baru");
	strcpy(sNo, "Tidak");
	strcpy(sNumarBucati, "Bilangan potongan");
	strcpy(sNumberOfCopies, "Bilangan salinan");
	strcpy(sNumberofstages, "Bilangan peringkat");
	strcpy(sNusuficienteplacidepozit, "Tidak semua bahagian telah dioptimumkan. Sebab-sebab yang mungkin: Tidak ada potongan yang cukup di Stok; Potongan tidak didayakan; Bahan keping dan Stok adalah berbeza; Parameter lain telah ditetapkan dengan salah.");
	strcpy(sOfficeNotInstaled, "Microsoft Office tidak dipasang ke komputer anda atau versi yang salah dipasang!");
	strcpy(sOldpassworddoesnotmatch, "Kata laluan lama tidak sepadan!");
	strcpy(sOnlinehelp, "Bantuan dalam talian");
	strcpy(sOnlypiecesofthesameheightinthelaststage, "Potongan ketinggian yang sama pada peringkat terakhir");
	strcpy(sOpen, "Buka");
	strcpy(sOptimization, "Pengoptimuman");
	strcpy(sOptimizationDone, "Pengoptimuman dilakukan! Anda boleh mencetak atau menyimpan gambar rajah yang diperoleh. Tekan butang Terima jika anda berpuas hati dengan penyelesaian semasa. Jika tidak tekan Mula semula.");
	strcpy(sOptimizationType, "Jenis pengoptimuman");
	strcpy(sOptions, "Pilihan");
	strcpy(sOptionsrelatedtotheinterface, "Pilihan yang berkaitan dengan antara muka");
	strcpy(sor, "atau");
	strcpy(sOthercomponents, "Komponen lain");
	strcpy(sOthers, "Lain-lain");
	strcpy(sOtherstatistics, "Statistik lain");
	strcpy(sOverrideExcelCSVfiles, "Menimpa fail Excel / CSV");
	strcpy(sParameter, "Parameter");
	strcpy(sParts, "PIECES");
	strcpy(sPattern, "Corak");
	strcpy(sPatternforwaste, "Corak untuk sekerap");
	strcpy(sPerimeter, "Perimeter");
	strcpy(sPermitedRotationAngle, "Sudut putaran dibenarkan");
	strcpy(sPhone, "Telefon");
	strcpy(sPicture, "Imej");
	strcpy(sPiece, "Piece");
	strcpy(sPieceindex, "Indeks kepingan");
	strcpy(sPieces, "Keping");
	strcpy(sPiecesize, "Saiz keping");
	strcpy(sPiecesizelabeledgebandwillbeprinted, "Saiz potongan, label, band tepi akan dicetak.");
	strcpy(sPierdere, "Scrap");
	strcpy(sPixels, "piksel");
	strcpy(sPlacilefolositeDepozit, "Keping digunakan dari Stok.");
	strcpy(sPlease_contact_us_at_contact_nestingtechnologies_com, "Sila hubungi kami di contact@nesting-technologies.com");
	strcpy(sPlease_contact_us_at_contact_optimalprograms_com, "Sila hubungi kami di contact@optimalprograms.com");
	strcpy(sPleaseenteralldataeitherasfractionalorrealDonotmixthem, "Sila masukkan semua data sama ada sebagai nilai fraksional atau nilai sebenar! Jangan campurkan mereka!");
	strcpy(sPleaseEnterSomeTypesOfMaterials, "Tiada jenis bahan yang ditakrifkan. Anda boleh menentukannya dari menu Bahan.");
	strcpy(sPleasesendtheNameandtheCodetotheaddresscontactoptimalprogramscominordertoobtaintheRegistrationKey, "Untuk mendapatkan Kunci Pendaftaran sila hantar Nama dan Kod kepada: contact@optimalprograms.com.");
	strcpy(sPolygon, "Poligon");
	strcpy(sPolygonsCircles, "Poligon, bulatan");
	strcpy(sPrecision, "Ketepatan");
	strcpy(sPretulnumar0, "Harga mesti melebihi 0!");
	strcpy(sPretulnumarreal, "Harga mestilah nombor sebenar!");
	strcpy(sPreview, "Pratonton");
	strcpy(sPrice, "Harga");
	strcpy(sPriceMustBeGreaterThanZero, "Harga mesti melebihi sifar");
	strcpy(sPriceofbars, "Harga bar");
	strcpy(sPriceperbar, "Harga setiap bar");
	strcpy(sPricepersheet, "Harga setiap helaian");
	strcpy(sPricepersquareunitofmaterial, "Harga per unit persegi bahan");
	strcpy(sPriceperunit, "Harga seunit");
	strcpy(sPrint, "Cetak");
	strcpy(sPrintdiagramsastables, "Rangka gambar cetak sebagai jadual.");
	strcpy(sPrinter, "Mesin pencetak");
	strcpy(sPrinterBounds, "Margin untuk pencetak");
	strcpy(sPrinting, "Percetakan");
	strcpy(sPrintonlyutilizedarea, "Cetakan hanya kawasan yang digunakan");
	strcpy(sPrintthecontentsoftheDemand, "Cetak kandungan bahagian-bahagian.");
	strcpy(sPrintthecontentsoftheInventory, "Cetak kandungan stok.");
	strcpy(sPrintthecurrentsolution, "Cetak penyelesaian semasa.");
	strcpy(sPriority, "Keutamaan");
	strcpy(sPrioritytocutapieceZero0isthehighestpriority, "Keutamaan untuk memotong sekeping. Zero (0) adalah keutamaan tertinggi.");
	strcpy(sProcentul0100, "Peratusan mestilah lebih besar dari 0 dan kurang atau sama dengan 100!");
	strcpy(sProcentulnumarreal, "Percent mesti nombor nyata!");
	strcpy(sProductdefinition, "Definisi produk");
	strcpy(sProductExists, "Produk sudah wujud. Pilih nama lain.");
	strcpy(sProductName, "Nama Produk");
	strcpy(sProducts, "Produk");
	strcpy(sProducts, "Produk");
	strcpy(sProject, "Projek");
	strcpy(sProperties, "Hartanah");
	strcpy(sProperty, "Harta");
	strcpy(sQuantity, "Kuantiti");
	strcpy(sQuantitynumberofsheetsofthistype, "Bilangan helai jenis ini");
	strcpy(sRadius, "Jejari");
	strcpy(sRectangular, "Segi empat tepat");
	strcpy(sRedefinetypesofedgeband, "Tentukan semula jenis kelebihan band");
	strcpy(sRedefinetypesofmaterial, "Nyatakan jenis bahan semula");
	strcpy(sRegistration, "Pendaftaran");
	strcpy(sRegistrationKeyfromOptimalPrograms, "Kunci pendaftaran");
	strcpy(sRegistrationSuccessful, "Pendaftaran berjaya!");
	strcpy(sRemoveallpiecesinInventory, "Keluarkan semua bahagian dalam Inventori.");
	strcpy(sRemoveCut, "Padamkan potong");
	strcpy(sRemovetheselectedpiece, "Padamkan bahagian yang dipilih");
	strcpy(sReports, "Laporan");
	strcpy(sRequestedMaterial, "Bahan yang diminta");
	strcpy(sRestore, "Pulihkan");
	strcpy(sResults, "Keputusan");
	strcpy(sReusedwaste, "Sisa semula");
	strcpy(sRight, "Kanan");
	strcpy(sRightcoordinateofthedefect, "Koordinat kecacatan dari sebelah kanan");
	strcpy(sRotation, "Putaran");
	strcpy(sRotationAngle, "Sudut putaran");
	strcpy(sRotationStep, "Langkah putaran");
	strcpy(sRoundAllFractionsTo, "Nilai pecahan mesti dibulatkan kepada");
	strcpy(sRow, "baris");
	strcpy(sRows, "Baris");
	strcpy(sRun, "Penyelesaian terkini");
	strcpy(sRunningtime, "masa berjalan");
	strcpy(sSameforall, "Yang sama untuk semua");
	strcpy(sSave, "Simpan");
	strcpy(sSaveAllImages, "Simpan semua imej");
	strcpy(sSaveAs, "Simpan sebagai");
	strcpy(sSaveChanges, "Bahagian telah berubah. Adakah anda mahu menyimpannya?");
	strcpy(sSaveCurrentImage, "Simpan imej semasa");
	strcpy(sSavedataparameters, "Simpan data dan parameter");
	strcpy(sSaveEverything, "Simpan segala-galanya");
	strcpy(sSaveInventory, "Simpan Inventori");
	strcpy(sSaveInventoryandDemand, "Simpan stok dan bahagian");
	strcpy(sSaveResults, "Simpan hasil");
	strcpy(sSaveStatisticsinafile, "Simpan statistik dalam fail");
	strcpy(sSavethecurrentimage, "Simpan imej semasa");
	strcpy(sSavethecurrentimageorstatistic, "Simpan imej semasa atau statistik");
	strcpy(sSavetheDEMANDinafile, "Simpan ke fail");
	strcpy(sSavetheDemandinafilewithadifferentname, "Simpan Bahagian dalam fail dengan nama yang berbeza.");
	strcpy(sSavetheREPOSITORYinafile, "Simpan Stok dalam fail");
	strcpy(sSerialNumber, "Kunci pendaftaran");
	strcpy(sService, "Perkhidmatan");
	strcpy(sSetDefaultValues, "Ini akan memulihkan semua parameter kepada nilai lalai mereka. Semua tetapan anda akan hilang. Adakah anda pasti mahu melakukan ini?");
	strcpy(sSetedgeband, "Tetapkan jalur tepi");
	strcpy(sSetedgetrim, "Tetapkan saiz potongan untuk kecacatan margin");
	strcpy(sSetthesameedgebandforalledges, "Tetapkan band kelebihan yang sama untuk semua pihak");
	strcpy(sSetthesamegrindingforalledges, "Tetapkan pengisaran yang sama untuk semua tepi");
	strcpy(sSetthesametrimforalledges, "Tetapkan pemotongan yang sama untuk kecacatan untuk semua tepi");
	strcpy(sSettings, "Tetapan");
	strcpy(sShape, "Bentuk");
	strcpy(sSheet, "Lembaran");
	strcpy(sSheetsBarstypes, "Jenis helaian_bar");
	strcpy(sSheetSize, "Saiz helaian");
	strcpy(sSheetsperPage, "Lembaran setiap halaman");
	strcpy(sShort, "Pendek");
	strcpy(sShorterexecutiontime, "Masa berjalan yang singkat");
	strcpy(sShowallsimpleproducts, "Tunjukkan semua produk mudah");
	strcpy(sShowcustomername, "Tunjukkan nama pelanggan");
	strcpy(sShowCustomTextOnEachPiece, "Paparkan teks tersuai pada setiap bahagian");
	strcpy(sShowdiagramasatable, "Tunjukkan gambarajah sebagai jadual.");
	strcpy(sShowedgeband, "Tunjukkan pinggir kelebihan");
	strcpy(sShowedgebandssettinginanewwindow, "Tunjukkan tetapan tepi kelebihan dalam tetingkap baru");
	strcpy(sShowgrindingsettingsinanewwindow, "Menunjukkan tetapan pengisaran di tetingkap baru.");
	strcpy(sShowHorizontalLabelsAlways, "Tunjukkan sentiasa label mendatar");
	strcpy(sShowRemovethesizeofthepiecesinthecurrentsolution, "Tunjukkan / sembunyikan saiz kepingan.");
	strcpy(sShowRemovethesizeofthewastesinthecurrentsolution, "Tunjukkan / sembunyikan saiz sekerap.");
	strcpy(sShowtotalcutlength, "Tunjukkan jumlah pemotongan total");
	strcpy(sShowtrimedgesettingsinanewwindow, "Tunjukkan tetapan kecacatan dalam tetingkap baru");
	strcpy(sSimpleMaterialExists, "Nama bahan sudah ditakrifkan dalam senarai bahan. Sila beri nama baru.");
	strcpy(sSinglePieceStrips, "Jalur satu bahagian");
	strcpy(sSizes, "Saiz");
	strcpy(sSmallerorequalto, "Lebih kecil atau sama dengan");
	strcpy(sSort, "Susun");
	strcpy(sSortAscendingByArea, "Isih mengikut kawasan dalam urutan menaik");
	strcpy(sSortDescendingByArea, "Isih mengikut kawasan dalam urutan menurun");
	strcpy(sSpecifyhowdifferentthepiecesinthelaststagecanbeValue0meansnodifference, "Tentukan bagaimana perbezaannya boleh menjadi bahagian dalam peringkat terakhir. Nilai 0 bermaksud tiada perbezaan.");
	strcpy(sSpecifyifpiecesinthelaststagecanbedifferentornotdepeultimaetapapotfidiferitesaunucadimensiune, "Tentukan jika kepingan di peringkat terakhir boleh berbeza atau tidak");
	strcpy(sSpecifyifthepiececanberotatedornotIfnotitwillbecutinthesamewayasitwasintroducedinDemandLengthofthepieceparalleltothelengthofthesheet, "Tentukan jika potongan itu boleh diputar atau tidak. Jika tidak, ia diletakkan dengan cara yang sama seperti ia diperkenalkan (panjang selari dengan panjang lembaran), ");
	strcpy(sSpecifyinhowmanystageswemakethecutsDuringastageallcutshavethesamedirection, "Tentukan berapa banyak peringkat yang kami buat.");
	strcpy(sStartthesearchprocess, "Mulakan proses carian");
	strcpy(sStatistics, "Statistik");
	strcpy(sStatisticsE, "Laporan Tambahan");
	strcpy(sStatisticsforeachtypeofmaterial, "Statistik untuk setiap jenis bahan");
	strcpy(sStep, "Langkah");
	strcpy(sStergeDepozit, "Adakah anda ingin memadamkan Inventori?");
	strcpy(sStergeMaterial, "Adakah anda ingin memadam bahan tersebut?");
	strcpy(sStergePiesele, "Anda mahu memadamkan sekeping?");
	strcpy(sStergePiesa, "Anda mahu memadamkan sekeping?");
	strcpy(sStopthesearchprocess, "Hentikan proses carian");
	strcpy(sStrongoptimization, "Pengoptimuman yang kuat");
	strcpy(sSubtractthebandthicknessfrompiecesize, "Kurangkan saiz kepingan dengan ketebalan jalur tepi");
	strcpy(sSummary, "Ringkasan");
	strcpy(sSuprafataTotalaFolosita, "Jumlah permukaan yang digunakan");
	strcpy(sSuprafatautilizata, "Penggunaan");
	strcpy(sSwitchbetweenfiberandrotationoption, "Beralih antara pilihan gentian dan putaran.");
	strcpy(sTechnical, "Teknikal");
	strcpy(sTechnicalsettings, "Tetapan teknikal");
	strcpy(sTemporaryPanelHint, "Panel sementara bagi bahagian yang bergerak di antara helaian.");
	strcpy(sText, "Teks");
	strcpy(sThe_application_has_expired, "Permohonan telah tamat tempoh.");
	strcpy(sThe_application_is_not_registered, "Permohonan tidak didaftarkan.");
	strcpy(sThe_application_was_first_started_on, "Permohonan itu mula-mula bermula");
	strcpy(sThecutsareperformedfromasidetotheothersideofthematerial, "Potongan dibuat dari sisi ke sisi lain bahan.");
	strcpy(sThecuttingmachinecanfollowtheshapeofthematerial, "Mesin pemotong boleh mengikut bentuk sepotong.");
	strcpy(sTheedgesofsheetsthatmustbetrimedduefaults, "Tepi lembaran yang harus dipangkas kerana kesalahannya");
	strcpy(sTheLargestSize, "Saiz terbesar");
	strcpy(sThenameofthecustomerforwhichyoucutthepiece, "Nama pelanggan yang anda potong.");
	strcpy(sThenameofyourcustomer, "Nama pelanggan anda");
	strcpy(sThepiececanberotated, "Sekeping boleh diputar");
	strcpy(sTheprogramtriestoavoidwasteswhichhavebothsizeslessthanthisvalue, "Program ini cuba mengelakkan skrap yang lebih kecil daripada nilai ini");
	strcpy(sThereAreNoProducts, "Tiada produk yang ditakrifkan lagi");
	strcpy(sThestockofmaterialhasbeenpreviouslyloadedfromanExcelorCSVformatPleaseloaditagain, "Stok bahan sebelum ini dimuatkan dari format Excel atau CSV. Sila muatkannya lagi jika anda mahu mengerjakannya.");
	strcpy(sThetotallengthofcutting, "Jumlah panjang pemotongan");
	strcpy(sThewidthofthecuttingsawForglasscuttingoptimizationitcanbe0Forwooditshouldbegreaterthan0, "Ketebalan saw. Untuk pemotongan kaca boleh 0. Untuk kayu ia harus lebih besar daripada 0.");
	strcpy(sThewidthofthecuttingsawforlinearpieces, "Ketebalan saw bagi kepingan linear.");
	strcpy(sThickness, "Ketebalan");
	strcpy(sThischaracterisusedforfillingthewasterectanglesIfyoudonotwantfilledwastejustremovethischaracter, "Simbol ini digunakan untuk mengisi segi empat tepat sisa. Sekiranya anda tidak mahu sisa yang diisi hanya mengeluarkannya.");
	strcpy(sThisindexhasvaluebetween1andthenumberofpieces, "Indeks ini mempunyai nilai antara 1 dan bilangan keping.");
	strcpy(sThisOptionWillOverrideTheInventoryFileIfLoadedFromExcelOrCsvFiles, "Opsyen ini akan mengatasi fail inventori jika dimuatkan dari fail excel atau csv.");
	strcpy(sThisProgramisLicensedTo, "Program ini dilesenkan kepada");
	strcpy(sThisvaluewillbeaddedtotheedgebandingmaterialoneachside, "Nilai ini akan ditambah ke tepi kelebihan pada setiap sisi");
	strcpy(sTipNevid, "Jenis bahan tidak boleh kosong.");
	strcpy(sTitle, "Tajuk");
	strcpy(sTools, "Alat");
	strcpy(sTop, "Teratas");
	strcpy(sTopcoordinateofthedefect, "Koordinat teratas kecacatan itu.");
	strcpy(sTotalGarbageWaste, "Semua skrap dibuang");
	strcpy(sTotalInventoryWaste, "Jumlah skrap saham");
	strcpy(sTotalRecycledWaste, "Semua skrap yang digunakan semula");
	strcpy(sTotalusedarea, "Jumlah kawasan yang digunakan");
	strcpy(sTotalusedlength, "Jumlah panjang yang digunakan");
	strcpy(sTrigonometric, "Trigonometri");
	strcpy(sTrim, "Memotong");
	strcpy(sTrimalledgesatthebeginning, "Potong semua tepi pada mulanya");
	strcpy(sTrimEdge, "Potong tepi");
	strcpy(sTwoPanels, "2 panel");
	strcpy(sType, "Taipkan");
	strcpy(sTypeofmaterialfromwhichtocut, "Jenis bahan dari mana untuk dipotong");
	strcpy(sTypesAreNotMatched, "Pengoptimuman tidak dilakukan! Pada masa ini, tidak ada bahan sedemikian dalam stok! Potongan boleh dipotong dari lembaran bahan yang sama. Tukar beberapa bahan dari lajur sepadan!");
	strcpy(sUndo, "Undo");
	strcpy(sUndoAccept, "Undo Terima");
	strcpy(sUnits, "unit");
	strcpy(sUnregisteredVersion, "Tidak berdaftar");
	strcpy(sUpdates, "Kemas kini");
	strcpy(sUsefulforwoodfurniture, "Berguna untuk perabot kayu");
	strcpy(sUseit, "Gunakannya");
	strcpy(sUsePieceinOptimization, "Gunakan bahagian dalam pengoptimuman");
	strcpy(sUserName, "Nama pengguna");
	strcpy(sUtilizationandWastes, "Penggunaan dan skrap");
	strcpy(sUtilizedArea, "Kawasan bahagian yang digunakan");
	strcpy(sUtilizedBars, "Bar yang digunakan");
	strcpy(sUtilizeddemandcount, "Bilangan bahagian yang digunakan");
	strcpy(sUtilizedParts, "Bahagian yang digunakan");
	strcpy(sUtilizedPieces, "Kepingan yang digunakan");
	strcpy(sUtilizedSheets, "Lembaran yang digunakan");
	strcpy(sValue, "Nilai");
	strcpy(sValueGreaterEqualToZero, "Nilai mestilah lebih besar atau sama dengan sifar");
	strcpy(sValueGreaterThanZero, "Nilai mestilah lebih besar daripada sifar");
	strcpy(sValueIntegerNumber, "Nilai mestilah nombor integer!");
	strcpy(sValueRealNumber, "Nilai mestilah nombor sebenar. Mungkin anda telah menggunakan koma bukannya tempoh atau viceversa. Sila perbaiki!");
	strcpy(s_The_number_is_too_big_or_it_has_too_many_digits_after_decimal_separator, "Nombornya terlalu besar atau terlalu banyak digit setelah pemisah perpuluhan!");
	strcpy(s_The_number_is_too_big, "Jumlahnya terlalu besar!");
	strcpy(sVertical, "Menegak");
	strcpy(sWaste, "Scrap");
	strcpy(sWastes, "Scrap");
	strcpy(sWasteAddedToWarehouse, "Skrap tersebut ditambahkan ke stok");
	strcpy(sWastelimits, "Julat untuk skrap");
	strcpy(sWasteType, "Jenis sekerap");
	strcpy(sWeakoptimization, "Pengoptimuman paling lemah");
	strcpy(sWhattoprint, "Apa yang perlu saya cetak");
	strcpy(s_What_to_print_or_save_to_file, "Perkara yang hendak dicetak atau disimpan ke fail");
	strcpy(sWhattoprintoneachpiece, "Apa yang hendak dicetak pada setiap bahagian");
	strcpy(sWhattoshowoneachpiece, "Apa yang perlu ditunjukkan pada setiap bahagian?");
	strcpy(sWidth, "Lebar");
	strcpy(sWood, "kayu");
	strcpy(sWorkingDirectory, "Folder kerja");
	strcpy(sWrongKey, "Kunci pendaftaran salah!");
	strcpy(sYes, "Ya");
	strcpy(sYoucannotchooseblackblueorredcolors, "Anda tidak boleh memilih warna hitam, biru atau merah.");
	strcpy(sYouCannotMixFractionalDataWithDecimalOnes, "Anda tidak boleh menggabungkan nilai fraksional dengan nilai sebenar!");
	strcpy(sYourcompany, "Syarikat awak");
	strcpy(sZip, "Poskod");
	strcpy(s_Set_the_origin_and_the_direction_of_the_axes, "Tetapkan asal dan arah paksi koordinat.");

}
