// Language strings: Polish
// Author: Optimal Programs
// License: MIT License
//---------------------------------------------------------------------------
#include <string.h>
//---------------------------------------------------------------------------
#include "language_string_id.h"
//---------------------------------------------------------------------------
void set_pl(void)
{
	// Polish
	// translated by a customer on 2020.08.30
	// last update on: 2025.11.01.0
	
	strcpy(s_Area, "Pole");
	strcpy(s_Mass, "Masa");
	strcpy(s_Advanced, "Zaawansowany");
	strcpy(s_Relative_coordinates, "Współrzędne względne");
	strcpy(s_Absolute_coordinates, "Współrzędne bezwzględne");
	strcpy(s_Append_more_rows, "Dołącz więcej wierszy");

	strcpy(s_Add_to_parts, "Dodaj do części.");
	strcpy(s_Additional, "Dodatkowy");
	strcpy(s_All_results, "Wszystkie wyniki.");
	strcpy(s_Allow_movement_of_pieces, "Zezwalaj na ruch kawałków");
	strcpy(s_Allow_part_in_part, "Pozwól kawałek w kawałku");
	strcpy(s_Invalid_piece_Angles_are_too_small_or_too_big_or_height_is_too_small, "Nieprawidłowy element! Kąty są za małe lub za duże, lub wysokość jest za mała.");
	strcpy(s_Append, "Dodaj");
	strcpy(s_As_it_is, "Tak, jak jest");
	strcpy(s_As_text, "Jako tekst");
	strcpy(s_Ascending, "Rosnąco");
	strcpy(s_Automatic, "Automatyczny");
	strcpy(s_Cannot_connect_to_the_Internet_Please_visit_our_website_from_a_browser, "Nie mogę połączyć się z Internetem! Wejdź na naszą stronę przy pomocy przeglądarki.");
	strcpy(s_Cannot_copy_or_move_the_files, "Nie można kopiować ani przenosić plików!");
	strcpy(s_Cannot_delete_the_file, "Nie można usunąć pliku!");
	strcpy(s_Cannot_modify_old_results, "Nie można modyfikować starych wyników!");
	strcpy(s_To_change_click_inside_a_cell_or_press_0_1_or_2, "Aby zmienić, kliknij wewnątrz komórki lub naciśnij 0, 1 lub 2.");
	strcpy(s_Cell, "Komórka");
	strcpy(s_Click_on_the_table_header_to_change_the_columns, "Kliknij nagłówek tabeli, aby zmienić kolumny.");
	strcpy(s_Close, "Zamknij");
	strcpy(s_Contact_us, "Skontaktuj się z nami");
	strcpy(s_Column, "Kolumna");
	strcpy(s_Comma, "Przecinek");
	strcpy(s_The_comma_symbol_cannot_simultaneously_be_the_list_separator_and_the_decimal_separator, "Symbol przecinka nie może być jednocześnie separatorem listy i separatorem dziesiętnym!");
	strcpy(s_Copy, "Kopiuj");
	strcpy(s_Copy_for_move, "Skopiuj do przeniesienia");
	strcpy(s_Cut_higher_level_strips_first, "Najpierw odetnij paski wyższego poziomu");
	strcpy(s_Cut_index, "Lista cięć");

	strcpy(s_The_data_have_been_changed_Do_you_want_to_save_them_to_a_file, "Dane zostały zmienione. Czy chcesz je zapisać do pliku?");
	strcpy(s_Decimal_separator, "Separator liczb dziesiętnych");
	strcpy(s_Restore_default_settings, "Przywróć ustawienia domyślne");
	strcpy(s_Delete_fiber, "Usuń włókno");
	strcpy(s_Descending, "Malejąco");
	strcpy(s_Discard_changes, "Odrzucać zmiany");

	strcpy(s_Delete_all_data, "Usunąć wszystkie dane?");
	strcpy(s_Dot, "Kropka");
	strcpy(s_Do_you_want_to_delete_the_picture, "Chcesz usunąć zdjęcie?");
	strcpy(s_Do_you_want_to_delete_the_product, "Chcesz usunąć produkt?");
	strcpy(s_Duplicate_and_append, "Powiel i dołącz.");
	strcpy(s_Duplicate_values_are_ignored, "Zduplikowane wartości zostały zignorowane!");
	strcpy(s_Error, "Błąd");
	strcpy(s_Error_loading_file, "Błąd podczas wczytywania pliku.");
	strcpy(s_export_everything, "Eksportuj wszystko");
	strcpy(s_Fit_to_screen, "Dopasować do ekranu.");
	strcpy(s_Force_fixed_height, "Narysuj elementy o ustalonej wysokości.");
	strcpy(s_Flipped, "Odwrócony");
	strcpy(s_Import, "Importuj");
	strcpy(s_If_angles_are_different_from_90_degrees_height_must_be_greater_than_0, "Jeżeli kąty są różne od 90 stopni, wysokość musi być większa od 0.");
	strcpy(s_Ignore, "Ignorować");
	strcpy(s_Incorrect_value, "Nieprawidłowa wartość");
	strcpy(s_Info, "Informacje");
	strcpy(s_Interior, "Wewnątrz");
	strcpy(s_Give_a_name, "Podaj imię.");
	strcpy(s_Group, "Pogrupuj to");
	strcpy(s_Header, "nagłówek");
	strcpy(s_Keep_it_as_it_is, "Zachowaj tak, jak jest");
	strcpy(s_Level, "Level");
	strcpy(s_Licensee, "Właściciel");
	strcpy(s_List_separator, "Oddzielacz listy");
	strcpy(s_Made_with_love_in_Cugir_Romania, "Wykonane z miłością w: Cugir, Rumunia");
	strcpy(s_Made_in, "Wyprodukowano w");
	strcpy(s_Manufacturer, "Producent");

	strcpy(s_Manual_arrange, "Układ ręczny");

	strcpy(s_Mixed, "Mieszany");
	strcpy(s_Multiple_shapes_detected_Next_rows_will_be_overwritten_Continue, "Wykryto więcej niż jeden kształt. Dlatego kolejne wiersze zostaną nadpisane. Kontynuować?");
	strcpy(s_More, "Więcej");
	strcpy(s_Multiple_values, "Wiele wartości");
	strcpy(s_No_texture, "Brak tekstury");
	strcpy(s_Number, "Numer");
	strcpy(s_Number_of_images, "Liczba zdjęć");
	strcpy(s_Number_of_vertices, "Liczba wierzchołków");
	strcpy(s_Offset, "Zrównoważyć");
	strcpy(s_Only_the_currently_selected_items, "Tylko aktualnie wybrane elementy.");
	strcpy(s_Optimizing_please_wait, "Optymalizacja ... proszę czekać.");

	strcpy(s_Paste, "Paste");

	strcpy(s_Piece_label, "Etykieta formatki");
	strcpy(s_Piece_size, "Rozmiar formatki");
	strcpy(s_Please_contact_us_by_email_if_you_receive_this_error, "Skontaktuj się z nami przez e-mail, jeśli pojawi się ten błąd.");
	strcpy(s_Please_save_it_first, "Proszę, zapisz go najpierw.");
	strcpy(s_Position, "Pozycja");
	strcpy(s_Preview, "Podgląd");
	strcpy(s_Rectangle, "Prostokąt");

	strcpy(s_Redo_the_last_operation, "Cofnij ostatnią operację");
	strcpy(s_Regular_polygon, "Regularny wielokąt");

	strcpy(s_Reused, "Ponownie wykorzystany");
	strcpy(s_Rotated, "Obróć");
	strcpy(s_Save_all, "Zapisz wszystko");
	strcpy(s_Scrap_label, "Etykieta odpadu");
	strcpy(s_Scrap_size, "Wymiary odpadu");
	strcpy(s_Semicolon, "Średnik");
	strcpy(s_Show_cut_index, "Pokaż listę cięć");
	strcpy(s_Show_information, "Pokaż informacje");
	strcpy(s_Show_piece_label, "Pokaż etykietę formatki");
	strcpy(s_Show_scrap_label, "Pokaż etykietę odpadu");
	strcpy(s_Show_scrap_s_size_on_the_small_pieces, "Pokaż wymiary odpadu na małych kawałkach.");
	strcpy(s_Show_size_of_pieces, "Pokaż rozmiar formatki");
	strcpy(s_Show_size_of_scrap, "Pokaż rozmiar odpadu");
	strcpy(s_Show_sizes, "Pokaż rozmiary");
	strcpy(s_Show_label, "Pokaż etykietę");
	strcpy(s_Show_length, "Pokaż długość");

	strcpy(s_Some_numerical_values_are_incorrect_Should_I_fix_all_the_incorrect_values, "Znalazłem nieprawidłowe wartości. Naprawić?");
	strcpy(s_Some_invalid_values_have_been_removed, "Usunięto niektóre nieprawidłowe wartości.");
	strcpy(s_Sort_by, "Sortuj według");
	strcpy(s_Sort_ascending_by, "Sortuj rosnąco według");
	strcpy(s_Sort_descending_by, "Sortuj malejąco według");
	strcpy(s_Start, "Start");
	strcpy(s_Starting_angle, "Kąt początkowy");

	strcpy(s_Sticker, "Naklejka");
	strcpy(s_Stock, "Magazyn");
	strcpy(s_Stop, "Stop");
	strcpy(s_System_setting, "Ustawienia systemowe");
	strcpy(s_Tabular, "Tabelaryczny");
	strcpy(s_Total, "Całkowity");
	strcpy(s_Total_size, "Całkowity rozmiar");
	strcpy(s_Terms_of_the_license, "Warunki licencji");
	strcpy(s_The_current_product_has_been_changed_Do_you_want_to_save_it_to_file, "Aktualna formatka została zmieniona. Czy zapisać ją do pliku");
	strcpy(s_The_value_is_out_of_the_allowed_range, "Wartość jest poza dozwolonym zakresem.");
	strcpy(s_The_value_must_be_a_real_or_fractional_number_Try_to_replace_the_comma_with_the_dot_if_you_want_to_enter_a_real_number, "Wartość musi być liczbą rzeczywistą lub ułamkową. Spróbuj zamienić przecinek na kropkę, jeśli chcesz wpisać liczbę rzeczywistą.");
	strcpy(s_This_feature_is_not_implemented_yet, "Ta funkcja nie jest jeszcze zaimplementowana.");
	strcpy(s_This_operation_cannot_be_reversed, "Tej operacji nie można cofnąć.");
	strcpy(s_Undo_the_last_operation, "Cofnij ostatnią operację.");
	strcpy(s_Utilization, "Wykorzystanie");
	strcpy(s_Utilized_Stock, "Wykorzystane zapasy");
	strcpy(s_Version, "Wersja");
	strcpy(s_Visible_columns, "Widoczne kolumny");
	strcpy(s_You_already_have_the_latest_version_installed, "Masz już zainstalowaną najnowszą wersję!");
	strcpy(s_What_is_exported, "Co jest eksportowane?");
	strcpy(s0meansanynumberofpieces, "Zero oznacza ilość części");
	strcpy(sAbout, "O programie");
	strcpy(sAccept, "Dodaj odpady użytkowe do magazynu");
	strcpy(sAcceptall, "Dodaj wszystkie");
	strcpy(sAcceptthecurrentsolution, "Zaakceptuj bieżące rozwiązanie");
	strcpy(sAdd, "Dodaj");
	strcpy(sAddapiece, "Dodaj formatkę");
	strcpy(sAddasimpleproducttoDemand, "Dodaj formatkę do istniejącej listy.");
	strcpy(sAddgrindingthicknesstopartsize, "dodaj naddatek na szlifowanie.");
	strcpy(sAddproductnametolabel, "Dodaj nazwę formatki na etykiecie");
	strcpy(sAddress, "Adres");
	strcpy(sAddselectedsizetoInventory, "Dodaj wybrany rozmiar do magazynu");
	strcpy(sAdhesivelabels, "Etykiety samoprzylepne");
	strcpy(sAdhesivelabelwithinformationaboutpiecesinDemandCustomernameLabelSizeCurrentData, "Naklejka z informacjami o formatce: nazwa Klienta, etykieta, rozmiar, oznaczenie");
	strcpy(sAdhesivelabelwithinformationaboutsheetsinInventory, "Naklejka z informacjami o arkuszu w magazynie.");
	strcpy(sAll, "Wszystko");
	strcpy(sAlloffcutswhichhavethesizegreaterthanthisvaluewillbeaddedtoInventory, "Wszystkie odpady większe niż ta wartość zostaną dodane do magazynu.");
	strcpy(sAllowMirroring, "Zezwalaj na odbicie lustrzane");
	strcpy(sAllowRotation, "Zezwalaj na obracanie");
	strcpy(sAllPieces, "Wszystkie formatki");
	strcpy(sAllpredefinedproducts, "Wszystkie predefiniowane formatki.");
	strcpy(sAnewwindowwillbedisplayedwheretheusercansettheedgebandsforeachedge, "Pojawi się nowe okno, w którym możesz zdefiniować okleinę dla każdej krawędzi.");
	strcpy(sAnewwindowwillbedisplayedwheretheusercansetthegrindingvalueforeachedgeofthsheet, "Pojawi się nowe okno, w którym dla każdej krawędzi możesz zdefiniować naddatek na szlifowanie.");
	strcpy(sAnewwindowwillbedisplayedwheretheusercansetthetrimvalueforeachedgeofthsheet, "Pojawi się nowe okno, w którym możesz zdefiniować przycięcie dla każdej krawędzi.");
	strcpy(sAngle, "Kąt");
	strcpy(sAngles, "Kąty");
	strcpy(sAnoptimizationparameterisarealnumber, "Parametr optymalizacji jest liczbą rzeczywistą.");
	strcpy(sAnoptimizationparameterisfractionalnumber, "Parametr optymalizacji jest liczbą ułamkową.");
	strcpy(sAnyShape, "Dowolny kształt");
	strcpy(sApolygonmusthaveatleast2vertices, "Wielokąt musi mieć co najmniej 2 wierzchołki!");
	strcpy(sApolygonmusthaveatleast3vertices, "Wielokąt musi mieć co najmniej 3 wierzchołki!");
	strcpy(sApplication_fails_to_initialize, "Nie udało się zainicjować programu!");
	strcpy(sArc, "Łuk");
	strcpy(sArcLength, "Długość łuku");
	strcpy(sAreaofusedsheets, "Powierzchnia wykorzystanych arkuszy");
	strcpy(sAshortdescriptionofthesheet, "Krótki opis arkusza");
	strcpy(sAtleastonepart, "Musisz wprowadzić co najmniej jeden kawałek.");
	strcpy(sAtTheMarginOfTheSheet, "Na krawędzi arkusza");
	strcpy(sBandtypes, "Rodzaje taśm krawędziowych.");
	strcpy(sBar, "Pręty/rury");
	strcpy(sBars, "Pręty/rury");
	strcpy(sBothsizesoftheoffcutsmustbegreaterthanthisvalue, "Długość i szerokość odpadu do ponownego wykorzystania musi być większa od tej wartości.");
	strcpy(sBottom, "Dolny");
	strcpy(sBottomcoordinateofthedefect, "Dolna współrzędna defektu");
	strcpy(sBreakCut, "Przełam cięcie");
	strcpy(sBrowse, "Wyszukaj.");
	strcpy(sBuy, "Kup");
	strcpy(sBuynow, "Kup teraz ...");
	strcpy(sCancel, "Anuluj");
	strcpy(sCannotBeEmpty, "wpisz wartość");
	strcpy(sCannotmovepartsbetweensheetswhenidenticalsheetsaregroupedPleaseungroupthesheetsfrommenu, "Nie można przenieść formatki z jednego arkusza na drugi, jeżeli identyczne arkusze są zgrupowane. Proszę anulować grupowanie arkuszy w menu.");
	strcpy(sCannotSaveFile, "Nie mogę zapisać pliku");
	strcpy(sCenter, "Wyśrodkuj");

	strcpy(sChangeDirection, "Zmień kierunek cięcia");
	strcpy(sChoose, "Wybierz");
	strcpy(sChooseProduct, "Wybierz produkt");
	strcpy(sCircle, "Koło");
	strcpy(sCity, "Miasto");
	strcpy(sClear, "Wyczyść");
	strcpy(sClockWise, "Zgodnie z kierunkiem obrotu wskazówek zegara.");
	strcpy(sClosewindow, "Zamknij");
	strcpy(sColor, "Kolor");
	strcpy(sColorofedgeband, "Kolor taśm krawędziowych");
	strcpy(sColorPattern, "Kolor/wzór");
	strcpy(sColorpiecesandwastes, "Kawałki i odpady kolorowe");
	strcpy(sColumns, "Kolumny");
	strcpy(sComment, "Komentarz");
	strcpy(sCompanyname, "Nazwa firmy");
	strcpy(sComplexMaterialExists, "Nazwa materiału jest już na liście określone złożonych materiałów. Proszę dać mu nową nazwę.");
	strcpy(sComputerCode, "Kod komputerowy");
	strcpy(sComputerCodefromyourcomputer, "Kod komputerowy (z komputera)");
	strcpy(sComputethetotalpriceofDemand, "Oblicz całkowitą cenę formatki");
	strcpy(sContents, "Treść");
	strcpy(sContinutComanda, "Treść części w terminie");
	strcpy(sContinutDepozit, "Treść wykazu w terminie");
	strcpy(sConversionIsDoneOnlyWhenSomePiecesHaveFractionalValues, "Konwersja jest wykonywana tylko wtedy, gdy niektóre kawałki mają ułamkowe wartości.");
	strcpy(sConvertsTheSizeOfWasteToAFractionalUnit, "Pokazuje wielkość odpadu jako wartość ułamkową.");
	strcpy(sCouldNotSaveFile1, "Nie można zapisać pliku w katalogu");
	strcpy(sCouldNotSaveFile2, "Być może nie masz wystarczających uprawnień. Proszę sprawdzić lub zmienić katalog roboczy z menu Ustawienia | Praca katalogu do katalogu, w którym masz uprawnienia do zapisu (na przykład c:\\temp).");
	strcpy(sCreationdateYMDHMS, "Data utworzenia (Y / M / D, H: M: S)");
	strcpy(sCurrentDate, "Aktualna data");
	strcpy(sCurrentDiagram, "Aktualny schemat");
	strcpy(sCurrentMaterial, "Aktualny materiał");
	strcpy(sCurrentversion, "Obecna wersja");
	strcpy(sCurve_not_closed_Try_increasing_DXF_linking_distance_parameter, "Wielokąt nie jest zamknięty! Spróbuj zwiększyć parametr odległość łączenia DXF.");
	strcpy(sCustomer, "Klient");
	strcpy(sCustomerName, "Nazwa Klienta");
	strcpy(sCustomMessage, "Niestandardowy komunikat");
	strcpy(sCutlength, "Długość cięcia");
	strcpy(sCut, "Skaleczenie");
	strcpy(sCuts, "Lista cięć");
	strcpy(sCutterThickness, "Grubość narzędzia tnącego");
	strcpy(sData, "Dane");
	strcpy(sDataCannotBeEmpty, "To pole nie może być puste.");
	strcpy(sDateymdhms, "Data (y / m / d / h / m / s)");
	strcpy(sDays_left_for_trial, "Czas na testowanie");
	strcpy(sDaysLeft, "pozostało dni");
	strcpy(sStandard, "Domyślne");
	strcpy(sDefaultInterface, "Domyślny interfejs");
	strcpy(sDefects, "Defekty");
	strcpy(sDefectsManager, "Zarządzaj defektami");
	strcpy(sDefectsofthematerialNopiecescanbeplacedinthefaultyzone, "Wady materiału. Brak kawałki mogą być umieszczone w strefie wadliwego.");
	strcpy(sDelete, "Usuń");
	strcpy(sDeletePiece, "Usuń formatkę");
	strcpy(sDeleteRow, "Usuń wiersz");
	strcpy(sDemandutilization, "Wycięte formatki.");
	strcpy(sDepozitulmodificat, "Wycięte formatki zostały usunięte. Odpad nadający się do ponownego użycia dodano do magazynu.");
	strcpy(sDepozitvid, "Magazyn jest pusty.");
	strcpy(sDesk, "Biurko");
	strcpy(sDiagram, "Schemat");
	strcpy(sDiagrams, "Diagramy");
	strcpy(sDiagramasatable, "Diagram w formie tabeli");
	strcpy(sDigits, "Cyfry");
	strcpy(sDimensiuniplaca, "Rozmiar arkusza");
	strcpy(sDirection, "Kierunek");
	strcpy(sDistanceBetweenRows, "Odległość między rzędami");
	strcpy(sDonotuseit, "Nie używaj.");
	strcpy(sDownload, "Pobierz");
	strcpy(sDoYouWantToClearTheData, "Chcesz usunąć dane?");
	strcpy(sDoYouWantToSaveDemand, "Formatki zostały zmienione. Chcesz zapisać zmiany?");
	strcpy(sDoYouWantToSaveParts, "Czy chcesz zapisać listę formatek?");
	strcpy(sDoYouWantToSaveRepository, "Zawartość magazynu została zmieniona. Czy chcesz zapisać zmiany?");
	strcpy(sDrawing, "Rysunek");
	strcpy(sDrawthesolutioncolorful, "Narysuj kolorowe rozwiązanie");
	strcpy(sDuplicateTypes, "Niektóre typy są powielone! Usuń duplikaty");
	strcpy(sDuplicateTypesWithComplex, "Niektóre nazwy materiałów już istnieją na liście złożonych typów! Proszę usunąć duplikaty");
	strcpy(sDuplicateValues, "Powielone wartości");
	strcpy(sEdgeband, "Taśmy na krawędziach");
	strcpy(sEdgebandingwhichisplacedontheedgesofyourpiecePleasedefineedgebandingtypesfromMaterialsEdgeBandingmenu, "Pasma krawędzi są umieszczane na marginesach Twojego dzieła. Zdefiniuj prążki krawędzi w menu Materiały.");
	strcpy(sEdgebandsthatwillbeappliedtoeachpart, "Taśmy brzegowe, które będą stosowane do każdej formatki");
	strcpy(sEdgeBandTolerance, "Tolerancja dla obrzeży");
	strcpy(sEdgesthatmustbecutduefaults, "Krawędzie, które muszą być przycięte ze względu na defekty");
	strcpy(sEdgetoedge, "Od krawędzi do krawędzi");
	strcpy(sEdit, "Edytuj");
	strcpy(sEmail, "e-mail");
	strcpy(sEmptyData, "Dane są puste!");
	strcpy(sEnabled, "Włączone");
	strcpy(sEnabledisabledefectsoftheinventorysheets, "Włącz/wyłącz defekty");
	strcpy(sEnterLabel, "Wprowadź etykietę");
	strcpy(sEnterTheMaterialName, "Wprowadź nazwę materiału");
	strcpy(sEnterTheProductName, "Wpisz nazwę produktu");
	strcpy(sEvaluationError, "Błąd podczas obliczania wyrażenia!");
	strcpy(sExit, "Wyjście");
	strcpy(sExpired, "Licencja na oprogramowanie wygasła! Proszę zarejestrować program");
	strcpy(sExport, "Eksport");
	strcpy(sExportAllDiagrams, "Wyeksportuj wszystkie rysunki");
	strcpy(sExportAllToASingleFile, "Eksportuj wszystko do jednego pliku");
	strcpy(sExportOptions, "Opcje eksportu.");
	strcpy(sExporttoDXFformat, "Eksport do formatu DXF");
	strcpy(sExporttoExcel, "Eksport do Excel");
	strcpy(sExpresieIncorecta, "Nieprawidłowe wyrażenie matematyczne!");
	strcpy(sExtensions, "Extensions");
	strcpy(sExtra, "Dodatkowy");
	strcpy(sExtraComponents, "Dodatkowe komponenty");
	strcpy(sExtracomponentsattachedtoDemand, "Dodatkowe elementy zostały dołączone do listy formatek");
	strcpy(sFile, "Plik");
	strcpy(sFileName, "Nazwa pliku");
	strcpy(sFillWastes, "Na rysunku zakreskuj odpady.");
	strcpy(sFindoptimalbarsheetsize, "Znajdź optymalną wielkość do rur i arkuszy.");
	strcpy(sFindoptimalsizeofInventorypieces, "Znajdź w magazynie optymalny rozmiar arkuszy.");
	strcpy(sFirstcutMultiplestages, "Pierwszy kierunek skrawania - wiele etapów");
	strcpy(sFirstdirectionforcutishorizontal, "Pierwszy kierunek cięcia jest poziomy.");
	strcpy(sFirstdirectionforcutisvertical, "Pierwszy kierunek cięcia jest pionowy.");
	strcpy(sFollowthecontourofpieces, "Podążaj za konturem formatki");
	strcpy(sFont, "Czcionka");
	strcpy(sFontsize, "Rozmiar czcionki");
	strcpy(sFullInfo, "Pełne informacje");
	strcpy(sDisposedWaste, "Utylizowane odpady");
	strcpy(sGeneral, "Ogólnie");
	strcpy(sGenerateCNC, "Generuj G-KOD");
	strcpy(sGrain, "Tekstura");
	strcpy(sGraindirection, "Kierunek tekstury");
	strcpy(sGraphic, "Graficzny");
	strcpy(sGreaterorequalto, "Większy lub równy");
	strcpy(sGrid, "Stoły");
	strcpy(sGrinding, "Naddatek na szlifowanie");
	strcpy(sGrosimeTaieturaScalata, "Grubość cięcia na tym rysunku nie została przedstawiona w skali. Fakt ten nie wpływa na wyniki optymalizacji");
	strcpy(sGroupidenticallayouts, "Grupowanie identycznych arkuszy");
	strcpy(sGroupIdenticalParts, "Grupuj identyczne formatki");
	strcpy(sGroupingOfIdenticalPiecesIntoOneRow, "Grupowanie identycznych formatek w jednym rzędzie");
	strcpy(sGroupPartsAfterLoadingFromFile, "Grupowanie formatek po wczytaniu z pliku");
	strcpy(sHeight, "Wysokość");
	strcpy(sHeighttolerance, "Tolerancja wysokości");
	strcpy(sHelp, "Pomoc");
	strcpy(sHistory, "Historia");
	strcpy(sHorizontal, "Poziomy");
	strcpy(sHowtodisplayprintedgebands, "Jak wyświetlane są pasma krawędzi?");
	strcpy(sIfyousetthebandforoneedgeallwillreceivethesamevalue, "Jeśli ustawisz pasmo na jedną krawędź, wszyscy otrzymają tę samą wartość.");
	strcpy(sIfyousetthegrindingforoneedgeallwillreceivethesamevalue, "Jeżeli ustawisz wielkość naddatku na szlifowanie, wszystkie krawędzie otrzymają taki sam naddatek.");
	strcpy(sIfyousetthetrimforoneedgeallwillreceivethesamevalue, "Jeżeli ustawisz wielkość przycięcia, wszystkie krawędzie otrzymają taką samą wartość.");
	strcpy(sImageBounds, "Granice rysunku");
	strcpy(sImageSize, "Rozmiar");
	strcpy(sImportData, "Importuj dane");
	strcpy(sIncorrectPassword, "Nieprawidłowe hasło");
	strcpy(sIndex, "Lista");
	strcpy(sInformationaboutcustomer, "Informacje o Kliencie");
	strcpy(sInputALanguageName, "Podaj nazwę języka");
	strcpy(sInsert, "Dodaj");
	strcpy(sInsertPiece, "Dodaj formatkę");
	strcpy(sInterface, "Interfejs");
	strcpy(sInterfaceSettings, "Ustawienia interfejsu");
	strcpy(sInvalidHardware, "Nie mogę wykryć sprzętu! Proszę o kontakt z contact@optimalprograms.com");
	strcpy(sInvalidNumber, "Nieprawidłowy numer");
	strcpy(sInvalidOrderOfComputation, "Nie można ustalić kolejności obliczania długości. Definicja produktu zawiera powiązania cykliczne!");
	strcpy(sInvalidRegistration, "Kod rejestracyjny jest nieprawidłowy !");
	strcpy(sInvalidTime, "Czas systemowy tego komputera jest nieprawidłowy");
	strcpy(sInventory, "Magazyn");
	strcpy(sisafractionalvalue, "Czy jest wartością ułamkową");
	strcpy(sIsArc, "Czy jest łukiem");
	strcpy(sisarealvalue, "Czy jest wartością rzeczywistą.");
	strcpy(sLabel, "Etykieta");
	strcpy(sLabels, "Etykiety");
	strcpy(sLanguage, "Język");
	strcpy(sLatimeanumar0, "Szerokość powinna być większa niż 0!");
	strcpy(sLatimeanumarreal, "Szerokość musi być liczbą rzeczywistą!");
	strcpy(sLayerName, "Nazwa warstwy");
	strcpy(sLeft, "Lewa");
	strcpy(sLeftcoordinateofthedefect, "Lewa współrzędna defektu.");
	strcpy(sLength, "Długość");
	strcpy(sLengthofthepiecestocut, "Rozmiar formatki do wycięcia");
	strcpy(sLengthofthepiecestocutfrom, "Rozmiar arkusza do pocięcia");
	strcpy(sLengthofusedbars, "Rozmiar używanych prętów");
	strcpy(sLicenseAgreement, "Umowa licencyjna");
	strcpy(sLinear, "Liniowy");
	strcpy(sLinethickness, "Grubość pióra");
	strcpy(sLoadafileandappenddatatothecurrentDemand, "Wczytaj plik i dołącz dane do aktualnego zapotrzebowania.");
	strcpy(sLoadanexistingDemandfromafile, "Wczytaj listę formatek z pliku.");
	strcpy(sLoadAppend, "Wczytaj i dodaj do istniejących");
	strcpy(sLoadEverything, "Wczytaj wszystko");
	strcpy(sLoadInventory, "Załaduj arkusze do magazynu");
	strcpy(sLoadInventoryandDemand, "Wczytaj z pliku: arkusze i formatki");
	strcpy(sLoadResults, "Wczytaj wyniki z pliku");
	strcpy(sLocked, "Zamknięty");
	strcpy(sLogo, "Logo");
	strcpy(sLong, "Długość");
	strcpy(sLongerexecutiontime, "Dłuższy czas realizacji");
	strcpy(sLungime, "Szerokość");
	strcpy(sLungimeanumar0, "Długość musi być większa niż 0!");
	strcpy(sLungimeanumarreal, "Długość musi być liczbą rzeczywistą!");
	strcpy(sLungimeaTotalaFolosita, "Całkowita wykorzystana długość");
	strcpy(sMagnification, "Powiększenie");
	strcpy(sMagnify, "Powiększ");
	strcpy(sMargins, "Marginesy");
	strcpy(sMarginsForPaper, "Marginesy papieru");
	strcpy(sMarginsOfTheLabel, "Marginesy etykiety");
	strcpy(sMaterial, "Tworzywo");
	strcpy(sMaterialName, "Nazwa materiału");
	strcpy(sMaterials, "Materiały");
	strcpy(sMaterialstypes, "Typy Materiałów");
	strcpy(sMax, "Maksimum");
	strcpy(sMaximalArea, "Maksymalny powierzchnia");
	strcpy(sMaximalCutLength, "Maksymalna długość cięcia");
	strcpy(sMaxlength, "Maksymalna długość");
	strcpy(sMaxPiecesperBar, "Maksymalna liczba sztuk na bar");
	strcpy(sMaxwidth, "Maksymalna szerokość.");
	strcpy(sMeasurementUnit, "Jednostka miary");
	strcpy(sMin, "Minimum");
	strcpy(sMinimalBreakSize, "Minimalny rozmiar pęknięcie");
	strcpy(sMinimalUsefulSize, "Minimalna użyteczna wielkość");
	strcpy(sMinimalwastesizetoInventory, "Minimany wymiar odpadu, który może być dodany do magazynu");
	strcpy(s_What_to_minimize, "Co minimalizować?");
	strcpy(sMinlength, "Minimalna długość");
	strcpy(sMinwidth, "Minimalna szerokość");
	strcpy(sMirror, "Lustro");
	strcpy(sMirroring, "Odbicie lustrzane");
	strcpy(sMiscellaneous, "Inne statystyki");
	strcpy(sModify, "Zmień");
	strcpy(sModifytheselectedpiece, "Zmień wybraną formatkę");
	strcpy(sMovePiece, "Przenieś formatkę");
	strcpy(sMultiplestages, "Wielu etapach");
	strcpy(sName, "Nazwa");
	strcpy(sNameofedgeband, "Nazwa taśmy krawędziowej");
	strcpy(sNewDEMANDUnsaveddatawillbelost, "Nowe części? Niezapisane dane zostaną utracone!");
	strcpy(sNewLanguage, "Nowy język");
	strcpy(sNewMaterial, "Nowy materiał");
	strcpy(sNewPasswordincorectlyintroduced, "Nowe hasło błędnie wprowadzone!");
	strcpy(sNewProduct, "Nowy produkt");
	strcpy(sNewversion, "Nowa wersja");
	strcpy(sNo, "Nie");
	strcpy(sNumarBucati, "Ilość formatek");
	strcpy(sNumberOfCopies, "Liczba kopii");
	strcpy(sNumberofstages, "Liczba stopni");
	strcpy(sNusuficienteplacidepozit, "Nie wszystkie elementy zostały zoptymalizowane. Możliwe przyczyny: brak wystarczającej liczby arkuszy w magazynie, pole użyj go nie zostało zaznaczone, materiały na liście formatek i w magazynie są różne. Sprawdź także inne parametry optymalizacji!");
	strcpy(sOfficeNotInstaled, "Microsoft Office nie jest zainstalowany na tym komputerze lub zainstalowano niewłaściwą wersję!");
	strcpy(sOldpassworddoesnotmatch, "Stare hasło nie pasuje!");
	strcpy(sOnlinehelp, "Pomoc online");
	strcpy(sOnlypiecesofthesameheightinthelaststage, "Kawałki tej samej wysokości w ostatnim etapie");
	strcpy(sOpen, "Otwórz");
	strcpy(sOptimization, "Optymalizacja");
	strcpy(sOptimizationDone, "");
	strcpy(sOptimizationType, "Typ optymalizacji");
	strcpy(sOptions, "Opcje");
	strcpy(sOptionsrelatedtotheinterface, "Opcje interfejsu");
	strcpy(sor, "lub");
	strcpy(sOthercomponents, "Inne akcesoria");
	strcpy(sOthers, "Inne");
	strcpy(sOtherstatistics, "Inne statystyki");
	strcpy(sOverrideExcelCSVfiles, "Zastąp Excel / CSV");
	strcpy(sParameter, "Parametr");
	strcpy(sParts, "Części");
	strcpy(sPattern, "Model");
	strcpy(sPatternforwaste, "Formuła do identyfikacji odpadów");
	strcpy(sPerimeter, "Obwód");
	strcpy(sPermitedRotationAngle, "Dopuszczalny kąt obrotu.");
	strcpy(sPhone, "Telefon");
	strcpy(sPicture, "Rysunek");
	strcpy(sPiece, "Formatka");
	strcpy(sPieceindex, "Lista formatek");
	strcpy(sPieces, "Sztuk");
	strcpy(sPiecesize, "Wielkość formatki");
	strcpy(sPiecesizelabeledgebandwillbeprinted, "Zostaną wydrukowane: rozmiar formatki, etykieta, taśmy krawędziowe");
	strcpy(sPierdere, "Odpad");
	strcpy(sPixels, "Pikseli");
	strcpy(sPlacilefolositeDepozit, "Wykorzystane elementy z magazynu.");
	strcpy(sPlease_contact_us_at_contact_nestingtechnologies_com, "Prosimy o kontakt na contact@nesting-technologies.com");
	strcpy(sPlease_contact_us_at_contact_optimalprograms_com, "Prosimy o kontakt na contact@optimalprograms.com");
	strcpy(sPleaseenteralldataeitherasfractionalorrealDonotmixthem, "Wprowadź wszystkie dane jako wartości ułamkowe lub rzeczywiste! Nie mieszaj ich!!");
	strcpy(sPleaseEnterSomeTypesOfMaterials, "Nie zdefiniowano rodzaju materiału. Możesz to zrobić w menu materiały");
	strcpy(sPleasesendtheNameandtheCodetotheaddresscontactoptimalprogramscominordertoobtaintheRegistrationKey, "Aby uzyskać klucz rejestracyjny prosze przesłać nazwę i kod na adres: contact@optimalprograms.com.");
	strcpy(sPolygon, "Wielokąt");
	strcpy(sPolygonsCircles, "Wielokąty, koła");
	strcpy(sPrecision, "Precyzja");
	strcpy(sPretulnumar0, "Cena musi być większy od 0!");
	strcpy(sPretulnumarreal, "Cena musi być liczbą rzeczywistą!");
	strcpy(sPreview, "Podgląd");
	strcpy(sPrice, "Cena");
	strcpy(sPriceMustBeGreaterThanZero, "Cena musi być większa od zera");
	strcpy(sPriceofbars, "Cena za pręty");
	strcpy(sPriceperbar, "Cena za 1 pręt");
	strcpy(sPricepersheet, "Cena za 1 arkusz");
	strcpy(sPricepersquareunitofmaterial, "Cena za metr kwadratowy materiału");
	strcpy(sPriceperunit, "Cena za sztukę");
	strcpy(sPrint, "Drukuj");
	strcpy(sPrintdiagramsastables, "Wydrukuj wykresy w formie tabel.");
	strcpy(sPrinter, "Drukarka");
	strcpy(sPrinterBounds, "Marginesy drukarki");
	strcpy(sPrinting, "Drukuj");
	strcpy(sPrintonlyutilizedarea, "Wydrukuj tylko wykorzystaną powierzchnię");
	strcpy(sPrintthecontentsoftheDemand, "Wydrukuj zawartość listy formatek do wycięcia.");
	strcpy(sPrintthecontentsoftheInventory, "Wydrukuj zawartość magazynu.");
	strcpy(sPrintthecurrentsolution, "Drukowanie bieżącego rozwiązania.");
	strcpy(sPriority, "Priorytet");
	strcpy(sPrioritytocutapieceZero0isthehighestpriority, "Priorytet wycinania formatki: 0 najwyższy.");
	strcpy(sProcentul0100, "Wartość w procentach musi być większą od 0 i <100!");
	strcpy(sProcentulnumarreal, "Wartość w procentach musi być liczbą rzeczywistą!");
	strcpy(sProductdefinition, "Parametry produktu.");
	strcpy(sProductExists, "Produkt już istnieje. Wybierz inną nazwę.");
	strcpy(sProductName, "Nazwa produktu");
	strcpy(sProducts, "Produkt");
	strcpy(sProducts, "Produkty");
	strcpy(sProject, "Projekt");
	strcpy(sProperties, "Właściwości");
	strcpy(sProperty, "Cecha");
	strcpy(sQuantity, "Ilość");
	strcpy(sQuantitynumberofsheetsofthistype, "Liczba arkuszy tego rodzaju");
	strcpy(sRadius, "Promień");
	strcpy(sRectangular, "Prostokątne");
	strcpy(sRedefinetypesofedgeband, "Zmień typ wykończenia krawędzi");
	strcpy(sRedefinetypesofmaterial, "Zmień rodzaj materiału");
	strcpy(sRegistration, "Rejestracja");
	strcpy(sRegistrationKeyfromOptimalPrograms, "Klucz rejestracyjny");
	strcpy(sRegistrationSuccessful, "Rejestracja zakończona sukcesem!");
	strcpy(sRemoveallpiecesinInventory, "Usuń wszystkie elemnty z magazynu.");
	strcpy(sRemoveCut, "Usuń cięcie");
	strcpy(sRemovetheselectedpiece, "Usuń wybraną formatkę");
	strcpy(sReports, "Raporty");
	strcpy(sRequestedMaterial, "Preferowany typ materiału");
	strcpy(sRestore, "Przywróć");
	strcpy(sResults, "Wyniki");
	strcpy(sReusedwaste, "Odpady do ponownego wykorzystania");
	strcpy(sRight, "Prawo");
	strcpy(sRightcoordinateofthedefect, "Prawa współrzędna defektu.");
	strcpy(sRotation, "Obrót");
	strcpy(sRotationAngle, "Kąt obrotu.");
	strcpy(sRotationStep, "Krok obrotu.");
	strcpy(sRoundAllFractionsTo, "Ułamkową wartość należy zaokrąglić do");
	strcpy(sRow, "Rząd");
	strcpy(sRows, "Rzędy");
	strcpy(sRun, "Najnowsze rozwiązania");
	strcpy(sRunningtime, "Czas od uruchomienia");
	strcpy(sSameforall, "To samo dla wszystkich");
	strcpy(sSave, "Zapisz");
	strcpy(sSaveAllImages, "Zapisz wszystkie obrazy");
	strcpy(sSaveAs, "Zapisz jako");
	strcpy(sSaveChanges, "Formatki zostały zmienione. Czy chcesz zapisać zmiany?");
	strcpy(sSaveCurrentImage, "Zapisz aktualny obraz");
	strcpy(sSavedataparameters, "Zapisz dane i parametry");
	strcpy(sSaveEverything, "Zapisz wszystko");
	strcpy(sSaveInventory, "Zapisz stan magazynu.");
	strcpy(sSaveInventoryandDemand, "Zapisz listę formatek i stan magazynu");
	strcpy(sSaveResults, "Zapisz wyniki");
	strcpy(sSaveStatisticsinafile, "Zapisz statystyki w pliku");
	strcpy(sSavethecurrentimage, "Zapisz bieżący obraz");
	strcpy(sSavethecurrentimageorstatistic, "Zapisz bieżący obraz lub statystykę");
	strcpy(sSavetheDEMANDinafile, "Zapisz do pliku");
	strcpy(sSavetheDemandinafilewithadifferentname, "Zapisz listę formatek do pliku pod inną nazwą");
	strcpy(sSavetheREPOSITORYinafile, "Zapisz do pliku stan magazynu");
	strcpy(sSerialNumber, "Klucz rejestracyjny");
	strcpy(sService, "Serwis");
	strcpy(sSetDefaultValues, "Spowoduje to przywrócenie wszystkich parametrów do ich wartości domyślnych. Wszystkie ustawienia zostaną utracone. Czy jesteś pewien, że chcesz to zrobić?");
	strcpy(sSetedgeband, "Ustaw obszar krawędzi");
	strcpy(sSetedgetrim, "Ustaw margines cięcia pozwalający pominięcie defektów");
	strcpy(sSetthesameedgebandforalledges, "Ustaw taki sam margines dla wszystkich krawędzi");
	strcpy(sSetthesamegrindingforalledges, "Ustaw taki sam naddatek na szlifowanie dla wszystkich krawędzi");
	strcpy(sSetthesametrimforalledges, "Ustaw takie samo cięcie ze względu na defekty dla wszystkich krawędzi");
	strcpy(sSettings, "Ustawienia");
	strcpy(sShape, "Kształt");
	strcpy(sSheet, "Arkusz");
	strcpy(sSheetsBarstypes, "Typy prętów i arkuszy");
	strcpy(sSheetSize, "Rozmiar arkusza");
	strcpy(sSheetsperPage, "Ilość arkuszy na stronie");
	strcpy(sShort, "Krótki");
	strcpy(sShorterexecutiontime, "Krótki czas pracy");
	strcpy(sShowallsimpleproducts, "Pokaż wszystkie nieskomplikowane formatki");
	strcpy(sShowcustomername, "Pokaż nazwę klienta");
	strcpy(sShowCustomTextOnEachPiece, "Pokaż niestandardowy tekst na każdej formatce");
	strcpy(sShowdiagramasatable, "Pokaż schemat jako tabelę");
	strcpy(sShowedgeband, "Pokaż taśmy krawędziowe");
	strcpy(sShowedgebandssettinginanewwindow, "Pokaż w nowym oknie ustawienia taśm krawędziowych");
	strcpy(sShowgrindingsettingsinanewwindow, "Pokaż w nowym oknie ustawienia szlifowania");
	strcpy(sShowHorizontalLabelsAlways, "Zawsze pokazuj poziome etykiety");
	strcpy(sShowRemovethesizeofthepiecesinthecurrentsolution, "Pokaż/ukryj rozmiar formatki");
	strcpy(sShowRemovethesizeofthewastesinthecurrentsolution, "Pokaż/ukryj ilość odpadów do utylizacji");
	strcpy(sShowtotalcutlength, "Pokaż całkowitą długość cięcia");
	strcpy(sShowtrimedgesettingsinanewwindow, "Pokaż w nowym oknie ustawienia defektów");
	strcpy(sSimpleMaterialExists, "Nazwa arkusza już istnieje. Proszę podaj inną nazwę.");
	strcpy(sSinglePieceStrips, "Ilość pasków z jednego kawałka");
	strcpy(sSizes, "Rozmiary");
	strcpy(sSmallerorequalto, "Mniejsza lub równa");
	strcpy(sSort, "Sortuj");
	strcpy(sSortAscendingByArea, "Sortuj rosnąco według powierzchni.");
	strcpy(sSortDescendingByArea, "Sortuj malejąco według powierzchni.");
	strcpy(sSpecifyhowdifferentthepiecesinthelaststagecanbeValue0meansnodifference, "Określ, jak różne mogą być kawałki w ostatnim etapie. Wartość 0 oznacza, nie ma różnicy.");
	strcpy(sSpecifyifpiecesinthelaststagecanbedifferentornotdepeultimaetapapotfidiferitesaunucadimensiune, "Czy formatki na ostatnim etapie mogą się różnić?");
	strcpy(sSpecifyifthepiececanberotatedornotIfnotitwillbecutinthesamewayasitwasintroducedinDemandLengthofthepieceparalleltothelengthofthesheet, "Czy formatkę można obracać przy wycinaniu? Jeżeli nie, to zostanie ona wycięta zgodnie z kierunkowością określoną na zestawieniu (długość równoległa do długości arkusza), ");
	strcpy(sSpecifyinhowmanystageswemakethecutsDuringastageallcutshavethesamedirection, "W ilu etapach możemy wykonywać cięcie?");
	strcpy(sStartthesearchprocess, "Wyszukaj");
	strcpy(sStatistics, "Statystyka");
	strcpy(sStatisticsE, "Dodatkowe raporty");
	strcpy(sStatisticsforeachtypeofmaterial, "Statystyki dla każdego rodzaju materiału");
	strcpy(sStep, "Krok");
	strcpy(sStergeDepozit, "Czy chcesz usunąć arkusze z magazynu?");
	strcpy(sStergeMaterial, "Czy chcesz usunąć materiał?");
	strcpy(sStergePiesele, "Czy chcesz usunąć formatkę?");
	strcpy(sStergePiesa, "Czy chcesz usunąć formatkę?");
	strcpy(sStopthesearchprocess, "Zatrzymaj wyszukiwanie");
	strcpy(sStrongoptimization, "Silna optymalizacja");
	strcpy(sSubtractthebandthicknessfrompiecesize, "Zmniejszyć rozmiar kawałek z grubości zespołu");
	strcpy(sSummary, "Podsumowanie");
	strcpy(sSuprafataTotalaFolosita, "Całkowita powieżchnia wyciętych formatek");
	strcpy(sSuprafatautilizata, "Wykorzystanie");
	strcpy(sSwitchbetweenfiberandrotationoption, "Przełączać się między włókna i opcji rotacji.");
	strcpy(sTechnical, "Parametry techniczne");
	strcpy(sTechnicalsettings, "Ustawienia techniczne");
	strcpy(sTemporaryPanelHint, "Panel tymczasowy do przesuwania części między arkuszami.");
	strcpy(sText, "Tekst");
	strcpy(sThe_application_has_expired, "Licencja tego programu wygasła.");
	strcpy(sThe_application_is_not_registered, "Oprogramowanie nie jest zarejestrowane");
	strcpy(sThe_application_was_first_started_on, "Program został uruchomiony po raz pierwszy");
	strcpy(sThecutsareperformedfromasidetotheothersideofthematerial, "Cięcia są wykonywane na wskroś.");
	strcpy(sThecuttingmachinecanfollowtheshapeofthematerial, "Maszyna tnąca może podążać za kształtem elementu.");
	strcpy(sTheedgesofsheetsthatmustbetrimedduefaults, "Krawędzie arkuszy, które należy przyciąć z powod defektów.");
	strcpy(sTheLargestSize, "Największy rozmiar");
	strcpy(sThenameofthecustomerforwhichyoucutthepiece, "Nazwa zamawiającego");
	strcpy(sThenameofyourcustomer, "Nazwa klienta");
	strcpy(sThepiececanberotated, "Formatka może być obracana");
	strcpy(sTheprogramtriestoavoidwasteswhichhavebothsizeslessthanthisvalue, "Program stara się uniknąć odpadów o wymiarach mniejszych od tej wartości");
	strcpy(sThereAreNoProducts, "Nie ma jeszcze określonych produktów");
	strcpy(sThestockofmaterialhasbeenpreviouslyloadedfromanExcelorCSVformatPleaseloaditagain, "Zapasy materiału zostały wcześniej załadowane do magazynu z pliku w formatcie Excel lub CSV. Proszę załadować go ponownie, jeśli chcesz pracować na nim.");
	strcpy(sThetotallengthofcutting, "Łączna długość cięcia");
	strcpy(sThewidthofthecuttingsawForglasscuttingoptimizationitcanbe0Forwooditshouldbegreaterthan0, "Grubość piły: do szkła może być = 0 do innych materiałów powinien być > 0");
	strcpy(sThewidthofthecuttingsawforlinearpieces, "Grubość piły do elementów liniowych.**");
	strcpy(sThickness, "Grubość");
	strcpy(sThischaracterisusedforfillingthewasterectanglesIfyoudonotwantfilledwastejustremovethischaracter, "Ten symbol jest używany do wypełniania prostokątów odpadów. Jeśli nie chcesz, wypełniony odpadami po prostu usuń go.");
	strcpy(sThisindexhasvaluebetween1andthenumberofpieces, "Ten index przybiera wartość od 1 do liczby sztuk.");
	strcpy(sThisOptionWillOverrideTheInventoryFileIfLoadedFromExcelOrCsvFiles, "Ta opcja nadpisze plik magazyn, jeśli zostanie załadowany plik programu Excel lub CSV");
	strcpy(sThisProgramisLicensedTo, "Ten program jest licencjonowany");
	strcpy(sThisvaluewillbeaddedtotheedgebandingmaterialoneachside, "Wartość ta będzie dodane do materiału krawędzi pasów na każdej stronie");
	strcpy(sTipNevid, "Pole rodzaj materiału nie może być puste");
	strcpy(sTitle, "Tytuł");
	strcpy(sTools, "Narzędzia");
	strcpy(sTop, "Góra");
	strcpy(sTopcoordinateofthedefect, "Górna współrzędna defektu.");
	strcpy(sTotalGarbageWaste, "Wszystkie odpady do utylizacji");
	strcpy(sTotalInventoryWaste, "Odpady magazynowe ogółem.");
	strcpy(sTotalRecycledWaste, "Cały ponownie wykorzystany odpad.");
	strcpy(sTotalusedarea, "Całkowita użyta powierzchnia.");
	strcpy(sTotalusedlength, "Całkowita długość używane");
	strcpy(sTrigonometric, "Trygonometryczny");
	strcpy(sTrim, "Przytnij.");
	strcpy(sTrimalledgesatthebeginning, "Przytnij wszystkie krawędzie.");
	strcpy(sTrimEdge, "Przytnij krawędzie.");
	strcpy(sTwoPanels, "2 panele");
	strcpy(sType, "Typ");
	strcpy(sTypeofmaterialfromwhichtocut, "Rodzaj materiału, z którego mam wyciąć.");
	strcpy(sTypesAreNotMatched, "Optymalizacja nie została przeprowadzona! Materiały z tabel części i zapasów nie pasują do siebie! Można wyciąć część tylko z materiału o tej samej nazwie w magazynie. Zmień nazwy materiałów w odpowiednich kolumnach!");
	strcpy(sUndo, "Anuluj");
	strcpy(sUndoAccept, "Cofnij Akceptuj");
	strcpy(sUnits, "szt.");
	strcpy(sUnregisteredVersion, "Niezarejestrowany");
	strcpy(sUpdates, "Aktualizacje");
	strcpy(sUsefulforwoodfurniture, "Przydatne do mebli z drewna");
	strcpy(sUseit, "Użyj go");
	strcpy(sUsePieceinOptimization, "Użyj kawałek w optymalizacji");
	strcpy(sUserName, "Nazwa użytkownika");
	strcpy(sUtilizationandWastes, "Wykorzystanie i odpad");
	strcpy(sUtilizedArea, "Powierzchnia wyciętych formatek");
	strcpy(sUtilizedBars, "Wykożystane pręty");
	strcpy(sUtilizeddemandcount, "Liczba wykorzystanych formatek.");
	strcpy(sUtilizedParts, "Wykorzystane części");
	strcpy(sUtilizedPieces, "Wykorzystywane kawałki");
	strcpy(sUtilizedSheets, "Wykorzystane arkusze");
	strcpy(sValue, "Wartość");
	strcpy(sValueGreaterEqualToZero, "Wartość musi być większa lub równa zero");
	strcpy(sValueGreaterThanZero, "Wartość musi być większa niż zero");
	strcpy(sValueIntegerNumber, "Wartość musi być liczbą całkowitą!");
	strcpy(sValueRealNumber, "Wartość musi być liczbą rzeczywistą. Być może użyłeś przecinka zamiast kropki lub odwrotnie. Proszę napraw to!");
	strcpy(s_The_number_is_too_big_or_it_has_too_many_digits_after_decimal_separator, "Liczba jest za duża lub ma za dużo cyfr po separatorze dziesiętnym!");
	strcpy(s_The_number_is_too_big, "Liczba jest za duża!");
	strcpy(sVertical, "Pionowy");
	strcpy(sWaste, "Odpad");
	strcpy(sWastes, "Odpad");
	strcpy(sWasteAddedToWarehouse, "Odpad do odzysku dodany do magazynu");
	strcpy(sWastelimits, "Limity dla odpadów");
	strcpy(sWasteType, "Rodzaj odpadów");
	strcpy(sWeakoptimization, "Najsłabsza optymalizacja");
	strcpy(sWhattoprint, "Co wydrukować?");
	strcpy(s_What_to_print_or_save_to_file, "Co wydrukować lub zapisać do pliku");
	strcpy(sWhattoprintoneachpiece, "Co mam wydrukować na każdej formatce?");
	strcpy(sWhattoshowoneachpiece, "Co mam pokazać na każdej formatce?");
	strcpy(sWidth, "Szerokość");
	strcpy(sWood, "Drewno");
	strcpy(sWorkingDirectory, "Katalog roboczy");
	strcpy(sWrongKey, "Niewłaściwy klucz rejestracyjny!");
	strcpy(sYes, "Tak");
	strcpy(sYoucannotchooseblackblueorredcolors, "Nie możesz wybrać koloru czarnego, niebieskiego ani czerwonego.");
	strcpy(sYouCannotMixFractionalDataWithDecimalOnes, "Nie można mieszać wartości ułamkowych z wartościami rzeczywistymi.");
	strcpy(sYourcompany, "Nazwa Twojej firmy.");
	strcpy(sZip, "Kod pocztowy");
	strcpy(s_Set_the_origin_and_the_direction_of_the_axes, "Ustaw początek i kierunek osi współrzędnych.");










	strcpy(s_Number_of_digits_after_the_decimal_separator, "Liczba cyfr po separatorze dziesiętnym");
	strcpy(s_Percentages, "Procenty");
}

