// Language strings: Albanian
// Author: Optimal Programs
// License: MIT License
//---------------------------------------------------------------------------
#include <string.h>
//---------------------------------------------------------------------------
#include "language_string_id.h"
//---------------------------------------------------------------------------
void set_sq(void)
{
	//Albanian
	//translated with google translate on 2020.07.06
	//2025.3.29.0
	strcpy(s_Advanced, "E avancuar");
	strcpy(s_Relative_coordinates, "Koordinatat relative");
	strcpy(s_Absolute_coordinates, "Koordinatat absolute");
	strcpy(s_Append_more_rows, "Shtoni më shumë rreshta");

	strcpy(s_Add_to_parts, "Shtoni në pjesë.");
	strcpy(s_Additional, "Shtesë");
	strcpy(s_All_results, "Të gjitha rezultatet.");
	strcpy(s_Allow_movement_of_pieces, "Lejoni lëvizjen e pjesëve");
	strcpy(s_Allow_part_in_part, "Lejo pjesë-pjesë");
	strcpy(s_Invalid_piece_Angles_are_too_small_or_too_big_or_height_is_too_small, "Pjesë e pavlefshme! Këndet janë shumë të vogla ose shumë të mëdha, ose lartësia është shumë e vogël.");
	strcpy(s_Append, "bashkangjit");
	strcpy(s_As_it_is, "Ashtu sic eshte");
	strcpy(s_As_text, "Si tekst");
	strcpy(s_Ascending, "Në ngjitje");
	strcpy(s_Automatic, "Automatik");
	strcpy(s_Cannot_connect_to_the_Internet_Please_visit_our_website_from_a_browser, "Nuk mund të lidhet me Internetin! Ju lutemi vizitoni faqen tonë të internetit nga një shfletues.");
	strcpy(s_Cannot_copy_or_move_the_files, "Nuk mund të kopjoni ose zhvendosni skedarët!");
	strcpy(s_Cannot_delete_the_file, "Skedari nuk mund të fshihet!");
	strcpy(s_Cannot_modify_old_results, "Rezultatet e vjetra nuk mund të modifikohen!");
	strcpy(s_To_change_click_inside_a_cell_or_press_0_1_or_2, "Për të ndryshuar, klikoni brenda një qelize ose shtypni 0, 1, ose 2.");
	strcpy(s_Cell, "Qelizë");
	strcpy(s_Click_on_the_table_header_to_change_the_columns, "Klikoni në kokën e tabelës për të ndryshuar kolonat.");
	strcpy(s_Close, "Mbylle");
	strcpy(s_Contact_us, "Na kontaktoni");
	strcpy(s_Column, "Kolona");
	strcpy(s_Comma, "presje");

	strcpy(s_Copy, "Kopjoni");
	strcpy(s_Copy_for_move, "Kopjoni për lëvizje");
	strcpy(s_Cut_higher_level_strips_first, "Pritini së pari shiritat e nivelit më të lartë");
	strcpy(s_Cut_index, "Indeksi i prerjes");

	strcpy(s_The_data_have_been_changed_Do_you_want_to_save_them_to_a_file, "Të dhënat janë ndryshuar. Dëshironi t'i ruani në një skedar?");
	strcpy(s_Decimal_separator, "Ndarëse dhjetore");
	strcpy(s_Restore_default_settings, "Rivendos cilësimet e paracaktuara");
	strcpy(s_Delete_fiber, "Fshini fibrat");
	strcpy(s_Descending, "Zbritni");
	strcpy(s_Discard_changes, "Hidhni ndryshimet");

	strcpy(s_Delete_all_data, "Të fshihen të gjitha të dhënat?");
	strcpy(s_Dot, "Pika");
	strcpy(s_Do_you_want_to_delete_the_picture, "Dëshironi të fshini foton?");
	strcpy(s_Do_you_want_to_delete_the_product, "Dëshironi të fshini produktin?");
	strcpy(s_Duplicate_and_append, "Dublikoni dhe shtoni.");
	strcpy(s_Duplicate_values_are_ignored, "Vlerat e kopjuara nuk merren parasysh!");
	strcpy(s_Error, "Gabim");
	strcpy(s_Error_loading_file, "Gabim gjatë ngarkimit të skedarit.");
	strcpy(s_export_everything, "Eksporto gjithçka");
	strcpy(s_Fit_to_screen, "Përshtatet në ekran.");
	strcpy(s_Force_fixed_height, "Vizatoni pjesët me një lartësi të caktuar.");
	strcpy(s_Flipped, "Përmbys");
	strcpy(s_Import, "import");
	strcpy(s_If_angles_are_different_from_90_degrees_height_must_be_greater_than_0, "Nëse këndet janë të ndryshme nga 90 gradë, lartësia duhet të jetë më e madhe se 0.");
	strcpy(s_Ignore, "Injoro");
	strcpy(s_Incorrect_value, "Vlera e gabuar");
	strcpy(s_Info, "Informacion");
	strcpy(s_Interior, "i brendshëm");
	strcpy(s_Give_a_name, "Jep një emër.");
	strcpy(s_Group, "Grupojeni atë");
	strcpy(s_Header, "Kreu");
	strcpy(s_Keep_it_as_it_is, "Mbajeni ashtu siç është");
	strcpy(s_Level, "Level");
	strcpy(s_Licensee, "I licencuari");
	strcpy(s_List_separator, "Ndarës i listës");
	strcpy(s_Made_with_love_in_Cugir_Romania, "E bërë, me dashuri, në Cugir, Rumani");
	strcpy(s_Made_in, "Prodhuar në");
	strcpy(s_Manufacturer, "Prodhuesi");

	strcpy(s_Manual_arrange, "Rregulloni manualisht");

	strcpy(s_Mixed, "i përzier");
	strcpy(s_Multiple_shapes_detected_Next_rows_will_be_overwritten_Continue, "U zbuluan më shumë se një formë. Prandaj, rreshtat pasues do të mbishkruhen. Të vazhdohet?");
	strcpy(s_More, "Më shumë");
	strcpy(s_Multiple_values, "Vlera të shumëfishta");
	strcpy(s_No_texture, "Nuk ka teksturë");
	strcpy(s_Number, "Numrin");
	strcpy(s_Number_of_images, "Numri i imazheve");
	strcpy(s_Number_of_vertices, "Numri i vertikteve");
	strcpy(s_Offset, "Kompensimi");
	strcpy(s_Only_the_currently_selected_items, "Vetëm artikujt e zgjedhur aktualisht.");
	strcpy(s_Optimizing_please_wait, "Duke u optimizuar ... ju lutemi prisni.");

	strcpy(s_Paste, "Paste");

	strcpy(s_Piece_label, "Etiketa e pjesës");
	strcpy(s_Piece_size, "Madhësia e copës");
	strcpy(s_Please_contact_us_by_email_if_you_receive_this_error, "Ju lutemi na kontaktoni me email nëse e merrni këtë gabim.");
	strcpy(s_Please_save_it_first, "Ju lutem ruajeni së pari.");
	strcpy(s_Position, "Pozicioni");
	strcpy(s_Preview, "Paraprakisht");
	strcpy(s_Rectangle, "Drejtkëndësh");

	strcpy(s_Redo_the_last_operation, "Rivendosni operacionin e fundit");
	strcpy(s_Regular_polygon, "Poligoni i rregullt");

	strcpy(s_Reused, "Ripërdorur");
	strcpy(s_Rotated, "Ndërruar");
	strcpy(s_Save_all, "Ruaj te gjitha");
	strcpy(s_Scrap_label, "Etiketa e skrapit");
	strcpy(s_Scrap_size, "Madhësia e skrapit");
	strcpy(s_Semicolon, "Pikëpresje");
	strcpy(s_Show_cut_index, "Trego indeksin e prerjeve");
	strcpy(s_Show_information, "Trego informacione");
	strcpy(s_Show_piece_label, "Trego etiketën e pjesës");
	strcpy(s_Show_scrap_label, "Trego etiketën e skrapit");
	strcpy(s_Show_scrap_s_size_on_the_small_pieces, "Trego madhësinë e skrapit në copat e vogla");
	strcpy(s_Show_size_of_pieces, "Trego madhësinë e pjesës");
	strcpy(s_Show_size_of_scrap, "Trego madhësinë e skrapit");
	strcpy(s_Show_sizes, "Trego madhësitë");
	strcpy(s_Show_label, "Shfaq etiketën");
	strcpy(s_Show_length, "Trego gjatësinë");

	strcpy(s_Some_numerical_values_are_incorrect_Should_I_fix_all_the_incorrect_values, "Disa vlera numerike janë të pasakta! A duhet të rregulloj të gjitha vlerat e pasakta?");
	strcpy(s_Some_invalid_values_have_been_removed, "Disa vlera të pavlefshme janë hequr.");
	strcpy(s_Sort_by, "Ndaj sipas");
	strcpy(s_Sort_ascending_by, "Rendit duke u ngjitur nga");
	strcpy(s_Sort_descending_by, "Rendit duke zbritur nga");
	strcpy(s_Start, "Start");
	strcpy(s_Starting_angle, "Këndi i fillimit");


	strcpy(s_Stock, "Aksionare");
	strcpy(s_Stop, "Stop");

	strcpy(s_Tabular, "Tabela");
	strcpy(s_Total, "Total");
	strcpy(s_Total_size, "Madhësia totale");
	strcpy(s_Terms_of_the_license, "Kushtet e licencës");
	strcpy(s_The_current_product_has_been_changed_Do_you_want_to_save_it_to_file, "Produkti aktual është ndryshuar. A doni ta ruani atë për të paraqitur?");
	strcpy(s_The_value_is_out_of_the_allowed_range, "Vlera është jashtë kufijve të lejuar.");
	strcpy(s_The_value_must_be_a_real_or_fractional_number_Try_to_replace_the_comma_with_the_dot_if_you_want_to_enter_a_real_number, "Vlera duhet të jetë një numër real ose i pjesshëm. Provoni të zëvendësoni presjen me pikën nëse doni të vendosni një numër të vërtetë.");
	strcpy(s_This_feature_is_not_implemented_yet, "Kjo veçori nuk është zbatuar ende.");
	strcpy(s_This_operation_cannot_be_reversed, "Ky operacion nuk mund të kthehet mbrapsht.");
	strcpy(s_Undo_the_last_operation, "Zhbëj operacionin e fundit.");
	strcpy(s_Utilization, "Shfrytëzimi");
	strcpy(s_Utilized_Stock, "Stoku i shfrytëzuar");
	strcpy(s_Version, "Version");
	strcpy(s_Visible_columns, "Kolona të dukshme");
	strcpy(s_You_already_have_the_latest_version_installed, "Tashmë keni versionin më të ri të instaluar!");
	strcpy(s_What_is_exported, "Çfarë eksportohet?");
	strcpy(s0meansanynumberofpieces, "Zero do të thotë çdo numër i pjesëve");
	strcpy(sAbout, "për");
	strcpy(sAccept, "pranoj");
	strcpy(sAcceptall, "Pranoni të gjitha");
	strcpy(sAcceptthecurrentsolution, "Pranoni zgjidhjen aktuale");
	strcpy(sAdd, "Shtoj");
	strcpy(sAddapiece, "Shtoni një copë");
	strcpy(sAddasimpleproducttoDemand, "Shtoni një produkt në pjesët ekzistuese.");
	strcpy(sAddgrindingthicknesstopartsize, "Shtoni trashësinë e bluarjes në madhësinë e pjesës");
	strcpy(sAddproductnametolabel, "Shtojeni emrin e produktit në etiketë");
	strcpy(sAddress, "Adresë");
	strcpy(sAddselectedsizetoInventory, "Shtoni madhësinë e zgjedhur në magazinë");
	strcpy(sAdhesivelabels, "Etiketat ngjitëse");
	strcpy(sAdhesivelabelwithinformationaboutpiecesinDemandCustomernameLabelSizeCurrentData, "Etiketë ngjitëse me informacione për pjesët: Emri i klientit, Etiketa, Madhësia, Të dhënat aktuale etj.");
	strcpy(sAdhesivelabelwithinformationaboutsheetsinInventory, "Etiketa ngjitëse me informacione rreth fletëve në magazinë.");
	strcpy(sAll, "të gjithë");
	strcpy(sAlloffcutswhichhavethesizegreaterthanthisvaluewillbeaddedtoInventory, "Të gjitha skrapet më të mëdha se kjo vlerë do të shtohen në stok");
	strcpy(sAllowMirroring, "Lejoni rrokullisjen");
	strcpy(sAllowRotation, "Lejo rotacionin");
	strcpy(sAllPieces, "Të gjitha pjesët");
	strcpy(sAllpredefinedproducts, "Të gjitha produktet e paracaktuara");
	strcpy(sAnewwindowwillbedisplayedwheretheusercansettheedgebandsforeachedge, "Do të shfaqet një dritare e re ku përdoruesi mund të vendosë brezin e skajit për secilën anë.");
	strcpy(sAnewwindowwillbedisplayedwheretheusercansetthegrindingvalueforeachedgeofthsheet, "Do të shfaqet një dritare e re ku përdoruesi mund të vendosë madhësinë e bluarjes për secilën anë të pjesës.");
	strcpy(sAnewwindowwillbedisplayedwheretheusercansetthetrimvalueforeachedgeofthsheet, "Do të shfaqet një dritare e re ku përdoruesi mund të vendosë vlerën e shkurtimit për secilën anë të pjesës.");
	strcpy(sAngle, "kënd");
	strcpy(sAngles, "kënd");
	strcpy(sAnoptimizationparameterisarealnumber, "Një parametër i optimizmit është një numër real.");
	strcpy(sAnoptimizationparameterisfractionalnumber, "Një parametër i optimizmit është numri thyesor.");
	strcpy(sAnyShape, "Forma e vërtetë");
	strcpy(sApolygonmusthaveatleast2vertices, "Një shumëkëndësh duhet të ketë të paktën 2 vertikale!");
	strcpy(sApolygonmusthaveatleast3vertices, "Një shumëkëndësh duhet të ketë të paktën 3 vertikale!");
	strcpy(sApplication_fails_to_initialize, "Aplikacioni dështoi në inicializimin!");
	strcpy(sArc, "hark");
	strcpy(sArcLength, "Gjatësia e harkut");
	strcpy(sAreaofusedsheets, "Zona e fletëve të përdorura");
	strcpy(sAshortdescriptionofthesheet, "Një përshkrim i shkurtër i fletës");
	strcpy(sAtleastonepart, "Ju duhet të futni të paktën një pjesë.");
	strcpy(sAtTheMarginOfTheSheet, "Në kufirin e fletës");
	strcpy(sBandtypes, "Llojet e brezave të skajeve");
	strcpy(sBar, "bare");
	strcpy(sBars, "bare");
	strcpy(sBothsizesoftheoffcutsmustbegreaterthanthisvalue, "Të dy madhësitë e skrapit duhet të jenë më të mëdha se kjo vlerë.");
	strcpy(sBottom, "fund");
	strcpy(sBottomcoordinateofthedefect, "Koordinata e poshtme e defektit");
	strcpy(sBreakCut, "Prish prerjen");
	strcpy(sBrowse, "Shfleto");
	strcpy(sBuy, "Blej");
	strcpy(sBuynow, "Bleni tani ...");
	strcpy(sCancel, "Anulojeni atë");
	strcpy(sCannotBeEmpty, "nuk mund të jetë bosh!");
	strcpy(sCannotmovepartsbetweensheetswhenidenticalsheetsaregroupedPleaseungroupthesheetsfrommenu, "Nuk mund të lëvizë pjesët nga një fletë në tjetrën nëse fletët identike janë të grupuara. Ju lutemi anuloni grupimin e fletëve nga menuja.");
	strcpy(sCannotSaveFile, "Nuk mund të ruhet skedari");
	strcpy(sCenter, "qendër");

	strcpy(sChangeDirection, "Ndryshoni drejtimin e prerë");
	strcpy(sChoose, "zgjedh");
	strcpy(sChooseProduct, "Zgjidhni produktin");
	strcpy(sCircle, "rreth");
	strcpy(sCity, "qytet");
	strcpy(sClear, "Qartë");
	strcpy(sClockWise, "clockwise");
	strcpy(sClosewindow, "Mbyll dritaren");
	strcpy(sColor, "Ngjyrë");
	strcpy(sColorofedgeband, "Ngjyra e brezave të skajeve");
	strcpy(sColorPattern, "Ngjyra / modeli");
	strcpy(sColorpiecesandwastes, "Pjesë dhe mbeturina me ngjyra");
	strcpy(sColumns, "kolonë");
	strcpy(sComment, "koment");
	strcpy(sCompanyname, "Emri i Kompanise");
	strcpy(sComplexMaterialExists, "Emri i materialit është përcaktuar tashmë në listën e materialeve komplekse. Ju lutemi jepni një emër të ri.");
	strcpy(sComputerCode, "Kodi kompjuterik");
	strcpy(sComputerCodefromyourcomputer, "Kodi i kompjuterit (nga kompjuteri juaj)");
	strcpy(sComputethetotalpriceofDemand, "Llogaritni çmimin e përgjithshëm të Pjesëve");
	strcpy(sContents, "përmbajtje");
	strcpy(sContinutComanda, "Përmbajtja e pjesëve në datë");
	strcpy(sContinutDepozit, "Përmbajtja e aksioneve në datë");
	strcpy(sConversionIsDoneOnlyWhenSomePiecesHaveFractionalValues, "Konvertimi bëhet vetëm kur disa pjesë kanë vlera thyese.");
	strcpy(sConvertsTheSizeOfWasteToAFractionalUnit, "Tregon madhësinë e skrapit si një vlerë e pjesshme.");
	strcpy(sCouldNotSaveFile1, "Nuk mund ta shkruaj skedarin në drejtori");
	strcpy(sCouldNotSaveFile2, "Ju mund të mos keni të drejta të mjaftueshme. Ju lutemi kontrolloni ose ndryshoni drejtorinë e punës nga menuja Cilësimet | Drejtoria e punës në një dosje ku ju keni të drejtë të shkruani (për shembull c: \\ temp).");
	strcpy(sCreationdateYMDHMS, "Data e krijimit (Y / M / D- H: M: S)");
	strcpy(sCurrentDate, "Data aktuale");
	strcpy(sCurrentDiagram, "Diagrami aktual");
	strcpy(sCurrentMaterial, "Materiali aktual");
	strcpy(sCurrentversion, "Versioni aktual");
	strcpy(sCurve_not_closed_Try_increasing_DXF_linking_distance_parameter, "Poligoni nuk është i mbyllur! Provoni të rritni parametrin DXF që lidh distancën.");
	strcpy(sCustomer, "klient");
	strcpy(sCustomerName, "Emri i Klientit");
	strcpy(sCustomMessage, "Mesazh personal");
	strcpy(sCutlength, "Gjatësia e prerjes");
	strcpy(sCut, "Prerje");
	strcpy(sCuts, "Prerje");
	strcpy(sCutterThickness, "Trashësia e prerë");
	strcpy(sData, "të dhëna");
	strcpy(sDataCannotBeEmpty, "Të dhënat nuk mund të jenë bosh!");
	strcpy(sDateymdhms, "Data (y / m / d / h / m / s)");
	strcpy(sDays_left_for_trial, "Ditët kanë mbetur për gjyq");
	strcpy(sDaysLeft, "ditë të mbetura");
	strcpy(sStandard, "standard");
	strcpy(sDefaultInterface, "Ndërfaqja e paracaktuar");
	strcpy(sDefects, "defektet");
	strcpy(sDefectsManager, "Menaxhoni defektet");
	strcpy(sDefectsofthematerialNopiecescanbeplacedinthefaultyzone, "Defektet e materialit. Asnjë pjesë nuk mund të vendoset në zonën e dëmtuar.");
	strcpy(sDelete, "fshini");
	strcpy(sDeletePiece, "Fshij copën");
	strcpy(sDeleteRow, "Fshi rreshtin");
	strcpy(sDemandutilization, "Shfrytëzimi i pjesëve");
	strcpy(sDepozitulmodificat, "Pjesët e përdorura janë hequr. Skrapi është shtuar në stok.");
	strcpy(sDepozitvid, "Stoku është bosh");
	strcpy(sDesk, "tavolinë");
	strcpy(sDiagram, "Diagramë");
	strcpy(sDiagrams, "Diagramet");
	strcpy(sDiagramasatable, "Diagrami si tabelë");
	strcpy(sDigits, "shifra");
	strcpy(sDimensiuniplaca, "Madhësia e fletës");
	strcpy(sDirection, "Drejtim");
	strcpy(sDistanceBetweenRows, "Distanca midis rreshtave");
	strcpy(sDonotuseit, "Mos e përdorni");
	strcpy(sDownload, "Shkarko");
	strcpy(sDoYouWantToClearTheData, "A doni të fshini të dhënat?");
	strcpy(sDoYouWantToSaveDemand, "Pjesët janë ndryshuar! A doni të ruani ndryshimet?");
	strcpy(sDoYouWantToSaveParts, "A doni të ruani pjesët?");
	strcpy(sDoYouWantToSaveRepository, "Stoku është ndryshuar! A doni të ruani ndryshimet?");
	strcpy(sDrawing, "vizatim");
	strcpy(sDrawthesolutioncolorful, "Vizatoni zgjidhjen me ngjyra");
	strcpy(sDuplicateTypes, "Disa lloje janë dublikuar! Ju lutemi hiqni kopjimet");
	strcpy(sDuplicateTypesWithComplex, "Disa emra të materialeve tashmë ekzistojnë në listën e llojeve komplekse! Ju lutemi hiqni kopjimet");
	strcpy(sDuplicateValues, "Vlerat e kopjuara");
	strcpy(sEdgeband, "Rripa buzë");
	strcpy(sEdgebandingwhichisplacedontheedgesofyourpiecePleasedefineedgebandingtypesfromMaterialsEdgeBandingmenu, "Shiritat e skajeve vendosen në kufijtë e pjesës suaj. Ju lutemi përcaktoni fashat në menunë Materialet.");
	strcpy(sEdgebandsthatwillbeappliedtoeachpart, "Shiritat e skajit që aplikohen në secilën pjesë.");
	strcpy(sEdgeBandTolerance, "Toleranca për brezin e skajit");
	strcpy(sEdgesthatmustbecutduefaults, "Edges që duhet të priten për shkak të defekteve.");
	strcpy(sEdgetoedge, "Nga skaji në skaj");
	strcpy(sEdit, "redaktoj");
	strcpy(sEmail, "Email");
	strcpy(sEmptyData, "Të dhënat janë bosh!");
	strcpy(sEnabled, "enabled");
	strcpy(sEnabledisabledefectsoftheinventorysheets, "Aktivizoni / çaktivizoni defektet e aksioneve");
	strcpy(sEnterLabel, "Futni etiketën");
	strcpy(sEnterTheMaterialName, "Vendosni emrin e materialit");
	strcpy(sEnterTheProductName, "Vendosni emrin e produktit");
	strcpy(sEvaluationError, "Gabim në vlerësimin e shprehjes!");
	strcpy(sExit, "dalje");
	strcpy(sExpired, "Softueri ka skaduar! Ju lutemi regjistroni programin!");
	strcpy(sExport, "eksport");
	strcpy(sExportAllDiagrams, "Eksportoni të gjitha diagramet");
	strcpy(sExportAllToASingleFile, "Eksportoni të gjithë në një skedar të vetëm");
	strcpy(sExportOptions, "Opsionet e eksportit");
	strcpy(sExporttoDXFformat, "Eksportoni në formatin DXF");
	strcpy(sExporttoExcel, "Eksportoni në Excel");
	strcpy(sExpresieIncorecta, "Shprehje e pasaktë matematikore!");
	strcpy(sExtensions, "Zgjerime");
	strcpy(sExtra, "shtesë");
	strcpy(sExtraComponents, "Përbërësit shtesë");
	strcpy(sExtracomponentsattachedtoDemand, "Komponentë shtesë bashkangjitur pjesëve");
	strcpy(sFile, "skedar");
	strcpy(sFileName, "Emri i skedarit");
	strcpy(sFillWastes, "Vizatoni mbeturina me linja të zhdrejtë");
	strcpy(sFindoptimalbarsheetsize, "Gjeni madhësinë optimale për shufra dhe çarçafë.");
	strcpy(sFindoptimalsizeofInventorypieces, "Gjeni madhësinë optimale të pjesëve të aksioneve");
	strcpy(sFirstcutMultiplestages, "Drejtimi i parë i prerë për optimizimin e fazës së shumëfishtë.");
	strcpy(sFirstdirectionforcutishorizontal, "Drejtimi i parë për prerje është horizontale.");
	strcpy(sFirstdirectionforcutisvertical, "Drejtimi i parë për prerje është vertikal.");
	strcpy(sFollowthecontourofpieces, "Ndiqni konturin e copave");
	strcpy(sFont, "burim");
	strcpy(sFontsize, "Përmasa e germave");
	strcpy(sFullInfo, "Informacion i plotë");
	strcpy(sDisposedWaste, "Mbetjet e deponuara");
	strcpy(sGeneral, "i përgjithshëm");
	strcpy(sGenerateCNC, "Gjeneroni CNC");
	strcpy(sGrain, "Cilësi");
	strcpy(sGraindirection, "Drejtimi i fibrave");
	strcpy(sGraphic, "grafik");
	strcpy(sGreaterorequalto, "Më e madhe ose e barabartë me");
	strcpy(sGrid, "tabelat");
	strcpy(sGrinding, "bluarje");
	strcpy(sGrosimeTaieturaScalata, "Trashësia e prerë nga kjo foto mund të jetë e ndryshme nga ajo reale sepse pjesët nuk përfaqësohen në shkallën e tyre të vërtetë. Ky fakt nuk ndikon në rezultatet.");
	strcpy(sGroupidenticallayouts, "Fletët identike të grupit");
	strcpy(sGroupIdenticalParts, "Gruponi pjesë identike");
	strcpy(sGroupingOfIdenticalPiecesIntoOneRow, "Gruponi pjesët identike në një rresht.");
	strcpy(sGroupPartsAfterLoadingFromFile, "Pjesët e grupit kur ngarkoni nga skedari");
	strcpy(sHeight, "lartësi");
	strcpy(sHeighttolerance, "Toleranca për lartësinë");
	strcpy(sHelp, "Ndihmë");
	strcpy(sHistory, "histori");
	strcpy(sHorizontal, "horizontal");
	strcpy(sHowtodisplayprintedgebands, "Si shfaqen brezat e skajit?");
	strcpy(sIfyousetthebandforoneedgeallwillreceivethesamevalue, "Nëse vendosni brezin për një skaj, të gjitha skajet do të marrin të njëjtën vlerë.");
	strcpy(sIfyousetthegrindingforoneedgeallwillreceivethesamevalue, "Nëse vendosni vlerën e bluarjes për një skaj, të gjitha skajet do të marrin të njëjtën vlerë.");
	strcpy(sIfyousetthetrimforoneedgeallwillreceivethesamevalue, "Nëse vendosni zvogëlimin për një skaj, të gjitha skajet do të marrin të njëjtën vlerë.");
	strcpy(sImageBounds, "Kufijtë për imazhin");
	strcpy(sImageSize, "Madhësia e figurës");
	strcpy(sImportData, "Importoni të dhënat");
	strcpy(sIncorrectPassword, "Fjalëkalim i pasaktë");
	strcpy(sIndex, "indeks");
	strcpy(sInformationaboutcustomer, "Informacione rreth klientit");
	strcpy(sInputALanguageName, "Vendosni emrin e gjuhës");
	strcpy(sInsert, "Fut");
	strcpy(sInsertPiece, "Vendosni copë");
	strcpy(sInterface, "Interface");
	strcpy(sInterfaceSettings, "Cilësimet e ndërfaqes");
	strcpy(sInvalidHardware, "Unë nuk mund ta zbuloja pajisjen. Ju lutemi na kontaktoni në contact@optimalprograms.com");
	strcpy(sInvalidNumber, "Numër i pavlefshëm");
	strcpy(sInvalidOrderOfComputation, "Nuk mund të vendoset një urdhër për llogaritjen e gjatësive. Ekzistojnë marrëdhënie rrethore në përcaktimin e produktit!");
	strcpy(sInvalidRegistration, "Regjistrimi është i pavlefshëm!");
	strcpy(sInvalidTime, "Koha e sistemit tuaj është e pavlefshme.");
	strcpy(sInventory, "Aksionare");
	strcpy(sisafractionalvalue, "është një vlerë e pjesshme.");
	strcpy(sIsArc, "Cshtë hark");
	strcpy(sisarealvalue, "është një vlerë e vërtetë.");
	strcpy(sLabel, "etiketë");
	strcpy(sLabels, "Etiketa");
	strcpy(sLanguage, "Gjuhe");
	strcpy(sLatimeanumar0, "Gjerësia duhet të jetë më e madhe se 0!");
	strcpy(sLatimeanumarreal, "Gjerësia duhet të jetë një numër i vërtetë!");
	strcpy(sLayerName, "Emri i shtresës");
	strcpy(sLeft, "majtas");
	strcpy(sLeftcoordinateofthedefect, "Koordinata e majtë e defektit");
	strcpy(sLength, "gjatësi");
	strcpy(sLengthofthepiecestocut, "Madhësia e copës për prerje");
	strcpy(sLengthofthepiecestocutfrom, "Madhësia e fletës për prerje");
	strcpy(sLengthofusedbars, "Madhësia e shufrave të përdorura");
	strcpy(sLicenseAgreement, "Marrëveshja e licencës");
	strcpy(sLinear, "linear");
	strcpy(sLinethickness, "Trashësia e lapsit");
	strcpy(sLoadafileandappenddatatothecurrentDemand, "Ngarkoni një skedar dhe bashkojini të dhënat në pjesët aktuale.");
	strcpy(sLoadanexistingDemandfromafile, "Ngarkoni pjesët ekzistuese nga një skedar.");
	strcpy(sLoadAppend, "Ngarkesa dhe shtojca");
	strcpy(sLoadEverything, "Ngarko gjithçka");
	strcpy(sLoadInventory, "Ngarkoni aksionet");
	strcpy(sLoadInventoryandDemand, "Ngarkoni stokun dhe pjesët");
	strcpy(sLoadResults, "Ngarkoni rezultatet");
	strcpy(sLocked, "I mbyllur");
	strcpy(sLogo, "Logo");
	strcpy(sLong, "gjatë");
	strcpy(sLongerexecutiontime, "Koha më e gjatë e vrapimit");
	strcpy(sLungime, "gjatësi");
	strcpy(sLungimeanumar0, "Gjatësia duhet të jetë më e madhe se 0!");
	strcpy(sLungimeanumarreal, "Gjatësia duhet të jetë një numër i vërtetë!");
	strcpy(sLungimeaTotalaFolosita, "Gjatësia totale e përdorur");
	strcpy(sMagnification, "zmadhim");
	strcpy(sMagnify, "Magnify");
	strcpy(sMargins, "Mbulesat");
	strcpy(sMarginsForPaper, "Marzhet për letër");
	strcpy(sMarginsOfTheLabel, "Kufijtë e etiketës");
	strcpy(sMaterial, "material");
	strcpy(sMaterialName, "Emri i materialit");
	strcpy(sMaterials, "Materiale");
	strcpy(sMaterialstypes, "Llojet e materialeve");
	strcpy(sMax, "Max");
	strcpy(sMaximalArea, "Zona maksimale");
	strcpy(sMaximalCutLength, "Gjatësia maksimale e prerjes");
	strcpy(sMaxlength, "Gjatësia maksimale");
	strcpy(sMaxPiecesperBar, "Numri maksimal i copave për bar");
	strcpy(sMaxwidth, "Gjerësia maksimale");
	strcpy(sMeasurementUnit, "Njësia e matjes");
	strcpy(sMin, "Min");
	strcpy(sMinimalBreakSize, "Madhësia minimale e pushimit");
	strcpy(sMinimalUsefulSize, "Madhësia minimale e dobishme");
	strcpy(sMinimalwastesizetoInventory, "Madhësia minimale e skrapit të shtuar në stok.");
	strcpy(s_What_to_minimize, "Çfarë duhet minimizuar?");
	strcpy(sMinlength, "Gjatësia minimale");
	strcpy(sMinwidth, "Gjerësia minimale");
	strcpy(sMirror, "pasqyrë");
	strcpy(sMirroring, "pasqyroj");
	strcpy(sMiscellaneous, "Statistika të tjera");
	strcpy(sModify, "Modifiko");
	strcpy(sModifytheselectedpiece, "Modifikoni pjesën e zgjedhur");
	strcpy(sMovePiece, "Lëvizni copën");
	strcpy(sMultiplestages, "Faza të shumëfishta");
	strcpy(sName, "emër");
	strcpy(sNameofedgeband, "Emri i brezit të skajit");
	strcpy(sNewDEMANDUnsaveddatawillbelost, "Pjese te reja? Të dhënat e pa kursyera do të humbasin!");
	strcpy(sNewLanguage, "Gjuhë e re");
	strcpy(sNewMaterial, "Material i ri");
	strcpy(sNewPasswordincorectlyintroduced, "Fjalëkalimi i ri futur gabimisht!");
	strcpy(sNewProduct, "Produkt i ri");
	strcpy(sNewversion, "Versioni i ri");
	strcpy(sNo, "jo");
	strcpy(sNumarBucati, "Numri i pjesëve");
	strcpy(sNumberOfCopies, "Numri i kopjeve");
	strcpy(sNumberofstages, "Numri i fazave");
	strcpy(sNusuficienteplacidepozit, "Jo të gjitha pjesët janë optimizuar. Shkaqet e mundshme: Nuk ka pjesë të mjaftueshme në Stok; Pjesët nuk janë të aktivizuara; Materiali i pjesëve dhe Stoku është i ndryshëm; Parametrat e tjerë janë vendosur gabimisht.");
	strcpy(sOfficeNotInstaled, "Microsoft Office nuk është i instaluar në kompjuterin tuaj ose është instaluar një version i pasaktë!");
	strcpy(sOldpassworddoesnotmatch, "Fjalëkalimi i vjetër nuk përputhet!");
	strcpy(sOnlinehelp, "Ndihmë në internet");
	strcpy(sOnlypiecesofthesameheightinthelaststage, "Pjesë me të njëjtën lartësi në fazën e fundit");
	strcpy(sOpen, "hapur");
	strcpy(sOptimization, "optimization");
	strcpy(sOptimizationDone, "Optimizimi i kryer! Ju mund të shtypni ose ruani diagramet e marra. Shtypni butonin Prano nëse jeni të kënaqur me zgjidhjen aktuale. Përndryshe shtypni Filloni përsëri.");
	strcpy(sOptimizationType, "Lloji i optimizmit");
	strcpy(sOptions, "Opsione");
	strcpy(sOptionsrelatedtotheinterface, "Opsionet në lidhje me ndërfaqen");
	strcpy(sor, "ose");
	strcpy(sOthercomponents, "Komponentët e tjerë");
	strcpy(sOthers, "Të tjerët");
	strcpy(sOtherstatistics, "Statistika të tjera");
	strcpy(sOverrideExcelCSVfiles, "Refuzoni skedarët Excel / CSV");
	strcpy(sParameter, "parametër");
	strcpy(sParts, "PJESË");
	strcpy(sPattern, "model");
	strcpy(sPatternforwaste, "Modeli për skrap");
	strcpy(sPerimeter, "Perimetër");
	strcpy(sPermitedRotationAngle, "Këndi i lejuar i rrotullimit");
	strcpy(sPhone, "telefon");
	strcpy(sPicture, "imazh");
	strcpy(sPiece, "copë");
	strcpy(sPieceindex, "Indeksi i pjesës");
	strcpy(sPieces, "Copë");
	strcpy(sPiecesize, "Madhësia e copës");
	strcpy(sPiecesizelabeledgebandwillbeprinted, "Madhësia e pjesës, etiketa, shiritat e skajeve do të shtypen.");
	strcpy(sPierdere, "copëz");
	strcpy(sPixels, "pixels");
	strcpy(sPlacilefolositeDepozit, "Pjesë të përdorura nga Stoku.");
	strcpy(sPlease_contact_us_at_contact_nestingtechnologies_com, "Ju lutemi na kontaktoni në contact@nesting-technologies.com");
	strcpy(sPlease_contact_us_at_contact_optimalprograms_com, "Ju lutemi na kontaktoni në contact@optimalprograms.com");
	strcpy(sPleaseenteralldataeitherasfractionalorrealDonotmixthem, "Ju lutemi shkruani të gjitha të dhënat ose si vlera thyese ose vlera reale! Mos i përzieni!");
	strcpy(sPleaseEnterSomeTypesOfMaterials, "Nuk ka asnjë lloj materiali të përcaktuar. Ju mund t'i përcaktoni ato nga menuja Materiale.");
	strcpy(sPleasesendtheNameandtheCodetotheaddresscontactoptimalprogramscominordertoobtaintheRegistrationKey, "Për të marrë çelësin e regjistrimit, ju lutemi dërgoni emrin dhe kodin në adresën: contact@optimalprograms.com.");
	strcpy(sPolygon, "shumëkëndësh");
	strcpy(sPolygonsCircles, "Poligone, qarqe");
	strcpy(sPrecision, "Saktësi");
	strcpy(sPretulnumar0, "Mimi duhet të jetë më i madh se 0!");
	strcpy(sPretulnumarreal, "Mimi duhet të jetë një numër real!");
	strcpy(sPreview, "inspektim");
	strcpy(sPrice, "çmim");
	strcpy(sPriceMustBeGreaterThanZero, "Mimi duhet të jetë më i madh se zero");
	strcpy(sPriceofbars, "Pricemimi i bareve");
	strcpy(sPriceperbar, "Mimi për bar");
	strcpy(sPricepersheet, "Mimi për fletë");
	strcpy(sPricepersquareunitofmaterial, "Mimi për njësi katrore të materialit");
	strcpy(sPriceperunit, "Pricemimi për njësi");
	strcpy(sPrint, "shtyp");
	strcpy(sPrintdiagramsastables, "Shtypni diagrame si tabela.");
	strcpy(sPrinter, "printer");
	strcpy(sPrinterBounds, "Marzhet për printer");
	strcpy(sPrinting, "shtypje");
	strcpy(sPrintonlyutilizedarea, "Shtypni vetëm zonën e përdorur");
	strcpy(sPrintthecontentsoftheDemand, "Shtypni përmbajtjen e pjesëve.");
	strcpy(sPrintthecontentsoftheInventory, "Printoni përmbajtjen e aksioneve.");
	strcpy(sPrintthecurrentsolution, "Shtypni zgjidhjen aktuale.");
	strcpy(sPriority, "prioritet");
	strcpy(sPrioritytocutapieceZero0isthehighestpriority, "Prioriteti për të prerë një copë. Zero (0) është përparësia më e lartë.");
	strcpy(sProcentul0100, "Përqindjet duhet të jenë më të mëdha se 0 dhe më pak ose të barabarta me 100!");
	strcpy(sProcentulnumarreal, "Përqindjet duhet të jenë një numër real!");
	strcpy(sProductdefinition, "Përkufizimi i produktit");
	strcpy(sProductExists, "Produkti tashmë ekziston. Zgjidhni një emër tjetër.");
	strcpy(sProductName, "Emri i produktit");
	strcpy(sProducts, "Produkt");
	strcpy(sProducts, "Produkte");
	strcpy(sProject, "Projekt");
	strcpy(sProperties, "Vetitë");
	strcpy(sProperty, "pronë");
	strcpy(sQuantity, "sasi");
	strcpy(sQuantitynumberofsheetsofthistype, "Numri i fletëve të këtij lloji");
	strcpy(sRadius, "rreze");
	strcpy(sRectangular, "Drejtkëndor");
	strcpy(sRedefinetypesofedgeband, "Përcaktoni llojet e brezit të skajit");
	strcpy(sRedefinetypesofmaterial, "Përcaktoni llojet e materialeve");
	strcpy(sRegistration, "regjistrim");
	strcpy(sRegistrationKeyfromOptimalPrograms, "Çelësi i regjistrimit");
	strcpy(sRegistrationSuccessful, "Regjistrimi ishte i suksesshëm!");
	strcpy(sRemoveallpiecesinInventory, "Hiq të gjitha pjesët në Inventar.");
	strcpy(sRemoveCut, "Fshij prerë");
	strcpy(sRemovetheselectedpiece, "Fshini copën e zgjedhur");
	strcpy(sReports, "raportet");
	strcpy(sRequestedMaterial, "Materiali i kërkuar");
	strcpy(sRestore, "kthej");
	strcpy(sResults, "rezultatet");
	strcpy(sReusedwaste, "Mbeturinat e ripërdorura");
	strcpy(sRight, "e drejtë");
	strcpy(sRightcoordinateofthedefect, "Koordinatat e defektit nga ana e djathtë");
	strcpy(sRotation, "rrotullim");
	strcpy(sRotationAngle, "Këndi i rrotullimit");
	strcpy(sRotationStep, "Hapi i rrotullimit");
	strcpy(sRoundAllFractionsTo, "Vlerat e pjesëve duhet të rrumbullakohen në");
	strcpy(sRow, "rresht");
	strcpy(sRows, "rreshtat");
	strcpy(sRun, "Zgjidhjet e fundit");
	strcpy(sRunningtime, "Koha per vrap");
	strcpy(sSameforall, "E njëjta gjë për të gjithë");
	strcpy(sSave, "ruaj");
	strcpy(sSaveAllImages, "Ruani të gjitha imazhet");
	strcpy(sSaveAs, "Ruaj si");
	strcpy(sSaveChanges, "Pjesët janë ndryshuar. A doni t'i ruani ato?");
	strcpy(sSaveCurrentImage, "Ruani imazhin aktual");
	strcpy(sSavedataparameters, "Ruani të dhënat dhe parametrat");
	strcpy(sSaveEverything, "Ruani gjithçka");
	strcpy(sSaveInventory, "Ruani inventarin");
	strcpy(sSaveInventoryandDemand, "Ruani aksionet dhe pjesët");
	strcpy(sSaveResults, "Ruani rezultatet");
	strcpy(sSaveStatisticsinafile, "Ruani statistikat në një skedar");
	strcpy(sSavethecurrentimage, "Ruani imazhin aktual");
	strcpy(sSavethecurrentimageorstatistic, "Ruani imazhin aktual ose statistikat");
	strcpy(sSavetheDEMANDinafile, "Ruani në skedar");
	strcpy(sSavetheDemandinafilewithadifferentname, "Ruani Pjesët në një skedar me një emër tjetër.");
	strcpy(sSavetheREPOSITORYinafile, "Ruani Stokun në një skedar");
	strcpy(sSerialNumber, "Çelësi i regjistrimit");
	strcpy(sService, "shërbim");
	strcpy(sSetDefaultValues, "Kjo do të rivendosë të gjithë parametrat në vlerat e tyre të paracaktuar. Të gjitha cilësimet tuaja do të humbasin. A jeni i sigurt që doni ta bëni këtë?");
	strcpy(sSetedgeband, "Vendosni brezin e skajit");
	strcpy(sSetedgetrim, "Vendosni madhësinë e prerë për defektet e margjinave");
	strcpy(sSetthesameedgebandforalledges, "Vendosni të njëjtën brez buzë për të gjitha palët");
	strcpy(sSetthesamegrindingforalledges, "Vendosni të njëjtën bluarje për të gjitha skajet");
	strcpy(sSetthesametrimforalledges, "Vendosni të njëjtën prerje për defektet për të gjitha skajet");
	strcpy(sSettings, "Cilësimet");
	strcpy(sShape, "formë");
	strcpy(sSheet, "fletë");
	strcpy(sSheetsBarstypes, "Llojet e fletëve_shufrave");
	strcpy(sSheetSize, "Madhësia e fletës");
	strcpy(sSheetsperPage, "Fletë për faqe");
	strcpy(sShort, "I shkurtër");
	strcpy(sShorterexecutiontime, "Koha e shkurtër e drejtimit");
	strcpy(sShowallsimpleproducts, "Trego të gjitha produktet e thjeshta");
	strcpy(sShowcustomername, "Trego emrin e klientit");
	strcpy(sShowCustomTextOnEachPiece, "Trego tekst me porosi në secilën pjesë");
	strcpy(sShowdiagramasatable, "Trego diagramin si tabelë.");
	strcpy(sShowedgeband, "Trego bandat e skajit");
	strcpy(sShowedgebandssettinginanewwindow, "Trego parametrat e brezave të skajit në një dritare të re");
	strcpy(sShowgrindingsettingsinanewwindow, "Tregon cilësimet e bluarjes në një dritare të re");
	strcpy(sShowHorizontalLabelsAlways, "Trego etiketat horizontale gjithmonë");
	strcpy(sShowRemovethesizeofthepiecesinthecurrentsolution, "Trego / fshih madhësinë e copave.");
	strcpy(sShowRemovethesizeofthewastesinthecurrentsolution, "Trego / fshih madhësinë e skrapit.");
	strcpy(sShowtotalcutlength, "Trego gjatësinë totale të prerjes");
	strcpy(sShowtrimedgesettingsinanewwindow, "Trego cilësimet e defekteve në një dritare të re");
	strcpy(sSimpleMaterialExists, "Emri i materialit është përcaktuar tashmë në listën e materialeve. Ju lutemi jepni një emër të ri.");
	strcpy(sSinglePieceStrips, "Vija të një pjese");
	strcpy(sSizes, "Sizes");
	strcpy(sSmallerorequalto, "Më e vogël ose e barabartë me");
	strcpy(sSort, "lloj");
	strcpy(sSortAscendingByArea, "Rendit sipas zonës në rend ngjitje");
	strcpy(sSortDescendingByArea, "Rendit sipas zonës në rend zbritës");
	strcpy(sSpecifyhowdifferentthepiecesinthelaststagecanbeValue0meansnodifference, "Specifikoni se sa të ndryshme mund të jenë pjesët në fazën e fundit. Vlera 0 nuk do të thotë asnjë ndryshim.");
	strcpy(sSpecifyifpiecesinthelaststagecanbedifferentornotdepeultimaetapapotfidiferitesaunucadimensiune, "Specifikoni nëse pjesët në fazën e fundit mund të jenë të ndryshme ose jo");
	strcpy(sSpecifyifthepiececanberotatedornotIfnotitwillbecutinthesamewayasitwasintroducedinDemandLengthofthepieceparalleltothelengthofthesheet, "Specifikoni nëse copa mund të rrotullohet apo jo. Nëse jo, vendoset në të njëjtën mënyrë siç është prezantuar (gjatësia e pjesës paralel me gjatësinë e fletës),");
	strcpy(sSpecifyinhowmanystageswemakethecutsDuringastageallcutshavethesamedirection, "Specifikoni në sa faza bëjmë shkurtimet.");
	strcpy(sStartthesearchprocess, "Filloni procesin e kërkimit");
	strcpy(sStatistics, "të dhëna statistikore");
	strcpy(sStatisticsE, "Raporte shtesë");
	strcpy(sStatisticsforeachtypeofmaterial, "Statistikat për secilin lloj materiali");
	strcpy(sStep, "hap");
	strcpy(sStergeDepozit, "Dëshironi të fshini Inventarin?");
	strcpy(sStergeMaterial, "A doni të fshini materialin?");
	strcpy(sStergePiesele, "A doni të fshini copën?");
	strcpy(sStergePiesa, "A doni të fshini copën?");
	strcpy(sStopthesearchprocess, "Ndaloni procesin e kërkimit");
	strcpy(sStrongoptimization, "Optimizim i fortë");
	strcpy(sSubtractthebandthicknessfrompiecesize, "Ulni madhësinë e copave me trashësinë e brezit të skajit");
	strcpy(sSummary, "përmbledhje");
	strcpy(sSuprafataTotalaFolosita, "Sipërfaqja totale e përdorur");
	strcpy(sSuprafatautilizata, "shfrytëzim");
	strcpy(sSwitchbetweenfiberandrotationoption, "Kaloni midis opsionit të fibrës dhe rotacionit.");
	strcpy(sTechnical, "teknik");
	strcpy(sTechnicalsettings, "Cilësimet teknike");
	strcpy(sTemporaryPanelHint, "Paneli i përkohshëm për lëvizjen e pjesëve ndërmjet çarçafëve.");
	strcpy(sText, "tekst");
	strcpy(sThe_application_has_expired, "Kërkesa ka skaduar.");
	strcpy(sThe_application_is_not_registered, "Aplikacioni nuk është i regjistruar.");
	strcpy(sThe_application_was_first_started_on, "Aplikimi filloi së pari");
	strcpy(sThecutsareperformedfromasidetotheothersideofthematerial, "Shkurtimet bëhen nga një anë në anën tjetër të materialit.");
	strcpy(sThecuttingmachinecanfollowtheshapeofthematerial, "Makina e prerjes mund të ndjekë formën e pjesës.");
	strcpy(sTheedgesofsheetsthatmustbetrimedduefaults, "Skajet e çarçafëve që duhet të shkurtohen për shkak të gabimeve");
	strcpy(sTheLargestSize, "Madhësia më e madhe");
	strcpy(sThenameofthecustomerforwhichyoucutthepiece, "Emri i klientit për të cilin keni prerë copën.");
	strcpy(sThenameofyourcustomer, "Emri i klientit tuaj");
	strcpy(sThepiececanberotated, "Pjesa mund të rrotullohet");
	strcpy(sTheprogramtriestoavoidwasteswhichhavebothsizeslessthanthisvalue, "Programi përpiqet të shmangë skrapin që është më i vogël se kjo vlerë");
	strcpy(sThereAreNoProducts, "Ende nuk ka produkte të përcaktuara");
	strcpy(sThestockofmaterialhasbeenpreviouslyloadedfromanExcelorCSVformatPleaseloaditagain, "Stoku i materialit është ngarkuar më parë nga një format Excel ose CSV. Ju lutemi ngarkoni përsëri nëse doni të punoni në të.");
	strcpy(sThetotallengthofcutting, "Gjatësia totale e prerjes");
	strcpy(sThewidthofthecuttingsawForglasscuttingoptimizationitcanbe0Forwooditshouldbegreaterthan0, "Trashësia e sharrës. Për prerjen e qelqit mund të jetë 0. Për drurin duhet të jetë më e madhe se 0.");
	strcpy(sThewidthofthecuttingsawforlinearpieces, "Trashësia e sharrës për copa lineare.");
	strcpy(sThickness, "Trashësia");
	strcpy(sThischaracterisusedforfillingthewasterectanglesIfyoudonotwantfilledwastejustremovethischaracter, "Ky simbol përdoret për mbushjen e drejtkëndëshave të mbeturinave. Nëse nuk doni mbeturina të mbushura thjesht hiqni atë.");
	strcpy(sThisindexhasvaluebetween1andthenumberofpieces, "Ky indeks ka vlerë midis 1 dhe numrit të pjesëve.");
	strcpy(sThisOptionWillOverrideTheInventoryFileIfLoadedFromExcelOrCsvFiles, "Ky opsion do të anashkalojë skedarin e inventarit nëse ngarkohet nga skedarët excel ose CSV.");
	strcpy(sThisProgramisLicensedTo, "Ky program është i licencuar për të");
	strcpy(sThisvaluewillbeaddedtotheedgebandingmaterialoneachside, "Kjo vlerë do të shtohet në brezin e skajit në secilën anë");
	strcpy(sTipNevid, "Lloji i materialit nuk mund të jetë bosh.");
	strcpy(sTitle, "titull");
	strcpy(sTools, "Tools");
	strcpy(sTop, "më i lartë");
	strcpy(sTopcoordinateofthedefect, "Koordinata e lartë e defektit.");
	strcpy(sTotalGarbageWaste, "Të gjitha skrapet e hedhura");
	strcpy(sTotalInventoryWaste, "Skrap total i aksioneve");
	strcpy(sTotalRecycledWaste, "Të gjitha skrapet e ripërdorura");
	strcpy(sTotalusedarea, "Sipërfaqja totale e përdorur");
	strcpy(sTotalusedlength, "Gjatësia totale e përdorur");
	strcpy(sTrigonometric, "trigonometrik");
	strcpy(sTrim, "Trim");
	strcpy(sTrimalledgesatthebeginning, "Pritini të gjitha skajet në fillim");
	strcpy(sTrimEdge, "Trim buzë");
	strcpy(sTwoPanels, "2 panele");
	strcpy(sType, "lloj");
	strcpy(sTypeofmaterialfromwhichtocut, "Lloji i materialit nga i cili duhet prerë");
	strcpy(sTypesAreNotMatched, "Optimizimi nuk u krye! Aktualisht, nuk ka asnjë material të tillë në magazinë! Pjesët mund të priten nga çarçafët e të njëjtit material. Ndryshoni disa materiale nga kolona përkatëse!");
	strcpy(sUndo, "Undo");
	strcpy(sUndoAccept, "Zhbëj Prano");
	strcpy(sUnits, "njësitë");
	strcpy(sUnregisteredVersion, "i paregjistruar");
	strcpy(sUpdates, "Updates");
	strcpy(sUsefulforwoodfurniture, "Dobishme për mobilje prej druri");
	strcpy(sUseit, "Perdore");
	strcpy(sUsePieceinOptimization, "Përdorni copën në optimizim");
	strcpy(sUserName, "Emri i përdoruesit");
	strcpy(sUtilizationandWastes, "Shfrytëzimi dhe skrapi");
	strcpy(sUtilizedArea, "Zona e pjesëve të përdorura");
	strcpy(sUtilizedBars, "Bare të shfrytëzuara");
	strcpy(sUtilizeddemandcount, "Numri i pjesëve të përdorura");
	strcpy(sUtilizedParts, "Pjesë të përdorura");
	strcpy(sUtilizedPieces, "Pjesë të përdorura");
	strcpy(sUtilizedSheets, "Fletë të përdorura");
	strcpy(sValue, "vlerë");
	strcpy(sValueGreaterEqualToZero, "Vlera duhet të jetë më e madhe ose e barabartë me zero");
	strcpy(sValueGreaterThanZero, "Vlera duhet të jetë më e madhe se zero");
	strcpy(sValueIntegerNumber, "Vlera duhet të jetë një numër i plotë!");
	strcpy(sValueRealNumber, "Vlera duhet të jetë një numër real. Ndoshta ju keni përdorur presje në vend të periudhës ose anasjelltas. Ju lutemi rregulloni!");
	strcpy(s_The_number_is_too_big_or_it_has_too_many_digits_after_decimal_separator, "Numri është shumë i madh ose ka shumë shifra pas ndarjes dhjetore!");
	strcpy(s_The_number_is_too_big, "Numri është shumë i madh!");
	strcpy(sVertical, "vertikale");
	strcpy(sWaste, "Humbje");
	strcpy(sWastes, "Humbje");
	strcpy(sWasteAddedToWarehouse, "Skrapi i shtuar në stok");
	strcpy(sWastelimits, "Gama e skrapit");
	strcpy(sWasteType, "Lloji i skrapit");
	strcpy(sWeakoptimization, "Optimizimi më i dobët");
	strcpy(sWhattoprint, "Shouldfarë duhet të printoj");
	strcpy(s_What_to_print_or_save_to_file, "Çfarë të printoni ose ruani në skedar");
	strcpy(sWhattoprintoneachpiece, "Farë duhet të shtypni në secilën pjesë");
	strcpy(sWhattoshowoneachpiece, "Farë duhet të tregoni në secilën pjesë?");
	strcpy(sWidth, "gjerësi");
	strcpy(sWood, "dru");
	strcpy(sWorkingDirectory, "Dosje pune");
	strcpy(sWrongKey, "Keyelësi i gabuar i regjistrimit!");
	strcpy(sYes, "po");
	strcpy(sYoucannotchooseblackblueorredcolors, "Ju nuk mund të zgjidhni ngjyrat e zeza, blu ose të kuqe.");
	strcpy(sYouCannotMixFractionalDataWithDecimalOnes, "Ju nuk mund të përzieni vlerat e thyesave me vlerat reale!");
	strcpy(sYourcompany, "Kompania juaj");
	strcpy(sZip, "Kodi Postar");
	strcpy(s_Set_the_origin_and_the_direction_of_the_axes, "Vendosni origjinën dhe drejtimin e boshteve të koordinatave.");

}
