// Language strings: Czech
// Author: Optimal Programs
// License: MIT License
//---------------------------------------------------------------------------
#include <string.h>
//---------------------------------------------------------------------------
#include "language_string_id.h"
//---------------------------------------------------------------------------
void set_cz(void)
{
	//Czech
	//translated by a customer
	//2025.3.29.0
	strcpy(s_Advanced, "Moderní");
	strcpy(s_Relative_coordinates, "Relativní souřadnice");
	strcpy(s_Absolute_coordinates, "Absolutní souřadnice");
	strcpy(s_Append_more_rows, "Připojte další řádky");

	strcpy(s_Add_to_parts, "Přidat k dílcům.");
	strcpy(s_Additional, "Další");
	strcpy(s_All_results, "Všechny výsledky.");
	strcpy(s_Allow_movement_of_pieces, "Umožněte pohyb kusů");
	strcpy(s_Allow_part_in_part, "Povolit kus v kuse");
	strcpy(s_Invalid_piece_Angles_are_too_small_or_too_big_or_height_is_too_small, "Neplatný kus! Úhly jsou příliš malé nebo příliš velké, nebo je výška příliš malá.");
	strcpy(s_Append, "Připojit");
	strcpy(s_As_it_is, "Tak, jak je");
	strcpy(s_As_text, "Jako text");
	strcpy(s_Ascending, "Vzestupně");
	strcpy(s_Automatic, "Automaticky");
	strcpy(s_Cannot_connect_to_the_Internet_Please_visit_our_website_from_a_browser, "Nelze se připojit k internetu! Navštivte prosím náš web z prohlížeče.");
	strcpy(s_Cannot_copy_or_move_the_files, "Nelze kopírovat nebo přesouvat soubory!");
	strcpy(s_Cannot_delete_the_file, "Soubor nelze smazat!");
	strcpy(s_Cannot_modify_old_results, "Staré výsledky nelze upravit!");
	strcpy(s_To_change_click_inside_a_cell_or_press_0_1_or_2, "Chcete-li změnit, klikněte do buňky nebo stiskněte 0, 1 nebo 2.");
	strcpy(s_Cell, "Buňka");
	strcpy(s_Click_on_the_table_header_to_change_the_columns, "Kliknutím na záhlaví tabulky změníte sloupce.");
	strcpy(s_Close, "Zavřít");
	strcpy(s_Contact_us, "Kontaktujte nás");
	strcpy(s_Column, "Sloupec");
	strcpy(s_Comma, "Čárka");

	strcpy(s_Copy, "kopírovat");
	strcpy(s_Copy_for_move, "Kopírovat pro přesun");
	strcpy(s_Cut_higher_level_strips_first, "Nejprve odřízněte pásy vyšší úrovně");
	strcpy(s_Cut_index, "Zobrazit index řezání");

	strcpy(s_The_data_have_been_changed_Do_you_want_to_save_them_to_a_file, "Data byla změněna. Chcete je uložit do souboru?");
	strcpy(s_Decimal_separator, "Desetinný oddělovač");
	strcpy(s_Restore_default_settings, "Obnovit výchozí nastavení");
	strcpy(s_Delete_fiber, "Odstranit vlákno");
	strcpy(s_Descending, "Sestupně");
	strcpy(s_Discard_changes, "Zahodit změny");

	strcpy(s_Delete_all_data, "Smazat všechna data?");
	strcpy(s_Dot, "Tečka");
	strcpy(s_Do_you_want_to_delete_the_picture, "Chcete smazat obrázek?");
	strcpy(s_Do_you_want_to_delete_the_product, "Chcete produkt smazat?");
	strcpy(s_Duplicate_and_append, "Duplikovat a připojit.");
	strcpy(s_Duplicate_values_are_ignored, "Duplicitní hodnoty byly ignorovány!");
	strcpy(s_Error, "Chyba");
	strcpy(s_Error_loading_file, "Chyba při načítání souboru.");
	strcpy(s_export_everything, "Exportovat vše");
	strcpy(s_Fit_to_screen, "Přizpůsobit obrazovce.");
	strcpy(s_Force_fixed_height, "Nakreslete dílky s pevnou výškou.");
	strcpy(s_Flipped, "Převráceno");
	strcpy(s_Import, "Importovat");
	strcpy(s_If_angles_are_different_from_90_degrees_height_must_be_greater_than_0, "Pokud se úhly liší od 90 stupňů, výška musí být větší než 0.");
	strcpy(s_Ignore, "Ignorovat");
	strcpy(s_Incorrect_value, "Nesprávná hodnota");
	strcpy(s_Info, "Info");
	strcpy(s_Interior, "vnitřní");
	strcpy(s_Give_a_name, "Uveďte jméno.");
	strcpy(s_Group, "Seskupte to");
	strcpy(s_Header, "Záhlaví");
	strcpy(s_Keep_it_as_it_is, "Zachovejte to tak, jak je");
	strcpy(s_Level, "Level");
	strcpy(s_Licensee, "Držitel licence");
	strcpy(s_List_separator, "Oddělovač seznamu");
	strcpy(s_Made_with_love_in_Cugir_Romania, "Vyrobeno s láskou v Cugir, Rumunsko");
	strcpy(s_Made_in, "Vyrobeno v");
	strcpy(s_Manufacturer, "Výrobce");

	strcpy(s_Manual_arrange, "Ruční uspořádání");

	strcpy(s_Mixed, "Smíšený");
	strcpy(s_Multiple_shapes_detected_Next_rows_will_be_overwritten_Continue, "Bylo zjištěno více než jeden tvar. Proto budou následující řádky přepsány. Pokračovat?");
	strcpy(s_More, "Více");
	strcpy(s_Multiple_values, "Více hodnot");
	strcpy(s_No_texture, "Žádná textura");
	strcpy(s_Number, "Číslo");
	strcpy(s_Number_of_images, "Počet obrázků");
	strcpy(s_Number_of_vertices, "Počet vrcholů");
	strcpy(s_Offset, "Offset");
	strcpy(s_Only_the_currently_selected_items, "Pouze aktuálně vybrané položky.");
	strcpy(s_Optimizing_please_wait, "Probíhá optimalizace... čekejte prosím.");

	strcpy(s_Paste, "Vložit");

	strcpy(s_Piece_label, "Zobrazit štítek kusu");
	strcpy(s_Piece_size, "Zobrazit velikosti kusu");
	strcpy(s_Please_contact_us_by_email_if_you_receive_this_error, "Pokud se zobrazí tato chyba, kontaktujte nás e-mailem.");
	strcpy(s_Please_save_it_first, "Nejprve si to prosím uložte.");
	strcpy(s_Position, "Pozice");
	strcpy(s_Preview, "Náhled");
	strcpy(s_Rectangle, "Obdélník");

	strcpy(s_Redo_the_last_operation, "Obnovte poslední operaci");
	strcpy(s_Regular_polygon, "Pravidelný mnohoúhelník");

	strcpy(s_Reused, "Opětovně použito");
	strcpy(s_Rotated, "Otočeno");
	strcpy(s_Save_all, "Uložit vše");
	strcpy(s_Scrap_label, "Zobrazit štítek odpadu");
	strcpy(s_Scrap_size, "Zobrazit velikosti odpadu");
	strcpy(s_Semicolon, "Středník");
	strcpy(s_Show_cut_index, "Zobrazit index řezání");
	strcpy(s_Show_information, "Zobrazit informace");
	strcpy(s_Show_piece_label, "Zobrazit štítek kusu");
	strcpy(s_Show_scrap_label, "Zobrazit štítek odpadu");
	strcpy(s_Show_scrap_s_size_on_the_small_pieces, "Zobrazit velikost odpadu malých kusů");
	strcpy(s_Show_size_of_pieces, "Zobrazit velikosti kusů");
	strcpy(s_Show_size_of_scrap, "Zobrazit velikost odpadů");
	strcpy(s_Show_sizes, "Zobrazit velikosti");
	strcpy(s_Show_label, "Zobrazit štítek");
	strcpy(s_Show_length, "Zobrazit délku");

	strcpy(s_Some_numerical_values_are_incorrect_Should_I_fix_all_the_incorrect_values, "Některé číselné hodnoty jsou nesprávné! Mám opravit všechny nesprávné hodnoty?");
	strcpy(s_Some_invalid_values_have_been_removed, "Některé neplatné hodnoty byly odstraněny.");
	strcpy(s_Sort_by, "Seřadit podle");
	strcpy(s_Sort_ascending_by, "Seřadit vzestupně podle");
	strcpy(s_Sort_descending_by, "Seřadit sestupně podle");
	strcpy(s_Start, "Start");
	strcpy(s_Starting_angle, "Počáteční úhel");


	strcpy(s_Stock, "Inventář");
	strcpy(s_Stop, "Stop");

	strcpy(s_Tabular, "Tabelární");
	strcpy(s_Total, "Celkový");
	strcpy(s_Total_size, "Celková velikost");
	strcpy(s_Terms_of_the_license, "Podmínky licence");
	strcpy(s_The_current_product_has_been_changed_Do_you_want_to_save_it_to_file, "Aktuální produkt byl změněn. Chcete ji uložit do souboru?");
	strcpy(s_The_value_is_out_of_the_allowed_range, "Hodnota je mimo povolený rozsah.");
	strcpy(s_The_value_must_be_a_real_or_fractional_number_Try_to_replace_the_comma_with_the_dot_if_you_want_to_enter_a_real_number, "Hodnota musí být skutečné nebo zlomkové číslo. Zkuste zadat čárku tečkou, pokud chcete zadat skutečné číslo.");
	strcpy(s_This_feature_is_not_implemented_yet, "Tato funkce zatím není implementována.");
	strcpy(s_This_operation_cannot_be_reversed, "Tuto operaci nelze vrátit zpět.");
	strcpy(s_Undo_the_last_operation, "Zrušit poslední operaci.");
	strcpy(s_Utilization, "Využití");
	strcpy(s_Utilized_Stock, "Využité zásoby");
	strcpy(s_Version, "Verze");
	strcpy(s_Visible_columns, "Viditelné sloupce");
	strcpy(s_You_already_have_the_latest_version_installed, "Již máte nainstalovanou nejnovější verzi!");
	strcpy(s_What_is_exported, "Co se exportuje?");
	strcpy(s0meansanynumberofpieces, "Nula znamená libovolný počet kusů");
	strcpy(sAbout, "O nás");
	strcpy(sAccept, "Přijmout");
	strcpy(sAcceptall, "Přijmout všechny");
	strcpy(sAcceptthecurrentsolution, "Přijmout aktuální řešení");
	strcpy(sAdd, "Připojit");
	strcpy(sAddapiece, "Přidat kus");
	strcpy(sAddasimpleproducttoDemand, "Přidání produktu na stávající poptávku.");
	strcpy(sAddgrindingthicknesstopartsize, "Přidat tloušťku broušení na velikost kusu");
	strcpy(sAddproductnametolabel, "Připojit k názvu výrobku se značku");
	strcpy(sAddress, "Adresa");
	strcpy(sAddselectedsizetoInventory, "Přidat vybranou velikost do seznamu");
	strcpy(sAdhesivelabels, "Samolepící štítky");
	strcpy(sAdhesivelabelwithinformationaboutpiecesinDemandCustomernameLabelSizeCurrentData, "Etiketa s informacemi o kusech zakázky: jméno zákazníka, etiketa, velikost, aktuální údaje.");
	strcpy(sAdhesivelabelwithinformationaboutsheetsinInventory, "Etiketa s informacemi o listech v inventáři.");
	strcpy(sAll, "Vše");
	strcpy(sAlloffcutswhichhavethesizegreaterthanthisvaluewillbeaddedtoInventory, "Všechny odřezky, které mají velikost větší než tato hodnota, budou přidány do skladu");
	strcpy(sAllowMirroring, "Povolit překlopení");
	strcpy(sAllowRotation, "Povolit otáčení");
	strcpy(sAllPieces, "Všechny kusy");
	strcpy(sAllpredefinedproducts, "Všechny předdefinované produkty");
	strcpy(sAnewwindowwillbedisplayedwheretheusercansettheedgebandsforeachedge, "Nové okno se zobrazí, pokud uživatel může nastavit okrajové pásy pro každou hranu");
	strcpy(sAnewwindowwillbedisplayedwheretheusercansetthegrindingvalueforeachedgeofthsheet, "nové okno se okno, ve kterém může uživatel nastavit brusný hodnotu pro každý okraj kusu.");
	strcpy(sAnewwindowwillbedisplayedwheretheusercansetthetrimvalueforeachedgeofthsheet, "Nové okno se zobrazí, kde uživatel může nastavit vady na každé hrany kusu.");
	strcpy(sAngle, "Úhel");
	strcpy(sAngles, "úhly");
	strcpy(sAnoptimizationparameterisarealnumber, "Optimalizační parametr je reálné číslo.");
	strcpy(sAnoptimizationparameterisfractionalnumber, "Optimalizační parametr je frakční číslo.");
	strcpy(sAnyShape, "Skutečná geometrie");
	strcpy(sApolygonmusthaveatleast2vertices, "Mnohoúhelník musí mít alespoň 2 vrcholy!");
	strcpy(sApolygonmusthaveatleast3vertices, "Mnohoúhelník musí mít alespoň 3 vrcholy!");
	strcpy(sApplication_fails_to_initialize, "Softwaru se nezdařila inicializace.");
	strcpy(sArc, "Oblouk");
	strcpy(sArcLength, "Délka oblouku");
	strcpy(sAreaofusedsheets, "Oblast použitých listů");
	strcpy(sAshortdescriptionofthesheet, "Stručný popis listu");
	strcpy(sAtleastonepart, "Alespoň jeden kus, musí být zaveden.");
	strcpy(sAtTheMarginOfTheSheet, "Na okraji listu");
	strcpy(sBandtypes, "Typy olepených hran.");
	strcpy(sBar, "Tyče / trubky");
	strcpy(sBars, "Tyče / trubky");
	strcpy(sBothsizesoftheoffcutsmustbegreaterthanthisvalue, "Obě velikosti odřezků musí být větší než tato hodnota.");
	strcpy(sBottom, "Spodní");
	strcpy(sBottomcoordinateofthedefect, "Spodní Souřadnice vady");
	strcpy(sBreakCut, "Přerušit řez");
	strcpy(sBrowse, "prohlížet");
	strcpy(sBuy, "Koupit");
	strcpy(sBuynow, "Kup teď ...");
	strcpy(sCancel, "Zrušit");
	strcpy(sCannotBeEmpty, "nemůže být prázdný!");
	strcpy(sCannotmovepartsbetweensheetswhenidenticalsheetsaregroupedPleaseungroupthesheetsfrommenu, "Nelze přesunout díly z jednoho listu do druhého, pokud jsou totožné listy jsou seskupeny prosím zrušit seskupení listů z nabídky..");
	strcpy(sCannotSaveFile, "Nelze uložit soubor");
	strcpy(sCenter, "Střed");

	strcpy(sChangeDirection, "Změnit směr");
	strcpy(sChoose, "Vybrat");
	strcpy(sChooseProduct, "Vyberte produkt");
	strcpy(sCircle, "Kruh");
	strcpy(sCity, "Město");
	strcpy(sClear, "Vymazat");
	strcpy(sClockWise, "Ve směru hodinových ručiček");
	strcpy(sClosewindow, "Zavřít okno");
	strcpy(sColor, "Barva");
	strcpy(sColorofedgeband, "Barva okraje hrany");
	strcpy(sColorPattern, "Barva / vzor");
	strcpy(sColorpiecesandwastes, "Kusy a odpady barevně.");
	strcpy(sColumns, "Sloupce");
	strcpy(sComment, "Komentář");
	strcpy(sCompanyname, "Název společnosti");
	strcpy(sComplexMaterialExists, "Název materiálu je již definován v seznamu komplexních materiálů. Prosím, zadejte mu nové jméno.");
	strcpy(sComputerCode, "Počítačový kód");
	strcpy(sComputerCodefromyourcomputer, "Počítačový kód (z počítače)");
	strcpy(sComputethetotalpriceofDemand, "Spočítat celkovou cenu zakázky");
	strcpy(sContents, "Obsahuje");
	strcpy(sContinutComanda, "Obsahuje dílce zakázky ke dni");
	strcpy(sContinutDepozit, "Obsahuje sklad ke dni");
	strcpy(sConversionIsDoneOnlyWhenSomePiecesHaveFractionalValues, "Konverze se provádí pouze tehdy, když některé kousky mají nepatrné hodnoty.");
	strcpy(sConvertsTheSizeOfWasteToAFractionalUnit, "Zobrazuje velikost odpadu jako frakční hodnotu.");
	strcpy(sCouldNotSaveFile1, "Nelze zapsat soubor v adresáři");
	strcpy(sCouldNotSaveFile2, "Nesmíte mít dostatečná práva. Zkontrolujte nebo změňte pracovní adresář z menu Nastavení | Pracovní adresář do složky, kde máte práva pro zápis (např. c:\\temp).");
	strcpy(sCreationdateYMDHMS, "Datum vytvoření (Y / M / D, H: M: S)");
	strcpy(sCurrentDate, "Aktuální datum");
	strcpy(sCurrentDiagram, "Aktuální diagram");
	strcpy(sCurrentMaterial, "Aktuální Materiál");
	strcpy(sCurrentversion, "Současná verze");
	strcpy(sCurve_not_closed_Try_increasing_DXF_linking_distance_parameter, "Mnohoúhelník není uzavřen! Zkuste zvýšit parametr DXF linking distance.");
	strcpy(sCustomer, "Zákazník");
	strcpy(sCustomerName, "Jméno zákazníka");
	strcpy(sCustomMessage, "Vlastní zpráva");
	strcpy(sCutlength, "Délka řezu");
	strcpy(sCut, "Řez");
	strcpy(sCuts, "Řezy");
	strcpy(sCutterThickness, "Tloušťka řezu");
	strcpy(sData, "Údaje");
	strcpy(sDataCannotBeEmpty, "Data nemohou být prázdná!");
	strcpy(sDateymdhms, "Datum (y / m / d / h / m / s)");
	strcpy(sDays_left_for_trial, "K dispozici dnů pro testování");
	strcpy(sDaysLeft, "Zbývající dny");
	strcpy(sStandard, "Standardní");
	strcpy(sDefaultInterface, "Výchozí rozhraní");
	strcpy(sDefects, "Vady");
	strcpy(sDefectsManager, "Správa vady");
	strcpy(sDefectsofthematerialNopiecescanbeplacedinthefaultyzone, "Vady materiálu. Žádné kusy mohou být umístěny v vadného zóně.");
	strcpy(sDelete, "Vymazat");
	strcpy(sDeletePiece, "Odstranit kus");
	strcpy(sDeleteRow, "Smazat řádek");
	strcpy(sDemandutilization, "Využití poptávky");
	strcpy(sDepozitulmodificat, "Používané kusy byly odstraněny. Ostatky byly přidány do zásoby.");
	strcpy(sDepozitvid, "Populace je prázdný");
	strcpy(sDesk, "psací stůl");
	strcpy(sDiagram, "Diagram");
	strcpy(sDiagrams, "Diagramy");
	strcpy(sDiagramasatable, "Diagram jako stůl");
	strcpy(sDigits, "číslice");
	strcpy(sDimensiuniplaca, "Velikost listu");
	strcpy(sDirection, "Směr");
	strcpy(sDistanceBetweenRows, "Vzdálenost mezi řádky");
	strcpy(sDonotuseit, "Nepoužívejte");
	strcpy(sDownload, "Stažení");
	strcpy(sDoYouWantToClearTheData, "Chcete-li odstranit data?");
	strcpy(sDoYouWantToSaveDemand, "Díly byly změněny! Chcete-li uložit změny?");
	strcpy(sDoYouWantToSaveParts, "Chcete ušetřit části?");
	strcpy(sDoYouWantToSaveRepository, "Fotografie byla změněna! Chcete-li uložit změny?");
	strcpy(sDrawing, "kresby");
	strcpy(sDrawthesolutioncolorful, "Vykreslit řešení barevně");
	strcpy(sDuplicateTypes, "Některé typy jsou duplikovány! Prosím odstranění duplicit");
	strcpy(sDuplicateTypesWithComplex, "Některé názvy materiálů již existují v seznamu komplexních typů! Prosím, odstraňte duplicity");
	strcpy(sDuplicateValues, "Duplicitní hodnoty");
	strcpy(sEdgeband, "Hrany");
	strcpy(sEdgebandingwhichisplacedontheedgesofyourpiecePleasedefineedgebandingtypesfromMaterialsEdgeBandingmenu, "Olepování hran, které jsou umístěné na okrajích kusu. Prosím definujte olepováné typy materiálů z menu.");
	strcpy(sEdgebandsthatwillbeappliedtoeachpart, "Hrany, které budou použity pro každou část.");
	strcpy(sEdgeBandTolerance, "Tolerance pro olepování hran");
	strcpy(sEdgesthatmustbecutduefaults, "Hrany, které musí být řezané v důsledku chyby.");
	strcpy(sEdgetoedge, "Od okraje k okraji");
	strcpy(sEdit, "Upravit");
	strcpy(sEmail, "E-mail");
	strcpy(sEmptyData, "Údaje jsou prázdné!");
	strcpy(sEnabled, "Povoleno");
	strcpy(sEnabledisabledefectsoftheinventorysheets, "Zapnout / vypnout vady na skladě");
	strcpy(sEnterLabel, "Vložte štítek");
	strcpy(sEnterTheMaterialName, "Vložte jméno materiálu");
	strcpy(sEnterTheProductName, "Zadejte název produktu");
	strcpy(sEvaluationError, "Chyba na vyhodnocení výrazu!");
	strcpy(sExit, "Odejít");
	strcpy(sExpired, "Licence softwaru vypršela! Prosím zaregistrujte software!");
	strcpy(sExport, "Export");
	strcpy(sExportAllDiagrams, "Exportujte všechny diagramy");
	strcpy(sExportAllToASingleFile, "Exportovat vše do jednoho souboru");
	strcpy(sExportOptions, "Možnosti exportu.");
	strcpy(sExporttoDXFformat, "Export do formátu DXF");
	strcpy(sExporttoExcel, "Export do Excelu");
	strcpy(sExpresieIncorecta, "Nesprávné matematický výraz!");
	strcpy(sExtensions, "Rozšíření");
	strcpy(sExtra, "Extra");
	strcpy(sExtraComponents, "Extra komponenty");
	strcpy(sExtracomponentsattachedtoDemand, "Extra komponenty přidané k dílcům");
	strcpy(sFile, "Soubor");
	strcpy(sFileName, "Název souboru");
	strcpy(sFillWastes, "Vykresli odpad z šikmých čar");
	strcpy(sFindoptimalbarsheetsize, "Najdi optimální velikost pro trubky a plechy.");
	strcpy(sFindoptimalsizeofInventorypieces, "Najdi optimální velikost napříč kusy na skladě");
	strcpy(sFirstcutMultiplestages, "Směr prvního řezu - Více Průběh");
	strcpy(sFirstdirectionforcutishorizontal, "Směr prvního řezu je horizontální.");
	strcpy(sFirstdirectionforcutisvertical, "Směr prvního řezu je vertikální.");
	strcpy(sFollowthecontourofpieces, "Následuj obrys kusů");
	strcpy(sFont, "Font");
	strcpy(sFontsize, "Velikost písma");
	strcpy(sFullInfo, "Kompletní informace");
	strcpy(sDisposedWaste, "Likvidovaný odpad");
	strcpy(sGeneral, "Hlavní");
	strcpy(sGenerateCNC, "Generovat CNC");
	strcpy(sGrain, "Textura");
	strcpy(sGraindirection, "Směr let");
	strcpy(sGraphic, "Grafický");
	strcpy(sGreaterorequalto, "Větší nebo roven");
	strcpy(sGrid, "tabulky");
	strcpy(sGrinding, "broušení tloušťka");
	strcpy(sGrosimeTaieturaScalata, "Tloušťka řezu z obrázku se může lišit od skutečného jednoho, protože kusy nejsou zastoupeni v jejich skutečném měřítku. Tato skutečnost nemá vliv na výsledky.");
	strcpy(sGroupidenticallayouts, "Seskupit stejné listy");
	strcpy(sGroupIdenticalParts, "Seskupit stejné díly.");
	strcpy(sGroupingOfIdenticalPiecesIntoOneRow, "Seskupit stejné kusy do jednoho řádku.");
	strcpy(sGroupPartsAfterLoadingFromFile, "Seskupit dílce po načtení ze souboru");
	strcpy(sHeight, "Výška");
	strcpy(sHeighttolerance, "Tolerance pro výšku");
	strcpy(sHelp, "Nápověda");
	strcpy(sHistory, "Historie");
	strcpy(sHorizontal, "Horizontálně");
	strcpy(sHowtodisplayprintedgebands, "Jak se zobrazí hrany dílců?");
	strcpy(sIfyousetthebandforoneedgeallwillreceivethesamevalue, "Pokud nastavíte pásmo pro jednu hranu, budou všechny nastaveny na stejnou hodnotu.");
	strcpy(sIfyousetthegrindingforoneedgeallwillreceivethesamevalue, "Pokud nastavíte hodnotu broušení pro jednoho okraje, všechny hrany obdrží stejnou hodnotu.");
	strcpy(sIfyousetthetrimforoneedgeallwillreceivethesamevalue, "Pokud nastavíte ozdoby na jednom okraji, všechny hrany obdrží stejnou hodnotu.");
	strcpy(sImageBounds, "Hranice pro obrázek");
	strcpy(sImageSize, "Velikost obrázku.");
	strcpy(sImportData, "Import dat.");
	strcpy(sIncorrectPassword, "Nesprávné heslo");
	strcpy(sIndex, "Index");
	strcpy(sInformationaboutcustomer, "Informace o zákazníkovi");
	strcpy(sInputALanguageName, "Zadejte název do jazyka");
	strcpy(sInsert, "Vložit");
	strcpy(sInsertPiece, "Vložit kus");
	strcpy(sInterface, "Rozhraní");
	strcpy(sInterfaceSettings, "Nastavení rozhraní");
	strcpy(sInvalidHardware, "Nemohl jsem rozpoznat hardware. Prosím, kontaktujte nás na adrese contact@optimalprograms.com");
	strcpy(sInvalidNumber, "Neplatné číslo");
	strcpy(sInvalidOrderOfComputation, "Pořadí pro výpočet délky nelze zjistit. Tam jsou kruhové vztahy v definice výrobku!");
	strcpy(sInvalidRegistration, "Registrace je neplatná!");
	strcpy(sInvalidTime, "Čas vašeho systému je neplatná.");
	strcpy(sInventory, "Inventář");
	strcpy(sisafractionalvalue, "je desetinná hodnota.");
	strcpy(sIsArc, "Je oblouku");
	strcpy(sisarealvalue, "je reálná hodnota.");
	strcpy(sLabel, "Štítek");
	strcpy(sLabels, "Etikety");
	strcpy(sLanguage, "Jazyk");
	strcpy(sLatimeanumar0, "Šířka musí být větší než 0!");
	strcpy(sLatimeanumarreal, "Šířka musí být reálné číslo!");
	strcpy(sLayerName, "Název vrstvy");
	strcpy(sLeft, "Levý");
	strcpy(sLeftcoordinateofthedefect, "Levé souřadnice vady");
	strcpy(sLength, "Délka");
	strcpy(sLengthofthepiecestocut, "Ks velikost pro řezání");
	strcpy(sLengthofthepiecestocutfrom, "Rozměr pro řezání");
	strcpy(sLengthofusedbars, "Velikost použitých tyčí");
	strcpy(sLicenseAgreement, "Licenční smlouva");
	strcpy(sLinear, "Linear");
	strcpy(sLinethickness, "Tloušťka pera");
	strcpy(sLoadafileandappenddatatothecurrentDemand, "Načíst soubor a připojit data k aktuální poptávky.");
	strcpy(sLoadanexistingDemandfromafile, "Načíst existující poptávky ze souboru.");
	strcpy(sLoadAppend, "Načíst a Připojit");
	strcpy(sLoadEverything, "load vše");
	strcpy(sLoadInventory, "Vložte zboží");
	strcpy(sLoadInventoryandDemand, "Vložte zboží a poptávky");
	strcpy(sLoadResults, "Vložte výsledků");
	strcpy(sLocked, "zamčený");
	strcpy(sLogo, "logo");
	strcpy(sLong, "Long");
	strcpy(sLongerexecutiontime, "Delší doba realizace");
	strcpy(sLungime, "Šířka");
	strcpy(sLungimeanumar0, "Délka musí být větší než 0!");
	strcpy(sLungimeanumarreal, "Délka musí být reálné číslo!");
	strcpy(sLungimeaTotalaFolosita, "Celková využívaná délka");
	strcpy(sMagnification, "Zvětšení");
	strcpy(sMagnify, "Zvětšit");
	strcpy(sMargins, "Okraje");
	strcpy(sMarginsForPaper, "Okraje pro papír");
	strcpy(sMarginsOfTheLabel, "Okraje štítku");
	strcpy(sMaterial, "Materiál");
	strcpy(sMaterialName, "Název materiálu");
	strcpy(sMaterials, "Materiály");
	strcpy(sMaterialstypes, "Materiály typy");
	strcpy(sMax, "Max");
	strcpy(sMaximalArea, "Maximální plocha");
	strcpy(sMaximalCutLength, "Maximální délka řezu");
	strcpy(sMaxlength, "Maximální délka");
	strcpy(sMaxPiecesperBar, "Max Počet kusů Bar");
	strcpy(sMaxwidth, "Maximální šířka.");
	strcpy(sMeasurementUnit, "Jednotka měření");
	strcpy(sMin, "min");
	strcpy(sMinimalBreakSize, "Minimální velikost prasknutí");
	strcpy(sMinimalUsefulSize, "Minimální užitečná velikost");
	strcpy(sMinimalwastesizetoInventory, "Minimální velikost odpadu zpět do skladu");
	strcpy(s_What_to_minimize, "Co minimalizovat?");
	strcpy(sMinlength, "Minimální délka");
	strcpy(sMinwidth, "Minimální šířka");
	strcpy(sMirror, "Zrcadlo");
	strcpy(sMirroring, "Zrcadlení");
	strcpy(sMiscellaneous, "Smíšený");
	strcpy(sModify, "Upravit");
	strcpy(sModifytheselectedpiece, "Upravit vybraný kus");
	strcpy(sMovePiece, "Přesunout kousek.");
	strcpy(sMultiplestages, "Více Průběh");
	strcpy(sName, "Jméno");
	strcpy(sNameofedgeband, "Název okrajových pásem");
	strcpy(sNewDEMANDUnsaveddatawillbelost, "Nové díly? Neuložená data budou ztracena!");
	strcpy(sNewLanguage, "Nový jazyk");
	strcpy(sNewMaterial, "Nový materiál");
	strcpy(sNewPasswordincorectlyintroduced, "Nové heslo nesprávně zaveden!");
	strcpy(sNewProduct, "Nový produkt");
	strcpy(sNewversion, "Nová verze");
	strcpy(sNo, "Ne");
	strcpy(sNumarBucati, "Počet kusů");
	strcpy(sNumberOfCopies, "Počet kopií");
	strcpy(sNumberofstages, "Počet stupňů");
	strcpy(sNusuficienteplacidepozit, "Ne všechny kusy byly optimalizovány. Možné příčiny: není dostatek kusů na skladě, dílce nejsou využity v optimalizaci");
	strcpy(sOfficeNotInstaled, "Microsoft Office není nainstalován na vašem počítači nebo verzi špatným je nainstalován!");
	strcpy(sOldpassworddoesnotmatch, "Staré heslo nesouhlasí!");
	strcpy(sOnlinehelp, "Online nápověda");
	strcpy(sOnlypiecesofthesameheightinthelaststage, "Kusy ve stejné výšce v posledním stadiu.");
	strcpy(sOpen, "Otevřít");
	strcpy(sOptimization, "Optimalizace");
	strcpy(sOptimizationDone, "Optimalizace provedeny! Můžete vytisknout nebo uložit získané diagramy. Stiskněte tlačítko Přijmout, pokud jste spokojeni s aktuálním řešením. V opačném případě stiskněte Začít znovu.");
	strcpy(sOptimizationType, "Typ optimalizace");
	strcpy(sOptions, "Možnosti");
	strcpy(sOptionsrelatedtotheinterface, "Volby týkající se rozhraní");
	strcpy(sor, "nebo");
	strcpy(sOthercomponents, "Ostatní komponenty");
	strcpy(sOthers, "Ostatní");
	strcpy(sOtherstatistics, "Další statistiky");
	strcpy(sOverrideExcelCSVfiles, "Přepsat Excel / CSV soubory");
	strcpy(sParameter, "Parametr");
	strcpy(sParts, "DÍLY");
	strcpy(sPattern, "Vzor");
	strcpy(sPatternforwaste, "Vzor pro odpad");
	strcpy(sPerimeter, "Obvod");
	strcpy(sPermitedRotationAngle, "Povolený úhel rotace.");
	strcpy(sPhone, "Telefon");
	strcpy(sPicture, "Obrázek");
	strcpy(sPiece, "Kus");
	strcpy(sPieceindex, "Index kusu");
	strcpy(sPieces, "Ks");
	strcpy(sPiecesize, "Kus má velikost");
	strcpy(sPiecesizelabeledgebandwillbeprinted, "Velikost kusu, štítek, hrany budou vytištěny.");
	strcpy(sPierdere, "Odpad");
	strcpy(sPixels, "pixelů");
	strcpy(sPlacilefolositeDepozit, "Využité kusy z inventáře.");
	strcpy(sPlease_contact_us_at_contact_nestingtechnologies_com, "Prosím, kontaktujte nás na contact@nesting-technologies.com");
	strcpy(sPlease_contact_us_at_contact_optimalprograms_com, "Prosím, kontaktujte nás na contact@optimalprograms.com");
	strcpy(sPleaseenteralldataeitherasfractionalorrealDonotmixthem, "Zadejte prosím všechny údaje buď jako nepatrné, nebo skutečné Nemíchejte je!");
	strcpy(sPleaseEnterSomeTypesOfMaterials, "Neexistuje žádný typ materiálu definovaného. Můžete definovat z materiálů menu.");
	strcpy(sPleasesendtheNameandtheCodetotheaddresscontactoptimalprogramscominordertoobtaintheRegistrationKey, "Za účelem získání registračního klíče pošlete prosím název a kód: contact@optimalprograms.com~~HEAD=dobj.");
	strcpy(sPolygon, "Polygon");
	strcpy(sPolygonsCircles, "Polygony, kruhy");
	strcpy(sPrecision, "Přesnost");
	strcpy(sPretulnumar0, "Cena musí být větší než 0!");
	strcpy(sPretulnumarreal, "Cena musí být reálné číslo!");
	strcpy(sPreview, "Náhled");
	strcpy(sPrice, "Cena");
	strcpy(sPriceMustBeGreaterThanZero, "Cena musí být větší než nula");
	strcpy(sPriceofbars, "Cena tubek / tyčí");
	strcpy(sPriceperbar, "Cena za trubku / tyč");
	strcpy(sPricepersheet, "Cena za list");
	strcpy(sPricepersquareunitofmaterial, "Cena za čtvereční jednotku materiálu.");
	strcpy(sPriceperunit, "Cena za jednotku");
	strcpy(sPrint, "Vytisknout");
	strcpy(sPrintdiagramsastables, "Tisk diagramy ve formě tabulek.");
	strcpy(sPrinter, "Tiskárna");
	strcpy(sPrinterBounds, "Okraje pro tiskárnu");
	strcpy(sPrinting, "Tisk");
	strcpy(sPrintonlyutilizedarea, "Tisk pouze vybrané oblasti");
	strcpy(sPrintthecontentsoftheDemand, "Vytisknout obsah zakázky.");
	strcpy(sPrintthecontentsoftheInventory, "Vytisknout obsah přířezu.");
	strcpy(sPrintthecurrentsolution, "Tisk aktuálního řešení.");
	strcpy(sPriority, "Priorita");
	strcpy(sPrioritytocutapieceZero0isthehighestpriority, "Priorita snížit kus. Nula (0) je nejvyšší prioritou.");
	strcpy(sProcentul0100, "Tyto procent musí být větší než 0 a menší nebo roven 100!");
	strcpy(sProcentulnumarreal, "Tyto procent musí být reálné číslo!");
	strcpy(sProductdefinition, "Definice výrobku");
	strcpy(sProductExists, "Produkt již existuje. Zvolte jiný název.");
	strcpy(sProductName, "Název výrobku");
	strcpy(sProducts, "Produkt");
	strcpy(sProducts, "Produkty");
	strcpy(sProject, "Projekt");
	strcpy(sProperties, "Vlastnosti");
	strcpy(sProperty, "Vlastnost");
	strcpy(sQuantity, "Množství");
	strcpy(sQuantitynumberofsheetsofthistype, "Počet listů tohoto typu");
	strcpy(sRadius, "Poloměr");
	strcpy(sRectangular, "Obdélníkový");
	strcpy(sRedefinetypesofedgeband, "Předefinovat typy hran");
	strcpy(sRedefinetypesofmaterial, "Předefinovat typů materiálů");
	strcpy(sRegistration, "Registrace");
	strcpy(sRegistrationKeyfromOptimalPrograms, "Registrační klíč");
	strcpy(sRegistrationSuccessful, "Registrace proběhla úspěšně!");
	strcpy(sRemoveallpiecesinInventory, "Odstraňte všechny kusy v inventáři.");
	strcpy(sRemoveCut, "Odstranit řez");
	strcpy(sRemovetheselectedpiece, "Odstranit vybraný kus");
	strcpy(sReports, "Zprávy");
	strcpy(sRequestedMaterial, "Požadovaný Materiál");
	strcpy(sRestore, "Obnovit");
	strcpy(sResults, "Výsledky");
	strcpy(sReusedwaste, "Využitých odpadů");
	strcpy(sRight, "Pravý");
	strcpy(sRightcoordinateofthedefect, "Souřadnice defektu z prava");
	strcpy(sRotation, "Rotace");
	strcpy(sRotationAngle, "Úhel natočení");
	strcpy(sRotationStep, "Rotace krok");
	strcpy(sRoundAllFractionsTo, "Tyto nepatrné hodnoty musí být zaokrouhleny na");
	strcpy(sRow, "řádek");
	strcpy(sRows, "Řádky");
	strcpy(sRun, "Nejnovější řešení");
	strcpy(sRunningtime, "Doba chodu");
	strcpy(sSameforall, "Stejné pro všechny");
	strcpy(sSave, "Uložit");
	strcpy(sSaveAllImages, "Uložit všechny obrázky");
	strcpy(sSaveAs, "Uložit jako");
	strcpy(sSaveChanges, "Zakázka byla změněna. Chcete ji uložit?");
	strcpy(sSaveCurrentImage, "Uložit aktuální obrázek");
	strcpy(sSavedataparameters, "Uložit data a parametry");
	strcpy(sSaveEverything, "Uložit všechno");
	strcpy(sSaveInventory, "Uložit Inventory");
	strcpy(sSaveInventoryandDemand, "Uložit skladové zásoby a zakázku");
	strcpy(sSaveResults, "Uložit výsledky");
	strcpy(sSaveStatisticsinafile, "Uložit statistiky do souboru");
	strcpy(sSavethecurrentimage, "Uložit aktuální obrázek");
	strcpy(sSavethecurrentimageorstatistic, "Uložit aktuální obrázek nebo statistiky");
	strcpy(sSavetheDEMANDinafile, "Uložit do souboru");
	strcpy(sSavetheDemandinafilewithadifferentname, "Uložte zakázky do souboru s jiným názvem.");
	strcpy(sSavetheREPOSITORYinafile, "Uložit sklad do souboru");
	strcpy(sSerialNumber, "Registrační klíč");
	strcpy(sService, "služba");
	strcpy(sSetDefaultValues, "To obnoví všechny parametry na jejich výchozí hodnoty. Všechna vaše nastavení budou ztracena. Jste si jisti, že to chcete udělat?");
	strcpy(sSetedgeband, "Nastavit hrany");
	strcpy(sSetedgetrim, "Nastavte řezání za vady hran");
	strcpy(sSetthesameedgebandforalledges, "Nastavte stejnou hranu pro všechny hrany");
	strcpy(sSetthesamegrindingforalledges, "Nastavte stejné broušení pro všechny hrany.");
	strcpy(sSetthesametrimforalledges, "Nastavte stejné řezání za vady pro všechny hrany");
	strcpy(sSettings, "Nastavení");
	strcpy(sShape, "Tvar");
	strcpy(sSheet, "List");
	strcpy(sSheetsBarstypes, "Listy_tyče typy");
	strcpy(sSheetSize, "Velikost listu");
	strcpy(sSheetsperPage, "Listů na stránce");
	strcpy(sShort, "Krátký");
	strcpy(sShorterexecutiontime, "Krátká doba chodu");
	strcpy(sShowallsimpleproducts, "Zobrazit všechny jednoduché produkty");
	strcpy(sShowcustomername, "Zobrazit jméno zákazníka");
	strcpy(sShowCustomTextOnEachPiece, "Zobrazit vlastního textu na každém kusu");
	strcpy(sShowdiagramasatable, "Zobrazit diagram jako stůl.");
	strcpy(sShowedgeband, "Zobrazit okraje hran");
	strcpy(sShowedgebandssettinginanewwindow, "Zobrazit nastavení hran v novém okně.");
	strcpy(sShowgrindingsettingsinanewwindow, "seriály broušení nastavení v novém okně.");
	strcpy(sShowHorizontalLabelsAlways, "Zobraz štítky vždy horizontálně");
	strcpy(sShowRemovethesizeofthepiecesinthecurrentsolution, "Zobrazit / Odebrat velikosti kusů v aktuálním řešení.");
	strcpy(sShowRemovethesizeofthewastesinthecurrentsolution, "Zobrazit / Odebrat o velikosti odpadů v aktuálním řešení.");
	strcpy(sShowtotalcutlength, "Zobrazit celkovou řeznou délku");
	strcpy(sShowtrimedgesettingsinanewwindow, "Zobrazit nastavení vad v novém okně.");
	strcpy(sSimpleMaterialExists, "Název materiálu je již definován v seznamu materiálů. Prosím, dát mu nové jméno.");
	strcpy(sSinglePieceStrips, "Stripes jednoho kusu.");
	strcpy(sSizes, "Velikosti");
	strcpy(sSmallerorequalto, "Menší nebo rovno");
	strcpy(sSort, "Seřadit");
	strcpy(sSortAscendingByArea, "Seřadit vzestupně podle oblasti");
	strcpy(sSortDescendingByArea, "Seřadit sestupně podle plochy");
	strcpy(sSpecifyhowdifferentthepiecesinthelaststagecanbeValue0meansnodifference, "Určete, jak různé mohou být kusy v poslední fázi. Hodnota 0 znamená žádný rozdíl., ");
	strcpy(sSpecifyifpiecesinthelaststagecanbedifferentornotdepeultimaetapapotfidiferitesaunucadimensiune, "Určete, zda kusy v poslední fázi může být odlišná, nebo ne");
	strcpy(sSpecifyifthepiececanberotatedornotIfnotitwillbecutinthesamewayasitwasintroducedinDemandLengthofthepieceparalleltothelengthofthesheet, "Určení případě, že kus může být otočen nebo ne. Jestliže ne, bude nařezán stejným způsobem, jako to bylo zavedeno v Demand (délka kusu souběžně s délkou listu), ");
	strcpy(sSpecifyinhowmanystageswemakethecutsDuringastageallcutshavethesamedirection, "Určete, v kolika fázích děláme řezy.");
	strcpy(sStartthesearchprocess, "Spustit vyhledávání");
	strcpy(sStatistics, "Statistika");
	strcpy(sStatisticsE, "Zprávy Extra");
	strcpy(sStatisticsforeachtypeofmaterial, "Statistika pro každý typ materiálu");
	strcpy(sStep, "Krok");
	strcpy(sStergeDepozit, "Chcete-li odstranit zásob?");
	strcpy(sStergeMaterial, "Odstranit materiál?");
	strcpy(sStergePiesele, "Chcete-li odstranit skladbu?");
	strcpy(sStergePiesa, "Chcete-li odstranit skladbu?");
	strcpy(sStopthesearchprocess, "Zastavte proces hledání");
	strcpy(sStrongoptimization, "Silná optimalizace");
	strcpy(sSubtractthebandthicknessfrompiecesize, "Zmenšit velikosti kusů o tloušťky hran.");
	strcpy(sSummary, "shrnutí");
	strcpy(sSuprafataTotalaFolosita, "Celkem využitá plocha");
	strcpy(sSuprafatautilizata, "Využití");
	strcpy(sSwitchbetweenfiberandrotationoption, "Přepínání mezi vlákna a možnost střídání.");
	strcpy(sTechnical, "Technický");
	strcpy(sTechnicalsettings, "Technické nastavení");
	strcpy(sTemporaryPanelHint, "Dočasné panel pro pohyblivé části mezi listy.");
	strcpy(sText, "Text");
	strcpy(sThe_application_has_expired, "Program vypršel.");
	strcpy(sThe_application_is_not_registered, "Software není registrován.");
	strcpy(sThe_application_was_first_started_on, "Software byl poprvé spuštěn.");
	strcpy(sThecutsareperformedfromasidetotheothersideofthematerial, "Inkaso se provádí z boku na druhé straně materiálu.");
	strcpy(sThecuttingmachinecanfollowtheshapeofthematerial, "Řezačka může sledovat tvar kusu.");
	strcpy(sTheedgesofsheetsthatmustbetrimedduefaults, "Okraje listů, které musí být ořezané z důvodu poruch");
	strcpy(sTheLargestSize, "Největší velikost.");
	strcpy(sThenameofthecustomerforwhichyoucutthepiece, "Jméno zákazníka, pro které části jste sekat kus.");
	strcpy(sThenameofyourcustomer, "Jméno zákazníka");
	strcpy(sThepiececanberotated, "Kus lze otáčet");
	strcpy(sTheprogramtriestoavoidwasteswhichhavebothsizeslessthanthisvalue, "Program se snaží, aby se zabránilo odpady, které mají obě velikosti menší než tato hodnota");
	strcpy(sThereAreNoProducts, "Zatím nejsou definovány žádné produkty");
	strcpy(sThestockofmaterialhasbeenpreviouslyloadedfromanExcelorCSVformatPleaseloaditagain, "Zásoby materiálu již dříve načten z aplikace Excel nebo CSV formátu. Prosím, vložte ji znovu, pokud chcete pracovat na něm.");
	strcpy(sThetotallengthofcutting, "Celková délka řezu");
	strcpy(sThewidthofthecuttingsawForglasscuttingoptimizationitcanbe0Forwooditshouldbegreaterthan0, "Tloušťka pily. Pro řezání skla může být 0. Na dřevo by mělo být větší než 0,.");
	strcpy(sThewidthofthecuttingsawforlinearpieces, "Tloušťka pily pro lineární kusy.");
	strcpy(sThickness, "Tloušťka");
	strcpy(sThischaracterisusedforfillingthewasterectanglesIfyoudonotwantfilledwastejustremovethischaracter, "Tento symbol se používá k vyplnění odpadních obdélníky. Pokud nechcete, aby vyplněný odpad jen odstranit to.");
	strcpy(sThisindexhasvaluebetween1andthenumberofpieces, "Tento index má hodnotu mezi 1 a počet kusů.");
	strcpy(sThisOptionWillOverrideTheInventoryFileIfLoadedFromExcelOrCsvFiles, "Tato volba přepíše zásob soubor, pokud je načten z aplikace Excel nebo CSV souborů.");
	strcpy(sThisProgramisLicensedTo, "Tento program je licencován na");
	strcpy(sThisvaluewillbeaddedtotheedgebandingmaterialoneachside, "Tato hodnota se přidá k olepování materiálu na každé straně");
	strcpy(sTipNevid, "Typ materiálu nemůže být prázdný.");
	strcpy(sTitle, "Název");
	strcpy(sTools, "Nástroje");
	strcpy(sTop, "Horní");
	strcpy(sTopcoordinateofthedefect, "Horní Souřadnice vady.");
	strcpy(sTotalGarbageWaste, "Všechen zlikvidovaný odpad");
	strcpy(sTotalInventoryWaste, "Všechen odpad");
	strcpy(sTotalRecycledWaste, "Všechen recyklovaný odpad");
	strcpy(sTotalusedarea, "Celková využitá plocha");
	strcpy(sTotalusedlength, "Celková využitá délka");
	strcpy(sTrigonometric, "Trigonometrické");
	strcpy(sTrim, "Oříznout");
	strcpy(sTrimalledgesatthebeginning, "Ořízněte všechny hrany na začátku");
	strcpy(sTrimEdge, "Ořízněte okraj");
	strcpy(sTwoPanels, "2 okna");
	strcpy(sType, "typ");
	strcpy(sTypeofmaterialfromwhichtocut, "Typ materiálu, ze kterého řezat");
	strcpy(sTypesAreNotMatched, "Optimalizace se neprovádí! Kusy budou řezat z fólií z inventáře, které mají stejný typ materiálu. V současné době je ve skladu, není tento materiál! Změnit některé materiály z příslušného sloupce!");
	strcpy(sUndo, "Vrátit");
	strcpy(sUndoAccept, "Vrátit Přijmout");
	strcpy(sUnits, "jednotky");
	strcpy(sUnregisteredVersion, "Neregistrovaný");
	strcpy(sUpdates, "Aktualizace");
	strcpy(sUsefulforwoodfurniture, "Vhodné pro dřevěný nábytek");
	strcpy(sUseit, "Použijte jej");
	strcpy(sUsePieceinOptimization, "Použijte kus v optimalizaci");
	strcpy(sUserName, "Uživatelské jméno");
	strcpy(sUtilizationandWastes, "Využití a Odpady");
	strcpy(sUtilizedArea, "Oblast využívaných částí");
	strcpy(sUtilizedBars, "Využil tyče");
	strcpy(sUtilizeddemandcount, "Počet použitých kusů.");
	strcpy(sUtilizedParts, "Využité díly");
	strcpy(sUtilizedPieces, "Využité kusy");
	strcpy(sUtilizedSheets, "Využité listy");
	strcpy(sValue, "Hodnota");
	strcpy(sValueGreaterEqualToZero, "Hodnota musí být větší nebo rovna nule");
	strcpy(sValueGreaterThanZero, "Hodnota musí být větší než nula");
	strcpy(sValueIntegerNumber, "Hodnota musí být celé číslo!");
	strcpy(sValueRealNumber, "Hodnota musí být reálné číslo. Možná jste použili, místo. nebo obráceně. Opravte je prosím!");
	strcpy(s_The_number_is_too_big_or_it_has_too_many_digits_after_decimal_separator, "Číslo je příliš velké nebo má příliš mnoho číslic za desetinným oddělovačem!");
	strcpy(s_The_number_is_too_big, "Číslo je příliš velké!");
	strcpy(sVertical, "Vertikálně");
	strcpy(sWaste, "Odpad");
	strcpy(sWastes, "Odpad");
	strcpy(sWasteAddedToWarehouse, "Odpad přidán do skladu");
	strcpy(sWastelimits, "limity pro odpad");
	strcpy(sWasteType, "Druh odpadu");
	strcpy(sWeakoptimization, "Nejslabší optimalizace");
	strcpy(sWhattoprint, "Co bych měl vytisknout");
	strcpy(s_What_to_print_or_save_to_file, "Co vytisknout nebo uložit do souboru");
	strcpy(sWhattoprintoneachpiece, "Co tisknout na každý kus");
	strcpy(sWhattoshowoneachpiece, "Co pro zobrazení na každém kusu?");
	strcpy(sWidth, "Šířka");
	strcpy(sWood, "dřevo");
	strcpy(sWorkingDirectory, "Pracovní adresář");
	strcpy(sWrongKey, "Špatný Registrační klíč!");
	strcpy(sYes, "Ano");
	strcpy(sYoucannotchooseblackblueorredcolors, "You cannot choose black, blue or red colors.");
	strcpy(sYouCannotMixFractionalDataWithDecimalOnes, "Nelze kombinovat nepatrné hodnoty se skutečnými hodnotami!");
	strcpy(sYourcompany, "Vaše společnost");
	strcpy(sZip, "PSČ");
	strcpy(s_Set_the_origin_and_the_direction_of_the_axes, "Nastavte počátek a směr os souřadnic.");

}
